### ISSUE TITLE
Document SpinUp vs. ECS decision process

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#100]
**ACCEPTANCE**
- [ ] We have identified the high-level functional and non-functional requirements for our container deployment platform
- [ ] We have identified a timeline for completing evaluations of ECS and SpinUp in relation to the requirements
- [ ] We have identified a decision making process and date

Please use the following document to capture requirements
https://docs.google.com/document/d/1BitesAOAcdxJlawDCU_wPzhzCsX9SXv9BqoOZ-xIOZQ/edit#heading=h.oomcj5oted9g

**Comment by dl-maura** [comment]
We are moving forward with ECS and looking at SpinUp sometime in the future.
