### ISSUE TITLE
IIIF request for non-existent OID returns HTTP 500

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1002]
**Story**

Requests for a non-existent OID returns an HTTP 500 Internal Server Error from nginx.  Blacklight's permissions check is raising an exception when querying Solr for the auth check and not finding the OID.

**Acceptance**

- [x] The permission check in Blacklight returns a 401 status code  if the OID does not exist

**Comment by martinlovell** [comment]
The issue may be with nginx auth module not understanding the 404 response.

http://nginx.org/en/docs/http/ngx_http_auth_request_module.html
(notice: Any other response code returned by the subrequest is considered an error.)

Updating CheckAuthorization to return a 401 or 403 when the solr document isn't found causes nginx to pass through the 401/403.  (No longer getting 500 error.)  But, it doesn't seem possible to pass through a 404.  

(If nginx gets a 404, it thinks the auth system is not found...not that the thing being authorized is not found.)

**Comment by mikeapp** [comment]
`We can return 200 from the auth check when the child/parent is not found, and have the cantaloupe return the 404.`

I'm concerned that might open up a vulnerability if secure content is left in S3 and the Solr record is deleted. 

I'd propose close won't fix.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/491

**Comment by martinlovell** [comment]
Test with: 
https://collections-uat.library.yale.edu/iiif/2/1073833190/full/!200,200/0/default.jpg
