### ISSUE TITLE
[Check] Make smoke tests run against staging and prod in jenkins

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#1005]
The jenkins jobs define an association between cluster names and hostnames for most of the environments, but not for staging and production; this results in the smoke tests running against non-existent hostnames in jenkins for staging and prod deploys.

**Acceptance**
- [ ] Document what smoke tests are being run
- [ ] Make a decision on which way to go

**Comment by DraxIndustries79** [comment]
We'll have to figure out what's actually occurring here before we decide on taking action

**Comment by mlooney** [comment]
prod & stage are definitely running the tests, but there are 2 of 12 that are commented out in the suite (they would be commented out in all environments).

**Comment by mlooney** [comment]
```
  1) The cluster at https://yul-dc:nocrawl@collections-staging.library.yale.edu The blacklight site at https://yul-dc:nocrawl@collections-staging.library.yale.edu has a yale-only item that does not show Universal Viewer
     # Temporarily skipped with xit
     # ./smoke_spec/deploy_spec.rb:80

  2) The cluster at https://yul-dc:nocrawl@collections-staging.library.yale.edu The management index page at https://collections-staging.library.yale.edu/management has version numbers in the table
     # Temporarily skipped with xit
     # ./smoke_spec/deploy_spec.rb:135

```
