### ISSUE TITLE
Run intensive workers on their own Fargate container instance

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1006]
**ISSUE**
We don't want memory intensive PDF jobs to compete with other background processes.

**ACCEPTANCE**
- [x] Intensive workers run on their own Fargate instance(s)
- [x] non-intensive workers run on a separate EC2 instance(s)
- [x] deploy to all environments
  - [x] uat
  - [x] staging
  - [x] prod

**Comment by martinlovell** [comment]
The PDF Jobs don't need the mounts as far as I know, so they may not necessarily need EC2 instances.    PDF generation downloads PTIFFs from S3.
Not sure if that's a good idea to run them with Fargate, but it's an option.

**Comment by mlooney** [comment]
Since we don't require the fs, as noted above, converting to fargate

**Comment by martinlovell** [comment]
Updated UAT by deploying intensive workers.  (Explicitly used same version that was already installed for uat management.)

![Screen Shot 2021-02-01 at 4.02.38 PM.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/139f9922-2fde-49cd-aa64-400c0099cf9f)

**Comment by mikeapp** [comment]
Done
