### ISSUE TITLE
Remove URI from Display

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1011]
We want to remove the metadata uri from display since it won't mean anything to users

**Comment by dl-maura** [comment]
On local:
![Screen Shot 2021-01-22 at 4.31.28 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/0ac8419e-da13-47e6-b6b2-150da11a7d85)

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3c1836e9-729f-45cd-bf57-a51f6d31c877)
