### ISSUE TITLE
Correct cataloging for 5 items with improper dates

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1015]
**ISSUE** 
After completing the reindex of works on production with the new Metadata Cloud mappings, there appear to be only 4 items remaining with invalid dates.

Reference Search: https://collections.library.yale.edu/catalog?q=&search_field=all_fields&sort=year_isim+asc%2C+id+desc&range%5Byear_isim%5D%5Bbegin%5D=2240&range%5Byear_isim%5D%5Bend%5D=5686&range%5Byear_isim%5D%5Bbegin%5D=2022&range%5Byear_isim%5D%5Bend%5D=9999&commit=Apply

OIDS:
* [11378440](https://collections.library.yale.edu/catalog/11378440) A New Ballad, to the tune of, Good People give ear, while a story I tell .. or, Packington's Pound.   
[link to 11378440 in management](https://collections.library.yale.edu/management/parent_objects/11378440) see `intEndYear` from MC  
* [16671737](https://collections.library.yale.edu/catalog/16671737) Ormesby, in Lincolnshire: William Massingberd, 1719-1802
* [2038998](https://collections.library.yale.edu/catalog/2038998) Pringle, Sir John, Correspondence (C 2292-2298)
* [17111154](https://collections.library.yale.edu/catalog/17111154) Kipling, Rudyard

**ACCEPTANCE**
- [x] Identify the source issue and correct for each of the four items above
- [x] Test in staging
- [x] Update the metadata for each of the five items in the production instance of the DL
  - [x] 11378440
  - [x] 16671737
  - [x] 2038998
  - [x] 17111154
  - [x] 16584381

**Comment by martinlovell** [comment]
Updated Metadata for the following oids on staging:
2038998
16584381
11378440
16671737
17111154

Before: 
![Screen Shot 2021-01-28 at 7.47.35 AM.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/12e06ef4-179b-4622-86a2-107ad8c3b14e)

After:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/ef014b7e-c7a9-4616-adfd-f0178912cdc7)

**Comment by dl-maura** [comment]
I haven't done this in prod because of the solr issues and I wasn't sure if that would mess anything up
