### ISSUE TITLE
Data-table requests produce timeouts in production

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1016]
**ISSUE**
When I try to search for a parent OID in the production instance of the management application, I'm getting Ajax datable errors that seem to be related to timeout issues.

**STEPS TO REPRODUCE**
The issue appears to occur any time I try to use the search for any parent OID in the Parent Objects tab (in production).

**ACCEPTANCE**
- [ ] I can successfully use the data-table search functionality in production

**DETAILS**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/42680add-9c0e-4588-b5dd-2f2899c1298e)

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/7f0b8caa-8005-4eb7-bc1a-770664b0feb9)

**Comment by maxkadel** [comment]
Were we seeing this at times other than during the last ingest? Postgres was pegged at 100% cpu usage, I think because of some stuck background jobs, so this might be more related to ingest issues than the data tables.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/dc670b66-9ec4-4df8-a6a6-d43f8a86e59c) Looks like the changes that cool down our ingest database load cleared up the errors.  We may still want the exact-match rather than substring search behavior for this feature.

**Comment by alishaevn** [comment]
I'm also not having an issue with searching on prod this morning. It took 45-60 seconds to search the 112,216 records, but it's working.

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/5500f413-13f3-4457-9cae-e9d03a336f1d)

**Comment by alishaevn** [comment]
@mark-dce can you try this again?

**Comment by mark-dce** [comment]
It's taking about 45 seconds, but isn't timing out... on the first try.  I'm still able to trigger the timeouts on subsequent request, and I feel like we still need to do something about it.

45 seconds is a very long time to wait without any kind of feedback - i.e. I don't see a spinner or progress bar during that time, so it looks like the system isn't doing anything.  I think I see part of what's happening - If I change what I type of hit return in the box again because it doesn't look like anything is happening, the browser just keeps sending new requests while the old ones are still active 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3064318/106311327-d27c5480-6219-11eb-9f4d-c2493e7b80ed.png">

**Comment by mark-dce** [comment]
Steps to reproduce:

1. Visit https://collections.library.yale.edu/management/parent_objects
2. Enter a specific OID in the search box - e.g. 2003501
3. Impatiently delete what you pasted (use backspace or highlight and delete)
4. Re-paste your OID

This seems to trigger a new request for `parent_objest.json` for each keystroke or text entry, and now I have a stack of requests lined up that all time out after one another.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3064318/106312531-a8c42d00-621b-11eb-84fa-c7abb21046eb.png">

**Comment by alishaevn** [comment]
so this appears to be more about user error? 

two thoughts:
- maybe we could move the "processing" alert that shows up about halfway down screen, up to the top?
- or put messaging around the space bar that informs the user to wait until their current query has completed before beginning a new one?

**Comment by mark-dce** [comment]
I think we still have a long-term performance issue - the collections are only going to grow over time since Beinecke is only a fraction of Yale's total digital holdings.  

I like the idea of improving the UI, but I'd also still like to explore making the searching more performant.  Is it possible to constrain the search to speficif fields - i.e. could we have an OID search box, a visibility drop down, a BibID search box, and a ASPace search box?  Then we would only need to wildcard/partial search when someone typed something in the ASpace box and everything else could be exact match.

**Comment by alishaevn** [comment]
Also, while the ui plays a role, I agree with mark that that's also a performance issue.
- when I copy paste a number into the search bar, it works successfully (first video below)
- when I type the full number out, I get the data tables warning (second video) 
- not sure if there's a way to make the datatable "wait" to search until a certain amount of time has elapsed

https://images.zenhubusercontent.com/242185115/f5fd1179-1755-498a-9695-6ba5926c231a/success.mp4

https://images.zenhubusercontent.com/242185115/5584e0c1-a406-4076-bb32-19236fdb179d/fail.mp4

**Comment by mark-dce** [comment]
From the network view in my browser debugger, it looks like the UI is sending off one request for each keystroke.  Is there any way we can override the behavior to having some kind of submit button instead of issuing a request on each keystroke?

**Comment by orangewolf** [comment]
https://datatables.net/reference/option/searchDelay is a good jumping off point in the docs.

Basically the answer is yes - we could up the delay (the simplest thing) or catch the event unless a return is detected (we'd need to add some UI to explain this). 

I also think we should fix the search side and we can go over what that looks like code wise when we meet today.

**Comment by mark-dce** [comment]
We're going to replace this ticket with #1043 and #1044 which focus on improving the search behavior by adjusting the datable UI.
