### ISSUE TITLE
Set up Test and UAT mounts for Access Master pair trees on Storage@Yale

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1019]
**STORY**
As an operations manager, I would like separate writable pair tree locations on Storage@Yale for test and uat purposes, so that developers adding features do doing maintenance on Goobi import code can't inadvertently write to or overwrite data in the production pair tree.

**ACCEPTANCE**
Set up access master mounts like the current one for production shared as follows

Mount the access master pair trees for each environment to /data/00-09 sub directories

- [ ] `test` access master mount point - to support
     - [ ] infra DL environment
     - [ ] test DL environment
- [ ] `uat` access master mount point - to support
    - [ ] uat DL environment
    - [ ] demo DL environment
- [x] `prod` access master mount point - to support
    - [x] staging DL environment 
    - [x] production DL environment

**Comment by bobrice** [comment]
These mounts were requested in Service Now # INC1931508

**Comment by dl-maura** [comment]
The shares are ready

**Comment by ra359** [comment]
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_005/yul_dc_uat1-CC1702-LIBITS 
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_006/yul_dc_tst1-CC1702-LIBITS

**Comment by ra359** [comment]
Adding the followiing to `bin/create-continst.sh`:

`
  # NFS mounts for Access Master pair trees
  #   For staging/prod:
  #     wcsfs00.its.yale.internal:/yul_dc_nfs_store_0 mounted to /data/00
  #     wcsfs00.its.yale.internal:/yul_dc_nfs_store_1 mounted to /data/01
  #     ..
  #     wcsfs00.its.yale.internal:/yul_dc_nfs_store_10 mounted to /data/10
  #
  #   For test/infra:
  #     wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_006/yul_dc_tst1-CC1702-LIBITS to /data
  #
  #   For uat/demo:
  #     wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_005/yul_dc_uat1-CC1702-LIBITS to /data

  if [ $CLUSTER_NAME="yul-dc-prod" ] || [ $CLUSTER_NAME="yul-dc-staging" ]
  then
    for i in {0..10}
    do
      t=\`printf '%02d' \$i\`
      mkdir -p /data/\$t
      mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 wcsfs00.its.yale.internal:/yul_dc_nfs_store_\$i /data/\$t
    done" | base64 -w0)
  elif [ $CLUSTER_NAME="yul-dc-test" ] || [ $CLUSTER_NAME="yul-dc-infra" ]
  then
      mkdir -p /data
      mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_006/yul_dc_tst1-CC1702-LIBITS /data
  elif [ $CLUSTER_NAME="yul-dc-uat" ] || [ $CLUSTER_NAME="yul-dc-demo" ]
  then
      mkdir -p /data
      mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_005/yul_dc_uat1-CC1702-LIBITS /data
  fi
`

**Comment by ra359** [comment]
Debugging `bin/create-continst.sh` as it's throwing an error...

**Comment by ra359** [comment]
deployed to UAT/TEST yesterday

**Comment by ra359** [comment]
re-deployed to UAT, seems ok now.
Had to tweak `bin/create-continst.sh`

**Comment by ra359** [comment]
both UAT and TEST should be square now:

wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU/jss_export  250G  105G  146G  42% /brbl-dsu/jss_export

wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU/dcs         250G  105G  146G  42% /brbl-dsu/dcs

wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_006/yul_dc_tst1-CC1702-LIBITS                  20T     0   20T   0% /data

**Comment by dl-maura** [comment]
I had some items failing (like they should)
