### ISSUE TITLE
Add new Notch8 folks to team

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#102]
**ISSUE**
Alex Boster, Kait Sewell, and Dylan Salay will be joining the project starting May 4.

**ACCCEPTANCE**
- [x] Add names & ids to the team roster https://docs.google.com/spreadsheets/d/1buZmd2Nq_R8yL6NYUySPW5cWaNoZwNRWqk-1OIzYX74/edit#gid=0
- [x] Add new folks to GitHub team
- [x] Add new folks to DockerHub
- [x] Add new folks to #yale-libraries Slack channel
- [X] N/A ~Add new folks to Yale project folder(s) on Box~ (anyone with the link...)
- [X] Add new folks to Yale project folder(s) on Google Drive
- [x] Invite to recurring meetings
- [X] N/A ~Other?~

**Comment by DraxIndustries79** [comment]
Github:
Alex Boster: tilthouse
Kait Sewell: K8Sewell
Dylan Salay: dylansalay

**Comment by mikeapp** [comment]
Github invitations sent

**Comment by K8Sewell** [comment]
DockerHub ID - kaitsewell

**Comment by dylansalay** [comment]
DockerHub ID - 24238
