### ISSUE TITLE
Mock-up sample re-association CSV

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1023]
**ISSUE**
We can de-couple a number of re-association stories if we settle on the CSV format first.

**ACCEPTANCE**
Develop a sample CSV that
- [x] Includes the expected header row - i.e. decide on the header row labels
- [x] includes sample data for
   - [x] one parent mapped to one child (can this be a mock example?)
   - [x] one parent mapped to multiple children
   - [x] parent object titles
   - [x] child object captions
   - [x] child object labels
   - [x] child object order (when more than one child is associated with a parent)
   - [x] child object iiif (viewing hint)

**Comment by dl-maura** [comment]
Assuming this is for import, the sheet doesn't currently have title for parent for import.

**Comment by mark-dce** [comment]
If DSU folks don't need or want the title, we can definitely leave it out - it does get redundant on works with lots of children.  I included it mostly out of habit when designing processes like this - it acts as an auditing support for the humans who aren't as familiar with the IDs.

**Comment by dl-maura** [comment]
I take it back, it is there ,I was confusing this with something else! Sheet is under review but should be done hopefully today!

**Comment by dl-maura** [comment]
I made up header rows but we can change them as needed -- I couldn't remember if the goobi labels are the same as the labels in dcs

**Comment by dl-maura** [comment]
https://docs.google.com/spreadsheets/d/1doda9saL0lfyRuCB-uFaB761BRAh8Nj9tc1J2KDTBDc/edit?usp=sharing
