### ISSUE TITLE
Import captions and labels from a re-associaton CSV file

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1024]
**STORY**
As a member of the digital studio team, I would like to be able to use the same workflow to update cations and labels as the one I use for managing re-associations, so that I don't have to keep switching between different processes for similar work.

**ACCEPTANCE**
Given a csv export process as described in #1020 and #1022
- [ ] from each row, import the **caption** for the corresponding child image
- [ ]  from each row, import the **label** for the corresponding child image

**Comment by dl-maura** [comment]
this is already in another ticket we're working on
