### ISSUE TITLE
Address memory issue in calculating sha's

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1027]
We are sometimes running out of memory when comparing the access master and temp file's sha's in the management application while creating ptiffs. Refactor so that this method is less memory-intensive.

### Implementation notes
* The method Max is guessing might need to be refactored - https://github.com/yalelibrary/yul-dc-management/blob/b029d500dcf76a61931f5334d2bc7cef1c8e0899/app/models/pyramidal_tiff.rb#L70 
* Honeybadger error - https://app.honeybadger.io/projects/72674/faults/74204526
* Documentation of likely cause & fix - https://bugfactory.io/blog/ruby-digest-with-constant-memory-usage/

**Comment by martinlovell** [comment]
Two possible solutions: 

https://github.com/yalelibrary/yul-dc-management/compare/sha_memory_management_1
Only reads part of the beginning and end of very large files to perform checksum.  (Middle of file could be different and they will still pass.)

https://github.com/yalelibrary/yul-dc-management/compare/sha_memory_management_2
Explicitly chunks file to ensure that file reading is done in chunks.  (Not sure how SHA is implemented and how much of a buffer is kept internally by Digest::SHA256.  May not affect memory usage.)

**Comment by martinlovell** [comment]
After hearing from @mlooney  and @mikeapp , option 2: https://github.com/yalelibrary/yul-dc-management/pull/476

Passes in file in chunks.

**Comment by martinlovell** [comment]
It does seem like ruby's implementation of .file does chunk, so we may have already been chunking, but now we are sure:
https://github.com/ruby/ruby/blob/48b94b791997881929c739c64f95ac30f3fd0bb9/ext/digest/lib/digest.rb#L49

**Comment by dl-maura** [comment]
Need something with ptiffs to test

**Comment by martinlovell** [comment]
Address by removing checksum in this situation.  (Still runs checksum against Goobi provided sha in mets after copying that file into place.)

https://github.com/yalelibrary/yul-dc-management/pull/479

**Comment by martinlovell** [comment]
Ingested new object without PTIFFs generated yet in test:
https://collections-test.library.yale.edu/catalog/17383663

**Comment by martinlovell** [comment]
Ingested new object without PTIFFs into UAT:
https://collections-uat.library.yale.edu/catalog/17342584

(Verified the PTIFF were not yul-dc-image-samples, and that they were there after with correct create dates.)
