### ISSUE TITLE
SPIKE: Diagnose and propose solution to top 4 Honeybadger errors

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1028]
**ISSUE**
We are consistently overrunning our Honeybadger license limits despite already having increased our error quota two times.  This is 1) expensive, and 2) creates a low signal to noise ratio.

**ACCETPANCE**
- [ ] Review the top 4 errors from the management app (compare "Count" vs. "Last" - address the top 4 that have occurred within the last week)
- [ ] Write a ticket proposing a solution to reduce each error type by at least 50%

**BACKGROUND**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/a9e571fc-8602-4cf8-9cb8-37ac561213b3)

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/6c6fb3c0-3bf9-4155-b062-9d2a6f1bde12)

**Comment by mikeapp** [comment]
The Cantaloupe server's `delegates.rb` file appears to have debugging code left in the `s3source_object_info` method:

```
    begin
      fail "NoSuchFileException"
    rescue => exception
      Honeybadger.notify(exception, {
        error_message: "404 Not Found: #{bucket}/#{image_path}"
      })
    end
```

![Screen Shot 2021-02-02 at 10.38.54 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/4f4f75e9-18a6-47bd-a91b-23ba859690ac)

**Comment by mikeapp** [comment]
Created #1058 and #1065, will close this ticket.
