### ISSUE TITLE
ASpace Mappings should use translations for "linear feet" and "mixed materials"

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1029]
**Story**

For example, right now Linear Feet is coming through as linear_feet, Mixed Materials is coming through mixed_materials.

**Acceptance**
- [ ] Extent terms use human-readable form
- [ ] ~~"mixed_materials" uses human-readable form.~~  (Not sure where this is being displayed in the current UI.)

**Comment by FCRodriguez7** [comment]
Linear Feet
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/91059ec7-5049-4889-9386-22e4e1a9163e)


Mixed Materials 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3db9ab32-6536-4c03-9693-8056e4bf29cd)

**Comment by mikeapp** [comment]
So this is still an issue, we'll need to consult with YAMS.
For "linear_feet" see https://collections.library.yale.edu/catalog/31960579

**Comment by DraxIndustries79** [comment]
Check after 7/21 MC update.  We may get a fix on this.

**Comment by FCRodriguez7** [comment]
wait for the last ingest process to complete.

**Comment by FCRodriguez7** [comment]
List for mixed_materials
10001148
2052809
2052784
17145211
17167797

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/catalog/31960579
Extent is no longer in the result of metadata cloud:
https://metadata-api.library.yale.edu/metadatacloud/api/1.0.1/aspace/repositories/11/archival_objects/680179?mediaType=json
The ASpace record was updated on July 20th.

**Comment by mikeapp** [comment]
@martinlovell  Perhaps missing values are related to MC issue #277 - looking only in the leaf nodes for extent values?   Is the next ticket for MC investigation or should we ask Mark/DSU for an example?

**Comment by MaggieZhaoYale** [comment]
@mikeapp Mark confirmed that extent is only in the leaf nodes last week. I will ask Mark for an example.

**Comment by MaggieZhaoYale** [comment]
https://collections-test.library.yale.edu/management/parent_objects/10719304
has the extent "16 pages"

**Comment by MaggieZhaoYale** [comment]
Mark added "16 pages" as the first extent, and a second extent subrecord (1 linear_feet, which should show up as 1 linear feet), but it's not showing up, even after updating the object. 
Metadata cloud does not show the second extent https://metadata-api-test.library.yale.edu/metadatacloud/api/1.0.1/aspace/repositories/11/archival_objects/204680?mediaType=json.
