### ISSUE TITLE
Restrict access to works not marked "Public"

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#103]
**STORY**
We'll be bringing in new works to solr may not be ready for public access, the system should default to restricting access to works unless they are explicitly marked public.

**ACCEPTANCE**
- [x] Determine a subset consisting of 30-35 of the current sample set and add an access field to them and mark those works as public.
- [x] Implement access restrictions that prevent the remaining works from being discovered in blacklight

**Comment by DraxIndustries79** [comment]
Requirement is that they appear in search results but get "Cannot Display."

**Comment by K8Sewell** [comment]
Confirmed in standup - that adding a field to the record's data will be required to complete this objective.

**Comment by K8Sewell** [comment]
Note pulling 43 not 45 records because 2 are marked non public.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/6b49fe75-d404-4a5c-a606-61a47c8cf0cc)

**Comment by K8Sewell** [comment]
Paths to files that were marked non public.  Randomly chosen.  No correlation to Yale's public/nonpublic listings.  

/yul-dc-blacklight/spec/fixtures/voyager/bid-1264367.json
/yul-dc-blacklight/spec/fixtures/voyager/bid-9734851.json

**Comment by dl-maura** [comment]
Items are:
1264367 -- https://brbl-dl.library.yale.edu/vufind/Record/3538687?object_id=2030006 (The glory of old England ...)
9734851 -- https://brbl-dl.library.yale.edu/vufind/Record/3592331?object_id=10269867 (Indulgence Scroll)
