### ISSUE TITLE
Solr - failed to reserve shared memory

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1035]
Some relevant-seeming breadcrumbs here - https://github.com/docker-solr/docker-solr/issues/273 

Does not seem to be something that is causing people problems in production, as far as I can tell.

```
solr_1               | Starting Solr v1.0.6
solr_1               | The currently defined JAVA_HOME (/usr/local/openjdk-11) refers to a location
solr_1               | where java was found but jstack was not found. Continuing.
solr_1               | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1               | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1               | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
```

**Comment by epugh** [comment]
@maxkadel I fixed the warning about the jstack error in Solr 8.8 ;-)   I'm looking at the other message.

**Comment by epugh** [comment]
@maxkadel https://github.com/apache/lucene-solr/pull/2304

**Comment by Subhajitdas298** [comment]
> @maxkadel I fixed the warning about the jstack error in Solr 8.8 ;-) I'm looking at the other message.

Hi @epugh, can you please shared your experience on this? Is it by using the jattach?

**Comment by epugh** [comment]
Checkout https://issues.apache.org/jira/browse/SOLR-15133 and https://github.com/apache/lucene-solr/pull/2304

**Comment by epugh** [comment]
https://issues.apache.org/jira/browse/SOLR-15010 and yes, by adding jattach.  Solr 8.8 doesn't have this issue.
