### ISSUE TITLE
[Check] Check for SuggestComponent errors

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1036]
**Story**

**Check whether we can close this.**
- [ ] Immediate work is to look at the Solr logs to see if this error is recurring.  If not, close it.  Make tickets for other errors.

Original issue:

Problem building mySuggester index

I believe we've tried a couple times to address this, looking at https://github.com/projectblacklight/blacklight/issues/1972 for resources. Either this is present multiple places / ways, or we have not addressed the core (lol) of the issue.

```
2021-01-28 17:52:40.275 ERROR (searcherExecutor-15-thread-1-processing-x:blacklight-core) [   x:blacklight-core] o.a.s.h.c.SuggestComponent Exception in building suggester index for mySuggester:  => java.lang.IllegalArgumentException: input automaton is too large: 1001
```

Which leads to what looks like an infinite loop of

```
	at org.apache.lucene.util.automaton.Operations.topoSortStates(Operations.java:1275) ~[?:?]
```

Acceptance:
- [ ] Investigate whether this is still an issue

**Comment by maxkadel** [comment]
One question I have is - we've tried to address this on the image with at least 2 commits that affect https://github.com/yalelibrary/yul-dc-solr/blame/master/solr/conf/schema.xml , but would this take effect on a solr core that had already been built / instantiated, or only for a new solr core?

**Comment by orangewolf** [comment]
you would need to copy the config files in to the existing core
