### ISSUE TITLE
IIIF Canvases missing labels

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1038]
It looks like there are numerous IIIF manifests that have Canvases without the `label` attribute.   This is not permitted by the specification and viewers assume it is present.

See https://collections.library.yale.edu/manifests/2020085 for example, which results in this display in Mirador:

![Screen Shot 2021-01-28 at 3.41.52 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9362d665-c4c5-4a6a-9955-3965f5bc7206)

If data for the label is lacking, the recommendation is to supply an empty string.

*Acceptance*
- [x] Every Canvas in a Manifest has a `label` attribute
- [x] Where data is not available the `label`  is an empty string.
- [ ] The Manifest passes the IIIF Validator https://iiif.io/api/presentation/validator/service/

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/494

**Comment by martinlovell** [comment]
For 2000930 on test:

Before:
![image](https://user-images.githubusercontent.com/32851993/107258187-82677400-6a09-11eb-8eac-1b2314168d71.png)


After:
![image](https://user-images.githubusercontent.com/32851993/107258125-6fed3a80-6a09-11eb-930c-df76885e42b3.png)
