### ISSUE TITLE
SPIKE: Reference implementations of IIIF access controls

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#104]
**ACCEPTANCE**
- [x] Find at least three different sites implementing some form of image access control
- [x] Write up similarities and difference between implementations
- [x] Evaluate whether it works with either UV and Mirador 2 or 3

**SUGGESTIONS**
- [x] Stanford/Emory
- [ ] Getty
- [x] British Library* - http://access.bl.uk/item/viewer/ark:/81055/vdc_000000021732#?c=0&m=0&s=0&cv=0
- [x] Ask in IIIF Slack for suggestions

Document in progress here: 
https://docs.google.com/document/d/1BdpOpXkfDssOQfnmDJ5iqcszIes80DjkEA7dbr5i2tw/edit#

**Comment by dl-maura** [comment]
Rob Sanderson is coming to Yale from Getty, and we want to ask him questions. David Newberry at Getty (on IIIF slack)

**Comment by mikeapp** [comment]
Also Stefano Cossu at the Getty (who is also on IIIF Slack)
