### ISSUE TITLE
Issue with links from Orbis and changing the number of items per page in search results.

### ISSUE THREAD

**Issue by rebeccahirsch** [yalelibrary/YUL-DC#1047]
**Story**

If you click on a link from Orbis (http://hdl.handle.net/10079/bibid/11167038) and you try to toggle from 10 results per page to 20, it seems to execute a search that brings back every item in the collection. It doesn't seem to be a function of how many results a linked search has, as even ones with more than 10 exhibit the same behavior (http://hdl.handle.net/10079/bibid/3660118).

**Acceptance**

- [ ] Search results don't change.  If this requires a change to the format of the incoming link, then document this and we'll make a change in the redirect application that generates the redirect from the old Beinecke site to the new digital collections site.

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/524

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.2

**Comment by mikeapp** [comment]
Looks good!
