### ISSUE TITLE
index and Display sourceCreator

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1048]
Example: 2004676

Some items have sourceCreator, which doesn't appear to be being indexed in management or displayed in blacklight

- [ ] Add sourceCreator to management to be indexed
- [ ] Add sourceCreator to blacklight display, located under sourceTitle, with label Collection/Other Creator per RH

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/480

https://github.com/yalelibrary/yul-dc-management/pull/501

**Comment by dl-maura** [comment]
![Screen Shot 2021-02-09 at 3.19.43 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c3d71579-d9b9-442e-921a-bf4b52ed6a75)
