### ISSUE TITLE
Add emergency banner to Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1049]
**Story**

As a user, I'd like to be informed when there are unanticipated changes to Library services.  Other Yale Library sites display a banner with announcements related to COVID, closures, etc., see https://search.library.yale.edu for an example.   Digital Collections should display the same banner.   

**Background**

The banner message and color are provided via a centrally managed `banner.json` file.  See https://banner.library.yale.edu/banner.html for a minimal example.

**Acceptance**

- [ ] Digital Collections displays a banner at the top of the page when an announcement is published via the central `banner.json` file.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/478
