### ISSUE TITLE
SPIKE: Dynatrace vs AWS PSQL Load

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1051]

**Comment by bobrice** [comment]
Need more information about what this is.  Monitoring related?

**Comment by mikeapp** [comment]
My vague recollection was that at one point someone saw Postgres CPU high on one monitor and low on another (Cloudwatch vs Dynatrace).   

Are we happy with the monitoring in place for the Postgres instance?  If so, I recommend we close this ticket.
