### ISSUE TITLE
Feb. 3rd Production & Staging Deployment 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1053]
On Wednesday, we will be using the maintenance window to update the staging and production systems:
- [x] Prod Management version: v2.27.6
- [x] Prod Blacklight version: v1.39.3
- [x] Staging Management version: v2.27.6
- [x] Staging Blacklight version: v1.39.3

**Comment by mikeapp** [comment]
There are 1M objects in the cantaloupe cache, I think deleting via the web interface will be problematic.

**Comment by bobrice** [comment]
management has been deployed to staging and prod

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/771453e7-5e9a-485e-bb0b-11c0bbb96d21)

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/d0f6860b-1cb3-49e9-93a3-3cba7ec86a7c)

**Comment by dl-maura** [comment]
try again this afternoon
