### ISSUE TITLE
Update Manifest Metadata to match new fields/orders in blacklight

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1054]
We updated the field names and order in the blacklight app, and now we want to mimic that in the manifests.

(List incoming)

In order:

Alternative Title
Creator
Published/Created (currently just Date)
Copyright Date
Publication Place
Publisher
Abstract
Description
Extent
Extent of Digitization
Projection
Scale
Coordinates
Digital
Edition
Langauge
Call Number
Collection Title (currently Source Title)
Collection Creator (doesn't exist, coming in 1048, not sure if you wanted a heads up now)
Collection Created (Currently Source Created)
Collection Date (currently Source Date)
Collection Note (currently Source Note)
Collection Edition (currently Source edition)
Container / Volume Information
Finding Aid
Format
Genre
Material
Resource Type
Subject (Geographic)
Subject (Name)
Subject (Topic)
Access
Rights
Citation (currently References)
Orbis ID (currently Orbis Bib ID)
OID
More Information

Remove: record type, source, uri, number of pages

**Comment by FCRodriguez7** [comment]
What should happen to these fields?

    label: 'Extent of Digitization',
    label: 'Number of Pages',
    label: 'Projection',
    label: 'Scale',
    label: 'Material',
    label: 'Resource Type',
    label: 'Copyright Date',
    label: 'Coordinates',
    label: 'Digital',
    label: 'Edition',
    label: 'Language',
    label: 'Publication Place',
    label: 'Publisher',
    label: 'Source Created',
    label: 'Source Edition',
    label: 'Source Note',
    label: 'More Information',

**Comment by dl-maura** [comment]
Do want those, I will update list and let Frederick know they were added

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/503

**Comment by dl-maura** [comment]
add Collection Creator (doesn't exist, coming in 1048, not sure if you wanted a heads up now) to another ticket

**Comment by FCRodriguez7** [comment]
**The work is missing some of the correct labels.** 


Alternative Title
Creator
Published/Created Date (currently just Date) **- do not need to change, this matches blacklight application already**
Copyright Date
Publication Place
Publisher
Abstract
Description
Extent
Extent of Digitization
Projection
Scale
Coordinates
Digital
Edition
Langauge
Call Number
Collection Title (currently Source Title) **- does need to change, this does not match the blacklight application  already**
Collection Creator (doesn't exist, coming in 1048, not sure if you wanted a heads up now) **- separate into another card, work is not ready for this sprint**
Collection Created (Currently Source Created)**- does need to change, this does not match the blacklight application  already**
Collection Date (currently Source Date)**- does need to change, this does not match the blacklight application  already**
Collection Note (currently Source Note)**- does need to change, this does not match the blacklight application  already**
Collection Edition (currently Source edition)**- does need to change, this does not match the blacklight application  already**
Container / Volume Information
Finding Aid
Format
Genre
Material
Resource Type
Subject (Geographic)
Subject (Name)
Subject (Topic)
Access
Rights
Citation (currently References) **- does need to change, this does not match the blacklight application  already**
Orbis ID (currently Orbis Bib ID)
OID
More Information

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/507

**Comment by dl-maura** [comment]
Looks good to me on test:
![Screen Shot 2021-02-10 at 8.49.42 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/f5df8909-cb13-47f1-a56f-b2c1e256493d)
![Screen Shot 2021-02-10 at 8.49.59 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/01db22eb-c6c7-4d51-bbda-b69639b51316)

**Comment by FCRodriguez7** [comment]
I tested it this morning, here's the test: 

Before Code  Modifications
![Screen Recording 2021-02-10 at 09.25.22 AM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/197a619c-c53d-4f50-8977-6ce0f3af4eb6)

After Code Modifications
![Screen Recording 2021-02-10 at 09.26.46 AM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/99add4ae-0adc-4c32-a32b-f90a456b83d4)
