### ISSUE TITLE
Integrate Google Tag Manager (& Analytics) into production application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#1056]
**STORY**
We would like to enable Google Tag Manager, and by extension Google Analytics, running on the production discovery application (yul-dc-blacklight), so that we can begin measuring user impact and other statistics.

**ACCEPTANCE**
- [ ] Add the required code snippet to the application - see below
- [ ] Work with the AUXR team (Sarah Tudesco & Meng Tang) to finalize any required configurations in Google Tag Manager

>Begin forwarded message:
>
>From: "Tudesco, Sarah" 
>
>Hello Mark,
> 
>The AUXR Group is here to help. Meng Tang (a member of the AUXR team) and configured a new Google Analytics / Google Tag Manager setup for the site:https://collections.library.yale.edu/.
> 
>To get started, you need to install the container code on the site.
 >
>Google Tag Manager Code:
> 
>Paste this code as high in the <head> of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PX75HSF');</script>
<!-- End Google Tag Manager -->
``` 
>Additionally, paste this code immediately after the opening <body> tag:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PX75HSF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
``` 
>If you have a setup where there is a pre-configured module or GTM, you may just need the Container information: 
>GTM-PX75HSF
> 
>Once the code is installed, we can check Google Analytics to make sure it’s receiving data. Once everything is working, then we can drill down into the configuration details to ensure that we’re collecting the information we want.
> 
>Sarah
> 
>Sarah J. Tudesco (she/her/hers)
>Program Director, Assessment & User Experience Research
>Yale Library
>Department email: auxr@yale.edu

**Comment by kcompsci** [comment]
Here is a link to the Github pull request

https://github.com/yalelibrary/yul-dc-blacklight/pull/477

**Comment by mikeapp** [comment]
I see data in the 'realtime' view when visiting UAT.
