### ISSUE TITLE
Inconsistent deploy to collections-test

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1061]
The current Jenkins script behaves inconsistently in deploying the workers to collections-test. Sometimes the `ACCESS_MASTER_MOUNT` is set to "s3" (which is incorrect and will break the ingest of any new objects in production), sometimes it is set to "/data" which is correct. 

In talking to McClain, it appears the issue may be, at least in part, this stanza, which creates a race condition between the deploy of the two types of workers. This is different between the collections-test deployment script and the production deployment script.

```
if [ "$DEPLOY" = "deploy-mgmt" ]; then
	cam deploy-worker $CLUSTER_NAME &
    WORKER_COUNT=1 cam deploy-intensive-worker $CLUSTER_NAME
fi
```

**Comment by maxkadel** [comment]
You can see this by going to the historical task definitions and looking at what the ACCESS_MASTER_MOUNT is set to. See, e.g., https://console.aws.amazon.com/ecs/home?region=us-east-1#/taskDefinitions/yul-dc-test-worker/166, https://console.aws.amazon.com/ecs/home?region=us-east-1#/taskDefinitions/yul-dc-test-worker/165, https://console.aws.amazon.com/ecs/home?region=us-east-1#/taskDefinitions/yul-dc-test-worker/164

**Comment by mikeapp** [comment]
Keith removed the ampersand to bring test in line with production
