### ISSUE TITLE
Fix Blacklight query strings with double quotes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1065]
**Story**

Honeybadger is reporting searches that have callNumbers wrapped in two sets of quotes (`%22`), which causes an error.  

https://collections.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&callNumber_tesim=%22%22YCAL+MSS+269%22%22&commit=SEARCH&

~~I'm assuming this is due to a pre-existing link having quotes, and a second set being added by the redirect app.~~
See comment below, this is from advanced search.

**Acceptance**
Wherever the redirect app adds quotes:
- [ ] Advanced search does not add a second set of quotes (?)

**Comment by edejesusyale** [comment]
This is caused by the advanced search specifically having double quotes.

**Comment by edejesusyale** [comment]
Going to monkey patch the blacklight advanced search gem to sanitize the query.

**Comment by maxkadel** [comment]
> Going to monkey patch the blacklight advanced search gem to sanitize the query.

Does this mean you're working on it? Want to put it "in progress" and put your name on it?

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/compare/main...1065_double_quotes

**Comment by edejesusyale** [comment]
Using the url on test: https://collections-test.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&callNumber_tesim=%22%22Ernst%2073%22%22&commit=SEARCH&

Returns results.

**Comment by mikeapp** [comment]
Looks good, closing.

UAT example w/one set of quotes:

https://collections-uat.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&creator_tesim=&title_tesim=&callNumber_tesim=%22Za+Zot3%22&date_fields=&subject_fields=&genre_fields=&oid_ssi=&child_oids_ssim=&commit=SEARCH

w/two sets of quotes:

https://collections-uat.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&creator_tesim=&title_tesim=&callNumber_tesim=%22%22Za+Zot3%22%22&date_fields=&subject_fields=&genre_fields=&oid_ssi=&child_oids_ssim=&commit=SEARCH
