### ISSUE TITLE
Log progress and final status of "Reassociate child oids" batch action

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1074]
**Summary:**

We have added two new batch actions, "reassociate child oids" and "re-generate ptiffs," batch processes associated with these actions should report their status.  This ticket is for "Reassociate child oids."

**Acceptance:**
- [ ] "Reassociate child oids" batch action
  - [ ] log the process
  - [ ] give the final status of the import

**Comment by maxkadel** [comment]
Broken out from #1021

**Comment by martinlovell** [comment]
See also: #1075

**Comment by DraxIndustries79** [comment]
Note that if Notch8/DCE picks this up, make sure to pair with Yale.

**Comment by DraxIndustries79** [comment]
Split into separate tickets.

**Comment by mikeapp** [comment]
![Screen Shot 2021-02-25 at 2.07.06 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/939e81e8-30d3-424d-8bb6-99cefe694076)
