### ISSUE TITLE
SPIKE: Review Failed PDFs in production

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1076]
Failed parent oids:
16865295:  PTiff 16865345.tif is 2GB
16674641: Failed on glyph: U+0654 (https://codepoints.net/U+0654?lang=en) ARABIC HAMZA Above
16591156: Failed on glyph: U+0654 (https://codepoints.net/U+0654?lang=en) ARABIC HAMZA Above
11640388: Failed on glyph: U+202A (https://codepoints.net/U+202A?lang=en) LEFT-TO-RIGHT EMBEDDING
10843794:  Failed on glyph: U+0655 (https://codepoints.net/U+0655?lang=en) ARABIC HAMZA Below
10840913:  Failed on glyph: U+0654 (https://codepoints.net/U+0654?lang=en) ARABIC HAMZA Above
10840910:  Failed on glyph: U+0654 (https://codepoints.net/U+0654?lang=en) ARABIC HAMZA Above
10840909:  Failed on glyph: U+0654 (https://codepoints.net/U+0654?lang=en) ARABIC HAMZA Above
2053268: Ptiff 10616789.tif is 1.9GB

**Comment by dl-maura** [comment]
Some characters aren't in the fonts

**Comment by dl-maura** [comment]
Need to address the large item failures
