### ISSUE TITLE
Reduce vertical padding on banner

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1078]
**Story**

The announcement header (green) on Quicksearch (search.library.yale.edu) is shorter than on our Blacklight.

**Acceptance**
- [x] Reduce or eliminate the padding on the announcement header.  (Is there a minimum we want to keep for accessibility?)
- [x] Eliminate the white border around the green box.

**Comment by DraxIndustries79** [comment]
If there's an accessibility issue, leave it alone and remove the white border.
