### ISSUE TITLE
Add confirmation for global Reindex and Update Metadata buttons

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1079]
**Story**

![Screen Shot 2021-02-18 at 1.07.51 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/4ad0d099-a551-4b60-93b7-f32da71817d4)

Reindexing is very expensive and we should confirm the user's intent when they click on this option.
(In the future we will likely limit this permission to superusers).

**Acceptance**

- [ ] Add a confirmation dialog or intermediate screen for each of the two functions with the text:  "This action will (reindex|update metadata for) the entire contents of the system.  Are you sure you want to proceed?"

**Comment by FCRodriguez7** [comment]
[Uploading... Add confirmation for global Reindex and Update Metadata buttons#1079.gif]
