### ISSUE TITLE
(not-)"blank" labels from Goobi

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#1082]
**Story**
The examples we have from Goobi have " - " as the label for the child objects (see https://collections-test.library.yale.edu/management/parent_objects/30000557 ) 

Discussion:
* Goobi likely cannot be modified without unreasonable effort
* We do not want to store " - " in the database
* Decision:  change the Management app to store nil instead of this value

**Acceptance**
- [x] When the label " - " is provided by Goobi, the Management application stores a nil value.

**Comment by dl-maura** [comment]
- be converted and saved as nil

**Comment by mikeapp** [comment]
Goobi import on test looks good:

![Screen Shot 2021-02-16 at 1.31.51 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/ff6eaf84-df09-4648-95bd-b69913eec9be)
