### ISSUE TITLE
Which fields should be included in PDF cover page metadata?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1084]
**Story**
Cover page metadata for PDFs seems to be missing important data, such as the call number.   

**Acceptance**
- [x] Document desired field names/order for engineering team

**Comment by dl-maura** [comment]
Title (already there)
Date (already there --maybe update to Published/Created Date for harmony with Blacklight?)
Call Number (which is there but using the old MC fieldname so needs to be fixed)
Rights (already there)
Container Information (already there)
Extent of Digitization (new)

**Comment by mikeapp** [comment]
See related ticket
