### ISSUE TITLE
Make management app users viewable

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1086]
**Story**

Admins of the management system need to be able to review the users who can log in.

**Acceptance**
- [x] A new item `Users` is added to the left menu in the management app
- [x] Clicking that item leads to a page that presents a paginated and sortable list of users, with column headers/values:
  - [x] "NetId" as label for `uid`
  - [x] "Email" as label for `email` 
  - [x] "Inactive" as label for `deactivated`

**Stretch Goals:**
- [x] Default to "Active" users only
- [x] Dropdowns on columns like with the parent object table for "Active," etc (like ILS Ladybird)

**Implementation Notes:**
Follow data table format.
Use column-based searching.

**Comment by dylansalay** [comment]
By default to "Active" Users only, do we only want to query non-deactivated Users for this table? If so, does it still make sense to have a dropdown on the "Inactive" column if we will never return deactivated Users?

**Comment by mikeapp** [comment]
We want to be able to see them if the filter is turned off

**Comment by mikeapp** [comment]
Looks good on test, needs to get into a release.
