### ISSUE TITLE
Allow creation of new users in the management app

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1088]
**Story**

As an admin of the management app I would like to be able to create new users.

**Acceptance**

- [x] On the "Users" screen there is an option to create a new user by providing a NetID.
- [x] The creation process requires an email address to be associated with the user
- [x] The action creates the user with the appropriate `uid` and `provider` values, and defaults the user to being active

**Comment by martinlovell** [comment]
Form:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/e717f3aa-d4e9-46b3-ba70-31d567c5f813)

https://github.com/yalelibrary/yul-dc-management/pull/535
