### ISSUE TITLE
Update PDF metadata fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1093]
**Story**

As a user I'd like to have sufficient metadata on the cover page of my PDF.   Unfortunately there seems to be an issue with this, perhaps related to metadata cloud/Solr name changes.   We have been provided with a list of the desired fields, see #1084

**Acceptance**
- [ ] PDF cover pages contain the desired fields from #1084

PDF fields:

Title (already there)
Date (already there --maybe update to Published/Created Date for harmony with Blacklight?)
Call Number (which is there but using the old MC fieldname so needs to be fixed)
Collection Title (NEW)
Rights (already there)
Container Information (already there)
Extent of Digitization (NEW)

**Comment by martinlovell** [comment]
It might be possible to extend and use: config/initializers/metadata_fields.rb

**Comment by mikeapp** [comment]
UAT:

![Screen Shot 2021-02-25 at 1.10.31 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/8ca5fbdd-c7c5-4e8f-ae01-da8caa9f257f)
