### ISSUE TITLE
Restrict global "Reindex" and "Update Metadata" functionality to admins

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1094]
**Story**

![Screen Shot 2021-02-18 at 1.07.51 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f1a73efc-adbe-4cfb-ae8b-b5967f31bfd4)

In the management application, reindexing the entire data set is a very expensive operation.   The ability to do this should be limited to those with the system admin role.

**Acceptance**
- [x] Only users with the `sysadmin` role can initiate these functions
- [x] The UI shows the option as disabled for non-sysadmins

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/550
