### ISSUE TITLE
Failed PTIFF generation should fail job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1098]
**Story**

A failed PTIFF generation job was logged as completed on production.  No PTIFF was uploaded to S3.   We should investigate whether the reporting will be fixed by the pending refactor, but in any case the PTIFF job should have failed and been re-queued rather than completing.

Job: 145
Parent OID:  17300443
Child OID: 17310051

**Acceptance**

- [x] Be sure that if no PTIFF is uploaded to S3 the PTIFF job triggers an error resulting in subsequent retries and eventual failure per Delayed Job.

**Comment by mikeapp** [comment]
See https://github.com/yalelibrary/yul-dc-management/pull/521

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/521

**Comment by mikeapp** [comment]
Want to check in about how this interacts with delayed_job retries.
