### ISSUE TITLE
Parent Batch Process Detail shows incorrect event timestamp for children

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1101]
**Story**

In the Batch Process Detail view the child object's timestamp is not that of the event, but of the record creation.   The table should display the timestamp of the event.

![Screen Shot 2021-02-22 at 11.09.32 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/8544431e-e92a-4388-b845-345e2c80eac8)

**Acceptance**

- [ ] The table shows the timestamp of the correlated status/event.

**Comment by DraxIndustries79** [comment]
If Frederick's findings about this being a historical issue are validated, there may be another ticket or we may decide it's OK.
