### ISSUE TITLE
Log progress and final status of Re-generate ptiffs batch action

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1105]
**Summary:**

We have added two new batch actions, "reassociate child oids" and "re-generate ptiffs", batch processes associated with these actions should report their status.  **This ticket is for "Re-generate ptiffs."**

**Acceptance:**
- [x] Re-generate ptiffs batch action
  - [x] log the process
  - [x] give the final status of the import

**Comment by mikeapp** [comment]
Looks good for the happy path.   Trying a non-existent OID didn't display anything. I think that is for a subsequent issue related to batch-level status.
