### ISSUE TITLE
Create a Rails model for Administrative Sets in the management app.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1106]
**Story**

Eventually we'd like to associate every item with an administrative set for management purposes.   The MVP data required for the model are:

label: string (required)
summary: string
homepage: string
key: string   (required, this will be used for a short code like `sml` that will be passed from Goobi)

**Acceptance**

- [x] Create an `AdminSet` model.  
     - [x] Seed a set with the label 'Beinecke Library' and key `brbl`
     - [x] Seed a set with the label 'Sterling Memorial Library' and the key `sml`
- [x] Create a left menu item called 'Sets' in the Managment left menu, just below 'Users'
- [x] Link to a page that displays a data table view of the sets, with columns for 
    - [x] key
    - [x] label
    - [x] homepage (linked)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/532

**Comment by DraxIndustries79** [comment]
We'll combine PR's and review the final one.
