### ISSUE TITLE
Align image paths across environments

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#111]
**ISSUE**
It looks like we have two possible implementations for finding paths at https://github.com/yalelibrary/yul-dc-iiif-imageserver/blob/master/delegates.rb#L239-L250

It seems like this runs counter to the principle of dev-prod parity https://12factor.net/dev-prod-parity and potentially introduces inconsistencies between different prod-like environments.  I don’t know of any user-facing requirements that require us to support two different folder structures, so I’d like to see if we could eliminate the need for maintain two separate code paths - especially when there are no automated tests for either.

**ACCEPTANCE**
- [x] Select a single file organization strategy for all environments
- [x] Remove alternate code path from yul-dc-iiif-imageserver

**Comment by mark-dce** [comment]
See this for possible solution for copying between S3 buckets in different accounts https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/

**Comment by mikeapp** [comment]
I have copied the S3 images into the pairtree structure, leaving all but one of the original images intact at the top level so as not to impact anyone's work.    Next step is to update the image server, hope to have this for Monday.

**Comment by mikeapp** [comment]
PR for image server changes ready for review: https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/4

**Comment by mark-dce** [comment]
PTIFFS deleted successfully ( #141 )
