### ISSUE TITLE
Add logging for failures in SetupMetadataJob

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1110]
SetupMetadataJob completes quietly if mets and all image are not found, or if default_fetch of metadata fails.
It should send a failure message **and/or** raise an exception to cause the job to retry.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/529/files

**Comment by mikeapp** [comment]
Looks good.  On UAT, with bogus bib/barcode:

![Screen Shot 2021-02-25 at 2.52.17 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a697f8ff-868c-40a6-81e8-3bd3cea8cdd6)
