### ISSUE TITLE
Child Count not Updating in Table During Reassociation

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#1113]
Currently, the child count isn't updating int he main table, even when new children are added. Seems to only happen when adding children (counts do go down). This item really has 6 children now, but still shows 4.

![Screen Shot 2021-02-24 at 2.16.27 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/317f7dcc-db60-4165-ace8-525e4491d2c8)

**Comment by mikeapp** [comment]
Looks good on UAT
