### ISSUE TITLE
Adjust size limits on Cantaloupe

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1114]
**Story**

As a user I'd like to be able to download the image at full resolution using the links in UV.   Cantaloupe is  currently preventing this due to a size limitation.

![Screen Shot 2021-02-25 at 9.24.02 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/360c1a77-a1c1-4e0f-9843-f8c058fed0d0)

**Acceptance**
- [ ] The maximum limit has been removed ~~or adjusted to a high enough number to allow the largest size object in the system to be downloaded~~

**Comment by MaggieZhaoYale** [comment]
IIIF_IMAGE_VERSION: v1.0.5
Released on test and uat.
