### ISSUE TITLE
Attach persistent storage to ECS cluster

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#112]
As a system user,  I want my solo configuration & data stored persistently on a filesystem mounted into the solr container

### Acceptance Criteria

- [x] administrator can drop & rebuild cluster, and solr data remains unaffected

### Tasks:

* configure EFS storage
* configure ecs-compose to mount EFS into solr container
* configure solr to use said mount

**Comment by dl-maura** [comment]
Underway, McClain is reading documentation

**Comment by dl-maura** [comment]
Keith successfully attached
