### ISSUE TITLE
Show users in roles on the AdminSet page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1121]
**Story**

As management administrators, we'd like to be able to see users in the `editor` and `viewer` roles for an admin set.

**Acceptance**

- [x] On the AdminSet show page, create tables for the two roles and display any users who have the role on the current admin set:
    - [x] `viewer` role
    - [x] `editor` role

![Screen Shot 2021-02-28 at 5.26.33 PM 2.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/af2d944e-e889-4f4f-baf2-c28b700ff4fc)

**Comment by dylansalay** [comment]
1.) Should an AdminSet have_many Users and a User belongs_to AdminSet?
2.) Do we want new models for the Viewer and Editor  roles? In other words, do you want us to follow the rollify documentation for creating these roles by generating the models? Or would you prefer we follow the pattern you used for the sys_admin role?
3.) If you are a sys_admin can you also be a viewer or editor? Or will we need some new seed data for the viewer/editor roles?

**Comment by dylansalay** [comment]
- Can a user have multiple roles (sys_admin, editor/viewer)?
- Do you want these to be datatables?

**Comment by mikeapp** [comment]
Yes, they could have all three.  We'll ignore `sysadmin` for the purposes of AdminSets, just list the editors and viewers for the particular AdminSet that is being displayed.

No need for them to be data tables.

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-management/pull/546

**Comment by alishaevn** [comment]
Co-author: Alisha Evans <alisha@notch8.com>
Co-author: Dylan Salay <dylan@notch8.com>

# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1121

# Summary
- the admin set "show" page has a table to display all users with the role of "viewer"
- the admin set "show" page has a table to display all users with the role of "editor"

# Demo
| table with users | table without users |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/109727364-150eb500-7b69-11eb-8297-39e399b5840b.png) |  <img width="455" alt="image" src="https://user-images.githubusercontent.com/29032869/109727412-2b1c7580-7b69-11eb-86e4-59fb72decbde.png"> |
