### ISSUE TITLE
Allow addition/removal of users in roles on an AdminSet

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1122]
**Story**

As a system administrator, I'd like to be able to add and remove users from the `editor` and `viewer`  roles on an individual AdminSet. 

**Acceptance**

- [x] On each admin set show page, have an option to add a user in one of the roles for the site.  
   - [x] The user should be specified by NetID (i.e., text box).
   - [x] The role can be selected in a drop-down list, the first option should be ‘viewer’.   The other option should be `editor`.
   - [x] On submit:
       - [x]  if the netid/user does not exist in the system, display an error
       - [x] If the netid/user exists and is deactivated, add them but display a warning
        - [x] If the user is added as an editor, remove the viewer role if they have it (editor is superset of viewer privileges)
        - [x] The user should be assigned to the `:editor` or `:viewer` roles using Rolify.  
- [x] Add a Remove button or link  next to each user listed in the Viewer and Editor tables
   - [x] Clicking the button removes the user from that role on the set.

![Screen Shot 2021-02-28 at 5.26.33 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0e6bcdb1-dfa0-47bc-98dd-ecca4b725146)

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-management/pull/547

**Comment by alishaevn** [comment]
Co-author: Alisha Evans <alisha@notch8.com>
Co-author: Dylan Salay <dylan@notch8.com>

# Summary
- users can be added as a viewer _or_ editor per admin set
- users can be removed from their role per admin set

# Demo
https://share.getcloudapp.com/4gu1E1PK

# Resources
- https://rubyinrails.com/2019/07/11/rails-routes-member-vs-collection/

**Comment by mikeapp** [comment]
Does `RolesController` need an auth check that the logged in user is authorized to modify roles?
