### ISSUE TITLE
Remove Notifications

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1123]
**Story** 

The notifications functionality in the management application is not in use and there are some performance concerns around using the current implementation.

**Acceptance**
- [ ] Remove the associated left menu item from the management UI 
- [ ] Remove the associated code
- [ ] Drop the DB table(s)?

**Comment by FCRodriguez7** [comment]
Remove notification from management?

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/674

PR is ready if we don't want to drop the table.

**Comment by FCRodriguez7** [comment]
Released management v2.45.4

**Comment by edejesusyale** [comment]
Side bar on test:
![Screen Shot 2021-06-22 at 2.12.56 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/cc398ed9-decb-4216-83ad-d315439b2d4c)

**Comment by edejesusyale** [comment]
Closed by Mistake
