### ISSUE TITLE
Deployment : March 3rd

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1124]
**Versions**

Management: **v2.32.0**
Blacklight:  **No changes this week**

**Staging : March 2nd**
- [x] Management

**Production : March 3rd**
- [x] Management
- [x] Image server: double CPU and memory

**Comment by martinlovell** [comment]
Everything looks good and as expected.  Blacklight (search, thumbs, image viewer) and management are running as expected.

Image server task definition:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/5f4d30d8-86af-4830-a79c-474fea788565)


Managment footer:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/b700502b-88a7-44ac-bd84-cf509b3cbd81)
