### ISSUE TITLE
Fix upside down images

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1129]
See: 
https://collections.library.yale.edu/catalog/2068561  vs
https://brbl-legacy-dl.library.yale.edu/vufind/Record/3445228

There’s two images in the new DL that are upside down – we’re not entirely sure why, as they display correctly in both the legacy DL and in Storage at Yale, but they need to be re-ingested. Can you please pull them from this location:
 storage.yale.edu/home\DSU_Beinecke-CC0691-YUL\IMAGES-DERIVATIVE_TIFF-2019-2020\BRBL_Outsidejob_25

**Comment by mikeapp** [comment]
Note that the issue may be that the PTIFF generation is not respecting the EXIF/TIFF orientation flag.   See https://www.awaresystems.be/imaging/tiff/tifftags/orientation.html

It might be worth downloading the PTIFF to see whether it displays correctly - does the PTIFF generator copy the flag from the TIFF to the PTIFF?  It's possible that it does but that Cantaloupe doesn't respect it.

We may need to have a preprocessing step where we rotate the TIFF image and produce a correctly oriented TIFF before generating the PTIFF.

**Comment by martinlovell** [comment]
We had originally used the access master from /fc_Beinecke-807001-YUL/TIFS_FROM_JP2/2068561/
rather than /DSU_Beinecke-CC0691-YUL/IMAGES-DERIVATIVE_TIFF-2019-2020/BRBL_Outsidejob_25/Derivatives

Viewing two originals using mac preview shows them flipped.

After refreshing the access master with the 2 images from /DSU_Beinecke-CC0691-YUL/IMAGES-DERIVATIVE_TIFF-2019-2020/BRBL_Outsidejob_25/Derivatives and recreating the PTIFFs, the image seems to have flipped.
(IIIF derivative cache is 24 hours, so we'll have to wait for some zoom levels to be updated.)

We do not scan `/DSU_Beinecke-CC0691-YUL/IMAGES-DERIVATIVE_TIFF-2019-2020/` by default.

Currently, we only scan these directories for images:
```
/fc_Beinecke-807001-YUL/TIFS_FROM_JP2
/fc_beinecke2-YUL-CC0691-YUL/IMAGES-DERIVATIVE_TIFF
/fc_Beinecke-807001-YUL/Gap_load
/fc_beinecke2-YUL-CC0691-YUL/IMAGES-DERIVATIVE_TIFF-2015-2017
/DSU_Beinecke-CC0691-YUL/Missing_DL_TIFS/
```

**Comment by martinlovell** [comment]
For testing see:

https://collections.library.yale.edu/iiif/2/1305108/full/!205,200/0/default.jpg
![image 1](https://collections.library.yale.edu/iiif/2/1305108/full/!205,200/0/default.jpg)

https://collections.library.yale.edu/iiif/2/1305109/full/!205,200/0/default.jpg
![image 2](https://collections.library.yale.edu/iiif/2/1305109/full/!205,200/0/default.jpg)
