### ISSUE TITLE
Add system/goobi user to BRBL and JSS sets with editor role

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1141]
**Story**

Once we have permissions in place, we will need to authorize the "system" user to add content to the BRBL and ~JSS~ SML sets.

**Acceptance**

Grant the user (`System` ?) that the Goobi scans run under the `editor` role for ~JSS~ SML and BRBL.

- [x] Test
- [x] UAT
- [ ] Staging
- [x] Production

**Comment by martinlovell** [comment]
On production, there is only SML and BRBL admin sets.  System is editor of both.
On staging, the System user has not been created yet, since there hasn't been a goobi scan done there yet.

Should we add the JSS admin set to production and staging?

**Comment by mikeapp** [comment]
We don't need the JSS set for now so let's not add it.
