### ISSUE TITLE
Finish oboarding Steve and Tracy

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1146]
Finish setup for Steve:
- [x] add to list of management users
- [x] DevOps ticket
- [x] other roles as needed?

**Comment by mikeapp** [comment]
INC1965777 for DevOps

**Comment by DraxIndustries79** [comment]
INC1965777 for DevOps appears not to be resolved for Steve (AWS credentials not created).  Tracy confirms she is good.

**Comment by mikeapp** [comment]
They were sent but not received.  I requested they be sent again.
