### ISSUE TITLE
Remediate ingest of JSS and other test items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1147]
**Story**

Due to the test shares being mounted to production/staging, Goobi test content was unexpectedly ingested into the production system.   

**Action**

Review batch jobs 150-216.  

- [x] If the parent OID is above 30,000,000, we can just delete the object
- [x]  If the parent OID is below 30,000,000 we need to identify whether the ingest succeeded and whether it may have impacted a pre-existing Beinecke object.   This may involve finding the parent and child OIDs to be sure that the ingest didn't overwrite existing objects.

**Comment by MaggieZhaoYale** [comment]
Except parent oid 1234, 327271, 372665, all other parent oids from Goobi-tst  export folder are above 30,000,000.
1234, 327271, 372665 did not have any children. 
The prod log shows these parent oids only appear delayed_jobs on 03/10.
