### ISSUE TITLE
Include viewing hints in manifests for bound materials

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#115]
**STORY**
When I'm viewing bound materials, I would like to be able to view facing pages at the same time, so that I have an experience more closely duplicating the original artifact.

**DETAILS**
This probably requires including a viewing hint in the manifest, see  
https://iiif.io/api/presentation/2.1/#viewinghint

**ACCEPTANCE**
- [ ] When I view a bound resource in a viewer like the UV demo site, it defaults to a 2-up view

**CURRENT BEHAVIOR**
![image](https://user-images.githubusercontent.com/3064318/81607935-17660f80-939b-11ea-9e79-99ae08ab9d2a.png)

**DESIRED BEHVAIOR**
![image](https://user-images.githubusercontent.com/3064318/81608539-17b2da80-939c-11ea-8cff-14bba3ac8428.png)

**Comment by mikeapp** [comment]
PR is yalelibrary/yul-dc-fixture-manifests#2  - need input
