### ISSUE TITLE
Management dependabot fixes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1151]
**Story**

There are a few dependabot security issues listed. 

**Acceptance**

- [x] Investigate and bump gem versions as needed

Potentially do with #1152

**Comment by alishaevn** [comment]
dependabot alerts: https://github.com/yalelibrary/yul-dc-management/security/dependabot

**Comment by FCRodriguez7** [comment]
Released management v2.35.0
