### ISSUE TITLE
Blacklight dependabot fixes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1152]
**Story**

There are a few dependabot security issues listed. 

**Acceptance**

- [x] Investigate and bump gem versions as needed

Potentially do with #1151

**Comment by alishaevn** [comment]
dependabot alerts: https://github.com/yalelibrary/yul-dc-blacklight/security/dependabot

**Comment by FCRodriguez7** [comment]
I ran a conservative patch update.  The patch command worked and for some reason deleted safe_yaml. 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c4e55c40-e303-48ff-a736-cb6d4529d7f1)


----
I readded the gem.

**Comment by FCRodriguez7** [comment]
I have tested the branch in the test environment.  Works!

**Comment by FCRodriguez7** [comment]
Blacklight v1.41.4
