### ISSUE TITLE
Add the proper provider information to the app/controllers/catalog_controller.rb

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1158]
**Story:**
The proper provider information needs to be added to `app/controllers/catalog_controller.rb`

See: https://github.com/projectblacklight/blacklight_oai_provider#blacklight-configuration

Example:
```
config.oai = {
      provider: {
        repository_name: 'Test',
        repository_url: 'http://localhost/catalog/oai',
        record_prefix: 'oai:test',
        admin_email: 'root@localhost',
        sample_id: '109660'
      },
      document: {
        limit: 25,            # number of records returned with each request, default: 15
        set_fields: [        # ability to define ListSets, optional, default: nil
          { label: 'language', solr_field: 'language_facet' }
        ]
      }
    }
```

**Acceptance:**
- [ ] `app/controllers/catalog_controller.rb` is updated

NOTE: There is some thoughtwork that needs to happen as to what these values should be

**Comment by alishaevn** [comment]
# WIP PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/488

**Comment by alishaevn** [comment]
Spoke to rob about this. We can close https://github.com/yalelibrary/yul-dc-blacklight/pull/488 and instead build upon https://github.com/yalelibrary/yul-dc-blacklight/pull/487.

will need to speak with mike and/or rebecca hirsch to get the correct config values (refer to screenshot above)

**Comment by mikeapp** [comment]
I'd suggest we do this to get started, we can modify later this sprint/next sprint.   

* repository_name: 'Yale University Library Digital Collections"
* repository_url (**should change per environment, e.g -test, -uat**): https://collections.library.yale.edu/catalog/oai
* record_prefix (I think we can leave the same across environments): collections.library.yale.edu
* admin_email:  TBD, leave as-is for now
* sample_id:  2002046
* limit: 25
* set_fields: TBD, leave as-is for now

**Comment by mikeapp** [comment]
I'm going to go ahead and make these changes on the open PR.

**Comment by mikeapp** [comment]
Active PR is now https://github.com/yalelibrary/yul-dc-blacklight/pull/487
Contains:
* Installation of the gem (Rob)
* Configuration info for the provider (Alisha)
* Configuration of a few Dublin Core fields so we can see the gem is providing data (Mike)

Examples:

* Screen capture of http://127.0.0.1:3000/catalog/oai?verb=Identify:
![Screen Shot 2021-03-18 at 6.34.10 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b64fc5c9-0bf5-42a5-8da1-68e4d7afc0d9)

* List records and then navigate to the DC version of a record:

![Screen Shot 2021-03-18 at 6.34.01 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/17f10c75-2250-4bb1-b1ae-59f2ef48555e)

**Comment by DraxIndustries79** [comment]
Information provided above gives the necessary context, but Notch8 team is finished with hours for the week if anyone can pick this up.
