### ISSUE TITLE
Define the MODS format

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1159]
**Story:**
Detail the correct format for MODS that the OAI consumers are expecting. 

**Acceptance:**
Put in shared folder:
 - [x] Get MODS examples from the Ladybird OAI-PMH provider 
 - [x] Get spreadsheet of preliminary mapping

**Comment by kcompsci** [comment]
Here is the original Ladybird to Findit mapping:
[https://app.zenhub.com/files/242185115/04bb5229-b91a-43ee-9ab2-43dc3c03fd2e/download]

Here is the preliminary mapping from the metadata cloud to the Ladybird fields and the difference between the initial Ladybird mapping for the original digital collections (Findit) to the current (Metadata cloud):
Link to Excel Spreadsheet: https://yaleedu-my.sharepoint.com/:x:/r/personal/lakeisha_robinson_yale_edu/Documents/Ladybird%20and%20Solr%20Fields%20lrr.xlsx?d=web4eed5aab6a40c69602dc38446caeff&csf=1&web=1&e=yjgfr5

**Comment by mikeapp** [comment]
@martinlovell @MaggieZhaoYale We should also look at the mapping work done by the metadata TF, they were originally looking at MODS mappings for fields.

**Comment by MaggieZhaoYale** [comment]
I confirmed  the preliminary mapping was worked off of the Metadata Taskforce Mapping sheet.
