### ISSUE TITLE
Add MODS format to Ruby-oai library

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1160]
**Story:**
The MODS format must be added to ruby-oai library.
Blacklight-oai-provider formats are defined in http://github.com/code4lib/ruby-oai. See https://github.com/neubloc/ruby-oai/commit/7bd9ad0d75c983a96425ab5ae005d2701a17d705 as an example of this being done for Marc once upon a time. 
- Fork ruby-oai
- Add support for our MODS needs. 

This work should result in a MODS PR back to ruby-oai if possible.

**Acceptance:**
- [ ] MODS format added to ruby-oai
  - [ ] Forked ruby-oai
  - [ ] Added support for our MODS needs

Bonus:
- [ ] MODS PR back to ruby-oai

**Comment by mikeapp** [comment]
There may have been changes to the library that allow us to do this without a fork.  For instance it looks like there is a method to register a new format:  https://github.com/code4lib/ruby-oai/blob/3cdc12d86c7d1dde00b47105a7dab6def3f6801d/lib/oai/provider.rb#L276

**Comment by martinlovell** [comment]
Simple spike to link it in through the SolrDocument.to_oai_mods....just getting a feel for how it works:
https://github.com/yalelibrary/yul-dc-blacklight/compare/1160_spike_mods?expand=1

Going to: http://localhost:3000/catalog/oai?verb=ListRecords&metadataPrefix=oai_mods shows the response.

(Didn't implement any actual mods code.)

**Comment by martinlovell** [comment]
Rather than fork and update ruby-oai, we are able to add mods format by adding to_oai_mods to SolrDocument and adding some configuration so that the oai_mods format was registered.
