### ISSUE TITLE
Connect MODS format to blacklight_oai_provider

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1161]
**Story:**
MODS format must be connected to `blacklight_oai_provider`. Actually enabling the user to see MODS data at /catalog/oai?
```
verb=ListMetadataFormats
```
Fork the BlacklightOaiProvieder gem and connect it to the mods format. This may be as simple as adding a method to the BlacklightOaiProvider::SolrDocument concern. That seems to be the only place where DC is specified in that gem. 

Notes: This should be contributed back if possible.
Can be done in parallel w/ #1162

**Acceptance:**
- [ ] MODS connected to `blacklight_oai_provider`
  - [ ] Forked `blacklight_oai_provider` gem
  - [ ] Likely solution is to a method to the BlacklightOaiProvider::SolrDocument concern
- [ ] User can see MODS data at /catalog/oai?
- [ ] Iterate on MODS data until it matches data from Ladybird provider

Bonus:
- [ ] PR contributed back

**Comment by martinlovell** [comment]
Fields without equivalents in DigitalCollections that are in LB mods:
```
<mods:identifier type="brbl">brbl999956</mods:identifier>

```

**Comment by martinlovell** [comment]
https://collections-test.library.yale.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_mods

**Comment by mikeapp** [comment]
I believe that we're only indexing/publishing language names in English.  There's an attribute to indicate this in MODS, which we should include, see https://www.loc.gov/standards/mods/userguide/language.html

We can only provide the `text` (second line), not the `code` (third line)
```
<language>
<languageTerm type="text">French</languageTerm>
<languageTerm type="code" authority="iso639-2b">fre</languageTerm>
</language>
```
