### ISSUE TITLE
Add timestamp to records on index

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1162]
**Story:**
As an OAI consumer, I need a timestamp field in the solr index so that we know when records were most recently updated. This timestamp should be updated whenever the management application indexes the record in solr.

Start from https://github.com/yalelibrary/yul-dc-blacklight/pull/487

Note: Can be done in parallel w/ #1161
May already be a timestamp in the solr record/built into solr (OAI library has a place where you can configure which timestamp to use)

**Acceptance:**
- [x] OAI timestamp appears in solr index
- [x] Timestamp is updated when management application indexes the record

**Comment by martinlovell** [comment]
Solr records have a timestamp field provided by solr.
It may be possible to use that existing field.

(View a parent object in management, scroll to bottom, click "Solr Document."  Scroll to the bottom of the resulting json to see timestamp field.)

**Comment by mikeapp** [comment]
I think @martinlovell  is correct based on local testing.  After merging #1158 give the provider a try using the Dublin Core records, I think you will see correct timestamps for the record.

**Comment by DraxIndustries79** [comment]
Possible this can be closed?  Just needs to be deployed.
