### ISSUE TITLE
Write access to jss_export and dcs directories

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1167]
**Story**

The Preservica ingest script needs to be able to write a "done" file into the Goobi packages after they have been ingested.  David is reporting that he does not have write access to the jss_export and dcs directories, although he can read them.

**Acceptance**

David/Preservation have write access to:

The `dcs` folder in:
- [ ] test
- [ ] uat 
- [ ] production
The `jss_export` folder in:
- [ ] test
- [ ] uat
- [ ] production

**Comment by ra359** [comment]
Pinged David Cirella 2021-Mar-23 to see if everything was ok on his end (Preservica). No response yet.

**Comment by ra359** [comment]
David responded - he said will test this week and confirm.
