### ISSUE TITLE
Finding Aid link

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1171]
**Story**

Updates to Metadata Cloud will potentially return multiple Finding Aid links from Voyager records.

**Blocked by MC ticket 260**

**Acceptance**
- [x] All Finding Aid links are rendered when there's more than one.

**Comment by mikeapp** [comment]
Needs Metadata Cloud ticket.

**Comment by martinlovell** [comment]
Some questions:

Should we leave FindingAid as is and add solr fields for RelatedResourceOnline and ResourceVersionOnline from ILS, then make sure those display properly with Titles and Links or just Links?

Does it seem better to parse the two new MC fields on the management side and convert to HTML, a more consistent delimited value, or parallel arrays in Solr so that Blacklight can deal with it more easily?  (Or index as is and parse on the Blacklight side?)

**Comment by mikeapp** [comment]
I would *not* convert it to HTML.  I think indexing as-is and parsing in Blacklight would be fine.

**Comment by martinlovell** [comment]
### Metadata cloud updates related to this ticket:

`findingAid` is always just a URL without a label.  It will be one of more URLs in an array.
This is already setup as a show field, but only displays the first URL when there are multiple URLs.

Added fields:
`relatedResourceOnline`
`resourceVersionOnline`

These need to be stored in Solr separately from the finding aid and will be multi-value.  Store the values as they come from metadata cloud.

We need a show field for these two in blacklight.  The values in the field are | (pipe) separated.
The value should be split on "|" into components.
After splitting on "|" parse the resulting parts to determine if they are URLs or labels by looking for an "http" prefix.

(Typically it will look like this: `relatedResourceOnline: "View Related Resource|http://library.somewhere.com/special_page"` )

If there is one link and one label, use the link and label to construct the link in the show field.
If there is just one link, use the link only.

If there is more than 2 components after splitting on "|", or there are no link components, it's likely a cataloging error.
In this case, should the show field not display?

**Comment by mikeapp** [comment]
> If there is more than 2 components after splitting on "|", or there are no link components, it's likely a cataloging error.
> In this case, should the show field not display?
I agree.

**Comment by martinlovell** [comment]
Bib 11040744 does have a value for testing.

However, I am still having some issues in metadata cloud getting these two fields.
This should be fixed in PR 305 for MC, but still needs to be deployed for production.

I'll update this comment when it has been deployed to test and UAT.

**Comment by FCRodriguez7** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/614

Management PR: https://github.com/yalelibrary/yul-dc-management/pull/725

**Comment by martinlovell** [comment]
Using bib id 12244725 is interesting.
It has multiple related resources with different labels.

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/083b3d96-ed08-4f70-b7e5-fed74dcdd264)

**Comment by FCRodriguez7** [comment]
Released management v2.45.13
