### ISSUE TITLE
Deployment: March 24

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1174]
This week's deployment should be the Blacklight and Management applications.  The versions are attached. 

Blacklight: **v1.41.5**
Management: **v2.35.0**

**Staging:** March 23rd
- [x] Blacklight
- [x] Management

**Production:** March 24th
- [x] Blacklight
- [x] Management

**Comment by bobrice** [comment]
staging deploys are complete

**Comment by bobrice** [comment]
production deploys are complete
