### ISSUE TITLE
OAI provider should only vend public and YCO records

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1179]
The system should respect the access control settings on an object.  OAI provider would not generate a DC record; it will act like it doesn't exist.

**Acceptance**
- [ ] If a record's access status is not Public or Yale Community Only, the OAI provider should not vend a record for that object.

**Notes**
https://github.com/projectblacklight/blacklight/wiki/Extending-or-Modifying-Blacklight-Search-Behavior#extending-the-searchbuilder might be relevant.

**Comment by martinlovell** [comment]
Some info on the visibility filter in blacklight and OAI:
The filter by visibility is here: https://github.com/yalelibrary/yul-dc-blacklight/blob/main/app/models/search_builder.rb#L36

It seems like even GetRecord goes through that code when I run tests locally.
On my local system when I set one of the items to private, I no longer can see it with GetRecord, but on test I can.
Not sure what is causing the difference.

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/495

**Comment by FCRodriguez7** [comment]
The example I used https://collections-test.library.yale.edu/catalog/oai?verb=GetRecord&metadataPrefix=oai_mods&identifier=oai:collections.library.yale.edu:17245011
