### ISSUE TITLE
Create a vanilla rails application for the management application with a rake task to populate solr from fixture data

### ISSUE THREAD

**Issue by geekscruff** [yalelibrary/YUL-DC#118]
**ACCEPTANCE**

- [x] create yalelibraryit/dc-management-base in docker hub @mikeapp 
- [x] There is a vanilla rails application in yalelibrary/yul-dc-management and a docker image in yalelibraryit/dc-management

**Comment by mikeapp** [comment]
Docker good to go:
`docker push yalelibraryit/dc-management-base:tagname`
