### ISSUE TITLE
End-to-end test of sample JSS packages in production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1180]
**Story**

JSS images are staged and package files are ready to feed into Goobi.    We'd like to test a small number of packages in the production  workflow, creating Goobi packages and ingesting them into both Digital Collections and Preservica.

**Acceptance**
- [x] A small (<10) number of packages are created via the production Goobi server
- [x] The packages are ingested by the production management interface.
- [x] Digital Preservation ingests the packages into Preservica
- [x] The Preservica packages are reviewed and found to be complete.

**Comment by DraxIndustries79** [comment]
Need outreach to David re: Digital Preservation. Maggie will email him.

**Comment by DraxIndustries79** [comment]
Let's follow up with David if we don't hear by Friday 4/9

**Comment by MaggieZhaoYale** [comment]
David will meet with Rebecca next week (April 14th)  before starting the Preservation ingests.
