### ISSUE TITLE
Ingest OIDS taken from the Missing OIDS list

### ISSUE THREAD

**Issue by rebeccahirsch** [yalelibrary/YUL-DC#1191]
**Story**

Review of the list of missing OIDs has identified this subset as needing to be ingested.  (See first comment for the OIDs.)

**Acceptance**
- [x] Ingest this list of oids into staging
- [x] Ingest this list of oids into production
- [ ] Give Rebecca list of any that fail, and any information obtained about why

**Comment by rebeccahirsch** [comment]
I could not get an attachment to upload so here's the list. If you want a CVS let me know and I can DM it to you on Slack:

2000071
2002026
2002824
2003317
2004883
2004887
2005363
2005589
2007268
2007627
2007670
2007671
2007672
2007673
2007674
2007675
2007676
2007677
2007678
2008509
2008510
2008511
2008513
2013492
2013645
2014564
2014580
2014596
2016750
2017000
2017002
2017005
2017009
2017010
2017012
2017017
2017020
2017024
2017028
2017238
2017252
2017253
2017728
2018345
2018721
2018724
2018737
2019988
2020948
2021216
2021277
2022101
2026707
2026779
2036313
2037190
2043559
2043771
2043792
2043802
2043849
2043980
2044520
2044526
2046751
2046902
2047026
2052754
2053584
2053586
2054208
2055249
2055250
2056655
2056656
2056657
2056658
2056659
2056660
2056661
2056846
2057503
2057504
2057512
2057539
2057545
2064562
2065164
2065165
2065167
2065171
2065172
2065175
2065176
2065323
2066811
2067575
2068733
2110169
2110176
2110939
2110945
2112449
9998333
9998404
9998405
9998686
9998696
10034118
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10079802
10189518
10256330
10292959
10450136
10460161
10468122
10508605
10518919
10597097
10606915
10606932
10606955
10677643
10927623
11186575
11186576
11186610
11186610
11186610
11186610
11186610
11186610
11186610
11705698
11705700
11747789
11868212
12189438
12327980
15534525
15812698
15952383
16147631
16169340
16495506
16538176
16569887
16593867
16598872
16598956
16600476
16601277
16601278
16601279
16601280
16601282
16601283
16601284
16601285
16601286
16601287
16601288
16601289
16627439
16708283
16712418
16729379
16729384
16808199
16861855
16867527
16917297
17122607
17122716
17122748
17145170
17145183

**Comment by FCRodriguez7** [comment]
**Staging Errors**

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/861d8438-7e2c-49ca-83f0-9def479f823b)

**Comment by FCRodriguez7** [comment]
**Production Errors** - 31 errors

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d35fa53b-0eaf-444c-841d-f4857b0b3bc9)

**Comment by FCRodriguez7** [comment]
The file has links to information about the failures. 

[https://app.zenhub.com/files/242185115/27028145-33a7-4371-84e5-1df291faf1fe/download](https://app.zenhub.com/files/242185115/27028145-33a7-4371-84e5-1df291faf1fe/download)
