### ISSUE TITLE
Order children when returning OIDs from child_oids

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1192]
**Story**

We may want to use the Solr record to determine the order of OIDs in the object.  Right now the ParentObject does not seem to explicitly order the OIDs returned from the `child_oids` method, which is where the data in Solr originates.   

**Acceptance**
- [x] Order the returned child OIDs by `order`, then `oid` (in case two OIDs have the same `order` integer value)

**Comment by alishaevn** [comment]
`Branch: 1192_order_oid
Deployed:2021-04-07T19:15:24-04:00`

This branch is currently on test. Dylan and I bashed into the test ec2 container and ran the following commands:
- `po = ParentObject.first`
- `po.child_objects`

The resulting data does show child objects in order according to the `order` property on each child.

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/9540835b-70e5-4d2a-98e6-e7d28dafa6c5)
