### ISSUE TITLE
Open Universal Viewer to a specific page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1193]
**Story**

We'd like to be able to open Universal Viewer to a specific page/IIIF Canvas if a parameter (`child_oid`) is passed to the catalog's object page.   For instance,  this URL: `https://collections.library.yale.edu/catalog/2002046?child_oid=1006105` would cause the UV to open to page `16v`.

Universal viewer can be initialized with the focus on a specific IIIF Canvas by using an integer parameter indicating the canvas position within the sequence, see https://github.com/UniversalViewer/universalviewer/wiki/Embedding#data-canvasindex

After issue #1192 is complete and content reindexed in Solr, the position of the child OID in the Solr `child_oids_ssim` should give the correct position in the IIIF Manifest sequence. 

**Acceptance**
- [x] Passing the `child_oid` parameter (with a valid child OID of the parent) to an individual object's page will cause the Universal Viewer to display/focus on that image.
- [x] Passing an invalid OID (e.g., not a member of the parent) will result in UV opening normally (i.e., showing the first page of the object)

**Comment by alishaevn** [comment]
Dylan and I think the change that needs to happen is with the `manifest_url` in "app/views/catalog/_uv.html.erb" of the blacklight app.

**Comment by edejesusyale** [comment]
http://localhost:3000/catalog/2012036 defaults to this page:
![Screen Shot 2021-04-08 at 11.15.37 AM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/f6988147-5cef-4fef-b859-5d99d4f8d793)

http://localhost:3000/catalog/2012036?child_oid=1052762 gives
![Screen Shot 2021-04-08 at 11.14.52 AM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/642e64cb-1ba9-47eb-b77f-2a8ac2810622)

**Comment by edejesusyale** [comment]
## On test

http://collections-test.library.yale.edu/catalog/2 :![Screen Shot 2021-04-08 at 12.02.41 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/3245e846-e3e7-477f-87be-1dcc73c7cfaa)

## Child oid 10629366: ![Screen Shot 2021-04-08 at 12.01.27 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/cdd94440-2c94-4d90-944c-16ce537d7353)

## Using child_oid:
https://collections-test.library.yale.edu/catalog/2?child_oid=10629366:
![Screen Shot 2021-04-08 at 12.00.49 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/0d6b6172-a382-49f8-8c68-9b90e11c8da3)
