### ISSUE TITLE
Update the fixture data from the metadata cloud

### ISSUE THREAD

**Issue by geekscruff** [yalelibrary/YUL-DC#120]
**ACCEPTANCE**
From my development environment:

- [x] The 45 local fixtures have been updated from the metadata cloud and committed to github
- [x] Existing tests using the fixture data pass
- [x] I can trigger updates on demand via rake task or other process 

**DEVELOPMENT NOTES**

- [x] Add a new rake task that talks to the metadata cloud and updates the existing fixtures

**OTHER NOTES**

- See notes on #108 from Martin about basic auth and the metadata cloud
- Be aware that access to the cloud required being on the campus network (via VPN)
- This ticket is very much about being about to talk to the metadata cloud

See notes on #

**Comment by maxkadel** [comment]
There are now two rake tasks that fulfill the needs expressed in this ticket, both documented in the README. 
* One refreshes the fixture data from the metadata cloud
```bundle exec rake yale:refresh_fixture_data```
* The other indexes the existing fixture data to solr
```SOLR_CORE=blacklight-core bundle exec rake yale:index_fixture_data```
* There is also a rake task to clean out a solr core 
```SOLR_CORE=blacklight-core bundle exec rake yale:clean_solr```
