### ISSUE TITLE
SPIKE: Design session for TIFF download

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1200]
**Story**

As I user I'd like to be able to download the original source TIFF, for example to use in a publication.

**Acceptance**
- [ ] Discuss how to accomplish this given the system architecture.

**Comment by DraxIndustries79** [comment]
Meeting notes:
https://docs.google.com/document/d/1L96_Wz4qmkJ4gFBvi8jwkyU-sTBCJuz1N1UAQxD9XC8/edit

Next Steps:
- Rebecca and Mike will plan a meeting w/ Moira Fitzgerald
- First sprint tickets:  Design and Message Passing in iframe
- Set up a new/separate S3 bucket

**Comment by mikeapp** [comment]
Meeting planned.

**Comment by mikeapp** [comment]
See #1224 for S3 ticket.

**Comment by mikeapp** [comment]
#1225 for UV message passing
