### ISSUE TITLE
OpenGraph support

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1202]
**Story**

As a user, I'd like links to the site to display properly when pasted into Facebook.   Use OpenGraph to accomplish this: https://ogp.me

**Acceptance**
- Tags are present on an object page
  - [x] `og:title` contains the title
  - [x] `og:url` is the page URL
  - [x] `og:type` is `website`
  - [x] `og:description` contains the alternative title, creator, and publication date
  - [x] Image tags, if the object visibility is `Public`:
   - [x] `og:image` has a link to the thumbnail image JPEG
   - [x] `og:image:type` has the mime type `image/jpeg`
- [x] `og` namespaces defined in the `<html>` element (if required)

**Comment by FCRodriguez7** [comment]
Namespace: 
![Screen Shot 2021-04-23 at 1.37.20 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d37ca1a7-6c09-4652-a49d-03d17c86f8ae)

Object page tags:
![Screen Shot 2021-04-23 at 11.19.26 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6171ebdf-fded-4155-887e-85abd21ef87d)

**Comment by FCRodriguez7** [comment]
The PR for the feature: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/525

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.3

**Comment by mikeapp** [comment]
Looks good!
