### ISSUE TITLE
Schema.org metadata for object pages

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1203]
**Story**

https://schema.org allows the embedding of structured metadata in a web page for use by Google and other consumers.  We would like to include basic metadata in the page using this format.

**Acceptance**
- [x] schema.org metadata is embedded using JSON-LD, see https://developers.google.com/search/docs/guides/intro-structured-data for an example
- [x] All pages use the https://schema.org/CreativeWork type 
- Thing Fields  https://schema.org/Thing
  - `name` = title
  - `alternateName` = alternate title
  - `description` = description fields 
  - `image` = thumbnail URL, if public
  - `url` = page URL
- CreativeWork Fields  https://schema.org/CreativeWork 
  - [x] ~~`abstract`~~  (no mapping for now)
  - [x] `about` = subject (topic), subject (name), subject (place)
  - [x] `author` = creator
  - [x] `genre` = genre
  - [x] `materialExtent` = extent
  - [x] `temporal` = date
  - [x] `thumbnailUrl` = thumbnail URL, if public

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/513

**Comment by martinlovell** [comment]
Found an issue with Metadata for this URL using validation tool:
https://collections-test.library.yale.edu/catalog/2112327

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/c364189a-70a4-4917-8500-005d0ad1fdc4)

We may need an @type for the about entry so that place is a valid property.  "Thing" is the default type.

**Comment by mikeapp** [comment]
Yes, we should use `https://schema.org/CreativeWork`

**Comment by martinlovell** [comment]
We are for the main item, but I tried putting in "about" as an object with separate `subject (topic), subject (name), subject (place)` properties.  

Should "about" just be a comma separated string?

**Comment by martinlovell** [comment]
After looking more at the schema.org schema, it looks like the "about" property on CreativeWork should be of type "Thing"

Thing has a name and description, (etc. https://schema.org/Thing) but not a topic or place.
Maybe we should put subjectName_ssim into "name" and combine subjectTopic_ssim and subjectGeographic_ssim for "description."

Like this: https://github.com/yalelibrary/yul-dc-blacklight/pull/516

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/523

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.2
