### ISSUE TITLE
Indicate to Google that search result lists should not be indexed

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1204]
**Story**

As a user, I am confused by Google results that return search result listing from the site.   Search result lists should be excluded using techniques found here:  https://developers.google.com/search/docs/advanced/crawling/block-indexing  

For example, this result page for a facet search should not be indexed:
https://collections.library.yale.edu/catalog?f%5Blanguage_ssim%5D%5B%5D=English&q=&search_field=all_fields

Crawlers will still be able to find the individual object pages by using our sitemap.

**Acceptance**
- [x] Search result pages indicate to crawlers that they should not be indexed.

**Comment by FCRodriguez7** [comment]
Git Branch: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/506

**Comment by FCRodriguez7** [comment]
In blacklight release[ v1.41.10](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.41.10)

**Comment by FCRodriguez7** [comment]
Lakeisha and I verified on staging noindex:

![Screen Shot 2021-04-13 at 4.25.10 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/aaea0f05-6ac8-4a60-9dc1-72963b748dba)
