### ISSUE TITLE
Finish adding Ladybird to MODS fields

### ISSUE THREAD

**Issue by kcompsci** [yalelibrary/YUL-DC#1207]
Starting this card at fdid 67

**Comment by DraxIndustries79** [comment]
I believe that we're only indexing/publishing language names in English.  There's an attribute to indicate this in MODS, which we should include, see https://www.loc.gov/standards/mods/userguide/language.html

Looking at an example from the spec, we can only provide the `text` (second line), not the `code` (third line)
```
<language>
  <languageTerm type="text">French</languageTerm>
  <languageTerm type="code" authority="iso639-2b">fre</languageTerm>
</language>
```

**Comment by MaggieZhaoYale** [comment]
92:
`{"fdid": 92, "field": "SubjectGeographicCode", "enabled": true},`
solr_indexable.rb  to_solr does not have this

**Comment by MaggieZhaoYale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/505

**Comment by FCRodriguez7** [comment]
Git Branch: https://github.com/yalelibrary/yul-dc-blacklight/pull/505

**Comment by mikeapp** [comment]
We can move the language change into a new issue.

**Comment by FCRodriguez7** [comment]
In blacklight [release ](**url**)

**Comment by FCRodriguez7** [comment]
Testing the feature out: https://collections-staging.library.yale.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_mods
