### ISSUE TITLE
Private visibility setting not restricting access

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1208]
**Story**

In UAT, an object set to `Private` access remains accessible:

https://collections-uat.library.yale.edu/management/parent_objects/17342584

![Screen Shot 2021-04-07 at 1.23.28 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/e4226418-5cae-4152-ae09-61f7994628df)

https://collections-uat.library.yale.edu/catalog/17342584

![Screen Shot 2021-04-07 at 1.23.36 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/542c20a1-83ae-444b-a907-bd97ce17b1c4)

**Acceptance**
- [ ] Private access setting restricts access to the web view, images, manifest, and PDF.
- [ ] Check that we have sufficient tests for this.

**Comment by edejesusyale** [comment]
![Screen Shot 2021-04-07 at 2.08.56 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/9bd7f20e-f554-42cc-a018-5bf85b5f3123)

The issue seems to be that the job is not being started even though it is the only job.

**Comment by martinlovell** [comment]
Tried on test:  https://collections-test.library.yale.edu/catalog/2068607
Seems good there.

**Comment by martinlovell** [comment]
@edejesusyale is right.

To see the actual solr record, you have to click the link at the bottom of the parent object view page in management:
https://collections-uat.library.yale.edu/management/parent_objects/17342584/solr_document

(The solr document displayed on the show page is generated when the page is shown, so it is not necessarily the same in solr.)

**Comment by mikeapp** [comment]
@martinlovell  Do we need a new ticket to explore why the record is not being reindexed?

**Comment by martinlovell** [comment]
@mikeapp  It looks like it did setup the job, but that the workers are not running on UAT.
It would be good to investigate why the workers stop running sometimes (or are running but not picking up jobs).
