### ISSUE TITLE
SPIKE: Planning for full text search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1209]
**Story**

There is a requirement for the site to support full-text search.   In FindIt this is accomplished by indexing the individual children with their full-page transcription (a .txt file).  Fedora stores the text in a datastream.  We need to discuss how to handle this for the new system.

**Acceptance**
Conduct a planning session to discuss:
- [x] Ingest and file storage
- [x] Indexing
- [x] Search within an object (i.e., search of children)
- [x] IIIF Search API

**Comment by DraxIndustries79** [comment]
Notes:  https://docs.google.com/document/d/16XDR3PYgBejocpXXGMCgpDkLSOirkvIGWGDBGcO0oSs/edit

**Comment by mikeapp** [comment]
See #1223 for S3 setup.
