### ISSUE TITLE
Set up Test cluster @ DCE

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#121]
**ISSUE**
We need a testing (breakable) environment to deploy and test proposed code changes.

**ACCEPTANCE**
- [x] I can reach an image service at images-test.curationexperts.com/images/iiif
- [x] I can reach a manifest service at images-test.curationexperts.com/manifests
- [x] I can reach a blacklight service at collections-test.curationexperts.com/catalog
- [x] The environment can be rebuilt in under 2 hours if we intentionally (or inadvertently) conduct destructive testing against it

**Comment by dl-maura** [comment]
Working on documenting process
