### ISSUE TITLE
MODS link fields in OAI-PMH

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1212]
**Story**

MODS records vended from the legacy OAI-PMH provider contain a `<mods:location>` stanza that includes 
* the Voyager BIBID (if available) 
* `mods:url` elements for:
   * the "object in context" (i.e., the object page in the collections site)
   * the "preview" (thumbnail)
   * the "raw object" (quarter size) 

```
<mods:location>
                        <mods:holdingSimple>
                            <mods:copyInformation>
                                <mods:electronicLocator>7944291</mods:electronicLocator>
                            </mods:copyInformation>
                        </mods:holdingSimple>
                        <mods:url access="object in context" displayLabel="View information and digital image(s) in the Beinecke Library’s Digital Images Online database">http://brbl-dl.library.yale.edu/legacyhandler.php?fld=bib&amp;id=2107064</mods:url>
                        <mods:url access="preview">http://brbl-media.library.yale.edu/imagehandler.php?size=thumb&amp;object_id=2107064</mods:url>
                        <mods:url access="raw object">http://brbl-media.library.yale.edu/imagehandler.php?size=quarter&amp;object_id=2107064</mods:url>
</mods:location>
```

![Screen Shot 2021-04-12 at 11.58.40 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/009b589e-1a97-4cd9-869b-f1ed7826f217)

**Acceptance**
- [x] The `<mods:electronicLocator>` is provided with the Orbis BIBID, when it is available
- [ ] The `<mods:url>` elements are provided
   - [ ]  `<mods:url access="object in context" ...` links to the web page (edit for clarity: the object's page on collections.library.yale.edu)
     - [ ] Text of the link should be: "View information and digital image(s) in the Yale University Library Digital Collections site"
   - [ ] `<mods:url access="preview" ...`. links to the thumbnail for the first child (or representative image, if specified)
   - [ ] `<mods:url access="raw object" ... `  links to the full-size image    (i.e.,  IIIF   `... /{id}/full/full/0/default.jpg` )

**Comment by kcompsci** [comment]
Made progress and we were able to capture the BibId:
![image.png](https://images.zenhubusercontent.com/5e5d5c3556005302d06b5e8a/c3dbb07a-a549-4d4e-8c0d-245b3e24f825)

**Comment by FCRodriguez7** [comment]
The hyperlinks in general do not work.  We need more information about <mods:url access="object in context" ... links to the web page.

**Comment by mikeapp** [comment]
@FCRodriguez7 That should link to the object's page in Blacklight.

**Comment by kcompsci** [comment]
Here is an example of a uri being used int the MODS XML:
![image.png](https://images.zenhubusercontent.com/5e5d5c3556005302d06b5e8a/d5fda631-0767-4202-8b33-746a9598952f)

We have implemented the following:
![image.png](https://images.zenhubusercontent.com/5e5d5c3556005302d06b5e8a/47f35df1-3488-4fd5-8308-5560d9eec274)
All the examples are not clickable from the MODS XML

As for the Full size image, are we making assumptions that the '!200,200' part of the url that we should replace with 'full' will always be the same format (!<some number>,<some number>)?

**Comment by mikeapp** [comment]
The link should be to collections.library.yale.edu and not the BRBL-DL site that has been decommissioned.

**Comment by mikeapp** [comment]
For the IIIF URL you can link to (e.g.) `https://collections.library.yale.edu/iiiif/2/{child oid}/full/full/0/default.jpg`. e.g., https://collections.library.yale.edu/iiif/2/10590015/full/full/0/default.jpg

Use https for all links

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/508https://github.com/yalelibrary/yul-dc-blacklight/pull/508

**Comment by FCRodriguez7** [comment]
Review from the test environment: 

![Screen Shot 2021-04-16 at 10.02.16 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/adab1e5d-e9b0-4c9d-a806-4d9f528bbd58)

**Comment by mikeapp** [comment]
```
<mods:url access="object in context" displayLabel="View information and digital image(s) in the Beinecke Library’s Digital Images Online database" xlink:href="https://collections.library.yale.edu" ></mods:url>
```

This should be a link to the specific object, not the homepage, similar to how the legacy link has the object ID.

**Comment by FCRodriguez7** [comment]
When you wrote it should be a link to the specific object, not the homepage, similar to how the legacy link has the object ID. Are you referring to an idea similar to what's below?

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9ff83435-e875-48df-91ac-02e827a9da32)

**Comment by mikeapp** [comment]
It should link to the web page for the object, (e.g., https://collections.library.yale.edu/catalog/2004515 if the object was OID 2004515)
