### ISSUE TITLE
MODS language field

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1217]
**Story**

I believe that we're only indexing/publishing language names in English. There's an attribute to indicate this in MODS, which we should include, see https://www.loc.gov/standards/mods/userguide/language.html

Looking at an example from the spec, we can only provide the text (second line), not the code (third line)

```
<language>
  <languageTerm type="text">French</languageTerm>
  <languageTerm type="code" authority="iso639-2b">fre</languageTerm>
</language>
```

**Acceptance**
- [ ] Add `type="text"` to the languageTerm

**Comment by FCRodriguez7** [comment]
release v1.42.0
