### ISSUE TITLE
Link header to home page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1218]
**Story**

If you arrive on an object's page from an external link there's no obvious means to start a new search.

**Note:** clicking the "Yale University..." text in the blue YUL header does do this but isn't obvious.

**Acceptance**

- [x] Show the "Start Over" button even if you don't have an active search.   
- [x] Change the button's text to "NEW SEARCH" (match current case/formatting).  This is a global change, not conditional.

 ![Screen Shot 2021-04-13 at 1.47.46 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9061661d-e916-4a25-bd6e-3303193ebbee)to the site's homepage.

**Comment by mikeapp** [comment]
**Story**

If you arrive on an object's page from an external link there's no obvious means to start a new search.

**Note:** clicking the "Yale University..." text in the blue YUL header does do this but isn't obvious.

**Acceptance**

- [ ] Show the "Start Over" button even if you don't have an active search.   
- [ ] Link the "Digital Collections" header to the home page

 ![Screen Shot 2021-04-13 at 1.47.46 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9061661d-e916-4a25-bd6e-3303193ebbee)to the site's homepage.

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/512

# Expected behavior
- the button on a show page says "new search" whether there is an active search or not
- I tested this by changing the conditional statement in the code. unsure how to test this otherwise because I seem to always have a `current_search_session`

# Demo
![image](https://user-images.githubusercontent.com/29032869/114631929-62a33500-9c72-11eb-9e68-95498eb943b0.png)

**Comment by FCRodriguez7** [comment]
As in the previous design, the two buttons don't align anymore.   Should the two buttons be aligned?


| before | after |
|---|---|
|![Screen Shot 2021-04-16 at 9.21.44 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a67f19a0-fc12-4f6d-9bf3-7245f42e1280)|![Screen Shot 2021-04-16 at 9.20.49 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6b04422e-325c-4a93-a5d7-1996e2483c28)|

**Comment by DraxIndustries79** [comment]
We'll open a bug ticket to fix the alignment of the buttons.
