### ISSUE TITLE
Fix alignment of "New Search" button

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1220]
**Story**

The addition/update of the "New Search" button in https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1218 seems to have an alignment issue where it bumps "Back to Search Results" below instead of on the same line.  This seems to be happening at full screen, not just at reduced breakpoints.  Update this alignment to keep both buttons aligned side-by-side.
![a67f19a0-fc12-4f6d-9bf3-7245f42e1280.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/29a74a97-cebb-49bd-901a-810824eac61e)

**Acceptance**

- [x] "New Search" and "Back to Search Results" button are aligned side by side as in the "before" image.

**Comment by mikeapp** [comment]
BTW, the current code looks good for me in Safari when I have sufficient window width:

![Screen Shot 2021-04-18 at 3.01.44 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3828f6bf-12a7-4295-b650-1f701bc78b18)

**Comment by FCRodriguez7** [comment]
The buttons look great at sufficient window width. At the different breakpoints, the buttons are stacking when they should be linear.

**Comment by FCRodriguez7** [comment]
Git PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/517

**Comment by mikeapp** [comment]
Looks great across the various breakpoints!
