### ISSUE TITLE
Create S3 buckets per environment for downloads

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1224]
**Story**

Users will request files for download.  Decision from the spike ticket was to use S3 for delivery.   The plan is for all content in the bucket to be ephemeral so we will use a lifecycle rule to remove files after a period of time.

**Acceptance**

- Create S3 buckets for each environment
  - [x] yul-dc-download-test
  - [x] yul-dc-download-uat
  - [x] yul-dc-download-staging
  - [x] yul-dc-download-prod
  - [x] yul-dc-download-infra
  - [x] yul-dc-download-demo
- [x] Create a lifecycle rule for each bucket to delete its contents after 7 days.
- Only developer and system accounts should have access to these buckets.  We will probably generate time-limited signed URLs to allow user downloads. 

Note: May be best to pick up with #1223 at the same time.

**Comment by mlooney** [comment]
variables named:
    
    ACCESS_DOWNLOAD_BUCKET    and OCR_DOWNLOAD_BUCKET

**Comment by bobrice** [comment]
Complete
