### ISSUE TITLE
SPIKE: management interface UI improvements

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1226]
**Story**

We have not paid much attention to the management interface's UI and styling.   We'd like to improve this before we onboard Beinecke.

**Acceptance**

- [ ] Propose improvements to Parent Object display and edit pages (i.e., for individual objects)
- [ ] Propose additional changes that might help usability.

**Comment by martinlovell** [comment]
After writing some of the Find/Edit Objects documentation, it seems like it would be really nice to have something in the UI where you could just enter an OID and go directly to the edit page (if you have permission).  Whether is was a parent or child.

No need to filter a table or anything, just oid -> edit in one click.

**Comment by alishaevn** [comment]
# Previous PR's related to fonts:
- https://github.com/yalelibrary/yul-dc-blacklight/pull/325
- https://github.com/yalelibrary/yul-dc-blacklight/pull/405
- https://github.com/yalelibrary/yul-dc-blacklight/pull/455
- https://github.com/yalelibrary/yul-dc-blacklight/pull/459

**Comment by tmacmath** [comment]
I am working on getting the management UI installed.

**Comment by tmacmath** [comment]
Management UI is installed

**Comment by tmacmath** [comment]
Met with Martin and Alisha to discuss functionality and layout current app; discussed desired functionality and layout changes to enhance usability. Discussion notes are being compiled into a document. 
- Meet with Mike/Rebecca/DSU to obtain users' perspective (as opposed to developers' perspective)?

**Comment by tmacmath** [comment]
Toggle table column visibility: 

[https://api.jquerymobile.com/table-columntoggle/](https://api.jquerymobile.com/table-columntoggle/)

**Comment by tmacmath** [comment]
Hi all, 

Here's my vision for the Management UI Parent Objects page: 

[](https://xd.adobe.com/view/60accee6-cca4-4aa7-b731-01fefd804692-35ff/)

A few changes: 

- Actions links have been replaced with icons (View, Edit, Delete, etc.)
- Fewer columns appear in the table. If you want to select columns to view, you would be able to use the widget (tap the Columns button in the prototype and you can see how that would work - you can select or deselect the columns you'd like to show or hide). Tap the button again to close the widget. 

Please let me know what you thing, and if you have any further suggestions. 

Tracy

**Comment by tmacmath** [comment]
Adding this for reference: ![Screen Shot 2021-05-25 at 2.00.39 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/7f53274c-d97f-44bb-a547-27a6c7e47f39)
