### ISSUE TITLE
Create variables for new S3 buckets

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1228]
**Story**

#1223 and #1224 create new S3 buckets, we need the names of these to be accessible to the application via the parameter store.

**Acceptance**

- [x] SSM variables created for OCR & TIFF download buckets.
- [x] Values populated per environment 
- [ ] Local dev/camerata concerns?

**Comment by mlooney** [comment]
naming the variables OCR_DOWNLOAD_BUCKET & DOWNLOAD_BUCKET

**Comment by DraxIndustries79** [comment]
Need a new camerata
