### ISSUE TITLE
Update statement on harmful content

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1229]
**Story**
From Alison: As you may recall, and as Rebecca knows, the statement on potentially harmful context at the bottom of http://collections.library.yale.edu/ was pending a link to a full statement on the YUL website when we posted it. The text on the YUL website is now in place. Would it be possible to update the statement on http://collections.library.yale.edu/ accordingly?:

**Acceptance**

- [x] Statement on collections.library.yale.edu homepage is changed to:

Yale University Library’s collections contain historical and contemporary materials documenting human expression and lived experience. Content may include images or language that library users may find harmful, offensive, or inappropriate. Some of these words or images are now recognized as offensive and unacceptable; some may have been viewed as unacceptable when they were created. Yale University Library staff are engaged in addressing or contextualizing this content and language; for more information, see the Statement on Potentially Harmful Content.

- [x] The last five words "Statement...Content" should be a link to https://guides.library.yale.edu/about/statement-on-content

**Comment by FCRodriguez7** [comment]
The desired changed in local dev environment: 

![Screen Shot 2021-04-21 at 1.21.28 PM.png](https://images.zenhubusercontent.com/5e6013c
029e314c92afd4769/d25a7318-80de-4295-8174-2928b21312b7)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/520

**Comment by FCRodriguez7** [comment]
release v1.42.0
