### ISSUE TITLE
Provide TLS security for test cluster @ DCE

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#123]
**ISSUE**
For security reasons, we should use HTTPS encryption for all communications from clients to the system.

**ACCEPTANCE**
- [x] I can access the image services at https://images-test.curationexperts.com
- [x] I can access the discovery application at https:://collections-test.curationexperts.com
- [x] All unencrypted http requests are redirected to encrypted https endpoints
- [x] We have experimented using Amazon Certificate Manager to provide and manage the certificates (https://aws.amazon.com/certificate-manager/)

**Comment by mlooney** [comment]
there is no unencrypted http listener on the load balancer. we can add one, if required.

**Comment by dl-maura** [comment]
adding listener and hostname
