### ISSUE TITLE
Reload JSS Prod items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1230]
**Story**

We'd like to store the Preservica IDs for ingested content from Goobi.   The initial JSS items in PROD were loaded before we had code to do this.

**Acceptance**
- [x] Delete JSS items in production (approx. 40)
- [x] Reinigest Goobi packages for these items

**Comment by MaggieZhaoYale** [comment]
- Deleted 44 JSS items in production

- reingested Goobi package for 44 items.

- Checked the logs on yul-dc-pord management workers and confirmed that  all the parent id, preservica_id, child_preservica_id, parent_oid, child_oid, ingest_time were stored in the **preservica_ingest** table.

(preservica_child information was spread in the  logs of 7 different workers)
