### ISSUE TITLE
Goobi account for Mark C.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1232]
Create a Goobi account for Mark Custer in all environments.

**Comment by MaggieZhaoYale** [comment]
@mikeapp Will Mark be an Administration or super admin as Jon and Kevin? Thank you.

**Comment by kevinglick** [comment]
I'm not an expert on Goobi, but I think Mark will need to have super admin access.

**Comment by mikeapp** [comment]
That sounds good, at least for now.

**Comment by MaggieZhaoYale** [comment]
Added Mark as the super admin. He confirmed that he could login to Goobi.
