### ISSUE TITLE
Load 100 more JSS items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1234]
**Story**

The first batch of JSS items has loaded in production.  Let's load another ~100 items.

**Acceptance**
- [x] Load 100 JSS items into production
- [x] report to the team on any issues

**Comment by MaggieZhaoYale** [comment]
Imported 31 items into Goobi, 23 were ingested into the production.
Bib 4419621 with 8 volumes were not able to imported into Goobi.
It is  not in the Orbis. Got "no longer held by the Yale Library." 
https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=441962

**Comment by mikeapp** [comment]
Correction: https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=4419621

**Comment by mikeapp** [comment]
This looks like a case for an e-variant record, since we have the images.

**Comment by mikeapp** [comment]
I think we can go ahead and ingest more objects to see whether this is a one-off occurrence.  

If we see more missing Voyager records we might want to audit the entire set of JSS BIB/Barcodes per #1236

**Comment by MaggieZhaoYale** [comment]
Ingested 64 more.
https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=4419621 now is https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=11747720
(based on the barcode search, all 8 barcodes are attached to 11747720)
There are two more bibs that are no longer in Orbis. 

- https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=702016, searching by the barcode, the new bib is: https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=11855051

- https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=2243640, searching by the barcode, the new bib is: https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=11747720

**Comment by MaggieZhaoYale** [comment]
25 bibs are not in Voyager. 
Here is the list of the bibs and the alternative bibs may replace them[https://app.zenhub.com/files/242185115/ea7166f9-11fd-4567-b6f4-0a7c11a6ae5f/download](https://app.zenhub.com/files/242185115/ea7166f9-11fd-4567-b6f4-0a7c11a6ae5f/download)
