### ISSUE TITLE
Add log entry on Manifest changes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1238]
**Story**

For each Parent Object, we need to track changes to its associated IIIF Manifest.   This data will be used to generate an Activity Stream as described in the  IIIF Change Discovery API https://iiif.io/api/discovery/   Essentially this requires a log of CRUD actions on the Manifest, presented in chronological order.

Note: we'll eventually decide where/how to generate the ActivityStreams, but that's for another ticket.  This may involve creating a database table to log this data, or sending it to another system.

**Acceptance**
-  Create a log entry for each of the events below.  
   - [x] `Create` when a Manifest is first published, or published from a deleted or non-accessible  (i.e., not Public or YCO)  state
   - [x] `Update` when a Manifest is updated
      - [x] Changes that do not change the contents of the Manifest should not create an Update event.   (Store manifest checksum on the parent object and use that for comparison.)
   - [x] `Delete` when a Manifest is deleted or the Parent is made inaccessible (i.e., not Public or YCO)
   - [x] A timestamp is logged for each event.

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/603
