### ISSUE TITLE
SPIKE: Design for ActivityStreams

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1242]
**Story**

We need to decide how to handle publication of activity streams for IIIF as well as other data not related to digital collections.

**Can we use Thursday for this?**

**Acceptance**
- [x] Meet and discuss

**Comment by DraxIndustries79** [comment]
[Notes from meeting.](https://docs.google.com/document/d/15Um6SwwABuzlNVqK3EtTpZudXwF49atHtlUHgLrV5KU/edit)

Next Steps:

- Keep thinking about this
- Plan to continue discussion in the next week to plan tickets
- Yue has been involved, may be worth looping in
- There will be more potential ActivityStreams in the future, so clustering them may have some value
