### ISSUE TITLE
Test OpenGraph on Facebook

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1243]
**Story**

We've added OpenGraph support in #1202.   We should see what it looks like in practice.

**Accpetance**

- [ ] Add item link in Facebook, etc. and see what the snippet looks like.
- [ ] Screen capture it?

**Comment by alishaevn** [comment]
https://images.zenhubusercontent.com/242185115/87f20054-8804-45b9-995b-95b5e9ee9f0d/1243.mp4

@mikeapp is this what you were trying to verify?

**Comment by mikeapp** [comment]
Yes, but I think this needs the new code live in production after tomorrow’s release for the `og:` meta tags to be present.

**Comment by mikeapp** [comment]
https://www.opengraph.xyz/url/https:%2F%2Fcollections.library.yale.edu%2Fcatalog%2F2004567/

![Screen Shot 2021-04-28 at 1.49.56 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/44bd2648-6169-49d4-be57-9d93246b6a50)

**Comment by mikeapp** [comment]
Image is pixelated, we might want to increase the resolution.
