### ISSUE TITLE
Document Management UI features for BRBL DSU

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1245]
DSU Staff needs documentation of management interface.  We need step by step instructions for the following activities:

**Acceptance**

- Find/Edit objects
  - [x] Searching for objects
  - [x] Editing a parent
  - [x] Editing a child
- Reassociation workflow
   - [x] Export Child OIDs
   - [x] Upload revised versions
- [ ] Spreadsheet to adjust captions and labels

-----
Possible Reviewers
- [ ] Rebecca Hirsch
- [ ] Kevin Glick 
- [ ] Jonathan Manton 
- [ ] Kevin (from Notch8)
- [ ] Alisha Evans

**Comment by martinlovell** [comment]
I can do the reassociation workflow if now one has started: https://docs.google.com/document/d/1ysmuN9rqSszNwz527phkADAhZs-1j7qiG_P96dXRlr4/edit
