### ISSUE TITLE
Show Page Toolbar needs alignment

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1247]
The toolbar alignment on the show page needs rework. 

Acceptance: 
- [ ] correct the alignment only at all resolution viewing points.

----

Current Design Implementation
![Screen Shot 2021-04-21 at 9.29.18 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b038010d-0c8f-416b-8475-79a0a112e05d)

Desired Design Implementation
  ![Screen Shot 2021-04-26 at 2.40.47 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d1487bd8-3c41-40d7-b694-6c92d68ede19)

**Comment by FCRodriguez7** [comment]
![ShowPage Toolbar Alignment.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/fe2189f9-9024-4bf5-a2ea-49436905cb77)

**Comment by FCRodriguez7** [comment]
PR branch https://github.com/yalelibrary/yul-dc-blacklight.git

**Comment by DraxIndustries79** [comment]
@FCRodriguez7 is this a bug or pointable work?  I feel like pointable...if you agree can you throw some points on the estimate?  If not, no worries, I defer to your assessment thanks!

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.4

**Comment by FCRodriguez7** [comment]
v1.42.5
