### ISSUE TITLE
Add confirmation message for global Goobi button

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1248]
**Story**

![Screen Shot 2021-04-28 at 11.29.29 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/93100440-4b32-40f8-b686-43008602fc3f)

**Acceptance**

- [ ] Add a confirmation dialog or intermediate screen for each of the two functions with the text:  "Are you sure you want to proceed? This action will process Goobi objects for the entire system."

**Optional**
- [ ] The Goobi button disappears until all `.done` files are written.  Look for directory scan job.

**Comment by MaggieZhaoYale** [comment]
duplicate with #1364
