### ISSUE TITLE
Clean up public endpoints to SpinUp cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#125]
**ISSUE**
Since we're not going to be moving forward with SpinUp for the time being, we should decommission the public endpoints.

**ACCEPTANCE**
Remove the configuration & and any registrations for 
- [x] The blacklight application at https://dl-test.library.yale.edu/
- [x] The manifest service at https://iiif-test.library.yale.edu/manifests
- [x] The image service at https://iiif-test.library.yale.edu/images
- [x] Spinup containers are deleted

**Comment by dl-maura** [comment]
Check with Rick

**Comment by ra359** [comment]
Tracking requests in ServiceNow tkt INC1759061

**Comment by ra359** [comment]
The following DNS entries were deleted via INC1759134 :

dl-test.library.yale.edu
iiif-manifests-test.library.yale.edu
iiif-images-test.library.yale.edu
