### ISSUE TITLE
Update Demo to latest versions

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1255]
**Story**

We will want to use the Demo cluster to test full text search.   It should be updated to the latest version.

**Acceptance**
- Check the applications in the Demo environment and confirm the latest versions are in use:
  - [x] Management
  - [x] Blacklight
  - [x] Image server
  - [x] Solr
  - [x] Postgres
- [x] Confirm Metadata Cloud API version is latest
- [x] Refresh metadata

**Comment by FCRodriguez7** [comment]
The current version of 
- Blacklight v1.39.3
- management v2.27.3
