### ISSUE TITLE
Index full text into Solr

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1259]
**Story**

In order to allow full text searches we need to index the page-level OCR files under the parent object.

**Acceptance**
- [x] When the object is (re)indexed, check whether the full text is available for an object.  
If it is, then:
-  For each child, read the full text from the OCR S3 bucket for the current environment
   - [x] Add each OID's text to an array
   - [x] if OCR is missing for any child, throw an exception
- Index the array of full text values into a new SOLR field `fulltext_tsim` (verify this isn't already in use)

**Comment by martinlovell** [comment]
Sample solr record with full text: https://collections-test.library.yale.edu/management/parent_objects/2007727/solr_document

**Comment by FCRodriguez7** [comment]
Released management v2.36.7
