### ISSUE TITLE
Draft DevOps diagram of the Staging cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#126]
**ISSUE**
We need a view of the ecosystem that documents the information DevOps needs to successfully build and support the new application.   We have a number of existing drawings and documentation, along with a reference implementation in DCE's AWS account.  

**RESOURCES**
High-Level Block Diagram: [PNG](https://drive.google.com/file/d/1BWYY5NwehNTLtCGoTbrv2Vghcv8HDPK0/view?usp=sharing) & [Draw.io](https://drive.google.com/file/d/1fbSQZVn9RP752AVJ2iM1apGZEbqOiYaq/view?usp=sharing)
ECS Infrastruture Diagram [PNG] & [LucidChart](https://app.lucidchart.com/documents/edit/559e21eb-881b-4b97-9908-c7c30a68710c/0_0)
[URI Strategy](https://docs.google.com/presentation/d/1p58-Prs_ZQAqAj73uYvt8YIRhl02edc-ivNUkj8RtY4/edit#slide=id.g722593bcb2_1_0)
[Deployment Pipeline](https://docs.google.com/drawings/d/17v70XScfte8nKU8Gz3_h-0dlgkFBz9nxgB-YHyDOnv0/edit)
[Docker-Compose Script](https://github.com/yalelibrary/yul-dc-camerata) 

**ACCEPTANCE**
Based on the various resources available, 
- [x] We have a DevOps focused draft view of the infrastructure

**Comment by dl-maura** [comment]
Maura will set up a one-hour meeting
