### ISSUE TITLE
Document Management Interface: Create Videos

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1262]
DSU Staff needs documentation of management interface.  Following the creation of text documentation, we need demo videos for the following activities:

**Acceptance**

- Find/Edit objects
  - [x] Searching for objects
  - [x] Editing a parent
  - [x] Editing a child
- Reassociation workflow
   - [x] Export Child OIDs
   - [x] Upload revised versions
- [ ] Spreadsheet to adjust captions and labels

-----
Possible Reviewers
- [x] Rebecca Hirsch
- [ ] Kevin Glick 
- [ ] Jonathan Manton 
- [ ] Kevin (from Notch8)
- [ ] Alisha Evans

**Comment by FCRodriguez7** [comment]
Draft video: working on cutting the right viewing option.  Please comment below:

**Option 1**
https://images.zenhubusercontent.com/242185115/d9cef980-c780-4de2-9e88-9d8035c4fe0b/editingdigitialobject___opt1.mov

**Option 2**
![EditingDigitialObjectOpt2.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/40b13a44-7efa-4555-ad05-83d0b56b3f31)

**Option 3**
![EditingDigitialObjectOpt3.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b23080bf-71ac-4e9a-a749-6e8ee75dc764)

**Comment by mikeapp** [comment]
Option 3

**Comment by FCRodriguez7** [comment]
https://images.zenhubusercontent.com/242185115/e0af7b89-9eaf-4a89-8d57-83230a0b78a8/dctrainingfindedit___sd_480p.mov

**Comment by mikeapp** [comment]
Quality looks good on the file in Box.

**Comment by mikeapp** [comment]
Link to Box folder posted in Slack.
