### ISSUE TITLE
Child Object 30523670 of a JSS object 30523162 failed to convert PTIFF due to Conversion script exited with error code 1

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1266]
- [x] find the tiff on pairtree

- [x] find the original jpg or pdf

- [x] convert pdf to ptiff  (no grayya)

- [x] upload tiff to pairtree

- [x] recreate child ptiff

**Comment by mlooney** [comment]
resolved
