### ISSUE TITLE
batch process/ QueueAdapters::DelayedJobAdapter::JobWrapper execution expired (Delayed::Worker.max_run_time is only 3600 seconds)

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1268]
Description: Tried "Start Goobi Scan" last night and this morning in collection prod to ingest packages of JSS objects and did not see any object created.
MetsDirectoryScanJob has error: 
`Execution expired (Delayed::Worker.max_run_time is only 3600 seconds)`
I tried the Goobi scan in Collection-test and it worked as expected. 
(Maybe check NFS Share. Usually the tasks should not take that long)

**Comment by oraposa** [comment]
@mlooney please grab @oraposa when you pick this one up. thanks.
