### ISSUE TITLE
Prevent search engines from indexing the test & demo blacklight sites

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#127]
**ISSUE**
We want to avoid having search engines index test and staging sites.

**REFERENCES**
[How to keep your staging or development site out of the index](https://searchengineland.com/how-to-keep-staging-development-site-index-286987)
[Decision document](https://docs.google.com/document/d/1NIMfqY94v2Uot_btoB0D627G7hWy9JlBzplb3NnKWao/edit?usp=sharing)

**ACCEPTANCE**
- [x] We have selected a strategy to prevent web-crawlers from indexing publicly accessible production-like (but non-production) sites.
- [x] We have implemented the strategy for the DCE test site
- [ ] We have implemented the strategy for the DCE demo site
- [ ] We have implemented the strategy for the Yale test site

**Comment by dl-maura** [comment]
Maura will set up decision meeting for a week out.

**Comment by fnibbit** [comment]
http basic auth strategy selected.
