### ISSUE TITLE
Focused searches return incorrect results

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1275]
**Story**

Searches on Subject appears to return too many results.   I can return results for a match on Call Number using a Subject search:
https://collections.library.yale.edu/catalog?search_field=subjectName_ssim&q=landberg. Results like this one seem only to match the record's Call Number:
![Screen Shot 2021-05-07 at 7.19.53 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/28b291c9-bd50-4dae-8583-18ce8e43b27d)*

**Acceptance**
- [ ] Identify which specific searches exhibit this issue (is it only Subject?)
- [ ] Restrict the searches to the correct field

**Comment by edejesusyale** [comment]
It is only an issue with basic searches on Subject field because the field was put into the `pf` field  (which is for boosting) instead of `qf` which limits the search to only that field.

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/536
