### ISSUE TITLE
METS Import should import caption data

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1276]
**Story**

Imports from METS files should retrieve and store the caption data found in the METS.   The initial imports from Beinecke have turned encountered this problem.   We should be seeing the captions in the management UI and the IIIF Manifest:

![Screen Shot 2021-05-07 at 5.06.18 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/8e0f0b98-4764-4cb1-bb71-2cb141fae10d)

**Acceptance**

- [x] Caption data from the METS file for each child object should be stored in the database
- [x] The caption data should be included in the Canvas-level `metadata` in the IIIF Manifest.  (This may be done?)

**Comment by MaggieZhaoYale** [comment]
Tested in the collection-test, the other fields in the logical part such as DMDID, id etc should be deleted

**Comment by MaggieZhaoYale** [comment]
Example of Child Caption:
https://collections-test.library.yale.edu/management/parent_objects/800013363

**Comment by mikeapp** [comment]
@MaggieZhaoYale I'll approve this based on the object in test.
