### ISSUE TITLE
Dependabot: Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1277]
**Story**

We have more alerts to resolve

**Acceptance**

- [ ] Apply PR
- [x] Review alerts w PRs.
- [ ] Review alerts w/o PRs.

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/cddbf04c-f22e-45fb-810d-efeb06352cb2)

**Comment by FCRodriguez7** [comment]
v2.36.5

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: frederick rodriguez <frederick.rodriguez@yale.edu>

# PR
https://github.com/yalelibrary/yul-dc-management/pull/613

# Expected behavior
- the dependabot alert for actionpack should be resolved

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/614

# Expected behavior
- the dependabot alert for postcss should be resolved

**Comment by FCRodriguez7** [comment]
Released management v2.36.7

**Comment by FCRodriguez7** [comment]
Postcss dependency
https://github.com/yalelibrary/yul-dc-management/pull/619

**Comment by FCRodriguez7** [comment]
There was still an alert message for: 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6451bef9-c871-47ba-99cc-c5dd9f6e1b68)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/621

**Comment by alishaevn** [comment]
another bot pr from today: https://github.com/yalelibrary/yul-dc-management/pull/623

**Comment by FCRodriguez7** [comment]
management release v2.37.0
