### ISSUE TITLE
Dependabot: Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1278]
**Story**

We have more alerts!

**Acceptance**
- [ ] Review alerts w PRs.
- [ ] Review alerts w/o PRs.

![Screen Shot 2021-05-11 at 2.29.16 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/cd0d1abb-d87c-4b9b-af8e-3a09a183a2db)

**Comment by FCRodriguez7** [comment]
Upgrade postcss:
https://github.com/yalelibrary/yul-dc-blacklight/pull/540

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/549

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.10
