### ISSUE TITLE
Display a facet for work "format" (Type of Resource)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#128]
**STORY**
As a musicologist, I would like to be able to narrow my search by the type of material, so that I only see musical scores that match my search criteria.

**DETAILS**
The ladybird source metadata contains a field called `format` which represents a small controlled vocabulary for the high-level format of the work.  In the current BRBL DL, this facet is called "Type of Resource".   We will need to update the current work fixtures to include the format field from ladybird.

**ACCEPTANCE**
- [ ] I can facet my search results by `format` (don't worry about renaming the field label for now)
- [ ] With the sample data, format includes (but is not limited to) the values 'text' and 'still image'

**EXAMPLE FROM CURRENT DL**
![image](https://user-images.githubusercontent.com/3064318/81711949-bc372a00-9439-11ea-9bb9-f11ccbc34121.png)

**Comment by FCRodriguez7** [comment]
Don't need moving image, sound recording-nonmusical, and sound recording.

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/35

**Comment by FCRodriguez7** [comment]
Bess' example https://github.com/emory-libraries/dlp-lux/tree/master/spec/system Maybe look at these examples?

**Comment by FCRodriguez7** [comment]
The test was completed and pushed to the branch during the week.
