### ISSUE TITLE
[Valid] Summary indexed but not displayed?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1280]
**Story**

Searching for `Dogg` turns up https://collections.library.yale.edu/catalog/10033744

It has a summary in Voyager that includes that word.   I'm guessing this data is also in Ladybird but whatever field it is matching on in the system is not displayed:

Manuscript on paper, in a single hand, of four short tales. The first, titled "The Tameing a Shrew," describes a man's successful intimidation of his new wife, "a Cross grained Jade." "The Dogg of Doggs" is an unfinished tale which concerns a farmer's decision to bury his dog in the church graveyard, for which "most abominable sacralidge" he is brought to trial. The third piece, "Tom Dainth," follows the protagonist's extraordinary luck, both good and bad, in hunting; and the final piece, "Jack Sholdering A Lye," follows the attempts of a Scottish gentleman and his servant to woo a rich widow.

**Story**
- [ ] Decide how to handle this

**Comment by K8Sewell** [comment]
# Follow Up Questions
* Do we want to display the summary on the show page?
* Are there any other fields that are indexed that should be shown on the show page?

**Comment by mikeapp** [comment]
The data does not appear to be in the system.  @motropuk suggests it may be matching on a child label.  Should close.
