### ISSUE TITLE
SPIKE: Test IIIF Search gem [DO NOT MERGE]

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1281]
**Story**

Boston Public Library has created an IIIF Search gem:  https://github.com/boston-library/blacklight_iiif_search
The purpose of this spike is to create a branch that will allow us to test it locally.

**Acceptance**
This is a best guess at what's required.

- [x] Create a branch for this work
- [ ] Install the gem (version 2)
- Create a rake task to generate test data.
   - [x] Use a test object that has text available for its children
   - [x] For each child create a Solr record with the following fields:
       `id` : child's oid,  
       `parent_ssi` : child's parent OID, 
       `child_fulltext_tesim`: contents of the child's full text `.txt` feel
- [x] Configure the gem to use these fields, per https://github.com/boston-library/blacklight_iiif_search#installation
    - [x] Do not configure the autosuggest information, we won't use it.
- [x] Test the endpoint manually per https://github.com/boston-library/blacklight_iiif_search#basic-usage
    - [x] Capture the JSON response and attach it to this issue.
- [ ] Report to the team on success or blockers

**Comment by martinlovell** [comment]
```json
{
  "@context": [
    "http://iiif.io/api/presentation/2/context.json",
    "http://iiif.io/api/search/1/context.json"
  ],
  "@id": "http://localhost:3000/catalog/2005512/iiif_search?q=document",
  "@type": "sc:AnnotationList",
  "resources": [
    {
      "@id": "http://localhost/manifests/oid/2005512/canvas/1030368/image/1",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "This is a test.\n\nThis is the OCR text for 1030368.\n\nSearch for some text to see if this document"
      },
      "on": "http://localhost/manifests/oid/2005512/canvas/1030368#xywh=0,0,0,0"
    }
  ],
  "hits": [
    {
      "@type": "search:Hit",
      "annotations": [
        "http://localhost/manifests/oid/2005512/canvas/1030368/image/1"
      ]
    }
  ],
  "within": {
    "@type": "sc:Layer",
    "total": 1
  },
  "startIndex": 0
}
```

**Comment by mikeapp** [comment]
I have a question about the annotation `@id`s above, they should not match the Canvas ids

**Comment by martinlovell** [comment]
This is the response leaving the annotation id as implemented in the Gem and overriding the canvas used on the annotation:
```json
{
  "@context": [
    "http://iiif.io/api/presentation/2/context.json",
    "http://iiif.io/api/search/1/context.json"
  ],
  "@id": "http://localhost:3000/catalog/2005512/iiif_search?q=test",
  "@type": "sc:AnnotationList",
  "resources": [
    {
      "@id": "http://localhost:3000/catalog/2005512/canvas/1032318/annotation/0",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "Test OCR text\n"
      },
      "on": "http://localhost/manifests/oid/2005512/canvas/1032318#xywh=0,0,0,0"
    },
    {
      "@id": "http://localhost:3000/catalog/2005512/canvas/1030368/annotation/0",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "This is a test.\n\nThis is the OCR text for 1030368.\n\nSearch for some text to see if this document"
      },
      "on": "http://localhost/manifests/oid/2005512/canvas/1030368#xywh=0,0,0,0"
    }
  ],
  "hits": [
    {
      "@type": "search:Hit",
      "annotations": [
        "http://localhost:3000/catalog/2005512/canvas/1032318/annotation/0"
      ]
    },
    {
      "@type": "search:Hit",
      "annotations": [
        "http://localhost:3000/catalog/2005512/canvas/1030368/annotation/0"
      ]
    }
  ],
  "within": {
    "@type": "sc:Layer",
    "total": 2
  },
  "startIndex": 0
}
```

See:
https://github.com/boston-library/blacklight_iiif_search/blob/master/app/models/concerns/blacklight_iiif_search/annotation_behavior.rb
vs
https://github.com/yalelibrary/yul-dc-blacklight/blob/1283-iiif-search-api-gem-implementation/app/models/concerns/blacklight_iiif_search/annotation_behavior.rb

**Comment by mikeapp** [comment]
That looks good, their method uses an id that seems to come from Solr (or the ordering of results):
`#{controller.solr_document_url(parent_document[:id])}/canvas/#{document[:id]}/annotation/#{hl_index}`

**Comment by martinlovell** [comment]
Is this okay to merge with the full text branch?

**Comment by mikeapp** [comment]
Yes, go ahead and then put this issue in the UAT column.
