### ISSUE TITLE
SPIKE: Investigate access control for IIIF Search API gem

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1283]
**Story**

We are investigating use of the Boston Public Library's IIIF Search API gem.  See #1281 for a link.    We'd like to know how difficult it will be to restrict access to the API for objects with Yale Community Only access, and to block all searches for any parent that is missing or has non-Public/YCO access.

Note that we could use the Nginx approach (as with manifests/images) but for this ticket I'd like to consider how we'd use application code to do this, or a modification to the gem.

**Acceptance**
- [ ] Review the gem and suggest an approach to access control.  Provide a rough estimate of level of effort.

**Comment by martinlovell** [comment]
We can override iiif_search and iiif_suggest in CatalogController, and pass to "super" if the user has access to the document.

The gem uses a module to add iiif_search and iiif_suggest to CatalogController.
