### ISSUE TITLE
Add Child Caption to PDF

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1285]
**Story**
Add Child Caption to PDF

**Acceptance**
What's the definition of "done" for this ticket? 
- [x] Caption displays in PDF if it presents

![Screen Shot 2021-05-12 at 10.01.17 AM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/e7c7870e-a84d-44ea-a913-d96f6ab12611)

**Comment by martinlovell** [comment]
Example on test: https://collections-test.library.yale.edu/pdfs/17298305.pdf

**Comment by FCRodriguez7** [comment]
Released management v2.36.7
