### ISSUE TITLE
Add Label field to Child edit/index page

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1286]
**Story**
Add Child Label to Child edit, index page

**Acceptance**
What's the definition of "done" for this ticket? 
- [x] Label field display and can be edited/saved

**Comment by MaggieZhaoYale** [comment]
Example: https://collections-test.library.yale.edu/management/child_objects/800039391

**Comment by FCRodriguez7** [comment]
Released management v2.36.7
