### ISSUE TITLE
JSS image failure

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1287]
![Screen Shot 2021-05-12 at 1.53.58 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/affe5402-0a3b-4319-9930-0f52ba79db1c)

**Comment by MaggieZhaoYale** [comment]
It could be the graya image issue which caused the image failed of Child object 3023670.

**Comment by mlooney** [comment]
The file turned out to be empty in the pair tree. I exported it from collections as pdf and converted it to 300dpi tiff, and put the result into the pair tree. should process now.


```
app@ip-10-5-68-41:~/webapp$ ls -l /data/09/96/30/60/01/96/30600196.tif
-rw-r--r-- 1 app app 11552278 May 12 21:37 /data/09/96/30/60/01/96/30600196.tif

```

**Comment by MaggieZhaoYale** [comment]
Thank you @mlooney. The child oid is 30600916, not 30600196. I will recreate child ptiff after you put it in the pair tree.

**Comment by MaggieZhaoYale** [comment]
Recreated ptiff for child 30600916. Looks great. Thank you @mlooney
