### ISSUE TITLE
JSS child creation failure

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1288]
**Story**
Multiple jobs on 5/12 have this error:

https://collections.library.yale.edu/management/batch_processes/1290/parent_objects/30609849
![Screen Shot 2021-05-12 at 1.57.56 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/96fec697-96b3-45bb-968f-e274f397d6ec)

**Comment by mikeapp** [comment]
Looking at Batch 1283, the parent object has the correct number of children (1022, which matches the METS file):
https://collections.library.yale.edu/management/parent_objects/30603722

It looks like the batch processed the first 409 children correctly, the rest do not have height/width values:
![Screen Shot 2021-05-12 at 2.30.37 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f460fb5d-7496-4d13-a9a7-5ef3e84ac855)

**Comment by mikeapp** [comment]
It is possible that these errors were caused by the deployment this morning around 11am.  It would have interrupted the jobs.   The time looks about right.

**Comment by MaggieZhaoYale** [comment]
I will delete the five parents, and reprocess them.

**Comment by mikeapp** [comment]
I think there might be more than five?  On the second page of batch results I see these:

https://collections.library.yale.edu/management/batch_processes/1270/parent_objects/30600497
https://collections.library.yale.edu/management/batch_processes/1273/parent_objects/30601544
https://collections.library.yale.edu/management/batch_processes/1275/parent_objects/30602070
https://collections.library.yale.edu/management/batch_processes/1283/parent_objects/30603722
https://collections.library.yale.edu/management/batch_processes/1284/parent_objects/30604745
https://collections.library.yale.edu/management/batch_processes/1288/parent_objects/30607871

**Comment by MaggieZhaoYale** [comment]
Thank you. Yes, there are 13 failed objects.

**Comment by MaggieZhaoYale** [comment]
Reprocessed them and all completed without failure except one image (30600916) ptiff convert failed https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1287
