### ISSUE TITLE
Add full text search option to Blacklight simple and advanced search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1290]
**Story**

As a user I'd like to be able to search the full text of items in the system, both in the simple search interface drop down:

![Screen Shot 2021-05-13 at 9.56.18 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/e838bd28-99ed-4f62-80ca-2fca63b259ea)

and in advanced search.

**Acceptance**
- [x] a "FULL TEXT" search option appears as the last item in the drop-down for simple searches
- [x] a "Full Text" label and input appears in advanced search, between the Genre and Parent OID search fields
- [x] both of these search the full text of the parents
- [x] search results list return highlighted snippets, like for other fields (see picture below):
     -  [x] label is "Full Text:"
     -  [x] displayed beneath the other metadata fields
     -  [x] for the first five matches
- [x] Check and report back about the Blacklight's SOLR query.  Does the full contents of the fulltext_tsim field get returned with Show/Index/OAI List/OAI GetRecord, etc?  See #1289

 ![Screen Shot 2021-05-13 at 10.05.18 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/4b571aaa-7172-41ba-93e1-9e2695fd350e)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/542

**Comment by martinlovell** [comment]
It does look like fulltext_tsim is being returned in the record for at least some BL queries.

**Comment by martinlovell** [comment]
It may not be possible to exclude a field using "fl" or any other parameter.
It may be that the only option is to add the fl parameter in blacklight, or in SOLR config for the query handler.
https://issues.apache.org/jira/browse/SOLR-3191

Blacklight does not pass in fl, so by default fl=*.

**Comment by mikeapp** [comment]
Split the ticket or rewrite the scope of #1289 if that will let you close out this ticket.   It seems like that ticket could be "implement explicit fl" is enough work to merit its own ticket.

**Comment by martinlovell** [comment]
Index page and OAI Get and List can be handled by adding `fl` in search builder.
`fl` must contain timestamp for OAI to work properly.

For Show page and Access checks handled through

**Comment by alishaevn** [comment]
verified this on test

| advanced | basic |
| --- | --- |
| ![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/756510c4-50ba-47c4-85e4-755f93b16fcb) | ![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/c326129b-5101-40ef-99c5-e134c2604d5e) |
| https://collections-test.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&creator_tesim=&title_tesim=&callNumber_tesim=&date_fields=&subject_fields=&genre_fields=&fulltext_tsim_advanced=like+directness+of++Willie&oid_ssi=&child_oids_ssim=&commit=SEARCH | https://collections-test.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&all_fields_advanced=&creator_tesim=&title_tesim=&callNumber_tesim=&date_fields=&subject_fields=&genre_fields=&oid_ssi=&search_field=fulltext_tsim&q=other+pictures+of+Willie%29|
