### ISSUE TITLE
Speed up mets directory scan

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1292]
As a user, I would like the mets directory scan to run faster so that new mets files are processed more quickly.

- [ ] Directory scan completes in a less than 15 minutes to pick up all the new jobs.  (Ingest jobs may take longer to complete.)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/618

**Comment by mikeapp** [comment]
When I run this in UAT I don't see anything running in the delayed jobs dashboard.  Is it completing too quickly?
