### ISSUE TITLE
Re-ingest Beinecke items after caption fix is deployed

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1296]
**Story**

Beinecke items from Goobi were deleted from production due to missing captions.  After the caption fix is deployed, re-ingest those Goobi packages.

**Acceptance**
- [ ] Beinecke items re-ingested
- [ ] Captions appear on items that have them

**Comment by MaggieZhaoYale** [comment]
Need to confirm with Rebecca Aldi: Only 4 objects  imported on May 7th have Caption.
30597978
30598035
30598201
30598849
