### ISSUE TITLE
Display 'format' metadata on the item's show page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#130]
**STORY**
As a scholar, I would like to be able to distinguish between maps that are illustrations in books versus printed works that are published as maps.

**DETAILS**
The ladybird source metadata contains a field called `format` which represents a small controlled vocabulary for the high-level format of the work.  In the current BRBL DL, this facet is called "Type of Resource".   We will need to update the current work fixtures to include the format field from ladybird.

**ACCEPTANCE**
- [x] When I'm viewing the item page for a work, it includes the `format` field (for now, leave the field table matching the source data from LadyBird)
- [x] With the sample data, format includes (but is not limited to) the values 'text' and 'cartographic'

**EXAMPLE FROM CURRENT DL**
https://brbl-dl.library.yale.edu/vufind/Record/4163866?image_id=16595618

**Comment by edejesusyale** [comment]
With the change to the `voyager_indexing_service.rb` that Frederick and I made in #128, the format should be shown since the format field was already set up. After reindexing the fixtures to add the format field: [Uploading... Screen Shot 2020-05-12 at 3.01.15 PM.png ]

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/35

**Comment by FCRodriguez7** [comment]
Bess' example https://github.com/emory-libraries/dlp-lux/tree/master/spec/system Maybe look at these examples?

**Comment by FCRodriguez7** [comment]
The test was created today and will be pushed shortly.   

Frederick
