### ISSUE TITLE
Implement access control for the Search API

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1303]
**Story**

The IIIF Search API endpoint should follow the same rules as the IIIF Manifest endpoint

**Acceptance**
- [x] If the image access is Public, the endpoint for that image is public
- [x] If the image access is Yale Community Only, the endpoint should be accessible only to on-campus or logged-in users
- [x] If the image has any other access level (i.e., it is Private or some other value) , it should not be accessible at all

**Comment by dylansalay** [comment]
Pull Request: https://github.com/yalelibrary/yul-dc-blacklight/pull/547
