### ISSUE TITLE
Recreate Solomon Sir Jones page on new brbl-archive site

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1305]
**Story**

On the brbl-archive site there are php pages that display a Kaltura viewer:
http://brbl-archive.library.yale.edu/exhibitions/celluloidwest/SolomonSirJones/

This needs to be refactored to static HTML - perhaps with a link to the videos elsewhere (~~Rebecca mentioned they may be on YouTube?~~  Link to Aviary, see below).

**Acceptance**
- [ ] The page is replaced on the new LIT-hosted version with static HTML
- [ ] The page is tested on the new server.

**Comment by motropuk** [comment]
@mikeapp These videos are all now available in Aviary https://beineckelibrary.aviaryplatform.com/collections/1058

**Comment by tmacmath** [comment]
I'm wondering why this page is to be re-created as a static HTML page. Won't it be going into the new DL? I guess my question is, are we still supporting the old brbl-archive site?

**Comment by tmacmath** [comment]
Working on this now. Halfway through.

**Comment by DraxIndustries79** [comment]
Working on this locally for now.  Will coordinate with Bob.

**Comment by tmacmath** [comment]
This is what the recreated page looks like - I'm just working on adding the rest of the captions and the links in the image/thumbnail gallery. ![SSR-page-capture.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/67cee5a8-9923-47f2-91bf-86463dc39270)

**Comment by tmacmath** [comment]
Doing a final test of the Aviary links then sending files to Bob R.

**Comment by tmacmath** [comment]
Sent files to Bob Rice yesterday afternoon (via Filelocker).

**Comment by tmacmath** [comment]
Path to index.html: 

/solomon-sir-jones/app/index.html
