### ISSUE TITLE
Investigate problem BRBL items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1309]
**Story**

A few items at the start of the search results seem to have issues.   For example, https://collections.library.yale.edu/catalog/2013548 won't reindex, even when "Update Metadata" is clicked in the management UI.  Also, it's Solr record shows as `null` in the management parent page.

**Acceptance**
- Examine parent OIDs and fix or report back on status:
  - [x] 2013548
  - [x] 16039409
  - [x] 10589898

**Comment by MaggieZhaoYale** [comment]
2013548
 16039409
each one image failed to convert to ptiff
There is another ticket for this. 
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1315

**Comment by FCRodriguez7** [comment]
For 10589898, the image is broken.  The problem is the ptiff:

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1baad393-19e2-4266-b906-048dcb8fa567)

**Comment by FCRodriguez7** [comment]
We need to get the images from the original source.
