### ISSUE TITLE
Metadata: Some fields are concatenated when they should remain distinct

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1310]
**Story provided by Metadata TF**

Some fields are concatenated when they should remain distinct
Examples: 
246 and the 630 and separated by ‘and’?  See “[Alternative Title: Voynich manuscript and Voynich manuscript](https://collections-demo.library.yale.edu/catalog/2002046).  Also "Materīaly dli︠a︡ geografīi i statistiki Rossīi, sobrannye ofit︠s︡erami Generalʹnago shtaba and Матерiалы для географiи и статистики Россiи, собранные офицерами Генеральнаго штаба" https://collections.library.yale.edu/catalog/30719263

524s and 510s, both labeled "References"[He danc'd like a monkey, his pockets well cram'd](https://collections-demo.library.yale.edu/catalog/11861430)  

500 and 590: [The story of Sigurd the Volsung and the fall of the Niblungs](https://collections-demo.library.yale.edu/catalog/2046716)

Aim to avoid concatenation of MARC tags unless specifically indicated. Check if MARC handler is treating as list and inserting “and”. Try deduping or changing Blacklight handler to insert newline rather than “and”. 

**Note:** You will need to look at the metadata cloud mappings to determine the relevant Solr fields.

**Acceptance**
- [x] The above-mentioned fields use line breaks to separate values.

**Visual Example:** 
![Screen Shot 2021-05-25 at 2.54.24 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d3b04e6c-8253-40c3-b1d4-82c1440e097a)

**Comment by mikeapp** [comment]
246:  AlternativeTitleDisplay
630:  Genre, Subject***  (depends on subfield?)
524: PreferredCitation
510: IndexedBy
500 and 590: Description

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/565

**Comment by mikeapp** [comment]
When on test, should be able to check with:
(title) https://collections-test.library.yale.edu/catalog/800043384
(alternative title, possibly?) https://collections-test.library.yale.edu/catalog/16628751

**Comment by FCRodriguez7** [comment]
Released blacklight v1.42.14
