### ISSUE TITLE
Remove Deprecated Fields from Solr Index

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1311]
- [x] Verify that all fields in SolrIndexable marked as deprecated are not used in Blacklight. (box_ssim and partOf_tesim are used in Blacklight for OAI, so they shouldn't be there.)

- [x] Remove indexing of deprecated fields in SolrIndexable that are no longer used or needed in Blacklight.

**Comment by martinlovell** [comment]
`partOf_tesim` just used in OAI mods, probably based on a LB match with the old code.
We could move that out of deprecated in management if it seems valid to use for the OAI mods, even though we don't display it anywhere else.

`box_ssim` is also used by OAI, but I think that one is really deprecated and we favor containerGrouping_ssim since it's more generic.  We should probably update OAI code to not use box_ssim or folder_ssim, and use containerGrouping_ssim instead.  (folder_ssim should probably be moved to deprecated in management.)

`edition_tesim` is only used by the CitationStringProcessor.  It's not indexed at all by management so will always be null.  There is a sourceEdition_tesim field indexed. I'm not sure if that's the same thing.

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/852

**Comment by FCRodriguez7** [comment]
Released blacklight v1.58.3

Released management v2.54.3
