### ISSUE TITLE
Caption should match physical images 

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1314]
**Story**
One caption may apply to multiple physical images. Each images should have its matched caption if it is applied.
  Mets.xml 
<mets:structLink> part indicates the links between logical part and physical part:
e.g.
   <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0001" />
    <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0001" />
    <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0001" />
    <mets:smLink xlink:to="PHYS_0004" xlink:from="LOG_0002" />
    <mets:smLink xlink:to="PHYS_0005" xlink:from="LOG_0002" />
    <mets:smLink xlink:to="PHYS_0006" xlink:from="LOG_0002" />
    <mets:smLink xlink:to="PHYS_0007" xlink:from="LOG_0003" />
    <mets:smLink xlink:to="PHYS_0008" xlink:from="LOG_0003" />
    <mets:smLink xlink:to="PHYS_0009" xlink:from="LOG_0003" />

**Acceptance**
- [ ] Captions appear on items that have them
- [ ] Ingest 30597978, 30598035, 30598201, 30598849

**Comment by FCRodriguez7** [comment]
Released management v2.37.1

**Comment by MaggieZhaoYale** [comment]
https://collections-test.library.yale.edu/management/parent_objects/800013363

**Comment by MaggieZhaoYale** [comment]
Test example:
https://collections-uat.library.yale.edu/management/parent_objects/30003162 (3rd image does not have caption)
(modified the the logical part and smLink in mets.xml and re-ingested this object.

**Comment by FCRodriguez7** [comment]
Maggie and I tested the feature on a record in the UAT environment and a few records on TEST environment.  The feature is working properly and ready for acceptance.
