### ISSUE TITLE
Separate fulltext search results snippets with line break

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1317]
**Story**

Separate fulltext search results snippets with line break, not commas.

**Acceptance**
- [ ] Each snippet on the result page is on a separate line,

**Visual Example:** 
![Screen Shot 2021-05-25 at 2.34.09 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5cf39c19-6877-4b8e-9968-e82c3c36a687)

**Comment by alishaevn** [comment]
https://solr.apache.org/guide/8_7/highlighting.html

**Comment by FCRodriguez7** [comment]
I am not sure if we want the extra line space.  

![119727283-f4cc5a80-be26-11eb-906a-4f9383f0b7cf.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3fb4640d-b2e8-4bdd-9163-afb153a6d460)

**Comment by mikeapp** [comment]
I think that it OK for now.

**Comment by dylansalay** [comment]
@mikeapp @FCRodriguez7 I just pushed up a commit to remove the extra space. Shall I add it back?

**Comment by mikeapp** [comment]
No need, it's fine either way.  I'm sure we'll end up styling it more based on stakeholder feedback.

**Comment by FCRodriguez7** [comment]
**Example without the "extra line space"** 

![Screen Shot 2021-05-27 at 11.14.50 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e5e12526-aca4-4470-9963-2c5b0e63a1db)
