### ISSUE TITLE
Include additional fields in fixture data

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#132]
**STORY**
In order to support development of a more complete end-user experience, we need to supply additional metadata fields in our fixture set.

**ACCEPTANCE**
The fixtures include the following fields (populated when available)
- [x] format
- [ ] oid
- [ ] title
- [ ] language
- [ ] creator
- [ ] description
- [ ] orbisBibId
- [ ] alternativeTitle
- [ ] source
- [ ] recordType
- [ ] identifierMfhd
- [ ] identifierShelfMark
- [ ] box
- [ ] sourceTitle
- [ ] sourceDate
- [ ] sourceNote
- [ ] extentOfDigitization
- [ ] date
- [ ] extent
- [ ] subjectName
- [ ] subjectTopic
- [ ] genre
- [ ] partOf
- [ ] rights
- [ ] orbisBarcode
- [ ] findingAid
- [ ] references
- [ ] dateStructured
- [ ] collectionId
- [ ] children
- [ ] publicationPlace
- [ ] folder
- [ ] numberOfPages
- [ ] importUrl
- [ ] resourceType
- [ ] sourceCreated
- [ ] edition
- [ ] uri
- [ ] abstract
- [ ] geoSubject
- [ ] illustrativeMatter
- [ ] publisher
- [ ] material
- [ ] scale
- [ ] digital
- [ ] coordinates
- [ ] copyrightDate
- [ ] projection

NOTE: the solr mappings suggested here may be helpful (or may not):
https://github.com/yalelibrary/yul-dc-blacklight/blob/4f578c0f10ea50645772b58886ca16af5a0015b4/spec/fixtures/ladybird-to-solr.sh

**Comment by martinlovell** [comment]
This would be a good opportunity to move the mapping code out of the rake task and create some tests for it.
It could be done with TDD, which would be a good learning experience for us.
I'd be happy to create a stub for a JsonRecordToSolr class or something similar, and I could create some pending tests if that would be helpful.

That way if we want to re implement the mapper later, we can without worrying that it breaks.

**Comment by martinlovell** [comment]
Refactored a few things on this branch: https://github.com/yalelibrary/yul-dc-management/tree/index_metadata_cloud_data

Refreshing metadata is working not in container.
Indexing is working.
Ready no to add any fields and tests. Will continue in the morning.

**Comment by martinlovell** [comment]
Started again (above branch was abandoned) from master without refactoring anything.
Just added a bunch of assignments.  Rubo cop complains because of size of method and assignments (which refactoring and not having a huge list of assignments will help.)

https://github.com/yalelibrary/yul-dc-management/pull/new/132_include_additional_fields_when_indexing_fixture

**Comment by martinlovell** [comment]
See: https://github.com/yalelibrary/yul-dc-management/pull/18
