### ISSUE TITLE
Service to return fulltext data

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1322]
**Story**

We anticipate a requirement to display the transcription/OCR of the page(s) the user is looking at in the Universal Viewer.  To facilitate this, we'd like an endpoint that will deliver this data in JSON format.   The content will be delivered on W3 Web Annotation format.

```
{
          "id": "https://SERVER_NAME/annotation/oid/2004521/canvas/1064614/fulltext",
          "type": "Annotation",
          "motivation": "supplementing",
          "body": {
            "type": "TextualBody",
            "value": "[FULL TEXT HERE]"
          },
          "target": "https://SERVER_NAME/manifests/oid/2004521/canvas/1064614"
 }
```

**Acceptance**
- An endpoint exists that will return JSON for a given child OID.  
- The data is a W3C web annotation targeting the child Canvas
- The endpoint enforces access control based on the Parent's access level:
  - [x]  Public: all requests are allowed
  - [x]  Yale Community Only: allowed only if the user is on campus or logged in
  - [x]  All others: denied
  - Note that although the parent OID is present in the URL patterns above, don't trust that value.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/562

**Comment by martinlovell** [comment]
https://collections-demo.library.yale.edu/annotation/oid/10171425/canvas/1419041/fulltext
https://collections-demo.library.yale.edu/annotation/oid/10171425/canvas/1419042/fulltext
