### ISSUE TITLE
one BRBL object has xml tag in title

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1329]
**Story**

https://collections.library.yale.edu/catalog/31259461
<title xlink:type="simple" render="italic">The Poet in the Imaginary Museum: Essays of Two Decades</title>. Clippings of reviews.

The main title of the mets.xml has this information too. 
The information was pull from the ArchivesSpace 

https://metadata-api.library.yale.edu/metadatacloud/api/aspace/repositories/11/archival_objects/225270?mediaType=json

**Acceptance**
- [x] Check the  metadata in metadata cloud and get the source of title which contains the xml tag
- [x] Informed Rebecca that title information was pulled from ArchivesSpace
~~- [ ] ArchivesSpace update the metadata
- [ ] BRBL reprocess and re-export the object
- [ ] Delete the object in DL and re-ingest~~

**Comment by DraxIndustries79** [comment]
Waiting on ArchivesSpace to make a change on the metadata.  Will be a week or more, due to vacation.

**Comment by MaggieZhaoYale** [comment]
updated metadata cloud to check stripTag for "fieldValue"
