### ISSUE TITLE
JSS page order

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1331]
**Story**

Objects with incorrect page order:
https://collections.library.yale.edu/catalog/31174894

**Acceptance**
- [ ] review and correct order of pages if needed

**Comment by MaggieZhaoYale** [comment]
brbl-dsu/jss_import/8553012_39002100083345
slavicbooks:976009 jump to slavicbooks:1154500
will reprocess the images.

**Comment by MaggieZhaoYale** [comment]
Replaced with https://collections.library.yale.edu/management/parent_objects/31444656
