### ISSUE TITLE
extentOfDigitization  not show in Goobi ingested objects

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1333]
**Story:**
Extent of Digitization and for Goobi ingested objects do not have value.
e.g. 
JSS object: https://collections.library.yale.edu/management/parent_objects/31398439
BRBL object: https://collections.library.yale.edu/management/parent_objects/31317520

Extent of Digitization is in the mets.xml
Xpath: ./mods:mods/#mods:part

**Acceptance:**
- [ ] Get the value from the mets document  if it is a Goobi ingest object

**Comment by FCRodriguez7** [comment]
Released management v2.42.1

**Comment by FCRodriguez7** [comment]
Released management v2.42.1

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/parent_objects/900057165
https://collections-uat.library.yale.edu/management/parent_objects/900056552
