### ISSUE TITLE
Populated page order data in the Child Objects table 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1337]
**User Story**
As a viewer or editor in the Management Application, I want the page order to appear on the Child Objects Table

**Acceptance**
- [ ] the "Order" column has populated page order data

**Path to the table:** 
Batch Processes > Click on Process ID > Click on "Parent OID" Click on "Child OID"> Click on Child Object > Click on "All Child Objects"

**Current Table:**
![Screen Shot 2021-05-28 at 11.42.43 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/08c8b791-1bb2-4861-a73a-0236b2a2bece)

**Comment by martinlovell** [comment]
I agree, is was a issue with data on UAT.
