### ISSUE TITLE
Move the label data in the label column on the child objects table

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1338]
**User Story**
As a viewer or editor in the Management Application, I want the label data to appear in the label column.  Currently, the label data appears in the caption column on the Child Objects table

**Acceptance**
- [ ] the "Label" column should have the correct populated label data

**Path to the table:** 
Batch Processes > Click on Process ID > Click on "Parent OID" Click on "Child OID"> Click on Child Object > Click on "All Child Objects"

**Current Table:**
![Screen Shot 2021-05-28 at 11.42.43 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/08c8b791-1bb2-4861-a73a-0236b2a2bece)

**Proposed Table:** 
![Screen Shot 2021-05-28 at 11.42.43 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5d7dec7f-c383-41f4-a3cf-050ab2e10e64)

**Comment by mikeapp** [comment]
I think this is a data issue, in production I can see `order` and `label` in the correct columns:

![Screen Shot 2021-05-28 at 2.30.47 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a3a1f685-e5e3-461a-8ab2-39afb10b3ab8)

**Comment by alishaevn** [comment]
confirming that this also appears to no longer be an issue in local dev
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/ec78ff26-5c5e-4ab3-be8b-26b7f19dbe4b)

**Comment by FCRodriguez7** [comment]
I checked all three environments, local, prod, and uat.   This is only occurring in UAT.

**Comment by martinlovell** [comment]
I agree, is was a issue with data on UAT.
