### ISSUE TITLE
Populate solr with fixture data from the management app

### ISSUE THREAD

**Issue by geekscruff** [yalelibrary/YUL-DC#134]
**ACCEPTANCE**

- [x] There is a rake task to create fixture data from the same 45-record dataset as Blacklight
- [x] There are tests to show the fixture data is importing as expected

HINTS: 

- steal from the Blacklight app, this work has been done there
- with a vanilla rails app, you'll need to setup the connection to solr; use rsolr for that

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/81944507-d94f3280-95ca-11ea-86ad-33bc0819336d.png)
