### ISSUE TITLE
Management UI Navigation sidebar

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1341]
**Story:** 

Give the current Management app sidebar a look and feel that is consistent with the current DL UI. 

**Acceptance:** 

- [x] Use approved Yale font (Mallory) for nav links

- [x] Use color for link and div to indicate current page (selected) - see design mockup. Color palette is attached for reference.  (https://xd.adobe.com/view/8f11c305-11c3-4fa2-8955-4f74f1f08942-da42/)

**Comment by tmacmath** [comment]
![Screen Shot 2021-05-26 at 2.00.05 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/3c9f1eab-ff84-4e81-bac3-aad94324421f)

**Comment by FCRodriguez7** [comment]
I am having issues with the hover: 

![Screen Shot 2021-06-04 at 1.53.36 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f493cfce-15bd-4bc6-8777-73d2bad6feff)

**Comment by FCRodriguez7** [comment]
**DEMO**
https://images.zenhubusercontent.com/242185115/1d8decb2-af96-41c6-a1e4-41aa8fd1f72b/screen_recording_2021_06_04_at_3_07_59_pm.mov

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/654

**Comment by FCRodriguez7** [comment]
PR: Released management v2.42.0

**Comment by FCRodriguez7** [comment]
Deployed as of June 4 2021 @ 6 pm.
