### ISSUE TITLE
Management UI app global footer

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1342]
**Story:** 

Create global footer for versioning info, so that it will be clear that this information applies to the whole app and not to whatever is on the current page. (See attached design mockup for reference)

![Screen Shot 2021-05-28 at 2.35.22 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/2b9be5f7-0d2d-45e6-92d0-feab1b97b80d)

Acceptance: 

- [ ] Create a global footer with left-aligned versioning info (same as the current app, but moved into a specific region on the page)

**Comment by FCRodriguez7** [comment]
**ACTUAL MODIFICATION**

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/649

**Comment by FCRodriguez7** [comment]
Released management v2.41.0
