### ISSUE TITLE
Add "Child Objects" to management left menu

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1343]
**Story**

As a management user I would like to be able to sort and filter child objects like I do the parents.

**Acceptance**
- [x] Display "Child Objects" in the left menu, below "Parent Objects"
- [x] The link should lead to https://collections.library.yale.edu/management/child_objects
 
![Screen Shot 2021-05-28 at 2.36.19 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b5743d03-da77-4b73-a3fc-3ab85a7e9e8f)

**Comment by FCRodriguez7** [comment]
**Demo of the Feature:** 

https://images.zenhubusercontent.com/242185115/b53cd142-3a21-4c5f-bb26-bb0c4f51dfcd/slidebar_childobjectlabel.mov

**Comment by FCRodriguez7** [comment]
I need to finish the writing test for the feature.

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/638

**Comment by FCRodriguez7** [comment]
Released management v2.38.0
