### ISSUE TITLE
Create digitization_note field on Parent Object

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1345]
**Story**

DSU would like to import the digitization note field.

**Acceptance**
- [ ] Add a `digitization_note` text field to the ParentObject
- [ ] In the display page for a parent object, show the digitization note
- [ ] In the edit page for a parent object, allow the digitization note to be edited in a text area

**Comment by FCRodriguez7** [comment]
Released management v2.42.1

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/parent_objects/900057165
https://collections-uat.library.yale.edu/management/parent_objects/900056552
