### ISSUE TITLE
Import digitization note data from Goobi

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1346]
**Story**

DSU would like to import the digitization note from Goobi.

**Acceptance**
- [ ] The digitization note is imported from METS and stored in the digitization_note field of the Parent Object.

**Comment by MaggieZhaoYale** [comment]
digitizationNote (xpath: ./mods:mods/#mods:note[@type='admin'])
![image.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/398a6b91-adb3-4f81-8cbf-71437804edb1)

**Comment by MaggieZhaoYale** [comment]
Two test records in uat:
https://collections-uat.library.yale.edu/management/parent_objects/900057165
https://collections-uat.library.yale.edu/management/parent_objects/900056552
![Screen Shot 2021-06-07 at 11.33.15 AM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/4ba6993a-cd3b-43e4-90e4-23de10bc94ef)
