### ISSUE TITLE
Add color palette to management app

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#1348]
# Summary
Add the management color palette to the repo so it can be used in the new UI work

# Acceptance
- [x] the colors below are in the app
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/3569af7b-d7e8-487e-80e4-9972789c9532)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/637

# Expected behavior
- the colors below have been added to the repo
![image](https://user-images.githubusercontent.com/29032869/120370575-9e996480-c2c9-11eb-8bd4-f1538572fe54.png)


# Demo
![image](https://user-images.githubusercontent.com/29032869/120370519-875a7700-c2c9-11eb-9330-96d0c3645306.png)

**Comment by alishaevn** [comment]
this is working on test
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/ae21a6b7-41be-44c7-895d-efacabdd5475)

**Comment by FCRodriguez7** [comment]
Released management v2.38.0
