### ISSUE TITLE
Begin image copy and report

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#135]
Tasks:
- [x] Verify with Bob that the share mounted is set up for production 
- [x] Begin copying master images

Acceptance:
- [x] Add report to this issue next Monday on 
    - [x] total # of files copied
    - [x] total bytes copied
    - [x] total copy time
    - [x] average file size
    - [x] average copy time
    - [x] description of any errors or issues encountered

**Comment by kcompsci** [comment]
Here are some stats as of 11:40 am 2/26/20:
- Copy started at 12:22 pm on Friday 2/22/20
- A total of 75085 objects copied
- In 72 hrs a total of 51822 objects copied (5 seconds per object)
- A total of 1 object error occurred. Error message: **** OID 15816491 Error while copying .ERROR message: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /fc_beinecke2-YUL-CC0691-YUL/IMAGES-DERIVATIVE_TIFF/SML_MAPS_TRANSFER/SML_MAPS_TRANSFER_603-610 /15816491.tif
