### ISSUE TITLE
Management UI app data table column select

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1350]
**Story:** 

Add the column toggle/select widget to the data table: 

[https://api.jquerymobile.com/table-columntoggle/](url)

**Comment by martinlovell** [comment]
Using datatables "Buttons" extension with styling to approximate jquery table-column toggle.    (See colvis default styling: https://datatables.net/extensions/fixedcolumns/examples/styling/colvis.html)

![show-hide-columns](https://user-images.githubusercontent.com/32851993/120508569-d5d54780-c395-11eb-891a-330225fac8d9.gif)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/642

**Comment by FCRodriguez7** [comment]
Released management v2.40.0

**Comment by mikeapp** [comment]
Nice!
