### ISSUE TITLE
Finish JSS ingest of non-problem items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1351]
**Story**

Ingest the remaining JSS items that don't have metadata issues.

**Acceptance**
- [x] Finish JSS ingest.

**Comment by MaggieZhaoYale** [comment]
Finished all non-problem items.
2899 JSS items are in the DL. 
464 items are inactive barcodes or bibs id changes/deleted
1 item does not have any images which matches that in the http://jss.library.yale.edu/DPresInterface/VolumesServlet?query=Sistematicheskai%EF%B8%A0a%EF%B8%A1%20rospis%CA%B9%20knigam&pid=slavicbooks:154307&from=GroupPortalServlet&gpsHitPageStart=1
(All problematic items are recorded in the attached excel)
[https://app.zenhub.com/files/242185115/089a6de7-5eeb-49a7-8897-c006e310d29d/download](https://app.zenhub.com/files/242185115/089a6de7-5eeb-49a7-8897-c006e310d29d/download)
