### ISSUE TITLE
Bump ws from 6.2.1 to 6.2.2 on management

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#1355]
# Summary
the following dependabot alert has surfaced in the management app
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/cec35e84-bf67-41b5-9c4e-dc72bd8dda4a)

# Acceptance criteria
- approve and merge the pr that dependabot opened
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/51fd9eb6-89ee-4f81-9120-88c42472ecb0)

**Comment by alishaevn** [comment]
merged
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/61b3d936-7dbe-43ad-bd79-a3b6fdeb8c01)

**Comment by FCRodriguez7** [comment]
Released management v2.40.0
