### ISSUE TITLE
Add mallory fonts

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#1356]
# Summary
- the mallory and mallory mp fonts are desired to be used in the management repo, but aren't in the app yet

# Acceptance criteria
- add the mallory fonts that are in the blacklight app
- add the mallory mp fonts that are in the blacklight app

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/643

**Comment by FCRodriguez7** [comment]
Released management v2.40.0
