### ISSUE TITLE
Merge Main -> Fulltext Branch

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1358]
Merge Main to a new branch off of fulltext.
Fix merge conflicts.
Create PR new branch -> fulltext.

**Comment by FCRodriguez7** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/564

**Comment by FCRodriguez7** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/650
