### ISSUE TITLE
Decision document for crawl prevention

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#136]
https://searchengineland.com/how-to-keep-staging-development-site-index-286987

ACCEPTANCE
* [x] Decision document outlining pros/cons of possible crawl prevention strategies for DCE Test, DCE Demo, Yale Test sites

in support of https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/127

**Comment by dl-maura** [comment]
Will share in ticket today.

**Comment by fnibbit** [comment]
https://docs.google.com/document/d/1NIMfqY94v2Uot_btoB0D627G7hWy9JlBzplb3NnKWao/edit?usp=sharing
