### ISSUE TITLE
Facet for items with full text available

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1360]
**Story**

We would like to be able to facet on items that have full text available.  

**Acceptance**
- Create a new facet in Blacklight
   - [ ] Solr field is `has_fulltext_ssi`
   - [ ] Label for the facet should be `Full Text Available`
- In management
   - [ ] Parent Objects without full text should set the value  `No` in the Solr field
   - [ ] Parent Objects with full text should set the value `Yes` in the Solr field

**Comment by mikeapp** [comment]
@edejesusyale  Apologies for not specifying the position in the facet list.  Please make it the last facet.

**Comment by FCRodriguez7** [comment]
Feature must be reindexed.

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/580
