### ISSUE TITLE
Full-text Simple Search description 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1361]
**Story**

In FindIt there is descriptive text for the full text search option that displays in a popup when hovering over the "what's this?" text:
![Screen Shot 2021-06-06 at 5.40.22 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9ab3f210-caa1-4069-ad99-6dede96db93d)

In Blacklight we'd like to display a similar message:
```
Search full text that occurs in a work. Not all works contain searchable full text.
```

**Acceptance**
Display the message in two places:
- [ ] In the simple search, when "full text" is selected in the drop down, display the message under the text input for the search. ![Screen Shot 2021-06-08 at 1.30.01 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/12fd831d-33f6-4222-944c-741a71cef91a)
- [ ] In the advanced search, display the message under the text input for the full-text search option. ![Screen Shot 2021-06-08 at 1.31.09 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/310fd4af-8e9f-4554-9e4d-f1c5386ccd92)

**Comment by FCRodriguez7** [comment]
**Actual Propose Modification**

![aa0c0941-fa7f-428b-92e3-94da3122a851.jpg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/79394769-50cc-4609-b719-3952698af0cd)

**Comment by FCRodriguez7** [comment]
Simple Search PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/585
