### ISSUE TITLE
SPIKE: Simple full text search highlights other fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1366]
**Story**

When searching full text (e.g., "the") the results highlight matches in other fields (e.g., in the title).

![Screen Shot 2021-06-07 at 2.38.30 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d0d20a66-b10f-4649-9008-9a096621594a)

**Acceptance**
- [ ] Simple searches for full text highlight matches in the full text display only.

**Comment by FCRodriguez7** [comment]
If title highlighting is not desired anymore: 

![option a.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a4db482a-cb36-4eef-998b-fa2a8736a194)

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/570

**Comment by FCRodriguez7** [comment]
What do we want? 

----
![Screen Shot 2021-06-09 at 11.36.47 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5c29c54c-a825-4794-84e8-dbd75fb0402f)

----
![Screen Shot 2021-06-09 at 11.37.12 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f90d0613-421f-421b-a1e1-abc02e5eb738)

**Comment by mikeapp** [comment]
Is the change causing fields to not appear?  Or is an open search causing all fields to appear?

**Comment by mikeapp** [comment]
Looks good on demo
