### ISSUE TITLE
Advanced search: full text search highlights other fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1367]
**Story**

When searching full text (e.g., "the") in Advanced Search the results highlight matches in other fields (e.g., in the title).

See #1362 for simple search equivalent.

**Acceptance**
- [x] Advanced searches for full text highlight matches in the full text display only.

**Comment by FCRodriguez7** [comment]
PR:  https://github.com/yalelibrary/yul-dc-blacklight/pull/571

**Comment by FCRodriguez7** [comment]
Additional work to the advanced search exclusive highlighting: https://github.com/yalelibrary/yul-dc-blacklight/pull/574

**Comment by mikeapp** [comment]
Looks good on demo
