### ISSUE TITLE
Multiple titles in object page header should have line breaks

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1368]
**Story**

We switched to breaks instead of "and" in the metadata display, but the page header should also do this:

![Screen Shot 2021-06-07 at 2.56.43 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/03f61803-ec9d-4920-9c44-2ef74946c886)

Object is https://collections.library.yale.edu/catalog/31901015

**Acceptance**
- [x] Multiple titles in the page header should be on new lines

----
**Test Record:**
https://collections-test.library.yale.edu/catalog/800043384

**Current State**
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4574a88f-82ca-4d83-ac49-a027c1707be5)

**Proposed State**
![Screen Shot 2021-06-11 at 1.03.22 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4a09cfea-c9bc-4802-b8eb-99f1717d39f8)

**Comment by mikeapp** [comment]
https://collections-test.library.yale.edu/catalog/800043384

**Comment by FCRodriguez7** [comment]
**Before Code Modification**

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4574a88f-82ca-4d83-ac49-a027c1707be5)

**Comment by FCRodriguez7** [comment]
I put the code on test and reindexed 800043384.

**Comment by FCRodriguez7** [comment]
https://images.zenhubusercontent.com/242185115/7fdbc88b-acdf-4139-8fdc-da9ea08773d3/multiple_titles_in_1368object_page_header_should_have_line_breaks.mov

**Comment by FCRodriguez7** [comment]
Released blacklight v1.44.0

**Comment by FCRodriguez7** [comment]
The feature requires a metadata update on management.

**Comment by mikeapp** [comment]
Looks good on test, can't find a suitable object on UAT.
