### ISSUE TITLE
Toggle to display full text for objects 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1370]
**Story**

As a user, I'd like the option to show the transcription for the child object or object(s) that are selected in the Universal Viewer.    

**Mock Up**

Closed:
![full_text_closed.jpg](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/465bdefc-613c-4d98-8716-22bbae6001c5)

Open, single page focus in UV:
![full_text_open.jpg](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/862e274d-c5d8-4ec9-b450-d3c78b9971b8)

Open, two-up view (IIIF viewing hint `paged`) in UV:
![full_text_two_up.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3d898376-79eb-4a30-ae07-79bddc966d48)

**Acceptance**
-  For objects with full text available, a "Show full text" button displays beneath the UV viewer.
   - When clicked:
       - [x] The full text for the child/children in focus in the UV is displayed beneath the UV, in an area the same width as the viewer.
       - [x] If UV is displaying a two-up view (IIIF viewing hint `paged` on the parent object), the full text for the two children is displayed side-by-side.
- When the user navigates to a new child in the UV
   - [x] The full text display updates to show the full text for the new child/children that are in focus.

**Comment by mikeapp** [comment]
Example two-up object on test: https://collections-test.library.yale.edu/catalog/800043384

**Comment by alishaevn** [comment]
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>
co-author: jp engstrom <jp@notch8.com>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/586

# Demo
https://user-images.githubusercontent.com/29032869/123183055-8d192780-d445-11eb-9265-53a38ccfc815.mp4

**Comment by FCRodriguez7** [comment]
The feature has been deployed to demo.
