### ISSUE TITLE
Update link from Blacklight homepage to Statement on Harmful Language...

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1371]
**Story**

"I happened to notice yesterday that the link on the homepage of https://collections.library.yale.edu/ still points to the Statement on Harmful Language in Archival Description (https://guides.library.yale.edu/specialcollections/statementondescription), rather than the Statement on Potentially Harmful Content (https://guides.library.yale.edu/about/statement-on-content). I think that’s because I wasn’t clear when we were corresponding back in April that the text (which did change) and also the hyperlink itself should be updated."

**Acceptance**
- [x] Link on homepage in Blacklight is updated.

**Bonus**
- [x] Correct the paragraph word hung 

![Screen Shot 2021-06-10 at 10.23.00 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6176f90b-8218-487d-a8d8-b6b1b5aff9bb)

![Screen Shot 2021-06-10 at 10.23.00 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6f3d80e4-413a-4a58-a999-840c13dec075)

**Comment by FCRodriguez7** [comment]
**Demo Change**

![1371_UpdateHarmLanguageStatement.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/adcbfce5-b066-4721-9971-4263cf3653bc)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.43.0
