### ISSUE TITLE
add drop down to extent of digitization and edit box under Digitization Note in parent object datatable

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1372]
Parent object update metadata datatable: 

- [x] add drop down list of extent of digitization, so can be searched and edited

- [x] input box under Digitization note, so can be searched and edited

**Comment by MaggieZhaoYale** [comment]
[Uploading... datatable_digi.mov]

**Comment by mikeapp** [comment]
I just deployed to UAT

**Comment by MaggieZhaoYale** [comment]
Thank you!
