### ISSUE TITLE
Give datatables full page width

### ISSUE THREAD

**Issue by dylansalay** [yalelibrary/YUL-DC#1373]
**Story:** 
The datatables do not extend to the full width of the page, unless they have enough columns to do so
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/3de4539a-2923-4fe2-815c-c26ba9599934)

**Acceptance:**
- [x] Update all datatables to take up the full width of their bounding box, while maintaining scrollability, despite the amount of columns

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-management/pull/671

# Expected behavior
- all datatables are full width

# Demo
https://user-images.githubusercontent.com/29032869/122155974-e1f0e880-ce1c-11eb-94fa-194d68e28426.mp4

**Comment by mikeapp** [comment]
Looks good!
