### ISSUE TITLE
Create/update dependent objects when processing metadata updates

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1384]
**Story**

The system should create dependent objects when the parent object is (re)indexed.   There is code for this in `activity_stream_reader.rb` but:

* the Activity Stream functionality isn't being used yet
* that code updates every parent object each time it is run, which is inefficient

See https://github.com/yalelibrary/yul-dc-management/blob/df31261bfbf50ed88e97a21554eb9a711d7ab511/app/lib/activity_stream_reader.rb#L71

**Acceptance**
- [x] Add logic to update dependent objects in `SetupMetadataJob.perform`

**Comment by martinlovell** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/679

(The code is in ParentObject.default_fetch(), which is triggered by SetupMetadata Job.)

**Comment by FCRodriguez7** [comment]
Released management v2.45.5

**Comment by mikeapp** [comment]
No visible impact.
