### ISSUE TITLE
SPIKE: Look for JSS full text files

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1387]
**Story**

We may want to bring full text content over from JSS, if we can find it.   Are there files on disk, or full-text data streams in the Fedora objects?

**Acceptance**
- [ ] Look for JSS full text and report back

**Comment by MaggieZhaoYale** [comment]
We did not find ocr/full text on the  fedora server, and no search result return ocr.
The schema.xml indicates text_rus, text_cze, text_gre, text_noneng were the fieldtype for fulltext. The solr query by these fields return 0;

We reached out Eric James who left the fulltext comment on the schema.xml.
Here is his response:
I believe there was OCR, and it was in an indexed Fedora3 datastream.  The full text might have been embedded in the PDF too (also a Fedora3 datastream), I don’t totally remember.

**Comment by kcompsci** [comment]
What we've discovered is that the PDF is being used as full text search in JSS. There is no separate data stream in  Fedora that stores it. Eric James (one of the original developer of the interface) also confirmed that he didn't see one in Fedora although originally he thought there was.

**Comment by mikeapp** [comment]
I see now, there's a PDF per page.    Let me consider next steps.
