### ISSUE TITLE
Full text: simple search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1389]
**Story**

Our stakeholders would like to model the simple search box on that found at Hathi Trust ( https://www.hathitrust.org ).   On that site there are radio buttons that offer a choice of searching the catalog or the full text.  Mapping the design to our site, it would look like this:

![search_catalog.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/dd7e13dc-c031-434d-af33-4d3514bfe39b)

![search_full_text.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d90c4a35-2156-474f-9c92-44a8ab26d4df)

**Acceptance**
- [x] The "FULL TEXT" option is hidden or removed in the drop down.
- [x] Radio buttons beneath the text input area offer two options:
   - Description
   - Full text
- When Description is selected:
  - [x] Drop-down list is displayed
  - [x] If "All fields" is selected in the drop-down, the placeholder text should read: "Search words about the items"
   - [x] If another field is selected the placeholder text should be "Search"
- When Full Text is selected:
   - [x] The drop-down should be hidden
   - [x] The placeholder text should change to "Search words within the items" 
   - [x] Clicking search should run a full text search

**Comment by FCRodriguez7** [comment]
https://images.zenhubusercontent.com/242185115/9ec8ff81-fc7e-4779-af06-f1564f4ec7c8/screen_recording_2021_06_29_at_1_12_24_pm.mov
