### ISSUE TITLE
Full text: advanced search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1390]
**Story**

Following the example of Hathi Trust, we'd like the placeholder text on the advanced search page to describe what the user will be searching.

**Acceptance**
On the advanced search page:
- [ ]  The "All fields" text input should have the placeholder text: "Search words about the items"
- [ ] The "Full text" text input should have the placeholder text: "Search words within the items"

**Comment by FCRodriguez7** [comment]
The feature has been deployed to demo.
