### ISSUE TITLE
Final BRBL gap load

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1397]
**Story**

Time for the final gap load of Beinecke content!  From Mark: " the last OID is from a different project (36 rather than 3), in case that impacts how the metadata and files are brought over."

OIDs are in this spreadsheet: [https://app.zenhub.com/files/242185115/cbd7517d-0d14-483e-9aba-46cfdb033296/download](https://app.zenhub.com/files/242185115/cbd7517d-0d14-483e-9aba-46cfdb033296/download)

**Acceptance**
- [x] Identify the child images
- [x] Migrate the child images into the production filesystem
- [ ] Ingest the objects

**Comment by kcompsci** [comment]
Checklist Item #2 is in process.

**Comment by mikeapp** [comment]
7 missing images from 4 parents

**Comment by martinlovell** [comment]
This was the only oid in the list they gave us that has 3 missing images: 2004504

These also have missing images, but may be from a prior gap load:  
10256330
15534525
15812698
2022101

Started test ingest into staging.

**Comment by martinlovell** [comment]
Everything is ingested except for these:
16813294
17286627
16813291
16778826
16813290
16813292
(And 2004504 mentioned above)

There were not queued for some reason.  Spot checking an image from each, they do have file assets, but no BRBL references.

Not sure why the child list didn't get generated from rackspace using our standard scripts.  We can probably manually create the list of children or try the rackspace scripts again for just these parents.

**Comment by mikeapp** [comment]
I think Jay turned off the LB->DL sync a few weeks ago so it seem unlikely that you'd get new data from Rackspace.

**Comment by martinlovell** [comment]
I was able to import these into asset inventory using the child list from metadata cloud (production).
They are queued up to copy.
