### ISSUE TITLE
Datatables: back button loses state

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1400]
**Story**

When navigating back to the datatables using the browser's "back" button, filter/sort state is lost.

**Acceptance**
- [x] Back button works as expected with the datatables

**Note:** Rob suggests keeping datatable state in a cookie or js storage and read from there.  Tables should be page specific.

**Comment by alishaevn** [comment]
potential solution? https://stackoverflow.com/a/40646241/8079848

**Comment by FCRodriguez7** [comment]
Released management v2.45.7
