### ISSUE TITLE
Add indexes to improve Datatables performance

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1403]
**Story**

DSU has indicated that the Child Objects datatables sometimes time out.    For instance, filtering by a specific OID times out.
 
**Acceptance**
Write migration so that it succeeds if index already exists.
Add indexes to Child Objects for:
 - [x] OID
 - [x] Parent
 - [x] Order
 - [x] Label
 - [x] Caption

**Comment by fordmadox** [comment]
Just a reminder that this issue continues to be very difficult when using the user interface.  When I accessed the page this morning, it took 20 seconds to load ("Showing 1 to 50 of 1,426,108 entries"), and you cannot filter for a specific child OID until after that initial load.  Searching in lieu of filtering would be preferable, but in the meantime, is the best solution to tell staff to construct their own URLs when accessing a known child OID?

**Comment by mikeapp** [comment]
See https://stackoverflow.com/questions/21795023/how-to-create-a-migration-to-remove-an-index-only-if-it-exists-rather-than-thro and remember we are on 6.0.x.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/761

**Comment by FCRodriguez7** [comment]
Released management v2.48.8
