### ISSUE TITLE
Parent Object display page: add public view button

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1404]
**Story**

DSU request: "Add “public view” option to the Parent OID object page (currently only available in the DataTables view)."

I'm assuming we can use the same icon as in the datatable, but we can check with Tracy.

**Acceptance**
- [x] A public view button is available on the Parent Object page. 
- [x] It opens the view in a new tab

**Comment by K8Sewell** [comment]
Happy to take input from Tracy on styling.  Attempted to match existing flow and design.  [PR ready for review](https://github.com/yalelibrary/yul-dc-management/pull/693)

**Comment by tmacmath** [comment]
Here is the hex code for the Button styling: #cb444a (red fill); #ffffff (white text)

Please also remove the redundant text next the button, allowing the button to align left.

**Comment by K8Sewell** [comment]
Hi @tmacmath - sorry I think there is some confusion.  This ticket is for the public view link for the work not the delete button.  ![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/335a1c43-2958-4f0a-9c7b-0a36a9d93635)  Please let me know if you need rework on the styling of the 'Public View' link next to Solr Document.

**Comment by FCRodriguez7** [comment]
Released management v2.45.8
