### ISSUE TITLE
Child Object display page: remove "All Child Objects" link

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1405]
**Story**

On the Child Object display page: remove "All Child Objects" link since it is the same behavior as clicking "Child Objects" in the left menu.

**Acceptance**
- [x] The "All Child Objects" link in removed from the bottom of the Child Object display page.

**Comment by dylansalay** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/685

**Comment by FCRodriguez7** [comment]
Released management v2.45.6
