### ISSUE TITLE
Provide a template CSV for each batch job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1406]
**Story**

Each batch job type requires a different csv format.   Templates should be available for each job type.

**Acceptance**
-  Create templates for each job type:
    - [x] Create Parent Objects
    - [x] Export Child OIDs
    - [x] Reassociate Child OIDs
    - [x] Recrete Child OID PTIFFs
- [x] On the Batch Process screen, next to (or near) the drop-down to select the job type, display a link "download template"
- [x] The link should update to the point to the correct template when the user selects the batch job type.
- [x] The link should trigger a download or open in a new tab (not replace the batch process screen)

![Screen Shot 2021-06-25 at 1.21.30 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3edfe66e-31e0-47a5-8516-a6801112efe3)

**Comment by mikeapp** [comment]
@tmacmath  Does the solution above sound OK or should we just link to a page with a list of the templates?

**Comment by dylansalay** [comment]
I started on this here: https://github.com/yalelibrary/yul-dc-management/pull/691 

I created a form to get the batch_action and send it to the new controller action.
The new controller action calls a method to get the correct template. I left TODO's in the batch process model for what I think comes next. Feel free to ping me in slack with any questions on my thought process here.

**Comment by martinlovell** [comment]
Finishing up from Dylan's work by filling in TODO's.

**Comment by FCRodriguez7** [comment]
Released management v2.45.9
