### ISSUE TITLE
Batch job for delete

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1407]
**Story**

DSU would like a delete batch job.

**Accpetance**
- [x] Format should be `oid`, `action`
- [x] The job must require the `delete` action to be specified for each OID
- For each OID the  job deletes:
   - [x] the parent SOLR record
   - [x] all child SOLR records
   - [x] the PDF
   - [x] the children
   - [x] the Parent
   - [x] manifest  (see below for unnecessary detail)
- The job respects permissions: 
   - [x] the user must have the editor role in the admin collection to which the parent belongs
   - [x] System admin permission  *does not* override this requirement (i.e., admins will need to make themselves an editor first)
- [x] Delete LEAVES ptiffs

~~(Full text will be a separate ticket)~~ see below

**Note** 
- We don't really need to worry about the manifest since it won't be available without Solr record, which won't be created until the new manifest is generated.   We create the Solr record before queueing the PDF job, which means a stale PDF will be made available if we don't delete the PDF.  However it could be helpful to have a delete marker in S3, so let's go ahead and delete the manifest anyway.
- The full text data needs to stay, at least for now.  Loading full text is a manual process.  We'll eventually improve on this but currently we don't want to delete or modify it.

**Comment by mikeapp** [comment]
We could eventually add `update`, `reindex` action types, so plan with that in mind.

**Comment by DraxIndustries79** [comment]
Per Mike:  Might be using the wrong bucket for the delete.  Source vs. Sample.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/710

**Comment by FCRodriguez7** [comment]
Released management v2.46.2
