### ISSUE TITLE
Add container grouping to Parent Object model and display

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1409]
**Story**

Beinecke DSU has requested the ability to view and filter on the container grouping  in the Parent Object.

**Acceptance**
- [x] Create a new field on the ParentObject model for container grouping
- [x] When the ParentObject metadata is updated, store the `containerGrouping` value of the MetadataCloud JSON in this new field.  If there's more than one value in the array just store the first.
- [x] Add the new field to the Parent Object datatable
    - [x] Users should be able to filter on this field
- [x] Display the container grouping on the Parent Object display page above the bibid:

Put it below Call number (see #1398)

![Screen Shot 2021-06-25 at 11.32.32 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/96fea2a7-27fe-4794-aaa7-82eb88dfe70b)

**Comment by FCRodriguez7** [comment]
Released management v2.45.7
