### ISSUE TITLE
Delete PTIFF images from top level of DCE S3 bucket

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#141]
After all dependencies on the 'flat' (non-pairtree) file structure for PTIFFs have been removed, delete the images.

See #111

**Comment by mark-dce** [comment]
![image](https://user-images.githubusercontent.com/3064318/82593136-9e6b7280-9b67-11ea-9ead-b55e529487cc.png)

**Comment by mark-dce** [comment]
![image](https://user-images.githubusercontent.com/3064318/82603134-c2cf4b00-9b77-11ea-8cb3-6550a95e6258.png)
