### ISSUE TITLE
Display archival context in search result list

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1414]
**Story**

We would like to indicate to the user which repository and collection contains an object.

**Acceptance**
- [ ] Display the information in the search results list. 
  - [ ] For objects with ASpace source data, format each value from `ancestorTitles`, delimited by `>`   See #1413 for field names in Solr.
- [ ] Use the same horizontal spacing/alignment as the other fields (there's no space in the mock below)
Display does not include links.

 ![Screen Shot 2021-06-28 at 1.28.18 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/c791d68e-1dd6-4fe5-9873-d329bc203a22)

**Comment by MaggieZhaoYale** [comment]
@mikeapp Is link required? Thank you.

**Comment by mikeapp** [comment]
No, we need to do other work before we know what the links will look like.

**Comment by MaggieZhaoYale** [comment]
Thank you @mikeapp I got you.
