### ISSUE TITLE
Display archival context in individual object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1415]
**Story**

Same as #1414, but for the object page.

**Acceptance**
- [x] Archival context value (same as #1414) is displayed beneath the title as shown.
No links are required for now!

![Screen Shot 2021-06-28 at 1.39.41 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d19dab2f-b884-4776-9f61-116a46ac8a51)

From XD:
![Screen Shot 2021-06-29 at 2.44.00 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7828346e-478c-4e79-9dfb-5403bbe3a15e)

**Comment by FCRodriguez7** [comment]
I left a comment on the pr this morning.

**Comment by FCRodriguez7** [comment]
The bread crumbs don't appear to be links or be styled similar to the proposed design. 

![Screen Shot 2021-07-09 at 2.03.02 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b9acc06a-4aae-4434-8f0a-c86fb4b451cc)
