### ISSUE TITLE
Add "Collection Note" field to IIIF Manifest

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1416]
**Story**

The IIIF Manifest metadata should indicate the collection that contains the object.

**Acceptance**
- [x] Add a field to the Manifest
  - Label is "Collection Note"
  - Value is the same as #1414.  It should be text only, not a link
  - See the mockup for position within the metadata field list.  **Note that the collection title/date fields will also need to be added, so position under Call Number for now.**
- [x] Only add this field if the ancestor hierarchy is present

 ![Screen Shot 2021-06-28 at 1.43.57 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/2ac79413-0de6-4e45-9442-1b1af2ef6d8b)

**Comment by FCRodriguez7** [comment]
The current of the array for collection notes:

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/18ca5d29-6dbd-4dba-ab83-3c550a4d80cf)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-management/pull/706

The current image of it: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/276a3068-f57a-4ac5-bd6d-e8abb07f09e4)

**Comment by mikeapp** [comment]
Note that the actual breadcrumb data should begin with the repository and then narrow down, so the example should begin with Beinecke.

**Comment by FCRodriguez7** [comment]
I think you want the array in the reverse order.  The current code just puts the array on the screen in the original order.  I can reverse the order of the array.

**Comment by mikeapp** [comment]
* Yes, please have the displayed list start with the largest scope (i.e., Repository), as in the mock image.
* The `sourceNote` mapping needs to stay as well, please add it back.    This will provide data in that field for Ladybird objects.

**Comment by mikeapp** [comment]
collections-demo is still showing reverse order of the hierarchy:

![Screen Shot 2021-07-15 at 8.59.24 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/2486e7db-0f4f-44da-a1e0-4b709dbd9f00)!

[Screen Shot 2021-07-15 at 8.36.50 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/57e7eb90-9005-4299-8382-bd228f07b696)

**Comment by FCRodriguez7** [comment]
Made additionally modification and additions to the feature code: https://github.com/yalelibrary/yul-dc-management/pull/716/files

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-management/pull/720

**Comment by FCRodriguez7** [comment]
The code modification on the test environment:

![1416_Feature](https://user-images.githubusercontent.com/41123693/126560631-7393f9c0-f850-4c76-8b87-13acc61677ad.gif)
