### ISSUE TITLE
Implement "Repository" facet

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1417]
**Story**

We'd like users to be able to facet by repository.

**Acceptance**
- [x] Add a "Repository" facet, based on the value indexed in #1413.  It should appear immediately after the "Access" facet.  Mockup:

![Screen Shot 2021-06-28 at 1.49.10 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/2849f464-d653-48b7-ac8e-3fb4d05189a4)

**Comment by FCRodriguez7** [comment]
The feature looks good.

https://images.zenhubusercontent.com/242185115/f08d2a3d-690c-40c5-8f4d-b5a95114e79f/screen_recording_2021_07_02_at_12_41_56_pm.mov
