### ISSUE TITLE
Create "Collection Title" facet

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1419]
**Story**

We'd like to be able to facet on Collection Title.  

**Acceptance**
- [x] Add a facet "Collection Title" immediately below the new "Repository" facet (see #1417).   See #1413 for the Solr field name.

**Comment by FCRodriguez7** [comment]
The feature looks good. 

[Uploading... Screen Recording 2021-07-02 at 12.41.56 PM.mov]
