### ISSUE TITLE
Decision required: objects with with full text for some children

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1423]
**Story**

We currently:
- consider an object to have full text if the first page has full text
- consider it an error when objects with full text (i.e., the first page has full text) do not have full text for every subsequent page

What happens if a reassociation is made that would introduce children w/o full text?   Currently:
- if the first page has full text, indexing would fail due to later pages missing full text
- if the first page does not have full text, the object would be considered not to have full text at all

Since it seems likely that this could occur in the future, we need to decide how to handle it.
Suggestions:
* Add a third option to the facet (currently "Yes" or "No") "Partial" 
* Display a warning to the user on the object page
* Adjust disclaimer text that appears under the search box when searching full text.

All of this will require some additional dev work.

**Comment by lindsaymking** [comment]
"Partial" seems like a good option to add, even though I get why we didn't want to originally. It is a likely scenario that some digitized objects exist where there is no text on some of the pages, including the first page, even if all of the text IS transcribed.

IMO, a warning to the user on the object page makes more sense than trying to create a brief disclaimer for the search box.

Could there be a different way of determining which objects have full text?

**Comment by mikeapp** [comment]
We can definitely check whether every page has transcription and flag the object as partial if there are pages without a corresponding transcription file.   

I think there's a flag in From The Page that indicates whether the object was transcribed completely, Beinecke will need to be sure these are set correctly before we process their data.

**Comment by mikeapp** [comment]
Decision:
* Check all children for availability of full text
* Use 'partial' if any children do not have a corresponding full text file
