### ISSUE TITLE
Export list of all parent + child OIDs from production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1424]
**Story**

Beinecke would like to conduct an audit of OIDs in the system vs. their legacy storage before we delete the derivative store from the old DL.

**Acceptance**
- [x] Export a list of all children from the production DB  in a csv that contains:
      - child oid
      - child's parent oid

**Comment by mlooney** [comment]
[https://app.zenhub.com/files/242185115/0fd6ad3a-0765-45b5-9a1d-b728f9a4b646/download](https://app.zenhub.com/files/242185115/0fd6ad3a-0765-45b5-9a1d-b728f9a4b646/download)
