### ISSUE TITLE
Check for child sequence problems in production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1426]
**Story**

We'd like to check for children with ambiguous sequence ordering in production.   This can result in unexpected behavior since the children will then be (re)ordered by OID when updated.

**Acceptance**
- [x] Query for where a parent has more than one child OID with the same `order` value.  Output would look like this (e.g., two children for parent 1 have a 0 `order`):

```
 parent_oid | z_order | z_count 
------------+---------+---------
          1 |       0 |       2
```

**Comment by mlooney** [comment]
This yielded zero rows, and I think it's the query we want (I'm willing to be corrected by a sql guru tho)


```sql

select co.parent_object_oid k, co.order o, count(co.order) c 
        from parent_objects po 
        join child_objects co on (co.parent_object_oid=po.oid) 
        group by k,o 
        having count(co.order) > 1 ;

```
