### ISSUE TITLE
Create new Solr Version and Deploy if Necessary

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1429]
**Story**

Solr config needs to be updated for full text to work properly.  We handle this using migrations and schema api for the already existing cores, but should probably cut a new version on the solr repo and get a new versioned container.

See: https://github.com/yalelibrary/yul-dc-solr/pull/23

**Acceptance**
- [ ] Create a new version of the Solr image
- [ ] Try deploying the new image on test

**Comment by mikeapp** [comment]
@mlooney @martinlovell  I think we can close this, it was incorporated into the memory flag update?
