### ISSUE TITLE
Provide deployment timestamp accessible to apps running in the cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#143]
**STORY**
As a team member and stakeholder, I want to be able to know when the last code was successfully deployed to a cluster, so I can understand what version of the code I'm interacting with.

**ACCEPTANCE**
-  [x] Containers deployed to the cluster have access to a timestamp for the last deployment - see #139

**NOTES**
Consider dropping a timestamp file in the container or setting an environment variable.

**Comment by dl-maura** [comment]
Jez is working with Bess looking at the CI and creating the timestamp

**Comment by JzGo** [comment]
PR open for this: https://github.com/yalelibrary/yul-dc-blacklight/pull/57

**Comment by fnibbit** [comment]
Merged this PR; added a PR to put the same command in the docker-compose in yul-dc-camerata.  ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/5b252343-3830-4cbd-8189-c2faa93d4562)
