### ISSUE TITLE
Parent object page: behavior after clicking update metadata

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1431]
**Story**

After clicking the "update metadata" button on the individual parent object's page I am taken back to the listing of all parent objects.  I would like to stay on the individual object page and see a success message.

**Acceptance**
- [x] The user should remain on the same page rather than return to the list.
- [x] A flash confirmation message should be displayed:   "This object has been queued for a metadata update."

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/699


![UpdateMetadata](https://user-images.githubusercontent.com/32851993/124937754-b0131200-dfd5-11eb-81f1-cd8cffe46727.gif)

**Comment by FCRodriguez7** [comment]
Released management v2.45.8
