### ISSUE TITLE
Fix font style on individual parent and child object, sets, user pages

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1433]
**Story**

Alisha pointed out during sprint planning that we haven't applied the font styles to some pages.   

**Acceptance**
Apply font style (consistent with the parent object list page, etc.) to the single record view pages for:
- [x] parent
- [x] child
- [x] user
- [x] admin set

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/700

**Comment by FCRodriguez7** [comment]
Released management v2.45.9
