### ISSUE TITLE
solr index failed 

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1436]
Story: 
Two BRBL object ingested from Goobi Solr indexing failed
https://collections.library.yale.edu/management/batch_processes/4171  31912890
https://collections.library.yale.edu/management/batch_processes/4172  31912933
Solr indexing failed due to undefined method `include?' for nil:NilClass

- [ ] identify the cause of failures

- [ ] fix it and re-ingest

**Comment by MaggieZhaoYale** [comment]
date_structure is  null. Will check DateExtractorFunction.java in Marc4JExtract

**Comment by DraxIndustries79** [comment]
This is waiting for the MC deployment
