### ISSUE TITLE
Don't write IIIF Manifests or descriptive metadata to S3 if unchanged

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1437]
**Story**

We are now versioning Manifests and descriptive metadata in S3, so we really don't want to perform unnecessary writes. 

**Acceptance**
- [x] Check the S3 `etag` against the MD5 of the Manifest and don't write it if the Manifest/metadata if it is unchanged.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/695

**Comment by FCRodriguez7** [comment]
Released management v2.45.8
