### ISSUE TITLE
Add parent title and call number to export child OIDs batch job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1439]
**Story**

The Beinecke DSU has requested two additional fields be included in the Export Child OIDs batch job.  Both are from the Parent Object:
* Title
* Call number

**Acceptance**
The batch job exports include:
- [x]  The parent object's title(s), pipe-delimited (`|`),  in a column with the header `parent_title`. 
- [x] The parent object's call number, in a column with the header `call_number`

**Comment by MaggieZhaoYale** [comment]
parent title is already in the export child OIDs batch job csv. https://github.com/yalelibrary/yul-dc-management/blob/4335d359347c5706cb7f60d52224277cdff25a7c/app/models/concerns/csv_exportable.rb

**Comment by mikeapp** [comment]
OK, thanks,  leave that as-is.

**Comment by FCRodriguez7** [comment]
Released management v2.45.12
