### ISSUE TITLE
Verify SOLR child object count is updated after reassociation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1440]
**Bug Report**

Beinecke DSU reported that the child object count did not update properly sometimes after a reassociation job was run.  No further information is available.

**Acceptance**
- [x] Test reassociation jobs, including a job that removes all children from a parent.
- [ ] If a bug is found, fix.

**Comment by martinlovell** [comment]
Seems to work:
Tested manually and added test https://github.com/yalelibrary/yul-dc-management/pull/717

**Comment by FCRodriguez7** [comment]
Released management v2.45.12
