### ISSUE TITLE
Changes to Parent Object should trigger reindex/manifest/PDF build

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1442]
**Story**

If you manually edit fields on a Parent Object, such as the catalog ID or IIIF-related fields, and click the "Update Parent Object" button, the changes are saved to the database but the various downstream representations are not updated.

![Screen Shot 2021-07-08 at 4.24.34 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/351e8d29-4247-4364-80a9-e6e0f1ac44e8)

**Acceptance**
- [x] Trigger metadata update workflow
- [x] Change button text to read "Save Parent Object And Update Metadata"

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/713

![MetadataQueAfterSave](https://user-images.githubusercontent.com/32851993/125653285-7c42a2c7-fc47-452f-a7d4-f1792ebea9f6.gif)

**Comment by FCRodriguez7** [comment]
Released management v2.45.12
