### ISSUE TITLE
SPIKE: Role setup in Camerata

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1444]
**Story**

We need to be able to provide a role for ECS tasks via camerata.

**Acceptance**
- [ ] Camerata sets the correct role(s) during ECS deployment

Note:  This is part of an overall goal to build more in-house Yale knowledge in camerata, so its a good opportunity for pairing.

**Comment by mlooney** [comment]
Can we be more specific on which role we want set on what resource?

**Comment by kbcarter** [comment]
We were able to successfully configure the role but IIIF and workers may require code changes to use task role.

**Comment by DraxIndustries79** [comment]
Will leave this here as a reminder, but will likely make a new ticket if there's more work/investigation to be done.

**Comment by mikeapp** [comment]
The property name is `task_role_arn`  but in the branch the value was the role name, not the complete ARN.   The examples I found online do use the full ARN, could that be the problem?

**Comment by mikeapp** [comment]
* Role appeared in management console, so ARN was not the issue.
