### ISSUE TITLE
Strip HTML from ancestor values

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1448]
**Story**

HTML is being displayed in the archival breadcrumbs:

![Screen Shot 2021-07-09 at 11.40.42 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3801ddec-8375-4dce-a82b-2c5ed2d5f77d)

We should remove tags for now.

**Acceptance**
When indexing:
- [ ] strip HTML tags from `ancestorDisplayStrings_tesim`
- [ ] strip HTML tags from `ancestorTitles_tesim`

**Comment by martinlovell** [comment]
This should be done already in Metadata cloud.  Maybe the metadata is old?

See:
https://metadata-api-test.library.yale.edu/metadatacloud/api/aspace/repositories/11/archival_objects/607814?mediaType=json
(New mapping with repository)

https://metadata-api.library.yale.edu/metadatacloud/api/aspace/repositories/11/archival_objects/607814?mediaType=json
(Old mapping without repository)

**Comment by mikeapp** [comment]
Thanks, I thought this sounded familiar.   We probably need to run a metadata refresh on test and uat.

**Comment by mikeapp** [comment]
Confirmed, looks good after a metadata refresh.
