### ISSUE TITLE
Show collection hierarchy on Blacklight object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1449]
**Story**

As a user, I would like a visual display of the hierarchy archival object location.

<details> 
<summary>
Change in Format
</summary>

![af4f0c39-1e04-4c61-a352-33d81cad9ea5.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3f8eab62-c19e-4dab-8585-c73bfe638d0c)
</details>

<details> 
<summary>
Proposed Image at First
</summary>

![Screen Shot 2021-07-09 at 11.59.07 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/af4f0c39-1e04-4c61-a352-33d81cad9ea5)
</details>

**Acceptance**
- [x] Consult with Tracy on the icon selection
- [x] Display the ancestor hierarchy as depicted above [ancestor display strings, not the title]
- [x] Show top- and bottom-most hierarchy with an expander (`...`) as described in #1454
- [x] Do not make the items links for now

**Comment by tmacmath** [comment]
Here is a link to the ArchivesSpace stylesheet - I'm trying to get more info, because it seems as if they are either using custom icons, or icons from a previous version of IcoMoon:

https://github.com/archivesspace/archivesspace/blob/master/frontend/app/assets/stylesheets/archivesspace/icons.less

**Comment by tmacmath** [comment]
Until we get a bit more info, you can use this stack icon as a placeholder: 

![image.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/f56547ca-90f7-42f1-85a1-3ee9946384f2)

**Comment by tmacmath** [comment]
Just got more info: Lyrasis used Font Awesome icons for ArchivesSpace:

[https://fontawesome.com/v5.15/icons/layer-group?style=solid](url)

**Comment by FCRodriguez7** [comment]
Should the context tree be the first item displayed in the collection information block of the show page?

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7f80c4a6-5780-4e90-84d7-07304e8df0fb)

**Comment by tmacmath** [comment]
This was the original design: 

![image.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/91682aca-0b8d-40f0-819f-9eafa532c75e)

**Comment by FCRodriguez7** [comment]
We add the (...) 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7e9a31b0-f28e-42e8-816d-ef2a031c7506)

**Comment by mikeapp** [comment]
The requirements doc says it should show the top three and bottom three levels by default.  Only additional intermediate levels should collapse.

**Comment by FCRodriguez7** [comment]
The description in ticket 1454 is "the breadcrumbs is: Repository > Collection > Top most series ... Grandparent > Parent. Clicking the ... displays the full hierarchy."   

The description has three top levels and only two bottom levels.  Is that a correct interpretation of the description?

**Comment by FCRodriguez7** [comment]
@tmacmath Eric and I understand the depicted design.  However, the design does not take into account for the additional fields below container / volume information.  That was the question we asked today.

**Comment by mikeapp** [comment]
Sorry, you are correct.  We do need a design from @tmacmath for the expander but could use what you have as a placeholder for now...

**Comment by FCRodriguez7** [comment]
The pr: https://github.com/yalelibrary/yul-dc-blacklight/pull/609

**Comment by FCRodriguez7** [comment]
Feature on Demo: 

![Archival tree on single item page.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c9b22e21-cd0a-4045-88e3-d99fb8d46836)

**Comment by mikeapp** [comment]
Looks great!
