### ISSUE TITLE
Link to ASpace 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1450]
**Story**

For ASpace items, link to the ASpace record.

Proposed Image: 
![Screen Shot 2021-07-09 at 12.12.50 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0bddd4d0-ed84-4b18-a013-2ac1c2638331)

Actual Feature and Function:
![ASpace Link.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8b417f40-089a-413a-bf3e-59470d2d8aba)

**Acceptance**
For items with an `archiveSpaceUri` value:
- [x] Add a link with the text and icon, as shown above
- [x] The URL of the link should concatenate "https://archives.yale.edu" and the `archiveSpaceUri` value
- [x] The link should open in a new window.

**Comment by FCRodriguez7** [comment]
The progress so far. 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f5a74842-0435-48c5-9a86-fa6858ea8680)
