### ISSUE TITLE
Display Finding Aid link

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1451]
**Story**

If a Finding Aid exists, we'd like to link to it.  Wireframe:

![Screen Shot 2021-07-09 at 1.34.13 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7c6d0731-4f6d-488a-96c6-05c4a6dd89a9)

**Acceptance**
- [x] Use the first URL in `findingAid_ssim` for the link
- [x] Use text, icon, and position as in the wireframe; note that the link includes the collection title.
- [x] Open the Finding Aid in a new window

TODO: How to handle multiple?

Note/Decision:  We are going to check for collection_title_ssi

**Comment by FCRodriguez7** [comment]
Question for standup:
The condition must have collection_title_ssi

**Comment by mikeapp** [comment]
We should also talk about whether we want to implement this before the blocking issue in Metadata Cloud is cleared.

**Comment by FCRodriguez7** [comment]
Here is a ladybird example: 
https://collections-demo.library.yale.edu/catalog/2002046

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/fb77a5f7-d3a0-4f56-a5d8-0eeb7357e37d)

**Comment by FCRodriguez7** [comment]
If collection title and find aid has one element in each, it should be displayed.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/617
