### ISSUE TITLE
Show Collection Title facet when a Repository is selected

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1452]
**Story**

The Collection Title facet should display only after a Repository facet value has been selected.

Note: a subsequent issue will address the behavior when the user removes a Repository facet from their search criteria.

**Acceptance**

- [ ] The Collection Title facet does not display by default
- [ ] The Collection Title facet displays when a Repository facet value is selected 
  - Note: this should follow the default Blacklight behavior, i.e., the facet won't display if there is no Collection Title data for that repository.

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/606
