### ISSUE TITLE
ON HOLD: Remove Collection Title facet search condition when the user removes the Repository search condition

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1453]
**Story**

Consider the case where a user selects a Repository facet, then selects a Collection Title facet.   The user might then remove the repository criterion, but their search will remain the same, since the Collection Title is a subset of the repository.     Instead, we'd like to the removal of the Repository facet to also clear the Collection Title facet selection, so the new search will not be restricted to a single repository.

![Screen Shot 2021-07-12 at 10.23.49 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/dd67560e-8ccc-4c52-9557-270af089f7a4)

**Acceptance**
- [ ] Removing the Repository facet from the search criteria also removes the Collection Title.

**Comment by DraxIndustries79** [comment]
JQuery?  Solr?  None of the above?

**Comment by edejesusyale** [comment]
The date slider had issues with this as well and was addressed in the following commit:
https://github.com/yalelibrary/yul-dc-blacklight/commit/214510dc06af44229a87a2fcf0264312db4fc054

It seems that I just removed the date parameter from the request url itself in the "X" link.

**Comment by DraxIndustries79** [comment]
@edejesusyale will pair with Kait and JP

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/636

**Comment by mikeapp** [comment]
I'm seeing some unexpected behavior on collections-demo, the search condition remains but with added elements:

![Screen Shot 2021-08-30 at 11.47.24 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/4c8a7a74-a52a-4fef-8e62-15d8f86f8fbd)

**Comment by K8Sewell** [comment]
Hi Mike, welcome back :) Thanks for checking this out.  Whenever you get a chance would love to know how you were able to see this as I was unable to replicate the behavior on 'collections-demo' but JP and I were able to add the 'found in' constraint to also be removed when 'Repository' is removed with this PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/651 - would be great to make sure this is the direction you wanted this to move.

**Comment by mikeapp** [comment]
Sorry, I was clicking the breadcrumb, which is not the same as the collection title.  Somehow the removal of the repository causes the "Found In" header to add the last bit of text at the end ("Search_field=All_fields") but I'm not sure whether it is related to this PR at all.

To replicate:
1. Limit by Repository to Beinecke
2. Click on a link in the breadcrumb/hierarchy for one of the search results 
![Screen Shot 2021-08-30 at 2.48.21 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a9e94ed1-facc-474b-a608-357a11b588ab)
3. Remove the Repository restriction
![Screen Shot 2021-08-30 at 2.48.31 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7043d063-ec78-41b9-800d-348d8874173f)

**Comment by K8Sewell** [comment]
Hi Mike, I believe it is related to this PR.  By removing the 'Found In' when the repository is removed this behavior would no longer exist.  However, is that the desired behavior?  To remove 'Found In' when 'Repository' is removed.

**Comment by mikeapp** [comment]
I hate to ask, but can we revert this for now?  I want to talk to the stakeholders.

**Comment by K8Sewell** [comment]
Codebase has changed to much to do an automated revert but I can put up a PR this afternoon to pull out the changes and I'll make that second one a draft so it doesn't accidentally get merged.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/652 

PR to revert feature

**Comment by DraxIndustries79** [comment]
On hold pending review and decisions.
