### ISSUE TITLE
Collapse breadcrumbs with many levels of hierarchy

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1454]
**Story**

Some archival records will have many levels of hierarchy.   We'd like to display the top- and bottom-most levels, with a "..." in between,  to keep the display manageable.   Users should be able to click the "..." to display the full hierarchy.

**Acceptance**
- [x] Default display of the breadcrumbs is:  ` Repository > Collection > Top most series ... Grandparent > Parent`. Clicking the `...` displays the full hierarchy.
   - [x] in the breadcrumbs on the search results page
   - [x] in the individual object page breadcrumb that appears immediately below the title

**Comment by mikeapp** [comment]
I will link possible fixtures here:

* https://collections-demo.library.yale.edu/catalog/2019635

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/605

(Hierarchy in images were manipulated to be large; the repeats in the hierarchy are not an error.)

![expand-hierarchy-show.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/0f78caf5-1f2b-46f5-ba0e-847069018499)

![expand-hierarchy-index.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/5a99ff6f-affa-40ca-98ae-146778b82961)
