### ISSUE TITLE
Index archival Ancestor Titles to allow searching with a hierarchy

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1456]
**Story**

We have facets for Repository and Collection Title, but these are just the top two levels of the archival hierarchy.   There may be many additional levels present in the archive and users may wish to filter their search to objects at one of these lower levels.   

Consider a hierarchy like this one, displayed on the result page:
`Beinecke Rare Book and Manuscript Library (BRBL) > Carl Van Vechten Papers Relating to African American Arts and Letters (JWJ MSS 1050) > Photographs > Color Slides > Portraits`

We'd like users to be able to click any level and run a search for items at that level.  So clicking on Photographs would run a search for items that match:
`Beinecke Rare Book and Manuscript Library (BRBL) > Carl Van Vechten Papers Relating to African American Arts and Letters (JWJ MSS 1050) > Photographs`

To enable this we must first index the ancestor data appropriately.

See See https://cwiki.apache.org/confluence/display/SOLR/HierarchicalFaceting for examples of tokenizing and indexing multiple levels of hierarchy.  

**Acceptance**
- [x] Index the data into a new Solr field 'ancestor_titles_hierarchy_ssim` based on the AncestorTitles MC field.
- [x] Create tests to demonstrate retrieval of data records based on searches of different levels of the hierarchy, such as the "Photographs" example above.

**Comment by kcompsci** [comment]
Maggie and I met and we are a bit unclear on a couple of items. First, in reference to "_We'd like users to be able to click any level and run a search for items at that level. So clicking on Photographs would run a search for items that _match:__ we'd like a better understanding of _that match_. What are we matching? If you take a look at how Findit implements archival objects here is an example: https://findit.library.yale.edu/catalog/digcoll:1193001. In Solr it's breadcrumbs_ssm field is indexed as: <str><a href="/catalog/digcoll:1191497">Henry A. Kissinger papers, part III</a> > <a href="/catalog/digcoll:1192508">Series VII. Photographs</a> > <a href="/catalog/digcoll:1192999">General</a> > Broome Technical Community College</str>. If you click on a link within the breadcrumbs you are re-directed to the single item page of that particular object. Example: If you go to the above findit link and click on the "Series VII. Photographs" hyperlink inside the breadcrumbs you will be re-directed to the single item page of that object "https://findit.library.yale.edu/catalog/digcoll:1192508". Then when you are there you can search within the Series VII. Photographs folder for what you specify in the search within box located to the left of the screen.

**Comment by mikeapp** [comment]
In DCS there is no item that corresponds to the series, or other intermediate level.   So clicking on `Henry A. Kissinger papers, part III > Series VII. Photographs >` needs to return any Parent Object that has an `ancestor_titles_hierarchy_ssim` that contains that string.

The "PathHierarchyTokenizerFactory" section in the Solr documentation I linked suggests that you would index into `ancestor_titles_hierarchy_ssim` the following set of values for this record (they use `/` for the delimiter, I use ` > `):

`Henry A. Kissinger papers, part III >`,
`Henry A. Kissinger papers, part III > Series VII. Photographs >`,
`Henry A. Kissinger papers, part III > Series VII. Photographs > General >`,
`Henry A. Kissinger papers, part III > Series VII. Photographs > General > Broome Technical Community`,
`Henry A. Kissinger papers, part III > Series VII. Photographs > General > Broome Technical Community > College >`

Then when a user clicks on "General", the system would issue a search for `Henry A. Kissinger papers, part III > Series VII. Photographs > General >` and find this record (and any others with that value).

There are other approaches though so look at that documentation and talk to @edejesusyale who was working on a similar problem for Quicksearch.

**Comment by kcompsci** [comment]
We completed step 1:

  "ancestor_titles_hierarchy_ssim": [
    "Beinecke Rare Book and Manuscript Library (BRBL) > ",
    "Beinecke Rare Book and Manuscript Library (BRBL) > Robert Giard papers (YCAL MSS 702) > ",
    "Beinecke Rare Book and Manuscript Library (BRBL) > Robert Giard papers (YCAL MSS 702) > February 2005 Acquisition > ",
    "Beinecke Rare Book and Manuscript Library (BRBL) > Robert Giard papers (YCAL MSS 702) > February 2005 Acquisition > Professional papers > "
  ],
  "ancestorTitles_tesim": [
    "Professional papers",
    "February 2005 Acquisition",
    "Robert Giard papers (YCAL MSS 702)",
    "Beinecke Rare Book and Manuscript Library (BRBL)"

**Comment by MaggieZhaoYale** [comment]
ancestor_titles_hierarchy_ssim as facet.field in solr:

![Screen Shot 2021-07-26 at 1.54.08 PM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/a54bcb54-708f-4655-b4a6-956c2fdaa8a1)

**Comment by MaggieZhaoYale** [comment]
Example in demo:
https://collections-demo.library.yale.edu/management/parent_objects/16847708
in solr record:
 "ancestor_titles_hierarchy_ssim": [
    "Beinecke Rare Book and Manuscript Library > ",
    "Beinecke Rare Book and Manuscript Library > Photographs of prominent African Americans (JWJ MSS 76) > ",
    "Beinecke Rare Book and Manuscript Library > Photographs of prominent African Americans (JWJ MSS 76) > Series II. Photographs of Blacks > ",
    "Beinecke Rare Book and Manuscript Library > Photographs of prominent African Americans (JWJ MSS 76) > Series II. Photographs of Blacks > Photographs collected by Grace Nail Johnson > "
  ],
