### ISSUE TITLE
[CHECK] Don't include code in Repository field value

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1460]
**Story**

Repository names should not include the identifier code, such as `(BRBL)`, in the facet value.

This may be more easily fixed upstream in Metadata Cloud, YAMS folks may be able to point us to a field that does not have the unwanted text.

**Acceptance**
- [x] When indexed display repository values do not include the identifier code

**Comment by martinlovell** [comment]
The repository JSON from archives space has a "display_string" and "name".
It looks like the display_string is the name + (code).

It may be that mapping "name" rather than "display_string" would work, but we need verification from YAMS.

**Comment by martinlovell** [comment]
Metadata cloud UAT and Test have been updated so that "name" is used rather than "display_string".
