### ISSUE TITLE
Add call_number column to batch process reassociate child oid template

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1461]
Accepte

- [x] call_number added in the template
![Screen Shot 2021-07-15 at 2.49.39 PM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/05cb05ff-2744-4e9b-b70d-3afbabd77b66)

**Comment by FCRodriguez7** [comment]
Released management v2.45.12
