### ISSUE TITLE
Remove link from harmful content statement.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1464]
**Story**

The link to the statement on harmful content is in flux.

**Acceptance**
- [x] Remove the link from the Blacklight home page, in red below:

![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/2c78d395-88dd-4c0a-b889-d32e4351a89e)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2021-07-19 at 2.11.09 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ee8bda7f-e70a-4695-8d2f-282969f81b52)

**Comment by FCRodriguez7** [comment]
The PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/610

**Comment by edejesusyale** [comment]
In release: Released blacklight v1.44.3

**Comment by motropuk** [comment]
@FCRodriguez7 @mikeapp Apologies for the late change here, but we have been asked to do this differently. In short, we now just need to replace the link that we point to at the end of this statement. 

So we need to retain the text as it currently exists, but the link here in blue now need to point to https://guides.library.yale.edu/statementharmfulcontent 

[Screen Shot 2021-07-16 at 14.36.17.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/e82f274f-c5a3-4164-8535-70eecf58c00e)

**Comment by FCRodriguez7** [comment]
@motropuk I modified the link to the one provided. 

The PR is https://github.com/yalelibrary/yul-dc-blacklight/pull/611
