### ISSUE TITLE
"Update Parent Objects" batch job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1466]
**Story**

Beinecke DSU needs to update Parent Object fields for which the Management application serves as the primary authority.

**Acceptance**
Implement an "Update parent objects" batch job.  
- [x] The input sheet must contain a column for the `oid` and columns for any fields to be updated.
- [x] **If a column does not exist in the spreadsheet, do not update the data for that field.** 
- [x] As a final step, initiate a metadata update job for each object that is updated by this batch job.

The job updates the following fields:
- [x] Metadata source  (validated, see Edit Parent Object screen for controlled fields)
- [x] Visibility (validated...) 
- [x] Rights Statement
- [x] Extent of digitization (validated)
- [x] Digitization note
- Voyager identifiers
  - [x] Bib
  - [x] Holding
  - [x] Item
  - [x] Barcode
- [x] ASpace URI
- [x] IIIF viewing direction (validated)
- [x]  IIIF viewing hint (validated)

**Comment by K8Sewell** [comment]
PR ready for review once AWS key is sorted out and CI is rerun - https://github.com/yalelibrary/yul-dc-management/pull/742

https://images.zenhubusercontent.com/242185115/35d33db7-d684-4c52-9c3e-ce74dbf304c4/screen_recording_2021_08_11_at_03_40_24_pm.mp4

**Comment by martinlovell** [comment]
Should we skip the whole row if one of the columns fails validation, or just ignore that column?

**Comment by mikeapp** [comment]
I think that's fine for now but possibly not ideal from the user's point of view.    We'll see how it works for DSU in practice.

**Comment by K8Sewell** [comment]
We've updated the PR with detailed messaging for controlled vocab and the PR is ready for review again.
