### ISSUE TITLE
Fix abstract concatenation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1468]
**Story**

Abstract notes are also receiving the ", and" concatenation treatment,  see https://collections.library.yale.edu/catalog/17451921.  

Instead, those notes should appear as a paragraphs (or, at least, have line breaks, preferably two).

**Acceptance**

- [x] Use `<p>` tags for the notes, rather than `, ..., and`
![Screen Shot 2021-07-20 at 2.23.38 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/07f8467e-4e2b-453b-9d2a-80377b16bd83)

**Comment by martinlovell** [comment]
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/40909135-58a7-4e0e-9e93-01a6d1d136ab)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/628#pullrequestreview-723706991

**Comment by FCRodriguez7** [comment]
Released blacklight v1.44.7

**Comment by mikeapp** [comment]
Looks good https://collections-uat.library.yale.edu/catalog/2002755
