### ISSUE TITLE
S3 delete permissions

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1469]
**Story**

The application needs to delete stale PDFs - i.e., when a parent is deleted.
The image server needs to delete stale images from its cache.

**Acceptance**
Grant the application  permissions to delete keys under these prefixes:
- `/pdfs/*`
- `/cantaloupe/*`

for the buckets:
- [x] yul-dc-image-samples
- [x] yul-dc-uat-samples
- [x] yul-dc-demo-samples
- [x] yul-dc-prod-images

and one more that I missed:
- [x] yul-dc-dev-image-samples

**Comment by kbcarter** [comment]
Updated DigitalCollectionsRole role with with following permissions
```
{
            "Sid": "S3BucketDelete",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::yul-dc-image-samples/pdfs/*",
                "arn:aws:s3:::yul-dc-image-samples/cantaloupe/*",
                "arn:aws:s3:::yul-dc-uat-samples/pdfs/*",
                "arn:aws:s3:::yul-dc-uat-samples/cantaloupe/*",
                "arn:aws:s3:::yul-dc-demo-samples/pdfs/*",
                "arn:aws:s3:::yul-dc-demo-samples/cantaloupe/*",
                "arn:aws:s3:::yul-dc-prod-images/pdfs/*",
                "arn:aws:s3:::yul-dc-prod-images/cantaloupe/*"
            ]
        }
```

**Comment by mikeapp** [comment]
Thanks!  @jpengst can check whether lets the delete job do its thing.

**Comment by mikeapp** [comment]
@kbcarter  I forgot to include the bucket developers use for local dev work, can you also add permissions for: `yul-dc-image-samples` ?

**Comment by kbcarter** [comment]
@mikeapp, yul-dc-image-samples is already apart of the policy.

**Comment by mikeapp** [comment]
@kbcarter  Apologies, the additional bucket is `yul-dc-dev-image-samples`

**Comment by kbcarter** [comment]
@mikeapp, I've add the missing bucket to the policy
