### ISSUE TITLE
Investigate image viewer errors

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1470]
**Story**

We're seeing UV freeze when users click on multiple thumbnails from  large objects.   The user has to close the browser window to continue.

**Acceptance**
- [x] Restart the image tasks and test again.  It's possible that this is due to a misbehaving image server.  (also added to the weekly deployment ticket #1463 so check whether this has already been done)
- [x] Check the WAF rules - do we have any rules that would block based on high numbers of requests?  We tend to see the problem after clicking on multiple image thumbnails in quick succession.  (I think the WAF looks at a 5-minute time span so this seems unlikely.)

Next steps will be to resolve #1469 which should reduce the (very large) number of S3 errors in the image server logs.   This will help with troubleshooting.

**Comment by ra359** [comment]
For alb-yul-dc-prod and alb-yul-dc-staging we currently allow a max of 2,400 requests from a single IP address in a five minute period.

**Comment by mikeapp** [comment]
Thanks.  I'm able to hit the problem within a few hundred requests, so the firewall is probably not the issue.

**Comment by mikeapp** [comment]
I can still reproduce the issue.
