### ISSUE TITLE
Empty metadata category on single object page

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1475]
**Story**
The Subjects, Formats, And Genres category is sometimes empty.  Ex: https://collections-test.library.yale.edu/catalog/16847708

![Screen Shot 2021-07-22 at 2.52.36 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f08643de-7cb5-4d15-97f4-9e43022acf9c)

**Acceptance**
- [x] Don't display the header if all fields are empty.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.45.0

**Comment by mikeapp** [comment]
Looks good on test.
