### ISSUE TITLE
UV freezes when loading images

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1478]
**Story**

On some objects the UV freezes after the user clicks on a few objects.  One example is:  https://collections.library.yale.edu/catalog/31960579   This does not seem to happen on all objects.  I have not been able to reproduce the problem in Mirador.

When the page freezes it becomes completely unresponsive and closing the browser tab is the only way to move forward.

The problem seems to be related to our image server or possibly an interaction with our viewer:
* I reproduced the problem using our manifest in the demo UV viewer at https://universalviewer.io
* I was unable to reproduce the problem using our instance of UV and a manifest from the Bodleian library

So far we have:
* restarted the IIIF Image servers
* checked the firewall rules

**Acceptance**
- [x] Check with DSU about problem images and if there are any differences in structure or technical properties that need to be accounted for
- [ ] Follow up may be to gather a list of tiffs with this issue

**Comment by mikeapp** [comment]
When the UV freezes it is in an infinite loop.  Note the values at the breakpoint:

![Screen Shot 2021-07-23 at 11.51.55 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/4b2935fa-baba-492f-99e2-53544aa37d97)

Also, the images on the problem object above have an unexpected second value in the `tiles` section:

![Screen Shot 2021-07-23 at 3.48.09 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/c0aa90b9-4cb2-4ed6-a50e-aebd2e662d68)

**Comment by mikeapp** [comment]
Confirmed, clicking on the problem image will cause the freeze.   Try `[Slide] 16` in https://collections.library.yale.edu/catalog/31960579 
Its `info.json` contains a `tiles` array with two elements, as show above, see  https://collections.library.yale.edu/iiif/2/31960584/info.json

**Comment by MaggieZhaoYale** [comment]
From McClain:

https://collections.library.yale.edu/iiif/2/31960584/full/!200,200/0/default.jpg
31960584
Corrupt data
The data provided does not follow the specification.
ExifLoader: The data supplied does not seem to contain EXIF data.

**Comment by MaggieZhaoYale** [comment]
<?xpacket end="w"?>
  RichTIFFIPTC Data: <present>, 28 bytes
  Photoshop Data: <present>, 4820 bytes
  EXIFIFDOffset: 0x76858b0
  ICC Profile: <present>, 3144 bytes
TIFF Directory at offset 0x124278960 (76858b0)
  ColorSpace: 1
  PixelXDimension: 8192
  PixelYDimension: 5056
3:01
suspect.tif: TIFF image data, little-endian, direntries=22, height=5056, bps=278, compression=none, PhotometricIntepretation=RGB, orientation=upper-left, width=8192

**Comment by MaggieZhaoYale** [comment]
Mark sent a new image. McClain and I uploaded it and re-process to ptiff.
So far the issue still exists. Martin reminded us that It may also be the IIIF server cache.  It might hold the original for up to 24 hours.
Will check it later.
In the meantime, Mark will check with the photographers. Photoshop might have written some non-standrard data to the embedded metadata.

**Comment by MaggieZhaoYale** [comment]
Reloaded a new image without metadata embedded. Will check again after server cached cleared.

**Comment by mikeapp** [comment]
This is a Cantaloupe issue, not related to the image.  I checked the cached data that backs the `info.json` file and there's one set of size/tile data there.   It's generating the second set on the fly, it appears to impact images that have a dimension that is a multiple of 1024.

**Comment by MaggieZhaoYale** [comment]
Mark trimmed the image, so the widith of that image is 8191 which is not divisible by 1024. It's replaced the previous image.

**Comment by fordmadox** [comment]
The width is still showing up as 8192 here, though: https://collections.library.yale.edu/iiif/2/31960584/info.json. Can someone force that to be updated so that we can test whether this temporary type of hack will work while we wait for whatever patch is needed?  

I also suspect that we could have images with even more tiles than two (at least we'd certainly have a lot more than this one image that has at least two tiles), but I'd have to download all of the JSON files to test since I don't have read-only access to the database :)

**Comment by fordmadox** [comment]
Just a note that the 1-pixel-shave hack works, so now we just need to 1) isolate and patch the bug (is that in UV, since I don't know why multiple title declarations should be an issue?) and 2) find all the other affected images (e.g. https://collections.library.yale.edu/iiif/2/31960902/info.json, which is part of the same object).

**Comment by fordmadox** [comment]
I still don't know exactly what's causing the javascript issues, but two more notes:

- Multiple tiles dos not appear to be the issue, although I'm still unclear on how those are generated.  Anyhow, 
  - 1024 width (e.g. https://collections.library.yale.edu/iiif/2/32134869/info.json, two tiles but no bug)
  - 2048 (e.g. https://collections.library.yale.edu/iiif/2/31964657/info.json, ditto)
  - 4096 (e.g., https://collections.library.yale.edu/iiif/2/31962346/info.json, yep)
- So far, I've only seen the bug when the width is exactly 8192.  That affects 51 images in the "brbl" set, and renders the following object unusable:
https://collections.library.yale.edu/catalog/31960579
https://collections.library.yale.edu/catalog/15484149
https://collections.library.yale.edu/catalog/15604013
https://collections.library.yale.edu/catalog/15814494
https://collections.library.yale.edu/catalog/15497805
https://collections.library.yale.edu/catalog/15824485
https://collections.library.yale.edu/catalog/15811413
https://collections.library.yale.edu/catalog/15483212
https://collections.library.yale.edu/catalog/15476471
https://collections.library.yale.edu/catalog/15536532
https://collections.library.yale.edu/catalog/2012325

**Comment by mikeapp** [comment]
Last week I found examples with multiple tile sets in the Cantaloupe Github discussions, apparently normal (e.g., https://github.com/cantaloupe-project/cantaloupe/issues/401 ), not an artifact of anything we're doing locally.

This OSD bug sounded similar and relates to IIIF tiles, but not sure it's the same thing: https://github.com/openseadragon/openseadragon/issues/1282

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/catalog/31960579 now the UV does freeze on this image
https://collections.library.yale.edu/iiif/2/31960584/info.json shows 8091. There is one tile set in this image.

**Comment by fordmadox** [comment]
Thanks!  Can we try the same approach of explicitly closing OSD to see if that clears things up when switching to those particular images?

**Comment by fordmadox** [comment]
Also, the behavior appears to be intermittent in some cases (but consistent in others). Here's an intermittent example: . https://collections.library.yale.edu/catalog/15814494.  That one did not work originally when I tested it by switching to the second image... later on it worked fine without delay..  and other times it loops and crashes my browser again  :)

**Comment by mikeapp** [comment]
UV does call `viewer.close();` before setting up the new image.
