### ISSUE TITLE
Add fields to single item view - publication & rights

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#148]
**STORY**
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

**NOTE**
Use the ladybird field name as the label for now.

**ACCEPTANCE**
The single item view for a work displays the metadata for the following fields when they are populated:
- [x] rights
- [x] publicationPlace
- [x] sourceCreated
- [x] publisher
- [x] copyrightDate

**Comment by K8Sewell** [comment]
![Screen Shot 2020-05-26 at 11.29.58 AM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/317937d8-beec-4060-a90e-aa3b38f5d152)

Displays requested fields on show page.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/50
