### ISSUE TITLE
Full Text: allow "partial" full text status

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1481]
**This should be done in a new branch, not `fulltext`**
**The new branch name is next_phase_fulltext_feature**

**Story**

Objects may be partially transcribed, or reassociations may result in the combination of a transcribed object with one that has no transcription.  This should be indicated in the Full Text search facet.   

The current approach of checking the first page for transcription and then assuming that the entire object is transcribed will no longer work.  To avoid performing repeated scans of AWS S3, we will record the full-text status at the child level on ingest. 

**Acceptance**
- [ ] Add a `full_text` field to the Child Object model with type Boolean, defaulting to false
- [x] The Parent Object will need to be refactored to be able to indicate that it has partial full text (i.e. some of its children have `full_text` true and others false).  Currently there's a method to return a boolean (`full_text?`).   All values should be based on the values set in the Child Objects, not a real-time scan of S3.
- [x] If an object has partial full text, in `solr_indexable.rb` index the value "Partial" (currently the value is "Yes" or "No"). 
- [x] the logic ought to account for when the object has partial text

**Comment by DraxIndustries79** [comment]
@FCRodriguez7 will make a ticket for @kbcarter

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-management/pull/756
