### ISSUE TITLE
Add links to hierarchy elements in search results page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1482]
**Story**

In the search results page, each element of the archival hierarchy (i.e., the "Found in" field) should be a link that will scope the user's current search to that level of the hierarchy.  

![Screen Shot 2021-07-26 at 10.04.58 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/59ef42ad-5fe4-4f2f-b434-6475ff3498c5)

**Acceptance**
- [x] Each element of the hierarchy is a link
- [x] Clicking the link restricts the user's search to objects at that level of the collection or below. 
- [x] Other criteria of the user's search remain unchanged.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/622
