### ISSUE TITLE
Add links to hierarchy elements on single object page breadcrumb

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1483]
**Story**

Users should easily be able to restrict their search to a specific archive or component of an archive.  

This ticket is the parallel of #1482 but for the top of the individual object page.

**Acceptance**
- [x] Each element of the hierarchy is a link
- [x] Clicking the link restricts the user's search to objects at that level of the collection or below. 
- [x] Other criteria of the user's search remain unchanged.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/629

**Comment by FCRodriguez7** [comment]
**Demo of Feature:** 

![1483_AddHierarchyLinksBreadcrumbtoSingleItemPage.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2cd4ba02-cfcc-4d22-8701-228e6426ae3a)
