### ISSUE TITLE
Add links to hierarchy from graphical display on single object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1485]
**Story**

Users should easily be able to restrict their search to a specific archive or component of an archive.  

![Screen Shot 2021-07-26 at 10.42.47 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/dba1f5f9-4b21-4e1d-8b58-79f7bbd7b91d)

This ticket is the parallel of #1483 but for the graphical display of the hierarchy in the metadata section of the individual object page.    

Note that the center display uses a metadata field that contains slightly different values than the breadcrumbs and Solr index.   You need to use the index/facet values when searching.   

**Acceptance**
- [x] Each element of the hierarchy is a link
- [x] Clicking the link restricts the user's search to objects at that level of the collection or below. 
- [x] Other criteria of the user's search remain unchanged.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/624

**Comment by FCRodriguez7** [comment]
There is an issue with the demo environment.  I successfully deployed this feature to test, see below: 


![1485_Feature.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c6a9a976-8f46-4baf-bb3e-e73c32be02b7)
