### ISSUE TITLE
Full Text: show full text status on Child Object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1488]
**Story**

As an administrator I'd like to be able to see the parent and child object's status in the admin interface.

**Acceptance**
- [x] Display (read-only) the child's full-text status beneath "Parent Object"
- [x] The label should be "Full text:" with values of yes or no
- [x] Beneath this, have the option "Download full text" with a signed link ("Click to Download") to the full-text file in S3.   (i.e., follow the pattern of the PTIFF download link)
- [x] Put in a conditional when the fulltext is "no," the download links/section should not appear.

![Screen Shot 2021-07-26 at 1.35.05 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/1cc2149e-ea29-4748-8131-e508f8362657)

**Comment by FCRodriguez7** [comment]
I wonder if we should put in a conditional when the fulltext is no, the download links/section does not appear. 
Thoughts???? This current behavior could confuse users to have the link active when fulltext is no.

![Screen Shot 2021-09-16 at 5.06.16 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/061dca96-58df-4e6b-8db6-3c7b1a6fe389)

**Comment by FCRodriguez7** [comment]
**Fulltext NO**
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/98b48907-6a3d-4f4f-98e3-63b6c49acba9)
-----
**Fulltext YES**

https://images.zenhubusercontent.com/242185115/43f51a0a-49ee-41e8-8794-6a7c57d27bb2/screen_recording_2021_09_17_at_4_00_29_pm.mov

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/777
