### ISSUE TITLE
Add fields to single item view - miscellaneous

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#149]
**STORY**
As a scholar, I would like to see all the available descriptive metadata about a work, so that I can better understand the work's context.

**NOTE**
Use the ladybird field name as the label for now.

**ACCEPTANCE**
The single item view for a work displays the metadata for the following fields when they are populated:
- [x] source
- [x] recordType
- [x] sourceTitle
- [x] sourceDate
- [x] sourceNote
- [x] references
- [x] dateStructured
- [x] children
- [x] importUrl
- [ ] sourceCreated
- [x] illustrativeMatter

**Comment by K8Sewell** [comment]
The field 'sourceCreated' is a duplicate from ticket #148 and will be left out unless otherwise directed.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/52

Screen shot of Miscellaneous fields on single item view
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/70069e6b-a496-4542-bc04-54db631f3219)
