### ISSUE TITLE
Blacklight: left-align access message

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1491]
**Issue**

The advisory about restricted access is not aligned with the rest of the text on the page:

![Screen Shot 2021-07-28 at 10.33.58 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/1546226c-ae0d-44d5-ae68-6acfa0b9d109)

**Acceptance**

- [x] The message is left-aligned with the title and "Description" text, etc.
   - [x] Desktop responsive design alignment 
   - [x] Mobile responsive design alignment

**Comment by FCRodriguez7** [comment]
**Draft of Alignment Modification:** 

![Screen Shot 2021-08-11 at 1.48.22 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a5274b59-c993-443c-9129-4ca37b61e24c)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/633

**Comment by FCRodriguez7** [comment]
Released blacklight v1.45.0

**Comment by mikeapp** [comment]
Looks good on staging, from off-campus:

![Screen Shot 2021-08-17 at 1.16.07 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/fa633e5d-dc16-446e-9bbd-7d09f8b84346)
