### ISSUE TITLE
Determine an approach for patched UV build.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1495]
**Story**

We're seeing problems with UV that might/will require local patches:

1. If the full text search result targets a Canvas that does not have a label, the UV displays an empty box.  It is impossible to click on the box to jump to the page.  Martin submitted a patch for this to UV:  https://github.com/UniversalViewer/universalviewer/pull/792
2. Problems loading/refreshing certain images.  #1478   Fix TBD, but may involve patching UV or even OSD.

Related: Issue #1507 is to investigate using the latest UV code.

**Acceptance**
- [ ] If npm package for 3.1.4 fixes the problem, we can use that.
- [ ] If we need to use the latest code (i.e., not in an official release), determine an approach to including a new UV in the build.

**Comment by martinlovell** [comment]
It's _possible_ to fix it by patching 3.1.1's `uv.js` with `sed`.

I added this to the end of "scripts"->'"uv-config" in package.json:
`& shx sed -i s/u=this.extension.helper.manifest.options.defaultLabel/u=e.extension.helper.manifest.options.defaultLabel/ ./public/uv/uv.js`

Then ran `yarn run uv-install && yarn run uv-config` from the container.
