### ISSUE TITLE
Set SOLR_HEAP to a reasonable number

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1496]
**Story**
Still getting OOM errors on Solr.  The memory appears to be limited, despite the increase yesterday by DevOps.   Reading the documentation, Solr has a low out-of-the-box limit ( https://solr.apache.org/guide/8_5/taking-solr-to-production.html ).   We should be able to set the SOLR_HEAP environment variable as shown there.  

**Acceptance**
- [ ] SOLR_HEAP environment variable set to `12g` in the collections-test cluster

**Comment by bobrice** [comment]
I believe this entry would be made in the Dockerfile.  Who handles that?

**Comment by mikeapp** [comment]
@mlooney will you be able to pick this up?
