### ISSUE TITLE
Allow users to authenticate to the discovery app

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#150]
**ISSUE**
We want to be able to display restricted materials to Yale community members, so we need a way to authenticate Yale users.

**DETAILS**
This is a scaffolding story to set up database authentication for now so that we can proceed with other access and authorization tickets.  We'll switch over to connect to Yale's CAS authentication at a later point in the project

**ACCEPTANCE**
- [x] There are tests for the following:
- [x] I can sign up for a user id
- [x] I can log-in to the application with my user id
- [x] I can see my bookmarks when I log out and log back in

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/47
