### ISSUE TITLE
Add warning about child object deletion when deleting parent

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1500]
**Story**

It is not clear that child objects will be deleted along with the parent.

**Acceptance**
- [x] Add "and its children" after "Permanently delete this object".

![Screen Shot 2021-08-04 at 1.38.45 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/438afadd-a5b9-4fba-99be-6903d8917e02)

**Comment by FCRodriguez7** [comment]
Released management v2.47.0
