### ISSUE TITLE
Add template CSV for delete parent batch job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1506]
**Story**

The "Delete Parent Objects" batch job template link does not download a template

**Acceptance**
- [ ] Clicking the link should download a template file.

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/743

**Comment by FCRodriguez7** [comment]
Released management v2.47.1
