### ISSUE TITLE
SPIKE: Test latest UV code for freeze issue

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1507]
**Story**
See #1478 for troubleshooting to date.   UV freezes somewhat reliably on certain images.  OpenSeadragon goes into a loop due to values related to tile sizes being Infinity. 

**Update**  It looks like the UV main branch behaves normally.   Using the latest code would have the advantage of including a patch that fixes an issue related to full text searching.   There is an version 3.1.4 in npm that was released recently, but is not listed as a release on the Github site: https://www.npmjs.com/package/universalviewer/v/3.1.4.   Based on the release date this should contain Martin's fix for the fulltext issue https://github.com/UniversalViewer/universalviewer/pull/792

If this is successful then issue #1495 will address incorporating the new UV version into the build.

**Acceptance**
- [ ] Test 3.1.4 of UV locally and check whether it freezes.
- [ ] Perform general testing:
  - [x] viewing objects, especially ones that caused freezes in  #1478
  - [x] full text searching
    - [x] check that hits display properly in UV for canvases with no labels (e.g., JSS items).

**Comment by mikeapp** [comment]
I downloaded and build UV from source and did not encounter the problem on a local copy of Manifest https://collections.library.yale.edu/manifests/15497805, which does seem to break the DCS UV.   Note that I was testing UV standalone.

**Comment by mikeapp** [comment]
@K8Sewell some examples on test:
https://collections-test.library.yale.edu/catalog/800007096
https://collections-test.library.yale.edu/catalog/800047436

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/670

**Comment by K8Sewell** [comment]
Discussed deploying to test environment to see if issues with freezing on JSS items is resolved.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.9

**Comment by mikeapp** [comment]
Looks good:
* Works on images that caused freezes (i.e., dimension of 8192 on one edge)
* Full text search navigation works (i.e., you can click on a blue marker and jump to the result match)
* Other full text features work as before
