### ISSUE TITLE
Change Expand/Collapse break point for archival tree on object show page

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1509]
**Story**
Currently the hierarchical link tree for archival context under Collection Information on the single object show page shows collapsed with an ellipsis with apparently any more than 2 levels.  This should be updated to go as far as 6 levels before collapsing with ellipsis.  With 7 or more levels, default view should be collapsed to show only the broadest 3 and narrowest 3 with an ellipsis in between; clicking on ellipsis expands to show all levels in the middle.

**Current Design:**
![Screen Shot 2021-08-09 at 1.23.20 PM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/d4222f39-60d4-4851-af04-7422e0429e61)

**Proposed Design:**
6 or less:
![Screen Shot 2021-08-09 at 1.43.44 PM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/b23203a1-e482-42ab-9b21-4572a04f2062)
7 or more:
![Screen Shot 2021-08-09 at 1.44.16 PM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/c17eeb7b-5922-4517-95b9-a791ddc00315)

**Acceptance:**
- [ ] Hierarchical links tree on single object show page limits to six display items and collapses with an ellipsis with 7+.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/634
