### ISSUE TITLE
"Yale" users can see works marked "Yale-only"

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#151]
**STORY**
As a collection owner, I would like to be able to share certain works that have restricted access to Yale community members, but protect them from public discovery.

**NOTE** for the purposes of this ticket, work with the management team to copy two works and make Yale-only copies of them.

**ACCEPTANCE**
- [ ] When I log in as member of the "Yale" community, I can see restricted works
- [ ] When I am not logged in, I cannot see restricted works in search results
- [ ] When I am not logged in and try to access a restricted work directly by URL, I get some type of "forbidden" response

**Comment by alishaevn** [comment]
Checking with @jpengst & @dylansalay to see whether the work they did on [152](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/152) has been deployed.

**Comment by alishaevn** [comment]
A second MR for [152](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/152) was submitted yesterday that has not been approved/merged yet.
https://github.com/yalelibrary/yul-dc-management/pull/26

**Comment by bess** [comment]
Data indexing from the management app is now in place (PR #67) so we should have all the data needed for this.
