### ISSUE TITLE
Fix Archival Branch on Demo

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1510]
**Story**
The archival branch is not displaying properly on demo.  In particular, the links do not work.

**Acceptance**
- [ ] The branch is working again.

**Comment by mikeapp** [comment]
Looking at the Events tab for the demo cluster, the worker deployments have been failing for a couple of weeks due to a RESOURCE.ENI issue.   Assigning to DevOps.

**Comment by mikeapp** [comment]
Looks good!
