### ISSUE TITLE
Increase SOLR memory in non-prod environments

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1512]
**Story**

Increasing Solr memory on collections-test resolved the issues with full text indexing.   We'd like to increase the memory to match test (16GB) in all of the non-prod environments and deploy the new Docker image that sets the Solr memory allocation to 12GB.

We can take outages at any time in these environments. 

**Acceptance**
Solr memory is at 16GB for:
- [x] demo
- [x] uat
- [x] staging

Solr task updated to **v1.0.8**:
- [x] demo
- [x] uat
- [x] staging

**Comment by bobrice** [comment]
complete
