### ISSUE TITLE
Refactor "Update Metadata" to initiate a batch job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1514]
**Story**
The "Update Metadata" button on the Parent Objects page triggers a method call that attempts to loop through all of the parents and queue them individually for metadata updates.   With 100,000+ objects in the system (and growing!) this will time out.

Method: https://github.com/yalelibrary/yul-dc-management/blob/69ab65a9177fca1333e3d6ba0a401d1f1169fe7d/app/controllers/parent_objects_controller.rb#L100

**Acceptance**
- [x] Refactor this to call a new batch job, modeled on the SolrReindexAllJob (https://github.com/yalelibrary/yul-dc-management/blob/main/app/jobs/solr_reindex_all_job.rb), that queues the metadata updates in batches.   This will avoid timeouts.

**Comment by martinlovell** [comment]
Having some AWS S3 Key errors in CI.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/741

**Comment by FCRodriguez7** [comment]
Released management v2.47.1
