### ISSUE TITLE
ignore upper case extension in the image file when check the image exist on Goobi server

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1517]
- [ ] when check image file exist on Goobi server allow upper case extension 

The image path in the Goobi mets.xml is lower case:
`<mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049804_20210812_181645/ML964W637Folio_Test12_08122021_media/800049806.tif" />`
The actual image could be: 800049806.TIF
This causes the images not found when ingest the objects into DCS.

 `def all_images_present?
    files.all? { |file| File.exist?(file[:mets_access_master_path]) }
  end`

**Comment by MaggieZhaoYale** [comment]
Ready to review: https://github.com/yalelibrary/yul-dc-management/pull/1045/

**Comment by MaggieZhaoYale** [comment]
@K8Sewell The Goobi ingest test on the collection-test was failed. I will create a new PR.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.56

**Comment by MaggieZhaoYale** [comment]
Tested on the collection-test https://collections-test.library.yale.edu/management/batch_processes/602 looks good.

**Comment by MaggieZhaoYale** [comment]
Tested on uat, looks good. https://collections-uat.library.yale.edu/management/parent_objects/900105420
