### ISSUE TITLE
Return to first page of search results when using breadcrumb link

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1518]
**Story**

On page 2 of search results, if I click the breadcrumb to refine my search, I end up on a blank page.   This is because the `page=2` parameter is in the breadcrumb link, but the added restriction returns only one page of results.

![Screen Shot 2021-08-12 at 4.34.11 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3b111e08-5ac1-4266-a1f7-06edfba72905)

The demo cluster has enough objects to test this now.

**Acceptance**
Always send the user to page 1 of the result list when narrowing the search.
- [x] from the search results breadcrumb
- [x] from the single object page breadcrumb
- [x] from the single object page graphical breadcrumb

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/647

**Comment by mikeapp** [comment]
Looks good!
