### ISSUE TITLE
SPIKE: Add private & restricted fixtures

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#152]
**ISSUE**
We want to be able to test access restrictions in the discovery application, so we need appropriate test data.

**DETAILS**
Possible option: 
For now, because we don't want to risk exposing restricted content, let's use copies of public content and just flag them as private and restricted copies.

Use "Fair Lucretia's garland" OID 2107188 to make "Fair Lucretia's garland [private copy]" ID 2107188-priv
Use "Fair Lucretia's garland" OID 2107188 to make "Fair Lucretia's garland [yale-only copy]" ID 2107188-yale
Use "Dai Min kyūhen bankoku jinseki rotei zenzu" OID 16189097 to make "Dai Min kyūhen bankoku jinseki rotei zenzu [private copy]" ID 16189097-priv
Use "Dai Min kyūhen bankoku jinseki rotei zenzu" OID 16189097 to make "Dai Min kyūhen bankoku jinseki rotei zenzu [yale-only copy]" ID 16189097-yale

**ACCEPTANCE**
- [x] Spend up to 4 hours time boxed to
  - [x] Evaluate possible options and
  - [x] Develop a prototype solution
- [x] Fixtures should not contain actual restricted content - use dummy data or copies of metadata from public works

**Comment by maxkadel** [comment]
Mapping `itemPermission` from Metadata Cloud to `visibility_ssi` in Solr. Currently, the example values are "Public", "Yale Community Only", and "Private". 

Per Martin, possible values for this field for Beinecke include:
- Public
- Yale Community Only
- Restricted Access
- Open With Permission
- Beinecke Staff Only

There was one other, in a non-BRBL collection:
- Audience Internal
