### ISSUE TITLE
Fix periodically failing test in Management

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1520]
This test: `rspec ./spec/system/batch_process_spec.rb:166` is failing periodically.

It has to do with clicking on this link based on the ID: click_on(BatchProcess.last.id.to_s)
It may be that the randomly generated batch process id matches some batch messages links in the table on occasion.

Wrapping the click_on() with a within() to target the correct column of the table may fix it.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/753

**Comment by FCRodriguez7** [comment]
Released management v2.48.3
