### ISSUE TITLE
Merge Fulltext to Main

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1527]
**Story**

**After the 8/18 deployment** merge the `fulltext` branch to `main` in preparation for deployment to production on 8/25.

**Acceptance**
- [x] Merge `fulltext` to `main`
- [x] Test locally
- [x] Deploy to test
- [x] Update metadata
- [x] Test full text features
  - [x] Search box radio buttons
  - [x] Facet
  - [x] Search results and snippets
  - [x] Search carries to individual object page UV instance

Notes: Bob will check the overnight server capacity in preparation for this

**Comment by FCRodriguez7** [comment]
Released blacklight v1.46.0

**Comment by FCRodriguez7** [comment]
Released management v2.48.2

**Comment by mikeapp** [comment]
On collections-test I manually updated the largest JSS items, which would add about 30K pages.  It appears that many of the Beinecke items are still indexed, searching for `and` is returning hits from Beinecke archival content.

**Comment by mikeapp** [comment]
A cursory test looks good.  I will start a metadata update for Beinecke on collections-test to pick up any other objects.
