### ISSUE TITLE
Add simple pagination for JSS items w/full text

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1528]
**Story**

There's a bug in the UV that causes a display issue with full text search when a IIIF Canvas has a blank label.   To work around this we need to supply made-up pagination (1, 2, 3, ... ) in the `label`s for the JSS items that have full text.   

[A list of the JSS OIDs in Production that have full text staged.](https://app.zenhub.com/files/242185115/d460c6db-8d89-49b3-9d83-f269045b0a1b/download)

**Acceptance**
- [x] For the list of attached Parent OIDs on the production cluster, the Child Objects have a `label` value set to their sequence within the Parent (1, 2, 3...).   

Notes: The best approach might be a rake task, we'll have to do this again with additional JSS items (2,000+ ?).

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/762

**Comment by mikeapp** [comment]
See comment on the PR.

**Comment by K8Sewell** [comment]
Took PR back to draft to address comment and code coverage.

**Comment by jpengst** [comment]
Removed the rake task spec: https://github.com/yalelibrary/yul-dc-management/pull/765

**Comment by K8Sewell** [comment]
PR Ready - https://github.com/yalelibrary/yul-dc-management/pull/762

**Comment by FCRodriguez7** [comment]
Released management v2.48.11
