### ISSUE TITLE
Do not add to preservica ingest table if no parent_uuid

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1529]
uuid config in Goobi can be false, therefore null value assigned to uuid. e.g. the project DCS Ingest from Network Attached Storage sets the uuid config as false. 
If there is no ID in the xpath "/mets:mets/mets:fileSec/mets:fileGrp", that means the uuid is configured as false, it should not be recorded in the preservica Ingest table.
https://github.com/yalelibrary/yul-dc-management/blob/main/app/models/mets_document.rb#L16
Example of mets doc without uuid:

`  <mets:fileSec>
    <mets:fileGrp USE="PRESENTATION">
      <mets:file ID="FILE_0001_PRESENTATION" MIMETYPE="image/tiff" CHECKSUMTYPE="SHA-1" CHECKSUM="06741ce5baf065d75944e98c9f53da053014d936">
        <mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049872_20210817_130948/Ma21Y11R47ms89LM5000_ilsbarcode39002126214817bib13341633_media/800049873.tif" />
      </mets:file>
      <mets:file ID="FILE_0002_PRESENTATION" MIMETYPE="image/tiff" CHECKSUMTYPE="SHA-1" CHECKSUM="0bbc0239cc5dee7c1d291e4d764a7f8bc4439d4f">
        <mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049872_20210817_130948/Ma21Y11R47ms89LM5000_ilsbarcode39002126214817bib13341633_media/800049874.tif" />
      </mets:file>
      <mets:file ID="FILE_0003_PRESENTATION" MIMETYPE="image/tiff" CHECKSUMTYPE="SHA-1" CHECKSUM="3a95ac7888b0242c6849bd08f1b514f25cbca51a">
        <mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049872_20210817_130948/Ma21Y11R47ms89LM5000_ilsbarcode39002126214817bib13341633_media/800049875.tif" />
      </mets:file>
      <mets:file ID="FILE_0004_PRESENTATION" MIMETYPE="image/tiff" CHECKSUMTYPE="SHA-1" CHECKSUM="410c75711906425d945bee24bc09f9c1769e161e">
        <mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049872_20210817_130948/Ma21Y11R47ms89LM5000_ilsbarcode39002126214817bib13341633_media/800049876.tif" />
      </mets:file>
      <mets:file ID="FILE_0005_PRESENTATION" MIMETYPE="image/tiff" CHECKSUMTYPE="SHA-1" CHECKSUM="0e8261a16328e2dce254c3a737a68e4160f98375">
        <mets:FLocat LOCTYPE="URL" xlink:href="file:///brbl-dsu/dcs/800049872_20210817_130948/Ma21Y11R47ms89LM5000_ilsbarcode39002126214817bib13341633_media/800049877.tif" />
      </mets:file>
    </mets:fileGrp>
`

Acceptance:
- [x] If there is no ID in the xpath "/mets:mets/mets:fileSec/mets:fileGrp", that means the uuid is configured as false, it should not be recorded in the preservica Ingest table.

**Comment by MaggieZhaoYale** [comment]
https://github.com/yalelibrary/yul-dc-management/pulls

**Comment by FCRodriguez7** [comment]
Released management v2.48.7

**Comment by MaggieZhaoYale** [comment]
Children was added to preservicaIngest separately. Should check nil of children uuid too.
