### ISSUE TITLE
Search result order should be based on archivalSort order if scores match

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1530]
**Story**

If items have the same search score, they should be sorted based on their position in the archival hierarchy.   This is indicated by the `archivalSort` field, which consists of five-digit, zero-padded numbers separated by a period, e.g., `00000.00001.00006`.

**Acceptance**
- [x] Use the `archivalSort` field as a last element of the sort - i.e., after all other sort conditions are applied, sort on this field.

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/654

**Comment by DraxIndustries79** [comment]
Updating to apply to criteria other than Relevance.

**Comment by K8Sewell** [comment]
Add to all other sort bys

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/657
