### ISSUE TITLE
Rework icon for access denied and language for UV placeholder

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1531]
**Story**

We've received a request to update the language in the icon for the access denied image and associated text that displays in place of the UV.

Request from Lucy/DCSAG:
```
The current text on the thumbnail that appears on the search results page reads:
 
ACCESS RESTRICTED
To Yale University
Off-Site? 
Please login with your NetID. 
 
The proposed revised text to appear in the thumbnail reads:
 
Access available on Yale network only
due to copyright or other restrictions.
Off-site? Login with NetID.
 
If it is possible to revise the text string that appears at the top of the page when you click on the digital object, that would be wonderful.
 
That text currently reads:
 
The digital version of this work is restricted to the Yale Community.
Please login using  your Yale NetID or contact library staff to inquire about access to a physical copy.
 
We propose:
 
The digital version of this work is restricted due to copyright or other restrictions.
Please login using  your Yale NetID or contact library staff to inquire about access to a physical copy.
```

**Acceptance**
- [ ] This work will be done in a branch.  Screenshots should be attached to this ticket for review.
- [x] New text for icon that displays for Yale Community Only images when user is off campus and not logged in:
```
Access available on Yale network only
due to copyright or other restrictions.
Off-site? Login with NetID.
```
- [x] New UV placeholder text that displays in the same circumstances:
```
The digital version of this work is restricted due to copyright or other restrictions.
Please login using  your Yale NetID or contact library staff to inquire about access to a physical copy.
```

**Comment by K8Sewell** [comment]
This [short line](https://github.com/yalelibrary/yul-dc-blacklight/blob/59f957505f64afc71c0c48cf7fa86864b4442b92/app/helpers/access_helper.rb#L27) seems ok but it's more this [second one](https://github.com/yalelibrary/yul-dc-blacklight/blob/59f957505f64afc71c0c48cf7fa86864b4442b92/app/helpers/access_helper.rb#L35) I believe may want to be updated as well in the spirit of this ticket.  Not an exhaustive search but was nearby.

**Comment by mikeapp** [comment]
@K8Sewell I think those only display if the item is not Public or YCO, which is a pretty rare case.  I am OK to leave them as-is for now.

**Comment by K8Sewell** [comment]
@mikeapp thank you.  Have left them as is in the [PR](https://github.com/yalelibrary/yul-dc-blacklight/pull/641) which is ready for the thumbnail, whenever you have a chance @FCRodriguez7 Thank you for the design help!

**Comment by FCRodriguez7** [comment]
I added this icon as part of this ticket: 

![AccessRestrictedv3.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/aea837d2-db33-4fe0-9e47-ca8580c3693a)

**Comment by FCRodriguez7** [comment]
Before Modification 
 ![Screen Shot 2021-08-19 at 2.59.25 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a2aa65bc-c0f1-4647-bfcd-e7e20ee32afa)

After Modification
![Screen Shot 2021-08-19 at 2.59.37 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/11256488-521c-41da-800b-6c9b37f091d8)

**Comment by FCRodriguez7** [comment]
The new icon has a darker broader line than the original one.  I created a new icon with the broader line (no line), see below. 

![Draft placeholder restricted objects.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c8af188e-96d1-48bd-ac9e-40b41857296a)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/641

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.0

**Comment by DraxIndustries79** [comment]
Backing this out of release and awaiting for approval.

**Comment by motropuk** [comment]
We got approval for the work in this ticket. So this can be deployed on Weds
