### ISSUE TITLE
Archival Context graphical display expands into Collection Information subheader area

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1532]
**Story**

The archival context hierarchy can expand to overlap the section header.  See https://collections-demo.library.yale.edu/catalog/2042376

![Screen Shot 2021-08-16 at 2.11.11 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d0fed6a3-bb46-4d42-85a6-b78ff83666e9)

**Acceptance**
- [x] Space below title expands to fit the hierarchy.

**Comment by tmacmath** [comment]
I have a new design mockup for this - discussing with Alison and Christy. Got some preliminary feedback from Cliff in DSU.

**Comment by FCRodriguez7** [comment]
The current modifcation 

![Ticket_1532.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f63b280b-de13-43f6-a56e-c0bf3decefc6)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/645

**Comment by FCRodriguez7** [comment]
Please use this oid: 
2042376
