### ISSUE TITLE
IIIF Service Performance Baseline

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#154]
**ACCEPTANCE**
- [x] Document current cluster CPU and Memory config
- [x] Create a set of repeatable tests (JMeter or other) that tell us
  - [ ] The average load time for an image out of a randomized set of 20
  - [ ] The average pan time for a large image
  - [ ] The average zoom time for a large image
  - [ ] How many users the system can respond to before returning some errors
  - [ ] How many users the system can respond to before returning 50% errors

**Comment by dl-maura** [comment]
Rachel has completed creating/running tests, working on reporting

**Comment by fnibbit** [comment]
Raw test results, summary, and automatically generated reports in https://drive.google.com/drive/folders/1q3xSV-iVtN_9OHdGYeFdQmnTaSA9k96E (to view the automatically generated reports, download the folders before opening in a browser).
