### ISSUE TITLE
Update Parent Objects job not triggering updates

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1544]
**Story**

When submitting jobs, the Update Parent Object job is not triggering a metadata update.   

1. Compare batch jobs 420 (performs the update) and 425 (a week later, doesn't update) on collections-test.
2. Compare 415 and 426, which should update multiple fields

The metadata update will also trigger a manifest rebuild.

**Acceptance**
- [ ] The job always triggers a metadata update for each parent OID.

**Comment by K8Sewell** [comment]
Currently getting this error and attempting to debug

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4799c346-18ee-44d4-8e87-9f6791948cbd)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/755

**Comment by K8Sewell** [comment]
On test I set myself as an editor of the 'brbl' set but am still getting permission errors when I try to use the update batch process.  Is there a step in granting myself access that I missed?
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4aadc5c7-e1e6-45c3-a0fb-67fc30ab9df3)

**Comment by mikeapp** [comment]
Looks good on test
