### ISSUE TITLE
Change CircleCI config to use latest Solr

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1545]
**Story**

We have a new Solr release (v1.0.8).  CircleCI is referencing a branch build: `image: yalelibraryit/dc-solr:1362_fulltext_suggest_retain_case`

**Acceptance**
- [x] use the 1.0.8 Solr image in the .circleci/config.yml. 
   - [x] Blacklight
   - [x] Management

**Comment by FCRodriguez7** [comment]
I believe that this repo does not follow the same deployment pattern as management and blacklight.  I have set up a meeting with McClain to talk about deployment and other stuff.

**Comment by FCRodriguez7** [comment]
Question here: 

Should the image point to the latest release (v1.0.8) or the main branch?

**Comment by FCRodriguez7** [comment]
the blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/682

the management PR:

**Comment by FCRodriguez7** [comment]
We have failures.

**Comment by FCRodriguez7** [comment]
The release for management: Released management v2.48.19

**Comment by mlooney** [comment]
Updated the docker scripts to accept SOLR_HEAP environment variables, defaulting to the current 12gb

**Comment by FCRodriguez7** [comment]
Blacklight:
Released blacklight v1.51.2

Management:
Released management v2.49.6
