### ISSUE TITLE
Unset column values in Reassociate Child OIDs job

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1546]
**Story**

Related to: #1467 Reassociation batch job: graceful handling of missing column

You can set the field to an empty string `""` but the implementation skips any value that is nil.   For the `label`, `caption`, and `viewing hint` it should be possible to set the value to nil.

**Acceptance**
- [x] If entire column is missing, do not update that property for any object
- [x] If one of the nullable columns (`label`, `caption`, and `viewing hint`) is present but an individual value is nil, set the value of that property to nil on the Child Object

**Comment by jpengst** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/754

**Comment by FCRodriguez7** [comment]
Released management v2.48.5

**Comment by mikeapp** [comment]
This seems to be skipping values that are not last.  For instance, I'm trying to nil out the caption of the second item, but this doesn't change the value at all (it remains 'B').

```
parent_oid,child_oid,order,parent_title,call_number,label,caption,viewing_hint
17327103,17327204,1,"Worcell, Stanisław Gabriel",GEN MSS 1387,1,A, 
17327103,17327205,2,"Worcell, Stanisław Gabriel",GEN MSS 1387,2,, 
17327103,17327206,3,"Worcell, Stanisław Gabriel",GEN MSS 1387,3,C, 
17327103,17327207,4,"Worcell, Stanisław Gabriel",GEN MSS 1387,4,D, 
```

Job: https://collections-uat.library.yale.edu/management/batch_processes/361

**Comment by mikeapp** [comment]
Looks good!
