### ISSUE TITLE
Export list of all Beinecke Parent OIDs from Production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1548]
**Story**

Beinecke DSU has requested a list of all Parent OIDs from the production database.   The list is too long to export via in the Management UI.

**Acceptance**
- [x] Provide a list of all Parent OIDs in the Beiencke admin set from the production server.

**Comment by mlooney** [comment]
[https://app.zenhub.com/files/242185115/7d19354d-921e-487d-b5fb-57eeaf3b0a00/download](https://app.zenhub.com/files/242185115/7d19354d-921e-487d-b5fb-57eeaf3b0a00/download)
