### ISSUE TITLE
Repo Blacklight | Branch Clean-up Party

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1549]
As a developer, I do not want stale branches in the blacklight repo. 

**Acceptance:** 

**Delete Stale Branches**

~~- [ ] autotagging-fix-test Updated 3 days ago by JzGo *discuss if should be kept*~~
- [x] i459-style-the-search-bar Updated 12 months ago by alishaevn
- [x] 475_single_page_pagination Updated 12 months ago by edejesusyale
- [x] i462-add-font-awesome Updated 11 months ago by K8Sewell
- [x] single-item-show Updated 11 months ago by K8Sewell
- [x] gemfile-rubocop-fix Updated 11 months ago by alishaevn
- [x] 661_fix_thumbnails Updated 11 months ago by edejesusyale
- [x] dynatrace Updated 9 months ago by dylansalay
- [x] remove_old_docker_compose Updated 9 months ago by orangewolf
- [x] buttons-again Updated 9 months ago by Maura Carbone, check out by: orangewolf
- [x] i708_iiif_image_proxy Updated 9 months ago by orangewolf
- [x] i708_iiif_image_auth Updated 9 months ago by orangewolf
- [x] 9_fix_date_slider Updated 9 months ago by alishaevn
- [x] iiif-auth-take-3 Updated 9 months ago by orangewolf
- [x] iiif-auth-take-4 Updated 9 months ago by orangewolf
- [x] iiif-auth-take-5 Updated 9 months ago by orangewolf
- [x] 877_date_slider Updated 8 months ago by edejesusyale
- [x] fix-hero-image-asset-pipeline Updated 8 months ago by alishaevn
- [x] 1048_source_creator Updated 6 months ago by edejesusyale
- [x] master Updated 6 months ago by FCRodriguez7

**Comment by orangewolf** [comment]
I took care of mine, Alisha's and Dylan's.  I'll coordinate with Jez about hers

**Comment by orangewolf** [comment]
buttons again is a real PR now.
