### ISSUE TITLE
Create Goobi test server

### ISSUE THREAD

**Issue by ra359** [yalelibrary/YUL-DC#155]

**Comment by ra359** [comment]
-[ ] Create Ubuntu 18.04 VMware VM  for Intranda (yul-goobi-tst1.library.yale.internal/172.18.60.110)
-[ ] Create Intranda and YUL Engineering accounts
-[ ] Work with Intranda to perform installation
-[ ] Create F5 VIP for to terminate ssl and expose VM to Yale campus only (goobi-test.library.yale.edu)

**Comment by dl-maura** [comment]
Rick is working with Sebastian tomorrow

**Comment by ra359** [comment]
Installation complete: https://goobi-test.library.yale.edu/

Outstanding issues:
- Install Opsview client for monitoring
- Install NetBackup client
- Determining workflow w/ regards to home dirs exported via Samba
- Create data location S@Y NFS mount under /opt
- Create prod environment (do we need a uat env?)
- Is integration with Yale's AD desired/possible? SSO? Or do we have to manage user or dept accounts in the local LDAP?
- Sebastian has some catalogging questions which he will funnel thru Steffen
