### ISSUE TITLE
Controlled indexing of JSS full text on Production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1553]
**Story**

We want to gradually index the full text of JSS items on Production.

**Process**
- [x] Find a random sample of child OIDs in the `yul-dc-ocr-prod` bucket.
- [x] Create a list of 15-20 parent objects
- [x] Manually “update metadata” on those objects
- [x] Repeat the process, but use the Update Parent Object batch job, if available, to update the objects in groups of 5-10.
- [ ] ~~Refresh JSS items without full text so they have "no" full text status. See list of parent OIDs with full text in #1528~~
- [ ] ~~ Refresh metadata on all BRBL items so they have "no" full text status.~~

~~Mike will provide the full list of 800 objects on Monday 8/30.~~

**Comment by DraxIndustries79** [comment]
Mike has a list of OIDs, we can start indexing after the release on 9/1

**Comment by FCRodriguez7** [comment]
@mikeapp Could we have a list for the last two items in the acceptance criteria?

**Comment by martinlovell** [comment]
Ran some batches based on the list:
https://collections.library.yale.edu/management/batch_processes/5103
https://collections.library.yale.edu/management/batch_processes/5102
https://collections.library.yale.edu/management/batch_processes/5101

I'm seeing extra jobs for solr_index. e.g batch 5102 had 10 parents, but it may have created 20. batch 1503 created 30 jobs.

I started to see jobs fail updating solr, so I cleared the failed jobs to prevent too much stress on solr.
(Blacklight seemed responsive during this testing.)
```
RSolr::Error::Http
URI: http://yul-dc-prod-solr.yul-dc-prod:8983/solr/blacklight-core/update?wt=json
Request Headers: {"Content-Type"=>"application/json"}
```

We should take a look at #1556

**Comment by martinlovell** [comment]
It seems like some other jobs triggered solr_indexes.  At least one generate manifest job failed writing to solr, so that must trigger a solr write.  So, batches of 10 would immediately create 20 solr index jobs, but then later in the process generate more when manifests were updated, etc.

**Comment by mikeapp** [comment]
👍  I've seen this behavior as well.

**Comment by martinlovell** [comment]
We could get rid of all the duplicate jobs. Maybe something like this would work:
```
DELETE FROM
    delayed_jobs a
        USING delayed_jobs b
WHERE
    a.id < b.id
    AND substring(a.handler, 'job_class: [^\n]*') = substring(b.handler, 'job_class: [^\n]*')
    AND substring(a.handler, '_aj_globalid: [^\n]*') = substring(b.handler, '_aj_globalid: [^\n]*');
```

**Comment by mikeapp** [comment]
587 indexed on prod currently
