### ISSUE TITLE
Tagging Releases should wait for the image to exist

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#1555]
It is possible to create a new release before the CI job that builds the image is complete (if someone reviews the PR quickly). This causes the CI job for the release to fail.  Add code to the CI pipeline that will wait until the image is done being created for a reasonable, but not infinite time period before moving forward with the release tagging.

**Comment by DraxIndustries79** [comment]
Path forward:
1. Merge into main
2. Test
3. Make a quick release, that will prove the bug is fixed
