### ISSUE TITLE
Clean up CSV fixtures

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#1560]
# Summary
What was once a few CSVs for easy use in `spec/fixtures` has blossomed and become a little unruly.  To ease use over time the CSV fixtures should be moved into their own folder.

# Acceptance Criteria
- [x] team updated with new location for use in development
- [x] CSVs moved to their own directory
- [x] all fixture paths are updated

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-management/pull/770

**Comment by FCRodriguez7** [comment]
Released management v2.48.11
