### ISSUE TITLE
New archival hierarchy design mockup

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1561]
This design mockup is based on feedback from the Archival Context group, DSU and others. It is meant to address confusion re: the label "Collection Information", and also meant to highlight where the current item is found within the hierarchy. External links are also given more visual separation from the collection info itself. 

**Acceptance:** 
- [x] Move the hierarchy tree to the antepenultimate position of the data block
- [x] Subtitle for hierarchy tree - Item Within Collection Hierarchy: 
- [x] Create a $light_grey box around the two links 
- [x] Format hierarchy tree for all mobile screens

**Don't Include:** 
deactivating the last link in the tree.

**Uploaded here for review before development:**
![collection-info-mockup-new-label.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/19478380-ef0e-43fe-b781-e3ccd5d0a780)

**Comment by DraxIndustries79** [comment]
@tmacmath and @FCRodriguez7 to update with more information on mobile.

**Comment by FCRodriguez7** [comment]
The grey color in the image is different from the color in the repo.  Here are the grey colors in the repo:
$darkest_grey: #222222;
$dark_grey: #4a4a4a;
$medium_grey: #7b736b;
$light_grey: #dddddd;
$lighter_grey: #f5f6f6;
$lightest_grey: #f9f9f9;
$border_grey: #cccccc;

**Comment by tmacmath** [comment]
We are seeing what the tree looks like on mobile using word-wrap. If that doesn't look good, an alternative would be to use the breadcrumb format for smaller devices: 
![hierarchy-on-mobile.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/109a24ec-5397-4fd9-af09-848a14405e14)

**Comment by FCRodriguez7** [comment]
Another Design

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4fcb9b8c-2153-42ae-8d25-3a9521fa4d14)

**Comment by FCRodriguez7** [comment]
We should add more space to the subtitles in this section.

**Comment by FCRodriguez7** [comment]
Demo: 
![1561_New Archival_HierarchyDesign.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/51c674fa-66aa-415e-81a1-57405eb0d5bc)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/655

**Comment by FCRodriguez7** [comment]
Smaller Size:  We may want to consider a smaller size resolution of 467 for some design programming.

![a98ad891-30ec-46c0-9869-f74efd7fe67f.jpg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c82e88fd-9f40-40a8-b4a5-5ec41b8f596f)
