### ISSUE TITLE
Delete Parent Batch Job doesn't require action value

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1563]
**Story**

DSU reports that the delete parent batch job does not require the `delete` value in the second column (i.e., just uploading a list of OIDs will work).   The `delete` value was intended to prevent accidental deletion.

In addition, the template is incorrect:

![Screen Shot 2021-08-31 at 12.54.45 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0bf966b9-9da1-4743-a9a8-bf72a1da2175)

It should be `oid`, `action`

See #1407 for initial requirements

**Acceptance**
- [x] Remediate the template
- [x] Validate the bug report
  - [x] Remediate to require `action` of `delete`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/764

**Comment by FCRodriguez7** [comment]
Released management v2.48.10

**Comment by mikeapp** [comment]
Looks good.
