### ISSUE TITLE
AWS S3 Access Denied 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1565]
**User Story:**
The correct permission might be missing for the OCR bucket or one similar to it. 

**Acceptance:**
- [x] set the correct permission for the OCR AWS S3 bucket or one similar to it with the new keys

**Error Message:**

Failures:

  1) ParentObject indexing to Solr from the database with Ladybird ParentObjects can reindex all the parent objects in a background job
     Failure/Error: resp = @client.get_object(bucket: bucket, key: file_path)
     
     Aws::S3::Errors::AccessDenied:
       Access Denied
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.75.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.75.0/lib/aws-sdk-s3/plugins/dualstack.rb:30:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.75.0/lib/aws-sdk-s3/plugins/accelerate.rb:47:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/seahorse/client/plugins/response_target.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.104.4/lib/seahorse/client/request.rb:72:in `send_request'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.75.0/lib/aws-sdk-s3/client.rb:4666:in `get_object'
     # ./app/services/s3_service.rb:101:in `download_full_text'
     # ./app/models/concerns/solr_indexable.rb:176:in `block in child_object_solr_documents'
     # ./app/models/concerns/solr_indexable.rb:175:in `map'
     # ./app/models/concerns/solr_indexable.rb:175:in `child_object_solr_documents'
     # ./app/models/concerns/solr_indexable.rb:166:in `to_solr_full_text'
     # ./app/jobs/solr_reindex_all_job.rb:23:in `block (2 levels) in perform'
     # ./app/jobs/solr_reindex_all_job.rb:22:in `map'
     # ./app/jobs/solr_reindex_all_job.rb:22:in `block in perform'
     # ./app/jobs/solr_reindex_all_job.rb:20:in `each_slice'
     # ./app/jobs/solr_reindex_all_job.rb:20:in `perform'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/i18n-1.8.10/lib/i18n.rb:309:in `with_locale'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/semantic_logger-4.7.4/lib/semantic_logger/semantic_logger.rb:348:in `tagged'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/semantic_logger-4.7.4/lib/semantic_logger/base.rb:200:in `tagged'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/extensions/active_job/logging.rb:11:in `tag_logger'
     # ./spec/models/parent_object_solr_spec.rb:115:in `block (3 levels) in <top (required)>'
     # ./spec/models/parent_object_solr_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/models/parent_object_solr_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/support/solr_helper.rb:12:in `block (2 levels) in <module:SolrHelper>'

**Comment by kbcarter** [comment]
Added the ocr buckets to the CI User permissions.
