### ISSUE TITLE
validation of visibility allow nil/empty value

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1570]
Story: Objects with Ladybird fdid 180 without value will through an error: Validation failed: Visibility is not a valid value. 
Visibility only allows ['Private', 'Public', 'Yale Community Only']

- [x] allows empty Visibility value from Ladybird data, and the default value will be Private if it was empty.

**Comment by MaggieZhaoYale** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/759

**Comment by FCRodriguez7** [comment]
Released management v2.48.7

**Comment by MaggieZhaoYale** [comment]
[Uploading... visibility_private.mov]
