### ISSUE TITLE
Include parent_ssi in returned fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1571]
**Story**

UV is not displaying navigation options for full text search correctly.  The "Previous Result" and "Next Result" buttons are inactive and the thumbnails with hits do not have the magnifying glass (?) icon next to them in the left-hand thumbnail viewer area.

One possible cause is that URIs in the search results are missing the parent OID, which should appear between `oid` and `canvas`.  For example:
`"on": "https://collections-uat.library.yale.edu/manifests/oid//canvas/16794176#xywh=0,0,0,0"`

We believe the reason is that the `parent_ssi` field is not being returned by default after the recent Solr field list refactoring.

**Acceptance**
- [x] Have the `parent_ssi` field returned by default.   This could be done by adding it to the list at https://github.com/yalelibrary/yul-dc-blacklight/blob/882231309321fb23cc786a0e56d0a310b95756d0/app/models/search_builder.rb#L35

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/656

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.5
