### ISSUE TITLE
Reverse sort order for archival position

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1573]
**Story**

The sort order as implemented in #1450 returns the results in reverse alphabetical order.  Currently:

1. Beinecke Rare Book and Manuscript Library > Filippo Tommaso Marinetti papers (GEN MSS 130) > Letters to and about Filippo Tommaso Marinetti > Apollinaire, Guillaume to FTM
2. Beinecke Rare Book and Manuscript Library > Filippo Tommaso Marinetti papers (GEN MSS 130) > Letters to and about Filippo Tommaso Marinetti > Agencia Americana, Rio de Janeiro to Agamerican (Agencia Americana), Genoa
3. Beinecke Rare Book and Manuscript Library > Filippo Tommaso Marinetti papers (GEN MSS 130) > Letters by FILIPPO TOMMASO MARINETTI > Marinetti, Benedetta Cappa

So "Letters to..." is before "Letters by.." and within "Letters to..." "Apollinaire..." appears before "Agencia..."

**Acceptance**
- [ ] Reverse the sort order to terms appear alphabetical order.

**Comment by K8Sewell** [comment]
Change sort to ascending

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/657

**Comment by mikeapp** [comment]
I'm still seeing reverse alphabetical order in -demo.

https://collections-demo.library.yale.edu/catalog?f%5Bancestor_titles_hierarchy_ssim%5D%5B%5D=Beinecke+Rare+Book+and+Manuscript+Library+%3E+Filippo+Tommaso+Marinetti+papers+%28GEN+MSS+130%29+%3E+&q=&search_field=all_fields

**Comment by mikeapp** [comment]
Observation: when I choose sort by creator it comes out in the correct order (Armani, Bailby, Corradini, ..):

![Screen Shot 2021-09-08 at 2.21.37 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/6e2b3862-6669-45bc-978d-726c5772042c)

**Comment by mikeapp** [comment]
@K8Sewell  We've added more content to -demo.  Looking at the Langston Hughes collection, the folders and items are appearing in the proper order, which seems to match ASpace.  So I think maybe it's OK?  I'm inclined to ask the archivists to review at this point.

The Langston Hughes Papers is a good test set:

Archives at Yale: https://archives.yale.edu/repositories/11/resources/969

Sample search: https://collections-demo.library.yale.edu/catalog?f%5Bancestor_titles_hierarchy_ssim%5D%5B%5D=Beinecke+Rare+Book+and+Manuscript+Library+%3E+Langston+Hughes+papers+%28JWJ+MSS+26%29+%3E+&f%5Brepository_ssi%5D%5B%5D=Beinecke+Rare+Book+and+Manuscript+Library&q=&search_field=all_fields&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc%2C+archivalSort_ssi+asc
