### ISSUE TITLE
Merge main into archival

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1574]
**Story**

We don't want the archival branch to fall too far behind the main branch.

**Acceptance**
- [x] merge the main branch of Blacklight Application to the archival branch.
- [x] merge the main branch of Management Application to the archival branch.

**Comment by FCRodriguez7** [comment]
Management Application PR:
https://github.com/yalelibrary/yul-dc-management/pull/766

**Comment by FCRodriguez7** [comment]
Blacklight Application PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/666
