### ISSUE TITLE
Map language codes to human-readable strings

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#158]
**STORY**
As a researcher, I'd like language names presented as full names instead of shortened id-codes, so that I don't have to look up what language "ar" (Arkansas?) or "ge" (Ge'ez ?) stand for if I don't know off the top of my head.

NOTES:  This problem can be solved with either i8n, which give us the nice ability to present language names in the localized context at a later time; or with a controlled vocabulary mapping like the ones supported by [Questioning Authority] https://github.com/samvera/questioning_authority#questioning-authority - if Yale is using a standard vocabulary for language encoding, this solution allows for additional language codes to be added in metadata without needing to modify code in any way

**ACCEPTANCE**
- [x] Write-up research results that are able to make this ticket actionable

- [x] In the facets list, I see full language names like "English", "Latin", and "Arabic"
- [x] On the search result lists, I see full language names
- [x] In the single item view for a work, I see the full language name

| **CURRENT** | **DESIRED** (more or less 😉 ) |
|---------------|---------------------------------|
| <img width="273" alt="image" src="https://user-images.githubusercontent.com/3064318/82910400-35ea1000-9f30-11ea-9d51-465d1e352e6f.png"> | <img width="271" alt="image" src="https://user-images.githubusercontent.com/3064318/82910959-e5bf7d80-9f30-11ea-835f-adb16e9a343c.png"> |

**Comment by mikeapp** [comment]
You'll find a mix of two and three letter codes from ISO 639-1 and -2.  And sometimes there are multiple codes.   https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

You'll also see them combined, we'll eventually need to have some index time post-processing?
OID: 2033567 https://brbl-dl.library.yale.edu/vufind/Record/3440736?object_id=2033567
MARC:
```
<datafield ind1="0" ind2=" " tag="041">
<subfield code="a">yidgerheblat</subfield>
</datafield> 
```

**Comment by alishaevn** [comment]
I'd like to sit in on this conversation when it happens.

**Comment by tilthouse** [comment]
For immediate implementation, we can use the `iso-639` gem which provides an in-memory mapping of ISO-639-1 and -2 codes to English and French names (and the inverse mapping as well). This mapping happens at load time, so we can freely use without worrying about rendering performance.

If English and French are sufficient, this implementation may be good enough, long term. If we need the German names, we will have to do something else. 

I'd suggest writing an importer for the data and basically do something similar to the gem. Or, a
alternatives include: importing the data into a Table Based Authority for `questioning_authority` or potentially using loc.gov data as a remote authority.

**Comment by tilthouse** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/61

![Screen Shot 1](https://images.zenhubusercontent.com/5eac64cbd2eb22688406f33e/e6a99a2c-d1e6-42be-a5d5-2e49aaa9f320)

![Screen Shot 2](https://images.zenhubusercontent.com/5eac64cbd2eb22688406f33e/1e058705-df88-4199-9fac-fa5ef47cd1e3)
