### ISSUE TITLE
Update homepage text

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1581]
**Story**

Stakeholders would like the homepage text under the search bar updated to better describe the collections.

**Acceptance**
- [x] Homepage text under the search bar reads:

Yale Library's digital collections provide access to millions of digitized works and images. This site is a living database, and new materials are added regularly. Search or click an image below to begin your exploration.
There are Yale Library digital collections not available on this site. More information on these additional collections can be found here.

- [x] The word "here" should link to https://web.library.yale.edu/digital-collections

![Capture.JPG](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/d903a271-37c5-436d-9381-4bb502439dd3)

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/cb4a4297-d946-4219-9085-d4a442f47073)

**Comment by FCRodriguez7** [comment]
DEMO:

![1581_ChangeHomepageStatement.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c800bfda-9490-4e02-878e-82bb989ebcf3)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.7

**Comment by motropuk** [comment]
@FCRodriguez7  The wrong text has been updated. This update is for the text directly under the search bar, not the Statement on Potentially Harmful Content. The Statement on Potentially Harmful Content should remain unchanged. The text under the search bar should be replaced with "Yale Library's digital collections provide access to millions of digitized works and images. This site is a living database, and new materials are added regularly. Search or click an image below to begin your exploration. There are Yale Library digital collections not available on this site. More information on these additional collections can be found here."![Capture.JPG](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/b2ab195c-e977-48ee-8412-6a328c2dfe60)

**Comment by FCRodriguez7** [comment]
I changed the link on the top underneath the search bar: 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/17d8181c-6139-4047-a3e4-e77e75abd7a5)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/671

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.8

**Comment by motropuk** [comment]
Thanks @FCRodriguez7. This looks good.
