### ISSUE TITLE
Specs for Rake Tasks

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#1582]
# Summary
Recent commit reveals lack of coverage for tasks.  Current code coverage for `lib/` is under 40%.  Only one rake task has an associated spec.

# Acceptance Criteria
- [ ] Review existing rake tasks
- [ ] Remove rake tasks that have outlived usefullness
- [ ] Bring `lib/` up to 97% code coverage

# Screenshot

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/2ca5defe-dcb3-45ae-977d-b07cdd0e5c6d)

# Rake Tasks & Descriptions
### access_masters
- Copy fixtures to S3

### authorized_users
-  Upload authorized users to S3

### child_objects
- Save child oids to CSV

### fixture_updates
- Update Archives Space fixtures
- Update ILS fixtures
- Update Ladybird fixtures

### manifests
- Copy fixtures to S3
- Remove .json from manifest ids in fixture files

### parent_oids
- Create list of random selection of parent oids
- Update Ladybird fixtures
- Update Voyager fixtures
- Update ArchiveSpace fixtures

### s3download
- Build urls for downloading child ptiffs from s3
- Copy images from a pairtree in one bucket into another; takes a csv file, source bucket name, target bucket name

### solr
- Index all database records
- Delete all solr documents

### update_from_activity_stream
- Retrieve updated records based on the Activity Stream

**Comment by K8Sewell** [comment]
[Draft PR](https://github.com/yalelibrary/yul-dc-management/pull/765)

**Comment by DraxIndustries79** [comment]
Note:  see if making specs pending does the trick
