### ISSUE TITLE
Export child OIDs job sometimes includes only first letter of parent title

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1584]
**Story**

Beinecke has noted that sometimes the parent title in the CSV produced by the export child OIDs job just contains the first line of the title.  

See the "created file" (i.e., the output CSV) for this job: https://collections.library.yale.edu/management/batch_processes/5098

**Acceptance**
- [x] Determine whether a bug or feature :) 
- [x] If clearly a bug, remediate: the full parent title should be included

**Comment by martinlovell** [comment]
This looks like a metadata issue.  The authoritative_json['title'] is not an array for these parent objects.

**Comment by jpengst** [comment]
I agree with Martin. I'm doing some investigating here and can confirm that it's not an export batch process issue. The manifest is also only showing the first letter for the title:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/b90a1174-7c42-40ab-bc87-75927f70037f)

**Comment by K8Sewell** [comment]
PR for fixing expectation in Reassociation - https://github.com/yalelibrary/yul-dc-management/pull/772

Further investigation showed normal behavior when parent title is stored as an array...leading to believe that metadata updates will resolve bug.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/b46f52a9-8413-402e-b326-d538656c4c8d)

**Comment by mikeapp** [comment]
@K8Sewell  Actually, the parent title should not be able to be updated since it is coming from authoritative metadata.  You can close the PR, I will make a new ticket.

**Comment by mikeapp** [comment]
See https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1607

**Comment by FCRodriguez7** [comment]
Released management v2.48.13
