### ISSUE TITLE
Published/Created margin bug

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#1585]
Current margin-left overlap on small devices:  
  

![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/00972e6c-8280-4237-b9b0-ef3ec7a49017)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/664

**Comment by mikeapp** [comment]
Looks good!
