### ISSUE TITLE
Please add '/yul/dcs' to Goobi scan_directories

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1587]
The newly created directory yul is for non-brbl projects in Goobi servers. There will be some subdirectories by units or projects. 
In order to ingest the objects on the  directory or subdirectories, they should be included in the Goobi scan directory of DCS

- [x]  Add `/yul/dcs` to scan_directories  (management   app/lib/mets_directory_scanner.rb) (may not necessary if add a GOOBI_SCAN_DIRECTORIES)

- [X] Add AWS parameter store GOOBI_SCAN_DIRECTORIES (/brbl-dsu/dcs,/brbl-dsu/jss_export,/yul/dcs)

- [x] Add GOOBI_SCAN_DIRECTORIES on  Camerata

- [x] Add S@Y of /yul to Goobi_HOT and be mounted to the worker

**Comment by MaggieZhaoYale** [comment]
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_007/yul_goobi_non_BRBL_tst-CC1702-LIBITS is for /yul on Goobi-test;
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_007/yul_goobi_non_BRBL_uat-CC1702-LIBITS  is for /yul on Goobi-uat;
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_007/yul_goobi_non_BRBL_prd-CC1702-LIBITS is for /yul on Goobi-prod

**Comment by martinlovell** [comment]
Camerata updates for env variable: https://github.com/yalelibrary/yul-dc-camerata/pull/314

**Comment by MaggieZhaoYale** [comment]
@kbcarter https://yale.service-now.com/nav_to.do?uri=incident.do?sys_id=a093650e1b62f010b0f9fee58d4bcbc1%26sysparm_view=ess
ServiceNow ticket: [INC2094179](https://yale.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=a093650e1b62f010b0f9fee58d4bcbc1%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by kbcarter** [comment]
![image.png](https://images.zenhubusercontent.com/5e6002742347da559ce428f3/3ebf512c-8312-4413-b4a2-522ae1cb1357)

Successfully updated scripts to add Goobi non-brbl mounts

**Comment by kbcarter** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/315

**Comment by MaggieZhaoYale** [comment]
It seems the Goobi scan did not start at all on DCS test/uat. no error information, no any related scan activity in the log. I informed Keith.

**Comment by kbcarter** [comment]
mount added to test and uat

**Comment by motropuk** [comment]
Tested again on DCS Test but Goobi Scan is still not picking up any packages from yul/dcs

**Comment by motropuk** [comment]
This is now working on DCS Test! Example https://collections-test.library.yale.edu/catalog/800052319. Need to add to UAT now and Prod on Weds

**Comment by motropuk** [comment]
We will deploy this change to DCS UAT and Prod, but would be able to test here until we work on #1624. So once this change has been deployed to DCS UAT and Prod this ticket can be closed. We will test during #1624

**Comment by MaggieZhaoYale** [comment]
Jon is not in the tomcat8 user group on Goobi-UAT/Prod server.
