### ISSUE TITLE
Further Rotation - non-prod environments

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1588]
**Story**

Rotate non-prod environments

**Acceptance**
- [x] UAT
- [x] Demo
- [x] Staging

**Comment by DraxIndustries79** [comment]
@bobrice replace after Wednesday's deployment

**Comment by bobrice** [comment]
Redeployed management in UAT to pick up this change.  Let us know when to move on to the next environment.

**Comment by mikeapp** [comment]
UAT looks good.  OK to move to Demo.

**Comment by mikeapp** [comment]
Note that we should also redeploy Blacklight since it accesses full text in the OCR S3 bucket.

**Comment by mikeapp** [comment]
Let's wait until UAT is tested.
