### ISSUE TITLE
Slow parent_object creation during testing - management

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#1591]
![Screen Shot 2021-09-09 at 4.32.45 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/c1da172e-324c-46d7-b46e-b8e690cf70ee)

Using the gem test-prof, I was able to see that the creation of a single parent object for testing using factorybot takes around 1.6 seconds. We spend about half of the  ~16 minutes just creating the parent objects. For some tests can take up to 30 seconds for a single parentobject:

![Screen Shot 2021-09-10 at 9.16.48 AM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/cb153814-c563-4217-965f-ce2d21e4a5ca)

**Comment by jpengst** [comment]
Specs optimized to run about 4 minutes quicker.
PR: https://github.com/yalelibrary/yul-dc-management/pull/775

**Comment by FCRodriguez7** [comment]
Released management v2.48.14
