### ISSUE TITLE
Single Item Archival Tree Design Bug

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1592]
User Story:
As a user, I do not want the tree to overlaps the subtitle on the single item page.   

Current Image:
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/46998a6e-389d-472a-b3fa-5171fcd06e51)

Proposed Fix: 
![Single Item Archival Tree Design Bug#1592.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c5f64b55-77a2-4051-a7d6-e15939e7867c)

**Comment by FCRodriguez7** [comment]
The PR:
https://github.com/yalelibrary/yul-dc-blacklight/pull/667

**Comment by FCRodriguez7** [comment]
Photo from an iPhone: 

![IMG_8384.PNG](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6d93334c-43f7-4382-a0a4-f0064b241760)

**Comment by mikeapp** [comment]
Looks good.
