### ISSUE TITLE
Clicking on archival context breadcrumb in search results should execute new search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1594]
**Story**

As a user, I'd like the system to run a new search, clearing any existing search criteria, whenever I click on one of the archival context breadcrumb links in a search result listing, at the top of the object page, or in the graphical context hierarchy.    The current behavior retains other search filters, which is confusing.

**Acceptance**

- [x] In the search results, clicking on the breadcrumb/hierarchy links launches a new search without additional criteria (i.e., only searching for "Found in", but not retaining other facets or text search criteria).  This should be applied in:

![Screen Shot 2021-09-10 at 4.39.28 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d3199f19-f98b-48f3-b572-b2e999ee2e23)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/674

**Comment by FCRodriguez7** [comment]
Please resolve the branch conflicts

**Comment by mikeapp** [comment]
Looks good
