### ISSUE TITLE
Clicking on archival context breadcrumb at the top of object page should execute new search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1595]
**Story**

As a user, I'd like the system to run a new search, clearing any existing search criteria, whenever I click on one of the archival context breadcrumb links  at the top of the object page.    The current behavior retains other search filters, which is confusing.

**Acceptance**

- [x] At the top of the object page, clicking on the breadcrumb/hierarchy links launches a new search without additional criteria (i.e., only searching for "Found in", but not retaining other facets or text search criteria).  

![Screen Shot 2021-09-10 at 4.42.56 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/094b097b-5f03-4eae-ada2-aeb32a559f48)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/674

**Comment by FCRodriguez7** [comment]
please resolve the branch conflicts

**Comment by mikeapp** [comment]
Looks good on demo
