### ISSUE TITLE
Clicking on archival context breadcrumb in the object page's graphical hierarchy should execute new search

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1596]
**Story**

As a user, I'd like the system to run a new search, clearing any existing search criteria, whenever I click on one of the archival context breadcrumb links in the graphical hierarchy on the object page. The current behavior retains other search filters, which is confusing.

**Acceptance**

- [x]  On the object page, clicking on the breadcrumb/hierarchy links launches a new search without additional criteria (i.e., only searching for "Found in", but not retaining other facets or text search criteria).

![Screen Shot 2021-09-10 at 4.45.41 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9c8f3003-f063-4567-8513-09018eff370a)

**Comment by martinlovell** [comment]
![ClearArchival](https://user-images.githubusercontent.com/32851993/133805525-58cc1b78-3a24-4aa0-a947-f7d74958f398.gif)
.

https://github.com/yalelibrary/yul-dc-blacklight/pull/674

**Comment by mikeapp** [comment]
Looks good on demo.
