### ISSUE TITLE
Finding Aid link missing collection name for Ladybird items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1598]
**Story**

Items from Ladybird that have ASpace links are displaying the Finding Aid link without a collection title (i.e. "View full finding aid for"):

![Screen Shot 2021-09-10 at 4.50.51 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/5ab8c72f-fee9-4680-8d4f-add097d7eaeb)

**Acceptance**
If the title would be blank after "View full finding aid for" using the current logic:
- [x] Display the value mapped for "Collection Title", if present
- [x] Display the fallback text "for this collection" if the Collection Title is blank.

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/672

**Comment by mikeapp** [comment]
Not seeing the collection title on demo, e.g., https://collections-demo.library.yale.edu/catalog/10081049

![Screen Shot 2021-09-19 at 3.34.44 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0a8b5550-002e-4709-bc67-7036c184058b)

**Comment by K8Sewell** [comment]
Would you like an additional fallback added for the `sourceTitle` that is being used on the show page?  Right now the code looks for collectionTitle and if it isn't present that's when we get the fallback text of 'this collection' but what I'm hearing here is that we should also have a fallback in case the `sourceTitle` is present and this should be moved back to in development.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/54b2c8f5-9a92-42e3-9b82-07016fd9c04a)

**Comment by mikeapp** [comment]
Sorry, I intended the value labelled as "Collection Title", so use `sourceTitle_tesim` as the default title (ignore `collection_title_ssi`).

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/678 - PR for switching it over to sourceTitle

**Comment by K8Sewell** [comment]
Does not work as expected on demo

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/acaddc1d-ee08-4a95-9a34-86c0df7d32f0)

**Comment by mikeapp** [comment]
@K8Sewell It looks like the logic needs to be:
* `collection_title_ssi`  which is needed for Aspace records 
* else `sourceTitle_tesim` for Ladybird and Voyager records
* else "this collection" when none are present.

**Comment by K8Sewell** [comment]
PR for multiple fallbacks as described above - https://github.com/yalelibrary/yul-dc-blacklight/pull/680

**Comment by K8Sewell** [comment]
Looks good on demo
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/325feb28-78e1-4941-9f84-8f0abb5a829b)

**Comment by mikeapp** [comment]
Looks good.
