### ISSUE TITLE
Remove  end ">" from "Found In" 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1599]
**Story**

In the search criteria display ("You searched for"), when the "Found In" filter is displayed, remove the leading and trailing `>` characters.   Current display:

![Screen Shot 2021-09-11 at 12.36.59 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/28d9ed57-f640-46d5-8fb0-41d74183b1f7)

The desired display would be:
Found in > Beinecke Rare Book and Manuscript Library > Carl Van Vechten Papers Relating to African American Arts and Letters (JWJ MSS 1050)

**Acceptance**
- The trailing `>` is dropped

**Comment by K8Sewell** [comment]
Is this occurring anywhere other than the constraints?  Such as the show page?

**Comment by mikeapp** [comment]
It is not appearing elsewhere, just in the criteria display.

![Screen Shot 2021-09-14 at 1.29.54 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0a346543-00b5-452a-8ba3-cfd657ce72fc)

![Screen Shot 2021-09-14 at 1.29.47 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/54b5645e-1edf-4254-ac49-aabe5cf20e04)

![Screen Shot 2021-09-14 at 1.29.40 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a544024f-ed44-487c-8135-81fcd410c984)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/778

**Comment by mikeapp** [comment]
https://collections-demo.library.yale.edu/catalog?f%5Brepository_ssi%5D%5B%5D=Beinecke+Rare+Book+and+Manuscript+Library&q=&search_field=all_fields

**Comment by jpengst** [comment]
Looks good!
![Image 2021-09-30 at 10.27.42 AM.jpg](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/b92b4896-22c7-46ba-bfc1-41bb893d512e)

**Comment by FCRodriguez7** [comment]
Released management v2.49.4

**Comment by mikeapp** [comment]
Looks good
