### ISSUE TITLE
Display item title as last element of hierarchy at the top of the object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1600]
**Story**

In the archival context hierarchy the title of the object should be displayed as the last element, but not linked.

For instance, this hierarchy for https://collections-demo.library.yale.edu/catalog/2019635 would be followed by "> Hughes, Langston"

 ![Screen Shot 2021-09-11 at 12.46.23 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7a304d70-fdf0-4563-8bb8-1f51c7890b03)

**Acceptance**

- [x] The object title is displayed as the last element of the "Found in" hierarchy at the top of the object page.
- [x] Title is not a link.
- [x] Adjust the display so that the "last three" folders below the expander (if shown) include this item (i.e., the last two items from the folder hierarchy, plus the item title, will be displayed).
- [x] Adjust the threshold for when the expander is displayed, if necessary.  In other words, count the object itself when determining whether the hierarch is deep enough to require display of the expander icon.

**Comment by K8Sewell** [comment]
Would this also be grey text ie - not a link for the displayed item?

**Comment by martinlovell** [comment]
![AddTitleToFoundInShow.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/de4ff728-e629-446d-b93c-324def083fa5)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/675

**Comment by mikeapp** [comment]
Looks good on demo.
