### ISSUE TITLE
Display item title as last element of graphical hierarchy on the object page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1601]
**Story**

In the graphical archival context hierarchy on the object page, the title of the object should be displayed as the last element, but not linked.

**Acceptance**

- [x] The object title is displayed as the last element of the graphical hierarchy on the object page.
- [x] The title should not be a link
- [x] Adjust the display so that the "bottom three" folders below the expander include this item (i.e., the last two items from the folder hierarchy, plus the item title, will be displayed), as shown below.
- [x] Adjust the threshold for when the expander is displayed, if necessary.  In other words, count the object itself when determining whether the hierarch is deep enough to require display of the expander icon.
- [x] Use the folder icon as shown
![Screen Shot 2021-09-11 at 12.51.17 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a2ac149e-1402-49d1-ad9f-bf16dbe56914)

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/673

**Comment by mikeapp** [comment]
Looks good on demo
