### ISSUE TITLE
Display item title as last element of archival hierarchy in search result list

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1602]
**Story**

On the search results list page, the "Found in" archival context should have the title of the object  as the last element, linked to the object page.  Example:

![Screen Shot 2021-09-11 at 1.28.23 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/80dbdb1a-863b-49ef-a363-25c67e2990c1)

**Acceptance**

- [x] The object title is displayed as the last element of the archival hierarchy
- [x] It links to the object page
- [x] Adjust the display so that the "bottom three" folders below the expander include this item (i.e., the last two items from the folder hierarchy, plus the item title, will be displayed), as shown below.
- [x] Adjust the threshold for when the expander is displayed, if necessary.  In other words, count the object itself when determining whether the hierarch is deep enough to require display of the expander icon.

**Comment by jpengst** [comment]
Is it possible for an object to not have a title_tesim?

**Comment by mikeapp** [comment]
I suspect that would only happen if there was a data error in a Ladybird record.   ASpace and Voyager won't allow this, I think (?).

**Comment by motropuk** [comment]
Correct, ASpace and Voyager both require titles in a record, so I think the only source where this could be an issue is Ladybird.

**Comment by jpengst** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/679

**Comment by mikeapp** [comment]
Looks good

**Comment by mikeapp** [comment]
@jpengst I think this wasn't released.   Last `archival_feature_branch` *mangement*  push to Docker Hub was 14 days ago (!?)

**Comment by jpengst** [comment]
I think this one is released and working correctly. Did you mean to post this to 1599? (https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1599). But regardless, if the last management push was 14 days ago, then I think that would solve the issue I was having with 1599! :)

**Comment by mikeapp** [comment]
@jpengst Yes, sorry!
