### ISSUE TITLE
Reassociation jobs should not update the parent object title.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1607]
**Story**

The reassociation job logic will update the authoritative JSON with the parent title supplied in the CSV.    The application should not do this, the title should always be whatever is reported from the source system.

See: https://github.com/yalelibrary/yul-dc-management/blob/0d4ed76a830d52bd767a88bfef03812b635ad4cf/app/models/concerns/reassociatable.rb#L55

**Acceptance**
- [x] Remove the ability to update the title via the reassociation job.

**Comment by martinlovell** [comment]
This is why the title was sometimes a string instead of an array in #1584

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-management/pull/774

Should we also update the template or leave as is? 

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3afb0aea-7233-4f7f-a8df-de64eed9c51c)

**Comment by mikeapp** [comment]
Remove it from the template, along with call_number.   

I'll make a new issue for call_number - it should not be updatable either.

**Comment by mikeapp** [comment]
See #1610 for call number.

**Comment by FCRodriguez7** [comment]
Released management v2.48.13

**Comment by K8Sewell** [comment]
Template no longer has parent title or call number
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d495a48c-35cb-4941-b15d-844c5f7c5af7)

When parent title or call number are added to the CSV they are ignored.  Parent Object before reassociate job
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4c30c04c-239b-4bc3-b26b-4f428c30e8ce)

and after this job - https://collections-uat.library.yale.edu/management/batch_processes/392- processed
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/ddc41b9e-90ce-4c1e-b090-3ca144e32fcf)

**Comment by mikeapp** [comment]
Looks good!
