### ISSUE TITLE
Reassociation job error handling

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1608]
**Story**

It looks like a reassociation job is being retried due to an unhandled error.  I wonder whether this isn't causing a cascade of other types of jobs?

![Screen Shot 2021-09-14 at 2.47.11 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d8786d31-2772-4819-a8a0-d815fadd9afa)

**Acceptance**
- [x] Catch the exception and log an error for the child (?)

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-management/pull/776

**Comment by FCRodriguez7** [comment]
Released management v2.48.13

**Comment by K8Sewell** [comment]
Struggling a bit to get the same [] errors now that the parent and call number are ignored.  Could use insight to trigger verified error.  Queued with invalid csv format - https://collections-uat.library.yale.edu/management/batch_processes/393 - and was caught by another error handling.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8b22951f-db25-4d43-9b1f-00bfd4c208e2)

**Comment by martinlovell** [comment]
You can trigger it if you put in a really huge order for one of the oids:  100000000000000000000000
(Passes validation that it's an int, but DB save fails.)

**Comment by mikeapp** [comment]
I think this is good?  We've removed the code that would update the parent, which is where the example error was raised.   Using an invalid OID per Martin's suggestion is also logged correctly.
