### ISSUE TITLE
Reassociation jobs should not update call number

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1610]
**Story**

The reassociation job logic will update the parent's call number based on the value supplied in the CSV. The application should not do this, the call number should always be whatever is reported from the source system.

See: https://github.com/yalelibrary/yul-dc-management/blob/0d4ed76a830d52bd767a88bfef03812b635ad4cf/app/models/concerns/reassociatable.rb#L54

**Acceptance**
- [x]  Remove the ability to update the call number via the reassociation job.

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-management/pull/774

**Comment by FCRodriguez7** [comment]
Work captured in ticket 1584

management verison v2.48.13

**Comment by mikeapp** [comment]
Looks good!
