### ISSUE TITLE
Add volume number to search results fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1611]
**Story**

The volumeEnumeration field in Voyager, which is already mapped in Metadata Cloud and displays on item level pages, needs to also display in the search results listing for an item. At present, without this field in the search results, it is not possible to distinguish between volumes of a multi volume set, e.g https://collections.library.yale.edu/catalog?search_field=title_tesim&fulltext_search=1&q=Sochinenii%EF%B8%A0a%EF%B8%A1+M.E.+Saltykova. The volume information for each item in this search displays once you go into an item https://collections.library.yale.edu/catalog/30123058 (under Container/ Volume Information), but this information should also display in the search results page. 

**Acceptance**

- [x] "Container/ Volume Information" (Solr field `containerGrouping_tesim`) displays in search results
- [x] The field should appear next after the Collection Title / `sourceTitle_tesim` field
- [ ] Properly space the field title with the field data for the Container/ Volume Information and the rest of the section
OR 
- [x] Implement a phrase with 20 or fewer characters

**Comment by FCRodriguez7** [comment]
Images of the feature: 

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9dc65268-c589-4e96-bb83-47bfb4caf22e)

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8cf9add4-9821-4d26-914f-e3a388994125)

**Comment by mikeapp** [comment]
@motropuk 
* Is the container/volume information in the correct position (i.e., following Collection Title)?    
* Is it a problem that we'll see box/folder information for archival items?

**Comment by FCRodriguez7** [comment]
There's a PR in draft:

https://github.com/yalelibrary/yul-dc-blacklight/pull/681

**Comment by motropuk** [comment]
@FCRodriguez7 I am checking with Mark Custer and Alison Clemens about positioning and box/folder questions

**Comment by FCRodriguez7** [comment]
@motropuk ty; I added two new acceptance criteria.  I hope the descriptions of the new criteria could help make a decision.  

Properly space the field title with the field data for the Container/ Volume Information and the rest of the section

OR
 
Implement a phrase with 20 or fewer characters

**Comment by motropuk** [comment]
@FCRodriguez7 The position for this is fine (following Collection Title). Its also fine that this contains box and folder info in addition to volumes. As for spacing issue, lets just use "Container/Volume" as the field label, and remove the work information at the end. Let me know if you need other info

**Comment by FCRodriguez7** [comment]
@motropuk Ill implement a phrase with 20 or fewer characters

**Comment by FCRodriguez7** [comment]
@mikeapp 
@motropuk 

The new field name with 20 or few chars like better: 

spec/system/view_fields_in_search_spec.rb![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4fbce486-db83-42a0-be67-a812154bbf60)

**Comment by motropuk** [comment]
@FCRodriguez7 Excellent! Looks good to me!

**Comment by FCRodriguez7** [comment]
Released blacklight v1.48.0

**Comment by FCRodriguez7** [comment]
Code on test: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e9674f5a-429d-47f8-8f01-4eaef6e82654)

----
**This is interesting and perhaps a bug: **
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/17a7d0d7-737f-4562-89f0-0f7becb31fe9)

**Comment by FCRodriguez7** [comment]
An object from UAT: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0a337c4b-8514-4128-9422-935ab6093315)

**Comment by MaggieZhaoYale** [comment]
@FCRodriguez7 date_ssim is empty 
is from marc: "260cg:264|*0|c:264|*1|c:264|*2|c:264|*3|c", the voyager record is: 
https://orbis.library.yale.edu/vwebv/staffView?bibId=11749433
date is empty

**Comment by mikeapp** [comment]
See #1640 for blank values, Metadata Cloud fix in process
