### ISSUE TITLE
Remedy html sanitizer in blacklight

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#1613]
# Summary
For items with multiple rights statements there is a desire to have the multiples display on new lines.  However there is a [helper method](https://github.com/yalelibrary/yul-dc-blacklight/blob/main/app/controllers/catalog_controller.rb#L252) in the Blacklight repo that needs to not remove the `\n` inserted by the management app.  This ticket will display the multiple rights statements on new lines in the public display of the item.  Follow up ticket to - https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1576

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/bc09cc87-9350-4db1-806b-1ddc1a5ca3fa)

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/676

**Comment by FCRodriguez7** [comment]
Released blacklight v1.47.10
