### ISSUE TITLE
Exception when full text is not present

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1615]
**Story**

Honeybadger is reporting large numbers of errors on URLs to the "annotations" controller.  This has been happening since fulltext went live.

![Screen Shot 2021-09-20 at 9.04.54 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/ff9f0c3b-0099-4b6e-a346-cfc423524a36)

**Acceptance**
- [x]  ~~Call the correct route~~ The route is fine, it's when a record has no full text that this error is triggered
- [x]  Be sure that child objects w/o full text should do not cause server-side errors - for example: add a try/catch to `getFulltext` method in application.js

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/686

**Comment by FCRodriguez7** [comment]
Released blacklight v1.48.2
