### ISSUE TITLE
Merge main branch into archival feature branch

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1617]
**Story**

Most of the archival tickets are complete and we are planning to deploy to production next week, so it would be a good time to merge main into the archival feature branch.

**Acceptance**
Main merged to archival feature branch:
- [ ] Management
- [x] Blacklight

**Comment by FCRodriguez7** [comment]
The PR for Management: 
https://github.com/yalelibrary/yul-dc-management/pull/788

The PR for Blacklight: 
[add here]
