### ISSUE TITLE
Migrate EBooks in Yale Digital Collection

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1618]
**Story**

We need to migrate the following select OIDS from Yale Digital Collection in Findit (PID 66) to DCS
17364739, 16880164, 16688069, 16206433, 16206662, 16159940, 16042689, 16045909, 16161081, 16688180, 16045659, 17219520, 16368033, 17481317

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the SML admin set
 - [ ] Audit objects in DCS UAT with collection owner
 - [ ] Import the objects into DCS PROD into the the SML admin set
 - [ ] Audit objects in DCS PROD
 - [ ] Update Findit handles to point to DCS
 - [ ] Set collection to Private in Ladybird

**Comment by MaggieZhaoYale** [comment]
The three parent objects: 17364739, 17219520,  17481317 are only on Fedora Prod, not on Fedora UAT or test
16173239,16646200,16085628,16607177,16645238 are also part of Yale Digital Collection. They are not in the list of this ticket.

**Comment by motropuk** [comment]
@MaggieZhaoYale Yale Digital Collection contains two different types of materials, ebooks and periodicals. We only want to bring over the ebooks at this time. Periodicals will stay in Findit for now. The OIDS you mention that are not listed (16173239,16646200,16085628,16607177,16645238) are all periodicals, so we dont want to bring those over. We only want to bring over the list of oids mentioned in the Story at the top of this ticket

**Comment by MaggieZhaoYale** [comment]
@motropuk Thank you.
16880164, 16688069, 16206433, 16206662, 16159940, 16042689, 16045909, 16161081, 16688180, 16045659, 16368033 are available on Fedora UAT. I will get the images of these parent first. 
 17364739, 17219520, 17481317  will not be i
ngested into uat since they are not on the fedora uat.
I also noticed that some of them only have jp2.

**Comment by MaggieZhaoYale** [comment]
11 parent oids of Ebooks are in uat (17364739, 17219520, 17481317 are not in Fedora UAT)
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16042689
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16045659
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16045909
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16159940
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16161081
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16206433
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16206662
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16368033
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16688069
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/16880164
https://collections-uat.library.yale.edu/management/batch_processes/410/parent_objects/116688180

**Comment by motropuk** [comment]
@MaggieZhaoYale I will review these and send to Angela Sidman for her to take a look at took before we move everything to Prod

**Comment by motropuk** [comment]
I have emailed Angela Sidman to have her review these in UAT. She is out of the office until Monday. So this is on hold pending her response

**Comment by motropuk** [comment]
@MaggieZhaoYale We have discovered a problem which will mean we cant migrate these ebooks to DCS now. Findit hosts both original PDFs supplied by a publisher (complete with OCR) for these ebooks as well as images of each page which have been extracted from this PDF it seems, for use in Findit. So, the PDF link here for example https://findit.library.yale.edu/catalog/digcoll:2817368, provides you with the PDF from the publisher. Whereas the images at the bottom of the page have been created from this PDF, I think. We have only migrated the images from Findit to DCS here, so currently the original PDF is not available in DCS, and we don't have functionality to support hosting PDFs like this at this time. So these ebooks will need to stay in Findit until PDF support is available in DCS. This ticket can be closed but dont know if you need to add points to this for the work you did already?
