### ISSUE TITLE
Migrate Medical and Scientific Incunables Collection

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1619]
**Story**

Migration the Medical and Scientific Incunables Collection (PID 115) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Med admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the Med admin set
 - [x] Audit objects in DCS PROD

**Comment by MaggieZhaoYale** [comment]
All 2042 images are jp2. @motropuk 
The parent oid:
16986916
16986915
16986892
16986877
16986884
16986875
16986881
16986882
16986876
16986880
16986878
16986879
16986893
16986885
16986891
16986883
16986887
16986896
16986895
16986902
16986888
16986889
16986890
16986894
16986886
16986903
16986900
16986907
16986908
16986904
16986898
16986911
16986901
16986899
16986914
16986910
16986897
16986913
16986905
16986917
16986909
16986912
16986906

**Comment by motropuk** [comment]
Thanks @MaggieZhaoYale. Lets see what Medical say about the test example we sent them using ImageMagik from the collection we are working on in #1578. If they are happy with that, we can use the same process on this collection. I will set #1578 as blocker to this ticket for now

**Comment by motropuk** [comment]
@MaggieZhaoYale We can also now proceed with this ticket as Medical have given the thumbs up to image conversion. So we can stage this in UAT too

**Comment by MaggieZhaoYale** [comment]
43 parent oids of this collection are in Collection-uat: pls see the attached excel
[https://app.zenhub.com/files/242185115/8fb6f9ba-2435-4b0a-85a1-bfb3e6cb6057/download](https://app.zenhub.com/files/242185115/8fb6f9ba-2435-4b0a-85a1-bfb3e6cb6057/download)

**Comment by motropuk** [comment]
Initial audit in UAT all looks good. Going to check with Medical Library for approval to move forward

**Comment by motropuk** [comment]
@MaggieZhaoYale Medical gave thumbs up. We can move this into Production

**Comment by MaggieZhaoYale** [comment]
@motropuk Added to Production https://collections.library.yale.edu/management/batch_processes/5311

**Comment by motropuk** [comment]
Looks good. This ticket can be closed
