### ISSUE TITLE
Schedule periodic metadata updates from Metadata Cloud

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1620]
**Story**

Metadata Cloud provides an Activity Stream that identifies descriptive metadata records that have been updated in Voyager and ASpace.    A job has already been written that will process the ActivityStream and create metadata update jobs in DCS, see #1420.  What's needed is a way to schedule this job on a recurring basis (e.g., nightly).

**Acceptance**
- [x] Review possible gems identified in https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1543
- [x] Select an approach and implement a scheduling mechanism
- [x] If the job is not launched automatically, provide a manual mechanism for queuing the job 
- [x] Provide a UI component to indicate the scheduler status or the time the job last ran

We can refine the approach from here

**Comment by DraxIndustries79** [comment]
To start we'll schedule these nightly to avoid interfering with work hours.

**Comment by jpengst** [comment]
Here's a screenshot of the Reoccurring Jobs dashboard:  
https://share.getcloudapp.com/7KuAPNNQ

**Comment by DraxIndustries79** [comment]
Update "Created" and "Updated" to remove "at"

**Comment by jpengst** [comment]
Draft PR: https://github.com/yalelibrary/yul-dc-management/pull/841

**Comment by jpengst** [comment]
Camerata PR: https://github.com/yalelibrary/yul-dc-camerata/pull/321

**Comment by DraxIndustries79** [comment]
We'll hold this till after Wed's release then merge.

**Comment by FCRodriguez7** [comment]
Released management v2.53.0

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.0

**Comment by mikeapp** [comment]
I'm seeing an issue on local where the management instance queues the activity stream update job and then exits.

**Comment by mikeapp** [comment]
Getting `504 Gateway Time-out` when attempting to trigger the job manually on test.

**Comment by martinlovell** [comment]
We probably have to do big updates in chunks, or put something in to reset it if it hasn't run in a long time and there are > X number of items in the stream to process.

It's feasible that 24 hours could produce too many activity stream entries to handle in one batch, so maybe we need to chunk it up regardless.

**Comment by K8Sewell** [comment]
PR to remove it from the main template and puts it in chain with production template - https://github.com/yalelibrary/yul-dc-camerata/pull/323 - goal of this PR is to stop it from running this one command and then shutting down.  

WIll investigate gateway timeout on test and dividing up the updates.

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.2

**Comment by K8Sewell** [comment]
Was able to replicate gateway timeout on test but on uat it appears working 
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/584d5be7-3455-4a73-8443-211d61222004)

**Comment by mikeapp** [comment]
Do we need to disable this on staging?

**Comment by martinlovell** [comment]
> Was able to replicate gateway timeout on test but on uat it appears working 
This is probably because it was run on Test months ago, so it's trying to find the difference since the last time it was run. 
On UAT, it was never run before, so sets the last time to the current time and doesn't look back in the stream.

**Comment by DraxIndustries79** [comment]
Waiting to resolve camerata issue

**Comment by motropuk** [comment]
@mikeapp Did we resolve the issue with Camerata issue that was blocking this. If so, we should prioritize getting this work finished up next sprint?

**Comment by martinlovell** [comment]
We can start manually running the job in production: https://collections.library.yale.edu/management/reoccurring_jobs

**Comment by mikeapp** [comment]
Running a job on test now.

**Comment by mikeapp** [comment]
@motropuk  Please edit an TEST ASpace record corresponding to a DCS UAT asset and let us know the OID.   When that's done we'll run another metadata sync.

**Comment by motropuk** [comment]
Sync test should pickup change for OID 900057352 in UAT. I added the new title to this object in ASpace TEST which now reads "Mother of Us All. (UPDATED 01/20/2022 TO TEST DCS SYNC)"

**Comment by mikeapp** [comment]
Looks good: https://collections-uat.library.yale.edu/catalog/900057352

**Comment by mikeapp** [comment]
So the manual option is working.   I think we still need to decide how to bootstrap the initial instance of `ActivityStreamJob` so that it runs nightly.
