### ISSUE TITLE
Limit CSV rows for batch jobs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1622]
**Story**

We need to limit the number of input rows for batch jobs.   We recently had a job submitted that contained tens of thousands of blank rows,  which caused a slowdown and eventually failed.

**Acceptance**
- [x] Use the skip blanks option when reading the CSV 
- [x] Immediately reject input CSVs for batch jobs that contain more than 10,000 rows.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/784

**Comment by FCRodriguez7** [comment]
Released management v2.48.18
