### ISSUE TITLE
Add DCS Ingest from Network Attached Storage project to Goobi UAT and Prod

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1624]
**Story**

Add the DCS Ingest from Network Attached Storage project that is currently in Goobi Test to Goobi UAT and Prod

**Acceptance**
 - [x] Build DCS Ingest from Network Attached Storage project in Goobi UAT
 - [x] Run exports from project into DCS UAT
 - [x] Build DCS Ingest from Network Attached Storage project in Goobi Prod
 - [x] Run exports from project into DCS PROD
 - [x] Setup admin privileges for Project user group in Prod
 - [x] Setup NAS Ingest cancelled project in Prod
 - [x] Install Dynatrace on Goobi prod servers

**Comment by MaggieZhaoYale** [comment]
@bobrice Goobi UAT and Prod Deployment ticket   [INC2103573 ](https://yale.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=90e325e11bf2781029b375d4cc4bcba4%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by motropuk** [comment]
Brining @MaggieZhaoYale comment over from #1578 Jon is not in the tomcat8 user group on Goobi-UAT/Prod server.

**Comment by motropuk** [comment]
Support ticket sent to Intranda to solve permissions issue in UAT

**Comment by motropuk** [comment]
I have built the Network Attached Storage project in both Goobi UAT and Prod, but experiencing same permissions issue on both. Waiting for Intranda support to address this.

**Comment by motropuk** [comment]
UAT issue fixed. Waiting on deployment of config changes to Goobi Production to run export into DCS Production

**Comment by MaggieZhaoYale** [comment]
Rick, this is the serviceNow ticket to request deploy to Goobi-prd. @bobrice @Ricardo Aliwalas (could not @ rick) https://yale.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=ef504a7b1bf6f01029b375d4cc4bcb5c%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true

Thank you

**Comment by motropuk** [comment]
Project is in Goobi Production and Music and MSSA and now adding content to test load. Ticket can be closed.
