### ISSUE TITLE
[SPIKE] Review ASpace digital object requirements

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1625]
**Story**

We'd like to write digital object records into ASpace.  Mark has provided documentation on the ASpace data/API requirements.

**Acceptance**
- [x] Review the documentation (ask Mike for it)

**Comment by DraxIndustries79** [comment]
We'll use Thurs or Fri after standup to group on this.

**Comment by mikeapp** [comment]
Let's aim for Friday.  Look in slack for documentation.

**Comment by mikeapp** [comment]
* Two new tickets created for follow-up
* After we have an API designed for Metadata Cloud, Yale team will implement a stub so DCS can call it.
* Might include Mark C. in standups when we get to implementation
