### ISSUE TITLE
Add project_identifier field to ParentObject

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1631]
**Story**

Create `project_identifier` text field on ParentObject model

**Acceptance**
- [x] Add a `project_identifier` field to the ParentObject, of type text
- [x] Add an index for the field, since it will be used for filtering/sorting
- [x] Display the field value on the ParentObject show page in the management app, immediately beneath the "Set", with the label "Project ID:"

![Screen Shot 2021-09-28 at 1.26.56 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b558d1da-cdc5-43bb-bd14-810ef268a63d)

- [x] Allow the field to be edited on the ParentObject edit page.  Put the text field next to the Set.
- [x] Move "Metadata Source" and "Visibility" to a new row of their own in the form.

![Screen Shot 2021-09-28 at 1.27.25 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9412695c-b12c-4268-9829-85c696a2c50b)

**Comment by jpengst** [comment]
Do we want to add this to the search fields in Blacklight?

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/797

**Comment by motropuk** [comment]
@jpengst We dont need for this field to display on the front end of DCS, or be an option that end users can search or facet on in the UI. However, what would be useful if possible is to be able to build a URL string that groups objects by this id on the front end that we can send to collection owners as we work on their collections being migrated from Findit. I dont know if this is possible and if so what the lift is. Not essential if not possible.

**Comment by FCRodriguez7** [comment]
Released management v2.49.2

**Comment by mikeapp** [comment]
Looks good
