### ISSUE TITLE
Review JS console output for any exceptions/errors

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1634]
**Story**

We'd like to know if there are any unexpected Javascript errors being encountered.

**Acceptance**
- [x] View the various pages on the site with the browser's Javascript developer console open and report errors that are being logged.

**Comment by K8Sewell** [comment]
# Notes
Review of site and console showed few Javascript errors - see video & details below - however there are a number of other URL Generation Errors occurring in HoneyBadger.  For example:

1. Manifest not found - https://app.honeybadger.io/projects/72587/faults/78991608
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/addbb145-c3d7-4d25-90a8-487560727eb5)

2. PDF not found - https://app.honeybadger.io/projects/72587/faults/79089874
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9527a009-705d-45ed-ae29-e5d2d0c524c3)

Maybe some chore tickets? 

# Video & Details
One error found: Uncaught TypeError on home page
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/f4b895cd-9f5d-42cf-bce2-3625f28ed495)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9df61e16-240c-47f5-850c-be8015990753)

https://images.zenhubusercontent.com/242185115/ef359d10-c8b5-4c6a-8bbc-363a60777c87/screen_recording_2021_09_24_at_04_41_36_pm.mp4

**Comment by K8Sewell** [comment]
Created 4 Chore tickets: [#1648](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1648), [#1649]((https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1649), [#1650](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1650), & [#1651](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1651)
