### ISSUE TITLE
Organize/comment code in BatchProcess

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1637]
**Story**

The BatchProcess model has grown somewhat unwieldy.   It could benefit from a reordering of the methods and comments.   There's code for setup, queueing the jobs, and then methods particular to specific jobs.  Grouping these and commenting around the groups might help orient engineers to the code and also point to potential opportunities for refactoring.

**Acceptance**
- [ ] Reorder methods in BatchProcess into logical groups and comment on the groups

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/786

**Comment by FCRodriguez7** [comment]
Released management v2.48.20
