### ISSUE TITLE
[Check] Possible bug: Solr records for children not deleted

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1638]
**Story**

`rspec spec/system/batch_process_delete_parent_spec.rb:32` against main fails on my local system.  The test is failing because the child records (for the OCR text) are not being deleted from Solr, only the parent.   The test passes on CircleCI.

**Acceptance**
- [x] Delete child Solr records when deleting the parent

**Comment by K8Sewell** [comment]
# Notes
* Specs passing locally - see screenshots
* Deleting parent deletes children - see video
* Query of solr for child record returns nothing - see screenshots
# Screenshots
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d5f6bb44-7a2d-46cb-a64b-86f6141f0c68)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/95986026-8cd6-4db6-b815-c060d02cf1d2)

# Video
https://images.zenhubusercontent.com/242185115/32beb2ba-f32f-4932-a3d0-0537525167b7/screen_recording_2021_11_17_at_09_25_54_am.mp4
