### ISSUE TITLE
Possible bug: Solr records for children not deleted

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1639]
**Story**

`rspec spec/system/batch_process_delete_parent_spec.rb:32` against main fails on my local system.  The test is failing because the child records (for the OCR text) are not being deleted from Solr, only the parent.   The test passes on CircleCI.

**Acceptance**
- [x] Delete child Solr records when deleting the parent

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/789
