### ISSUE TITLE
Align field mappings between Blacklight and Management applications

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#164]
**ISSUE**
When we use the management app importer to add fixtures to Solr instead of the blacklight importer, not all of the fields and facets are showing up even though we can see the metadata in solr.  We believe this is due to slight differences between the field used in each application.

**ACCEPTANCE**
- [x] I see all the expected facets when searching
- [x] I see matching metadata for the work when I look in Solr and when I view the blacklight show page

**Comment by maxkadel** [comment]
I have updated the Management application to match the Blacklight Solr mapping, and that's been merged. When Camerata is spun up locally using the updated management indexing rake task, it shows the expected fields in Blacklight.
