### ISSUE TITLE
Bug: Published/Created field blank entry for Voyager records

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1640]
**Story**

The 'published / created' data field is blank for some voyager records.  The bug appeared on test after blacklight release [v1.48.0] (https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.48.0).   

Code on test: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/17a7d0d7-737f-4562-89f0-0f7becb31fe9)

**Acceptance**
- [ ] Determine whether this is due to bad data coming from Metadata Cloud (or Voyager), or the result of processing in the Management App

**Comment by MaggieZhaoYale** [comment]
Published /Created data comes from `date_ssim`
`date_ssim` is from metadata cloud `date` which is mapping from MARC "260cg:264|0|c:264|1|c:264|2|c:264|3|c"
 The voyager record of this record is:
https://orbis.library.yale.edu/vwebv/staffView?bibId=11749433
There is no valid date from $260/264 from this record. 
There is dataStructured from metadata cloud get date range 1889 -1903

**Comment by mikeapp** [comment]
Metadata Cloud work is under way.

**Comment by martinlovell** [comment]
UAT metadata cloud is updated.  Production on Wednesday.
https://metadata-api-uat.library.yale.edu/metadatacloud/api/1.0.1/ils/barcode/39002071797303?bib=11749433&mediaType=json

**Comment by mikeapp** [comment]
Fixed record on test after reindex.   I don't have a sample on UAT.
