### ISSUE TITLE
Change field label for Container / Volume information on main object page

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1641]
**Story**
We recently change the field label for "Container / Volume information" on the search results page, to a shorter phrase "Container / Volume" (see #1611). We should make the same change on object pages too. 

![Screen Shot 2021-09-23 at 14.40.51.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/7378430c-da52-432f-a60f-ffef735a9a04)

**Acceptance**
- [x] "Container / Volume information" field title on parent object pages changed to "Container / Volume"

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/687

**Comment by FCRodriguez7** [comment]
Released blacklight v1.48.2

**Comment by mikeapp** [comment]
Looks good

**Comment by motropuk** [comment]
@mikeapp Looking at UAT with v 1.49.1, and this change is not being reflected there https://collections-uat.library.yale.edu/catalog/16479170

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/696

**Comment by FCRodriguez7** [comment]
Released blacklight v1.50.0

**Comment by mikeapp** [comment]
Looks good on UAT.
