### ISSUE TITLE
Filter out BRBL DL and other links brought over from Voyager

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1647]
**Story**
This ticket is a follow up to #1636. We need to be able to filter the resourceVersionOnline_ssim values currently brought over from Voyager, to exclude:

- Links to the old BRBL DL (in 856:42:$3 - starting http://beinecke.library.yale.edu or http://beinecke1.library.yale.edu)
- Links to YUL's instance of Content DM (in 856:41:$3 starting http://digital.library.yale.edu)
- Divinity's ad hoc server (in 856:42:$3 starting http://divinity-adhoc.library.yale.edu/FosterPapers/)
- Links to Beinecke Library's Digital Images Online database (in 856:41:$3 starting http://brbl-archive.library.yale.edu)

Additionally, all remaining 856 values should map to RelatedResourceOnline not to ResourceVersionOnline

**Acceptance**
- [x] BRBL DL, Content DM, Divinity ad hoc server and BRBL Digital Images Online database links not longer display in DCS when an object is associated with ILS
- [x] All other links brought over from Voyager 856 are labeled as Related Resource Online on object page for object associated with ILS.

**Comment by FCRodriguez7** [comment]
@motropuk could you provide examples?

**Comment by motropuk** [comment]
@FCRodriguez7 Here are two to start with. 

https://collections-test.library.yale.edu/catalog/15737336
- Example http://digital.library.yale.edu

https://collections-test.library.yale.edu/catalog/30000483
- Example of http://beinecke.library.yale.edu

We dont have examples in Test for the other link formats. So if we need these let me know and I will create them

**Comment by FCRodriguez7** [comment]
**Data field name**

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f2d88585-72ff-4dfa-9dc6-fdbb9ebbb714)

**Comment by FCRodriguez7** [comment]
@motropuk I am out of the office today.  However, I deployed the feature in this ticket to demo environment for review and feedback,  please feel free to test out demo.

**Comment by motropuk** [comment]
Thanks @FCRodriguez7. I am looking on Demo but the filter does not seem to be working. See https://collections-demo.library.yale.edu/catalog/2002046

**Comment by FCRodriguez7** [comment]
@motropuk  The deployment worked: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5ba46d41-5d3f-4470-ab40-d0de181ec07b)

**Comment by FCRodriguez7** [comment]
@motropuk

**Comment by FCRodriguez7** [comment]
Environment with the code modification
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4c01a0d2-b1f4-4514-83da-0e84003c7594)

**Comment by FCRodriguez7** [comment]
The PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/721

**Comment by FCRodriguez7** [comment]
Released blacklight v1.58.0
