### ISSUE TITLE
Create Dockerhub machine user for to push images from CircleCI

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#165]
How and why to create machine users - https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds .

Must be done by Yale Dockerhub organization owner (maybe only Michael?)

- You will need an email address not currently connected to a Dockerhub account 
- Create a Dockerhub account using that email address
- Once you have a machine user account, give it build and push permissions to the YUL-DC image repositories
- We are not creating our autobuilds in Dockerhub, but in CircleCI. Go to https://app.circleci.com/settings/organization/github/yalelibrary/contexts, click on yul-dc, delete the existing DOCKER_LOGIN and DOCKER_PASSWORD environment variables and replace with the appropriate values from the machine user.

**Comment by dl-maura** [comment]
Max is added so he can work with Rick on setting this up

**Comment by ra359** [comment]
Looks like we have an existing Dockerhub acct we can use:
Email: libdevops@yale.edu
Username: yulciuser

**Comment by maxkadel** [comment]
Added to CircleCI context, should be available to all YUL-DC projects now

**Comment by maxkadel** [comment]
Wrong username / password combo, setting it back to me for now

**Comment by maxkadel** [comment]
Updated, working
![image](https://user-images.githubusercontent.com/45948126/84076851-7e7be180-a9a4-11ea-8b68-0848c1eb0f5e.png)
