### ISSUE TITLE
Job failed without status message

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1653]
**Story**

This batch job failed without a status message:

![Screen Shot 2021-09-28 at 9.26.17 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d578e0ed-bc22-4785-9704-d9933840b9e2)

![Screen Shot 2021-09-28 at 9.26.06 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d8065f8d-8969-4f66-a46e-ec48f05abbec)

**Acceptance**
- [ ] This failure should log a status message for the job so the user understands what happened.

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-management/pull/803

**Comment by FCRodriguez7** [comment]
Released management v2.49.5

**Comment by mikeapp** [comment]
Looks good, provides error messages on UAT.
