### ISSUE TITLE
Add THIS ITEM label to lowest level item in context tree. 

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1658]
**Story**

Add a "THIS ITEM" icon to lowest level item in archival context tree display. Position this icon like so:

![3a3abab5-be62-43fb-ad10-06816b33a6dd.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/d8ef6469-041f-402d-81a2-bdff13af8ab6)

Note:  move forward as styled text vs. an image icon

**Acceptance**
- [ ] Icon displays to the left of the title for the lowest level object in archival context tree

**Comment by K8Sewell** [comment]
Working on enabling view in line with screenshot above but wondered how folks might feel about this screenshot of another option.

**Comment by tmacmath** [comment]
Hi Kate, the folder name should be inline with the label - the label is replacing the folder icon.

**Comment by K8Sewell** [comment]
Screenshot more in line with mock up
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3a15d78e-8392-401a-a110-6d540fc0a7e4)

**Comment by K8Sewell** [comment]
PR in draft.  Can come out of draft when we have the hex code for the green. https://github.com/yalelibrary/yul-dc-blacklight/pull/699

**Comment by K8Sewell** [comment]
Got the hex code and the PR above is ready for review.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.52.0
