### ISSUE TITLE
Change heading for archival context tree

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1659]
**Story**

Change “Item Within Collection Hierarchy” to “Search for Additional Digitized Material in This Collection:”

![Screen Shot 2021-09-29 at 09.15.17.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/1063b25b-1e60-4d69-abe7-6226644c4666)

**Acceptance**
- [x] "Search for Additional Digitized Material in This Collection" appears as header immediately above archival context tree

**Comment by FCRodriguez7** [comment]
@motropuk 
The current wording: 
Search for Additional Digitized Material in This Collection.

Should 'this' be capitalized?

**Comment by motropuk** [comment]
@FCRodriguez7 Yes This should be capitalized. Looks like we have follow title case for these field labels, so title should be Search for Additional Digitized Material in This Collection.

**Comment by FCRodriguez7** [comment]
@motropuk 

perfect, I liked that one too.  I will complete the mobile versions for it shortly.

**Comment by FCRodriguez7** [comment]
**First Mobile Screen:** 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/146ff498-1f1a-446b-8628-46843f1b3dca)

**Comment by FCRodriguez7** [comment]
DEMO

![1659_ObPgArchivalHeadingChange.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/65fb474e-806b-42db-83da-bb1cf32edea2)

**Comment by FCRodriguez7** [comment]
The PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/702

**Comment by FCRodriguez7** [comment]
Released blacklight v1.53.0

**Comment by FCRodriguez7** [comment]
**Image from an iPhone Pro**

![Passports, consular affidavits, related documents - Yale University Library.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/acb4bb57-f4c1-40db-b1a9-fd1261481626)

**Comment by mikeapp** [comment]
Looks good!
