### ISSUE TITLE
Add Repository to Collection Information field cluster

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1660]
**Story**

We need to display the repository name within the Collection Information section on each object page, for all metadata sources. For some sources, this will repeat information found in the archival context tree and the breadcrumb, but this is OK and is the desired outcome. Repository name should appear as the first field below the Collection Information field header. It should display with the field label "Repository" in bold, matching the other field labels in this cluster. The value in this field should not link.  Display SSIM.

![Screen Shot 2021-09-29 at 09.47.39.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/cffdf2bc-088f-4c09-a64e-a7b1bddcef20)

**Acceptance**
- [ ] Repository should display as the first field under Collection Information section header on an object page

**Comment by motropuk** [comment]
Updated this ticket with additional information needed. Ready to be pointed and moved into Sprint

**Comment by FCRodriguez7** [comment]
@motropuk 
Here's an image:

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0758b437-ce8f-4726-a2c0-0ca529071115)

**Comment by motropuk** [comment]
@FCRodriguez7 This looks good. Thanks

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/46630711-ff13-438e-80e8-fd5fe8f3969f)

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/06fbf9e8-e9a4-46ff-a30c-6e8ad53c328f)

**Comment by FCRodriguez7** [comment]
The PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/701

**Comment by FCRodriguez7** [comment]
Released blacklight v1.51.0

**Comment by mikeapp** [comment]
Looks good on UAT.
