### ISSUE TITLE
Move Container / Volume under collection hierarchy

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1661]
**Story**

Move the Container/Volume Field to display below archival context tree on an object page. It would appear below context tree but above links to Archives at Yale and the Finding Aid

![Screen Shot 2021-09-29 at 09.57.37.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/7acb1f63-21a0-4864-820f-5e35a8212b3f)

**Acceptance**
- [x] Container/Volume Field displays below archival context tree on an object page

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/239009c6-b882-426b-aa09-14280999942a)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/695

**Comment by FCRodriguez7** [comment]
Released blacklight v1.50.0

**Comment by mikeapp** [comment]
Looks good on UAT.
