### ISSUE TITLE
Resize Archives at Yale and Finding aid links

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1662]
**Story**

The links we currently provide to Archives at Yale and to the Findit aid for an item are larger (16px) than other text or links on the an object page (14px). We need resize this down to match the size of other text

 ![Screen Shot 2021-09-29 at 10.05.13.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/faef0b31-5603-4d40-a319-b6bd48f7d7e4)

**Acceptance**
- [ ] Font and size of text use for links matches font and size used for other field text on an object page

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/700

**Comment by K8Sewell** [comment]
Failed in CI but passed locally, taking PR to draft til resolved.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/a80184ae-871f-4883-b235-22d714a73b97)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/6bd34ef0-cbd6-4a27-9b5e-ffc45ce34c00)

**Comment by K8Sewell** [comment]
Re run of pipeline succeeded so PR above is ready for review

**Comment by FCRodriguez7** [comment]
Released blacklight v1.51.1

**Comment by mikeapp** [comment]
Does the padding around the text also need to be resized (design question).
