### ISSUE TITLE
Update font family and size for breadcrumbs on object pages

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1664]
**Story**

The font used for the breadcrumb trail at the top of an object page does not match the rest of the DCS design. DCS uses the Mallory font family. This should be used for this breadcrumb trail also. The size of this breadcrumb should also match the 14px used for other text on object page.

![Screen Shot 2021-09-29 at 11.24.15.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/7e87d865-6f21-499d-a5c4-7f6ee5cb9469)

**Acceptance**
- [x] Context breadcrumb trail on object pages displays with Mallory font family, consistent with the rest of the design for the DCS UI.

**Comment by K8Sewell** [comment]
Which Mallory font?  We have 8 to chose from.  The core metadata is Mallory-Medium at font weight 500

/*************************** MALLORY ***************************/

  font-family: 'Mallory-Bold';

  font-family: 'Mallory-BoldItalic';

  font-family: 'Mallory-Book';

  font-family: 'Mallory-BookItalic';

  font-family: 'Mallory-Light';

  font-family: 'Mallory-LightItalic';

  font-family: 'Mallory-Medium';

  font-family: 'Mallory-MediumItalic';


/*************************** MALLORY MP ***************************/

  font-family: 'MalloryMP-Black';

  font-family: 'MalloryMP-BlackItalic';

  font-family: 'MalloryMP-Bold';

  font-family: 'MalloryMP-BoldItalic';

  font-family: 'MalloryMP-Medium';

  font-family: 'MalloryMP-MediumItalic';

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/697

**Comment by motropuk** [comment]
@K8Sewell Mallory-Medium at font weight 500 looks good to me.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.50.0

**Comment by mikeapp** [comment]
Looks good on UAT.
