### ISSUE TITLE
[SPIKE] Plan for knowledge transfer for AWS/ECS/Camerata

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1666]
**Story**

The team needs to transfer knowledge from @mlooney to Yale staff to be sure we're capable of supporting the ECS cluster, camerata, etc. for the long term.

**Acceptance**
- [x] Meet to discuss topics for teachouts, documentation, etc.
- [ ] Schedule subsequent meeting dates for these events

Meeting Thurs 10/14 after standup

[Notes](https://docs.google.com/document/d/1gPvNxoVF7MVwVxdlL2ZEHsehY2sAmjNJu5I3RMR88Yg/edit)

**Comment by DraxIndustries79** [comment]
Thursday 10/7 after standup
