### ISSUE TITLE
Migrate Complex Objects from Sanborn Maps Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1668]
**Story**

Migration of Complex Objects from Sanborn Maps (PID 21) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the BRBL admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the BRBL admin set
 - [x] Audit objects in DCS PROD
- [x] Fix issue with children in production that wont convert
- [x] Locate missing child in PROD
-  [x] Update handles URLs to point to DCS
- [x] Add Project ID to objects in DCS

**Comment by MaggieZhaoYale** [comment]
child 11680701 of parent 11681507 was not found in fedora
child 11679526 (1.4GB) of parent  11679621 failed to convert PTIFF 
Child Object 11679479 (2.6GB) of parent 11679490 failed to convert PTIFF error 137

**Comment by MaggieZhaoYale** [comment]
461 complex parents are in the collection-uat.
41 simple objects are not in collection-uat
5 images failed to converted to PTIFF. Is it possible to replace these tifs
Child Object 11681579 of  parent 11681839  
Child Object 11680685 of parent  11681505
Child Object 11679526 of parent  11679621
Child Object 11676555 of parent  11676591
Child Object 11676535  of parent  11676588

**Comment by MaggieZhaoYale** [comment]
These images are not incompatible.
11681579
11680685
11679526
11676555
Is it possible to find alternative images for them?

**Comment by MaggieZhaoYale** [comment]
@motropuk Handler excel:
[https://app.zenhub.com/files/242185115/4cdbdce6-996c-4887-b837-468c5e3971d6/download](https://app.zenhub.com/files/242185115/4cdbdce6-996c-4887-b837-468c5e3971d6/download)

**Comment by motropuk** [comment]
Have also sent a message to Sarah Coe to see if she has a copy of 11040299 of parent 11040301 which is missing in Fedora

**Comment by motropuk** [comment]
Sarah is on vacation this week, so we are on hold with this ticket

**Comment by motropuk** [comment]
Simple objects were migrated over in #1722. Total of 502 objects in management app, which is the correct number for this collection, but only 492 displaying on front end. 6 objects are known issues outlined about, but we now have another 4 that are not displaying. More work to do here

**Comment by motropuk** [comment]
@MaggieZhaoYale Copy of 11040299 of parent 11040301 is here \\storage.yale.edu\home\FC_Ladybird-807001-YUL\Replacement files for DCS

**Comment by MaggieZhaoYale** [comment]
@motropuk attached child 11040299 to parent 11040301 https://collections-uat.library.yale.edu/management/parent_objects/11040301

**Comment by motropuk** [comment]
Thanks @MaggieZhaoYale. Looks good. Can we add this missing child to production now.

**Comment by motropuk** [comment]
Missing image now found and in Production. Also created replacement images for the 5 children that would not convert to PTIFF in prod

child 11680685 of parent 11681505
child 11681579 of parent 11681839
child 11679526 of parent 11679621
child 11676555 of parent 11676591
child 11118481 of parent 11122735

@MaggieZhaoYale to add to Prod

**Comment by MaggieZhaoYale** [comment]
@motropuk Missing children are in the production now. 
https://collections.library.yale.edu/management/batch_processes/6221
https://collections.library.yale.edu/management/batch_processes/6220

https://collections.library.yale.edu/management/child_objects/11676555 please ignore the status in the batch process of this child.

**Comment by MaggieZhaoYale** [comment]
@motropuk handle excel:
[https://app.zenhub.com/files/242185115/6a6a336e-ffd1-437f-85e0-cb63cf128ad1/download](https://app.zenhub.com/files/242185115/6a6a336e-ffd1-437f-85e0-cb63cf128ad1/download)

**Comment by motropuk** [comment]
502 objects in DCS management app which is correct. However, on 497 showing via https://collections.library.yale.edu/catalog?f[project_identifier_tesi][]=21&q=&search_field=all_fields. Cant figure out why there is a discrepancy here. Investigating

**Comment by MaggieZhaoYale** [comment]
11105680,11175782,11175784,11605575,11687069 are not in the list of blacklight
