### ISSUE TITLE
Reduce padding around links to Archives at Yale

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1676]
**Story**

Follow on from #1662 - we need to reduce the padding around the links provided within the archival context display on an object page

Actual Design
![Screen Shot 2021-10-05 at 14.44.35.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/c25a0ee4-023c-41e9-946f-afc7b3702c5e)

Propose Design Change
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/72599e2e-1163-474d-9707-1cef3ac28b50)
**Acceptance**

- [x] Padding is reduced between each link only, not around the links.

**Comment by tmacmath** [comment]
Consider using an unordered list inside a div instead of using <p> tags (see attached file)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/705

**Comment by FCRodriguez7** [comment]
DEMO:

![1676_DesignChangeArchivesLinks.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2123925d-0e6b-4fef-9513-697f091786da)
