### ISSUE TITLE
[Valid] Bug Object Page Container / Volume alignment

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1679]
User Story

As the product designer, I want the Container / Volume data to appear across from the subtitle on the mobile screen.  

Current Design
![Screen Shot 2021-10-06 at 3.07.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/18035011-1f9b-43af-9988-cfefe357e58a)

Propose Design
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/15570384-893a-458e-bf6f-dc6a95511d74)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/727

**Comment by FCRodriguez7** [comment]
![1679_BugContainerBoxObjectpage.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0be45165-f5a7-4e76-94a5-ceca8534efb7)

**Comment by FCRodriguez7** [comment]
**iPhone Res**
![Passports, consular affidavits, related documents - Yale University Library.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d781be38-f1c5-45b2-8ad0-d5aeaac00ce3)
----
**Larger Mobile Screen Res - Long side**
![IMG_0048.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8429da0e-f938-4008-be1c-ed22e381af9c)


----
**Larger Mobile Screen Res - Short side**
![IMG_0049.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ee12e540-4d33-4834-bd73-3109395ab0b5)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.58.1

**Comment by mikeapp** [comment]
Looks good
