### ISSUE TITLE
Migrate Divinity Manuscripts Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1683]
**Story**

Migration of the Sanborn Maps (PID Divinity Manuscripts Collection) from Findit into DCS

**Acceptance**
 - [ ] Export image files from Fedora
 - [ ] Import image files into the DCS pairtree
 - [ ] Generate list of Parent OIDs
 - [ ] Import the objects into DCS UAT into the Divinity admin set
 - [ ] Audit objects in DCS UAT with collection owner
 - [ ] Import the objects into DCS PROD into the the Divinity admin set
 - [ ] Audit objects in DCS PROD

**Comment by MaggieZhaoYale** [comment]
The  active_fedora_model_ssim of all parent except one 16850014(complex parent) are simple. Will modify the rake task for this collection.

**Comment by motropuk** [comment]
@MaggieZhaoYale We dont have a way to bring simple objects from Ladybird over to DCS at this time. So will need to hold off on this migration for now. I will close this ticket and we can come back to this once we can move simple objects
