### ISSUE TITLE
Add Series Facet for ASpace objects

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1687]
**Story**
If the collection title facet is selected, users should then be presented with a facet to view by “grouping,” that will display a menu of series from the selected collection. “Groupings” displayed in the facet should include: components from specified collections with their “Level of Description” encoded as a) “Series”, b) “Record Group,” or c) “Other Level” with “accession” or “Accession” entered as text in the “other level” field. If there is only one series, do not enable grouping facet

This work is dependent on a new mapping to provide the data needed for this series facet, see https://git.yale.edu/Library-IT/Metadata_Field_Mappings/issues/80. This ticket is on hold until this mapping work has been completed.  

**Acceptance**
- [x] New mappings are in place from metadata cloud to provide the data needed for series facet.
- [x] Series facet appears when selection is made in collection title facet; series doesn't display by default unless you've made a selection in "Collection"
- [x] Ask Archival Context team to review examples in Demo or Test before moving to UAT

**Comment by DraxIndustries79** [comment]
Probably "Series" but Jonathon will confirm with the group.

**Comment by motropuk** [comment]
Facet should be called "Grouping"

**Comment by martinlovell** [comment]
Management PR:
https://github.com/yalelibrary/yul-dc-management/pull/835

(Calling the field series_ssi in solr to match the metadata cloud field.  I will label with Grouping in blacklight.)

**Comment by FCRodriguez7** [comment]
Released management v2.52.0

**Comment by FCRodriguez7** [comment]
Released blacklight v1.55.1

**Comment by motropuk** [comment]
Have sent this work to Archival Context Team for review

**Comment by martinlovell** [comment]
Archival Context Team reported issue with the sorting of the facet, so moving back.

**Comment by martinlovell** [comment]
Deployed update to Demo which uses special series_sort_ssi for the facet to cause them to sort by position in archives space.

Draft PRs (waiting for review by Archival Group)
https://github.com/yalelibrary/yul-dc-management/pull/839
https://github.com/yalelibrary/yul-dc-blacklight/pull/719

**Comment by motropuk** [comment]
@martinlovell Sending to archival context team to review

**Comment by motropuk** [comment]
@martinlovell Got the thumbs up from the archival context team to move forward

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/719
https://github.com/yalelibrary/yul-dc-management/pull/839

**Comment by FCRodriguez7** [comment]
Released blacklight v1.55.3

Released management v2.52.3

**Comment by motropuk** [comment]
Looks good on UAT
