### ISSUE TITLE
Create Batch Process to delete multiple child objects

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1692]
**Story**

There is currently no easy process for delete child objects in bulk through the DCS Management App. The current workaround has been to create a new fake parent to which you then attached the children you want to delete, moving them from their original parent, and then deleting the fake parent. 

Instead, we need to implement a batch process to delete child objects. The template for this process can be the same as the current export child oids process, and simply ask for oid and admin set. 

**Acceptance**
- [x] "Delete Child Objects" job available as a batch process
- [x] Template for "Delete Child Objects" available
- [x] Add an "action" column that requires the value to be "delete" or the row won't be processed

**Comment by martinlovell** [comment]
In Release v2.49.11
