### ISSUE TITLE
SPIKE: Convert Simple Objects to Complex during migration

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1697]
**Story**

A number of collections in Ladybird/Findit contain simple objects, with no parent child relationships. For simple objects brought into DCS, we need to figure out a way to make them complex in DCS. The preferred approach would be to maintain the current oid for the simple object in Ladybird at the parent level in DCS, so that is that OID is displayed for the object in Blacklight. However, this would result in the child in DCS getting a new OID. If that child was to become disconnected from its parent, it would be impossible to then match it to its original OID in ladybird. 

- [x] Allow users to specify that a parent object is Simple for Create Parent Objects batch
- [x] Create new ChildObject with newly minted OID for simple parents
- [x] Add original_oid database property to ChildObject and set with Parent's oid
- [x] Move the access master (Image name is originally ParentOid, rename and move to the right location so that it's the newly minted child oid.)
- [x] Add guard so that if a user tries to import an parent with children as a simple, it will raise an exception.

Two examples include:

_LWL general collection - Complex Objects (PID 60)_
- Note title here is misleading, these are simple objects
- Example object https://findit.library.yale.edu/catalog/digcoll:4046817 

_Lam Qua Paintings (PID 50)_

**Comment by FCRodriguez7** [comment]
Schedule a small project with simple objects.
