### ISSUE TITLE
Migrate Peter Parker’s Papers

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1700]
**Story**

Migration of the Peter Parker’s Papers (PID 53) from Findit into DCS

Note that this collection uses that archival context view in Findit https://findit.library.yale.edu/catalog/digcoll:4934412. There are levels of this hierarchy in Ladybird, that have oids but no images e.g 16808762. This is because they are purely intended to represent the hierarchy and not a digital object. 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Medical Library admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Test reassociation with ASpace in DCS UAT before moving collection to Prod
 - [x] Import the objects into DCS PROD into the the Medical Library admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS
- [x] Add Project ID to objects in DCS

**Comment by MaggieZhaoYale** [comment]
@motropuk This is the excel of the Handler update:
[https://app.zenhub.com/files/242185115/68542dfc-e4ab-4d1f-925c-7fa34fcb3453/download](https://app.zenhub.com/files/242185115/68542dfc-e4ab-4d1f-925c-7fa34fcb3453/download)
