### ISSUE TITLE
Migrate Maurice Durand Han Nom Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1705]
Migration of the Maurice Durand Han Nom Collection (PID 31) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the MSSA admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the MSSA admin set
 - [x] Audit objects in DCS PROD
-  [x] Fix issue with Child Object 10687706 of parent 10687885 
-  [x] Update handles URLs to point to DCS
- [x] Add Project ID to objects in DCS

**Comment by MaggieZhaoYale** [comment]
@motropuk 187 Parent objects were ingested into DCS UAT.
One child object was not found in the fedora and ladybird
Child Object 10687706 of parent https://collections-uat.library.yale.edu/management/parent_objects/10687885
Ladybird page: https://ladybird.library.yale.edu/object_overview.aspx?qoid=10687706

**Comment by motropuk** [comment]
Checking with MSSA to see if Child Object 10687706 of parent 10687885 is in Preservica to see if we could get a copy

**Comment by motropuk** [comment]
@MaggieZhaoYale Move ahead with adding to Production. We will fix the issue with the missing image there. I will probably remove it and set parent 10687885 to partially digitized and add digitization note to say that this page is missing

**Comment by MaggieZhaoYale** [comment]
@motropuk This is the handle excel: [https://app.zenhub.com/files/242185115/4388c71f-f235-4678-a1fa-1e5d15ca683f/download](https://app.zenhub.com/files/242185115/4388c71f-f235-4678-a1fa-1e5d15ca683f/download)

**Comment by MaggieZhaoYale** [comment]
@motropuk  187 in prod. As that in the UAT, Child Object 10687706 of parent 10687885 could not be found in Fedora.
https://collections.library.yale.edu/management/batch_processes/6032 please ignore the 99 skipped row.
