### ISSUE TITLE
Management Parent Object DataTable Names

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1707]
**User Story**
As a user, I want a single capitalization style on the parent data table.  

![e3ab169d-6733-4b7f-b5cb-1eaf9d2bb811.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0d7d22a0-5e16-4636-9cd1-ac98ba1c86f6)

**Acceptance** Pick one style or case
- [x] Title-style
- [ ] Sentence-style
or 
- [ ] camelCase
- [ ] PascalCase
- [ ] snake_case
- [ ] kebab-case

**Comment by motropuk** [comment]
@FCRodriguez7 Lets go with Title-style

**Comment by FCRodriguez7** [comment]
Were the other table headers completed?

**Comment by motropuk** [comment]
Looks good. Good to close
