### ISSUE TITLE
Add Rob Kaufman to project resources

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#171]
**ACCEPTANCE**
Move any tasks to stand-alone tickets that cannot be completed in one sprint.
- [x] GitHub
- [x] DockerHub
- [x] ZenHub
- [x] Slack
- [x] Google Drive
- [x] Box
- [ ] Yale NETID
- [ ] Yale VPN

**Comment by dl-maura** [comment]
VPN still on hold due to covid
