### ISSUE TITLE
Spike: Analysis of ECS deploy error

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1715]
We get `was unable to place a task because no container instance met all of its requirements. The closest matching ... encountered error \"RESOURCE:ENI\"`

See: in Jenkins: /YUL-DC-Staging-Deploy/116/console

It does eventually succeed, but it may be slower to deploy since it encounters the error and has to re-try deploying the tasks.

It may be related to the EC2 instance size the the number of ENI (network interfaces) it can have at one time.  Eventually the error goes away and the deploy works.  It may be that as old containers shut down, ENI become available, so the new ones eventually start.

**Comment by bobrice** [comment]
This issue is due to a lack of resources in the cluster during the deploy but appears to be benign as the deploy is successful once the older task versions have been stopped and replaced.

**Comment by mikeapp** [comment]
OK, will close
