### ISSUE TITLE
Migrate Ravi Goel Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1717]
**Story**

Migration of the Ravi Goel Collection (PID 61) from Findit into DCS

Note that this collection uses that archival context view in Findit. There are levels of this hierarchy in Ladybird, that have oids but no images. This is because they are purely intended to represent the hierarchy and not a digital object. We should just migrate objects with images attached 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the MSSA admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the MSSA admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS
- [x] Add Project ID to objects in DCS

**Comment by MaggieZhaoYale** [comment]
Handle excel:
[https://app.zenhub.com/files/242185115/d3b7adaf-9868-4f85-8dd4-543480a7affc/download](https://app.zenhub.com/files/242185115/d3b7adaf-9868-4f85-8dd4-543480a7affc/download)

**Comment by MaggieZhaoYale** [comment]
@motropuk https://collections-uat.library.yale.edu/management/batch_processes/478 In uat

**Comment by motropuk** [comment]
@MaggieZhaoYale This looks good in UAT. Can be moved to Prod

**Comment by MaggieZhaoYale** [comment]
@motropuk https://collections.library.yale.edu/management/batch_processes/6041 136 in Prod.
