### ISSUE TITLE
Clean up unprioritized and future board columns

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1721]
**Story**

A number of tickets have been moved into the unprioritized and future columns on our sprint board. We need to review these to see which are still relevant and which could be closed as they are no longer an issue or have been fixed. As these are reviewed, suggest items that might be a light lift or something we might consider bringing into the backlog to be worked on as time allows. 

When closing tickets, remove estimates if no work has been done. 

**Acceptance**
- [x] Schedule meeting for this week w/ @bobrice after standup to review
- [x] Tickets in unprioritized and future board columns that are no longer relevant have been closed
- [ ] Tickets for light lift work moved to backlog

**Comment by DraxIndustries79** [comment]
Plan to meet Thurs 11/11 after standup
