### ISSUE TITLE
Migrate Simple Objects from Sanborn Maps Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1722]
**Story**

Migration of Simple Objects from Sanborn Maps (PID 21) from Findit into DCS

Complex objects from this collection have already been migrated into DCS Production, see #1668. Additionally, this will test work done during Spike #1697

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the BRBL admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the BRBL admin set
 - [x] Audit objects in DCS PROD

**Comment by MaggieZhaoYale** [comment]
8 out of 41 failed. Although the original images are in the image master path, the new child image could not be renamed and copied.
Error in log, example:
 Unable to rename simple parent access master for parent_oid: 11675895 and new child: 900057397: Permission denied @ rb_file_s_rename - (/data/09/95/11/67/58/95/11675895.tif, /data/09/97/90/00/57/39/900057397.tif)

**Comment by MaggieZhaoYale** [comment]
@motropuk The remaining 8 parent oid were 
processed.
There are totally 41. Please ignore the failed information of the 8 parent oid. If check the parent oid page, you will see the image.
https://collections-uat.library.yale.edu/management/batch_processes/484/parent_objects/11175785

**Comment by motropuk** [comment]
Good to move to Production

**Comment by MaggieZhaoYale** [comment]
@motropuk The handle excel:
[https://app.zenhub.com/files/242185115/f0652ec3-7b36-4a3b-a217-9e2e8c4253b6/download](https://app.zenhub.com/files/242185115/f0652ec3-7b36-4a3b-a217-9e2e8c4253b6/download)

**Comment by MaggieZhaoYale** [comment]
41 Simple objects are in Prod. 
https://collections.library.yale.edu/management/batch_processes/6088b . Please ignore the "failed" status on the 7 parent objects. If you click these parents, you will see the image was created. @motropuk
