### ISSUE TITLE
Review and update technical documentation

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1724]
**Story**

Existing technical documentation for DCS exists as Readme documents in Yale Library's Github repo https://github.com/yalelibrary - Notably: 

Management App - https://github.com/yalelibrary/yul-dc-management
Blacklight - https://github.com/yalelibrary/yul-dc-blacklight 
Documentation repo - https://github.com/yalelibrary/yul-dc-documentation/wiki

This documentation needs to be reviewed and updated as appropriate. Also consider if Github is the best place for this documentation, or if a different documentation solution for DCS could be used. 

**Acceptance**
- [x] Add camerata documentation
- [x] Review and update existing ReadMEs
- [x] Spike to make recommendations on better documentation practice

**Comment by martinlovell** [comment]
There have been some requests for us to provide information about:
MC Field Name -> Solr Field Name -> BL Display (Label, facet?, searchable?, sortable?)
If we had a table with this information, **and maintained it**, it would be pretty useful to other groups as well as for us.

**Comment by jpengst** [comment]
Sounds good. I think the wiki would be the best place for that information.

**Comment by krcourville** [comment]
@martinlovell : I'd wonder about the possibility to generate that documentation, especially, if it's already documented in code somehow.

**Comment by martinlovell** [comment]
That might be possible for parts of it.  @edejesusyale  wrote some code that went through the config in blacklight to figure out which fields needed to go in the "fl" parameter for SOLR.  I wonder if some similar code could go through the blacklight config and generate a list of the sort/search/index/facet's labels and solr fields.

(It might not be possible for the mapping from MC to Solr with the way the code is setup.)

**Comment by jpengst** [comment]
Current draft for the field name document: https://github.com/yalelibrary/yul-dc-documentation/wiki/Field-Names

**Comment by jpengst** [comment]
Camerata PR: https://github.com/yalelibrary/yul-dc-camerata/pull/322

**Comment by DraxIndustries79** [comment]
JP recommends wiki, but using ReadME for actionable tips.  Let's get @mikeapp input.

**Comment by DraxIndustries79** [comment]
Use ReadME to link to Wiki articles
