### ISSUE TITLE
Add Child OIDs to PDFs

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1727]
**Story**

Patrons often contact BRBL access services to obtain high res versions of the objects in DCS. They will often reference PDFs they have pulled down from DCS when referring to images they want. To help locate the images in these PDFs quickly, we should add the Child OID for each image to the PDF. We currently include Caption information for each image, but we would like to now include Image OID. Example https://collections.library.yale.edu/pdfs/32237871.pdf

This should be labeled in the PDF as Image ID

**Acceptance**
- [x] Child OID appears for each image in PDFs available to download for each object.
- [x] Child OID is labelled Image ID

**Comment by martinlovell** [comment]
Sample PDF:

[https://app.zenhub.com/files/242185115/baa73276-928c-48ab-b208-90ec26bc9367/download](https://app.zenhub.com/files/242185115/baa73276-928c-48ab-b208-90ec26bc9367/download)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/834

**Comment by FCRodriguez7** [comment]
Released management v2.52.0

**Comment by motropuk** [comment]
Sent this work to BRBL for review

**Comment by motropuk** [comment]
This looks good and is ready to close
