### ISSUE TITLE
Review terminology used throughout DCS for consistancy

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1728]
**Story**

We have used different language in different places for the same . 

A good example is the terminology we use for Child OIDs throughout the site. In the More Information panel in the UV, this is labeled Image OID. However, in a URL pointing directly to an image we use Child OID e.g https://collections.library.yale.edu/catalog/11861587?child_oid=11864874. We are also about to use the term Image ID for this OID in PDF, see #1727. 

We should review DCS for similar terminology discrepancies, and then select a universal term to apply

**Acceptance**
- [x] Create a single document with a table that has the main term associated with each referenced term.

**Comment by DraxIndustries79** [comment]
Per Jonathan, Working Group will review the chart and make decisions
