### ISSUE TITLE
Set up CircleCI on Camerata for Blacklight & Management integration

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#173]
Goal is to focus on "does this all come up locally and work together" and not "is ECS deployment working and smoke tested" for this ticket.

- Set up CircleCI 
  - [x] Use Yale postgresql image and not the Circle CI image for this level of testing
- Create a matrix running
  - [ ] The masters against each other
  - [x] the release versions against each other
- [x] There is some form of smoke test that checks Blacklight responds to search requests, some minimum number of search results are returned, for some item there is a manifest, and the system returns images specified in the manifest.

**Comment by orangewolf** [comment]
I think it might be worth holding on this until https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/207 can be agreed on as I believe that will inform direction for this ticket

**Comment by orangewolf** [comment]
As part of this ticket we should make sure Camerata uses the Yale postgres image and not the default CircleCI issue.

**Comment by orangewolf** [comment]
This ticket is no longer blocked (cc @bess )

**Comment by fnibbit** [comment]
Rob's PR https://github.com/yalelibrary/yul-dc-camerata/pull/73 got this working using the camerata docker-compose file.

**Comment by fnibbit** [comment]
Created an AWS user with just S3 access, replaced the credentials in the CircleCI project.
