### ISSUE TITLE
Don't create a PTIFF Job if the child already has a PTIFF

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1730]
To help reduce the number of DelayedJobs for performance reasons, skip creating a job for ptiffs that already have a width and height and a ptiff on S3.

- [x] In SetupMetadataJob.setup_child_object_jobs(), don't call GeneratePtiffJob.perform_later on any children that have a width & height set and a PTIFF on S3. (See PyramidalTiff.file_on_s3)
- [x] If no GeneratePtiffJobs are created in SetupMetadataJob.setup_child_object_jobs(), complete the logic at the end of GeneratePtiffJobs to kick off the manifest job if it's needed: `GenerateManifestJob.perform_later(parent_object, parent_object.current_batch_process,parent_object.current_batch_connection) if parent_object.needs_a_manifest?`
- [x] Make sure Recreate Child Oid Ptiffs still runs the jobs.
- [x] Adjust related tests.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/832

**Comment by FCRodriguez7** [comment]
Released management v2.51.1
