### ISSUE TITLE
Spike: Evaluate Options to get DelayedJob performant with > 500,000 jobs and alternatives

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1731]
Collect information on the issues with DelayedJob with a high (>500,000) number of jobs.  Determine what our options are to:

- [x] Adjust the database and/or DelayedJob code so it performs better
- [x] Other implementations of Active Job
- [x] Other options

See: https://medium.com/@coder_iq/delayed-jobs-hell-and-how-i-saved-myself-from-it-43411c271019

**Comment by mikeapp** [comment]
Sidekiq has cool features but is Redis-backed :(

**Comment by DraxIndustries79** [comment]
@martinlovell has code for path forward to review
