### ISSUE TITLE
Parent object full text status should show partial when appropriate 

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1734]
**Story**

When 1 or more children attached to a parent have a full text status of No, the Parent Object full text status should show as "partial".

Currently, the full text status for a Parent Object shows as true, even if 1 or more children don't have full text e.g https://collections-uat.library.yale.edu/management/parent_objects/15475232. The status of true should only display for parents where all children have full text. If no children have full text, the status at the parent level should display as false. 

**Acceptance**
- [ ] Parents with 1 or more children without full text display the full text status "partial"

**Comment by FCRodriguez7** [comment]
![Screen Shot 2021-11-04 at 1.22.57 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d8e86ad3-76ed-498f-87e5-2093bba43b79)

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/838

**Comment by FCRodriguez7** [comment]
Released management v2.52.1

**Comment by motropuk** [comment]
Looks good. Good to close
