### ISSUE TITLE
Standardize column headers for CSV exports and batch process templates

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1735]
**Story**

Currently, the column headers used for exports from the Parent Object data table are formatted differently to those used by the templates required for batch updates. In most cases the headers on the Parent Object spreadsheet are capitalized and include spaces. The headers used on the batch update templates are all lowercase and use underscores instead of spaces. 

We should standardize these headers to use the same formatting for parent and child object table exports and batch process templates. All lowercase with underscores is preferred. 

**Acceptance**
- [ ] column headers used on parent object are formatted to be lower case with underscores
- [ ] column headers used on child object are formatted to be lower case with underscores

**Comment by K8Sewell** [comment]
Draft PR: https://github.com/yalelibrary/yul-dc-management/pull/840

**Comment by FCRodriguez7** [comment]
Released management v2.52.2

**Comment by jpengst** [comment]
Looks good on test

**Comment by motropuk** [comment]
Looks good on UAT
