### ISSUE TITLE
Split Large Update Full Text Status Jobs to Prevent Timeout

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1740]
**Story**

When running an "update fulltext status" job in production with all 916 full text parents, it appears that the job will timeout because of the 1hour limit on delayed jobs.

**Acceptance**
- [ ] Management should split the job up so that the 1 hour time limit isn't reached.

**Comment by martinlovell** [comment]
See Batch Job: https://collections.library.yale.edu/management/batch_processes/6035
The batch had 900+ parents, but only 19 finished before the 1 hour timeout.

**Comment by martinlovell** [comment]
Split it up into 10,000 children batches. (Jobs still work on parents, so parents are split based on number of children.)
https://github.com/yalelibrary/yul-dc-management/pull/844

**Comment by FCRodriguez7** [comment]
Released management v2.52.5
