### ISSUE TITLE
Display "Show Full Text" for Partial full text Parents

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1741]
**Story**

The "Show Full Text" link doesn't display parents that have partial full text.

**Acceptance**
- [x] The link displays for items with partial full text

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/724

**Comment by FCRodriguez7** [comment]
Released blacklight v1.56.0
