### ISSUE TITLE
Adjust Circle CI config to use new Solr image with less than default 12G

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1742]
The new solr image uses 12GB by default.  Circle CI fails periodically with that much memory.

Update the configuration to use the latest solr image, but configured to use 4G.

- [x] Management updated to use yalelibraryit/dc-solr:v1.0.9 image with 4G.
- [x] Blacklight updated to use yalelibraryit/dc-solr:v1.0.9 image with 4G.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/837
https://github.com/yalelibrary/yul-dc-blacklight/pull/718

**Comment by FCRodriguez7** [comment]
Released blacklight v1.55.2

**Comment by DraxIndustries79** [comment]
We'll wait to see if it passes deployment on one of the servers.

**Comment by FCRodriguez7** [comment]
Released management v2.52.1
