### ISSUE TITLE
Explore and implement option to edit labels for download options in UV

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1743]
**Story**

We would like to change the default labels used when selecting options to download images via UV. Currently, three options are presented - two for "whole image" one at a reduced size and one at full size. A third option for "current view" is presented when a user zooms in on an image. 

Is it possible to edit the labels used for these options? We are most interested in being to change the ones currently being used for "whole image" to indicate that one is full size and the other reduced size.

Note:  This is a spike to investigate capabilities in UV

 ![Screen Shot 2021-11-05 at 11.15.45.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/bbed05b2-888a-444e-ba20-a4ea1789fa39)

**Acceptance**
- [x] Investigate ability to edit labels or to override UV and create own labels
- [x] Full image label now says "Full size"
- [x] Smaller image label now says "Reduced size"

**Comment by K8Sewell** [comment]
### Spike Research
Found the localization file in UV that sets these download dialogue options should we wish to overwrite the existing labels and found where to add additional download option in management app.  Will wait to proceed with implementation until direction decided upon.

### Estimates
 - change the existing: 3
- add additional option: 2

### Locale Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/520553e1-1f81-4fc6-a9d4-82f6ca1e4666)

**Comment by motropuk** [comment]
@jpengst @K8Sewell For full res image lets change "Whole image" to "Full size. For the lower res image lets change "Whole image" to "Reduced size". Both labels would then be followed by the dimensions and (jpg), matching the current label format.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/725

**Comment by FCRodriguez7** [comment]
Released blacklight v1.57.0

**Comment by motropuk** [comment]
Looks good on UAT
