### ISSUE TITLE
[ON HOLD]Migrate LWL general collection (PID 60)

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1744]
**Story**

Migration of the LWL general collection (PID 60) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the wal admin set
 - [ ] Audit objects in DCS UAT with collection owner
 - [ ] Import the objects into DCS PROD into the the wal admin set
 - [ ] Audit objects in DCS PROD
-  [ ] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@motropuk (Both simple objects and complex are in UAT)
- Complex parents:
 https://collections-uat.library.yale.edu/management/parent_objects/17088939
 https://collections-uat.library.yale.edu/management/parent_objects/17088908

1. Simple objects: 
 https://collections-uat.library.yale.edu/management/batch_processes/513 (sorted by status, failed first) please ignore the first failed which is re-processed and the image was found. if click the parent, you will see the record is completed; The other 3 failed records do not in ladybird uat, but in prod.

**Comment by motropuk** [comment]
Audit of this collection is going to be a long process. Quite a few complexities to sort out, which will require meetings with LWL and additional investigation

**Comment by motropuk** [comment]
We will need to rethink LWLs migration. Will close this ticket and write a new one.
