### ISSUE TITLE
[CHECK] Check for Parent OID images being Left after Simple Ingest

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1745]
**Check whether this is still relevant**

During simple object ingest the original image with the Parent's OID is moved to the newly minted Child OID's location.

In some cases, the move partially fails: 
New child oid image is created, but the parent oid is not deleted.

In this case, the process continues, and the simple is successfully ingested.
However, we have an extra access master with the parent oid still.

This only happens with some parents, and it's not obvious which permissions are different.

**Acceptance:**
- [ ] Parent image is removed when it is moved

**Comment by mlooney** [comment]
possibly related to #1794?
