### ISSUE TITLE
[SPIKE] Test more recent version of the Passenger Docker base image

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1748]
**Description**

This task is from knowledge transfer discussion. 

We would like to bump the Passenger Docker image to a more recent version and test.

**Acceptance**
- [x] Select a more recent version
- [x] Verify that Management and Blacklight start with the new image
- [x] Create a branch for more in-depth testing
- [ ] Report on any issues

**Comment by mlooney** [comment]
The only significant issue was the custom vips package, which was easily rectified

**Comment by DraxIndustries79** [comment]
Make a new ticket.

**Comment by DraxIndustries79** [comment]
@mikeapp will review with @bobrice
