### ISSUE TITLE
Pingdom alert for private URL

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1749]
**Story**

We'd like a pingdom alarm that will alert for a known private asset if the PDF or image returns an HTTP 2xx / success code.   

**Acceptance**
- [ ] Alarm triggers if https://collections.library.yale.edu/pdfs/31909488.pdf returns HTTP 2xx / success
- [ ] Alarm triggers if https://collections.library.yale.edu/iiif/2/31909491/full/90,/0/default.jpg? returns HTTP 2xx / success

**Comment by DraxIndustries79** [comment]
Bob will check to see if they have access here.

**Comment by bobrice** [comment]
Put in a request with LIT Client services to work on.  Steve Wieda is responsible for this monitor.
