### ISSUE TITLE
Don't check for OCR on S3 during Object Creation

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1750]
We have a mechanism to update Child Objects' full text status using a batch job.
Currently, the system also checks for OCR text during ingest, which may take a while.

- [x] Remove the check for OCR on S3 during child object creation.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/843

**Comment by FCRodriguez7** [comment]
Released management v2.52.4
