### ISSUE TITLE
Determine approach to Preservica authentication

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1757]
**Story**

Preservica enforces access control and units generally have access only to their own content.  We need to determine how DCS will authenticate itself - by individual user, user per admin set, or some other way.

**Acceptance**
- [x] Discuss and decide

**Comment by mikeapp** [comment]
Per @motropuk we will use credentials per admin set.

**Comment by motropuk** [comment]
Will use credentials per DCS admin set. This ticket can be closed
