### ISSUE TITLE
Review Delayed Job Dashboard Mockup

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1758]
- [x] Deploy dashboard_mockup branch to Demo (or some other environment that's available.)
- [x] Get feedback on mockup from users who use the delayed job dashboard.

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/df412fbc-c453-438b-8e16-7b8924cedd7d)

**Comment by FCRodriguez7** [comment]
@tmacmath could you talk about styling?

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/845

**Comment by FCRodriguez7** [comment]
@martinlovell 

Tracy and I looked at the new job status page this morning.  This is the minimal vital styling we want to provide as feedback to get this ticket out the door (see below).  We will create tickets for the other tables. 

![Screen Shot 2021-12-01 at 11.04.33 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ca11622b-30cf-4408-b814-c552a065370c)

**Comment by FCRodriguez7** [comment]
Tickets also must be created for the sub table tabs. 

Frederick
