### ISSUE TITLE
IIIF Presentation API v3 implementation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1760]
**Story**

We would like to begin using the the IIIF Presentation API v 3.0 for IIIF Manifests.

**Acceptance**

- [x] Requests for IIIF Manifests return a 3.0 Manifest
- Viewer functionality remains unchanged in both UV and Mirador
  - [x] Metadata display
  - [x] Image zoom
  - [x] Image thumbnails
  - [x] "paged" / two - up viewing
  - [x] Full-text search

**Comment by mikeapp** [comment]
Draft PR: https://github.com/yalelibrary/yul-dc-management/pull/846

**Comment by mikeapp** [comment]
PR out of draft.  We can complete the testing checks above on test / UAT.

**Comment by FCRodriguez7** [comment]
Released management v2.54.0
