### ISSUE TITLE
Migrate Divinity Library Manuscripts

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1761]
**Story**

Migration of the Divinity Library Manuscripts (PID 109) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the div admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the div admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
1 Complex parent: https://collections-uat.library.yale.edu/management/parent_objects/16850014
64 Simple objects:
https://collections-uat.library.yale.edu/management/batch_processes/521

**Comment by motropuk** [comment]
Have written to Divinity to ask if we can move into DCS Production

**Comment by motropuk** [comment]
I deleted a number of Parents from this collection which were duplications in Fedora. So there are now 32 parents in UAT. We should move these 32 parents only to Production https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1761

**Comment by MaggieZhaoYale** [comment]
32 
 simple objects are in the prod: https://collections.library.yale.edu/management/batch_processes/6235/parent_objects/17147576 (please ignore the failed message on the 9 parents, if you click the parent oids, you will see they were completed)
1 complex parent https://collections.library.yale.edu/management/batch_processes/6234/parent_objects/16850014
