### ISSUE TITLE
Index additional Parent Object fields

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1763]
**Story**

Filtering on Parent Objects in the datatables is slow.   We should index more fields that allow filtering.

**Acceptance**
Add indexes on the following Parent Object fields:
- [x] call_number
- [x] aspace_uri
- [x] bib
- [x] barcode
- [x] item
- [x] holding

**Comment by K8Sewell** [comment]
Draft PR: https://github.com/yalelibrary/yul-dc-management/pull/849

**Comment by FCRodriguez7** [comment]
Released management v2.54.2

**Comment by FCRodriguez7** [comment]
This needs a time estimation
