### ISSUE TITLE
raise the limit of  imagemagick 

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1765]
Story: TIFF images can up to 4GB. Recently, we have an image over 3GB, it failed because the size is bigger than the max size in the setting of  imagemagick.

- [ ] Raise memory size to 4GB temporarily in container

- [ ] Raise pixel size

**Comment by DraxIndustries79** [comment]
Stakeholders will limit image input size to 2GB themselves.
