### ISSUE TITLE
Bring code coverage back to 97% or greater - Management

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#1766]
# Summary
Current code coverage is 95%.  This ticket aims to increase the coverage to 97% or greater.

# Acceptance
- [x] Increase code coverage

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/183b934d-1953-45d0-9a53-1fd8b918f92d)

**Comment by K8Sewell** [comment]
Does anyone understand why one of these is 100% and the other is 0% with identical ish tests?

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/342a8e28-87fd-4521-be87-bd87b1782c86)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/f0329b0b-4dca-45d5-88a0-a96f14b1d574)

**Comment by DraxIndustries79** [comment]
https://docs.coveralls.io/parallel-build-webhook

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/850
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/afa9ac39-05e3-4265-a35d-d59d3942d5e9)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.58.4
