### ISSUE TITLE
IIIF Manifests: change "Provider" back to "Attribution" in label?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1768]
v2:

![Screen Shot 2021-11-22 at 9.27.04 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/8dd6e5c4-4708-42d5-96ad-c91059dfc234)

v3 changed to:
![Screen Shot 2021-11-22 at 9.25.54 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b231a77b-d95a-4040-89b5-98cadaa2966b)

IIIF v2 had an `attribution` field that was always shown and was populated with "Yale University Library".  In v3 this is now `requiredStatement` and the label(s) are configurable.  I used "Provider" for the label, but perhaps should change it back to "Attribution" so it looks exactly like v2?

The museum community requested the removal of "Attribution" because of the use of the term with regard to the creator of the object (e.g., "attributed to Turner").

**Comment by motropuk** [comment]
Keep as Provider. Closing ticket
