### ISSUE TITLE
Modal trigger link

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1770]
The modal trigger link in the facets should be the same font size and color as the links above it. 

**Current Design**
![Screen Shot 2021-11-23 at 12.34.58 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/3ff2771f-cb89-44d5-b657-84c32ebf8482)

**Propose Design**
![modal-link-mock.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/bef4e7a6-eb02-4993-a7a3-e34f4268049f)

**Acceptance criteria:**
- [x] Font size should be 12px
- [x] Link color should be #006EF5
- [x] First letter should be capitalized (More >>)

**Comment by tmacmath** [comment]
![modal-link-mock.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/e7d65fbf-3f73-4c71-a224-ee782a6915e1)

**Comment by tmacmath** [comment]
![modal-link-mock.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/bef4e7a6-eb02-4993-a7a3-e34f4268049f)

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/730

**Comment by FCRodriguez7** [comment]
Released blacklight v1.58.4

**Comment by motropuk** [comment]
Looks good on UAT

**Comment by mikeapp** [comment]
Looks good
