### ISSUE TITLE
Investigate long time enqueued GeneratePdfJob

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1771]
Story: There are 2883 enqueued PDF job on delayed job dashboard: https://collections.library.yale.edu/management/delayed_job/overview?queues=pdf
Goobi Object ingested on Nov.5 and Nov22, and objects ingested after Nov.5 do not have PDF.
e.g. https://collections.library.yale.edu/management/batch_processes/6198/parent_objects/32250238

- [x] Check if intensive worker is running

- [x] GeneratePdfJob is functional

**Comment by mikeapp** [comment]
The intensive worker is running and it looks like the number of PDF jobs in the queue is slowly decreasing.

**Comment by mikeapp** [comment]
We should watch this until the queue is empty, its possible that the worker thread is crashing and being restarted on Wednesdays when we redeploy (?).
