### ISSUE TITLE
Add FEATURE_FLAGS configuration to Camerata

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1772]
The FEATURE_FLAGS environment variable will be used to turn features off or on.

First use will be: if the FEATURE_FLAGS includes |DO-SEND|, digital object change notification is turned on.
The idea is that the value will contain a pipe delimited list of feature flags.

- [ ] Configure Camerata to supply this environment variable based on a corresponding value in the parameter store.

This will be an opportunity to test the documentation on adding a new parameter to the containers.

**Comment by martinlovell** [comment]
Blocked:  I'm having trouble finding the documentation on what files to edit (docker-compose files) to add a new variable.  

(I see the info about setting values in the parameter store using the commandline, but not the files that need to be edited to get them into the containers.)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/328/files

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.4
