### ISSUE TITLE
Review Open Graph metadata in Facebook, Twitter, etc.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1773]
**Story**

Received a report that Facebook is showing the IIIF logo and not the page thumbnail that is provided in the object page's Open Graph metadata.

https://ogp.me

![Screen Shot 2021-11-29 at 11.51.58 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/84f259db-72ef-4561-bca0-07d85c98c5aa)

https://collections.library.yale.edu/catalog/11530121

**Acceptance**
Object thumbnail should appear when page link is posted in
- [ ] Facebook
- [ ] Twitter

**Comment by FCRodriguez7** [comment]
Image appears busted in twitter: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2e68d254-b7fc-4686-8d0f-1f21408b98f0)

**Comment by FCRodriguez7** [comment]
Currently reading this https://www.opengraph.io/examples/ruby-open-graph-example/

**Comment by FCRodriguez7** [comment]
Not really fixed yet: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ef765af1-86d5-4aa6-bf3a-ecfd51c5cdd3)

**Comment by FCRodriguez7** [comment]
Blocker until the code reaches production.

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.1

**Comment by DraxIndustries79** [comment]
This needs to be tested in production after the 1/5 release and if it doesn't work we'll move this ticket back.

**Comment by FCRodriguez7** [comment]
The patch for this feature works; however, there's an odd behavior with the Facebook post, see the mini clip below. 

https://images.zenhubusercontent.com/242185115/54825a26-ca94-48c4-a1bb-d569f9c60183/1773_facebookbehavior.mov

**Comment by martinlovell** [comment]
Alison pointed out the card invalidator for facebook that we could try if we find some are caching the IIIF image. 
https://developers.facebook.com/tools/debug/sharing/batch/
(It requires a facebook login.)
