### ISSUE TITLE
Re-size h1 in modals

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/YUL-DC#1774]
Change the h1 to an h2 - it is better for accessibility, since the modal is acting like a new section of top-level content. 

Acceptance criteria: 

- [x] Change h1 in modals to h2

**Comment by tmacmath** [comment]
This needs to be an actual h2 - we cannot just change the font size currently associated with the global h1.

**Comment by FCRodriguez7** [comment]
The modal was customized.

**Comment by FCRodriguez7** [comment]
completing the test for the feature.

**Comment by FCRodriguez7** [comment]
The PR: 
https://github.com/yalelibrary/yul-dc-blacklight/pull/732

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.0
