### ISSUE TITLE
[DISCUSSION] Discuss plans for redirects in Parent Objects

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1775]
**Story**

An earlier spike (#1696) investigated how best to offer redirects when an object was deleted.   The recommendation was to "soft delete" parent objects.   The parent object would store the redirect target.

**Acceptance**
- [ ] Discuss recommendations
- [x] Create further tickets

**Comment by jpengst** [comment]
Example of how we can redirect: https://github.com/yalelibrary/yul-dc-blacklight/pull/726
