### ISSUE TITLE
Redirects: add redirect_to to Parent Object

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1776]
**Story**

We would like to support redirects for Parent Objects via a "soft delete" mechanism that retains the Parent Object record.   To do this we need to store and make editable a field to contain the destination URL.

**Acceptance**

- [x] Add the field `redirect_to` (text) to the Parent Object model
- [x] Validate url - at least 'yale.edu' addresses
- [x] Add an index for the field
- [x] Display the field on the Parent Object view page, immediately beneath the Project ID.   Do not display the field if it is blank.
- [x] Redirect To field is only displayed when a Parent Object has 0 children
- [x] Add a field to the Parent Object edit form in a new row of its own, beneath "oid" and above "metadata source"
- [x] Add a "Redirected Parent Object" datatable - Datatable will only display parent objects that have been redirected.
 - [x] Remove redirected parents from parent object datatable query
- [x] Add mechanism for when 'redirect_to' is filled out that prevents user from saving without acknowledging this will remove this record from blacklight. After the user has confirmed the parent object will be deleted from blacklight and submits the form, they will be redirected to the minified parent showpage 
- [x] Add "Redirect" to `visibility_ssi` when creating new redirect parent

**Comment by jpengst** [comment]
For `Add filter to datatable - redirect_to or not redirected results`, do we want this to be an additional filter (button/toggle)?

**Comment by jpengst** [comment]
is the "Redirect To" field only supposed to be visible when the parent has no children? Or do we always want to display the field on the parent object /edit page?

**Comment by mikeapp** [comment]
It might be helpful to have both a boolean filter and the ability to search/filter to specific values.

**Comment by K8Sewell** [comment]
# Videos
### Parent Object with Children does not display 'Redirect To' on edit form
https://images.zenhubusercontent.com/242185115/419df286-0bb0-456b-b089-01f107aba7ef/screen_recording_2021_12_09_at_10_24_39_am.mp4

**Comment by jpengst** [comment]
Modal and URL format messages:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/e3afdeb6-7c34-4994-9ea0-1c871d5769b3)  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/419ef4b3-5961-4ffd-8dd0-cd06404c872e)

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/859

**Comment by mikeapp** [comment]
Looks good and meets the criteria.  Some items for discussion:
* I attempted to reverse the process: I reassociated children back to the parent and changed the visibility but could not update metadata for the object.  This needs a new ticket, or else we should be explicit that there's no return without deleting the object.
* Setting the redirect clears the record, including  the catalog identifiers.  The IDs might be helpful if someone wanted to know what this object once was.

**Comment by mikeapp** [comment]
@FCRodriguez7  It wasn't merged b/c it was in draft.  I just merged it.

**Comment by FCRodriguez7** [comment]
This is the correct release for the ticket: Released management v2.55.5

**Comment by DraxIndustries79** [comment]
On hold for the next release.
