### ISSUE TITLE
Migrate LWL collection (UAT portion)

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1778]
**Story**

We need to take a different approach to migrating LWL's collection from findit to DCS, replacing what we previously did in #1723 and #1744. LWL's collections in Ladybird/Findit are complicated and using our normal migration method resulted in a mismatch in terms of number of objects brought over. LWL have said that Voyager should be considered the most reliable source for their digital collection. Therefore we will work on pulling all of the digColl numbers current in Voyager for LWL items, and then use these numbers to extract objects from Fedora. We will migrate these objects only to DCS.   

**Acceptance**
- [x] Email Tech Services (copying Ellen) to request a list of all digcol numbers listed in LWL records in Voyager 
- [x] Delete existing LWL objects in UAT so there are no LWL parents left
- [x] Pull subset of objects from Fedora using digcol numbers (Jon will provide list of for this subset)
 - [x] Import subset image files into the DCS pairtree
 - [x] Import the 1st subset objects into DCS UAT into the LWL admin set
 - [x] Audit 1st subset objects in DCS UAT with LWL
 - [x] Import the 2nd subset objects into DCS UAT into the LWL admin set
 - [x] Audit 2nd subset objects in DCS UAT with LWL
- [x] Pull remaining items from Fedora
- [x] Import remaining items image files into the DCS pairtree
- [x] Import the remaining items into DCS UAT into the LWL admin set
- [x] Ensure all LWL items are Public
- [x] Add holdings aka MFHD IDs to DCS items
- [x] Audit full set with LWL in UAT
- [x] Begin conversation with LWL about Voyager reassociation

**Background**
Alison's LWL notes and selected files are here: https://yale.box.com/s/bef7hjcs4z2gv6atuuolrj3zx5l1ppzy

**Comment by motropuk** [comment]
Yukari created Voyager export with Digcoll numbers, but waiting on input from Ellen to help interpret this and create a list of select Digcoll numbers we can use as a test migration

**Comment by motropuk** [comment]
Ellen is currently cleanup export from Voyager and selecting 500 digcoll numbers we can use for an initial migration

**Comment by motropuk** [comment]
Here is the subset of objects we can migrate to UAT now. Digcoll number is in Column B. These could be in either Project 60 or 23 so need to think through how to do this [https://app.zenhub.com/files/242185115/3ea450d6-8fc3-4747-a038-55b193b08e4d/download](https://app.zenhub.com/files/242185115/3ea450d6-8fc3-4747-a038-55b193b08e4d/download)

**Comment by MaggieZhaoYale** [comment]
Tested two digColls from the list (one simple, one complex)
https://collections-uat.library.yale.edu/management/batch_processes/549 @motropuk 

Downloading images of other objects is in progress

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/batch_processes/554/parent_objects/16944842 does not have the child 16944888 in fedora (it is in the ladybird)

**Comment by MaggieZhaoYale** [comment]
@motropuk https://collections-uat.library.yale.edu/management/batch_processes/554 is ready to review. Please ignore the failed objects which were re-processed. 
The only failed parent https://collections-uat.library.yale.edu/management/batch_processes/554/parent_objects/16944842 does not have the child 16944888 in fedora (it is in the ladybird)

**Comment by motropuk** [comment]
Re child 16944888 for parent 16944842 - while this has a thumbnail preview in Ladybird, there is no image in Fedora for it. No hydra ID is supplied for this image. This page also does not display on the front end in Findit. I am therefore going to delete this child in UAT

**Comment by motropuk** [comment]
Looks like there are more objects we need to pull over to UAT. The sample list LWL supplied lists 634 objects. There are only 335 in UAT at the moment.

**Comment by motropuk** [comment]
Emailed LWL. Waiting for response, which will probably be in the new year now, so adding a waiting label to this ticket

**Comment by motropuk** [comment]
@alisonclemens will take the lead on this migration with LWL going forward

**Comment by DraxIndustries79** [comment]
Reviewing initial test loads.

**Comment by DraxIndustries79** [comment]
Check in early week of 2/1

**Comment by DraxIndustries79** [comment]
Alison continuing to work with stakeholders

**Comment by motropuk** [comment]
Deadline March 22nd to complete this migration

**Comment by motropuk** [comment]
Remaining UAT work
- Ellen is spot checking records following a batch process update Alison applied to add MFHD ids to each record in DCS UAT
- Ellen is running some tests to update child object Labels and Captions
- Jon and Summer are working on problem items here https://docs.google.com/spreadsheets/d/1TyJrGSGHlVUkrz2mDfHF5SsuOqZ9CJYo052Qc561WMc/edit#gid=0
It looks like we have solutions for most things except rows 1-13 which we will focus on

**Comment by motropuk** [comment]
Update

- Ellen is still spot checking records following a batch process update Alison applied to add MFHD ids to each record in DCS UAT
- Ellen is still running some tests to update child object Labels and Captions
- Summer working on lines 3-13 of https://docs.google.com/spreadsheets/d/1TyJrGSGHlVUkrz2mDfHF5SsuOqZ9CJYo052Qc561WMc/edit#gid=0

**Comment by motropuk** [comment]
Have emailed LWL to suggest we move forward with the production migration starting the week of Apr 25th. We have fixes or solutions in place now for most of the problematic objects, which we will work on fixing after migration to prod in #1950. If stakeholder is happy to move forward, we will close this ticket at the end of this current 2 week sprint, and start #1950 at that time

**Comment by motropuk** [comment]
We can close this ticket once we add points and move onto Production ticket #1950
