### ISSUE TITLE
Redirects: Index "redirect" objects into Solr for parents with a redirect

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1781]
**Story**

To implement redirects in Blacklight the "deleted" parent with a redirect will need to be indexed differently.  

**Acceptance**
- [x] When the parent object is assigned a redirect URL, index a minimal object into Solr that has the field that contains the URL.

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/861

**Comment by mikeapp** [comment]
@K8Sewell Looks good but has a merge conflict.

**Comment by FCRodriguez7** [comment]
Released management v2.55.7
