### ISSUE TITLE
Redirects:  Implement Blacklight redirect handling 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1782]
**Story**

When the parent OID in Solr contains a redirect object instead of a full parent object, send a redirect to the browser.

**Acceptance**
- [x] "redirect" parent objects result in a redirect being sent to the broswer
- [x] other parent objects display normally
- [x] the auth service rejects auth requests (for pdfs, or manifests) of a "redirect" parent
  - [x] results in not found
  - [x] tests exist for this case

**Comment by K8Sewell** [comment]
PR Ready for review: https://github.com/yalelibrary/yul-dc-blacklight/pull/737

https://images.zenhubusercontent.com/242185115/831c8336-28cf-4e07-86e7-1905ce546906/screen_recording_2022_01_06_at_03_30_06_pm.mp4

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.5

**Comment by K8Sewell** [comment]
I'm a little hesitant to redirect objects arbitrarily even on test.  Are there any records that were waiting for this feature I can utilize @motropuk?

**Comment by motropuk** [comment]
@K8Sewell Here is the example BRBL provided for redirect. 

They want this https://collections.library.yale.edu/catalog/10081383 to redirect to this https://collections.library.yale.edu/catalog/17451921?child_oid=17451962

@alisonclemens if you have other examples or suggestions, please feel free to add

**Comment by K8Sewell** [comment]
We were unable to get a copy of the scrapbook into the test env but we were able to prove the redirect works in blacklight.  

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/7622b534-f9bf-4469-a6a9-741ff019faf2)

# Video

https://images.zenhubusercontent.com/242185115/f66b630d-fd63-4f7e-89b6-f5dbf239aed6/screen_recording_2022_01_10_at_02_57_14_pm.mp4

**Comment by mikeapp** [comment]
Deploying to UAT.
