### ISSUE TITLE
Redirects: Support setting redirect_to during "Update Parent Objects"

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1783]
**Story**

Users would like to set the redirect URL when updating parent objects via batch jobs.

**Acceptance**
- [x] Accept a redirect URL in the Update Parent Objects batch job.
- [x] Provides warning to user if there are still child objects attached to parent
- [x] Provides validation for redirect to

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/870

**Comment by K8Sewell** [comment]
adding 'redirect to' to template

**Comment by K8Sewell** [comment]
PR Ready - https://github.com/yalelibrary/yul-dc-management/pull/870

**Comment by FCRodriguez7** [comment]
Released management v2.56.4
