### ISSUE TITLE
Redirects: Support setting redirect via "Reassociate Child Oids" batch jobs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1784]
**Story**

Beinecke would like to be able to redirect objects that lose all children during reassociation batch process.

**Acceptance**
- [x] If all children of a parent OID are transferred to the same destination parent OID during the "Reassociate Child Oids" batch job, create 'redirect_to' for the empty parent and assign it a redirect to the destination parent.
- [x] Job should not be able to reassociate children to a 'redirected_to' parent

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/883

### Screenshots
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/b02eb309-9ebd-4ca0-91ef-325fd2be1c34)

**Comment by FCRodriguez7** [comment]
Released management v2.58.4

**Comment by mikeapp** [comment]
Looks good on UAT.
