### ISSUE TITLE
Migrate Day Mission Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1785]
**Story**

Migration the Day Missions Collection (PID 28) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Div admin set
 - [x] Audit objects in DCS UAT
 - [x] Import the objects into DCS PROD into the the Div admin set

**Comment by MaggieZhaoYale** [comment]
Parents do not have active children:16387268,16387791,16387865,16387141,16388279,16387368,16387457,16388118,16387556,16387629
A total of 241619 images

**Comment by MaggieZhaoYale** [comment]
Majority of ptiff creation failed in UAT

**Comment by MaggieZhaoYale** [comment]
e.g. check 11054186.tif with "identify"

11054186.tif TIFF 2362x3463 2362x3463+0+0 1-bit Bilevel Gray 80284B 0.000u 0:00.011
identify: Unknown field with tag 41728 (0xa300) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: Unknown field with tag 42016 (0xa420) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Failed to read custom directory at offset 3748. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Unknown field with tag 41728 (0xa300) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: Unknown field with tag 42016 (0xa420) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: delegate library support not built-in 'yul_dc_store_8/86/11/05/41/86/11054186.tif' (XML) @ warning/profile.c/ValidateXMPProfile/1690.

**Comment by motropuk** [comment]
Tiff images threw up an error when opening in Photoshop. They are also very small e.g 80K for a tiff! We managed to open an image, and then resave it in GIMP. The resaved image they successfully converted to PTIFF. 

During resave, we also removed any compression algorithm. Maggie will explore if we can do somehow batch process all the images in this collection, to do whatever GIMP did when resaving.

**Comment by MaggieZhaoYale** [comment]
Some parent only have inactive children:
11086066
11086160
11107268
16388118
child: 16041231 of 16035431 is inactive
child: 11680077 of 11680050 is inactive

**Comment by motropuk** [comment]
Reviewed this in UAT and found some issues 
- There are 6999 parents for PID 28 in Ladybird, but only 3360 parents migrated to UAT
- Only 2913 out of the 3360 parents that did make it to UAT are displaying in blacklight https://collections-uat.library.yale.edu/catalog?f[project_identifier_tesi][]=28&q=&search_field=all_fields. 6 parents are set to private, and Maggie noticed 8 parents with inactive images, but this still leaves a difference of 461

So open questions still to resolve 
- Why did only 3360 out of 6999 parents migrate
- Why are such a large number of the parents that did migrate not displaying in Blacklight

**Comment by MaggieZhaoYale** [comment]
ladybird uat has an issue. Metadata cloud could not get the data from ladybird uat. Richard has the access. He is in PTO until tomorrow.

**Comment by MaggieZhaoYale** [comment]
Parent could not found in Ladybird:

oid_16804879 
oid_16804881
oid_16804929 
oid_16804882
oid_11431593
oid_16804878
oid_16804880
oid_11126125
oid_17126607

oid_11126125

Some parent only have inactive children:
oid-16387457 76 images
oid-16387556 76 images
oid-16387141 119 images
oid-16387368 76 images
oid-16387629 72 images
oid-16388118 70 Failed

The following parents have children without images:
oid-11086160
oid-11086066
oid-16966113
images issue: 
oid_16853815 of  oid_16854157 failed to convert to ptif (ladybird does not have the image)
oid_16852118 of  oid_16852878 failed to convert to ptif
oid_16853609 of oid_ 16853627 failed to convert to ptif
oid_16853295 of  oid_16853467 failed to convert to ptif
oid_16852392 of  oid_16852882 failed to convert to ptif
oid_16852209 of  oid_16852879 failed to convert to ptif

Child without image:

oid_16768274 of parent  oid_16769603 no image
oid_16966164 no image
oid_child 16809813 of  oid_16813116 no image
oid_11523171 of oid_11523164 image false
oid_16786317 of  oid_16789871 no image
oid_16889338 of  oid_16892449 no image
oid_16966281 of  oid_16966184 no image
oid_16764178 of  oid_16764277 no image
Image issue:
oid_16853815 of  oid_16854157 failed to convert to ptif 
oid_16852118 of  oid_16852878 failed to convert to ptif
oid_16853609 of  oid_16853627 failed to convert to ptif
oid_16853295 of  oid_16853467 failed to convert to ptif
oid_16852392 of  oid_16852882 failed to convert to ptif
oid_16852209 of  oid_16852879 failed to convert to ptif


oid_11428432 of oid_11428388 no image
oid_16809845 of oid_16813117 no image
oid_16899690 of  oid_16900748 no image
oid_16772847 of  oid_16778815 no image
oid_11093453 of  oid_11093414 no image
oid_16888193 of oid_ 16892438 no image
oid_16900163 of  oid_16900755 no image
oid_11428382 of  oid_11428328 no image
oid_16592597 of  oid_16592625 no image
oid_16780970 of  oid_16780835 no image
oid_11653081 of  oid_11653017  no image
oid_16806244 of  oid_16806205 no image
oid_11664379 of  oid_11664373 no image
oid_11068584 of oid_11068468 no image
oid_16943812 of  oid_16944959 no image
oid_16908313 of oid_ 16915344  no image
oid_16899690 of  oid_16900748 no image
oid_16943606 of oid_16944957 no image
oid_11523861 of oid_ 11523850  no image
oid_11653081 of  oid_11653017 no image
oid_16943606 of  oid_16944957  no image
oid_11664379 of  oid_11664373 no image
oid_11093443 of  oid_11093414 no image
oid_11068592 of oid_11068592 no image

**Comment by MaggieZhaoYale** [comment]
@motropuk 6342 in UAT ( Fedora query got total 6352 parent)
The problematic issues were list in the previous comment. 
10 parent objects could not be found in Ladybird,so they do not show in the  result by filtering the proj 28.
oid_16804879
oid_16804881
oid_16804929
oid_16804882
oid_11431593
oid_16804878
oid_16804880
oid_11126125
oid_17126607
oid_11126125

**Comment by motropuk** [comment]
@MaggieZhaoYale Just checked this in UAT. I see we have 6342 parents in management which is good. Still short of the 6362 in Findit, but I can troubleshoot the remaining 20. You mention 10 of the missing above which is great. However, a bigger issue is that only 5159 are showing in UAT blacklight https://collections-uat.library.yale.edu/catalog?f%5bproject_identifier_tesi%5d%5b%5d=28&q=&search_field=all_fields. I check the visibility settings and those are fine. So there are still a number of objects that are not displaying in blacklight. I noticed that 16864427 and 16024279 dont have any children, but otherwise I am not why so many are not displaying.

**Comment by MaggieZhaoYale** [comment]
@motropuk The other 10 are following parents. They are not found in ladybird, so no projid show in the management. So far totally 6352 including these. The missing 10 could be inactive records because there are 6352 active records in fedora.
oid_16804881
oid_16804929
oid_16804882
oid_11431593
oid_16804878
oid_16804880
oid_11126125
oid_17126607
oid_11126125

So far i found: 32 parents has one child which does not have image or failed to convert to ptiff; 4 parents without children images, 6 parents only have the inactive children. 
I will compare the oids on the blacklight and 6352 to find out the list of oids not in blacklight

**Comment by MaggieZhaoYale** [comment]
@motropuk 94 parent failed in UAT. 
The issues are listed in the doc
[https://app.zenhub.com/files/242185115/70301f62-3e48-4c44-b58a-af138ce9d36e/download](https://app.zenhub.com/files/242185115/70301f62-3e48-4c44-b58a-af138ce9d36e/download)

**Comment by motropuk** [comment]
Only 4241 objects are in UAT. Our first attempt brought over 6342 which was good. That was still a little short of the 6362 objects for this collection that display in Findit, but close. The issue was that only 5159 of those 6342 were displaying in UAT Blacklight. I know we have 94 objects that have issues, but we now seem to be missing a lot of objects.

**Comment by MaggieZhaoYale** [comment]
117 failed in prod. This excel lists the failed parents in uat and prod [https://app.zenhub.com/files/242185115/28a0dd3e-10b8-447e-bd54-07f041cb4c60/download](https://app.zenhub.com/files/242185115/28a0dd3e-10b8-447e-bd54-07f041cb4c60/download)

**Comment by motropuk** [comment]
Production audit review happening here https://docs.google.com/spreadsheets/d/1kcxYqDlVwlqk4WZf_d3Cje4HAKXHiCEtevH3Sn3c8HU/edit?usp=sharing

**Comment by motropuk** [comment]
This just needs points and then can be closed. This took some time to complete so I think is probably and an 8 at least.
