### ISSUE TITLE
New Main Delay Job Table Design

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1787]
**User Story**
As the product designer, I want the new delay job main table to have the same styling as the rest of the application.   

**Current Design** 
![Screen Shot 2021-12-01 at 10.09.45 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c3393714-90f2-4799-92ec-83228afb35d7)

**Propose Design**
![Screen Shot 2021-12-01 at 1.43.01 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c292d571-2873-4476-b283-614eed14abb4)

**Acceptance Criteria**
- [x] create table heading 
- [x] create table subheading 
- [x] format table
- [x] style table 
- [x] style link for "the old jobs table"  
- [x] create tickets for sub-tables
     - [x] working 
     - [x] failed  
     - [x] pending  
   
_* this work excludes tables from the original mockup, such as enqueued and a second table displaying pdf and ptiff jobs._

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/845

**Comment by FCRodriguez7** [comment]
Released management v2.55.0

**Comment by FCRodriguez7** [comment]
The error column is messy.  Therefore, I am reaching out to @tmacmath about the error column.  Maybe the column could have the word 'log' or a word linked to the full error.

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/209472de-6fdc-4d49-9e29-242511970638)

**Comment by krcourville** [comment]
You could apply some truncation styling and maybe add a link to see "more".

some info on `text-overflow: ellipsis;`
https://www.w3docs.com/snippets/css/how-to-truncate-multi-line-string-with-pure-css.html

**Comment by motropuk** [comment]
Looks fine on UAT
