### ISSUE TITLE
Add DigitalObject update hook when ParentObject is deleted

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1796]
Management has an hook for after_update on ParentObject to send a DigitalObjectUpdate to metadata cloud.

It should also send an update when the ParentObject is hard deleted.

DigitalObjects should be deleted when ParentObjects are deleted.

- [x] If a ParentObject has a DigitalObjectJson value that is not nil, send an update to metadata cloud when the Parent is deleted with the prior object containing the DigitalObjectJson value and the new object being null.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/854

**Comment by FCRodriguez7** [comment]
Released management v2.55.2
