### ISSUE TITLE
Migrate Drama School Collection

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1797]
**Story**

Migration the Drama School Collection (PID 6) from Findit into DCS

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Arts admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the Arts admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
850 are in the UAT.
https://collections-uat.library.yale.edu/management/batch_processes/531
Please ignore 179 failed. After re-processed a few time, they all completed.

**Comment by MaggieZhaoYale** [comment]
@motropuk Handle excel: [https://app.zenhub.com/files/242185115/b2454c01-96fb-467a-a894-547c3eacb9fd/download](https://app.zenhub.com/files/242185115/b2454c01-96fb-467a-a894-547c3eacb9fd/download)

**Comment by motropuk** [comment]
Can be moved to Production

**Comment by MaggieZhaoYale** [comment]
@motropuk 850 objects are in the Prod
https://collections.library.yale.edu/management/batch_processes/6419 Please ignore the failed objects. They were completed after re-proceeded

**Comment by motropuk** [comment]
4 of the parents for the collection are not displaying in Prod blacklight - see https://collections.library.yale.edu/catalog?f[project_identifier_tesi][]=6&q=&search_field=all_fields. @MaggieZhaoYale is investigating

**Comment by motropuk** [comment]
This is all set and can be closed
