### ISSUE TITLE
Update mapping for Creator in ASpace

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1799]
**Story**

DCS metadata mapping to ArchivesSpace currently pulls in creator information for an object from the collection level of a finding aid, if a creator is not presented at the file/item level. For example, for this parent object https://collections-uat.library.yale.edu/catalog/15603880 the creator listed, is the creator of the collection, listed at the collection level in ArchivesSpace for the collection this item belongs to. This is made obvious on the Archives at Yale record for this item https://archives.yale.edu/repositories/12/archival_objects/802216 which shows that the Creator is "From the collection".

We would like to follow this same principal in DCS. When the creator of an object is inherited from a higher level of description in the archival hierarchy in ASpace, the entry in DCS should be prepended with _From the Collection:_

So for the example listed above, the entry would be _From the Collection:_ Goel, Ravi D.

**Acceptance**
- [ ] For objects associated with ASpace, when Creator information is inherited from a higher level of description in ArchivesSpace, the entry should be prepended with the statement _From the Collection:_
- [ ] Reindex ASpace sources for all admin sets

**Comment by martinlovell** [comment]
There's a similar request for ASpace/QS integration which has a different prepended string based on where the creator is found in the hierarchy.  So, in addition to "From the Collection:", there could also be "From the Series:"  (There may be an agent on a parent archival object which is not a series.  Should that also be labeled "From the Series"?)

Ideally  we can distinguish the creators the same way in QS and DCS.  Using "From the Collection" for all creators off the parent will be the easiest to implement, but if we need the "From the Series" distinction in QS, we can ideally implement that while we are adjusting for this DCS change.

**Comment by motropuk** [comment]
For now, we should just use "From the Collection" when inheriting a creator from a Resource record or any superior archival object, regardless of the type. From the series would not make a lot of sense to users, and we generally don't use creators at series levels.

**Comment by martinlovell** [comment]
It looks good on UAT, and matches the corresponding list in Archives Space
https://collections-uat.library.yale.edu/catalog/30003166 (https://archives.yale.edu/repositories/11/archival_objects/445449)
https://collections-uat.library.yale.edu/catalog/17327104 (https://archives.yale.edu/repositories/11/archival_objects/680179)
https://collections-uat.library.yale.edu/catalog/17298316 (https://archives.yale.edu/repositories/11/archival_objects/192469)
