### ISSUE TITLE
Batch job to export all parent objects from one or more Admin Sets

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1802]
**Story**

Users would sometimes like to export all of their data about Parent Objects for analysis in Excel, etc.   These exports are too large for the Datatables to support.

**Acceptance**
- [x] A new batch job "Export all Parent Objects by Admin Set" is created
- [x] The batch job input CSV processes one column, `admin_set`
- [x] The batch job confirms that the user has read access to all of the admin sets in the CSV.  If not, it logs an error and terminates.
- [x] The batch job exports all of the same columns that are displayed in the datatable view, in the same order.
- [x] The results are ordered by admin set code and then by `oid` within each admin set.

**Comment by K8Sewell** [comment]
# Screenshots

### Produced CSV
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9ad95455-3944-46d6-bd3a-71d19e44c44e)

### Error Message
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/abb10971-3102-4db8-be9c-bdd98c8a5662)

### Batch Process Option
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/17c32c9d-8d4c-448c-ac46-0f819d296173)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/863

**Comment by FCRodriguez7** [comment]
Released management v2.56.0

**Comment by mikeapp** [comment]
I am getting a timeout. for `brbl` on UAT.  Looking at the code, is this attempting to return results from a live query instead of generating the CSV asynchronously?

**Comment by jpengst** [comment]
Hmm. Yeah, the results are being returned in the csv_exportable where we're using a .where query. Sounds like this might need some adjusting?

**Comment by mikeapp** [comment]
New issues #1814 and #1815 to modify the child and parent exports to run the query only once and persist the data, then deliver the file when the user clicks the download link.

**Comment by DraxIndustries79** [comment]
We're going to keep this open to make sure that #1814 and #1815 don't affect this because we're changing the way admin sets are gathered.  Need to confirm this is still working following those.

**Comment by motropuk** [comment]
Tested this on UAT. Spotted two issues

- Download Template link does not seem to work for Export All Parent Objects by Admin set batch process
- When clicking on "Created file" link when process is done, I got a .txt file downloaded, rather than a .csv

**Comment by motropuk** [comment]
@jpengst @K8Sewell Tested this again. The issue seems to be on Chrome only. Managed to pull down the CSV as expected on Firefox. But when I click on the link to created file in Chrome, it downloads as .txt file. Tried on two instances on Chrome on different machines and get the same result. Must be a setting in Chrome somewhere I dont know about perhaps
