### ISSUE TITLE
Display and Filter by Subject Headings in Blacklight

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1810]
As a user, I want to see subject headings, and filter by full or partial subject headings.

The full subject headings  are in subjectHeading_ssim, containing the complete subject headings:
e.g `Music > England > London > History and criticism`

In blacklight, the display helper for the subjectHeading_ssim show field, should split by > and make each component a link to the subjectHeadingFacet_ssim with the full heading up to that point.

subjectHeadingFacet_ssim will be a facet in blacklight, without displaying in the facet area.
subjectHeading_ssim will be a show field in blacklight with a display helper.

Work has been completed to index the subject headings in Management:
https://github.com/yalelibrary/yul-dc-management/pull/862

Acceptance:
- [x] Subject headings display based on subjectHeading_ssim
- [x] Each component is a link which filters to documents with matching or partially matching subject headings.

Bonus Acceptance:
Stakeholders would like it if there was a visual clue that the links will consider the entire subject heading up to that point. With the links, if a user hovers over London in the example, it would be ideal if the the entire subject heading up to that point got the hover state. So, when the user hovers over London, the string "Music > England > London " would be highlighted so the user understands that they aren't just searching for London as a separate item, and that they will only get results with the entire subject heading up to that point.
If hover state is not possible, it may also be helpful to set the title for the link to be the Subject Heading up to that point, so that the tooltip or screen reader will let the user know what the link will search for.

**Comment by martinlovell** [comment]
![SubjectHeadingTEMP](https://user-images.githubusercontent.com/32851993/146831738-8c5357be-b60e-48bb-a912-14971386c479.gif)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/736

**Comment by martinlovell** [comment]
Possible way to do underlining (**Not** in the PR): 
![SubjectHeadingPossible.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/bcc06e19-4eda-458e-9ca1-062d841b7eb8)

**Comment by martinlovell** [comment]
Subject Heading on Test:
https://collections-test.library.yale.edu/catalog/15821075
https://collections-test.library.yale.edu/catalog/2000017
https://collections-test.library.yale.edu/catalog/800051943
https://collections-test.library.yale.edu/catalog/800049866
https://collections-test.library.yale.edu/catalog/800049872

**Comment by FCRodriguez7** [comment]
Release v2.55.6 and deployed

**Comment by martinlovell** [comment]
Examples on UAT:
https://collections-uat.library.yale.edu/catalog/900048109
https://collections-uat.library.yale.edu/catalog/900053855
https://collections-uat.library.yale.edu/catalog/900053442
https://collections-uat.library.yale.edu/catalog/900042013

Some examples with duplicates in Subject (Topic) fields:
https://collections-uat.library.yale.edu/catalog/900052098
https://collections-uat.library.yale.edu/catalog/900052021

**Comment by motropuk** [comment]
Shared this work with Mark Custer to review

**Comment by motropuk** [comment]
Looks good on UAT. Can close this

**Comment by martinlovell** [comment]
Blacklight release v1.59.4
