### ISSUE TITLE
IIIF: Updates for v3 validation.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1811]
**Story**

Validator caught some issues:
- The `label` for the PDF download needs to be updated to a language map.
- Image services should be within an array. 

**Acceptance**

- [ ] `label` is a language map
- [ ] Image services should be an array, even though there is only one.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/864

**Comment by FCRodriguez7** [comment]
Released management v2.55.7

**Comment by mikeapp** [comment]
I think this looks good on UAT, will re-validate manifests when deployed to production.
