### ISSUE TITLE
[SPIKE] Investigate ongoing PTIFF conversation failures

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1812]
**Story**

During a number of recent migrations, multiple images brought over from Fedora have been failing to successfully convert to PTIFF. We need to understand why this is happening. 

Filesize might be one reason.  See #1767 where 24 simple objects failed to convert to PTIFF. Maggie investigated and found that many of these were over 1GB in size, sometimes bigger. So did this cause the PTIFF failure?

Other examples where PTIFF is failing can be found in #1785 

Once we understand why this is happening we should either fix bugs etc accordingly, or document limitations/requirements for files being added to DCS e.g if files need to be under a certain size. This will inform some user documentation we will be creating in the new year for staff ingesting content into DCS. 

**Acceptance**
- [ ] Once we understand why failures are happening, either make necessary system changes or document file limitations/requirements

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/868

**Comment by FCRodriguez7** [comment]
Released management v2.56.2
