### ISSUE TITLE
Update to later Ruby version

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1813]
**Story**

As a system owner I'd like us to stay on a supported release of Ruby.  Per https://www.ruby-lang.org/en/downloads/branches/ it looks like we should move to Ruby 2.7, as the 2.6 EOL date is 2022-03-31.   We are using `phusion/passenger-ruby26:1.0.10` as the Rails base image.

**Acceptance**
- [x] Update the base image to a Ruby 2.7 image
- [x] Update Dockerfiles as needed in the yul-dc projects
- [ ] Test

**Comment by FCRodriguez7** [comment]
I wrote a message about pairing to Rob this morning.

**Comment by FCRodriguez7** [comment]
PRs

https://github.com/yalelibrary/yul-dc-management/pull/937

https://github.com/yalelibrary/yul-dc-blacklight/pull/767

https://github.com/yalelibrary/yul-dc-camerata/pull/334

**Comment by FCRodriguez7** [comment]
please complete this: cam build [environment]

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.7
Released management v2.59.5

**Comment by K8Sewell** [comment]
Tested UAT and Test.  Nothing appeared broken.
