### ISSUE TITLE
Export Child OIDs batch job reruns query on export

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1814]
**Story**

The "Export Child OIDs" batch job does not persist the output of the query it runs, so when the user clicks the link to download the output CSV, the query is run again.

The job should run the query once and persist the results.  When the user downloads the CSV output, it should deliver the file, not run the query again.

**Acceptance**
- [x] The batch job persists the results of the query to S3 
  - suggestion: use the "samples" bucket, `/batch/job/{number}/{name}`
- [x] The download link delivers the persisted results and doesn't execute the query again
- [x] The download process confirms that the user is logged in and has privileges to access to the batch job page

**Comment by K8Sewell** [comment]
# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/fc269001-a753-440e-9162-ed2101f58292)

**Comment by FCRodriguez7** [comment]
Released management v2.56.2

**Comment by K8Sewell** [comment]
looks good on test


![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/07ebc92c-ab6a-4950-9c0d-0809a57fb544)

**Comment by motropuk** [comment]
Also getting a .txt file rather than .csv for created file from this process
