### ISSUE TITLE
Bug in SubjectHeading indexing

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1816]
As a blacklight developer, I need subject headings mapped so that they can be displayed and faceted.

Subject heading indexing was not complete.
- [x] Update code to index subject heading
- [x] Add test for solr indexable to test for mapping

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/865

**Comment by martinlovell** [comment]
Subject Heading on Test:
https://collections-test.library.yale.edu/catalog/15821075
https://collections-test.library.yale.edu/catalog/2000017
https://collections-test.library.yale.edu/catalog/800051943
https://collections-test.library.yale.edu/catalog/800049866
https://collections-test.library.yale.edu/catalog/800049872

**Comment by FCRodriguez7** [comment]
Released v2.56.1 and deployment

**Comment by motropuk** [comment]
Can close this
