### ISSUE TITLE
Refresh DataTable more Quickly on First Refresh

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1817]
**Story**

As a management user, I would like the table to refresh more quickly the first time, so I can get feedback that the Batch Job I just submitted has been created.

We have javascript to refresh some datatables every 30 seconds: https://github.com/yalelibrary/yul-dc-management/blob/main/app/javascript/packs/application.js#L312

This works as expected; however, when a batch is first submitted and the table is displayed, it takes 30 seconds to see that job. 

If the table refreshes more quickly the first time, then the job will appear in the table sooner.  After the first refresh, it can refresh every 30 seconds as it does now.

**Acceptance**
- [ ] First table refresh occurs in ~ 3 to 5 seconds.
- [ ] Refreshes after the first one occur every 30 seconds.

**Comment by martinlovell** [comment]
This doesn't seem to be an issue anymore.  When I submit a batch, it shows up in the table right after it is submitted.

**Comment by martinlovell** [comment]
PR if needed: https://github.com/yalelibrary/yul-dc-management/pull/945

**Comment by DraxIndustries79** [comment]
@mikeapp to check this out when he's back.

**Comment by mikeapp** [comment]
@martinlovell  The PR is still in draft

**Comment by martinlovell** [comment]
Merged

**Comment by FCRodriguez7** [comment]
Released management v2.59.9
