### ISSUE TITLE
1/5 Deployment to Production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1818]
**Versions**

Management: v2.56.1
Blacklight: v1.59.4 

**Staging**
- [x] Mangement
- [x] Blacklight

**Production**
- [x] Mangement
- [x] Blacklight
- [x] Recycle image server tasks

Note:  Cam feature flag autoinstall in this release.

**Comment by bobrice** [comment]
complete

**Comment by FCRodriguez7** [comment]
The open graph patch looks good: 
Twitter
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3edd83bd-56e9-443e-99d0-964eecd2ad44)

Facebook: 
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/630790af-8ea2-4ddf-acc5-4b4b29119054)

See the note

**Comment by martinlovell** [comment]
Deploy looks good to me.

Updates one ILS item to test subject headings: https://collections.library.yale.edu/catalog/32249988
Reindex of ILS items is necessary for subject headings.

**Comment by motropuk** [comment]
We should create a new ticket for ILS reindex.
