### ISSUE TITLE
[SPIKE] Preservica API investigation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1819]
**Story**

The Preservica object model has a deep hierarchy and we potentially need information (file type, checksum, etc.) from different objects.   We should see whether the API has any methods to return aggregated data.

We could see up to 7 API calls per child if we need to retrieve each individually:

* Structural Object 
  * Children 
    * Child (Information Object)
      * Representations [representation type]
        * Representation
          * Content Object 
            * Generations [active or not]
              * Generation [format]
                * Bitstream [checksum]
                  * Content 

**Acceptance**
- [ ] Review the API docs and report back on whether there is a way to get either a nested response (for example, for a content object, return all of the generations and their bitstream descriptions in one request)

**Comment by mikeapp** [comment]
See my post in Slack with a link to the sample XML responses.

**Comment by FCRodriguez7** [comment]
A Few Consideration Points:
- There's not a one-to-one map from structure to a file or objects. 
-  Objects can be multiplied generation(s)
- Bitstream could be faulty
- The content object can be more than one
- Start at the content object for speed

Notes: 
The return of multiply calls and aggregated data was returned as a feature in v5 of the API.  The current version (v6) makes it difficult.
