### ISSUE TITLE
Store digital object source and  Preservica ID on Parent Object

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1820]
**Story**

We'd like to be able to load digital object structure and files from Preservica.  To do this, we need to designate items as having Preservica as their digital object source.  We also need to know the Preservica ID of the item.

**Acceptance**
- [x] Parent Object has a `preservica_uri` column
  - [x] this can be null or a string
- [x] Parent Object has a `digital_object_source` column
  - [x] valid values show be `null` and Preservica (or use a FK)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/874

**Comment by FCRodriguez7** [comment]
Release Management v2.57.0
