### ISSUE TITLE
Create Preservica logins for Music DCS Admin Set

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1825]
**Story**

DCS will need to log and use a specific Preservica login for each DCS admin set, to be used when making API calls to Preservica.  Each login will provide access to specific security tags in Preservica. We will need to work with each unit to work out which security tags the login for their admin set should be able to access. 

This ticket will test a single login for the Music Admin Set. Logins for other admin sets will then be setup via ticket #1849

**Acceptance**
- [x] Submit ticket to DPS to create login
- [x] Create Preservica DEV login for Music Admin Set that maps to MUSIC_OPEN and MUSIC_RESTRICTED security tags
- [x] Ensure there are objects in Preservica Dev with MUSIC_OPEN and MUSIC_RESTRICTED security tags
- [x] Add login to Parameter Store for DCS Test
- [x] Run test API call

**Comment by motropuk** [comment]
@mikeapp For the first acceptance point here, I am thinking this should probably be a separate ticket?

**Comment by motropuk** [comment]
List off all security tags currently in DCS Production https://yale.box.com/s/c0ivuo3o8a4pj35r1llcmddnt0r1wlsb

**Comment by motropuk** [comment]
Examples used until now both set to MUSIC_RESTRICTED. New Login can access these objects

The first, https://preservica-dev-v6.library.yale.edu/explorer/explorer.html#properties:IO&2bb7374a-bbd6-4f8d-a580-5dc2d6eddb02 , uses an alternate ingest workflow that results in a single asset (information object) with two different representations.

The second, https://preservica-dev-v6.library.yale.edu/explorer/explorer.html#browse:SO&7fe35e8c-c21a-444a-a2e2-e3c926b519c4&null, ingested with a standard workflow, results in a folder (structural object) with different assets (information objects) for each file. The have the intended respresentation (tiffs are Preservation type and the pdf is Representation type).

**Comment by mikeapp** [comment]
Credentials added on collections-test parameter store variable.  Next redeploy should pick up the new value.
