### ISSUE TITLE
AWS update: Restart services 

### ISSUE THREAD

**Issue by bobrice** [yalelibrary/YUL-DC#1826]
A software update has been deployed to the AWS Fargate infrastructure. This software update impacts the Amazon ECS services listed below.

This software update requires that the tasks in your affected services be relaunched by forcing a new service deployment in the US-EAST-1 Region. You can update your service and force a new service deployment using the AWS Management Console, AWS SDKs, or the AWS CLI.

If you do not complete this update before January 11, 2022, your service will be updated automatically by AWS.

How does this affect you?
In order for your Fargate tasks to be placed on the updated infrastructure, the tasks must be relaunched. When updating a service and forcing a new deployment, the service scheduler will stop all existing tasks and start new ones using the updated Fargate platform version. Data stored locally by the older tasks will be lost and cannot be recovered. The service scheduler ensures that the desired task count for your service is maintained. Your deployment preferences in terms of minimum healthy percent and maximum percent still apply.

What do you need to do?
We recommend that you update your service, specifying the force new deployment parameter, before January 11, 2022. For more information, see Task Retirement [1]. If you do not update your service by January 11, 2022, AWS will update the service on your behalf after this date.

/*Update services with force new deployment set*/ aws ecs update-service \ --service service_name \ --cluster cluster_name \ --force-new-deployment

What happens if you do not update before January 11, 2022?
If you do not complete this update before January 11, 2022, AWS will update the service on your behalf. Typically services, should see little to no interruption during and after the update. Please test your application for tolerance to periodic upgrades to ensure service availability.

Why is this update needed?
AWS Fargate continually updates the underlying infrastructure. Some of these updates require additional action by the customer or by AWS. This software update requires that all Fargate tasks that are running as a part of the services specified above be stopped so they can be relaunched.

**Comment by bobrice** [comment]
- [ ] yul-dc-test-images
- [ ] yul-dc-demo-psql
- [ ] yul-dc-prod-mgmt
- [ ] yul-dc-test-psql
- [ ] yul-dc-staging-mgmt
- [ ] yul-dc-staging-psql
- [ ] yul-dc-staging-intensive-worker
- [ ] yul-dc-prod-intensive-worker
- [ ] yul-dc-demo-intensive-worker
- [ ] yul-dc-demo-mgmt
- [ ] yul-dc-uat-psql
- [ ] yul-dc-uat-images
- [ ] yul-dc-demo-blacklight
- [ ] yul-dc-staging-blacklight
- [ ] yul-dc-staging-images
- [ ] yul-dc-demo-images

**Comment by bobrice** [comment]
DC Demo Deploys failed at the smoke test steps...

Please fix these tests to avoid failures in the future.
https://cm-prd.library.yale.edu/job/YUL-DC-Demo-Deploy/227/console

**Comment by mikeapp** [comment]
Working on it.  Code deployed to demo is out of date.

**Comment by mikeapp** [comment]
tests pass, had to reindex two objects using the new code for IIIF v3.
