### ISSUE TITLE
Dynatrace monitor: Disable for some environments?

### ISSUE THREAD

**Issue by bobrice** [yalelibrary/YUL-DC#1827]
This is to discuss whether, or not, to monitor all DC environments and/or services with Dynatrace.  Is there value to monitor every task and service in every environment?

**Comment by DraxIndustries79** [comment]
@mikeapp @FCRodriguez7 the rest of the team was OK with reallocating some licenses here (ie, no ones really using the tool on the call just want to check with you both)

**Comment by DraxIndustries79** [comment]
Mike Ok with reallocating, but we may need to revert if there's an issue with AWS monitoring
