### ISSUE TITLE
Reindex All ILS records in Production for Subject Headings

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1830]
ILS Records need to be re-indexed so that Subject Headings are available to the user.

- [ ] Reindex all ILS records in Production
- [ ] Spot check some records to verify that subject headings are visible and facet correctly.  (Some ILS records do not have any subject headings.  Quicksearch is a good place to see if a Bib record has subject headings.)

**Comment by motropuk** [comment]
Duplicate ticket for #1829. Closing this one
