### ISSUE TITLE
Add Series ID to Found In breadcrumb

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1832]
**Story**

The Found In breadcrumb at the top of the item pages and in the search results view should be updated to include the Series ID (romanized if a simple numeral). For example, this item https://collections.library.yale.edu/catalog/32207880 should have this breadcrumb, Found In: Manuscripts and Archives > Othniel Charles Marsh papers (MS 343) > Series I: General correspondence > Avery, John

Series ID information is already displaying in the Item Location field cluster, so it can be pulled in the same way it's being pulled there

**Acceptance**
- [ ] Review breadcrumb on search results to confirm Series ID is present (test Series IDs with simple numerals and Series IDs with complex indicators)
- [x] Review breadcrumb on item pages 
- [x] Value should match what is in the hierarchy on the show page

**Comment by alisonclemens** [comment]
**Story**

The Found In breadcrumb at the top of the item pages and in the search results view should be updated to include the Series ID (romanized if a simple numeral). For example, this item https://collections.library.yale.edu/catalog/32207880 should have this breadcrumb, Found In: Manuscripts and Archives > Othniel Charles Marsh papers (MS 343) > Series I: General correspondence > Avery, John

Series ID information is already displaying in the Item Location field cluster, so it can be pulled in the same way it's being pulled there

**Acceptance**
- [] Review breadcrumb on search results and item pages to confirm Series ID is present (test Series IDs with simple numerals and Series IDs with complex indicators)

**Comment by martinlovell** [comment]
From metadata cloud: ancestorDisplayStrings has the series ID, ancestorTitles does not.

ancestorDisplayStrings also typically has the dates appended to the series. (See example: https://collections.library.yale.edu/catalog/32207880)
@alisonclemens , is it okay if they also have the dates appended?

**Comment by martinlovell** [comment]
Looking at this some more, we also have a series value in solr that's the series with the prefix, but without the date.  So, I'll try to swap out the current title with that one.  (Unless you do want the date.)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/755

**Comment by martinlovell** [comment]
![SeriesTitle.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/7c1cdb02-30f6-4d14-8974-eb2711416189)

Note: The series title in the breadcrumb does not have the date as it does in the hierarchy.  Let us know if you'd like the date appended.

**Comment by motropuk** [comment]
Flagging the question above for @alisonclemens

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.0
