### ISSUE TITLE
Add or activate links in IIIF Item Viewer More Information pane

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1833]
**Story**

Functional requirements for archival context specified that 

a) The finding aid handle link (e.g., http://hdl.handle.net/10079/fa/mssa.ms.0343) in the More Information pane of the IIIF viewer should be active (i.e., it should be clickable for users)

b) The link to the AAY landing page for the component (e.g., https://archives.yale.edu/repositories/12/archival_objects/2019510 for https://collections.library.yale.edu/catalog/32207880) should be added to the More Information pane of the IIIF viewer; this link should also be active

**Acceptance**
- [ ] Finding aid handle links are confirmed active in viewer
- [ ] AAY landing page links for components are confirmed to be present and active in viewer

**Comment by mikeapp** [comment]
Needs discussion as to placement or label for the Archives at Yale page link.

![Screen Shot 2022-01-12 at 11.17.16 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/214903a1-8c9a-4ceb-ace5-6f4fc3fd030c)

**Comment by alisonclemens** [comment]
The above looks good to the archival context team -- thank you @mikeapp !

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-management/pull/877

**Comment by martinlovell** [comment]
Reindexed on test:
https://collections-test.library.yale.edu/catalog/800052256
https://collections-test.library.yale.edu/catalog/800052319

**Comment by FCRodriguez7** [comment]
Release Management v2.57.1

**Comment by motropuk** [comment]
Looks good on UAT https://collections-uat.library.yale.edu/catalog/16998726. 

Will need to reindex all ASpace in Prod for this to work, so need a ticket for that
