### ISSUE TITLE
Add sort by collection order functionality

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1834]
**Story**

In cases where the Collection and/or Grouping facets are selected, add sort by “Collection Order” to dropdown menu for sort options so that users can sort results (e.g., things in a collection in series 1 would appear before series 2, etc); add gentle prompt when collection or grouping facet is selected to ask if users want to sort by collection order

**Use case**

The main way to search for Thistlewood seems to be for "OSB MSS 176" or "thistlewood," delineated in quotes, which returns 61 items. To find a particular volume, you then need to browse the collection overall or know the date (which won't help entirely because some of the volumes have date spans). Sorting by relevance or by date does not help in this case

**Acceptance**

- [x] Sort by collection order appears and operates as expected when Collection facet is selected
- [x] Sort by collection order appears and operates as expected when Grouping facet is selected

**Comment by alisonclemens** [comment]
**Story**

In cases where the Collection and/or Grouping facets are selected, add sort by “Collection Order” to dropdown menu for sort options so that users can sort results (e.g., things in a collection in series 1 would appear before series 2, etc); add gentle prompt when collection or grouping facet is selected to ask if users want to sort by collection order

**Use case**

The main way to search for Thistlewood seems to be for "OSB MSS 176" or "thistlewood," delineated in quotes, which returns 61 items.  To find a particular volume, you then need to browse the collection overall or know the date (which won't help entirely because some of the volumes have date spans). Sorting by relevance or by date does not help in this case

**Acceptance**
- [ ] Sort by collection order appears and operates as expected when Collection facet is selected
- [ ] Sort by collection order appears and operates as expected when Grouping facet is selected

**Comment by martinlovell** [comment]
PR to add sort by "Collection Order" if the Collection or Grouping facet are selected: https://github.com/yalelibrary/yul-dc-blacklight/pull/760
I'm not sure how best to add the prompt.  I put the option at the top of the list just below the default (By Relevance) sort in the drop down.  We could display something when the facets are selected but sort by collection is not selected. 

With facet selected:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/5df184ec-a859-494a-97b6-089aa43e825f)
Without facet selected:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/2bf0c49a-c310-4bae-b8dc-d79e2294b07b)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.2

**Comment by motropuk** [comment]
Looks good on UAT. @alisonclemens Should review this too however

**Comment by fordmadox** [comment]
Just a quick note that the facet in the above screenshot has a repo value of Beinecke.... but the Found In links correctly display MSSA.  Not sure if that's just an issue with the test data, but just an FYI.
