### ISSUE TITLE
Terminology changes in IIIF and Blacklight

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1835]
**Story**

Following the terminology review we did in #1728, we would like to make the following changes (see [terminology sheet](https://docs.google.com/spreadsheets/d/1Te2FMhvP_urVmWNMQ0_1pRUBd-LDjIwNNooAj6RAiBI/edit#gid=0) for line references): 

- Change all references to Child OID in backlight, to Image ID
  - Line 2: URLs in blacklight, e.g https://collections.library.yale.edu/catalog/11861587?child_oid=11864874 should replace child oid with image id e.g https://collections.library.yale.edu/catalog/11861587?image_id=11864874.
  - Line 5: "Image OID" label in More Information panel in UV should display as "Image ID" e.g ![Screenshot 2022-01-06 110705.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/c57b8757-1790-4136-a176-ae69c0166fbf)

- Update references to OID for parents in blacklight, to Object ID (OID)
  - Line 3: "OID" label in More Information panel in UV should display as "Object ID (OID) ![Screenshot 2022-01-06 113914.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/1b3748f5-1375-4b41-90b2-7e882720c261) 
  - "OID label under Identifiers header on object page should be changed to Object ID (OID) ![Screenshot 2022-01-06 120104.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/3f1e998c-131c-4098-a55a-4474ffc6c71b)

**Acceptance**
- Blacklight
  - [x] OID in changed to "Object ID (OID)" in metadata display
  - [x] URLs to child objects in Blacklight follow this example https://collections.library.yale.edu/catalog/11861587?image_id=1186487 
  - [x] Existing links to child objects continue to work
- Management
 - [x] "Image OID" label in More Information panel in UV should be changed to "Image ID"
 - [x] OID is changed to "Object ID (OID)

**Comment by fordmadox** [comment]
That sounds great to me!  

One question: could the child object links still function (directly or via a re-direct) when someone uses the old "child_oid" format?  I'm not sure if we have examples out there, but I expect some exist in the wild by this point.

**Comment by mikeapp** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/889

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.10
Released management v2.58.6

**Comment by mikeapp** [comment]
Sample item in UAT: https://collections-uat.library.yale.edu/catalog/900057165

**Comment by motropuk** [comment]
Look good in UAT.
