### ISSUE TITLE
BUG/Spike: BRBL Ladybird parents in production with No Children

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1836]
There are 50+ ladybird/brbl parents with 0 children in production.
Find them: On parent object page, sort by # of children, review those with 0 children.

Some still have a show page in blacklight and appear in search results:
eg: https://collections.library.yale.edu/catalog/10268782
This one also has children in Metadata cloud and authoritative JSON.
On the show page in management, the SOLR document is blank, so it may be having trouble generating the JSON for the SOLR document.

(Some ladybird/brbl with 0 children are restricted, etc. and do not / should not have a show page.)

- [ ] Determine why 10268782 and similar parents are not indexed properly and have no canvases in the IIIF manifest, etc.

**Comment by fordmadox** [comment]
Thanks!  Just a note that some of the objects listed as "private" have essentially been deleted but are being kept around until staff can provide a re-direct.  Anyhow, please let me know what you find out about the others in case there are any changes we need to make.

**Comment by fordmadox** [comment]
@martinlovell :  I'm not sure if this issue is related, but just in case is is, here's another example OID to check: 32265308.  That has children, but the Solr record is also 'null'.  If you can let me know if there is anything that we need to do to fix records like that, we'll get on it!

**Comment by mikeapp** [comment]
Could this be related to #1828 ?

**Comment by martinlovell** [comment]
See comment on #1869

**Comment by mikeapp** [comment]
Observation: there are about 4,000 child objects in production with no width/height recorded.  There are also about 1,300 failed jobs, most of which are related to images not being found, or permissions issues.   We may need a separate ticket for remediation.

**Comment by motropuk** [comment]
I will note that this is impacting all ingests it seems. We are running Goobi scan once a day now. Many of these are still showing as being in process, days after the processes were started.

**Comment by DraxIndustries79** [comment]
Need to establish if there's a use case for a Parent with no Children

**Comment by K8Sewell** [comment]
PR to be refactored to account for slow loading of child objects and add  a check for if the parent has no children - https://github.com/yalelibrary/yul-dc-management/pull/893

**Comment by K8Sewell** [comment]
Videos and screenshots in PR - https://github.com/yalelibrary/yul-dc-management/pull/915

**Comment by FCRodriguez7** [comment]
Released management v2.58.20

**Comment by FCRodriguez7** [comment]
Released management v2.58.20

**Comment by DraxIndustries79** [comment]
Database is down so we may not be able to move this forward as usual.

**Comment by mikeapp** [comment]
Created revert commit after feedback.  Need to reconsider how to handle attempts to reindex object after partially successful ingest.

**Comment by FCRodriguez7** [comment]
Released management v2.58.21
for the revert

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/927

**Comment by mikeapp** [comment]
Merged spec change.

**Comment by FCRodriguez7** [comment]
Released management v2.58.25

**Comment by mikeapp** [comment]
Looks good on UAT.  Reassociated children of parent to two different parents, object was deleted from Solr.
