### ISSUE TITLE
Fix "Container/Volume" label width

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1838]
**Issue**

In Blacklight the "Container/Volume" label's width can result in the corresponding value being indented.  Reported by Mark C.

![Screen Shot 2022-01-07 at 9.36.19 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7a3d0efd-1a56-4e29-a0ed-c16ae666d699)![Screen Shot 2022-01-07 at 9.37.43 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/5c33914b-5212-4890-b05c-238b339debe8)![Screen Shot 2022-01-07 at 9.36.28 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/bfa99038-4f19-460d-8229-b92f05632569)

**Acceptance**
- [x] Value is left-aligned properly

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/764

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.5

**Comment by mikeapp** [comment]
Looks good!
