### ISSUE TITLE
Blacklight: filter digicoll handle links

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1839]
**Story**

In Blacklight we'd like to filter out/suppress links for ILS items in the format `http://hdl.handle.net/10079/digcoll/ ` since these are handles/permalinks that either point to FindIt or (after they are updated) to the record in DCS.  In other words, they are self-referential.

See https://github.com/yalelibrary/yul-dc-blacklight/blob/f06e40d09685bd7840271fcd999b0f9839ba6f35/app/helpers/blacklight_helper.rb#L298

Reported by Mark C.

See also #1808

**Acceptance**

- [x] digicoll handles are suppressed for ILS records in the method above

**Comment by motropuk** [comment]
Looks good in UAT https://collections-uat.library.yale.edu/catalog/11036106. Good to close
