### ISSUE TITLE
Test Image Server Performance viz memory & CPU

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#184]
**ACCPTANCE**
Conduct and document performance baselines for the IIIF image service for
- [x] 512cpu / 4GB memory (i.e. the current configuration)
- [x] 1024cpu / 4GB memory
- [x] 2048cpu / 4GB memory
- [x] ~512cpu / 16GB memory~ 1024cpu / 8GB memory
- [x] 2048cpu / 16GB memory
- [ ] any other cpu memory settings that seem worth testing (re decreasing  performance curves)

Analyze the results to determine whether 
- [ ] Performance improvement is flat, linear, or decreasing with additional memory
- [ ] Performance improvement is flat, linear, or decreasing with additional cpu
- [ ] Memory or CPU increases have a more direct impact on performance
- [ ] Performance bottlenecks appear to be unrelated to memory or cpu (i.e. mostly flat or shallow curve increases in performance)

REFERENCES
* https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/
* Valid Task Memory and CPU combinations https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html

**Comment by JzGo** [comment]
Collecting the results in google drive with a larger wrap up/summary to come: [imageserver load test results](https://drive.google.com/drive/folders/1hdUG206nLXbgC1xdULbjskhlIeMRu3Ir)

**Comment by fnibbit** [comment]
https://docs.google.com/document/d/13ETOfVn_NGRqYRgskqkBQEajylXIa9qTo-KCZqABI6k/ executive summary

https://docs.google.com/document/d/1txvQzVWRg3N3xe5HaN7Gk8SZzRV-E3VIqWzWgFL9jkM/edit individual test run graphs
