### ISSUE TITLE
Create parameter store value for Preservica credentials

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1840]
**Story**

The system requires Preservica creds for each Admin Set in order to allow imports.

**Acceptance**

- [x] Create a parameter store `SecureString` value `PRESERVICA_CREDENTIALS` for each environment
   - [x] Populate the value as an empty JSON object, i.e., `{ }`
- [x] Modify camerata to make the value available to the management and normal worker docker containers.

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-camerata/pull/331

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.6

**Comment by mikeapp** [comment]
Invisible change, #1842 will surface any problems.
