### ISSUE TITLE
Display flash message on Admin Set page if Preservica not configured

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1842]
**Story**

As a developer or an admin user I'd like to know whether the AdminSet has Preservica credentials available.

See #1841 for the expected JSON format on the environment variable.  You can test the failure cases after #1840 is done by adding simulated credentials in the expected format.

**Acceptance**

- [x] Create a method on the admin set that returns true if the `PRESERVICA_CREDENTIALS` environment variable:
  - exists
  - is valid JSON
  - contains the admin set code as a key (e.g., `brbl`)
  - the key references an object that contains the `username` and `password` keys with non-blank values
- [x] On the Admin Set display page, show an alert flash message if the above is false:  "Preservica credentials not configured for this Admin Set"

**Comment by K8Sewell** [comment]
Is this screenshot acceptable?
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/bd6d1ae3-7559-4d3e-a0f9-f6174f144453)

**Comment by jpengst** [comment]
Flash Message:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/df19c22b-2192-4512-b954-33da2bbcf442)

**Comment by DraxIndustries79** [comment]
Flash message version.  Maybe yellow?  (Not green)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/890

**Comment by FCRodriguez7** [comment]
Released Management v2.58.7

**Comment by motropuk** [comment]
Looks good on UAT
