### ISSUE TITLE
Create a parameter store value for Preservica host

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1843]
**Story**

DCS needs to know the Preservica host (and port, if applicable), on a per-environment basis.

Should be done in parallel with #1840

**Acceptance**

- [x] Create a AWS Parameter Store string value `PRESERVICA_HOST` for non-prod environments and populate values, pointing to Preservica development server:
  - [x] test
  - [x] demo
  - [x] uat
- [x] Modify camerata to pass the value to the Docker containers
- [x] Display Preservica host value on management app configuration page

**Comment by mikeapp** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/881

**Comment by FCRodriguez7** [comment]
Released management v2.58.2
