### ISSUE TITLE
Index parents with full text in a intensive worker queue

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1844]
**Story**

Solr appears to be overwhelmed by simultaneous indexing of full text data.  We should rate limit the indexing of full-text parents by using a queue on the intensive worker.

**Acceptance**
- [x] Add a fulltext queue on the intensive workers, with one processor  per intensive worker.
- [x] Queue reindexing of parents with full text into this queue

**Comment by martinlovell** [comment]
Camerata change to add a new queue to the intensive workers:
https://github.com/yalelibrary/yul-dc-camerata/pull/329

**Comment by martinlovell** [comment]
Management change to index full text parents in new queue:
https://github.com/yalelibrary/yul-dc-management/pull/875

**Comment by martinlovell** [comment]
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/84db86bf-e3ad-49c9-a34b-0c85f1c60c01)

**Comment by FCRodriguez7** [comment]
Released management v2.58.0

**Comment by FCRodriguez7** [comment]
Release Management v2.57.1

**Comment by martinlovell** [comment]
On test, 800009028 has full text.
(There are others with full text in SOLR, but reindex will remove full text status since they don't have full_text set for the children.  Update Full Text job is needed to update the children.)

**Comment by mikeapp** [comment]
Looks good on UAT.
