### ISSUE TITLE
SPIKE - Best Approach to Mapping for Creator in ASpace

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1845]
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1799

**Comment by FCRodriguez7** [comment]
**Item Page** 
![Screen Shot 2022-01-12 at 12.03.41 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d3f20d8b-eba3-4084-95ca-8b84e131b7a2)

Questions about result page:
![Screen Shot 2022-01-12 at 12.03.18 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/bf811faf-8e35-4f53-a176-dbe629dabc9f)

**Comment by alisonclemens** [comment]
This looks great -- thank you, @FCRodriguez7! I don't think the search results page (or the item page, for that matter) need to have a live creator link, but curious to hear what @motropuk thinks

Did you have a question about formatting the "From the collection" string? I seem to recall that you might have but don't see a note about this in the ticket

**Comment by FCRodriguez7** [comment]
@alisonclemens @motropuk  I do have a question about the string format 'From the collection.'  Should the string have a colon (:) or other capitalizations (From the Collection)?

**Comment by motropuk** [comment]
Thanks @FCRodriguez7. I agree with @alisonclemens that the search results page doesn't need a live creator link. 

As for styling of "From the collection" I think we should following the formatting for the same prefix as used in Archives at Yale i.e _From the Collection:_

Example in Archives at Yale https://archives.yale.edu/repositories/12/archival_objects/802216

**Comment by FCRodriguez7** [comment]
The proposed result page design: 

![Screen Shot 2022-01-12 at 4.23.19 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6a16ce4d-ee4c-4daa-87c5-c134b625ad8a)
 
-----

The proposed item page design: 

![Screen Shot 2022-01-12 at 3.46.12 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e11fff1f-19cb-4829-b7e6-14de81eb6ab4)

![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f41b2609-11c7-43d1-8e21-a100d047a567)

**Comment by motropuk** [comment]
Looks good to me

**Comment by FCRodriguez7** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/876

**Comment by FCRodriguez7** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/738

**Comment by FCRodriguez7** [comment]
Released management v2.58.0

**Comment by martinlovell** [comment]
Reindexed on test:
https://collections-test.library.yale.edu/catalog/800052256
https://collections-test.library.yale.edu/catalog/800052319

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.6
