### ISSUE TITLE
Migrate Litchfield Law School Student Notebooks

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1846]
**Story**

Migration the Litchfield Law School Student Notebooks (PID 71) from Findit into DCS. 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Law admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the Law admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@motropuk  146 parents are in UAT except two children failed
child image-16124058 of parent-16123696 not found in fedora or ladybird
child image-16098079.tif of parent- 16098078 not found in fedora or ladybird

**Comment by motropuk** [comment]
Emailed Law for approval to move to Prod. 

Notes for audit once we move this to prod
- Need to update all records to Public 
- Issue with catalog numbers and extra digits again, so not releasing
- Need to delete child image-16124058 of parent-16123696 
- Need to delete child image-16098079 of parent-16098078

**Comment by motropuk** [comment]
@MaggieZhaoYale This can be moved to Prod

**Comment by MaggieZhaoYale** [comment]
@motropuk In prod.

**Comment by motropuk** [comment]
@MaggieZhaoYale Could I get a list of the handles for this collection when you get time

**Comment by motropuk** [comment]
Waiting for updated list of bib ids for this collection, to then batch update once we have this

**Comment by MaggieZhaoYale** [comment]
@motropuk The handles URL is here: [https://app.zenhub.com/files/242185115/d55f888f-34fd-4ca0-80a2-5f515aa49609/download](https://app.zenhub.com/files/242185115/d55f888f-34fd-4ca0-80a2-5f515aa49609/download)

**Comment by motropuk** [comment]
This is complete. There are some bib ids to update and law will send these next week. But the migration of this collection is complete
