### ISSUE TITLE
Migrate Yale Law School Bulletin

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1847]
**Story**

Migration the Yale Law School Bulletin (PID 117) from Findit into DCS. 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the Law admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the Law admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
The collection is in UAT: https://collections-uat.library.yale.edu/management/batch_processes/620/parent_objects/17154409
Two images are missing:

- image 17176098 of parent 17154409. The image is inactive

- image 17190177 of parent  17154486. The image is not found on the Fedora datastream.

**Comment by motropuk** [comment]
Will ask Law about missing/inactive images for parents 17154409 and 17154486. However, it looks like we are still missing one object from Ladybird/Findit for this collection. There are 144 objects in Findit for this https://findit.library.yale.edu/?_=1642774795394&f%5Bdigital_collection_sim%5D%5B%5D=Yale+Law+School+Bulletin. There are only 143 objects in DCS UAT. Once we figure out what's missing, I will contact Law to review and ask about parents with missing images

**Comment by MaggieZhaoYale** [comment]
17154392 is not found in Fedora, and it does not have image attached in ladybird. https://findit.library.yale.edu/catalog/digcoll:5048922

**Comment by motropuk** [comment]
Emailed Law. Waiting for approval to move into Production. 

Notes for when we do the Production migration
- All objects can be set to "Public" visibility  
- Child oid 17190177 can be deleted from parent 17154486. Page labels should be updated after this is done to correct pagination. Filter child page by parent ID. Export CSV. Updated. Run reassociate child objects batch job to update them. 
- Child 17176098 can be deleted from parent 17154409. Page labels should be updated after this is done to correct pagination.

**Comment by motropuk** [comment]
@MaggieZhaoYale We can move this to production now

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/abf95b34-853d-4279-bd90-7ed488102b38/download](https://app.zenhub.com/files/242185115/abf95b34-853d-4279-bd90-7ed488102b38/download) Law Handle (except 17154392 which is not found in Fedora)

**Comment by MaggieZhaoYale** [comment]
@motropuk Ingested into prod. 
image oid-17176098 of parent oid-17154409. The image is inactive

image oid-17190177 of parent oid-17154486. The image is not found on the Fedora datastream.
