### ISSUE TITLE
Test Manifest Service performance viz Memory and CPU

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#185]
**ACCPTANCE**
Conduct and document performance baselines for the manifest service for
- [x] 512cpu / 4GB memory (i.e. the current configuration)
- [x] 1024cpu / 4GB memory
- [x] 2048cpu / 4GB memory
- [x] ~512cpu / 16GB memory~ 1024cpu / 8GB memory
- [x] 2048cpu / 16GB memory
- [ ] any other cpu memory settings that seem worth testing (re decreasing  performance curves)

Analyze the results to determine whether 
- [ ] Performance improvement is flat, linear, or decreasing with additional memory
- [ ] Performance improvement is flat, linear, or decreasing with additional cpu
- [ ] Memory or CPU increases have a more direct impact on performance
- [ ] Performance bottlenecks appear to be unrelated to memory or cpu (i.e. mostly flat or shallow curve increases in performance)

REFERENCES
* https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/
* Valid Task Memory and CPU combinations https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html

**Comment by JzGo** [comment]
Collecting the results in google drive with a larger wrap up/summary to come: [manifest load test results](https://drive.google.com/drive/folders/1UuLUeYQvm27eTrl_cHpHn17lvmqytYVv)

**Comment by fnibbit** [comment]
https://docs.google.com/document/d/1I1It6ofSM7G34i6dFUyZ_M59EQXFa4LcCiJuJWx1718/edit#heading=h.86m8lz7zt21h summary notes, charts to come
