### ISSUE TITLE
Fix IIIF start property

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1850]
IIIF `start` needs to be a resource with a type, not just a simple string.

**Acceptance**

- `start` is a resource with an `id` and `type`

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-management/pull/882

**Comment by mikeapp** [comment]
Note that this property is not processed by UV, as far as I can tell.  Mirador will open to the specified Canvas.

**Comment by FCRodriguez7** [comment]
Released management v2.58.3

**Comment by mikeapp** [comment]
Looks good on UAT
