### ISSUE TITLE
Create simple Preservica client

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1851]
**Story**

The Management app needs to interact with Preservica.   To develop this functionality, we need a simple service class that can log in and request objects via the Preservica API.

**Acceptance**
- [x] Create a service class for Preservica based on Martin's code https://github.com/martinlovell/preservica_experimentation
- [x] Code should use the PRESERVICA_HOST environment variable to determine which instance to communicate with
- [x] The service should take the Admin Set code (e.g., `brbl`) to be used and retrieve the credentials from the PRESERVICA_CREDENTIALS environment variable.

**Comment by martinlovell** [comment]
Does this ticket include setting up tests and fixtures, etc?

I could set it up similarly to the metadata client which checks ENV["VPN"] == "true" to see whether to load fixtures or make real API calls.

**Comment by mikeapp** [comment]
Perhaps hold off until we start to build out some of the model classes in the next ticket in this sequence?

**Comment by martinlovell** [comment]
Added a few tests to get the coverage to pass.

https://github.com/yalelibrary/yul-dc-management/pull/891
