### ISSUE TITLE
Add methods to get data from Preservica model classes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1853]
**Story**

The management application will need to extract key information from the Preservica XML responses.  We should add convenience methods to the model classes to return this data.

**Acceptance**
Add methods to return the following data from these model classes:
- [x] Representation: `type`
- [x] Generation: `zip:Formats` string, `active` property boolean
- [x] Bitstream:  file size as number, sha512 hash string

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/905

**Comment by mikeapp** [comment]
@martinlovell  Just merged that PR, sorry if it was not ready - feel free to revert it!

**Comment by FCRodriguez7** [comment]
Released management v2.58.16
