### ISSUE TITLE
Download Preservica content referenced from Bitstream

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1854]
**Story**

The Management application needs to be able to download a file that is referenced from a Bitstream via the Preservica API.

Eventually this will be used to write the file to the pairtree but the goal of the current ticket is to have a test that downloads and validates the file.

**Acceptance**
- [x] Add a method to the Bitstream model that returns the `<Content>` URI
- [x] Add a method to the Bitstream model that downloads the content to a file 
- [x] Tests should confirm that the SHA512 and file size of the download match 
- [x] Do not load all data into memory, download to files in chunks.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/916

The PR does not stream to the file. The data is loaded into memory before going to the file.
@mikeapp  , let me now if it should stream for this ticket.

**Comment by DraxIndustries79** [comment]
Per Mike, streaming to disc would be optimal.

**Comment by FCRodriguez7** [comment]
v2.58.19

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/921
