### ISSUE TITLE
Retrieve subset of descendants for some Preservica models

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1857]
**Story**

In certain cases we don't want to retrieve all descendants of a Preservica object, but only a filtered subset. 

**Acceptance**
Add methods to retrieve filtered subset of descendants for:
- [x] Representations: retrieve Representations based on `type` value.   For the sample XML, the value is "Preservation", but there could also be "Access" copies, etc.
- [x] Generations: retrieve Generation with `active` property value of `true`

**Comment by jpengst** [comment]
Are these methods supposed to return xml files based on the representation we're attempting to retrieve? Or are these methods supposed to return the types value from an xml file?

**Comment by FCRodriguez7** [comment]
Released management v2.58.20
