### ISSUE TITLE
Error when Setting Redirect URL of Parent with Aspace or Voyager Authoritative Source

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1859]
If a parent uses Aspace or Voyager as the authoritative metadata source, the object fails after a redirect URL is set.

_Reproduce error:_
- Edit a Parent Object that has 0 children so that it has aspace as the authoritative source and an aspace URI set or Voyager as the metadata source.
- Edit that parent and enter a redirect URL and save.

There will be an error after save, and the parent can no longer be viewed in management.
It does appear to save the parent, the issue may just be that it's unable to display it on the parent object show page.
You may be able to correct the parent by going directly to the edit page with: `/management/parent_objects/<OID>/edit` an setting the source to Ladybird.

The error in cloud watch is `ArchiveSpace uri required to build ArchiveSpace url` so it may just be an issue displaying the metadata cloud URL at the top of the parent object show page in management.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/886

**Comment by FCRodriguez7** [comment]
Released management v2.58.5

**Comment by FCRodriguez7** [comment]
The release has been deployed to test and uat.

**Comment by mikeapp** [comment]
Seems to work, at least the parent is visible in the table and no error in the batch job screen.
