### ISSUE TITLE
Create PTIFF derivatives

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#186]
**ACCEPTANCE**
Given one or more file paths to one or more access master images on disk
- [ ] I can run a script that creates a pyramidal tiff derivative of the image
- [ ] The stiff is saved somewhere I can access it for later us
   - [ ] [GOOD] to a location on disk  -OR-
   - [ ] [BETTER] to the bucket on S3 where the image service expects to find images

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-ptiff-shell-script
