### ISSUE TITLE
Blacklight Dependency Patching WK4 22

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1860]
**User Story**
The application's dependencies should be up-to-date for week 4 of the year.

AUTO GENERATED 
![Screen Shot 2022-01-21 at 1.33.50 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/59180137-79b9-4280-8fce-472de022cdde)

MANUAL PATCH
![Screen Shot 2022-01-21 at 2.35.54 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e534af8a-ff70-42b9-966a-cdd61c9bdad1)

---
**Acceptance**
- [x] follow-redirects
- [x] node-forge
- [x] shelljs
- [x] node-fetch 
- [x] xmldom 
- [x] json-schema
- [x] postcss
- [x] is-svg
- [x] three
~~- [ ] actionpack~~

**Comment by FCRodriguez7** [comment]
AUTO GEN PRs:
https://github.com/yalelibrary/yul-dc-blacklight/pull/741
https://github.com/yalelibrary/yul-dc-blacklight/pull/740
https://github.com/yalelibrary/yul-dc-blacklight/pull/739

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.7 for #739

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/744

**Comment by FCRodriguez7** [comment]
node-fetch 
https://github.com/yalelibrary/yul-dc-blacklight/pull/746

**Comment by FCRodriguez7** [comment]
json-schema
https://github.com/yalelibrary/yul-dc-blacklight/pull/748

**Comment by FCRodriguez7** [comment]
postcss [Released Blacklight v1.59.14] 
https://github.com/yalelibrary/yul-dc-blacklight/pull/749

**Comment by DraxIndustries79** [comment]
Actionpack removed as we'll have to upgrade Ruby

**Comment by FCRodriguez7** [comment]
Three [ ]
https://github.com/yalelibrary/yul-dc-blacklight/pull/750
