### ISSUE TITLE
Solr local image does not create cores

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1862]
**Story**

Solr local image does not create cores.  I believe this is due to a change that was made during log4j remediation (entrypoint is overriding the startup command in docker compose).

**Solution**
- [x] Remove `ENTRYPOINT ["/boot.sh"] ` from Dockerfile
- [x] Rely on `command`s in Camerata docker-compose files to call `boot.sh`

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-solr/pull/29

**Comment by mikeapp** [comment]
Looks good locally, next step is to push an image with a custom tag and deploy it to collections-test.

**Comment by DraxIndustries79** [comment]
This will need a devops ticket, so on hold for now

**Comment by DraxIndustries79** [comment]
Mike is opening a ServiceNow ticket

**Comment by bobrice** [comment]
@mikeapp Instructions for deploying solr to dc clusters can be found at....
https://git.yale.edu/Library-ESS/DCE/wiki/Update-Solr-container-version

Let us know if you want a run through and if you have any trouble accessing this wiki

**Comment by mikeapp** [comment]
@bobrice Submitted a ticket for DevOps to do the deployment.

**Comment by bobrice** [comment]
Solr has been redeployed in demo.

**Comment by mikeapp** [comment]
Thanks @bobrice - it looks good on demo.  I'll create a release.

**Comment by mikeapp** [comment]
Release v1.0.13
Ticket submitted to request deployment to collections-demo

**Comment by bobrice** [comment]
Deployed to test.  Waiting for results from Engineering.

**Comment by DraxIndustries79** [comment]
Deployed to UAT.

**Comment by mikeapp** [comment]
UAT looks good.
