### ISSUE TITLE
Add Preservica columns to Child Object 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1864]
**Story**

Each child object will be associated with a Content Object in Preservica.   The hierarchy is as follows:

* Content Object
  * Generations
    * Generation
        * Bitstream

We will want to track the information about the Preservica source for each child.

**Acceptance**
On the child object model:
- [x] add text column `preservica_content_object_uri`
- [x] add text column `preservica_generation_uri`
- [x] add text column `preservica_bitstream_uri`
- [x] add indexes for all three columns
- [x] Display all three on the Child Object show page, after the Parent Object field.  Labels should be based on the field names ("Preservica Content Object URI", etc.)
![Screen Shot 2022-01-24 at 2.33.41 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/fff6ef51-309c-4879-a252-4e9b15304b7f)
- [x] Values should not be editable

**Comment by mikeapp** [comment]
For Goobi import, the logic is as follows:
1. When the parent is created, a flag is set `parent.from_mets = true`
2. The Generate PTIFF Job first copies the TIFF to the pair tree if `from_mets` is true.
3. The Manifest job sets `parent.from_mets = false`, so subsequent updates will not re-donwload the file

We should discuss whether we want to have a flag on the parent, the children, or some combination of existing fields to determine whether to download the file from Preservica.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/909

**Comment by jpengst** [comment]
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/cae3f825-eee7-4d56-be11-87494de005a9)

**Comment by FCRodriguez7** [comment]
Released management v2.58.16

**Comment by motropuk** [comment]
Looks good on UAT

**Comment by mikeapp** [comment]
I didn't think it was necessary to show them on the edit screen, the values are only going to be useful if you need to search Preservica.

**Comment by motropuk** [comment]
Thanks @mikeapp. That makes sense. Thanks for the clarification. I think this is good to close then
