### ISSUE TITLE
Add Preservica fields to Child Object datatable

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1865]
**Story**

The new Preservica fields should appear in the Child Object datatable.  They should be filterable.

**Acceptance**
* The following columns appear in the Child Object datatable:
  - [x] preservica_content_object_uri
  - [x] preservica_generation_uri
  - [x] preservica_bitstream_uri
- [x] Columns should appear after "Original OID"
- [x] Labels should match those on the Child Object show page
- [x] Columns should be filterable (i.e., match on a string)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/910

**Comment by FCRodriguez7** [comment]
Released management v2.58.16

**Comment by motropuk** [comment]
Looks good on UAT
