### ISSUE TITLE
Direct Law catalog record links to QuickSearch

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1866]
**Story**

We have just migrated the first collection from Law https://collections.library.yale.edu/catalog?f%5bproject_identifier_tesi%5d%5b%5d=117&q=&search_field=all_fields. This surfaced an issue in that the number listed under Orbis ID for each journal refers to a catalog record in Sierra (Law's ILS) https://collections.library.yale.edu/catalog/17154522. Currently, when you click on this iD in the Orbis ID field, it returns an error, as it is trying to find that id in Orbis, which is not there. 

In time we plan on integrating Sierra with DCS, so Sierra can be a metadata source for objects in DCS. For now however, the proposed solution is that and ids in the Orbis ID field that start with a  b (e.g b16732352) so direct to QuickSearch instead of Orbis. Sierra records are included in QuickSearch.  For example, https://search.library.yale.edu/catalog/b167323

**Acceptance**
- [ ] DCS should direct links provided in blacklight for Orbis IDs starting with "b" to QuickSearch

**Comment by martinlovell** [comment]
@motropuk Should the label for the link still be "Orbis Record" or should if have some other label?

**Comment by motropuk** [comment]
@martinlovell Is it possible for the label to be different just for records we will direct to QuickSearch, or would the change need to be a universal one?

**Comment by martinlovell** [comment]
It's possible that we could map the "Orbis Ids" starting with b to some other field in SOLR, and give it a different label.

**Comment by motropuk** [comment]
@martinlovell Lets go with Quicksearch ID

**Comment by martinlovell** [comment]
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/49025d59-6c2f-4579-b6b6-533a71c09f24)

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.1

**Comment by FCRodriguez7** [comment]
Released management v2.58.24

**Comment by DraxIndustries79** [comment]
This needs a reindex.  Note here when reindex is complete.

**Comment by mikeapp** [comment]
It looks like Sierra ID for the test item was different on collections-uat (a `2` was appended), so I edited it to match prod.   Looks good to me now: https://collections-uat.library.yale.edu/catalog/17154522
