### ISSUE TITLE
Modify Create Parent batch job to create Parent Object with Preservica values

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1867]
**Story**

We would like to be able to import from Preservica using the Create Parent Objects batch job.   To accomplish this, the job will need to accept additional fields.    The job will also have to determine whether the import is being requested from Ladybird or Preservica.

The goal of this ticket is to create the parent, populate identifier fields, and sync metadata from Metadata Cloud.  Creation of the child objects will be described in another ticket.

**Acceptance**
- [x] If the row in the Create Parent Object batch job input CSV contains the OID and Admin Set, process the row as an import from Ladybird (i.e., keep the current behavior.)
- [x] If the digital_object_source and preservica_uri fields are present, process the row as a request to import from Preservica
- [x]  Fields should be processed from the row and validated as follows:
  - [x] OID: must not be present, auto-generated during ingest
  - [x] Admin Set: required
  - [x] metadata_source: required, must be ils or aspace
  - [x] ASpace URI or BIB: required based on Metadata Source
  - [x] Holding, Item, Barcode: optional
  - [x] Visibility: required
- [x] The batch job should assign the values provided to the Parent Object
- [x] CSV field headers/names should be consistent with update parent object sheet.
- [x] Add all additional fields to the csv template

**Comment by jpengst** [comment]
Should we have 2 separate download templates? One for regular create parents (oid, admin set) and one for preservica? required for preservica: oid, admin_set, metadata_source, aspace_uri/bib, visibility. And should we list the optional fields in preservica download template? (holding, item, barcode)

**Comment by mikeapp** [comment]
Just keep one template with all the fields.  Let's say the job should set the holding/item/barcode if present.

**Comment by mikeapp** [comment]
@jpengst A new requirement came up that will require an additional field on the parent.  We should decide whether to pause this and add the new field, or make a new ticket and add it after this is done.

The new field will indicate the name of the `Representation` that we want to use.  For example:

```
<Representations>
        <Representation type="Preservation" name="Preservation-1"
            >https://preservica-dev-v6.library.yale.edu/api/entity/information-objects/1e42a2bb-8953-41b6-bcc3-1a19c86a5e3d/representations/Preservation/1</Representation>
    </Representations>
```

This list could have multiple entries with `name`s like `Preservation-2` or `Access-1`.  We will need to know which one to choose.

**Comment by jpengst** [comment]
Question about the "sync metadata from Metadata Cloud" part of the ticket; If we're generating a random oid during ingest, where is the metadata supposed to come from?

**Comment by mikeapp** [comment]
The metadata cloud call should use the URI generated based on the Voyager or ASpace ID - that's why the metadata source should be supplied.   If the metadata source is set but the required IDs aren't present, it will be an error.

**Comment by jpengst** [comment]
Preservica Parent Objects are being created via the batch process successfully and validations are in place to check if the CSV is valid. Currently working on the "sync metadata from Metadata Cloud" part of the ticket, which Im a little confuse on. 
Does the aspace_uri and bib hold the metadata information that needs to be fetched?

**Comment by mikeapp** [comment]
Try queueing the `SetupMetadataJob`.  This would be what we want after the children are created (still to do in #1879), so that the rest of the workflow would proceed normally (PTIFF generation, manifest creation, PDF generation).   However, we don't have children yet so this method may throw an error.   An error would be OK for now though, as long as we see that the parent gets populated with the correct metadata from metadata cloud.

**Comment by jpengst** [comment]
The SetupMetadataJob is currently being performed and errors on `parent_object.default_fetch(current_batch_process, current_batch_connection)`. 
The default fetch is getting caught up on `self.aspace_json = MetadataSource.find_by(metadata_cloud_name: "aspace").fetch_record(self)` Since `self` is the newly created parent object, I'm not sure whats expected to be fetched, if that makes sense.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/924

**Comment by mikeapp** [comment]
Looks good. Tested with a minimal CSV:
```
admin_set,source,aspace_uri,visibility,digital_object_source,preservica_uri
brbl,aspace,/repositories/11/archival_objects/292854,Public,Preservica,/preservica/1234
```

The Parent Object was created, the metadata source, URIs, etc. populated, and the metadata successfully retrieved from Metadata Cloud.  

The batch job doesn't report any status, I assume that's expected at this point.

**Comment by FCRodriguez7** [comment]
Release Management v2.59.1

**Comment by mikeapp** [comment]
Same behavior on UAT as I saw in local testing, good to close.
