### ISSUE TITLE
Remove/hide redirected items from Solr search results

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1870]
**Story** 

Redirected items are displaying in the search results.  We'd like them not to be displayed.

![Screen Shot 2022-01-26 at 9.35.26 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/cbd8b002-f4f3-4b1a-838e-c0e9c5cda1f6)

**Acceptance**

- [x] These items do not display in the search results.
- [x] ~~Digital images~~ Manifest and PDF are blocked or redirected if they still exist. 
  - Are the PDF and Manifest deleted when the object's children are removed?  If so, then this isn't an issue.
  - Should `access_helper.rb` return false for the digital object check?

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/753

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.16

**Comment by martinlovell** [comment]
Sort by title, go to last page:
https://collections-test.library.yale.edu/catalog?page=1215&q=&search_field=all_fields&sort=title_ssim+asc%2C+oid_ssi+desc%2C+archivalSort_ssi+asc
