### ISSUE TITLE
Locate full text for Yale Law School Bulletin

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1872]
**Story**

The Law Library informed us that the Yale Law School Bulletin has full text that needs to be brought over to DCS (migrated #1847). I did a quick sample review of some of the issues in Findit e.g https://findit.library.yale.edu/images_layout/fullview?parentoid=17154529 and dont see full text attached. So the full text might not be in Fedora. We need to investigate

**Acceptance**
- [x] Review fedora for this collection to see if it contains Full Text files
- [x] Locate full text files if not in Fedora
- [x] Bulk update file names to child oids
- [x] Upload full text txt to S3 yul-dc-ocr-prod
- [x] Add full text files to DCS production

**Comment by MaggieZhaoYale** [comment]
I ran a script to check ocr (txt) for  collection 117, there is no full text for all the images.

**Comment by motropuk** [comment]
Law have copies of all of the full text that they will share with me. However, these files are named semantically and do not include the child oid of the image they correspond to. So there appears to be a significant amount of work needed to match the .txt files with the child images. Suggestions for other less labor intensive approaches I might be missing?

**Comment by motropuk** [comment]
Law sent an example of a full text file for this collection, which includes current naming
[https://app.zenhub.com/files/242185115/3e2213ac-d096-451a-b963-af7d84f19ea2/download](https://app.zenhub.com/files/242185115/3e2213ac-d096-451a-b963-af7d84f19ea2/download)

Law might be able to bulk rename these files. However, in order to do so they need a csv which includes parent OIDs for the collection, with all the associated child oids per parent, in sort order. They could then match this to the current files and use a batch renaming app to update all the files. Is this something we can produce @MaggieZhaoYale?

**Comment by motropuk** [comment]
Complete set of full text items are here https://yale.app.box.com/folder/155046052039.

**Comment by MaggieZhaoYale** [comment]
@motropuk  I got the  list of oid and .txt/.pdf path file from ladybird DB. As the next step, I will match the set of the full text items with oid

**Comment by MaggieZhaoYale** [comment]
A few Oids has more than 1 full text file:
e.g. 17167342 has more than 1 full text file: b16732352_1869-1870_00_eng_0001.txt, b16732352_1869-1870_00_eng_0002.txt,b16732352_1870-1871_00_eng_0005.txt
These fulltext files have  different content. 
17175845 b16732352_1871-1872_00_eng_0004.txt, b16732352_1870-1871_00_eng_0006.txt
b16732352_1871-1872_00_eng_0004.txt

**Comment by motropuk** [comment]
This is done and be closed
