### ISSUE TITLE
Bug: Unable to search for strings contained in Archival Hierarchy

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1874]
Problem:
Searching for "alphabets and birthdays" does not return this record: https://collections.library.yale.edu/catalog/2064365
It only matches the exact string: https://collections.library.yale.edu/catalog?fulltext_search=1&search_field=all_fields&fulltext_search=1&q=%22Beinecke+Rare+Book+and+Manuscript+Library+%3E+Gertrude+Stein+and+Alice+B.+Toklas+papers+%28YCAL+MSS+76%29+%3E+Writings+of+Gertrude+Stein+%3E+GERTRUDE+STEIN+BIBLIOGRAPH+%3E+To+do+a+book+about+alphabets+and+birthdays%22

- [x] Change search_field array's value: `ancestor_titles_hierarchy_ssim` to `ancestorDisplayStrings_tesim` in CatalogController. Similar values are in both fields, but the text field is tokenized/stemmed, etc so partial matches will work, etc.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/752

**Comment by martinlovell** [comment]
https://collections-test.library.yale.edu/catalog?fulltext_search=1&q=general+correspondence&search_field=all_fields

**Comment by motropuk** [comment]
Looks good on UAT
