### ISSUE TITLE
Change parent object preservica_uri to text type

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1877]
**Story**

Preservica URIs in the samples are ~150 bytes including the hostname, so *should* fit in a 255 byte `string` but the overhead in Postgres seems like a couple of bytes, so let's change it to `text` so we don't have to worry about it in the future.   

@jpengst asked about this in the discussion of either the parent or the child objects tickets and I think text is the way to go.

**Acceptance**
- [ ] Change Parent Object `preservica_uri` field type from `string` to `text`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/911

**Comment by FCRodriguez7** [comment]
Released management v2.58.17

**Comment by mikeapp** [comment]
Good on UAT
