### ISSUE TITLE
Create Child Objects from Preservica

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1879]
**Discuss**

On the initial import of a Preservica object, create a DCS child for each Preservica Child within the Structural Object. 

Note that for Goobi import, the logic is as follows:
1. When the parent is created, a flag is set `parent.from_mets = true`
2. The Generate PTIFF Job first copies the TIFF to the pair tree if `from_mets` is true.
3. The Manifest job sets `parent.from_mets = false`, so subsequent updates will not re-donwload the file

* We should discuss whether we want to have a flag on the parent, the children, or some combination of existing fields to determine whether to download the file from Preservica.

* Information Object
   * Representations
     * Representation
        * Content Object
           * Generations
              * Generation
                  * Bitstream

**Acceptance**
For each Preservica child Information Object:
- [x] An OID is generated
- [x] A DCS child object is created
- [x] The `order` is set based on the order in the Preservica object
- [x] The `preservica_*_uri` fields are populated
- [x] Identify the representation that corresponds to the `preservica_representation_name` field of the parent.
- [x] Identify the active generation is a TIFF, or else throw an error
- [x] The Bitstream's SHA512 checksum is stored in the `sha512_checksum` field
- [x] The TIFF Bitstream's Content  is downloaded to the pairtrtee
- [x] Subsequent PTIFF creation job is run
- [x] Add method to update last_preservica_update

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/940

**Comment by mikeapp** [comment]
I am having difficulty with this, my jobs end with no feedback.  Can you email me an import CSV that works against the dev server?   It looks like there are some error cases that need improved handling.   For instance, I started by forgetting to set the credentials variable, so that should probably be an immediate fail and warning if not set.

**Comment by jpengst** [comment]
Added Preservica credentials check for CSV Import:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/5c673b3d-10a6-487c-9a4c-1ea91797c4a9)

**Comment by K8Sewell** [comment]
Successful import of children from Preservica - https://collections-demo.library.yale.edu/catalog/30000000

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8225a8ef-6aa2-4a3c-9861-50b03e76e177)

**Comment by FCRodriguez7** [comment]
Released management v2.59.8

**Comment by mikeapp** [comment]
This worked but the batch job is not reporting status:

![Screen Shot 2022-03-23 at 1.48.20 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/3ada6b61-2bbc-4717-bb45-48ae39f606e0)

![Screen Shot 2022-03-23 at 1.48.26 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/931e02fd-273f-42ce-8de3-0c94bd870a7d)
