### ISSUE TITLE
Upgrade javascript dependencies as indicated

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#188]
The Blacklight application currently lists the following javascript deprecations. Address these where possible. 

```
warning @rails/webpacker > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

**Comment by alishaevn** [comment]
The details above are from when I ran `dc build` earlier this week. Some things have changed with the Dockerfile since then so I ran it again yesterday to see if I could still duplicate the warnings.

`dc build` — Required ruby-2.6.6 is not installed. To install do: 'rvm install "ruby-2.6.6"'.
`dc build` --no-cache — “Your Ruby version is 2.6.5, but your Gemfile specified 2.6.6. ERROR: Service ‘base’ failed to build: The command ‘/bin/sh -c /sbin/setuser app bash -l -c “bundle check || bundle install”' returned a non-zero code: 18"

`dc build blacklight` — successfully finishes
`dc build --no-cache blacklight` — (the command that fixed the issue yesterday) successfully finishes

`dc build base` — “Your Ruby version is 2.6.5, but your Gemfile specified 2.6.6. ERROR: Service ‘base’ failed to build: The command ‘/bin/sh -c /sbin/setuser app bash -l -c “bundle check || bundle install”' returned a non-zero code: 18"
`dc build --no-cache base` — same error as above

`dc up` works fine and pulling the base image from dockerhub didn’t change anything.


I informed rob of the errors and hopefully we can troubleshoot them today.

**Comment by FCRodriguez7** [comment]
Alisha, 

I want to collaborate with you on this ticket if you have not solved it yet.  

Frederick

**Comment by alishaevn** [comment]
Made some changes to the Dockerfile.base file with Rob. `dc build base` (which is the first half of the `dc build` command, where the issue was occuring) is now working. It shows the same js errors:

```
Step 16/19 : RUN /sbin/setuser app /bin/bash -l -c "cd /home/app/webapp && DB_ADAPTER=nulldb bundle exec rake assets:precompile"
 ---> Running in 5f0bbcd92b82
yarn install v1.22.4
info No lockfile found.
$ rm -rf ./public/uv
[1/4] Resolving packages...
warning @rails/webpacker > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
```

**Comment by alishaevn** [comment]
These warnings are all coming from dependencies within the blacklight app.

- `warning @rails/webpacker > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`
  - as of Feb 11th 2020, request is fully deprecated.
  - node-sass `v 4.14.1` shows `"request": "^2.88.0"` in their package.json which; they will need to remove the dependency in order for the warning to go away.
<br>

- `warning @rails/webpacker > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`
  - As of Feb 11th 2020, request is fully deprecated.
  - node-gyp shows `"request": "^2.88.2"` in their package.json; they will need to remove the dependency in order for the warning to go away.
<br>

- `warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`
- `warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`
- `warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`
  - chokidar v3 was released on Apr 30, 2019
  - there's an active thread in the webpacker repo about switching to chokidar v3
  - as of today, the latest message was from May 5: https://github.com/webpack/watchpack/issues/130
<br>

- `warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
- `warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`
  - "Is npm bugging you about this module being deprecated? You are probably depending on this module via the source-map-resolve package. For example:
  nanomatch > snapdragon > source-map-resolve > resolve-url
  The solution is to make your dependency chain update to source-map-resolve version 0.6.0 or later, or switch to dependencies not using source-map-resolve at all."
  - this fix has to be implemented by webpacker
<br>
