### ISSUE TITLE
Update Yale University Library logo link

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1880]
**Story**

Currently, the Yale University Library logo in the top left corner of DCS points back to https://collections.library.yale.edu/. We need to update this so it instead points to https://library.yale.edu/. This will ensure the linking for this logo is consistent across YUL webpages
![Screen Shot 2022-02-01 at 11.31.35.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/ea7d3b3d-3f90-4724-b26f-55679e2fa386)

**Acceptance**
- [x] Yale University Library logo directs to https://library.yale.edu/

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/754

**Comment by FCRodriguez7** [comment]
Released blacklight v1.59.17
