### ISSUE TITLE
Preservica Generation object: add method to get FormatGroup

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1881]
**Story**

It looks like Preservica creates a shorthand for the file format in the Generation's FormatGroup element:
` <xip:FormatGroup>tiff</xip:FormatGroup>`

This may be easier to match on than the format name (e.g., "Tagged Image File Format").

**Acceptance**

- [x] Add method to Generation to retrieve the format group

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/920
