### ISSUE TITLE
Revisit automation of nightly metadata sync.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1883]
**Story**

We have manually tested the metadata sync but need to automate process so that the job runs nightly.

See #1620, including reverted Camerata changes.

**Acceptance**
- [ ] When the system is started, an Activity Stream job (`activity_stream_job.rb`) is queued if none is already pending.
- [ ]  The job runs nightly at 1am

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/333 - for review

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.8

**Comment by mikeapp** [comment]
Ran successfully in UAT.  Deployment to test last night failed for some reason, I redeployed today so we can check test tomorrow if we'd like.  I think we can close this.

Note that the change is in camerata so any management redeploy in production should activate this.
