### ISSUE TITLE
Quickfix: Update Management App parent object table display 

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1885]
**Story**

The Parent Objects table in the Management App does not make it easy for users (at least on Chrome, Safari, Firefox, and likely in other browsers) to scroll to the right to view additional columns. Suggest adding bottom scroll bar or other mechanism for easily viewing the table in its entirety.

Note: There is a scrollbar if you manage to get to the bottom of the table.  Solution for now is to have the scrollbar appear at the bottom of each break point depending on how zoomed.

**Acceptance**
- [ ] Users in a variety of browsers are able to scroll to view all columns in the table
- [ ] Make ticket to discuss a more holistic solution to handle what we're seeing in the tables now.

**Comment by alisonclemens** [comment]
**Story**

The Parent Objects table in the Management App does not make it easy for users (at least on Chrome, and likely in other browsers) to scroll to the right to view additional columns. Suggest adding bottom scroll bar or other mechanism for easily viewing the table in its entirety.

**Acceptance**
- [ ] Users in a variety of browsers are able to scroll to view all columns in the table

**Comment by FCRodriguez7** [comment]
@alisonclemens I have added the quick fix to the test environment for you to checkout.

**Comment by FCRodriguez7** [comment]
The current PR: https://github.com/yalelibrary/yul-dc-management/pull/944

**Comment by FCRodriguez7** [comment]
Released management v2.59.7

**Comment by motropuk** [comment]
This looks fine to me. Good to close
