### ISSUE TITLE
Give all Management App users ability to access Sets menu

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1886]

**Comment by alisonclemens** [comment]
**Story**

Non-system admins in the Management App are currently unable to access the Sets menu. They should be able to do so in order to facilitate their ability to do reporting. They should not be able to add themselves to a different set.

**Acceptance**
- [ ] All Management App users can access the Sets menu
- [ ] Only systems admins can add themselves to sets via the Sets menu

**Comment by jpengst** [comment]
Should the users be able to access the individual sets edit page? ex: management/admin_sets/2 or just the /admin_sets showpage?

"New Admin Set" button should be disabled/hidden on the showpage. 
Also the "edit" pencil link should be disabled/hidden for non-admin users if they can't view the individual edit pages.

**Comment by alisonclemens** [comment]
Is it possible for them to be able to access the admin_sets showpage plus any individual sets pages for which they're viewers or editors?

**Comment by motropuk** [comment]
@alisonclemens will document the process of running this job via batch processed, for system admins who cant access admin sets
