### ISSUE TITLE
Image server memory settings

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1887]
**Story**

The image server is currently using the default memory settings for Java, sets the heap size to 25% of memory.   Total system memory tops out at about 40% used. 

**Acceptance**
- [x] Introduce a variable for memory setting into the image server templates in Camerata 
   - [x] Use a sane default for local development (e.g., `-Xmx2g`)
   - [x] Use an adaptive value for ECS deployments (e.g., ` -XX:MaxRAMPercentage=80.0`)
- [x] Modify the image server `boot.sh` file to use these values.

**Comment by mikeapp** [comment]
Image server PR: https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/29
Camerata PR: https://github.com/yalelibrary/yul-dc-camerata/pull/332

**Comment by FCRodriguez7** [comment]
Released camerata v4.2.7

**Comment by FCRodriguez7** [comment]
Camerata part of the ticket
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3df7e8d6-7ff9-4d61-b477-c5fff3405af3)

**Comment by mikeapp** [comment]
See #1892
