### ISSUE TITLE
Remove deprecated indexing code

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#189]
Remove deprecated indexing code from the blacklight application, now that we're getting our indexing from the management app. 

- [x] the indexing service is removed
- [x] its tests are removed
- [x] its rake task is removed
- [x] any references to it in the README have been removed

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/74

PR up for review.  Please let me know if any other edits are needed to complete this ticket.  Thanks!

**Comment by K8Sewell** [comment]
As a note - there were no references to the deprecated indexing service in the README so no change was made there.

**Comment by K8Sewell** [comment]
PR was merged into master.
