### ISSUE TITLE
Map LB FDID 70 to Caption field for children records

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1895]
**Story**
The Ladybird (LB) FDID 70 field is mapped to DCS at the parent level; it should also be mapped at the child level, to the Caption field. This will ensure ready migration of important LB data into DCS.

**Acceptance**
- [x] FDID 70 (MC title field)  is mapped to Caption field

**Comment by alisonclemens** [comment]
**Story**
The Ladybird (LB) FDID 70 field is mapped to the DCS Label field at the parent level; it should also be mapped at the child level. This will ensure ready migration of important LB data into DCS.

**Acceptance**
- [ ] FDID 70 is mapped to Label field

**Comment by martinlovell** [comment]
Looking at some data, it looks like it's not uncommon for the title (FDID 70) of the child to be the same as the title (FDID 70) or the sourceTitle (FDID 63) of the parent.

**Comment by motropuk** [comment]
@martinlovell Yes this is common for simple objects pull from Ladybird, but not for complex objects

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/931

**Comment by FCRodriguez7** [comment]
Released management v2.59.0

**Comment by martinlovell** [comment]
This change will only affect new items that are imported.
Records that were already imported will have to be updated via batch/cvs.

**Comment by mikeapp** [comment]
Testing on UAT with OID 16825034

**Comment by mikeapp** [comment]
Seeing odd characters:
` "---\n- Inside front cover\n",`

It looks like the value is coming from MC as an array not a string (
`"title": ["[Two designs for a cabinet at Strawberry Hill] [art original] / E.E."],` ) and the databases is storing the YAML serialization of the array.  Recommend we take the first element when the value is an array.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/932

**Comment by martinlovell** [comment]
The fix is on UAT.
I recreated 16825034 and it looks better.

**Comment by martinlovell** [comment]
Fixed in release: v2.59.2

**Comment by martinlovell** [comment]
I made 16825034 public to test searching.  Search for a child caption found the parent: https://collections-uat.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=Figurae+in+fundo%2C+lateribusque+ollae+depictae

**Comment by motropuk** [comment]
Looks good on UAT
