### ISSUE TITLE
Load test IIIF Image server release v1.0.8

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1896]
**Story**

A new image server release has been created (#1892) that:
* decreases the DNS TTL to 120 seconds
* increases the available memory to 80% of the container

We would like to validate that it will perform reasonably under load.

**Acceptance**
- [ ] Perform a load test on the image server in UAT.

**Comment by mikeapp** [comment]
Files provided to DevOps

**Comment by ra359** [comment]
The test plan has been created (using ~dozen of the provided urls). Need to determing the initial number of simulated users. Will kick off test run later today or tomorrow morning.

**Comment by ra359** [comment]
- [x] Enabled Container Insights for UAT and created a dashboard.
- [x] Verified that that WAF ACL rate limit was not in effect for UAT

We are having difficulty placing meaningful load (500 users/0.67% failure rate) presumably because of caching. At the moment, still using a handful of URL's.

**Comment by ra359** [comment]
Results here: https://brbl-archive.library.yale.edu/YUL-DCE-IIIF/
