### ISSUE TITLE
Add an Author Facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#190]
**ACCEPTANCE**
- [x] I can facet works based on the Author of the work

**Comment by K8Sewell** [comment]
Draft PR up.  Still working on getting the Author names to display all as one unit instead of split up.

https://github.com/yalelibrary/yul-dc-blacklight/pull/75

![Screen Shot 2020-06-03 at 2.22.36 PM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/0582e5c7-8dde-418f-a711-757458d88588)

**Comment by mark-dce** [comment]
Kait - it looks like author is currently being indexed as `author_tsim` which means it's being tokenized as text - i.e. tokenized (broken apart) into terms based on word boundaries and punctuation.  For fields that we want to use in facets and not have them broken up into individual words, we'll probably also need to index the same data as `author_ssim` which means `symbol` `stored` `indexed` `multiple`.  In Solr, symbols are not tokenized and text fields are.  It's totally fine to index the same field multiple times.  We'll need to work with the management team to update the indexing of this field (and any other fields that have strings that should not be broken apart on spaces, etc.)

**Comment by K8Sewell** [comment]
Great!  Thanks for the update, Mark.  I've just updated the branch I'm on to use _ssim and there are some screen shots below.  I'll make note of any other facet fields that need addressed.  Thanks again!

![Screen Shot 2020-06-03 at 4.06.08 PM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9a4d2a45-b2e0-425e-bd87-9864ebbeebcb)

![Screen Shot 2020-06-03 at 4.07.57 PM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/83764f99-0fc0-4a43-b898-eac92016f161)

**Comment by K8Sewell** [comment]
Looked at the other facet tickets.  All of the other fields are _ssim so shouldn't be an issue on any upcoming tickets this sprint.
