### ISSUE TITLE
Management: Dependabot PRs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1900]
**Story**

Updating Puma server and a node library.

**Acceptance**
- [x] Dependabot PRs merged.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/925
https://github.com/yalelibrary/yul-dc-management/pull/926

**Comment by FCRodriguez7** [comment]
Released management v2.58.25
