### ISSUE TITLE
Migrate Civil War Photographs

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1904]
**Story**

Migration the Civil War Photographs (PID 46) from Findit into DCS. 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the MED admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the MED admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
73 parents. Here is the handle:
[https://app.zenhub.com/files/242185115/c7fd4000-f2f8-4064-9119-c7321712cede/download](https://app.zenhub.com/files/242185115/c7fd4000-f2f8-4064-9119-c7321712cede/download)

**Comment by motropuk** [comment]
Looks good in UAT. Waiting for approval from Medical to move to Prod

**Comment by motropuk** [comment]
@MaggieZhaoYale We can move this to Prod

**Comment by MaggieZhaoYale** [comment]
@motropuk 73 parents are in the prod. https://collections.library.yale.edu/management/batch_processes/7098
