### ISSUE TITLE
Bug: Batch Processes Status, Message, and Batch Action for Delete Parent Objects

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1905]
**User Story**
As a user of the management DCS, I want more accurate information for the Batch Processes table.   I want to modify the status, messages, and batch action information for the delete parent objects.  

**When the process completes** 
- [x] the status should display "Batch complete"
- [x] the messages display an 0

**When the process fails**
- [x] the status should display "View Messages" that directs the user to the failed messages.
- [x] the messages display ought to be a non-zero if possible 

**Notes:**
* The last case of a partial failure was fixed in the last ticket.  
* The batch action column will remain as is
* The weight of the messaging needs to be carried by the batch status message

Example for when the process completes
![Screen Shot 2022-02-17 at 1.33.41 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3c565a3c-f9b9-46e4-be83-32b67a6866c9)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/942  
  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/9a9383c9-89a7-44eb-a58e-87d69c3ebfe7)

**Comment by FCRodriguez7** [comment]
Released management v2.59.6

**Comment by motropuk** [comment]
This is not working for me in UAT. See top job here. This failed. See messages icon, but status says batch complete![Screen Shot 2022-03-08 at 16.11.35.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/d96f936a-6fbc-426f-abb9-31111f89bebc)

**Comment by K8Sewell** [comment]
This ticket was specific to the 'delete parent objects' batch action - which looks like it does say batch complete in the screenshot.  Our approach was to take the actions one by one and address them individually.  We need to create another ticket to address the behavior in 'update parent objects' and I can work on getting it set up.  Our expectation is that each action is in need of a refactor for more precise message handling.

**Comment by motropuk** [comment]
Thanks @K8Sewell. I totally missed this (re it only being for the delete parent objects job). Apologies! In that case, this is done and can be closed
