### ISSUE TITLE
Migrate Harvey Cushing Photographs

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1906]
**Story**

Migration the Migrate Harvey Cushing Photographs (PID 48) from Findit into DCS. 

**Acceptance**
 - [x] Export image files from Fedora
 - [x] Import image files into the DCS pairtree
 - [x] Generate list of Parent OIDs
 - [x] Import the objects into DCS UAT into the MED admin set
 - [x] Audit objects in DCS UAT with collection owner
 - [x] Import the objects into DCS PROD into the the MED admin set
 - [x] Audit objects in DCS PROD
-  [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
simple objects

**Comment by motropuk** [comment]
Looks good in UAT. Waiting for approval from medical to move to UAT

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/management/batch_processes/7210 @motropuk 109 simple objects in prod.
