### ISSUE TITLE
[SPIKE] Review alternative structure of Preservica objects

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1909]
**Story**

Preservica objects may be structured in two ways.  The first pattern assumes the that the top-level Structural Object can have multiple children ("Information Objects") and that each of those children ultimately represents a single view/image.   In the second pattern a single Representation can have multiple Content Objects, each of which represents a separate view/image

**Pattern 1**
`Structural Object` -> 1..n `Information object` -> 1..n `Representations` -> 1 `Content Object`

**Pattern 2**
`Structural Object` -> ? `Information object` -> 1..n `Representations` -> 1...n `Content Objects`

**Outcomes**
- [ ] Meet briefly to review XML examples.
- [ ] Decide how to approach this.  Straw proposal: User should enter the specific `Information Object` URI as the Preservica URI if using the second  pattern.

**Comment by K8Sewell** [comment]
Was able to create multiple children with second pattern in this Spike branch - https://github.com/yalelibrary/yul-dc-management/pull/941 - presuming the user will provide an information object uri for pattern two.

**Comment by DraxIndustries79** [comment]
Waiting:  Till the first pattern is complete/checked
