### ISSUE TITLE
Add a Genre facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#191]
**ACCEPTANCE**
- [ ] I can narrow my search by faceting works by Genre

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/77

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-06-04 at 12.24.31 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/91c9a1b9-add5-44d5-b47e-419f99eb35b6)


![Screen Shot 2020-06-04 at 12.24.41 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3dca92a2-c87d-4397-a0a3-7ef238e32114)
