### ISSUE TITLE
Migrate Lam Qua Paintings Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1911]
**Story**

Migrate the Lam Qua Paintings Collection (PID 50) from FindIt into DCS.

**Acceptance**

- [x] Get replacement files from Medical - https://yale.app.box.com/folder/147029457685?utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans
- [x] Import image files into the DCS pairtree
- [x] Generate list of Parent OIDs
- [x] Import the objects into DCS UAT into the Med admin set
- [x] Audit objects in DCS UAT with collection owner
- [x] Import the objects into DCS PROD into the Med admin set
- [x] Audit objects in DCS PROD
- [x] Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm https://yale.app.box.com/folder/147029457685?utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans I got the page not found error.

**Comment by sshetenhelm** [comment]
Checking with Med Lib to see if this link is still active / if we need to be added to folder.

**Comment by sshetenhelm** [comment]
Med Lib has given myself and @MaggieZhaoYale access to folder.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 
There are 86 images in the folder, while the findit has 80 images. 7 images in the folder do not match the oid in the findit. 
Lam_Qua_8328_09
Lam_Qua_8437_36b
Lam_Qua_8779_82
Lam_Qua_8781_83
Lam_Qua_8785_85
Lam_Qua_8788_86
5948679
79 oids have the corresponding images in the folder, only one doe not have 15948679

**Comment by motropuk** [comment]
We can ignore these 6 images. These are new things to be added to the collection, so will need to go through Goobi. We can remind Melissa about this. 
Lam_Qua_8328_09
Lam_Qua_8437_36b
Lam_Qua_8779_82
Lam_Qua_8781_83
Lam_Qua_8785_85
Lam_Qua_8788_86

As for 5948679, this is just a naming error. This should be 15948679. @sshetenhelm or @MaggieZhaoYale can edit the name of the file in box https://yale.app.box.com/file/867409959032 to 15948679

**Comment by MaggieZhaoYale** [comment]
@motropuk @sshetenhelm 80 simple parents in the UAT https://collections-uat.library.yale.edu/management/batch_processes/745
Here is the handle excel:
[https://app.zenhub.com/files/242185115/3e48ad82-212c-4e55-9655-49bc5d3e4382/download](https://app.zenhub.com/files/242185115/3e48ad82-212c-4e55-9655-49bc5d3e4382/download)

**Comment by sshetenhelm** [comment]
Looks good in UAT! Waiting for approval from Medical to move to Prod

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale  These can be moved to PROD :)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 80 simple objects in prod now.

**Comment by sshetenhelm** [comment]
Still waiting on access to Persistent Linking Service (handles).

**Comment by motropuk** [comment]
This is all set. Just needs points
