### ISSUE TITLE
Access for Dev team to Preservica Test

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1915]
**Story**

Need to setup access to Preservica Test for DCS dev team. Preservica Test is behind SSO login, so can use netid and password for access. 

For the purposes of testing, dev team will be given access to all MUSIC_OPEN content in Preservica Test

**Acceptance**
- [ ] All members of DCS dev team can login to https://yul-pres-tsdb.library.yale.edu/ and access MUSIC_OPEN content

**Comment by motropuk** [comment]
Submitted request to Digital Preservation Services

**Comment by motropuk** [comment]
Permissions will also provide access to Prod for same content

**Comment by motropuk** [comment]
This is done. Could someone on the dev team check if they can access this object https://yul-pres-tsdb.library.yale.edu/explorer/explorer.html#browse:SO&bfac21a1-2e80-411a-9504-e784cd16d1e9&null. If so, this work is complete

**Comment by K8Sewell** [comment]
Was able to log in with my yale credentials.  Thanks for setting this up!
