### ISSUE TITLE
[DISCUSS] Split PDFs into separate bucket to avoid overwrites from the staging server?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1917]
**Story**

The nightly metadata sync in staging  ~~may~~ will rewrite production PDFs using data in staging that is not up to date.

Unfortunately we currently store the PDFs in the same bucket as the PTIFFs.   We have  ~ 1.4 TB of PDFs.

**Acceptance**
- [ ] Decide whether to deactivate the sync using a feature flag or split PDFs into their own bucket, with per-environment config.   We could config the staging S3 bucket to delete PDFs after a certain time period.

- [ ] Turn off staging management workers for now.

**Comment by mikeapp** [comment]
ServiceNow ticket created to turn off the Mgmt workers.

**Comment by DraxIndustries79** [comment]
Will check in Thurs 2/24 to make decisions.
