### ISSUE TITLE
Duplicate recurring metadata refresh jobs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1918]
**Story**

A new recurring activity stream sync job seems to be created each time we redeploy, on test and UAT.  This is not happening in production yet but will on the next deployment if we don't have a workaround.

**Acceptance**
- [ ] Queue on start only if the job does not exist

**Comment by martinlovell** [comment]
Removed the extra job(s) on UAT and test a few days ago...So those are good until we deploy again.
We should manually remove the extra on Prod after deploying Wednesday. (Making sure to leave one.)

**Comment by martinlovell** [comment]
![RecurringJob.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/fdc654c5-e43d-4b23-b6f7-e7ea9490ea73)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/939
