### ISSUE TITLE
Migrate Postcards Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1921]
**Story**
Migrate the Postcards Collection (PID 55) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Med admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Med admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm This is the handle:
[https://app.zenhub.com/files/242185115/c515eac9-3218-44fd-8976-3cc624d28658/download](https://app.zenhub.com/files/242185115/c515eac9-3218-44fd-8976-3cc624d28658/download)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm @motropuk 66 parents in uat. Ready to audit. Thank you.

**Comment by sshetenhelm** [comment]
All 66 objects came over as private, did a batch process to correct visibility to public. 
@MaggieZhaoYale these are ready for PROD :)

**Comment by MaggieZhaoYale** [comment]
As far as I know, batch process would not correct visibility to public.

**Comment by sshetenhelm** [comment]
Maybe I used the wrong vocabulary -- Jon and I did a Batch Action to Update visibility of Parent Objects to Public. I can confirm they are in UAT now with "Access: Public", so either (a) when Jon and I previewed the collection, we had the wrong project ID in the URL which resulted in no search results and there was no problem to fix or (b) we fixed it but I wrote the wrong thing above. 

Sorry for the confusion! Feel free to chime in @motropuk

**Comment by motropuk** [comment]
@MaggieZhaoYale this is just a note about a batch update we had to do in UAT during the audit process that we will also need to do in production. @sshetenhelm and I will take care of this, so nothing you need to do. Collection is just ready to move to prod

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Thank you.

**Comment by MaggieZhaoYale** [comment]
@motropuk @sshetenhelm 66 parents in prod. https://collections.library.yale.edu/management/batch_processes/7319
please ignore the one in progress, I reprocessed the child and it passed.

**Comment by sshetenhelm** [comment]
Still waiting on access to Persistent Linking Service (handles).

**Comment by motropuk** [comment]
This is all set. Just needs points
