### ISSUE TITLE
Missing JSS Parent Object

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1924]
**Story**

JSS Parent 30811664 was in the list of items provided for full text work, but is not present in DCS production.  

Note that this could be a glitch, the data dump I have has only two pages listed.  On the other hand, the page PIDs are not duplicated elsewhere in the data dump:

 ![Screen Shot 2022-03-01 at 9.08.32 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/ba47c08e-c59d-45e1-9cc5-45f71e2f368d)

**Acceptance**
- [ ] Identify missing object
- [ ] Ingest object
- [ ] Update full text status
- [ ] Reindex

**Comment by MaggieZhaoYale** [comment]
@MaggieZhaoYale 30811664 was created in the prod, then deleted later. The record is problematic.  The http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:2148930&query=&size=1 It is supposed to have 572 pages, but only two images in fedora. I checked this one with Marena Fisher, she did not find anything in Fedora after the second image. 
I deleted the parent object later.
