### ISSUE TITLE
Update links in DCS header menu

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1925]
**Story**

Some links in the top header menu for DCS are broken and need to be updated. Note that the DCS will eventually be updated to use the new YUL header structure, but in the meantime, we need to fix the following broken links.

**Acceptance**
Under Services menu
- [x] Off Campus Access -- update link to https://guides.library.yale.edu/OffCampusAccess

Under Libraries and Collections menu
- [x] Arts Library -- update link to https://web.library.yale.edu/building/haas-family-arts-library
- [x] Bass Library -- update link to https://web.library.yale.edu/building/bass-library
- [x] Beinecke Library -- update link to https://web.library.yale.edu/building/beinecke-rare-book-library
- [x] Classics Library -- update link to https://web.library.yale.edu/building/classics-library
- [x] Divinity Library -- update link to https://web.library.yale.edu/building/divinity-library
- [x] International Collections -- update link to https://web.library.yale.edu/international-collections
- [x] Law Library -- update link to https://web.library.yale.edu/building/lillian-goldman-law-library
- [x] Lewis Walpole Library -- update link to https://web.library.yale.edu/building/lewis-walpole-library
- [x] Library Collection Services -- update link to https://web.library.yale.edu/sd/dept/library-collection-services-and-operations
- [x] Marx Science & Social Science Library -- update link to https://web.library.yale.edu/building/marx-science-and-social-science-library
- [x] Mathematics Library -- update link to https://web.library.yale.edu/building/mathematics-library
- [x] Medical Library -- update link to https://web.library.yale.edu/building/cushingwhitney-medical-library
- [x] Sterling Library -- update link to https://web.library.yale.edu/building/sterling-memorial-library
- [x] Yale Center for British Art -- update link to https://web.library.yale.edu/building/yale-center-for-british-art

Under the Information and Policies menu
- [x] Library Hours -- update link to https://library.yale.edu/visit-and-study
- [x] Departments and Staff -- update link to https://library.yale.edu/staff-directory
- [x] Services for Persons with Disabilities -- update link to https://web.library.yale.edu/services-persons-disabilities
- [x] Scanning, Printing, and Copying -- update link to https://web.library.yale.edu/help/scanning-printing-copying
- [x] Computers Wireless -- update link name to “Computers & Wireless” and update link to https://web.library.yale.edu/help/computers-and-wireless
- [x] Purchase Request -- update link to https://ask.library.yale.edu/faq/174852

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.6

**Comment by motropuk** [comment]
@alisonclemens could you review this in UAT and approve this once thats done. Thanks

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/770

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.8
