### ISSUE TITLE
Migrate George Palade EM Photographs Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1926]
**Story**
Migrate the Migrate George Palade EM Photographs Collection (PID 47) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Med admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Med admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm This is the handle[https://app.zenhub.com/files/242185115/938d8ce2-7975-4ec4-b8ac-33e1d4c9ebd5/download](https://app.zenhub.com/files/242185115/938d8ce2-7975-4ec4-b8ac-33e1d4c9ebd5/download)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale These are ready for PROD :)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 190 simple objects in the prod https://collections.library.yale.edu/management/batch_processes/7536

**Comment by motropuk** [comment]
Looks good in Prod. Good to close (after points)
