### ISSUE TITLE
Reindex all sources in Test, UAT and Prod

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1930]
**Story**
Need to reindex all sources for #1884 to go into effect

Do repo by repo (excluding Beinecke) one at a time.

**Acceptance**
- [x] Reindex all sources for all sets in TEST
- [x] Reindex all sources for all sets in UAT
- [x] Reindex all sources for all sets except BRBL in Prod

**Comment by sshetenhelm** [comment]
This should be good but @motropuk if you could take a quick look to confirm, that'd be great.

**Comment by motropuk** [comment]
@sshetenhelm Everything looks good except the value for the arts library. The full value in Archives at Yale is "Robert B. Haas Family Arts Library Special Collections". The entry we have is just Haas Family Arts Library Special Collections. So I think we need to update that value in each instance and then reindex just the arts set (all sources) in each instance

**Comment by sshetenhelm** [comment]
Interesting! It's still just Haas on https://puitestarchivesspace.library.yale.edu/repositories so that's what I went with. Just updated it with the full name in TEST, UAT, and PROD. PROD has finished but UAT will take longer due to number of objects.
