### ISSUE TITLE
SPIKE: Partially processed items from METS

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1932]
**Story**

Some items seem to have been ingested, I think though Goobi, but are unable to be fully processed.
See:  https://collections.library.yale.edu/management/parent_objects/32268733

Stack trace in delayed job:
![Screen Shot 2022-03-07 at 2.49.57 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/8ff180bc-6c18-4f79-bd3d-fe5d659700ac)

**Acceptance**
- [ ] Review error and determine root cause (per @MaggieZhaoYale 1 image was not processed)
- [ ] Suggest a way to identify other objects that might be broken so that we can remediate them

**Comment by MaggieZhaoYale** [comment]
Get the list of children oid starts with 3 (assuming Goobi objects) without image 
[https://app.zenhub.com/files/242185115/9cd258f0-c217-4fa0-98b9-d89f896d9e3c/download](https://app.zenhub.com/files/242185115/9cd258f0-c217-4fa0-98b9-d89f896d9e3c/download)

**Comment by DraxIndustries79** [comment]
Maggie is making a new ticket for problem children
