### ISSUE TITLE
Migrate Pathology Teaching Illustrations Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1933]
**Story**
Migrate the Pathology Teaching Illustrations Collection (PID 52) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Med admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Med admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
The handle excel is here: [https://app.zenhub.com/files/242185115/10702e8f-3d48-4c9b-abf7-2555534bf8a3/download](https://app.zenhub.com/files/242185115/10702e8f-3d48-4c9b-abf7-2555534bf8a3/download)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Ready for PROD :)

**Comment by sshetenhelm** [comment]
Done, just needs points.
