### ISSUE TITLE
Bug: Batch Processes Status and Message for Update Parent Objects

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#1934]
**User Story**
As a user of the management DCS, I want more accurate information for the Batch Processes table. I want to modify the status and messages information for the update parent objects.

**Acceptance**
When the process completes

- [ ] the status should display "Batch complete"
- [ ] the messages display an 0

When the process fails

- [ ] the status should display "View Messages" that directs the user to the failed messages.
- [ ] the messages display ought to be a non-zero if possible

**Current Screenshot**
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/cc79fb11-46d7-4d6e-b2fd-b7f8aa73e81a)

**Comment by jpengst** [comment]
It seems like the status and messaging is working as intended. If there is a field that fails validation, the object still gets updated with the other valid fields and is reported as "Complete". If we want the objects to Fail and not update any of the other valid fields, we will need to stop the process from updating and report as "Failed".
