### ISSUE TITLE
IIIF viewingDirection fix

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1936]
**Story**

IIIF Manifest `viewingDirection` should not be an array.

**Acceptance**
- [ ] Change from an array to a string

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-management/pull/946

**Comment by FCRodriguez7** [comment]
Released management v2.59.7

**Comment by mikeapp** [comment]
https://collections-uat.library.yale.edu/catalog/12301559
