### ISSUE TITLE
Delayed Job: sleep delay setting

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1937]
**Story**

Delayed job is creating a lot of database load.   We should adjust the`Delayed::Worker.sleep_delay` to 120 seconds to prevent constant database traffic from the workers. See https://github.com/collectiveidea/delayed_job#gory-details

It looks like this was intended to be configurable via environment variable, see   `g.sleep_delay = ENV['WORKER_SLEEP_DELAY']` in https://github.com/yalelibrary/yul-dc-management/blob/9863f5fbdbc80464a3520d42e5691d655594c568/config/delayed_job_pool.rb#L11

* I'd suggest that we set the value to ~~60~~ 15 seconds  in the ECS worker template in Camerata.    
* We can experiment setting this value in the development template but I think we probably want to leave it as-is so our jobs start quickly when we are developing and testing.

**Acceptance**
- [x] Set the sleep delay to 15 seconds for ECS

**Comment by mikeapp** [comment]
PRs
Management: https://github.com/yalelibrary/yul-dc-management/pull/943
Camerata: https://github.com/yalelibrary/yul-dc-camerata/pull/336

**Comment by FCRodriguez7** [comment]
Released management v2.59.7
