### ISSUE TITLE
Delayed Job: reduce default number of retries

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1938]
**Story**

DJ will retry up to 25 times per https://github.com/collectiveidea/delayed_job#gory-details.  It is very unlikely that we would want jobs to be retried for 20 days (!).

See code reference in #1937 for method where this could be set, similar to the sleep delay.

**Acceptance**
- [ ] Reduce `max_attempts` in production to 15
- [ ] For local development, reduce to 3

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-management/pull/950

**Comment by FCRodriguez7** [comment]
Released management v2.59.9
