### ISSUE TITLE
images failed to convert to PTIFF or image missing

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#1942]
Processed 206 children with nil width/length for the ticket:
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1932
31 children failed. 
8 of them cannot found; others failed to convert to PTIFF with error code

- [x] identify the missing image

- [ ] find the missing image if it is possible

- [x]  identify the images which are failed to convert to PTIFF, 

- [ ] ask for replace images if it is possible

[https://app.zenhub.com/files/242185115/9d782c56-1fe2-4d26-9bcb-79258da70453/download](https://app.zenhub.com/files/242185115/9d782c56-1fe2-4d26-9bcb-79258da70453/download)

--------------------------------------------
More Goobi ingest errors -- 
Batch processes 7951 (OID 32335454) and 7948 (32335409) failed to convert to PTIFF. These have multiple children where most children pass but one or two fail. These have errors that mention different byte numbers.

Batch process 7947 (OID 32335023) 4 of 385 failed to convert to PTIFF. Error states ' "/tmp/d20220323-16540-iivnxc/32335296.tif" is not a known file format '

**Comment by MaggieZhaoYale** [comment]
18 of them are BRBL Goobi objects. The list including the Goobi process information was passed to Mark to investigate

**Comment by sshetenhelm** [comment]
Med Library will try re-ingesting their two failed images.

**Comment by sshetenhelm** [comment]
Re-opened and added details re: new Goobi PTIFF ingest errors.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The size of the original images in the Goobi server is significant different from that in the DCS image pairtree. It looks that there may issue when copying these images to the master path.
I manually copied four images from Goobi server to the image pairtree and re-create the ptiff, all completed. There are two or more, I will check tomorrow morning.

**Comment by MaggieZhaoYale** [comment]
Manually copied the images with error from Goobi to DCS image pairtree and reprocessed the ptiff, the parents look fine now.
The issue was: The pairtree of the problematic images were created, but the images were not fully copied.
https://collections.library.yale.edu/management/parent_objects/32335023
https://collections.library.yale.edu/management/batch_processes/7960/parent_objects/32335454
https://collections.library.yale.edu/management/parent_objects/32335409

**Comment by mikeapp** [comment]
We need to take a look at the fixity check in the copy routine.  There does appear to be a comparison of the checksum between the source and destination files, https://github.com/yalelibrary/yul-dc-management/blob/09a287dbe5ee97c24830ceab91e547e4a18be078/app/models/child_object.rb#L82

**Comment by mikeapp** [comment]
#1986
