### ISSUE TITLE
Metadata update and redirected records

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1943]
**Story**

When a record is redirected some of its data is cleared, such as its ASpace URI.    This means that a metadata refresh job that targets it will always fail (and retry 25 times!).

Prod example:
Job 766 updates Parent 2037971

**Acceptance**
- [x] Skip redirected records during metadata update

**Comment by FCRodriguez7** [comment]
Released management v2.59.10

**Comment by mikeapp** [comment]
This works.
