### ISSUE TITLE
Migrate Bookplates Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1944]
**Story**
Migrate the Bookplates Collection (PID 45) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Med admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Med admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 1068 simple object in UAT now https://collections-uat.library.yale.edu/management/batch_processes/794

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Here is the handle excel[https://app.zenhub.com/files/242185115/79040b98-8bb8-43e4-8ce2-8ea0023eae86/download](https://app.zenhub.com/files/242185115/79040b98-8bb8-43e4-8ce2-8ea0023eae86/download)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm is ready to audit in prod.

**Comment by sshetenhelm** [comment]
Done! Just needs points.
