### ISSUE TITLE
Ability to remove data from fields controllable via the DCS Management App in batch

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1945]
**Story**

As a user of the DCS Management App, I want to be able to clear out existing data in from one or more of the following fields, via one of the following batch jobs

**Reassociate Child OID**
- Label
- Caption
- Viewing Hint

**Update Parent Objects**
- Project Identifier
- digitization note
- Extent of Digitization
- Bib
- Holding
- Item
- Barcode
- Aspace URI
- Viewing direction
- Display Layout
- Redirect to
-  ~~Preservica URI~~
-  ~~Preservica Representation Name~~

Some sort of instruction would need to be added to the revenant fields within the .csv uploaded for each of these jobs, to ensure triggering the deletion of data in this field was intentional. Maybe using "" would result in a trigger to delete the information in the given field. 

May be worth beginning by documenting current behavior and seeing what we're doing now.

**Acceptance**
- [x] Decide on best approach to this and instruction users would need to add to batch .csv to indicate a deletion
- [x] Create ticket to implement chosen solution

**Comment by martinlovell** [comment]
Technically, the csv reader will treat `""` the same as nothing in that row, so it would be easier to have the user put in some kind of value.  

Maybe `_blank_` would work.  (I'm not sure what would be best for the users, and we would want to make sure it's not easy to get slightly wrong and fill the field with some bogus value).

It may be possible to get `""` to work if that seems like the safest option.

(Also, for "order" on children, we would have to set it to some integer.   So, I'm not sure how we would blank it out.  Now, order has to be a whole number (>=0))

**Comment by motropuk** [comment]
Thanks @martinlovell. Good point about Order. That is a mistake. I will remove that as a ticket to address in this ticket. As for what value to use, I think _blank_ could work. Would be interested to hear from @alisonclemens and @ucancallmealicia however

**Comment by motropuk** [comment]
Lets go with the version with underscores before and after. Thanks @martinlovell

**Comment by martinlovell** [comment]
While working on this, I noticed that Preservica URI and Preservica Representation Name can not be updated using the update parent objects job.  

That is probably on purpose, since it would require a re-sync to have it take effect.  Also, they should probably not be allowed to blank out since the the digital object source is likely preservica for items which have values for those fields.  It may be that updating those values should be part of resyncing, and they can not be blanked out.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/972

**Comment by martinlovell** [comment]
Released management v2.59.20
