### ISSUE TITLE
Management: Parent Object display improvements

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1946]
**Story**

The display of individual Parent Objects in Management could be improved. 

**Acceptance**
- [x] Have the field labels and values in columns, with all values left-justified, similar to the object display in Blacklight. See below.
- [x] Match fonts and weights for the labels/values to those in Blacklight
- [x] Make the headers for "Authoritative JSON" and "Solr Record" match the Blacklight display page headers (like "Collection Information" below)
- [x] Move "Authoritative Metadata source" and the "Update Metadata for this Object" label/button above "Metadata Cloud URI"

![Screen Shot 2022-03-15 at 9.24.34 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f9e0f9bf-75e0-4b26-acdb-4ec48e6ac8b4)

**Comment by jpengst** [comment]
First pass:
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/c1f93985-4d32-40e0-931d-9c269bec36c7)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/955

**Comment by K8Sewell** [comment]
Hey @AKFosterDev I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by FCRodriguez7** [comment]
Released management v2.59.10

**Comment by mikeapp** [comment]
One small issue is that "Select different representative thumbnail" is right-aligned, but I think we can make a follow-on ticket for fixing that.

**Comment by FCRodriguez7** [comment]
Edge
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f1d0784e-9198-421a-a982-555c9ba8e24c)

Chrome
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c6427814-7496-4a5e-b0f8-ea165d872cce)

Firefox
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/dc057008-596a-4603-bcb9-82831ba6a937)

Safari
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e68b96a7-f9ed-4091-bd73-4d9accd66add)

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/970

**Comment by martinlovell** [comment]
I'm not sure if this was intentional, but these latest changes removes the scrollbar for the child objects list, which will push down the rest of the page when there are a lot of children.

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5cc082a0-6410-4f16-bd1e-bdf943071114)

**Comment by FCRodriguez7** [comment]
Released management v2.59.19
