### ISSUE TITLE
[SPIKE] Develop requirements for Preservica resync

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1947]
**Story**

We'd like to be able to resync objects from Preservica if a change has been made.

**Acceptance**
- [ ] Discuss possible types of changes.  (e.g., child added, removed, replaced)
- [ ] Replicate changes in Preservica and develop fixtures for analysis
- [ ] Outline code logic to resync DCS with minimal disruption

**Comment by DraxIndustries79** [comment]
Plan will be to meet Wednesday 3/16
