### ISSUE TITLE
Testing LB/migration and Goobi ingest

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1949]
**Story**

After the Preservica changes we should conduct tests of Goobi ingest and Ladybird/migration ingests on test or UAT.

**Acceptance**
- [x] Goobi ingest looks good
- [x] Migration ingest looks good

**Comment by MaggieZhaoYale** [comment]
Tested on UAT. Three Goobi objects look fine:
https://collections-uat.library.yale.edu/management/parent_objects/900124059
https://collections-uat.library.yale.edu/management/batch_processes/896/parent_objects/900124050
https://collections-uat.library.yale.edu/management/batch_processes/895/parent_objects/900105540

**Comment by MaggieZhaoYale** [comment]
Both Goobi ingest and migration test are fine.
