### ISSUE TITLE
Add DCS homepage link to the search result page

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1957]
**Story**
Users who have searched the DCS would benefit from a way to return to the DCS homepage after conducting a search. A link to https://collections.library.yale.edu/ should be added to the "Digital Collections" text on the left side of the search results page (this is the text above the search limits).

**Acceptance**
- [x] Link is added and directs users to https://collections.library.yale.edu/

**Comment by FCRodriguez7** [comment]
The PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/777

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.14
