### ISSUE TITLE
Change height of datatables so that horizontal scrollbar appears on page

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1958]
- [x] Change height of table so that horizontal scrollbar appears above the fold

**Comment by martinlovell** [comment]
Tested on Demo.

https://github.com/yalelibrary/yul-dc-management/pull/953

**Comment by FCRodriguez7** [comment]
Released management v2.59.11

**Comment by mikeapp** [comment]
Looks good to me, should we demo this?
