### ISSUE TITLE
INVESTIGATE: Silence blacklight deprecation warnings

### ISSUE THREAD

**Issue by tilthouse** [yalelibrary/YUL-DC#196]
Investigate if and how to silence deprecation warnings in our app. 

Timebox to 1/2 day

**Comment by bess** [comment]
Breadcrumb from the Blacklight slack channel: https://github.com/Shopify/deprecation_toolkit

**Comment by tilthouse** [comment]
We will use the deprecation toolkit to suppress these warnings
