### ISSUE TITLE
Create documentation for DCS management app

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1963]
**Story**

As a collection owner of content in DCS, I need to access to clear and up to date documentation to help me use the DCS management app

**Acceptance**
- [x] Draft management app documentation
- [x] Seek input from library staff about draft
- [x] Integrate feedback from Staff after April 8th
- [x] Create step by step breakdowns of what each batch process does
- [x] Enhance documentation around batch processes

**Comment by motropuk** [comment]
Additional work right now includes creating step by step breakdowns of each batch process. Will then use this to enhance Management App documentation, to answer questions about things you want to do in DCS and how to do these, in line with this cookbook approach Summer started https://docs.google.com/document/d/1l-XlSKdS6ylkGq7pPLR1F2QUfvaIUzVlFaLVZQRpm-A/edit#heading=h.3bt2ekbogzo8

**Comment by sshetenhelm** [comment]
I have some feedback via email that Ellen provided in our email thread titled "RE: Digcoll-OID mapping" but that's it. I'll work through the google doc feedback.

**Comment by motropuk** [comment]
We can close this ticket when @sshetenhelm has added point. Will move the work of linking to the documentation from the management app to a new ticket
