### ISSUE TITLE
Utility to export Preservica XML to disk

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1965]
**Story**

We need to be able to export Preservica XML files to disk for inspection and use as fixture objects.

**Acceptance**
- [x] Write an exporter that takes as arguments a URI for a structural object URI and representation name, and exports all of the child objects as XML. (Pattern 1)
- [x] Write an exporter to take an information object URI and representation name and export all of the child objects. (Pattern 2) 
- [x] Directory structure:
  - [x] Directory name should include the top-level object ID
  - [x] XML files should include the object type name and possibly the  ID (e.g., "stucturalObject-123" ?)

**Comment by martinlovell** [comment]
See comment in PR for details: https://github.com/yalelibrary/yul-dc-management/pull/962

This exports the XML for the objects, which is useful for seeing what the objects are like in Preservica.

It would be helpful to make a similar task for creating fixtures.  For the fixtures, there are a few types that don't need the xml for the object itself, but need some other API calls (e.g. `/api/entity/structural-objects/#{id}/children`).  For the fixtures, we would create the full directory structure and make the filename just the last part of the uri path. That will make it easy to match the path/filename with the api call when mocking.

**Comment by mikeapp** [comment]
Looks good!
