### ISSUE TITLE
Migrate Garvin Ladybird metadata to ASpace and reassociate 

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1967]
**Story**

The majority of the Garvin City Planning Collection was moved into DCS Production (see #1929). However, a number of parent objects are still not displaying in Blacklight. This is mostly due to missing or problematic images that were not successfully brought over from Fedora. Fixing the issues in Ladybird/Fedora to bring these missing images is not practical. Therefore we have agreed with Arts that we will add these missing images to DCS via Goobi, as new ingests. However, before we can do this, we need to migrate all of the existing metadata for the collection to Aspace, so the collection can then be reassociated with this ASpace data, and the missing objects can be brought in via Goobi, again using their corresponding data in ASpace. 

**Acceptance**
- [x] Export existing data from ASpace along with corresponding OIDs to aid later reassociation
- [x] Map data elements to ASpace fields in consultation with Arts
- [x] Ingest data in ASpace
- [x] Reassociate existing parents in DCS with ASpace data
- [ ] Close this ticket and pickup #1929

**Comment by ucancallmealicia** [comment]
Updated Garvin metadata is in Aspace PROD: https://archives.yale.edu/repositories/5/resources/12798. OIDs are matched with new URIs, with the broken/missing images from #1929 excluded. Waiting for full availability of prod aspace sync before updating parent objects in DCS with aspace URIs.

**Comment by DraxIndustries79** [comment]
Alicia back July 11
