### ISSUE TITLE
[SPIKE] Decide how to handle how HTML links from metadata display in Blacklight

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#1970]
Story

A number of objects in DCS have HTML links in their metadata which display as plain text in Blacklight. For example, OID: 
16626437
![Screen Shot 2022-03-23 at 2.50.04 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/f3e6fda9-b4cb-45cf-bdbd-797857776ab6)

We would like to decide the best course of action to handle how links in metadata appear in Blacklight.

Acceptance

- [x] Identify objects that include html links in their metadata
- [x] Identify the fields those links appear in
- [x] Identify any other locally-controlled fields links may appear in
- [x] Decide on the best approach to handle how HTML links from metadata appear in Blacklight
- [ ] Create a ticket to implement the chosen solution

**Comment by sshetenhelm** [comment]
3590 objects include "<a href=" in their metadata: https://collections.library.yale.edu/catalog?fulltext_search=1&search_field=all_fields&fulltext_search=1&q=%22%3Ca+href%22

**Comment by martinlovell** [comment]
I took a look at the code, and we did already have something in place that allowed links in the RIghts field. (no other fields).

There was a bug that caused it to render incorrectly.
It is updated in this PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/779
to display the link instead of the HTML.

This may not be a complete fix, since it is only for the rights field. We can apply the same helper to other fields that need to display links.

**Comment by sshetenhelm** [comment]
Links also appear in 'Description' field but those are the only two I've seen so far. 
Example: [https://collections.library.yale.edu/catalog/10689253](https://collections.library.yale.edu/catalog/10689253)

**Comment by martinlovell** [comment]
Added PR for description field:
https://github.com/yalelibrary/yul-dc-blacklight/pull/780

**Comment by martinlovell** [comment]
Show page changes are in release: v1.60.16

**Comment by martinlovell** [comment]
Links look correct in UV:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/f3c3a2dd-9fe5-45cf-8e33-f729133d0d7f)

**Comment by martinlovell** [comment]
Follow up issue for IIIF Manifests: #2019

**Comment by martinlovell** [comment]
For testing in UAT: https://collections-uat.library.yale.edu/catalog/10689253 (description field).
Summer's query for UAT for multiple documents with rights fields with links: https://collections-uat.library.yale.edu/catalog?fulltext_search=1&search_field=all_fields&fulltext_search=1&q=%22%3Ca+href%22
