### ISSUE TITLE
Add Parameter/Environment Variable for Archive Space Base URL

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#1972]
The links to archives space are hard coded to go to `https://archives.yale.edu`

As a user testing digital object updates in DCS UAT, I would like the links to go to `https://puitestarchivesspace.library.yale.edu` instead, since the digital objects from UAT go to test archives space.
(This is a request from Mark Custer @fordmadox )

Code where the link prefix is currently hard coded:
https://github.com/yalelibrary/yul-dc-blacklight/blob/main/app/helpers/blacklight_helper.rb#L185

- [x] Add a parameter to the AWS parameter store for UAT which is set to `https://puitestarchivesspace.library.yale.edu`
- [x] Update camerata to pass that variable to the containers as an environment variable.
- [x] Update blacklight to use that environment variable if present, and default to `https://archives.yale.edu` if not present.

Use the documentation here: https://github.com/yalelibrary/yul-dc-camerata/wiki/Parameters,-and-How-to-Add-Them
- [x] Update the documentation, or confirm that it's complete and correct

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/776
https://github.com/yalelibrary/yul-dc-camerata/pull/337

**Comment by FCRodriguez7** [comment]
Released blacklight v1.60.13

**Comment by mikeapp** [comment]
Looks good.
