### ISSUE TITLE
UV3: Adjust responsive design so more information bar remains present

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#1978]
**Story**

A number of end users have noted that they have not been able to see the more information bar in UV when viewing DCS objects on smaller screens or reducing window sizes on desktop monitors. Is it possible to adjust the threshold within the responsive design for DCS so this bar remains visible for longer when adjust the display width. 

Testing this in Chrome on a 1920x1080 monitor, more information bar disappears when window width is reduced below 1318px. 

**Acceptance**
- [ ] Adjust responsive design so More Information bar in UV displays for smaller screens as much as possible/practical

**Comment by mikeapp** [comment]
I'm looking at this in UV 4, see #1989 for possible CSS.  I'd imagine it is similar in UV 3.
