### ISSUE TITLE
Silence blacklight deprecations

### ISSUE THREAD

**Issue by tilthouse** [yalelibrary/YUL-DC#198]
Pending the results of investiagtion

**Comment by tilthouse** [comment]
To be pointed or removed after investigation

**Comment by bess** [comment]
Our tests are no longer full of deprecation warnings! 

![Screen Shot 2020-06-08 at 4.07.42 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/e2b84c56-21d8-4464-b333-57996e7ecbb4)
