### ISSUE TITLE
SPIKE: Determine how to facilitate linking to specific pages within multi-page objects

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1980]
**ISSUE**
Staff would like to be able to provide library patrons with links to specified pages within multi-page objects, and there is currently no ready way to do so. The current work-around is to navigate to the desired page within the IIIF viewer, open the MORE INFORMATION panel, locate the “Image OID,” and manually append that OID to the end of the URL for the page using the following structure: https://collections.library.yale.edu/catalog/17105724?child_oid=17112326 

We should examine options for making this functionality more seamless and apparent to users; identify an option to proceed with.

**ACCEPTANCE**
- [x] Identify two or more options to generate URLs for specified individual pages within multipage items
- [x] Recommend one to implement

**Comment by jpengst** [comment]
Possible solution is to show the child uv link in the "More Information" side panel:  
  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/1fda9932-a24f-4ea3-8996-9f40adaed470)

**Comment by jpengst** [comment]
Another potential solution is to put the link in the "Share" modal. Although, this has not been figured out yet and could be a heavier lift:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/6c92d019-4616-4b0d-94fc-804cdd3d253c)

**Comment by martinlovell** [comment]
v2.59.22

**Comment by martinlovell** [comment]
Test by updating a parent with more than one child, get the link through the viewer, and trying the link to see if it goes to the right page.

**Comment by motropuk** [comment]
Looks good in UAT - tested with https://collections-uat.library.yale.edu/catalog/10723635 which has the same OID in UAT and Prod so the link works
