### ISSUE TITLE
Reduce Cantaloupe max-age

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1981]
**Story**

Cache setting on `info.json` responses should be shorter?

```
Cache-Control: max-age=2592000, public, no-transform
```

**Acceptance**
- [ ] set max-age to 86400 (1 day) instead of 30 days.

**Comment by AKFosterDev** [comment]
The current max age currently set to 604800 (one week) which was completed in this [PR}(https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/19/files). Can this ticket be closed?

## Screenshot
![Screen Shot 2022-06-13 at 10.52.21 AM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/ecb0af9c-0b7e-4157-aace-855e52af7eac))
