### ISSUE TITLE
Goobi to pairtree file copy can fail

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1986]
**Story**

The code that copies files from the Goobi share to the pairtree can fail and leave a partial file in place. See https://github.com/yalelibrary/yul-dc-management/blob/09a287dbe5ee97c24830ceab91e547e4a18be078/app/models/child_object.rb#L65

The logic 
(1) checks whether a file already exists and returns if so (i.e., assumes it is good)
(2) if no file already exists, it copies the file and checksums it

If an error happens during (2), the file may be partially written.  A subsequent retry of the job will assume that the file is good.

**Acceptance**
- [x] See whether we can use the checksum from the METS for the fixity check, rather than the checksum of the source file
- [x] Perform a fixity check of file on disk if it already exists and raise an error if it is corrupted.

**Comment by martinlovell** [comment]
@mikeapp : @MaggieZhaoYale and I updated the PR to add the checksum check in the mets validation and to check the checksum of the source file in the copy to pair tree method.

**Comment by martinlovell** [comment]
Released management v2.59.21
