### ISSUE TITLE
UV SPIKE: return from full-screen mode does not resize image

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1987]
**Story**

In UV4, after using the viewer in fullscreen mode, when the viewer returns to the embedded view it does not resize the image.   (This may be related to the custom JS we use to resize the viewer?).   

Example after exiting full screen mode:

![Screen Shot 2022-03-29 at 10.39.25 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/1a447e9f-63ba-4827-beb2-ff663543d450)

It should show the whole object (assuming the user did not zoom in):
![Screen Shot 2022-03-29 at 10.42.19 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/ce196258-86bc-4daf-8feb-27f6dd2a14e6)

**Acceptance**
- [ ] Investigate if this is related to screen size and at what size this occurs
- [ ] Viewer retains the view of the object when exiting full-screen mode.

Create PR to `uv4` feature branch.

**Comment by K8Sewell** [comment]
I was able to reproduce the incorrect resizing behavior and by implementing an example I found it looks like we have the desired functionality back.  I will work on getting PR together.

https://images.zenhubusercontent.com/242185115/3020e25a-55c4-4d6b-806f-9a2e7feb2ee3/screen_recording_2022_04_14_at_03_06_31_pm.mp4

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/785

**Comment by martinlovell** [comment]
Released management v2.59.26

**Comment by mikeapp** [comment]
I'm using Mac + Safari
