### ISSUE TITLE
UV4: Show/hide full text

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1988]
**Story**

In UV4 the show/hide full text button is displayed and is able to be toggled, but does not trigger the display of the full text beneath the viewer.   See any full-text item in production for an example of the desired behavior (e.g., https://collections.library.yale.edu/catalog/30692173 )

Location of button:
![Screen Shot 2022-03-29 at 10.45.46 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/e3f678c1-3e81-42da-8c4a-a2e2fcf93ecd)

**Acceptance**
- [x] The show full text button shows the full text
- [x] This works in 1-up viewing mode 
- [x] This works in 2-up viewing modes (i.e., the object's "Display Layout / Viewing Hint"  is set to `paged`)

Create PR to `uv4` feature branch.

**Comment by K8Sewell** [comment]
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8734c686-ee0d-4eed-a6e2-dbf18add7f3a)
https://images.zenhubusercontent.com/242185115/56895d17-7e08-412b-8a0f-0f19231d8384/screen_recording_2022_04_13_at_03_49_38_pm.mp4

Full text working in uv4 - PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/783

**Comment by K8Sewell** [comment]
Screen shot from demo 
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8782cfb9-1204-476f-870a-ff48e53ef2c0)

**Comment by mikeapp** [comment]
Using Mac+Safari, on the initial "show" I see the same text twice.  If I navigate away to another page and then back I only see it once. https://collections-demo.library.yale.edu/catalog/16748034

![Screen Shot 2022-04-20 at 1.45.17 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/57ee041f-2885-4f56-997a-f49286c01306)

![Screen Shot 2022-04-20 at 1.45.32 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/081fa59d-9ce0-4b51-93e2-4c61235a6a2a)

**Comment by K8Sewell** [comment]
Not able to replicate this behavior on Safari.  On first load only got one listing of full text.  
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/efd2ca12-b79c-4d11-a427-0079bb56dc34)


Showing only one listing in Chrome as well
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/ba967bc2-54fa-4d32-8a2d-0e3b79a82c06)

**Comment by mikeapp** [comment]
Now I can't reproduce it either.
