### ISSUE TITLE
Add a link to Genre on the show page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#199]
**ACCEPTANCE**
- [ ] The Genre field links to other works with the same value

NOTE: See #194 for a detailed example

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/77

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-06-04 at 12.24.53 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/345a5020-5143-49fe-b26c-dad941e0bdcb)
