### ISSUE TITLE
Update metadata by admin set will not skip redirected objects

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1991]
**Story**

@martinlovell  points out that the code to skip metadata to redirected objects uses a default parameter value for `where` (1) but  updating metadata for an admin set will supply a value for this parameter.    

(1) https://github.com/yalelibrary/yul-dc-management/blob/9878af12383d3bdb9ba88861a652270d8b3e95d5/app/jobs/update_all_metadata_job.rb#L10

(2)  https://github.com/yalelibrary/yul-dc-management/blob/adff2c82b3f8349f6f7155f083dad0e22f561c62/app/controllers/parent_objects_controller.rb#L125 

I believe we can always skip metadata updates on these objects.

**Acceptance**
- [x] Always skip metadata updates for redirected objects

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/969

**Comment by mikeapp** [comment]
Looks good.  Tested on UAT against MUS Ladybird objects, the one redirected object in this category did not appear in the error queue.
