### ISSUE TITLE
UV4: Cross-browser testing

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1993]
**Story**

We should perform cross-browser testing on Mac and Windows.

**Acceptance**

Test the items in the test plan in each browser.

 **Test plan**
  - load
  - zoom
  - full screen
  - full text search and search result navigation
  - metadata display
  - download
  - show/hide full text

**Test on Mac**
   - [x] Chrome
   - [x] Firefox
   - [x] Safari

**Test on Windows**
   - [x] Chrome 
   - [x] Edge
   - [x] Firefox

Create PR to `uv4` feature branch.

**Comment by DraxIndustries79** [comment]
Waiting for new VPN approvals for Amanda.

**Comment by AKFosterDev** [comment]
### Mac
1. Chrome: 
  - load - works as expected
  - zoom - works as expected
  - full screen - works as expected
  - full text search and search result navigation - full text hover box not populating text and click to page not working
  - metadata display - works as expected
  - download - works as expected

2. Safari:  
  - load - works as expected
  - zoom - works as expected
  - full screen - Full screen not expanding vertically.
  - full text search and search result navigation - works as expected
  - metadata display - works as expected
  - download - works as expected

3. Firefox:  
  - load - works as expected
  - zoom - works as expected
  - full screen - works as expected
  - full text search and search result navigation - works as expected
  - metadata display - works as expected
  - download - works as expected

**Comment by AKFosterDev** [comment]
VPN access has been straightened out.

**Comment by AKFosterDev** [comment]
Noticed another behavior across all browsers and systems. The Attribution pop up loads automatically. Not sure if this is wanted.

![image.png](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/1b6aec66-7ba7-4a15-a433-41a845b83a36)

**Comment by mikeapp** [comment]
@AKFosterDev That is expected behavior.   Per the IIIF Presentation spec it "MUST be displayed when the resource is displayed or used."  https://iiif.io/api/presentation/3.0/#requiredstatement
