### ISSUE TITLE
Rename uv.html file to avoid cache issues

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1994]
**Story**

After deploying UV 4 to the demo server my browser still delivered the cached `uv.html` file with UV 3.

**Acceptance**
- [x] Determine whether `uv.html` and/or any related files will cause issues.  (I think there's a config file `config/uv/uv.html` whose name did not change with UV4 but the content may not have changed either, in which case it won't be a problem.)
- [ ] Use a cache-breaking parameter in the request. 

Create PR to `uv4` feature branch.

**Comment by AKFosterDev** [comment]
PR ready for review https://github.com/yalelibrary/yul-dc-blacklight/pull/787

## Screenshots

### Before
![Screen Shot 2022-04-21 at 2.59.52 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/e8bd92f2-f796-4944-b638-05f37ad82727)

### After
![Screen Shot 2022-04-21 at 3.06.54 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/432997b9-40dd-483f-9d19-4efc9ca38c34)

**Comment by mikeapp** [comment]
Good idea to use the meta tags, but I think there's still an issue when we first replace the file, if the user's browser already has it in the cache.

**Comment by mikeapp** [comment]
Also, the "embed" option at the bottom left of the UV provides a URL that references `uv.html` directly, so if we rename the file we would need to redirect from the old location.
