### ISSUE TITLE
UV4: Pass full text search to viewer

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#1995]
**Story**

Full text searches in DCS will pass the search term to the viewer on the individual object page and automatically execute a search.   For example, clicking on any result in  https://collections.library.yale.edu/catalog?search_field=fulltext_tesim&fulltext_search=2&q=Хотите will navigate to the item page and the viewer will show results for that word.

In UV4 the term is not being read by the viewer.

In UV3 `uv.html` I believe the following configuration was captured by the following configuration setting:
`highlight: urlDataProvider.get('q'),`

**Acceptance**
- [x] The search term is passed to UV when the individual item page is displayed.   UV automatically runs the search and displays the results. 

Make the PR to the `uv4` branch.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/784

https://images.zenhubusercontent.com/242185115/42c5186c-f0be-4f8b-a891-514f39ebb75c/screen_recording_2022_04_14_at_11_41_19_am.mp4

**Comment by K8Sewell** [comment]
Screenshot from demo 
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4120b0bc-61c1-4ab6-9baf-af7e737cb630)

**Comment by mikeapp** [comment]
Looks good!  

Noticed an unrelated issue we had with UV3 and blank labels, created #2034
