### ISSUE TITLE
Migrate Medical Instruments Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2002]
**Story**
Migrate the Medical Instruments (Called _Medical Instruments and Artifacts_ in FindIt) Collection (PID 51) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Med admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Med admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 510 complex objects in uat https://collections-uat.library.yale.edu/management/batch_processes/939
There are two simple objects not ingested into UAT because no tif/jp2 in fedora:
17324440
17319838

**Comment by sshetenhelm** [comment]
17319838 appears to be a duplicate of 17324509. Asking Med to confirm.

Requested new image for 17324440 or for Med to confirm if a duplicate  exists that I didn't recognize.

Note to self: had to use batch process to change visibility to Public.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Sure. I could put the image for 17324440 in the pairtree. Please send me the image or the direct me the link of the image.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The simple object was added to uat https://collections-uat.library.yale.edu/management/batch_processes/954

**Comment by sshetenhelm** [comment]
Thanks @MaggieZhaoYale! Could you please move these to PROD?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 510 complex parents + 1 simple object in prod. It is ready to audit in prod. Thank u.

**Comment by sshetenhelm** [comment]
Done! Just needs points :)
