### ISSUE TITLE
Migrate Lillian Goldman Law Library Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2004]
**Story**
Migrate the Lillian Goldman Law Library Collection (PID 99) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by sshetenhelm** [comment]
1. Requested images for 16807678 & 16807679 from Law.
2. 16737204 (not brought over due to 0 children or files) and 16736453 both appear to be redundant records. Asked Law to confirm that they are unnecessary.
3. 17341455 appears under this collection in FindIt but is actually a listing from the Yale Law Directory and Facebook collection (PID 120). This will not be included in our final numbers for PID 99.

If Law confirms that 16736453 and 16737204 are redundant, our final number of parent objects for this collection in DCS should be 47 instead of 50.

**Comment by sshetenhelm** [comment]
1. Received image for missing child from parent 16807679 from Law. I will share with @MaggieZhaoYale via Box.

2. Child 16736594 from parent 16807678 was accidentally uploaded to that object. That child can be deleted.

3. Law had confirmed that parents 16737204 and 16736453 are redundant and can be ignored/deleted.

4. Law has indicated these files have OCR/txt. I have confirmed this in Ladybird and created #2021 for this work.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm added the missing child 16736615 to  https://collections-uat.library.yale.edu/management/parent_objects/16807679
deleted the child 16736614;
It looks that 16737204 and 16736453 were already deleted.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm https://collections-uat.library.yale.edu/management/parent_objects/16807678 looks fine after updating metadata

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Thank you! We can move this to PROD

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/4ed06fa5-6492-4dd7-9d82-1566c1b2f3d7/download](https://app.zenhub.com/files/242185115/4ed06fa5-6492-4dd7-9d82-1566c1b2f3d7/download) @sshetenhelm handle is here.

**Comment by sshetenhelm** [comment]
One parent failed because it was missing child 16736614; child 16736614 is unnecessary, so I deleted it; parent works now! 
Ran batch process to updated visibility to public. 

@MaggieZhaoYale done! just needs points :)
