### ISSUE TITLE
Migrate Yale Law School Oral History Series Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2005]
**Story**
Migrate the Yale Law School Oral History Series Collection (PID 98) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm handle is here

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm https://collections-uat.library.yale.edu/management/batch_processes/950 8 complex parents. Ready to audit.

**Comment by sshetenhelm** [comment]
Law indicated that these should have full text files. I see embedded OCR in PDFs. Do we need to open a separate ticket to get the text info?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Please open a separate ticket for the full text. I will start download the ocr for these collections.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 
236 complex parents in UAT,  4 failed because:
child image 17326949 of parent 17328097 was not found in Fedora
child image  17329746 of parent  17332624 was not found in Fedora
child image  17334016 of parent  17341467 was not found in Fedora
child image  17332274 of parent   17333921 was not found in Fedora

**Comment by sshetenhelm** [comment]
Thanks @MaggieZhaoYale ! If I understand the other ticket, the full text will be available after going to PROD, correct? If so, we're ready to move to PROD :)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm It is ready to audit in prod. https://collections.library.yale.edu/management/batch_processes/8018

**Comment by sshetenhelm** [comment]
Ran batch process to update full text status - https://collections.library.yale.edu/management/batch_processes/8038

But I don't see full text info on public end. Where should that info display?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm solr record of the parents should have  has_fulltext_ssi: Partial or Yes, but it is no. I am still investigating this.

**Comment by MaggieZhaoYale** [comment]
@mikeapp Thank you. I will run metadata update.

**Comment by MaggieZhaoYale** [comment]
The fulltext search box displays (Search within this item:) https://collections.library.yale.edu/catalog/16331191. However it seems the search did not return results.

**Comment by mikeapp** [comment]
This is the same object that had the encoding issue.  I suspect that it will require looking at the individual transcription files to find the problem(s).   Possibly opening and re-saving them in a text editor with UTF-8 encoding, or writing a script to convert the encoding.

**Comment by MaggieZhaoYale** [comment]
@mikeapp Thank you. Will do

**Comment by mikeapp** [comment]
It looks like there are eight failed jobs in the `intensive_solr_index` on production, all with `source sequence is illegal/malformed utf-8`

**Comment by MaggieZhaoYale** [comment]
The txt are encoding in ISO-8859-1. I will write a script to convert the encoding.

**Comment by MaggieZhaoYale** [comment]
created to-uft8.bash and ran the script to convert the files from ISO-8859 to utf-8, then copied to S3 fulltext bucket.

**Comment by sshetenhelm** [comment]
Comments re: OCR have been copied to OCR ticket #2018 so we can close this ticket. 
@MaggieZhaoYale Could you please add points to this one? Thank you!
