### ISSUE TITLE
Migrate Legal Manuscripts Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2006]
**Story**
Migrate the Legal Manuscripts Collection (PID 96) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
Ready to audit on UAT https://collections-uat.library.yale.edu/management/batch_processes/951
