### ISSUE TITLE
Migrate Yale Law Yearbooks Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2007]
**Story**
Migrate the Yale Law Yearbooks Collection (PID 119) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by sshetenhelm** [comment]
43 parents show for this collection in FindIt. However, it looks like there should actually be 47 parents.
Parent 17341456 is a hierarchical record and should not be included. 
List of parent OIDs that should be migrated is here: [https://app.zenhub.com/files/242185115/b1be83c6-cc88-4ebf-ae58-6a7f14fdaec1/download](https://app.zenhub.com/files/242185115/b1be83c6-cc88-4ebf-ae58-6a7f14fdaec1/download)

I will request the tifs of missing children from Law.

**Comment by MaggieZhaoYale** [comment]
I am reprocess this collection by query the list of the OIDs

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale the four missing children are available at [https://yale.box.com/s/f7ahv0nwh03bj49yafmohrxjke5zz2hb](https://yale.box.com/s/f7ahv0nwh03bj49yafmohrxjke5zz2hb)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Thank you. I will upload the images and copied them to the pairtree.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 47 parents in uat. There is still one image missing:  17329660 of parent https://collections-uat.library.yale.edu/management/parent_objects/17332624. The child oid is not in fedora.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale the missing image is here: [https://yale.box.com/s/r8i0tiacckvxclojvkjb5uqs03s7814q](https://yale.box.com/s/r8i0tiacckvxclojvkjb5uqs03s7814q )

We are ready to move to PROD :)

Note to self: Batch process for visibility Yale Community Only

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/management/batch_processes/8069 It is ready to audit in PROD @sshetenhelm

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale could you please send me handles?

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/22bb27da-b95f-4369-a90a-738a43b42664/download](https://app.zenhub.com/files/242185115/22bb27da-b95f-4369-a90a-738a43b42664/download) @sshetenhelm Here is the handle.
Sorry, sometimes I had trouble uploading the attached files.
