### ISSUE TITLE
Migrate Italian Municipal Statutes Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2008]
**Story**
Migrate the Italian Municipal Statutes Collection (PID 97) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/ca39a5ab-e0cf-4878-9b5a-a3e307dcf1f1/download](https://app.zenhub.com/files/242185115/ca39a5ab-e0cf-4878-9b5a-a3e307dcf1f1/download) This is the handle excel@sshetenhelm

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Some images  failed to convert PTIFF due to Conversion script. I will reprocess these child images. If not work, we may need replace these images.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Reproceeded the failed images. 16/64 were completed. 48/64 failed due to 137 out of memory error. The size of these images is less than 100MB.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale ready for PROD :)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm https://collections.library.yale.edu/management/batch_processes/8088 It is in prod. Please ignore the failed one, it passed after retry.

**Comment by sshetenhelm** [comment]
Done! Just needs points @MaggieZhaoYale
