### ISSUE TITLE
Migrate Yale Law Directory and Facebook Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2009]
**Story**
Migrate the Yale Law Directory and Facebook Collection (PID 120) from FindIt into DCS.

**Acceptance**

- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the Law admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the Law admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Handle excel was sent to your email. Batch process to UAT is in process. https://collections-uat.library.yale.edu/management/batch_processes/968

**Comment by sshetenhelm** [comment]
Law has indicated they have OCR files for these objects that they will send to us.

Note to self: Ran batch process to limit to Yale Community Only.

**Comment by MaggieZhaoYale** [comment]
@MaggieZhaoYale Thank you, Summer. I would like to move these to PROD first if it is possible, then process OCR files.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale OK to move to PROD before processing OCR :) 

I made a new ticket for the OCR for this collection at #2031 so we can close out this migration ticket and just have the OCR one active

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/c9c0448f-3888-4abd-a6a8-c47c85fdb20b/download](https://app.zenhub.com/files/242185115/c9c0448f-3888-4abd-a6a8-c47c85fdb20b/download) @sshetenhelm The handle is here.

**Comment by sshetenhelm** [comment]
Done! Just needs points :) @MaggieZhaoYale
