### ISSUE TITLE
Preventing jobs from running on redirected Parents

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2010]
#### PDF Jobs
Some `GeneratePdfJob`s are being run on redirected parents:

See:
https://collections.library.yale.edu/management/delayed_job_dashboard/show/15447560 for oid 2018187
https://collections.library.yale.edu/management/delayed_job_dashboard/show/15447567 for oid 2018190

The jobs fail, and are re-queued.  The PDF job should not be attempted on redirected parents.

#### Manifest Jobs
The `GeneratePdfJob` is queued from the `GenerateManifestJob`.
The `GenerateManifestJob` shouldn't be run on redirected parents.

GenerateManifestJobs are queued in a few places.  In this case, it's most likely being queued in `Reassociatable.update_related_parent_objects`.

#### Acceptance:
- [x] Determine if `Reassociatable.update_related_parent_objects` is the only path where manifest jobs are queued for redirected parents. 
- [x] Check for other unnecessary jobs that may be run on redirected parents.
- [x] Prevent the unnecessary jobs from being queued and add defensive code

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/980

**Comment by martinlovell** [comment]
v2.59.23

**Comment by martinlovell** [comment]
Test by reassociating all children to one other parent so the old parent gets redirected.  Check that there are no new failed PDF jobs for the old parent.  (And/Or redirect an existing parent with no children using update parent objects.)

**Comment by motropuk** [comment]
As far as I can tell this is still failing on UAT. I redirected 900099893 and then checked the PDF jobs queue and there were two new failed PDF jobs for this object ![Screen Shot 2022-04-08 at 14.31.20.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/54cb5f16-74f2-43fb-955e-344aa7208a19)
