### ISSUE TITLE
specify the error message for valid_mets

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#2015]
When  mets fails the validation during the Goobi ingest process, a general message "must be a valid METs file" is recorded. Each condition has to be checked one by one for the debugging. 
Hope error message raises on each condition. This will save time on debugging the Goobi ingest issue. 
https://github.com/yalelibrary/yul-dc-management/blob/b9ed6045bb9df9a81bfe81503c416d7786762b2c/app/models/mets_document.rb
Raise error message for each condiion:

- [x] blank rights_statement

- [x] valid_metadata_source_path

- [x] fixture_images_in_production?

- [x] admin_set.present?

- [x] all_images_have_checksum?

**Comment by MaggieZhaoYale** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/981

**Comment by FCRodriguez7** [comment]
Released management v2.59.24
