### ISSUE TITLE
BUG: Fix conditional for archive space base URL

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2016]
In `BlacklightHelper.aspace_link(arg)` the conditional for getting the base URL for archives space is incorrect.

The environment variable is added to the environment as a blank string when there is no value in the parameter store.

Change: 

`base_url = ENV['ARCHIVES_SPACE_BASE_URL'] || "https://archives.yale.edu"`
to 
`base_url = ENV['ARCHIVES_SPACE_BASE_URL'].presense || "https://archives.yale.edu"`

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/830

**Comment by mikeapp** [comment]
v1.60.38
