### ISSUE TITLE
Retrieve OCR files for Yale Law School Oral History Series Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2018]
Yale Law School Oral History Series Collection (PID 98) has OCR files that need to be downloaded and added to their objects for their migration from FindIt to DCS.

See #2005 for migration ticket & comments regarding OCR file issues.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 32 OCR (txt) are missing). Is it possible to get these OCR from law library? Thank you. 
Here is the list of missing ocr:
dig CoId                proj  parentoid  oid
digcoll:4579904, 98, 16330786, 16330846
digcoll:4580073, 98, 16331124, 16331134
digcoll:4580145, 98, 16330971, 16331042
digcoll:4580068, 98, 16331124, 16331126
digcoll:4579919, 98, 16330786, 16330788
digcoll:4579999, 98, 16330847, 16330890
digcoll:4580030, 98, 16330847, 16330891
digcoll:4579961, 98, 16330892, 16330894
digcoll:4580150, 98, 16330971, 16331043
digcoll:4580565, 98, 16331081, 16331083
digcoll:4580571, 98, 16331081, 16331122
digcoll:4580553, 98, 16331081, 16331123
digcoll:4580198, 98, 16331124, 16331189
digcoll:4580242, 98, 16331191, 16331193
digcoll:4580235, 98, 16331191, 16331223
digcoll:4580022, 98, 16330847, 16330849
digcoll:4580154, 98, 16330971, 16330981
digcoll:4579957, 98, 16330892, 16330968
digcoll:4580013, 98, 16330847, 16330857
digcoll:4580033, 98, 16330847, 16330889
digcoll:4579950, 98, 16330892, 16330902
digcoll:4580134, 98, 16330971, 16330973
 digcoll:4580547, 98, 16331081, 16331091
digcoll:4580241, 98, 16331191, 16331222
digcoll:4579589, 98, 16330786, 16330796
digcoll:4579573, 98, 16330786, 16330845
 digcoll:4579580, 98, 16330786, 16330844
 digcoll:4579982, 98, 16330892, 16330969
digcoll:4579936, 98, 16330892, 16330970
digcoll:4580097, 98, 16331044, 16331052
digcoll:4580554, 98, 16331081, 16331121
digcoll:4580204, 98, 16331124, 16331190



![image.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/163f7cca-38f0-43e6-a7a3-7cc25fff9283)

**Comment by MaggieZhaoYale** [comment]
Sure. @sshetenhelm

**Comment by MaggieZhaoYale** [comment]
The full text files were copied to the s3 yul-dc-ocr-prod/fulltext bucket. Fulltext will be batch-processed after collection 98 is ingested into the dcs prod.

**Comment by sshetenhelm** [comment]
Here are comments re: OCR that are being carried over from Oral History Migration Ticket #2005 , which we are closing. 

- MA: Need to run metadata update after updating full text status. (04/13/22)
- MZ: Full text search box (search within item) was displaying but not returning results within searches (04/13/22)
- MA: Possible need to re-save in text editor with UTF-8 encoding or write a script to convert encoding (04/13/22)
- MA: 8 failed jobs in `intensive_solr_index` on PROD with `source sequence is illegal/malformed utf-8` (04/13/22)
- MZ: Txt files are encoding in ISO-8859-1; will write script to convert encoding (04/14/22)
- MZ: created to-uft8.bash and ran the script to convert the files from ISO-8859 to utf-8, then copied to S3 fulltext bucket. Still get: source sequence is illegal/malformed utf-8 /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport- (04/14/22)

**Comment by MaggieZhaoYale** [comment]
Fulltext search of the following objects works
https://collections.library.yale.edu/catalog/16331191
https://collections.library.yale.edu/catalog/16331044
https://collections.library.yale.edu/catalog/16330971
Other 5 did not get any result with fulltext. Refreshed their metadata and to see if works

**Comment by MaggieZhaoYale** [comment]
Full text search did not return results:
https://collections.library.yale.edu/catalog/16331081
https://collections.library.yale.edu/catalog/16331124
https://collections.library.yale.edu/catalog/16330892
https://collections.library.yale.edu/catalog/16330847
https://collections.library.yale.edu/catalog/16330786

**Comment by mikeapp** [comment]
For https://collections.library.yale.edu/catalog/16330892 the timestamp in Solr is `"timestamp":"2022-04-08T17:47:05.675Z`. But the last metadata update is more recent.  So perhaps it is not being indexed properly.

**Comment by MaggieZhaoYale** [comment]
@mikeapp Thank you. This makes sense.

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/management/child_objects/16331100 charset=binary

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/management/child_objects/16331104 unknow-8bit cannot convert

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Fixed the fulltext search for all the parents in this collection.
