### ISSUE TITLE
[CHECK] Sanitize and wrap field values with Links in IIIF Manifest

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2019]
The links in the rights fields display and work in UV and Mirador.  However, they have a class from the original value, and they are not wrapped in a tag.

Allowing the class (or other HTML) in the fields may interfere with the viewers.

IIIF Presentation 3.0 specifications says the value "MUST" start and end with < and >.
IIIF Presentation 3.0 says the clients should remove problematic attributes/tags, but doesn't mention class attributes specifically. (And we can't be sure clients will properly implement this.)

To be safe with our current viewers and to be compliant with Presentation 3.0:
- [ ] Sanitized any metadata and description values that look like they contain HTML.  
- [ ] If there are links remaining after sanitizing, wrap the value in a `<span>` tag.

See:
https://iiif.io/api/presentation/2.0/#descriptive-properties
https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values

**Comment by martinlovell** [comment]
Note: We could sanitize before putting in SOLR/DB when coming from Metadata cloud, but probably shouldn't wrap it in a span there.  We would still need to sanitize it in blacklight since the rights field is editable in management, and it's better to use sanitize instead of making it html_safe without checking.  So, it's probable better to keep it as is in blacklight and also sanitize and wrap when generating the manifest.

**Comment by mikeapp** [comment]
From Unprioriitized, we should look at #2019

**Comment by martinlovell** [comment]
Examples of manifests with non-wrapped HTML: 
https://collections.library.yale.edu/manifests/16626437. (Rights)
https://collections.library.yale.edu/manifests/16032482 (Rights)
https://collections.library.yale.edu/manifests/2026728 (Rights)

Also, I noticed that the rights in the IIIF manifest is being pulled in from the authority data rather than the rights_statement field in the database.
e.g. see rights for https://collections.library.yale.edu/manifests/32182244 vs rights in record: https://collections.library.yale.edu/catalog/32182244
Should right be pulled from the editable field in the DB?

**Comment by martinlovell** [comment]
PR for wrapping and sanitizing: https://github.com/yalelibrary/yul-dc-management/pull/1234   (1234!!)
PR for rights statement: https://github.com/yalelibrary/yul-dc-management/pull/1233

**Comment by jpengst** [comment]
Deployed to Test v2.62.5

**Comment by mikeapp** [comment]
Looks good on test

**Comment by mikeapp** [comment]
Looks good on UAT
