### ISSUE TITLE
Use display coordinates when available

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2020]
**Story**

The coordinate display is showing data that might not make sense to users.   Example: https://collections.library.yale.edu/catalog/15831816

![Screen Shot 2022-04-12 at 2.28.32 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/fb3f6c03-5b44-4710-b2fb-c378694cd4a9)

We are currently using the `coordinate` field from Metadata Cloud.          
`coordinates_ssim: json_to_index["coordinate"],`

But for records that have MARC we should prefer `coordinate_display`

![Screen Shot 2022-04-12 at 2.28.08 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/9af6536c-574c-4f12-90db-5144d7e3bf5b)

**Acceptance**
- [x] Add  `coordinates_display` to the Solr index
- [x] Populate the field with the MC value of `coordinate_display` if present, otherwise use the same value as the  `coordinate` field
- [x] Update Blacklight to display `coordinates_display` in the object result page
- [x] Use this value in the IIIF Manifest metadata display

**Comment by martinlovell** [comment]
Moved  back to team review for Blacklight PR: yalelibrary/yul-dc-blacklight#786

**Comment by martinlovell** [comment]
Released management v2.59.27

**Comment by mikeapp** [comment]
Looks good: https://collections-uat.library.yale.edu/catalog/15811575
