### ISSUE TITLE
Retrieve and Ingest OCR files for Lillian Goldman Law Library Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2021]
Lillian Goldman Law Library Collection (PID 99) has OCR files that need to be downloaded and added to their objects for their migration from FindIt to DCS.

See #2004 for migration ticket.

- [x] Get OCR files from Law
- [ ]  If necessary, run script to convert files to utf-8 (similar to work done in #2005) 
- [x]  Ingest OCR files into DCS
- [x]  Run batch process to update full text status
- [x]  Run metadata update
- [x]  Audit in PROD with stakeholder

**Comment by MaggieZhaoYale** [comment]
Totally 6019 records, missing ocr: 3220

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Would it be easy to generate a list of individual missing OCR files, or would it be best to ask Law if they have ALL the OCR files available in their storage?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm I will re-run the script to get the missing OIDs.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Here is the list of the missing OCR
[https://app.zenhub.com/files/242185115/15a3ef82-602b-4d22-b58a-25f6b8681425/download](https://app.zenhub.com/files/242185115/15a3ef82-602b-4d22-b58a-25f6b8681425/download)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale most of these are the complete OCR files for full books. I can request these from Law.  Also:
- OIDs 16321239, 16327861, and 16328242 are text pages from the middle of an object. I will request these files.
- OID 16736453 we are excluding this record, so we can ignore.
- OIDs 16320356, 16320358, 16320362, 16320424, 16320436, 16320472, 16320474, 16320482, 16320578, 16320608, 16320852, 16320856, 16321391, and 16321392 are just blank pages or covers, so I won't request these files.

The full list of OIDs divided by object is available in this file, if that is helpful. Each object is divided by color. [https://yale.box.com/s/sq7z31xcvlkt550njcylcsvb5x6paxxr](https://yale.box.com/s/sq7z31xcvlkt550njcylcsvb5x6paxxr)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale is it ok to get all OCR files in one directory, or would you prefer the files divided into folders by collection and/or object?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm I would prefer the file divided into folders by collections. Thank you.

**Comment by DraxIndustries79** [comment]
Next week

**Comment by sshetenhelm** [comment]
Received 3204 OCR files from law. They indicated a few we requested are missing, but to move forward anyway. In process of sharing these with Maggie.

**Comment by sshetenhelm** [comment]
Done! Just needs points :)
