### ISSUE TITLE
Preservica sync: create new child objects if new content found in Preservica

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2026]
**Story**

The synchronization process might discover new Content Objects that have been added in Preservica.  In this case the sync process should create a new Child Object in DCS.

**Acceptance**
- [x] Identify new Content Objects that do not have a corresponding Child Object in DCS
- [x] Create a new Child Object for each Content Object.   
- [x] Populate the same URI and checksum fields (etc.?) as would happen during the initial ingest from Preservica
- [x] Import the image binary to the pairtree
- [x] Set order sequentially, replicating order in Preservica will be done in ticket #2025
~~- [ ] Set the Child Object's `order` to match the position in the Preservica object (as in #2025)~~
- [x] Confirm that the subsequent processing (i.e., metadata update, etc.) results in the PTIFF being generated.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/986
