### ISSUE TITLE
Issue with data table column sort for Parent Objects

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2027]
**Story**

Sorting on some columns in the parent objects data table view does not seem to be working as expected. 

For example, if you click the up/down sort arrows on the Digitization Note column, some sorting appears to be happening as the order of objects changes. However, the results at the top of the column are always blank, regardless of which direction you sort in. There are multiple objects in DCS with a digitization note, so expected behavior would be that one of these sort directions would bring back objects where there is data in the digitization note.

Documentation to help with sort order for data tables is available here https://datatables.net/plug-ins/sorting/

**Note:** Check here if there are a combo of blank fields and null value, empty strings, or space affecting this.

**Acceptance**
- [x] Test sort order on all columns in Parent Objects data table to ensure sorting is happening as expected
- [x] Identify problematic columns where sorting is incorrect
- [x] Apply fix for sort order for problematic columns

**Comment by K8Sewell** [comment]
Does not appear to be a sorting issue but a data issue.  Recommended fix would be to write a rake task to go through all parent objects and if a digital object source is not set then set it to 'None' to prevent the loading of nil or empty string values.

**Comment by DraxIndustries79** [comment]
Decided to edit the affected records to "none"

**Comment by K8Sewell** [comment]
@motropuk here are the oids that need their Digital Object Source updated to 'None' and that will resolve the odd sorting behavior seen.

32206209
32193450
2033572
17154486
32301959
15603880

**Comment by K8Sewell** [comment]
Looks good for sorting
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9b464a7e-bf03-4278-8ac8-d7d9b5fe27b3)

**Comment by motropuk** [comment]
Still having problems with this sorting for a number of columns, including digitization note. So maybe we could look at this after standup tomorrow

**Comment by K8Sewell** [comment]
Resolved issue with Digital Object Source but taking this back to 'In Progress' to address issues in the the Digitization Note column.

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1005

**Comment by motropuk** [comment]
Looks good in UAT
