### ISSUE TITLE
PDF: Log Image OID when processing fails

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2028]
**Story**

When a PDF job fails due to an error processing an image, the specific image OID is not available.  Example:
```
 PDF Java app returned non zero response code for 16329203: java.io.IOException: Preprocessing failed: convert -resize 2000x2000 /tmp/d20220413-83-beeogn/pdfPageOriginal4002052291061422033img[0] /tmp/d20220413-83-beeogn/pdfPageConverted17680879049294762820.jpg
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.getBufferedImage(JpegPdfConcatImpl.java:406)
```

**Acceptance**
- [x] In addition to the failed command, the error message should provide the URL of the source image, but without any parameters (this is a security concern due to the use of singed URLs).

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-pdf-gen/pull/15

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/985

**Comment by martinlovell** [comment]
Released management v2.59.27

**Comment by mikeapp** [comment]
Improved error message appears:

![Screen Shot 2022-04-21 at 1.28.51 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/14290145-eaa0-4721-b50d-2b5438e68d21)

**Comment by martinlovell** [comment]
(The errors from convert get repeated because it retries)
