### ISSUE TITLE
Retrieve and ingest OCR for Yale Law Directory and Facebook Collection 

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2031]
**Story**
Yale Law Directory and Facebook Collection (PID 120) has OCR files that need to be retrieved and added to their objects for their migration from FindIt to DCS.

See #2009 for migration ticket.

Law has indicated that OCR files can be added after collection has been moved to PROD. 

**Acceptance**

- [x] Get OCR files from Law
- [ ] If necessary, run script to convert files to utf-8 (similar to work done in #2005)
- [x] Ingest OCR files into DCS
- [x] Run batch process to update full text status
- [x] Run metadata update
- [x] Audit in PROD with stakeholder

**Comment by MaggieZhaoYale** [comment]
2848/5698 ocr files missing.

**Comment by sshetenhelm** [comment]
Received 4,281 OCR files from Law. As per Maggie's comment above, in process of facilitating transfer to Maggie.

**Comment by sshetenhelm** [comment]
Done! Just needs points.
