### ISSUE TITLE
Preservica sync: download new binary if generation or bitstream has changed.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2034]
**Story**

If the Content Object exists in both DCS and Preservica, we need to check whether the object has been changed in any way.

**Acceptance**
When the Content Object URI for the child matches that found in Preservica:
- [x] Check whether the current Generation or Bitstream URIs in Preservica match those in DCS.  

If they do not match, then the object has been updated in Preservica, so sync the object:
- [x] Download the new binary file to the DCS pairtree
- [x] Update the child object Generation URI with the new value from Preservica
- [x] Update the child object Bitstream URI with the new value from Preservica
- [ ] Unset the child object's height and width values.   This should cause the PTIFF to be regenerated when the rest of the metadata update job (and downstream jobs) run.

**Comment by K8Sewell** [comment]
Draft PR up for insight.  https://github.com/yalelibrary/yul-dc-management/pull/992/files  The check I'm using for generation isn't working for bitstream so I am just working out the last few kinks with ensuring a new binary is downloaded to the pair tree and the bitstream check.

**Comment by K8Sewell** [comment]
New binaries are downloading in this updated version of this PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/992

**Comment by martinlovell** [comment]
Released management v2.59.30
