### ISSUE TITLE
Bug: Redirection shows "invalid object" page instead of redirect

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2035]
**Story** 
BRBL wants OIDs to redirect to new OIDs. When users navigate to these OIDs, they receive an "invalid object ID" page instead of getting redirected. We have two instances reported; the first is described below, and links to both instances are in this ticket.

BRBL wants OID 31910118 to redirect to OID 32340978. OID 32340978 looks great in DCS; no errors. When users navigate to OID 31910118, instead of being redirected to OID 32340978, users receive a page that states that they have provided an "invalid object ID." 

BRBL has indicated that they have successfully redirected objects before and after this redirection attempt. 

We have already tried (1) updating the metadata (which failed because redirects remove the bib) and (2) removing the redirect, replacing the bib, updating the metadata, and repeating the redirect. Neither of these worked.

**Relevant links** 
First instance - 
31910118 in MGMT -https://collections.library.yale.edu/management/parent_objects/31910118
31910118 in Blacklight/DCS - https://collections.library.yale.edu/catalog/31910118 
32340978 in MGMT - https://collections.library.yale.edu/management/parent_objects/32340978
32340978 in Blacklight/DCS - https://collections.library.yale.edu/catalog/32340978 

Second instance - 
2057114 in MGMT - 
https://collections.library.yale.edu/management/parent_objects/2057114
2057114 in Blacklight/DCS - 
https://collections.library.yale.edu/catalog/2057114
32191697 in MGMT - 
https://collections.library.yale.edu/management/parent_objects/32191697
32191697 in Blacklight/DCS - 
https://collections.library.yale.edu/catalog/32191697

**Acceptance**
- [ ] OID 31910118 successfully redirects to OID 32340978 on DCS front-end.
- [ ] OID 2057114 successfully redirects to OID 32191697 on DCS front-end.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/993

**Comment by martinlovell** [comment]
Released management v2.59.29
