### ISSUE TITLE
UV4: Test full screen mode across multiple browsers

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2037]
**Story**

UV4: Full screen mode has browser-specific issues.   For instance, on Mac+Safari the viewer does not extend to full height, although it does take the full width of the screen.  See #1987 and comments.

**Acceptance**
Test and document issues with UV4 full-screen display  on:
- [x] Mac/Safari
- [x] Mac/Chrome
- [x] Mac/Firefox
- [x] Windows/Chrome
- [x] Windows/Edge
- [x] Windows/Firefox

**Comment by K8Sewell** [comment]
Mac/Chrome - works as expected
Mac/Firefox - works as expected
Mac/Safari - does not extend vertically
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/c299ca77-393d-4194-a801-98bbaf37c33e)

**Comment by mikeapp** [comment]
UV release 4.0.0-pre.105 includes fix for this and also another issue with menus on mobile.

**Comment by AKFosterDev** [comment]
This work has been completed on related ticket #[1993](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1993)
