### ISSUE TITLE
Preservica: sync from Parent Object page should create entry in Batch Job table.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2038]
**Story**

As an admin user I would like to be able to track the status of a Preservica sync job that I have triggered through the button on the Parent Object web page.

**Acceptance**
For a Preservica sync job initiated from the button on the Parent Object page
- [x] The job should appear in the Batch Process list
- [x] Job status should be reported there

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/991

**Comment by martinlovell** [comment]
Released management v2.59.28
