### ISSUE TITLE
Set cache meta tags on UV3 uv.html page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2041]
**Story**

We want to be sure that users are delivered the new uv.html page when we update to UV4.  

**Acceptance**
- [ ] Set the cache meta tags from #1994 on the main branch `uv.html` page so that users on the system will stop caching the page.

**Comment by AKFosterDev** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/788

## Screenshots

### Before
![Screen Shot 2022-04-26 at 12.24.38 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/b2b260fc-53f3-4032-8f30-ea095a9d6916)

### After
![Screen Shot 2022-04-26 at 1.00.20 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/f26256e5-946b-472b-bfa8-146a531bc316)

**Comment by martinlovell** [comment]
v1.60.19
