### ISSUE TITLE
UV4: Fix full screen mode in Safari

### ISSUE THREAD

**Issue by AKFosterDev** [yalelibrary/YUL-DC#2042]
## Story
Mac+Safari the viewer does not extend to full height, although it does take the full width of the screen.

## Acceptance
- [x] View extends to full height and width when using full screen toggle

## Screenshot
![image.png](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/9d73d20d-5cc2-496d-8f95-9b61c68068a7)

**Comment by mikeapp** [comment]
UV release 4.0.0-pre.105 includes fix for this and also another issue with menus on mobile.

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/791

## Screencast
This is the behavior now before updating to the newest release published this morning. 

https://images.zenhubusercontent.com/242185115/973d77c9-6cf9-402d-b580-9698e32a64fa/screen_recording_2022_04_28_at_10_13_24_am.mp4

**Comment by AKFosterDev** [comment]
PR ready for review - 

## Screencast
This is the behavior now before updating to the newest release published this morning. 

https://images.zenhubusercontent.com/242185115/973d77c9-6cf9-402d-b580-9698e32a64fa/screen_recording_2022_04_28_at_10_13_24_am.mp4

**Comment by AKFosterDev** [comment]
PR ready for review - 

## Screencast
This is the behavior now before updating to the newest release published this morning. 

https://images.zenhubusercontent.com/242185115/973d77c9-6cf9-402d-b580-9698e32a64fa/screen_recording_2022_04_28_at_10_13_24_am.mp4
