### ISSUE TITLE
Link to new management app documentation

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2048]
**Story**

We have new documentation for the management app, that @sshetenhelm created. We need to link to this from the Test, UAT and Prod instances of DCS. 

The documentation is current a Google Doc. In time we will move this into a different documentation solution, but for now we will just link to the Google Doc. 

The documentation is here https://docs.google.com/document/d/1hTc108JDYLYcXy-TG_KJE4A626-ps59XhkKUFGlnaPQ/edit?usp=sharing 

Ideally we would like this link to be accessible regardless of which screen you are on in the management app. Proposed location is: 
![Screen Shot 2022-04-26 at 15.21.10.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/03688ab8-f5bd-476b-9776-25afcd3ef848)

**Acceptance**
-  [x] Jonathan and Tracy to make final decision on placement and any updates to ticket
-  [x] Link to documentation is available from management app

**Comment by motropuk** [comment]
- Use design and location as outlined in image on ticket
- Color of link text should same blue as Digital Library Management Portal text on banner
- Should include an icon to right of User Guide text indicating link opens in new tab
- Make sure link opens in new tab
- Font family for user guide text should be same as Digital Library Management Portal text (Mallory Medium)
- Font size for user guide text should be 16pt or 18pt

@tmacmath would need to review the link in Test once its in place

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1000

Note: Digital Library Management Portal is actually Mallory Light so that font was used for the User Guide.

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/1006

**Comment by motropuk** [comment]
Looks good in UAT but @tmacmath can you also review

**Comment by tmacmath** [comment]
Looks good to me. Thanks!
