### ISSUE TITLE
Solr deprecation warning

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#205]
The Solr image is super chatty. 

Look at, and try to address, some of the warnings, e.g. 
```bash
WARN  (coreLoadExecutor-9-thread-1) [   x:blacklight-core] o.a.s.s.FieldTypePluginLoader TokenizerFactory is using deprecated 6.1.0 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
```

**Comment by mikeapp** [comment]
Perhaps just a one line change?  Here's the equivalent 5->6 issue:
https://github.com/samvera/hyku/issues/636
https://github.com/samvera/hyku/pull/646/files
