### ISSUE TITLE
Reassociated Children Won’t Display in DCS

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2050]
**Story**
BRBL reassociated the children of different parents into one parent, [OID 2005141](https://collections.library.yale.edu/management/parent_objects/2005141). The children show up as being associated with the parent within the Management App. However, the JSON and Solr records are both “null”. 

During the reassociation [batch process 8022](https://collections.library.yale.edu/management/batch_processes/8022/parent_objects/2005141), the user received an error stating: 
“Unable to generate PDF, No authoritative_json to create PDF for 2005141”

In [Blacklight](https://collections.library.yale.edu/catalog/2005141), the first two images load successfully (these images were originally in the parent), but the following 14 images (the reassociated children) do not display. However, it is possible to download the original Ptiff through the Management App and view their correct labels. 

The original metadata source for this object was ladybird; it was updated to [Voyager](https://orbis.library.yale.edu/vwebv/holdingsInfo?bibId=16138021), but the user indicates the linking has not been successful, and the Ladybird information is still visible. The Bib ID is the Management App is different from what is being displayed in Blacklight. 

The catalog record the parent was originally linked to and that is currently displaying in Blacklight has been deleted.

This is currently the only reported case of this issue. We have tried running a metadata update and recreating child oid ptiffs, and neither process has resolved the issue.

**Acceptance**
- [x] All 16 children of parent [OID 2005141](https://collections.library.yale.edu/management/parent_objects/2005141) display successfully in Blacklight
- [x] Catalog record information in Blacklight matches what is currently in Management App

**Comment by martinlovell** [comment]
It's a bad error message.  It should say 'item not found'.

I think the issue is that the item id in management is actually the barcode.
So, moving the item id to the barcode field should fix it.

(I get a response from https://metadata-api.library.yale.edu/metadatacloud/api/ils/barcode/39002136827566?bib=16138021&mediaType=json)

**Comment by sshetenhelm** [comment]
Thank you! I've confirmed with BRBL that that's the barcode. We're now receiving a "Bib and barcode mismatch" error from the Metadata Cloud url, so I've asked BRBL to double-check their numbers.

**Comment by sshetenhelm** [comment]
Works after correcting barcode and recreating child oid ptiffs. Not actually a bug, just user error.
