### ISSUE TITLE
SPIKE: Fix code coverage reporting

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2052]
**Story**

We used to have code coverage metrics provided to us per-PR.   There's no indication there now. 

* The Coveralls site appears to have stopped reporting in early March, see  https://coveralls.io/github/yalelibrary
* The coveralls token in CircleCI seems to be OK
* I think changes were made related to splitting/parallelizing the tests, but don't remember the details.
* If it looks like coveralls.io is not supporting Ruby well, we can look at other solutions (see issue in comment below).  I'm a bit reluctant to add the third-party gem that's not supported by the vendor.

UPDATE: See the CircleCI  builds for more info:

![Screen Shot 2022-04-28 at 2.52.57 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/cfc01f9b-eb3e-4d24-97bb-fe1615374097)

**Acceptance**
- [ ] Determine cause and next steps for reestablishing the integration.

**Comment by mikeapp** [comment]
https://github.com/lemurheavy/coveralls-ruby/issues/163 might be relevant

**Comment by orangewolf** [comment]
ideas - use CircleCI + Simplecov https://rubyyagi.com/merge-simplecov-circleci/
use sonarqube with json formatter https://docs.sonarqube.org/latest/analysis/coverage/

**Comment by mikeapp** [comment]
There is a CircleCI Orb for SonarCloud: https://circleci.com/developer/orbs/orb/sonarsource/sonarcloud to perform the static checks.   I don't see an option for the json formatter in their test coverage documentation though. :(

It might be best to continue to use CircleCI + SimpleCov.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1002

**Comment by K8Sewell** [comment]
PR for blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/810
PR for management - https://github.com/yalelibrary/yul-dc-management/pull/1002
