### ISSUE TITLE
Protect against duplicate full text

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2053]
# Summary
On occasion when loading full text there is duplicate text displayed.  This behavior was reported in a Safari browser but may not be browser dependent.

# Acceptance Criteria
- [x] add javascript to protect against duplicate full text

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/aadf35c0-b77a-4101-b7ee-b73b2c4629c2)

**Comment by AKFosterDev** [comment]
Code for the full text fix is complete. Waiting on PR due to local rspec testing environment errors.

## Screencast
https://images.zenhubusercontent.com/242185115/502f9284-2195-43ac-aee2-b65ae25811f9/show_full_text_fix_chrome.mp4

**Comment by mikeapp** [comment]
@AKFosterDev Did you test this in the 2-page view as well?

**Comment by AKFosterDev** [comment]
I hadn't but I just did and yes, the fix I implemented broke the 2-up full text behavior. I will need to take another crack at it.

**Comment by AKFosterDev** [comment]
Updated PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/795

## Screencast

https://images.zenhubusercontent.com/242185115/50f72818-7946-4d22-b1d3-25e4714aed44/2_up_full_text_fix.mp4

**Comment by mikeapp** [comment]
Looks good.  Don't have a 2-up example on demo but looks good in the video.
