### ISSUE TITLE
UV4: update to latest release with exit fullscreen fix

### ISSUE THREAD

**Issue by AKFosterDev** [yalelibrary/YUL-DC#2054]
**Story**

Update to newest UV release that fixes the fullscreen exit issue from [#2042](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2042) and #[#1987](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1987)

**Acceptance**

- [x] Update universal viewer to newest release v 4.0.0-pre.105
- [x] Update package.json and build
- [x] Test fullscreen exit across browsers

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/793

## Screencast

https://images.zenhubusercontent.com/242185115/3e32d99c-0e7b-4231-b46b-45bd19d734bd/uv4_safari_fullscreen_fix.mp4

**Comment by AKFosterDev** [comment]
There were files that were missing from the original PR made for this ticket. The following PR adds those missing files.

New PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/796

**Comment by mikeapp** [comment]
Looks good!
