### ISSUE TITLE
[Check] Blacklight: fix HTML conformance bugs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2055]
**Story**

Sonarcloud has identified a number of bugs in yul-dc-blacklight related to HTML attributes and elements.  https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=yalelibrary_yul-dc-blacklight

CSS bugs will be addressed in another issue.

**Acceptance**
- [ ] Fix HTML bugs

**Comment by martinlovell** [comment]
There were only a few issues, so added them to the CSS PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/794

There are a couple html fragments with `<li>` wrappers that get used within a `<ul>` which I did not change.  Sonarqube wants the li's wrapped in a ul in the same file, but they can't be.

**Comment by martinlovell** [comment]
One last HTML issue: https://github.com/yalelibrary/yul-dc-blacklight/pull/836

**Comment by MaggieZhaoYale** [comment]
Released blacklight v1.60.45
