### ISSUE TITLE
Management: fix HTML bugs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2057]
**Story**

Sonarcloud has identified a number of bugs in yul-dc-management  related to HTML attributes and elements.  https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=yalelibrary_yul-dc-management

Resolving these issues may help with accessibility.

**Acceptance**
- [x] Fix HTML bugs

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/999

## Note
1. For the "Add a description to this table." issues: It's suggested to use `aria-describedby` if there is an element on the page you can use as the `aria-label`. Using `aria-describedby` requires passing an id for the element being referenced. I decided to use `aria-label` for simplicity and not cluttering the code with ids.  It's my understanding that this work is being done to appease Sonarcloud. If you would like me to refactor to use `aria-describedby`, please let me know.

2. For the "Surround this `<li>` item tag by a `<ul>` or `<ol>` container one." issues - These `li` elements are wrapped in a `ul` element in the app/views/kaminari/_paginator.html.erb file. Can we override these issues in Sonarcloud?

![image](https://user-images.githubusercontent.com/39319859/167004776-43449623-c318-43f1-8759-6cdbc6a910e8.png)

3. For the "Add "lang" and/or "xml:lang" attributes to this "<html>" element" issues - I added both `lang='EN' xml:lang='en'` to most of the files as coverall.

**Comment by mikeapp** [comment]
@AKFosterDev  We can mark issues as resolved in Sonarcloud if they are false positives. If it still complains about the tables after the merge I'll close those.  For the second item, I can close those as well.
