### ISSUE TITLE
Blacklight: adjust links per Sonarcloud feedback

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2058]
**Story**

Sonarcloud has suggested adding `rel="noopener"` to links to external pages found  in `app/views/shared/_footer.html.erb` that open in a new window 

**Acceptance**
- [ ] `rel="noopener"` attribute added to links in the footer that open in a new window

**Comment by mikeapp** [comment]
https://sonarcloud.io/project/security_hotspots?id=yalelibrary_yul-dc-blacklight

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/797

## Note
Adds rel="noopener" attribute to all footer links per Sonarcloud feedback. The ticket said "external" links but Sonarcloud flagged all links within the footer with the exception of the erb link to "Feedback". Please advise if you would like this attribute added here as well.

![image](https://user-images.githubusercontent.com/39319859/166842106-f9d25853-de89-43f4-be21-671972843df9.png)
