### ISSUE TITLE
Add read_access_group_ssim to Solr index

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#206]
The Blacklight Access-Controls gem requires `read_access_group_ssim`, currently only indexing `visibility_ssi`
- [ ] Index `itemPermission` from the Metadata Cloud to `read_access_group_ssim`, in addition to `visibility_ssi` (this is accurate for LadyBird, not positive about other sources)

**Comment by bess** [comment]
Let's hold off on this until we have more clear requirements around visibility metadata.
