### ISSUE TITLE
Additional people to approve deletions in Preservica

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2060]
**Story**

Whenever a file is deleted in Preservica, someone needs to approve the deletion in Preservica before the file disappears. 

Right now only DPS staff can approve these deletions. We need to ask DPS to assign rights to more people to be able to approve deletions for the security tags in Preservica exposed to DCS. 

**Acceptance**
- [x] Identify people who need to be able to approve deletions in Preservica for all security tags exposed to Preservica
- [x] Ask stakeholders for approval for required permissions
- [x] Ask DPS to assign deletion approval rights to identified people
- [x] Each person should test to ensure they can approve the deletion of an object in Preservica

**Comment by motropuk** [comment]
Going to ask DPS to add @sshetenhelm to the list of people who can kick off or approve deletions for all of the security tags in Preservica.

**Comment by motropuk** [comment]
Wrote to stakeholders to ask if anyone has objections to Summer getting the permission she needs to kick off or approve deletions in Preservica. Asked for comments by end of next week Friday June 3

**Comment by motropuk** [comment]
Submitted a ticket to DPS to give summer a data-management role in Preservica for all of the security tags exposed to DCS. Waiting for them to set this up

**Comment by sshetenhelm** [comment]
I have a training set up on 6/17 with D.C. provided permissions are set up by then.

**Comment by sshetenhelm** [comment]
Training with digital preservation complete. Confirmed ability to log in to TEST and PROD instances for both YUL and LAW; practiced deletion process in TEST.
