### ISSUE TITLE
Add alt text to placeholder images for Yale Only items

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2062]
**Story**

The following image is displayed for Yale Only items, when an end user is not logged into DCS or on the Yale Network https://collections.library.yale.edu/assets/placeholder_restricted-0dd5b13a1f754e46c832e1b76fffc59cc0ba0303afacae21bf25a01701ce57a0.png. 

However, there is no alt text for this image ![Screen Shot 2022-05-04 at 11.39.01 AM.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/130deecb-c007-46d9-aeb4-80d7c6168cbc)

As this image includes text, we need alt text to also be available when those images display. 

These images appear in DCS search results https://collections.library.yale.edu/catalog?f%5Bvisibility_ssi%5D%5B%5D=Yale+Community+Only&q=&search_field=all_fields

This alt text should match the text of the image. But see #2071 for how to form the word "log in"

**Acceptance**
- [x] Alt text available for placeholder images for Yale only items

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/800

## Screenshot
![Screen Shot 2022-05-11 at 12.27.33 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/f3f9e396-b44f-4a63-b455-36ae99113a94)![Screen Shot 2022-05-11 at 12.27.33 PM.JPG]
