### ISSUE TITLE
Merge uv4 branch to production

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2065]
**Story**

All work related to UV4 is complete.   We should merge and test in preparation for deployment on Wednesday.

**Acceptance**
- [x] Merge `uv4` to `main` 
- [x] Build new Blacklight version
- [x] Deploy to test and UAT

**Comment by mikeapp** [comment]
I opened the `uv4`->`main` PR so I can't review it.

**Comment by martinlovell** [comment]
In v1.60.21
