### ISSUE TITLE
Migrate Divinity Library Photographs Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2066]
**Story**
Migrate the Divinity Library Photographs Collection (PIDs 18 and 100) from FindIt into DCS.
- Images in FindIt = 17,707
- Collection includes images from PIDs 18 and 100, and one or two from 28
- George O. has identified [16,365 objects with OIDs and digcoll numbers](https://docs.google.com/spreadsheets/d/1eXANSPNgKkRaGM2m_cO5Qo6PxfR5ZKRnUTwGPTLuOHY/edit?usp=sharing) 
- Need to identify 1342 files 

**Acceptance**
- [x]  Export image files from Fedora for digcolls listed
- [x]  Import image files into the DCS pairtree for digcolls listed
- [x]  Import the objects into DCS UAT into the div admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the div admin set
- [ ]  Fix any identified errors
- [x]  Find the missing 1,342 files
- [x]  Import the missing 1,342 files into PROD
- [x]  Fix any identified errors
- [x]  Audit objects in DCS PROD with collection owner
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
There are 196 deleted or inactive object among the list of 16,365 records. [https://app.zenhub.com/files/242185115/8f3f38ae-c36b-4066-b3c3-d899061b598d/download](https://app.zenhub.com/files/242185115/8f3f38ae-c36b-4066-b3c3-d899061b598d/download)

**Comment by MaggieZhaoYale** [comment]
5 failed.
No image in fedora https://collections-uat.library.yale.edu/management/parent_objects/11420795 (in findit https://findit.library.yale.edu/catalog/digcoll:1017245)

4 failed to convert to PTIFF
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12376484
identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Failed to read custom directory at offset 31569060. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: delegate library support not built-in '/data/yul-dc-uat/tmp/c11/c11_divinity/08/84/12/37/64/84/12376484.tif' (XML) @ warning/profile.c/ValidateXMPProfile/1690.
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12375979
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/11425662
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12375974

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Replacement children for parents 12376484, 12375979, and 12375974 available at DCS_MaggieandSummer > Divinity Library Photographs Migration 

I'll have to ask Graziano for parents 11420795 and 11425662

**Comment by sshetenhelm** [comment]
DIV said we can put these in PROD and fix errors there if that's how we'd like to proceed.

**Comment by MaggieZhaoYale** [comment]
90 failed parents in prod. I am checking.

**Comment by MaggieZhaoYale** [comment]
The three images have issues. 900135711.tif TIFF 5768x5470 5768x5470+0+0 8-bit Grayscale Gray 25.5906MiB 0.000u 0:00.035
identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Failed to read custom directory at offset 31569060. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: delegate library support not built-in '900135711.tif' (XML) @ warning/profile.c/ValidateXMPProfile/1690.

All failed in creating ptiff. 

It looks there is a bug in retry. e..g https://collections.library.yale.edu/management/batch_processes/8706/parent_objects/11432913 This is a simple parent, and it suppose to have one image, the initial batch was failed, after a few retries, two children were created.

**Comment by MaggieZhaoYale** [comment]
10 failed in prod:
5 failed.
No image in fedora https://collections-uat.library.yale.edu/management/parent_objects/11420795 (in findit https://findit.library.yale.edu/catalog/digcoll:1017245)

4 failed to convert to PTIFF
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12376484
identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898. identify: Can not read TIFF directory count. TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/540.
identify: Failed to read custom directory at offset 31569060. TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/540. identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898.
identify: delegate library support not built-in '/data/yul-dc-uat/tmp/c11/c11_divinity/08/84/12/37/64/84/12376484.tif' (XML) @ warning/profile.c/ValidateXMPProfile/1690.
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12375979
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/11425662
https://collections-uat.library.yale.edu/management/batch_processes/1034/parent_objects/12375974
https://collections.library.yale.edu/management/batch_processes/8715/parent_objects/12376551  Child Object 32379175 failed to convert PTIFF due to Conversion script exited with error code 137. --- Script exited with status 137 at line 54 Script exited with status 137 at line 58 --- (vips:2865): VIPS-WARNING **: 19:24:56.460: error in tile 0 x 3918 TIFFFillStrip: Read error at scanline 3917; got 3960 bytes, expected 13490 tiff2vips: read error
https://collections.library.yale.edu/management/batch_processes/8715/parent_objects/12376200
https://collections.library.yale.edu/management/batch_processes/8715/parent_objects/11420795
https://collections.library.yale.edu/management/parent_objects/11427222

.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Totally 17707 in prod
Totally 11 failed. 
- https://collections.library.yale.edu/management/batch_processes/8736 1520 in prod
1 failed, not able to get metadata from the ladybird:
16718776 is in findit, but not found in ladybird  https://collections.library.yale.edu/management/batch_processes/8736/parent_objects/16718776 https://ladybird.library.yale.edu/object_overview.aspx?qoid=16718776
https://findit.library.yale.edu/catalog/digcoll:4696473

- https://collections.library.yale.edu/management/batch_processes/8737 13 in prod

-  https://collections.library.yale.edu/management/batch_processes/8706 9999 in prod 10 failed. please ignore 16 in the batch. 6 were fixed. See above message for the 10 failed. 
- https://collections.library.yale.edu/management/batch_processes/8707 5842 in prod
- https://collections.library.yale.edu/management/batch_processes/8708 331 in prod

**Comment by sshetenhelm** [comment]
WOOOO THANK YOU @MaggieZhaoYale ! 17707 in FINDIT and PROD MGMT! 

For 12376484, 12375979, and 12375974, were those with the replacement files we received from Div last week?

For 11420795, we have the replacement child in our shared DCS_MaggieandSummer > Divinity Library Photographs Migration folder. 

For 11425662, we received a file from DIV, but it is damaged, so I need to request a new file.

I will look into the other issues.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Thank you
For 12376484, 12375979, and 12375974, were those with the replacement files we received from Div last week? yes, but unfortunately, these images could not be converted into PTIFF, identify: Bogus "StripByteCounts" field, ignoring and calculating from imagelength. TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/898. identify: Can not read TIFF directory count. TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/540.
I will replace 11420795

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Here is the handle excel
[https://app.zenhub.com/files/242185115/3721d841-e133-43e7-9412-e73b4c3f2e71/download](https://app.zenhub.com/files/242185115/3721d841-e133-43e7-9412-e73b4c3f2e71/download)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale 
I have requested replacement files for the following:
11425662, 11427222, 12375974, 12375979, 12376484, 12376542 and 12376551

These 2879 parents from PID 18 have 0 children in PROD DCS: [](url)[Uploading... DivinityPhotos_PID18_NoChildrenPROD.csv]

These 300 parents from PID 100 have 0 children in PROD DCS: [Uploading... DivinityPhotos_PID100_NoChildrenPROD.csv]

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The batch has 0 child in the each parent. I will re-process this one.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm reprocessed 5842 objects, except  14536895 failed to converted to ptiff, the others were completed. https://collections.library.yale.edu/management/batch_processes/8794

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale I have replacement files for parents 11427222, 12375979, 12376484, 12376542 and 12376551
They are in DCS_MaggieandSummer > Divinity Library Photographs Migration > NEW

DIV said their files for 11425662 and 12375974 are corrupted and will need to be reshot. 

I think that might be all of the problem images?

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Replacements for 11425662 and 12375974 have been added to other parents in DCS_MaggieandSummer > Divinity Library Photographs Migration > NEW

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm re-processed the images https://collections.library.yale.edu/management/batch_processes/8873
11427222 is not in the folder /NEW, 14536895 is in the folder, but not in the list you mentioned below: 
quote your comment: @MaggieZhaoYale I have replacement files for parents 11427222, 12375979, 12376484, 12376542 and 12376551
They are in DCS_MaggieandSummer > Divinity Library Photographs Migration > NEW

DIV said their files for 11425662 and 12375974 are corrupted and will need to be reshot.

**Comment by sshetenhelm** [comment]
12,878 visible in Blacklight for PID 18
4,826 visible in Blacklight for PID 100

Total of 17,704 visible in Blacklight

16718776, 0 children in MGMT, is a duplicate of 16729314, which is active in DCS/Blacklight. This was duplicated in FindIt, so we can take it out of the total and delete this 776 parent OID.

Accounts for 17,705 images

I can't find 2.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Could we please import the following (final!!!!) two children in PROD MGMT? They are in both ladybird and FindIt

12377800 - PID 18
17095189 - PID 100

**Comment by motropuk** [comment]
Looks good in Prod! Congrats @sshetenhelm and @MaggieZhaoYale and thanks. This was a HUGE amount of work
