### ISSUE TITLE
Test ASpace digital object linking

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2067]
**Story**

We need to test ASpace digital object linking and updates after the feature is turned on. 

**Acceptance**
- [x] Coordinate testing with Mark and others
- [ ] Testing
- [ ] Identify Issues
- [ ] Resolve Issues
- [ ] Test again
- [ ] Stakeholder signoff

**Comment by sshetenhelm** [comment]
Mark has already started testing. Confirming that all objects we've tried so far are showing up in the Metadata Cloud JSON, so that's good! 

Meeting with Mark this afternoon to talk further testing/how it's going.

**Comment by martinlovell** [comment]
Bob updated the config so that the file-urls in the digital objects will point to production.  We also updated the code so that it defaults to production.  I scheduled a metadata cloud deploy for next Wednesday: (5/18)

**Comment by sshetenhelm** [comment]
Mark turned off permissions temporarily to make sure nothing is publishing to PROD ASpace.

**Comment by sshetenhelm** [comment]
Still testing, delayed jobs in UAT slowing some things down.

**Comment by sshetenhelm** [comment]
Meeting with M.C. tomorrow @10:30 to discuss his experiences.

**Comment by sshetenhelm** [comment]
Testing has been taking place in UAT. Some feedback: 

- When you delete a parent in the Management App, the digital object in ASPACE wants to delete but is failing; ASpace won’t let it delete. See below for error recorded in JSON file: 
![ASpace_Object_Deletion_Error.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/4ca933d8-2e65-4d26-8b80-b440612ff12a)

Mark C. mentioned that Lyrasis recently changed something that blocked database access; he will look into this to see if he needs to make changed on his side. 

-  When a record is unpublished in ArchivesSpace, it does not make Private or delete the object in Blacklight/Management; the object is disconnected from the metadata record, but remains visible in Blacklight with the previous metadata. 

When a record is deleted in ArchivesSpace, we would like the corresponding parent in Management to have its visibility changed to Private. 

Example Parent 10014129 in UAT [Blacklight](https://collections-uat.library.yale.edu/catalog/10014129)
Example Parent 10014129 in [Test ("UAT") ArchivesSpace](https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/781638?_ga=2.14261687.127531703.1653595396-738509661.1643218753)
Example Parent 10014129 in [UAT Management](https://collections-uat.library.yale.edu/management/parent_objects/10014129) 

Clicking on Metadata Cloud link in MGMT returns a message that the ArchivesSpace record is unpublished. 
- - -

Testing is still ongoing; still need to test objects that have been redirected.

**Comment by martinlovell** [comment]
The use_statement change has been deployed:
The file_version for the DCS html page has "text-html" as the use_statement now.

**Comment by sshetenhelm** [comment]
Created tickets for issues reported -- 

#2117 - [ASpace Linking] Make DCS Parent Private when object is deleted or unpublished

#2118 - [ASpace Linking] Changing to 'Yale Community Only' Breaks Image in ASpace

#2119 - [ASpace Linking] Making DCS Object 'Private' Does Not Remove Link in Aspace

**Comment by fordmadox** [comment]
Martin, I've just updated all instances of our ASpace to use "text-html" as
the value instead of "text/html". So, things should be good to go now.
Sorry I didn't do that last week.
