### ISSUE TITLE
Refactor Docker image build process to simplify build process

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#207]
**ISSUE**
Our Docker image build process had gone through a few technical hand-offs and has a few gotcha's and places it could be clarified and sped up.

We'd like an image workflow that's easy for the whole team to understand and use.

**ACCEPTANCE**
- [x] Distinctions between base builds and working builds are well commented and understood by multiple team members
- [x] The process to trigger base and working builds is automated
- [x] The process to push base builds to docker hub is automated
- [x] The process to push final builds to DockerHub is automated
    - [x] images on DockerHub are tagged with the corresponding git SHA
- [x] [BONUS] DockerHub images corresponding to a release on GitHub are tagged on DockerHub with their release version.

**Comment by orangewolf** [comment]
Proposal

- Consolidate Dockerfiles down to single file with multi-stage build (https://docs.docker.com/develop/develop-images/multistage-build/)
- Document build and release of new base process as a manual process including incrementing the upstream label and the created label.  (I'm not sure what automating this would look like other than maybe as a git tagging exercise?, open to ideas here)

- Document in README that devs only need to build when Gemfile, Dockerfile or ops directory content change, no other code changes should necessitate needing to build the image. Document a "pull" first mentality where master is the primarily pulled docker tag.

- On any feature branch build the image and create a tag that matches the git sha of that commit when the image is built
- When the tests pass, retag that sha to be the branch name (?)
- When a release is is tagged in Github, retag the docker image corrisponding to that sha to have that release

Bonus:
- Expire sha based tags after 2 weeks, but keep release tag based shas

**Comment by maxkadel** [comment]
Proposal - I like it a lot.
Point 1. Yes, please.
Point 2. Yes, please. Possibly also limit who can push to the tagged "release" versions of the base stage? I don't generally like to do that, but right now it feels a little fragile.
Point 3. Yes. I've updated the management README some but I think it could use further refinement.
Points 4 & 5. I like this refinement.
Point 6. I'd like that, but am not sure how to automate it. I know the Github Workflows will do it, but I think it's preferable not to split tagging between CircleCI and Github Workflows?
Bonus. That would be awesome. I know I don't have the level of access to the Dockerhub repo to set that up, I don't know whether the CI user does.

**Comment by orangewolf** [comment]
@mark-dce I'm requesting that the Hub cleanup be broken out in to its own story. The scope got a little big on this one and I've done enough research to know there is not a "just grab this tool it handles it". We'll likely need to use the Docker Hub API to build a little utility to do the clean up. Maybe 1/2 days more work, but more than this little 2 estimate can hold.
