### ISSUE TITLE
Replace "Login" with "Log in"

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2071]
**Story**

Change all uses of the term "Login" or Sign in to "Log in" across DCS blacklight

- Sign in on header
![Screen Shot 2022-05-09 at 15.24.07.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/feed6849-2d77-4cb7-886a-c5b2bcf53a21)

- Update image for Yale Community Only placeholder image in search results
![Screen Shot 2022-05-09 at 15.26.31.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/0af94b30-56ef-4504-b41c-ed2e73405dd1)

- Text on Yale Community Only object page
![Screen Shot 2022-05-09 at 15.27.40.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/652bd768-6677-44bb-b7a2-0afa6aa81764) 

**Acceptance**
- [x] "Sign in" text on header changed to "Log in"
- [x] New Yale Community Only placeholder image created with "Log in" instead if "Login
- [x] Updated text on Yale Community Only object page should read "Please log in using your Yale NetID or contact library staff to inquire about access to a physical copy."

**Comment by DraxIndustries79** [comment]
@AKFosterDev we think @FCRodriguez7 has the right image.

**Comment by AKFosterDev** [comment]
Code complete. Draft [PR](https://github.com/yalelibrary/yul-dc-blacklight/pull/802) in progress

Waiting to get updated png from Frederick tomorrow to finalize PR.

Wondering if we want to add another ticket for the Logout & Sign out instances.

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/802

Removed old placeholder image and replaced with updated image.

## Screenshot
![image.png](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/e494ce31-f0de-47d9-8df9-d465b7c4436f)

**Comment by motropuk** [comment]
Looks good on UAT
