### ISSUE TITLE
Add preservica_representation_type column to create parents batch process template

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2072]
**Story**

We need to add preservica_representation_type as a column in the .csv template for the Create Parent Object batch job. Acceptable values for this column will be "Preservation" or "Access"

**Acceptance**
- [x] preservica_representation_type available on Create Parent Object .csv template

**Comment by motropuk** [comment]
Moving to on hold as DPS are suggestion a different field for identifying the representation where the value would be consistent

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1013

**Comment by K8Sewell** [comment]
deployed to test - [v2.59.37](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.37)

**Comment by motropuk** [comment]
Looks good on UAT
