### ISSUE TITLE
M1 Blacklight/Management Resolve Selenium Crash

### ISSUE THREAD

**Issue by AKFosterDev** [yalelibrary/YUL-DC#2073]
## Error message
![image.png](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/2fabfe5c-0b29-4180-980e-43218cd5e365)

Resolve Selenium webdriver error when running specs.

## Acceptance Criteria
- [ ] Working specs

**Comment by AKFosterDev** [comment]
## Update
This is an issue we are experiencing on a few of our other projects at Software Services by Scientist.com.

**Comment by K8Sewell** [comment]
Need access to be able to test experimental base image 
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/f21aa46a-2512-4685-b675-ab6a353166eb)

**Comment by DraxIndustries79** [comment]
Kait and Amanda need docker hub access; sending ID's to Mike to add.

**Comment by mikeapp** [comment]
I tried launching the Selenium arm-based image and configuring based on instructions on the Selenium site and https://thurlow.io/ruby/2020/11/06/remote-selenium-webdriver-servers-with-rails-capybara-and-rspec.html    I got communication working to the Selenium server but I'm not sure that communication back to the Rails server was successful.  In any event, I created a ticket to bump Rspec and Capybara with the thought that this should also bring in the latest Selenium driver, in case that is the issue.

**Comment by AKFosterDev** [comment]
PR for Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/833
PR for Management - https://github.com/yalelibrary/yul-dc-management/pull/1062

**Comment by mikeapp** [comment]
@AKFosterDev I've merged these.  Running management locally I get an error, can you try to reproduce it?

`rspec spec/system/user_spec.rb:76` results in 
`Capybara::ElementNotFound: Unable to find css "#user_email"`

But perhaps its something in my test environment...

**Comment by AKFosterDev** [comment]
@mikeapp I'm getting the same failing spec locally. Capybara is treating the (#user_email) as an id but there is no such id on the p tag in the view. I think it's strange that it passed on circleci but not locally. Is that the only spec that is failing locally for you?

**Comment by mikeapp** [comment]
I think this was the only failure.

**Comment by K8Sewell** [comment]
Released to UAT with:
- management - [v2.59.61](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.61)
- blacklight - [v1.60.41](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.41)
