### ISSUE TITLE
API calls to Preservica should only pull in .tif files

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2074]
**Story**

During testing for #2039, when running the Create Parents batch process for an object in Preservica (using structure 2), the batch failed as one of the children returned from Preservica could not be converted to PTIFF https://collections-uat.library.yale.edu/management/batch_processes/1012/parent_objects/900126499 

When exploring the child that failed to convert, https://collections-uat.library.yale.edu/management/batch_processes/1012/parent_objects/900126499/child_objects/900126580, it was discovered that there was a thumbs.db file at the end of the sequence of content objects for this asset in Preservica
![Screen Shot 2022-05-10 at 13.16.38.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/c7f7df13-172c-41e7-9d73-e4d6e0bb3d4b)

DCS appears to have picked up this file as part of the call to Preservica. When DCS finds content objects in Preservica that are not .tif files, it should ignore these, and not pull them over to DCS

A good object to use to test this is "b3ffec3c-bb42-4a72-90ee-3f38bc364f02" as this is the one with the thumbs.db included. 

**Acceptance**
- [x] Create parents batch job for "b3ffec3c-bb42-4a72-90ee-3f38bc364f02" in Preservica completes without error

**Comment by martinlovell** [comment]
I'm working on filtering based on the bitstream filename ending with "tif" or "tiff".

Generations also have a formatName: `Tagged Image File Format`.

We could filter on formatName in the generation, but I think it would still require finding the bitstream by filename too. Based on the XML, it seems like it's possible for a generation to have multiple formats, and it's not clear if there's an indication of which bitstream matches which format.

It may be necessary to first filter based on the generation containing a `Tagged Image File Format`.  If it does, then getting the first bitstream with a "tif" extension.

Currently, we always get the first bitstream from the generation and assume it's a tif.

Question: Do we need to cover the case when one Generation has multiple formats and bitstreams, where we need to find the bitstream that has the tif format?  @motropuk   

(That structure might be used when there is text and an image together in one generation.)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1004

**Comment by motropuk** [comment]
Processed fine and only brought in TIF images. So all set
