### ISSUE TITLE
PDF Colors Wrong

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2075]
For parents [16201231](https://collections.library.yale.edu/catalog/16201231) and [16196483](https://collections.library.yale.edu/catalog/16196483), which previously had PDF generation errors, the PDF is now generating after re-indexing the objects, but the colors in the PDF for some children are different than the colors in the tif files. 

The images in the PDF should be identical to the images displaying in Blacklight. 

- For parent 16201231, this is specifically affecting children 12 and 13.
- For parent 16196483, this is specifically affecting children 1, 12, and 13.
- All of the affected children previously were not displaying in Blacklight but are displaying now after running a recreate child OID ptiff batch process. Re-indexing the objects and recreating the ptiffs do not correct the pdf error.

**Comment by martinlovell** [comment]
- [ ] Double check that the color space on the ptiffs that have color problems are related to the color space conversion the PDF generator uses.
- [ ] Remove color space conversion from PDF generator, and verify that the PDF generator will fail on those images in this case.
- [ ] Delete any PDFs that have color problems (maybe)
- [ ] Document info on the color space for the PTIFFs that have the issue

**Comment by martinlovell** [comment]
Image with issue has CMYK color space on largest of PTIFF images, which is the one we use for PDFs:
```
identify 16222931.tif 
16222931.tif[0] TIFF 4037x3290 4037x3290+0+0 8-bit CMYK 20.6723MiB 0.010u 0:00.059
16222931.tif[1] TIFF 2018x1645 2018x1645+0+0 8-bit sRGB 0.010u 0:00.040
16222931.tif[2] TIFF 1009x822 1009x822+0+0 8-bit sRGB 0.000u 0:00.019
16222931.tif[3] TIFF 504x411 504x411+0+0 8-bit sRGB 0.000u 0:00.009
16222931.tif[4] TIFF 252x205 252x205+0+0 8-bit sRGB 0.000u 0:00.000
16222931.tif[5] TIFF 126x102 126x102+0+0 8-bit sRGB 0.000u 0:00.000
```

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1003

**Comment by mikeapp** [comment]
These now seem to fail instead of look wrong:
```
Caused by: javax.imageio.IIOException: Unsupported Image Type at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1139) at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110) at 
```
