### ISSUE TITLE
UV4: security issue when embedding in a different site

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2077]
**Story**

Mark Custer has said that there are issues with embedding UV4 in another site.  The issue has to do with cross-origin access from DCS to the ASpace site.  See the JS console when viewing https://puitestarchivesspace.library.yale.edu/repositories/11/archival_objects/3411283

**Update:** There's an `embedded` configuration that prevents the check of the parent window.  See the `uv.html` at https://codesandbox.io/s/uv-config-example-7kh4s?file=/uv.html:845-1052 :

```
<script type="text/javascript">
      var urlAdaptor = new UV.URLAdaptor(true);

      const data = urlAdaptor.getInitialData({
        embedded: true
      });

      uv = UV.init("uv", data);
    </script>
```

Relevant code in UV4 in `BaseExtension.ts`:
```
getShareUrl(): string | null {
    // If not embedded on an external domain (this causes CORS errors when fetching parent url)
    if (!this.data.embedded) {
```

Also, in `uv.html`: `$UV_Iframe.contentDocument.location.reload(true)` the value of `contentDocument` should be `null` if not sameorigin, so there should be a check for that.

**Acceptance**
- [x] Add the `embedded: true` config param
- [x] Deploy feature branch to UAT and check that the embed works correctly in test ASpace
- [x] Check for null from `contentDocument` in `uv.html`

**Comment by ucancallmealicia** [comment]
Example of embedded IIIF in ArchivesSpace prod: https://archives.yale.edu/repositories/11/archival_objects/2676962

**Comment by mikeapp** [comment]
I edited the ASpace test page and changed the iframe src to another, minimal instance of the UV hosted on another site - same error.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/801

It looks like it's working on test aspace:
https://puitestarchivesspace.library.yale.edu/repositories/11/archival_objects/3411293

(I do see a stacktrace in the java console when exiting full screen, but I see the same issue on production with V3.  It doesn't seem related to `$UV_Iframe`)

**Comment by mikeapp** [comment]
Looks good!
