### ISSUE TITLE
Change name of Sync with Preservica batch job

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2078]
**Story**

Rename the existing "Sync with Preservica" batch job to "Resync with Preservica". 

It might be misleading to some stakeholders who think you need to use the sync with Preservica job to create the initial parent jobs in DCS. 

**Acceptance**
- [x] Sync with Preservica batch job renamed to Resync with Preservica 
- [x] Rename csv template

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1010

## Screenshot
![Screen Shot 2022-05-17 at 3.39.19 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/5b862f16-ee5b-450c-995b-9f55a9d58fe4)

**Comment by motropuk** [comment]
Name looks good on UAT. However, if you click on the download template link now, nothing happens. This worked previously, so wonder if this work somehow impacted the template link?

**Comment by AKFosterDev** [comment]
Changed name of csv template.

PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1014

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1015

## Screenshot
![Screen Shot 2022-05-23 at 11.45.54 AM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/4255c138-a821-4ddc-b594-e7ca6c549d2b)

**Comment by motropuk** [comment]
Looks good on UAT and template downloads
