### ISSUE TITLE
Modify Preservica API call to use Representation Type

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2079]
**Story**

Our current calls from DCS to Preservica use the Representation Name attribute to identify the correct Representation to pull in. However, the values in this attribute are not consistent across Preservica as they are assigned when SIPs are created and can be adjusted to whatever the user wants. 

However, the Type attribute, which is system assigned rather that user assigned, is much more consistent. Values in this attribute will be either "Preservation" or "Access". We should therefore use this attribute to identify the Representation we want to pull in. When using the Create parents job, users will be able to add either Preservation or Access to the preservica_representation_type column. See #2072 for an additional task needed to support this. 

As Preservica can have more than one Representation for both Preservation and Access, the call will also need to select the last appended to the stated type. One solution would be to parse the full XML for the Preservica object, iterate through all the representations with Preservation or Access type (depending which is stated in the batch process template) and then take the last one. 

**Note:**  Replace Name with Type.

**Acceptance**
- [x] Call to Preservica uses Representation Type to identify which representation to pull onto DCS
- [x] Run create parents job, adding preservica_representation_type manually to template and ensure parent is successfully created

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1012

**Comment by K8Sewell** [comment]
deployed to test - [v2.59.37](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.37)

**Comment by motropuk** [comment]
Checks out on UAT
