### ISSUE TITLE
Remove formattedLocales in uv.html

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2081]
There's some code in uv.html related to `formattedLocales`.
It doesn't seem like `formattedLocales` is used in V4 setup, so it's probably not needed.

- [ ] Verify that `formattedLocales` is not needed.
- [ ] Remove code that creates `formattedLocales` if it's not needed.

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.46](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.46)
