### ISSUE TITLE
[DISCUSS] Back up files during  file replacement 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2084]
**Topic**

All environments share the same "original image" storage on Storage at Yale.  With Preservica we are introducing the idea of modifying those files directly.    Up until now, we haven't deleted any of these files after import.   How do we want to handle this in a way that won't allow accidental deletions or cross-environment impacts.

**Comment by K8Sewell** [comment]
Discuss 11/10, Thursday
