### ISSUE TITLE
OCR Files for Yale Law Yearbooks (PID 119)

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2085]
**Story**
Yale Law Yearbooks (PID 119) has OCR files that need to be added to their objects for their migration from FindIt to DCS.

See #2007 for closed migration ticket.

**Acceptance**
- [x] Get OCR files from Law
- [ ] If necessary, run script to convert files to uff-8 (similar work done in #2005)
- [x] Ingest OCR files into DCS
- [x] Run batch process to update full text status
- [x] Run metadata update
- [x] Audit in PROD with stakeholder

**Comment by MaggieZhaoYale** [comment]
NO ocr was found in Fedora.

**Comment by sshetenhelm** [comment]
Requested files from Law.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale OCR files for all parents EXCEPT 17332082 are in DCS_MaggieandSummer > Law Yearbooks OCR.
Files are in folders by parent and named with child OIDs.

Parent 17332082 has only 8 children in Ladybird, FindIt, and DCS, but we received 202 OCR files. Asking Law how many children should be here.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Updated the fulltext/metedata https://collections.library.yale.edu/management/batch_processes/8803

**Comment by sshetenhelm** [comment]
Looks good! Created new ticket for missing children on one parent at #2113

@MaggieZhaoYale just needs points :)
