### ISSUE TITLE
IIIF navDate

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2086]
**Story**

IIIF defines a `navDate` property ( https://iiif.io/api/presentation/3.0/#navdate ).  It is "[a] date that clients may use for navigation purposes when presenting the resource to the user in a date-based user interface, such as a calendar or timeline."

**Acceptance**
- [x] If `year_isim` contains a single year value, construct a `navDate` using the year, for example: ` "navDate": "2010-01-01T00:00:00Z" `

**Comment by mikeapp** [comment]
What does `structuredDate` look like if we know the month, or month and day?  Examples I have found only contain the year.

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1016

**Comment by mikeapp** [comment]
We'll hold this until next Weds.

**Comment by mikeapp** [comment]
IIIF prefers the `Z` indicator for the timezone offset, instead of `+00:00`.   The spec seems to be checking for this, but actually it doesn't, see these comparisons:

```
irb(main):002:0> DateTime.new(2011) == '2011-01-01T00:00:00'
=> true
irb(main):003:0> DateTime.new(2011) == '2011-01-01T00:00:00Z'
=> true
irb(main):004:0> DateTime.new(2011) == '2011-01-01T00:00:00+00:00'
=> true
```

You can force the `Z` by explicitly converting to UTC, and I'd suggest converting to a string when you insert the value into the manifest structure:
````
DateTime.new(2011).utc.iso8601
=> "2011-01-01T00:00:00Z"
```

**Comment by mikeapp** [comment]
in local testing I also get `"navDate":null` from  OID 2005512 / "The gold pen used by Lincoln to sign the Emancipation Proclamation in the Executive Mansion, Washington, D.C., 1863 Jan 1'

**Comment by K8Sewell** [comment]
No problem, will convert to a string in utc.  For OID 2005512 there is no dateStructured value in the fixture data so I confirmed we'd get null  in the case it was empty.  Is there something else it should be?

**Comment by K8Sewell** [comment]
PR should be through CI any minute - https://github.com/yalelibrary/yul-dc-management/pull/1016

**Comment by mikeapp** [comment]
Sorry, I should have paid closer attention there.  Per the spec the `navDate` must be a string representation of a date, so `null` is not allowed.  I'll make the change.
