### ISSUE TITLE
[SPIKE] Prepare for infrastructure and architecture teach out (8/5)

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2087]
**SPIKE**

We'd like to have a teach out on infrastructure and architecture for DCS.   Ideally we'd have at least one person from DevOps and one from Engineering collaborating on this.

The presentation would help us anticipate work required to meet our FY23 development objectives.

**Acceptance**'
- [ ] Slide deck

**Comment by DraxIndustries79** [comment]
We need a collaborator from Devops

**Comment by K8Sewell** [comment]
Slide deck link - https://docs.google.com/presentation/d/1Q_mnOyP3i3SDb0fnvK5kQ8yzo5f_b5QqLv9lyCPq5k8/edit?usp=sharing

Could use help from Dev Ops just to make sure it all looks alright.

**Comment by DraxIndustries79** [comment]
Adding Keith to this to review, but giving him some breathing room after being out for 3 weeks.  Check in Monday 6/27.

**Comment by K8Sewell** [comment]
Keith and I had a chance to review the deck and it's ready to present.

**Comment by DraxIndustries79** [comment]
Find a time week of 8/1 (not 8/2) and record it.

**Comment by DraxIndustries79** [comment]
Friday 8/5
