### ISSUE TITLE
Change Sign Out to Log Out

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2089]
**Story**

Follow on ticket from #2071

We need to change Sign out (which appears in DCS when a user is Logged in) to Log out

![Screen Shot 2022-05-16 at 14.53.49.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/d972b22f-8133-4910-8e40-543a00fa8d62)

**Acceptance**
- [ ] When logged in, a user sees the option to Log out next to their username, instead of Sign out

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/804

## Screenshot
![Screen Shot 2022-05-17 at 1.13.54 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/80b65b17-3ad3-4170-9ee3-61913239fc73)

**Comment by motropuk** [comment]
Looks good on UAT
