### ISSUE TITLE
Refresh preservica token and re-login when necessary

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2090]
Story: As a management user, I do not want jobs to fail due to a Preservica authentication errors.

Credentials are failing during child creation in some cases: see batch process 1039 in UAT.  
This may happen during image downloads, since the same PreservicaClient/token is used for all Bitstreams.

- [ ] Refresh preservica token for PreservicaClients that are active for a long period of time in PreservicaClient.  (Login response contains "validFor", which may be the number of minutes the token is valid for.  The value is 15, so the token may be valid for 15 minutes.)

- [ ] Re-login when refresh fails.  (Tokens may still expire before refresh is possible during large image downloads, so it's possible that the token expires before refresh is called.)

**Comment by martinlovell** [comment]
Bug confirmed and submitted to Preservice.  Work-around in this PR:

https://github.com/yalelibrary/yul-dc-management/pull/1011

**Comment by martinlovell** [comment]
(I forgot to take the PR out of draft.  It's updated now.)

**Comment by motropuk** [comment]
@ucancallmealicia to test this
