### ISSUE TITLE
Remove Update Metadata button from Parent Objects page in MGMT

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2091]
**Story**

Metadata should be updated on a collection-by-collection basis. The 'Update Metadata' button on the Parent Objects page of the Management App updates all metadata in DCS. We should remove this button to prevent users from updating all DCS metadata at once time.

**Acceptance**

- [x] Remove the 'Update Metadata' button from the Management App

![UpdateMetadataButton.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/6975ca0b-0041-44e0-bdb6-d1958dbf4886)

**Comment by motropuk** [comment]
Looks good on UAT
