### ISSUE TITLE
Investigate UV failure

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2094]
**Story**

Release v1.60.23 had issue with UV4 full text search that forced us to roll back the production deployment.   The problem was resolved by using UV version `4.0.0-pre.105` instead of `4.0.0-pre.107`

It's not clear why `4.0.0-pre.107` failed though.   We want to be sure that we can upgrade the UV version in the future, so we should determine a cause or at least assemble enough information to file a bug report for UV.

**Acceptance**
- [ ] Investigate the error with full text search in the v1.60.23 build
- [ ] Fix or file a bug report

**Comment by AKFosterDev** [comment]
It appears the only change from 4.0.0-pre.105 to 4.0.0-pre.107 was the addition of manifesto.js. 
![Screen Shot 2022-05-25 at 10.29.59 AM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/73c37e52-ba37-4209-944f-714cf39497bc)

**Comment by mikeapp** [comment]
Deploying v1.60.23 to demo

**Comment by mikeapp** [comment]
Trying a new build from main updated with the latest version of UV.

**Comment by mikeapp** [comment]
Version `4.0.0-pre.108` full text search appears to work.  Deployed branch `uv4diagnostic` to demo:

![Screen Shot 2022-06-03 at 2.16.34 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d8f68218-4e58-4e09-9381-894746dc50d9
)

**Comment by AKFosterDev** [comment]
Looks good on Mac - Safari, Chrome and Firefox.
