### ISSUE TITLE
SPIKE: Search: autosuggest service slow

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2095]
**Story**

The autosuggest service has slowed considerably, it takes more than 5 seconds to return a result list in UV.   This is likely due to Solr.   See https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1036 and earlier tickets,

It seems like we need to improve performance or disable the feature.

**Acceptance**
- [ ] Check SOLR core setup vs. Max's last ticket
- [ ] Determine how to improve response times

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/blob/main/app/controllers/catalog_controller.rb#L623

**Comment by DraxIndustries79** [comment]
From Rob, Blacklight is known for slow autosuggest.  We could check in with the community re: any solutions, or potentially other organizations who are utilizing it.

**Comment by mikeapp** [comment]
I wonder whether we can switch the code above to a filter query.   This may be faster and more cacheable.

**Comment by mikeapp** [comment]
v2.59.45
