### ISSUE TITLE
UV4: testing

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2096]
**Story**

Repeat tests from https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1993

Paged, LTR:  https://collections-uat.library.yale.edu/catalog/16712418
Paged, RTL: https://collections-uat.library.yale.edu/catalog/16876304
Full text: https://collections-uat.library.yale.edu/catalog/16748034

**Acceptance**
Test the items in the test plan in each browser.

 **Test plan**
  - load
  - zoom
  - full screen
  - full text search and search result navigation
  - metadata display
  - download
  - show/hide full text

**Test on Mac**
   - [x] Chrome
   - [x] Firefox
   - [x] Safari

**Test on Windows**
   - [x] Chrome 
   - [x] Edge
   - [x] Firefox

**Comment by AKFosterDev** [comment]
Completed testing on:

**Mac**
  Chrome

**Windows**
  Chrome
  Firefox
  Edge

All seem to be working as expected.
