### ISSUE TITLE
Configure image download options in UV4

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2099]
**Story**

The options presented to download an image in UAT (UV4) appear to what come out of the box with UV
![Screen Shot 2022-05-23 at 10.00.26.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/d74a4689-f0dc-47e6-b591-564f26555abc)

We need to configure the options here to match current Production options (which is currently on UV3)
![Screen Shot 2022-05-23 at 10.46.23.png](https://images.zenhubusercontent.com/60786c408c8643227aa47d8f/9180128f-6d4d-49bc-b287-30516fd4d02a)

Also, if possible, the "Full Size" download should be the selected by default when you click on the download icon in UV. 

**Acceptance**
- [ ] Download options available in UV4 match those currently available in UV3 (Reduced size and Full Size_
- [ ] Full size option should be selected by default when clicking on download icon in UV

**Comment by motropuk** [comment]
Like to get this done this week to not hold up UV4 deployment on Weds

**Comment by mikeapp** [comment]
It looks like `uv-seadragon-...-en-GB...` config file is not loaded by UV4?    Line 127 of `uv-config.json` in the [sandbox](https://codesandbox.io/s/uv-config-example-7kh4s?file=/uv-config.json:3856-3861) looks similar if not the same, probably it just needs to be moved to our copy of the same file.

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/807

**Comment by K8Sewell** [comment]
PR to force fetch of new uv-config.json - https://github.com/yalelibrary/yul-dc-blacklight/pull/808
