### ISSUE TITLE
Add a link to Orbis

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#210]
**STORY**
As a researcher, I'd like an easy way to get to the catalog record for the work I'm looking at.

**ACCEPTANCE**
On the work show page in blacklight
- [x] There's a link that takes me to Orbis from the Orbis Bib ID field
- [x] The link points to a handle that redirects to the correct catalog record in Orbis

**EXAMPLE**
https://collections-demo.curationexperts.com/catalog/11913649 should have a link to
http://hdl.handle.net/10079/bibid/3827095

**IMPLENTATION HINTS**
"http://hdl.handle.net/10079/bibid/" is likely a constant for all Yale Handle urls.

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/95

# Story
As a researcher, I'd like an easy way to get to the catalog record for the work I'm looking at. There's a link that takes me to Orbis from the Orbis Bib ID field. The link points to a handle that redirects to the correct catalog record in Orbis

# Demo
![i210](https://user-images.githubusercontent.com/29032869/84213003-5fe51b80-aa74-11ea-870a-be0544eba463.gif)
