### ISSUE TITLE
[Bug] Update Parent Batch Processes Not Finishing in UAT and PROD

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2100]
Large update parent batch processes in UAT and PROD are not finishing. In most cases, the process gets to a certain point in the spreadsheet and stops processing parent OIDs. Examples are below:

**UAT:**
[Batch Process 1062](https://collections-uat.library.yale.edu/management/batch_processes/1062)
7,216 out of 8,279 OIDs processed

[Batch Process 1063](https://collections-uat.library.yale.edu/management/batch_processes/1063)
6,729 out of 8,280 OIDs processed

**PROD:**
[Batch Process 8738](https://collections.library.yale.edu/management/batch_processes/8738)
2,406 out of 9998 OIDs processed

[Batch Process 8739](https://collections.library.yale.edu/management/batch_processes/8739)
4,790 out of 9,746 OIDs processed

**Acceptance**
- [ ] We would like Batch Processes to process every parent in the spreadsheet.

**Comment by sshetenhelm** [comment]
[Batch Process 8743 ](https://collections.library.yale.edu/management/batch_processes/8743) fully processed with 1162 / 1162 objects updating.

**Comment by mikeapp** [comment]
Will try adjusting the number of delayed job processes first.

**Comment by motropuk** [comment]
@mikeapp to write ticket to increase CPU and Memory on UAT

**Comment by mikeapp** [comment]
Requested doubling of resources on standard workers in UAT.

**Comment by motropuk** [comment]
Need to run some new tests in UAT to see if the old problems we experienced resurface

**Comment by motropuk** [comment]
@mikeapp Here is the batch process that Alicia ran https://collections-uat.library.yale.edu/management/batch_processes/1096. Batch was for 8279 objects. Seems to have stalled at/only completed 1,490 objects.

**Comment by mikeapp** [comment]
I ran a new batch job with the input from 1096, https://collections-uat.library.yale.edu/management/batch_processes/1099.   The job halted after processing 365 records.  I checked the database and there is no batch status message logged against the parent.   Honeybadger did not report any issues during the run.

**Comment by mikeapp** [comment]
The main job seems to stop when memory use reaches near 100%.  I have requested an increaese from 3GB to 8GB of RAM.

**Comment by mikeapp** [comment]
The Garvin test job was able to complete after the memory increase.   Memory use hit about 5GB.

**Comment by mikeapp** [comment]
If we are not going to re-run one of the Garvin batches for now, then we could close this and see how #2114 behaves in production.
