### ISSUE TITLE
UV 4 Cache Busting

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2102]
**Story**

After the UV 4 deployment, in the Chrome Browser, if a user has visited DCS recently, they only see an empty black box with no images loading within the UV.  This issue gets resolved once a user clears their cached version of the `uv.html` file.  We want the browser to **not cache this file**, and Chrome appears to be ignoring or not strictly following the no-cache headers in the HTML page. 

**Acceptance**
- [ ] Decide on a cache-breaking parameter.  Possibilities: Blacklight version or timestamp
- [ ] `uv.html` page is loaded with a cache-breaking parameter
- [ ] `uv-config.json` is loaded (by the `uv.html` page) with a cache-breaking parameter

**Comment by AKFosterDev** [comment]
Would it be acceptable to expire all assets?
 ![Screen Shot 2022-06-06 at 10.57.19 AM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/1de080a6-96ca-49ba-a6ed-95b42df625bf
)

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/815

**Comment by K8Sewell** [comment]
Released in version 1.60.30 - however not yet deployed to test due to dependency conflict described in ticket #2115

**Comment by AKFosterDev** [comment]
Tested on 'Test'. Works as expected. 

![Screen Shot 2022-06-14 at 9.17.05 AM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/75e64949-be76-45d5-8d0b-d62de55d1a64)
