### ISSUE TITLE
[DISCUSS] IIIF Structural Metadata Requirements 

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2103]
Requirements gathering to create a spec for IIIF Structural Metadata development work, similar to requirements we gathered to develop archival context. 

Use cases
- Multi folder objects
- Periodicals (maybe)

Meeting scheduled for 2022.06.01 2:30 pm to 3:00 pm including Mark Custer.

Follow-up to #2098 

See [previous doc](https://docs.google.com/document/d/191Kz52V-YoramZLiMoRVWsmrIoi39SLr_sZgIDPRJmY/edit#) for IIIF notes.

**Comment by motropuk** [comment]
Meeting done. Notes here https://docs.google.com/document/d/191Kz52V-YoramZLiMoRVWsmrIoi39SLr_sZgIDPRJmY/edit#
