### ISSUE TITLE
Update this item process needs to run of any parents that get modified by a preservica sync.

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2105]
**Story**

While testing #2083, a resync with Preservica (when a new child had been added to Preservica) would create a child record in DCS, but then not attach an image to that child. After testing it was discovered that after adding the child dcs didn’t go through the update process on the created Parent to check all the PTIFFs, generate the manifest and PDF, etc. We trigger this manually but clicking on the “Update this item” on the created parent and the child image and new manifest, etc processed as expected. We therefore need to update our code for this batch process to make sure it triggers the “Update this item” process on any parents that get modified by a preservica sync.

**Acceptance**
- [x] Rsync job with Preservica successfully picks up a new child object in Preservica, creates a new child object in DCS and adds image file to that child 
- [x] Batch process should complete fully, with all status updated and job completed

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/1018

**Comment by AKFosterDev** [comment]
Release to UAT - https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.40

**Comment by martinlovell** [comment]
v2.59.43

**Comment by motropuk** [comment]
Running a test in UAT https://collections-uat.library.yale.edu/management/batch_processes/1111/parent_objects/900146265. So far the resync is still not completing as expecting, but will monitor through the day to see if it completes

**Comment by motropuk** [comment]
First test above failed as the fixity for the added child image in Preservica was set to SHA1. Updated this to SHA512 and running the test again https://collections-uat.library.yale.edu/management/batch_processes/1112

**Comment by motropuk** [comment]
Second test was successful. The PDF generating stage is still running but that is because there is a large queue of PDF jobs on UAT right now. But I think we can call this ticket done.
