### ISSUE TITLE
[DISCUSS] Requirements - Granular Access Controls

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2106]
Discussion on requirements for Granular Access Controls. 

- For content requiring more granular access permissions that Yale or public. E.g Kissinger 
- Also additional options will be needed once guidelines for sensitive materials is implemented, including opt it click through options, and restrictions for pre authenticated individual researchers
- Also need for allowing accessing to material for individual patrons only for a set period of time, like Aviary. 

Follow-up to #2098 

Add notes to [requirements gathering doc](https://docs.google.com/document/d/191Kz52V-YoramZLiMoRVWsmrIoi39SLr_sZgIDPRJmY/edit#)

**Meeting Friday 7/29 after standup.**

**Comment by motropuk** [comment]
Notes for our upcoming discussion on Friday after standup https://docs.google.com/document/d/191Kz52V-YoramZLiMoRVWsmrIoi39SLr_sZgIDPRJmY/edit#heading=h.w1uzxxt1sx96

**Comment by motropuk** [comment]
Follow up work is in #2169
