### ISSUE TITLE
Add a link to other items with the same call number

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#211]
**STORY**
As a researcher, I'd like an easy way to see all other items that share the call number of the work I'm currently looking at, so that I can browse related resources.

**ACCEPTANCE**
On the item's show page
- [ ] The "Identifier Shelf Mark" value links to a search for all items with a matching call number.

**EXAMPLE**
See the call number field on this page https://brbl-dl.library.yale.edu/vufind/Record/3442553

**Comment by bess** [comment]
@edejesusyale I'm going to leave this in review / QA until you can demo what we have and talk through with the team whether it's good enough for now or whether we need to pursue one of the strategies you outlined above.
