### ISSUE TITLE
Bump to rails 6.0.5

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2110]
**Story**

Rails needs updating to 6.0.5

**Acceptance**
- [x] Blacklight
- [x] Management

**Comment by AKFosterDev** [comment]
## Management

PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1021

**Comment by AKFosterDev** [comment]
## Blacklight
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/813

**Comment by K8Sewell** [comment]
No issues found on test site

**Comment by mikeapp** [comment]
Looks good on UAT
