### ISSUE TITLE
Learn about IIIF Ranges

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2112]
**Story**

A desired new feature is the ability to create and modify a table of contents/navigational structure within the object.   This will be expressed in IIIF and used by UV/Mirador.

**Everyone on the team should look.  Assign yourself to the ticket when you've completed that.**

**Acceptance**
Read
- [ ] https://iiif.io/api/presentation/3.0/#54-range
- [ ] https://iiif.io/api/cookbook/recipe/0024-book-4-toc/

**Comment by AKFosterDev** [comment]
Read through provided documentation links.
