### ISSUE TITLE
Update base Docker image for Cantaloupe

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2116]
**Story**

We should update the base image used for the Cantaloupe server if a newer one is available.

**Acceptance**
- [ ] Update base image for the image server
- [ ] Test

**Comment by AKFosterDev** [comment]
@mikeapp - Upon originally picking up this ticket I began updating the image to the most recent version of Cantaloupe (from 4.1.6 to 5.0.5) and JRUBY (from 9.3.0.0 to 9.3.4.0). The configuration of the Cantaloupe file had changed from a .war file to a .jar file. I worked through all of the items in the UPGRADING.md file. I am unsure if this builds correctly and am unsure how to test that it is built correctly. 
Here is a draft PR for the work that was originally completed - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/31

On Friday, 6/17/22, I paired up with Martin. He suggested upgrading to a version that still incorporated the .war file configuration. I updated the Cantaloupe version only from 4.1.6 to 4.1.11 and made the corresponding changes noted in the UPGRADING.md file. 
Here is a draft PR for this work - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/30

**Comment by AKFosterDev** [comment]
The updated draft PR is ready for review - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/30

This needs to be deployed to test server to make sure the image is working.

**Comment by AKFosterDev** [comment]
## Summary
Add build option to cantaloupe template

Camarata PR Ready for review - https://github.com/yalelibrary/yul-dc-camerata/pull/344

**Comment by mikeapp** [comment]
Deploying 2116_UpdateBaseImageLowerRelease to demo

**Comment by AKFosterDev** [comment]
Testing note - Rob mentioned that browser cache needs to be cleared before testing the new image.

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/30

**Comment by AKFosterDev** [comment]
New release created for yul-dc-iiif-imageserver [v1.0.9](https://github.com/yalelibrary/yul-dc-iiif-imageserver/releases/tag/v1.0.9)

**Comment by mikeapp** [comment]
Deployed to UAT and Staging
