### ISSUE TITLE
[ASpace Linking] Making DCS Object 'Private' Does Not Remove Link in Aspace

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2119]
See #2067 for Aspace Linking Testing ticket 

**Story**
When an object that was Public in DCS is made Private, the link is not removed from Aspace. The link displays with a broken image. 

When an object is made Private in DCS, we would like the link to be removed from ASpace.

Notes -- As per M.C., the user is a sysadmin, which means it should have all necessary permissions. We may need to check with Trip/Lyrasis about database changes that may be causing issues. 

[Example object in UAT MGMT](https://collections-uat.library.yale.edu/management/parent_objects/10009938)
[That object's record in "test" ASpace](https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1065118)

![Screen Shot 2022-06-03 at 4.24.34 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/dc2ab7e8-e92b-4a73-8d2a-6dd53b0bfafc)

**Comment by martinlovell** [comment]
I was able to delete using the MC user with a python script.  It's likely something in the way that we are authenticating in Metadata cloud.  (I deleted /repositories/12/digital_objects/178422 manually.  ASpace PUI has not updated yet, but the `/repositories/12/archival_objects/1065118` shows no DO instances through the API.)

**Comment by martinlovell** [comment]
PUI still shows the viewer.  It looks like the DO was deleted successfully, and the AO no longer has it listed in the instances list.  However, it's still displaying the viewer and links: https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1065118

**Comment by martinlovell** [comment]
Updated in UAT.  Delete is successful.

**Comment by martinlovell** [comment]
(There is still some issue where https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1065118 is still showing the DO links, but the DO is deleted and not in the archival object's json from what I can tell.)

**Comment by ucancallmealicia** [comment]
Tested the delete and it works. It took a minute for the TEST PUI to register the change and remove the viewer, but it happened. @martinlovell I didn't see any DO links in the link you posted above, so maybe it just took some time to index?

When I made the DCS object public again, a new digital object was created. 

With that said, I think what we actually want is for the entire digital object to be unpublished - not deleted - when a DCS object is made private. When I first tested this just the manifest file URI in the digital object was being unpublished when a DCS record was made private, but the rest of the digital object was published. This may have caused the issue with the viewer still being present in the archival object record.

**Comment by martinlovell** [comment]
So, for private in DCS, set the DO publish=false and all the file_versions too?
@ucancallmealicia , that should be pretty straight forward.  It seems better too since if something goes private and then back to Public in DCS, the digital object ID will still be the same.
So, we should only delete the Digital Object if the Parent is deleted in DCS?

**Comment by ucancallmealicia** [comment]
That's correct, set the DO publish = false if the DCS object is private. You shouldn't have to unpublish the file versions if the whole DO is not published. 

And yes, only delete the DO if the parent is deleted from DCS.

Thanks!

**Comment by martinlovell** [comment]
Link is removed now, but there is a followup ticket: #2126

**Comment by fordmadox** [comment]
Right, this is an ASpace issue.  It looks like removing a linked record (in
this case, a digital object) will *not* trigger a re-index of the archival
object.  I just edited the archival object
<https://puitestarchivesspace.library.yale.edu/repositories/12/archival_objects/1065118>(and
appended something to its title to clearly indicate that it was edited),
and at that point the previously-existing/linked digital object will be
removed.  So, I expect that whenever a previously-linked digital object is
updated OR deleted (unless a new digital object is created and linked to
that same archival object at the same time), we will need the code to grab
and re-post the associated archival object.  Doing that will ensure that
the archival object is re-indexed and updated as necessary.
