### ISSUE TITLE
Spike: Investigate "sorry, too many clients already" errors

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2123]
Honeybadger is reporting errors from Postgres.  The app sometimes gets a "sorry, too many clients already " from postgres when trying to make a connection.

**Comment by bobrice** [comment]
Increasing the connection limit in postgresql.conf will likely fix this issue.  Once that's done we can increase CPU from 2048 to 4096 and redeploy to implement.  This requires a downtime.

**Comment by martinlovell** [comment]
Follow up ticket: #2127

(We can close this spike.)
