### ISSUE TITLE
Copy placeholder_restricted.png to a static location

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2125]
As a developer, I want to create digital objects in archives space that reference placeholder_restricted.png without asset IDs.

We need to reference `placeholder_restricted.png` when creating Digital Object from ParentObjects with Yale Community Only visibility.

`placeholder_restricted.png`  is handled by the rails asset pipeline, so if the image is changes it will get a new generated URL.  This will cause problems if DOs reference the old URL.

The file should be copied to public/image in the app so that it can be referenced with a URL that doesn't change: /images/placeholder_restricted.png
OR
The file should be copied to a static site, like the one we use for fonts  (https://static.library.yale.edu).

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/817

**Comment by K8Sewell** [comment]
Release - https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.31 - deploying to test

**Comment by martinlovell** [comment]
Deployed to UAT
See image: https://collections-uat.library.yale.edu/images/placeholder_restricted.png

**Comment by motropuk** [comment]
Looks good in UAT. See that this image now has a static URL that can be added to ASpace objects. Follow up work with be in #2118
