### ISSUE TITLE
Don't delete Aspace Digital Objects when DCS Parent is marked Private

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2126]
Currently, when a Parent in DCS is marked Private, the digital object is deleted from archives space.

Instead, it should keep the digital object and mark it private (publish=false).

Metadata cloud will handle setting publish=false for private items:  https://github.com/yalelibrary/metadata-cloud/issues/420

DCS does not generate a DO when an item is private, which causes it to be deleted.  It should generate one with private visibility.

- [x] Update DCS to generate a DO (with private visibility) when a parent is private.  (In `DigitalObjectManagement.generate_digital_object_json()`).

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1025

**Comment by martinlovell** [comment]
v2.59.43

**Comment by motropuk** [comment]
@martinlovell @ucancallmealicia @sshetenhelm do you have an example record I can use to test this?

**Comment by motropuk** [comment]
Thanks @martinlovell I will test

**Comment by motropuk** [comment]
Looks good on UAT and ASpace test. See the DCS object for https://puitestarchivesspace.library.yale.edu/repositories/6/archival_objects/2538740 to Private. Disappeared from Test Archives at Yale after about 20 mins, and then checked the DO in Aspace Test and it was still present but set to be unpublished as expected. So good to close
