### ISSUE TITLE
Add a date facet with a date slider

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#213]
**STORY**
As a researcher, I'd like to be able to refine my search by date, so that I can view works representative of a particular time period.

**ACCEPTANCE**
- [x] I can limit my search results using a date slider like the one in FindIt - http://findit.library.yale.edu/catalog?utf8=✓&utf8=✓&search_field=all_fields&q=&range%5Bstart_year_isim%5D%5Bbegin%5D=1579&range%5Bstart_year_isim%5D%5Bend%5D=1767&commit=Limit

**IMPLEMENTAION HINTS**
We'll use the [blacklight range limit gem](https://github.com/projectblacklight/blacklight_range_limit).  We'll probably need to add an additional integer year index based on the value in the `date_structured_ssim` field.

PIROR ART
Search: https://github.com/emory-libraries/dlp-lux/pull/235/files
Index: https://github.com/emory-libraries/dlp-curate/pull/937/files

**Comment by bess** [comment]
@FCRodriguez7 Looks good in your screen shot but not actually showing up on our production server. Would you help me figure out why later so we can close this?
