### ISSUE TITLE
Retest DCS -> AAY synchronization on UAT

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2130]
Test all synchronization, focusing on recent changes.

- [x] Yale Community Only objects in DCS have the "restricted" thumbnail image from DCS.
- [x] Private objects in DCS have a digital object in AAY with publish=false.

- [x] Test other synchronization between DCS and AAY

**Comment by sshetenhelm** [comment]
@ucancallmealicia will test. Thank you, Alicia!

**Comment by ucancallmealicia** [comment]
Testing spreadsheet: https://docs.google.com/spreadsheets/d/1YsYAM2N2CsG856gvGbmcTOOgQxxQMjDmHf8Tlepqpow
