### ISSUE TITLE
Prod metadata sync stuck

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2134]
The ActivityStream sync on production stopped on 6/16.   It needs to be restarted.

**Comment by martinlovell** [comment]
Updated "Running" record manually, so it should run tonight.  
Having a way to do this as an admin through the UI would be nice, or the system could automatically marking any that are "Running" for more than 6 hours as failed.

**Comment by martinlovell** [comment]
The job is still not finishing.  It's not timing out, so it may be a resource issue on the workers.
Waiting for #2135 to see if it finishes with more resources.
