### ISSUE TITLE
Display Parent Object version history

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2136]
**Story**

As a content owner I would like to be able to see the revision history of a Parent Object in the Management app.

The revision history can be derived from two sources, the `batch_processes`/`batch_connections` tables and the [Papertrai](https://github.com/paper-trail-gem/paper_trail)l `versions` table.    The Batches are useful in that they provide context for the updates and are almost always associated with a specific user.   The Pepertrail history is comprehensive - it includes manual updates made in the UI - but often does not have the user information.

For this feature we will load information from both the Batch tables and the Papertrail, and combine the data for presentation in a single table, ordered by timestamp of when the update occurred.

Because Papertrail contains many entries without user details (and sometimes multiple updates resulting from a single batch job), the user will be presented with a check box that, when selected, will exclude entries from the list that do not have an associated user.   This will declutter the list.   The user will have the option to uncheck the box and show all events.  

**Acceptance**

* Create a new route and view.  For example:  `/parent_objects/123/versions`
* Add a link from the current Parent Objects page,  see screenshot 1 below
* Layout and headers/text in screenshot 2 below

**Security**
* The version history should be viewable only by users who can view the Parent Object display page.

**Data**
* Timestamp:  `created_at` for the Batch or Version
   * Convert to local time
*  User:  Look up user first/last name.   Batch process stores the user, see Papertrail docs (`version.whodunnit` ?) 
* Job or Event:  Batch process `batch_action` or Version `event`
* Job status:  Batch process `batch_status`
* Job ID:  Batch process ID, linked to display page for that process
   * Link opens in a new window, has appropriate icon
* Default sort is by Timestamp DESCENDING (most recent event first)

**Controls**
* Checkbox above the list.  When checked, the list does not display any row without a value for the User column.
  * DEFAULT TO CHECKED
* Columns are not sortable
* No pagination for now

[1] Link location
![Screen Shot 2022-06-21 at 3.20.08 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f65af450-891f-4c34-806f-095db5c85ffc)

[2] New Page Layout
![Screen Shot 2022-06-22 at 1.19.44 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/2e039d0e-ad71-4044-946a-53dc0865c26b)

**Comment by martinlovell** [comment]
v2.59.49

**Comment by martinlovell** [comment]
v2.59.49

**Comment by motropuk** [comment]
Looks good in UAT
