### ISSUE TITLE
[SPIKE] Point existing DCS parent at a new Preservica URI

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2137]
**Story**

While testing Preservica syncing in #2039, and through discussions with DPS, it has become clear that in most instances, when changes are needed related to image files associated with an object in DCS (e.g adding a new image file, deleting an image file, replacing an image file, reordering image files), the best approach will be for collection owners to reingest the entire object in Preservica, complete with the required changes, to create a new object, which will have a new UUID.  

Therefore, as a collection owner, I want to be able to update an existing parent in DCS, that is synced with Preservica, to point that parent at a new Preservica object. I would expect to do this by updating the Preservica URI for the existing DCS parent. I want the existing Parent OID and metadata to persist. Additionally, I want the existing Child OIDs to persist for files that were already pulled into DCS from the previous Preservica object. 

To ensure that child OIDs persist, one option could be we pull in, store and check all checksums when syncing with Preservica. This would ensure that if an existing parent in DCS was updated to point at a new Preservica object, and then we ran a resync on that DCS parent, it should only pull in files with checksums currently not stored in DCS. Additional, if DCS found a checksum was missing for a file it already had stored, it would remove that file from DCS. However, an unknown for this approach is how DCS would interpret and update sort order, given that this might also change. 

**Acceptance**
- [x] Decide on approach 
- [x] Send email to DC mailing list asking for input

**Comment by motropuk** [comment]
Will discuss after standup tomorrow 07/06

**Comment by sshetenhelm** [comment]
Decided to send message to specific stakeholders to request feedback. Message sent 2022.07.08 to Mark Custer, Jennifer Coggins, and Stephen Goeman with relevant DCS team members CC'ed.

**Comment by motropuk** [comment]
Can be closed. When we get response, we will feed this into work in #2138, and create any additional tickets as needed after that
