### ISSUE TITLE
Finding Aid should be a clickable link

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#214]
**ACCEPTANCE**
On single item views with a value in the "Finding Aid" field
- [ ] The value displayed in "Finding Aid" should be clickable as a link to the corresponding finding aid.

![image](https://user-images.githubusercontent.com/3064318/84157206-11ae2900-aa30-11ea-88f8-ea7aa6642859.png)

Example: https://collections-demo.curationexperts.com/catalog/10001192

**Comment by bess** [comment]
See https://collections-demo.curationexperts.com/catalog/2005512 for a live example
