### ISSUE TITLE
Add preservica timestamp to image

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2144]
# Summary
To add a 'last updated' timestamp to the image on the child record show page in management a new attribute needs to be captured during ingest.  Then this new attribute will need displayed on the child object show page.

# Acceptance
- [ ] 'last_preservica_update' attribute added to show page for child object

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1033

**Comment by martinlovell** [comment]
v2.59.48
