### ISSUE TITLE
Allow Setting Parent to Private when Metadata is not found or Suppressed

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2146]
As a user, I would like to be able to set a Parent Object to Private and remove it from Blacklight, even if the metadata is no longer available.

ASpace objects which point to an archival object that is missing or restricted will automatically be set to Private.  So, this isn't really an issue for Parents pointing to Archives Space.

However, if an ILS record points to a Bib that becomes suppressed or is deleted, there is no way to remove the parent from blacklight by setting it to private in DCS management.  Solr Index does not occur during the update process because it stops when if fails to download the metaddata and never gets to the solr index phase.

- [x] If a parent is set to private in management, call solr_index to remove it from blacklight even if the request to metadata cloud does not succeed because it is not found or suppressed.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1046

**Comment by martinlovell** [comment]
v2.59.54

**Comment by mikeapp** [comment]
Tested by pointing UAT 2055095 at a non-existent bib, then updating access to private.   The object was removed.  I changed the bib back and set access to public and it was restored.
