### ISSUE TITLE
Zoom and rotation options not displaying in UV

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2147]
**Story**

As an end user, I want to always have the option to rotate an image in Universal Viewer. The option to rotate images in Universal Viewer is currently not displaying for objects in DCS e.g https://collections.library.yale.edu/catalog/32344574 

Compare this to this image in UV in YCBA's digital collections platform https://collections.britishart.yale.edu/catalog/tms:10116. A small panel is available top left of the image when you hover over the image, which allows you to zoom in and out and rotate the image. Is it possible this feature was not configured in the new version of UV when we implemented it? 

**Acceptance**
- [ ] Options to click to zoom in or out on an image or rotate it are available in UV

**Comment by motropuk** [comment]
Update: The zoom and rotation options appear when you go into full screen for UV.

**Comment by AKFosterDev** [comment]
Release [v1.60.34](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.34)
