### ISSUE TITLE
Identify candidates for easy reassociation work

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2148]
**Story**

With all Phase 2 collections now migrated, we should review each collection to identify which could be easily reassociated with Aspace or Voyager. 

Two documents that will help with this work are the Legacy Collection Migration Plan https://docs.google.com/document/d/1ppw7BSWArP6L9n989wliFTa37Bfl7FOA8y9vU3KVWw8/edit and Legacy Collection Analysis survey data https://docs.google.com/spreadsheets/d/1E-PwAdYQaNvri7okwn5btTB3w2KUEzvHyMvlcrn8Q5E/edit#gid=0. We should also review data in DCS to see which migrated parents came over with Voyager and ASpace identifiers in place. Parents with identifiers already in place will be the easiest to reassociate. 

For this initial work, we would want to create three lists

1. Collections with existing description in Voyager or ASpace and identifiers already in DCS
2. Collections with existing description in Voyager or ASpace without identifiers in DCS
3. Collections without existing description in Voyager or ASpace (description likely just in Ladybird)

The results of this work would then inform discussions with stakeholders before any work was done

**Acceptance**
- [ ] Three lists of collections as described above

**Comment by sshetenhelm** [comment]
Started [google sheet](https://docs.google.com/spreadsheets/d/1sHq-u2bfbkgLzlOwCwOBp9UptqIxtJiPRdNph_0rkhQ/edit?usp=sharing) to track work

**Comment by ucancallmealicia** [comment]
Reviewed the MSSA collections on the YUL Legacy Collections spreadsheet - there are four (Durand, Goel, Wieland, Dumas) that have already been migrated to DCS from Find-it and will be easy to reassociate.

**Comment by sshetenhelm** [comment]
Identified five collections that should be ready for reassociation -- the four described above and Law's Litchfield Law School Student Notebooks. 

All other collections seem to need additional information, excluding Garvin, LWL, and Papyrus.

Sanborn maps looks to be the next closest in terms of potentially reassociating.
