### ISSUE TITLE
Cleanup unprioritized and future board columns

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2149]
**Story**
Its been a while since we reviewed the unprioritized and future board columns (see #1721). We should do another review and clear anything that is not longer relevant and add things to check to the backlog. 

**Acceptance**
- [ ] Old tickets in unprioritized and future board columns that are no longer relevant are closed
- [ ] Tickets that need checking added to backlog

**Comment by mikeapp** [comment]
Looked at Future column, moved #1663 and #1273 into backlog as potentially quick fixes.   Close a few issues that seemed obsolete.   The remainder appear valid.

**Comment by mikeapp** [comment]
We should look at #2016 and #2019 in the Unprioritized column

**Comment by mikeapp** [comment]
Deleted the "Future" pipeline and moved all issues there to "Unprioritized"

**Comment by mikeapp** [comment]
I reordered issues in the Unprioritized column
