### ISSUE TITLE
Display thumbnails for public works

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#215]
**ACCETPANCE**
When showing search results, 
- [ ] Public access works should display a thumbnail of the first image in the manifest
- [ ] The thumbnail should fit within a 200 px x 200 px bounding box
- [ ] The thumbnail should retain the aspect ratio of the original image

See also:  #216 #217

**EXAMPLE**
![image](https://user-images.githubusercontent.com/3064318/84158783-e0cef380-aa31-11ea-8175-cabc014faa92.png)

See also:  #216 #217

**Comment by mikeapp** [comment]
The image information is only available in the manifest file right now, so you'll need to load and parse it.  One option might be to do it client-side for the moment.   I thought I'd point out the Manifesto.js  library that could help with this: https://iiif-commons.github.io/manifesto/index.html

This gist has an example of reading the data from the manifest:
https://gist.github.com/mikeapp/80e6170acaae9716100cdda0cc29f6b3

There's actually a bit more processing we'd want to for a more general case (checking for an explicit Manifest-level thumbnail, then a startCanvas, and an explicit thumbnail on the Canvas itself).

**Comment by FCRodriguez7** [comment]
blacklight gallery gem???

**Comment by mark-dce** [comment]
I think the process looks something like this:

For the work "Indulgence Scroll" -i.e.
https://collections-demo.curationexperts.com/catalog/10269867 

1. Find the work's OID - e.g. 10269867  (there is a field in the solr document with this value)
2. Request the manifest for the work - (eg. https://collections-demo.curationexperts.com/manifests/10269867.json ) - i.d. host/manifests/${OID}.json
3.  extract sequences[0].canvases[0].images[0].resource.id for the image url
4. render a version of that image in the search results list that fits in a 200x200 bounding box - see the [IIIF image api size spec](https://iiif.io/api/image/3.0/#42-size) especially the ! option to get something like https://collections-demo.curationexperts.com/iiif/2/1003311/full/!200,200/0/default.jpg

**Comment by alishaevn** [comment]
Co-authored by: Frederick Rodriguez <frederick.rodriguez@yale.edu>

# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/123

# Acceptance
When showing search results, 
- [ ] Public access works should display a thumbnail of the first image in the manifest
- [ ] The thumbnail should fit within a 200 px x 200 px bounding box
- [ ] The thumbnail should retain the aspect ratio of the original image

# Testing
1. Do an empty search
2. Verify that thumbnails for public works are displayed if they have images, as shown below:
![Screen Shot 2020-06-16 at 11 56 41 AM](https://user-images.githubusercontent.com/40175979/84798033-79341d80-afc8-11ea-8bc7-2410df68e370.png)
