### ISSUE TITLE
Serialize structure models to IIIF JSON

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2151]
**Story**

The Rails models for structure should be able to be serialized to IIIF JSON per the Presentation API 3 spec.  See https://iiif.io/api/presentation/3.0/#b-example-manifest-response for an example. 

See https://github.com/yalelibrary/yul-dc-documentation/blob/main/structure.md#range-serialization for sample JSON output.

**Acceptance**
- [ ] Serialization

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/1040

**Comment by AKFosterDev** [comment]
Cut Management release [v2.59.52](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.52) deployed to Test
