### ISSUE TITLE
IIIF Structure deserializer

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2152]
**Story**

Once we have the Rails models to represent IIIF structure and can serialize the models to IIIF JSON, we need to implement the IIIF deserializer.    This should allow us to take a IIIF Range and build the corresponding object model in the database.   

Notes at https://github.com/yalelibrary/yul-dc-documentation/blob/main/structure.md

**Acceptance**
- [x] Code can accept a IIIF JSON Range and will create models for the Range and its child Ranges and Canvas references recursively.
- [x] The the `id` of the submitted Range matches an existing Range for the parent, the code will replace the Range and any existing child data with the new data.     
- [x] Test round-tripping a model 
- [x] Test a failed attempt to update a Range and verify that the existing data remains after

**Comment by K8Sewell** [comment]
These  tests already  exist in the iiif_structure branch - https://github.com/yalelibrary/yul-dc-management/blob/iiif_structure/spec/models/concerns/iiif_range_builder_spec.rb - which break down the Deserialization functions.

**Comment by martinlovell** [comment]
Looks good to me

**Comment by AKFosterDev** [comment]
Cut Management release [v2.59.52](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.52) deployed to Test
