### ISSUE TITLE
Create controller and routes for Structures

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2153]
**Story**

We would like a controller and routes to expose structures for retrieval and updates.  These should be access controlled.

A route /manifests/:id/ranges/:id allows GET/POST/PUT/DELETE actions on the individual structure resources. The client will send the entire Range and all of its children. The server can delete the current representation of the range and reconstruct it using the data submitted by the client.

See https://github.com/yalelibrary/yul-dc-documentation/blob/main/structure.md#rails-routes for detailed discussion.

**Acceptance**
`/manifests/:parent_id/ranges/:id` performs CRUD actions on the individual structure resources. The client will send the entire Range and all of its children. The server can delete the current representation of the range and reconstruct it using the data submitted by the client.
- [x] GET
- [x] POST
- [x] PUT
- [x] DELETE 

- [x] All are access controlled based on the logged-in user and their privileges for the ParentObject's AdminSet, see https://github.com/yalelibrary/yul-dc-documentation/blob/main/structure.md#permissions

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1041
