### ISSUE TITLE
Bump Rails in management and Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2155]
**Story**

See dependabot - we need to update Rails.

**Acceptance**
- [x] Management
- [x] Blacklight

**Comment by AKFosterDev** [comment]
**Blacklight**  PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/823
**Management** PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1037

**Comment by AKFosterDev** [comment]
**Blacklight** release [v1.60.35](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.35)

**Management** release [v2.59.51](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.51)

Deployed to UAT
