### ISSUE TITLE
UV HTML and JS cache issues

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2157]
**Story**

Looks like uv.html and UV.js are being cached again.  Regression?

**Acceptance*
- [ ] Be sure that UV.js and uv.html aren't cached.  Especially on Chrome.

**Comment by AKFosterDev** [comment]
I am unable to recreate this cache issue. On the production site and when run locally the uv.html and uv.js are being completed with a 200 response.
