### ISSUE TITLE
Structure Editor: create React app, test fetching a Manifest

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2158]
**Story**

For the structure editor UI we'll use a React app.  We need to test cookie-based auth for the API endpoint.

**Acceptance**
- [x] Create the React app and commit it to the new Repo
  - [x] Use Typescript.   Spike #2160 is to set aside time to review it. 
- [x] Test fetching a Manifest from the Management app endpoint
  - [x] Auth via session cookie

**Comment by K8Sewell** [comment]
React: PR ready for review - https://github.com/yalelibrary/yul-dc-structure-editor/pull/1
Management: PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1038
