### ISSUE TITLE
Structure Editor: Display thumbnail grid

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2159]
**Story**

Create components to load a IIIF manifest and display a thumbnail grid, with labels, similar to https://mikeapp.github.io/iiif-structure-demo/   The grid should be flexible and reflow based on screen width; assume we'll add a panel to the left side containing the object hierarchy.

Notes:
1.  The manifest and the list of Canvases in the `items` property will be immutable. We won't allow the user to reorder the images in the grid.
2.  In the future we will want to have different display options.  For instance large/small options for the size of the thumbnails.
3. The demo has an input form that allows the user to supply the Manifest URI.  Feel free to use that approach or to accept the URI as a parameter.

![Screen Shot 2022-07-15 at 3.20.42 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/004422d3-36b9-49c1-aef5-20ceb5589866)

**Acceptance**
- [ ] Loads a Maniifest
- [ ] Renders a thumbnail grid
- [ ] Lazily loads the images.  I used `react-intersection-observer` 
- [ ] Use Typescript https://www.typescriptlang.org !!!

**Comment by K8Sewell** [comment]
Forgot lazy loading but this PR adds it. https://github.com/yalelibrary/yul-dc-structure-editor/pull/4
