### ISSUE TITLE
Display placeholder thumbnail for Yale-only works when I'm not logged in

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#216]
**ACCETPANCE**
 When I'm not logged in and there are Yale-Only works in my search results
- [x] The works should display a placeholder image 
- [x] The placeholder should fit within a 200 px x 200 px bounding box

See also:  #215 #217

**PLACEHOLDER**
*We'll make a prettier version later...*

![image](https://user-images.githubusercontent.com/3064318/84158249-4a023700-aa31-11ea-8641-e3c14f2375fc.png)

**EXAMPLE**
![image](https://user-images.githubusercontent.com/3064318/84158732-d280d780-aa31-11ea-80f7-d407f739b1ef.png)

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/127

**Comment by alishaevn** [comment]
![image](https://user-images.githubusercontent.com/29032869/84921759-c15f4880-b079-11ea-9e5b-21ed285a4f1b.png)
