### ISSUE TITLE
[SPIKE] Structure Editor: Mock up tree widget, test drag and drop

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2161]
**Story**

Mock a left-hand "Structure View" using the Ant Design tree widget:  https://ant.design/components/tree/   You can populate it with static data, there's some sample data in the documentation.

Use the demo as a model: 
* App:  https://mikeapp.github.io/iiif-structure-demo/
* Code:  https://github.com/mikeapp/iiif-structure-demo/blob/main/src/component/StructureView.tsx

**Acceptance**
- [x] The app has a left-side column, like the demo
- [x] The tree widget displays with sample data
- [x] Explore the drag-and-drop options for reordering.
- [ ] Explore checkbox select/copy/paste option for reordering?
- [x] Need decision to go with Ant Design or reconsider....

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-structure-editor/pull/12

### Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/b0615577-5530-4b26-966e-6bcc1c4d3e29)
