### ISSUE TITLE
Structure Editor: make thumbnails selectable

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2163]
**Story**

A user should be able to select single or multiple thumbnails in the thumbnail grid.   Other components will need to access the selected items, for instance to add the Canvases to a Range.   The stored references should be to the Canvas, not the image service associated with the Canvas.

Use a React context to manage the state.   https://reactjs.org/docs/context.html

**Acceptance**
- [x] Selected Oids are stored in state ~~Create a React Context to store the selection data~~ Only passing through one level so added complexity seemed overkill
- [x] A user can select a thumbnail/Canvas by clicking on it
- [x] A user can deselect with command+click  ~~A user can deselect the selected Canvas by clicking on it~~ this is not a feature in Finder so pulled from list to simplify
- [x] A user can select a range of Canvases by clicking the starting thumbnail, then shift-clicking the ending thumbnail.
- [x] A user can command+click to add an additional Canvas to the current selection.

**Comment by K8Sewell** [comment]
PR for review - https://github.com/yalelibrary/yul-dc-structure-editor/pull/5
