### ISSUE TITLE
Show thumbnail for Yale-Only works to logged in users

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#217]
**ACCETPANCE**
When showing Yale-only Items in search results AND I am logged in, 
- [ ] Display a thumbnail of the first image in the manifest
- [ ] The thumbnail should fit within a 200 px x 200 px bounding box
- [ ] The thumbnail should retain the aspect ratio of the original image

See Also:  #215 #216

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/127

**Comment by alishaevn** [comment]
![image](https://user-images.githubusercontent.com/29032869/84921722-b60c1d00-b079-11ea-9894-2edf224ce9aa.png)
