### ISSUE TITLE
Walk through of Aviary access request workflow

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2171]
**Story**

Aviary provides an access request workflow similar to what is needed for Kissinger.   We should have a demo of this to the group.

**Acceptance:**
- [x] Record walkthrough
- [x] Team watch demo video

**Comment by motropuk** [comment]
Walkthrough video is here ready for the team to review and ask questions https://yalemusiclib.aviaryplatform.com/r/j96057dx1r?access=OiHXt6fXf-5_HnW22etM-Q==. We can tackle questions in standup, on this ticket or on Slack. Whatever people prefer

**Comment by tmacmath** [comment]
Watching this now. Will be saving for future reference.
