### ISSUE TITLE
Test removal of COVID banner

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2173]
**Story**

We have been asked to take down the COVID banner from all web sites.   Please test locally and confirm that the acceptance criteria are met. Test with the test banner JSON, which contains no message: https://banner.library.yale.edu/test/banner.json

If modifications are required, test against both the production and test banners.

Test with the banner: https://banner.library.yale.edu/test/banner.json

**Acceptance**
- [ ] The banner message and its containing bar should not appear.  The first visual element on the page should be the blue Yale University Library header.

![Screen Shot 2022-08-01 at 11.34.43 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/c1ccb65b-fdf0-476b-b791-d1c33965b08c)

**Comment by mikeapp** [comment]
I commented on the PR.

**Comment by AKFosterDev** [comment]
There is a new PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/828

Reverted back to production banner uri.
