### ISSUE TITLE
Add "Admin Set" column to Batch Processes table

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2174]
Work for Spike at #2120 

Add the "Admin Set" column to Batch Processes table.

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-management/pull/1052

**Comment by mikeapp** [comment]
Small question on the PR...

**Comment by K8Sewell** [comment]
I'm sorry but I'm not seeing the question on the PR

**Comment by mikeapp** [comment]
Released management v2.59.57

**Comment by mikeapp** [comment]
Looks good on UAT:
![Screen Shot 2022-09-06 at 1.48.47 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/f4f81487-baaa-4a2b-b37b-50198f7b8afc)

**Comment by sshetenhelm** [comment]
In UAT, tried to ingest an object with Goobi with DIV assigned as admin set. Nothing appeared in Admin Set column: 
![Screen Shot 2022-09-06 at 1.56.08 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/28699ec3-3566-4873-9095-df2b24041933)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1061

**Comment by sshetenhelm** [comment]
In UAT, tried the following three ingests:
1. DCS_Ingest_from_Network_Attached_Storage workflow with default admin set
2. DCS_Ingest_from_Network_Attached_Storage with Divinity admin set
3. Digital_Library with Divinity admin set

Alas! No admin sets showed up for me in the table for any of the three tests. 

![Screen Shot 2022-09-08 at 8.49.19 AM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/88a36cc5-b023-42db-9c94-7442a0ac60b2)

**Comment by K8Sewell** [comment]
Release [v2.59.59](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.59) deployed to test

**Comment by sshetenhelm** [comment]
Having problems getting things to ingest properly from Goobi into Management Test. Trying to troubleshoot so we can review this in test.

**Comment by sshetenhelm** [comment]
Did two tests, one with BRBL admin set and one with DIV.

Both show as "SML" in "Admin Set" in batch process table:

![Screen Shot 2022-09-13 at 2.13.07 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/c081f414-5ce7-4ffa-b176-ee9174f04111]

Parent from batch process 1166: 
![Screen Shot 2022-09-13 at 2.13.01 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/6cc2ae38-8a3f-4712-b159-560fbe1432c6)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1065

**Comment by K8Sewell** [comment]
Released to UAT in [v2.59.61](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.61)

**Comment by sshetenhelm** [comment]
Looks good on UAT! :)
