### ISSUE TITLE
[Bug] UV and Link to Parent with missing PTIFF displaying in Archives at Yale

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2175]
For [parent 32268679](https://collections.library.yale.edu/management/parent_objects/32268679), the UV and digital object link are displaying in [Archives at Yale](https://archives.yale.edu/repositories/11/archival_objects/567832) although object is not displaying in [Blacklight](https://collections.library.yale.edu/catalog/32268679) due to a PTIFF creation error. 

The fourth child, [OID 32268683](https://collections.library.yale.edu/management/child_objects/32268683), will not resolve because it does not have a file attached. 

However, the UV and a link to DCS exist in Archives at Yale at the above uri. 

As a staff member, I do not want broken objects to display in Archives at Yale.

(Related -- is there a way to prevent objects from showing up in Aspace until after all PTIFFs have generated?)

**Comment by martinlovell** [comment]
Instead of running the digitalobject check whenever the parent is saved, we could run it after solr_index is triggered.  This would ensure that it is only run if the object is indexed in SOLR so that it's in sync with Blacklight rather than Management.  Solr index should not occur if the object is not ready to display in blacklight and runs after the manifest is created.  Solr index also runs when an object becomes private to delete the document, and it runs when visibility has changed, etc.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1047

**Comment by martinlovell** [comment]
v2.59.54

**Comment by martinlovell** [comment]
Ready for testing on management UAT and archives space: puitestarchivesspace.library.yale.edu

**Comment by mikeapp** [comment]
If I make an item on UAT private, what is the expected time delay for the item to be removed from ASpace?

**Comment by martinlovell** [comment]
It depends....It should update the digital object in aspace within 10, 15 minutes after the solr_index succeeds.  But the PUI for aspace sometimes is delayed.  (Sometimes in test aspace it's broken and doesn't update until the pui sync is fixed.)   Summer might have permissions to view it in the aspace management ui.

**Comment by mikeapp** [comment]
Testing https://collections-uat.library.yale.edu/management/parent_objects/900105540  Marked as private, waiting for digital objects to disappear from ASpace.

**Comment by mikeapp** [comment]
Used broken record: https://collections-uat.library.yale.edu/management/parent_objects/16857981

Associated with: https://puitestarchivesspace.library.yale.edu/repositories/5/archival_objects/2477889
