### ISSUE TITLE
Search digitization note field in Advanced Search

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2177]
**Story**

As an end user, I would like to be able to search the digitization note field in DCS via Advanced Search. I would not expect this field to be indexed and searched via a general keyword search done via the search box on the DCS homepage or at the top of the result page, but would like to be able to search it via the Advanced Search option

**Acceptance**
- [ ] Digitization note can be search via Advanced Search

**Comment by motropuk** [comment]
Good test phrase is "Digitized from microfilm"

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/829

**Comment by mikeapp** [comment]
v1.60.38

**Comment by mikeapp** [comment]
Looks good on UAT, can close.
