### ISSUE TITLE
Dependabot: library update

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2178]
There's one update to Gemfile.lock in each repo.  There are JS updates too, but not as critical.

**Acceptance**
- [x] Management
- [x] Blacklight

**Comment by K8Sewell** [comment]
Management release - [v2.59.55](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.55)
Blacklight release - [v1.60.37](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.37)

**Comment by K8Sewell** [comment]
test looks good
