### ISSUE TITLE
[Bug] Ampersand displays as character reference in some fields

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2179]
**Story**
Not sure if this is a DCS, Metadata Cloud, or Voyager/ArchivesSpace issue.

When metadata including an ampersand is brought into MGMT, some fields display the ampersand as the character reference. 

As a user, I want to see the ampersand itself, not the character reference.

Example OID in Management: [https://collections.library.yale.edu/management/parent_objects/2015295](https://collections.library.yale.edu/management/parent_objects/2015295)
Example OID in Blacklight: [https://collections.library.yale.edu/catalog/2015295](https://collections.library.yale.edu/catalog/2015295) 
Example OID in ArchivesSpace: [https://archives.yale.edu/repositories/11/archival_objects/3492669](https://archives.yale.edu/repositories/11/archival_objects/3492669)

Search returns [2,783 results](https://collections.library.yale.edu/catalog?search_field=all_fields&q=%26amp%3B) for the character reference spelled out, but I think it is also returning objects that include the ampersand character.

Screenshot: ![ampersand.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/e093e09b-1faa-404a-9cd0-ff4e3956b5f9)

**Acceptance:**
- [ ] Where these fields are rendered, convert the entity code to the character

**Comment by mikeapp** [comment]
Another example:
![Screen Shot 2022-08-16 at 1.16.25 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a3641cfe-bdd3-423a-a962-03221f4aa471)

**Comment by MaggieZhaoYale** [comment]
&amp; in this record comes from Aspace. 
We could transfer the ampand in metadata cloud or in the management app.

**Comment by MaggieZhaoYale** [comment]
PR to review: https://github.com/yalelibrary/yul-dc-management/pull/1063

**Comment by K8Sewell** [comment]
Release [v2.59.60](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.60) deployed to UAT

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The fix was only apply for the ancestor title/ ancestor title structure files. The ampersand are in the title fields which is not include in the fix. I will the apply the replacement to other fields.

**Comment by MaggieZhaoYale** [comment]
Fixing the issue in management app will end with change in a few places, such as solr index fields, child label, iii-representation, pdf-representation. I am working on fix this in metadata cloud and marc4jextract, so no need to treat the fields individually.

**Comment by MaggieZhaoYale** [comment]
I checked Voyager, only summary 520 fields in 375 records have the "&amp;".
abstractNote is mapped in metadata cloud for 520; 

while  management map uses abstract and map abstract in solr. abstractNote is not used in management. 
see the abstract in managememt apphttps://github.com/yalelibrary/yul-dc-management/blob/2975936720b60acd8f9469750d98544670b1418e/config/initializers/metadata_fields.rb
https://github.com/yalelibrary/yul-dc-management/blob/7161453349dcaa127159df95e9305dda164b0ece/app/models/concerns/solr_indexable.rb
@mikeapp @motropuk is it a mismatch between metadata cloud and the management app?

**Comment by MaggieZhaoYale** [comment]
PR in metadata cloud: https://github.com/yalelibrary/metadata-cloud/pull/426

**Comment by MaggieZhaoYale** [comment]
This will be held for answers from metadata experts:
We have a question about metadata mapping for digital collection system, it may also a question for the Lux mapping.
Using a flag to mark the fields which should be unescaped may be the safer way. A list of fields which can be unescaped these characters for Voyager, Ladybird, Aspace are needed. Tim Thompson was contacted. 
So far we treated all fields flagged as  stripTags in ASpace as unescaped. @alisonclemens  @motropuk are there any fields of Aspace/Ladybird should keep these characters (e.g. &ampand; &nbsp; etc)  
Here is the metadata mapping fields for ILS, ladybrid and Aspace
https://git.yale.edu/Library-IT/Metadata_Field_Mappings/blob/test/aspace-map.json
Thank you. 

Here is the metadata mapping files: https://git.yale.edu/Library-IT/Metadata_Field_Mappings/blob/test/voyager-bib-map.json
Here is an example of voyager records with &bull;&nbsp; in summary fields: https://orbis-tst.library.yale.edu/vwebv/holdingsInfo?searchId=44&recCount=50&recPointer=0&bibId=16236215, Lux test also shows the &nbsp; http://yul-lux-dev1.library.yale.internal/ils/bib/16236215

**Comment by MaggieZhaoYale** [comment]
Tim's reply: As long as the data is being serialized as JSON, I can't see any issues with unescaping those particular characters.

**Comment by alisonclemens** [comment]
@MaggieZhaoYale to your question above, I can't think of any fields that should keep these characters. Tagging @ucancallmealicia in case she can think of any cases

**Comment by MaggieZhaoYale** [comment]
UAT examples:
https://metadata-api-uat.library.yale.edu/metadatacloud/api/1.0.1/ladybird/oid/10970272?include-children=1&mediaType=json
https://metadata-api-uat.library.yale.edu/metadatacloud/api/1.0.1/ils/bib/16236215/?mediaType=json

**Comment by sshetenhelm** [comment]
I still see the character reference coming over on UAT Blacklight.
![Screen Shot 2022-10-03 at 2.09.44 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/f0219f79-9b6a-46f4-9114-aee9ceea06c4)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The changes were made in the metadata cloud. You have to refresh the metadata in the management app
After refresh the metadata: the &amp is "&"
https://collections-uat.library.yale.edu/catalog/10970272

**Comment by sshetenhelm** [comment]
Oh gosh! So sorry. 

It looks great after the refresh!
