### ISSUE TITLE
Add 'Digitization Funding Source' field to parent object page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2180]
**Story**

As a staff member, I need to include information about the digitization funding source for certain digital objects (ex. Arcadia Fund digitized objects). This information is not recored in descriptive records outside of Ladybird.

I would like a field in the Parent Object's page where I can input funding information.
This field would appear under 'Digitization Note' in the Management App and Blacklight. 
This field could be edited via a free text box, similar to how the Digitization Note field is edited. 

**Acceptance**
- [x] `digitization_funding_source` field added to Parent Object model.  It should be able to contain any length of text.
- [x] In Management, the field is displayed on the Parent object page after the "Digitization Note" field
- [x] In Management,  the field is editable on the Parent object edit page.
- [x] In Blacklight, the field displays on the single object page after "Digitization Note"

**Comment by AKFosterDev** [comment]
Question: Do we want a "Digitization Funding Source" column added to the Parent Object index table or is this information only visible on the show page?

![image.png](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/f13d4013-37fd-4b43-8984-13282cad0935)

**Comment by AKFosterDev** [comment]
## Blacklight
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/832

## Management
Draft PR waiting for questions to be answered - https://github.com/yalelibrary/yul-dc-management/pull/1059

## Screenshots

### Blacklight
![BL show page.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/46c39d86-ed98-47ad-b4b0-e3eb88cb142c)

### Management
![PO show page.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/ad0cee7a-ae4b-4792-bd9c-6eb9a511214c)

![edit PO page.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/8751bfba-71b0-4e52-a289-20e866a92bdc)

**Comment by motropuk** [comment]
See follow up tickets after this is done - #2201, #2200, #2199

**Comment by AKFosterDev** [comment]
Management release v2.59.58 and Blacklight release v1.60.39 deployed to Test.

**Comment by K8Sewell** [comment]
Looks good on test
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/2f671e6a-0ff8-4de3-bdcb-0869934ce238)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/39732d10-dc4a-4509-a26e-270db1a60870)

**Comment by K8Sewell** [comment]
Looks good on UAT

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/6c961ffd-5e2a-4353-869a-f8c3436cab43)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d4301ade-f424-4cfa-839d-9aa3e326c8d1)
