### ISSUE TITLE
DISCUSS: Child caption searching improvements 

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2181]
**Story**

As an end user, when I search for child/image captions in DCS, when I click into one of the search results, I want to be directed to the specific image that includes my search term, and I would that term to be highlighted. 

For example, if I was to do a keyword search for "percement de l'Avenue de l'Operas, Paris, 1877" - this would return one parent result https://collections.library.yale.edu/catalog/16195945. However, when I click into the parent, I am taken to the first child image. The caption relevant to my search is in fact the last image for this parent. So instead of opening the parent to the first child image, I would like the parent to open to https://collections.library.yale.edu/catalog/16195945?child_oid=16402548. If my search term could also then be highlighted that would be great. 

**Acceptance**
- [ ] Make Ticket For:  When doing a keyword search for percement de l'Avenue de l'Operas, Paris, 1877" and opening the resulting parent, you are directed to https://collections.library.yale.edu/catalog/1619594 which contains your search term in the caption

**Comment by DraxIndustries79** [comment]
Meeting after standup Thursday 9/15

**Comment by DraxIndustries79** [comment]
Decision:  It's OK to search and display caption snippets
Next step:  Make ticket for wireframes, which we'll run past public service group

**Comment by ucancallmealicia** [comment]
No issues - Kissinger does not have child captions

**Comment by motropuk** [comment]
In that case, decision stands thats its OK to search and expose child captions for Yale only objects.  Can someone create the ticket for the wireframes?

**Comment by sshetenhelm** [comment]
Placeholder at #2223
