### ISSUE TITLE
Add submit button to structure editor

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2183]
**Story**

A user of the structure editor should be able to submit a new or revised structure from the React app.    The user should be able to return to the structure editor later and load the updated IIIF Manifest.

Per conversation in standup, this assumes there is already an API call to retrieve the dynamically generated Manifest that includes the latest structure data.

Question: is there already a way to provide an API key to the React app?

**Acceptance**
- [ ] Add a "save changes" button to the React app that submits the new structure data to the Management endpoint.
- [ ] Ideally the button would only be active after the user has made a change that hasn't been saved.
- [ ] The React app should be able to load an updated Manifest from the Management app.

**Comment by K8Sewell** [comment]
2 PRs - merged
