### ISSUE TITLE
SPIKE: Bump Rspec and Capybara versions on management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2188]
**Story**

Related to M1 issues in #2073, I think we should update our testing infrastructure so we're more likely to be compatible with Docker-hosted selenium.

**Acceptance**
On Management:
- [ ] Run test suite on Intel 
- [x] Bump Rspec from 4 to 5 
- [x] Bump Capybara from 2.x to 3.x (latest is `3.37.1`)
- [x] Run test suite again and confirm results are the same
   - [x] If they are, create a PR
   - [ ] If they are not, describe discrepancies in a comment.

**Comment by mikeapp** [comment]
I had a look at `webmock` but think we could leave it alone unless we see problems.

**Comment by DraxIndustries79** [comment]
Since this wasn't required for M1 work, this is lower priority but we should turn to it when we have time.

**Comment by AKFosterDev** [comment]
Management - Capybara bumped from 3.32.2 to 3.37.1
Blacklight - Capybara bumped from 3.33.0 to 3.37.1

It was not necessary to bump the Rspec version to get Selenium working for specs.

## Related Ticket
[#2073 M1 Blacklight/Management Resolve Selenium Crash](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2073)

**Comment by AKFosterDev** [comment]
Management PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1066

**Comment by K8Sewell** [comment]
Release [v2.59.62](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.62) deployed to Test

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by K8Sewell** [comment]
Rspec was not bumped to v5 in last pr.  Taking back to in progress to address this.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1070

**Comment by K8Sewell** [comment]
Release [v2.59.63](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.63) deployed to Test
