### ISSUE TITLE
Delete obsolete branches in fixture manifests

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#219]
**ACCETPANCE**
- [x] Manifest fixtures are stored with host references to http://127.0.0.1
- [x] IIIF manifest service is updated appropriately
- [x] Obsolete branches are deleted from the fixture repo

**Comment by fnibbit** [comment]
Blocker: mismatch between IDs being created by management app and IDs on fixture manifests.  Why that's a blocker for this ticket: current collections-demo uses manifest service version that points to manifest fixtures on a branch; can't delete that branch until collections-demo is updated, need a combination of application versions that generates mutually-intelligible manifest URLs to see images in collections-demo.
