### ISSUE TITLE
Record demo of Structure Editor

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2190]
**Story**

Record a demo of the Structure Editor for stakeholders.

**Acceptance**
- [x] video available

**Comment by K8Sewell** [comment]
https://share.getcloudapp.com/L1u9pX2j

**Comment by K8Sewell** [comment]
https://share.getcloudapp.com/bLu5RLbq

**Comment by mikeapp** [comment]
Looks great, thank you!
