### ISSUE TITLE
Pagination of Manifest thumbnail grid

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2191]
**Story**

When working with a large Manifest (1400 items), scrolling to the bottom of the single page thumbnail grid results in a long delay (I gave up after 90 seconds).   

**Acceptance**
- [x] Add pagination to the thumbnail grid
- [x] Pagination should have the option to jump to the last page
- [x] The option to move ahead/back more than one page would be ideal
- [x] Add an option to select the number of items to display (e.g., 25, 50, 100, 200).
- [x] Selection of Canvases should work across pages

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-structure-editor/pull/23

**Comment by mikeapp** [comment]
@martinlovell  Could you add the "jumper"?  That could be useful for larger items.
