### ISSUE TITLE
Check Blacklight sessions table in production DB.  

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2195]
**Story**

Both Quicksearch and FindIt periodically truncate the sessions table in production.  Do we need this?

**Acceptance**
- [ ] Check the table 
- [ ] Truncate if necessary, during an outage window.

**Comment by martinlovell** [comment]
I think blacklight and management are both using the Cookie store to hold the whole session, so there's no database storage.
