### ISSUE TITLE
Security update in Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2196]
**Story**

One critical security upgrade for a gem.

**Acceptance**
- [x] Blacklight updated.

**Comment by K8Sewell** [comment]
Release [v1.60.40](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.40) deployed to test

**Comment by K8Sewell** [comment]
Looks good on test.  Can log in.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4c8f65bd-1664-41ae-95b8-64a873ecf514)

**Comment by mikeapp** [comment]
Looks good on UAT
