### ISSUE TITLE
Add 'Digitization Funding Source' to Update Parent Objects batch process templates

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2199]
**Story**

Following on from #2180, we need to add Digitization Funding Source to the Update Parent Objects batch process template

The column header should be digitization_funding_source

**Acceptance**
- [x] digitization_funding_source column available on Update Parent Objects batch process template
- [x] Running Update Parent Objects batch process with something in the digitization_funding_source column, makes the required updated to a parent
- [x] Double check Update Parent Objects batch process itself knows how to update the Digitization Funding Source column

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1068

**Comment by K8Sewell** [comment]
Release [v2.59.62](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.62) deployed to Test

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Looks good in UAT! :)
