### ISSUE TITLE
Add Digitization Funding Source column parent objects Data Table

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2200]
**Story**

Following on from #2180, a Digitization Funding Source column should display in the Data Table under Parent Objects in the Management App

**Acceptance**
- [x] Digitization Funding Source column displays in parent objects data table

**Comment by AKFosterDev** [comment]
This work completed on related ticket [#2180](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2180)

### Screenshot
![Screen Shot 2022-09-14 at 1.19.41 PM.JPG](https://images.zenhubusercontent.com/62320545ecde9b03edb16d84/ab54e308-1cd7-4022-9847-7a68f90f7d7a)

**Comment by sshetenhelm** [comment]
Looks good on UAT to me.
