### ISSUE TITLE
Bump RSpec and Capybara versions in Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2203]
**Story**

See #2188, which should provide us with the correct versions to use.

RSpec - v5.0.0
Capybara - v3.37.1

**Acceptance**
- [ ] Libraries updated and tests pass.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/835

**Comment by K8Sewell** [comment]
Release [v1.60.43](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.43) deployed to Test

**Comment by K8Sewell** [comment]
Deployed to UAT
