### ISSUE TITLE
Export by admin set: exported data has full name of admin set

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2204]
**Story**

When exporting by admin set, the output CSV has the full name of the repository instead of the letter code:

![Screen Shot 2022-09-06 at 1.43.47 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a4846932-b106-4d9f-8062-bc958520e228)

I think this is not round-trippable?

**Acceptance**
- [x] Change exported data to use `sml`, etc., instead of the full name.

**Comment by mikeapp** [comment]
Looking at this again, it is correct.  These are OIDs/Parent Objects being exported.

**Comment by MaggieZhaoYale** [comment]
![Screen Shot 2022-09-14 at 11.20.09 AM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/abd88297-4e97-4e33-ab6a-94cc9ed70b89)
The parent export csv/excel displays the admin_set as the code, not the full name.

**Comment by MaggieZhaoYale** [comment]
Ready to review: https://github.com/yalelibrary/yul-dc-management/pull/1067

**Comment by K8Sewell** [comment]
Release [v2.59.62](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.62) deployed to Test

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Looks good in UAT :)
