### ISSUE TITLE
Create ticket to update DCS homepage

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2208]
**Story**

Now that more units across the library are represented in DCS, we should update the Highlights section on the DCS homepage to reflect collections from across the library, not just BRBL. 

**Acceptance**
- [x] Identify collections across the library to add to the highlights section
- [x] Source representative images 
- [ ] Finalize images, captions, actions to take on links, and alt text
- [ ] Update the highlights to include the new collections

See this document for notes on images etc. https://docs.google.com/document/d/1q7EqFheYSTkSyPPtCLDWH4ZYsQL_DIj3pzzqYKun8Gs/edit?usp=sharing

**Comment by motropuk** [comment]
Alison, Summer and I discuss this ticket yesterday and have a path forward. 

There are currently 8 blocks available under the Highlights section on the DCS homepage. Discounting SML, there are also then 8 units/libraries represented in DCS. So we will use one block on this highlights page for each of the libraries represented in DCS. We will also commit to updating the collection selected to be added here by each unit, on a quarterly basis. @alisonclemens will put together some ideas for featured collections / hero images for each of the repos, working with the folks actually at the repos, and report back

**Comment by DraxIndustries79** [comment]
This is more of a long-game ticket as it requires stakeholder feedbackl

**Comment by DraxIndustries79** [comment]
Alison following up Monday 12/5 and will move forward depending on if they reply.
