### ISSUE TITLE
Create placeholder management menu item and overview page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2212]
**Story**

Once naming has been decided, create an overview page and left menu link in Management for the new feature.

"Permission Sets"

**Acceptance**
- [x] Left menu item
  - [x] Label TBD
  - [x] Position beneath "Admin Sets"
  - [x] Only visible to System Admins, and admins or approvers of one or more Permission Sets
- [x] Menu item links to an overview page that lists all all Permission Sets (name TBD) that the user has access to
  - [x] List can be a list or table sorted alphabetically by the set's `label` (we'll refine the UI later)
  - [x] **System admins** can see all
  - [x] Permission set admins and approvers can see only their sets

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1073

**Comment by martinlovell** [comment]
In release v2.59.65

**Comment by sshetenhelm** [comment]
Really minor, but could we please switch the order of "label" and "key" so it matches the order of the "Sets" columns?
