### ISSUE TITLE
Implement management permissions model

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2213]
**Story**

Implement permissions model for Open with Permission using cancancan / rolify.

**Acceptance**

- [x] Create a `PermissionSet` model with the following properties
   - [x] label (text)
   - [x] key (text)
   - [x] max_queue_length (integer, default 10)
- [x] ...and add methods to add/remove users in these roles, similar to the pattern in `AdminSet`:
  - [x] `approver` 
  - [x] and `administrator` 

Create the following abilities:
- [x]  **System admins** have permission to create new Permission Sets
- [x] Permission Set Admins can 
   - [x] view the set's admin page
   - [x] add approvers
   - [x] remove approvers
   - [x] edit properties such as the max request queue length 
   - [x] ...also do anything an Approver can
- [x] Permission Set Approvers can
   - [x] view the set's approval page
   - [x] change the approval status of a request (approve/reject/revoke approval)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1071

**Comment by K8Sewell** [comment]
Release [v2.59.64](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.64) deployed to Test

**Comment by jpengst** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Apologies; where would this be implemented/controlled in UAT?

**Comment by jpengst** [comment]
There isn't anything visible on the front end w/ this ticket.
