### ISSUE TITLE
Nightly report of broken parent and child objects

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2214]
**Story**
As a staff member, I would like to know 
- the OIDs of parent objects that have failed child objects
- the OIDs of the failed child objects within those parents

I would like to be able to check this in the Management App. 

Currently, staff can see some information about failures via the following ways:
- In Child Objects table, put a parent OID in, and sort by width / height, because broken child object files don’t have widths and heights. However, this requires someone to know the specific parent OID is broken. 
- If performing a batch process, broken parents will show as failures in the batch process details. 
- For System Admin users, by reviewing the Delayed Job Dashboard (although this is not very user friendly). 

**Acceptance**
Create an ActiveJob that will be scheduled to run nightly that will perform the query and email results.

- [ ] Set up email
  - [ ] Create a Parameter Store parameter for INGEST_ERROR_EMAIL in all clusters
  - [ ] Set @sshetenhelm 's address as the recipient
- [x] Create a job
  - [x] Job should log a message and and end if INGEST_ERROR_EMAIL is not set
  - [x] The job should run a query to return: admin set, parent OID, child OID for objects where child OID width or height is `null` or `0`
  - [x] Order results by admin set, parent OID, child OID
  - [x] Create a CSV with the results
  - [x] Email CSV to the INGEST_ERROR_EMAIL address

**Comment by martinlovell** [comment]
PR for report and running report manually.  For sys admins only:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/8399d221-6b6b-4722-80eb-e6179923f5c1)
https://github.com/yalelibrary/yul-dc-management/pull/1079

**Comment by martinlovell** [comment]
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/340c3d3f-f513-4351-a983-8fbfcefc75d3)

**Comment by martinlovell** [comment]
PR for management to automate report run and email the report.

https://github.com/yalelibrary/yul-dc-management/pull/1080

**Comment by martinlovell** [comment]
The report can be viewed, and it is scheduled to run at 1AM on UAT

The email environment variable work is not complete in camerata yet or set in parameter store, but please provide feedback on the report itself and the page to view them, and verify the nightly job is running, etc.
