### ISSUE TITLE
Review Blacklight bookmark/favorites implementation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2216]
**Story**

Blacklight has a bookmark feature that was removed from our UI.  Is it suitable for our requirement to allow users to save a list of items?

**Acceptance**
- [x] Create a throwaway account at https://demo.projectblacklight.org
- [x] Experiment with bookmarking content
- [ ] Make implementation ticket

**Comment by alisonclemens** [comment]
I think this is a fine start, although in the demo environment the Email and Cite features don't seem to be working. But if those are resolved in a production environment, I think this would be a good starting point. In the future we may want to add functionality, but we can wait to roll this out and hear from users before considering that. I think this gives us a good starting point

**Comment by sshetenhelm** [comment]
I suggest we comment with feedback after reviewing and unassign ourselves to get this moved across the board. 

I agree with Alison, this looks like a good starting point. We would potentially want to integrate a feature that allow users to reorder based upon their own priorities.

**Comment by ucancallmealicia** [comment]
Agree with everyone else that we should implement this

**Comment by motropuk** [comment]
Wait for @mikeapp to write follow up tickets to implement

**Comment by mikeapp** [comment]
See #2255
