### ISSUE TITLE
Suppress full text snippets for Yale Community Only items

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2220]
**Story**

See #2217

**Acceptance**
- [ ] Full text snippets do not display in the results list if the item's permission is not public and the user is not logged in.

**Comment by mikeapp** [comment]
It would be great to exclude these fields before the documents are rendered since there are multiple possible formats (HTML, JSON, ...)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/834

**Comment by K8Sewell** [comment]
Release [v1.60.42](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.42) deployed to Test

**Comment by mikeapp** [comment]
Difficult to UAT since I am on campus.  There is no private/full text content on staging.

Searches work normally on UAT, so will go ahead and deploy.
