### ISSUE TITLE
Add 'Digitization Funding Source' to Export Parent Objects job from admin set

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2221]
**Story**

Following on from #2199, we need to make sure that Digitization Funding Source is included in the Export Parent Objects job that is triggered via the admin set menu. 

**Acceptance**
- [ ] When running an Export Parent Objects job from the admin set in DCS, Digitization Funding Source is included

**Comment by jpengst** [comment]
Looks like this work has already been completed by @martinlovell

**Comment by sshetenhelm** [comment]
Confirmed that this works in UAT.
