### ISSUE TITLE
[DISCUSS]: Child Caption Search Improvements

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2223]
Discussion in #2181

When doing a keyword search for "percement de l'Avenue de l'Operas, Paris, 1877" and opening the resulting parent, you are directed to https://collections.library.yale.edu/catalog/1619594 which contains your search term in the caption

- [x] Discuss and make design decisions
- [x] Create Ticket: Make wireframes
- [x] Create Ticket: Get feedback from public services
- [ ] Create Ticket to Create tickets for work

Meet:  Thursday 10/27

**Comment by DraxIndustries79** [comment]
On Hold till Jonathan is back, unless Summer can move it forward.

**Comment by DraxIndustries79** [comment]
**Notes:**https://docs.google.com/document/d/1XuO7JhGdGTZlv54ths7dh_GwHOczuzH64pffhivUkmg/edit?usp=sharing
Tickets to create:
- [ ] Make branch indexing both caption and label to test search results @mikeapp 
- [ ] Test results with different admin sets @alisonclemens
