### ISSUE TITLE
Fix pending specs in management & blacklight

### ISSUE THREAD

**Issue by AKFosterDev** [yalelibrary/YUL-DC#2225]
Due to the M1 fixes some specs were marked pending. This is a chore to go back and rework these pending specs.

**management**
- [x] /spec/jobs/generate_pdf_job_spec.rb:40 
- [x] /spec/jobs/generate_pdf_job_spec.rb:56

**blacklight**
- [x] /spec/system/date_slider_spec.rb:109

**Comment by K8Sewell** [comment]
PR for Blacklight ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/840

**Comment by K8Sewell** [comment]
PR for Management ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1086

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.70](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.70)
