### ISSUE TITLE
Create Permission Set "Admin Page" / edit form

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2226]
**Story**

As the administrator of a permission set, I'd like to be able to access a page where I can make administrative changes such as adding/removing approvers or adjusting the maximum site of the request queue.

**Acceptance**
- [x] Create a form page that displays with following data about the Permission Set:
  - [x] Label
  - [x] Key
  - [x] Max request queue length
  - [x] List of users
  - [x] List of approvers
- [x] Allow users with System Admin privileges to create a new Permission Set using this form.
- [x] Allow users with admin privileges to edit an existing set and save the data
- [x]  Link to this form on the overview page created as part of issue 2212:
  - [x] At the top of the page add a "Create a new Permission Set" button that is visible only to System Admins
  - [x] Display a link to the form (with the text "edit") next to each Permission Sets if the user has admin access to the set

**Comment by DraxIndustries79** [comment]
Mike is making a ticket for the edit functionality

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1077

**Comment by martinlovell** [comment]
v2.59.67
