### ISSUE TITLE
Share Structure Editor Demo to Beinecke DSU

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#2228]
Demo from [#2190](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2190) needs to be shared with Beinecke DSU for feedback.

Decided sharing the video demo was a good first step to get feedback on visual.

**Acceptance:**
- [x] Share video with Beinecke DSU
- [x] Summarize responses
- [x] Create any necessary tickets from feedback
- [x] Respond to stakeholders who submitted feedback

**Comment by sshetenhelm** [comment]
Video shared via DCS listserv and forwarded with a personal message/request for feedback to specific stakeholders. 

Requested feedback by Friday, October 7th.

**Comment by sshetenhelm** [comment]
Received feedback from three stakeholders.
Feedback available in this google doc: https://docs.google.com/document/d/1rUGVJnMsJz2IykkWp79Tk0_E_MjLNHL-wyKUwtVxnD4/edit?usp=sharing

**Comment by DraxIndustries79** [comment]
Check in with Summer when she's back re: next steps

**Comment by sshetenhelm** [comment]
**Questions that could become development tickets if answer is no:**
- Is there a limit to the amount of hierarchy levels?
- Can we add things later to an existing structure?
- Can we delete an existing structure later?
- Could we be able to link between different objects?

**Questions for non-development tickets**
- What are the policies around use? What structures should be identified?

**Questions for development not embedded in structure editor**
- Will the annotation feature also be rolled out in the future?
- Can METS XML be used to create structure outside the editor?
