### ISSUE TITLE
BUG: Container Grouping Incorrect on Metadata Cloud

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2229]
See container grouping on: 
https://metadata-api.library.yale.edu/metadatacloud/api/aspace/repositories/11/archival_objects/3107292?mediaType=json

The metadata cloud record is incorrect:
It contains: `Box 148, folder 4498 | Box 299, folder 2780`
It should be grouped like this: `Box 148, folder 2780 | Box 299, folder 4498`

This is causing a problem with DCS:
See incorrect container grouping: https://collections.library.yale.edu/catalog/10190007
vs correct on Archives Space: https://archives.yale.edu/repositories/11/archival_objects/3107292
(This is also causing metadata issues in Quicksearch)

The problem may occur on any archival objects with more than one top container.

- [ ] Create a ticket to update the metadata for all parents in DCS associated with archival objects which have more then one top container.  The list of archives space IDs (and maybe oids) can be generated using the archives space database by looking for archival objects with more than one top container and a digital object.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/metadata-cloud/issues/427
https://github.com/yalelibrary/metadata-cloud/pull/428

**Comment by sshetenhelm** [comment]
Looks good on UAT.
