### ISSUE TITLE
Batch update child captions and labels via batch process

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2234]
**Story**
As a staff member, I would like to update the captions and labels of multiple child objects at one time without reassociating them with another parent.

Currently, if I run a Reassociate Child OID batch process, I can update captions and labels only if I move the child to a new parent. This is problematic if a parent only has one child, because moving the child causes the parent to redirect, and the child cannot be re-attached. 

Currently, when I run the process, I get the following results:

- An error stating the parent and child oid are already attached, when I use the existing parent OID
- An error stating there is no parent oid, if I leave the parent oid blank
- An error stating I cannot return the child to the original parent, if I have moved it from a parent with only one child to a different parent and try to move it back, as the original parent has now been redirected

I would like to update child captions and labels while having the child remain attached to the same parent.

**Acceptance**
- [x] Investigate and make recommendation on approach below

- [ ] Update 'Reassociate child oids' batch process to allow for child labels and captions to be updated if the parent oid field is left blank or is the current parent

OR

- [x] Create a new 'Update child caption and label' batch process that only updates child captions and labels

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1082

**Comment by MaggieZhaoYale** [comment]
Confirmed the enhancement in the test.

**Comment by MaggieZhaoYale** [comment]
Looks good in UAT

**Comment by MaggieZhaoYale** [comment]
Released management v2.59.69

**Comment by sshetenhelm** [comment]
Batch process updated captions and labels, but in the Batch Processes table, it does not show the admin set for the parents. Would it be possible to have the admin set display in the batch process table like for the other processes?
 ![Screen Shot 2022-10-21 at 2.16.48 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/1e7f7692-4d74-4df0-bf3c-76bc46a2fecd)

**Comment by jpengst** [comment]
PR for admin set:  https://github.com/yalelibrary/yul-dc-management/pull/1085

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.70](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.70)

**Comment by mikeapp** [comment]
looks good on UAT
![Screen Shot 2022-10-31 at 1.33.50 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/6663bd1f-466e-48b4-8cf1-776730f39e8e)
