### ISSUE TITLE
[bug] Unicode character (Arabic) preventing PDF from generating 

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2236]
PDFs are not generating for some objects that include Arabic unicode characters (ex. [32259802](https://collections.library.yale.edu/catalog/32259802)).

The Delayed Job Dashboard shows the following error:
![Screen Shot 2022-10-04 at 11.23.48 AM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/ffeee8c1-050b-490c-b599-99fcb140740c)

We would like the PDF to generate for these objects and handle Arabic fonts accordingly. 

**Acceptance:**
- [x] Implement solution where a box is shown for characters that won't render

**Comment by martinlovell** [comment]
Maybe this: https://stackoverflow.com/questions/51481600/handle-many-unicode-caracters-with-pdfbox
or try FOP: https://github.com/apache/xmlgraphics-fop

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-pdf-gen/pull/16

Also, exploring expanding merging the font files together to eliminate the code changes above and will report back if I can sort that out.

**Comment by martinlovell** [comment]
Working on testing this.  I tried the new sample json with the old jar and it worked, so I think the title might not have the character that it fails on.  (Not all Arabic text fails.  It's just a few characters that cause the issue.)

**Comment by martinlovell** [comment]
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/42e8f760-747c-47d4-b7c7-92641b6c9280)

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/71e4fb8c-7d60-407d-82f6-d082fa82d8c6)

**Comment by DraxIndustries79** [comment]
@sshetenhelm will check with Robin

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.3](https://github.com/yalelibrary/yul-dc-pdf-gen/releases/tag/v1.3)

**Comment by sshetenhelm** [comment]
**Update from Robin after seeing screenshot**
The characters have become disjoined and the entire string is displaying in the wrong direction. The presence of the square box is the LEAST of our problems! **If this is the result, it’s far, far better to suppress the Arabic script entirely.**

So we would need to either 
[a] just suppress the Arabic and only show whatever Romanized information is available or 
[b] get the PDF to correctly display text from right to left.

**Comment by K8Sewell** [comment]
PR to use new pdf gen jar file in management - https://github.com/yalelibrary/yul-dc-management/pull/1112

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.78](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.78)

**Comment by K8Sewell** [comment]
Parent Object 32259802 exists in incomplete status in [Test](https://collections-test.library.yale.edu/management/parent_objects/32259802) and [UAT](https://collections-uat.library.yale.edu/management/parent_objects/32259802).  I saw it was in Bienecke on production blacklight but couldn't confirm it on production management because I don't have access.  I could use help from someone with access to confirm what admin set [32259802](https://collections.library.yale.edu/catalog/32259802) this is actually part of so I can test if the fix deployed works once I get the object's metadata.

**Comment by martinlovell** [comment]
You can take a random working parent and set it to use Voyager as the authority and set the bib to `12178872` and the barcode to `39002091639691` and it should get the right metadata. (It will keep the old children.)

**Comment by martinlovell** [comment]
PDFs look good.  It's not possible to test this specifically since we no longer send R-to-L text to the PDF generator.

**Comment by K8Sewell** [comment]
Deployed to UAT
