### ISSUE TITLE
Remove versions from setup_remote_docker

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2240]
I received an email from Circle CI about removing the docker version from our Circle CI configuration's setup_remote_docker:

See info here: https://discuss.circleci.com/t/setup-remote-docker-architecture-change/45303?mkt_tok=NDg1LVpNSC02MjYAAAGHPYyhaRvSKDSnQk7Cn8rU9N9RbKBdzn1Kb_hK8aGZKUeQOdgUFsoYcjtLNtACxvzFjS8N-wiyqmZx-WuCWyzZboIh7g1I38OnWIxQAMvaeIFN4w

The email suggests removing the docker version from setup_remote_docker commands.

**Comment by MaggieZhaoYale** [comment]
Released blacklight v1.60.45
Released management v2.59.69
