### ISSUE TITLE
Metadata cloud sync failing for holding records in Walpole

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2241]
**Story**

The Walpole library is currently updating some of its parent objects in DCS, to include both the bib and holdings IDs for the metadata for these objects in Voyager. 

These updates appear to be failing. See this batch for example https://collections.library.yale.edu/management/batch_processes/10167. 

While the parents are being updated to include the current bib ids and holdings ids, the night syncs to refresh metadata from these parents does not appear to be happening. 

Many of the parents in these updates appear to have not completed properly, and include a metadata cloud error e.g https://collections.library.yale.edu/management/batch_processes/10167/parent_objects/10727380 

**Acceptance**
- [ ] Syncs to Walpole parents that have been updated to include both parent and holdings ID in Voyager, successfully update when changes have been made in Voyager

**Comment by martinlovell** [comment]
It looks like it's related to high volume requests for Voyage records.
We have 40 workers simultaneously pulling voyager records, which is causing problems.

I can reproduce it on UAT, so I will work on it there.  It may be that there is some kind of deadlock getting the connections to voyager.

**Comment by martinlovell** [comment]
Metadata Cloud was updated in UAT

See job: https://collections-uat.library.yale.edu/management/batch_processes/1205

(there are still some issues in the batch statuses, but the metadata cloud errors are gone and the objects are fully updated with authoritative metadata populated with voyager data.)

A job from before the fix with the same CSV shows the errors: https://collections-uat.library.yale.edu/management/batch_processes/1204

E.g: 
Before: https://collections-uat.library.yale.edu/management/batch_processes/1204/parent_objects/11001517
After: https://collections-uat.library.yale.edu/management/batch_processes/1205/parent_objects/11001517

Metadata cloud deploy is scheduled for next Wednesday (Oct 19)

**Comment by motropuk** [comment]
Working in UAT. Will tell Walpole the fix will go into production on Weds

**Comment by martinlovell** [comment]
@motropuk and @sshetenhelm 
Metadata cloud has been deployed, so Walpole sync should work now.
It would probably be easiest to update them all by admin set if it won't cause too much of a job backup rather than re-running all the spreadsheets with failures.
