### ISSUE TITLE
[Discussion] Develop guidance around use of structure editor

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2243]
**Placeholder -- feel free to edit**

Users want guidance and/or "policies" for when and how to use the Structure Editor feature. 

See #2228 for structure editor feedback. 

Feel free to flesh out ticket as needed.

**Comment by motropuk** [comment]
We will start some documentation for the feature which will include use cases etc, and distribute/office hour

**Comment by motropuk** [comment]
@motropuk will create a new ticket to create this actual documentation

**Comment by motropuk** [comment]
Follow up ticket #2246
