### ISSUE TITLE
RSpec Test Failing CI (Sometimes)

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2244]
`rspec ./spec/system/batch_process_detail_spec.rb:146` is failing sometimes in CI.

See: https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-management/5832/workflows/f1a33208-3065-4652-a885-25b34e19d65d/jobs/12179 and
https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-management/5812/workflows/525877f7-01e2-432c-9308-3a53d298bcd2/jobs/12134

It is probably related to the order of the tests.  Rerunning the tests usually works.

- [x] Fix the test so that it will not cause a key violation

**Comment by MaggieZhaoYale** [comment]
Released management v2.59.69
