### ISSUE TITLE
[Bug] Digital Collections home link in Blacklight points to PROD across all environments

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2245]
**Story**
Currently, the Digital Collections home link in TEST and UAT that appears to the top left of the search results page points to the PROD environment. 

Staff would like to stay in the same environment when they are working within a particular environment in blacklight.

**Screenshot**
![Screen Shot 2022-10-20 at 9.48.13 AM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/9f804b22-7255-4cbe-b6d6-cbae746b1667)

**Acceptance**

- [ ] Update link on TEST to point to TEST home page
- [ ] Update link on UAT to point to UAT home page

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/841

**Comment by K8Sewell** [comment]
Looks good on test 
https://images.zenhubusercontent.com/242185115/74f50bb4-1113-4372-a0a2-94371438c0d4/screen_recording_2022_11_01_at_03_55_57_pm.mp4

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you :)
