### ISSUE TITLE
Create documentation for Structure Editor

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2246]
**Story**

Following on from #2243, we decided to create draft documentation for the structure editor (as it exists now) that outlines how to use the editor, and the use cases the editor was designed to support. This will not indicate this is policy, at least not yet, but will outline which objects it would be best to use the editor for. 

This would be a Google doc as end-user documentation.

**Acceptance**
- [x] Documentation drafted

**Comment by sshetenhelm** [comment]
First draft of documentation completed and available at [https://docs.google.com/document/d/1Hno5z5XuxkfzvC7ZOxJydRbrPcJ6ulOg0orQ23Jdf4Q/edit?usp=sharing](https://docs.google.com/document/d/1Hno5z5XuxkfzvC7ZOxJydRbrPcJ6ulOg0orQ23Jdf4Q/edit?usp=sharing)

Follow-up work created in #2270 to update, review, and share once feature is officially ready.

**Comment by motropuk** [comment]
Documentation looks great! Thanks Summer. We can close this ticket
