### ISSUE TITLE
Don't try to send report email if recipient not set

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2247]
The Problem Report nightly email is send (attempted), even if the email recipient is blank.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1084

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.70](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.70)
