### ISSUE TITLE
Improve design of Parent Object display page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2251]
**Story**

The Parent Object display page in Management contains a large number of data fields and it can be hard to locate the data that you are interested in.   Improvements to the page design are needed.

**Acceptance**
- [x] Get feedback from stakeholders re: page layout/design
- [x] Get feedback from users re: grouping of fields on the page
- [x] Propose one or more new designs for this page

**Comment by tmacmath** [comment]
Waiting for feedback from one more user - two have already responded. The third user usually has really helpful suggestions, so I'm waiting for his.

**Comment by tmacmath** [comment]
Setting up a meeting with Stephen, Leigh and Cliff to discuss optimal grouping/arrangement of fields
