### ISSUE TITLE
Merge Structure Editor to main branch

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2252]
**Story**

We're ready to merge the structure editor and deploy it to production.

**Acceptance**
- [ ] Merge structure editor to main branch

**Comment by martinlovell** [comment]
v2.59.71

**Comment by K8Sewell** [comment]
Looks like it's working as expected on Test

https://collections-test.library.yale.edu/catalog/800052578

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by mikeapp** [comment]
Looks good on UAT.
