### ISSUE TITLE
Bump nokogiri

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2254]
**Story**

See automated PRs for Management and Blacklight

**Acceptance**
- [x] Management
- [x] Blacklight

**Comment by martinlovell** [comment]
v2.59.71

**Comment by K8Sewell** [comment]
Blacklight - deployed to test in release [v1.60.47](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.47)

**Comment by K8Sewell** [comment]
no obvious issues on test for either blacklight or management

**Comment by K8Sewell** [comment]
Deployed to UAT
