### ISSUE TITLE
SPIKE: Restore bookmark feature

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2255]
**Story**

Bookmarking was removed in #423.   We would like to revert this change in a branch so that we can see what the default behavior would look like in our modified UI.  I expect that we will then need to review the design.

**Acceptance**
- [x] Turn the bookmark function back on
- [x] Test behavior locally if possible to validate that bookmarked items are saved
- [x] Attach screen shots to allow for a design discussion.

**Comment by jpengst** [comment]
Index View:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/b5cf9d0e-2227-4f9a-b4b4-711a99ea54d8)

**Comment by jpengst** [comment]
Showpage bottom toolbar:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/8aec1761-4292-4086-8ec3-5dd4e5a91f4d)  
  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/e5a26325-3470-448e-9262-e16db6fe62a8)

**Comment by jpengst** [comment]
/bookmarks page:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/24999b1f-14c5-4787-acb7-7695f632c264)
