### ISSUE TITLE
DISCUSS: Impact of Auth0 work

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2256]
**Story**

Yale will be undertaking a project, aimed to complete in Summer 2023, to replace the current single sign on solution used to allow non-Yale patrons can be authenticated to use Aeon and the current solution used to control access to the Kissinger collection. The current solution for this is end of life. The new solution will be Auth0 https://auth0.com/ 

The DCS team need to discuss how the implementation of Auth0 impacts/delays the work we are doing for Open with Permission. Mike will know more about this by our next sprint (Nov 1-7), so we should have this discussion then

**Acceptance**
- [ ] DCS team understands the impact of Auth0 work and understands what work can continue and what if anything needs to be put down until this implementation is complete.

**Comment by DraxIndustries79** [comment]
Friday 11/4 after standup

**Comment by mikeapp** [comment]
Created #2271 to capture questions as we move forward.
