### ISSUE TITLE
Bookmark UI redesign

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2257]
**Story**

The bookmark functionality from Blacklight can be turned on again, but it needs design work.

See #2255 for screen captures of our current UI with the feature turned on.

**Acceptance**
- [x] Look at other examples [?]
- [x] Produce new design
- [x] Accessibility of check box vs. link
- [x] Create implementation tickets.

**Comment by tmacmath** [comment]
@mikeapp This is what the current experience looks like in Quicksearch - I believe I designed this a while back.![Screen Shot 2022-11-03 at 10.21.40 AM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/3859480d-222c-4187-977d-49c1a4bf8949)

**Comment by tmacmath** [comment]
I really like this interface and the way the save/like links appear on mouseover: 

https://www.europeana.eu/en/search?page=1&query=&view=grid

**Comment by tmacmath** [comment]
Doing some sketching

**Comment by tmacmath** [comment]
This is the first mockup - I'm creating a couple of others. There is one issue I will need to research further with this mockup (related to functionality).![Bookmark-UI-mockup-template.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/d2b65cd1-86eb-41ea-8fae-873332c538ea)

**Comment by tmacmath** [comment]
Two more concepts are attached below: in the first, we would keep the default OOB placement of the bookmark form select. In the second, it would be placed below the metadata. ![Bookmark-UI-mockup_v2.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/f3a1b05d-81f6-4b18-bf9c-d288c4408670)![Bookmark-UI-mockup_v3.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/59e9823a-09a8-449a-a51d-7c14327bd2fb)

**Comment by tmacmath** [comment]
I feel like either one of the latter two would make implementation easiest - there would be no styling necessary. I do like the clean look of the link as opposed to the select box, but that's just my opinion.

**Comment by tmacmath** [comment]
The Bodleian Library does not use any text at all - they just use a pushpin icon:![Screen Shot 2022-11-11 at 3.14.10 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/493803db-7b7b-4152-b2fc-298d3378cded)

**Comment by tmacmath** [comment]
Two more options: OOTB bookmark functionality, but placed below metadata fields![Bookmark-UI-mockup-below-metadata.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/e9d66cb8-7830-4236-b3e6-26c325f1476e)![Bookmark-UI-mockup-bookmarked-state.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/8236001e-2455-483a-b808-3fec00c8d87e)

**Comment by tmacmath** [comment]
I think the only other issue is whether or not the language should be consistent with Quicksearch - they are using "Save to list" instead of "Bookmark". I don't really sure if users are able to create lists in the DL, though. I'm fine with leaving it as "Bookmark/s".

**Comment by tmacmath** [comment]
With regard to accessibility, I think a check box is nice to have because a screen reader will announce state (whether or not a box is checked or unchecked). It's pretty clear to someone using a screenreader: 

https://www.youtube.com/watch?v=bJx-LA2x_jQ&t=28s

**Comment by tmacmath** [comment]
I think what we should do is to turn on the default bookmark functionality and then evaluate it. The Blacklight UX group has done a lot of accessibility work, so I don't want to change anything if it's not needed. I will evaluate when it's implemented.

**Comment by tmacmath** [comment]
Ticket has been created (#2299).

**Comment by DraxIndustries79** [comment]
@tmacmath You can look at Demo

**Comment by tmacmath** [comment]
@K8Sewell Okay, so this is worth a try - I moved the div with the bookmark form below the h3 (inside the document_header row div) and this is what it looks like now: ![Screen Shot 2022-11-29 at 2.23.52 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/9810c592-4ff2-4ea1-8f0d-214ff18d140a)

**Comment by tmacmath** [comment]
Also - is there a reason the header tag was changed to a div tag? 

![Screen Shot 2022-11-29 at 2.58.48 PM.png](https://images.zenhubusercontent.com/604a2edec7bb2836333e6ec0/007af5d6-17a2-4788-9a5c-14b92c6fedec)

**Comment by tmacmath** [comment]
Implementation ticket created #2311
