### ISSUE TITLE
SPIKE: Display label and caption hits in search results list

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2259]
**Story**

We would like to display hits against the image label or caption on the search results page.  This is a spike so work will remain in this branch, we will test this branch to help determine next steps for label/caption searching.  

This is a follow-on from #2223

Note: Look at how full text search results are displayed for similar behavior.

**Acceptance**
- [x] If the search matches on the "Image Label" data:
  - [x] display the first matching label on the search results page
      - [x] the label should be "Image Label"
  - [x] highlight the matching text
  - [x] display the total count of matches
- [x] If the search matches on the "Image Caption" data:
  - [x] display the first matching caption on the search results page
    - [x] the label should be "Image Caption"
  - [x] highlight the matching text
  - [x] display the total count of matches

**Comment by martinlovell** [comment]
Deployed to demo:
- https://collections-demo.library.yale.edu/catalog?search_field=all_fields&q=Further+Elemental+Analyses+of+the+Vinland+Map
- https://collections-demo.library.yale.edu/catalog?search_field=all_fields&q=%22folder+971%22
- https://collections-demo.library.yale.edu/catalog?search_field=all_fields&q=%22original%22
