### ISSUE TITLE
Structure Editor integration tests

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2261]
**Story**
We should have tests to verify the Structure Editor is working in the context of the Management app.

**Acceptance**
- [ ] Create any Rspec tests needed to validate that the structure editor is working in the Managment app.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1089

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.74](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.74)

**Comment by K8Sewell** [comment]
No issues on Test.  Deployed to UAT.
