### ISSUE TITLE
Rails applications should be running in "production" mode on ECS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#227]
**ISSUE**
We're running ECS clusters in rails default environment RAILS_ENV=development.  For performance and security reasons, we should be running in rails production mode.

**ACCEPANCE**
- [x] Rails-based applications running on ECS should be started in production mode
- [x] I should get a "we're sorry..." message instead of a stack or route dump when requesting an invalid record
  - [x] e.g. when I visit https://collections-demo.curationexperts.com/foo I should not see a route list
  - [ ] e.g. when I visit https://collections-demo.curationexperts.com/catalog/foo I should not see a stack dump

**Comment by JzGo** [comment]
PR for setting PASSENGER_APP_ENV in camerata has been merged: https://github.com/yalelibrary/yul-dc-camerata/pull/37

Was able to successfully test setting the PASSENGER_APP_ENV in blacklight and reaching the standard prod default Rails error screen but not from within camerata as it relied on the blacklight and management app containers having secret_key_base configured.

**Comment by mark-dce** [comment]
You're right, we're going to need to deal with secrets in production environments.  I probably merged Pull Request #37](https://github.com/yalelibrary/yul-dc-camerata/pull/37) prematurely - I thought I'd tested it out and seen the expected blacklight responses and errors first but I either had something cached in my browser or the deployment hadn't fully stabilized yet.

Breadcrumbs for secrets:
https://guides.rubyonrails.org/security.html#custom-credentials

and the help text mentioned there
```
# bundle exec rails credentials:help
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /home/app/webapp/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Usage:
  rails credentials [options]

=== Storing Encrypted Credentials in Source Control

The Rails `credentials` commands provide access to encrypted credentials,
so you can safely store access tokens, database passwords, and the like
safely inside the app without relying on a mess of ENVs.

This also allows for atomic deploys: no need to coordinate key changes
to get everything working as the keys are shipped with the code.

=== Setup

Applications after Rails 5.2 automatically have a basic credentials file generated
that just contains the secret_key_base used by MessageVerifiers/MessageEncryptors, like the ones
signing and encrypting cookies.

For applications created prior to Rails 5.2, we'll automatically generate a new
credentials file in `config/credentials.yml.enc` the first time you run `rails credentials:edit`.
If you didn't have a master key saved in `config/master.key`, that'll be created too.

Don't lose this master key! Put it in a password manager your team can access.
Should you lose it no one, including you, will be able to access any encrypted
credentials.

Don't commit the key! Add `config/master.key` to your source control's
ignore file. If you use Git, Rails handles this for you.

Rails also looks for the master key in `ENV["RAILS_MASTER_KEY"]`, if that's easier to manage.

You could prepend that to your server's start command like this:

   RAILS_MASTER_KEY="very-secret-and-secure" server.start

=== Editing Credentials

This will open a temporary file in `$EDITOR` with the decrypted contents to edit
the encrypted credentials.

When the temporary file is next saved the contents are encrypted and written to
`config/credentials.yml.enc` while the file itself is destroyed to prevent credentials
from leaking.

=== Environment Specific Credentials

The `credentials` command supports passing an `--environment` option to create an
environment specific override. That override will take precedence over the
global `config/credentials.yml.enc` file when running in that environment. So:

   rails credentials:edit --environment development

will create `config/credentials/development.yml.enc` with the corresponding
encryption key in `config/credentials/development.key` if the credentials file
doesn't exist.

The encryption key can also be put in `ENV["RAILS_MASTER_KEY"]`, which takes
precedence over the file encryption key.

In addition to that, the default credentials lookup paths can be overridden through
`config.credentials.content_path` and `config.credentials.key_path`.
root@a38b96feddce:/home/app/webapp# 
```

**Comment by mark-dce** [comment]
It looks like `config/credentials.yml.enc` was generated during the [initial commit of the blacklight app](https://github.com/yalelibrary/yul-dc-blacklight/blob/master/config/credentials.yml.enc), so the committer might have the original master.key file in their local environment.  

Same for the [initial commit of the management app](https://github.com/yalelibrary/yul-dc-management/blob/master/config/credentials.yml.enc).

Master keys are excluded from git by the default .gitignore generated by rails - https://github.com/yalelibrary/yul-dc-management/blob/091ef33c0a074e2ae00f8db7f791bde12d9b6531/.gitignore#L29

In-lieu of recapturing the initial master keys, we could generate a single new master key and use it to re-encrypt `config/credentials.yml.enc` for both the blacklight and management apps.  It looks like we'll need to figure out a mechanism to securely distribute the `master.key` file to folks that need.

**Comment by mark-dce** [comment]
As a start, I generated new `config/credentials.yml.enc` files for the blacklight and management apps - here are the corresponding PRs:  
https://github.com/yalelibrary/yul-dc-blacklight/pull/115  
https://github.com/yalelibrary/yul-dc-management/pull/62  
I'll share the corresponding RAILS_MASTER_KEY via private slack

Here's a sketch of how to inject a locally set RAILS_MASTER_KEY into the container environments
https://github.com/yalelibrary/yul-dc-camerata/compare/fix-passenger-error
This lets you do something like 
```
RAILS_MASTER_KEY=1234567890123456 docker-compose up blacklight
```

With those changes, Passenger no longer gives errors, but then I hit database errors like:  
```
ActionView::Template::Error (FATAL:  database "blacklight_yul_production" does not exist
):
```
I'm guessing there will be similar Solr errors related to the expected production cores not existing.

I've just been trying to get camerata launch everything successfully in production mode using `docker-compose up`.  It might be worth focusing on getting production mode working locally before worrying about deploying to ECS.

**Comment by JzGo** [comment]
Was able to get both apps running in production mode via camerata.

I have two draft PRs up addressing the errors I hit when trying to get management and blacklight running.

- `blocked host` error: https://github.com/yalelibrary/yul-dc-management/pull/71/files
-  `blacklight_yul_production doesn't exist` db error: https://github.com/yalelibrary/yul-dc-blacklight/pull/124/files

**Comment by mark-dce** [comment]
Hi @JzGo & @maxkadel -

I think Max is submitting a PR for the blocked host issue right now.

I think this PR addresses the database and encryption key (passenger errors) issues:  
https://github.com/yalelibrary/yul-dc-camerata/pull/57
