### ISSUE TITLE
Create PermissionRequestUser model

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2273]
**Story**

We need a model to capture the user data for requests to access open-by-permission items.

**Acceptance**
- [x] Create a model `PermissionRequestUser`
- [x] Add properties from https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims (see types listed there)
  - [x] `sub`
  - [x] `name`
  - [x] `email`
  - [x] `email_verified`
  - [x] `oidc_updated_at` (DateTime, note the prefix to distinguish from Rails updated_at)
- [x] All values are mandatory

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1090

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.73](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.73)

**Comment by K8Sewell** [comment]
No issues on Test.  Deployed to UAT.
