### ISSUE TITLE
[DISCUSS] Plan TIFF downloading from DCS

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2280]
**Story**

We need to resurface an initial discussion we had about providing the ability for patrons to download TIFFs from DCS (see #1200). This need continues to be expressed as a priority requirement by our access services staff. This is a goal for DCS for FY23, so we need to plan this work in more detail and create tickets for active development work. 

**Acceptance**
- [ ] Discuss and decide on path forward
- [ ] Create tickets for active development work

**Comment by mikeapp** [comment]
So I don't forget: we should look at AWS WAF Bot Control as a CAPTCHA service/bot blocker.

**Comment by DraxIndustries79** [comment]
Friday 12/2
