### ISSUE TITLE
Downloading guidelines in End User Documentation

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2281]
**Story**

Access Services staff have requested guidelines that they can point patrons to that outline:
- The different size/quality options that can be downloaded from DCS (Reduced Size, Full Size and PDF) for a digital object
- That full size JPEG image is publication quality
- The steps for how to download an image from DCS via UV
- The steps for downloading a PDF of a digital object in DCS

Once we have something drafted we should share with Mary-Ellen Budney, Genevieve Coyle, Steve Ross and Mark Custer for review

**Acceptance**
- [x] Documentation drafted
- [x] Send draft to staff listed above
- [x] Incorporate suggested changes
- [ ] Send final version of documentation to staff above and flag in digital collections newsletter

**Comment by sshetenhelm** [comment]
Updates created based on stakeholder feedback. Sent to stakeholders for round 2 of feedback.
