### ISSUE TITLE
[bug] Management PROD workers - execution expired

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2285]
Various jobs in Management Prod have been failing with the following message:

`execution expired (Delayed::Worker.max_run_time is only 7200 seconds)`

**Example job IDs include the following:** 
19698185 & 19688865 (Generate PDF Jobs for object 32410579)
* For this object, PDF is not available -- "Item not found" page displays when clicking on link to PDF
* Object has 37 children
**EDIT 2022.12.14 --** Received a worker timeout yesterday after doing a super large ingest from Goobi. Error message added to bottom of ticket.

This also happened for [Batch Process 10151](https://collections.library.yale.edu/management/batch_processes/10151) when a user attempted an “export all parent objects by admin set” batch process with an empty template (header row but no data). 

[Full error message here](https://docs.google.com/document/d/1mCC0hpS6UWqABticYVp_fafgBDX1QkYZmb77qUtclhk/edit?usp=sharing) 
(apologies; won't let me upload a file)

**2022.12.14. ingest error:**
Delayed::WorkerTimeout: execution expired (Delayed::Worker.max_run_time is only 7200 seconds)

Summary
MetsDirectoryScanJob#perform

Hostname: ip-10-5-69-116.ec2.internal

Context
component: MetsDirectoryScanJob
action: perform
job_id: 19767157
handler: --- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper job_data: job_class: MetsDirectoryScanJob ...
last_error:
attempts: 0
queue: default
Trace
app/lib/mets_directory_scanner.rb:8:in `glob`
app/lib/mets_directory_scanner.rb:8:in `block in perform_scan`
app/lib/mets_directory_scanner.rb:7:in `each`

**Comment by jpengst** [comment]
Did some investigating and the images in the 32410579 object are huge (about 25,000 x 32,000 px). I'm wondering if it's timing out the PDF job for similar reasons as (2322)[https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2322] and that increasing the resources would remedy both 2322 and this ticket.

**Comment by sshetenhelm** [comment]
[https://app.zenhub.com/files/242185115/c116baf3-057d-4da1-871b-f03129a82f0b/download](https://app.zenhub.com/files/242185115/c116baf3-057d-4da1-871b-f03129a82f0b/download)

@jpengst error message is available in above file

**Comment by jpengst** [comment]
Possible PR Fix: https://github.com/yalelibrary/yul-dc-management/pull/1125

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.85](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.85)

**Comment by K8Sewell** [comment]
Could not fetch data for object 32410579 on Test.  Will promote to UAT to test where object is available.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/75c6180f-60c9-480a-9517-09b7f3ed6052)

**Comment by sshetenhelm** [comment]
Tried to test this, had some failures but suspect they are related to Goobi image uploading and not the workers. Will do another test and update.

**Comment by sshetenhelm** [comment]
Still working on this

**Comment by sshetenhelm** [comment]
Tried to recreate PTIFFs of two large objects ([2041002](https://collections-uat.library.yale.edu/management/parent_objects/2041002) and [2003431](https://collections-uat.library.yale.edu/management/parent_objects/2003431)) but received the following error message: 

![Screen Shot 2023-02-03 at 1.38.55 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/000dee89-bb07-432e-a7cd-a3a3e1dadd5c)

Yale humans, is this a result of recent changes, or does this need a Yale ServiceNow ticket?

**Comment by sshetenhelm** [comment]
Just a note to say these images resolved eventually.

**Comment by sshetenhelm** [comment]
This seems to be working now! I think we are ready to close! :)
