### ISSUE TITLE
Bump minimatch - Management

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2289]
dependabot bump for minimatch

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1094

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.73](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.73)

**Comment by K8Sewell** [comment]
No issues on Test.  Deployed to UAT.
