### ISSUE TITLE
Set up HoneyBadger for exception reporting

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#229]
**ACCEPTANCE**
- [x] We have a dedicated [Honeybadger](https://www.honeybadger.io) organization for the Beinecke project
- [x] Rails apps running on the test and demo clusters are configured to report exceptions to Honeybadger
- [x] Team-members have access to honeybadger
   - [x] Bob
   - [x] Rick
   - [x] Mike
   - [x] Mark
   - [x] McClain
   - [x] Jez
   - [x] Rachel K
   - [x] Bess
   - [x] Rob
   - [x] Max
   - [x] Dylan
   - [x] JP

**Comment by dl-maura** [comment]
Also looking at New Relic

**Comment by mark-dce** [comment]
Projects configured to report errors to HoneyBadger can be accessed at https://app.honeybadger.io/projects (using your login credentials)

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/3064318/86074498-ba5a1200-ba4b-11ea-8eff-b2d905f562a7.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/3064318/86074537-ce9e0f00-ba4b-11ea-984d-569b4c1e83e9.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3064318/86074658-f8573600-ba4b-11ea-83fa-862386fe3f21.png">
