### ISSUE TITLE
[Bug] Universal Viewer not being created in ArchivesSpace for specific object

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2294]
[Parent object 32464331 ](https://collections.library.yale.edu/catalog/32464331)was created in DCS and linked to ArchivesSpace, but the Universal Viewer did not populate in the [ArchivesSpace record](https://archives.yale.edu/repositories/11/archival_objects/3527358). We tried updating the object using the button on the Editing Parent Objects page, updating the parent via a batch process, and changing the Visibility from Public to Private and back again. 

This is currently the only example we have found for this bug. 

**Acceptance**

- [x] Parent object 32464331 displays in ArchivesSpace
- [x] Fix is in place to prevent this from happening with other objects

**Comment by martinlovell** [comment]
Metadata cloud doesn't have a record of it and the DCS db didn't store one, so I think it might be getting an error trying to send it to metadata cloud because of the title length.

I'll do some testing to verify in UAT.  We can update the field size in the metadatacloud db if that's the issue.

**Comment by martinlovell** [comment]
I updated the field type in the DB and it looks good now.

**Comment by sshetenhelm** [comment]
This looks great! Thank you so much @martinlovell :)
