### ISSUE TITLE
Create new base image build for Blacklight/Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2295]
**Story**

We should keep the Ruby/Passenger base image updates.

Base image uses phusion/passenger-ruby27:2.3.1
The newest version in Dockerhub was in October.

**Acceptance**
- [x] Build a new base image
- [x] Build new management
- [x] Build new blacklight

**Comment by mikeapp** [comment]
See #2277

**Comment by K8Sewell** [comment]
PR for Camerata - https://github.com/yalelibrary/yul-dc-camerata/pull/353

**Comment by K8Sewell** [comment]
Management - Deployed to Test with release [v2.59.76](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.76)
Blacklight - Deployed to Test with release [v1.60.50](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.50)

**Comment by K8Sewell** [comment]
Deployed to UAT
