### ISSUE TITLE
Create new IIIF Image Server image

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2296]
**Story**

We should keep up with the Java base image.

Imageserver uses openjdk:11
newest version ~August?
should build new image?

**Acceptance**
- [ ] Build a new imageseerver Docker image based on the latest  image

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/32

Once this is merged and we cut a new release that should trigger a pull of the most recent [openjdk11](https://hub.docker.com/_/openjdk/tags?page=1&name=11&ordering=-name)

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.0.10](https://github.com/yalelibrary/yul-dc-iiif-imageserver/releases/tag/v1.0.10)

**Comment by K8Sewell** [comment]
No issues found on Test

**Comment by mikeapp** [comment]
Looks good on UAT
