### ISSUE TITLE
Deploy bookmark branch to collections-demo

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2301]
**Story**

Deploy the bookmarks branch to collections-demo for Tracy to review.

**Acceptance**
- [ ] Branch deployed

**Comment by K8Sewell** [comment]
Seem to have broken demo and trying to debug - https://cm-prd.library.yale.edu/job/YUL-DC-Demo-Deploy/283/console

**Comment by K8Sewell** [comment]
Ready for review on demo

**Comment by mikeapp** [comment]
Looks good/bad :)
