### ISSUE TITLE
[SPIKE] Original Technical Metadata Included in Downloaded Images

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2308]
**Story**
Currently, when users download full-size images, the technical metadata of the image changes to reflect different information than what was recorded in the original image file. We would like the downloaded file to retain the original technical metadata, if possible. 

We would like our developers to please explore the possibility of retaining this metadata. 

It is our understanding that downloadable JPGs are being created by Cantaloupe upon request, and that it may not be possible due to the conversion process to retain the original metadata. But we'd like to look into it nonetheless!

**Acceptance**
- [ ] Determine if retaining original metadata in images after downloading is possible
- [ ] If so, make new ticket for development work

**Comment by mikeapp** [comment]
There is a setting (`processor.metadata.preserve` ?) to copy metadata from source to derivative but the docs warn that it only works for derivatives in the same format as the original, so may not work for PTIFF->JPG.

**Comment by mikeapp** [comment]
It looks like this was made configurable in Cantaloupe version 5, with an option to copy XMP metadata:  https://cantaloupe-project.github.io/manual/5.0/metadata.html.  The developer warns that selectively changing metadata is difficult but possible.

**Comment by DraxIndustries79** [comment]
Next:  @sshetenhelm should share with Mark and Access Services staff.

**Comment by sshetenhelm** [comment]
Email sent to Moira, Stephen R., Genevieve, and Mark C. requesting feedback.

**Comment by sshetenhelm** [comment]
Compiled feedback from stakeholders:

If technical metadata is included in TIFF downloads, we **do not** need to include it in the various JPG derivative downloads. 

HOWEVER

Stakeholders say it “Would be nice” to have the technical metadata separate from the image file somewhere as well (ex. “sidecar metadata file, like how most a/v files in Preservica have that type of information available in PBCore metadata files.”)

BECAUSE

“patrons in general (and many staff) are confused by what has been originally shot as a TIFF, JPG, or Bookeye PDF,” and “It would be great if it could be clear to staff whether the image needs to be shot again or if there is an existing high-res scan that is suitable for the patron’s needs.” 

**Potential next steps:**
- Create a new ticket for download TIFFs that specifies that original technical metadata should be included (apologies if this exists—I didn’t see other TIFF tickets outside of the ‘Closed’ ones). 
- Close this ticket, as we don’t need original technical metadata embedded with JPG derivative downloads. 
- Create a ticket in the backlog for looking into how to provide metadata about available files/quality, etc.
