### ISSUE TITLE
PermissionRequest API validation

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2309]
**Story**

Additional error handling for the PermissionRequest API.

Return HTTP status codes with a JSON message (based on https://jsonapi.org/format/#errors ) 

**Acceptance**
- [x] If the User (i.e., requestor) is missing from the request return HTTP 400 with the message "User object is missing"
- [x] If the User's `sub`, `name`, or `email` are missing or empty, return HTTP 400 with the message "User [subject|name|email| is missing", depending on which field is missing.
- [x] If the OID is not a valid parent OID, return HTTP 400 with the message "Invalid Parent OID"
- [x] If the parent OID has private visibility, return HTTP 400 with the message "Parent Object is private"
- [x] If the parent OID has public visibility, return HTTP 400 with the message "Parent Object is public, permission not required"

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1105

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.77](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.77)

**Comment by K8Sewell** [comment]
No obvious issues on Test
