### ISSUE TITLE
Parent visibility should not display 'Redirect' in dropdown if children are attached to parent

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2312]
**Story**

In the Management App, when a user edits a parent directly on the parent page, they have the option of selecting "Redirect" from the Visibility drop-down menu even when there are children still attached to the parent. 

This is a problem because:

- Parents cannot be successfully redirected unless there are no children attached. 
- If there are children attached, the 'Redirect URL' field does not appear.
- If an object is redirected without a URL, it does not show up in either the parent object or redirect parent object table. It is only accessible via a direct URL.

We would like to have the Redirect option not show up in the Visibility drop-down menu if a parent still has child objects attached.

**Acceptance**

- [x] Redirect does not show up on Editing Parent Page Visibility drop-down menu if there are child objects attached to a parent
- [x] Redirect still shows up on the Editing Parent Page Visibility drop-down menu if there are no child objects attached to a parent

This dropdown:
![Screen Shot 2022-12-01 at 3.58.10 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/fc43cd9a-d8ca-4995-8a0e-ada879488e10)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1107

**Comment by K8Sewell** [comment]
Looks good on Test
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8d85d703-0281-437a-b7d6-4bf59ced3e2c)

**Comment by sshetenhelm** [comment]
Looks great! Thank you! :)
