### ISSUE TITLE
[SPIKE] Explore options to add links to UV downloads panel

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2315]
**Story**

We'd like to add a link to the UV download panel that points to a URL to download the original TIFF (or triggers Javascript to do it).

**Acceptance**
- [ ] Determine what options we have, if any, in UV.

**Comment by mikeapp** [comment]
There's a UV setting that sounds promising:  `downloadDialogue` -> `content` -> `entireFileAsOriginal`

**Comment by K8Sewell** [comment]
Villanova University was kind enough to share how they provided this option for their users.  https://digital.library.villanova.edu/Item/vudl:92879/Manifest  In the sequences they leverage the rendering option to provide the link and text for downloading the entire file.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/68492251-e1e5-4bfb-97f8-bb30fc3fc7e9)
