### ISSUE TITLE
Tests should use test index (not development)

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#232]
Currently when we run tests they clobber the contents of the development index. 

- [x] Running our automated tests locally should leave the development index unchanged

**Comment by FCRodriguez7** [comment]
**A Picture of different Solr cores:** 

![Screen Shot 2020-06-16 at 1.19.16 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7f952394-f94a-4780-bcd6-810f702a17c0)


![Screen Shot 2020-06-16 at 1.19.25 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f08c10c8-17f4-4f11-aece-3010f20656ce)

**Comment by K8Sewell** [comment]
PR - ready for review
https://github.com/yalelibrary/yul-dc-blacklight/pull/143

**Comment by K8Sewell** [comment]
Merged in - https://github.com/yalelibrary/yul-dc-blacklight/pull/144
