### ISSUE TITLE
Management API to stage file for download

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2321]
**Story**

We need an API in Management that queues the job to stage a file for a download.

**Acceptance**
- [x] Create an API at `/api/download/stage/child/:oid`
- [x] If the child does not have Public or YCO visibility, return HTTP 403 Forbidden
- [x] Otherwise, queue the job as defined in #2319 and return HTTP 200 OK

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1119

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.81](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.81)

**Comment by K8Sewell** [comment]
API call results in expected JSON for when acces is allowed but still waiting to see the file actually show up in the S3 bucket
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/a23da18b-17ac-4d56-bbb2-6b81ffebc1ad)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/7e05c984-aded-43fa-b654-910b4266217b)

**Comment by K8Sewell** [comment]
We lost the bucket name at some point.  Taking this back to in progress to fix.

**Comment by K8Sewell** [comment]
Martin was able to get a few images in the 'download' bucket with the API.  This process won't work in local development.  Would we like to invest the energy to provide the functionality to local dev or should we move forward?  We would need to do something similar to - https://github.com/yalelibrary/yul-dc-management/blob/0c525b55f705d739d399219cc8cf2b61cc98a15c/app/models/pyramidal_tiff.rb#L69 - which we do have an example to draw from.

**Comment by mikeapp** [comment]
Decision was to move forward w/o implementing for local development.

**Comment by K8Sewell** [comment]
Deployed to UAT.  To test manually enter a url like this `https://collections-uat.library.yale.edu/management/api/download/stage/child/900148257` with a child oid at the end that is either part of parent that is Public or YCO.  User should get above json responses and be able to find the tiff in the s3 download bucket `yul-dc-download-uat`.

**Comment by sshetenhelm** [comment]
1. Received `{"title":"Child object staged for download."}` for Public child object 1003343

2. Received `{"title":"Child object staged for download."}` for Yale Community Only child object 1004537

I only receive the above when I am logged into MGMT UAT. If I am not logged in (like how users will not log into MGMT), I receive the `Not found. Authentication passthru.` notification. Is that expected behavior?
