### ISSUE TITLE
[Bug] Large images return 500 internal service error and will not download full size JPG

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2322]
**Story**
Parent objects with very large full size jpgs (examples below) return a 500 internal service error (java.lang.NullPointerException) when users try to load the image to download. 

Here are some examples that return the error:
- Child 1 (16793688) of parent 16793594 has a resolution of 7688 x 12200px
- Child 1 (32335538) of parent 32335537 has a resolution of 12986 x 5999px
- Child 3 (10616789) of parent 2053268 has a resolution of 37569 x 22267px
- Child 1 (16865356) of parent 2037299 has a resolution of 34311 x 23177

We would like users to be able to load and download full size JPGs regardless of size.

**Acceptance**
- [ ] Users can download large full size jpgs

**Comment by mikeapp** [comment]
I think we are still using only about half of the available memory on the system.  I think the requet-by-percentage of RAM is not working correctly, although it allocated more than we originally had.   Should we set hard -Xmx values via parameters?

**Comment by mikeapp** [comment]
The memory option for the server is currently set in the ECS docker compose template and does not use a variable.  

Recommendations:
1.  Boost RAM and CPU available to production image servers (e.g., 8GB -> 16GB).  
2. Set the `IIIF_JAVA_OPTS` for each cluster to a reasonable value using the Java `-Xmx` flag 
3. Adjust the iiif-images-compose.ecs.yml template to use the variable

**Comment by martinlovell** [comment]
PR for passing IIIF_JAVA_OPTS variable: https://github.com/yalelibrary/yul-dc-camerata/pull/357

**Comment by sshetenhelm** [comment]
https://collections-uat.library.yale.edu/catalog/16793594 child 1 (7688 x 12200px) successfully loaded after about ~5 seconds.

https://collections-uat.library.yale.edu/catalog/16719894 child 6 (37944 x 4604px) successfully loaded after ~ 10-15 seconds

Child 12 ( 90345 x 2908px) of https://collections-uat.library.yale.edu/catalog/11141252 attempts to load for approximately 5 seconds, then the little wheel at the top of my browser (Chrome, Mac OS, over Yale VPN) just stops and all I see is a white screen.

**Comment by mikeapp** [comment]
Max size is about 65K on the 90K pixel wide image.  I was able to get the system to utilize more of the available  memory but it did not seem to process a larger size.

![Screenshot 2023-02-02 at 2.10.47 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/7f32cd8f-2ac2-447c-9ed1-bf5893649490)

**Comment by mikeapp** [comment]
We may be hitting a Java limitation.  I managed to trigger an error message below, which I found discussion of here:   https://github.com/haraldk/TwelveMonkeys/issues/398

![Screenshot 2023-02-16 at 2.39.54 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/fd11f564-f7d7-4e6c-9079-fd50a2420c63)

**Comment by sshetenhelm** [comment]
So does that mean it is not possible using Cantaloupe to output a JPG larger than 65,535, or is that a configuration we made when setting it up?

**Comment by sshetenhelm** [comment]
Is this moved into 'Review on UAT' because of #2408?
