### ISSUE TITLE
Plan Kissinger Migration

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2323]
Placeholder -- Summer and Jon (at least) need to make a plan for the Kissinger migration.

- [x] Make a plan
- [x] Create tickets for work

**Comment by sshetenhelm** [comment]
[Google doc for planning](https://docs.google.com/document/d/12zmhX4pM5jcutJBzD5hanrUVPNWZBSP4feXmurBD-Qg/edit?usp=sharing)

**Comment by motropuk** [comment]
Alicia, Summer and I will meet after standup Weds this week to work on this

**Comment by sshetenhelm** [comment]
Initial planning started in Google doc. Currently try to set up meeting with stakeholders.

**Comment by sshetenhelm** [comment]
Meeting scheduled for 2023.01.26 at 9:30 am. Should we move out of this week's sprint?

**Comment by sshetenhelm** [comment]
Ticket for public 2004 material (round 1): #2366

Ticket for public 1981 material (round 2): #2367
