### ISSUE TITLE
Migrate Persian Philological Texts Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2325]
**Story**
Migrate the Persian Philological Texts Collection (PID 33) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the SML admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the SML admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 22 parents were imported in uat https://collections-uat.library.yale.edu/management/batch_processes/1269
compare to findit-uat 
https://findit-uat.library.yale.edu/?_=1670532318580&f%5Bdigital_collection_sim%5D%5B%5D=Persian+Philological+Texts
Ready to audit in UAT.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm  22 parents are in UAT https://collections-uat.library.yale.edu/management/batch_processes/1269 (ignore the error message  that image not found) 
Compare to findit -uat https://findit-uat.library.yale.edu/?_=1670591528457&f%5Bdigital_collection_sim%5D%5B%5D=Persian+Philological+Texts

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 22 parents in DCS prod https://collections.library.yale.edu/management/batch_processes/11033

**Comment by sshetenhelm** [comment]
Thanks @MaggieZhaoYale !

For parent 11396985, none of the child images came over.
For parent 11034348, child image 11031422 did not come over. 

- [ ] Maggie: Ingest 401 child images for parent 11396985
- [ ] Summer: Find image 11317074_000_00_per_000125.tif

**Comment by sshetenhelm** [comment]
Found image 11317074_000_00_per_000125.tif.

@MaggieZhaoYale I dropped it in the folder DCS_MaggieandSummer 

- [ ] Ingest 401 child images for parent 11396985
- [ ] Attach image 11317074_000_00_per_000125.tif to child 11031422 in PROD

**Comment by MaggieZhaoYale** [comment]
401 child images of 11396985 only have jpeg in fedora, and converted them to tif via ImageMagik were failed.

**Comment by sshetenhelm** [comment]
@motropuk We already have object 11396985 as object 10613257 in DCS. It looks like this was in FindIt twice--once under this collection, and a second time under a BRBL collection. Do we need to ingest this version as well? I think it's the same physical object--it has the same bookplate.

This one in FindIt: [11396985](https://findit.library.yale.edu/catalog/digcoll:194998) 
BRBL one in FindIt: [10613257](https://findit.library.yale.edu/catalog/digcoll:4460631)
BRBL one in DCS:  [10613257](https://collections.library.yale.edu/catalog/10613257)

**Comment by motropuk** [comment]
No need to migrate this object again, but can we make sure the existing one in DCS has the PID in the project ID for this collection

**Comment by sshetenhelm** [comment]
Updated; we're good! @MaggieZhaoYale could you please provide the handles? Thank you!

**Comment by MaggieZhaoYale** [comment]
[https://app.zenhub.com/files/242185115/70b1b7cb-3597-4d8f-a710-1c25d08ea819/download](https://app.zenhub.com/files/242185115/70b1b7cb-3597-4d8f-a710-1c25d08ea819/download) @sshetenhelm   Here are the handles

**Comment by sshetenhelm** [comment]
Finished & ready to close :)
