### ISSUE TITLE
Migrate Hebrew Satirical Newspapers Collection

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2326]
**Story**
Migrate the Hebrew Satirical Newspapers Collection (PID 41) from FindIt into DCS.

**Acceptance**
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Generate list of Parent OIDs
- [x]  Import the objects into DCS UAT into the SML admin set
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the SML admin set
- [x]  Audit objects in DCS PROD
- [x]  Update handles URLs to point to DCS

**Comment by MaggieZhaoYale** [comment]
Find it uat: https://findit-uat.library.yale.edu/?_=1670595610322&f%5Bdigital_collection_sim%5D%5B%5D=Hebrew+Satirical+Newspapers
DCS uat https://collections-uat.library.yale.edu/management/batch_processes/1270
118 parents in uat

**Comment by sshetenhelm** [comment]
Looks good in UAT!

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm  118 parents in prod: https://collections.library.yale.edu/management/batch_processes/11067

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Looks good in PROD! Could you please give me the handles? Thank you!
