### ISSUE TITLE
Add subresource integrity hash for SiteImprove 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2328]
**Story**

We'd like to use a subresource integrity check for siteimprove.

See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Acceptance**
- [x] Create a hash for the script
- [x] Add the hash to the JS `<script>` tag

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/856

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.54](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.54)

**Comment by K8Sewell** [comment]
Looks good on Test, deployed to UAT
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d83ab1c7-681b-4d96-aee7-0378518996b4)

**Comment by mikeapp** [comment]
@jpengst   We heard from Siteimprove that the script does change, so we need to revert this change.  
Sorry!

**Comment by jpengst** [comment]
Revert PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/858

**Comment by K8Sewell** [comment]
Revert deployed to Test with release [v1.60.55](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.55)

**Comment by K8Sewell** [comment]
Hash no longer present on script, deploying to UAT
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/956c5c0e-7844-4e63-a1b9-500e5fead2db)
