### ISSUE TITLE
Add _blank_ capability to "update child objects caption and label" batch process

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2330]
**Story**

Currently, for the Update Parent Objects batch process, users can put `_blank_ ` as a value in a metadata field to remove data from that field. 

For the Update Child Objects Caption and Label batch process, if a user enters`_blank_`, the text _ blank _displays in the Universal Viewer and Management App as data for those child objects.

When used in the Update Child Objects Caption and Label batch process, we would like the value `_blank_ `to result in the removal of data from that field.

**Approval**

- [x] Value of `_blank_ `in Label or Caption column of Update Child Objects Caption and Label batch process removes/deletes all current data from that field

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1115

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.79](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.79)

**Comment by K8Sewell** [comment]
### before
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d2006aef-e396-4ffa-b5b0-2df499bd82fc)

### after
blocked by enqueued jobs on Test

**Comment by jpengst** [comment]
Looks good on Test

**Comment by K8Sewell** [comment]
Deployed to UAT
