### ISSUE TITLE
Blacklight download controller

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2331]
**Story**

Create a controller in Blacklight that allows for TIFF download.

**Acceptance**

In a feature branch...

- [x] Controller route `/download/tiff/:child_oid`
- [x] Authorization check (also see error conditions below)
  - [x] Public: all users can download
  - [x] YCO: must be on campus or logged in
- [x] If the user is authorized and file exists in the download bucket
  - [x] Read metadata from S3 if needed (e.g., for content length)
  - [x] Stream the file to the client
- [x] If the user is authorized but the file does not exist in the S3 bucket
  - [x] Send a request to the management API to copy the file to S3
  - [x] Set the response status to [HTTP 202 Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202)
    - [x] Set headers so that this response is not cached
  - [x] Notify the user "Please try again in a few minutes" (we'll change this later)
- [x] Error/access conditions
  - [x] If no child exists with that OID return HTTP 404
  - [x] If child does not have YCO or Public permissions, return HTTP 404
  - [x] If permission is YCO but the user is not on campus and not logged in, return HTTP 401 Unauthorized
    - [x] Set headers so that this response is not cached

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/861

**Comment by mikeapp** [comment]
Reminder this is in a feature branch, we could test on the demo cluster if needed.

**Comment by K8Sewell** [comment]
Deployed to Demo. Routes to root on standard failure and that's working but not seeing the redirect to the 'try again later' message for when the image isn't on s3 yet.  Will do more testing tomorrow to see if this needs to go back to in progress.

**Comment by K8Sewell** [comment]
Still unable to reach the 'try again' message.  Taking this back to in progress to discern why images are not being queued for download.

**Comment by K8Sewell** [comment]
Additional error handling added in this PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/864

**Comment by K8Sewell** [comment]
Deployed to Demo

**Comment by K8Sewell** [comment]
Now broken in a new and interesting way - taking back to in progress
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/631208e4-c9f6-449a-9c2b-6a5fc857bc27)

**Comment by K8Sewell** [comment]
Refactor PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/865

**Comment by K8Sewell** [comment]
Redirect and notice are working on Demo but it did not save to s3 yet so further testing is needed.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/803766aa-6948-4887-b198-3e9965e136f2)

**Comment by martinlovell** [comment]
The problem may be that DownloadOriginalController is checking credentials, but blacklight isn't logged in.
It might need a `skip_before_action :authenticate_user!`.    (The access will be limited to the cluster before deploying to the public.)

**Comment by K8Sewell** [comment]
Sort of implements what you suggested but not exactly.  PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/868.  Still working on trying to get a `skip_before_action` to work.

**Comment by K8Sewell** [comment]
Deployed recent management version to test out solution and while testing noticed that the folders and items have been cleared from the bucket.  Did we set up some deletion rules for this bucket that we need to adjust?
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/9584777f-19e1-48ca-992f-03dfc32bceef)

**Comment by martinlovell** [comment]
Yes, some of the download buckets are setup to delete after a period of time.   See the management tab on the bucket.

**Comment by sshetenhelm** [comment]
We would like some assistance from DevOps! Please refer to slack.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/876

**Comment by K8Sewell** [comment]
When testing locally I uploaded a tif manually and it's ending was .tiff so I've updated the blacklight repo to match in the PR above.  The PR below is for management to do the same.

https://github.com/yalelibrary/yul-dc-management/pull/1146

**Comment by mikeapp** [comment]
I think we use the `.tif` extension for most images in the repo.  I'd like to stick with that.

**Comment by K8Sewell** [comment]
Revert back to .tif in blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/877

**Comment by K8Sewell** [comment]
Deployed to Demo.  Redirected and downloaded (although tif downloaded doesn't appear to still be on S3(may have been cached)) as expected.  Did not see job triggered or tif show up in AWS.  Will leave in review on Test for further testing.

**Comment by K8Sewell** [comment]
Merged PRs
Camerata - https://github.com/yalelibrary/yul-dc-camerata/pull/360
Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/880

**Comment by MaggieZhaoYale** [comment]
The download jobs are in the Management delayed job board:


![Image](https://user-images.githubusercontent.com/46331329/224115418-8ab7a139-e9cd-4140-a8a7-58df6a2873bb.png)

yul-dc-download-test does not have the image. Is it possible that it was cleared?

**Comment by K8Sewell** [comment]
Adds logging - https://github.com/yalelibrary/yul-dc-management/pull/1153

**Comment by K8Sewell** [comment]
We are enqueuing the job on Demo now



![Image](https://user-images.githubusercontent.com/36549923/224400405-1931aee9-0bde-4081-a800-af0b7d7c317b.png)
