### ISSUE TITLE
PDF Bug: Remove R-To-L text from PDF values

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2334]
Until we are able to properly render R-to-L text, remove those values from the json used to generate the PDF documents.
Our records usually contain a Romanized version of the values.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1114

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.79](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.79)

**Comment by martinlovell** [comment]
looks good on test: https://collections-test.library.yale.edu/catalog/800045169

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Looks good on UAT!
https://collections-uat.library.yale.edu/catalog/12297587

Ready to close :)
