### ISSUE TITLE
Update text for Extent of Digitization field

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2335]
**Story**

As an end user of DCS, I would like improved clarity around the meaning of information in the Extent of Digitization field. It would be useful if the values in that field were expressed as full sentences.

**Acceptance**
- [x] Change "Completely digitized" value to "This object has been completely digitized."
- [x] Change "Partially digitized" value to "This object has been partially digitized."

**Comment by mikeapp** [comment]
Would this change also be made in the facet display?

**Comment by mikeapp** [comment]
Would this change also be made in the facet display?

**Comment by jpengst** [comment]
Specs that need updated after the change: 
Models - batch_process_spec, batch_process_update_parent_spec, mets_document_spec 
System - parent_object_spec

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1133

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.58](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.58)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/380183b7-52e1-4df9-a908-afae29ea806c)
