### ISSUE TITLE
Troubleshoot Deployments: Jenkins

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2338]
**Story**

Jenkins deployment are failing, even with a known-good Docker image.   DevOps was able to manually redeploy an image in ECS.

**Acceptance**
- [x] Review recent commits to Camerata: were there any changes there that would impact the deployment? (Last commit was 12/5 so... https://github.com/yalelibrary/yul-dc-camerata/commits/main )
- [x] Review Jenkins logs.   Perhaps also look at the last successful server deployments and see whether anything changed?
- [x] @bobrice configured Jenkins to install and use the correct Bundler and Ruby versions

**Comment by bobrice** [comment]
The error that may be the root of the problem is related to a bundler/ruby version mismatch.  No changes were made by DevOps since the last successfull deployment on 12/21/2022.

Error:
Using /var/lib/jenkins/.rvm/gems/ruby-2.5.1 with gemset dc
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
	bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
Build step 'Execute shell' marked build as failure

**Comment by mikeapp** [comment]
It looks like that is during the camerata install.

**Comment by bobrice** [comment]
For some reason the deploy job is looking for a very specific version of bundler since our last run.  It's working now, but I had to specify the bunder version to install in the job.  A hack for now.

**Comment by bobrice** [comment]
I took a different approach on dc-staging.  I changed the version of ruby from 2.5.1 to 2.6.0 without changing the bundler line and that also fixed the issue.  Staging images are re-deploying via Jenkins after this change.

**Comment by bobrice** [comment]
The image server has been restarting constantly over the past few days with a healthcheck failure.  The deployment appears to be in a loop of starting and stopping images tasks.

**Comment by bobrice** [comment]
Dynatrace installs are taking 12 minutes to complete causing healthchecks to fail for the images target group resulting in a deployment loop.  Changed the Dynatrace key to an invalid value the parameter store and tasks are deploying normally now.  

Working with ITS Monitoring team on a solution.
