### ISSUE TITLE
Code Coverage - Management

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2339]
### Summary
Code coverage goal is 97%.  As of 1.4.23:
Management -  94.44%

### Acceptance
- [x] raise code coverage on management repo

**Comment by K8Sewell** [comment]
Coverage raised to 96% in this PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1117

**Comment by mikeapp** [comment]
There's a change to `app/controllers/api/permission_requests_controller.rb`.   Which ticket is that related to?

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.80](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.80)

**Comment by K8Sewell** [comment]
No obvious issues on management - deploying to UAT
