### ISSUE TITLE
Investigate if box_ssim values are correct 

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#234]
**BACKGROUND**
It seems as if box_ssim is using the same data as identifierShelfMark_ssim, as seen here from https://github.com/yalelibrary/yul-dc-management/blob/master/app/services/fixture_indexing_service.rb:
![Screen Shot 2020-06-16 at 1.54.04 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/d7c265ae-be5f-473e-b7ee-f475a35bf661)
Here's an example of data from Solr: 
![Screen Shot 2020-06-11 at 2.34.16 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/42c2bd32-b4f4-4942-801d-9a322f42c811).
**ACCEPTANCE**
- [x] Investigate if box_ssim should be pulling in the same data as identifierShelfMark_ssim
- [x] Make changes to the management application to pull in the correct data if necessary, else close ticket.

**Comment by maxkadel** [comment]
Right now these are being [mapped from the same value](https://github.com/yalelibrary/yul-dc-management/blob/e36aeb5b7ab9227f23b9b89283e895d288a8439d/app/services/fixture_indexing_service.rb#L70) from the MetadataCloud. Based on this example, it looks like maybe the mapping should be from [`volumeEnumeration`](https://github.com/yalelibrary/yul-dc-management/blob/e36aeb5b7ab9227f23b9b89283e895d288a8439d/spec/fixtures/ils/V-10001192.json#L122)

There are a few other values that are currently commented out, maybe someone who's working on the MetadataCloud application could go over the mappings as they currently are and update them? (@martinlovell @yjyale @MaggieZhaoYale )
