### ISSUE TITLE
Troubleshoot Deployments: Dynatrace

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2340]
**Story**

The Dynatrace agent is taking a long time to download.

**Acceptance**
- [x] Identify cause of the slowdown
  - [x] Contact ITS
- [x] Determine next steps.   Should we download deploy the agent after (or in parallel to) starting the application?

**Comment by martinlovell** [comment]
The base image script puts the download _and_ install into the background.
(see: https://github.com/yalelibrary/yul-dc-camerata/blob/main/base/ops/boot.sh)

The iiif container downloads in the foreground, and then puts the install into the background:
(see: https://github.com/yalelibrary/yul-dc-iiif-imageserver/blob/main/ops/boot.sh)

We should update iiif to match the base image dynatrace setup.
