### ISSUE TITLE
null child height/width 

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#2341]
There are 499 child images have null height or width. Some of them may have the wrong image format (.e.g. jp2) in the pairtree. e.g. https://collections.library.yale.edu/management/parent_objects/11396985

Here is the list[https://app.zenhub.com/files/242185115/dc2e8a77-241f-4025-997b-350572d4926c/download](https://app.zenhub.com/files/242185115/dc2e8a77-241f-4025-997b-350572d4926c/download):

- [x] Identify the issues 

- [x]  Find/replace with the alternative tif if it is possible

- [x] Delete 401 children of 11396985 to 10613257, and redirect parent 11396985 to 10613257

- [x] Recreate Ptiff if the tif images are in the pairtree

**Comment by MaggieZhaoYale** [comment]
Reprocessed some images and redirect 401 children. The most of images were fixed. The rest are:

- [ ] 11872504 (parent: 2007676 order:1) brbl no image in pairtree & ladybird

- [ ] 11872499 (parent 2007671, order :1 ) brbl no image in pairtree & ladybird

- [ ] 32329884 (parent 32329883, order :1 ) brbl no image in pairtree & ladybird

- [ ] 32302730 (parent 10020249 , order :1 ) no image in ladybird & Findit

- [ ] 11872499 (parent  2007671, order :1 ) brbl no image in pairtree & ladybird

- [ ] 32302734 (no image in Findit, has the pairtree path, but no image in the directory)

- [ ] 32302730 (no image in Findit, has the pairtree path, but no image in the directory)

- [ ] 15490074  (parent  16852894, order :1 ) has tif in Findit and will pull the image from Fedora

**Comment by fordmadox** [comment]
Thanks for this, Maggie!  I've asked Stephen to investigate the Beinecke
ones.  It seems that the first two Ladybird-era ones (image IDs 1872504
and 11872499, listed twice above) were requested to be deleted during the
original migration process (before you were on the case!), but I guess they
weren't.  I think those should be fine once Stephen deletes the images from
MGMT App.

The other one, 32329883, was from a pilot of NEDCC negatives that were
uploaded by Cliff last year.  Those were essentially "preservation" TIFFs,
rather than access TIFFs, so the files were quite large.  It looks like
when you re-ran the PTIFF job, though, that it fixed the issue.  Thanks!

**Comment by sshetenhelm** [comment]
- 11872499 - deleted redundant child
- 32302735 - deleted redundant child
- 3600709 - deleted redundant child
- 11872502 - deleted redundant child
- 11872506 - deleted redundant child
- 32302689 - duplicate object; deleted & redirected parent to 10010788 
- 32302730 - duplicate object; deleted & redirected parent to 10015627 

Still working on others.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale replacement images for children: 
15490266, 
15490267,
15490268 

from parent 16852894 are in DCS_MaggieandSummer > Null child replacements > 16852894

**Comment by sshetenhelm** [comment]
@ucancallmealicia is it possible that the images from parents [10515164](https://findit.library.yale.edu/catalog/digcoll:4350923) and [10515163](https://findit.library.yale.edu/catalog/digcoll:4350754) are part of object [10539296](https://collections.library.yale.edu/catalog/10539296)?

They have different record groups but appear to all be Yale swimming, so wanted to ask.

**Comment by ucancallmealicia** [comment]
@sshetenhelm yes I remember working on these a long time ago. There were a few MADID images each of which had two similar/duplicate Ladybird records, and one of each of the pairs of Ladybird records did not render in find-it. I reassociated the ones that did render into the OID above. So 10515164 and 10515163 should be all set and do not need replacements.

**Comment by sshetenhelm** [comment]
Thank you @ucancallmealicia ! 

I've removed these objects from MGMT PROD. Ready to close!

@MaggieZhaoYale would you like to point?
