### ISSUE TITLE
Update IIIF Manifests batch job 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2347]
**Story**

It would be helpful to have a batch job that just updated the IIIF Manifests by admin set.  I believe this will also then queue the PDF job, if we want to reuse the existing Manifest job.

**Acceptance**
- [x] Create a button on the admin set page to trigger the `update_manifests_job`
- [x] The job should queue in batches of 5000 (same limit as 'update metadata job')
- [x] The job should queue all non-private parents in the admin set for manifest re-generation.
- [x] The job should validate that the user has write access to the admin set 
~~- [ ] Create a batch job that takes a CSV containing the admin set(s) as its input parameter~~
~~- [ ] Make the downloadable sample spreadsheet used to create the job.~~

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1120

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.83](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.83)

**Comment by K8Sewell** [comment]
Looks great on Test - Deploying to UAT
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3c2408f5-0573-4a70-aee6-a1062d335773)

**Comment by K8Sewell** [comment]
Taking back to in progress to refactor.

**Comment by jpengst** [comment]
Removed Batch Process and updated specs PR: https://github.com/yalelibrary/yul-dc-management/pull/1123

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.84](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.84)

**Comment by K8Sewell** [comment]
Looks good on Test.  Deploying to UAT
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/dec6b144-98ad-43d3-b121-666e806bff1c)

**Comment by jpengst** [comment]
Bug PR: https://github.com/yalelibrary/yul-dc-management/pull/1132

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.87](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.87)

**Comment by K8Sewell** [comment]
Looks like it is working on Test.  Got a bunch of manifest jobs triggered to start.  No obvious errors.  Will promote to UAT.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/ad6be023-f6ba-472d-9f49-b1a230fd69b6)

**Comment by sshetenhelm** [comment]
The only failed jobs seem to be related to objects that have broken child images (and therefore cannot successfully generate a manifest anyway), so I would say this is good to go.
