### ISSUE TITLE
[SPIKE] Upgrade Ruby/Rails

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2348]
**Story**

Evaluate upgrade of Ruby and Rails version for Management and Blacklight.

Ruby 2.7 EOL 3/31/23
Rails 6.0 EOL 6/1/23

**Acceptance**
- [x] Test higher Ruby versions (aim at least 3.0, but go as high as we can)
- [x] Test higher Rails versions (at least to 6.1)
- [x] Does current Blacklight have any issues with Rails 7?  If not, lets push.
- [ ] Report if blockers, create individual tickets for further work.

**Comment by K8Sewell** [comment]
### PRs to upgrade to Ruby v3.1.3
Camerata - https://github.com/yalelibrary/yul-dc-camerata/pull/356
Management - https://github.com/yalelibrary/yul-dc-management/pull/1124
Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/866

**Comment by jpengst** [comment]
To upgrade Rails to 7.0, we need to update the activejob-scheduler gemspec versions. I currently do not have access to push to the repo:  
![image.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/d1efaf9f-b759-4324-a54b-565957c6c169)

**Comment by K8Sewell** [comment]
PR to update the gemspec in activejob-scheduler - https://github.com/yalelibrary/activejob-scheduler/pull/1

**Comment by K8Sewell** [comment]
Management - Upgrade Rails to 6.1 - https://github.com/yalelibrary/yul-dc-management/pull/1126

**Comment by K8Sewell** [comment]
As part of the Blacklight upgrade to Rails 6.1 some functionality has changed.  While the query itself is sanitized of not closed quotes, the user now sees exactly what they typed.  Is this behavior acceptable or do we need to refactor?

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/43f8341d-3c34-49a9-bf59-fa24f76c3cbb)

**Comment by K8Sewell** [comment]
### PRs for Review
* https://github.com/yalelibrary/yul-dc-management/pull/1126
* https://github.com/yalelibrary/yul-dc-blacklight/pull/867

### Ticket for Review
* https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2387

**Comment by K8Sewell** [comment]
Blacklight - Deployed to Test with release [v1.60.59](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.59)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.
