### ISSUE TITLE
Dependabot fixes for Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2349]
**Acceptance**
- [ ] Apply dependabot fixes to Management

**Comment by K8Sewell** [comment]
Bumps `globalid`, `minitest`, and `zeitwerk` - https://github.com/yalelibrary/yul-dc-management/pull/1122
Bumps `rack` - https://github.com/yalelibrary/yul-dc-management/pull/1121

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.82](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.82)

**Comment by K8Sewell** [comment]
Looks good on Test but dealing with issue preventing deploy to UAT - see ticket #2350 for details

**Comment by sshetenhelm** [comment]
Looks good on UAT, nothing weird noticed.
