### ISSUE TITLE
Images not displaying 

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#235]
In `yul-dc-blacklight` v1.3.0 / Camerata v1.4.0 images are not displaying. The appears to be because the id numbers of the fixture objects changed and added prefixes, and now the links to the iiif manifests no longer work because the manifests do not contain those prefixes. 

![Screen Shot 2020-06-11 at 3.40.39 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/34bf8082-b68e-4f71-a4f0-ae0f2a90b803)

**Comment by fnibbit** [comment]
Immediate issue resolved by @maxkadel management app version 1.4.1 which creates ladybird-based IDs without the prefix; ongoing strategy for use of IDs and generation/update of manifests merits discussion.

**Comment by bess** [comment]
Fixed.

![Screen Shot 2020-06-15 at 12.34.10 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/3f0ecefa-1e35-4eed-990f-141145985592)
