### ISSUE TITLE
[SPIKE] Blacklight update

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2352]
**Story**

We are running Blacklight 7.10.   The current release of Blacklight is 7.33.  

Also, it looks like Blacklight 8 is in pre-release, at `8.0.0-pre.4`.  See docs at https://github.com/projectblacklight/blacklight/wiki/Upgrading-to-Blacklight-8.   This recommends upgrading to the latest 7.x series and remediating all deprecations.

It might be a good idea to do this before moving on to Open With Permission work, if it won't delay us too much.

**Acceptance**
- [ ] Investigate upgrading Blacklight to 7.33.  
- [ ] If this causes what seems to be a prohibitive amount of problems, try upgrading to an intermediate version

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.61](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.61)

**Comment by K8Sewell** [comment]
No obvious issues on Test.  Will promote to UAT.
