### ISSUE TITLE
Terms and Conditions data model.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2353]
**Story**

Permissions Sets may have associated terms and conditions that users must accept before requesting access to content.   

Some business rules:
* There can be 0 or 1 active T&Cs for a Permission Set.   The active T&Cs will not have an inactivated_at date.
* If a new T&C is created the old one is marked as inactive, but they are never deleted.  All versions are retained.
* T&Cs are not editable after they are created
* The system will record the user and timestamp both when a T&C is activated and when it is inactivated.
* Only admins of the Permission Set should be able to manage the T&Cs.

Data model:
* Many-to-one relationship with PermissionSet
* activated_at: timestamp when made active 
* activated_by: `User` who created/made active
*  inactivated_at: timestamp when made inactive
*  invactivated_by: `User` who made inactive
*  title:  text
*  body:   text

**Acceptance**
- [x] Create a PermissionSetTerms model as described above
- [x] A PermissionSet can have many PermissionSetTerms
   - [x] add a method to get the active PermissionSetTerms (i.e., the not inactive one)?

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1128

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.85](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.85)

**Comment by K8Sewell** [comment]
Terms column present on Test.  Will promote to UAT.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/5a7b7244-43c2-403b-82dd-3ab08700a74b)
