### ISSUE TITLE
Display latest T&C in Permission Sets list.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2354]
**Story**

In the listing of Permission Sets, display the latest T&C time if there is an active T&C for the Permission Set.

![PS_list_page.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/91afdc06-b689-4f8e-878a-b7298b4c4d85)

**Acceptance**
- [x] Display date/time as shown above if there is an active PermissionSetTerms
- [x] Display "None"  if none exists/is active  
- [x] Also, align the header with the table
- [x] Include the user

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1129

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.85](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.85)

**Comment by K8Sewell** [comment]
Terms column present on Test.  Will promote to UAT.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/5a7b7244-43c2-403b-82dd-3ab08700a74b)
