### ISSUE TITLE
Remove IP addresses from authentication list

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2355]
Yale is removing two IP address ranges from the list of public IP addresses that are used to provide access to IP-authenticated resources:

192.26.88.*
192.31.236.*

We will need to have these two IP addresses removed from any IP lists that are used for access control purposes. These are changes that affect DCS and FindIt. 

**Acceptance**
- [ ] Check to see if there are issues doing this work now, re: revoking access when people should still have it
- [ ] Remove the two aforementioned IP address from any lists that are used to provide access to IP-authenticated resources

**Note**
I have asked for but have yet to receive an exact date for when these addresses will be removed.
Since we don't know the ramifications, we'll put the work in a branch that we only merge when it's OK.

**Comment by sshetenhelm** [comment]
Needs to be updated by mid-June 2023. Attached to this comment are notes and a document from Jennifer.

**Comments from Jennifer B.:**
"The deletion of the 192.26.88.* range is less urgent than the deletion of 192.31.236.*. 192.26.88.* is currently unused and will not be immediately re-purposed. However, ITS will be moving the Yale Guest wi-fi network into the 192.31.236.* range in June; because Yale Guest is freely accessible to anyone with a wi-fi connection that is close enough to Yale’s campus, our licensed e-resources cannot be accessible to those addresses (allowing non-Yale affiliated users to access our licensed e-resources is a violation of most of our license agreements)."

[https://app.zenhub.com/files/242185115/c98c08df-0fe0-4b9b-881e-79414d7affa6/download](https://app.zenhub.com/files/242185115/c98c08df-0fe0-4b9b-881e-79414d7affa6/download)

**Comment by jpengst** [comment]
I'm not seeing 192.26.88.* or 192.31.236.* in the parameter store IP ranges

**Comment by motropuk** [comment]
Mentioned at standup today - good chance that these two IPs are just not part of the active set of IPs the library is using. Discussed comparing the list of active Yale IPs with what we have in DCS. Up to date list is here https://web.library.yale.edu/departments/e-resources/ip?app=yalesites

**Comment by jpengst** [comment]
I'm not seeing the two IPs in either the active Yale IPs or Parameter Store.
I think we can close this? Moving this to In Progress for discussion 2/2
