### ISSUE TITLE
Display T&C version on Permission Set show page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2356]
**Story**

When viewing an individual Permission Set, the user should be able to see whether there is an active T&C for the set.

**Acceptance**
- [x] The label for the field should be "Terms and Conditions"
- [x] Display the active PermissionSetTerms title, with the date/time in brackets following it.
- [x] Display "None" if no terms are active.
- [x] A link "Manage Terms and Conditions" should be displayed if the logged in user is an Administrator of the PermissionSet.   (This could float to the right as shown, but do whatever is expedient - I'm sure we'll do a design review later.)
   - [x] The management page will be defined in a subsequent ticket.
- [x] Formatting: please add some space between the top section and the user management area.

![terms_permission_set_page.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/0b4e3aa9-fc30-470b-bef2-43dec03a8ff8)

**Comment by martinlovell** [comment]
I will probably combine this with #2354 since they are pretty similar.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1129

**Comment by mikeapp** [comment]
@martinlovell  Should this be in "team review"?

**Comment by sshetenhelm** [comment]
Looks good to me although we will need to re-check the "Terms and Conditions" version information functionality when we are able to make T&Cs/different versions.
