### ISSUE TITLE
UV Images don't display [Dev Environment]

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#236]
The change in the naming of manifests seems to. not allow the images from appearing in the development environment.  

E.g. If you search on  "The glory of old England ..." in the demo site appears (see link 2) while in the test site does not appear (see link 1):

[1] https://collections-test.curationexperts.com/catalog/LB-2030006

[2] https://collections-demo.curationexperts.com/manifests/2055095.json

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/133
