### ISSUE TITLE
Migrate Public materials from Kissinger 2004

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2366]
**Story**
Migrate the 'Open for Research' materials from Kissinger MS 2004 (PID 39) from FindIt into DCS.

**Acceptance**
- [x] Provide list of parent OIDs (Summer)
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Import the objects into DCS UAT into the MSSA admin set
- [x]  Audit objects in DCS UAT for file/other ingest errors
- [x]  Audit objects in DCS UAT for Preservica/ASpace information
- [x]  Import text files into DCS UAT
- [x]  Audit text files for errors
- [x] Re-import 120 'open with permissions' objects in MSSA admin set
- [x] Import text files for 120 'open with permissions' objects
- [x]  Audit objects in DCS UAT for file/other ingest errors
- [x]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the MSSA admin set
- [x]  Audit objects in DCS PROD for file/other ingest errors
- [x]  Audit text files for errors
- [x]  Audit objects in DCS PROD with collection owner
- [x]  Update handles URLs to point to DCS

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale here is the list of parent OIDs for PID 39 that are open with permission. There are 802.

[https://app.zenhub.com/files/242185115/34ba3c6e-b711-4f59-803e-1149f96229b5/download](https://app.zenhub.com/files/242185115/34ba3c6e-b711-4f59-803e-1149f96229b5/download)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Downloading images (70418 images) are in progress. 
Three oids list in the excel do not have children: 
15235480
15235481
15235482

**Comment by sshetenhelm** [comment]
These three parents link out to Aviary and do not appear to have locally-hosted files attached. They are in Series VIII -- Moving Images and Sound recordings. Records for these objects are available in Archives at Yale.

I think we should proceed without worrying about these objects, but should mention them to Josh.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 
Totally 32 parents are without children (including the above 3)[https://app.zenhub.com/files/242185115/b314acc8-f910-4c13-85c4-30fc94243c4b/download](https://app.zenhub.com/files/242185115/b314acc8-f910-4c13-85c4-30fc94243c4b/download)

**Comment by MaggieZhaoYale** [comment]
There are 120 records with  "itemPermission":"Open With Permission"
DCS only accept Private, Public, Yale Community Only as the visibility. 
DCS management has to be modified in order to allow process items with permission "Open With Permission" [https://app.zenhub.com/files/242185115/e63102e0-76ab-4ffb-adc4-4cb378783ef2/download](https://app.zenhub.com/files/242185115/e63102e0-76ab-4ffb-adc4-4cb378783ef2/download)
@sshetenhelm

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/batch_processes/1292/parent_objects/12480439 86 children in findit, 319 in ladybird. 12482000 (shows the image was not found in this parent) is the children of of 12480439, and it also has 188 children.  https://collections-uat.library.yale.edu/management/parent_objects/12482000

**Comment by sshetenhelm** [comment]
* The parents without children are all for A/V records that link out to Aviary
* 12480439 is a hierarchical record; I can delete
* Working on others

**Comment by sshetenhelm** [comment]
* The 32 parents without children have been removed from UAT and their handles have been redirected to Aviary.
* Hierarchical parent 12480439 has been removed from UAT.

* The 120 parents with visibility issues are [visible in FindIt](https://findit.library.yale.edu/catalog/digcoll:1193127) and their 'Conditions Governing Access' state that they are open for research. 
@MaggieZhaoYale do you know where the Visibility information is being pulled from? A certain field in Ladybird or FindIt?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm "Open with Permission" comes from the itemPermission in ladybird "fdid": 180

**Comment by sshetenhelm** [comment]
That's helpful, thanks Maggie! I'll talk to George. These were from folders that we opened last year; I'm wondering if we just missed something that should have been updated. I will check and get back to you :)

**Comment by sshetenhelm** [comment]
Reassociated 120 parent objects with ArchivesSpace uris; this successfully pulled in the child images. Currently running recreate child oid PTIFF jobs so images will correctly load.

**Comment by sshetenhelm** [comment]
For the 120 aforementioned objects, PTIFFs will not load in UAT MGMT and are listed as "pending, or parent deleted"; however, when I click on a child object page, I can download the PTIFF and successfully open it on my computer. 

I have tried:
* Recreate child oid ptiffs job
* Batch update metadata
* Batch update manifests
* Selecting new thumbnail (has previously 'fixed' things, did not for this migration)
* Change source back to Ladybird
* Change source back to ASpace

These objects do not display in the problem report. 

Screenshots:
![Screen Shot 2023-02-13 at 9.59.41 AM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/5678458c-a2ff-4a10-a24d-275e40b1d6e3)![Screen Shot 2023-02-13 at 9.59.54 AM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/5341050a-3839-42d1-a66b-d256f3d205f1)

**Comment by sshetenhelm** [comment]
* 802 objects were on original list 
* 32 objects were removed and their handles redirected to Aviary
* 1 hierarchical parent was removed 
* 757 objects have a PID of 39

There is a discrepancy of 12 objects. I will investigate.

**Comment by sshetenhelm** [comment]
* 759 parents in UAT MGMT
* 759 parents in UAT Blacklight

@ucancallmealicia is there a subjectively "easy-ish" way to match parents with ASpace or Preservica info? These should all be described. I matched the 120 that were loading but probably did it in a very silly way.

**Comment by ucancallmealicia** [comment]
Yep I can match them up if you can provide me w/ a list of the parents

**Comment by sshetenhelm** [comment]
@ucancallmealicia perfect! There are 759 objects, 120 have aspace uris already

spreadsheet of parent export from MGMT uat: 
[https://app.zenhub.com/files/242185115/3ce524ce-8f74-4aac-93d2-c61737118ba7/download](https://app.zenhub.com/files/242185115/3ce524ce-8f74-4aac-93d2-c61737118ba7/download)

**Comment by sshetenhelm** [comment]
Thank you to Alicia for the file! Double-checking updated objects before sending to Josh for approval :)

**Comment by sshetenhelm** [comment]
UAT Blacklight collection link sent to Josh for approval; waiting for response before pushing to PROD.

**Comment by sshetenhelm** [comment]
Emailed Josh today to see where he is at with this and clarify what we need from him.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Josh has let us know that these objects include text files in Ladybird. Could we please pull the text files in as well?

**Comment by MaggieZhaoYale** [comment]
missing 27468 ocr 
42710 ocr downloaded

**Comment by MaggieZhaoYale** [comment]
[Uploading... kissinger_missing_ocr.csv]
The list of oids that miss ocr 
(The list includes digColl id of the child, child oid, and parent oid (repeated in the list) @sshetenhelm

**Comment by sshetenhelm** [comment]
678 of 759 parents are missing OCR files, wheeee. Will start working on these.

**Comment by sshetenhelm** [comment]
Working on ~70 objects that are missing 1 page of OCR. Most appear to be blank pages.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale the fix for those 120 pesky permissions parents is in UAT. Could you please try to reingest them? Parent oids here, for your convenience: 

[MS2004_120parents.csv](https://github.com/yalelibrary/YUL-DC/files/11005076/MS2004_120parents.csv)

- [ ] Reingest 120 parents

**Comment by sshetenhelm** [comment]
Round 2 of OCR files is also ready! Files are in DCS_MaggieandSummer > ocr

- [ ] Ingest 1901 ocr files

**Comment by sshetenhelm** [comment]
- [x] Ingest round 3 ocr files (1116) and update parents

- [ ] Ingest round 4 ocr files and update parents (3816 children, 78 parents) 

[MS2004_OCR_round4_oids.xlsx](https://github.com/yalelibrary/YUL-DC/files/11032511/MS2004_OCR_round4_oids.xlsx)

**Comment by sshetenhelm** [comment]
Thanks @MaggieZhaoYale !

- [ ] Ingest round 5 ocr files and update parents (4979 children, 76 parents) 

[MS2004_OCR_round5_oids.xlsx](https://github.com/yalelibrary/YUL-DC/files/11042111/MS2004_OCR_round5_oids.xlsx)

**Comment by sshetenhelm** [comment]
- [ ] Ingest round 6 of ocr files and update parents (3293 children, 45 parents)


[MS2004_OCR_round6_oids.csv](https://github.com/yalelibrary/YUL-DC/files/11078510/MS2004_OCR_round6_oids.csv)

**Comment by sshetenhelm** [comment]
Thank you so much @MaggieZhaoYale ! Here's the next batch: 

- [ ] Ingest round 8 of ocr files and update parents (3202 children, 37 parents)


[MS2004_OCR_round8_oids.csv](https://github.com/yalelibrary/YUL-DC/files/11124311/MS2004_OCR_round8_oids.csv)

**Comment by sshetenhelm** [comment]
Thank you so much again @MaggieZhaoYale ! Here's the next batch:

- [ ] Ingest round 9 of ocr files and update parents (3756 children, 37 parents)


[MS2004_OCR_round9_oids.csv](https://github.com/yalelibrary/YUL-DC/files/11139619/MS2004_OCR_round9_oids.csv)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale do you have a simple way of determining what the remaining OIDs without TXT files are? If so, could you please let me know what OIDs we are missing? There should be some.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale 3793 from your list are blanks, list attached


[PID39_blankOCR.csv](https://github.com/yalelibrary/YUL-DC/files/11264814/PID39_blankOCR.csv)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale I'm seeing:

- 420 objects with **no OCR**
- 329 with **partial OCR**

No objects show as having Full OCR, which is incorrect (unless DCS is reading the blank OCR pages as "no ocr"). 

This means there are also **10** additional objects that don't have any OCR information.

I will look at this today and try to determine a path forward.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm I reprocessed OCR.

**Comment by sshetenhelm** [comment]
Currently at:
* 672 YES full text (yay)
* 87 Partial
* 0 No (HOORAY!)

Will investigate the 87 partial to see what's up.

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale !

The next batch has 969 blank OCR files that need to be generated for 19 parents. There are also two children from two separate parents that have actual OCR files that need to be ingested. These ocr files are saved in "DCS_MaggieandSummer > Kissinger ocr" and the filenames are the child oids.

Blank child oids: 

[MS2004_ReadyBlanks02.xlsx](https://github.com/yalelibrary/YUL-DC/files/11444770/MS2004_ReadyBlanks02.xlsx)

- [ ] Ingest 969 child blank text OCR files for 19 parents
- [ ] Ingest txt file for child object 15071150 from parent 12480481
- [ ] Ingest txt file for child object 15140788 from parent 12480546

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Thank you so much! Just checked, and we need only one blank child OCR file to finish the OCR!!

- [ ] Ingest blank txt for child object 15222042 from parent object 12480252

**Comment by sshetenhelm** [comment]
Confirmed all 759 are now Full Text - Yes.

Sent URL to stakeholder to confirm. Once confirmed, can move into PROD :)

**Comment by sshetenhelm** [comment]
Attached 'waiting' label -- waiting for stakeholder approval.

**Comment by sshetenhelm** [comment]
Stakeholder has approved collection on UAT! @MaggieZhaoYale we are ready to move to PROD :)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 759 parents in prod. https://collections.library.yale.edu/management/batch_processes/12442.
Batch process of fulltext is running.

**Comment by sshetenhelm** [comment]
- 114 objects have no full text
- 618 objects have partial full text
- 27 objects have full text

Investigating.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Copied all full text files to production and reprocessed. https://collections.library.yale.edu/management/batch_processes/12446

**Comment by sshetenhelm** [comment]
Manifests have been recreated and all 759 objects show as having full text. Have sent link to collection owner for review/approval.

@MaggieZhaoYale would you please be able to generate a handle file?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm  Will do. It may take me little bit time to clear records in the handle file.

**Comment by MaggieZhaoYale** [comment]
[kissinger_prod.csv](https://github.com/yalelibrary/YUL-DC/files/11559938/kissinger_prod.csv)

@sshetenhelm Here is the handle file.

**Comment by sshetenhelm** [comment]
Handles successfully updated. Just waiting on final approval from Josh.

**Comment by sshetenhelm** [comment]
Josh has indicated there are one or two objects missing. I will investigate further and report back.

**Comment by sshetenhelm** [comment]
Objects missing are objects that were flipped to open recently.

75 objects are ready to ingest, a remaining 18 objects have errors in Ladybird and will need to be ingested at a future date.

@MaggieZhaoYale could you please bring over the OIDs in this spreadsheet? 
[new_ms2004.csv](https://github.com/yalelibrary/YUL-DC/files/11600035/new_ms2004.csv)

- [ ] Ingest 75 objects into PROD

**Comment by MaggieZhaoYale** [comment]
[missing_0605.csv](https://github.com/yalelibrary/YUL-DC/files/11653768/missing_0605.csv)

Missing OCR (or blank OCR list) @sshetenhelm

**Comment by sshetenhelm** [comment]
- [ ] Create and ingest blank OCR files for the following 1547 objects:


[blank_MS2004_20230612.csv](https://github.com/yalelibrary/YUL-DC/files/11726636/blank_MS2004_20230612.csv)



Ingest OCR files [found in DCS_MaggieAndSummer > for the following 6 objects:

- [ ] 15003472
- [ ] 14996352
- [ ] 15064525
- [ ] 15065282
- [ ] 15067886
- [ ] 15067772

**Comment by sshetenhelm** [comment]
Parent [12479736](https://collections.library.yale.edu/management/parent_objects/12479736) is missing all child TIFF images. Child images are [visible in FindIt](https://findit.library.yale.edu/catalog/digcoll:1193135).

[Parent 12479792](https://collections.library.yale.edu/management/parent_objects/12479792) says "Full Text Available -- Yes" in the Management App, but the Solr record reads _"has_fulltext_ssi": "No",_

I can see that there are text files attached to these when looking at the child objects. The text files can be downloaded, so they should be there. 

I have tried:
* Running the update fulltext status batch process for this object
* Recreating the IIIF manifest
* Updating the metadata

@MaggieZhaoYale any ideas on how to get the status to update?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm It looks there is a bug related to has_fulltext_ssi 
I checked a few full text available parents, all have has_fulltext_ssi as "No".

**Comment by sshetenhelm** [comment]
So for [Parent 12479792](https://collections.library.yale.edu/management/parent_objects/12479792), there is a [Solr Exception error](https://collections.library.yale.edu/management/delayed_job/failed?queues=intensive_solr_index#22620113). 

Error reads as follows:
    "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException"],
    "msg":"Exception writing document id 12479792 to the index; possible analysis error: Document contains at least one immense term in field=\"suggest\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 101, 101, 32, 13, 10, 115, 101, 105, 116, 101, 32, 50, 32, 102, 114, 97, 110, 107, 102, 117, 114, 116, 101, 114, 32, 97, 108, 108, 103]...', original message: bytes can be at most 32766 in length; got 33851. Perhaps the document has an indexed string field (solr.StrField) which is too large",
    "code":400}}

**Comment by MaggieZhaoYale** [comment]
Images of the Parent [12479736](https://collections.library.yale.edu/management/parent_objects/12479736) are copied and  updated

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale 
Apologies, parent 12479736 is also missing OCR files. Could you please attach the OCR? They are available at:
DCS_MaggieAndSummer > Kissinger OCR

- [ ] Ingest parent 12479736 ocr (8 files)

After that, resolving the solr issue with parent 12479792 should be the last thing.

**Comment by MaggieZhaoYale** [comment]
`Document contains at least one immense term in field=\"suggest\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[115, 101, 101, 32, 13, 10, 115, 101, 105, 116, 101, 32, 50, 32, 102, 114, 97, 110, 107, 102, 117, 114, 116, 101, 114, 32, 97, 108, 108, 103]...', original message: bytes can be at most 32766 in length; got 33851. Perhaps the document has an indexed string field (solr.StrField) which is too large"`
looks like the fulltext_tesim has UTF8

**Comment by mikeapp** [comment]
The batch jobs don't seem to have an error, e.g., https://collections.library.yale.edu/management/batch_processes/12973 ?d

**Comment by martinlovell** [comment]
If may be that the managed-schema is out of date.  SOLR for digitalcollections uses managed schema, so once the core is created, the schema must be updated using API calls to SOLR.

Although we have this PR (https://github.com/yalelibrary/yul-dc-solr/pull/17), looking at managed schema on test, we get this:

```
  <copyField source="*_tsim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_tesim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_ssim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_si" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_tsim" dest="suggest"/>
  <copyField source="*_tesim" dest="suggest"/>
  <copyField source="*_ssim" dest="suggest"/>
  <copyField source="*_si" dest="suggest"/>
  <copyField source="*_tsim" dest="spell"/>
  <copyField source="*_tesim" dest="spell"/>
  <copyField source="*_ssim" dest="spell"/>
  <copyField source="*_si" dest="spell"/>
  <copyField source="author_tsim" dest="author_spell"/>
  <copyField source="subject_ssim" dest="subject_spell"/>
  <copyField source="title_tsim" dest="title_spell"/>
```
(running curl from the docker image on test: curl 'http://yul-dc-test-solr.yul-dc-test:8983/solr/blacklight-core/admin/file?file=managed-schema')

I assume we'd see something similar on UAT and Production.

So, we need to update the schema to remove the copyField using API calls.
We have done this previously with migrations: https://github.com/yalelibrary/yul-dc-management/blob/main/db/migrate/20210610133513_create_solr_ocr_field_type.rb
This could also be done manually.

This is the API documentation: https://solr.apache.org/guide/8_0/schema-api.html#delete-a-copy-field-rule
For the other schema api calls, we added a method in SolrService to perform the change.

**Comment by sshetenhelm** [comment]
Created ticket #2539 to revisit the work on this particular parent object after #2531 has been completed. Closing this ticket as the rest of MS 2004 has been successfully migrated.
