### ISSUE TITLE
Migrate public materials from Kissinger 1981

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2367]
**Story**
Migrate the 'Open for Research' materials from Kissinger MS 1981 (PID 35) from FindIt into DCS.

**Acceptance**
- [x] Provide list of parent OIDs (Summer)
- [x]  Export image files from Fedora
- [x]  Import image files into the DCS pairtree
- [x]  Import the objects into DCS UAT into the MSSA admin set
- [x]  Convert illegal/malformed utf-8 ocr files
- [x] Import text files for objects into DCS UAT 
- [x] Audit objects in DCS UAT for file/other ingest errors
- [ ] Audit objects in DCS UAT for full text ingest errors
- [ ]  Audit objects in DCS UAT for Preservica/ASpace information
- [ ]  Audit objects in DCS UAT with collection owner
- [x]  Import the objects into DCS PROD into the the MSSA admin set
- [x]  Audit objects in DCS PROD for file/other ingest errors
- [x] Audit objects in DCS PROD for full text ingest errors
- [x]  Audit objects in DCS PROD for ASpace information
- [x]  Audit objects in DCS PROD with collection owner
- [x]  Update handles URLs to point to DCS

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale list of 5,953 public parent OIDs from MS 1981: 

[MS1981_publicparents.csv](https://github.com/yalelibrary/YUL-DC/files/12113347/MS1981_publicparents.csv)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Still copying images files into the DCS pairtree, and copying ocr to UAT bucket. It will take a few days due to the number of the images/ocr.
3814 child oids are missing tif



[kissinger_1981_noimage.csv](https://github.com/yalelibrary/YUL-DC/files/12280188/kissinger_1981_noimage.csv)


124 children without ocr:


[1981_2_ocr_missing.csv](https://github.com/yalelibrary/YUL-DC/files/12280194/1981_2_ocr_missing.csv)

**Comment by sshetenhelm** [comment]
The 124 parent oids that do not have children are all for audio or video files that are in Aviary. They can be excluded from DCS.

For the 3,814 child oids that are missing TIFs, we need images for only two of them:
17489701 - Placeholder image indicating something was removed from this object
17489702 - Placeholder image indicating something was removed from this object

I will try and wrangle those two images. 

Still checking on OCR. Apologies for the delay!

**Comment by MaggieZhaoYale** [comment]
5830 parents created. 
I will list the parents which have missing  images.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 
In addition to include the parent oids which have missing images, also have parents having one or more child images failed to convert to ptiff. 
[1981_public_parents_missing_images_0912.csv](https://github.com/yalelibrary/YUL-DC/files/12588588/1981_public_parents_missing_images_0912.csv)

**Comment by sshetenhelm** [comment]
Thank you Maggie, I'll start investigating.

**Comment by sshetenhelm** [comment]
Deleted 66 objects with 0 children because they were hierarchical parents only. Working through remaining parents.

Currently: 
4,193 in Blacklight UAT
5,763 objects in MGMT UAT

1 object has been set to Private pending Sensitive Material review.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Could you please try and re-ingest all the child images from FindIt for each parent OID on this list? 

[MS1981_27parents_formerlypermission.csv](https://github.com/yalelibrary/YUL-DC/files/12730443/MS1981_27parents_formerlypermission.csv)

- [ ] Reingest child images for 27 parent objects

It looks like many of the failed parents had their permissions switched last year in FindIt from 'Open with Permission' to 'Public'. If the above images fail, we might need to look at problems with LB/FindIt/Hydra, if possible.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm 28 parents re-ingested https://collections-uat.library.yale.edu/management/batch_processes/1560

**Comment by sshetenhelm** [comment]
Excellent! Confirming that these parents appear in Blacklight after running the 'recreate child OID ptiff' job and updating visibility to Public.

Could you please try to reingest this next batch? There are 321 parents. 

- [ ] Reingest 321 parent objects

**Comment by MaggieZhaoYale** [comment]
Batch process of 321 parents https://collections-uat.library.yale.edu/management/batch_processes/1578
Full text update: https://collections-uat.library.yale.edu/management/batch_processes/1579

**Comment by sshetenhelm** [comment]
Currently: 
4,543 in Blacklight UAT 
5,763 objects in MGMT UAT 
Difference of 1,220

@MaggieZhaoYale could you please start on the next batch? There are 265 in this one. 

[MS1981_265.csv](https://github.com/yalelibrary/YUL-DC/files/12819924/MS1981_265.csv)

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm  These records https://collections-uat.library.yale.edu/management/batch_processes/1583 are  not found in metadata-uat (not in ladybird uat), but in the in the production. 
Batch process got this error:  SetupMetadataJob failed to retrieve authoritative metadata. [https://metadata-api-uat.library.yale.edu/metadatacloud/api/1.0.1/ladybird/oid/11786548?include-children=1&mediaType=json]
https://metadata-api.library.yale.edu/metadatacloud/api/1.0.1/ladybird/oid/11786548?include-children=1&mediaType=json has the record.

**Comment by sshetenhelm** [comment]
Currently: 
4,806 in Blacklight UAT 
5,763 objects in MGMT UAT 
Difference of 957

Most recent batch had unknown problems with Problems with 11784882 and 11786444. Will try to troubleshoot.

@MaggieZhaoYale could you please start the next batch? There are 343 parents in this one. 

[MS1981_343.csv](https://github.com/yalelibrary/YUL-DC/files/12873081/MS1981_343.csv)

**Comment by MaggieZhaoYale** [comment]
Batch Create 343 parents:https://collections-uat.library.yale.edu/management/batch_processes/1616
update fulltext: https://collections-uat.library.yale.edu/management/batch_processes/1617

**Comment by sshetenhelm** [comment]
5,149 in Blacklight
5,763 in MGMT
Difference of 614

Thanks @MaggieZhaoYale ! Can we please start the last big batch? There are 577 in this one: 

[MS1981_577.csv](https://github.com/yalelibrary/YUL-DC/files/13030164/MS1981_577.csv)

**Comment by MaggieZhaoYale** [comment]
577 batch https://collections-uat.library.yale.edu/management/batch_processes/1626

**Comment by sshetenhelm** [comment]
Blacklight - 5,721
Management - 5,763

Difference of 42, working on identifying outstanding parents

**Comment by sshetenhelm** [comment]
Have identified 40 of 42 outstanding parents.

For the following 8 parents, **all images appear to be ingested into UAT**, but even though they appear to Complete the ‘recreate child oid PTIFF’ batch process, they cannot go through the full update process, because **Metadata Cloud returns an “Unauthorized Access Restriction” error:**
11774423
11774476
11775541
11780820
11782421
11783774
11784882
11786444

The following 5 parents are missing all of their images in UAT, and **they also have the ‘Unauthorized Access Restriction’ Metadata Cloud message:**
11780150
11783337
11783678
11784375
11784739

The following 1 parent is missing 24 images in MGMT and has the 'Unauthorized Access Restriction' in MC. However, it looks fine in LB.
11782557

For the above 14 parents, 

- [ ] I will reassociate with their ArchivesSpace records to pull in the Metadata (they are described in TEST Aspace). 

If that works...

- [ ] I will recreate child oid PTIFFs for the first 8
- [ ] I will ask Maggie to try and pull in images for the other 6. 

The following 2 parents have two child objects each that fail to load. In LB, these child images are just black boxes. **LIT and Curator are investigating and will report back hopefully next week:**
11781151
11781202

The following 10 parents still have ‘Open with Permission’ images in LB, despite being open to the public (similar to some MS 2004 objects, as per TICKET). I will try to re-open them in LB/FindIt. If publishing to LB/FindIt is still not working, I will create a ticket to address at a later date:
11785184
11785197
11785321
11785322
11785618
11785619
11785849
11785850
11785851
11786356

- [ ] I will try to re-open in LB

The following 14 parents are missing all of their images in MGMT, but look fine in LB. Could @MaggieZhaoYale please try to re-ingest these 14 parents?
11782688
11783462
11783611
11784237
11784239
11784603
11784665
11786920
11786958
11786964
11787006
11787102
11787105
11787109

- [ ] 14 parents re-ingested

**Comment by sshetenhelm** [comment]
For the following 8 parents, even though the 'recreate child OID ptiff' batch process shows as successful, the child images still refuse to generate: 

11774423
11774476
11775541
11780820
11782421
11783774
11784882
11786444

@MaggieZhaoYale is this something you would be able to investigate? I think 11774423 at least is reporting a 'Malformed UTF-8' error.

**Comment by MaggieZhaoYale** [comment]
Reprocessed the 8 records https://collections-uat.library.yale.edu/management/batch_processes/1651, manifest saved, solr indexed, pdf generated, did not see related failure in the delayed job board, but solr document return nothing

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Just realized that these records are private. If change to public, they'll work.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Some Partial full text may be caused by blanket images. I could create txt files for if these children are identified.

**Comment by MaggieZhaoYale** [comment]
Reprocessed 6 Unauthorized Access Restriction and 10 Open with Permission https://collections-uat.library.yale.edu/management/batch_processes/1659. All look good except one parent 11780150. This oid has different data on uat/test data and prod.
parent 11780150 has 114 children in Fedora and Ladybird production, 154 children in test/uat. 154 children in DCS https://collections-uat.library.yale.edu/management/parent_objects/11780150
The images and ocr are downloaded from production fedora, so no images are found https://collections-uat.library.yale.edu/management/batch_processes/1659/parent_objects/11780150. Can we ignore this on UAT?

**Comment by sshetenhelm** [comment]
**Parents -** 
Blacklight - 5757
MGMT - 5763
Difference of 6

**Full Text -** 
Yes - 847
Partial - 4823
None - 93

92 out of 93 objects (360 children) have Full Text = None, and do not include any text documents. 

@MaggieZhaoYale, could you please generate and add 360 blank text files for the children on the following list of parent/child oids? 

I will:
(a) Look into 11780150
(b) Work on the partial text parents

**Comment by MaggieZhaoYale** [comment]
Investigated detecting photographs from images with text. I tried python script to detect a few P35 images with opencv-python and pytesseract and got pretty accurate results.
Require:  update Python to 3.6+, and install opencv-python and pytesseract on yul-fi-prd1 server

**Comment by sshetenhelm** [comment]
We are bumping to PROD despite still need to resolve some OCR issues, etc., due to recent events. 

* 5,763 objects in DCS PROD for MS 1981 -- Thank you Maggie!
* 1,847 as of 2023.11.30 1:37 pm in Blacklight PROD
* I am working on Aspace reassociations -- these are all described at object level, so just matching some things up
* Lauren is working on OCR

**Comment by MaggieZhaoYale** [comment]
p35 has 5763 parents in both management and blacklight

**Comment by sshetenhelm** [comment]
5763 objects in blacklight

Full Text
Yes -17
Partial - 4
None - 5742

@MaggieZhaoYale I see there are some full text updates running. Did all the files come over too? Curious why "None" is so high here.

**Comment by sshetenhelm** [comment]
We've received the batch of not-full-text from Maggie and will look into missing text.

**Comment by sshetenhelm** [comment]
1524 child objects are confirmed to have missing OCR. They are in this spreadsheet: 

[MS1981_OutstandingOCR.csv](https://github.com/yalelibrary/YUL-DC/files/13707371/MS1981_OutstandingOCR.csv)

13 parent objects have missing OCR and have children that did not flip to open properly in Ladybird/FindIt. They are as follows: 
11775554
11775580
11780209
11782324
11782427
11782962
11782974
11783222
11783515
11784217
11785197
11785322
11785848

We need to (a) flip the children of these parents to 'open' in FindIt/Ladybird, (b) confirm they have the same number of children in DCS as FindIt, and (c) confirm if they are missing OCR in FindIt.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm105 children of the above 13 parents do not have ocr


[1981_fulltext_blank_1220.csv](https://github.com/yalelibrary/YUL-DC/files/13728474/1981_fulltext_blank_1220.csv)

**Comment by sshetenhelm** [comment]
Only one of those objects should have OCR, so now the total number of objects that need to have OCR files attached is 1525. I've added that child to this list:
[MS1981_OutstandingOCR.csv](https://github.com/yalelibrary/YUL-DC/files/13729760/MS1981_OutstandingOCR.csv)

@MaggieZhaoYale can you try again to get the OCR files from Ladybird/FindIt for the 1525 children on the list, or do Lauren and I need to find and provide those files for you?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Found 1458 OCR files and were copied to prod-ocr bucket. 
Attached are the 67 child oids without OCR in Findit. 

[1221.csv](https://github.com/yalelibrary/YUL-DC/files/13742207/1221.csv)

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale I've spot-checked the above files in Ladybird, and none of them have full text. Could you please generate and attach blank .txt files for the above 9 children?

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Generate the blank txt and updated the full text status. There are still 129 parents have partial full text. I am checking them.

**Comment by sshetenhelm** [comment]
All parents have Full Text = Yes in Management App! Yay!

Starting on matching with Aspace URIs. Once source is switched, object will sync/recreate and accurate Full Text status will start appearing in Blacklight.

**Comment by MaggieZhaoYale** [comment]
Yay!

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Could you please provide the handles for us? Thank you!

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm The list of old and new handles is attached:


[kissinger_1981_handle.csv](https://github.com/yalelibrary/YUL-DC/files/13866520/kissinger_1981_handle.csv)

**Comment by sshetenhelm** [comment]
Sent email to check in with Josh re: approval. Received email stating OOO with intermittent email access until Thursday. Still in waiting.

**Comment by sshetenhelm** [comment]
Ready to clooooose! Thanks so much @MaggieZhaoYale and @laurenb33
