### ISSUE TITLE
Implement "show" for an individual T&C 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2369]
**Story**

Show an individual T&C.

**Acceptance**
- [x] Link from "view" from T&C management page in #2357
- [x] Permission: restrict to admins of the permission set
- [x] "Back" links back to T&C management page

![Create TCs - View Terms-2.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/15a5842c-8e37-4d73-81fa-d59de09df5fa)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1136

**Comment by jpengst** [comment]
Deployed to Test v2.59.89

**Comment by K8Sewell** [comment]
Show page renders on Test.  Will promote to UAT.
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/5c1c9843-0f4f-47f0-b5ec-964e963ac2ed)
