### ISSUE TITLE
See images in Universal Viewer on development environments

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#237]
Currently starting up the services together locally from yul-dc-camerata doesn't show images in Universal Viewer, because the manifest server builds URLs that expect the port of the manifest server and the port of the image server to match; this is true in deployed environments but not on local builds.

One option to harmonize the services (per McClain) "you'd need to set up something like pound and reproduce the ALB configuration (path based routing) and access the local cluster through it so everything goes over the same port externally, as is in production
https://linux.die.net/man/8/pound "

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/e6e86b47-4634-4184-b587-3b0b60633a5d)

In progress: uses changes in https://github.com/yalelibrary/yul-dc-iiif-manifest/tree/template and https://github.com/yalelibrary/yul-dc-camerata/tree/manifest-template to generate manifests that know the image server is in a different place than the manifest server (http://localhost/ vs. http://localhost:8182)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/64ba5526-ce5b-4973-86c3-6aaccb15466b)

Not tested on a deployed environment yet so not ready to PR.

**Comment by fnibbit** [comment]
Manifest service v2.0.0 has been released, https://github.com/yalelibrary/yul-dc-camerata/pull/53 has details on the test deploy.    Spinning up locally from the camerata docker-compose looks like screenshots above, as does spinning up locally from docker-compose in https://github.com/yalelibrary/yul-dc-blacklight/pull/133

**Comment by K8Sewell** [comment]
Testing this out locally worked great.  Did encounter a bug but making another ticket for the unrelated issue.
