### ISSUE TITLE
Review On Campus IP List

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#2373]
**Story**

We'd like to be sure our list of Yale IP ranges is up to date. Up to date list is here https://web.library.yale.edu/departments/e-resources/ip?app=yalesites

**Acceptance**
- [x] Review parameter store list against the published on campus IP list.

**Comment by jpengst** [comment]
There are 3 IP ranges in the parameter store. The only one **_not_** listed in the updated IP ranges is 172.16.*.*
