### ISSUE TITLE
API call to retrieve Terms for a Permission Set

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2376]
**Story**

We'd like the Blacklight instance to be able to retrieve the active Terms and Conditions for a Permission Set.

**Acceptance**
- [x] For a GET from  `/api/permission_sets/:id/terms` Return the current T&Cs for the permission set
- [x] Return as JSON.  Keys:  `id` of the T&Cs, `title`, `body` 

```
{
   "id": 123,
   "title": "Lorem ipsum...",
   "body": "Nunc est bibendum,...."
}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1138

**Comment by mikeapp** [comment]
For the "no active T&Cs" case, return a HTTP 204 No Content.

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.90](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.90)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.

**Comment by K8Sewell** [comment]
To test on UAT visit https://collections-uat.library.yale.edu/management/api/permission_sets/2/terms and make sure it returns json with term info.

**Comment by mikeapp** [comment]
Found one issue, this should not require an authenticated user.  The Blacklight instance will be making the call to this, not a user.

**Comment by jpengst** [comment]
> Found one issue, this should not require an authenticated user. The Blacklight instance will be making the call to this, not a user. Created a new ticket #2397

Ah, right! Good catch, thanks!
