### ISSUE TITLE
Add a "back" link to the Manage T&Cs page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2380]
**Story**

The user should have a way to navigate back from the Manage T&Cs page to the Permission Set.

**Acceptance**
- [ ] On the Manage T&Cs page, add a "back" link beneath the Create/Remove buttons that takes the user back to the Permission Set.

![Screenshot 2023-02-13 at 2.24.54 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/1f2a407c-1a13-442a-80bd-d83647424fc8)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1142

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.92](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.92)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/220696065-2fac1fac-0493-495a-8633-efd2e3f4f06d.png)

**Comment by sshetenhelm** [comment]
Looks good! Clicked on UAT, sent me back :)
