### ISSUE TITLE
Configure AWS WAF "challenge" rule for downloads on TEST, UAT

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2381]
**Story**

We'd like to protect image downloads with ~~CAPTCHA~~  the  "challenge" method, when rate limits are exceeded.
https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html

See discussion in comments below. 

**Acceptance**
Create a rule in the AWS WAF to protect the route `/download/tiff/*` with a  "challenge" when the rate limit is exceeded:
- [x] on DEMO
- [x] on TEST
- [x] on UAT

If this works,
- [x] Create ticket for PROD

**Comment by sshetenhelm** [comment]
1. Are there any accessibility issues to take into consideration if using a CAPTCHA? 

2. If going the browser/javascript route, are there any privacy issues to take into consideration? What info is being passed, etc.? 

If going captcha route, I'm in favor of something that kicks in after a certain # of downloads as opposed to being required for all downloads.

**Comment by mikeapp** [comment]
I'll send a video of the Captcha.  It does have an audio option for accessibility and is available in 10-12 languages.

For the "Challenge" option it loads a page w/Javascript that processes some data that's unique per-request and sends it back to the server. To the user it just looks like a blank screen for a fraction of a second.  It "proves" there's a browser because the Javascript is executed.  I don't believe it is storing any data long term.   It does set a cookie so that the firewall can track that you've passed the Captcha/Challenge and not show it again for few minutes.

The minimum threshold for rate-based limiting is 100 requests in a 5 minute period.  It seems like it would be difficult for a human to trigger that by clicking in the viewer.   

Another option would be to just block requests from that IP when the request threshold is reached, the user or system would have to wait for a minute or two before they could download any more.  This would be simpler than CAPTCHA/Challenge but would not be as effective in blocking bulk harvesting.

**Comment by sshetenhelm** [comment]
We would like to move forward with the "challenge" option, if possible.

After speaking internally, some team members feel this would provide the most streamlined/non-disruptive user experience.

**Comment by sshetenhelm** [comment]
Michael will meet with DevOps

**Comment by ra359** [comment]
Started looking at the WAF doco - nothing configured yet.

**Comment by mikeapp** [comment]
Route is `/download/tiff/*`
