### ISSUE TITLE
Management data model and API to record user agreement to Terms and Conditions.

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2383]
**Story**

When a user agrees to a permission set's terms in Blacklight (TBD what this looks like!) the Blacklight instance should make a service call to management to created a record of that agreement.

Q: shorten the route?

**Acceptance**
In Management:
- [x] Create a model `PermissionSetTermsAgreement` that stores:
   - [x] a reference to the PermissionSetTerms
   - [x] a reference to the PermissionRequestUser
   - [x] a timestamp indicating the time the agreement was recorded (`agreement_ts` ?)
   - [x] We will want to query by user frequently, so this should be indexed (probably will be by default...)
- [x] Create an API at `/api/permission_sets/:id/permission_set_terms/:id/agree/:sub` that receives a POST and:
  - [x] looks up the user by PermissionSetUser.sub
  - [x] looks up the PermissionSetTerms by id
  - [x] creates the `PermissionSetTermsAgreement`  record with the current timestamp as the `agreement_ts` 
  - [x] Return HTTP 400 Bad Request if the user and/or terms don't exist
  - [x] Return HTTP 500 for all other errors

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1148

**Comment by mikeapp** [comment]
I don't think we need `app/controllers/terms_agreements_controller.rb` if all creation is handled through the `permissions_sets_controller.rb` ... or is there is a reason to keep it?

**Comment by jpengst** [comment]
Good point. PR updated

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.94](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.94)

**Comment by K8Sewell** [comment]
Getting an access denied instead of the expected 400 error when the user doesn't exist (I have no way of creating a PermissionRequestUser) so putting this back in progress.


![Image](https://user-images.githubusercontent.com/36549923/223837912-a96dd440-ce18-4a46-9980-3cfb9c2a228c.png)

**Comment by jpengst** [comment]
Bug fix PR: https://github.com/yalelibrary/yul-dc-management/pull/1152

**Comment by jpengst** [comment]
Deployed to Test v2.59.95
