### ISSUE TITLE
Add IIIF Manifest "rendering" for original image download

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2390]
**Story**

The IIIF Manifest should contain a `rendering` property for each Canvas that references the original image download.

See https://iiif.io/api/presentation/3.0/#rendering

**Acceptance**
- [ ] In the IIIF Manifest generation code, add a `rendering` for each Canvas.
- [ ] The `id` should be `https://{host}/download/tiff/{child_oid}`
- [ ] The `label` should be "Full size original"
- [ ] The `type` should be `Image`
- [ ] The `format` should be `image/tiff`

**Note:** This needs to go into a new feature branch with downloads for management

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1147

**Comment by K8Sewell** [comment]
Ran into the same issue twice trying to deploy the feature branch to Demo


![Image](https://user-images.githubusercontent.com/36549923/222250810-470172e0-04ba-4095-8283-b04092982d1e.png)

**Comment by mikeapp** [comment]
Looks good on demo.
