### ISSUE TITLE
Fix nightly update job on UAT

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2395]
**Story**
On UAT nightly metadata update job stopped on 2/16

**Acceptance**
- [x] Fix and allow nightly jobs to run
- [x] Check demo and test?

**Comment by sshetenhelm** [comment]
Didn't see that this ran in UAT, and there are no pending jobs listed: 



![Image](https://user-images.githubusercontent.com/98423494/228919248-15ec1525-93bf-44c7-bdca-8c438c54c63f.png)

**Comment by martinlovell** [comment]
It should be setup now.  (I think I started it in Demo but forgot UAT after manually resetting the "Running" job).

When there's not a stuck job, admins for management can click "Check status of Recurring Jobs" and then kick it off if it's not running.  If the most recent job is listed as "Running" but it's old, it's probably stuck and you won't be able to kick it off in the UI.

We could add something to the UI to allow admins to Reset the recurring jobs, which would change the status from "Running" to "Manually Reset" if the recurring job is more than, say, a day old (and it's not actually running.)  This would allow users to fix the stuck recurring jobs using the UI.  (currently I log in and do it manually from the command line.)
It's not that often, so maybe not high priority.  @sshetenhelm , let me know if you want me to add a ticket for a UI reset of stalled Recurring Jobs.

**Comment by sshetenhelm** [comment]
@martinlovell not high priority, but definitely a useful feature to have! Could you please add a ticket in the backlog for a UI reset of stalled recurring jobs? I'd love to have it put in place once we have finalized some of our other priorities. Thank you for being so thoughtful!

**Comment by martinlovell** [comment]
I added a ticket to the backlog: https://github.com/yalelibrary/YUL-DC/issues/2446
