### ISSUE TITLE
Authenticate users against Yale CAS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#240]
**STORY**
As a repository owner, I want users to be able to log in with their Yale NetID, so that I can display images restricted to the Yale community to them.

**ACCEPTANCE**
- [ ] I can log in to the discovery application using my Yale NetID
- [ ] When I am logged in I can view works restricted to the yale community - e.g. https://collections-demo.curationexperts.com/catalog/16189097-yale should display Universal Viewer and the Map when I am logged in with my NetID (and only when I am logged in)

**Comment by mikeapp** [comment]
I put together a vanilla Rails app that will sign you in via CAS:
https://github.com/mikeapp/omniauth-cas

**Comment by FCRodriguez7** [comment]
Test examples: 
https://github.com/dlindahl/omniauth-cas/blob/master/spec/omniauth/strategies/cas/logout_request_spec.rb

https://github.com/dlindahl/omniauth-cas/blob/master/spec/omniauth/strategies/cas_spec.rb

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/132

**Comment by FCRodriguez7** [comment]
Rubocop issue: 
app/controllers/omniauth_callbacks_controller.rb:6:5: W: Lint/NestedMethodDefinition: Method definitions must not be nested. Use lambda instead.
    def auth ...


A solution: 
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/NestedMethodDefinition

**Comment by mark-dce** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/3064318/85426671-68435900-b540-11ea-9940-f5f34a8bfc83.png">
