### ISSUE TITLE
Test Preservica Integration Workflows in DCS Production

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2400]
**Story**

Yale's production instance of Preservica is due to switch over to version 6.5 (the target version for the upgrade) on Monday 02/23/2023. DPS are not yet sure whether full functionality will be available at that point but they do expect to be able to at least provide access via the (v6) User Interface and via the (v6) API. They will update Yale staff on Monday with more information and a timeline for the remaining functionality to be available (they expect it will be no more than a few days later).

This allows for our DCS/Preservica integration to move into Production use. While there is still one large piece of work left on the DCS side, see #2168, this does not stop us from moving all the work we have done already into Production, as what we have will already allow us to do the majority of the ingest work we want to start at the library. 

Testing should follow the draft documentation creating for ingesting content into Preservica https://docs.google.com/document/d/1_Hx8YQYO56EK_1-rQnBTSKQ5m_khhjY4ACMKeXW8oeU/edit?usp=sharing. For this testing, we will use content from the Music Library's collections, that are in Preservica and waiting for ingest into DCS https://docs.google.com/spreadsheets/d/1BJtN4sspxKDkDkIIXOor43NCTmic53MO9Yu1WYsCMio/edit#gid=0 (things that are not green) 

**Acceptance**
- [x] Test Alicia's script for pulling Preservica IDs based on ASpace IDs for Structure 2
- [x] Investigate Structure 2 parents that failed to ingest into DCS (in note below)
- [x] Test workflow: Create a new parent object in DCS (Preservica Structure 1)
- [x] Test workflow: Create a new parent object in DCS (Preservica Structure 2)
- [x] Test workflow: Create multiple new parent object in DCS
- [x] Resync all objects in MUSICINGESTDEFAULT with Aspace
- [x] Test Alicia's script for pulling Preservica IDs based on ASpace IDs for Structure 1
- [x] Test workflow: Add a single new image to an existing parent in DCS
- [x] Test workflow: Delete a single image for an existing parent in DCS
- [x] Test Workflow: Replace a single image for an existing parent in DCS
- [x] Test Workflow: Reorder a single image for an existing parent in DCS
- [x] Create for resync and ptiff jobs. These should be priortized above PDF jobs
- [x] Create ticket for .tif vs .TIF issue if needed

**Comment by motropuk** [comment]
Successfully ingested an object into DCS Prod pulling from Preservica Prod https://collections.library.yale.edu/catalog/32501372 

Working on adding identifiers for objects to use in testing, that @sshetenhelm will then use to test the rest of the workflow. Reminder that add/delete/replace/and reorder for single images will not work if the object in Preservica is packaged using Structure 2. Only works on Structure 1. See https://docs.google.com/document/d/1_Hx8YQYO56EK_1-rQnBTSKQ5m_khhjY4ACMKeXW8oeU/edit#heading=h.1p8y2wz7c5zo.

**Comment by motropuk** [comment]
Also successful ingest using Structure 1 https://archives.yale.edu/repositories/6/archival_objects/2537154

**Comment by motropuk** [comment]
One of the biggest challenges with the current Ingest from Preservica to DCS workflow is identifying Preservica IDs at scale. If something is packaged in Structure 2 in Preservica, you can use the ID that is also in ASpace, so thats easy, and I am sure we could script a way to pull these IDs from ASpace based on ASpace URI. However, you cant update any children in Structure 2, so we are suggesting people ingest using Structure 1, which would then include a subfolder for the TIFF images. See https://docs.google.com/document/d/1_Hx8YQYO56EK_1-rQnBTSKQ5m_khhjY4ACMKeXW8oeU/edit#heading=h.1p8y2wz7c5zo for info about all this. However, for structure 1, the ID in ASpace takes you to the parent record in Preservica. The ID we would need to provide to DCS would be for one of the child folders in that parent record, say the one containing the TIFF images. I need to check in with @ucancallmealicia about this when she is back next week, so moving this ticket back to in Sprint for now until I can speak with Alicia more about this

**Comment by motropuk** [comment]
Successfully used the .sql script Alicia created to pull several parent objects from Preservica, that use Structure 2, and ingest these into DCS. Adding documentation for this here https://docs.google.com/document/d/1_Hx8YQYO56EK_1-rQnBTSKQ5m_khhjY4ACMKeXW8oeU/edit#heading=h.eib294p9et6q

No need to do the same for multiple objects that use Structure 1 and also add this to the documentation. This will involve testing the Python script Alicia created

**Comment by motropuk** [comment]
Three parents using structure 2 failed to ingest into DCS. Need to look at this and understand why. The parent records have been deleted from DCS prod. Need to look at Preservica to see what is happening here

- /repositories/6/archival_objects/2612184
- /repositories/6/archival_objects/2612890
- /repositories/6/archival_objects/2613432

**Comment by motropuk** [comment]
Cant figure out what is happening with https://preservica.library.yale.edu/explorer/explorer.html#prop:Unknown&084a501f-7579-468b-a4b9-414405a9bd23. DPS cant see any issues. Try to resync in case it failed before due to an outrage in the API call, but also failed again. Job does not "Fail" in DCS, it just does not pull in any children. Will need to make sure the job shows as failed if it does not pull anything in.

**Comment by motropuk** [comment]
So I think the issue with https://preservica.library.yale.edu/explorer/explorer.html#properties:IO&084a501f-7579-468b-a4b9-414405a9bd23 is that the files have uppercase .TIF extensions, instead of .tif, which seems to have been used for all the ingests that succeeded. I seem to remember this issue of file extension formatting came up before for us?

**Comment by motropuk** [comment]
Working on ingesting to Structure 1 parents. These are not synced with ASpace, but will allow for me to test replacement workflows. But am also working on syncing some Structure 1 objects with ASpace, so I can then also test Alicia's script for structure 1 objects

**Comment by motropuk** [comment]
Workflows above are now in Prod. Added a child image file to an existing parent in Preservica Prod. However, DCS process appears to be stalled https://collections.library.yale.edu/management/batch_processes/11947/parent_objects/32551323

**Comment by sshetenhelm** [comment]
Check priority on jobs

**Comment by motropuk** [comment]
Replacement for single child image was not successful. As you can see in Production Preservica, I have replaced a single child image to create a new generation. I ran the resync in DCS which completed successfully https://collections.library.yale.edu/management/batch_processes/11991/parent_objects/32551323. However, the child image did not update in DCS https://collections.library.yale.edu/management/batch_processes/11991/parent_objects/32551323 (the replacement is rotated 90 degrees). 

![Image](https://user-images.githubusercontent.com/13023486/228333359-a91cc757-0282-42b0-bc9a-dd7cf5014975.png)

**Comment by motropuk** [comment]
Added bit of fun - if Preservica syncs an object with ASpace that was not previously syncronized with ASpace, the checksum appears to change. This results in a previously connected DCS object throwing up a checksum error if we try to resync it with Preservica https://collections.library.yale.edu/management/batch_processes/12079

**Comment by motropuk** [comment]
Ran a resync on https://collections-uat.library.yale.edu/management/parent_objects/900148026 in UAT, to test the PR above, and the updated image is still not being picked up. This image in DCS https://collections.library.yale.edu/catalog/900148026?child_oid=900148036 should be updating to a version that is rotated 90 degrees and has a red star on it. This is the version that is in Preservica Test, but DCS is not pulling it in

**Comment by DraxIndustries79** [comment]
Waiting for Kait to return

**Comment by motropuk** [comment]
Successfully tested @ucancallmealicia script for pulling IDs from Preservica for objects packaged using Structure 1. However, ingest into DCS for these structure 1 examples is failing https://collections.library.yale.edu/management/batch_processes/12250. Could be a different issue. The batch says it's completed, but then each parent does not seem to have been created successfully. Each shows a MC issue. Have not seen this before. Could this be related to #2436 which rolled out today?

**Comment by motropuk** [comment]
Found another example of an object in Preservica that DCS will not pickup as the file extensions for the files have uppercase .TIF file extensions.

**Comment by motropuk** [comment]
I am still getting metadata cloud sync errors when trying to ingest some aspace content. Its not consistent however, and I just cant figure out what is going on here. 

[create_parent_objects_hindsight_firstfolder.csv](https://github.com/yalelibrary/YUL-DC/files/11400376/create_parent_objects_hindsight_firstfolder.csv)

Results in this batch https://collections.library.yale.edu/management/batch_processes/12273/parent_objects/32578504

Which includes this error SetupMetadataJob failed to retrieve authoritative metadata. [https://metadata-api.library.yale.edu/metadatacloud/api/1.0.1/aspace/repositories/12/archival_objects/3495096?mediaType=json

**Comment by martinlovell** [comment]
It's because the archival object is not published in archives space:
https://archives.yale.edu/repositories/12/archival_objects/3495096

(It looks like it's there, but not published based on the response here: https://metadata-api.library.yale.edu/metadatacloud/api/1.0.1/aspace/repositories/12/archival_objects/3495096?mediaType=json)

**Comment by motropuk** [comment]
Thanks @martinlovell. I thought that the publication status didnt impact MC pull? @ucancallmealicia could you clarify. I did try publishing the object in ASpace but the sync still fails. Does the whole resource need to be published for it to work?

**Comment by martinlovell** [comment]
It's checking "has_unpublished_ancestor", so if any of the parents aren't published, MC won't let DCS view the object.

**Comment by motropuk** [comment]
OK I will try publishing the collection and see if that allows us to sync

**Comment by DraxIndustries79** [comment]
ASpace record needs to be published the week of May 18

**Comment by motropuk** [comment]
Waiting on staff returning next week to publish finding aid for Hindsight so we can try to reingest this collection. Also waiting on #2471 before further testing of image replacements

**Comment by motropuk** [comment]
Will check on single image replacement once #2471 rolls into production on Wednesday

**Comment by motropuk** [comment]
Resync of single image seems to have worked in Prod. However while the image has updated in the thumbnail in the UV, the image in the main part of the UV display has not updated https://collections.library.yale.edu/catalog/32551323?child_oid=32551411. Not sure why this is and need to investigate more.

**Comment by motropuk** [comment]
UV display eventually updated and image is now rotated as expected. Will switch back to regular rotation as this was a test in prod

**Comment by motropuk** [comment]
Seems to be taking a really long time for images to update in the UV after resync and the ptiff update https://collections.library.yale.edu/catalog/32551323?child_oid=32551411. Ran a job at 9am to update this, but by 2pm it had still not updated

**Comment by DraxIndustries79** [comment]
Check back in on this after the MC issue is resolved.

**Comment by motropuk** [comment]
Created #2515 to look into job queue prioritization for preservica related tasks

**Comment by motropuk** [comment]
Setup #2516 to look into formatting issue with file extensions

**Comment by motropuk** [comment]
Running the resync again to fix this image https://collections.library.yale.edu/management/batch_processes/12847/parent_objects/32551323. Waiting for batch proceses to complete and will then test reordering

**Comment by motropuk** [comment]
Replacement image from Preservica successfully synced with DCS. Ran the PTIFF recreate job for the child object. I think this has worked as the thumbnail here has updated but again the main image in the UV has not updated (should be portrait instead of landscape) https://collections.library.yale.edu/catalog/32551323?child_oid=32551411. But I think this is due to the issue @mikeapp noted in #2503

**Comment by motropuk** [comment]
This ticket is done! Good to close. All remaining work is in other tickets that are already on the board
