### ISSUE TITLE
Create Parent Object Batch Process should generate new parent OIDs & require sources

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2403]
**Story**
As a user, I want to use the Create Parent Object batch process to create multiple new parent objects at once. Each new parent object should have an OID, be added to an admin set, and have source and metadata information.

Currently, when view on the Batch Process page, the Create Parent Object batch process returns a message of ‘The file is being generated,’ and no data appears in the table. When looking at the Delayed Job Dashboard, an error message is returned that states the following: 

    PG::NotNullViolation: ERROR:  null value in column "connectable_id" violates not-null constraint
    DETAIL:  Failing row contains (8398801, 1312, ParentObject, null, 2023-02-27 15:44:24.791606, 2023-02-27 
    15:44:24.791606, null).

We the process to successfully generate new oids and create new parent objects.

Context:
The Create Parent Object batch process will be used with objects existing in Preservica. Because objects are not being created/ingested through Goobi, there is currently no step in place to generate new OIDs for these parent objects. 

**Acceptance**

- [x] The ‘Create Parent Object’ batch process generates new OIDs for each csv row with data.
- [x] The ‘Create Parent Object’ batch process displays the new parents in the Batch Process data table.
- [x] The ‘Create Parent Object’ batch process displays a message to the user on the Batch Process page if it fails. 

- [x] The ‘Create Parent Object’ batch process fails if there is no source information.
- [x] The ‘Create Parent Object’ batch process fails if there is no set information.

**Comment by K8Sewell** [comment]
Could we get the csv or link to this job that created the error above?

**Comment by sshetenhelm** [comment]
In UAT, Batch Process [1312](https://collections-uat.library.yale.edu/management/batch_processes/1312)

**Comment by sshetenhelm** [comment]
Parent object with 0 children created in UAT, required "set" and defaulted to "ArchivesSpace" for source
https://collections-uat.library.yale.edu/management/parent_objects/900148394

**Comment by sshetenhelm** [comment]
Updating to say that Jon was able to create parents using the batch process with Preservica information in the spreadsheet, and it created OIDs: 
https://collections.library.yale.edu/management/batch_processes/11806/
https://collections.library.yale.edu/management/batch_processes/11802/

**Comment by K8Sewell** [comment]
Because of the way we are using `next` I wasn't able to refactor as much as I would have liked to but the PR is ready for review and it's working - https://github.com/yalelibrary/yul-dc-management/pull/1149

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.96](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.96)

**Comment by sshetenhelm** [comment]
[Batch 631](https://collections-test.library.yale.edu/management/batch_processes/631) -- Created parents even though 'source' was not filled out (although had aspace uri in spreadsheet). Parents defaulted to Ladybird as source. These parents should not have been created. 

[Batch 633](https://collections-test.library.yale.edu/management/batch_processes/633/download) -- Did not create parents even though 'source' and 'aspace_uri' were filled out. Failure message: "Setup job failed to save: ArchiveSpace uri required to build ArchiveSpace url"

**Comment by jpengst** [comment]
I think the Batch 633 error listed above might be an existing bug. I'm still getting that error on test and UAT after this PR was reverted and deployed.

**Comment by jpengst** [comment]
Also deleted an existing complete aspace record and recreated it via BP and got the same error.

**Comment by sshetenhelm** [comment]
Created #2436 to address bug with aspace uris

**Comment by jpengst** [comment]
PR Bug Fix for Source validations: https://github.com/yalelibrary/yul-dc-management/pull/1161

**Comment by martinlovell** [comment]
v2.59.99

**Comment by K8Sewell** [comment]
I had a permission failure even though I'm an editor on this admin set so I may need some one else to test this on Test.  In the meantime I will move this back to in progress because I should have access to make this change.


![Image](https://user-images.githubusercontent.com/36549923/229232270-ba738a30-9ef7-4445-a644-468aa3d49b02.png)

**Comment by sshetenhelm** [comment]
Removed and tried to re-add Kait as editor of this set, received message that her account was deactivated, even though it shows as active in users. Created bug ticket #2451
