### ISSUE TITLE
Dependabot - Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2405]
# Summary
CSRF vulnerability in our version of omniauth.  https://github.com/yalelibrary/yul-dc-blacklight/security/dependabot/159

# Acceptance Criteria
- [x] Apply Ruby fixes

**Comment by K8Sewell** [comment]
Mike actually fixed this for us and made the necessary changes already - https://github.com/yalelibrary/yul-dc-blacklight/pull/461
