### ISSUE TITLE
Objects with permissions "issues" ingest as Private Visibility

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2406]
This ticket is created in response to #2379

**Story**
Objects with Visibilities other than Public, Private, or Yale Community Only (ex. Open with Permission) may fail to ingest correctly into DCS. For example, the 120 Kissinger MS 2004 objects with a Visibility of Open with Permission migrated without metadata or child objects attached. In these instances, we want the objects to default to a Visibility of Private in order to ingest correctly. 

**Acceptance**

- [x] Objects with visibilities other than Public, Private, or Yale Community Only successfully ingest into DCS under the Visibility of Private
- [x] Child objects attached to these parent objects successfully ingest
- [x] The number of child objects displays in the Parent Objects table

**Comment by jpengst** [comment]
Child Objects created successfully:  


![Image](https://user-images.githubusercontent.com/24666568/224857775-3d9a8df1-5c80-401f-8b17-d98134e00a0b.png)

  
Datatable now counts the correct child count (object 12479170):  


![Image](https://user-images.githubusercontent.com/24666568/224857831-2bb5eca1-9488-41d3-bf80-b8d7639de902.png)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1154

**Comment by sshetenhelm** [comment]
Appears to be working in UAT! Will close to get points in current sprint; thank you so much!
