### ISSUE TITLE
IIIF Manifest generation throws an error if it encounters a child with no image dimensions.

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2409]
# Summary
IIIF Manifest generation throws an error if it encounters a child with no image dimensions.  On Admin Set show page the Update IIIF Manifests button was clicked and triggered a large number of jobs.  Some failed.  This ticket aims to address the cause of the failure.

stack trace: undefined method `>' for nil:NilClass
sample failed job: https://collections-demo.library.yale.edu/management/delayed_job/failed#6862859

Honeybadger:
`NoMethodError: undefined method `>' for nil:NilClass` at 
`/app/models/iiif_presentation_v3.rb:256:in `scaled_image_dimensions'`

# Acceptance
- [x] job terminates and writes a message to log indicating it's not producing the manifest because there's a child missing it's dimensions
- [x] does not queue subsequent PDF job

**Comment by mikeapp** [comment]
Looks like no image / dimensions are available, e.g., parent 10546047

**Comment by mikeapp** [comment]
Note that a separate job checks for broken children, so we are OK to log an error here and consider the job complete.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1201

**Comment by jpengst** [comment]
Deployed to Test v2.61.3

**Comment by K8Sewell** [comment]
Rework PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1206

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.61.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.61.4)

**Comment by sshetenhelm** [comment]
Updated IIIF manifests for Arts set on UAT, which should have a number of child objects with no image dimensions. What particularly should I be looking for to approve this?

**Comment by DraxIndustries79** [comment]
@sshetenhelm Have a look at the delayed jobs dashboard.  Should say "IIIF Manifest not created, child object, OID does not have valid dimensions"

**Comment by sshetenhelm** [comment]
No new IIIF manifest errors on UAT! Looks good, ready to close, and thank you!
