### ISSUE TITLE
Search by BibID

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#241]
**STORY**
As a researcher, I'd like to be able to search by a work's BibID, so that I can quickly find the digital version of an item I've found in the main catalog.

![Screen Shot 2020-06-16 at 10.38.18 AM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/e33c83dc-2bd1-46c8-ae6b-06d01446dcf4)

**ACCEPTANCE**
- [ ] In the search drop-down, I have an option to restrict my search to BibID
- [ ] When I select search by BibID and and enter the corresponding BibID, I get the work(s) that have that BibID

**Comment by FCRodriguez7** [comment]
I looked for a few BibID to search: 

1289001
16414889
3577942

**Comment by FCRodriguez7** [comment]
I have a draft PR. I need to finish the test.   

Frederick

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-06-17 at 8.46.39 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/17885118-b56c-45ea-8478-3c78ad364257)

**Comment by FCRodriguez7** [comment]
I have a test for this feature.
