### ISSUE TITLE
Modify download original redirect

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2416]
# Summary
Currently the 'download/tiff/oid' will redirect to a search for the child oid.  Instead of this the process should redirect to a new page with language describing the availability of the image, the move to a new tab, and refresh every 60 seconds to pull the download for the user.

# Acceptance
- [ ] clicking 'download original' link in UV redirects to new page 
- [ ] new page has logic to call if object is on S3 and to download the object once 
- [ ] new page includes language "You have been redirected to a new tab.  The image is not available for download yet.  The image will download when it is available."

# Example Design

![Image](https://user-images.githubusercontent.com/36549923/224411074-5f988abf-e252-40f7-8d05-ba79289a15fb.png)

**Comment by mikeapp** [comment]
@K8Sewell  There may be an issue with the Chrome behavior where the page stays visible when the download executes (i.e., if I reload the page the HTML is still visible even if the download succeeds).   Could Javascript running in the page continue to run and continue to download the image every X seconds?    Also we run the risk of re-queueing the job multiple times if the backend isn't processing them efficiently. 

It seems like it would be better to implement a route that returns the download status (i.e., is the item in S3).   The Javascript could poll that status route until the file is ready, then exit the loop and trigger the download.

**Comment by sshetenhelm** [comment]
Language with minor change:
"You have been redirected to a new tab. The image is not available for download yet. This page will refresh every minute. The image will download when **it** is available."

Thank you :)

**Comment by K8Sewell** [comment]
In progress screenshot


![Image](https://user-images.githubusercontent.com/36549923/225057429-d86dca8a-1351-4edb-8af6-6447ae27a587.png)

**Comment by K8Sewell** [comment]
PR ready to review - https://github.com/yalelibrary/yul-dc-blacklight/pull/883
