### ISSUE TITLE
Add IIIF rendering for largest deliverable JPG

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2417]
**Story**

Very large JPG image downloads from the IIIF are likely to fail. Assuming we set a maximum number of total pixels in Cantaloupe, we will want to want to offer an option to download JPGs at this size via the IIIF Canvas' `rendering` property, https://iiif.io/api/presentation/3.0/#rendering

See #2408 for the epic.

**Acceptance**
- [x] Create a MAX_PIXELS constant, set to 100_000_000
- [x] If the image size is > MAX_PIXELS
    - [x] Compute the height and width dimensions for the image that will produce the largest possible image with less than MAX_PIXELS.    The image aspect ratio should not change.
    - [x] Generate a IIIF image URL in the format `.../full/{width},/0/default.jpg`.   I.e., supply the scaled width and let the server compute the height.
- [x] Create an additional item in the `rendering` property for each Canvas, *before* the TIF download option
   - [x] the `id`:
      - [x] use the URL described above if the image needs to be scaled
      - [x] if the image does not need to be scaled, use the `/full/full/0/default.jpg` format    
   - [x] `type` is `Image`
   - [x] `format` is `image/jpeg` 
   - [x] `label` language is `en`
   - [x] `label` value is "Full size (jpg)" if not scaled, otherwise "Reduced size {heigh} x {width} (jpg)"

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-management/pull/1155

**Comment by K8Sewell** [comment]
Deployed to Demo

**Comment by sshetenhelm** [comment]
Works as expected across Mac/Chrome, Mac/Safari, and Windows/Edge. Closing, thank you everyone!
