### ISSUE TITLE
Initial parent object api for Quicksearch integration

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2418]
**Story**

Quicksearch will need to index DCS parent objects in order to include them in search results.  Quicksearch will harvest records via an API in Metadata Cloud, which will in turn call this new API in Management.

This ticket is to establish the controller for this API and provide some data.   Additional tickets will expand the data included in the response.

**Acceptance**
- [x] Create a controller in Management to handle requests to `/api/parent/{oid}`
- [x] The controller should be public
- [x] If the parent object's visibility is *not* `Public` or `Yale Community Only`, immediately return HTTP 403
- [x] If the parent does not exist return HTTP 404
- [x] If the parent does exist return the following JSON structure, using the appropriate values from the parent:

```
{
    "dcs": {
        "oid": "123",
        "visibility": "Public",
        "metadata_source": "ils",    // string of metadata source
        "bib":  ".....",
        "holding":  ".....",
        "item":  ".....",
        "barcode":  ".....",
        "aspace_uri":  ".....",
        "admin_set": "Beinecke",    // label of Admin Set
        "child_object_count": 43,
        "representative_child_oid": 123,
        "rights_statement": "....",
        "extent_of_digitization": "...",
        "digitization_note": "...",
        "call_number": "...",
        "container_grouping": "...",
        "redirect_to": "....",
        "iiif_manifest": "https://collections-*.library.yale.edu/manifests/123"   // URL varies demo/test/etc.
    }
}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1160

**Comment by K8Sewell** [comment]
Looks good on Test.  Was not logged in.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/227563633-2d98221a-69fc-4245-9ec2-dc50c7328ed4.png)

**Comment by mikeapp** [comment]
Can you convert these to integers rather than strings?   

```
        "child_object_count": "1",
        "representative_child_oid": "",
```

**Comment by mikeapp** [comment]
Also see Maggie's comments on the PR.  Are the labels available by lookup from a DB table.

**Comment by jpengst** [comment]
PR for updating strings to integers: https://github.com/yalelibrary/yul-dc-management/pull/1165

**Comment by K8Sewell** [comment]
Updated to integers in Test.  Will promote to UAT



![Image](https://user-images.githubusercontent.com/36549923/229230988-4b3ad175-9d39-4b74-adb4-6313c47525c1.png)
