### ISSUE TITLE
Add metadata to parent object API response

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2419]
**Story**

Quicksearch will use the cached metadata in DCS for indexing.  The parent object API response should include the metadata.

Blocked by #2418 

**Acceptance**
- [x] Include the descriptive metadata in the response under the key `metadata`
    - [x] If source is `ladybird` use JSON stored in the `ladybird_json` field
    - [x] If source is `ils` use JSON stored in `voyager_json` 
    - [x] If source is `aspace` use JSON stored in `aspace_json`

The response will look like:

```
{
    "dcs": {

     },
    "metadata": {     // this is the JSON blob from MC that is stored in our DB
         
    }
}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1162

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.98](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.98)

**Comment by K8Sewell** [comment]
Looks good on Test.  Was not logged in.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/227563633-2d98221a-69fc-4245-9ec2-dc50c7328ed4.png)
