### ISSUE TITLE
Sort by year ascending & descending

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#242]
**ISSUE**
Currently Year search result sort filter doesn't appear to function at all.  
![Screen Shot 2020-06-16 at 10.40.12 AM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/c31c44c9-6066-40e9-980c-c5fc5c21c2c1)

**ACCEPTANCE**
- [x] I can click on "Sort By..." and choose "date (oldest first)" to get results sorted by date in ascending order
- [x] I can click on "Sort By..." and choose "date (newest first)" to get results sorted by date in descending order
- [x] The default "Sort By Year" option is removed

See examples at  https://digital.library.emory.edu/?q=&search_field=common_fields&sort=year_for_lux_ssi+asc%2C+title_ssort+asc
and
https://digital.library.ucla.edu/catalog?q=&search_field=all_fields&sort=sort_year_isi+asc
![Screen Shot 2020-06-16 at 10.41.09 AM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/59dd7e4f-91cf-4d52-aaec-6feda549392a)

**Comment by tilthouse** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/137

![Screen Shot 2020-06-22 at 10.02.43 AM.png](https://images.zenhubusercontent.com/5eac64cbd2eb22688406f33e/c40e706f-b613-4c08-ac14-fbd422d8645d)

![Screen Shot 2020-06-22 at 10.03.11 AM.png](https://images.zenhubusercontent.com/5eac64cbd2eb22688406f33e/fd6f00d7-99e0-4aae-96de-3416f42680c7)

**Comment by mark-dce** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/3064318/85426848-9fb20580-b540-11ea-8e00-ebaa64539957.png">
