### ISSUE TITLE
Add children to API for Quicksearch integration

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2420]
**Story**

Quicksearch will eventually index child label/caption metadata, so it needs this information from DCS.

Blocked by #2418

**Acceptance**
- [x] Add an array of `children` to the `dcs` metadata structure in the API.
- [x] For each child provide:
  - [x] `oid` 
  - [x] `label`
  - [x] `caption`

```
{
    "dcs": {
        ...
        "children": [
           {
               "oid":  12345,
               "label":  "Lorem ipsum dolorem",
               "caption": "etc..."
            },
            ....   // rest of the children
        ]
      },
     "metadata": {
        ...
     }
}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1163

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.59.98](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.59.98)
