### ISSUE TITLE
Hide UV full-size download option via CSS

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2423]
**Story**

We want to hide the default option for "full size" image download in UV, to be replaced by the `rendering` for JPG in the Manifest.

![Image](https://user-images.githubusercontent.com/1987952/224807691-99c67369-251e-4285-b6a6-57683a6f0653.png)

See #2408

**Acceptance**
- [x] Do not display the download

This should work:

```
#wholeImageHighReslabel {
visibility: hidden;
display: none;
}
#wholeImageHighRes {
visibility: hidden;
display: none;
}
```

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-blacklight/pull/882

**Comment by K8Sewell** [comment]
Deployed to Demo

**Comment by K8Sewell** [comment]
Hidden on demo.



![Image](https://user-images.githubusercontent.com/36549923/226377286-9718f6ae-3228-401b-bd82-38ea538ca30b.png)

**Comment by sshetenhelm** [comment]
Looks good across multiple browsers! Will close. Thank you everyone for your excellent work!
