### ISSUE TITLE
Update parent batch job needs to include Preservica fields

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2426]
Story 

The update parent batch job needs to include the following fields:
- digital_object_source
- preservica_uri
- preservica_representation_type

This is needed so that existing parents, e.g migrated content, can be updated to point to Preservica as its content source

Once in production this work can we used to test and pull in content that was added to DCS using the Goobi Temp Ingest process, documented here https://docs.google.com/spreadsheets/d/1iqsayDnZz_ur8dH5iUHGap9kDfQkn2vMJ1dQms0hXBc/edit#gid=0

Acceptance
- [x] Parent(s) in DCS can be updated to point to Preservica as their content source  
- [x] CREATE TICKET FOR -- Update parents that were added to DCS using Goobi Temp ingest process

**Comment by jpengst** [comment]
```oid,source,admin_set,project_identifier,visibility,rights_statement,extent_of_digitization,digitization_note,digitization_funding_source,bib,holding,item,barcode,aspace_uri,viewing_direction,display_layout,redirect_to,digital_object_source,preservica_uri,preservica_representation_type
32204414,aspace,brbl,,,,,,,,,,,,,,,,Preservica,/uri,Preservation```

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.2)

**Comment by K8Sewell** [comment]
Preservica test db is not set up for Test.  Need to promote to UAT for testing.

**Comment by sshetenhelm** [comment]
Confirmed in UAT that this information is able to be added to a parent, but I don't think I have the right credentials set up to actually sync anything. 

Created #2465 for actual Preservica syncing in PROD for Goobi objects.
