### ISSUE TITLE
Clicking "missing" facet for "Date Created" causes error

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2427]
Reproduce by going to this page, open Date Created, and click the "missing" link:
https://collections.library.yale.edu/catalog?f[genre_ssim][]=Manuscripts%2C+Medieval+Germany+11th+century

**Comment by jpengst** [comment]
Cause of error:  


![Image](https://user-images.githubusercontent.com/24666568/231248781-04e1dcfb-c5d8-4cb1-83f0-32276d808f72.png)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/892

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.67](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.67)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.

**Comment by mikeapp** [comment]
Looks good on UAT.

**Comment by sshetenhelm** [comment]
Looks good to me too, ready to close, thank you :)
