### ISSUE TITLE
Make TIFFs download instead of open

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2428]
**Story**

We'd like the TIFF images to download automatically  instead of opening in the browser window, where the user will then have to manually initiate a download.   Additionally, we'd like the "waiting" tab to close automatically once the download is in progress.

**Acceptance**
- [x] Add `Content-Disposition` header to force download behavior
- [x] Add Javascript to close window after initiating download

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-blacklight/pull/885/files

**Comment by K8Sewell** [comment]
Deployed to Demo

**Comment by sshetenhelm** [comment]
Chrome on Mac -  tiffs downloaded successfully but the 'waiting' tabs never closed. 
Microsoft Edge - Same
Safari on Mac - tiff showed up in new tab in similar manner as JPG, had to right click to save, no automatic download

**Comment by sshetenhelm** [comment]
Edge is good, ready to close.
