### ISSUE TITLE
Limit retry attempts in download Javascript

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2431]
**Story**

The original TIFF download Javascript should not retry forever.   Set a limit of 10 retries, then display a message to the user.  Do not close the page if the loop terminates this way, so the user can see the message.

**Acceptance**
- [x] Javascript loop terminates after 10 tries
- [x] Tab stays on screen
- [x] Javascript updates the message with the text "The file could not be downloaded at this time.   Please try again later."

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/886
