### ISSUE TITLE
Create Parent Object Batch Process - ArchivesSpace errors

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2436]
**Story**
Created in response to #2403

When an ArchivesSpace uri is used in the 'Create Parent Objects' batch process, the process does not recognize the ArchivesSpace uri. The following failure message is returned:

_Setup job failed to save: ArchiveSpace uri required to build ArchiveSpace_

The parents are created but do not include any ArchivesSpace uri information. It has to be edited after creation to include the uri.

We want the 'Create Parent Objects' batch process to successfully recognize and include the ArchivesSpace uri when creating parents.

[Example in UAT](https://collections-uat.library.yale.edu/management/batch_processes/1316/parent_objects/900148394)

**Acceptance**

- [x] 'Create Parent Objects' batch process successfully creates a parent with an ArchviesSpace uri 
- [x] No failure messages are returned

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1181

**Comment by sshetenhelm** [comment]
It works! Ready to deploy to UAT :)

**Comment by sshetenhelm** [comment]
Works great! Ready to close.

Thank you so much!
