### ISSUE TITLE
Dependabot updates in Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2438]
Bumps rack version
PR - https://github.com/yalelibrary/yul-dc-management/pull/1156

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.0)

**Comment by K8Sewell** [comment]
No issues on Test.  Will promote to UAT.
