### ISSUE TITLE
Dependabot updates in Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2439]
Bumps rack version
PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/884

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.64](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.64)

**Comment by K8Sewell** [comment]
No issues on Test.  Will promote to UAT.
