### ISSUE TITLE
Prepare to copy images with Multiple Masters

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#244]
**ACCEPTANCE**
For Images that had multiple copies available
- [ ] Enter the resolved master filenames/paths into the image copy database
- [ ] Do any other setup required to allow the image copy to begin next week

**Comment by DraxIndustries79** [comment]
Acknowledging that this may need to be reevaluated after the meeting.

**Comment by martinlovell** [comment]
Imported most recent CSV of BRBL DL images.
Currently running set_file_path rake task which follows rules to try to determine a path for DL oids which have multiple image files.

Progress is being recorded here [https://github.com/yalelibrary/sprint-hub/issues/100](url)
