### ISSUE TITLE
Expose "date created" information for parents in parent objects table

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2441]
**Story**

There should be a "date created" in the database for each parent. We'd like to expose that date field in the data table for the parents, as this would help with reporting for content newly added to DCS.

**Acceptance**

- [x] Add date/timestamp of creation of Parent Object to the Parent Object datatable.
- [x] Title of field is "Date Created"
- [x] Allow sorting on this field
- [x] Add an index on this field in the database
- [x] Format consistent with batch process:  2023-03-28 18:01:39 UTC

**Comment by jpengst** [comment]
Created_at returns a pretty big string: `Tue, 14 Mar 2023 00:11:04.835007000 UTC +00:00`  
Do we want to make this more human readable?

**Comment by alisonclemens** [comment]
I think that would be helpful, if it's easy to do, particularly for the timestamp

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1169

**Comment by jpengst** [comment]
Deployed v2.60.01

**Comment by K8Sewell** [comment]
Displays on Test.  Will promote to UAT



![Image](https://user-images.githubusercontent.com/36549923/230424626-430b78e8-f54c-4432-a75f-aba6f3657937.png)

**Comment by sshetenhelm** [comment]
This is great!!! Thank you so much :)
