### ISSUE TITLE
Sample Failed PDF Jobs

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2442]
Multiple PDF jobs are failing with multiple error statements. Investigate jobs to see if there is common thread. 

**Acceptance**

- [x] Investigate a sample of failed PDF jobs
- [x] Update PDF failure tickets with more examples and information to facilitate error correction

**Comment by sshetenhelm** [comment]
Updated 3 PDF failure tickets--one was user error, two appear to be errors that occur as a result of how images were ingested. Samples PDF errors were able to be rectified by (a) running recreate child OID ptiff job, (b) choosing a new thumbnail to (c) generate a fresh manifest/PDF.

**Comment by martinlovell** [comment]
I was able to get a spreadsheet of the production jobs.  (I won't post here since it may contain sensitive information.)

**Comment by sshetenhelm** [comment]
@martinlovell could you please email or Teams chat me the spreadsheet? Thank you!
