### ISSUE TITLE
Downloads terminate when tab closes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2443]
**Story**

In Safari the download seems to terminate if the tab closes before the download is complete, at least for larger images.

Steps to reproduce:
1.  Open a large object such as a map in UV
1.  Click on UV download link
1. Blacklight shows tab
1. Javascript initiates download after first delay loop, blue progress indicator below address bar shows loading in progress
1. Tab closes, but no download is initiated.

Theory: Blacklight hasn't yet started sending a response - hence the blue progress loading bar is still showing, but not the download indicator.   

If that's the case, then delaying the window close by 5-10 seconds would help.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/889

**Comment by jpengst** [comment]
Deployed v1.60.65

**Comment by sshetenhelm** [comment]
Safari/mac, with [this example object](https://collections-uat.library.yale.edu/catalog/16336337) and [this object](https://collections-uat.library.yale.edu/catalog/11141252) the tab closed before the object could actually download for me.

**Comment by mikeapp** [comment]
For now, let's extend this to 60 seconds.

**Comment by jpengst** [comment]
Increases tab close time from 10 seconds to 60 seconds: https://github.com/yalelibrary/yul-dc-blacklight/pull/890

**Comment by jpengst** [comment]
Deployed v1.60.66

**Comment by K8Sewell** [comment]
Tab took over a minute to close after the download started.  Will deploy to UAT.
