### ISSUE TITLE
Ping Metadata Cloud when the records are deleted

### ISSUE THREAD

**Issue by MaggieZhaoYale** [yalelibrary/YUL-DC#2444]
Story
Related to ticket #2421 
 If the record is deleted, MD5  is null or deleted in DCSActivityStreamUpdate table
 

- [x] Perform a GET to Metadata Cloud
     MC URL `/streams/activity/dcs/oid/#{oid}/Delete`
         update the md5_metadata_hash for the the OID
 Do not directly associate the DCSActivityStreamUpdate model with the ParentObject model

**Comment by MaggieZhaoYale** [comment]
Ready to review https://github.com/yalelibrary/yul-dc-management/pulls/1166

**Comment by martinlovell** [comment]
v2.59.99
