### ISSUE TITLE
Reset Stalled ActivityStreamLogs using Interface

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2446]
If an activity stream job exits unexpectedly, it will leave a ActivityStreamLog in the database with a "Running" status.

This prevents the a new job from starting until it is fixed, because jobs are prevented from running if there is an existing ActivityStreamLog marked as Running.

**Story:** As an admin, I would like to be able to change the status of a failed ActivityStreamLog so that the activity stream jobs will run each night.

- [x] Add a button to the recurring jobs check status page: `reoccurring_jobs?check_status=true` if there is an ActivityStreamLog in the Running state that is more than 12 hours old.
- [x] If the user clicks the button, set the status of that ActivityStreamLog to "Manually Reset" and save it and redirect to the reoccurring_jobs page.
- [x] Only allow sysadmins to see the button or make the request to reset the jobs.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1192

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.8)

**Comment by K8Sewell** [comment]
Doesn't display when there is not a job running for over 12 hours.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/236547539-3eb7464b-4702-419f-9bdb-13578519bef2.png)
