### ISSUE TITLE
Active user account shows as 'deactivated' and twice in list when added as editor of set

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2451]
**Story**

Kait has an active user account in Management TEST. I added her as an editor of the mus set, but MGMT stated she does not have permissions for that set. When I removed her from the list and re-added her as an editor, I received the following message:

User: [netID] added as editor, but is deactivated

However, when I go into the user settings, I can see that her account is active.

Additionally, her netID appears twice in the set editor list, despite adding her once when she was not on the editor list.

We need user accounts to always show as active when they are, in fact, active, and only show in set lists once.

**Note** This ticket has been rescoped to fix the immediate issue with Kait's account.  Additional tickets have been created to address the underlying issue.

**Acceptance**
- [x] Assign @K8Sewell deactivated account a different NetID (e.g., append `-deactivated`)
- [x] Test to see if this corrects the problem

**Comment by mikeapp** [comment]
Suggestions, which should probably have their own tickets:
- [ ] Enforce unique value for NetID (will require cleanup of duplicates)
- [ ] On inactivation of a user, remove the user from all:
  - [ ] Admin sets
  - [ ] Approval sets

**Comment by K8Sewell** [comment]
Was able to log in with an active user name and perform actions as expected.  Martin also clarified that he removed duplicate users.
