### ISSUE TITLE
Missing web font error

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2456]
**Story**

We see a very large number of errors related to this missing web font:
`https://collections.library.yale.edu/packs/media/webfonts/fa-solid-900-4a2cd718.ttf`

Update: Also seeing failed requests for:
`https://collections.library.yale.edu/packs/media/webfonts/fa-solid-900-bb975c96.woff2`

**Acceptance**
- [ ] Determine whether this font is used and by what (our code, something else?)
- [ ] Determine where the font comes from and its licensing
- [x] Propose next steps - can we host in the repo, add to static.library.yale.edu or remove it?

**Comment by mikeapp** [comment]
It is coming from management, not blacklight (e.g.,  `/management/packs/css/application-1e40b4cf.css`)

**Comment by jpengst** [comment]
PR:  https://github.com/yalelibrary/yul-dc-management/pull/1184

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.6)

**Comment by K8Sewell** [comment]
Not seeing an error come up for test environment in honeybadger.  Will promote to UAT.

**Comment by mikeapp** [comment]
Looks good - all fonts load on UAT.
