### ISSUE TITLE
Honeybadger: report demo/test/uat environments separately

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2457]
**Story**

Honeybadger currently had three projects set up: blacklight, management, and iiif-imageserver.  They are all labelled as production.   I believe we send errors from each environment to the same 'production' environment in Honeybadger.  Ideally we'd create separate projects for each, or at least for development vs. production.   

**Acceptance**
- [x] Determine how Honeybadger determines the environment name/project
- [x] ~~Create new test/uat/demo projects in HB~~
- [x] Adjust application to send data to the correct project for its environment.
   - [x] Update initializers in Rails apps
   - [x] Add environment variables in image server

**Comment by mikeapp** [comment]
https://docs.honeybadger.io/lib/ruby/gem-reference/configuration/

**Comment by mikeapp** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/894

**Comment by mikeapp** [comment]
Still needs a Blacklight release

**Comment by jpengst** [comment]
> Still needs a Blacklight release

I just released Blacklight v1.60.69 to test

**Comment by mikeapp** [comment]
Looks good on UAT
