### ISSUE TITLE
Error vending OAI-PMH XML

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2461]
**Story**

Honeybadger report:  AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

Summary

catalog#show

URL: https://collections.library.yale.edu/catalog/10081177.oai_dc_xml

**Comment by jpengst** [comment]
Deployed test v1.60.70

**Comment by K8Sewell** [comment]
Visiting a redirected parent oid did not trigger a double render error.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/235240760-6cc6a29a-c32b-46b3-a483-81cd89825b15.png)

**Comment by mikeapp** [comment]
Trying:
https://collections-uat.library.yale.edu/catalog/10018921  -> redirects to record (on prod https://collections.library.yale.edu/catalog/10017466 )
https://collections-uat.library.yale.edu/catalog/10018921.oai_dc_xml

**Comment by jpengst** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/897

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.71](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.71)

**Comment by jpengst** [comment]
PR Reverted.  
New PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/899

**Comment by mikeapp** [comment]
See comment.

**Comment by jpengst** [comment]
Deployed to Test v1.60.73

**Comment by K8Sewell** [comment]
Promoting to UAT for testing where parent object exists

**Comment by mikeapp** [comment]
Looks good on UAT.
