### ISSUE TITLE
PTIFF generation resource issues

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2462]
**Story**

PTIFF creation is using up all memory and/or disk space on workers.   See Honeybadger for error messages.

See https://github.com/yalelibrary/yul-dc-management/blob/main/app/models/batch_process.rb#L366

- [x] Use 500MB threshold

**Comment by mikeapp** [comment]
I think we send very large images to the intensive worker.  Perhaps we could lower the size threshold at which this happens?

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-management/pull/1196

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.9)

**Comment by mikeapp** [comment]
Value should be 524,288,000

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1197

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.61.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.61.0)

**Comment by K8Sewell** [comment]
The 60MB image that was tested last time was in the correct queue this time, screen shot below.  Will promote to UAT so it can be tested with a larger than 500MB image.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/58a6bd46-40c4-4da6-afb0-2877363b89c1)

**Comment by mikeapp** [comment]
Looks good on UAT
