### ISSUE TITLE
Do not allow duplicate User IDs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2466]
**Story**

It is possible to create a new user account with the same NetID as an existing account.

**Acceptance**
- [x] Put a unique constraint on the NetID

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1176

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.3)

**Comment by K8Sewell** [comment]
Build failure on Test - could use help to investigate cause


![Image](https://user-images.githubusercontent.com/36549923/233419089-ac06fc44-6f47-457d-9abf-ca139c8d1171.png)

**Comment by martinlovell** [comment]
@mikeapp , I manually ran this in Test and UAT:
`User.where.not(id:User.select("MAX(id) as id").group(:uid).map(&:id)).each { |u| u.uid = "#{u.uid}__"; u.save }`

There were a couple with blank uids (goobi, system)

I have a PR to add the code to the migration: https://github.com/yalelibrary/yul-dc-management/pull/1179
Or, I can manually run in production if everything looks ok on test/uat.  (I don't think I have access to demo.)

**Comment by mikeapp** [comment]
Worked on UAT, dupes have appended characters

**Comment by martinlovell** [comment]
I manually removed the duplicates from Demo and Production.

I closed https://github.com/yalelibrary/yul-dc-management/pull/1179 just in case the automatic changes did something unexpected.
