### ISSUE TITLE
Remove deactivated IDs from roles

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2467]
**Story**

When a user ID is deactivated the user can stay in roles (viewer, editor, etc.).  They should be removed from all roles upon deactivation.

**Acceptance**
- [x] On inactivation of a user, remove the user from all:
  - [x] Admin sets
  - [x] Approval sets

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.8)

**Comment by K8Sewell** [comment]
Did not clear user from admin set when deactivated.  Will take back to in progress.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1195

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.9)

**Comment by K8Sewell** [comment]
Works on Test.  User's roles were cleared when deactivated.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/7121b272-9106-42f2-bf1c-81b78acac97e)

**Comment by sshetenhelm** [comment]
Works on UAT! Confirmed user was removed from admin sets and permissions sets.
