### ISSUE TITLE
Add CLUSTER_NAME env var

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2468]
# Summary
Add an environment variable that exposes the cluster name.

# Acceptance Criteria
- [ ] variables added to aws parameter store for each environment. Ex: `yul-dc-test`
- [ ] add new var to camerata

**Comment by mikeapp** [comment]
For CI should we do  `yul-dc-ci`?  And we probably should have a value that's common to all local development environments, perhaps we can set that in the local templates?

**Comment by mikeapp** [comment]
Looks like this exists in some files, mostly in ECS:
```
./blacklight-compose.local.yml

./iiif-images-compose.ecs.yml
./blacklight-compose.ecs.yml
./db-compose.ecs.yml
./management-compose.ecs.yml
./worker-compose.ecs.yml
./solr-compose.ecs.yml
./intensive-compose.ecs.yml
```

Should we hard-code a value for local development in the `.local.yml` files?   I don't want to produce metrics from local systems and sending data from random cluster names could drive up costs.

**Comment by mikeapp** [comment]
Decision: set CLUSTER_NAME as `local` in all local templates.

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-camerata/pull/363
