### ISSUE TITLE
Streamline thumbnail image IIIF access 

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#247]
Related to #216
* Any reason not to use the !200,200 (i.e., fit the image in this box) syntax instead of checking width/height?
https://collections-demo.curationexperts.com/iiif/2/1234822/full/!200,200/0/default.jpg

Also:
* The `get_child_img_url(oid)` method  has the URI of the collections-test server hard coded.  Is that an issue?

Acceptance:
- [ ] IIIF image API URL  uses `!` syntax

**Comment by mikeapp** [comment]
Canvas ratio is OK since the image aspect ration should be the same unless it is annotated onto only part of the Canvas (which is very edge case).

**Comment by FCRodriguez7** [comment]
I have confirmed the use of !200,200 syntax to check width/height in the codebase under the blacklight_helper.rb file.   

![Screen Shot 2020-06-24 at 9.37.04 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0d84e3eb-bc56-4742-9905-83e283867817)
