### ISSUE TITLE
Fix not updating image during preservica resync

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2471]
# Summary
During batch process 'Resync with Preservica' the metadata updated but the image was not replaced.  

# Acceptance
- [ ] resync process updates image when changed

**Comment by K8Sewell** [comment]
PR - https://github.com/yalelibrary/yul-dc-management/pull/1175

**Comment by K8Sewell** [comment]
Preservica instance is only connected to UAT so this needs to be promoted to UAT for testing.  Will wait until ticket on same release is tested and approved before promoting.

**Comment by sshetenhelm** [comment]
@motropuk is there an object in UAT we could use to test this?

**Comment by motropuk** [comment]
I ran a test sync on #2400 a a few days ago on this using this parent https://collections-uat.library.yale.edu/management/parent_objects/900148026. The sync completed but didnt pick up the changed child image file. However, I just ran the sync again now and now I am getting a checksum error https://collections-uat.library.yale.edu/management/batch_processes/1381. So need to pair with Kait on Monday to fix this

**Comment by K8Sewell** [comment]
PR for changing resync checksum logic - https://github.com/yalelibrary/yul-dc-management/pull/1189

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.7) - Will promote to UAT for testing as soon as other 2 tickets part of this release pass in Test env.

**Comment by K8Sewell** [comment]
Batch job [#1384](https://collections-uat.library.yale.edu/management/batch_processes/1384) completed successfully but the image in UV was not updated.  Needs rework.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1193

**Comment by K8Sewell** [comment]
Failed a smoke test so did not successfully deploy to UAT.  Will investigate first thing Monday.



![Image](https://user-images.githubusercontent.com/36549923/236568584-49ca3eab-c2b3-4fec-9cdc-531f11eba77d.png)

**Comment by K8Sewell** [comment]
Still is not updating the last image as expected.  Taking back to in progress.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/d5750fdf-ee50-4081-81b2-d31e17a17cd0)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1198

**Comment by jpengst** [comment]
Deployed to Test v2.61.1

**Comment by K8Sewell** [comment]
Image that should have changed did not update.  Taking back to in progress to investigate why the generation uri is incorrect and the image didn't update



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/fa6ca67c-fb9f-4498-8a98-28afdc443854)
