### ISSUE TITLE
CircleCI: Deprecated Docker convenience image

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2472]
**Story**

CircleCI is reporting a message about a deprecated Docker convenience image in the `build-and-push` and `publish-latest` steps.  https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

**Acceptance**
- [x] Update to use new image

**Comment by jpengst** [comment]
PR's:  
https://github.com/yalelibrary/yul-dc-blacklight/pull/901  
https://github.com/yalelibrary/yul-dc-management/pull/1199

**Comment by jpengst** [comment]
camerata PR: https://github.com/yalelibrary/yul-dc-camerata/pull/364
