### ISSUE TITLE
Gracefully handle Solr task redeploy

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2476]
**Story**

When a Solr task is terminated the lock file can remain in place.   This prevents a new Solr task from accessing the core.

**Acceptance**
- [ ]  Allow the Solr task to (safely) start up.

**Comment by bobrice** [comment]
This is likely to be handled by moving Solr from a container to an EC2 instance.  Work is underway in the Quicksearch project that will likely help us to prove whether, or not, this is true.
