### ISSUE TITLE
Export child object Full Text status and include in table

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2478]
**Story**
As a user, I would like to know what child objects have a text file attached. I would like to (a) see this information in the child object table and (b) have this information exported with other information during the export child batch process.

This Full text information is already available on the child object page in the Management App. I would like the same statuses to export. The statuses are: 

- Yes
- No

**Acceptance**

- [x] Full text information is included in the Export Child Oids batch process export
- [x] Full text information is included in the child object table between 'Original OID' and 'Preservica Content Object URI'

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1186

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.60.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.60.7)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.

exported csv


![Image](https://user-images.githubusercontent.com/36549923/236045112-7a4914ef-5244-4497-b9f1-7539c531a0b3.png)


datatable



![Image](https://user-images.githubusercontent.com/36549923/236045199-c13b64bd-2a74-4548-ba66-1a67de545f7a.png)

**Comment by sshetenhelm** [comment]
Ahhhh! Yeeessss!!!!! This is perfect and is going to make migrations with OCR so much easier!  YAAAAAYYYYY!!! Thank you!

Ready to close :) :) :)
