### ISSUE TITLE
SPIKE: Identify sample Voyager records that should have children (holding, item, barcode IDs)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#248]
**ACCEPTANCE**
Spend up to a day 
- [x] Identify which existing sample objects should have child IDs (item, holding, barcode)
OR
- [x] Identify 5-7 new sample objects with child IDs

- [x] Ensure we can read the corresponding records from the Metadata Cloud

**Comment by maxkadel** [comment]
Looks like the management application is not constructing the urls for items with a barcode correctly (not sure whether the metadatacloud api changed or it was just done incorrectly), fixing now.

**Comment by maxkadel** [comment]
oid | bib_id | barcode
----|-------|--------
2046567|1169354|39002094045136
2055095|1169354|39002094045110
2041002|1169354|39002094045128
16414889|3577942|39002113596465
11913649|3827095|39002097273412
