### ISSUE TITLE
Cloudwatch metrics for Blacklight

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2480]
**Story**

We'd like to add Cloudwatch metrics for certain events that can't be tracked via Google Analytics.

See #2463 for Management implementation, which is slightly different (it uses Rails events that are emitted by ActiveJob) but the code that interacts with Cloudwatch should be similar.

**Acceptance**
 - [x] Metric namespace is `DCS`, same as in Management
 - [x] Metric Name:  `Download`
 - [x] Use a new metric dimension `FileType` that will indicate the type of download
 - [x] Dimension for `ClusterName`

Send a data point when...
- [x] a TIFF is downloaded
   - [x]  FileType value is `TIFF`
- [x] a PDF is downloaded
   - [x] FileType value is `PDF`

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/925

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.83](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.83)

**Comment by mikeapp** [comment]
Feature flag turned on in test, UAT, and production.
