### ISSUE TITLE
Update S3 Buckets and Documentation

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2481]
# Summary
There are a number of S3 buckets.  The documentation for these was last updated in 2020.  A refresh of what is in use is needed in the documentation and anything not in use should be purged from S3.

# Acceptance
- [ ] review all `yul-dc` prepended buckets for use and update documentation - https://github.com/yalelibrary/yul-dc-documentation/wiki/S3-Bucket-Structure
- [x] delete unused buckets from S3

**Comment by mikeapp** [comment]
*-samples are OK, they hold manifests
*-download-* are OK, even if empty, they hold files staged for download; lifecycle rules will empty these buckets

The odd clusters (delete- zzz-) are DevOps, and staging needs to be cleaned up eventually.

**Comment by jpengst** [comment]
Wiki updated with manifest sample buckets
