### ISSUE TITLE
Apple touch icon

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2483]
**Story**

Honeybadger reported an error from an attempt to access the image `https://collections.library.yale.edu/apple-touch-icon-120x120-precomposed.png`.   This icon is apparently used by Safari.  It looks like there are thousands of requests per month for this, having an icon would reduce the amount of garbage in the logs.

**Acceptance**
- [x] Determine which icon sizes (120x120, etc.) are requested by Safari
- [x] Create icon(s) and add to app

**Comment by mikeapp** [comment]
Look at HB, there's also a 512x512

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/900

**Comment by mikeapp** [comment]
See PR for requested changes.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/902

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.75](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.75)
