### ISSUE TITLE
SPIKE: Sending mail fails on Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2484]
**Story**

Sending mail fails on Management: `Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 127: "/usr/sbin/sendmail...`
Command not found?

**Acceptance**
- [ ] Determine issue
- [ ] Mail is sent successfully

**Comment by bobrice** [comment]
@jpengst  for our machines to send e-mail we install postfix with yum and then configure main.cf with our local mail server address....

myhostname =<enter hostname here>
mydomain = library.yale.edu
relayhost = mail.yale.edu:587

Let me know if this is helpful.  Bob

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1216

**Comment by jpengst** [comment]
Deployed to Test v2.62.0

**Comment by martinlovell** [comment]
I manually went onto test and triggered the report with an email send. (Non scheduled reports through the UI do not send an email.)

Summer should have receive an email titled: "Digital Collections Daily Report" at about 9:35AM today.

**Comment by sshetenhelm** [comment]
It happened! I got an email with the subject 'Digital Collections Daily Report!' It had a csv with the broken child OIDs attached for TEST! It told me to have a great day! 

Hooray!

**Comment by sshetenhelm** [comment]
Received email with csv with UAT broken child OIDs! Great job!
