### ISSUE TITLE
Investigate issue with extent of digitization info not appearing in IIIF more information pane

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2488]
**Story**

As a user, I would like to reliably see extent of digitization information, when known, in the IIIF more information pane. The extent of digitization information is not currently appearing in the IIIF more information pane in many DCS records (e.g., https://collections.library.yale.edu/catalog/2111729, which you can see in the Description field cluster is completely digitized, but you can't see that in the more information pane). For items from smaller repositories, we appear to be able to resolve the issue by regenerating, but regenerating all of BRBL will cause load issues.

Note too that as a user, I see that extent of digitization has a value in the object's metadata on the show page but it is not listed in the more information panel, on the generated PDF cover page, or in that object's IIIF manifest. 

**Acceptance**
- [x] We understand why the extent of digitization information is not appearing in the viewer, on the PDF cover page, or in the relevant object's manifest
- [x] We create tickets to address the work.
- [x] We determined a path forward for regenerating IIIF manifests for BRBL, given load concerns about doing that for the repo as a whole

**Comment by jpengst** [comment]
Does the 2111729 object in production have extentOfDigitization_ssim listed in the Solr Record? I cant seem to find the object in the parent object datatable. I regenerated the object on test and it displays correctly in the UV (as mentioned in the ticket description).  
  
We added the extent_of_digitization to the Solr Record in October 2021. I'm wondering if the extent_of_digitization is missing from objects that were created before October 2021?

**Comment by sshetenhelm** [comment]
New objects are also missing the extent_of_digitization in the IIIF more information pane -- this object in PROD was created yesterday: [https://collections.library.yale.edu/catalog/32580612](https://collections.library.yale.edu/catalog/32580612)

**Comment by jpengst** [comment]
I ingested the 2111729 object on test with an oid,brbl csv and it was built under ladybird and recorded the extent of digitization correctly in the UV. I noticed the 2111729 object on production has an aspace source and not ladybird. Currently investigating why a ladybird object displays extent of digitization correctly and aspace doesnt

**Comment by jpengst** [comment]
Looks like it might be an issue specifically with aspace records and extent of digitization. There is no extent of digitization information in the manifests, but its in the solr record.

**Comment by mikeapp** [comment]
A possible issue is that in `iiif_presentation_v3.rb` the `metadata` method expects most values (except URLs) to be encapsulated in an array.  But the `extentOfDigitization_ssim` is a bare string value.   So the logic for non-Array fields needs to change so that if the string is not a URL (per the existing logic), the field is still included.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1200

**Comment by jpengst** [comment]
Ticket for adding extent_of_digitization to aspace csv's: https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=28961600

**Comment by mikeapp** [comment]
Looks good on test with parent  800052313

**Comment by DraxIndustries79** [comment]
Waiting for bug ticket to be resolved.

**Comment by sshetenhelm** [comment]
Created #2588 to address manifests
