### ISSUE TITLE
Text status in Parent Object table not sorting

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2489]
For text status in the Parent Object table, the sort feature with the table is not working as expected.

In Image 1, the table *should* have been sorted alphabetically in descending order:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/6f83627a-7688-4aa8-b658-6644d90f8409)

In Image 2, when you type any of the terms in the search box, you get zero results, even if there *should* be results returned: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/ab8ed239-3920-4d22-bcb2-87093a3596a1)

Would using a drop-down with our specific terms help solve any of the above?

**Comment by jpengst** [comment]
This bug is also present on the Child Objects datatable.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1202

**Comment by DraxIndustries79** [comment]
Need Mike's input on PR

**Comment by K8Sewell** [comment]
Reworked PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1202

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.61.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.61.4)

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.61.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.61.5)

**Comment by K8Sewell** [comment]
Sorting as expected on Test



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/b25411de-63fc-4530-8963-ab48680c673d)

**Comment by mikeapp** [comment]
* It looks like the column is blank in UAT, I think we'd need to run an "update full text status" job for existing items in order to set the database field?  
* Metadata updates may set the full text field to blank, breaking existing items. so we should not deploy this w/o a fix.

**Comment by mikeapp** [comment]
Also see #2521.  I can't run a full text update job on a parent to see weather that correctly updates a record.

**Comment by mikeapp** [comment]
Also, I see that the Child already has a `full_text` field defined, so do we want to rename that field so that we retain the current status?

**Comment by K8Sewell** [comment]
Will change so that default is None for the parent object and resubmit PR.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1215

**Comment by mikeapp** [comment]
We should try to get this to UAT today.

**Comment by jpengst** [comment]
Deployed to UAT v2.61.9

**Comment by sshetenhelm** [comment]
This also looks good to me on UAT! Parent and child tables sorting as expected :) 

THANK YOU SO MUCH for all the work you've put into this!
