### ISSUE TITLE
Update bookmark feature branch from Blacklight main

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2490]
**Story**
Before returning to bookmars / #2311 we should make sure the code is up to date.

**Acceptance**
- [x] Update Blacklight "bookmark" feature branch from main branch
- [x] Deploy to demo
- [ ] Discuss #2311 next steps

**Comment by jpengst** [comment]
Feature Branch: 2301_EnableBookmark

**Comment by jpengst** [comment]
2301_EnableBookmark deployed to demo

**Comment by K8Sewell** [comment]
On Demo - https://collections-demo.library.yale.edu

### Bookmarks page - 0 bookmarks

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/fc0d3308-0939-4518-9e87-61e240410366)


### Bookmarks page - 5 bookmarks
*to capture*




### Bookmark Link needed in Header

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/6b3e9d7d-e79d-4061-94d3-dcb18e24c780)


### Bookmark checkbox needed in Search Results

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/0531a263-96c7-45b8-8493-3b7af5996fe1)


### Bookmark tool needed on Show page

*to capture*

**Comment by K8Sewell** [comment]
Did not deploy to demo successfully



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/f3f0ade5-6209-4648-bb4a-2bd60023dd6a)

**Comment by sshetenhelm** [comment]
Looks good on demo to me. We also need to consider the spacing of the bookmark checkbox on the search results **Gallery view**.
