### ISSUE TITLE
Log Extent Of Digitization from Aspace CSV

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2495]
## Summary  
With the new ability to add Aspace records from a CSV, we need to record the extent_of_digitization. Extent of Digitization is not listed in an aspace authoritative json, so we need to require a csv with the extent of digitization when ingesting an aspace record.  
  
## Acceptance Criteria  
- [x] Add extent_of_digitization to csv template  
- [x] Assign extent_of_digitization to parent object when ingested via 'Create Parent Objects' batch process. 
- [x] Logs error if extent_of_digitization is missing from the csv. (Only with Aspace records)
- [x] Ensure Extent of Digitization is viewable in the objects UV.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1203

**Comment by jpengst** [comment]
Deployed to Test v2.61.3

**Comment by jpengst** [comment]
Extent of Digitization listed correctly in the UV:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/901a24c1-4967-40e3-8962-033e5c1d297e)

**Comment by jpengst** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
This is good up to checking for visibility in the UV. I was able to create parents (and received a proper warning when using wrong language for extent of digitization!) but cannot create JSON after reassociating two child OIDs to a parent. Looking to see if issue with UAT Metadata Cloud / TEST Aspace or if it is a "me" issue.
