### ISSUE TITLE
Full text search returning too much data

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2496]
**Story**

Full-text search is returning too much data, perhaps and not restricting the scope to the individual parent object.

For instance, searching for "thought" on parent https://collections.library.yale.edu/catalog/12481183 returns about 130 (JSON) pages of results.   Looking among the results, I found an example where the target ("on") is a manifest in a different parent (12481442).   The IIIF search service is being called for the correct parent by UV, for example https://collections.library.yale.edu/catalog/12481183/iiif_search?page=2&q=thoughts so the search should be limited to only that parent.   

```
{
            "@id": "https://collections.library.yale.edu/catalog/12481183/canvas/15104918/annotation/0",
            "@type": "oa:Annotation",
            "motivation": "sc:painting",
            "resource": {
                "@type": "cnt:ContentAsText",
                "chars": ".\" The delicacy was \r\ndiscovered accidentally. Then, for a \r\ntime, it was thought that the only way \r\nto"
            },
            "on": "https://collections.library.yale.edu/manifests/oid/12481442/canvas/15104918#xywh=0,0,0,0"
        }
```

**Acceptance**
- [x] Full text search returns the results for only the parent specified in the search request.

**Comment by K8Sewell** [comment]
Working on Demo


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/56d94604-d998-4472-9f16-fdd15bbb0dad)

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.76](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.76)

**Comment by K8Sewell** [comment]
There's only one record with full text on Test.  Deploying to UAT for further testing.  For context on Demo there are 4 records with full text and the search (as pictured above) that initially returned 8 results now returns the appropriate 2 results.

**Comment by K8Sewell** [comment]
On UAT

### Before
![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/260e92c7-3f4a-446d-bd82-cb58ca01e0c9)


### After
![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/68fbdd1d-1d18-4d56-9cf9-ede330910834)

**Comment by sshetenhelm** [comment]
Looks good to me as well!

1. Searched for 'east' in full text returned 455 parent objects. Search for 'east' in only parent 11870015 returned 4 hits, which is easily verified when looking at object.
2. No matches found for word 'cheese' in object, although 'cheese' is present in full text of 20 documents.


Thank yooouuu!
