### ISSUE TITLE
Remove parent_title and call_number from Reassociate Child Olds batch process

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2497]
**Story**
The Reassociate Child Oids batch process includes columns for parent_title and call_number. However, that information should not be edited manually, as it is getting pulled in from metadata records. As such, we would like to remove these two columns from the batch process template.

**Acceptance**

- [x] Remove parent_title (column d) and call_number (column e) from reassociate child oid batch process csv template
- [x] Ensure batch process still works after above columns have been removed

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1204

**Comment by jpengst** [comment]
Deployed to Test v2.61.3

**Comment by jpengst** [comment]
Looks good on Test

**Comment by jpengst** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
It works as expected, hurray! Thank you and ready to close.
