### ISSUE TITLE
Ingest MS 2004 objects after Ladybird errors resolved

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2502]
**Story**
There are 18 MS 2004 (PID 39) objects that had errors in Ladybird during migration that prevented them from being successfully migrated into DCS. Once LIT has resolved the issues with Ladybird, we should ingest these remaining 18 objects into DCS.

OIDS - 
[MS2004_ADD.csv](https://github.com/yalelibrary/YUL-DC/files/13979437/MS2004_ADD.csv)

**Acceptance**

- [x] Ensure 18 objects have been fixed
- [x] Migrate objects into DCS PROD 
- [x] Audit objects for image files
- [x] Audit objects for text files
- [x] Audit objects for aspace uris
- [x] Review objects with stakeholder
- [x] Update handles

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale !!! I appreciate you!

All 18 objects appear in Blacklight, and have Full Text = Yes in Management App. Just waiting for Full Text info to translate to Blacklight, which will likely take a while due to the job queue/processing time.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Attached is the list of old/new handles

[last_handle.csv](https://github.com/yalelibrary/YUL-DC/files/14084855/last_handle.csv)

**Comment by sshetenhelm** [comment]
Ready to close! @MaggieZhaoYale thoughts about points? I probably only spent about an hour combined on all my labor.
