### ISSUE TITLE
BUG: Error viewing recurring jobs status page when one is Running

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2504]
Use created_at instead of run_time for checking age of ActivityStreamLog.

https://github.com/yalelibrary/yul-dc-management/blob/main/app/controllers/reoccurring_jobs_controller.rb#L11

run_time is nil when the job is still running:

Honeybadger error:
Error: 
`NoMethodError: undefined method `<=' for nil:NilClass`
URL:
https://collections.library.yale.edu/management/reoccurring_jobs?check_status=true

app/controllers/reoccurring_jobs_controller.rb:11:in `index`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1226

**Comment by jpengst** [comment]
Deployed to Test v2.62.3

**Comment by jpengst** [comment]
Deployed to UAT v2.62.3

**Comment by martinlovell** [comment]
UAT has an Activity Stream entry with status "Running" which is more than 12 hours old. (The run_time is nil as we would expect in this situation.)

It should be possible to manually reset the entry using the UI.
