### ISSUE TITLE
Add fields to Digital Object json sent to Metadata Cloud

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2506]
**Story**

In order to create links from Voyager to DCS, additional information about the DCS item's metadata source is needed.

**Acceptance**
Add these new fields to the JSON generated in DigitalObjectManagment::generate_digital_object_json:

- [x] source (aspace, ils, ~~or ladybird [or sierra ?]~~)
- [x] bibId
- [x] holdingId
- [x] itemId
- [x] barcode

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1209

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.61.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.61.6)

**Comment by sshetenhelm** [comment]
Confirmed I see these in the digital object json. Ready to close :)
