### ISSUE TITLE
06/06 deployment -- SPECIAL TUESDAY EDITION

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2508]
Once we have confirmed that the ArchivesSpace upgrade is complete, we will need to redeploy the current version of the Management App to reconnect DCS with Metadata Cloud. 

We would like to do this deploy on Tuesday, instead of our usual Wednesday, to minimize service disruption time.

If the upgrade has not finished, we will only restart image servers this week.

**Acceptance**

- [x] Confirm with Alicia and/or Trip that the ArchivesSpace upgrade is complete and was successful
- [x] IF YES: Ensure the Metadata Cloud connection name that was changed has been changed back 
- [x] IF YES: Re-deploy the current version of Management (v2.61.1) to reconnect Metadata Cloud
- [x] Restart image servers for the week

**Comment by ucancallmealicia** [comment]
Confirming that upgrade is complete and was successful.

**Comment by martinlovell** [comment]
The Metadata Cloud connection name has been updated in the configuration.
