### ISSUE TITLE
Fix auto-tagging of docker images

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#251]
As part of our CI process, we auto-tag a docker hub image when we tag a release of Discovery or Management. These *should* look like `v1.2.3` in order to match our expectations elsewhere. Currently, they are instead being tagged as `releasev1.2.3`

- [ ] Auto-tag docker hub images created by our CI process without including the word `release` as a prefix

**Comment by bess** [comment]
Notes from conversation with Rob:
The auto-tagging of an image on docker hub is happening via a CircleCI environment variable.

Look for `parameters.to_tag`

On lines 82 & 85 of the circleci config we need to munge the release name to remove the word "release"

**Comment by mark-dce** [comment]
I think the `release1.6.0` tags you're seeing are actually artifacts of my pre-release branch names.  Max and I just released management and everything looks as expected:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/3064318/85180477-3339bc80-b249-11ea-8af9-019bb4f58e61.png">

**Comment by mark-dce** [comment]
Based on the screenshots above, it looks like CI + Dockerhub have the expected release tags
