### ISSUE TITLE
Check job queue prioritization for Preservica related tasks

### ISSUE THREAD

**Issue by motropuk** [yalelibrary/YUL-DC#2515]
**Story** 

Following in from #2400, we need to check the prioritization of jobs in the job queue to ensure that resyncing jobs from Preservica and PTIFF creation, is prioritized above PDF creation in DCS. 

**Acceptance** 

- [x] Preservica resyncing jobs in DCS are processed before PTIFF creation and PDF creation jobs
- [x] PTIFF creation jobs are prioritized for processing in DCS before PDF creation

**Comment by jpengst** [comment]
Priorities (Lower number means higher priority):  
  
Generate PTIFF Priority: 10  
Sync From Preservica priority: 50  
Generate PDF Priority: 50

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1230  

New Priorities after PR:  
Sync From Preservica priority: 0
Generate PTIFF Priority: 10
Generate PDF Priority: 50

**Comment by jpengst** [comment]
Deployed Test v2.62.4
