### ISSUE TITLE
Decrease TTL of images in Cantaloupe

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2518]
**Story**

Cantaloupe is setting a long TTL on vended images.  We should reduce this so that when we replace PTIFFs in DCS the users see the new files soon.

Also see #2503 

**Acceptance**
- [x] Set max age to 15 minutes in the cantaloupe config

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/35

**Comment by mikeapp** [comment]
Note that this decreases the source cache TTL as well, but that's going to be necessary to meet the use case.

**Comment by mikeapp** [comment]
We'll need a new Cantaloupe release tagged?

**Comment by jpengst** [comment]
Deployed to Images Test v1.0.13

**Comment by mikeapp** [comment]
I think both of the options that were changed are actually impacting the server-side cache, but not the TTL in the HTTP response.  On test I still see `Cache-Control: max-age=604800, private, no-transform`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/36

**Comment by jpengst** [comment]
Deployed to Images Test v1.0.14

**Comment by mikeapp** [comment]
Looks good on test, deploying to UAT

**Comment by mikeapp** [comment]
Looks good on UAT:
`Cache-Control: max-age=900, private, no-transform`
