### ISSUE TITLE
Update full text job gives Rails error message

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2521]
**Story**

Attempting to run an update full text job for parent 12479213 in UAT fails with a Rails generic error screen, the job is not queued.

This may be a problem with the template, which I downloaded and used.  Honeybadger reports:
`CSV::MalformedCSVError: Invalid byte sequence in UTF-8 in line 1.`

**Acceptance**
- [x] Test job using the template
- [ ] Fix template or other underlying issue

**Comment by K8Sewell** [comment]
Tested job with template and it completed no problem - however I will note that the text files downloaded for the child object's full text did not contain text as expected.  2 were blank and one was garbled backslashes and tic marks (only one child had text in the txt file downloaded from the show page).

**Comment by sshetenhelm** [comment]
Verifying that this is **not** the same object that is having full text problems in PROD. I also was able to successfully update full text status for a number of objects in UAT yesterday, including this object.

**Comment by DraxIndustries79** [comment]
Closing unless this pops up again.
