### ISSUE TITLE
Add warning pop-up when IIIF manifest button pressed

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2523]
**Story**

When a user clicks the 'Update IIIF Manifests' button on an admin set's page, we would like a pop-up to appear asking the user if they are sure they want to update the manifests. The user should confirm in the pop-up that they would want to update all IIIF manifests, or cancel the request. 

Pop up should appear before any jobs are queued.
Jobs should not queue until "yes" has been selected.

_Pop-up Text:_
Are you sure you want to update the IIIF manifests for this entire set?

_Options:_
- Yes, update manifests
- No, cancel request

**Acceptance**

- [x] Pop-up warning appears when 'Update IIIF Manifests' button is pressed
- [x] Pop-up includes aforementioned text and two options
- [x] 'Yes' option moves forward with updating manifests
- [x] 'No' option cancels the requests; no tasks re: updating manifests are created/queued, etc.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1212

**Comment by K8Sewell** [comment]
Got a pop up on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/57a94e99-c67a-453a-8a52-c95ef6d1fa46)

**Comment by sshetenhelm** [comment]
Confirming that I got the pop-up, 'OK' makes the job go, and 'Cancel' just closes the pop-up.

Looks good, ready to close!

Thank you for saving me from myself lol :)
