### ISSUE TITLE
Update 'ArchiveSpace' to 'ArchivesSpace' throughout Management App

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2525]
**Story**
Throughout the Management App, "ArchiveSpace" is displayed. We would like to change this to “ArchivesSpace” instead, to reflect the name of the system. 

Here are some places this is an issue:

- The individual parent object display page displays a value of “ArchiveSpace” for objects that are associated with ArchivesSpace Uris. 
- The Batch Update Metadata screen shows ArchiveSpace.

Screenshot:
![Image](https://user-images.githubusercontent.com/98423494/248411092-ecf36d2c-7008-408a-8e4e-1db616c2ff95.png)
<img width="252" alt="Screen Shot 2023-06-27 at 1 42 45 PM" src="https://github.com/yalelibrary/YUL-DC/assets/98423494/beb8769c-4b25-4499-9b59-d070b0fd42fc">

**Acceptance**
- [x] Authoritative Metadata Source value changed from ArchiveSpace to ArchivesSpace
- [x] Linking an object to its metadata using an ArchivesSpace uri still works
- [x] Value changed to ArchivesSpace in Batch Metadata Update pop-up from Sets page

**Comment by jpengst** [comment]
Do we want it to say "ArchivesSpace" site-wide or just here on the parent showpage? I believe its currently displayed as "ArchiveSpace" site-wide.

**Comment by sshetenhelm** [comment]
Yes, it should be corrected site-wide! I see it in the Batch Update Metadata pop-up; are there other places you've noticed as well?

**Comment by jpengst** [comment]
You can also select "ArchiveSpace" from the dropdown when selecting a Metadata Source.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1218

**Comment by jpengst** [comment]
Deployed to Test v2.62.3

**Comment by jpengst** [comment]
Woo!


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/27e8f8d0-91fa-41eb-8129-54c67a9543ea)




![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/096a8459-d458-482b-b351-1466a9589acf)

**Comment by sshetenhelm** [comment]
* Looks good in batch metadata update pop-up
* Batch metadata update for ArchivesSpace works as expected -- new date in 'last aspace update' on parent object table
* Looks good in Metadata Source drop-down on parent object edit page
* Changing source to ArchivesSpace from Metadata source dropdown still works

This looks to be working as expected! Yay!

**Comment by mikeapp** [comment]
In release v2.62.3

**Comment by jpengst** [comment]
Deployed to UAT v2.62.3

**Comment by sshetenhelm** [comment]
Looks great on UAT! Ready to close and thank you! :)
