### ISSUE TITLE
Create IP blacklist in AWS WAF

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2528]
**Story**

Create an AWS WAF or NACL rule to block specific IP addresses.

There was a sustained probe of DCS from the IP 209.145.56.2 last night, I got about 20-30 Honeybadger emails.   Do we have experience with blocking IPs via AWS WAF?  Could we get a block rule in place for DCS so that we can quickly add IPs to it if we come under attack?  

**Acceptance**
- [x] WAF rule created
- [x] Explain to Engineering how to add IPs in case of emergency ?

**Comment by ra359** [comment]
Created Web ACL "acl-block-bad-actors" using IP set "ip-set-for-bad-actors" which contains 209.145.56.2/32.
To add IP's in an emergency, have Operations page Devops on-call who can add the offending IP(s) to this IP set.
