### ISSUE TITLE
Add extent_of_full_text to dcs json return

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2530]
_For DCS/Quicksearch integration_

**Story**
DCS stakeholders would like search facets to be synchronized across DCS and Quicksearch. Full Text Status is not currently mapped through Metadata Cloud. We need to map full text to the Metadata Cloud/DCS API. 

**Acceptance**

- [x] Add extent_of_full_text to dcs json return

**Comment by MaggieZhaoYale** [comment]
PR to review: https://github.com/yalelibrary/yul-dc-management/pull/1220

**Comment by jpengst** [comment]
Deployed to Test

**Comment by martinlovell** [comment]
Looks good on UAT:
https://collections-uat.library.yale.edu/management/api/parent/900055812
