### ISSUE TITLE
Update Managed Schema to match schema in yul-dc-solr

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2531]
Acceptance:
- [x] add a method in SolrService to delete copyfields from the schema
- [ ] ~add a migration to delete the copyfields we don't need~
- [x] analyze changes in yul-dc-solr to see if other schema.xml changes were made that need to be applied

The managed-schema for existing cores may be out of date.  

SOLR for DCS uses managed schema, so once the core is created, the schema must be updated using API calls to SOLR.

Although we have this PR (https://github.com/yalelibrary/yul-dc-solr/pull/17), looking at managed schema on test, we get this:

```
...
  <copyField source="*_tsim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_tesim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_ssim" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_si" dest="all_text_timv" maxChars="3000"/>
  <copyField source="*_tsim" dest="suggest"/>
  <copyField source="*_tesim" dest="suggest"/>
  <copyField source="*_ssim" dest="suggest"/>
  <copyField source="*_si" dest="suggest"/>
  <copyField source="*_tsim" dest="spell"/>
  <copyField source="*_tesim" dest="spell"/>
  <copyField source="*_ssim" dest="spell"/>
  <copyField source="*_si" dest="spell"/>
  <copyField source="author_tsim" dest="author_spell"/>
  <copyField source="subject_ssim" dest="subject_spell"/>
  <copyField source="title_tsim" dest="title_spell"/>
...
```
(running curl from the docker image on test: curl 'http://yul-dc-test-solr.yul-dc-test:8983/solr/blacklight-core/admin/file?file=managed-schema')

I assume we'd see something similar on UAT and Production.

So, we need to update the schema to remove the copyField using API calls.
We have updated the schema previously with migrations: https://github.com/yalelibrary/yul-dc-management/blob/main/db/migrate/20210610133513_create_solr_ocr_field_type.rb
(This could also be done manually.)

This is the API documentation: https://solr.apache.org/guide/8_0/schema-api.html#delete-a-copy-field-rule

**Comment by MaggieZhaoYale** [comment]
postponed the meeting to June 30 after DCS standup

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1219

**Comment by sshetenhelm** [comment]
Parent 12479792 from Kissinger, which was causing full text issue, is not in UAT so we would need to migrate it in with the relevant text files to test this there.

**Comment by martinlovell** [comment]
Reproduced in test: https://collections-test.library.yale.edu/management/delayed_job_dashboard/show/3894312

**Comment by martinlovell** [comment]
Follow up: https://github.com/yalelibrary/YUL-DC/issues/2541

**Comment by jpengst** [comment]
Deployed Test v2.62.4
