### ISSUE TITLE
Show last Sierra update on Parent Object page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2532]
Related to Sierra work in #2514

**Story**
Sierra is being added as a source. We would like to show the timestamp of the last Sierra update on a parent object’s page. This information can go under ‘Last Voyager Update’ in the parent table. This information should update with a new timestamp every time the object is synced with Sierra.

![Image](https://user-images.githubusercontent.com/98423494/249535599-6ab9663d-6bd9-4e2b-863d-bd6a59b43901.png)

**Acceptance**

- [x] _Last Sierra Update:_ field added on parent object’s page in between _Last Voyager Update:_ and _Last Preservica Update:_
- [x] Field displays an updated timestamp when an object is synced with Sierra

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1228

**Comment by sshetenhelm** [comment]
Looks good to me! Field appears and timestamp updated when I resynced metadata.
