### ISSUE TITLE
Optimize parent objects data table query.

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2536]
The `includes` and `references` are no longer needed in the query for the ParentObjects table.

- [x] Remove `.includes(:child_objects)` and `.references(:child_objects)` from `ParentObjectDatatable.get_raw_records`
- [x] Make sure the query still works as expected

The ParentObjects data table is slow and has a timeout in my dev environment when I have more than ~30 parent objects.
If I remove the `.references(:child_objects)` from `ParentObjectDatatable.get_raw_records` it works.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1221

**Comment by jpengst** [comment]
Nice catch. This was added when we added the Full Text columns to the datatable because we needed to reference the Child Objects full text. Since that is no longer needed, we can pull this

**Comment by jpengst** [comment]
Deployed to Test

**Comment by sshetenhelm** [comment]
Confirming that the data table is waaaaaay faster now than it currently is in UAT and PROD.

**Comment by sshetenhelm** [comment]
UAT data table is now running faster and not giving timeout errors. Hooray!
