### ISSUE TITLE
Blacklight header changes

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2537]
The following changes should be made to the Blacklight header. Both affect the ‘Libraries & Collections’ drop down: 

- Remove Mathematics Library from list of libraries
- Change YCBA link to https://britishart.yale.edu/while-we-are-closed

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/a9ffc404-e779-40e2-9a0e-0108dd9709a4)

**Acceptance**

- [x] ‘Mathematics Library’ removed from Libraries & Collections dropdown
- [x] ‘Yale Center For British Art’ in Libraries & Collections dropdown now links to https://britishart.yale.edu/while-we-are-closed

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/908

**Comment by jpengst** [comment]
Deployed to Test v1.60.78

**Comment by sshetenhelm** [comment]
Looks good on Test

**Comment by jpengst** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Lookin' good on UAT, thank you!
