### ISSUE TITLE
BUG - Some images missing 

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#254]
The default jpg url produces a 404 for some images.  A misalignment in manifest data is suspected but further investigation is needed.  

<details>
For example:

Full Search Query - shows that some images are broken
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/65306397-9351-4950-b914-46d57895b0ae)

Investigation produces that for some images like the one for Fort Vancouver the default jpg below returned a 404
http://localhost:8182/iiif/2/1042003/full/250,/0/default.jpg

A record that did have it's thumbnail was tested and it's default jpg below did return an image
http://localhost:8182/iiif/2/16424347/full/250,/0/default.jpg

</details>

**Comment by mark-dce** [comment]
I think this is the same issue as #180 - i.e. there are some manifests that point to images that are currently missing fro S3 for "known" reasons.

Does it seem reasonable to close this ticket and replace it with #262?

**Comment by mark-dce** [comment]
Superseded by #262
