### ISSUE TITLE
Update SOLR schema in all environments

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2541]
- [x] Backup/Update Solr index during quiet time
  - [x] Backup SOLR index (Need devops to perform a SOLR backup or similar)
  - [x] ssh into a worker and run changes using `rails c`

Manually run the following using `rails c` from a worker container in:

- [x] Test
- [x] Demo (if we can deploy this there)
- [x] UAT
- [x] Production

Remove suggests:
```ruby
SolrService.delete_copy_field("*_tsim", "suggest")
SolrService.delete_copy_field("*_tesim", "suggest")
SolrService.delete_copy_field("*_ssim", "suggest")
SolrService.delete_copy_field("*_si", "suggest")
```

Also deleting spell related copy fields:
``` ruby
SolrService.delete_copy_field("*_tsim", "spell")
SolrService.delete_copy_field("*_tesim", "spell")
SolrService.delete_copy_field("*_ssim", "spell")
SolrService.delete_copy_field("*_si", "spell")
SolrService.delete_copy_field("author_tsim", "author_spell")
SolrService.delete_copy_field("subject_ssim", "subject_spell")
SolrService.delete_copy_field("title_tsim", "title_spell")
```

**Comment by martinlovell** [comment]
Follow up: https://github.com/yalelibrary/YUL-DC/issues/2541

**Comment by martinlovell** [comment]
I was able to backup and restore on Demo.  I verified that a record I updated was reverted.  I don't think that configuration is backed up, just the data.

Demo now uses an alternative directory for the index, which is a little odd:
Index:
    /var/solr/data/blacklight-core/data/restore.20230824191835605

**Comment by martinlovell** [comment]
Backup was successful:
```xml
  <lst name="backup">
    <str name="startTime">Wed Aug 30 18:13:48 UTC 2023</str>
    <int name="fileCount">397</int>
    <str name="status">success</str>
    <str name="snapshotCompletedAt">Wed Aug 30 18:41:29 UTC 2023</str>
    <str name="snapshotName">backup-2023-08-30b</str>
    <str name="directoryName">snapshot.backup-2023-08-30b</str>
  </lst>
```

Fields updates worked and managed-schema looks correct.
Test by ingesting something with a big full-text page.

**Comment by sshetenhelm** [comment]
Test with large full text job.

**Comment by sshetenhelm** [comment]
Confirming that Kissinger MS 2004 parent object 12479792 was able to successfully update and that full text features work as expected. Thank you Martin for all your work on this!

Ready to close.
