### ISSUE TITLE
Allow yarn.lock in Blacklight .dockerignore

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2542]
**Story**

Blacklight's `.dockerignore` file has an entry `yarn.lock`.    We commented this out for Management, we should make the same change for Blacklight.

**Acceptance**
- [x] Remove/comment out `yarn.lock` from the `.dockerignore` file in Blacklight

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/930

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.85](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.85)

**Comment by K8Sewell** [comment]
No obvious issues.  Will promote to UAT.
