### ISSUE TITLE
Add Contributor field to Blacklight parent display page and UV

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2543]
**Story**
Contributor is not a field that is currently displayed in Blacklight. Stakeholders would like to have the field Contributor displayed in Blacklight and the Universal Viewer 'More Information' pane underneath the Creator field.

Contextual info
* Contributor is already mapped to Metadata Cloud for Voyager, Aspace, and Ladybird
* ContributorDisplay is mapped to MC for Voyager and Ladybird
* Contributor is included in the Authoritative JSON as per Management
* contributor_tsim and contributorDisplay_tsim are included in the Solr Record as per Management

**Objects for testing**
Test objects with a Contributor:
https://collections-test.library.yale.edu/catalog/800039925 (ils)

UAT objects with a Contributor:
https://collections-uat.library.yale.edu/catalog/17355881 (ils)
https://collections-uat.library.yale.edu/catalog/15492878 (aspace)
https://collections-uat.library.yale.edu/catalog/15938906 (ladybird)

PROD objects with a Contributor:
https://collections.library.yale.edu/catalog/17355881 (ils)
https://collections.library.yale.edu/catalog/11592292 (aspace)
https://collections.library.yale.edu/catalog/15492878 (aspace)
https://collections.library.yale.edu/catalog/15938906 (ladybird)

**Acceptance**

- [x] Contributor is listed in Blacklight on the parent display page underneath Creator for objects that have data in this field
- [ ] Contributor is listed in the Universal Viewer ‘More Information’ pane underneath Creator for objects that have data in this field
- [x] For aspace objects, the prefix "From the collection:" should be displayed before the record metadata (similar to how creator displays in [11592292](https://collections.library.yale.edu/catalog/11592292)

**Comment by jpengst** [comment]
Do we want the Contributors to be a search link, similar to Creator?


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/7b2ded2a-4678-4430-b34f-1590138a44e1)

**Comment by sshetenhelm** [comment]
@alisonclemens do you have thoughts on this?

**Comment by jpengst** [comment]
I might have been mistaken on the Contributor search link. I think we might need to add Contributor as a search facet in order for the search to work correctly. I don't think we want to add a Contributor facet, right?


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/d534d5e5-246f-4ce0-92bb-c4bd789cd576)

**Comment by sshetenhelm** [comment]
No, I don't think we need a Contributor facet.

**Comment by jpengst** [comment]
PR for Blacklight:  
https://github.com/yalelibrary/yul-dc-blacklight/pull/909  
  
Management PR for UV display coming soon.

**Comment by jpengst** [comment]
Is the "From the Collection:" prefix for aspace records supposed to be in the UV as well?

**Comment by jpengst** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/30ca30c4-050a-4c6f-9deb-ba44a140913c)

**Comment by alisonclemens** [comment]
Yes, the "from the collection" prefix should be included in UV, too -- thank you JP!

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/1239  
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/909

**Comment by mikeapp** [comment]
The one test object on collections-test looks good.

**Comment by mikeapp** [comment]
I think this looks good on UAT:



![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/aaf86e99-c11c-41d6-95e7-30dd68ca0334)
