### ISSUE TITLE
BUG: 'Creator' does not display for Aspace objects in 'More Information' pane

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2547]
**Story**
The field _Creator_ should display in the 'More Information' pane of the Universal Viewer. This information successfully displays for objects associated with the ils and ladybird; however, information does not show for aspace objects.

The field should display in the 'More Information' pane between _Alternative Title_ and _Published/Created_, as it does for [ILS](https://collections.library.yale.edu/catalog/32601327) and [Ladybird](https://collections.library.yale.edu/catalog/17480196) objects.

Notes -- For aspace objects that get creator information inherited from the collection level, the prefix _From the collection:_ appears before the data from the Creator field

Example Objects - Test
https://collections-test.library.yale.edu/catalog/10719304
https://collections-test.library.yale.edu/catalog/30000692
https://collections-test.library.yale.edu/catalog/800052316

Example Objects - UAT
https://collections-uat.library.yale.edu/catalog/12480521
https://collections-uat.library.yale.edu/catalog/2033697
https://collections-uat.library.yale.edu/catalog/16056601

Example Objects - PROD
https://collections.library.yale.edu/catalog/32601393
https://collections.library.yale.edu/catalog/32571946
https://collections.library.yale.edu/catalog/16398190

**Acceptance**

- [x] Creator field displays in UV 'More information' pane for ArchivesSpace objects, between _Alternative Title_ and _Published/Created Date_
- [x] Creator field displays the prefix _From the Collection:_ before the record data for objects that inherit Creator from the collection record

**Comment by martinlovell** [comment]
(Updated PDF also)

https://github.com/yalelibrary/yul-dc-management/pull/1235

**Comment by jpengst** [comment]
Deployed to Test v2.62.5

**Comment by sshetenhelm** [comment]
Displays `<em> `tag in UV field. @alisonclemens do you think this info would still be clear to stakeholders if the phrase were not italicized?



![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/36d3e77a-76a7-4f66-a638-4bed94467a6a)

**Comment by alisonclemens** [comment]
I do, yes!

**Comment by martinlovell** [comment]
@sshetenhelm , which oid where you viewing in that screenshot?

**Comment by sshetenhelm** [comment]
10719304, but I just regenerated the IIIF manifests for all three TEST examples, so you should see `<em>` reflected in all three now

**Comment by martinlovell** [comment]
It looks like `<i>` works in UV and mirador:
https://collections-test.library.yale.edu/catalog/10719304
I updated it manually.

Does this seem good, or should we just strip the italics?

**Comment by martinlovell** [comment]
PR if we want to keep italics and display correctly: https://github.com/yalelibrary/yul-dc-management/pull/1238

**Comment by jpengst** [comment]
Deployed to Test v2.62.6

**Comment by mikeapp** [comment]
Looks good on UAT:



![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/0b62c4b8-63d6-415b-be89-a29c3c304a6c)
