### ISSUE TITLE
Review DCS on mobile devices and create tickets for needed changes

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2549]
**Story**
When viewing DCS on mobile devices, some formatting issues occur. We should look at DCS, identify issues, and create tickets to fix such work.

**Acceptance**

- [x] Review DCS on mobile devices (multiple browsers too)
- [x] Make list of any issues
- [x] Create tickets to address issues

**Comment by tmacmath** [comment]
I'd be happy to assist with this!

**Comment by sshetenhelm** [comment]
Created #2583 , #2584 , #2585 , and #2586 to start addressing issues. Tickets are in backlog. We can pull these into sprint and create more tickets as we have time/space to address these issues.
