### ISSUE TITLE
Add link to Bookmarks page in header

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2550]
**Story**
Users would like to access the list of their Bookmarks on the Bookmarks page from a link on DCS. IF possible, we would like to add the link to the Bookmarks page in the DCS header to the left of netID.

This is similar to how Quicksearch has their Lists link. Screenshot of Quicksearch:
![Image](https://user-images.githubusercontent.com/98423494/254986300-b1022b85-ce0e-4adb-b1b1-09fdfd63bc46.png)

Screenshot of where we'd like the link, if possible:
![Image](https://user-images.githubusercontent.com/98423494/254986533-361c75ee-1bbe-461e-87ac-1d4d42992381.png)

**Acceptance**

- [x] Link to Bookmarks page is added in header to the left of netID
- [x] Link to Bookmarks page is titled Bookmarks
- [ ] If not possible to add to header, another placement decision is made
- [ ] Ticket created for that work

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/910  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/b6f5873d-fdce-4894-8802-6b90e21666d0)

**Comment by sshetenhelm** [comment]
Looks good and works in mac/Chrome and mac/Safari.
