### ISSUE TITLE
Move Bookmarks checkbox on Search Results page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2551]
**Story**
Currently, the Bookmark check box is located:
* above the object title and slightly to the right in search results page list view
* above the object title and below the object thumbnail in gallery view

If possible, we would like to move the Bookmark check box to the right of an object’s metadata in list view. This is similar to how the Bookmark box displays on the [Project Blacklight demo search results page](https://demo.projectblacklight.org/?search_field=all_fields&q=).

Screenshot of demo PB:
![Image](https://user-images.githubusercontent.com/98423494/254988506-37584353-2363-456b-a27c-8568efe4bd78.png)

We would like to have this change made and see how it looks in gallery view before deciding additional actions for gallery view.

**Acceptance**

- [x] Bookmark check box is moved to right of object information in Search Results page
- [ ] Gallery view is reviewed
- [ ] If needed, new ticket made for Gallery view checkbox work (revert to previous box placement or new work)

**Comment by jpengst** [comment]
Feature Branch: 2301_EnableBookmark

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/914  
  
Screenshot:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/aa6b0aeb-0ad7-41ee-a7b5-581c109f90b4)

**Comment by sshetenhelm** [comment]
Bookmark checkbox is to the right of the object, but the spacing is not "clean" like in JP's screenshot. Looked the same for me in mac/Chrome, mac/Safari, and mac/Firefox. Could we try to update the spacing to have the bookmarks aligned like in JP's screenshot?

Screenshot of what I saw: 

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/8e7bdebc-c957-404c-9549-05d44822551f)

**Comment by jpengst** [comment]
Oh, weird!! I'll move this back and take a look

**Comment by jpengst** [comment]
Looks good on Demo:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/83695ec2-8d38-4a07-a69a-3a1ffc64ebf3)

**Comment by sshetenhelm** [comment]
Looks great! Thank you!
