### ISSUE TITLE
[BUG] Cyrillic script in 'Found in' breadcrumbs and Universal Viewer doesn't display correctly on parent object page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2552]
**Story**
Romanization of Cyrillic script in the 'Found in' breadcrumbs is not displaying correctly on the parent object display page for objects. Instead, a box with an X inside appears. In the Universal Viewer, the markers look like the letter U but with a flat bottom (see screenshot).

We would like the Romanization of Cyrillic script to display correctly in the 'Found in' breadcrumbs on the parent object page in Blacklight and in the Universal Viewer title and within UV metadata fields.

[Breadcrumbs display correctly on search results page, although the font for the 'special' characters looks different.](https://collections.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=Sbornik+svi%EF%B8%A0e%EF%B8%A1di%EF%B8%A0e%EF%B8%A1ni%CC%84i%CC%86+po)

Screenshot:
![Image](https://user-images.githubusercontent.com/98423494/254979188-8150e43e-3b8c-4346-8e6b-3c9c93dab8d3.png)

Screenshot of UV 'More Information' panel:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/dd323583-d238-47ec-b3d5-d4953a9f4d45)

Examples TEST:
https://collections-test.library.yale.edu/catalog/800012852
https://collections-test.library.yale.edu/catalog/800013368
https://collections-test.library.yale.edu/catalog/800034792

Examples UAT:
https://collections-uat.library.yale.edu/catalog/900036138
https://collections-uat.library.yale.edu/catalog/900037356
https://collections-uat.library.yale.edu/catalog/900051206

Examples PROD:
https://collections.library.yale.edu/catalog/30700142 
https://collections.library.yale.edu/catalog/30891202
https://collections.library.yale.edu/catalog/30067334
https://collections.library.yale.edu/catalog/30076056

**Acceptance**
- [x] Romanization of Cyrillic script in 'Found in' breadcrumbs on parent object page displays correctly, without "X" boxes
- [x] Romanization of Cyrillic script in UV Title displays correctly
- [x] Romanization of Cyrillic script in 'More Information' panel displays correctly

**Comment by mikeapp** [comment]
Breadcrumb title may need fallback fonts listed in CSS.
We may need to change fonts in UV's CSS - did QS team work on this?

**Comment by jpengst** [comment]
Looking for some feedback on the new font-weight additions in the UV:  

Before (Chrome):  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/876bbd77-16df-495b-9ac0-85a42edb7d44)

  
  
After (Chrome):  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/21528bae-cf7d-42ba-8485-c3aeafefb253)

**Comment by jpengst** [comment]
Looks like we don't need to add the increased font-weight to the UV because it renders the Cyrillic fonts perfectly if we just use Arial:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/21d269d7-406a-4c1d-84af-ea259ac6f163)

  
**Note** The breadcrumbs need the increased font-weight to render correctly on Chrome

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/918

**Comment by jpengst** [comment]
Deployed to Test v1.60.80

**Comment by K8Sewell** [comment]
Looking good on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/fdf944fc-0039-4ef4-af64-70f8c4d5d3e9)

**Comment by sshetenhelm** [comment]
Looks good on mac/Safari and mac/Firefox, but once again mac/Chrome does not like it. Still getting box icons in the Universal Viewer, even after (a) regenerating manifest and (b) using incognito browser.

The breadcrumbs look good though!

Screenshot:

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/88dd97ef-2397-4f10-85e7-3288c2df760d)

**Comment by jpengst** [comment]
Fix attempt 2 PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/923

**Comment by sshetenhelm** [comment]
Looks good to me! Thank you so much :)

Ready to close.
