### ISSUE TITLE
[BUG] Cyrillic script Romanization font weight inconsistent on Search Results page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2553]
**Story**
When objects that utilize Romanization of Cyrillic script are displayed on the search results page, the font for the metadata of the objects has inconsistent font weights. 

[Here's an example results page.](https://collections.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=Sbornik+svi%EF%B8%A0e%EF%B8%A1di%EF%B8%A0e%EF%B8%A1ni%CC%84i%CC%86+po)

And a screenshot with areas noted in red:
![Image](https://user-images.githubusercontent.com/98423494/255174271-62b0d9d8-547b-4143-996d-f1f23290b554.png)

It would be great if we could make the font weight consistent across the entire field/value/word/etc.

This is also a problem in Quicksearch results -- see quicksearch ticket 3021

**Acceptance**

- [x] For search results that include Romanization of Cyrillic script, the font weight is consistent across the entire field/value
- [ ] If problem is solved, share out to Quicksearch team

**Comment by DraxIndustries79** [comment]
Frederick may have some ideas from work on QS.

**Comment by jpengst** [comment]
How the font currently looks:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/f525efe3-52ed-49c5-96cd-ada870651b19)

  
  
With a slightly higher font-weight:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/ac73addc-e607-4b57-bea2-c4094cad9824)

  
  
Increased font-weight applied to both Title and Found In:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/525db939-b0fd-41f0-84a1-95370c7029a6)

**Comment by sshetenhelm** [comment]
I think the above solution looks good, unless @tmacmath thinks there is an accessibility reason we shouldn't do this.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/917

**Comment by jpengst** [comment]
Deployed to Test v1.60.80

**Comment by K8Sewell** [comment]
Looking good on Test.  Promoting to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/180585a2-853f-4581-9e15-dbbe42c44413)

**Comment by sshetenhelm** [comment]
Looks good! Thank you, ready to close.
