### ISSUE TITLE
Changes to Clear Bookmarks button on Bookmark page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2554]
**Story**

- We would like to rename the Clear Bookmarks button on the Bookmarks page to make it more obvious to users that they are clearing all bookmarks off their list. 
- We would also like to change the color of the button from red to [whatever @tmacmath thinks is best]. 
- Finally, we would like to update the language in the pop-up that appears when a user clicks the button to give users a more detailed warning.

**Acceptance**
- [x] Text of button ‘Clear Bookmarks’ button changed to ‘Clear All Bookmarks’
- [x] Color of button changed to [ @tmacmath 's choice]
- [ ] Language in pop-up updated to say “Are you sure you want to clear all bookmarks? You cannot **undo** this action.”

**Comment by tmacmath** [comment]
New button: 
- Font, font size and font-weight are the same as the previous button, only the font color is #ffffff.
- Button background color is #767676
<img width="1535" alt="clear-bookmarks-button" src="https://github.com/yalelibrary/YUL-DC/assets/9658383/5d5102d4-d3fe-4b34-b12c-704f031fb568">

**Comment by jpengst** [comment]
Feature Branch: 2301_EnableBookmark

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/911

**Comment by sshetenhelm** [comment]
Functional across mac/Chrome, mac/Safari, and mac/Firefox, but I put a typo in the original description. Could the pop-up please be changed to replace **undue** with **undo**?
