### ISSUE TITLE
Update font on Bookmarks page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2555]
**Story**
~~We would like the font used for the Bookmarks heading on the Bookmarks page to match the style of the rest of DCS.~~
We need to update the Heading tags.

Bookmarks heading currently:
![Image](https://user-images.githubusercontent.com/98423494/255285604-c014fe6a-4bec-44d6-a836-f49e0743e860.png)

**Acceptance**

- [ ] ~~Make "Digital Collections" an h1~~ 
- [ ] Make "Bookmarks" an h2. I can then look at it on demo

**Comment by tmacmath** [comment]
I need to look at this a bit more, because right now "Digital Collections" has an aria role of "1", meaning that it's an h1 structural element. However, a WAVE audit states that there is a missing h1 element. We can probably make "Bookmarks" an h2 element, but there is still the issue of the "Digital Collections" header.

**Comment by tmacmath** [comment]
This is what the other pages would look like with "Digital Collections" as an h1: 

<img width="1529" alt="Screenshot 2023-07-25 at 2 04 50 PM" src="https://github.com/yalelibrary/YUL-DC/assets/9658383/f6e22801-e354-4e33-a356-c596901f5b3f">

**Comment by tmacmath** [comment]
There is also the issue of page text that is marked as an h2 structural element, which is incorrect. This is the current page (when there are no bookmarks): 

<img width="1532" alt="Screenshot 2023-07-25 at 2 24 04 PM" src="https://github.com/yalelibrary/YUL-DC/assets/9658383/c97412ef-5775-41d2-a13c-6e99a245014b">

It should look like this: 

<img width="1526" alt="Screenshot 2023-07-25 at 2 16 49 PM" src="https://github.com/yalelibrary/YUL-DC/assets/9658383/499c27af-1905-449e-9776-97d11cab0377">

**Comment by tmacmath** [comment]
I think we can go ahead and make "Digital Collections" an h1, and "Bookmarks" an h2. I can then look at it on demo.

**Comment by K8Sewell** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/40c5ab09-ef12-4f0f-b4b7-6a35a9979d9d)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/915

**Comment by sshetenhelm** [comment]
I still see Bookmarks as H1 in demo.


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/bdc6e784-554d-47e3-82bd-616cd0894f66) ?

**Comment by sshetenhelm** [comment]
This has finally updated for me. I think we can close this now.
