### ISSUE TITLE
[BUG] Fix alignment of Cite button on Bookmarks page gallery view

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2556]
**Story**
On the Bookmarks page, if Gallery View is selected, the bottom of the Cite button aligns with the top of the thumbnail of the first bookmark result. We would like it to have similar spacing as the Cite button has with the first search result in List View.

Screenshot of Gallery View _[we don't want]_:
![Image](https://user-images.githubusercontent.com/98423494/255286269-208b7d84-8355-45b9-b04f-0870e91781f3.png)

Screenshot of List View _[we want!]_:
![Image](https://user-images.githubusercontent.com/98423494/255286277-57166577-2b01-4940-8d92-f8a7e6b76457.png)

**Acceptance**

- [ ] Update spacing of Cite button on Bookmarks Page, Gallery View to resemble List View

**Comment by jpengst** [comment]
Feature Branch: 2301_EnableBookmark

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/912  
  
Screenshot:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/0ffa773c-255c-45d4-98e6-6133ca8c1ce9)

**Comment by sshetenhelm** [comment]
Looks good across mac/Chrome, mac/Safari, and mac/Firefox.
