### ISSUE TITLE
[DISCUSS] Bookmark checkbox on parent object page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2557]
**Story** 
We need to decide where the bookmark checkbox should appear on an individual parent object page. Once that decision is made, we can create a ticket for that work.

**Acceptance**

- [x] Decide where on parent object page bookmark checkbox should be located
- [ ] Create ticket for development work

**Comment by sshetenhelm** [comment]
@tmacmath I think yesterday in chat you mentioned you liked the default view. Could you please post a screenshot here to remind us what that looks like?

**Comment by sshetenhelm** [comment]
Some possibilities:
1. 


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/0ff0738f-2f01-4dab-9850-8ad6e38c5958)


2. 


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/ba3064de-9d48-4a90-867d-5feb4a3d0d70)



3. 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/a20507af-aec8-4b80-8d48-15a5921ac99c)



4.

**Comment by alisonclemens** [comment]
I'd vote for #1 or #2

**Comment by tmacmath** [comment]
I like the default - #1. No one will see it in the other areas.

**Comment by sshetenhelm** [comment]
Decided on version #1.

Created #2663 to enact this work.

Ready to close.
