### ISSUE TITLE
Add Repository field to Universal Viewer ‘More Information’ pane for ILS and Ladybird objects

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2558]
**Story**
For objects that are associated with a Voyager record, we would like the Repository information to display in the ‘More Information’ pane of the Universal Viewer. Without the Repository, other fields in the UV — such as Call Number — cannot be accurately understood.

If it is fairly simple to do, we would also like to add Repository for Ladybird objects. If it seems like it will take a lot of time/effort, we can disregard.

Note: To see the change, we will need to regenerate the IIIF manifest for objects once the development work is deployed to each environment. 

**Acceptance**
- [x] _Repository_ is added to ‘More Information’ pane of Universal Viewer underneath ‘Language’ and above ‘Call Number’ for ILS objects
- [x] _Repository_ displays correct information for ILS objects
- [x] _Repository_ is added to ‘More Information’ pane of Universal Viewer underneath ‘Language’ and above ‘Call Number’ for Ladybird objects
- [x] _Repository_ displays correct information for Ladybird objects

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1240

**Comment by jpengst** [comment]
Deployed to Test v2.62.7

**Comment by jpengst** [comment]
Looks good on test:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/eab23d86-3e77-4e48-ae06-a0942d1ba883)

**Comment by mikeapp** [comment]
UAT looks good:

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/a1febfd4-0c24-42b2-9d6e-fd1b77161d5b)
