### ISSUE TITLE
Camerata deployment test suite needs better password management

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#256]
**ACCEPTANCE**
- [x] Provide a clear error if no username/password are set
- [x] Document mechanisms to set username/password
- [x] Provide option to use existing username/password from secrets

**Comment by JzGo** [comment]
Will have a PR for my changes up soon: https://github.com/yalelibrary/yul-dc-camerata/compare/improve-password-management-for-tests?expand=1

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/fc333a6e-3493-483c-b494-2033d741139d)

https://github.com/yalelibrary/yul-dc-camerata#running-the-deployment-test-against-a-deployed-cluster

Looks good!  I'm going to fix up the documentation+handling of the other environment variables (URLs for the microservices) today.
