### ISSUE TITLE
Investigate Job Spawning

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2563]
# Summary
Preservica resync jobs appear to be spawning multiple jobs when enqueued and failures occur.  

# Acceptance Criteria
- [x] determine cause and remedy

**Comment by K8Sewell** [comment]
Cause: During the update parent / resync with Preservica batch process it was grabbing all existing children and recreating their PTIFFs which explains the massive jump in delayed jobs and was not a delayed job malfunction.  https://collections.library.yale.edu/management/batch_processes/13434/parent_objects/10022080 - only 31 child objects on Preservica but has original 4 child objects as well.

Remedy: Not all child objects had a content uri to compare so they were left on the parent.  The incoming PR will remove child objects that do not have a content uri.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1242

**Comment by jpengst** [comment]
Deployed to Test v2.62.8

**Comment by K8Sewell** [comment]
Deploying to UAT to use Test Preservica instance.
