### ISSUE TITLE
Group Open With Permission models

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2564]
**Story**

In management, group models related to open with permission work into a subdirectory/namespace.   

**Acceptance**
- [x] Move permission_*.rb and terms_agreement.rb into `/app/models/open_with_permission`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1244

**Comment by jpengst** [comment]
PR is now ready!

**Comment by K8Sewell** [comment]
Deployed to UAT for testing with release [v2.63.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.63.2)
