### ISSUE TITLE
Typo on "clear all bookmarks" confirmation dialog

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2567]
**Story**

On the bookmarks list page (`/bookmarks`), when clicking "Clear All Bookmarks", the confirmation pop-up has a typo

**Acceptance**
- [x] Change "You cannot undue this action" to "You cannot undo this action"

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/919

**Comment by sshetenhelm** [comment]
I still see the typo on the collections-demo pop-up.

**Comment by sshetenhelm** [comment]
This is in collections-demo on mac/Firefox after I reset all of my data, history, cache, etc., closed and re-opened Firefox, and used an incognito window. I have no idea why my computer refuses to acknowledge the change, but if someone else Yale-side can verify, I'm happy to close these tickets.

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/73b6d7af-c241-40ce-bf15-fdf94f4c77d3)

**Comment by sshetenhelm** [comment]
Updated to say several Yale team members have confirmed they still see the typo as well. Not just me!

**Comment by jpengst** [comment]
Im seeing "undue" too. I think the h2 title change was deployed, but maybe the typo PR hasnt been deployed yet.

**Comment by sshetenhelm** [comment]
Looks great! Thank you!
