### ISSUE TITLE
Turn off bookmarks for guest users?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2568]
**Story**

Guest users can bookmark items.   We have also had problems on other systems with guest user accounts filling up the Users table.   I suggest that we turn off guest users if possible (see https://groups.google.com/g/blacklight-development/c/2_cg97j97YE )

**Acceptance**
- [x] Turn off guest user functionality
- [x] When clicking on Bookmarks link, users that are not logged in get a "you need to log in" message
- [x] Bookmark checkboxes don't display for non-logged-in users

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/922

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1019

**Comment by K8Sewell** [comment]
Deployed to Demo with [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/35b6465bf70253ef4e1126f0cc8cddec259f85d1)

**Comment by sshetenhelm** [comment]
* Confirmed that bookmark boxes are not visible for users in search results when not logged in
* Confirmed that bookmark boxes are not visible for users on parent object pages when not logged in
* Confirmed that users who are not logged in receive a "please log in" message when clicking "Saved Items" at the top of the page
* Confirmed that bookmark functionality continues to work as expected for users after logging in 

On feature branch, so ready to close. Thank you!
