### ISSUE TITLE
Add 'Related Resource Online' field to More Information pane

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2571]
**Story**
We would like the field 'Related Resource Online' to display in the More Information pane of the Universal Viewer for objects that include this information in their metadata. 

This field should only apply to ILS objects with MARC **856**42  **|3** **|u**

_Note: To see the change, we will need to regenerate the IIIF manifest for objects once the development work is deployed to each environment._

Sample Object - TEST
https://collections-test.library.yale.edu/catalog/10081383
(Reminder for Summer: changed bib info for testing purposes; original bib info in 'Digitization Note')

Sample Object - UAT
https://collections-uat.library.yale.edu/catalog/2001862

Sample Object - PROD
https://collections.library.yale.edu/catalog/2001862 

**Acceptance**

- [ ] _Related Resource Online_ is added to ‘More Information’ pane of Universal Viewer underneath ‘Collection Date’ and above 'Genre'
- [ ] _Related Resource Online_ data displayed in the pane matches information displayed on the parent object's page in DCS
- [ ] After approving on UAT, Summer changed the TEST object's bib info back to original

**Comment by martinlovell** [comment]
Should we add "Related Version Online" also?

**Comment by sshetenhelm** [comment]
@alisonclemens 'Related Version Online' is mapped to marc _856 |41 |3u_. I'm not sure I've seen any examples of this in use; have you heard of this field being actively used?

**Comment by martinlovell** [comment]
I was able to find a few bibs with values: 8252352, 9796548, 9796550, 9796555, 9796564, 9796240, 9796272, 8251670

For the blacklight view, we filter out any where the link goes to: "brbl-archive.library.yale.edu", "divinity-adhoc.library.yale.edu/FosterPapers", "digital.library.yale.edu", "beinecke.library.yale.edu", "beinecke1.library.yale.edu", "collections.library.yale.edu", "hdl.handle.net/10079/digcoll/", which we can do for the IIIF manifest also.

(We can make the "Related Version Online" a different ticket if that would work better.)

**Comment by sshetenhelm** [comment]
Thanks Martin! For the examples you've given, it looks like they are all going to PDFs showing the Table of Contents of each work. If something is in DCS, linking out to the table of contents elsewhere seems unnecessary; at this point in time, I'm happy to just include 'Related Resource Online.'

If, in the future, stakeholders request including RVO with a different use case, we can reconsider.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1243

**Comment by sshetenhelm** [comment]
Looks good on Test after regenerating the IIIF manifest!

**Comment by mikeapp** [comment]
@sshetenhelm This release is up on UAT

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you!
