### ISSUE TITLE
'Export All Parent Objects by Admin Set' batch process does not finish for BRBL

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#2574]
**Story**
The BRBL admin set in MGMT PROD contains 109,608 parent objects as of 2023.08.10. 
The 'Export All Parent Objects by Admin Set' batch process was initiated for the BRBL set at 4:00 pm on 2023.08.09. [As of 23 hours later, it has still not completed](https://collections.library.yale.edu/management/batch_processes/13447).

We should investigate why this job has not completed, and fix the 'Export All Parent Objects by Admin Set' batch process so that it successfully completes for a large admin set such as BRBL.

Screenshot of Delayed Job Dashboard message taken on 2023.08.16:

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/b9d40b3e-fd11-4858-bec7-a5f076df125f)

**Acceptance**

- [ ] The 'Export All Parents by Admin Set' batch process successfully completes for the BRBL admin set
- [ ] All BRBL parents are included in the export

**Comment by jpengst** [comment]
Was this BP in the "Working" status since it started on Aug 9?  I see the BP has completed and the file is ready for download. I'm wondering if it's a resources issue? I ran an export on UAT brbl that has about 60,000 records and it completed in about a minute.

**Comment by jpengst** [comment]
Refactor PR: https://github.com/yalelibrary/yul-dc-management/pull/1246

**Comment by jpengst** [comment]
Looks good on Test:


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/aafb8a05-7e4a-4083-a923-457a1b55432d)

**Comment by jpengst** [comment]
Deployed UAT v2.63.0

**Comment by jpengst** [comment]
Worked great on UAT:  
https://collections-uat.library.yale.edu/management/batch_processes/1510  
  
I exported 130k parents from all of the admin sets and it completed successfully.

**Comment by sshetenhelm** [comment]
Ready to close! Thank you

https://collections-uat.library.yale.edu/management/batch_processes/1520 
Successfully exported 100k+ objects from same admin set.
