### ISSUE TITLE
Permission Request Users: add NetID field

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2577]
**Story**

Cognito will assign a username to Yale users that contains the NetID, but is hard to read.   Blacklight should send the NetId to Management as well.

**Acceptance**
In Management:

- [x] Add a `netid` field to the PermissionRequestUser object.   It should be unique but nullable, since non-Yale users will not have a NetID.
- [x] Display this field wherever the other user information is displayed.
   - [x] `app/views/permission_requests/index.html.erb`
   - [ ] others?
- [x] Modify `PermissionRequestsController` to accept the `netid` as an additional parameter for the user in `find_or_create_user`

**Comment by jpengst** [comment]
Are we wanting to find_or_create_user based on the netid (if exists), or are we just saving the user.netid attribute (if it exists) from the request?

**Comment by mikeapp** [comment]
Just save it.  It should be unique, if it isn't then there's a problem upstream.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1264

**Comment by jpengst** [comment]
PR for NetID unique validation: https://github.com/yalelibrary/yul-dc-management/pull/1266

**Comment by jpengst** [comment]
Deployed to Test v2.63.7

**Comment by K8Sewell** [comment]
Visible on Test.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/53391f4a-687e-4eba-bce6-231d9567e714)

**Comment by sshetenhelm** [comment]
Confirming I can see netID field in UAT. Thank you!
