### ISSUE TITLE
Blacklight: add sub and netid fields to the Users table

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2578]
**Story**

Blacklight will need to store additional information about the users logging in from Cognito.

**Acceptance**
- [x] Add to the Users table a `sub` field as below
- [x] Add to the Users table a `netid` field as below

```
def up
    change_table :users do |t|
      t.string :sub, unique: true, null: false
      t.string :netid, unique: true
    end
  end
```

**Comment by jpengst** [comment]
Blacklight OwP feature Branch: `OwP_FeatureBranch`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/929

**Comment by DraxIndustries79** [comment]
@mikeapp would be good for you to review the updated PR

**Comment by K8Sewell** [comment]
Feature branch deployed to Demo with PR[#931](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by K8Sewell** [comment]
No issues logging in on Demo



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/c5426aba-7271-4bcf-b424-01d4468ff36c)
