### ISSUE TITLE
Management Dashboard - Choose metadata source from dropdown for Solr index

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#258]
- Right now, we have 3 separate buttons to index metadata to Solr, based on metadata source
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/87a6f3ea-c33b-42ea-925e-d43d6aa1ced9)

- I'd like a dropdown where I can choose my metadata source (Voyager ("ils"), Ladybird, ArchiveSpace, or All), and then have a single button to "Index to Solr"
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/c116521d-d5f5-4020-a35a-46fa9913a123)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/c4a0dac7-ba95-4dcb-84c2-aba9c59eaeec)

**Comment by mark-dce** [comment]
See the GitHub merge button for a single button solution to this kind of problem:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3064318/85459128-78bafa00-b567-11ea-8862-4289efab5be5.png">

**Comment by mark-dce** [comment]
The styles are rendering correctly, so it's hard to tell for sure, but it looks like this is doing the correct thing if we were seeing bootstrap correctly.  I'm going to close it for now and will re-open if there's an issue after we get bootstrap working in production.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/3064318/85958666-ac799380-b95c-11ea-8fc4-fae0de6dfba2.png">
