### ISSUE TITLE
Spike: PermissionSetsController - break out public API?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2581]
**Story**

For two controllers in Management the public API has been broken out into the `API::` module.  Should we do this for `PermissionSetsController` as well?    

**Acceptance**
- [x] break out `agreement_term` and `terms_api`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1270

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.63.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.63.9)

**Comment by K8Sewell** [comment]
No obvious issues.  Will promote to UAT.
