### ISSUE TITLE
[BUG] Mobile - Metadata in field is too close to the field label

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2583]
**Story**
For Blacklight on mobile devices, text in the metadata field abuts/overlaps field label. We should change margin-left for the <dd> from 82px to 100px for mobile only (media query).

Screenshot  (see Published/Created field):
![Image](https://user-images.githubusercontent.com/98423494/261653774-8abcec69-c5d2-43d0-b2ab-215b0d5a849f.png)

**Acceptance**
- [x] Change margin-left for the <dd> from 82px to 100px for mobile only (media query)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1012

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v1.61.8](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.61.8)

**Comment by sshetenhelm** [comment]
Looks good on test for me when using Developer Tools in browser to emulate.

**Comment by sshetenhelm** [comment]
It looks like it overlaps somewhere between 360 and 390 pixels, as per the developer tools in Chrome. Apologies I didn't catch this earlier. 

Is there some sort of best practice for super small width screens? 

It looks like fields with longer labels such as Subject (Geographic), Container / Volume, and Published/Created are the main culprits. 



![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/7317456a-4ab8-4e5e-a4f0-2f5c4f99ed47)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1018

**Comment by jpengst** [comment]
Deployed to Test v1.61.9

**Comment by K8Sewell** [comment]
Looks good on all breakpoints.  Will promote to UAT.

<details> 



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/9fb73bfa-b7b0-48a1-8931-94a75bedc6b7)




![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/07897ed0-6c8b-40ac-98ee-a176a8ec6433)





![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/ea8ce153-f366-406b-bdc2-ea545fa278a2)




![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/06de8ea6-12b6-4ebc-8aec-15f286d64075)





![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/f89a9689-75b4-4772-8abe-61e0933dc48e)






![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/defd0828-bb0b-4cd2-b414-0b65c41f6680)





</details>

**Comment by sshetenhelm** [comment]
Looks good in UAT! Thank you
