### ISSUE TITLE
Mobile - Extra spacing in text wrapping on landing page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2584]
**Story**
For Blacklight on mobile devices, for the _Statement on Potentially Harmful Content_ heading, there is extra space between lines when wrapping. We do not want this extra space. In #highlights h2, we should decrease line-height to 1.25 (in the media query).

Screenshot:

![Image](https://user-images.githubusercontent.com/98423494/261655495-39a4cdb2-9bc2-4fde-a740-a7730c622a5c.PNG)

**Acceptance**

- [ ] In #highlights h2, line-height is decreased to 1.25 (in the media query)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/1010

**Comment by laurenb33** [comment]
Look good on UAT! Ready to close :) 
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/9003d74c-e1f3-4a03-8e43-39acdff0b378)
