### ISSUE TITLE
[BUG] Mobile - Aspace tree top margin too small

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2585]
**Story**
On mobile, the ArchivesSpace tree directly abuts the ‘Search for Additional Material’ label. The Aspace tree should have a bigger top margin on mobile.

Screenshot:
![Image](https://user-images.githubusercontent.com/98423494/261656697-4b6af1b9-7ab9-43bd-b236-8168c67c3043.png)

**Acceptance**
- [x] ArchivesSpace tree has margin-top: 15% on mobile

**Comment by jpengst** [comment]
This might not be an issue anymore. I'm seeing pretty good mobile spacing across multiple browsers (safari, chrome, and firefox):  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/a327c258-4c07-4dad-8806-e2f57b5d9ed0)

**Comment by sshetenhelm** [comment]
I'm still seeing the same spacing as the original screenshot on my iphone 13 mini using Safari.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1017

**Comment by K8Sewell** [comment]
Looks good on mobile but on larger screens there is more space than there used to be.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/67d3cf5a-6a43-4435-a40c-b773408041f8)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1020

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.1](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.1)

**Comment by K8Sewell** [comment]
Looking alright on Test (in responsive mode in Safari).  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/56dafc8c-7b21-4dfb-8e64-6b43900508c8)

**Comment by sshetenhelm** [comment]
Looks good to me on UAT!  Ready to close :)
