### ISSUE TITLE
[BUG] Mobile - advanced search drop down arrows cover label

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2586]
**Story**
On mobile, on the Advanced Search page, for the "Find Items that Match" drop down, the blue arrow icons indicating there is a drop-down menu overlap with the text of the menu choice. We do not want the arrows and text to overlap.

Screenshot:
![Image](https://user-images.githubusercontent.com/98423494/261657952-59b1e579-2774-45ac-a3d7-6cb7774586f1.png)

Screenshot from iphone 13 mini, iOS 17.2.1, with Safari browser

**Acceptance**
- [x] Arrows and drop-down text do not overlap
- [x] Arrows appear to right of drop-down text

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1011

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.61.7](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.61.7)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1018

**Comment by jpengst** [comment]
Deployed to Test v1.61.9

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/ed553650-0275-417d-ad7f-12fdf7848b27)

**Comment by sshetenhelm** [comment]
Looks good in UAT! Thank you!
