### ISSUE TITLE
Add 'Open with Permission' and set key visibility to batch process spreadsheets

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2590]
**Story**
'Open with Permission' is a new Visibility status. We should update both (a) batch process templates and (b) resulting exported csv files to include this new status. We should also include the Permission Set Key for objects with this status.

**Acceptance**
Batch process templates -- Create Parent Objects (to be completed **AFTER** #2675)
- [x] _Create Parent Objects_ batch process accepts Visibility of `Open with Permission` 
- [x] _Create Parent Objects_ batch process includes column for Permission Set Key immediately after visibility column
- [x] _Create Parent Objects_ batch process fails if Visibility = OwP and there's no data or incorrect data in key cell
- [x] If failed for no permission or incorrect permission key, batch process failure message displays --  _Process failed. Permission Set missing or nonexistent._
- [x] _Create Parent Objects_ batch process fails if user is not admin of Permission set matching key
- [x] If failed for not admin, batch process failure message displays --  _Process failed. User does not have edit permissions for this Permission Set.'_

Batch process templates -- Update Parent Objects
- [x] _Update Parent Objects_ batch process accepts Visibility of `Open with Permission`
- [x] _Update Parent Objects_ batch process includes column for Permission Set Key immediately after visibility column
- [x] _Update Parent Objects_ batch process fails if Visibility = OwP and there's no data or incorrect data in key cell
- [x] If failed for no or incorrect permission key, batch process failure message displays --  _Process failed. Permission Set missing or nonexistent._
- [x] _Update Parent Objects_ batch process fails if user is not admin of Permission set matching key
- [x] If failed for not admin, batch process failure message displays --  _Process failed. User does not have edit permissions for this Permission Set._

Exported results CSVs -- 
- [x] _Export Parent Metadata_ batch process exported results csv includes Visibility of 'Open with Permission' and Permission Set key (in column immediately after Visibility column) for such objects
- [x] _Export All Parents by Admin Set_ batch process exported results csv includes Visibility of 'Open with Permission' and Permission Set key (in column immediately after Visibility column) for such objects
- [x] _Export All Parents by Admin Set_ batch process from admin set page exported results csv includes Visibility of 'Open with Permission' and Permission Set key (in column immediately after Visibility column) for such objects

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1320

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.66.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.5)

**Comment by K8Sewell** [comment]
Testing on Test: mostly good but rework may be needed.

* Create Parent Objects: Did not keep OwP visibility although it was set to it and I was an admin on this permission set during the processing of the create parent job.  
https://collections-test.library.yale.edu/management/parent_objects/10653833
https://collections-test.library.yale.edu/management/batch_processes/790

* Update Parent Objects: Updated to OwP visibility successfully but when I remove myself as an admin on the permission set I can still set the parent object's permission set key to that set I don't have permission for in the update batch process and I believe that should error instead.
https://collections-test.library.yale.edu/management/batch_processes/792
https://collections-test.library.yale.edu/management/batch_processes/794

* Export Parent Metadata: Includes OwP visibility and the correct permission set key
https://collections-test.library.yale.edu/management/batch_processes/795

* Export All Parents by Admin Set (from Batch Process page): Same as above
https://collections-test.library.yale.edu/management/batch_processes/796

* Export All Parents by Admin Set (from Admin Sets page): Same as above
https://collections-test.library.yale.edu/management/batch_processes/797

**Comment by K8Sewell** [comment]
Update on update parent job - permission warning as expected once I was not a sysadmin



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/5cdfb8f9-88c4-4614-bcb8-fb53f2d32477)

**Comment by jpengst** [comment]
bug PR: https://github.com/yalelibrary/yul-dc-management/pull/1322

**Comment by jpengst** [comment]
Deployed to Test v2.66.6

**Comment by sshetenhelm** [comment]
Uh, so this error appeared for [Batch Process 801](https://collections-test.library.yale.edu/management/batch_processes/801/parent_objects/800052797) when I tried to create a parent with the Key `Secondary Permission Set`, which is a real Key in Test. 

`Setup job failed to save: undefined local variable or method `permission_set_was' for #<ParentObject:0x000055d5a142fd48> Did you mean? permission_set_id_was permission_set permission_set_id permission_set= permission_set_id? permission_set_id=`

I **was able to successfully create the parent** despite the warning. 

I also tried the Update Parent Objects batch process, and received the same error as above when using the Permission Key `summer`, which is a real Key in Test. However, **the changes did save** when I completed this process. See [Batch Process 805](https://collections-test.library.yale.edu/management/batch_processes/805/parent_objects/2030427)

- [ ] Figure out why above error is appearing and resolve to prevent user confusion

For Update Parent Objects batch process, I did not receive a warning for leaving out the Key, although I can confirm that when I left out the key, the Visibility did not update. See [Batch process 804](https://collections-test.library.yale.edu/management/batch_processes/804)

- [ ] When Key is missing from Update Parent Objects batch process with Visibility = Open with Permission, batch process failure message displays -- _Process failed. Permission Set missing or nonexistent._

**Comment by K8Sewell** [comment]
@sshetenhelm I ran into this error too.  There's a fix coming w/ PR [#1325](https://github.com/yalelibrary/yul-dc-management/pull/1325) from ticket #2724 and that is in team review.  So that takes care of the first checkbox.  For the second one - I'll kick this ticket back to in progress so we can add the warning for if the permission set is missing/non-existent.  I believe there is already a check for this and perhaps the first error was gunking up the works but I'd like to do more investigation and make sure this is working as expected.

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.66.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.8)

**Comment by K8Sewell** [comment]
On Test, when replicating batch process # 804 to see if the `was` attribute was the cause of not getting the warning message for not having a permission set key, batch process [#813](https://collections-test.library.yale.edu/management/batch_processes/813) did not display a warning as expected.  Kicking back to in progress to determine why batch process is not receiving and displaying the expected error to the user.

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.66.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.9)

**Comment by sshetenhelm** [comment]
Looks great on UAT and works as expected! Had non-SysAdmin test for warning messages, and it worked!

Ready to close and THANK YOU!
