### ISSUE TITLE
Parent Object edit/view screen updates

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2591]
**Story**

In #2587 we defined a relationship between visibility and Permission Set select controls.  These controls should be adjacent on the form.

**Acceptance**
 - [ ] On the Parent Object edit view, move the Permission Set next to the Visibility as shown below.
 - [ ] On the Parent Object read-only view, display the Permission Set label immediately after the Visibility.
   
![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/9e917c73-ad80-45ba-9b29-5ce15db48ee2)

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/4a835026-1766-4fe3-89da-5c2c9991efa8)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1248

**Comment by sshetenhelm** [comment]
I'm seeing double in UAT on mac/Chrome and mac/Firefox.



![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/b28d96b3-f5c2-43b6-8e1b-edc687358cac)

**Comment by jpengst** [comment]
Oh no!! Yep, I had a merge conflict on this one and I missed it. Whoops! Ill fix. Thanks for finding it!

**Comment by jpengst** [comment]
Fixed on Test. Deploying to UAT:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/2278dc6d-c2ad-436c-a94a-785ceb18564f)

**Comment by jpengst** [comment]
Fixed on UAT:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/498e39bc-70d0-41e8-a054-bc6955667c80)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you!

Ready to close.
