### ISSUE TITLE
Open with Permission in Parent Object view(s)

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2592]
**Story**

The new "Open with Permission" visibility requires changes to the Parent Object edit view and its behavior.

Note that the "Access Control" requirements related to user roles in the Permission Sets will also apply to batch jobs in a future issue.

General rules:
*  If the Parent is "OwP", only an admin of the current Permission Set can change its visibility or permission set
* Only the admin of a Permission Set can assign an item to a Permission Set.
* As usual, a user must also be an editor or admin of the Parent's Admin Set to make any changes.

**Acceptance**

In the Parent Object edit screen:
   - [x] If the visibility is set to something other than "Open with Permission"
     - [x] set the Permission Set to "None"/null
     - [x] disable the Permission Set select control
   - [x] If the visibility is set to "Open with Permission"
     - [x] enable the Permission Set select control
     - [x] require the Permission Set value to be selected (i.e. not None/null)
 - [x] Access control
   - [x] If the Parent visibility is currently "Open with Permission"...
      - [x] disable the visibility and permission set controls if the user is not an admin of the Parent's permission set
      - [x] If the user is an admin of the PS and can edit it, the Permission Set select control should only display Permission Sets for which the user has admin privileges  
   - [x] If the Parent visibility is something else
      - [x] Only display the "Open with Permission" visibility option if the use is an admin of at least one permission set
      - [x] In the Permission Set select control, only display Permission Sets for which the user has admin privileges  
    - [x] In the controller validate that:
        - [x] the user has rights to change the Parent visibility away from "Open with Permission"
        - [x] the user has rights to change the Parent away from a Permission Set    
        - [x] the user has rights to change the Parent into a Permission Set

**Comment by jpengst** [comment]
"Only display the "Open with Permission" visibility option if the user is an admin of at least one permission set"  
  
Are we checking if the user is an admin of the specific `parent_object.permission_set`?  
Or is this saying we be checking if the user is an admin of **any** permission set?   
  
If we are checking for admin access on the specific `parent_object.permission_set`, that assumes that there is already a permission_set assigned to the parent object.

**Comment by mikeapp** [comment]
This: "checking if the user is an admin of any permission set?" 

If a parent object is *not* OwP, it  won't make sense to give the option to change it to OwP *unless* the user is an admin of at least one PermissionSet that they could then assign the object to.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1262

**Comment by jpengst** [comment]
Deployed to Test v2.63.7

**Comment by K8Sewell** [comment]
Visible on Test and working as expected.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/ab13d1d0-14c6-4c2b-a12c-25e82d1fc8a6)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/dbe90e63-4890-4c9a-b82c-f8e38178015b)

**Comment by sshetenhelm** [comment]
Looks good in UAT! Thank you :)



![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/ff1f9f5f-fbd8-4e78-98c3-f91cdc768385)
