### ISSUE TITLE
Use Sierra API to get MARC records

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2595]
Marc records for sierra are currently read from a static .mrc file containing all the marc records.
We have access the sierra api to get up-to-date marc data.

- [x] Setup Sierra API client in Java for metadata cloud.
- [x] Use the API to get the marc records for sierra requests.
- [x] Including example tests with mocks.

**Comment by martinlovell** [comment]
Service now ticket to add config to properties files:
[INC2604596](https://yale.service-now.com/nav_to.do?uri=incident.do?sys_id=e84266cc9781bd10a61a9614a253af8d)

**Comment by martinlovell** [comment]
PR for Switching to using API: https://github.com/yalelibrary/metadata-cloud/pull/487

**Comment by sshetenhelm** [comment]
Approval: look at sierra records, are they ok?

**Comment by sshetenhelm** [comment]
As per Law -- 

"This looks good! The only thing we noted that needs to be adjusted is the call number field. The 099 is removed in the digital record and the call number would have been moved to 533 |n. 

In addition, are you to pull the bib ID, barcode, and container/volume field (which in Sierra would be the volume field in the item record)? I think Voyager records have enumeration and chronology fields that we don’t have for volume information."

@martinlovell Should we close this initial API ticket and create new tickets for (a) call number and (b) container/volume? 

Not sure about pulling Bib and Barcode, as those would need to be input by Law to create objects???

**Comment by martinlovell** [comment]
Yes, new tickets for (a) and (b) sound good.

Currently, we are only going to the bib level.  We will need add new request handlers in MC that includes item ID or barcode id to pull information from the correct item, similarly to how we do with Voyager.

(The sierra api may not let us lookup items by barcode, but we can get all the items for a bib and look a match. https://techdocs.iii.com/sierraapi/Content/zAPIs/itemAPI.htm#Get. 
For Voyager, we give precedence to the barcode, so if there is a barcode and item id entered in DCS, we correct the item id to match the barcode when we get the data from MC.  We can do the same for Sierra.)

**Comment by sshetenhelm** [comment]
Created #2610 for Call Number Mapping

Created #2611 for Container/Volume

Created #2612 for Metadata Cloud request handlers

Please feel free to edit the above tickets to capture the work more accurately. Let me know if you need me to get any info from Law.

Ready to close.
