### ISSUE TITLE
Remove space from URI in docker compose template

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2596]
**Story**

Extra space in URI value in camerata template

**Acceptance**
- [x] space removed

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/366

**Comment by K8Sewell** [comment]
Merged and will be present in upcoming blacklight and management releases.

**Comment by mikeapp** [comment]
This only impacts development, so closing.
