### ISSUE TITLE
[DISCUSS] Block GPTBot?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2598]
**Question**

Do we want to block OpenAI/GPTBot from harvesting content?   

## Acceptance:
- [x] Decide if we want to block
- [x] Make a ticket if yes -- #2608

**Comment by sshetenhelm** [comment]
- I'm comfortable allowing GPTBot to scrape metadata. 
- I am not comfortable allowing GPTBot to scrape archival content materials (text, pdf, images, etc.)

Reasoning: 

- Most Yale-created metadata should be open (in theory).
- From a tech perspective, would want to explore load this would create on our system and implications on service for actual human users.
- I would want to do more investigation into copyright implications of allowing scraping of in-copyright data (ex. what exactly do Yale gift agreements say re: distribution of materials, what about materials for which we don't have clear gift agreements, etc.?).
- Also interested in the ethical or moral conversations around large-scale data harvesting of archival object content, especially of pre-digital era objects (this is my vague and not fully articulated thinking of things along the same lines as issues discussed in [Privacy anxieties: Ethics versus activism in archiving lesbian oral history online](https://doi.org/10.1215/01636545-2849576), etc.). 

@motropuk and @alisonclemens I would be interested in your thoughts before we confirm a final decision (which could be changed in the future, of course).

**Comment by alisonclemens** [comment]
Agreed with Summer on all of the above. Archival description at Yale is licensed under a CC0 1.0 Universal (CC0 1.0) Public Domain Dedication, so I'm likewise comfortable with metadata scraping but not content scraping. I'd also be fine with blocking the bot from scraping at all, if people prefer that

**Comment by sshetenhelm** [comment]
Summer will make placeholder ticket
