### ISSUE TITLE
[Bug] Extent of Digitization preface shows in Blacklight/UV for objects with no Extent of Digitization value

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2599]
**Story**
For objects that have currently have no information in the Extent of Digitization field, the value “This object has been no.” is added for the Extent of Digitization field in Blacklight when (1) a user performs an ‘Update Parent Object’ batch process that does not include ‘Extent of Digitization’ information and (2) when an object undergoes a fresh metadata sync.

Extent of Digitization was added as a required field in DCS after objects had already started being migrated and ingested into DCS. Many objects lack Extent of Digitization information, especially migrated objects. When a migrated object is reassociated with a descriptive record using using the ‘Update Parent Object’ batch process, the metadata/ updates and the Extent of Digitization field becomes visible in Blacklight. Objects that are edited and/or resynced with metadata also have this field appear in Blacklight.

For objects that lack this information, we would like to suppress the Extent of Digitization field from showing in Blacklight.

Screenshot:

![Image](https://user-images.githubusercontent.com/98423494/263109039-c7511ff6-c130-4ee4-8319-61fde9c12890.png)

**Example Objects:**
TEST
** For objects in TEST, ‘Extent of Digitization’ shows as an empty field in the UV but does not display on the parent view page in Blacklight. I could not replicate the same issue exactly. These objects have the empty field in UV.**
https://collections-test.library.yale.edu/catalog/2053296
https://collections-test.library.yale.edu/catalog/800015166

UAT
https://collections-uat.library.yale.edu/catalog/12482169
https://collections-uat.library.yale.edu/catalog/12482103

PROD
https://collections.library.yale.edu/catalog/16047548. (fixed via manual update, see comment below)
https://collections.library.yale.edu/catalog/16047546
https://collections.library.yale.edu/catalog/2005096
https://collections.library.yale.edu/catalog/11001422

See [Batch Process 13540](https://collections.library.yale.edu/management/batch_processes/13540) for an example of when this happened.

**Acceptance**

- [ ] Suppress the ‘Extent of Digitization’ field from Blacklight when an object does not have Extent of Digitization information

**Comment by mikeapp** [comment]
The facet also shows "No"  (example from PROD):

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/b3047596-a06d-4ae1-8604-ec3a3b5a1be0)

This value is in the index: `"extentOfDigitization_ssim":["No"]`.

**Comment by mikeapp** [comment]
Pressing "update metadata" did not change this, but performing a manual edit/update on the object worked, the Extent of Digitization field did not display.  

Code from `solr_indexable.rb`:

```
  def generate_digitization_note(digitization_note)
    digitization_note.presence || self&.digitization_note || nil
  end
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1257

**Comment by jpengst** [comment]
Deployed to Test v2.63.5

**Comment by sshetenhelm** [comment]
For Test, after recreating IIIF manifest, 'Extent of Digitization' is showing as label with blank data in UV (ex. object 2053296):


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/7730cacd-37f3-491f-bcd8-ce409cd66700)

**Comment by sshetenhelm** [comment]
Still seeing "Extent of Digitization" as empty label in UV after refreshing item manifest. Occurs across multiple browsers.

As per Mike's question, could these display in the faceting as "Unspecified" ?

**Comment by jpengst** [comment]
What's the status of this ticket? Last I remembered, we were waiting on feedback on what Extend of Digitization should say if the object isn't Completely or Partially Digitized. Are we using "Unspecified"?

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1282

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.3)

**Comment by K8Sewell** [comment]
Still looks blank in UV after the parent object went through an update.  Will move back to in progress.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/6163093a-980b-43e3-87bf-1b0efa311cec)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1285

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.5)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/34d67ffb-cc6d-419b-9d1e-289de8611db4)

**Comment by sshetenhelm** [comment]
With this fix, we are returned to our original issue, which is that the prefix on the parent object page displays incorrect text. On UAT, this now appears as _Extent of Digitization - This object has been unspecified._ This language is confusing for users. 

To clarify: 
1. If the object does not have a value for Extent of Digitization, we do not want the "Extent of Digitization" field to appear any place within the parent object page -- not in the parent object display page metadata, and not in the 'More Information' panel of the universal viewer.

2. We had requested that, if possible, "Unspecified" show up in the left hand filters under 'Extent of Digitization' in order to show that there were other outstanding objects if users tried to filter by extent of digitization. 

If #1 and #2 are not done together, than the priority is for #1 -- to remove the field completely from the parent object display page and universal viewer. The issue with the original fix was that "Extent of Digitization" was showing as a field but with no value in the More Information page. 

Please let me know if I need to further clarify!

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/1289  
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/945

**Comment by jpengst** [comment]
Deployed Test Management: v2.64.7  
Deployed Test Blacklight: v1.60.91

**Comment by laurenb33** [comment]
Hi all, 

Below is a list of the objects I checked; I can confirm 'extent of digitalization' has been successfully removed from Description for all of them. The objects under EoD 'unspecified' in UAT (4 objects) and TEST (4 objects) do not show 'Extent of Digitalization' under Description :) 

TEST
https://collections-test.library.yale.edu/catalog/2053296
https://collections-test.library.yale.edu/catalog/800015166

UAT
https://collections-uat.library.yale.edu/catalog/12482169
https://collections-uat.library.yale.edu/catalog/12482103

PROD
https://collections.library.yale.edu/catalog/16047548. (All set, Cait!)
