### ISSUE TITLE
SPIKE: Temporarily show Voyager and Ladybird records in Discovery for analysis purposes

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#260]
- The Management application currently indexes from each Metadata Source to Solr successfully
- Only Solr records from Ladybird are currently displaying in the Discovery application
- I would like to see the records from each Metadata Source in the Discovery application

- [x] Investigate why non-Ladybird Solr records are not displaying in Discovery application
  - First guess [visibility_ssi | itemPermission](https://github.com/yalelibrary/yul-dc-management/blob/e36aeb5b7ab9227f23b9b89283e895d288a8439d/app/services/fixture_indexing_service.rb#L88) may not be available in non-Ladybird records? 
- [x] Determine what steps would be needed in Management and / or Discovery applications to rectify
- [ ] Either rectify, or create further appropriate tickets

**Comment by maxkadel** [comment]
It is, in fact, the visibility_ssi. We need to treat Ladybird as the source of authority for visibility for items, even if the record we're showing is from Voyager or ArchiveSpace. 

This is the result of adding visibility to the ParentObject model, and adding it to Solr if it's not in the MetadataCloud record. 

Top record is Voyager, bottom record is Ladybird.
![image](https://user-images.githubusercontent.com/45948126/85465687-14079b80-b577-11ea-95d9-ec397bd53a90.png)

**Comment by mark-dce** [comment]
@maxkadel The records are not showing in the discovery interface, but the are available in Solr.  I think this is an adequate solution and am happy to close the ticket unless you want to work on visibility more.

**DISCOVERY**
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/3064318/85958768-9ddfac00-b95d-11ea-8cfe-2901d10f2b0c.png">

**SOLR**
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/3064318/85958809-f1ea9080-b95d-11ea-9f5a-e4de692a45c7.png">

**Comment by maxkadel** [comment]
@mark-dce the work to get these visible once the database is populated has already been merged - https://github.com/yalelibrary/yul-dc-management/commit/01d83c092b3e7c8dc68bda3bfde40e3119d3f924 

We just don't have a time/place for when the ids and visibility get populated in the database, which is why I added a button.
