### ISSUE TITLE
WAF rules fix

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2606]
**Story**

For DevOps, See ServiceNow ticket.

**Comment by ra359** [comment]
In the process of creating "acl-dcs-nonprod" and "alb-yul-dc-prod" Web ACLs that contain the (3) requirements.

**Comment by ra359** [comment]
new ACL "web-acl-dcs-nonprod" in effect on alb-yul-dc-test. This applies the following rules:

rule-block-by-ip
rule-challenge-tiff-downloads
rule-block-mgmnt-api

**Comment by mikeapp** [comment]
Looks good.  I do have a question that I'll add to the SN ticket.
