### ISSUE TITLE
Block GPTBot

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2608]
We would like to block GPTBot from scraping digital collections content--images, text files, PDFs, etc.

We are OK with allowing the scraping of Metadata only.

See: https://www.zdnet.com/article/how-to-block-openais-new-ai-training-web-crawler-from-ingesting-your-data/

**Acceptance**

GPTBot "disallowed"  in `robots.txt`  from:
- [x] Images
- [x] PDFs
- [x] Full text API endpoints

**Comment by mikeapp** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/951

**Comment by jpengst** [comment]
Deployed to UAT v1.60.94

**Comment by mikeapp** [comment]
Looks good to me on UAT
