### ISSUE TITLE
Add field ProvenanceUncontrolled to Blacklight and UV

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2609]
**Story**
`ProvenanceUncontrolled` is a field that stakeholders have requested be included in DCS. `ProvenanceUncontrolled` is already mapped in Metadata Cloud and included in an object’s JSON record. `ProvenanceUncontrolled` is not included in an object’s Solr record. We should not need users to be able to search Provenance at this time.

The field label on Blacklight should be Provenance.

**ProvenanceUncontrolled MARC:**
Bib:  
561a3

Holding:
561
541ad3

**ProvenanceUncontrolled Aspace:**
Field Type: notes
Note Types: custodhistacqinfo
Strip Tags: True
Join Strings: ,

**SAMPLE OBJECTS**
TEST - [https://collections-test.library.yale.edu/catalog/800045169](https://collections-test.library.yale.edu/catalog/800045169) (ILS)
[https://collections-test.library.yale.edu/catalog/800052182](https://collections-test.library.yale.edu/catalog/800052182) (Aspace)

UAT - [https://collections-uat.library.yale.edu/catalog/900102435](https://collections-uat.library.yale.edu/catalog/900102435) (ILS)
[https://collections-uat.library.yale.edu/catalog/900148576](https://collections-uat.library.yale.edu/catalog/900148576) (Aspace)

PROD - [https://collections.library.yale.edu/catalog/33071427](https://collections.library.yale.edu/catalog/33071427) (ILS)
[https://collections.library.yale.edu/catalog/33071633](https://collections.library.yale.edu/catalog/33071633) (Aspace)

**Acceptance**

- [x] `ProvenanceUncontrolled` displays on Blacklight parent object view page as _Provenance_
- [x] On parent object view page, _Provenance_ displays beneath _Description_ and above _Extent of Digitization_
- [x] `ProvenanceUncontrolled` displays in Universal Viewer ‘More Information’ pane as _Provenance_
- [x] In UV ‘More Information’ pane, _Provenance_ displays beneath _Description_ and above _Extent of Digitization_
- [x] _Provenance_ displays information that matches the object’s descriptive record
- [x] _Provenance_ label does not display on page or in the UV if the descriptive record does not have data in this field

**Comment by jpengst** [comment]
Looks good on test. Deploying to UAT

**Comment by sshetenhelm** [comment]
Looks good in UAT! Thank you so much.

Ready to close :) I appreciate you!
