### ISSUE TITLE
Add Container/Volume for Sierra

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2611]
**Story** 
Container/Volume information needs to be added for Sierra records. In Sierra, this would be the Volume field in the Item record. 

Original Sierra API work in #2595 

**Acceptance**

- [x] Container/Volume information added for Sierra records

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/metadata-cloud/pull/499

**Comment by martinlovell** [comment]
See: 
https://metadata-api-test.library.yale.edu/metadatacloud/api/sierra/barcode/35102006006772.json?bib=446543
or 
https://metadata-api-test.library.yale.edu/metadatacloud/api/sierra/item/737482.json?bib=446543

The bib data barcode or itemId does not include volumeEnumeration:
https://metadata-api-test.library.yale.edu/metadatacloud/api/sierra/bib/446543.json

**Comment by sshetenhelm** [comment]
Will confirm with Law before closing.

**Comment by sshetenhelm** [comment]
Ready to close :)

Thank you!
