### ISSUE TITLE
Add request handlers in Metadata Cloud for item info

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2612]
**Story**
Law has requested we pull the Bib ID and Barcode for Sierra records. We need to add new request handlers in MC that include item ID or barcode ID from the correct item, similar to how it is done with Voyager.

(The sierra api may not let us lookup items by barcode, but we can get all the items for a bib and look for a match. https://techdocs.iii.com/sierraapi/Content/zAPIs/itemAPI.htm#Get.
For Voyager, we give precedence to the barcode, so if there is a barcode and item id entered in DCS, we correct the item id to match the barcode when we get the data from MC. We can do the same for Sierra.)

Original Sierra API work in #2595

**Acceptance**

- [x] Add request handlers in MC that include item ID or barcode ID

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/metadata-cloud/pull/499

**Comment by martinlovell** [comment]
https://metadata-api-test.library.yale.edu/metadatacloud/api/sierra/barcode/35102006006772.json?bib=446543

**Comment by sshetenhelm** [comment]
Will confirm with Law before closing.
