### ISSUE TITLE
Adjust MC URL for Sierra to ignore holding

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2615]
When a ParentObject has Sierra as its source, the MC URL is generated in:
ParentObject.sierra_cloud_url().

For Sierra, the holding should not be included in the URL, so it should not be considered when generating the URL.

Valid Sierra URLs can be in the following formats:
```
http://localhost:8080/api/sierra/barcode/35102013950152?bib=1865833
http://localhost:8080/api/sierra/item/1599181?bib=1865833
http://localhost:8080/api/sierra/bib/394332
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1271

**Comment by sshetenhelm** [comment]
@martinlovell What's the best way to verify this?

**Comment by martinlovell** [comment]
You could give one of the records linked to Sierra a holding id and make sure it doesn't cause any issues.
(The holding id can be any number, since it should ignore it completely for those records.)

**Comment by sshetenhelm** [comment]
Looks good! Ready to close. Thank you!
