### ISSUE TITLE
Verify the MC URL for Voyager/ILS records

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2616]
For the Voyager source, the URL is generated based on the fields that have values.

The order of precedence is: 
```
barcode/bib
holding/bib
item/bib
bib
```
based on what fields have values.

If there is a value for item _and_ holding, but no barcode value, the MC url will use the value in holdingId and ignore the itemId.   

- [x] Holding and item should be reversed, so that if there is a value in holding and item, it will use the item value since that will pull in more data (volumeEnumeration).

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1272

**Comment by jpengst** [comment]
Deployed to Test v2.64.0

**Comment by martinlovell** [comment]
Test by putting in an item id and holding id, but no barcode.

Before it wouldn't get the item data in that case, but now it will
The only data we get from item is the VolumeEnumeration (from enum and chron), so you'd have to pick a bib/holding/item with has an enum/chron.

**Comment by sshetenhelm** [comment]
Looks good to me! Ready to close

Tested with:
https://metadata-api-test.library.yale.edu/metadatacloud/api/1.0.1/ils/item/10763792?bib=11167038&mediaType=json
