### ISSUE TITLE
Adjust Yale-only permission check for Cognito

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2617]
**Story**

"Logged-in" status is no longer sufficient to determine whether a user is a Yale user.  For YCO objects we need to check whether the user has a NetID.

**Acceptance**
- [x] For all YCO permission checks, ensure that the user is logged in _and_ has a NetID

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/934

**Comment by sshetenhelm** [comment]
Have inquired about test instance of Cognito, will update re: where to launch this work when I hear back.

**Comment by K8Sewell** [comment]
Taking back to In progress until Cognito login in ticket #2579 is resolved.

**Comment by mikeapp** [comment]
Not testable over VPN, but looks good.
