### ISSUE TITLE
Placeholder image for known missing images

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#262]
**STORY**
As we begin brining in more content, there will be a handful of parent works that don't have all child images available immediately.  We need a way to clearly identify images that we don't expect to display (even if temporarily)

**ACCEPTANCE**
- [ ] There is a clear visual placeholder when images are intentionally missing (so I can distinguish from true error states)
- [ ] We have a way to periodically scan for images in this state so we can obtain new access masters if needed

**NOTES**
There are a couple options for handling this:
1. At the S3 level, create a small placeholder image and copy it to have the expected OID of the images in question.  We'd then need to periodically scan S3 for images that have the size of the placeholder and figure out if we can find the appropriate master and proxy
2. At the cantaloup level, add a fallback to the delegate script that presents a placeholder if an image with the requested OID cannot be read from S3
3. At the manifest level, update the corresponding manifest canvases to point to a single placeholder image.  We could periodically scan manifests for canvases that point to the placeholder and take appropriate action.

**Comment by mikeapp** [comment]
I would like to participate in this discussion

**Comment by mark-dce** [comment]
Provisional strategy:
See if we can log image resolver failures to Honeybadger

[BONUS]
Can we communicate the error to UV in a more meaningful way (i.e. that doesn't give the auth red-herring error)

**Comment by mark-dce** [comment]
Mark to write up a revised ticket and have this group review - then we'll close this ticket.

**Comment by mark-dce** [comment]
See #295
