### ISSUE TITLE
Limit jobs to 3 retries

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2620]
**Story**

Continuous retries of failed jobs use system resources but rarely result in a successful outcome.

**Acceptance**
- [ ] Only retry failed jobs 3 times

**Comment by sshetenhelm** [comment]
Is there a time period we should space this out, as per Kait's question from yesterday? Like, try three times, but one minute apart? Five minutes apart?

**Comment by K8Sewell** [comment]
For delayed job `On error, the job is scheduled again in 5 seconds` but there is a way to override this.  What would be the desired frequency?  5 minutes sounds good to me but open to input.

**Comment by sshetenhelm** [comment]
Happy with 5 minutes unless @mikeapp has a reason it should be sooner.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1265 - for limiting to 3, will create another ticket for the time delay addition

**Comment by jpengst** [comment]
Deployed to Test v2.63.7

**Comment by K8Sewell** [comment]
Only makes it to 3 on Test then locks the job.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/e3f6b688-5e65-4eda-bb9d-0566c08dc15d)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bd325ffb-8003-425b-bc23-25d04573800f)

**Comment by sshetenhelm** [comment]
Looks good to me on UAT. Thank you!



![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/05f27704-0fd6-40c2-91c1-a6360967517f)
