### ISSUE TITLE
Complete IIIF Workshop - Discovery Team

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#263]
**STORY**
In order to help give everyone on the team common scaffolding and language around IIIF, we'd like everyone to work through the IIIF workshop at http://ronallo.com/iiif-workshop/

**ADDITIONAL BACKGROUND**
There's a number of other resources at https://iiif.io/apps-demos/ and https://github.com/IIIF/awesome-iiif#tutorials.  It would be useful to have a pair of team members review these resources and identify any others that are particularly valuable.

**ACCETPANCE**
- [ ] All team members have completed the tutorial
   - [x] Kevin Kochanski
   - [x] Bess Sadler
   - [x] Eric DeJesus
   - [x] Alisha Evans
   - [x] Frederick Rodriguez
   - [ ] Kait Sewell

**Comment by bess** [comment]
Many of us will be going through this together today at 3pm Eastern.

**Comment by bess** [comment]
@K8Sewell You're missing the second half of the tutorial, but I'm going to go ahead and close this ticket and we'll get you up to speed when you're back from sick leave.

**Comment by K8Sewell** [comment]
Catching up this morning
