### ISSUE TITLE
Ruby 3 - Upgrade Blacklight

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2631]
# Summary
Upgrade Blacklight to Ruby 3.2.2 and Rails 7 to match management

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/960

### Failing Specs (6 Local, 4 CI)

#### Local 
- [ ] rspec ./spec/system/date_slider_spec.rb:109 # Blacklight Range Limit is able to search with the slider
- [ ] rspec ./spec/system/show_page_spec.rb:182 # Show Page Universal Viewer sending child oid as a parameter uses child's page when oid is valid
- [ ] rspec ./spec/system/show_page_spec.rb:219 # Show Page with public works Metadata og tags are in the header of html
- [ ] rspec ./spec/system/show_page_spec.rb:243 # Show Page Metadata block is not displayed when empty
- [ ] rspec ./spec/system/view_fields_in_display_spec.rb:307 # View Search Results Within main document ASpace hierarchy graphical - [ ] display has an ellipsis instead of a full tree
- [ ] rspec ./spec/system/view_fields_in_display_spec.rb:313 # View Search Results Within main document ASpace hierarchy graphical display shows full tree on button click


#### CI
- [ ] rspec ./spec/system/date_slider_spec.rb:109 # Blacklight Range Limit is able to search with the slider
- [ ] rspec ./spec/system/show_page_spec.rb:219 # Show Page with public works Metadata og tags are in the header of html
- [ ] rspec ./spec/system/view_fields_in_display_spec.rb:307 # View Search Results Within main document ASpace hierarchy graphical display has an ellipsis instead of a full tree
- [ ] rspec ./spec/system/view_fields_in_display_spec.rb:313 # View Search Results Within main document ASpace hierarchy graphical display shows full tree on button click

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/960

**Comment by K8Sewell** [comment]
Waiting on test plan

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.61.0](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.61.0)

**Comment by sshetenhelm** [comment]
I think I've tested just about everything I could, on both Blacklight Test and Demo.

- Gallery View on both Test and Demo are missing thumbnails and have larger parent object title font than expected
- Demo showing permission request loop, but I know that is currently being worked on
- For logging in on Test, I received an authentication error (but I **could** log in on demo). 
- For Yale Community Only objects, I was unable to connect to TEST and DEMO when I was not on the VPN. We will not be able to test the Yale Community Only validation.

**Comment by K8Sewell** [comment]
* Will prep a ticket and get to work on fixing thumbnails in gallery view
* There's a PR to fix the request loop going through CI right now so will update when that's deployed - https://github.com/yalelibrary/yul-dc-blacklight/pull/980
* Here's a PR to fix the log in issue on Test - https://github.com/yalelibrary/yul-dc-blacklight/pull/981
* Is there something I can do to help with the YCO testing?

**Comment by K8Sewell** [comment]
Test environment's Blacklight is now live with release v1.61.4 and this is ready for testing.

**Comment by sshetenhelm** [comment]
1. Looks good on test, but could we please deploy fix to Demo as well? Also added that request in the gallery view ticket.
2. This still happens for me in Chrome (non-incognito browser and incognito browser) but not in Safari. Is this a "me" issue? 
3. Log in on test looks good!
4. As per Mike, not really a way to test; will make a note to be aware and test as soon as this gets deployed to Prod.

**Comment by sshetenhelm** [comment]
Gallery view on both looks good, confirmed that OwP "request loop" has been fixed, and log-in working as expected as well across TEST and DEMO. 

Ready to bump this upgrade into UAT! :)

**Comment by sshetenhelm** [comment]
Lauren and I both checked Blacklight, looks good on UAT! I think we are ready to close :)
