### ISSUE TITLE
OwP dropdown Bug

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2632]
## Summary  
I found a bug where Sysadmins could not see all Permission Sets in the PS dropdown.  
  
## Acceptance Criteria  
- [x] Sysadmins can view all Permission Sets

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1268

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.63.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.63.8)

**Comment by K8Sewell** [comment]
Able to see all permission sets even though I'm not an admin on them.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/615688fa-d371-42eb-92d1-f04be3f6e775)

**Comment by sshetenhelm** [comment]
Confirming that I can see all permissions sets even though not admin on all of them.

Looks good, ready to close. Thank you!
