### ISSUE TITLE
10/04 Deployment🍂

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2645]
Versions
Management: _no changes_
Blacklight: v1.60.85

Production

- [x] restart image servers
- [x] Blacklight

**Comment by bobrice** [comment]
All set.

Blacklight output: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/382/console
Imageserver output: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/383/console

**Comment by laurenb33** [comment]
Thanks, Bob! Looks great - ready to close!
