### ISSUE TITLE
Create page for Digital Collections Help Guide

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2646]
**Story**
We want to make a static Digital Collections Help Guide page on Blacklight with information for users. The page should include the same header and footer as the rest of DCS/Blacklight. 

Here is the page content with specifications added as comments (same doc as Tracy's comment below): 
[End-User-DCS-Documentation-with-specs.docx](https://github.com/yalelibrary/YUL-DC/files/12806497/End-User-DCS-Documentation-with-specs.docx)

**Acceptance**

- [x] Digital Collections Help Guide page created in Blacklight
- [x] Digital Collections Help Guide page has same header and footer as the rest of DCS/Blacklight
- [x] Digital Collections Help Guide page includes all text from linked document
- [x] Digital Collections Help Guide page is formatted as specified in linked document

**Comment by tmacmath** [comment]
Here is the link to the Digital Collections Help Guide page content with specifications:

https://yale.box.com/s/hiz7fld42py10su3oij77p3ruy0sol9t

**Comment by K8Sewell** [comment]
Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/936

**Comment by jpengst** [comment]
Deployed to Test v1.60.86

**Comment by sshetenhelm** [comment]
Font for body should be Mallory. I'm seeing a serif font on my end. @alisonclemens any other feedback re: Digital Collections Help Guide page?

**Comment by alisonclemens** [comment]
Only other comment from me is that the image captions (e.g., The download icon is a downward facing arrow over a horizontal bar located in the bottom left of the Universal Viewer.) are pretty tiny. I'm also not sure that the feedback footer screenshot needs to be quite so large, but I'm glad to leave that as-is if it looks okay to others

**Comment by sshetenhelm** [comment]
**Requested Adjustments:**

- [ ] Images and captions centered
- [ ] A margin of 3em above and below each image and caption
- [ ] A font size of 14px for the caption
- [ ] Mallory (regular) for the body text rather than Mallory-Medium. We are using Mallory-Medium primarily for metadata field labels. _(apologies for conflicting info on this!)_

**Comment by jpengst** [comment]
Revisions are ready for acceptance on UAT :)

**Comment by sshetenhelm** [comment]
Looks good to me! Thank you :)

**Comment by tmacmath** [comment]
Hi, I think there was some misunderstanding re: margins. We do not need to have a margin of 3em between the image and captions- there should be a margin *above* the image and *below* the caption to create some visual separation between the image and the rest of the body text. The image and caption should essentially be one "unit".

**Comment by tmacmath** [comment]
Screenshots attached: 

![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/b90cf384-4f0c-4c63-8460-42ae7508f71a)



![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/a1678296-13eb-4562-8312-34a4342890c5)
