### ISSUE TITLE
Link to Digital Collections Help Guide from home page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2648]
After page is created via #2646 

**Story**
We want to link to the Digital Collections help guide page from the DCS home page. This link should be in a content "block" that is below the Advanced Search link and to the right of the 'About' content. The content block:

- Should have an h2 header that states "Need help?"
- Should have text below the header that reads "For help using this site, please see the Digital Collections Help Guide."
- Should link to the static Digital Collections Help Guide from the phrase "Digital Collections Help Guide."
- Should utilize the following formatting:
  - Text - color: white, size: small, font-family: MalloryMP-Medium, left-aligned
  - Link - color: white, text-decoration: underline
  -  Content block - two columns within a container and row: the left column is col-7; the right is col-5 with a 3% margin at the top of each column.

Code is provided in the first comment.
Screenshot:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/085da4d6-8a0a-4e41-9226-5b3b5f3778df)

**Acceptance**

- [x] Content block added below 'Advanced Search' link and to the right of 'About' content 
- [x] Content block includes h2 header at top that states "Need help?"
  - [x] Header utilizes formatting described in ticket
- [x] Under header, content block includes the following text: "For help using this site, please see the Digital Collections Help Guide." 
  - [x] Text utilizes formatting described in ticket
- [x] Link to Digital Collections Help Guide page from the phrase "Digital Collections Help Guide."

**Comment by tmacmath** [comment]
- Font color: white;
- Font size is small 
- Font-family: MalloryMP-Medium (already being used)
- Link color should be white with text-decoration: underline. 
- Text should be left-aligned. 
- I used two columns within a container and row: the left column is col-7; the right is col-5 with a 3% margin at the top of each column. 

Code is here (includes the copy): 

```html

<div class="container">
  <div class="row">
	<div class="col-7" style="margin-top: 3%;">
	<h2 style="font-family: YaleNew-Roman;">About</h2>
		<p style="font-size: small; text-align: left; margin-top: 2%;">This site provides access to millions of digitized works and images. New materials are added regularly. There are Yale Library collections that are not available on this site. More information on additional collections can be found <a href="" style="color: white;text-decoration: underline;">here</a>.</p>
	</div>
	<div class="col-5" style="margin-top: 3%;">
	<h2 style="font-family: YaleNew-Roman;">Need help?</h2>
		<p style="font-size: small; text-align: left; margin-top: 3%;">For help using this site, please see the <a href="" style="color: white;text-decoration: underline;">Digital Collections help guide</a>.</p>
	</div>
  </div>
</div>

```

**Comment by tmacmath** [comment]
Here is a screenshot of what it looks like mocked up in the browser: 



![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/57d9df8a-e8e9-478d-8784-822f403a1dbe)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/938

**Comment by jpengst** [comment]
Deployed to Test v1.60.86

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/939

**Comment by jpengst** [comment]
Deployed to Test v1.60.87

**Comment by sshetenhelm** [comment]
Looks good to me on Test!

**Comment by sshetenhelm** [comment]
Looks good on UAT!
