### ISSUE TITLE
Issue Downloading Large TIFF on Blacklight

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2649]
**Story**:

A patron tried to download a large TIFF (1.5 gb) on Blacklight and it didn't work. The new tab that's supposed to kick off the  download opens with a 504 Gateway Time-out error message and the download doesn't start. I was able to successfully download the TIFF from MGMT PROD and smaller TIFFs from other related children on Blacklight. 

**Potentially the largest child?** 
Child [16865345](https://collections.library.yale.edu/catalog/16865295?child_oid=16865345), 34259 x 27090
**(Area of 928,076,310 pixels)**

Current Management child with greatest width: 
Child [32335548](https://collections.library.yale.edu/catalog/32335537?child_oid=32335548), 104872 x 6863
(Area of 719,736,536 pixels)

Current Management child with greatest height: 
Child [32246964](https://collections.library.yale.edu/catalog/32246963?child_oid=32246964), 8197 x 98704
(Area of 809,076,688 pixels)

We likely need to increase the image resources to accommodate images with an area of up to 950k pixels, if possible. I think we are in the 540ks (see link in comment).

**Example Object**:
https://collections.library.yale.edu/catalog/15486069?child_oid=15498387

**Acceptance**:

- [ ] Image resources updated to enable downloads of images with areas up to 950k pixels **(is this possible?)**
- [ ] Large TIFFs can successfully download from Blacklight

**Comment by mikeapp** [comment]
Both the TIF and JPEG downloads time out for me.
I think we have a hard limit on the timeout on the gateway, but DevOps would need to check.

For the JPEG the cause is probably the processing time required for Cantaloupe.
For the TIFF the cause is probably the time required to read the item from S3 and relay the bytes to the browser.

**Comment by sshetenhelm** [comment]
As per Keith in chat, 
Max Connection idle timeout 4000
Max HTTP client keepalive duration 604800 seconds

**Comment by mikeapp** [comment]
Current timeout is 60s.  This is "until first byte" is sent from the server.   For the TIFFs, my recollection is that the Blacklight code should be streaming data to the client (i.e., _not_ downloading the whole TIFF first).  We should confirm.

**Comment by sshetenhelm** [comment]
As per Martin, "Could it be something with nginx and rails?"

**Comment by martinlovell** [comment]
Based on https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_buffer_response, it looks like nginx buffering is off by default.
Their example shows some ruby code calling "flush()" on the output stream. Maybe that would help.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1033

**Comment by sshetenhelm** [comment]
"There was an error downloading the file. Please try again later."

**Comment by jpengst** [comment]
revert PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1034

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/1035 is deployed to test

I was able to download: 
https://collections.library.yale.edu/catalog/11205269?child_oid=11208305 (467M) and 
https://collections.library.yale.edu/catalog/16719894?child_oid=16719912 (500M) 174,694,176 pixels

Is there anything bigger in test?

**Comment by sshetenhelm** [comment]
I use https://collections-test.library.yale.edu/catalog/2007670?child_oid=11872498 but I think it worked for me today because I staged it yesterday.

https://collections-test.library.yale.edu/catalog/16173726?child_oid=16173880 has an area of 538,200,000 pixels 
https://collections-test.library.yale.edu/catalog/15234629?child_oid=16595618 has an area of 430,970,672 pixels

**Comment by laurenb33** [comment]
Downloading the TIFF for https://collections-test.library.yale.edu/catalog/2007670?child_oid=11872498 just worked for me!

**Comment by jpengst** [comment]
Deployed to Test v1.63.2

**Comment by jpengst** [comment]
Deployed to UAT v1.63.2

**Comment by sshetenhelm** [comment]
Successfully downloaded 2GB of scrolly goodness on UAT. High fives all around!

Ready to close.

**Comment by laurenb33** [comment]
> Successfully downloaded 2GB of scrolly goodness on UAT. High fives all around!
> 
> Ready to close.

YES! I was able to download https://collections-test.library.yale.edu/catalog/15234629?child_oid=16595618 in UAT - big ups to the team! 🎆⭐🎆⭐🎆⭐
