### ISSUE TITLE
Fix readme link to fixtures in iiif-manifest repo

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#265]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/3064318/85425032-49dc5e00-b53e-11ea-9ace-cac7e98bdae8.png">

**ACCEPTANCE**
- [ ] Links in the readme are valid
- [ ] [BONUS] find a tool that we can use to scan documentation for similar invalid links

**Comment by JzGo** [comment]
Open PR for pointing the link to yul-dc-fixture-manifests in the readme: https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/12

Initial search of tools for finding broken links turned up a bunch of crawler type things that downloaded html and parsed it which I wasn't to thrilled about so I turned my attention to cli based things.

I found this node based tool that works specifically for markdown: https://github.com/tcort/markdown-link-check

Results from README on master:
![Screen Shot 2020-06-24 at 10.12.37 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/1bb4bbe9-066c-4898-8223-f60017dd2b32)

Results from README from PR:
![Screen Shot 2020-06-24 at 10.15.00 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/b4e9bbca-b2f3-418c-955f-52f69ec71b92)
