### ISSUE TITLE
DISCUSS: OwP, how will user know which terms apply?

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2651]
**Story**

If we ever have multiple Permission Sets, how will the user know which T&Cs apply if we don't display them during each request? 

Instead of skipping the T&Cs if the user has agreed to them, should we still display them in some way?

**Acceptance**

- [x] Decide whether or not to display T&C with every request
- [x] Decide if T&C will also be displayed in some way elsewhere
- [x] Make ticket then close this

**Comment by sshetenhelm** [comment]
1. So far general consensus seems to be that we will display the Terms & Conditions with every request. This will ensure users are fully aware of the fact that T&C exist for an object. 
 
2. It would be great to embed a link somewhere to the T&C for an object. Would it be possible to either:

- Add a link from the bottom of the Universal Viewer, such as [Princeton](https://findingaids.princeton.edu/catalog/C1372_c97298-89800?onlineToggle=false) does with the link to Rights & Permissions? 
- Add a link from the Access value in the UV 'More Information' pane? (ex. The value for Access would be Open with Permission, and clicking on it takes the user to the Terms & Conditions, either as a new tab or pop-up or something.)

**Comment by sshetenhelm** [comment]
Kait has suggested adding the T&C information on the individual Parent Object page under the "Access and Usage Rights" section. We could either display them directly there (depending on length, may not be best idea) or link out. This would use similar logic as what is used in the archival tree.

If we add anything to the IIIF manifest, we would need to regenerate the manifests every time the T&C are updated, which would be very cumbersome for collections such as Kissinger.

**Comment by sshetenhelm** [comment]
Created #2745 for work in Blacklight

Ready to close
