### ISSUE TITLE
OwP: Management API to return user permissions data

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2652]
**Story**

Blacklight needs to be able to retrieve permissions information for a user from Management via an API call.

**Acceptance**

- [x] Create an API that returns data for a user by their `sub` value
- [x] API should return:
   - [x] a timestamp, so that Blacklight can expire stale information
   - [x] user information, currently only the `sub`
   - [x] a list of PermissionSetTerm IDs that have been accepted
   - [x] information about all PermissionRequests
      - [x] `oid`
      - [x] `permission_set`
      - [x] `permission_set_terms`
      - [x] `request_date`
      - [x] `request_status`
      - [x] `access_until`
    - [x] return empty arrays if no permission set terms or permissions
 - [x] return 404 if no permission_set_user exists for the `sub`  

```
{
    "timestamp": "20230215T16:22:43Z",           // Current time, gives Blacklight the option to
                                                // fetch new permissions when expired
    "user": {
        "sub": "abc..123",                      // Use the sub and not the ID for API calls
    },
    "permission_set_terms_agreed": [            // Shortcut terms checks if already agreed
        3,                                      // PermissionSetTerm IDs
        54,
        110
    ],
    "permissions": [                   
        {
            "oid": 203123,
            "permission_set": 12,               // Validate that OID is still in this set
            "permission_set_terms": 3,                         // Validate Terms are in agreed list above
            "request_status": true              // true == approved
            "request_date": "20230215T09:30:00Z"  // created_at
            "access_until": "20231115T16:22:43Z"     // Validate that the permission has not expired
        },
        {
            "oid": 434433,
            "permission_set": 85,
            "permission_set_terms": 54,
            "request_date": "20230215T09:30:00Z"
            "request_status": null
        },
        {
            "oid": 434433,
            "permission_set": 85,
            "permission_set_terms": 54,
            "request_date": "20230215T09:30:00Z"
            "request_status": false
        }
    ]
}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1275

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.1)
