### ISSUE TITLE
OwP: Request Page

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2655]
**Story**

For OwP items the user should be able to submit a request through Blacklight.

**Acceptance**
- [x] Use the same layout described in the T&Cs issue (no search bar, no facets)
- [x] Display summary metadata for the parent object, with these fields (note these do not match the graphic):
  - [x] Title
  - [x] Creator
  - [x] Published/Created
  - [x] Call Number
  - [x] Container/Volume
  - [x] Image Count
  - [x] Found in [breadcrumbs] 
- [x] After the object metadata display a header "Request Information"
- [x] Under this header, display the request form:
   - [x] "User ID:" / username from Cognito as text
   - [x] "Email:"  / email address from Cognito as text
   - [x] "Full name:" / text input field - REQUIRED
   - [x] "Reason for request:" / text area, at least three lines high - REQUIRED
   - [x]  Form actions:
     - [x] "Cancel" returns to the parent object page
     - [x] "Submit request" 
        - [x] causes the request to be submitted to Management
        - [x] if submission is successful display the confirmation page #2656 
        - [x] if submission fails, show the page again, with a flash message indicating the error
- [x] Add  `form` href link to signed in, without OwP access showpage. It should link to the T&Cs or request page

![Image](https://github.com/yalelibrary/YUL-DC/assets/1987952/8dc8bdba-eabf-4d87-b2c6-71734d608142)

**Comment by jpengst** [comment]
Should this page be on a new route? Such as something like `/catalog/oid/request` or should this form be on the showpage under the owp_restriction_message `"You are currently logged in to your account. However, you do not have permission to view this folder. If you would like to request permission, please fill out this form."`?

**Comment by jpengst** [comment]
PR's: https://github.com/yalelibrary/yul-dc-management/pull/1293  
https://github.com/yalelibrary/yul-dc-blacklight/pull/948

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.65.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.65.1) and branch [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by K8Sewell** [comment]
### Testing on Demo

Request Form

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/e7a1f6f3-8a1c-4ee8-848c-da023e82765c)


Required fields provide validation

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bb95685b-c0b6-42fe-87e0-1d5cecd39a68)



Redirects to confirmation page

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/c4d456c2-aaa0-4d81-8bf2-014be42d711d)

**Comment by sshetenhelm** [comment]
- Confirmed “Open with Permission” language exists for users that are not logged in, and that link to log in works. 
- Confirmed that, after logging in, I was able to click on, fill out, and submit form.
- Confirmed that I was unable to submit form without filling out Full Name and Reason.
- Confirmed that 'Cancel' takes me back to individual parent object display page
- Confirmed that, after filling out form and pressing “return” link, I see a message in light blue saying my request was submitted. 
- Confirmed that ‘Permission Request’ is shown in Management in Permission Requests table.

Unless there is something else to test, I think we might be ready to close this one?
