### ISSUE TITLE
Index ProvenanceUncontrolled in SOLR

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2658]
**Story**
ProvenanceUncontrolled is a field that stakeholders have requested be included in DCS. ProvenanceUncontrolled is already mapped in Metadata Cloud.

We need to index ProvenanceUncontrolled in SOLR before #2609.

ProvenanceUncontrolled MARC:
Bib:
561a3

Holding:
561
541ad3

ProvenanceUncontrolled Aspace:
Field Type: notes
Note Types: custodhistacqinfo
Strip Tags: True
Join Strings: ,

SAMPLE OBJECTS
TEST - https://collections-test.library.yale.edu/catalog/800045169 (ILS)
https://collections-test.library.yale.edu/catalog/800052182 (Aspace)

UAT - https://collections-uat.library.yale.edu/catalog/900102435 (ILS)
https://collections-uat.library.yale.edu/catalog/900148576 (Aspace)

PROD - https://collections.library.yale.edu/catalog/33071427 (ILS)
https://collections.library.yale.edu/catalog/33071633 (Aspace)

**Acceptance**
- [x] ProvenanceUncontrolled is indexed in SOLR

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1279

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.2)

**Comment by K8Sewell** [comment]
Indexed field after update - will promote to UAT



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/90281c58-8ea3-4f63-8270-38d8fa72f985)

**Comment by sshetenhelm** [comment]
Looks good on UAT, thank you so much!

Ready to close :)
