### ISSUE TITLE
Validate Captions display in UV

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#266]
**STORY**
Some works in the DL include page-level captions or annotations.  As a researcher, I'd like to be able to view this information while I'm viewing the corresponding image or page.

**ACCEPTANCE**
- [x] Identify sample works that should have page-level captions 
- [x] Ensure captions exist in the manifest fixtures
- [x] Ensure captions display in Universal Viewer

**Comment by dl-maura** [comment]
[https://app.zenhub.com/files/242185115/c1a8d8c0-576e-4cdf-a494-f5d047baa2a1/download](https://app.zenhub.com/files/242185115/c1a8d8c0-576e-4cdf-a494-f5d047baa2a1/download)

Not sure if this is how you want them displayed but the data is there. See OID 16797069 where the caption is cut off and I don't see a way to display it fully outside of hover (but I might be missing it, I am not a IIIF expert).
