### ISSUE TITLE
Omniauth Callbacks Specs

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2660]
## Summary  
omniuath_callbacks_controller_spec.rb needs to be updated to pass with the Cognito openid_connect parameters.   
  
## Acceptance Criteria  
- [x] omniauth_callbacks specs passing with cognito config

**Comment by K8Sewell** [comment]
PR ready for review: https://github.com/yalelibrary/yul-dc-blacklight/pull/962

**Comment by K8Sewell** [comment]
Just specs, nothing to really see here.
