### ISSUE TITLE
Add 'Preservica Representation Type' to 'Editing Parent Object' page in MGMT

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2661]
**Story**
A user may want to update the Preservica information for a single object in DCS. The 'Editing Parent Object' page in Management includes Digital Object Source and Preservica URI as editable fields. However, the required field 'Preservica Representation Type' is missing from this page. 

We would like to add 'Preservica Representation Type' to the 'Editing Parent Object' page in Management.

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/1bb00a8e-637a-44da-b616-1a42552b97f2)

**Acceptance**

- [x] Add label 'Preservica Representation Type' to the Editing Parent Object page, under the 'Digital Object Identifiers' section, after 'Preservica URI'
- [x] Under label, add drop-down menu with value selection options of 'Preservation' and 'Access'

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1288

**Comment by K8Sewell** [comment]
Update request on PR

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.6)

**Comment by K8Sewell** [comment]
Promoting to UAT to be able to test with Preservica objects.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1290

Will also make a ticket to add some validation to this field.

**Comment by K8Sewell** [comment]
Looking good on Test.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/e82ead1b-c13d-444b-84a4-b68d204de57e)

**Comment by sshetenhelm** [comment]
Ready to close! It worked :)
