### ISSUE TITLE
Add bookmark checkbox to Blacklight parent object display page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2663]
**Story**
Users should be able to bookmark an object in DCS from the parent object display page. As such, we need to add the bookmark checkbox to the Blacklight parent object display page. 

- We would like to add the box on the same horizontal line as the parent object title, but aligned to the right. 

**Visual**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/83514d07-b949-48bb-86f1-b6cd9c76ab74)

**Acceptance**
- [x] Bookmark checkbox is added to parent object display page in Blacklight
- [x] Bookmark checkbox is in same line as object title
- [x] Bookmark checkbox is aligned right, in alignment with the right edge of the Universal Viewer
- [x] Bookmark checkbox adds parent object to ‘Bookmarks’ list when checked
- [x] Bookmark checkbox removes parent object from ‘Bookmarks’ list when unchecked
- [x] REMOVE bookmark checkbox from bottom of page

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/964

**Comment by K8Sewell** [comment]
Looking ok on Demo on the show page for the object but the gallery view is gonna need a little TLC before this branch is ready.

https://collections-demo.library.yale.edu/catalog/17124881

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/0ce24ef2-f936-41b7-b3ab-23f51fd243e8)

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/a3361be3-9d27-4baa-ab03-8a72fe7d9079)





https://collections-demo.library.yale.edu/catalog?fulltext_search=1&q=&search_field=all_fields&view=gallery

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/666d48b9-8cdb-4d3a-9e47-bc158793b7f3)


A mobile first wireframe for the gallery search view would be super helpful.

**Comment by sshetenhelm** [comment]
Looks good on Demo. I remember this gallery view issue -- if I can't find a previous ticket with wireframes, will create new one.

Ready to close. Thank you!
