### ISSUE TITLE
10/25 Deployment 🧟‍♀️

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2665]
**Versions**
Management: _no changes_
Blacklight: _no changes_
Metadata Cloud: v1.3.0

**Production**

- [x]  restart image servers
- [x] Metadata Cloud

**Comment by bobrice** [comment]
All set.
Image server recycle output.
https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/386/
Metadatacloud deploy output:
https://cm-prd.library.yale.edu/job/MetaDataCloud/54/
