### ISSUE TITLE
Update Preservica TEST integrations with new URL

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2668]
**Story**
On **November 15th**, Preservica TEST will be released with a new URL. The new URL is http://testpreservica.library.yale.edu/

We need to update our TEST, UAT, and DEMO instances to work with the new URL. We're pretty sure this requires a variable to be updated in AWS parameter store, followed by a management redeploy on each environment.

**Acceptance**
- [x] AWS parameter store updated
  - [x] DEMO
  - [x] TEST
  - [x] UAT 
- [x] TEST Management redeployed
- [x] UAT Management redeployed
- [x] DEMO Management redeployed

**Comment by mikeapp** [comment]
Looks good in the task definitions in AWS.

**Comment by sshetenhelm** [comment]
Confirmed it works in Demo at least!

I'm comfortable closing.
