### ISSUE TITLE
11/8 Deployment 🗳️

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2669]
**Versions**
Management: _no changes_
Blacklight: _no changes_
Metadata Cloud: 1.3.2

**Production**

- [x] restart image servers
- [x] Metadata Cloud

**Comment by bobrice** [comment]
All set. 

Image server restart: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/390/

Metadatacloud deploy: https://cm-prd.library.yale.edu/job/MetaDataCloud/55/console

**Comment by laurenb33** [comment]
Thanks, Bob! 

Ready to close 🫡
