### ISSUE TITLE
Ensure manifests can be used in Mirador

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#267]
**STORY**
As a researcher, I'd like to be able to compare illustrations from works at the Beinecke ( such as https://collections-demo.curationexperts.com/catalog/16700283 ) against illustrations in works held by other institutions ( such as https://purl.stanford.edu/qm670kv1873 )

**ACCEPTANCE**
- [x] Manifests load successfully in a Mirador viewer such as the one at https://projectmirador.org/demo/
- [ ] [BONUS] we have a way of automating this type of testing

**Comment by dl-maura** [comment]
British Art Mirador: http://mirador.britishart.yale.edu/

**Comment by alishaevn** [comment]
Our current manifests will work with a Mirador viewer. 

# Testing Instructions
- Do a search on the collections demo site and choose one of the items
- Right click the "Manifest Link" link underneath the "Links" heading (right side of the page on desktop)
- Select "copy link address"

### British Art
- Go to http://mirador.britishart.yale.edu/
- Click the "add item" button
- Paste the link where it says "Add new object from URL:"
- Click "Load"
- Select the loaded item
- View the item in the mirador viewer

### Project Mirador
- Go to https://projectmirador.org/demo/
- Hover over the icon that looks like 4 squares and a down arrow
- Select "replace object"
- Paste the link where it says "Add new object from URL:"
- Click "Load"
- Select the loaded item
- View the item in the mirador viewer

**Comment by alishaevn** [comment]
### British Art Demo
![british.gif](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/609df44e-919c-4f75-9c21-8dc4e217ae8b)

**Comment by alishaevn** [comment]
### Project Mirador Demo
![project.gif](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/64d7f438-51ee-4753-a62c-84b6eef53b4c)
