### ISSUE TITLE
[BUG] 'Export All Parents by Admin Set' batch process header/values misaligned

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2670]
**Story**
When performing an 'Export All Parent Objects by Admin Set' batch process in Management UAT (2.64.2), the spreadsheet is misaligned starting with column P, 'Last Sierra update.' This does not happen in PROD (currently showing 2.63.3). 

Column P, 'last_sierra_update,' has data that matches the last aspace sync of an object, and column Q, last_aspace_update, is empty, even when objects have been synced with aspace.

We would like the data filled in the table to correspond with the appropriate header.

'Export Parent Metadata' batch process appears to be working correctly.

**Acceptance**

- [x] last_sierra_update displays data for last Sierra sync, and remains empty if object has not synced with Sierra
- [x] last_aspace_update displays data for last aspace sync
- [x] All remaining columns/values display as expected

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1286

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.5)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you, ready to close.
