### ISSUE TITLE
Management Prep for BL API calls

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2671]
## Summary  
We need to skip user authentication for `api/permission_sets_controller.rb`  
Also need to index OwP objects so that BL knows about the OwP visibility.  
  
## Acceptance Criteria  
- [x] Add `skip_before_action :authenticate_user!` in `api/permission_sets_controller.rb`  
- [x] Add 'Open with Permission' to `should_index?` in `parent_object.rb`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1284

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.5)

**Comment by K8Sewell** [comment]
No real way to test without Blacklight portion built out.  Will promote to UAT as nothing appears broken with Test.
