### ISSUE TITLE
Inaccurate characters showing in .csv exports in Management

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2673]
**Story**
When a user creates an export in Management, metadata from oids with diacritic characters are generating inaccurately in .csv exports. Here is an example of a caption from management vs. the exported .csv for OID 16165882:

- Caption in Management: établis pour sècher les bateaus [sic] et les filets dans le Détroit de Behring
- Exported .csv caption: Ã©tablis pour sÃ¨cher les bateaus [sic] et les filets dans le DÃ©troit de Behring

**Acceptance:**
- [ ] .csv exported from Management shows the accurate diacritics

**Comment by sshetenhelm** [comment]
Question for those more knowledgable: Is this a Management issue, or is this an excel/csv issue?

**Comment by mikeapp** [comment]
Looking at the downloaded CSV on the command line and in VSCode I see:
`Établis pour sécher les bateaus [sic] et les filets dans le Détroit de Behring`

Maybe Excel is handling it properly?

**Comment by sshetenhelm** [comment]
Someone mentioned in a workshop I was in that excel doesn't play well with UTF-8 -- this post seems to confirm that: https://answers.microsoft.com/en-us/msoffice/forum/all/opening-utf-8-encoded-csv-in-excel-that-appears-ok/94e1a881-b184-449d-8a59-27997d5e97ef

So this is an issue of either (a) changing the export data type or (b) user education re: excel settings or recommending another spreadsheet application?

**Comment by laurenb33** [comment]
Hi all! I figured out a fix:

1. Open .csv in Notepad 
2. Save as file as .txt file and select UTF BOM in drop down menu to the right
3. Open the file in excel 
4. Save as a .csv 

I tried this and it worked! Shall I share this with Stephen and create some documentation for others about exporting with diacritics?

**Comment by laurenb33** [comment]
So, I definitely took the more challenging way to figure it out above 😆
I just followed the instructions in the link that Summer provided and that worked as well. I think that will be the better route because you only have to use excel.

1. *Open Excel first*, don't double-click the CSV file.
2. Go to the *Data* tab on the ribbon.
3. Click *From Text/CSV*.
4. Select your CSV file and click *Import*.
5. In the preview window, if it looks incorrect, select *65001: Unicode (UTF-8)* from the dropdown menu for the file origin.
6. Click *Load*.

**Comment by laurenb33** [comment]
I communicated this with Stephen - he said that he will try it next time he has an export with diacritics.
