### ISSUE TITLE
Accommodate strings or integers for Bib/Holding/Item Ids from Metadata Cloud

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2674]
Metadata cloud is not consistent with Item Id type in the JSON.
ILS uses integers and Sierra uses strings.

Sierra updates with item ids are failing.

- [x] Update both ILS and Sierra to accept both integers and strings in the JSON from Metadata Cloud

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1287

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.64.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.5)

**Comment by K8Sewell** [comment]
Tried to recreate the parent object from the Sierra ticket [16153247](https://collections-test.library.yale.edu/management/parent_objects/16153247) but it didn't pull the child objects so I'm going to promote this to UAT so it can be tested with the PO on UAT that is a more complete record.

**Comment by sshetenhelm** [comment]
Looks good in UAT, thank you! 

Ready to close :)
