### ISSUE TITLE
Add five columns to ‘Create Parent Objects’ batch process

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2675]
**Story** 
Since we are now able to create parents with Preservica URIs, we need to **add five columns** to the _Create Parent Objects_ batch process template. By including these fields, staff will not have to navigate to an individual parent object's page to make additional edits after an object has been created. These are for fields that **already exist in Management and are currently included in the _Update Parent Objects_ batch process**, but not the _Create_ process. The fields are as follows: 

- digitization_note	
- digitization_funding_source	
- rights_statement	
- viewing_direction	
- display_layout 

We would like the five fields to start in the column immediately **after the extent_of_digitization column** and be provided in the order listed in the ticket. 

We would like the five fields to follow the **same specifications and rules** as in the _Update Parent Objects_ batch process.

**Acceptance**

- [x] `digitization_note` column added to Create Parent Object batch process template
- [x] `digitization_funding_source` added to Create Parent Object batch process template
- [x] `rights_statement` added to Create Parent Object batch process template
- [x] `viewing_direction` added to Create Parent Object batch process template
- [x] `display_layout` added to Create Parent Object batch process template
- [x] All five fields follow same rules/specifications for identical columns in _Update Parent Objects_ batch process template
- [x] All five fields successfully get added when a parent object is created via the batch process

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1302

**Comment by sshetenhelm** [comment]
Looks good on Test!

**Comment by jpengst** [comment]
Deployed to UAT v2.65.6

**Comment by sshetenhelm** [comment]
Looks good on UAT! Ready to close. Thank you! :)
