### ISSUE TITLE
11/15 Deployment🥒

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2676]
**Versions**
Management: 2.64.5
Blacklight: _no changes_

**Production**
- [x]  restart image servers
- [x] Management

**Comment by bobrice** [comment]
All set.

MGMT deploy: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/391/

ImageServer restart: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/392/
