### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2677]
# Summary
Added a new drop down to parent edit page.  Preservica Representation Type should have some validation on the field but it will require the update of a number of specs.

# Engineering Notes
Sample validation:
```
  validates :preservica_representation_type, format: { with: /\A(Preservation|Access)/, message: "Preservica representation type can't be None when Digital Object Source is Preservica" }, if: proc { digital_object_source == "Preservica" }
```
Sample spec:
```
      it 'validates preservica representation type based on digital object source' do
        select('Preservica')
        fill_in('Preservica uri', with: "/preservica_uri")
        click_on("Create Parent object")
        expect(page).to have_content "Preservica representation type can't be None when Digital Object Source is Preservica"
      end
```
Specs it will break:

- [x] rspec ./spec/system/user_spec.rb:111
- [x] rspec ./spec/system/parent_object_spec.rb:134 # ParentObjects creating a new ParentObject based on oid setting non-required values validates preservica uri format
- [x] rspec ./spec/models/preservica/preservica_sync_spec.rb:261 # Preservica::PreservicaObject user with permission can throw an error if parent object does not have a preservica representation type
- [x] rspec ./spec/system/batch_process_spec.rb:235 # BatchProcess when uploading a csv outputting csv uploads a CSV of parent oids in order to create export of child objects oids and orders
- [x] rspec ./spec/system/batch_process_spec.rb:217 # BatchProcess when uploading a csv outputting csv uploads a CSV of admin set in order to create export of parent object oids
- [x] rspec ./spec/system/batch_process_spec.rb:204 # BatchProcess when uploading a csv outputting csv uploads a CSV of parent objects in order to create export of parent objects metadata fails 2005512 row due to admin set permissions
- [x] rspec ./spec/system/batch_process_spec.rb:190 # BatchProcess when uploading a csv outputting csv uploads a CSV of parent objects in order to create export of parent objects metadata
- [x] rspec ./spec/system/batch_process_spec.rb:285 # BatchProcess when uploading a csv outputting csv round-tripping csv can create the output csv from a handmade csv
- [x] rspec ./spec/system/batch_process_spec.rb:275 # BatchProcess when uploading a csv outputting csv round-tripping csv can create the output csv from a csv that has been generated from the application
- [x] rspec ./spec/datatables/parent_object_datatable_spec.rb:13 # ParentObjectDatatable can handle a parent object

**Comment by jpengst** [comment]
Looks good on Test":  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/3a5d26fe-2027-4d83-bec4-d3d0b8b20e28)

**Comment by sshetenhelm** [comment]
When running an ‘update parents object’ batch process (Batch Process 1727) in UAT to change the Visibility of certain parent oids, the batch process was able to complete but displayed a “Skipped Import” status message for every parent object that did not have Preservica information.

The status message and note should not display for any objects without Preservica information if there is no data provided on the batch process template spreadsheet. Staff should be able to make non-Preservica updates to objects without Preservica information without getting an error warning. 

https://collections-uat.library.yale.edu/management/batch_processes/1727

**Comment by sshetenhelm** [comment]
[Batch process 773 in TEST ](https://collections-test.library.yale.edu/management/batch_processes/773) successfully processed without "skipped import" status message. So did 774 and 775.

**Comment by jpengst** [comment]
Thanks Summer! I successfully deployed that branch to UAT if we want to test further. Otherwise, I think this PR is good to go!  
https://github.com/yalelibrary/yul-dc-management/pull/1304

**Comment by sshetenhelm** [comment]
[Batch process 1738 in UAT](https://collections-uat.library.yale.edu/management/batch_processes/1738) completed successfully with no errors :)

**Comment by jpengst** [comment]
Deployed to UAT v2.65.6

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you :) 

Ready to close.
