### ISSUE TITLE
11/22 Deployment 🦃

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2678]
**Versions:**
Management: 2.64.8
Blacklight: 1.60.91

**Production**
- [x] restart image servers
- [x] Management
- [x] Blacklight

**Comment by bobrice** [comment]
Unleashed!  Beware the Kraken!

Mgmt: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/393/
Blacklight: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/394/
ImageServers: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/395/

**Comment by laurenb33** [comment]
Thanks, Bob! We will watch out for sure :) ready to close.

**Comment by laurenb33** [comment]
MGMT failed and is in progress for the second deploy, so the Kraken is not ready to close yet.

**Comment by laurenb33** [comment]
It is a success! Ready to close now.

**Comment by DraxIndustries79** [comment]
jk

**Comment by laurenb33** [comment]
All set now for real! Ready to close :)

**Comment by laurenb33** [comment]
Checked with Bob - Jenkins and the DWS parameter store and they are both showing that the correct version of Blacklight is listed (1.60.9). Mike suggested that I make a separate ticket for it: https://github.com/yalelibrary/YUL-DC/issues/2680
