### ISSUE TITLE
SPIKE: can we disable database authentication?

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#268]
**QUESTION**
Now that we have CAS enabled, do we need to continue supporting basic database authentication.

**ACCETPANCE**
- [ ] Determine whether **production** requirements can be met without database authentication
- [x] Determine whether **local testing** requirements can be met without database authentication
- [x] Determine whether **CI** requirements can be met without database authentication
- [x] Determine whether **development** requirements can be met without database authentication
- [ ] Recommendation for whether to proceed or not (and any corresponding tickets)

**Comment by mark-dce** [comment]
If it's useful for keeping dev/prod parity, it also appears there might be an CAS implementation on docker that we could use in development and test environments
https://apereo.github.io/cas/5.1.x/installation/Docker-Installation.html

**Comment by K8Sewell** [comment]
Research so far - 
Determine whether local testing requirements can be met without database authentication
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d93009e3-2276-4028-a731-b4654ff02b61)

Determine whether CI requirements can be met without database authentication
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/8db784f3-a5ec-4906-8202-dc4f4c88e5a9)

Determine whether development requirements can be met without database authentication
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3208c9c4-8074-4597-8490-ce5794d13d74)
