### ISSUE TITLE
11/29 Deployment✉️

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2681]
**Versions:**
Management: _no changes_
Blacklight: _no changes_

**Production**
- [x] restart image servers
- [x] SOLR reset
- [x] Postgres reset

**Comment by bobrice** [comment]
PSQL and SOLR have been restarted.

Image server restart: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/398/

**Comment by laurenb33** [comment]
Thanks, Bob! All set to close.
