### ISSUE TITLE
Change Download Tiff job priority

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2682]
**Story**
Because of the large amount of jobs in DCS, TIFF downloads are not resolving for users. As such, we would like to change the prioritization of TIFF download jobs to occur before other jobs in DCS.

**Acceptance**

- [x] Update upload tiff to s3 job to occur before other jobs in DCS
- [x] Confirm that TIFF downloads occur in a timely manner

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1292

**Comment by jpengst** [comment]
Deployed to Test v2.65.0
