### ISSUE TITLE
SPIKE: Identify code-coverage requirements for discovery application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#269]
**ACCEPTANCE**
- [x] The team has a working definition for the acceptable code coverage
- [x] The team has a working definition of any other code quality standards they wish to meet
- [x] The standards are documented in the wiki or similar location

**Comment by bess** [comment]
Currently code coverage for this app is ~84%. I would prefer to see it in the 95% - 100% range, but I'm happy to say that we've got measurement in place now, and no PR should make code coverage decrease more than 0.5%. 

![Screen Shot 2020-06-24 at 10.19.58 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/17090a1d-24e4-4614-8b4f-611dbbe060bf)

**Comment by DraxIndustries79** [comment]
We've decided on Coveralls and minimum 90% coverage aspiring to improve.
