### ISSUE TITLE
Job to Re-send Digital Object Requests

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2690]
Create a job to re-send digital object requests to Metadata Cloud for a given Admin Set.
This Job can be used to re-create DigitalObjects in ArchivesSpace or 856 links in ILS for all parents in an admin set.

- [x] Identify the parents
- [x] Force them to send digital object information in digital_object_check

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1307

**Comment by jpengst** [comment]
Deployed to Test v2.65.9

**Comment by martinlovell** [comment]
I had to make a fix to it: https://github.com/yalelibrary/yul-dc-management/pull/1311
(Tests were passing because to_solr was not present, and test parents were Private.)

**Comment by martinlovell** [comment]
Another PR: https://github.com/yalelibrary/yul-dc-management/pull/1312
(for nil child_object_count)

**Comment by jpengst** [comment]
Deployed to Test v2.66.1

**Comment by sshetenhelm** [comment]
Confirmed that this is working in UAT! Thank you! 

Ready to close :)
