### ISSUE TITLE
Deployment 12/13🌲

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2693]
**Versions:**
Management: 2.65.3
Blacklight: 1.60.92
MetadataCloud: 1.3.4

**Production:**

- [x] restart image servers
- [x] Management
- [x] Blacklight
- [x] MetadataCloud

**Comment by bobrice** [comment]
MGMT: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/404/
Blacklight: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/405/
ImageServers: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/406/
MetadataCloud: https://cm-prd.library.yale.edu/job/MetaDataCloud/57/

**Comment by laurenb33** [comment]
Thanks Bob! Ready to close :)
