### ISSUE TITLE
12/20 Deployment - Just Image Servers 🎊

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2696]
**Versions**
Management: _no change_
Blacklight: _no change_

**Production**
- [x] Recycle image server tasks

**Comment by bobrice** [comment]
https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/407/

**Comment by laurenb33** [comment]
Thanks, Bob! All set - ready to close: 
https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/408/
