### ISSUE TITLE
Change Feedback URL to accommodate new module in DCS

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2697]
**Story** 
In DCS, the link to the ‘Feedback’ form in the footer of the website goes to a ‘Page Not Found’ page on web.library.yale.edu during the following instances:

* From a search results page where a user has input a search term into the search bar, either in the metadata or the full text search
Example (enter URL, then click Feedback link in footer): https://collections.library.yale.edu/catalog?fulltext_search=1&q=cheese&...<https://collections.library.yale.edu/catalog?fulltext_search=1&q=cheese&search_field=all_fields>

* From a ‘failed search’ search results page
Example: https://collections.library.yale.edu/catalog?search_field=all_fields&ful...<https://collections.library.yale.edu/catalog?search_field=all_fields&fulltext_search=1&q=ladkjflakdjf>

This does not happen when a user clicks on the ‘Feedback’ form in the footer anywhere else on the website, including when a search is performed using the facets on the left side of DCS.

To fix this, when the URL is generated in the footer Feedback link in DCS and FindIT, the `&` needs to be changed to be coded as `%26`

Here is an example of what the link should look like: 
https://web.library.yale.edu/form/findit-feedback?findITURL=https://collections.library.yale.edu/catalog?search_field=all_fields%26q=dog

**Acceptance**
- [x] Change the Feedback footer URL coding to %26

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/953

**Comment by sshetenhelm** [comment]
Looks good on TEST with example search "Cheese" and "No results" page

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you so much!

Ready to close :)
