### ISSUE TITLE
1/3 Deployment 🎸

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2698]
**Versions**
Management: v2.65.6
Blacklight: _no changes_

**Production**
- [x] Management
- [x]  restart image servers

**Comment by bobrice** [comment]
All set.

MGMT output: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/410/
Image Server output: https://cm-prd.library.yale.edu/job/YUL-DC-Prod-Deploy/411/

**Comment by sshetenhelm** [comment]
Looks good! Ready to close. Thank you!
