### ISSUE TITLE
Resource review - IIIF background materials

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#270]
**STORY**
There's a number of other resources at https://iiif.io/apps-demos/ and https://github.com/IIIF/awesome-iiif#tutorials.  It would be useful to have a pair of team members review these resources and identify any others that are particularly valuable.

**ACCETPANCE**
- [x] One team member from each (management and discovery) has paired to review and curate resources from
   - [ ] https://github.com/IIIF/awesome-iiif
   - [ ] https://iiif.io/apps-demos/

**Comment by FCRodriguez7** [comment]
The Git site, Awesome-iiif,  has curated a diverse set of materials at different skill sets.  The site is a great resource for everyone.  However the site lacks an implementation demos section (https://library.stanford.edu/blogs/stanford-libraries-blog/2019/05/introducing-mirador-3-next-generation-image-comparison-viewer). The site is also missing valuable content, see below.  

**iiif Apps & Demos**
Missing Viewing Clients 
- IIPMooViewer
- Micro Service

**Image Servers** 
Missing Servers
- FSI Server & the adaptor
- Europeana 

A definition of a SHIM server show below the SHIM heading.   

There are broken links on the site.  While we recommend for the continuous use of the site, we strongly recommend adding PRs to correct some of the issues on the "Awesome" site.
