### ISSUE TITLE
Add SOLR_HEAP to variables in Camerata

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2702]
**Story**

After the UAT Solr restart the SOLR_HEAP variable in the ECS Task Definition is blank.   I suspect it is not being passed from Camerata since it is not listed in the `cluster.rb` file.

See #2694 

**Acceptance**
- [x] add SOLR_HEAP to `cluster.rb`
- [x] redeploy SOLR on UAT

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-camerata/pull/369

**Comment by bobrice** [comment]
Pulled the code and deployed to yul-dc-uat/solr via camerata.  The value for SOLR_HEAP wasn't populated after the update.  Revised the launch template to include the SOLR_HEAP value "18g" and restarted the task.
