### ISSUE TITLE
Clean up Synced Preservica objects

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2703]
For Goobi-ingested objects synced with Preservica, parents may have double sets of children (both the Preservica child and the Goobi child). We should review Goobi parents with Preservica information and delete the Goobi-only children while still retaining any caption and label information.

**Acceptance**
- [x] Review & clean up music synced objects
- [x] Review & clean up MSSA synced objects

**Comment by laurenb33** [comment]
All set - the majority of the issues were in the mus sets.
