### ISSUE TITLE
Add SOLR_HEAP for PROD

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2707]
**Story**
We need to undergo the same SOLR_HEAP variable work for PROD as we did last week for UAT. This should be completed before redeploying SOLR during the usual DCS deployment time.

Previous tickets:
#2694 (original ticket)
#2702 (work in UAT)

**Acceptance**
- [x] add SOLR_HEAP to parameter store for PROD
- [x] redeploy SOLR on PROD

**Comment by mikeapp** [comment]
I think this is done, even if the mechanics of setting this in #2694 are still in progress
