### ISSUE TITLE
OwP: Warning in MGMT if no Terms and Conditions

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2712]
**Story**
In the Management App, a warning message should display on a Permission Set's page when no Terms and Conditions are defined for the set. We would like this warning to display on the individual Permission Set Page when:

- A new Permission Set is created. It should appear underneath the green "successfully created" message.
- When a Permission Set page has "Terms and Conditions: None". It should appear above other content on the page.

Example placement and formatting (although this screenshot has the wrong font for the warning): 

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/a15aa94c-f60e-4f73-9e3e-6df2b163e1c2)

**Acceptance**

- [x] Warning message appears on individual Permission Set page when a new Permission Set is created 
- [x] Warning message appears on individual Permission Set page when set has _Terms and Conditions: None_
- [x] Warning message states _No Terms and Conditions are applied. Please select ‘Manage Terms and Conditions’ to apply Terms and Conditions to this Permission Set._
- [x] Warning message appears under green "successfully created" message and above all other content
- [x] Warning message has same formatting as yellow _Preservica credentials not configured for this Admin Set_ notification (yellow box with darker yellow font)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1318

**Comment by K8Sewell** [comment]
Will deploy to Test on main branch makes it through CI with release - [v2.66.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.4)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/67b4ba6e-432c-4162-a653-be4a2a0f5335)
