### ISSUE TITLE
Update colors for Management warning messages for accessibility

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2714]
**Story**
Some warnings in the Management App, such as the banner that appears when Preservica credentials have not been set up for a repository, include colors that may not pass accessibility requirements/best practices. We would please like recommendations for new colors in order to make these messages more accessible. Once we have recommendations, we would like to update these colors in the Management App style sheet.

**Acceptance**
- [x] Choose new color for font and outline: Font and border/outline color: #CC071E
- [x] Choose new color for background: Background color: #FAEAEA
- [x] Update MGMT stylesheet to reflect new colors

**Comment by tmacmath** [comment]
Font and border/outline color: #CC071E
Background color: #FAEAEA

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1321

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.66.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.5)

**Comment by K8Sewell** [comment]
Looks good on Test



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/c4bc8c5c-c678-4d86-a457-e4bdccb5e0c6)

**Comment by sshetenhelm** [comment]
Looks good! Ready to close. Thank you :)
