### ISSUE TITLE
OwP: Blacklight Error Message for No Terms and Conditions

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2715]
If an OwP object set does not have specified Terms and Conditions in MGMT, Blacklight shows a 404 "Sorry this page is unavailable at this time" error to users. This pages shows when a user tries to request permission to view an object, Instead, we would like it to throw an error message on Blacklight that will give the user specific details about the issue and who to contact about it.  

Acceptance 
- [x] Configure an error message for when a user requests permission to view an object, but there are no Terms and Conditions to validate
- [x] Message states _We are unable to complete your access request at this time. For more information about this object, click the ‘Feedback’ link located at the bottom of this page and fill out the form. We will get back to you as soon as possible._

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/965

**Comment by K8Sewell** [comment]
Rsolr errors seem to be holding up solr index jobs so this isn't possible to test right now.

**Comment by K8Sewell** [comment]
Looking good on Demo



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bf318bb0-e788-4d0e-a6e1-92302f970793)

**Comment by laurenb33** [comment]
Yeah, looks good on my end too :) Thanks JP and Kait!
