### ISSUE TITLE
[BUG] ‘Create parent object’ batch process not retaining Extent of Digitization for Preservica objects

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2717]
**Story**
When staff use the ‘Create Parent Object’ batch process and include Extent of Digitization information, the Extent of Digitization is not added to the parent object record for objects that include Preservica information. Objects without Preservica information include Extent of Digitization in the parent object record. 

Behavior is the same for both `Completely digitized` and `Partially digitized` values. 

[Example batch process in UAT - Batch Process 1785](https://collections-uat.library.yale.edu/management/batch_processes/1785)
Four parents created, Extent of Digitization only saved for the two parents with `digital_object_source` = `None`. 

Parents
[901622735](https://collections-uat.library.yale.edu/management/parent_objects/901622735) - No Preservica, Yes Extent of Digitization

[901622736](https://collections-uat.library.yale.edu/management/parent_objects/901622736) - No Preservica, Yes Extent of Digitization

[901622737](https://collections-uat.library.yale.edu/management/parent_objects/901622737) - Yes Preservica, No Extent of Digitization 

[901622738](https://collections-uat.library.yale.edu/management/parent_objects/901622738) - Yes Preservica, No Extent of Digitization 

**Acceptance**

- [x] Extent of Digitization status saves for all parents created using the Create Parent Object batch process, including parents with `digital_object_source` of `Preservica`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1315

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.66.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.3)

**Comment by K8Sewell** [comment]
Deploying to UAT because that instance is connected to the Test Preservica site

**Comment by sshetenhelm** [comment]
Works as expected in UAT. See [Batch Process 1788](https://collections-uat.library.yale.edu/management/batch_processes/1788/parent_objects/901622746)

THANK YOU! Ready to close.
