### ISSUE TITLE
Possible bug in BatchProcess admin sets

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2719]
It's getting the admin set using the authoritative_metadata_source_id:
```
sets << ', ' + AdminSet.find(parent_object.authoritative_metadata_source_id).key
```
https://github.com/yalelibrary/yul-dc-management/blob/main/app/models/batch_process.rb#L336

**Comment by sshetenhelm** [comment]
Does this just affect the "repo" that shows in the batch process tables/results pages, etc., or does this have an impact on "assigning" admin sets to parents, etc.?

**Comment by martinlovell** [comment]
It's just for display in the table

**Comment by sshetenhelm** [comment]
In MGMT UAT, I did two 'Export parents by admin set' batch processes that had two admin sets for each process, but the table is only displaying one. Could that possibly illustrate this bug?

**Processes:**
[Batch process 1816](https://collections-uat.library.yale.edu/management/batch_processes/1816)
[Batch process 1803](https://collections-uat.library.yale.edu/management/batch_processes/1803)

**Screenshot:**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/86be9c7c-9000-46c5-be37-171a3c2f8f02)

1816 should have both brbl and div
1803 should have both law and div

**Comment by K8Sewell** [comment]
Oh, that's a separate bug, unfortunately.  Can we get a ticket for that?  This ticket was for the `update_fulltext_status` job and the Export parents by admin sets uses another method so will need to make some changes there to make sure all the admin sets are getting captured.  But I did fix up the find call Martin referenced and the PR is ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1330

**Comment by sshetenhelm** [comment]
Created #2746 for new bug

**Comment by K8Sewell** [comment]
Pulls the correct admin set for update fulltext status job. Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/ec0c03bc-cc38-49c3-b4c1-423dc131e144)

**Comment by sshetenhelm** [comment]
Correct Admin set displays in UAT for this process as well.

Ready to close, unless there is a suggestion for something else that should be tested.
