### ISSUE TITLE
[Discuss] Missing OwP features

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2723]
We want to devote some time to discuss what features need to be added to the current OwP work. After regular standup, we will discuss the topics below on Friday, 2/9, and Monday, 2/12. 
**Friday's conversation should be recorded.**

On Friday, we will brainstorm what's missing from the OwP work, focusing on the question:
- [x] What is missing, yet necessary for the OwP work?

On Monday, we will discuss what needs to be built to address the missing OwP features, focusing on the question:
- [ ]  What should be built to address the missing features?

**Comment by K8Sewell** [comment]
OwP ticket ideas:
* Should we set up email notifications for approvers (& admin) when a new request come into a permission set they manage?
* When a new terms is assigned to a permission set all terms agreed info on the permission request should be cleared - should a notification be sent to the user requesting access or should the user just find out when they try to load the objects page?
* Do we want a 'status updated' notification alert in the header for request users?
* Should user's 'all requests' page have a link to the object's terms and conditions?
* Should an object page have a link for the user to see the object's terms and conditions?
* Where should we add links to the OwP explanation page?
