### ISSUE TITLE
Ensure Ruby/Blacklight upgrades are in OwP Feature Branch

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2725]
**Story**
Upgrade work was recently done that affects Blacklight. In addition to the main branch, we need to make sure these upgrades are also merged into the Open with Permissions Blacklight feature branch.

**Acceptance**
- [x] Merge upgrades into OwP Blacklight feature branch

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/966

**Comment by K8Sewell** [comment]
waiting until approval of permission request feature is built out so we can see a successful display of an OwP object
