### ISSUE TITLE
Add 'Title' and 'Rights Statement' to Export Metadata batch processes

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2726]
**Story**
In order to better facilitate their work, Library staff have requested that the following fields be added to the Export Parent Metadata batch processes: 

* Title - currently pulled from Metadata Cloud
* Rights Statement - Saved within the Management App

Use cases for Title:
First, when we are reassociating hundreds of records at a time using the "Export parent objects" to give us our working list, having the title display would help us better read what we are working on (since otherwise, all identifiers are strings of digits such as the OID, bibID, archivesspace URI, etc. which are easy for a machine to read but hard for a human). 
Second, titles for legacy records often contain metadata which should be in the caption field for our current metadata policies. 

Use case for Rights Statement: 
Sometimes, estates of collections will change the require language in the Rights Statements for works associated with those collections. Including the Rights Statement in exports will allow staff to easily identify what objects contain outdated language that needs to be replaced. 

**Acceptance**

Export Parent Metadata batch process
- [x] Add 'Title' metadata field to Export Parent Metadata batch process, after `child_object_count `and before `call_number`
- [x] Add 'Rights Statement' metadata field to Export Parent Metadata batch process, after `digitization_funding_source` and before `project_identifier`

Export All Parent Objects by Admin Set batch process
- [x] Add 'Title' metadata field to Export All parent objects by admin set batch process, after `child_object_count `and before `call_number`
- [x] Add 'Rights Statement' metadata field to Export All parent objects by admin set batch process, after `digitization_funding_source` and before `project_identifier`

**Comment by jpengst** [comment]
This has been included in the Export Source rework PR: https://github.com/yalelibrary/yul-dc-management/pull/1326

**Comment by K8Sewell** [comment]
Deploy to Test failed smoke tests for management deploy.

**Comment by sshetenhelm** [comment]
* Export by Admin Set looks good!
* Export parent metadata looks good!

**Comment by K8Sewell** [comment]
Deployed release [v2.66.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.7) to UAT

**Comment by sshetenhelm** [comment]
Howdy! I'm still seeing v2.66.6 on UAT. Could you please check the deployment?
