### ISSUE TITLE
Design for Permission Request Show Page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2727]
**Story**
In the Management App, we would like the Permission Request page to be updated to be more user friendly. Currently, it just displays label and value sets with paragraph breaks.

Screenshot of current formatting: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/df6139ba-8f98-485e-ae66-f3b7700de7e5)

We would like to add the following--

Buttons:

- Approve (to approve request)
- Deny (to deny request)

Beneath those buttons / options, we would like a button for the following:

- Change Object Access Requirements (to trigger a pop-up where the approver can recommend the object be made Public or Yale Community Only) 

Link:

- Blue “back” link similar to other pages at the bottom of the page 

Screenshot with suggested additions (my notes in red, please change colors to whatever is appropriate, etc.): 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/6d120e70-31c4-4c0a-958b-d3b5cff25654)

**Acceptance**

- [x] Design specs & wireframe for at least one new design of individual Permission Request page
- [x] Create ticket for engineering work

**Comment by tmacmath** [comment]
Pop-ups/modals are not recommended (and are actively discouraged these days) because they interrupt the user flow. Working on this page now.

**Comment by tmacmath** [comment]
First prototype has been created - working on a revised version per Summer's recommendations. Will post later today.
