### ISSUE TITLE
OwP: Change Editing Permissions for OwP key 

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2729]
Currently, all users can edit the OwP key on the Permission Set page. We would like to modify this, so all users cannot edit the OwP key on the Permission Set page.

Screenshot:
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/f9c8d1f5-9764-44dc-940b-077bfb7e6dcd)

Acceptance:
- [x] Disable ability to change the Permission Set KEY for all users

**Comment by jpengst** [comment]
This PR also validates uniqueness of the Key to prevent duplicates: https://github.com/yalelibrary/yul-dc-management/pull/1324

**Comment by jpengst** [comment]
Deployed to Test v2.66.6

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.66.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.6)

**Comment by laurenb33** [comment]
Confirmed that the key cannot be edited 👍👍👍👍
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/21cbb3c2-d023-4a93-890a-5e9da54d398c)

**Comment by sshetenhelm** [comment]
Looks good on Demo! But forgive me -- for Management OwP work, we are still deploying to regular UAT, correct? Just the Blacklight work is kept separate in the Demo branch?

**Comment by jpengst** [comment]
Yep, that is correct

**Comment by K8Sewell** [comment]
Deployed release [v2.66.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.66.6) to UAT
