### ISSUE TITLE
OwP: Changes to Permission Requests table

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2730]
First, we want to change the table to a data table. The features that are listed next will improve the functionality of the table for the approver. The request ID column to the left can be removed because it is not necessary for a user to see this information. We would like to add a button where the user can easily click to view an individual request. Lastly, we want to add the filters, clear, descending/ascending, search, and export to .csv functions that are similar to the parent and child object tables on Management. 

Screenshot of permission request table:
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/be908981-e112-40d9-9687-f5cfd04b6ff1)

Screenshot of filters and features on the MGMT parent table: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/e833cd65-fe83-4a50-bb0d-10a4e2c0e490)

Acceptance:
- [ ] Change to data table
- [ ] Remove the Request ID column
- [ ] Add button that the user can easily click to view an individual request 
- [ ] Add filters, clear, descending/ascending, search, and export to .csv functions to table

**Comment by K8Sewell** [comment]
PR in draft - will update when it makes it through CI

### Screenshot


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/8bccacd6-4074-4280-b9f2-ebf8ed78eef6)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1332

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.67.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.1)

**Comment by sshetenhelm** [comment]
I get an Ajax error DataTables warning when I try to sort/filter on the following fields:

- OID
- User Name
- User ID
- Net ID

The error prevents the filtering/sorting. Screenshot of message:


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/d39864f8-18cb-4980-a389-64cd82c2a3fd)

**Comment by sshetenhelm** [comment]
Also broken locally.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1354

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.67.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.8)

**Comment by sshetenhelm** [comment]
Working as expected on Demo :)
