### ISSUE TITLE
OwP: Fix Login Button on Blacklight OwP parent page

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2733]
We would like to change the Login button on Blacklight when a user clicks on parent objects that are OwP.  At the top of the page when a user is signed in, we would like to change yale university+net ID to the user's email. 

**Screenshot for parent object login:** 
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/745bb931-865c-4d9f-987b-9e852e5f1b5c)

Acceptance:

- [ ] Fix the login button

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/969

**Comment by K8Sewell** [comment]
Deployed to Demo with feature branch - [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by K8Sewell** [comment]
Unfortunately, getting an auth error on Demo when I try to use the log in link in the notification message.  



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bd7fdf78-d2ca-438c-90bd-3a90af942d9c)

**Comment by jpengst** [comment]
I don't think this is related to the re-work. Login button in nav bar has same error. Interesting

**Comment by jpengst** [comment]
Confirmed login button and OwP login button are both back to working.
