### ISSUE TITLE
Change Username to User's email in Blacklight

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2736]
At the top of the page when a user is signed in Blacklight, we would like to change yale university+net ID to the user's email. 

**Screenshot for username shown when logged in:** 
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/e01f245f-a00b-4523-b625-5cc913c350ed)

Acceptance:

- [ ] Change username shown to user's email

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/967

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.60.96](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.60.96)

**Comment by K8Sewell** [comment]
Failed quite a few smoke tests so attempting another deploy to see if it was a fluke.  If not we may need to adjust some of our smoke tests to work with this change.  



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/88758787-6fe6-4ea9-87b0-85e27ede8d11)

**Comment by K8Sewell** [comment]
Yep, second attempt resulted in the same output.  Looks like we may need to update some smoke tests or get some help from dev ops about what else may be going on here.

**Comment by K8Sewell** [comment]
Third attempt with a previously successful release (v1.60.95) also failed the smoke tests.  Leads me to believe this is unrelated to our code changes.

**Comment by K8Sewell** [comment]
Confirmed on AWS that Blacklight v1.60.96 was deployed to the Test environment.

**Comment by jpengst** [comment]
Bug PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/970

**Comment by K8Sewell** [comment]
Merging main into feature branch for testing in environment where user will more likely have an email.

**Comment by K8Sewell** [comment]
Displays user email if there is one available on Demo



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/e6fdfb83-3c1b-4cc4-a8b7-f8c23f863503)
