### ISSUE TITLE
Bookmark Gallery View -- Mobile-first Checkbox location wireframe

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2737]
**Story**
In the search results gallery view, the Bookmark checkbox needs to be moved. We would like a mobile-first wireframe to display where the checkbox should be located. 

Current views in Safari and Chrome on Macbook Pro:
SAFARI:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/7e7a9e4f-5090-48bf-9220-f1021a51a5b8)

CHROME:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/44d10f3b-9534-4f04-ac07-064bc66a35e0)

**Acceptance**
- [ ] Design/wireframe for search results gallery view that correctly places Bookmarks checkbox
- [ ] Subsequent ticket for engineering work

**Comment by tmacmath** [comment]
Is this view on collections-demo?

**Comment by tmacmath** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/49f8ad97-08e4-49b0-8a4a-0845f5dc35fa)

**Comment by tmacmath** [comment]
My apologies - the reason I created the mockup above was to mirror the one Summer posted initially. I will be posting mockups for an iPhone 13 in a few.

**Comment by tmacmath** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/b1ea788e-3ee4-4232-b79e-97076d5f4285)
