### ISSUE TITLE
Blacklight Explain OwP Page - Apply Formatting

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2738]
**Story**
Formatting of the page users see when encountering an unrequested Open with Permission object should be updated with the specs shared in #2593. 

Link as per #2593:  [https://xd.adobe.com/view/212032b9-959d-40fc-b0dd-7584eca7a8bb-7473/](https://xd.adobe.com/view/212032b9-959d-40fc-b0dd-7584eca7a8bb-7473/)
Click on the </> button to see the font and background colors.

**Acceptance**

- [x] Font for message Mallory-Medium 14px - used rem equivalent
- [x] Font for link Mallory-Bold 14px and includes decoration - underline  - used rem equivalent
- [x] Box border color and font color is 0053BF - used yale_blue (#043669) because it was pretty close to the dark blue of #0053BF
- [x] Background of box color is F2F7FC - there was no close match in our colors so added this one to our theme - we do have a couple light greys (#f5f6f6 & #f9f9f9) that I could switch this out for if desired
- [x] Width of box is width of container div

**Comment by K8Sewell** [comment]
Deployed to Demo with branch [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by K8Sewell** [comment]
Looks consistent on Demo.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/410cb744-35b4-49a0-bfea-f06fb36299d8)

**Comment by sshetenhelm** [comment]
Looks good! Thank you so much :) 

Ready to close
