### ISSUE TITLE
Programmatically identify visibility for an OID

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#274]
**ACCETPANCE**
Given a list of OIDs
- [ ] I can produce a list of "Public Access" OIDs
- [ ] I can get counts of other types of visibilities in the list 

Given the list of all OIDs
- [ ] I can produce a list of all "Public Access" OIDs

**Comment by maxkadel** [comment]
It's looking like this goes along with the work on #260 so picking them up at once
