### ISSUE TITLE
Prevent users from creating duplicate keys and labels

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2740]
**Story**
In order to keep a clear separation of permission sets, we should disable the ability for users to create a Key or Label that matches one that already exists. Currently, it is possible to create multiple Permission Sets with the exact same Key and Label. 

Additionally, when trying to create a new Permission Set or edit an existing Permission Set, users should receive a warning if they are using a Key or Label that already exists. 

**Screenshots of existing functionality:**

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/acfb2334-900d-438a-968c-0757f9ce11ac)

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/de859c14-402f-4ae1-be43-21abdb002086)

**Acceptance**
- [ ] Users cannot create Permission Set with Key that already exists (edit: included in #2729 PR?) 
- [ ] Users cannot create a Permission Set with Label that already exists
- [ ] Users cannot edit a Permission Set to change the Label to a Label that already exists
- [ ] Users cannot edit a Permission Set to change the Key to a Key that already exists (edit: included in #2729 PR?) 
- [ ] When creating a Permission Set, warning notice appears when the Key and/or Label matches an existing Key and/or Label, and Set does not save
- [ ] When editing a Permission Set, warning notice appears when the Key and/or Label matches an existing Key and/or Label, and edits do not save
- [ ] Warning message states: _The Key and/or Label you are trying to save already exists. Please update the Key and/or Label to a unique value._ 
- [ ] Warning message uses usual formatting (the red box)

**Comment by K8Sewell** [comment]
Is it ok if we keep the notification messages separate?


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bfcf80c4-ef0a-4b25-9794-66f7e9a9a9ae)

**Comment by sshetenhelm** [comment]
Yes, that would be great!

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1331

Just takes care of labels since keys were already done.

**Comment by K8Sewell** [comment]
Looks ok on Test.  Will deploy to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/89bf32d0-d21f-478e-af8a-186a8d6a7517)

**Comment by sshetenhelm** [comment]
1. Confirmed was unable to create a new Set with existing Key / Label
2. Confirmed was unable to edit an existing set to an existing Label
3. Confirmed still cannot edit Key ;) 
4. Confirmed received appropriate warnings

Ready to close! Thank you so much :)
