### ISSUE TITLE
Allow non-SysAdmin accounts access to individual permission requests

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2743]
**Story**
In the Management App, when a regular user is assigned as an approver or administrator of a Permission Set, they are unable to view the individual permission requests. Clicking on the number of the Request ID takes the user to a plain white page with the text ‘Access Denied.’ 

If that regular user is “upgraded” to a SysAdmin account, they can access the individual permission requests.

Both Permission Set Approvers and Administrators should be able to access the individual permission requests, even if they are not SysAdmins. 

**Acceptance**
- [x] Permission Set Approver (non SysAdmin) can view the individual permission request page when clicking on the Request ID
- [x] Permission Set Administrator (non SysAdmin) can view the individual permission request page when clicking on the Request ID

**Comment by K8Sewell** [comment]
During work on the datatable ticket I needed to update the ability model to make sure the right folks could see the right permission requests in the table and I think doing that also took care of the objectives in this ticket.  Made myself a non sysadmin and gave myself admin and approver roles and was able to verify that I could see an individual permission request's show page.  

PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1332

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.67.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.1)

**Comment by sshetenhelm** [comment]
Confirmed this works in DEMO.

We can bump work to UAT but since we have not put in any requests / functionality for requests in UAT yet we cannot review on UAT.
