### ISSUE TITLE
Admin set keys missing from Batch Process table for 'Export by admin set'

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2746]
**Story**
In MGMT UAT, I did two 'Export parents by admin set' batch processes using the Batch Process Template that had two admin sets for each process, but the table is only displaying one. 

**Processes:**
[Batch process 1816](https://collections-uat.library.yale.edu/management/batch_processes/1816)
[Batch process 1803](https://collections-uat.library.yale.edu/management/batch_processes/1803)

**Screenshot:**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/86be9c7c-9000-46c5-be37-171a3c2f8f02)

1816 should have both brbl and div
1803 should have both law and div

When exporting multiple admin sets, we would like all admin set keys to display in the Batch Process table.

**Acceptance**
- [x] All admin set keys for the ‘Export All Parent Objects by Admin Set’ display in the Admin Set column of the batch process table

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1336

**Comment by K8Sewell** [comment]
Included in Management release [v2.67.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.3)

**Comment by sshetenhelm** [comment]
Tested with [batch process 823](https://collections-test.library.yale.edu/management/batch_processes/823). 

Instead of displaying all 3 in the table, as I refreshed the 'batch process' page, it showed first only `mus` (which was first in the uploaded csv) and then only `div` (which was last in the uploaded csv). So, it's showing one at a time, in the order of the spreadsheet, as the process is... processed.

**Comment by jpengst** [comment]
I've done a few tests on test and local. It looks like this bug happens when the last item in the csv does not have any parent objects associated with it. Do we want the BP table to display all the admin sets that are present in the uploaded CSV? Or do we only want to show the admin sets that have parent objects in the set?

**Comment by sshetenhelm** [comment]
I think the best way would be to display all admin sets that were included in the csv, so users aren't under the impression that the process did not "read" that the admin set or something. 

However, if that behavior is significantly more difficult to get working than having only admin sets that have parent objects, I would be satisfied to go that route as well. In PROD, there shouldn't be any "active" admin sets that don't have parents (JSS isn't in use so wouldn't matter).

**Comment by jpengst** [comment]
Yep, no problem! BP table will now display all admin sets that are present in the csv.  
PR: https://github.com/yalelibrary/yul-dc-management/pull/1353

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.67.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.8)

**Comment by sshetenhelm** [comment]
Looks good on Test!

**Comment by K8Sewell** [comment]
Deployed to UAT

**Comment by sshetenhelm** [comment]
Works as expected on UAT! Thank you! 

Ready to close :)
