### ISSUE TITLE
Apply design for Permission Request Show Page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2748]
**Story**
Please apply the formatting / design for the Permission Request Show Page in Management. Specs were generated in #2727 

[Link to Prototype/User Flow](https://xd.adobe.com/view/b2e3db51-ae45-416e-9bc1-f3f9fcf433c3-e7b0/)

Screenshot:
![](https://private-user-images.githubusercontent.com/9658383/307919153-08371e41-f348-4961-a180-7ce3d4aedcc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTE5ODAsIm5iZiI6MTcwOTA1MTY4MCwicGF0aCI6Ii85NjU4MzgzLzMwNzkxOTE1My0wODM3MWU0MS1mMzQ4LTQ5NjEtYTE4MC03Y2UzZDRhZWRjYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTYzNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNmYjkwYzJlMDNhZTY5MzNhMzIwNzY2NDJiZDljNmI2Y2M2MjU5OThkYzk5N2ZkODlkNzM1MDk1YjA1N2EzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.srKaTL3gnRZ9VQvy1HtU_mt9q_RvBPsRz-ZuuyqS-Og)

**EDIT -- CHANGE SINCE SPRINT PLANNING**
The last row, labeled 'Test Label', should be labeled "Approver Notes". In the table should be a free-text field where the approver can provide optional free-text notes regarding their acceptance or denial of permission.

Please disregard the ‘Object Access Type’ section for the time being. That work will be addressed in a different ticket.

**Acceptance**

- [x] Data is presented in table
- [x] Table has gray background in alternating rows
- [x] Final row of table is “Action”
- [x] Action has two radio buttons — ‘Approve’ and ‘Deny’
- [x] Cancel button is located beneath the table
- [x] Green save button is located to the right of the Cancel button
- [x] Clicking Cancel takes the user back to the Permission Requests page
- [x] Clicking ‘Save’ when “Approve” is selected grants the requester permission to view the parent object
- [x] Clicking ‘Save’ when “Deny” is selected does not grant the requester permission to view the parent object
- [x] After clicking ‘Save,’ the page refreshes and displays green message “Changes saved successfully.”

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1337

**Comment by K8Sewell** [comment]
Included in Management release [v2.67.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.3)

**Comment by sshetenhelm** [comment]
Looks good!
