### ISSUE TITLE
Add Object Access Type functionality to Permission Request Show Page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2749]
**Story**
Permission Set Approvers and Administrators should be able to recommend a change of the Visibility of an object. This can be done using the small menu that was added at the bottom of the design in #2727. Specs are available in #2727 and here is [Link to prototype/user flow
](https://xd.adobe.com/view/b2e3db51-ae45-416e-9bc1-f3f9fcf433c3-e7b0/)

When the request is saved, an email should be sent to the following address:
digitalspecialcollections@yale.edu 

**Acceptance**

- [x] Add the heading “Object Access Type” underneath the individual Permission Request table.
- [x] Add a table with the first row labeled “Change Access Type?” And radio buttons that allow someone to choose No or Yes
- [x] Add a second row to the table labeled “New Access Type” and radio buttons that allow someone to choose Yale Community Only or Public
- [x] When Change Access Type? = No is selected, the “New Access Type” portion of the table is unable to be edited
- [x] When the green “Save” button is clicked, an email is sent to digitalspecialcollections@yale.edu with the following information:

Subject: DCS Object Visibility Update Request

“`[APPROVER NAMER]` has requested the following change in the Digital Collections System:
Permission Set: `[Permission Set Label]`
Admin Set: `[Admin Set Label]`
Parent OID: `[parent oid]`
New Visibility: `[Yale Community Only or Public]`”

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1339

**Comment by K8Sewell** [comment]
Included in Management release [v2.67.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.4)

**Comment by sshetenhelm** [comment]
Tested with [Permission request #16.](https://collections-demo.library.yale.edu/management/permission_requests/16)

1. Would it be possible to have the "Object Access Type" selection information save in this request if an approver requests to change the access? When I approved, I requested the change, but when I revisit the request I don't see the info saved (although I can see info like my approver note). 

2. After five minutes, have still not received email from DCS re: access change.

**Comment by K8Sewell** [comment]
Emails now sending from Demo.  

Yes, it's absolutely possible to retain that information - and a history of the visibility status if that would be helpful too.

**Comment by jpengst** [comment]
PR for saving New Access Type to page: https://github.com/yalelibrary/yul-dc-management/pull/1365

**Comment by jpengst** [comment]
I think we should create a new ticket for displaying version visibilities to the request page since that work is a bit out of scope for this feature.  
  
Also, the user flow for this currently isn't very intuitive. What do we think about just displaying what the current access type is and then having selections to change the access type below:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/5fb0e4b6-a297-4e8f-a48d-519fcd77cac6)

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.68.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.5)

**Comment by sshetenhelm** [comment]
Works on Demo! Thank you!

Ready to close :)

**Comment by sshetenhelm** [comment]
Check email before closing

**Comment by sshetenhelm** [comment]
Just approved two new requests and requested Access Type change. Waiting to hear from colleagues if the emails went through to DSCA email address.

**Comment by K8Sewell** [comment]
You may also see one from me as well.  Was also testing just a minute ago.

**Comment by sshetenhelm** [comment]
Alas! I have not received any emails.

**Comment by sshetenhelm** [comment]
Still no emails. Would we be able to update the email to either send to my email address also ( summer.shetenhelm@yale.edu ) , either in the "TO" field or the "CC" field? I worry there is something about the digitalspecialcollections address that is blocking these emails.

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.1)

**Comment by sshetenhelm** [comment]
In the words of Ric Flair, WOOOO!

...except the message should say "because **DCS** is configured to use your email address"

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/4817bf0f-b704-4b16-910e-5b2c5b7afba3)
