### ISSUE TITLE
Ruby Upgrade - Deploy and Test

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2751]
**Story**

We need to deploy the Ruby upgrade and test Management and Blacklight to ensure that DCS functions as expected. 

Testing should commence as soon as deployment is finished.

**Acceptance**
- [x] Merge Ruby into main
- [x] Deploy Ruby upgrade to main branch on Wednesday
- [x] Test Management - SysAdmin tasks & report back
- [x] Test Management - Non SysAdmin tasks & report back
- [x] Test Blacklight - User not logged in & report back
- [x] Test Blacklight - User logged in & report back
- [x] Test Blacklight - Demo, current Open with Permissions features & report back

- [x] UAT Management - SysAdmin tasks & report back
- [x] UAT Management - Non SysAdmin tasks & report back
- [x] UAT Blacklight - User not logged in & report back
- [x] UAT Blacklight - User logged in & report back

- [x] PROD MGMT - Sysadmin
- [x] PROD MGMT - Non Sysadmin
- - [x] Fix PTIFF job
- - [x] Fix Preservica Resync job
- [x] PROD Blacklight - not logged in 
- [x] PROD Blacklight - logged in

**Comment by martinlovell** [comment]
- [ ] Verify that nightly jobs are running (Activity stream and problem report)

**Comment by sshetenhelm** [comment]
Now in TEST, will pivot back to this morning of 2024.04.03.

**Comment by sshetenhelm** [comment]
Blacklight TEST has passed with flying colors :)

**Comment by sshetenhelm** [comment]
UAT Blacklight looks good, need to test Management UAT.

**Comment by sshetenhelm** [comment]
Management UAT is having Preservica ingest issues. I've commented with more details in the Preservica bug and Ruby Management upgrade tickets.

**Comment by sshetenhelm** [comment]
@laurenb33 we should run through our test script in PROD now that the deploy has gone out, just to double check. After that, we can close this ticket.

**Comment by sshetenhelm** [comment]
Did not test Delete Child OIDs or Reassociate Child OIDs yet because it's Prod and I didn't want to ruin anything. 

* **Recreate Child OID PTIFF** failed due to 'PTIFF not found' even though PTIFF is available and able to be downloaded directly through child image page. This information has been shared in the appropriate bug ticket that is already on the board.
* **Resync with Preservica** batch process did not appear to complete [as per the batch process details](https://collections.library.yale.edu/management/batch_processes/17213), but is recorded in the [parent object history](https://collections.library.yale.edu/management/parent_objects/33134650/versions?checked=false) . This object was successfully ingested from Preservica the first go around and has not had any file updates.
