### ISSUE TITLE
Add Full Text to DEMO and test OwP Visibility

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2752]
**Story**
Users without permission to view a parent should also be prevented from viewing that parent's Full Text information in Blacklight. 

To test this, we need to add full text to some parents on DEMO.

Example parent OIDs from DEMO: 
[10665710](https://collections-demo.library.yale.edu/management/parent_objects/10665710)
[11690527](https://collections-demo.library.yale.edu/management/parent_objects/11690527)
[10659098](https://collections-demo.library.yale.edu/management/parent_objects/10659098)
[10666025](https://collections-demo.library.yale.edu/management/parent_objects/10666025)
[10650963](https://collections-demo.library.yale.edu/management/parent_objects/10650963)

**Acceptance**

- [x] Add full text to 5 parent objects on DEMO
- [x] Change Visibility to Open with Permission
- [x] Test to see if permissions prevent user from viewing full text information

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Full text are in placed for the above records

**Comment by sshetenhelm** [comment]
Thanks @MaggieZhaoYale !

1. Confirmed that, although the Show full text / Hide full text links are visible, clicking on them does nothing, and the full text is not visible.
2. Confirmed that the status of Full Text = Yes remains for all objects in filter categories, even though Full Text is not visible.
3. Confirmed that, although the Show full text / Hide full text links are visible, no full text information or links appear in the page source code.
4. The full text is still searchable and comes up with relevant results when an object is Open with Permission, but stakeholder previously said that is not a dealbreaker if it is unavoidable. 

Question: Is there a way to suppress the "Show full text" / "Hide full text" links for objects that a user does not have permission to view? 
If not, that's OK; just think it might be less confusing for users if we can hide it when they don't have permission. 

Ready to close once we talk through the above question.
