### ISSUE TITLE
Fix Gallery View Thumbnails and Titles

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2755]
# Summary
In Blacklight in the Gallery View setting of the search results page the thumbnails for images are not showing and the titles for the object's are larger than they should be.

# Acceptance Criteria
- [x] restore thumbnails
- [x] set object title font size to equivalent of pre-ruby-upgrade size

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/04241572-5345-4d26-8c28-05d82bc76f83)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/983

**Comment by sshetenhelm** [comment]
This looks good on Test! Could we get the fix into DEMO as well, or should I make that request in another ticket?

**Comment by sshetenhelm** [comment]
Looks good in UAT and DEMO, ready to close :) THANK YOU!
