### ISSUE TITLE
Production key and secret management recommendation

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#276]
**ISSUE**
We have a number of non-public keys (like Honeybadger API keys) and secrets like S3 passwords that should not be checked into source control as clear text

**ACCEPTANCE**
- [ ] We have a recommendation for key management for production-like environments

**NOTE**
Yale is using Ansible Vault, based on this let's look at RAILS_MASTER_KEY encryption first

**Comment by mark-dce** [comment]
RECOMMENDATION:

For environment settings, pilot use of Amazon System Manager Parameter Store:
* Service Description https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html
* Setup for use with ECS https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html
* ECS-Params setup to read using ECS-CLI https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html ( see services / secrets )
*NOTE: this solution works for all containers*

For configuration within the blacklight and management applications, we can optionally use Rails encrypted credentials
* https://edgeguides.rubyonrails.org/security.html#environmental-security
*NOTE 1: this solution only works for rails applications*
*NOTE 2: this solution still requires a secure way to manage and distribute the RAILS_MASTER_KEY, so it may not offer any advantages over the primary solution*

**Comment by dl-maura** [comment]
@bobrice @ra359 Please take a look and let us know what you think of this
