### ISSUE TITLE
Move Bookmarks box on gallery view

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2761]
**Story**
The gallery view for Bookmarks should be updated to match the design in #2737. This design has the Bookmark box hovering above the object image.

**Acceptance**

- [x] Bookmark box moved to above parent object image

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/986

**Comment by sshetenhelm** [comment]
Looks good on DEMO!
