### ISSUE TITLE
Deploy Issue - Ruby Upgrade

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2764]
Last week, when trying to upgrade Ruby on Rails Management, the camerata deployment via Jenkins was running for 18 hours; devops halted it. We are unsure why the camerata deployment is stalling.

**Comment by K8Sewell** [comment]
Keith put up a [PR on camerata](https://github.com/yalelibrary/yul-dc-camerata/pull/371) that should get us the ability to deploy in the new Jenkins environment.  I've approved and merged the PR (after making sure mgmt & blacklight built and passed a few tests) so to test this we need help deploying releases in the new Jenkins or JP and I need access to it so we can kick of deploys again.

**Comment by K8Sewell** [comment]
We may have a fix.  After a pairing session with JP and Rob I can confirm that work (adding preservica_representation_type to exported csv) from mgmt release v2.67.5 is live on Test (the branch for this PR was deployed to the test env) and I'm not seeing any webpacker errors in the logs either. 

PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1351



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/5cc278e6-d5fc-4712-8db3-d2d1f54c98e9)

**Comment by K8Sewell** [comment]
Deployed with management release [v2.67.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.7)
