### ISSUE TITLE
Perpetual access to Approvers and Administrators of Permission Sets

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2766]
**Story**
For Open with Permission objects, users who are Approvers or Administrators of a Permission Set should have ongoing/perpetual access in Blacklight to all parent objects that are members of that Permission Set. 

**Acceptance**

- [x] Permission Set Approvers can access all objects in a Permission Set in Blacklight without having to request permission through Blacklight in perpetuity
- [x] Permission Set Administrators can access all objects in a Permission Set in Blacklight without having to request permission through Blacklight in perpetuity

**Comment by jpengst** [comment]
@mikeapp How do we want to lookup the Blacklight user in Management? The shared columns on the BL/Management user tables are `email` and `uid`. I figured `uid` would be the best to pass from BL to Management. However, since I have a sponsored identity, the two UID's do not match. Summer mentioned that this would also be an issue Kissinger Approvers with sponsored identities.

**Comment by jpengst** [comment]
Blacklight Draft PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/990  
Management Draft PR: https://github.com/yalelibrary/yul-dc-management/pull/1347

**Comment by mikeapp** [comment]
Currently you need a NetID to access Management, so the `uid` column contains the user's NetID.  

We can match the Blacklight user's NetID (I think we extract that, separately from the `uid`?) to the Management `uid`.

**Comment by jpengst** [comment]
Rework BL PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/992

**Comment by K8Sewell** [comment]
Included with this [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/bd9855b46ac6df3ee96f4d7043869e7c162b04fb) into the OwP_FeatureBranch which is currently being deployed to Demo.

**Comment by sshetenhelm** [comment]
Confirmed that I can see objects for which I am an administrator, even if I have not had a request "approved."
