### ISSUE TITLE
Suppress "Full Text" dropdown/links for OwP parents

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2768]
**Story**
When a parent object that includes full text has a Visibility of Open with Permission, and a user does not have permission to view the object, the "Show Full Text" / "Hide Full Text" options should be suppressed in Blacklight. Since a user without permission cannot view the text, they also should not view the text functionality.

Screenshot of current view:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/88445ec5-6b19-4195-9b34-08cc79071198)

**Acceptance**

- [x] Show Full Text / Hide Full Text does not display in Blacklight when a user does not have permission to view an Open with Permission object
- [x] Show Full Text / Hide Full Text works for OwP objects where a user had permission to view object

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/994

**Comment by K8Sewell** [comment]
Included with this [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/ebe086dea55d253db3879edc29b9053dfd860e8b) into the OwP_FeatureBranch which is currently being deployed to Demo.

**Comment by sshetenhelm** [comment]
Confirmed that the _Show text / Hide text_ functionality is hidden when a user doesn't have permission, and shows when a user has permission. 

However, no text displays when clicking on the "Show full text" for users with permission, even when an object has text in the text file. [Video example](https://drive.google.com/file/d/1_82Otte9kHQPg3YHyisBvK5fF4E4H7Q9/view?usp=sharing).

**Comment by sshetenhelm** [comment]
SORRY accidentally close, I reopened it!!!!

**Comment by laurenb33** [comment]
"Full text" is hidden for me on OwP objects that I don't have access to: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/63bc5027-67fd-44a5-95d5-c4b9ea05b167)
