### ISSUE TITLE
Suppress Full Text Snippet label from search results for OwP parents

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2769]
**Story**
The Search Results list in Blacklight includes Open with Permission parents that have full text. The Full Text label displays in the search result, although the text snippet is suppressed. We would like to suppress both the Full Text label and values (text snippet) for Open with Permission objects when a user does not have permission to view the parent object. 

Screenshot of current functionality:

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/5135a0d7-5e48-4b4f-be92-b355e0912349)

**Acceptance**

- [x] Full Text label is suppressed from search results for Open with Permission objects when user does not have permission to view object

**Comment by sshetenhelm** [comment]
I am still seeing the label in search results when I search with "Full text" selected in the search bar, both when I am logged in and when I am logged out:

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/d994a6a0-2009-4006-ad57-a2e3ffbc8579)

**Comment by jpengst** [comment]
Hiding the label is a bit of a heavier lift than anticipated. I found an easier solution to add "Unavailable" (or any other language you want) for Full Text snippets that the user does not have access to view:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/1539a1f6-4aaf-4809-8593-11b3f1e128e6)


Is this an acceptable solution, or do we want to pursue hiding the label?

**Comment by sshetenhelm** [comment]
Could we please change "Unavailable" to say "Available with permission" ? Otherwise, yes, 100% acceptable.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/998

**Comment by jpengst** [comment]
Deployed to Demo OwP_FeatureBranch

**Comment by sshetenhelm** [comment]
Looks great on DEMO! Thank you so much!

On feature branch, so Ready to Close.
