### ISSUE TITLE
Test for permission check to access text annotation endpoint

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2770]
**Story**

We should have a test that verifies that the text annotation endpoint `/annotation/oid/${$('#parent-oid').text()}/canvas/${child_oid}/fulltext` enforces permissions for OwP items.

**Acceptance**
- [ ] Test validates that a user w/o permission cannot access the text

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/995

**Comment by K8Sewell** [comment]
Deployed to Demo with [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by sshetenhelm** [comment]
@mikeapp is there a way to test this test?

**Comment by mikeapp** [comment]
I don't think so.
