### ISSUE TITLE
Add Date Approved/Denied to table

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2775]
**Story** 
Permission Approvers and Administrators want to easily see the date that a request was Approved or Denied. We would like this added as a column on the Permission Request table, after 'Request Status' but before 'Approver.' The value displayed will be a timestamp of when a request was approved or denied by the Approver. 

**Acceptance**

- [x] Add column titled 'Date Approved/Denied' after 'Request Status' column but before 'Approver' column
- [x] Data in column provides timestamp of when an individual request was approved or denied

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1343

**Comment by sshetenhelm** [comment]
Confirmed works for both approvals and denials, Timestamp is visible. THANK YOU!
