### ISSUE TITLE
Add Preservica Representation Type to Exports

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2777]
Currently, the Preservica representation type field is not included in the metadata for batch process. We would like it to be included in: the batch process exports for parent metadata and all parents by admin set. 

**Background**: 
The nightly job for our Reoccurring jobs table  has throwing this error since last Friday: 
_Failed: Validation failed: Preservica representation type can't be None when Digital Object Source is Preservica._ 
If the field is added to exports, it will be much easier to determine which object doesn't have a Preservica representation type to solve the reoccurring jobs issue. 

**Acceptance:** 
Add Preservica Representation Type to Batch process exports for:
- [x] Parent metadata 
- [x] All parents by admin set
- [x] Column appears after the "preservica_uri" column

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1341

**Comment by K8Sewell** [comment]
Will be deployed to Test with release [v2.67.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.67.5)

**Comment by sshetenhelm** [comment]
Looks good on test! Confirmed for both batch processes :)

**Comment by sshetenhelm** [comment]
Looks good on UAT for both batch processes! Ready to close. Thank you!
