### ISSUE TITLE
Remove case sensitivity from Preservica checksum validation

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2779]
**Story**
Depending on the packaging tool, checksums created for objects intended for DCS may be in either lower- or uppercase. However, our current checksum validation is case-sensitive, which results in errors for objects when they were created with specific packaging tools (ex. the PUT tool). 

We should update checksum validation to be not case-sensitive.

**Acceptance**

- [x] Remove case-sensitivity from Preservica checksum validation

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1345

**Comment by sshetenhelm** [comment]
Preservica upload is not working in UAT. Unsure if it is due to this bug fix or the Ruby upgrade. 

When attempting to upload, I received the following error: 
`Child Object 901622792 failed to convert PTIFF due to Expected file originals/92/90/16/22/79/901622792.tif not found.`
So I guess the child image did not successfully copy over from Preservica? 
[Video](https://drive.google.com/file/d/1RIYJOnHKAu-Do3EMgZk8pSKYvFTNHC2e/view?usp=sharing)

**Comment by sshetenhelm** [comment]
LIKELY related to upgrade, because the second time I tried this ingest, it was with an object that had ingested successfully prior to this.

**Comment by K8Sewell** [comment]
Picking this back up.  Being unable to find the tif in the originals folder is potentially due to a failure in copying from preservica but could also be a mismatch in which s3 bucket it's looking for that tif in or something else entirely.  Investigating cause and will hopefully have a fix soon.

**Comment by K8Sewell** [comment]
After adding an ACCESS_MASTER_MOUNT default variable to the parameter store a resync of the [901622791](https://collections-uat.library.yale.edu/management/parent_objects/901622791) parent object completed successfully.  I'm testing a larger sample to evaluate if that was the needed fix.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/8504484c-6f7a-4ea2-89ed-6cee4618681f)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-camerata/pull/378

Looks like the larger samples were successful as well.  The above PR will make a change to a few of the templates by updating '/data' to 's3' for the access master mount.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/935de015-a8f4-4b0c-b692-276f9c558255)

**Comment by K8Sewell** [comment]
Closed camerata PR - no. 378 - post discussion with Mike and Martin.  Clarified that PR was not needed - storage should be set to `/data` for deployed environments.  Mike deleted the ACCESS_MASTER_MOUNT env var from AWS parameter store and I redeployed to UAT.  Unfortunately, while most resync with preservica jobs succeeded I am still seeing that the original is not being found for some images.  I'll need to pair with someone with access to shares at yale to debug the original not found issue further.  The not being able to find the original file does seem to be a different issue than the case sensitivity issue for the checksum comparison so perhaps this is ready to be tested again.

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/9bfbbcae-c22e-40c5-8964-0429098b0b11)

**Comment by sshetenhelm** [comment]
Tried again and got the 'child image not found' failure - https://collections-uat.library.yale.edu/management/batch_processes/1880/parent_objects/901623823 
I used ils as the source this time to see if it was an Aspace issue or something, but still received the failure. For some reason the child is getting created and gets the label/filename from Preservica but DCS can't pull in the image itself.

**Comment by K8Sewell** [comment]
Deployed to UAT with release [v2.68.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.0)

**Comment by sshetenhelm** [comment]
1. Uploaded an object using the Preservica PUT tool.
2. Used batch process template to create parent using Preservica information.
3. Batch process failed with “couldn’t find child object” message.
4. Additionally,  the following fields from my ‘Create Parent Object’ batch process template were not retained:

- digitization_note
- digitization_funding_source
- rights_statement

5. Pressed “Resync metadata” button.
6. Refreshed page. Child objects successfully created.

**We need to ensure the child objects are being successfully created without (a) having to hit the resync button, (b) displaying a batch process failure message to the user, and (c) overwriting/ignoring any metadata input into the batch process spreadsheet.**

In this [3 minute video](https://drive.google.com/file/d/1FeHImSnbr9rgrq-JwRhO9Qvm2oTvZTp4/view?usp=sharing), you can see me filling out the spreadsheet, copying the Ref ID from Preservica, uploading, viewing the batch process status page and error message, resyncing the parent object, and looking for my missing metadata (which didn’t upload at all but I didn’t notice until after the resync). I suggest watching on 1.5x or 2x speed and pausing if you need to review something closer.

The good news is the images *DID* come in!

**Comment by K8Sewell** [comment]
PRs ready for review  - 

https://github.com/yalelibrary/yul-dc-management/pull/1359

https://github.com/yalelibrary/yul-dc-management/pull/1360 (tests passed last run but timed out in CI so should be green shortly)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1361

**Comment by K8Sewell** [comment]
Deployed to UAT with release [v2.68.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.1)

**Comment by K8Sewell** [comment]
Still seeing the missing original issue - taking back to in progress



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/d657452f-5353-4a9f-b415-d39cb47bb497)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1362

**Comment by K8Sewell** [comment]
Deployed to UAT with release [v2.68.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.2)

**Comment by sshetenhelm** [comment]
Tested with UAT batch processes [1931](https://collections-uat.library.yale.edu/management/batch_processes/1931) and [1932](https://collections-uat.library.yale.edu/management/batch_processes/1932).

Both batch processes remain in a state of "in progress" and don't pull in TIFFs with the 'Create' batch process.
However, both successfully pulled in TIFF images after either (a) resyncing the metadata using the "Update this item" button on the parent object page, or (b) "selecting" a new thumbnail (even though the images didn't exist yet) and saving, which caused the object to update and pull in the images. 

In a perfect world, we wouldn't need the additional resyncing step.

**Comment by K8Sewell** [comment]
Thanks for testing, Summer & JP.  Based on the testing results I have removed the retries (from prior PRs) that seemed to be creating a situation where the sync from preservica job would hang as incomplete and there was still an extra step needed to successfully pull in the original files over to the shares at yale from preservica so I have added a redo when the file is actually written to the access master path.  

PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1364/

**Comment by K8Sewell** [comment]
Deployed to UAT with release [v2.68.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.4)

**Comment by K8Sewell** [comment]
Taking back to in progress to resolve persisting originals file missing...the /data/ path access appears to be resolved but still need to fix the /originals/ path.  Have begun to schedule mobbing time to help with debugging.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/bcb547cc-05fd-4eed-856b-6191dcb66397)

**Comment by K8Sewell** [comment]
PR to add more descriptive logging ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1369

**Comment by K8Sewell** [comment]
PR that will fix the goodjob errors we were seeing in the worker logs on Test and UAT - https://github.com/yalelibrary/yul-dc-management/pull/1372/ (it is currently deployed on Test)

Currently investigating two things:
* why does the system think that the access masters for a single parent live on both S3 and the shares at Yale 


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/7d32d796-e3f5-49be-a4e0-c9a9bea8ba2c)




* why are we now getting this error in the worker logs 



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/2b202b71-c865-41f6-8335-1f9879137292)

https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/yul-dc-test/services/yul-dc-test-worker/tasks/c3139a9790a543ce9ce133c84792ed4b/logs?region=us-east-1
