### ISSUE TITLE
Bump to webpack ^v5 and upgrade webpack-dev-server

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2783]
# Summary
The blacklight app still utilizes a webpack version 4.  Management app is already on a 5+ version of webpacker & webpack-dev-server.  This ticket is for upgrading these packages in Blacklight.  Created based on comments in #2767

<details>

* Web pack - fix unmet peer dependence with universal viewer and web pack-dev-server 
    * warning "universalviewer > @iiif/iiif-av-component > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
    * warning "universalviewer > @iiif/iiif-av-component > less-loader@7.3.0" has unmet peer dependency "less@^3.5.0 || ^4.0.0".
    * warning "universalviewer > @iiif/iiif-av-component > less-loader@7.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
    * warning "universalviewer > @iiif/iiif-av-component > style-loader@2.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
    * warning "universalviewer > @iiif/iiif-av-component > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
    * warning "universalviewer > pdfjs-dist > worker-loader@1.1.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
    * warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
    * warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".

</details>

**Acceptance**
- [ ] upgrade webpack
- [ ] upgrade webpack-dev-server

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1028

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.8](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.8)

**Comment by K8Sewell** [comment]
UV is still working as expected.  Will promote to UAT.



![Image](https://github.com/user-attachments/assets/e7e49809-b306-4071-b6ad-5272e2e203c8)
