### ISSUE TITLE
Bump to omniauth v2.1.0 and fix breaking changes

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2784]
Created as per Kait's comments in #2767.

Bump to omniauth  v2.1.0 and fix breaking changes

**Acceptance**

**Comment by jpengst** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1031

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.9](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.9)

**Comment by K8Sewell** [comment]
Able to successfully log in on Test.  Will promote to UAT.



![Image](https://github.com/user-attachments/assets/e5b0b5a4-e673-4122-bd5b-65e7e48ed27f)

**Comment by laurenb33** [comment]
Logged in to UAT successfuly! Thanks JP and Kait - ready to close!

![Image](https://github.com/user-attachments/assets/346da97b-2669-4756-b8d4-42f154f86ea0)
