### ISSUE TITLE
Resolve or clear alerts - Camerata Dependabot Alerts

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2785]
Created as per Kait's comments in #2767.

Resolve or clear alerts -- [Camerata Dependabot Alerts](https://github.com/yalelibrary/yul-dc-camerata/security/dependabot)

**Acceptance**

- [ ] Alerts cleared or resolved

**Comment by K8Sewell** [comment]
PRs ready for review:
* Camerata - https://github.com/yalelibrary/yul-dc-camerata/pull/381
* Management - https://github.com/yalelibrary/yul-dc-management/pull/1413
* Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/1027

**Comment by K8Sewell** [comment]
Deployed to Test with Blacklight release [v1.62.7](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.7) and Management release [v2.70.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.9)

**Comment by sshetenhelm** [comment]
As far as I can tell, everything is behaving as expected. I'm comfortable bumping into UAT.

**Comment by laurenb33** [comment]
Both UAT MGMT and UV are behaving as expected - ready to close!
