### ISSUE TITLE
Migrate 2016 OwP Objects from MS 2004 into UAT (PID 39)

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2787]
**Story**
Migrate 2016 parent objects from the Kissinger MS 2004 collection (PID 39) from FindIt to DCS.
Parents OIDs in this attached file: 
[MS2004_ForMigration.csv](https://github.com/yalelibrary/YUL-DC/files/14744226/MS2004_ForMigration.csv)

**Acceptance**
- [x] Export image files from Fedora
- [x] Import image files into the DCS pairtree
- [x] Generate list of Parent OIDs (use list above)
- [x] Import the objects into DCS UAT into the MSSA admin set as Private
- [x] Import OCR files into DCS and update full text status
- [x] Audit images
- [x] Audit OCR
- [ ] Audit parents for ArchivesSpace information
- [x] Create backlog ticket for PROD migration

**Comment by MaggieZhaoYale** [comment]
Create parents object issues:  failed to convert PTIFF due to Expected file originals  xxxx not found.

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm It looks an issue in UAT. I tried to create one in prod, it went through fine.

**Comment by MaggieZhaoYale** [comment]
162/1944 parents still have some expected original ptiff not found on S3, even though these images are in the pairetree. 
https://collections-uat.library.yale.edu/management/batch_processes/2004

**Comment by sshetenhelm** [comment]
Looking at 14863855

In MGMT UAT, the Title in the JSON is 
```
"title": [
    "Zo-Zu, Image 1”
```

Which is a child of parent 12479629, which was created in MGMT UAT but has 0 child images generated due to missing images. The child OID for this is 14863855 in MGMT UAT; however, in Ladybird, it is 17488697.

I will review more of these failed parents to see if other similar things are happening. However, I don’t know why the child OID is different from Ladybird.

**Comment by sshetenhelm** [comment]
Deleted 381 parents that were actually LB children - https://collections-uat.library.yale.edu/management/batch_processes/2036

**Comment by MaggieZhaoYale** [comment]
> Looking at 14863855
> 
> In MGMT UAT, the Title in the JSON is
> 
> ```
> "title": [
>     "Zo-Zu, Image 1”
> ```
> 
> Which is a child of parent 12479629, which was created in MGMT UAT but has 0 child images generated due to missing images. The child OID for this is 14863855 in MGMT UAT; however, in Ladybird, it is 17488697.
> 
> I will review more of these failed parents to see if other similar things are happening. However, I don’t know why the child OID is different from Ladybird.

The parent 12479629 has 0 child images, its 74 children are archivalDigitized, and all have images.

**Comment by sshetenhelm** [comment]
The following parents have 0 child images: 
12479629 (the problematic _Zo-Zu_ parent mentioned above)
12479863
12481219
12481487

The following parents are missing 1 child image: 
12482030 - missing child order 57, oid 14775661
12482044 - missing child order 27, oid 14740525
12482081 - missing child order 140, oid 14759134

I will check Ladybird to see if images were attached to these in Ladybird/FindIt.

**Comment by sshetenhelm** [comment]
**ONE:** 
@MaggieZhaoYale could you please try and pull in the following three children? 
12482030 - missing child order 57, oid 14775661
12482044 - missing child order 27, oid 14740525
12482081 - missing child order 140, oid 14759134

If they won't migrate, I'll see if we can get original images from elsewhere.

**TWO:** 
We will address the three parents with 0 images in UAT when we migrate to PROD, due to discrepancies between OIDs across Ladybird UAT and PROD.

**THREE:** 
@MaggieZhaoYale , could we start pulling in text files for these objects, when you have a chance? Thank you!

**Comment by MaggieZhaoYale** [comment]
@sshetenhelm Although the images of the above 3 can be dowloaded from Fedora, all have conversion issue. e.g. https://collections-uat.library.yale.edu/management/batch_processes/2081/parent_objects/12482081/child_objects/14759134

**Comment by sshetenhelm** [comment]
Pulled three child images from Preservica--they are also having file issues. Have asked Josh if he knows of any other copies of these scans. We may need to bookmark these for solving in PROD later, especially if we need to have the pages re-scanned.

**Comment by sshetenhelm** [comment]
Working through OCR for partial text objects.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale Could you please re-try migrating the text files for these parents? Thank you!


[MS2004-OwP-None.csv](https://github.com/user-attachments/files/16787295/MS2004-OwP-None.csv)

**Comment by sshetenhelm** [comment]
After comparing UAT to Aspace, it looks like we have 73 outstanding MS 2004 objects that were not migrated. 1 is OwP (12482156), 72 are public.

csv: [MS2004-Additions.csv](https://github.com/user-attachments/files/16948782/MS2004-Additions.csv)

Outstanding actions:

- [ ] Attempt to re-migrate OCR for MS2004-OwP-None.csv (in previous comment)
- [ ] Migrate 73 outstanding parents as listed in MS2004-Additions.csv
- [ ] Provide outstanding OCR files 
- [ ] Add Aspace uris 
- [ ] Get stakeholder approver
- [ ] Migrate to PROD

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/batch_processes/2202 please ignore 140 failed parents, which were deleted. No ocr was found for the 73 parents.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale  First round of replacement OCR .txt files (~10,714) available at: FC_YULDCS-807001-YUL > DCS_MaggieandSummer > Kissinger_OCR > MS2004-01

- [ ] Ingest replacement child OCR files from above location (Maggie)
- [ ] Run 'Update FullTextStatus' batch process (Summer)

**Comment by sshetenhelm** [comment]
Next files: FC_YULDCS-807001-YUL > DCS_MaggieandSummer > Kissinger_OCR > MS2004-02

- [ ] Ingest replacement child OCR files from above location
- [ ] Run 'UpdateFullTextStatus' batch process with csv: [MS2004-02.csv](https://github.com/user-attachments/files/17262278/MS2004-02.csv)

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale ! MS2004-03 is uploaded in the same place, and MS2004-04 should be transferred into our share by the end of day (Mon 10/14)

- [ ] Ingest replacement child OCR files from above location for **MS2004-03**
- [ ] Run 'UpdateFullTextStatus' batch process with csv: [MS2004-03.csv](https://github.com/user-attachments/files/17363822/MS2004-03.csv)

- [ ] Ingest replacement child OCR files from above location for **MS2004-04**
- [ ] Run 'UpdateFullTextStatus' batch process with csv: [MS2004-04.csv](https://github.com/user-attachments/files/17363876/MS2004-04.csv)

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale ! Here are the next two batches; the folders are in the same location on the shared drive: 

- [ ] Ingest replacement child OCR files for MS2004-05
- [ ] Run 'UpdateFullTextStatus' batch process (Summer)
- [ ] Ingest replacement child OCR files for MS2004-06
- [ ] Run 'UpdateFullTextStatus' batch process (Summer)

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale !!!

We are down to 10 OwP objects that have 'None' for OCR. Not sure how I missed those but I will wrangle the files. 

~ In theory ~, all the partials should be in FC_YULDCS-807001-YUL > DCS_MaggieandSummer > Kissinger_OCR > MS2004-Partials

- [ ] Ingest replacement child OCR files for MS2004-Partials
- [ ] Run 'UpdateFullTextStatus' batch process (Summer)

Once we do the partials, I'll look at the entire collection again and provide both the missing Text = None and any remaining Text = Partial

**Comment by sshetenhelm** [comment]
Down to:
10 OwP objects with Full Text = None
4 OwP objects with Full Text = Partial

Gathering files now.

**Comment by sshetenhelm** [comment]
@MaggieZhaoYale - The final OCR files are in FC_YULDCS-807001-YUL > DCS_MaggieandSummer > Kissinger_OCR > MS2004-FINAL

Could you please upload them when you have a chance?

- [ ] Upload final OCR files (Maggie)
- [ ] FullText batch process (Summer)
- [ ] Compile master list of missing OCR files (missing from shared drive) and broken child images (Summer)
- [ ] Pass to stakeholder for QA (Summer)

**Comment by sshetenhelm** [comment]
**Totals** 
* 2016 Parents in Management
* 2008 parents in Blacklight

**Discrepancy of 8 parents due to the following:** 
_Corrupted image files on server; requesting/have requested rescans_ 
12479779 - Missing child order 143, oid 15035394
12482030 - Missing child order 57, oid 14775661
12482044 - Missing child order 27, oid 14740525
12482081 - Missing child order 140, oid 14759134

_Missing all images; Different OIDs in Ladybird UAT vs PROD_
12479629 - Box 115 | Folder 7
12479863 - Box 145 | Folder 5
12481487 - Box 213 | Folder 9

_Missing some images_
12482156 - Box 35 Folder 2 - Missing images for children 74 and 83 through 93 

I will pass collection off to stakeholder to review and ask if there is any reason why we can't provide the images for the last four parents (ex. are images missing for a _reason_?)

**Comment by jillpe** [comment]
Waiting for feedback from others

**Comment by sshetenhelm** [comment]
Thanks Maggie! After running 'recreate ptiff' the three parents attached to those children are now working :) 

Ready to close. Migration to PROD will be tracked in #2974
