### ISSUE TITLE
[Discuss] Investigate SPA results - Jquery

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2790]
We need to investigate and discuss how to apply the recommendations from the recent DCS SPA - starts on pg. 3 of the report (the link is in the Teams channel).

The second recommendation is to upgrade to the latest verision of jquery.

**Important Links/Info from @mikeapp:**
jquery-rails includes versions 1, 2, and 3 for backward compatibility, so we would need to fork the gem and remove it. There is an outstanding PR for this.
https://github.com/rails/jquery-rails/blob/master/VERSIONS.md
https://github.com/rails/jquery-rails/pull/298
UV uses JQuery 3.x so should not be impacted

## Acceptance
- [ ] one-paragraph explanation of why we want an exception to this work

**Comment by laurenb33** [comment]
In the DCS SPA report, the second migration recommendation was that the identified library Jquery version should be upgraded. The development team would like to apply for an exception from this requirement because the tool, Universal Viewer, for DCS Blacklight already uses JQuery 3.x. The response in the report found the outdated JQuery v1.12 because the Jquery-rails gem includes versions 1 and 2 for backward compatibility. It is possible to fork the gem and make the modifications needed, but the community of developers for the Jquery-rails gem are currently working on a fix to stop supporting versions 1 and 2: https://github.com/rails/jquery-rails/blob/master/VERSIONS.md This would be a heavy lift for our team to take on and maintain, especially when a fix is anticipated to be released soon. Overall, the development team would like to apply for an exception for upgrading JQuery because the DCS currently uses the most recent version.

**Comment by DraxIndustries79** [comment]
Next:

- Mike will check these
- Lauren will contact George

**Comment by laurenb33** [comment]
I submitted this exception on 5/6 - ready to close!
