### ISSUE TITLE
Refactor Logic for Permission Request Status

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2791]
Permission Request Status is currently using Boolean values. To better suit OwP, we would like to change the options of true/false to approved, denied, and pending.  Default as "Pending."

## Acceptance
- [x] change the options of true/false to approved, denied, pending, and expired.

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/1367

**Comment by jpengst** [comment]
Deployed to Demo v2.68.6 and Blacklight OwP_FeatureBranch

**Comment by sshetenhelm** [comment]
Approved, denied, and pending work. Gave myself permission for an object for only today; will verify tomorrow if "Expired" status works as well for objects moving forward. 

Past expirations still have the "approved" status (although that's not an issue if it works moving forward).

**Comment by sshetenhelm** [comment]
Lauren made ticket  [#2819](https://github.com/yalelibrary/YUL-DC/issues/2819) for the Expired status, so I think this is ready to close.
