### ISSUE TITLE
View Full Text for OwP Objects

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2795]
## Summary  
Full Text has a before_action auth check for rendering the full text. Auth checks between object access and full text access are fundamentally different. They both use the same `client_can_view_digital?` method, but they need to play nicely with each other. 
  
## Acceptance Criteria  
- [x] Full Text can render for OwP objects

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/999

**Comment by sshetenhelm** [comment]
@mikeapp may want to look this over :)

**Comment by K8Sewell** [comment]
Deployed to Demo with [this commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/84aadaaa9493438bcd4e377a7898051cfd46aac8) into the OwP_FeatureBranch

**Comment by sshetenhelm** [comment]
Looks good on Demo!

Ready to close :)
