### ISSUE TITLE
"Open with Permission" Language for DCS Help Guide

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2798]
**Story**
With the release of the Open with Permission feature, we need to explain to users what 'Open with Permission' means. We should draft language and add it to the 'Help Guide' on Blacklight located at `help_guide`. 

This ticket is just for the language. We will create a second ticket to add the language online.

**Acceptance**
- [x] Draft user-focused language explaining Open with Permission Visibility  
- [x] Create ticket to add to Blacklight feature branch

**Comment by sshetenhelm** [comment]
Suggestion for language to be added in the "What does it mean if I can't view an item in Digital Collections?" section, underneath the first two paragraphs about Yale Community Only objects: 

_Additionally, some materials may only be viewed online with permission. These materials also feature a thumbnail image identify them as only available with permission, and they fall into the Access category of Open with Permission. Some collections, such as the Henry A. Kissinger Papers, require approval from collection representatives outside of Yale University. Collections that are Open with Permission may require that patrons agree to a set of Terms & Conditions regarding use. 

Yale users may login using their Yale NetID and click on the request form link on an item’s page to request permission to view an object. Non-Yale patrons can create an account by clicking “Log In” at the top of the page and following the ‘Sign up’ link. Once logged in, patrons can click on the request form link on an item’s page to request permission to view an object.

In the “Notes” section of the request form, patrons should provide as much information as possible about the research they are undertaking and why they would like to view the selected object. More information allows collection approves to make a better informed response to a patron request._ 

@alisonclemens what do you think of the above? Should we ask public services for their thoughts?

**Comment by alisonclemens** [comment]
Looks good to me; just a few small comments/questions. 

For the last paragraph, is it a necessity on the Kissinger side that we want people to include as much information as possible? Or would it be possible to change this around to just say what kinds of information people should include in that field?

I've also made some minor suggested edits (**bolded**) below, mostly to align with the second person language in the rest of the Help Guide:

Additionally, some materials may only be viewed online with permission. These materials also feature a thumbnail image identifying them as only available with permission, and they fall into the Access category of Open with Permission. Some collections, such as the Henry A. Kissinger Papers, require approval from collection representatives outside of Yale University. Collections that are Open with Permission may require that patrons agree to a set of Terms & Conditions regarding use.

**If you are a Yale Digital Collections user, you may log in using your Yale NetID and click on the request form link on an item’s page to request permission to view an object. If you are a non-Yale Digital Collections user, you** can create an account by clicking “Log In” at the top of the page and following the "Sign up" link. Once logged in, **you** can click on the request form link on an item’s page to request permission to view an object.

In the “Notes” section of the request form, **we ask that you please provide** as much information as possible about the research **you** are undertaking and why **you** would like to view the selected object. More information allows collection **approvers** to make **an informed** response to **your** request.

**Comment by sshetenhelm** [comment]
Emailed stakeholders for feedback.

**Comment by sshetenhelm** [comment]
Created #2802 for actual work of adding language
