### ISSUE TITLE
Wireframe: Link to Permission Requests page on Blacklight

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2799]
**Story**
We need to decide how users will navigate to the [Permission Requests page](https://collections-demo.library.yale.edu/permission_requests) in Blacklight. Is this link in the header, next to Bookmarks? Is it located on the home page? In the footer? 

**Acceptance**

- [x] Decide location for link
- [x] Create some sort of mobile-first wireframe / mock-up / diagram of where link is to go
- [x] Create tickets for engineering work

**Comment by tmacmath** [comment]
Okay, I didn't realize at first that this link was for testing purposes only - I will rethink the placement based on functionality when all features have been added. For now, we can just place the link below the Bookmark selector. 

![Image](https://github.com/yalelibrary/YUL-DC/assets/9658383/d95561f9-d77f-4534-b402-2274a0a5a180)

**Comment by sshetenhelm** [comment]
I think all the "major" features have been added on Demo, at least from the user perspective, so having something that works for testing but is also "usable-enough" for an MVP is the goal. Apologies if I didn't make that clear in our earlier conversations. I worry with the placement above, that users will get confused about whether or not something needs to be bookmarked to be requested, or if everything needs to be requested. 

I was thinking of something more along the lines of putting it in the header next to bookmarks, as such: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/dc203f87-fa21-4d61-8e24-a56689fa1c88)

Or linking to it directly from the Bookmarks page, as such: 
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/0046c1af-bfbd-4c15-8791-4c4c6caa6866)

**Comment by sshetenhelm** [comment]
@tmacmath Does this help to add more context? 

**Scenario 1:** 
1. User navigates to DCS.
2. User wants to check their permission requests table to see what has been approved and access their requested objects.
3. Then, user wants to navigate to bookmarks list to request access to more objects.

**Scenario 2:** 
1. User performs a search in DCS.
2. User sees an object they want to request. 
3. User clicks the bookmark checkbox to add to their list directly from the search results.
4. User clicks on an object and makes a request.
5. Then, user wants to navigate to permission requests page to confirm it was added to list of requests. 


**Scenario 3:**
1. User performs a search in DCS.
2. User sees an object they want to request.
3. User clicks on the object but does not add the object to their Bookmarks list. 
4. User requests the object.
5. User returns later and wants to see the status of their request.

Collections such as Kissinger only allow a user to make 10 access requests at one time. So, the Bookmarks feature is where they can "hold onto" all the objects they want to request, and then work from that scratch sheet to submit the requests as they are able to.

However, Bookmarks can also be used as a list of favorites for all users, regardless of if they are requesting access or not. 

Additionally, users do not have to utilize the Bookmarks list to submit a request, so they may need a way to access their requests without having to go through Bookmarks. 

NOTE: This also makes me think we could add a link to the requests page from the notification that a request has been submitted, in addition to a link in a more "general" area. Ex: 

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/815c6517-7db8-44f0-ba53-b0d3134e6204)

**Comment by sshetenhelm** [comment]
After conversation yesterday, the following tickets for Blacklight updates have been created:

#2820 - Update pending request message in Blacklight, add link
#2821 - Add Access Requests link to header and update Bookmarks
#2822 - Updates to Permission Requests page
#2823 - Update "Bookmarks" language to "Saved Items"
