### ISSUE TITLE
Add OwP language to DEMO Help Guide

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2802]
**Story**
We would like the following language added to the 'Help Guide' on DEMO Blacklight located at `help_guide`. The language should appear in the ["What does it mean if I can't view an item in Digital Collections" section](https://collections-demo.library.yale.edu/help_guide#cant-view-in-dc) underneath the image and the caption that states "The Feedback link in the footer of the Digital Collection website."

**Language:** 
Additionally, some materials may only be viewed online with permission. These materials also feature a thumbnail image identifying them as only available with permission, and they fall into the Access category of Open with Permission. Some collections, such as the Henry A. Kissinger Papers, require approval from collection representatives outside of Yale University. Collections that are Open with Permission may require that patrons agree to a set of Terms & Conditions regarding use.

If you are a Yale Digital Collections user, you may log in using your Yale NetID and click on the request form link on an item’s page to request permission to view an object. If you are a non-Yale Digital Collections user, you can create an account by clicking “Log In” at the top of the page and following the "Sign up" link. Once logged in, you can click on the request form link on an item’s page to request permission to view an object.

In the “Notes” section of the request form, we ask that you please provide as much information as possible about the research you are undertaking and why you would like to view the selected object. More information allows collection approvers to make an informed response to your request.

**Acceptance**

- [x] Above language added to help guide between the caption "The Feedback link in the footer of the Digital Collections website" and the header "How do I request to view an item in person?"

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1000

**Comment by K8Sewell** [comment]
Deployed to Demo with this [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/2381ea61370988c7f95c7b70d82b46eb1df82108) into the OwP_FeatureBranch

**Comment by sshetenhelm** [comment]
Looks great on DEMO! Thank you!

Ready to close.
