### ISSUE TITLE
Display Terms and Conditions Bug

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2807]
## Summary  
When creating a new Permission Set Term and Condition, the term will not display in Blacklight if the first line in the dialogue box is empty.
  
Example:  

![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/49dfc76a-f99c-4550-87f4-acf6aa673da6)

  
This term will not display because of the empty line in the dialogue box.  
  
## Acceptance Criteria  
- [x] Terms will display in Blacklight even if there is a blank line in the dialogue box

**Comment by jpengst** [comment]
Yeah, I was thinking this would be a management ticket. I think it would be some type of action in management that would either prevent the terms from being saved with an error message, or we would have some type of before_save action that will automatically remove any extra lines before saving the data.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1391

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.5)

**Comment by K8Sewell** [comment]
Appears to be working as expected.  Will bump to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/411981ad-6ab5-4465-805d-feb19a8752e3)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/c8ea1a65-7bef-48c0-8bb6-a6cd295b8d86)

**Comment by jpengst** [comment]
This bug fix is for displaying in Blacklight. Confirmed to be working:  
<img width="1163" alt="image" src="https://github.com/yalelibrary/YUL-DC/assets/24666568/1487f1e8-1f1e-483e-b961-cb2c87bb810e">

**Comment by K8Sewell** [comment]
Failed to deploy worker containers so redeploying to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/10a8af22-6ba8-4879-bd8d-2b7ccd1dd71c)

**Comment by K8Sewell** [comment]
Waiting to deploy to UAT until testing for #2824 is completed.

**Comment by laurenb33** [comment]
I changed the Cats TC with a blank first line and was able to view the TC in UV! :)

![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/cae80ffe-db34-4b6f-b01a-f7884b27eaa8)

![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/28ea66fc-70ea-4992-a6ea-8a8c35ebe04f)
