### ISSUE TITLE
'Back' link on Permission Request page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2810]
**Story**
Staff may want to review permission requests without make changes. They should have the ability to click a "Back" link to return to the Permission Request data table page.

Example:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/00c2f710-d6c5-46f7-93fb-6ccd943dc5e9)

**Acceptance**

- [x] Add "Back" link to bottom of Individual Permission Request page
- [x] "Back" link navigates to Permission Request data table page

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1375

**Comment by K8Sewell** [comment]
Deployed to Demo and Test with release [v2.68.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.8)

**Comment by sshetenhelm** [comment]
Looks good to me!

Ready to close, as we don't have any permission requests on Test.
