### ISSUE TITLE
Add User Email to Individual Permission Request Page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2811]
**Story**
There may be instances where a permission set Approver would like to request more information from an individual regarding their request to view an object. To facilitate communication, we would like to add the User Email to the Individual Permission Request page. This information should display underneath “User ID” and above “User Note.” 

Screenshot:
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/c22e62ad-68ca-487b-9bb7-b549020de734)

**Acceptance**

- [x] User Email row added to table
- [x] User Email row displays email that correctly corresponds with the user
- [x] User Email row is underneath User ID and above User Note
- [x] Add "copy" button that copies email address to clipboard
- [ ] Tell your colleagues how you did it

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1382

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.1)

**Comment by sshetenhelm** [comment]
Email is visible and copy/paste functionality works! However, for sponsored identities, the email is no-email@yale.edu, which is interesting.

**Comment by sshetenhelm** [comment]
Received feedback that it is very uncommon for researchers with sponsored identities to be requesting access to Kissinger. I think that's why we threw this in waiting? If so, I don't think that needs to be a blocker for us to complete this ticket.
