### ISSUE TITLE
Only SysAdmins can create Permission Set

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2812]
**Story**
Currently, all Management users have the ability to create a Permission Set. However, because they are not System Admins, they create sets but cannot access or edit those sets because they are not Administrators of this set. Additionally, some Management users will not have Management Edit access, so they should not have the ability to create Permission Sets.

To solve this, we would like only System Administrators to have the ability to create a new Permission Set. We would also like the 'Create New Permission Set' button to be suppressed for Non-SysAdmin users (if possible--but we are open to other suggested solutions).

**Acceptance**

- [x] Non SysAdmin Management users cannot create new Permission Set
- [x] "Create New Permission Set" button is suppressed for Non SysAdmin users

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1376

**Comment by K8Sewell** [comment]
Deployed to Demo and Test with release [v2.68.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.8)

**Comment by K8Sewell** [comment]
Cannot see 'Create' button on Permission Sets page as a non Sys Admin.  Will move to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/94ab50ce-8785-47d8-9901-cc5396808d40)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thanks!

Ready to close :)
