### ISSUE TITLE
Add Permission Set Label to Parent Object Page data table

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2815]
**Story**
For parent objects with a Visibility of Open with Permission, staff would like to see the Permission Set Label in the Parent Objects data table page (`parent_objects`). This will allow staff to easily view all objects in one permission set. 

We would like this to be added as a column to the data table, located after the ‘Visibility” column but before the ‘Extent of Digitization’ column. 

We would like this to display as the Permission Set Label, as that is what is viewable in the individual Edit Parent Object Page drop-down menu.

**Screenshot**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/ea2d8638-cbbb-4278-bed4-c7d3a2bda75f)

**Acceptance**

- [x] “Permission Set Label” column added to Parent Object Page data table
- [x] Column is located after “Visibility” column but before “Extent of Digitization” column
- [x] Data in column accurately displays for objects

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1377

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.68.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.9)

**Comment by K8Sewell** [comment]
Looking good on Test and Demo

# Screenshots

### Test

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/9456994f-0c3e-49e3-95ad-3e8ea3eaf72e)




### Demo

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/b56d3c2a-fe34-457b-a223-5dfcfcf29ca3)

**Comment by sshetenhelm** [comment]
Looks great on UAT! Thank you so much, this is super helpful.

Ready to close.
