### ISSUE TITLE
Remove eyeball icon link from Request ID

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2816]
**Story**
In the Permission Requests data table, in the ‘Request ID’ column, there is an eyeball icon that links to the individual permission request page. 

Because eyeballs are used elsewhere in Management to link to Blacklight, we would like to remove the eyeball icon and link from the Request ID column of the Permission Requests data table. 

We like the behavior of the Request ID number linking to the Individual Permission Request page, as this is similar to the Batch Process table behavior. 

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/a757b45f-65e8-4465-9354-34a3d697288a)

**Acceptance**

- [x] Remove eyeball icon link from Request ID column of Permission Requests table

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1374

**Comment by K8Sewell** [comment]
Deployed to Demo and Test with release [v2.68.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.68.8)

**Comment by sshetenhelm** [comment]
Looks good! :)
