### ISSUE TITLE
Fix Extra amp; in Sanitize

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2818]
# Summary
During other tickets work a it was discovered in sanitize methods that they add an amp; after ampersands.

# Related Tickets
#2767 
#2780 

# Acceptance Criteria
- [x] fix sanitize methods so they do not add an extra amp; after ampersands

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/4ce7a0c8-e4c5-4c2f-83de-1e12ce28fe2a)

https://github.com/yalelibrary/yul-dc-management/pull/1348/files#diff-487c6db6ac726f34f1a91ffbae954366637de8a97d2668cd14420b27256c4569

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1408

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.6)

**Comment by K8Sewell** [comment]
Working as expected.  Will promote to UAT.

### Before



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/cb22cd9f-077e-4fe4-972a-001b352f3ddc)




### After


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/1790c90c-d14a-408c-bfe0-5164aaf7e6a3)

**Comment by laurenb33** [comment]
Unsure if this ticket is just for metadata - I tested putting in a request with & and the extra amp; shows:
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/27328ad0-b1d1-4f0f-8a1b-be947467adf0)

**Comment by sshetenhelm** [comment]
Confirmed works in UAT but requires IIIF manifests to be regenerated so we may see this a bit in PROD after deploying until we can update all the manifests.
