### ISSUE TITLE
Updates to permission_requests page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2822]
**Story** 
We would like to remove the “Back to Bookmarks” button from the permission_requests page. Additionally, we would like to change the header “Digital Access Requests” to read just “Access Requests”

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/62044f60-fded-4278-ab0e-cd5423385e11)

**Acceptance**

- [x] Back to Bookmarks button removed
- [x] Word “Digital” removed from header, so now header reads “Access Requests”

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1006

**Comment by K8Sewell** [comment]
Deployed to Demo with [OwP_FeatureBranch](https://github.com/yalelibrary/yul-dc-blacklight/pull/931)

**Comment by sshetenhelm** [comment]
Looks good! Thank you!

Ready to close
