### ISSUE TITLE
Original File Not Found

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2824]
# Summary
There are presently issues with ingest in PROD and UAT.  The details of the issues in production are detailed in the Original Story section below and are being addressed in ticket #2801 .  In UAT parent objects are pulling in metadata but are also not pulling in children.  Details of the ingest issue with UAT are in ticket #2779 .  Both environments are not able to successfully create children objects.

<details>

**Original Story**

Some Preservica objects are refusing to ingest in PROD using the Create Parent Objects batch process. Common characteristics of these objects include:
* They show as "pending, or parent deleted" > Failed in the Batch Process table
* They successfully pull in metadata from ArchivesSpace
* They show 0 children on the individual parent object page in Management 
* Pressing the "Synchronize Child Objects" button pulls in no children
* Attempting to re-ingest as new objects pulls in 0 children 

36 Papyri objects have been affected as well as 1 Colonel House object. 

Example Papyri [33195018](https://collections.library.yale.edu/management/parent_objects/33195018)
Example Col. House [33196257](https://collections.library.yale.edu/management/parent_objects/33196257)

**Original file not found**

In many cases the issue came down to the original file being not found when the GeneratePtiffJob is triggered.  For some reason the system is changing the value of the env var ACCESS_MASTER_MOUNT during the create child process which is where the original file lives that is needed to generate the derivative ptiffs for UV.

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/801b4a56-77fa-4f4c-b9f9-f50a9027ca61)

</details>

**Acceptance**
- [x] Check the DCS logs to see if we can locate at what step the process halts - when investigating the issues on production with Maggie and Martin nothing stood out as a culprit
- [x] Check the connection between Metadata Cloud to see if it is working correctly
- [x] Check the objects in Preservica to see if they have been requested by the Management App (if necessary)
- [ ] Re-enable the successful creation of child objects and their corresponding ptiffs

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1372/

### Below is last comment from ticket #2779 

PR that will fix the goodjob errors we were seeing in the worker logs on Test and UAT - https://github.com/yalelibrary/yul-dc-management/pull/1372/ (it was deployed on Test and can be redeployed there if desired)

Currently investigating two things:
* why does the system think that the access masters for a single parent live on both S3 and the shares at Yale 


![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/7d32d796-e3f5-49be-a4e0-c9a9bea8ba2c)




* why are we now getting this error in the worker logs 



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/2b202b71-c865-41f6-8335-1f9879137292)

https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/yul-dc-test/services/yul-dc-test-worker/tasks/c3139a9790a543ce9ce133c84792ed4b/logs?region=us-east-1

**Comment by K8Sewell** [comment]
Deployed to Test with PR - [1390](https://github.com/yalelibrary/yul-dc-management/pull/1390)

**Comment by K8Sewell** [comment]
After testing with a larger sample there is still a persistent file not found error that keeps many child records from successfully generating ptiffs.  Continuing research.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/d54b29de-32bf-4077-b35c-9e63056d1aa1)

**Comment by K8Sewell** [comment]
After pairing with Martin and Maggie and getting help from Keith to get the spike branch deployed to UAT this issue is ready for testing again.  The fix in the spike appears to be resolving the file missing issue.

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/b349c883-8913-42da-b98c-ad3716720077)

**Comment by sshetenhelm** [comment]
This previously-failed for PTIFF error object worked after this fix was put in place and I pressed the "resync with preservica" button - https://collections-uat.library.yale.edu/management/parent_objects/901623981

I got the checksum error for this one but no "missing ptiff" error (it's also for a huge object - a house diary with like 300+ pages) - https://collections-uat.library.yale.edu/management/batch_processes/1987/parent_objects/901624011

Checksum error for this as well, just one TIF file: https://collections-uat.library.yale.edu/management/batch_processes/1990/parent_objects/901624091

Looks like Lauren was able to get a batch from LWL to work though? https://collections-uat.library.yale.edu/management/batch_processes/1983/parent_objects/901623998

**Comment by laurenb33** [comment]
Confirming that my batch for Wal worked :)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1390

**Comment by K8Sewell** [comment]
Deploying to Demo and UAT with release [v2.69.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.7)

**Comment by laurenb33** [comment]
The batch Summer did on Friday for objects with a source of Ladybird is showing the PTIFF not found error:
https://collections-uat.library.yale.edu/management/batch_processes/2004

![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/56941df6-73b6-4fd1-845c-c0c6e4c2d367)

**Comment by sshetenhelm** [comment]
That batch was started before the deploy. I'm going to delete those parents and try and re-ingest.

**Comment by laurenb33** [comment]
The two objects I ingested yesterday worked!!!!
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/4a22cb45-75e2-48d2-bde7-b39acd759479)
