### ISSUE TITLE
Require Perm Set Key if OwP Object

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2827]
In a .csv for batch process ingests, if  "Open with Permission" is the item's intended visibility the Permission Set Key name needs to be included in the CSV. After the .csv is submitted, the authoritative JSON will also be checked (along with the csv) to see if the user has permission to change or modify the objects in a particular admin set. If the Perm Set Name is not included in the .csv, an error should be thrown in MGMT to let the user know that it needs to be included.

Acceptance:
- [x] Add Permission Set Key Name for Batch Process create an object
- [x] Add check for the authoritative JSON field: itemPermission
- [x] Throw an error in if the Perm Set Key name is not included in the .csv
- [x] Throw an error if the user does not have permission to edit the OwP set 
- [x] Ensure that Preservica objects can be set to OWP - moved to ticket #2836

**Comment by K8Sewell** [comment]
PR working it's way through CI.  Is the language on these screenshots ok or would a change be desired?

# Screenshots

### Not in CSV Error
![image](https://github.com/yalelibrary/yul-dc-management/assets/36549923/6f64d4af-1f1f-487d-a985-a2e5d9366f44)

### Permission Error

![image](https://github.com/yalelibrary/yul-dc-management/assets/36549923/e042ecad-5019-441a-ba56-28214b11e953)

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.5)

**Comment by K8Sewell** [comment]
Bumping to UAT so able to test with mssa Admin Set



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/3d5968eb-86a5-4868-8127-07c7c42d1159)

**Comment by K8Sewell** [comment]
Waiting to deploy to UAT until testing for #2824 is completed.

**Comment by K8Sewell** [comment]
Deploy is live on UAT for testing

**Comment by sshetenhelm** [comment]
Confirmed this works! Checked for both key and permissions. Thank you!

Ready to close :)
