### ISSUE TITLE
Ingest Col. House Diaries OCR

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2829]
**Story**
The 10-object collection Colonel House Diaries (MS 466 Series) was recently ingested into DCS from Preservica. This collection was originally hosted in CONTENTdm with attached OCR transcripts. We need to attach the OCR to the objects in DCS Prod.

- The files are located in `FC_YULDCS-807001-YUL > DCS_MaggieAndSummer > MS 466 ocr`
- There are 10 directories that are named with the parent OID. 
- Each directory contains .txt files that are named with the child OID.

Here is a .csv containing all the parent and child OIDs: [MS466-Children.csv](https://github.com/yalelibrary/YUL-DC/files/15323586/MS466-Children.csv)

The parents are: 
33192146
33196271
33195560
33196226
33196257
33195561
33196243
33196277
33196248
33195558

**Acceptance**
- [x] Attach the OCR for each of the 10 parents 
- [x] Run the 'Update Fulltext Status' batch process
- [x] QA in PROD 
- [x] Delete the OCR files from DCS_MaggieAndSummer

**Comment by MaggieZhaoYale** [comment]
https://collections.library.yale.edu/management/batch_processes/17077 'Update Fulltext Status"

**Comment by sshetenhelm** [comment]
Looks good in Prod! Hooray! Ready to close :)
