### ISSUE TITLE
[DISCUSS] FY 25 Work - Tech Debt - Camerata - Thurs 5/30

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2831]
**Story**
Our team has recognized that we need to address issues with Camerata as part of our FY 25 work. This ticket is intended to open the discussion about what work needs to be done.

See #2785 for a ticket about current alerts

Questions that arose during our Technical Debt Brainstorming Session:

- How does it help or hurt us?
- What does it do? 
- What does it do that we like/need? 
- How is it supported by Scientist? 
- Is the project maintained? 
- What's the lifespan? 
- What does it do that Terraform/Ansible do, and what is Camerata specifically needed for? 
- What is needed for developer machines vs. cutting releases?
- How do secrets populate into docker? 
- What sort of “lift” is needed to be able to use Camerata? 
- Would it be better to pivot to a different technology, and if so, what sort of "lift" is needed? 

Notes from Tech Debt discussion: 
It is basically just a wrapper for docker compose commands. Camerata is also a wrapper for AWS commands. We don’t want to add any features; this is potentially just our need for more understanding. 

**Acceptance**

- [x] Schedule a discussion to take place with pertinent team members (DevOps, Engineers, Tech Lead, Product Owner, anyone else interested)
- [ ] Collaborate on answers to the above questions
- [ ] Define our next steps & construct backlog tickets for that work

**Comment by DraxIndustries79** [comment]
Meeting 5/24
