### ISSUE TITLE
BUG: Access Requests Page Not Loading

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2839]
# Summary
Currently the route `/permission_requests` errors out with the generic rails error page.  

# Acceptance Criteria
- [ ] `/permission_requests` loads correctly

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/59d7990c-d33e-4bd3-be96-793ad03f2a1e)

**Comment by sshetenhelm** [comment]
Strange! I am able to see this and so were our testers today.

**Comment by jpengst** [comment]
Pulled from the logs on demo:  
```
App 11205 output: 2024-05-28 18:11:21.340976 I [11205:47860] [264ec37b-3865-4ee4-9846-ffbc8aa07194] (58.5ms) PermissionRequestsController -- Completed #index -- {:controller=>"PermissionRequestsController", :action=>"index", :format=>"HTML", :method=>"GET", :path=>"/permission_requests", :status=>500, :view_runtime=>0.0, :db_runtime=>0.34, :exception_object=>#<TypeError: no implicit conversion of nil into String>, :allocations=>32096, :status_message=>"Internal Server Error"}
```

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1393

This was an issue whenever a user had a request in an "Approved" state but no Access Until date. Blacklight didnt know what to do with the nil access_until date. I created this PR that adds a validation for permission requests. A request can no longer be saved successfully if a request has "Approve" selected, but no access date selected. The access date field will now be highlighted red if nothing is selected:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/3be0ae20-c0a8-4504-983c-cbbbd4dbb185)

**Comment by jpengst** [comment]
I also went into demo and added an access date to about 6 approved records that didn't have a date filled out. So that page should be fixed for everyone that was seeing the error :)

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.6)

**Comment by laurenb33** [comment]
I can see the page now! :)

![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/7463a4ab-aa51-45e4-98c3-1e8f0fd7508d)
