### ISSUE TITLE
Remove (TBD) from Permission Sets header

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2841]
**Story**
The Management permission_sets page has "(TBD)" after the “Permission Sets” header. We should remove "(TBD)".

**Screenshot**
![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/9469f109-b11a-4b99-a1c7-98802d73164d)

**Acceptance**
- [x] Remove text `(TBD)` from Management App `permission_sets` page header

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1394

**Comment by K8Sewell** [comment]
Deployed to Demo with release [v2.69.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.6)

**Comment by sshetenhelm** [comment]
Looks good in Demo! 

Could this get deployed to UAT as well, since the Management stuff is not in a feature branch? Thank you!

**Comment by laurenb33** [comment]
No TBD in sight on UAT! -
![Image](https://github.com/yalelibrary/YUL-DC/assets/143648448/340d3f07-efd0-4d44-8bfa-9e84f85d0dc4)
