### ISSUE TITLE
Prevent Permission Set Admin from Removing Self from Set

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2842]
**Story**
In the Management App, if a Permission Set Administrator removes themselves from a Permission Set, they cannot add themselves back. We would like Permission Set Administrators to be unable to remove themselves, but still retain the ability to move others.

This will prevent Permission Set Admins from accidentally removing themselves and having to request to be returned to power by a colleague. 

Additionally, this should help prevent “orphan” permission sets — sets without designated Administrators. 

**Acceptance**
- [x] Management users who are Permission Set Admins but not System Admins are unable to remove themselves as Administrators of a Permission Set
- [x] These Permission Set Admins retain the ability to remove other Approvers and Admins of their Permission Set

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1395

**Comment by K8Sewell** [comment]
Deploying to Demo and UAT with release [v2.69.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.69.7)
