### ISSUE TITLE
[BUG] Permission Request column 'Title' does not sort correctly

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2843]
**Story**
On the `permission_requests` page in Blacklight, each column of the table should sort in ascending and descending order. All columns except Title sort correctly. Title does not sort in ascending/descending alphabetical order, although the order does change when using the sort arrows.

**Video**
https://drive.google.com/file/d/1GrJYAsvXeYMbVMoiYue1lQDaqXOuWeur/view?usp=drive_link

We would like the column Title to sort in correct ascending / descending alphabetical order when using the sort feature.

**Acceptance**

- [x] Permission Request titles sort in Ascending Alphabetical correctly
- [x] Permission Request titles sort in Descending Alphabetical correctly

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1016

**Comment by K8Sewell** [comment]
Deployed to Demo with [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/d5d51fc1283eb304363eebb3e31ec1a17d41fff4)

**Comment by K8Sewell** [comment]
Investigating errors with deploy - [console output](https://ci.library.yale.edu/job/DigitalCollections/job/Cluster-Deploy/230/console)

**Comment by K8Sewell** [comment]
Title column is sorting as expected on Demo for me.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/0b6bb759-5da1-4609-86c4-af796ea70a37)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/3a5cabae-5c01-4c09-a9c7-28492acc4f4d)



And I'll make a ticket to fix the spacing on the sort arrows on the other columns.

**Comment by sshetenhelm** [comment]
Looks great in DEMO! Sorting correctly. Thank you!

Ready to close :)
