### ISSUE TITLE
Update OwP Request Confirmation messages in Blacklight

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2850]
**Story**
There are two places in Blacklight where we should update the confirmation messages that patrons see once they have submitted a request for permission.

ONE: 
The first is the page that displays immediately after a patron submits their form. Currently, a blue message that states “Your request has been submitted for review by Library staff” displays. We would like to update this language to:

`Your request has been submitted for review.`

The updated request removes the suffix “by Library staff.” This meets the Kissinger requirement of not implying that Yale library staff is making the decision.

TWO: 
The second is the message that displays on the individual parent object page when a request is pending. Currently, in place of the Universal Viewer is a blue box that states “Your request to access this item has been received. Thank you for your patience as we consider your request. You will be notified of the results of your request once a decision has been made. You can view all your requests on the Access Requests page.” We would like to update this language to:

`Your request to access this item has been received. Thank you for your patience as your request is considered. You will be notified via email of the results of your request once a decision has been made. You can view all of your requests and their statuses on your Access Requests page.`

We are adding “via email” to inform users of how to expect the approval notification, changing from active to passive voice to refrain from applying that "we" (as in "Yale") are the deciders, and adding “and their statuses” to indicate that there is a second way of seeing if a request has been approved or denied.

**Acceptance**

- [x] Text in banner that displays after a user submits a request form is updated to:

`Your request has been submitted for review.`

- [x] Placeholder text that displays on an individual parent object’s page when a request is pending is updated to: 

`Your request to access this item has been received. Thank you for your patience as your request is considered. You will be notified via email of the results of your request once a decision has been made. You can view all of your requests and their statuses on your Access Requests page.`

**Comment by sshetenhelm** [comment]
@tmacmath and @alisonclemens does the updated language sound clear to you? 

Moira suggested informing users they will receive an email, and the unspecified approver language meets the Kissinger requirements.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1014

**Comment by K8Sewell** [comment]
Deployed this [commit](https://github.com/yalelibrary/yul-dc-blacklight/pull/931/commits/352069914f27b66da3d44a70010ecaffb5ae5bef) for the OwP_FeatureBranch to Demo

**Comment by sshetenhelm** [comment]
Looks good in Blacklight on Demo! Thank you!

**Comment by sshetenhelm** [comment]
Only in Demo, so ready to close :)
