### ISSUE TITLE
Fix Spec Failing on Blacklight Main

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2852]
# Summary
Failure has made it's way into the main branch on blacklight repo.  From which change is undetermined as it was first discovered in the dependabot PR for nokogiri.  

# Acceptance Criteria
- [ ] main branch for blacklight passes CI successfully

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/a1e81fb4-b7f2-443e-9080-6948b8a84708)

**Comment by K8Sewell** [comment]
Flappy specs were the culprit - CI eventually passed on main without any changes.  PR to mark the flappy specs as pending - until the test effectiveness / coverage tech debt work is ready.

PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/1013

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v1.61.8](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.61.8)

**Comment by K8Sewell** [comment]
No issues noticed.  Will promote to UAT.

**Comment by sshetenhelm** [comment]
Anything we need to do to double-check this, or are we ready to close?
