### ISSUE TITLE
Permission Request Page Locks Up

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2854]
# Summary
If an admin or approver of a permission set forgets to set an Access Until value the page:
* won't save the permission request
* will turn the date box for access until red
* will make the date box unable to be edited
* If the page is refreshed after the first unsuccessful save the user then has the ability to edit the Access Until field but there are no instructions to let the user know to do that to make the field editable again
* If the user toggles the approver or deny radio buttons the access until field becomes editable again but no instructions for that either

# Acceptance Criteria
- [x] if a user does not enter an Access Until value - they should get an alert and/or instructions then be able to enter a value and save successfully -- "Please select an Access Until date. This is the date the user's access will expire."
- [x] add some form help tips

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/9f04f95e-033d-4f11-a52a-55d26e41b11e)

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.3)

**Comment by sshetenhelm** [comment]
Works as expected, but so sorry, could we please update the warning language to the following?: 

`Allow Access Until can’t be blank. Please select an Allow Access Until date. The user’s access will expire on this date.`

Otherwise looks good!

**Comment by jpengst** [comment]
Fixed it! I learned how to add custom validation messages, so that's pretty cool :)  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/dad94bd1-061e-4326-a91e-cbad95284e07)



PR: https://github.com/yalelibrary/yul-dc-management/pull/1406

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.4)

**Comment by sshetenhelm** [comment]
Works as expected on Demo! Thank you :) 

Ready to close
