### ISSUE TITLE
[BUG] Problem report status won't queue in UAT

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2857]
After clicking the check the status of the Problem Report button in Management UAT, it shows the message: "NOT queued." When the 'Queue the problem report job' button is pressed, it shows the message "The manual problem report job has been queued" and it generates a new report. However, when I click the status button after it still says "NOT queued." 

After the manually-triggered report is created, no other report jobs automatically queue. The  'Queue the problem report job' button essentially acts in the same way as the 'trigger job manually' button.

UAT is the only environment in which this is happening; the feature is working as expected in TEST and PROD Management.

**Acceptance**

- [ ] In Management UAT, the 'Queue the problem report job' queues the problem report
- [ ] The Problem Report job completes nightly without having to be constantly re-queued

**Comment by sshetenhelm** [comment]
As of 2024.06.14, job is displaying as queued.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1443

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.72.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.72.2)

**Comment by K8Sewell** [comment]
Queuing problem report job successfully on Test.  Will promote to UAT.

![Image](https://github.com/user-attachments/assets/93e3f146-aa6f-4f26-a865-9ad0f50edb43)

**Comment by sshetenhelm** [comment]
Job is queued in UAT and ran last night. Spreadsheet is downloadable and has info. Hooray!

Ready to close :)
