### ISSUE TITLE
[BUG] Storing Same Image for Multiple Child OIDs

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2858]
# Summary
During Preservica ingest the same image (same checksum and bitstream) is being saved to multiple child OIDs.

# Acceptance Criteria
- [ ] child images are unique

# Engineering Notes
Add logic to review and clean up duplicate child objects

PTIFF failure in Prod: https://collections.library.yale.edu/management/batch_processes/17189/parent_objects/33212740
Re-Sync with Preservica Attempt: https://collections.library.yale.edu/management/batch_processes/17190
[teams discussion](https://teams.microsoft.com/l/message/19:3b846173e3bf4c84a3d154056c4bb447@thread.tacv2/1718227629631?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=2feb0d22-b950-4c85-8e0e-501978f59a2b&parentMessageId=1718227629631&teamName=Engineering%20Projects%20with%20Consultants&channelName=DCS&createdTime=1718227629631)

**Comment by sshetenhelm** [comment]
Triplicate deletions in this UAT batch process - https://collections-uat.library.yale.edu/management/batch_processes/2039

**Comment by K8Sewell** [comment]
Potentially resolved by fix in ticket #2864
