### ISSUE TITLE
Fix ParentObject.replace_preservica_tif(co)

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2864]
ParentObject.replace_preservica_tif(co) copies all images to the same child OID. 
The last image is the one that ends up in child OID in the /data directory for all children.

See: https://github.com/yalelibrary/yul-dc-management/pull/1403/files#diff-acc421bf5477cf1667d0b61e9ded247f3b42335a2425020920d8c20919ff0384L293

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1403

**Comment by K8Sewell** [comment]
Deployed to Test, Demo, and UAT with release [v2.70.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.2)

**Comment by sshetenhelm** [comment]
To clarify, do you mean an object ingested into TEST Preservica that has two copies of the exact same image, with the exact same filename?

**Comment by sshetenhelm** [comment]
'Create parent' batch process in progress -- https://collections-uat.library.yale.edu/management/batch_processes/2052

**Comment by sshetenhelm** [comment]
Object uploaded successfully. Please note the repository added more files to this object, so it will now display as having 64 children instead of the original 38. Waiting on results of resync process now.

**Comment by sshetenhelm** [comment]
Successful? No longer running, unique children still displaying -- https://collections-uat.library.yale.edu/management/batch_processes/2055/parent_objects/901624363 

Do we need to run any other tests for this?

**Comment by K8Sewell** [comment]
Testing with this object was the main thing we needed to check.  Unless Martin has other test scenarios in mind - we are set.

**Comment by martinlovell** [comment]
We are all set as long as re-sync works with the right images in the right place.

**Comment by sshetenhelm** [comment]
Stakeholder stated they expected hundreds more images in this object. However, after investigating, we may think this is a stakeholder-to-Preservica workflow issue rather than a Preservica-to-DCS syncing issue. Let's keep this ticket and the next open for a little longer until we hear back from the stakeholder again.

**Comment by sshetenhelm** [comment]
Reconstructed Preservica object ingesting now -- https://collections-uat.library.yale.edu/management/batch_processes/2067

**Comment by sshetenhelm** [comment]
"New" object with 942 unique images successfully created. Pressed the "resync" button; we'll see what happens.

**Comment by sshetenhelm** [comment]
Looks good! We should be able to close this and the following ticket :)
