### ISSUE TITLE
[BUG] TIFF Download errors MissingTemplate

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2865]
**Story**
When a user attempts to download a TIFF in Blacklight, they receive the "We're sorry, but something went wrong" error screen. As per Martin, the logs report: 

`Exception: ActionView::MissingTemplate: Missing template download_original/tiff_staged.html, application/tiff_staged.html`

We would like users to be able to download TIFFs again.

**Acceptance**

- [x] TIFF downloads work in Blacklight

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1022

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.0](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.0)

**Comment by sshetenhelm** [comment]
Works on Test!

**Comment by K8Sewell** [comment]
Release [v1.62.0](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.0) deployed to UAT

**Comment by sshetenhelm** [comment]
Works on UAT! Thank you so much!
