### ISSUE TITLE
Add ActivityStreamJob to Batch Process Table

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2866]
# Summary
While using DelayedJob most cron jobs were included in the batch process table.  After switching to GoodJob those cron jobs got theIr own tab in the new dashboard.  However, the information provided in the GoodJob dashboard does not meet the needs of users.  

# Acceptance Criteria
- [ ] Add the activity stream job information to the Batch Process table dropdown list

**Comment by sshetenhelm** [comment]
Previously, similar to other batch processes, we were able to click on the Batch Process ID number, view all the parents OIDs and their _Completed_ or _Failed_ status, and click on a parent to see the error message. **The most important thing for us is knowing which parent OIDs failed to resync their metadata**, as that likely means the record itself or information entered into MGMT (bib, etc.) has an error.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1410

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.6](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.6)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/16ec1f6a-d799-4990-aafb-6b959dcfe6f8)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Ready to close :)
