### ISSUE TITLE
Add new Nightly Integrity Check job to Batch Process table

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2867]
Blocked by #2855 

**Story**
We have created a new nightly job to check the file integrity of images in DCS. We would like to have the results of that job display in the batch processes table, similar to how the ActivityStream job displays.

We would like to be able to view the following information:

1. Child OID checked and corresponding Parent OID
2. Completion status — Complete or Failed
3. An error message if Failed, including file location 

Something along the lines of what we already have is fine — ex. `Expected file originals/32/32/28/78/32/32287832.tif on S3 not found`

Please use whatever language you feel is appropriate for the error -- ex. 
`not found` / `is corrupted` / etc. 

**Acceptance**

- [x] Integrity Check nightly job appears in the Batch Process table
- [x] Integrity Check nightly job provides a list of parent and child OIDs checked
- [x] Integrity Check nightly job displays completion status of Complete or Failed
- [x] Error message displays the file location and something about what’s wrong

**Comment by K8Sewell** [comment]
Blocked until ticket #2855 is complete

**Comment by K8Sewell** [comment]
Work for this ticket is included in [this PR](https://github.com/yalelibrary/yul-dc-management/pull/1411) for ticket #2855

**Comment by jpengst** [comment]
Deployed to test v2.70.8

**Comment by jpengst** [comment]
bug PR: https://github.com/yalelibrary/yul-dc-management/pull/1414

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.70.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.9)

**Comment by jillpe** [comment]
Waiting for other nightly integrity check ticket

**Comment by laurenb33** [comment]
Look at all of these awesome integrity checks!
![Image](https://github.com/user-attachments/assets/d3fc43ec-4dce-4837-b102-9dad71e0767a)
