### ISSUE TITLE
Review Management App User Guide

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2868]
**Story**
As the fiscal year closes, we should review and update the main Management App User Guide to ensure the information is accurate and up-to-date. 

(Spoiler alert -- is isn't)

**Acceptance**
- [ ] Management App User Guide updated to reflect current system status

**Comment by laurenb33** [comment]
Just updated the MGMT guide - when we unleash OwP, I'll review it again to add info about the Permission Request page.
