### ISSUE TITLE
Add Activity Stream Log view and Reset

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2871]
Bring back the "Reoccurring Jobs" page to view the Activity Stream Logs and reset hanging jobs.

Acceptance:
- [ ] Sys admins can view the Activity Stream Logs
- [ ] Sys admins can reset Activity Stream runs that are "Running" and more than 12 hours old

**Comment by martinlovell** [comment]
![Image](https://github.com/yalelibrary/YUL-DC/assets/32851993/625f8f11-94b2-4fcb-a599-6d93cce89a6c)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1407

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v2.70.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.5)

**Comment by K8Sewell** [comment]
Looking good on Test.  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/37d69c6f-fa9c-41da-9fbb-7faffc334b24)

**Comment by sshetenhelm** [comment]
Looks as expected on UAT and functions as in the video Martin posted.
