### ISSUE TITLE
Fix Overlap - Mobile

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2872]
# Summary
During testing of another mobile fix ticket the overlap of metadata and links was apparent on a very small screen in a Safari browser.

# Acceptance Criteria
- [x] prevent metadata overlap
- [x] prevent link section overlap

# Screenshot

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/02acfdbd-b346-4cb9-8b04-f5b5f788af13)

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/1024

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.4](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.4)

**Comment by K8Sewell** [comment]
The lack of spaces in the Collection/Other Creator is preventing the overlap fixes from being complete.  Container / Volume and the metadata, AS links with themselves, & Digital Collections with the full text radio button are fixed though.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/43ce7bb4-a41e-43df-a61f-59bb89f57788)




![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/98ef4564-f701-42f1-8a57-6ba962a822d6)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/a678e889-87d5-4f75-848e-d91a378d6a22)

**Comment by K8Sewell** [comment]
PR to fix metadata label overlap found in testing - https://github.com/yalelibrary/yul-dc-blacklight/pull/1025

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.62.5](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.62.5)

**Comment by K8Sewell** [comment]
Looks good on Test (275px wide screen in Safari Browser).  Will promote to UAT.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/46667a55-3196-4e95-8f14-b53a095603e0)

**Comment by sshetenhelm** [comment]
Looks good to me! Thank you and ready to close :)
