### ISSUE TITLE
SPA implementation - CSP

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2875]
Per the Yale's Info Security team, we need to enable a Content Security Policy for DCS. Our extension to do this is until December 2024. The DCS SPA report is in the our Team channel. See related tickets #https://github.com/yalelibrary/YUL-DC/issues/2838 https://github.com/yalelibrary/YUL-DC/issues/2833

@K8Sewell has kindly answered the following questions about enabling a CSP for DCS:

What steps would be to be taken to enable a CSP for DCS?
Enable CSP settings in config/initializers/content_security_policy.rb
Add trusted resources to allowlist to resolve browser alerts
Address inline code by doing one of the following:
Move all inline code and inline styles to a file.
Move the code to a tag and get its hash key.
Use a 'nonce' tag attribute and add it to the corresponding tag.

Files w/ <script> tag:
Management - 1
Blacklight - 6
[source](https://www.stackhawk.com/blog/rails-content-security-policy-guide-what-it-is-and-how-to-enable-it/)

How do we turn on the CSP without breaking the inline javascript?
There is a setting to enable a reporting only functionality. However, once CSP is enabled it will break all inline javascript. Enabling this report only operation should only take 30 minutes to 2 hours.

**Acceptance:**
- [ ] Enable a CSP for DCS

**Comment by K8Sewell** [comment]
In progress PR - https://github.com/yalelibrary/yul-dc-management/pull/1445

**Comment by K8Sewell** [comment]
In progress notes:


- [x] set up to run in staging and production env - not dev - done but commented out during development
- [x] add header exceptions for testing and finding sources
- [ ] manually search production site for tags - to identify all necessary trusted sources
------------------------------------
- [ ] script
- [ ] img
- [x] style
- [ ] object
- [ ] font
-----------------------------------------
- [x] add nonces for exceptions - done but commented out until steps above complete
- [ ] address glyph box error - see details below

<details>

downloadable font: Glyph bbox was incorrect - downloadable font: Glyph bbox was incorrect (glyph ids 68 146 262 293) (font-family: "YaleNew-Roman" style:normal weight:400 stretch:100 src index:1) source: https://static.library.yale.edu/fonts/yalenew/YaleNew-normal-normal/yalenew-roman-webfont.woff2

</details>

**Comment by jpengst** [comment]
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1073  
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/1445

**Comment by K8Sewell** [comment]
Taking back to In Progress.

Notes from Testing:

On management we are getting cross origin errors for our fonts that should be addressed.  The javascript is acting as intended and there are no errors with the inline scripts.

On blacklight we are also getting CORS errors for our fonts as well as numerous errors for the style and script tags.  Additionally, we need to add the image for the banner to the trusted list and fix the inline scripts.

<details>

# Management

![Image](https://github.com/user-attachments/assets/1f92a0ab-14ef-4572-9b4d-c9515f65b59c)

![Image](https://github.com/user-attachments/assets/c6dba71d-49f1-4b10-b579-0c0a860cdd95)


![Image](https://github.com/user-attachments/assets/e7dde846-656c-4dcf-8cf8-461cea84e904)

# Blacklight

![Image](https://github.com/user-attachments/assets/48a6e363-c333-4a8a-b00f-0becfe2b7ed2)

![Image](https://github.com/user-attachments/assets/c685b7fd-996a-483f-860c-4f374d2a0b04)

![Image](https://github.com/user-attachments/assets/155301e1-77a5-4d26-89ca-e2892d736a76)

![Image](https://github.com/user-attachments/assets/84a9790c-2f54-4262-925c-ac808f349bc5)

![Image](https://github.com/user-attachments/assets/cb5d195e-cbec-4b56-9fc4-2819e06ca5f9)


</details>

**Comment by K8Sewell** [comment]
Next steps from standup [ 20.11.2024 ] 

* fix image source and in line script and style errors
* create ticket to address CORS errors for static fonts with ITS

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management/pull/1462

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/1075 * this is currently deployed to the Test environment for investigation

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1465 * this is also deployed to Test environment for easier review

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.73.4](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.73.4) & [v1.65.2](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.65.2)

**Comment by K8Sewell** [comment]
Blacklight - looks good, JS responding as expected

Management - JS not working on permission request show/edit page.  Taking back to in progress.

![Image](https://github.com/user-attachments/assets/4c9d50a2-7501-4ae9-bd4f-30bc399a99a8)

**Comment by K8Sewell** [comment]
PRs ready for review:

https://github.com/yalelibrary/yul-dc-blacklight/pull/1076
https://github.com/yalelibrary/yul-dc-management/pull/1466

**Comment by K8Sewell** [comment]
Deployed to Test with releases [v2.73.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.73.5) and [v1.65.3](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.65.3)

**Comment by K8Sewell** [comment]
Taking back to in progress to fix smoke tests.  Will create separate ticket to address the smoke test's ability to rollback to a prior deploy is not working great.

![Image](https://github.com/user-attachments/assets/ae0cd2d9-b6c4-45a9-9c1b-07516cacbdfe)

**Comment by K8Sewell** [comment]
Redeployed to Test after restarting solr container and smoke tests passed.  Manual testing of JS and styles looks good.  Will promote to UAT.

**Comment by K8Sewell** [comment]
For some reason UAT auto selects No as an option on the Permission Request edit page.  On Test it doesn't do this and the inline JS works fine.  On UAT the auto select of No is making it possible to do this - screenshot - so taking back to in progress.

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/e87f75fd-41e9-4f12-8cba-f5f409b918d8" />

**Comment by K8Sewell** [comment]
UAT has behavior that Test does not.  It autoselects the No option on the Permission Request show/edit page and that makes the inline JS not work properly.  Blacklight looks good, all the styles and JS are working as expected.  Taking back to in progress to fix up the auto selection of the No option for managment.

<img width="699" alt="Image" src="https://github.com/user-attachments/assets/c6e9cafd-37ee-4976-90c0-9410cd2508cd" />

**Comment by jpengst** [comment]
No additional changes needed. UAT is behaving as expected:
<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/8a89e59b-e91d-4de2-9274-2494baa34259" />

**Comment by laurenb33** [comment]
SPA Exception Extended until  January 31, 2025 :)
