### ISSUE TITLE
Spike: Refactor batch processes

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2879]
**Story**
We should refactor batch processes, including refining how admin sets are displayed in the batch process table.

**Acceptance**
- [x] Discovery
- [x] Make tickets for the work

**Comment by jpengst** [comment]
Refactor Admin Set BP display: https://github.com/orgs/yalelibrary/projects/1/views/1?filterQuery=&pane=issue&itemId=72280052

**Comment by jpengst** [comment]
Are we using any mets xml ingests anymore? Theres a few methods in our BP model that use them.

**Comment by jpengst** [comment]
Refactor BP model: https://github.com/orgs/yalelibrary/projects/1/views/1?filterQuery=&pane=issue&itemId=72384873
