### ISSUE TITLE
Batch Job Class - Separate code related to individual activities

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2881]
**Story**
The batch job class codebase currently has all code together, just grouped and commented. We should pull apart the code related to individual activities to make the code cleaner to understand. We need to be mindful of any needed changes to file names, language, etc.

We should pull apart the code according to _[Individual batch processes? Or by Action — ex. all the export metadata processes together, etc.?]_

**Acceptance**

**Comment by K8Sewell** [comment]
Done in #1616
