### ISSUE TITLE
Add Reset to Activity Stream Log

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2889]
The Activity Stream log page has been reinstated, but the reset button is still missing. We would like a button to reset hanging jobs to be added to the page. Previously, when a user pressed the Status button and a job needed to be triggered manually, the button would appear. Right now, the page just refreshes. 

Kait mentioned that it may be possible to do this through Good Jobs. On 7/9 sprint planning, it was unanimously agreed that we do not need the button on this page if it possible to do this in Good Jobs.

Acceptance:
- [ ]  Sys admins can reset Activity Stream runs that are "Running" and more than 12 hours old
OR 
- [ ] The ability to reset Activity Stream in Good Jobs

**Comment by K8Sewell** [comment]
On the GoodJobs dashboard each job has a button with 3 dots - when clicked a user can destroy the job that is hanging and will keep it from being re-tried.

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/5e6553da-26e6-49ba-8277-77859fca85bd)

Also, on the Cron tab there is option to trigger any of the nightly jobs by pressing what looks like a 'fast forward' button - that will enqueue a new job immediately.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/5dc8d697-fef4-4898-93a0-b6f0702025b7)


Happy to pair on a walkthrough of GoodJob anytime.

**Comment by laurenb33** [comment]
Thanks, Kait! I just used it to reset the Activity Stream jobs :)
