### ISSUE TITLE
BUG: Expired Status Allows Viewing

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2890]
# Summary
When testing another ticket I found I was able to view a record's images and my request for that record had expired.  I expected to not be able to see the images and to need to re-request access.

# Acceptance Criteria
- [ ] user with expired status cannot view images
- [ ] user with expired status must re-request access

# Screenshots

<details>

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/09cf2653-cb3c-4d33-88fd-d00ab6a83860)

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/b2a4b260-051e-49aa-962d-55c21d85676e)

</details>

**Comment by sshetenhelm** [comment]
@K8Sewell This is part of a permission set with the label 'test2', and I updated that set to be 'test3'. You are an Admin on that set, and perhaps was not before, so that is likely why you can see the object.

**Comment by K8Sewell** [comment]
@sshetenhelm yep, forgot about that viewing access as an admin.  When I experimented with other parent objects I had an expired status on I got the behavior I expected of not being able to see them and needing to re-request access.  Will close this ticket.  Thanks for checking!
