### ISSUE TITLE
Batch Process Checksum Mismatch

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2891]
Unfortunately, this [batch process ](https://collections.library.yale.edu/management/batch_processes/17370/parent_objects/33219047) failed due to checksum mismatch. So, the checksum mismatch error is persisting when trying to create an object.

**Comment by decirella** [comment]
The files associated with this item are on Storage@Yale ArchiveTier storage which was affected by a [recent outage](https://yale.service-now.com/it?id=it_outage&sys_id=9f3bae3147174250fc4dfbda436d4355) .  The download events by s_dcs_medical coincide with the service outage.
