### ISSUE TITLE
Migrate three AMEEL objects into UAT

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2893]
**Story**
In order to provide some examples of what a direct migration for AMEEL serials would look like, we would like to migrate three journal issues from the AMEEL collection (PID 59) from FindIt into UAT.

We would like to migrate the following three parent objects from PID 59 :
15511339
15763199 
15976485

**Acceptance**

- [x] Export image files from Fedora
- [x] Import image files into the DCS pairtree
- [x] Import the objects into DCS UAT into the SML admin set as Public
- [x] Audit images

**Comment by MaggieZhaoYale** [comment]
https://collections-uat.library.yale.edu/management/batch_processes/2084 
https://collections-uat.library.yale.edu/management/batch_processes/2086 (The failed one in above was corrected in this batch)

**Comment by sshetenhelm** [comment]
Thank you @MaggieZhaoYale ! Could you please add points?

Ready to close :)
