### ISSUE TITLE
Create Cognito Instance for UAT & PROD

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2894]
# Summary
To successfully transition to the new log in for the OwP feature additional configurations are needed.

# Acceptance Criteria
- [x] Create cognito instance for UAT & PROD
- [x] Input values in AWS Parameter Store for SSO env vars in yul-dc-uat & yul-dc-prod hierarchy

**Comment by jasonwuyale** [comment]
App Clients were created under the UAT pool and PROD pool. Client ID and Client secret will be shared in a secure channel.

**Comment by K8Sewell** [comment]
Params added for UAT.  Will be included in next deploy to that env.

**Comment by K8Sewell** [comment]
Some issues with log in still.  Presently investigating.



![Image](https://github.com/user-attachments/assets/cda4b2ff-786b-4ffe-8834-df66ae188641)

**Comment by K8Sewell** [comment]
Successfully able to log in to UAT.  PROD env will be set up before deploy to production.



![Image](https://github.com/user-attachments/assets/f4b64316-9ca3-480f-ad7e-2af0b0ae1612)

**Comment by K8Sewell** [comment]
PROD env vars for cognito are in place.

**Comment by jillpe** [comment]
Waiting until we deploy to confirm this works
