### ISSUE TITLE
Retrieve YIPP images from FindIt

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2896]
**Story**
There are approximately ~2000 parent objects in FindIt that are part of the YIPP collection. The majority of these items will not be migrated into DCS, and the entirety of the collection is being reimagined in Omeka. 

To support this work, we need to pull copies of all of the images for YIPP (PID 27).
Parent oids:
[YIPP-parent-OIDs.csv](https://github.com/user-attachments/files/16314544/YIPP-parent-OIDs.csv)

**Acceptance**
- [x]  Provide list of parent OIDs (Summer)
- [x]  Export image files from Fedora (TIF if available, JPG/JP2 if TIF broken)
- [x] Import images files into following location: FC_YULDCS-807001-YUL > DCS_MaggieandSummer > YIPP-images

**Comment by tmacmath** [comment]
Any progress on this ticket?

**Comment by sshetenhelm** [comment]
Confirming that 5000+ images have been input into the share specified. @tmacmath do you access to FC_YULDCS-807001-YUL ? And where do these images need to live to be able to be used in Omeka?

**Comment by sshetenhelm** [comment]
They are named with child OIDs though so we will need to do some child/parent matching work.

**Comment by sshetenhelm** [comment]
Ready to close :)
