### ISSUE TITLE
[BUG] Check for Unusual Objects

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2897]
In MGMT TEST, this [parent object](https://collections-test.library.yale.edu/management/parent_objects/1633987014242) has a child object count of 1, and there's a child object listed on the show page, but the link for that child goes to the child object data table. It has a child, but the child does not have an oid. Performing an 'Export child OIDs' batch process results in a spreadsheet with a blank value in the "child oid" field, but includes order and label information:

![Image](https://github.com/user-attachments/assets/aea93900-df2c-45ad-b517-dddfdcfe0c9d)

- This object was an older ingest (2021-10-12 12:58:55 UTC). 
- Another object that was ingested previously that year displays expected behavior - https://collections-test.library.yale.edu/management/parent_objects/2056655  - for a parent with child objects attached, but no child images

To confirm that this unusual object occurrence is just a one-off issue, we want to check the environments for objects with unexpected behaviors. 

Acceptance:
- [x] Check TEST for unusual objects
- [ ] Check DEMO for unusual objects
- [x] Check UAT for unusual objects
- [x] Check PROD for unusual objects
- [ ] Create job to assess object attributes

**Comment by jpengst** [comment]
We can close this. Martin and I confirmed that there are no other child objects on UAT or prod that have nil oids. The broken object in test must have gotten corrupted somehow a few years ago.
