### ISSUE TITLE
Open with Permission UAT - Stakeholder Testing

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2898]
AFTER LOGIN/COGNITO WORKS IN UAT

**Story**
We would like to test the patron-facing aspects of the Open with Permission feature. The google form [available here](https://docs.google.com/forms/d/e/1FAIpQLSewd-NpTwY0YK9ASYKClHYy64bbJhI2WV8wOnG9-uuz_kgUFA/viewform) can be sent to YUL staff to ask for feedback on the process from searching through submitting a request.

**Acceptance**

- [x] Share form via DCS Teams channel & request staff to fill out
- [x] Share form via email & request staff to fill out
- [x] Gather a minimum of five responses
- [x] Send out and gather replies for Round 3 of testing, to ensure access turns "off"
- [x] Make tickets for any necessary follow-up work

**Comment by jillpe** [comment]
Waiting for stakeholders to test

**Comment by sshetenhelm** [comment]
Testers will have object access expire on Wednesday; after that, will send Part 3 form to ensure access has turned off as expected. 

Keep waiting label on until after responses are in.

**Comment by sshetenhelm** [comment]
Part III has been sent.

Feature is working as expected for all users, with minor exception that could not be repeated by myself or the tester. 

Only area of improvement so far is to make the form look better (tickets created and in sprint).

**Comment by sshetenhelm** [comment]
Ready to close :)
