### ISSUE TITLE
7/31 Deployment🐴

### ISSUE THREAD

**Issue by laurenb33** [yalelibrary/YUL-DC#2899]
**Versions**
Management: v2.71.1
Blacklight: no changes
MetadataCloud:  v2.1.2

**Production**
- [x] restart image servers
- [x] Management
- [x] MetadataCloud

**Comment by laurenb33** [comment]
Deploy for MGMT, UV, and Images failed - Error message says that the version of Jenkins is out of date - from https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=71797323:

Because every version of camerata depends on Ruby >= 3.2.0
  and Gemfile depends on camerata >= 0,
  Ruby >= 3.2.0 is required.
So, because current Ruby version is = 2.6.0,
  version solving has failed.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=71797323

It appears old Jenkins will have to be updated to proceed @bobrice @kbcarter @thescreamingmandrake @ra359 
This deploy was minor, so it's no prob forgoing it this week.

**Comment by kbcarter** [comment]
@laurenb33 , did you try deploying from the new Jenkins environment?

**Comment by laurenb33** [comment]
@kbcarter - No, could you provide the link to new jenkins?

**Comment by K8Sewell** [comment]
Updated blacklight release version to the one prior to the release of the open with permission work because as I was working on ticket #2877 I noticed it mentioned having the OwP auth token in place before the release of the open with permission work.  Sorry for not catching this earlier.

**Comment by laurenb33** [comment]
MGMT and MDC are all set - Image/UV refresh didn't work on new Jenkins; Devops is investigating why.

**Comment by laurenb33** [comment]
All set - ready to close!
