### ISSUE TITLE
Refactor BP Admin Set

### ISSUE THREAD

**Issue by jpengst** [yalelibrary/YUL-DC#2901]
## Summary  
The way we save and display Admin Set labels in the BP table can be improved. Refactoring this will improve readability and usability for present and future jobs.     
  
## Acceptance Criteria  
- [x] Refactor admin set code to a separate method that can be applied in multiple jobs.  
- [x] Apply new method to the following jobs/methods in BatchProcess:
  - [x] `create_new_parent_csv`
  - [x] `update_fulltext_status`
  - [x] `recreate_child_oid_ptiffs`
  - [x] `refresh_metadata_cloud_mets`
  - [x] `sync_from_preservica`
- [x] Apply new method to the following jobs/methods in CsvExportable:
  - [x] `with_each_parent_object`
  - [x] `export_parent_metadata`
  - [x] `export_all_parents_source_csv`
  - [x] `child_output_csv`
- [x] Apply new method to the following jobs/methods in Deletable:  
  - [x] `delete_parent_objects`
  - [x] `delete_child_objects`
- [x] Apply new method to the following jobs/methods in IntegrityCheckable:
  - [x] `integrity_check`
- [x] Apply new method to the following jobs/methods in Reassociatable:
  - [x] `update_child_objects`
- [x] Apply new method to the following jobs/methods in Updatable:
  - [x] `update_child_objects_caption`
  - [x] `update_parent_objects`

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1428

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.71.7](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.7)

**Comment by K8Sewell** [comment]
Testing was successful.  Will promote to UAT.

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/7f59ae68-a822-44a6-ba03-6811056c1e5e">
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/d82a294b-dc35-40a5-8392-d4859d79f86d">
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/1fb0a0d7-8b56-4820-b201-e9e7230211bb">
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/8422f5a5-9413-463e-ab70-c34a256bef93">
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/e7425f56-7912-44a1-ac56-e59a87b4de03">




<details>
  - `child_output_csv` - Export Child Oids
<img width="899" alt="image" src="https://github.com/user-attachments/assets/dda0441f-615c-4903-a51b-3db1e95481ce">


  - `create_new_parent_csv` - Create New Parent
<img width="900" alt="image" src="https://github.com/user-attachments/assets/5abff6a0-15cf-403f-b6fb-388ee01d8fd3">


  - `delete_child_objects` - Delete Child Objects
<img width="898" alt="image" src="https://github.com/user-attachments/assets/ceaee910-d124-4d09-ac9f-377d897eca38">


  - `delete_parent_objects` - Delete Parent Objects
<img width="893" alt="image" src="https://github.com/user-attachments/assets/7535ebb9-bec2-426a-acd4-a2a5b391e827">


  - `export_all_parents_source_csv` - Export all Parents, button on Admin Sets index page 
<img width="896" alt="image" src="https://github.com/user-attachments/assets/622c2db2-a800-40f3-8c80-adeebf9e5a25">
 


  - `export_parent_metadata` - Export Parent Metadata
<img width="896" alt="image" src="https://github.com/user-attachments/assets/2c6cbbc7-a4d9-402e-baed-6669bc01f06b">


  - `integrity_check` - Cron Job: Integrity Check
<img width="901" alt="image" src="https://github.com/user-attachments/assets/10167c2e-d957-4b95-a69b-5d0bc81fe95c">



  - `recreate_child_oid_ptiffs` - Recreate Child Ptiff
 <img width="896" alt="image" src="https://github.com/user-attachments/assets/ee488e9c-ac30-4681-bed1-444cf6584d33">



  - `refresh_metadata_cloud_mets` - Unfortunately, don't have mets xml file so not tested


  - `sync_from_preservica` - Resync from Preservica
<img width="899" alt="image" src="https://github.com/user-attachments/assets/760a394b-ab03-48d5-a8e9-626cf22ab46d">


  - `update_child_objects_caption` - Update Child Objects Captions and Labels
<img width="904" alt="image" src="https://github.com/user-attachments/assets/93e69304-f112-43c0-87c5-bd2edfd772e1">


  - `update_child_objects` - ~used by~ Update Child Objects Captions and Labels
<img width="904" alt="image" src="https://github.com/user-attachments/assets/97777466-ec1a-4c35-937a-af0d8ca1f8cb">


  - `update_fulltext_status` - Update Fulltext Status
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/7c190cd7-52d5-452f-978b-2a94152e3495">


  - `update_parent_objects` - Update Parent Objects
<img width="902" alt="image" src="https://github.com/user-attachments/assets/6be232de-3159-4d69-b5a6-e670ee755a64">


  - `with_each_parent_object` - Export All Parent Objects by Admin Set
<img width="899" alt="image" src="https://github.com/user-attachments/assets/effa96e3-befb-4502-8707-d74f06d0b06a">


</details>

**Comment by sshetenhelm** [comment]
Tests queued; waiting for Kissinger jobs to resolve before tests can run.
