### ISSUE TITLE
[BUG] Users with created (non Yale) accounts can't sign in to Blacklight

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2903]
**Story**
When a user creates an account in DCS Blacklight, and they try to log in with that non-Yale created account, they receive the "Something went wrong" error message/screen. This occurs with accounts created in UAT both before and after AWS parameters were updated. We need non-Yale users to have the ability to log in, as they are the ones most likely to request Open with Permission objects.

**Acceptance**

- [x] Non-Yale accounts can be created
- [x] Non-Yale account holders can successfully log in and use DCS

**Comment by jpengst** [comment]
Looks like the issue here is that non-yale accounts don't have an Identities hash to pull a userId/netid from.  
Failing line is: `yale_identity = auth.extra.raw_info.identities.find { |i| yale_issuers.include?(i.issuer) }`  

How does the identities hash get injected into the auth hash for yale users and not non-yale users?

**Comment by jpengst** [comment]
Management PR: https://github.com/yalelibrary/yul-dc-management
Blacklight PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1036

**Comment by K8Sewell** [comment]
Deployed to Test with management release [v2.71.2](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.2) & blacklight release [v1.63.3](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.63.3)

**Comment by sshetenhelm** [comment]
Working as expected in Test!

Was able to log in successfully with non-Yale account in Chrome and Safari.
Was able to add items to Saved List and request an item.
Saved items and Requests continued to display after logging out and back in and after switching to a different browser.

**Comment by sshetenhelm** [comment]
Works on UAT in Chrome and Safari! Thank you!

Ready to close :)
