### ISSUE TITLE
Can't remove users from Permission Set in Management

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2904]
**Story**

As a system admin user I would like to be able to remove approvers/administrators from a Permission Set. 

* On test and UAT I see: "Permission Denied" when attempting to navigate to a Permission Set's details.
* In my local environment I do not see an option to remove the user:

![Image](https://github.com/user-attachments/assets/74bc7b6c-ae75-4b03-b07c-ffb64c862834)

**Acceptance**
- [x] Sysadmin users can access the edit screen for a Permission Set
- [x] Delete option is available for sysadmin users in the set.

**Comment by jpengst** [comment]
@mikeapp What happens if you create a PS on UAT or test? Can you access the permission sets after that? I was having the same error on UAT and I'm able to view the sets again after creating one. I'm not sure whats causing this behavior. Still investigating.

**Comment by mikeapp** [comment]
I created another set and saw the _x_ icons.   I think the problem may be that I added myself as an `approver` to the set shown in the description.  Perhaps having both roles caused it?

**Comment by sshetenhelm** [comment]
Here's something else to add to this ticket -- now I can't remove Mike as an administrator, even though (a) I receive a flash message confirming his removal and (b) I can add/remove other sys admins.
Video:
https://drive.google.com/file/d/1zW_4LoAEIHjXOI9ppo_rWGduMmNilnCA/view?usp=sharing

**Comment by jpengst** [comment]
Im also getting an error page when trying to view Mikes profile in /users:  


![Image](https://github.com/user-attachments/assets/c3cf68b7-ddd7-41cd-b46d-816ca21e5906)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1422

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.71.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.3)

**Comment by K8Sewell** [comment]
Editing and viewing capabilities restored on Test.  Will promote to UAT.


No option to remove self from permission set

![Image](https://github.com/user-attachments/assets/82a839aa-db8b-444a-8384-38a910a85737)

Able to remove and add users for permission set

![Image](https://github.com/user-attachments/assets/608cc96e-7b4a-4b36-a21d-b6368d6b60e8)

![Image](https://github.com/user-attachments/assets/064cb306-ec33-456a-8b10-643547c9a4e1)

![Image](https://github.com/user-attachments/assets/07cce737-5a5b-45be-a968-eca80ae8d316)

**Comment by sshetenhelm** [comment]
1. Receiving 'We're sorry, something went wrong' for Kait and JP through Users page (but can access Mike's page now).
2. Cannot remove Kait and JP as Perm Set Admins. [Video.](https://drive.google.com/file/d/183IfZq5J0kFuoJC5eFkir36yDzwsTeAw/view?usp=sharing)
3. CAN remove Kait and JP as Perm Set Approvers.
4. CAN remove other users as Perm Set Admin/Approvers.

**Comment by jpengst** [comment]
We need to delete a few corrupted roles on Test and UAT.  
Test: ed396, ks2552, mikea
UAT: ac2254, je459, ks2552

**Comment by K8Sewell** [comment]
Corrupted roles have been deleted from Test and UAT.

**Comment by sshetenhelm** [comment]
Lookin' good on Test and UAT! Ready to close :) Thanks!
