### ISSUE TITLE
Update OwP patron request form confirmation page

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2910]
Story
Staff testers have commented that the current Open with Permission form looks too "testy," and suggests an updated design before finalizing the "final" MVP. We would like the design of the Open with Permission form to more closely align with the rest of Blacklight.

Header should be updated 
Button should be updated to align with [Advanced Search buttons](https://collections.library.yale.edu/advanced)

Current form:
![Image](https://github.com/user-attachments/assets/fae1c424-4611-4e7e-a65e-edddec29c4d0)

Update to something like this:
![Image](https://github.com/user-attachments/assets/3ea2bec5-50a5-4750-a50d-2d211f060899)

Here's the button formatting classes/info from the advanced search page, for your reference: 

```
<div class="adv-search-sort-submit-buttons clearfix">
--
  | <input type="submit" name="commit" value="SEARCH" class="btn btn-primary lg-btn advanced-search-submit" id="advanced-search-submit2" data-disable-with="Search" aria-label="Search" role="button">
  | <button name="button" type="button" class="btn btn-primary lg-btn pull-right href-button" href="/catalog" aria-label="basic search" tabindex="0">
  | BASIC SEARCH
  | </button>    <button name="button" type="reset" class="btn btn-primary lg-btn pull-right" onclick="this.form.reset()" aria-label="clear form" tabindex="0">
  | CLEAR
  | </button>  </div>

```

**Acceptance**

- [x]  Header ‘Request information’ updated to font: _YaleNew_
- [x]  Header ‘Request information’ updated to font color: _043669_
- [x]  Text in all caps
- [x]  Text color is _043669_
- [x]  Button background color matches DCS background
- [x]  Button border is 1px, squared corners, color = _cccccb_ _(this might be wrong color)_

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1039

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.63.5](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.63.5)

**Comment by K8Sewell** [comment]
The font for the form and body text appears to still be the apple default.  Would we like to update this to the MalloryMedium we use on the rest of the body text on the site?  



![Image](https://github.com/user-attachments/assets/8749f793-2dd2-4af5-8dc8-fbb29b8eb2b9)

**Comment by sshetenhelm** [comment]
Yup, let's go ahead and update that as well.

**Comment by jpengst** [comment]
Do we want to change the color to match the metadata? 


![Image](https://github.com/user-attachments/assets/1b47c3fa-dfec-419d-9712-3130d7681e5d)

  
  
Or keep the black?  


![Image](https://github.com/user-attachments/assets/c1a169ca-7112-4d0e-b369-d55fc6688984)

**Comment by sshetenhelm** [comment]
I like the idea of keeping the black to distinguish between what is DCS text and what is "user-specific" text.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1040

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.63.6](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.63.6)

**Comment by K8Sewell** [comment]
Looks good on Test.  Will promote to UAT.



![Image](https://github.com/user-attachments/assets/f317fe04-7be5-4994-82eb-3930b092d816)

**Comment by laurenb33** [comment]
Button looks good enough to press on UAT: 
![Image](https://github.com/user-attachments/assets/9366ca15-a89b-424f-828c-0a9bf17d3520)
