### ISSUE TITLE
Review URLs blocked by WAF

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2911]
**Story**

Be sure we haven't left any APIs open.   

Current AWS WAF rules block requests to URLs that start with:

```
/management/api/download
/management/api/permission_requests
/management/api/permission_sets
/management/api/user
```

**Acceptance**
- [x] Review application routes for admin APIs and be sure they are covered by these blocks.
  - *Remember that the OID generator needs to be accessed by Goobi*
 
```
/management/api/oid
```

- [x] Note any additional routes
  - *For retrieving metadata*

```
management/api/parent
```
 
  - *For agreeing to terms*
 
```
management/agreement_term
```

- [x] Manually issue API requests (e.g., via `curl`) and verify that they are in fact blocked.
- [ ] ~~Create smoke tests that check each of the four patterns above via the cluster's public URL.~~ moved to ticket #2917 
- [ ] ~~Check with DevOps about creating a synthetic monitor for the production cluster.~~ moved to ticket #2918

**Comment by K8Sewell** [comment]
### Manual Testing Results
All WAF rules working as expected.  Two additional routes noted in ticket description that should be considered for having WAF rules created.

<details>

### On VPN

<details>
#### Prod
![Image](https://github.com/user-attachments/assets/9ccbedfa-6f8f-436e-87d8-360871e36c21)



![Image](https://github.com/user-attachments/assets/e5548489-2e53-4708-832e-4bb92dace71f)


####Test
![Image](https://github.com/user-attachments/assets/b0b345ab-4619-4b13-ac96-d9b49989bd69)
</details>


### Not on VPN

<details>
#### Prod
![Image](https://github.com/user-attachments/assets/cd4b1fb3-27b3-4f1e-8b70-d1985ca17056)

![Image](https://github.com/user-attachments/assets/0e9389cf-3509-4380-afe1-ae6f80817ae0)

![Image](https://github.com/user-attachments/assets/052a5bc0-83fc-4a4f-8ec1-b530831d4a8c)

![Image](https://github.com/user-attachments/assets/db7ba6c5-c846-42f2-944a-7421c0b4d264)


![Image](https://github.com/user-attachments/assets/8f964340-c85d-4c19-98c6-03ee89176041)


#### Test


![Image](https://github.com/user-attachments/assets/f9aa09b6-7ca3-4f6a-8a39-2ae3e825f937)


![Image](https://github.com/user-attachments/assets/39ddc4fd-ac4c-4297-89ce-e4e3b7d18e59)


![Image](https://github.com/user-attachments/assets/89920e60-99a4-4bfe-a24d-83aac732e831)


</details>


</details>

**Comment by martinlovell** [comment]
Is `management/agreement_term` in the WAF rules?
It should be if only Blacklight is making that request for the user.
It does check the OWP_AUTH_TOKE.  Should this be added to the WAF rules only to allow Blacklight if it's not there already?

**Comment by martinlovell** [comment]
`management/api/parent` is used by Metadata Cloud to get the data for use in Quicksearch, so that one needs to stay open.

So, `management/agreement_term` is the only one that needs to be added so that nothing outside the cluster can access it.

**Comment by K8Sewell** [comment]
Thanks for checking, Martin!  Will create that ticket and update summary in this one.
