### ISSUE TITLE
Build list of access-protected resource URLs/routes

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2912]
**Story**

Create a list of resources URLs/routes that are access controlled.   This list will be used for testing and monitoring.

| Resource type |  Example URL |
|---------------|-------|
| Full text           |   /annotation/oid/11781350/canvas/15014414/fulltext?oid=11781350&child_oid=15014414          |
|  Image             |   /iiif/2/15239177/full/!200,200/0/default.jpg          |
| Manifest          |  /manifests/15238597           |
| OwP Request  |  /catalog/2005512/request_form       |
| OwP Terms  |  /catalog/2005512/terms_and_conditions       |
| OwP Confirmation  |  /catalog/2005512/request_confirmation    |
| PDF                 |   /pdfs/15238597.pdf             |
| TIFF Download            |  /download/tiff/15014414      |
| TIFF Staged               |  /download/tiff/15014414/staged      |

  
**Acceptance**
- [x] Complete the list.   Add any missing URLs to the table above.
- [x] Make follow-up tickets
  - [x] Manual testing
  - [x] Smoke tests
  - [x] Monitoring/synthetics (?)

**Comment by K8Sewell** [comment]
Tickets Created:
- #2916 
- #2917 
- #2918

**Comment by sshetenhelm** [comment]
Since we have the list and tickets, we should be ready to close, yes?
