### ISSUE TITLE
[BUG] Sorting by date is numeric, not chronological

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2914]
**Story**
In the Access Requests table in Blacklight, users are able to sort the Request Date column in ascending and descending order. However, the sorting appears to be numerical instead of chronological, which means that Request Date is sorted by month and not by year-month-day. As such, in descending order, a request made in 12/2023 will display before 07/2024, etc.

[Video](https://drive.google.com/file/d/1EOTiJh-OzSRRyGOJN9e_bueCTacVFMOL/view?usp=sharing)

We would like the Request Date column to sort chronologically, if possible. 

**Acceptance**

- [x] Access Requests table 'Request Date' column sorts chronologically

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1041

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.63.7](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.63.7)

**Comment by K8Sewell** [comment]
Testing this blocked by error with auth token - see ticket #2877

**Comment by K8Sewell** [comment]
Sorting is chronological on Test.  Will promote to UAT.

**Comment by K8Sewell** [comment]
Live on UAT.  Also, live on Demo.  Was able to confirm sorting on Demo where I had more permission requests.

**Comment by sshetenhelm** [comment]
Works for me as well! Looks good, thank you, ready to close :)
