### ISSUE TITLE
Create Manual Test Plan for Restricted URLs

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2916]
# Summary
Use table of restricted URLs from tickets #2912 and #2911 to created a manual test plan for ensuring URLs behave as expected.

# Acceptance Criteria
- [ ] create document for manual test plan 
- [ ] share testing document in ticket

**Comment by jillpe** [comment]
Share google doc to Lauren. Lauren will make a copy and put this on SharePoint
