### ISSUE TITLE
Ensure or Add Unit Tests for Non-Yale and Not on Campus Users

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2919]
# Summary
We need to make sure that we have test coverage that will mock IPs outside of the allowed list and verify that non-Yale / Cognito users do not have access to URLs that should be restricted.  See tickets #2911 and #2912 for lists of protected URLs.

# Acceptance Criteria
- [ ] Verify that we have test coverage that mocks a variety of users and IPs regarding their access to the protected URLs
- [ ] Add tests if insufficient test coverage is found

**Comment by K8Sewell** [comment]
PRs in progress:
- https://github.com/yalelibrary/yul-dc-management/pull/1430
- https://github.com/yalelibrary/yul-dc-blacklight/pull/1046

**Comment by K8Sewell** [comment]
<details>


Management:
- [ ] 
- [ ] /management/api/download
    - [ ] yul-dc-blacklight/spec/requests/download_original_spec.rb
    - [x] OC - already set to off campus
    - [x] NY - added context and user for non yale

- [ ] /management/api/permission_requests
    - [ ] yul-dc-blacklight/spec/requests/open_with_permission/create_permission_requests_request_spec.rb
    - [ ] yul-dc-blacklight/spec/system/open_with_permission/permission_request_confirmation_page_spec.rb
    - [ ] OC - both specs have users that are off campus
    - [ ] NY - added tests to both for non yale users
    - [ ] 
- [ ] /management/api/permission_sets
    - [ ] yul-dc-blacklight/spec/requests/open_with_permission/create_permission_requests_request_spec.rb
    - [ ] yul-dc-blacklight/spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
    - [ ] yul-dc-blacklight/spec/system/fulltext_search_spec.rb
    - [ ] yul-dc-blacklight/spec/system/open_with_permission/permission_request_confirmation_page_spec.rb
    - [ ] yul-dc-blacklight/spec/system/open_with_permission/user_requests_table_page_spec.rb
    - [ ] OC - each spec has tests for off campus
    - [ ] NY - added non yale test to owp_object_show_page_request_spec & user_requests_table_page_spec & permission_request_confirmation_page_spec
    - [ ] 
- [ ] /management/api/user
    - [ ] Did not find this route in management routes.rb - also found no tests for it in management or blacklight
    - [ ] OC - 
    - [ ] NY - 
    - [ ] 
- [ ] /management/agreement_term
    - [ ] No tests found so added - yul-dc-blacklight/spec/system/open_with_permission/owp_agreement_term_spec.rb
    - [ ] OC - added
    - [ ] NY - added
    - [ ] 


Blacklight:
- [ ] 
- [ ] /annotation/oid/11781350/canvas/15014414/fulltext?oid=11781350&child_oid=15014414
    - [ ] yul-dc-blacklight/spec/requests/annotation_request_spec.rb
    - [ ] OC - present
    - [ ] NY - not present, authenticated and non authenticated present
- [ ] /iiif/2/15239177/full/!200,200/0/default.jpg
    - [ ] yul-dc-blacklight/spec/requests/iiif_request_spec.rb
    - [ ] OC - present
    - [ ] NY - not present, authenticated and non authenticated present
- [ ] /manifests/15238597
    - [ ] yul-dc-blacklight/spec/requests/manifests_request_spec.rb
    - [ ] OC - present
    - [ ] NY - not present, authenticated and non authenticated present
- [ ] /catalog/2005512/request_form
    - [ ] yul-dc-blacklight/spec/requests/open_with_permission/create_permission_requests_request_spec.rb
    - [ ] yul-dc-blacklight/spec/requests/open_with_permission/owp_object_show_page_request_spec.rb
    - [ ] yul-dc-blacklight/spec/system/show_page_spec.rb
    - [ ] yul-dc-blacklight/spec/system/open_with_permission/owp_agreement_term_spec.rb
    - [ ] OC - present
    - [ ] NY - present
- [ ] /catalog/2005512/terms_and_conditions
    - [ ] No tests found
    - [ ] OC - in progress
    - [ ] NY - in progress
- [ ] /catalog/2005512/request_confirmation
    - [ ] yul-dc-blacklight/spec/system/open_with_permission/permission_request_confirmation_page_spec.rb
    - [ ] OC - present
    - [ ] NY - present
- [ ] /pdfs/15238597.pdf
    - [ ] yul-dc-blacklight/spec/requests/pdfs_request_spec.rb
    - [ ] OC - present
    - [ ] NY - not present, authenticated and non authenticated present
- [ ] /download/tiff/15014414
    - [ ] yul-dc-blacklight/spec/requests/download_request_spec.rb
    - [ ] OC - present
    - [ ] NY - added 
- [ ] /download/tiff/15014414/staged
- [ ] same as above
</details>

**Comment by K8Sewell** [comment]
Deployed to Test and Demo with release [v1.63.9](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.63.9)

**Comment by K8Sewell** [comment]
Manual testing of OwP functionality mostly remains functional but I'm unable to view objects in blacklight that are part of a permission set that I am an approver for so taking back to in progress to fix the checking for admin access.

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.0](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.0)

**Comment by K8Sewell** [comment]
Issue with not adhering to approver/admin visibility is resolved.  Will promote to UAT.

![Image](https://github.com/user-attachments/assets/4a6dcdab-7672-4b74-bea8-a39cd664a997)

**Comment by sshetenhelm** [comment]
Confirming that I can see all Kissinger OwP objects, as an Admin, and that I still need to request permission for objects from sets I'm _not_ added to.
