### ISSUE TITLE
[BUG] Excel download row 1 blank

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2923]
**Story**
When a staff member downloads an excel file from the `parent_objects` table in Management using the Excel button, the excel file that is delivered has a blank row for row 1. The blank row appears to contain a bunch of merged cells. 

We would like row 1 of the spreadsheet to contain the usual column header information (`oid`, `admin_set`, etc.) in individual cells.

This issue does _not_ occur when downloading CSVs.

**Acceptance**

- [ ] Excel spreadsheet download includes header information in row 1 instead of blank merged cells

**Comment by laurenb33** [comment]
Hey @jpengst - that's correct. It appears that the first row is just one large cell and the title shows when I highlight it: 
![Image](https://github.com/user-attachments/assets/4b1e002e-7ca6-44c2-959e-ce3e315a0f28)

**Comment by jpengst** [comment]
OK, thanks for checking! 
Do we have any examples of "The blank row appears to contain a bunch of merged cells."? I'm not seeing that behavior on my end

**Comment by sshetenhelm** [comment]
[Example of row 1 = merged cell ](https://drive.google.com/file/d/1jpKxkuMQe6owBro-dehIX2BCV60sYw1O/view?usp=sharing)

**Comment by jpengst** [comment]
Ohhh, OK! Sorry, I thought a merged cell meant that all the data was merged into 1 cell. I'm not too familiar with Excel, if you haven't noticed haha

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1437

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.72.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.72.0)

**Comment by K8Sewell** [comment]
Looking good on Test.  Will promote to UAT.

![Image](https://github.com/user-attachments/assets/3752c54c-586e-4696-a308-eeb9b3323be5)

**Comment by sshetenhelm** [comment]
Works as expected on UAT! Thank you!

Ready to close
