### ISSUE TITLE
[BUG] MGMT Parent table - date filter inaccuracies

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2925]
**Story**
In Management, when a user filters via date on the `parent_objects` data table, the table sometimes includes dates out of the specified range for _Date Created_. These objects also appear in spreadsheet downloads of filtered views. This causes issues for users doing reporting, etc. 

We would like only the parent objects specified to display in the table and related spreadsheet downloads.

[Example](https://drive.google.com/file/d/1rC6awcC_pNwtOKA0OPxOICPUMkDJwfO1/view?usp=sharing)

**Acceptance**

- [x] _Date Created_ date filter excludes parent objects outside the specified range

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1432

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.71.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.8)

**Comment by sshetenhelm** [comment]
Looks good to me on test, with the ones I've tried at least

**Comment by K8Sewell** [comment]
Will promote to UAT.

**Comment by sshetenhelm** [comment]
Works as expected in UAT :) Ready to close. Thank you!
