### ISSUE TITLE
Line Coverage @ 83.78% : citation_string_processor.rb 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#293]
As a product owner, I want app > lib > yale > citation_string_processor.rb  near or at 95% so that there is a better understanding of features included in the test coverage.

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/163

# Expected Behavior
- The code coverage for citation_string_processor.rb has increased from 83.78% to 96.97%
