### ISSUE TITLE
Add link to Collections AI site

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2931]
**Story**

We would like to show a link to the Collections AI tool but only to users who have been added to the correct group in our authentication system.

![Image](https://github.com/user-attachments/assets/8d1ca6e6-093d-47e8-b0df-2a0d055c8f94)

**Acceptance**
- [x]  To logged-in users in the correct group, a link appears beneath the Universal Viewer and full text display area.  
    - [x] The link does not appear on OwP objects 
- [x] The link does not appear to other users.

**Comment by mikeapp** [comment]
WIP PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1051

**Comment by sshetenhelm** [comment]
@mikeapp Would it be possible to ensure this message displays below any current full-text? Or is it only for object with Full Text = None ?

**Comment by mikeapp** [comment]
I made the change as requested and adjusted the width to follow the metadata block.  I'd slightly prefer to have it directly under the UV and track the width of the UV, but happy either way since very few people will see it at all.

You can see that the CSS widths and breakpoints for the UV, the full text controls, and the metadata block aren't consistent across all screen widths.  Here are some examples from different widths, sometimes the metadata is wider than UV, sometimes not, etc.:

![Image](https://github.com/user-attachments/assets/851c60c8-551c-4c7f-a210-1949efa7e39c)
![Image](https://github.com/user-attachments/assets/26688fdb-a3c9-4b53-8910-181eda433599)

I don't know whether this was intended.

**Comment by sshetenhelm** [comment]
Well huh. I mean, if it looks better the other way, feel free to put it directly below the UV. 

I'll make a separate ticket for looking into the metadata and UV container widths.

**Comment by mikeapp** [comment]
PR here: https://github.com/yalelibrary/yul-dc-blacklight/pull/1051

Tests verify this doesn't show up to normal users

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.3](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.3)

**Comment by K8Sewell** [comment]
As a not logged in user and as logged in user I don't see the AI link on fulltext or non fulltext YCO objects.  @mikeapp is there additional configuration that needs to happen to add me to the cognito group that has permission to view the AI link?  Perhaps I don't have the correct permission and the groups are configured in the cognito dashboard.

**Comment by mikeapp** [comment]
Looks good to me on test

**Comment by mikeapp** [comment]
On UAT, the box w/link should not appear to anyone but a few folks (me and DevOps).

In production, I've removed Lauren's access, so she can verify that it does not appear for normal users.   Summer is in the AI user group in Cognito and should be able to see the link.

**Comment by mikeapp** [comment]
Looks good to me on UAT
