### ISSUE TITLE
Dependabot Alerts

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2932]
# Summary
Blacklight, Camerata, and Management have dependabot alerts to address.  

# Acceptance Criteria
Review and resolve alerts:

### Blacklight
- [x] [webpack](https://github.com/yalelibrary/yul-dc-blacklight/pull/1047)
- [x] [rexml](https://github.com/yalelibrary/yul-dc-blacklight/pull/1044)
- [x] [json-jwt](https://github.com/yalelibrary/yul-dc-blacklight/pull/1029)
- [x] [bootstrap](https://github.com/yalelibrary/yul-dc-blacklight/pull/1057)
- [x] [elliptic](https://github.com/yalelibrary/yul-dc-blacklight/pull/1055)
- [x] [express](https://github.com/yalelibrary/yul-dc-blacklight/pull/1056)

### Camerata
- [x] [rexml](https://github.com/yalelibrary/yul-dc-camerata/pull/385)

### Management
- [x] [webpack](https://github.com/yalelibrary/yul-dc-management/pull/1429)
- [x] [rexml](https://github.com/yalelibrary/yul-dc-management/pull/1427)
- [x] [fugit](https://github.com/yalelibrary/yul-dc-management/pull/1425)
- [x] [actiontext](https://github.com/yalelibrary/yul-dc-management/pull/1423)
- [x] [elliptic](https://github.com/yalelibrary/yul-dc-management/pull/1435)
- [x] [express](https://github.com/yalelibrary/yul-dc-management/pull/1436)

**Comment by K8Sewell** [comment]
Camerate upgrade included in deploy # 329

**Comment by K8Sewell** [comment]
Blacklight deployed to Test with release [v1.64.1](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.1)

**Comment by K8Sewell** [comment]
Management deployed to Test with release [v2.72.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.72.0)

**Comment by K8Sewell** [comment]
Functionality of both apps seems unaffected by the upgrades which is exactly what was hoped for.  Will promote to UAT.  Note: I did notice an issue during testing that we may or may not want to address - #2937.  This issue is not related to any of the packages that were updated.

**Comment by sshetenhelm** [comment]
Thank you Kait. I think we originally decided that we would treat this as a training issue in order to get the feature out on time, but since we're not ready to migrate Kissinger yet, we can address it.
