### ISSUE TITLE
Gracefully Handle No Terms

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2937]
# Summary
In Blacklight when a user visits a parent object that belongs to a Permission Set that does not have terms they are directed to a generic Rails error page.  There is code that is meant to handle empty terms so this ticket is to review and fix whatever has changed from the initial testing of this feature and now.

# Acceptance Criteria
- [x] a logged in user can visit a parent object that is part of a Permission Set that doesn't have terms and still receive a successful page load with instructions / notes on error with requesting access at this time

# Engineering Notes
There is a 'no implicit conversion of nil to string' error.  Assumption is that the page is trying to render the nil terms and it is breaking all the things.  There should be a catch already that guards against no terms but that does not appear to be playing ball.

### Screenshots
![Image](https://github.com/user-attachments/assets/c2324a8b-6db9-423c-9d9d-7286635179a1)
![Image](https://github.com/user-attachments/assets/7296c6b3-ba7f-4290-a2ea-0c355fd9e7d7)
![Image](https://github.com/user-attachments/assets/cd76fa05-3bdb-4406-90c8-12e4f4307f1e)

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.3](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.3)

**Comment by K8Sewell** [comment]
Looking good on Test.  Able to load page of parent object of permission set with no terms successfully and display error message when no terms are found.  Will promote to UAT.

![Image](https://github.com/user-attachments/assets/128c5a12-a133-4b72-aea0-d9d156c70133)
![Image](https://github.com/user-attachments/assets/9c443f8d-2dfa-4f98-9e4b-938d6f1a6a2d)

**Comment by K8Sewell** [comment]
Waiting to deploy to UAT until other ticket in release (#2931 ) has passed QA.

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you so much :) Ready to close
