### ISSUE TITLE
Switch Out Node-Sass for Sass

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2938]
# Summary
Node-sass has reached EOL.  Recommended approach is to switch to Sass.

![Image](https://github.com/user-attachments/assets/806e8670-060a-4524-8b9f-6ae663a12438)
![Image](https://github.com/user-attachments/assets/ea8908b7-5b13-433d-be42-fd15517be1de)

# Acceptance Criteria

- [x] `node-sass` is replaced with `sass` in Blacklight app (not used in Management or Camerata)

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1062

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.4](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.4)

**Comment by K8Sewell** [comment]
Nothing out of the ordinary on Test.  Will promote to UAT.
