### ISSUE TITLE
Align metadata & UV container widths

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2940]
The ratio of metadata container to UV seems to change based on screen size. In some sizes, the UV and metadata have the same width. In others, the metadata expands past where the UV expands.

1. Was there a reason for this?
2. If not, can we align the widths? 

Screenshots:
Full screen, zoom at 100%
![Image](https://github.com/user-attachments/assets/69900616-3b0c-4a47-92c3-df8a98de3cba)

Narrow window, zoom at 100%
![Image](https://github.com/user-attachments/assets/92078c0c-5ca1-4541-9e0b-0bfddebafe1a)

Full screen, zoom at ~67%
![Image](https://github.com/user-attachments/assets/b0929c6d-2e4b-4671-ad03-27290f9fbaf6)

**Acceptance**

- [x] Determine if there was a reason for this, and if not....
- [x] Update container of metadata to match width of UV

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1063

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.5](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.5)

**Comment by K8Sewell** [comment]
Behaving as expected on Test.  Deployed to UAT.

**Comment by sshetenhelm** [comment]
Works as expected on UAT. Thank you! Ready to close.
