### ISSUE TITLE
Add HoneyBadger exception reporting to iiif-image service

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#295]
**ISSUE**
Based on our discussion of how to handle missing images (see #262), we determined that the optimal solution would be to track requests for invalid image IDs, but not attempt to deliver any type of placeholder.  After some discussion of options, we agreed that attempting to track this type of error using HoneyBadger would provide consistency with how we track, monitor, and manage exemptions in the blacklight and management applications.

**ACCEPTANCE**
- [ ] The iiif_image service is configured to report exceptions to HoneyBadger
   - [x] Cantaloupe is updated with the necessary HoneyBadger config
   - [x] We have a new project and API configured in HoneyBadger
- [x] When I request an image using an invalid ID, a corresponding error gets logged in the iiif-image honeybadger project.  (e.g. when I request something like https://collections-test.curationexperts.com/iiif/2/bad_wolf/full/250,/0/default.jpg or https://collections-test.curationexperts.com/iiif/2/87654321/full/250,/0/default.jpg)

**Comment by mark-dce** [comment]
@bess may have some experience adding gems to a Cantaloupe server and/or see this commit in a similar cantaloupe project https://github.com/sul-dlss-labs/image-server/commit/8ea3fa6bcdbb597efe3e29849823b950e94cd1e0

**Comment by JzGo** [comment]
Looks like we need to upgrade our subscription. Honeybadger is telling me that I've reached my project limit.

**Comment by mark-dce** [comment]
Just made Jez an admin on the YUL-DC honeybadger team and that appears to have fixed the problem.

**Comment by JzGo** [comment]
Have a configuration for Honeybadger to report on invalid ids such that:


### **When given an id with no corresponding image**
![Screen Shot 2020-07-09 at 10.09.03 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/f7bf6ed3-1a9b-46ec-8bf8-d0bf00e7e11b)


### **Honeybadger will receive an notification**
![Screen Shot 2020-07-09 at 10.09.12 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/5dc58ba3-6172-4202-92d6-266fd4d97eff)

![Screen Shot 2020-07-09 at 10.09.21 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/ff80c00a-07ac-4c00-8416-03b62c5c5065)


**Note**: This was done with a standard Honeybadger notification and does not pull in the stack trace.

**Comment by JzGo** [comment]
PR up. If someone has a chance to pull it down and take a look: https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/8

**Comment by fnibbit** [comment]
Good news/bad news: I pushed up a new imageserver image to dockerhub (v1.0.1) and deployed it to collections-test.  The good news is that it built/deployed/passed deploy tests.  The bad news is that I'm not getting honeybadger notifications when I visit nonexistent image URLs on collections-test. (Could be my error in some way!)

Deployment details: Set the HONEYBADGER_API_KEY_IMAGESERVER environment variable in .secrets to the project-specific API key.  Added a line to docker-compose to pass that variable through, added a line to secrets.template to reflect that variable. https://github.com/yalelibrary/yul-dc-camerata/commit/720fc0f527177fba9c9814d670c45b7cd65c18f0

I think I'm going to focus next on getting docker image pushes on this + the other non-rails services automated so testing+debugging things like this will be easier.

**Comment by mark-dce** [comment]
@fnibbit see #356 for building & tagging containers on releases.  

@fnibbit & @JzGo I also wrote up #354 & #355 for more consistent handling of API Key environment variables.  Would it make sense to close this ticket and continue with those?  I.E. Honeybadger is configured, and we have seen exceptions logged, the issue now seems to be more generally about how we're handling setting up environment variables and I think that's a different issue than this ticket was meant to address.
