### ISSUE TITLE
Update 'Special Collection Guide' header menu link

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2951]
**Story**
The link titled _Guide to Using Special Collections_ located in the Digital Collections Header Menu under the _Research_ drop-down needs to be updated to point to a different url.

New URL: `https://library.yale.edu/find-request-and-use/use/using-special-collections`

The text can remain the same; only the link needs to be updated.

![Image](https://github.com/user-attachments/assets/2ea35e01-0828-4fa6-8d3f-53dcb620ba02)

**Acceptance**

- [x] _Guide to Using Special Collections_ link updated to new URL

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1068  
  
Note: I also updated the "Guide to Using Special Collections at Yale Univerity" link in the Help Guide.

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.7](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.7)

**Comment by sshetenhelm** [comment]
Thanks for doing the other link too JP.

Looks good on Test; let's bump to UAT.
