### ISSUE TITLE
Image not loading / Cache issues in Blacklight

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2958]
**Story**
Multiple users have stated that they are experiencing issues with images not loading correctly in DCS. This is usually resolved by using a different browser or incognito browser. These issues have been happening within shorter time frames -- that is to say, users have expressed experiencing the 'No Image Available' thumbnails and inability to load images within a shorter time period than previously. 

We would like to:
* investigate why this issue is happening more frequently
* see if it can be prevented

**Acceptance**

- [ ] Investigate issue (cache?)
- [ ] If possible, change Blacklight settings to prevent 'No Image Available' and loading issues from showing as frequently

**Comment by mikeapp** [comment]
I'll observe that the image servers instances are being replaced more often, the once a week restart may not be sufficient.

**Comment by laurenb33** [comment]
Reminder for tomorrow - could we put a waiting label on this and I'll keep the team posted when there is an update?

**Comment by laurenb33** [comment]
Thanks to @thescreamingmandrake the automation for deploying the image servers MWF at 8 am is all set! Ready to close.
