### ISSUE TITLE
Login Link or Redirect

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2959]
**Story**
When a user that is not already logged into the Management App clicks on a link to a Management Page other than the login page, they see a screen that states `Not found. Authentication passthru.` with no redirection links. We would like the page to either (a) redirect to the Management log in page for the appropriate environment or (b) include a link to the log in page for the appropriate environment.

**Acceptance**

- [x] Users are given option to log in when clicking on a Management link instead of only 'Not found' message
- [ ] ~~After logging in, users are taken to the original URL they were trying to navigate to~~ *removed from AC in standup - 2024.10.31*

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1456

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.72.8](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.72.8)

**Comment by sshetenhelm** [comment]
Confirmed I'm getting redirected to login screen on Test :) 

Let's bump to UAT

**Comment by sshetenhelm** [comment]
Looks good on UAT.

Ready to close :)
