### ISSUE TITLE
Batch job for validating migrated images

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2962]
**Story**
For migrated image files, we have checksums pulled from Ladybird (see #2900). We would like to use these checksums to validate migrated image files in DCS. 
This validation should occur via a nightly batch job. 
Ideally, it will be combined with the current validation job.
On the individual batch process page, there should be an error message when an image does not pass validation. 

Will likely need to complete #2963 prior to this ticket.

**Acceptance**

- [x] update integrity check batch job to include checksum verification as well as original file presence for all parent objects, including those with digital_object_source == Preservica
- [x] update integrity check to look for file size of 0
- [x] Validation occurs via an automated nightly job - *Integrity Check batch job is a cron job that is already set to run nightly*
- [x] Job either shows status of complete if successful or provides a message when an image does not pass validation of checksum - *This is the current behavior of the Integrity Check Job for file presence but we should confirm desired messaging.* 

_Message for checksum mismatch:_ 
The child oid # 007 has a checksum mismatch. The checksum of the image file saved to this child oid does not match the checksum of the image file in the database.  This may mean that the image has been corrupted.  Please verify integrity of image for child oid # 007 by manually comparing the checksum values and update record as necessary.

_Message for file size=0:_
The child oid # 007 has a file size of 0. Please verify image for child oid # 007.

**Comment by sshetenhelm** [comment]
I think the sample message you've provided will work. Thank you!

**Comment by K8Sewell** [comment]
Which checksum attribute will be 'source of truth'? ----- options: checksum, sha512_checksum, sha256_checksum, md5_checksum

Current handling of a child object checksum mismatch no action is currently taken on that child object.  An error message is relayed to the user but no changes are made on the object.  What if there was a default behavior or user initiated action to update the child object's checksum data if incorrect data is used or found - as is the case with many ladybird objects whose md5_checksum is known to have incorrect values?  The child object's checksum could be updated based on the actual file checksum because we would need to pull that value for the comparison.

**Comment by K8Sewell** [comment]
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1467

**Comment by jpengst** [comment]
Deployed to Test v2.73.6

**Comment by K8Sewell** [comment]
Currently running Integrity Check Job.

<img width="1273" alt="Image" src="https://github.com/user-attachments/assets/5b74145e-2c27-4323-8007-038cbb213ac0" />

**Comment by K8Sewell** [comment]
Cron job enqueued on UAT but may take some time before it is finished.  Will check back tomorrow morning.

<img width="143" alt="Image" src="https://github.com/user-attachments/assets/e0dc43a0-cee9-4bd9-bf0c-e4ac4b801df4" />

**Comment by K8Sewell** [comment]
New batch messages working as expected on UAT.  Will make a ticket to re-enable the integrity cron job on all environments once the checksums are ingested.

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/3dd833b5-905e-4ca6-bf5f-6791ced2b4c6" />
