### ISSUE TITLE
Adjust CORS for Static Fonts

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2972]
# Summary
Post enabling CSP configurations numerous errors for static fonts' website CORS settings.  This ticket is to update the `static.library.yale.edu` site with conducive CORS settings.

# Acceptance Criteria
- [ ] static font at `https://static.library.yale.edu/fonts/mallory/Mallory-Light.woff` updated to allow cross origin for collections*.library.yale.edu/management
- [ ] static font at `https://static.library.yale.edu/fonts/mallory/Mallory-Light.woff2` updated to allow cross origin for collections*.library.yale.edu/management
- [ ] static font at `https://static.library.yale.edu/fonts/yaledisplay/YaleDisplay-Roman.ttf` updated to allow cross origin for collections*.library.yale.edu

# Screenshots

<details>

## Management
![Image](https://github.com/user-attachments/assets/22d22664-3a69-474e-b61b-fd87dd214c26)

## Blacklight
![Image](https://github.com/user-attachments/assets/6b044959-d038-4264-a02b-1caa39c97b98)

</details>

# Engineering Notes

## Management
Mallory-Book and Yale New Roman work
Mallory-Light does not work

## Blacklight
MalloryMP-Medium, Yale New Roman, MalloryMP-Black, and Mallory-Book work
Yale Display Roman does not (woff works, ttf does not)

**Comment by ra359** [comment]
INC2940098 created and assigned to ITS/SpinUp team.

**Comment by K8Sewell** [comment]
No longer seeing CORS errors for static fonts on management or blacklight.

<img width="1276" alt="Image" src="https://github.com/user-attachments/assets/d560d7ea-a66a-4c4f-a4bc-1c6030bd1702" />
<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/7bb8c062-4d9d-4f8a-9955-2606b1edca54" />

<img width="485" alt="Image" src="https://github.com/user-attachments/assets/40ec79e4-49c4-4fb0-b55f-3d7a491f2875" />

<img width="499" alt="Image" src="https://github.com/user-attachments/assets/63408314-b588-4ede-87d9-ee60e591be9d" />
