### ISSUE TITLE
Problem Report out of Memory

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#2976]
The Problem Report is running out of memory when there are a lot of children without widths or heights

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/1464

**Comment by K8Sewell** [comment]
Deployed to Test with release [v2.73.3](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.73.3)

**Comment by K8Sewell** [comment]
Looking good on Test.  Deploying to UAT.

**Comment by K8Sewell** [comment]
Worker containers stable post deploy.

Manually triggering the job on the page works.  Currently will only pull first 1000 child objects without width and height.  Additional work needed to batch report effectively to not run the ProblemReportJob out of memory.

Saw a job that indicated an email was successfully sent to Summer but will need to confirm it was received.

![Image](https://github.com/user-attachments/assets/6e2b907e-ca53-48f0-9117-7cd11dd853c2)

**Comment by sshetenhelm** [comment]
Confirming the email was received! Thank you :)
