### ISSUE TITLE
Remove manifest fixtures with missing images

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#299]
**ACCEPTANCE**
- [x] Scan all works for canvasses pointing to non-existent tiffs 
    - [x] Remove the corresponding manifest from the fixture repo if the first image is missing.
- [x] Release a new version of the manifest service using the updated fixtures

**EXAMPLES**
* Fort Vancouver 2004628.json
* [Magazine page with various photographs of Leontyne Price] 2034600.json

**Comment by FCRodriguez7** [comment]
The manifest service is found here: https://github.com/yalelibrary/yul-dc-fixture-manifests

One can see all the manifest here: https://collections-test.curationexperts.com/manifests/

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3663df86-5b84-498f-8732-d84f1f2063ed)

**Comment by FCRodriguez7** [comment]
Remove manifest fixtures with missing images#299

Created a PR: https://github.com/yalelibrary/yul-dc-fixture-manifests/pull/4

**Comment by FCRodriguez7** [comment]
**New Current**

![Screen Shot 2020-07-02 at 11.39.14 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5916b447-f45f-40fe-9e16-fe6ac6e87a57)


![Screen Shot 2020-07-02 at 11.39.00 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/87df6801-d6d4-45fd-a7d5-b90bcb50a486)



![Screen Shot 2020-07-02 at 11.39.22 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d30e4cfc-ba15-4d63-907b-6a9640cd219d)

**Comment by FCRodriguez7** [comment]
Release a new version of the manifest service using the updated fixtures --> I created a new release for the manifest service v2.0.1.
