### ISSUE TITLE
Display a "No Preview Available" thumbnail when manifest is missing

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#300]
**STORY**
As a repository owner, I want the application behavior to degrade gracefully when backend services or data is unavailable, so that users can still make use of the system.  In particular, I want the system to display search results even when thumbnails can't be loaded.

**ACCETPANCE**
When a thumbnail is not available for a work
- [x] Display a placeholder in search results

**IMPLEMENTATION NOTE**
This should happen both when
* There is no manifest for the work at all
* The first image in the manifest can't be loaded

**CURRENT**
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3064318/86147828-7a347700-babf-11ea-9cb0-64a4e094c2bd.png">

**DESIRED**
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3064318/86148288-0e064300-bac0-11ea-900f-ab5ef7eaa7f3.png">

**Comment by FCRodriguez7** [comment]
The PR for the code change: https://github.com/yalelibrary/yul-dc-blacklight/pull/158

![Screen Shot 2020-07-01 at 4.19.17 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/099f7731-a8f1-44ae-9b1a-41ed49235a22)

**Comment by FCRodriguez7** [comment]
The manifest service is found here: https://github.com/yalelibrary/yul-dc-fixture-manifests

One can see all the manifest here: https://collections-test.curationexperts.com/manifests/
