### ISSUE TITLE
Diagram new work ingest flow

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#301]
**ACCEPTANCE**
One or more diagrams, pictures, screen mocks that show
-  [ ] The steps a user needs to take to upload 50 new works 
   - [x] Include how to specify whether to use LadyBird, Voyager, or ASpace as the source of authority
   - [x] Include how to specify which image OID(s) should be attached and the order
   - [x] Describe whether the process is the same or different for Goobi, externally digitized works, and/or legacy migrations
   - [ ] Describe the steps/screens/buttons a user should need to follow
   - [ ] Sketch any reporting or status screens the user should see

**Comment by mark-dce** [comment]
We discussed this as a partial description of the workflow:
https://drive.google.com/file/d/1ilFGwsUory0q_8DZgT8fQZ1Ete1GBlcA/view?usp=sharing

**Comment by dl-maura** [comment]
![DSU_Goobi_Flow - BookEye.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/93e3c6f6-666c-45c2-b7ea-cc67281fdf5c)![DSU_Goobi_Flow - StandardImaging.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/35f4041a-de59-40d0-b262-d97182e86b08)

**Comment by mark-dce** [comment]
Higher Level Ingest Workflow documents:

* [METS Ingest Specification](https://docs.google.com/document/d/1Vi0U1OWY6fx7_mOKx9JcMpnAbGIhkgYFxH09AqTUp9M/edit#) 
    * [METS Import Workflow](https://docs.google.com/drawings/d/10uq_8LRzcyal5aZrdFG3D53dSAfvW0MKYkmhY0YNcgI/edit)
* [Import Jobs](https://docs.google.com/drawings/d/1QAbeNliTefvq8bU4YhDm5PTnput0liTrNtUY7z5xPC0/edit)
* [Import Errors](https://docs.google.com/drawings/d/1uTsJ61U_r7eUQ54r38HdjCHtMqO6atdzCGqcM4y0h2Y/edit)
