### ISSUE TITLE
Ladybird field statistics

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#303]
**STORY**
As a product owner, I want to understand which fields occur with what frequency in LadyBird.

**ACCEPTANCE**
Using a random sampling of 10,000 public items from LadyBird (i.e. the LadyBird endpoint in the Metadata Cloud)
- [x] Produce a list of which field names occur
- [x] Count how many times each field occurs (this should be a number somewhere between 1 and 10,000)
    - [x] Display the raw count
    - [x] Display the count as a percentage of the total sample
- [ ] Track the elapsed time to run the process

**IMPLEMENTATION NOTE**
We may want to re-run this with different sample sets and sizes over the duration of the project, so provide a mechanism to run this as a rake task or page we can display in the management web app.

**Comment by mark-dce** [comment]
@maxkadel can you paste the results of the 10,000 object run to this ticket.  NOTE: this doesn't have to be run from test or demo - the data should be the same whether run from one of the ECS clusters or locally - right?

**Comment by mark-dce** [comment]
Further data questions:
* Which fields look like they contain controlled vocabularies? (how many terms are in the vocabulary, where do they come from)

**Comment by maxkadel** [comment]
https://docs.google.com/spreadsheets/d/1WeMppPyJ9Qly0fQp575UBLDSz-4ziZVmH6e5OgQdql0/edit?usp=sharing 

Sample of 9,775 Ladybird records
