### ISSUE TITLE
Rebuild collections-demo with persistence services

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#308]
**ACCEPTANCE**
- [ ] We can deploy to the cluster at `yul-demo` using new persistence scripts
- [ ] We do not have to re-import works that have already been imported during previous deploys

**IMPLEMENTATION HINT**
- [ ] We don't want to take collections-demo out of service for this, so we need to
    - [ ] Build a new cluster at `yul-demo2` & deploy current code to it
    - [ ] Point DNS at the load balancer for `yul-demo2`
    - [ ] Delete the old (non-persisting) `yul-demo`
    - [ ] Build a new (persisting) cluster at `yul-demo`, deploy to it, and load content
    - [ ] Point DNS at the load balancer for (the new) `yul-demo`
    - [ ] Delete the `yul-demo2` cluster

**Comment by fnibbit** [comment]
I think it makes sense to point dns to the existing yul-test-ng cluster while rebuilding yul-demo.
