### ISSUE TITLE
SPIKE: Restrict AWS keys for deployment only

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#309]
**STORY**
As an operations manager, I would like to be able to restrict which users can spin up new ECS clusters, so that folks don't inadvertently spin up orphan cluster that I have to keep paying for.

**ACCEPTANCE**
- [ ] We can set an AWS account so that it can deploy successfully (i.e. can deploy-main)
- [ ] The same account cannot create new AWS resources (i.e. can't build-cluster or add-alb)

**Comment by JzGo** [comment]
The following policy combined will all the **ec2 List actions** (omitted) created a policy that restricted a user from creating and configuring a cluster but allowed them to push (`service up`) and list `service ps`) services from an ecs cluster.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:PassRole"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ecs:CreateService",
                "ecs:DescribeTaskDefinition",
                "ecs:DescribeContainerInstances",
                "ecs:DescribeServices",
                "ecs:DescribeTasks",
                "ecs:ListAccountSettings",
                "ecs:ListTasks",
                "ecs:ListTaskDefinitions",
                "ecs:RegisterTaskDefinition",
                "ecs:UpdateService"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup"
            ],
            "Resource": "*"
        }
    ]
}
```

I experimented on using a very small application on my personal aws account so some expansion may be required for camerata.

Next steps are:

- [ ]  Create this policy in dce aws
- [ ]  Create a user and attach this policy
- [ ] Confirm user gets an error when attempting to create a cluster
- [ ] Confirm user can push and list services in via camerata commands

**Comment by JzGo** [comment]
Created new IAM policy: https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::229792048549:policy/ECSDeployOnlyIAMPolicy$jsonEditor

**Comment by fnibbit** [comment]
RAILS_MASTER_KEY=redacted bin/deploy-main.sh rkadel-jul14
Target cluster: rkadel-jul14
Using AWS_PROFILE=rkadel-restricted
      AWS_DEFAULT_REGION=us-east-1

An error occurred (AccessDenied) when calling the DescribeTargetGroups operation: User: arn:aws:iam::229792048549:user/rachel.kadel.restricted is not authorized to perform: elasticloadbalancing:DescribeTargetGroups

I think we need to add more inspecting-things types of privileges, both to make our existing scripts work and to empower team members to inspect and troubleshoot what they're doing when they deploy.

**Comment by fnibbit** [comment]
With Jez's most recent updates,  works for our existing deploy scripts when bin/get-params.sh isn't needed  ($CLUSTER_NAME-$TASK_NAME-params.yml is present); we're going to pair tomorrow to get some access blockers for iterating on this cleared up.

**Comment by JzGo** [comment]
I've successfully updated the policy to allow all the commands in get-params.sh (added Describe permissions for cloudformation and elasticfilesystem.

**Note**:

The following is the first error I had to debug. 

`An error occurred (SignatureDoesNotMatch) when calling the ListStackResources operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

It's a little misleading. Upon checking my AWS credentials for the restricted user, I discovered that the SECRET_KEY was  several characters shorter that my usual key. Creating a new set of keys got me what I needed.

**Comment by JzGo** [comment]
I was successfully able to run the deploy-solr and deploy-psql scripts using my restricted user. Additionally tested some other commands to ensure that they received meaningful responses from AWS. I can confirm that commands like `aws elbv2 describe-target-groups` and `aws elbv2 describe-load-balancers` return useful data from AWS (results were blank and without errors before).

**Comment by JzGo** [comment]
Rachel intends to take another pass at testing this on this on Friday.

**Comment by JzGo** [comment]
After working through some camerata issues last week, it looks like the current permissions allow solr deploys at the very least. But the service doesn't stay up. Need to troubleshoot cluster or rebuild it in order to finish these and unblock testing the cluster based restrictions.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/ee7a4a41-0272-49f4-81c0-bcc8eb7e5a10) -- all apps currently running on this cluster deployed by the rkadel-restricted account which uses jez's settings.  Looking forward to pairing on #310 this afternoon.
