### ISSUE TITLE
SPIKE: Restrict which clusters a user can deploy to

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#310]
**STORY**
As an operations manager, I would like to be able to allow developers to manage self-service deploys to a test environment, but restrict who can deploy who can deploy to a production-like demo environment.

**ACCETPANCE**
Given a developer AWS IAM user,
- [ ] They can deploy to the `yul-test` cluster
- [ ] They cannot deploy to the `yul-demo` cluster

Given an operations AWS IAM user,
- [ ] They can deploy to the `yul-test` cluster
- [ ] They can also deploy to the `yul-demo` cluster

**NOTE**
For the purpose of this ticket, only restrict one test account: arn:aws:iam::229792048549:user/dce-hosting.mark - we can generate a new access ID and Key for this user and share it securely for whoever is working on this ticket.

**Comment by fnibbit** [comment]
A documentation breadcrumb -- not picking up the ticket right now. 
from https://docs.aws.amazon.com/AmazonECS/latest/developerguide/security_iam_service-with-iam.html:

Resources
The Resource element specifies the object or objects to which the action applies. Statements must include either a Resource or a NotResource element. You specify a resource using an ARN or using the wildcard (*) to indicate that the statement applies to all resources.

The Amazon ECS cluster resource has the following ARN:

arn:${Partition}:ecs:${Region}:${Account}:cluster/${clusterName}
For more information about the format of ARNs, see Amazon Resource Names (ARNs) and AWS Service Namespaces.

For example, to specify the my-cluster cluster in your statement, use the following ARN:

"Resource": "arn:aws:ecs:us-east-1:123456789012:cluster/my-cluster"
