### ISSUE TITLE
Update IIIF Awesome site to include additional resources

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#311]
In #270, @FCRodriguez7 and @dylansalay identified additional resources that would be good to add. 

**ACCEPTANCE**
- [x] Make a PR to the IIIF-awesome repo with the missing resources identified in #270
- [x] Paste a link to the PR in the comments below

**Comment by FCRodriguez7** [comment]
---COPIED NOTES FROM TICKET
The Git site, Awesome-iiif, has curated a diverse set of materials at different skill sets. The site is a great resource for everyone. However the site lacks an implementation demos section (https://library.stanford.edu/blogs/stanford-libraries-blog/2019/05/introducing-mirador-3-next-generation-image-comparison-viewer). The site is also missing valuable content, see below.

iiif Apps & Demos
Missing Viewing Clients

IIPMooViewer
Micro Service
Image Servers
Missing Servers

FSI Server & the adaptor
Europeana
A definition of a SHIM server show below the SHIM heading.

There are broken links on the site. While we recommend for the continuous use of the site, we strongly recommend adding PRs to correct some of the issues on the "Awesome" site.

**Comment by FCRodriguez7** [comment]
I have included a definition for SHIM servers.
