### ISSUE TITLE
Tickets for Yale branded footer

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#318]
**STORY**
Based on our conversation with Matt Walker, we'd like to scope the work for styling the application footer

**ACCEPTANCE**
- [x] Write a ticket(s) for any color and styling that should be applied specifically to the page footer
- [x] Write a ticket(s) for any static links that should be included in the footer (e.g. System Status, Privacy Policy , Accessibility, etc.)
- [x] Write a ticket(s) describing any wireframes or mock-ups that would be helpful to clarify design intent or present design options before coding

**NOTES**
In addition to resources provided by Matt, feel free to consult existing Yale sites for context on existing links and functions (Use Matt's visual styling wherever possible):
* **Beinecke DL:** https://brbl-dl.library.yale.edu/vufind/Search/Results?lookfor=blue&type=AllFields&submit=Find&limit=16&sort=relevance
* **FindIt** (Yale Library Digital Collections): http://findit.library.yale.edu/?utf8=✓&utf8=✓&search_field=all_fields&q=blue
* **Yale University Library Homepage:** https://web.library.yale.edu

**Comment by K8Sewell** [comment]
Tickets for team review:
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/352
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/353
