### ISSUE TITLE
Implement an OID minter service to allocate IDs

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#320]
**STORY**
Multiple services including Goobi Ingest, Preservica, the new management application, and LadyBird need a means to allocate unique IDs without collisions.  Going forward, we would like Goobi to request the OIDs that will allow digitized objects to be identified in both the digital library (management application) and Preservica.  Initially we plan to seed the production version of this service with a number sufficiently high that it will not overlap remaining OIDs assigned by legacy users of LadyBird.

**ACCEPTANCE**
- [ ] We have a service that accepts requests for single new OIDs and returns unique IDs

**DETAILS**
See the design draft here: https://docs.google.com/document/d/1YkEZnyk2eAYa7ASTEB0zy5wyGaaZIRB040XUW0TYQ3I/edit

**Comment by mikeapp** [comment]
I'd be happy to join whoever works on this.  I came across an interesting issue with creating a migration for a Postgres sequence object:
https://stackoverflow.com/questions/9144556/create-sequence-in-migration-not-reflected-in-schema

**Comment by orangewolf** [comment]
@mikeapp reviewed this approach. It looks solid. One thing I will say that is a win for the more AR based "put it in a model" approach.  Your loop has the potential for sequence stealing.  If I have a request for 1000 oids and a request comes in for a 5 oids I might get:

...
999
1000
1001
1002
1005
1006
...

and
1003
1004
1010
1012
1013

or some other random setup.  If we go model we can use a bulk insert to keep blocks together and skip the loop.  I'm not sure if / how to do that with a straight sequence, though if you can it would solve this issue and make your current implementation my preferred implementation.

**Comment by mikeapp** [comment]
@orangewolf A normal transaction won't guarantee a gapless sequence; the code will need to begin a transaction, acquire a database lock, perform the SELECTs, then commit to release the lock.  This will block other callers.   On the other hand the process is fast (~1ms/OID) so the likely impact of contention is low.  I'm happy to make this change if the approach sounds reasonable.
