### ISSUE TITLE
Log OID Requests

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#323]
**ACCEPTANCE**
- [x] The IP address of requests are logged along with the OIDs allocated
- [x] [BONUS] if #322 is complete, log the username as well

**Comment by orangewolf** [comment]
@mark-dce @mikeapp we see two (ish) reasonable approaches here.

a) save the ip/user to the db when the OID is created. This would make refactoring the OID minter worth while. 

b) write to the Rails log (or some other log file).  This isn't as fast, but isn't slow, is a little harder to parse back if you need it, but has the advantage of being separate from the database table.

Do either of you have strong opinions on this? I acknowledge the ticket says "log" btw, which makes us lean toward (b), but we know that log shipping / saving in the cloud space is also more complex.

**Comment by mikeapp** [comment]
I'm for (b).  I think interest in this data is going to be ephemeral.

**Comment by orangewolf** [comment]
Too pretty - remove \n's
