### ISSUE TITLE
Build cluster with persistence in Yale AWS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#325]
**STORY**
We have automated build scripts that should allow us to build new ECS clusters in any AWS organization where we have users with the necessary privileges.  We'd like to test in an organization not owned by DCE.

**ACCEPTANCE**
- [x] Decide on a the name for the environment (staging? uat?, ???)
- [x] Build a cluster using the Camerata build scripts
- [x] Ensure we can deploy to the new cluster
- [x] Ensure the deploy_spec test suite runs successfully
- [x] Ensure selected members of the Engineering, DevOps, and Contractor teams can deploy

**Comment by kbcarter** [comment]
The test cluster is up and running with persistent storage. We are now waiting for DNS entry for collections-test.library.yale.edu to be created.
URL: alb-yul-dc-test-351429310.us-east-1.elb.amazonaws.com

**Comment by kbcarter** [comment]
Update DNS name: collections-test.library.yale.edu

**Comment by dl-maura** [comment]
PR in progress (yul-setup branch)

**Comment by dl-maura** [comment]
Working on README
