### ISSUE TITLE
Remove database authentication

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#330]
yul-dc-blackight currently has both CAS and database authentication enabled. The only reason to keep database auth is if we have people working on the project who cannot authenticate to Yale CAS.

AFTER @K8Sewell and @dylansalay have Yale logins:

- [ ] Remove database authentication

**Comment by K8Sewell** [comment]
Dylan, Jez, Rob, and I all received access today.  Pairing is planned to ensure all are able to successfully access.

**Comment by bess** [comment]
I am reassigning this ticket to @orangewolf who has kindly offered to take a look at where I'm stuck. My latest work is on this branch: https://github.com/yalelibrary/yul-dc-blacklight/tree/sign_into_cas
