### ISSUE TITLE
Add Names and Labels

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#332]
# Summary 
Lighthouse Audit 2020.07.08 identified the following areas for accessibility improvement:

### Home Page
* [x] Form elements do not have associated labels - Failing Elements: input.search-q.q.form-control.rounded-0.tt-hint

### Search Results Page
* [x] Form elements do not have associated labels - Failing Elements: input.search-q.q.form-control.rounded-0.tt-hint

### Object Show Page
* [x] ```<frame>``` or ```<iframe>``` elements do not have a title - Failing Elements: iframe.universal-viewer-iframe
* [x] Image elements do not have [alt] attributes - Failing Elements: img
* [x] Form elements do not have associated labels - Failing Elements: input.search-q.q.form-control.rounded-0.tt-hint
* [x] Links do not have a discernible name - Failing Elements: a.iiif-logo

**Comment by K8Sewell** [comment]
Resolved all items that were internal to our project.  The ```input.search-q.q.form-control.rounded-0.tt-hint``` that is failing on all pages is not actually the search input but the autocomplete associated w/ it.  This element also fails on the Blacklight Demo site so I think input from the team would be prudent to guide whether this is a fix that actually should go into the main Blacklight repo.

# Screenshot
<details>
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/c3748521-6508-4310-9580-72c99f95b8ce)
</details>

**Comment by DraxIndustries79** [comment]
Create separate ticket for Blacklight fix.  Make it clear we've done an accessibility audit and that will help the BlackLight folks prioritize it for merging.

**Comment by DraxIndustries79** [comment]
Kait will talk to Lea Ann and make a new ticket:
Form elements do not have associated labels - Failing Elements: input.search-q.q.form-control.rounded-0.tt-hint

**Comment by K8Sewell** [comment]
Ticket created - https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/391
