### ISSUE TITLE
Fix code coverage badge on the README

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#335]
The code coverage badge for the management app isn't displaying a number (see attached screenshot)

- [ ] Figure out why we're not seeing code coverage metrics and fix the problem

![Screen Shot 2020-07-10 at 10.47.50 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/1c553ac3-c053-4f4f-8b7a-8527b3f6fc09)

**Comment by mark-dce** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3064318/87992044-fc0b3500-caac-11ea-9d9c-e6e97ce79b40.png">
