### ISSUE TITLE
Add Search Result Highlighting

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#337]
**STORY**
The current [Beinecke site](https://brbl-dl.library.yale.edu/vufind/Search/Results?lookfor=baldwin&type=AllFields&submit=Find&limit=16&sort=relevance) site provide match highlighting.  We want the new system to have this capability too.

**ACCETPANCE**
Highlight search matches when they occur on the following fields:
- [x] Title (see #338) 
- [x] Creator
- [x] ~Date~ *uses facets not search*
- [x] Resource type
- [x] Call Number

**NOTES**
#338 Covers highlighting for the title since it's behavior is slightly different in regard to truncation & linking
#385 Covers highlighting fields that don't display in search results by default

**Comment by FCRodriguez7** [comment]
The highlighting for "Creator" works, see the image below: 

![Screen Shot 2020-07-24 at 4.23.22 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/05b53aad-6339-40a1-b802-4b7c843c343d)

**Comment by FCRodriguez7** [comment]
The highlighting did not work for  "Resource type" and "Call Number" due to the solr field type.   The field type must be a ssim instead of a tsim.

**Comment by FCRodriguez7** [comment]
Prototype the highlighting with a tesim instead of tsim: description_tesim.

**Comment by edejesusyale** [comment]
Using tesim as the field type makes the highlighting work in the search results.
The first is with ssim field type and the second is with tesim:

![failures_r_spec_example_groups_search_results_displays_field_within_search_results_fails_32.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/a2bdb43e-dd28-472a-bfb0-10fd3efb02ac)
![failures_r_spec_example_groups_search_results_displays_field_within_search_results_fails_514.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/211772bb-bda6-432c-a7f7-e5cbb0e44cc3)

**Comment by FCRodriguez7** [comment]
We were able to implement the highlighting for resource type and identifier shelfmark.  

![Screen Shot 2020-08-04 at 2.59.33 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2292095b-d115-469d-af93-183fd8071308)

**Comment by FCRodriguez7** [comment]
The PR:  https://github.com/yalelibrary/yul-dc-blacklight.git
