### ISSUE TITLE
Highlighting: Implement highlighting on Titles in results

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#338]
**STORY**
The current [Beinecke site](https://brbl-dl.library.yale.edu/vufind/Search/Results?lookfor=baldwin&type=AllFields&submit=Find&limit=16&sort=relevance) site provide match highlighting.  

Decide which fields highlighting should be implemented and add that functionality.

**ACCEPTANCE**
- [x] Implement highlighting on Titles in the results page

**Comment by edejesusyale** [comment]
After spending time working on the ticket, heres what I have learned.

1. Heading can be changed for records by using a different index_presenter in the catalog controller.
2. Solr responses return highlighting
3. Blacklight might be manipulating solr responses and hiding the highlighting in the response or is doing another query behind the scenes to get which terms are being highlighted.

**Comment by FCRodriguez7** [comment]
We were able to implement the highlighting for the title feild. 

![Screen Shot 2020-08-04 at 3.09.33 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/329bbaa1-a2db-4b27-badc-6ad58b0cf458)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-08-04 at 10.52.31 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4741b8f5-97ad-4a48-999b-af5845ac7e9a)

**Comment by FCRodriguez7** [comment]
The pr for this ticket: https://github.com/yalelibrary/yul-dc-blacklight/pull/218
