### ISSUE TITLE
Auto-tagging of docker image broken for management & discovery app

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#339]
Following the release instructions for the management app on July 13 led to this error. It appears either the instructions are incorrect or the auto-tagging feature is broken. 

On further investigation it appears that this is a race condition caused by the master branch not having completed its CI build before the tagging process started.

- [ ] Spend two hours investigating whether we can make the CI tagging process wait until the master branch has finished building
- [ ] IFF it's not possible to automate this wait time in CI, add to step 6 of the README release instructions: "Be sure to wait until the CI process for the master branch is complete before tagging the new release." 

![Screen Shot 2020-07-13 at 10.18.33 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/ecadd153-fee7-48f0-a97d-4186a1a4dceb)

**Comment by bess** [comment]
On further investigation it appears that this is a race condition caused by the `master` branch not having completed its CI build before the tagging process started. 

- [ ] Spend two hours investigating whether we can make the CI tagging process wait until the `master` branch has finished building

**Comment by orangewolf** [comment]
@bess this is the second time this has come up. I believe it got lost for not having a ticket last time, so I'm glad to see this.

**Comment by FCRodriguez7** [comment]
Its also occurring on the discovery application.
