### ISSUE TITLE
Update Yale Logo Text

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#340]
# Story
We are updating the blacklight app to match the branding outlined by Matthew Walker.

# Current
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/713ccc66-a8af-45fc-ad8c-575230c68933)

# Expected
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/fc1eb731-03e9-434a-99a4-aaf38271c310)

# Acceptance
- [x] The logo wording is updated
- [x] The typeface is updated
- [x] The spacing and positioning is updated

# Resources
Please refer to the [zeplin board](https://app.zeplin.io/project/5ec4c1c017d48d49285f8565/screen/5ec4c1fb026c9a30e1bb2062). Click on the portion of the design that you're editing to see the applicable assets and styles.

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-21 at 10.26.22 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ca1db798-85f9-403c-9d15-2c669113044f)

**Comment by FCRodriguez7** [comment]
Images missing from git repo.

**Comment by FCRodriguez7** [comment]
Recompression of logo images
