### ISSUE TITLE
Add the Places to Study nav bar link

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#341]
# Story
We are updating the blacklight app to match the branding outlined by Matthew Walker.

# Current
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/5dffd530-e34d-4d75-af21-cbb36f5dbda1)

# Expected
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/831e8cc4-00c3-4752-a066-41712a3d6e62)

# Acceptance
- [ ] "Places to Study" links out to https://web.library.yale.edu/places/to-study
- [ ] The spacing and positioning is updated

# Resources
Please refer to the [zeplin board](https://app.zeplin.io/project/5ec4c1c017d48d49285f8565/screen/5ec4c1fb026c9a30e1bb2062). Click on the portion of the design that you're editing to see the applicable assets and styles.

**Comment by FCRodriguez7** [comment]
We made progress on the navbar: 

![Screen Shot 2020-07-17 at 11.36.50 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/04ce5f9e-f2d2-4b68-bf08-ee065e070cec)

The next steps:
-  write more test
- switch the user name and logout text from right to left respectively
- change the word phase of logoff and login to Sign in and Sign out

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-17 at 2.28.57 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8393ff78-ebcc-45c9-9d82-515aef39f3ee)
