### ISSUE TITLE
Remove unused links from the nav bar

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#342]
# Story
We are updating the blacklight app to match the branding outlined by Matthew Walker.

# Current
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/5dffd530-e34d-4d75-af21-cbb36f5dbda1)

# Acceptance
- [x] Remove the "Bookmarks" link
- [x] Remove the "History" link

# Resources
Please refer to the [zeplin board](https://app.zeplin.io/project/5ec4c1c017d48d49285f8565/screen/5ec4c1fb026c9a30e1bb2062).

**Comment by FCRodriguez7** [comment]
**Updated Nav Bar**

![Screen Shot 2020-07-15 at 9.47.36 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/74111c49-65ab-4349-bf04-1ebd272ca6f4)

--------
![Screen Shot 2020-07-15 at 9.47.53 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b15b05c0-6d54-4622-b10c-98e2ce950693)
