### ISSUE TITLE
Update the Sign Out link

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#345]
# Story
We are updating the blacklight app to match the branding outlined by Matthew Walker.

# Current
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/5dffd530-e34d-4d75-af21-cbb36f5dbda1)

# Expected
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/831e8cc4-00c3-4752-a066-41712a3d6e62)

# Acceptance
- [x] The spacing and positioning is updated
- [x] The "Sign Out" button signs a user out
- [x] The current user's username shows to the left of the "Sign Out" button (the design shows a username and not an email. Does that mean that the "@yale.edu" portion of the email should be removed? Or do we want the entire email?)v - *MHB Note: I think this behavior changes when we login via CAS instead of database*

# Resources
Please refer to the [zeplin board](https://app.zeplin.io/project/5ec4c1c017d48d49285f8565/screen/5ec4c1fb026c9a30e1bb2062). Click on the portion of the design that you're editing to see the applicable assets and styles.

**Comment by mark-dce** [comment]
Let's revisit this ticket after #330 _Remove database authentication_  is complete.  I think this may not be needed after that.

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-17 at 2.28.57 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/55d8f876-774b-4ecb-92a9-400dc9aadf3c)
