### ISSUE TITLE
Add an Information & Policies nav bar dropdown

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#349]
# Story
We are updating the blacklight app to match the branding outlined by Matthew Walker.

# Expected
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/37cd65ba-b76a-4567-9246-56814f1084aa)

# Acceptance
- [ ] Update the secondary nav bar with an "Information & Policies" drop down link (should the dropdown include the links from https://web.library.yale.edu/?)

# Resources
Please refer to the [zeplin board](https://app.zeplin.io/project/5ec4c1c017d48d49285f8565/screen/5ec4c1fb026c9a30e1bb2062). Click on the portion of the design that you're editing to see the applicable assets and styles.

**Comment by mark-dce** [comment]
Superseded by #371 which generates the associated menus from a config file.
