### ISSUE TITLE
Add Yale University Library Footer

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#353]
# Acceptance Criteria
- [x] Blacklight app contains a Yale University Library footer on each page

## Links to Include
- [x] Research
- [x] Services
- [x] Libraries & Collections
- [x] Information & Policies

## Logo to Include
- [x] Yale University Library (text) logo

## Social Icons to Include
- [x] Yale University Library Twitter
- [x] Yale University Library Facebook
- [x] Yale University Library Instagram
- [x] Yale University Library E-Mail

# Wireframe Desktop
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/49d7e386-0d99-4955-a158-34ed7158fae5)

# Style Reference
https://yaleidentity.yale.edu/web

**Comment by FCRodriguez7** [comment]
Yale University Library (text)Logo 

Per discussion with Matt, he would like a logo and not text. 

![Screen Shot 2020-07-21 at 12.28.40 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5cc87ee8-6e67-466c-8cdf-83322137fed0)

**Comment by FCRodriguez7** [comment]
Make SHA text smaller and appear on the footer again.

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-22 at 9.44.46 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5226fc9d-6d77-460a-9c69-34b401c02e70)

**Comment by FCRodriguez7** [comment]
Fixing RSpec issue with feedback url.

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/new/AddYULFooter353

**Comment by FCRodriguez7** [comment]
RSpec not passing due to search relevance

**Comment by FCRodriguez7** [comment]
I fixed the error with this PR:https://github.com/yalelibrary/yul-dc-blacklight/pull/195/commits.
