### ISSUE TITLE
Consistent Honeybadger Key Configuration

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#354]
**ISSUE**
@JzGo came up with a way to set the HoneyBadger API Key that makes it clearer and easier to verify that the right key is being passed to the right container than our previous solution.  For consistency we should use the same solution in all containers.

See https://github.com/yalelibrary/yul-dc-iiif-imageserver/blob/539ebf485fe588828f7c8197ea5f54b478c68c14/delegates.rb#L4-L6

**DEV HINTS**
Consider putting the same type of key config somewhere like [production.rb](https://github.com/yalelibrary/yul-dc-management/blob/master/config/environments/production.rb) *OR* commit a `config/honeybadger.yml` with ERB like the following:
```
---
api_key: "<%= ENV['HONEYBADGER_API_KEY_BLACKLIGHT'] %>"
```

**DOCS**
https://docs.honeybadger.io/lib/ruby/gem-reference/configuration.html

**ACCEPTANCE**
- [x] Embed the Honeybadger API keys in the camerata docker-compose.ecs.yml file (as temporary scaffolding)
- [x] Update yul-dc-camerata to pass both old and new ways (e.g. as HONEYBADGER_API_KEY and as HONEYBADGER_API_KEY_BLACKLIGHT) *NOTE: this allows backward compatibility so we don't have to worry about synchronizing releases of the blacklight and management apps*
- [x] yul-dc-management configures the key in the same way in [production.rb](https://github.com/yalelibrary/yul-dc-management/blob/master/config/environments/production.rb) or a similar config file
- [x] yul-dc-blacklight configures the key in the same way in [production.rb]() or a similar config file

See #355 for final step to remove older mechanism for passing keys

**Comment by fnibbit** [comment]
https://collections-test.curationexperts.com/catalog/nonsense  ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/11c0c7fa-9147-42bc-b1d7-afdc94eda2ee)  Temporary scaffolding in place

**Comment by JzGo** [comment]
A possible intermediate commit for blacklight dependencies: 

https://github.com/yalelibrary/yul-dc-blacklight/pull/175

There's a description in the ticket for ^ but essentially spinning things up resulted in gemfile.lock updates that didn't make it in to the blacklight app.

honeybadger.yml commit for blacklight: https://github.com/yalelibrary/yul-dc-blacklight/pull/174

honeybadger.yml commit for management: https://github.com/yalelibrary/yul-dc-management/pull/149

**Comment by mark-dce** [comment]
I'm seeing errors for blacklight, but not management.
