### ISSUE TITLE
Manage HoneyBadger API Keys using Amazon System Manager Parameter Store 

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#355]
**STORY**
As a engineering and ops team members, we'd like a simpler means to manage keys than having to pass them around for everyone to store in local secrets files, and a more secure means than committing them to our code repos, so that we have a consistent and reliable way to inject environment configuration into ECS clusters.

**DEV HINTS**
See here for a potential recipe for accessing Paramter Store key-value pairs in ECS clusters:  
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html

Also see "Services / Secrets" in this example params file:  
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html

**ACCEPTANCE**
- [ ] Configure HoneyBadger API Keys in the Parameter Store
   - [ ] HONEYBADGER_API_KEY_BLACKLIGHT
   - [ ] HONEYBADGER_API_KEY_MANAGEMENT
   - [ ] HONEYBADGER_API_KEY_IMAGESERVER
- [ ]  Configure `yul-dc-blacklight` to read it's Honeybadger API key from the Parameter Store
- [ ]  Configure `yul-dc-management` to read it's Honeybadger API key from the Parameter Store
- [ ]  Configure `yul-dc-iiif-imageserve` to read it's Honeybadger API key from the Parameter Store
- [ ] Remove any keys directly specified in the `yul-dc-camerata` compose file (see #354)

Once the above steps are working, 
- [ ] Reset the API keys to new values that have never been checked into GitHub - e.g. https://app.honeybadger.io/projects/72587/tokens
- [ ] Save the new keys to the Parameter Store
- [ ] Redeploy to current clusters (probably yul-test & yul-demo) to activate new keys

**Comment by dl-maura** [comment]
Rob, is this all done? Can we close this?

**Comment by orangewolf** [comment]
yes
