### ISSUE TITLE
Strategy for missing access masters (~40K)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#361]
**ISSUE**
We need an agreed on strategy to handle access masters recorded in LadyBird that do not have corresponding digital files that we can locate.  At present we estimate there are approximately 40K missing files (out of over 1.1M total image files)

**ACCEPTANCE**
- [x] We have an agreed on strategy for works with no locatable digital files (i.e. no children exist)
- [x] We have an agreed on strategy for works with some missing files (i.e. some, but not all expected child files exist)
- [x] Appropriate tickets have been created to reflect any remediation work

**Comment by dl-maura** [comment]
Jay found all but 376 on RackSpace programmatically and is working on transferring and converting them. I'm spot checking some of the 376 since a few do seem to be in the DL, and we may have uncrossed masters for them.

**Comment by dl-maura** [comment]
Proposed Course of Action:
 - Copy and Convert programmatically located items
 - For not located:
   - Confirm not on RackSpace under a different OID (LB cross-reference?)
   - If not on RackSpace, check for uncropped masters which can be cropped
   - For anything left, compile a report and determine if it should be reshot

**Comment by kcompsci** [comment]
Just did a query and there are some objects that have been resolved per Martins last script. Currently running the image copy for 34657 new objects staged for copy. As of writing this update there are 1109298 images that have been copied.

**Comment by dl-maura** [comment]
Ticket 411 is for work to remediate
