### ISSUE TITLE
Create PTIFF from an Access Master

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#365]
**ACCETPANCE**
Given
- A pointer to an image file 
- A checksum for the file

Do the following
- [x] Validate the checksum - return and log an error if it doesn't match
- [x] Create a PTIFF corresponding to the file - return and log an error if the conversion fails for any reason
- [x] Store the PTIFF in an S3 bucket & return the link to the new PTIFF

**SAMPLE DATA**
https://drive.google.com/drive/folders/10Gk7DfEqbu40uENCFnwg9go_JKJtu1Qq?usp=sharing

**DEV HINTS**
There is a shell script that lays out the necessary steps at https://github.com/yalelibrary/yul-dc-ptiff-shell-script

**Comment by dl-maura** [comment]
Use the NGA way

**Comment by dl-maura** [comment]
PR just passed CI
