### ISSUE TITLE
Create all PTIFFs for all children of a given parent

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#366]
Extends work from #364

**ACEPTANCE**
Given a valid oid for a Parent Record
- [x] Find the access master for each associated child
- [x] Generate a PTIFF from the corresponding access master (by calling the process from #365)
- [x] Save the PTIFF to S3
- [x] Log any errors

**SAMPLE DATA**
https://drive.google.com/drive/folders/10Gk7DfEqbu40uENCFnwg9go_JKJtu1Qq?usp=sharing

**Comment by mark-dce** [comment]
Discussed with @mlooney the possibility of implementing this using AWS Lambda:
1) Copy the access master to the appropriate bucket on S3 (since we want them there for download)
2) Lambda receives notification and creates corresponding PTIFF 

Conversion steps are documented in the script here: https://github.com/yalelibrary/yul-dc-ptiff-shell-script
Google AWS Vips lambda for numerous how-to's

Tangentially related and also possibly of interest https://github.com/nulib/node-iiif & https://github.com/nulib/serverless-iiif

**Comment by mikeapp** [comment]
I have a few concerns:
* This use of Lambda for a single task will be a one-off, so there'll be some additional overhead in maintaining it and troubleshooting any issues.  Would it be kinder to our future selves to stick with something like Docker+autoscaling?
* There's currently a 3GB memory limit on a Lambda process. We should test carefully to be sure that large images don't hit this constraint.  High-end cameras can produce multi-GB images today, and we have use cases for stitching images of large objects (e.g., maps) that can produce a single large source image.   (The largest image I can find in BRBL is 2.7GB.).  With EC2 we'd be able to increase the memory/CPU if needed.
