### ISSUE TITLE
Create a manifest from a METS file

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#367]
Extends #364

**ACCEPTANCE**
Given a valid METS file
- [x] Create a IIIF Manifest reflecting the page and image structure
- [x] Save the manifest to S3 
- [ ] ~[BONUS] write the image count to the Parent Object model~ (will be pulled out into another ticket)

**SAMPLE DATA**
https://drive.google.com/drive/folders/10Gk7DfEqbu40uENCFnwg9go_JKJtu1Qq?usp=sharing

**Comment by maxkadel** [comment]
Downloaded a manifest validator and started up a vanilla ruby server from the fixture/manifests directory and validated that the structure is valid.

![image](https://user-images.githubusercontent.com/45948126/89941447-08d10380-dbe9-11ea-93f6-f29e90b82762.png)
