### ISSUE TITLE
Prepare Circle CI Teachout

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#370]
**ISSUE**
We'd like a walkthrough of CircleCI, esepecially in relation to how we're using it for 
* Running a CI test suite
* Building docker images and pushing them to DockerHub
* Tagging DockerHub images for the corresponding GitHub release

**ACCEPTANCE**
- [x] Prepare a teach-out
- [x] Present to the team (& record)

**Comment by dl-maura** [comment]
Early August?

**Comment by dl-maura** [comment]
Scheduled for 8/26
