### ISSUE TITLE
Add library sub-menu links to header

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#371]
**STORY**
As a repository owner, I'd like an easy way to configure navigation menus to other library resources in a way that lets me update them without significant code modifications.

**ACCEPTANCE**
- [x] There is a YAML file that can be edited and committed to the repository that defines the menu headings and entries (see initial sample below)
- [x] When the application loads, it builds the corresponding navigation menus for the header
- [x] Titles should appear as hover-text when they exist

**OUT OF SCOPE**
Building or automating the code to create the YAML file for the menus (but a sample code snippet is included below for reference in a future ticket if desired)

**TOP LEVEL DROP-DOWNS**
<img width="849" alt="image" src="https://user-images.githubusercontent.com/3064318/87567468-edc2b080-c689-11ea-991f-391ce35ae5c7.png">

**EXPANDED DROP-DOWN**
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3064318/87567685-35493c80-c68a-11ea-9168-fa43741ed7c1.png">

**TITLE as HOVER-TEXT**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3064318/87569794-45aee680-c68d-11ea-8e38-64b3bb710205.png">

**SAMPLE YAML**
```
---
---
- Research:
  - Quicksearch:
      url: http://search.library.yale.edu
      title: 
  - Search Library Catalog (Orbis):
      url: http://orbis.library.yale.edu/vwebv/
      title: Records for approximately 13 million volumes located across the University
        Library system.
  - Search Law Library Catalog (MORRIS):
      url: http://morris.law.yale.edu/
      title: Records for items located in Yale's Lillian Goldman Law Library. The
        extensive law collection is not represented in Orbis.
  - Search Borrow Direct:
      url: https://resources.library.yale.edu/cas/borrowdirect.aspx
      title: Borrow Direct is a service that allows Yale patrons to check the availability
        of and request books from the combined catalogs of Harvard, Princeton, Dartmouth,
        Cornell, Columbia, Penn, Brown, University of Chicago, and MIT within four
        business days. It can be used to obtain items that are currently unavailable
        for checkout at Yale, not held by the Yale library, or on course reserve.
  - Search WorldCat:
      url: http://firstsearch.oclc.org/dbname=WorldCat;autho=100157622;FSIP
      title: Includes more than 50 million records of books and other materials held
        in thousands of academic, public, special and national libraries around the
        world.
  - Search Articles+:
      url: http://yale.summon.serialssolutions.com/
      title: Search Articles+ provides a fast way to search across the fulltext of
        articles from thousands of published journals.
  - Search Digital Collections:
      url: http://web.library.yale.edu/digital-collections
      title: Access to digital image and text collections available from the Yale
        University Library.
  - Search Archives at Yale:
      url: http://archives.yale.edu
      title: Finding aids describe archival and manuscript collections at Arts, Beinecke,
        Divinity, and Music libraries, and the Manuscripts and Archives department
        in Sterling.
  - Research Guides:
      url: http://guides.library.yale.edu/
      title: Use these subject guides to get started in your research, formulate a
        research strategy for a topic, and find information about print and electronic
        resources.
  - Find Databases by Title:
      url: http://search.library.yale.edu/databases
      title: 'Find subject-specific databases by title. Direct links to subscribed
        and freely available research databases and other resources, such as encyclopedias,
        bibliographies and dictionaries. Some databases are also "cross-searchable";
        that is, they may be searched at one time in combination with other databases '
  - Find eJournals by Title:
      url: http://wa4py6yj8t.search.serialssolutions.com
      title: Browse or search for the titles of online journals and newspapers to
        which the library subscribes or has access to free on the Web.
  - Guide to Using Special Collections:
      url: http://guides.library.yale.edu/specialcollections
      title: 
- Services:
  - Your Personal Librarian:
      url: https://library.yale.edu/pl
      title: 
  - Subject Specialists:
      url: https://library.yale.edu/subject-specialists
      title: 
  - Research Support and Workshops:
      url: http://guides.library.yale.edu/research-help
      title: 
  - Citation Tools:
      url: http://guides.library.yale.edu/citationmanagement
      title: Create Bibliographies
  - Get It @Yale (Borrow Direct, Interlibrary Loan, Scan & Deliver):
      url: http://guides.library.yale.edu/getit
      title: ''
  - Course Reserves:
      url: http://guides.library.yale.edu/reserves
      title: 
  - Off-Campus Access:
      url: https://library.yale.edu/help/off-campus-access-vpn
      title: Connect your computer to the Yale VPN (network) while off-campus.
  - EliScholar:
      url: http://elischolar.library.yale.edu
      title: A digital repository of scholarly publications at Yale
  - 'OverDrive: Popular Audio and eBooks':
      url: http://yale.lib.overdrive.com/
      title: 'OverDrive is a distribution platform through which users of our library
        can download popular eBooks and audiobooks.  From our personalized Yale University
        OverDrive site, we offer access to a variety of fiction and non-fiction titles
        in many different formats. '
  - Bass Media Equipment:
      url: https://reservations.yale.edu/bmec/
      title: 
- Libraries & Collections:
  - Arts Library:
      url: https://library.yale.edu/building/arts-library
      title: Robert B. Haas Family Arts Library
  - Bass Library:
      url: https://library.yale.edu/building/bass-library
      title: Anne T. and Robert M. Bass Library
  - Beinecke Library:
      url: https://library.yale.edu/building/beinecke-library
      title: Beinecke Rare Book & Manuscript Library
  - Classics Library:
      url: https://library.yale.edu/building/classics-library
      title: 
  - Divinity Library:
      url: https://library.yale.edu/building/divinity-library
      title: Divinity School Library
  - Film Study Center:
      url: https://library.yale.edu/film
      title: 
  - Fortunoff Archive:
      url: http://www.library.yale.edu/testimonies/
      title: Fortunoff Video Archive for Holocaust Testimonies
  - Humanities Collections:
      url: https://library.yale.edu/humanities
      title: 
  - International Collections:
      url: https://library.yale.edu/international-collections
      title: 
  - Law Library:
      url: https://library.yale.edu/building/law-library
      title: Lillian Goldman Law Library in Memory of Sol Goldman
  - Lewis Walpole Library:
      url: https://library.yale.edu/building/lewis-walpole-library
      title: 
  - Library Collection Services:
      url: https://library.yale.edu/departments/lcs
      title: 
  - Manuscripts & Archives:
      url: https://library.yale.edu/mssa
      title: 
  - Map Collection:
      url: http://www.library.yale.edu/maps
      title: 
  - Marx Science & Social Science Library:
      url: https://library.yale.edu/building/marx-science-and-social-science-library
      title: 
  - Mathematics Library:
      url: https://library.yale.edu/building/math-library
      title: 
  - Medical Library:
      url: https://library.yale.edu/building/medical-library
      title: Harvey Cushing / John Hay Whitney Medical Library
  - Music Library:
      url: https://library.yale.edu/music
      title: Irving S. Gilmore Music Library
  - Sterling Library:
      url: https://library.yale.edu/building/sterling-library
      title: Sterling Memorial Library
  - Yale Center for British Art:
      url: https://library.yale.edu/building/yale-center-for-british-art
      title: 
- Information & Policies:
  - Library Hours:
      url: https://library.yale.edu/buildings
      title: ''
  - Departments & Staff:
      url: https://library.yale.edu/sd
      title: 
  - Borrowing & Circulation:
      url: http://guides.library.yale.edu/borrow
      title: Information about accessing and borrowing print material
  - Services for Persons with Disabilities:
      url: https://library.yale.edu/services-persons-disabilities
      title: 
  - Copyright Basics:
      url: http://guides.library.yale.edu/copyright-guidance/copyright-basics
      title: 
  - Scanning, Printing & Copying:
      url: https://library.yale.edu/help/scanning-printing-copying
      title: 
  - Computers & Wireless:
      url: https://library.yale.edu/help/computers-and-wireless
      title: 
  - Library Policies:
      url: http://guides.library.yale.edu/about/policies
      title: 
  - About the Library:
      url: http://guides.library.yale.edu/about
      title: 
  - Giving to the Library:
      url: https://library.yale.edu/development
      title: 
  - Purchase Request:
      url: https://library.yale.edu/form/purchase-request
      title: 
  - Working at the Library:
      url: http://guides.library.yale.edu/work
      title: 
  - Terms Governing Use of Materials:
      url: https://guides.library.yale.edu/about/policies/access
      title: 
```

**SCRAPING THE MENU FROM THE LIBRARY HOMEPAGE**
Generates the sample YAML above - note that relative paths on the library site need to have "https://library.yale.edu" prefix added for the links to work across sites.
```
require 'open-uri'
require 'nokogiri'

# Read the library homepage
doc = Nokogiri::HTML(open('https://web.library.yale.edu'))

# Extract the menu structures
menus = doc.at_css('#region-menu').css('.block-menu-block').collect{|menu| {menu.at_css('.block-title').text => menu.css('.leaf').collect{|leaf| { leaf.text =>{"url" => leaf.at_css('a')['href'], "title" => leaf.at_css('a')['title'] } } } } }

# Add the full path for relative links
menus.each {|group| group.values.first.each {|leaf| leaf.values.first['url'] = 'https://library.yale.edu' + leaf.values.first['url'] if leaf.values.first['url'][0] == "/" } }

# Convert it to YAML
puts menus.to_yaml
```

**Comment by orangewolf** [comment]
Updated simplified yaml

`---
Research:
  Quicksearch:
    url: http://search.library.yale.edu
    title:
  Search Library Catalog (Orbis):
    url: http://orbis.library.yale.edu/vwebv/
    title: Records for approximately 13 million volumes located across the University
      Library system.
  Search Law Library Catalog (MORRIS):
    url: http://morris.law.yale.edu/
    title: Records for items located in Yale's Lillian Goldman Law Library. The
      extensive law collection is not represented in Orbis.
  Search Borrow Direct:
    url: https://resources.library.yale.edu/cas/borrowdirect.aspx
    title: Borrow Direct is a service that allows Yale patrons to check the availability
      of and request books from the combined catalogs of Harvard, Princeton, Dartmouth,
      Cornell, Columbia, Penn, Brown, University of Chicago, and MIT within four
      business days. It can be used to obtain items that are currently unavailable
      for checkout at Yale, not held by the Yale library, or on course reserve.
  Search WorldCat:
    url: http://firstsearch.oclc.org/dbname=WorldCat;autho=100157622;FSIP
    title: Includes more than 50 million records of books and other materials held
      in thousands of academic, public, special and national libraries around the
      world.
  Search Articles+:
    url: http://yale.summon.serialssolutions.com/
    title: Search Articles+ provides a fast way to search across the fulltext of
      articles from thousands of published journals.
  Search Digital Collections:
    url: http://web.library.yale.edu/digital-collections
    title: Access to digital image and text collections available from the Yale
      University Library.
  Search Archives at Yale:
    url: http://archives.yale.edu
    title: Finding aids describe archival and manuscript collections at Arts, Beinecke,
      Divinity, and Music libraries, and the Manuscripts and Archives department
      in Sterling.
  Research Guides:
    url: http://guides.library.yale.edu/
    title: Use these subject guides to get started in your research, formulate a
      research strategy for a topic, and find information about print and electronic
      resources.
  Find Databases by Title:
    url: http://search.library.yale.edu/databases
    title: 'Find subject-specific databases by title. Direct links to subscribed
      and freely available research databases and other resources, such as encyclopedias,
      bibliographies and dictionaries. Some databases are also "cross-searchable";
      that is, they may be searched at one time in combination with other databases '
  Find eJournals by Title:
    url: http://wa4py6yj8t.search.serialssolutions.com
    title: Browse or search for the titles of online journals and newspapers to
      which the library subscribes or has access to free on the Web.
  Guide to Using Special Collections:
    url: http://guides.library.yale.edu/specialcollections
    title:
Services:
  Your Personal Librarian:
    url: https://library.yale.edu/pl
    title:
  Subject Specialists:
    url: https://library.yale.edu/subject-specialists
    title:
  Research Support and Workshops:
    url: http://guides.library.yale.edu/research-help
    title:
  Citation Tools:
    url: http://guides.library.yale.edu/citationmanagement
    title: Create Bibliographies
  Get It @Yale (Borrow Direct, Interlibrary Loan, Scan & Deliver):
    url: http://guides.library.yale.edu/getit
    title: ''
  Course Reserves:
    url: http://guides.library.yale.edu/reserves
    title:
  Off-Campus Access:
    url: https://library.yale.edu/help/off-campus-access-vpn
    title: Connect your computer to the Yale VPN (network) while off-campus.
  EliScholar:
    url: http://elischolar.library.yale.edu
    title: A digital repository of scholarly publications at Yale
  'OverDrive: Popular Audio and eBooks':
    url: http://yale.lib.overdrive.com/
    title: 'OverDrive is a distribution platform through which users of our library
      can download popular eBooks and audiobooks.  From our personalized Yale University
      OverDrive site, we offer access to a variety of fiction and non-fiction titles
      in many different formats. '
  Bass Media Equipment:
    url: https://reservations.yale.edu/bmec/
    title:
Libraries & Collections:
  Arts Library:
    url: https://library.yale.edu/building/arts-library
    title: Robert B. Haas Family Arts Library
  Bass Library:
    url: https://library.yale.edu/building/bass-library
    title: Anne T. and Robert M. Bass Library
  Beinecke Library:
    url: https://library.yale.edu/building/beinecke-library
    title: Beinecke Rare Book & Manuscript Library
  Classics Library:
    url: https://library.yale.edu/building/classics-library
    title:
  Divinity Library:
    url: https://library.yale.edu/building/divinity-library
    title: Divinity School Library
  Film Study Center:
    url: https://library.yale.edu/film
    title:
  Fortunoff Archive:
    url: http://www.library.yale.edu/testimonies/
    title: Fortunoff Video Archive for Holocaust Testimonies
  Humanities Collections:
    url: https://library.yale.edu/humanities
    title:
  International Collections:
    url: https://library.yale.edu/international-collections
    title:
  Law Library:
    url: https://library.yale.edu/building/law-library
    title: Lillian Goldman Law Library in Memory of Sol Goldman
  Lewis Walpole Library:
    url: https://library.yale.edu/building/lewis-walpole-library
    title:
  Library Collection Services:
    url: https://library.yale.edu/departments/lcs
    title:
  Manuscripts & Archives:
    url: https://library.yale.edu/mssa
    title:
  Map Collection:
    url: http://www.library.yale.edu/maps
    title:
  Marx Science & Social Science Library:
    url: https://library.yale.edu/building/marx-science-and-social-science-library
    title:
  Mathematics Library:
    url: https://library.yale.edu/building/math-library
    title:
  Medical Library:
    url: https://library.yale.edu/building/medical-library
    title: Harvey Cushing / John Hay Whitney Medical Library
  Music Library:
    url: https://library.yale.edu/music
    title: Irving S. Gilmore Music Library
  Sterling Library:
    url: https://library.yale.edu/building/sterling-library
    title: Sterling Memorial Library
  Yale Center for British Art:
    url: https://library.yale.edu/building/yale-center-for-british-art
    title:
Information & Policies:
  Library Hours:
    url: https://library.yale.edu/buildings
    title: ''
  Departments & Staff:
    url: https://library.yale.edu/sd
    title:
  Borrowing & Circulation:
    url: http://guides.library.yale.edu/borrow
    title: Information about accessing and borrowing print material
  Services for Persons with Disabilities:
    url: https://library.yale.edu/services-persons-disabilities
    title:
  Copyright Basics:
    url: http://guides.library.yale.edu/copyright-guidance/copyright-basics
    title:
  Scanning, Printing & Copying:
    url: https://library.yale.edu/help/scanning-printing-copying
    title:
  Computers & Wireless:
    url: https://library.yale.edu/help/computers-and-wireless
    title:
  Library Policies:
    url: http://guides.library.yale.edu/about/policies
    title:
  About the Library:
    url: http://guides.library.yale.edu/about
    title:
  Giving to the Library:
    url: https://library.yale.edu/development
    title:
  Purchase Request:
    url: https://library.yale.edu/form/purchase-request
    title:
  Working at the Library:
    url: http://guides.library.yale.edu/work
    title:
  Terms Governing Use of Materials:
    url: https://guides.library.yale.edu/about/policies/access
    title:
`

Some code snippets from our strategy session

loading yaml
`
menu = YAML.load_file(Rails.root.join('config', 'menu.yml'))
`

**Comment by FCRodriguez7** [comment]
The page styling is similar (https://web.library.yale.edu)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-24 at 3.26.22 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/855727ae-849e-40db-8544-5a34bfee0164)

**Comment by FCRodriguez7** [comment]
I have added the YAML file. 

![Screen Shot 2020-07-27 at 12.50.13 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1a57d2b6-7f21-47ac-be0c-8dbbaf2e477e)

**Comment by FCRodriguez7** [comment]
**HEADER**
![Screen Shot 2020-07-28 at 1.12.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/35543286-7c17-4c4a-90fd-d929efa78066)


**FOOTER**
![Screen Shot 2020-07-28 at 1.12.17 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9d894fb4-f0a4-4f21-ba99-ae022853d071)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-31 at 12.21.20 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/600e2550-ff40-4061-9486-4ee1beed3ebb)

![Screen Shot 2020-07-31 at 12.21.20 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6003f41f-7636-45df-af63-c37aff94801a)

-----

We are going to do more investigation about js code patterns for the header.

**Comment by alishaevn** [comment]
Co-authored by: Alisha Evans <alisha@notch8.com>

# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/201

# Summary
- [x] There is a YAML file that can be edited and committed to the repository that defines the menu headings and entries (see initial sample below)
- [x] When the application loads, it builds the corresponding navigation menus for the header
- [x] Titles should appear as hover-text when they exist

# Demo
![371](https://user-images.githubusercontent.com/29032869/89237518-3e9e3880-d5a8-11ea-9d4e-a7e12b068859.gif)
