### ISSUE TITLE
Determine cause of and remedy Dependabot tag error

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#372]
# Summary
Automated GitHub Dependabot pull request is failing CI.  For what seems to be an issue with the automated way the repo is referenced but further investigation is needed to determine the exact cause of the CI failure and remedy the issue.

# Acceptance Criteria
- [ ] Automated Dependabot security update PRs pass CI checks 

# Screenshot of Error 
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/81f7233c-cc87-47ad-b5a5-08413c9e3978)

# Links
* [Dependabot PR](https://github.com/yalelibrary/yul-dc-blacklight/pull/176)
* [CI Build Details](https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-blacklight/645/workflows/1a7ad930-9dee-423b-81bc-32f6c1034904/jobs/1302/steps)

**Comment by fnibbit** [comment]
More specific diagnosis, not yet a fix: https://docs.docker.com/engine/reference/commandline/tag/ "A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters."  The autotagging uses the branch name, un-altered, as the tag; these dependabot-created branches have slashes in their names, which are not allowed in docker tag names.

**Comment by bess** [comment]
It looks like our tests are passing, the only part of CI that's failing is the build and push of the docker image. Since we don't actually need the docker image for this branch, I have merged this PR and I think we don't need to spend more time on this.

**Comment by fnibbit** [comment]
I'm neck deep in autotagging right now anyway, and this affects all of our repos that use the autotagging each time a dependabot PR comes out.  It's going to be easier to fix now than to go "why'd that fail CI?  Oh, it's only sorta-failing CI, we can merge it anyway" a bunch more times.
