### ISSUE TITLE
Prevent element overlap

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#377]
# Summary
Currently there is an overlap of the tools section over the UV.  

# Acceptance Criteria
- [ ] Regardless of screen size, elements do not overlap
**NOTE:** for now, do the minimum effort to undo the overlap, since we think Matt Walker may have bigger changes proposed in the single item wireframes.

# Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/1e49c0e3-2e6c-4430-98ec-629f9ae7d8fc)

**Comment by mark-dce** [comment]
Hi Kate - I'm going to hold off on this one because I think we may want to redesign the single item view in a way that handles the tools differently and in a different location on the page.

**Comment by DraxIndustries79** [comment]
Duplicates #427
