### ISSUE TITLE
Add an environment (env) command to Camerata

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#379]
## Description
Add an environment (env) command to Camerata with the following subcommands:
  env copy FROM TO
  env set KEY VALUE --secret
  env get KEY

## Acceptance
- copy should clone the entire set of keys from one environment to another namespace
- set key just sets an arbitrary key (wrapping ssm cli call)
- get retrieves an arbitrary key (wrapping ssm cli call)

**Comment by JzGo** [comment]
WIP PR up here: [#131](https://github.com/yalelibrary/yul-dc-camerata/pull/131)

Will continue to make progress tomorrow. I would like to reconnect with Rachel K at some point on getting the specs in place.

**Comment by JzGo** [comment]
Successfully used `cam env_copy "YUL_TEST"` to duplicate existing params to 'YUL_TEST' namespaced params.
 
![Screen Shot 2020-08-27 at 9.21.11 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/50a49011-91ac-4c16-83be-aaba116c80b3)

Added some pending specs while sussing details on how to test these with rspec.

**Comment by JzGo** [comment]
Updated PR with the changes requested by Rachel. `env_get` now indicates to user if the requested param doesn't exist and `env_copy` should now prefix param names correctly.
