### ISSUE TITLE
Make deployment scripts respect namespaced SSM variables

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#380]
## Description
Each deployed environment should have its own namespaced copy of the SSM versions and secrets. Update the camerata cli and bin scripts to support this.

## Acceptance 
Test and Demo should be able to be deployed with different versions of management / blacklight and with separate honeybadger keys should we want to. 

See ticket #505 for work that we want to have accomplished through this

**Comment by orangewolf** [comment]
unless Jez or Rachel have already decided how to do this, it may be worth while to talk to Rob before starting it (I have some ideas I'm having trouble articulating here)

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/1384ec26-b973-4d6a-a0e0-ab6c8a358164)

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/d5e49cbf-a896-476a-9bac-6af5488afbd9)

The parameters that begin with /yul-dc-test/ were set by a jenkins deploy to collections-test.library.yale.edu this morning with the UPDATE_SSM box checked.  From the date column, you can see that the default versions of those parameters were left unchanged -- BLACKLIGHT_VERSION, CAMERATA_VERSION, etc. were last updated yesterday.

**Comment by fnibbit** [comment]
Last piece of this that I know of: The change to the YUL-DC-TEST-DEPLOY job in jenkins looks good, we should bring that over to the next cluster up the hierarchy.

**Comment by fnibbit** [comment]
The people who have access to do the last step on this ticket, AFAIK: Rick and Keith.
