### ISSUE TITLE
Update names for image service GitHub & DockerHub

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#382]
**ACCEPTANCE**
- [ ] Update CI build scripts to build `dc-images` instead of `dc-iiif-cantaloupe`
- [ ] Github `dc-images` instead of `yul-dc-iiif-imageserver`
- [ ] Rename Docker service name `dc-images` instead of `iiif_image`
   - [ ] On local builds
   - [ ] When deploying to ECS

- yul-dc-management --> dc-management
- yul-dc-blacklight --> dc-discovery
- yul-dc-camerata --> dc-camerata
- yul-dc-solr --> dc-index
- yul-dc-postgres --> dc-db
- yul-dc-iiif-manifest --> dc-manifests

**Comment by mikeapp** [comment]
won't fix
