### ISSUE TITLE
Index the number of images associated with a work

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#383]
**STORY**
As a researcher, I would like search results to show me how many images are associated with each work, so that I don't have to click off the page to determine if I've found an image-rich resource or not.

**ACCEPTANCE**
- [x] a field is indexed that contains the count of images associated with a work
- [x] the field is sortable as an integer (note: the discovery app team has assumed the field is named `imageCount_isi`, please coordinate with the discovery team if we want to use a different field name)

**DEV HINT**
For the time being, we don't have a full model of the child images attached to the work, so just use the count of  canvases in the associated manifest; we'll be updating this function when we update the management application to create manifest (see #367 - Create a manifest from a METS file).

Given the OID for the work, you can use the following hash to get the image count (again, we'll be updating this very shortly with #367)
```
OID_TO_COUNT_MAPPING = {10001192=>2, 10269867=>8, 10958722=>185, 11607445=>85, 11684565=>398, 11913649=>40, 14716192=>178, 16057777=>18, 16057779=>4, 16057780=>17, 16156712=>144, 16162984=>6, 16173726=>13, 16189096=>2, 16189097=>2, 16371253=>6, 16371267=>6, 16371272=>464, 16414889=>28, 16425155=>10, 16570776=>1128, 16685691=>1, 16700283=>2, 16712419=>159, 16797069=>336, 16854285=>4, 16854582=>9, 2003431=>1366, 2005512=>2, 2012036=>5, 2012143=>4, 2012315=>10, 2019757=>451, 2019759=>292, 2030006=>1, 2041002=>1318, 2046567=>1188, 2055095=>841, 2107188=>2, 2111169=>315}
```
so you can make a call something like this
```
> OID_TO_COUNT_MAPPING[11684565]
=> 398
```

You'll need to enclose the OIDs in the hash in quotes if you want to pass strings instead of integers.

**Comment by martinlovell** [comment]
You can add a parameter to MC: include-children=1, to get the children populated.
e.g. https://metadata-api-test.library.yale.edu/metadatacloud/api/ladybird/oid/15761897?mediaType=json&include-children=1

Then get the count with something like: `data_hash["children"].count`

**Comment by mark-dce** [comment]
Looks great on ECS
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/3064318/89565308-fbc8a480-d7e3-11ea-8c11-1e1868200ab7.png">
