### ISSUE TITLE
Update fields displayed in search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#384]
**STORY**
As a repository owner, I'd like to display the fields that are most likely to help a researcher triage the list of results they've found, so that they can identify items worth clicking into.

**NOTE**
This work is in preparation for a follow-on ticket for the visual styling of search result items (partials).

**ACCEPTANCE**
Search results should display the following fields (when they have data):
- [x] Title
- [x] Creator
- [x] Date
- [x] Image Count (new field - need to agree on a name with the management team)
- [x] Resource type
- [x] Call Number
- [x] Part Of (i.e. the collection name a work belongs to)

- [x] remove any other fields (Extent of Digitization, Format, Language, Genre)
- [x] suppress an fields that don't have data

**ADDITIONAL DETAILS**
Details and examples for each field to show in search results: https://docs.google.com/document/d/1dxGoaNAZ8p9OhH2_0BlQqreHvAtL3jtjoOwXq48kEmg/edit#

**Comment by K8Sewell** [comment]
### Pre Removal of Fields:
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/1ceea16d-d1a0-406a-a8c5-3693f97753bf)

### Post Removal of Fields:
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/3ff9a2ff-a25e-4ee4-9d1a-201164a716a7)

**Comment by K8Sewell** [comment]
Date added but noting will need to do some normalization of the data based on this rendering.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d3ae48d2-32ec-4f14-a93d-32afad0c77ed)

**Comment by K8Sewell** [comment]
Resource Type added
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/0116eb4d-09f5-42a3-8c0a-1ae2cfb09adc)

**Comment by K8Sewell** [comment]
Call number and Part of added as they were labeled in app (Identifier Shelf Mark and Collection Name)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/5e9ab5b9-7f76-42b4-a41c-0dfdda947704)

**Comment by K8Sewell** [comment]
Can't see Image Count yet but the PR is ready - https://github.com/yalelibrary/yul-dc-blacklight/pull/193

**Comment by K8Sewell** [comment]
Moving back to in progress until the rest of rspec is cleaned up.

**Comment by mark-dce** [comment]
@K8Sewell re: date - those look like we'd expect.  The bracket notation "[2020]" is common convention for data supplied by the cataloger rather than in the work itself - i.e. if I know a book was released in 1896 from another source like publisher's records, but it's not explicitly stated in the book itself, I might put "[1896]" as the publication date, whereas if there was a publication date of 1896 printed on the title page, I would put "1896" as the date.  

Similarly, this is the human readable version of the date, so we might even see information like "circa 1920".  There's a different date field called dateStructured that has the machine readable ISO format date that we use to drive the date facet, but it's less human friendly so we're showing the free from date here.
