### ISSUE TITLE
Update facet styling to match Yale styling and branding

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#386]
**ACCEPTANCE**
Given the facet styling shown in the [Digital Collections - Search Results](https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758)
- [ ] Update the discovery application to match the styling as closely as possible
- [ ] Write up a new ticket(s) for any parts of the design that are problematic to implement in blacklight

**NOTE**
Feel free to reach out to Matt Walker with any questions or proposed changes that might make it easier to implement the design.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/3064318/88066383-4e8f3480-cb33-11ea-8fa5-5772fab69d19.png">

**Comment by K8Sewell** [comment]
Reaching out to Matt for input on current implementation

### In Progress Screenshots 

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/2286196a-75a6-461d-b00b-d54d489f0643)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/a7b61176-55c7-4a71-b846-bfa50737fd60)
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/dc99f7e6-57e6-448a-a383-2b4ec8cec6b8)

**Comment by K8Sewell** [comment]
Awaiting response from Matt Walker on the current design implementation.

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/226

Put up PR for the in progress design.

**Comment by mark-dce** [comment]
The facet font size seems to be changing, which is a little distracting.  And the remove boxes don't seem to be rendering correctly in Safari
![image](https://user-images.githubusercontent.com/3064318/90422707-dd369900-e080-11ea-8fe7-0842a677dbf1.png)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-08-17 at 1.45.56 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/44f34f1f-258c-4ac8-b3bc-fb130282ba16)

**Comment by K8Sewell** [comment]
Bug reported on the 'selected' facet transforming to a larger text size (that caused this ticket to be moved back to in progress) is captured in [ticket #462](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/462) so am moving this ticket to closed to avoid duplication or confusion.  The bug is the 5th acceptance criteria on ticket #462.
