### ISSUE TITLE
Update "All Fields" search behavior

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#388]
**ACCEPTANCE**
- [ ] When I select "All Fields" for my search, as many of the following following fields as currently exist* should be searched:
* abstract
* alternativeTitle
* alternativeTitleDisplay
* bibId_ssim
* contents
* contributor
* contributorDisplay
* creator
* creatorDisplay
* description
* publicationPlace
* publisher
* sourceCreator
* sourceTitle
* subjectGeographic
* subjectName
* subjectOccupation
* subjectTitle
* subjectTitleDisplay
* subjectTopic
* title
* titleStatement_ssim

*NOTE: We'll do another pass on field mappings closer to release and make sure we catch anything that was in flux between the Metadata Cloud, Management App, and Discovery App - so if we don't get 100% of fields in right now, that's ok, we just want to get as many as we can so we have representative support for UI and UX design.

**Comment by FCRodriguez7** [comment]
![image.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/220a9e78-8791-407d-bb25-0686fb4d4bb8)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-07-24 at 9.27.08 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f6dbad58-3ebb-4e59-a797-ffc9a4cc13e2)

**Comment by mark-dce** [comment]
@FCRodriguez7 I'm sorry I might not have been clear - adding each individual field to the dropdown is going to make it much to long and intimidating to new searchers.  This ticket is about the behavior when I have "All Fields" selected as my dropdown choice.   Historically, we had to explicitly add which fields were included in the "All Fields" searches; it looks like newer versions of Blacklight have switched that behavior to use a wildcard, so this ticket is about figuring about how to explicitly exclude fields from the search - i.e. we want to explicitly exclude "Record Type" from the "All Fields" search because searches for "oid" currently match all results in the repository (https://collections-demo.curationexperts.com/?search_field=all_fields&q=oid). 

The necessary changes look like they could be accomplished by adding a `qf` field to the [All Fields](https://github.com/yalelibrary/yul-dc-blacklight/blob/master/app/controllers/catalog_controller.rb#L205) configuration so it would end up looking more like the title search, but with an array of fields passed to `qf`.

**Comment by FCRodriguez7** [comment]
Just from your example, currently, the code for OID search field uses the field type orbisBibId_ssim not oid_ssim or recordType_ssim. 

On a separate note, I now understand the ticket as to explicitly include in the 'all search field' as many of the fields in the list when clicking on it without a label in the dropdown.  I mock a search and send it by tomorrow morning. 

Frederick

**Comment by mark-dce** [comment]
FWIW - My example was meant to talk about searching for the literal word "oid", not searching for the value of an oid like '1098675'.  If you literally search for the word "oid" right now, every record matches because every record has a field called recordType_ssim, and every item has the exact string "oid" in that field.

**Comment by FCRodriguez7** [comment]
I will create the array with just the fields from the list on this ticket.   Should we remove the other field names (Title, Author, Subject, BibID) in the dropdown? Or should we leave them in the dropdown menu?  

![Screen Shot 2020-07-25 at 6.09.24 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/16feeedb-0152-4984-add3-349799e7f1c6)

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/205
