### ISSUE TITLE
Index available fields from metadata cloud

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#389]
**ACCEPTANCE**
- [x] Given JSON provided by the metadata cloud, index the following field to solr.
- [x] Maintain a list of any existing fields that need to be remapped and deprecated later. Make a new ticket with list.

**DEVELOPER NOTE**
I've tried to identify single value fields and index them appropriately -i.e. they end in '...i' for indexed instead of '...im' for indexed multiple.  If it's easier to treat everything as multiples, feel free to index everything as '...im' instead.

IMPORTANT SUFFIXES
_tesim: text-english (toikenization), stored, indexed, multivalued
_dtsi: date, stored, indexed (single valued)
_ssi: string (don't tokenize), stored, indexed (single valued) - common for identifiers
_ssim: string (don't tokenize), stored, indexed, multivalued
See the whole array of options here: https://github.com/yalelibrary/yul-dc-solr/blob/master/solr/conf/schema.xml#L12 

Summary of field data seen in metadata cloud https://docs.google.com/spreadsheets/d/1WeMppPyJ9Qly0fQp575UBLDSz-4ziZVmH6e5OgQdql0/edit#gid=0

| field  | suffix   |
|---|---|
| abstract | _tesim |
| accessionNumber | _ssi |
| accessRestrictions | _tesim |
| alternativeTitle | _tesim |
| archiveSpaceUri | _ssi |
| box | _ssim |
| caption | _tesim |
| collectionId | _tesim |
| contents | _tesim |
| contributor | _tesim |
| contributorDisplay | _tesim |
| coordinate | _ssim |
| copyrightDate | _ssim |
| creator | _tesim |
| creatorDisplay | _tesim |
| date | _ssim |
| dateDepicted | _ssim |
| dateStructured | dtsi |
| dependentUris | _ssim |
| description | _tesim |
| digital | _tesim |
| edition | _tesim |
| extent | _tesim |
| extentOfDigitization | _ssi |
| findingAid | _ssi |
| folder | _ssi |
| format | _tesim |
| genre | _tesim |
| geoSubject | _tesim |
| identifierShelfMark | _ssi |
| illustrativeMatter | _tesim |
| indexedBy | _tesim |
| itemPermission | _tesim |
| language | _ssim |
| localRecordNumber | _ssim |
| material | _tesim |
| numberOfPages | _ssim |
| oid | _ssi |
| orbisBarcode | _ssi |
| orbisRecord | _ssi |
| partOf | _tesim |
| projection | _tesim |
| publicationPlace | _tesim |
| publisher | _tesim |
| recordType | _ssi |
| references | _tesim |
| relatedUrl | _ssim |
| repository | _tesim |
| resourceType | _ssim |
| rights | _tesim |
| scale | _tesim |
| source | _ssim |
| sourceCreated | _tesim |
| sourceDate | _tesim |
| sourceEdition | _tesim |
| sourceNote | _tesim |
| sourceTitle | _tesim |
| subjectEra | _ssim |
| subjectGeographic | _tesim |
| subjectName | _tesim |
| subjectTitle | _tesim |
| subjectTitleDisplay | _tesim |
| subjectTopic | _tesim |
| title | _tesim |
| uri | _ssim |

**Comment by maxkadel** [comment]
See https://github.com/yalelibrary/yul-dc-management/pull/169 

Fields that will be deprecated, along with info on replacement field:

```
      # fields below this point will be deprecated in a future release
      abstract_ssim: data_hash["abstract"], # replaced by abstract_tesim
      alternativeTitle_ssim: data_hash["alternativeTitle"], # replaced by alternativeTitle_tesim
      alternative_title_tsm: data_hash["alternativeTitleDisplay"], # replaced by alternativeTitleDisplay_tesim
      date_tsim: data_hash["date"], # replaced by date_ssim
      geo_subject_ssim: data_hash["geoSubject"], # replaced by geoSubject_ssim
      illustrative_matter_tsi: data_hash["illustrativeMatter"], # replaced by illustrativeMatter_tesim
      material_ssim: data_hash["material"], # replaced by material_tesim
      oid_ssim: data_hash["oid"] || oid, # replaced by oid_ssi
      orbisBarcode_ssim: data_hash["orbisBarcode"] || data_hash["barcode"], # replaced by orbisBarcode_ssi
      orbisBibId_ssim: data_hash["orbisRecord"], # replaced by orbisBibId_ssi
      projection_ssim: data_hash["projection"], # replaced by projection_tesim
      recordType_ssim: data_hash["recordType"], # replaced by recordType_ssi
      references_ssim: data_hash["references"], # replaced by references_tesim
      scale_ssim: data_hash["scale"], # replaced by scale_tesim
      sourceCreated_ssim: data_hash["sourceCreated"], # replaced by sourceCreated_tesim
      sourceDate_ssim: data_hash["sourceDate"], # replaced by sourceDate_tesim
      sourceEdition_ssim: data_hash["sourceEdition"], # replaced by sourceEdition_tesim
      sourceNote_ssim: data_hash["sourceNote"], # replaced by sourceNote_tesim
      sourceTitle_ssim: data_hash["sourceTitle"], # repleaced by sourceTitle_tesim
      subject_topic_tsim: data_hash["subjectTopic"], # replaced by subjectTopic_tesim and subjectTopic_ssim
      title_tsim: data_hash["title"] # replaced by title_tesim
```

**Comment by maxkadel** [comment]
New ticket created for Discovery team - https://github.com/yalelibrary/YUL-DC/issues/396
