### ISSUE TITLE
Teach out updated Camerata (gem) deployment process

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#390]
**ACCEPTANCE**
- [ ] Folks on each team have seen a demo of how to use camerata to deploy
- [ ] Folks on each team have the opportunity to deploy to a test cluster as desired

**Comment by maxkadel** [comment]
Is this a duplicate of #407 ?

**Comment by mark-dce** [comment]
I think adjacent - I'd written this first and it's tightly scoped to the deployment process.  #407 covers local development and cluster build processes too.  

So I think the first bullet here is probably included in #407, but ensuring that each team member can deploy isn't directly covered in the other training ticket and we should probably elaborate this as a placeholder for ensuring that everyone has done at least one deploy to ECS environments.
