### ISSUE TITLE
Design solution for versioning Metadata Cloud API

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#395]
**STORY**
As a PO, I would like a way for the Metadata Cloud team to iterate on API functionality without breaking downstream consumers, so that development of the Management app isn't tightly coupled to development of the Metadata Cloud

**ACCEPTANCE**
- [x] There is an agreed and documented plan to decouple changes in the two applications (like a documented versioned API)
- [x] There are tickets on the Metadata Cloud board to implement the solution
- [x] There are tickets on the YUL-DC board to implement the solution

**Comment by martinlovell** [comment]
Some ideas on how this might work:
https://github.com/yalelibrary/metadata-cloud/blob/api_versioning/API_VERSIONING.md

**Comment by martinlovell** [comment]
We've done some work on implementing this.

It will be possible to roll it out without affecting any of the existing endpoint's mappings, but will give clients the ability to request different versions of the mappings from any environment.

(The readme file linked above provides some information about how the mapping versions are implemented and consumed.)

**Comment by maxkadel** [comment]
Created ticket https://github.com/yalelibrary/YUL-DC/issues/712 - can be broken into smaller tickets if need be

**Comment by orangewolf** [comment]
I agree with this ticket, it seems to clearly encompass the issue.  @mark-dce can we get your eyes on it when you get chance for approval?
