### ISSUE TITLE
Address Management application field deprecation

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#396]
The following fields are being deprecated in the Management application, and will be removed in a future release.

The Discovery application should point to the "replaced by" versions of the following fields:

```
      # fields below this point will be deprecated in a future release
      abstract_ssim: data_hash["abstract"], # replaced by abstract_tesim
      alternativeTitle_ssim: data_hash["alternativeTitle"], # replaced by alternativeTitle_tesim
      alternative_title_tsm: data_hash["alternativeTitleDisplay"], # replaced by alternativeTitleDisplay_tesim
      date_tsim: data_hash["date"], # replaced by date_ssim
      geo_subject_ssim: data_hash["geoSubject"], # replaced by geoSubject_ssim
      illustrative_matter_tsi: data_hash["illustrativeMatter"], # replaced by illustrativeMatter_tesim
      material_ssim: data_hash["material"], # replaced by material_tesim
      oid_ssim: data_hash["oid"] || oid, # replaced by oid_ssi
      orbisBarcode_ssim: data_hash["orbisBarcode"] || data_hash["barcode"], # replaced by orbisBarcode_ssi
      orbisBibId_ssim: data_hash["orbisRecord"], # replaced by orbisBibId_ssi
      projection_ssim: data_hash["projection"], # replaced by projection_tesim
      recordType_ssim: data_hash["recordType"], # replaced by recordType_ssi
      references_ssim: data_hash["references"], # replaced by references_tesim
      scale_ssim: data_hash["scale"], # replaced by scale_tesim
      sourceCreated_ssim: data_hash["sourceCreated"], # replaced by sourceCreated_tesim
      sourceDate_ssim: data_hash["sourceDate"], # replaced by sourceDate_tesim
      sourceEdition_ssim: data_hash["sourceEdition"], # replaced by sourceEdition_tesim
      sourceNote_ssim: data_hash["sourceNote"], # replaced by sourceNote_tesim
      sourceTitle_ssim: data_hash["sourceTitle"], # repleaced by sourceTitle_tesim
      subject_topic_tsim: data_hash["subjectTopic"], # replaced by subjectTopic_tesim and subjectTopic_ssim
      title_tsim: data_hash["title"] # replaced by title_tesim
```

For context, see https://github.com/yalelibrary/yul-dc-management/pull/169 and https://github.com/yalelibrary/YUL-DC/issues/389 

## Acceptance ##
As a user, when I search or filter on a given field, I should see the correct, non-deprecated terms in the url bar and not the existing deprecated terms. 

All deprecated terms are removed from the blacklight app (verifiable via code inspection)

A ticket in management project is created to remove the deprecated terms.

**Comment by K8Sewell** [comment]
* [x] abstract_ssim: data_hash["abstract"], # replaced by abstract_tesim
* [x] alternativeTitle_ssim: data_hash["alternativeTitle"], # replaced by alternativeTitle_tesim
* [ ] alternative_title_tsm: data_hash["alternativeTitleDisplay"], # replaced by alternativeTitleDisplay_tesim
alternative_title_tsm - does not exist in the Blacklight app, added alternativeTitleDisplay_tesim to show fields in catalog controller
* [x] date_tsim: data_hash["date"], # replaced by date_ssim
* [ ] geo_subject_ssim: data_hash["geoSubject"], # replaced by geoSubject_ssim
geoSubject_ssim is already present in the Blacklight app
* [x] illustrative_matter_tsi: data_hash["illustrativeMatter"], # replaced by illustrativeMatter_tesim
Both the illustrative_matter_tsi and illustativeMatter_ssim were changed to illustrativeMatter_tesim
* [x] material_ssim: data_hash["material"], # replaced by material_tesim
* [x] oid_ssim: data_hash["oid"] || oid, # replaced by oid_ssi
* [x] orbisBarcode_ssim: data_hash["orbisBarcode"] || data_hash["barcode"], # replaced by orbisBarcode_ssi
* [x] orbisBibId_ssim: data_hash["orbisRecord"], # replaced by orbisBibId_ssi
* [x] projection_ssim: data_hash["projection"], # replaced by projection_tesim
* [x] recordType_ssim: data_hash["recordType"], # replaced by recordType_ssi
* [x] references_ssim: data_hash["references"], # replaced by references_tesim
* [x] scale_ssim: data_hash["scale"], # replaced by scale_tesim
* [x] sourceCreated_ssim: data_hash["sourceCreated"], # replaced by sourceCreated_tesim
* [x] sourceDate_ssim: data_hash["sourceDate"], # replaced by sourceDate_tesim
* [ ] sourceEdition_ssim: data_hash["sourceEdition"], # replaced by sourceEdition_tesim
sourceEdition_ssim - does not exist in the Blacklight app, added sourceEdition_tesim to show fields in catalog controller
* [x] sourceNote_ssim: data_hash["sourceNote"], # replaced by sourceNote_tesim
* [x] sourceTitle_ssim: data_hash["sourceTitle"], # repleaced by sourceTitle_tesim
* [ ] subject_topic_tsim: data_hash["subjectTopic"], # replaced by subjectTopic_tesim and subjectTopic_ssim
 subject_topic_tsim - does not exist in the Blacklight app, subjectTopic_ssim was already present, added subjectTopic_tesim to show fields in catalog controller
* [x] title_tsim: data_hash["title"] # replaced by title_tesim

**Comment by K8Sewell** [comment]
### Progress Update
* When ```title_tsim``` is updated to ```title_tesim``` the displayed title becomes the numeric manifest ID.  
- Questions: 
* Once the data is reindexed from the newer management app will this issue resolve itself? 
* Would it be better to leave the _tsim?
* The only difference in the suffix is 'text' vs 'english text' so why is the title display breaking?

### Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d133c304-9f4c-43fa-a698-1be1ab3025ad)

### Testing Update
* Started with 5 broken tests due to changing the field suffix
* 2 remaining tests failing are ```spec/system/view_images_in_search_spec.rb``` lines 35 & 63 which makes sense since on the page there are no public images displaying.  Presently working on getting the public images to display.

### WIP PR
[Draft PR #207](https://github.com/yalelibrary/yul-dc-blacklight/pull/207)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/207
