### ISSUE TITLE
Request: Change Solr field types ssim to tesim

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#397]
**Current field types of** 
resourceType_ssim
identifierShelfMark_ssim

**Add field type to also be:**
resourceType_tesim
identifierShelfMark_tesim

**Comment by edejesusyale** [comment]
Using tesim as the field type makes the highlighting work in the search results.
The first is with ssim field type and the second is with tesim:

![failures_r_spec_example_groups_search_results_displays_field_within_search_results_fails_32.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/a2bdb43e-dd28-472a-bfb0-10fd3efb02ac)
![failures_r_spec_example_groups_search_results_displays_field_within_search_results_fails_514.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/211772bb-bda6-432c-a7f7-e5cbb0e44cc3)
