### ISSUE TITLE
Microservice versions not showing in management app front screen

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#398]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/5454a699-d1df-4c86-84a4-7ab1074f630a) (taken on version deployed mon. july 27) (wonder if this is related to the camerata change to using amazon SSM to track docker image versions rather than having .env be definitive)

**Comment by orangewolf** [comment]
we believe this is also is solves the blacklight version in the footer.
