### ISSUE TITLE
deploy-sql and deploy-solr not working through cam tool

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#401]
# Acceptant #
These two scripts should run the same both in and out of the camerata cli and produce the same results either way.

**Comment by JzGo** [comment]
When testing `cam deploy-solr` to the rkadel-jul14 test cluster, I receive this error:

![Screen Shot 2020-07-30 at 9.26.34 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/b13ebea1-b869-4abd-9847-94162b48c19a)

Honestly, this might be an issue with the the state of the test cluster. In using the shell scripts, I don't get the above error, but solr is still unable to start.
