### ISSUE TITLE
Teach Out - updated camerata tools

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#407]
**ACCEPTANCE**
- [x] Draft training to cover
    - [ ] blacklight setup, development, test runs
    - [ ] management setup, development, test runs
    - [ ] metadata and content population 
    - [ ] deployment
    - [ ] releasing 
    - [ ] Secret and configuration management (AWS SSM)
  
- [x] Schedule time for the week of 8/10

**Comment by RachelDCE** [comment]
Teachout scheduled: Wed, Aug 12, 2:00 pm (EST)
