### ISSUE TITLE
Identify 5-10 very large images in 3-5 parent objects

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#409]
**STORY**
We'd like some really big images to make sure our work streams handle large TIFFs effectively

**ACCEPTANCE**
- [x] Identify 3-5 works with one or more really large (storage size) TIFF files 
- [x] Add them to our sample sets (images and parent OIDs)

**Comment by dl-maura** [comment]
We selected 4 images:

10616789: https://brbl-dl.library.yale.edu/vufind/Record/3443475?image_id=10616789
16595639: https://brbl-dl.library.yale.edu/vufind/Record/4228338?image_id=16595639
16595638: https://brbl-dl.library.yale.edu/vufind/Record/4227529?image_id=16595638
16352433: https://brbl-dl.library.yale.edu/vufind/Record/4424069?image_id=16352433

**Comment by dl-maura** [comment]
I will be sharing a box link for these images to be downloaded

**Comment by dl-maura** [comment]
Delayed due to no power/wifi

**Comment by dl-maura** [comment]
I've uploaded them to box and shared with @mikeapp
