### ISSUE TITLE
Remove excess whitespace in safari 

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#410]
In Safari, there is excess whitespace between the title and the metadata on the search results screen

- [x] The whitespace between the header and the metadata in the search results screen should look the same as it does in firefox and chrome

![Screen Shot 2020-08-04 at 1.24.34 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/cf28a524-2ba9-4fbe-9fd0-607a9ae2a610)

**Comment by FCRodriguez7** [comment]
The current PR is in a draft.  The text now bleeds on the image. 

 ![Screen Shot 2020-08-12 at 10.10.34 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/971c2b08-7694-40e2-96cf-77dc263135f1)

**Comment by FCRodriguez7** [comment]
The correct changes were added to the css.  Safari looks identical to both Firefox and Chrome.  

![Screen Shot 2020-08-12 at 10 48 43 AM](https://user-images.githubusercontent.com/41123693/90029938-759bda80-dc89-11ea-9a2f-79b4e19bd995.png)

**Comment by FCRodriguez7** [comment]
There was an issue with text overlapping on smaller and medium screen size.  I have fixed the issue and the PR is ready.  

![Screen Shot 2020-08-13 at 12.15.33 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/409b07a8-e161-4455-bf72-e4b2b76aba2b)

![Screen Shot 2020-08-13 at 12.04.43 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/83fde6d3-1bff-4c75-8b58-11e8692a46bd)

![Screen Shot 2020-08-13 at 10.45.11 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0c8e7fac-dda0-40c9-b2bc-25f48665258c)
