### ISSUE TITLE
Remove hard-coded Honeybadger keys from Camerata

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#412]
Best practice is not to have Honeybadger keys committed, remove from https://github.com/yalelibrary/yul-dc-camerata/blob/ae2af74995cbd1fece3675a3cfb9dd5749ca8398/docker-compose.ecs.yml#L35

QUESTION: Remove from history? Or change keys?

**ACCEPTANCE**
- [x] Remove any honeybadger API keys directly specified in `yul-dc-camerata` (see #354)

Once the above step is complete, 
- [x] Reset the API keys to new values that have never been checked into GitHub - e.g. https://app.honeybadger.io/projects/72587/tokens
- [x] Save the new keys to the Parameter Store
- [x] Redeploy to current clusters (probably yul-test & yul-demo) to activate new keys

**Comment by mark-dce** [comment]
@maxkadel thanks for noticing this - it was supposed to have happened as part of this ticket but apparently didn't - 
https://github.com/yalelibrary/YUL-DC/issues/355
we'll have to be better about running through acceptance criteria before closing tickets ( shakes finger at @orangewolf )
