### ISSUE TITLE
IIIF Manifests - Hosts

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#415]
The situation: 
* Right now (8/10/2020), we have 
  * Fixture manifests that have the host as `127.0.0.1` for both images and manifests (see e.g. https://github.com/yalelibrary/yul-dc-fixture-manifests/blob/master/10001192.json)
  * A very simple web server that currently serves up the fixture manifests, and substitutes the environment variables for 
    * `IIIF_MANIFESTS_BASE_URL` for `http://127.0.0.1/manifests/`  
    * `IIIF_IMAGE_BASE_URL` for `http://127.0.0.1/iiif`
* The Management application is starting to create manifests, but needs to access the image server's (Cantaloupe's) `info.json` for a given image to get the correct width and height for the manifest. 
  * Because it needs to access the locally running image server, taking the most direct route to locally working code, the manifest urls still start with `http://127.0.0.1/manifests/` in the outputted manifests, but the `IIIF_IMAGE_BASE_URL` will be whatever works in a given environment, which will not ever be `http://127.0.0.1/iiif` (see [Camerata templates/iiif-manifest-compose.yml#L9](https://github.com/yalelibrary/yul-dc-camerata/blob/db7c2b71453b0ff520700ce22fbb3f24d215c1b3/templates/iiif-manifest-compose.yml#L9) and [Camerata templates/iiif-manifest-compose.ecs.yml#L6](https://github.com/yalelibrary/yul-dc-camerata/blob/db7c2b71453b0ff520700ce22fbb3f24d215c1b3/templates/iiif-manifest-compose.ecs.yml#L6)
* The Management application can save the generated manifests to S3, and could presumably also serve them to Blacklight directly. If that's the plan, how do we migrate to doing that? If not, do we need to have Management re-substitute `IIIF_IMAGE_BASE_URL` with `http://127.0.0.1/iiif`?

**Comment by maxkadel** [comment]
Decision document https://docs.google.com/document/d/1TSqKAtitOkgEJbsKJl0NK9FHfd5GP1PRfn8E-8LLak8/edit# (Currently DCE only)

**Comment by dl-maura** [comment]
See decision document above for final decisions/action items
