### ISSUE TITLE
Add step to release process

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#417]
- [x] Add a step to our release process in the README that says: "Move any tickets that have included in this release from `For Release` to `Ready for Acceptance`"

**Comment by maxkadel** [comment]
PRs added to 
 - Blacklight - https://github.com/yalelibrary/yul-dc-blacklight/pull/228
 - Management - https://github.com/yalelibrary/yul-dc-management/pull/207
 - Camerata - https://github.com/yalelibrary/yul-dc-camerata/pull/121
