### ISSUE TITLE
Manifests - add IIIF viewing direction & behavior

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#420]
- [ ] ~From XML import, saves viewingDirection to the ParentObject~
  - [ ] ~Valid options are left-to-right, right-to-left, top-to-bottom, and bottom-to-top (see https://iiif.io/api/presentation/2.1/#viewingdirection)~ (we are about to work a bunch on the xml changes, so it seemed better to allow this through the UI first, then once we have more examples from Goobi we can update that part of the code)
- [x] Add viewingDirection to IIIF manifest factory (default "left-to-right") [n.b. this is also the default if nothing is recorded)
- [ ] Add viewingHint to ~at least manifest level of IIIF manifest~ sequence
  - [x] Valid choices for 2.1 are individuals, paged, continuous, multi-part, non-paged, top, and facing-pages. See https://iiif.io/api/presentation/2.1/#viewinghint  
  - [ ] BONUS: If available for page / ChildObject level metadata, add to image annotation (see, e.g., https://collections-demo.library.yale.edu/catalog/2012315 - the image labeled "12r" is actually 2 facing pages, which is an exception to the rest of the images)

**Comment by maxkadel** [comment]
This ticket needs to be edited to reflect only IIIF version 2 (currently mixes 2 & 3)

**Comment by maxkadel** [comment]
before for 2012315
![image](https://user-images.githubusercontent.com/45948126/101216267-37b62e00-364d-11eb-99d9-e2a81c59510e.png)

**Comment by maxkadel** [comment]
After defining it as "paged" and "right-to-left"
![image](https://user-images.githubusercontent.com/45948126/101216539-ad21fe80-364d-11eb-8bb7-96f3df2f8f3a.png)

**Comment by maxkadel** [comment]
On UAT - https://collections-uat.library.yale.edu/catalog/16882821 

Before
![image](https://user-images.githubusercontent.com/45948126/101651356-f9cd5700-3a0a-11eb-97c5-597b60274a43.png)

After
![image](https://user-images.githubusercontent.com/45948126/101651720-60527500-3a0b-11eb-84b8-0792321ac6eb.png)

**Comment by mark-dce** [comment]
Nice!  Took me a second to remember I was driving on the left side of the road...
