### ISSUE TITLE
Add License and Attribution to IIIF Manifest

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#421]
For IIIF Viewers outside the context of the Yale Blacklight application, showing Yale works (e.g. https://universalviewer.io/uv.html?manifest=https://collections-uat.library.yale.edu/manifests/2003431.json )

- [x] Add appropriate license for work/ ParentObject to IIIF manifest
  - ~~NOTE: This is also on the show page in Blacklight, so it may be low-priority for the time being.~~ Added to metadata prior to this ticket
- [x] Add attribution statement to IIIF manifest
  - ~~QUESTION: What do we want this to be? Does it already exist somewhere? (Thinking of something along the lines of `"attribution": "Provided by the Beinecke Rare Book & Manuscript Library of the Yale University Library in New Haven, Connecticut"`~~
    - Using "Yale University Library" per Mike Appleby

**Comment by maxkadel** [comment]
## Before (on VPN):
https://collections-test.library.yale.edu/catalog/15495320
https://universalviewer.io/uv.html?manifest=https://collections-test.library.yale.edu/manifests/15495320#?c=0&m=0&s=0&cv=0&xywh=-1741%2C-82%2C4634%2C2304 
![image](https://user-images.githubusercontent.com/45948126/102627464-3b01ed00-4116-11eb-8840-0dcaf879155c.png)

**Comment by maxkadel** [comment]
After (on local) 
![image](https://user-images.githubusercontent.com/45948126/102636231-64c11100-4122-11eb-8082-a93bc3ed3e8b.png)

**Comment by maxkadel** [comment]
https://collections-test.library.yale.edu/management/parent_objects/999957
https://collections-test.library.yale.edu//catalog/999957

![image](https://user-images.githubusercontent.com/45948126/102922769-90166980-445c-11eb-9011-a8e8bfd4988a.png)

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/catalog/999957

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/4020aca6-0997-4c8f-be6c-8b5599624dc3)
