### ISSUE TITLE
Remove Bookmark checkbox on search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#423]
**ISSUE**
We've decided to remove the ability to retrieve bookmarks and removed the corresponding link from the header, but we still have bookmark checkboxes displaying in search results.  This gives the incorrect impression that users can save bookmarks within the application to retrieve later.

**ACCETPANCE**
- [x] Users do not have the option to bookmark items within search results
- [x] Users do not have the option to bookmark items in the toolbox

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3064318/89922137-3e172a80-dbc4-11ea-977d-dab9be454fbe.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/3064318/89922308-79195e00-dbc4-11ea-80ee-7b55a4826ed1.png">

**Comment by mikeapp** [comment]
Possibly helpful: https://github.com/projectblacklight/blacklight/wiki/Bookmarks

**Comment by FCRodriguez7** [comment]
I have commented out the bookmark functionality.  The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/230


----

![Screen Shot 2020-08-11 at 3.52.26 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/065bd827-ec47-4283-a3b5-df4cbda58ad5)

---

![Screen Shot 2020-08-11 at 3.52.41 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1c53e1bb-03d7-4893-8cc5-c653f8490ef7)
