### ISSUE TITLE
SPIKE: Bugherd to gather user feedback

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#425]
**STORY**
Yale is using Bugherd https://bugherd.com to track user feedback for other library projects, so if possible we'd like to pilot it's use for the Beinecke project.  Do a try run and report back on what it might look like to implement for the remainder of the project.

**ACCEPTANCE**
- [x] Grant team members access to bugherd
    - [x] Set up a free trial or add consultants to Yale's existing account
- [ ] ~Add Bugherd code to the discovery application~ see #453
- [x] Test submitting feedback
- [x] Recommend process for periodic review and response to user feedback

**Comment by mikeapp** [comment]
Assigning myself for account creation/management.  Happy to pair on other aspects as well.

**Comment by mark-dce** [comment]
![image](https://user-images.githubusercontent.com/3064318/90536059-2ea65d00-e141-11ea-8925-246163bbd022.png)

**Comment by mark-dce** [comment]
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3064318/90538215-da50ac80-e143-11ea-80ea-1867335fb408.png">

**Comment by mark-dce** [comment]
**PROCESS RECOMMENDATION**
1. Review any user submitted feedback weekly (Wednesday or Thursday)
2. Categorize issues as bug, in-scope enhancement, non-development, future phase, won't fix
3. Add bug and in-scope enhancement requests to the upcoming sprint
4. Respond to user submitting the feedback about the status of their issue
