### ISSUE TITLE
Update Facet Order

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#426]
**ACCEPTANCE**
- [ ] Facets should appear in the following order
    * Extent of Digitization
    * Format
    * Genre
    * Resource Type
    * Language
    * Author
    * Subject Topic (needs to be added)
    * Subject Name (needs to be added)
    * Call Number
    * Digital Collection
    * Publication Date

**Comment by K8Sewell** [comment]
PR up for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/231
