### ISSUE TITLE
Move tools to bottom of item view page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#427]
**STORY**
The blacklight toolbox current sits on top of universal viewer and obstructs UV controls.  While we develop a full page design, we'd like to make this less distracting for the time being.

**ACCEPTANCE**
- [ ] The tools box displays below metadata and above the footer 
- [ ] The results look at least as pretty as the mock up below
- [ ] [BONUS] the results look better than the screenshot 😉

<img width="642" alt="image" src="https://user-images.githubusercontent.com/3064318/89925836-9866ba00-dbc9-11ea-8016-5f9c30746d41.png">

**Comment by K8Sewell** [comment]
PR up for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/229

**Comment by mikeapp** [comment]
It looks like the invisible sidebar div is still overlaying UV and intercepting clicks to the controls.  The highlighted ones aren't working for me:

![Screen Shot 2020-08-14 at 1.27.09 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b268900b-4167-43c8-a8bb-cad12181ce82)

**Comment by mikeapp** [comment]
A bigger issue for discussion, but if we drop the sidebar it's probably worth expanding the main div to col-lg-12 and making UV wider.  UV is fixed width though, so perhaps we need to consider what happens with it on mobile in general?

**Comment by K8Sewell** [comment]
Adjusted the z index of the UV viewer so now the elements that were unable to be selected are now available again.

https://github.com/yalelibrary/yul-dc-blacklight/pull/238
