### ISSUE TITLE
Refine facet rendering

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#429]
# Summary
Feedback relayed from Matt on in progress facet designs

# Acceptance Criteria
- [x] Rotate caret - should point up when collapsed and point down when expanded
- [ ] Put the numbers inside parenthesis and move next to the item name
- [x] Move x's to the right hand side

**Comment by dl-maura** [comment]
![Screen Shot 2020-08-12 at 1.08.28 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c4b4de70-87df-4fab-bcc8-abd67c4ce9bb)

**Comment by K8Sewell** [comment]
WIP PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/234

### In Progress Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/bcaa510c-f48b-4a13-8a3c-a98122d6a99b)

**Comment by K8Sewell** [comment]
Alternate option - also not true to design - will keep at it
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/87cfe46a-86eb-4e93-9487-7e4be91d4f8a)

**Comment by K8Sewell** [comment]
Initial assumption that one would be able to simply get the correct partial from blacklight and overwrite it was incorrect.  The facet value is actual rendered through a component and the facet count is tacked on the end so this is not as simple as moving a few span elements around in an html.erb file.  Screenshot below and [link to blacklight repo where method is defined](https://github.com/projectblacklight/blacklight/blob/8b86f9ed6530821642431391f99b83d5371c4433/app/components/blacklight/facet_item_component.rb#L75)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/c220e00b-c762-499d-9831-21f7cca48566)

Will continue to attempt to match the Zeplin design for the rest of the afternoon and will post any further updates if I have any.

**Comment by orangewolf** [comment]
Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by alishaevn** [comment]
https://github.com/projectblacklight/blacklight/blob/e7d59c6544bf241874e1fd5216329e324691b6d0/app/helpers/blacklight/facets_helper_behavior.rb#L224 ?

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-08-17 at 1.45.56 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e1f554d8-283c-43e2-8119-ca584462728c)

**Comment by K8Sewell** [comment]
Moving this ticket to closed to avoid duplication or confusion.  I wrote this ticket with incorrect directions for the facet caret and that is fixed in (ticket #462)[https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/462].  Ticket #462 also has clearer acceptance criteria and visuals.
