### ISSUE TITLE
Review PTIFFF Conversion (in DL)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#430]
**ACCEPTANCE**
- [x] Identify staff to review converted PTIFFs 
- [x] Select a random sample of images from the images associated with the first 500 migrated objects
- [x] Review the images for quality and artifact issues
- [x] Write up tickets to address any issues that are identified

**Comment by mikeapp** [comment]
Looks like the NGA has updated their code to improve color profile handling:
https://github.com/NationalGalleryOfArt/iipsrv/blob/master/imagescripts/tiff_to_pyramid.bash

This might alleviate the errors that I had to modify the earlier version to ignore.

**Comment by mikeapp** [comment]
Original issue for VIPS: https://github.com/libvips/libvips/issues/659

**Comment by dl-maura** [comment]
Start this work when the 500 ptiffs are generated, and have DSU/YUL folks review and let us know of any issues. Will create tickets for issues based on that

**Comment by dl-maura** [comment]
https://docs.google.com/spreadsheets/d/1fPnfguoLPFPEu4a9HbVjLuDBG6o4iBb7iWQ8NS6be1E/edit?usp=sharing

**Comment by dl-maura** [comment]
Maura will make list of child oids
