### ISSUE TITLE
SPIKE: Plan to handle file paths and image processing

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#437]
- Manifests need image height and width
  - May need to be re-scaled from preservation masters

**Comment by bess** [comment]
@mikeapp Suggests: We should get the height and width from the ptiff generator and record these values in the database. 

- [ ] Change the manifest generator service to get this info from the database instead of from cantaloupe 

+1 Rob
+1 Bess 

Max and Bess to write up implementation ticket.

**Comment by maxkadel** [comment]
#505 #506 #507 #508 #509 #510 and #511 were created based on this work. See also https://docs.google.com/document/d/1TSqKAtitOkgEJbsKJl0NK9FHfd5GP1PRfn8E-8LLak8/edit#
