### ISSUE TITLE
Install and configure Delayed Job and Delayed Job Web for Active Job

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#438]
# Acceptance
- [x] as a logged in user i can see the web interface for background jobs
- [x] when I create a new parent object the metadata cloud call is done in the background
- [x] when I create a new parent object the solr indexing is done in the background
- [x] developers can run delayed jobs when they spin their stack up
- [x] deployment will start a background worker

# Hints
Please note - use active job here and not direct delayed job calls
https://github.com/collectiveidea/delayed_job
https://github.com/ejschmitt/delayed_job_web

**Comment by jpengst** [comment]
Update for Friday:
Delayed Job is hooked up. Background cloud calls and Solr indexing working as well. 

TODO: 
developers can run delayed jobs when they spin their stack up
deployment will start a background worker
authentication for the web ui 

No blockers

**Comment by orangewolf** [comment]
This is ready for final review. Max's questions are at least responded to, the start up issue is resolved and I old school rebased it to clean up the history for Bess.
