### ISSUE TITLE
Provide gallery view for search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#445]
**STORY**
As a scholar, I'm interested in the visual characteristics of works, and would like to be able to view search results in a way that allows me to see more thumbnails on the screen at one time

**DEVELOPER HINT**
This is typically accomplished by implementing the [Blacklight Gallery](https://github.com/projectblacklight/blacklight-gallery#blacklightgallery) gem.

**ACCEPTANCE**
- [x] I can toggle search results between list and gallery views
  - [x] If using blacklight-gallery, remove slide-show and mortar view options
- [x] Gallery views should include
  - [x] The thumbnail for the work (as a link to the work)
  - [x] The work title (as a link to the work)

**Comment by FCRodriguez7** [comment]
I thought twice about adding this comment: 
https://www.microsoft.com/en-us/edge?&OCID=AID2001284_SEM

**Comment by FCRodriguez7** [comment]
The example provided by DCE: 

https://digital.library.ucla.edu/catalog?q=&search_field=all_fields&utf8=✓&view=gallery

**Comment by FCRodriguez7** [comment]
Co-authored-by: Alisha Evans <alisha@notch8.com>

MR: https://github.com/yalelibrary/yul-dc-blacklight/pull/241

As a scholar, I'm interested in the visual characteristics of works, and would like to be able to view search results in a way that allows me to see more thumbnails on the screen at one time

**DEVELOPER HINT**
Implemented the [Blacklight Gallery](https://github.com/projectblacklight/blacklight-gallery#blacklightgallery) gem.

**ACCEPTANCE**
- [x] I can toggle search results between list and gallery views
  - [x] If using blacklight-gallery, remove slide-show and mortar view options
- [x] Gallery views should include
  - [x] The thumbnail for the work (as a link to the work)
  - [x] The item title (as a link to the work)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41123693/90679795-b1f1ac80-e22e-11ea-8189-18876c20519f.gif)
