### ISSUE TITLE
SPIKE: Evaluate tools for cross-browser testing

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#449]
**ISSUE**
Folks using all the major modern browsers including Microsoft Edge, Safari, Chrome, and Firefox need to successfully access and navigate the DL.  Rather than leaving browser compatibility issues to be discovered and reported by users, is there any way we can make cross-browser testing a routine or automatic part of our development workflow.

**ACCEPTANCE**
- [x] Investigate whether Yale has any existing tooling in this area (Kara Franco might have pointers)
- [x] Identify 3-4 options for cross browser testing (see https://www.browserstack.com, https://crossbrowsertesting.com, https://saucelabs.com/cross-browser-testing, any tools Yale currently uses, etc.)
- [x] Spend up to 4 hours reviewing and piloting each selected service
- [x] Develop a list of the most useful and relevant features of each
- [x] Recommend a tool and estimate (write up a ticket) the steps to implement it and run it manually or automatically as part of our acceptance testing process

**Comment by K8Sewell** [comment]
[Cross browser testing research document.](https://docs.google.com/spreadsheets/d/19yYtxOpXFM4bcAwS69Ca-sS_N9Uf7tolRdyUa_OoaH0/edit?usp=sharing)  Will add notes from implementation spikes once complete.

**Comment by K8Sewell** [comment]
Spike notes have been added to the research document.

**Comment by K8Sewell** [comment]
Notes added for platform usage to research document.

**Comment by K8Sewell** [comment]
Tickets for team review added to unprioritized - #503 & #504
