### ISSUE TITLE
SPIKE: Recommend method for debugging issues with Microsoft Edge browser

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#450]
**ISSUE**
In order to resolve Edge-specific browser compatibility issues, we'll need some platform to develop and test against.  This might be a dedicated testing machine (laptop), a virtual machine running a current recent desktop version of Windows with Edge installed, Edge installed on Mac, a virtualized solution like https://www.browserstack.com, or some other solution that supports iterative debugging and development.

**ACCEPTANCE**
- [x] Pilot and recommend a solution for debugging and resolving Edge specific browser issues.

**Comment by FCRodriguez7** [comment]
I thought twice about adding this comment.  Microsoft has an Edge favor for Apple.  
https://www.microsoft.com/en-us/edge?&OCID=AID2001284_SEM

**Comment by alishaevn** [comment]
@dl-maura  I'm unable to access the remote desktop right now. I tried with http://yuldce01.yu.yale.edu/ and 10.6.68.25

#### Chrome
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/743753e6-101e-41ee-b65d-0a751f5cbcaf)

#### Safari
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/379a07ed-66fa-4ace-aa6c-e1e877a09ed9)

#### Firefox
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/d2c31316-1c5d-420f-8e26-2c68d0b80528)

**Comment by alishaevn** [comment]
I was able to connect! the steps I followed are:

- download [microsoft remote desktop](https://apps.apple.com/us/app/microsoft-remote-desktop/id1295203466?mt=12)
- sign into the vpn using the cisco client
- open microsoft remote desktop
- add a new pc:
  - pc name: yuldce01.yu.yale.edu
  - user account: click the drop down and press "add user account" (same un/pw you logged into the vpn with)
- under "friendly name" I put "microsoft edge", but it isn't necessary
- "save"
- double click the pc you just created (it will have a name if you gave it one)
- when you see this message, press "continue"
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/cf606f83-e176-4cbe-8d80-8fac485585c9)


you're now connected!

**Comment by dl-maura** [comment]
We will use the vpc when people need it
