### ISSUE TITLE
Practice submitting bugherd feedback

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#451]
**PROCESS**
* Join the project using the guest access link: https://www.bugherd.com/invitation/yxyxqrpeunoxnvq7fdegag
* Watch the getting started video https://www.youtube.com/watch?v=XcU9Gd8rg8M
* Visit the test site at https://collections-test.library.yale.edu/
* Submit a sample feedback item
* Go to the project and resolve the feedback

**ACCEPTANCE**
- [x] Mark
- [x] Maura
- [x] Mike
- [ ] Rebecca
- [x] Bess
- [x] Alisha
- [x] Kait
- [x] Frederick
- [ ] Eric

**Comment by mikeapp** [comment]
I've had an issue with Bugherd not appearing in Safari unless I turn off tracking protection.
