### ISSUE TITLE
Initial Tooling teach-out with Kara Franco

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#452]
**ACCEPTANCE**
- [x] One or more team members conduct a walk-through of our accessibility testing process so far with Kara.

**Comment by K8Sewell** [comment]
Emailed Kara; working out time to touch base.

**Comment by K8Sewell** [comment]
Check in scheduled for 8/26 after Discovery stand up w/ Frederick, Kara and myself.

**Comment by K8Sewell** [comment]
Post meeting with Kara recommendation is to continue using the industry standard aXe gem for automated testing and Lighthouse for manual testing at regular intervals.  Additional accessibility resources and research from Kara will be added to this ticket once it is received and organized.

**Comment by K8Sewell** [comment]
# Additional Resources
### Videos
[A11yCasts (series of YouTube videos about accessibility from Google)](https://www.youtube.com/watch?v=HtTyRajRuyY)
[W3C Intro to Accessibility edX (Free)](https://www.edx.org/course/web-accessibility-introduction)

### Guides and Standards
[WCAG Overview](https://www.w3.org/WAI/standards-guidelines/wcag/)
[ARIA Overview](https://www.w3.org/WAI/standards-guidelines/aria/)
[W3C WAI Tutorials](https://www.w3.org/WAI/tutorials/)

### Testing
[Screen reader testing Q&A](https://webaim.org/articles/screenreader_testing/)
[Keyboard Testing Basics](https://webaim.org/techniques/keyboard/)

### Resources to follow
[Digita11y- The Great Accessible Blog Round up (list of influential bloggers)](https://www.digitala11y.com/accessibility-blogs/)
[A11yWeekly (newsletter that sends links to great info)](https://a11yweekly.com/)
[MicroAssist Accessibility Newsletter (more legal focused, less dev focus- but a great resource for keeping up with disability rights!)](hhttps://www.microassist.com/digital-access/news/)
