### ISSUE TITLE
Add Bugherd javascript to the discovery application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#453]
**NOTES**
Copy and paste this code inside the `<head\>` tag on all the pages you would like to use BugHerd with.
```
<script type="text/javascript" src="https://www.bugherd.com/sidebarv2.js?apikey=#{ENV(BUGHERD_API_KEY)}" async="true"></script>
```

**DISCUSSION**
Do we need to keep the api key private?

**ACCEPTANCE**
- [ ] Set up a bugherd project key in AWS Parameter Store
- [ ] Update deployment scripting to read the project key
- [ ] Add the code to the application and deploy

**Comment by mark-dce** [comment]
Hi,

Mark Bussey needs your help to install some Javascript for the Digital Collections project on BugHerd.
To do this, add this code snippet in the <head> tag of all pages on http://collections-test.library.yale.edu/.

```
<script type="text/javascript" src="https://www.bugherd.com/sidebarv2.js?apikey=...key.omitted..." async="true"></script>
``` 

Oh, and don't forget to let Mark Bussey know when you're done.

Cheers,

The BugHerd Team.

**Comment by K8Sewell** [comment]
Double checking - we decided that adding the API key directly was the desired path forward, yes?

**Comment by K8Sewell** [comment]
Added BugHerd js and screenshots below confirm it is present on all pages.  Awaiting confirmation on API key management before creating a PR.

### Screenshots:
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/c556a49c-13c4-425c-afc0-ec1e8c8473b7)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/ef365ab5-6698-4a3a-89d3-8b7807d53510)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/2d60faa2-a82f-4cb6-84c6-0f71551e90bc)

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/242 - PR Ready for Review

**Comment by alishaevn** [comment]
I pulled this branch and was able to add a task on the local blacklight app. I went to the bugherd - digital collections kanban board and marked my task (#9) as archived.
