### ISSUE TITLE
Search result walkthrough with Matt Walker

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#454]
**ACCEPTANCE**
- [x] Schedule a hour to walk through the search result page with Matt W. and get any initial feedback
- [x] Work with Matt to write up any tickets for remaining changes and fixes to the index page

**Comment by FCRodriguez7** [comment]
Matt's mockups for the search result page: 

![Screen Shot 2020-08-18 at 2.01.23 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/74eace98-ed27-4122-a1a7-453a436be6e5)



![Screen Shot 2020-08-18 at 2.01.37 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/169f2731-1f8c-4f89-a2e5-b54da150862b)




![Screen Shot 2020-08-18 at 2.01.49 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/fe553161-c88f-4789-9ed5-3663954f711d)

**Comment by FCRodriguez7** [comment]
Matt will document the changes he would like to see on the page by Friday.

**Comment by alishaevn** [comment]
Until that documentation comes, I've created tickets #459, #461, #462, #463, #464, #465 and #466

**Comment by FCRodriguez7** [comment]
I talked to Matt again this morning.  We are on schedule to get his feedback documented on Friday.

**Comment by alishaevn** [comment]
Added #471 to style the search results gallery view.

**Comment by FCRodriguez7** [comment]
As of this morning, August 24,  Matt's working on the feedback for the search result page.   And he'll provide the feedback shortly.
