### ISSUE TITLE
Single item view walkthrough with Matt Walker

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#455]
**ACCEPTANCE**
- [x] Schedule an hour to walk through the single item view page with Matt W. and get any initial feedback
     - [x] Schedule a half hour to walk through the single item view page to talk about design
- [x] Work with Matt to write up any tickets for remaining changes and fixes to the single item view page
     - [x] Schedule another half hour to walk through the tickets for the single item view page design.

**Comment by FCRodriguez7** [comment]
I talked to Matt about designing a single items page.  He asked for examples of design patterns from other institutions.   After a brief chat with Mark, both Matt and I received an email from Mark about the design for the single items page.  

I have another meeting with Matt on Friday to talk about the single items page.

**Comment by FCRodriguez7** [comment]
Sharing the design for those without access to the application: 

![Digital Collections - Item Page.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/946e9428-587e-40ab-9808-54ad24b169f2)
