### ISSUE TITLE
Additional facet styling

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#462]
## Summary
Update the app UI to match Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)

## Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/591ce24b-a054-4810-a3ff-282bfd1ad891)

## Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/90927bd8-63c5-414e-9d3a-127731eb084a)

## Acceptance Criteria
- [x] Line separating the facets should be a lighter grey
- [x] Unselected facets should have a thinner downward facing caret
- [x] Selected facets should have a thinner upward facing caret
- [ ] The number of available facet types should show right next to the type, in parentheses 
- [x] When a type of facet is selected, the type and number should keep the same styling
- [x] The selected facet should also have a right aligned grey box with a white X inside to remove the facet (this replaces the "remove constraint <facet type>" button that appears under the search bar when a type is clicked

**Comment by K8Sewell** [comment]
Would like to potentially recommend using a (font awesome icon)[https://fontawesome.com/icons/times-circle?style=solid] for the 'x' to prevent the break in rendering the image in Safari and to better control sizing of the element. 

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/19dc7771-bcbc-4d9f-a500-c414208fbb1b)

**Comment by DraxIndustries79** [comment]
Per Matt Walker, it's not essential to spend a lot of time trying to replicate the parenthetical numbers if it's difficult.
![Screen Shot 2020-09-02 at 4.50.47 PM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/f9faa2b8-4da5-497c-b6b0-dd119a1f03ee)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/268

### Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d87f4c5f-efc2-4cdb-8aa8-e874d3c8c66b)

**Comment by K8Sewell** [comment]
### Needs Rework
- [ ] display x png icon
- [ ] prevent overflow to next row

### Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/f30eec94-5e73-4792-9bb6-d4273a480f00)

**Comment by K8Sewell** [comment]
Updated - would be helpful to test with more records.  Facet count can be in the thousands and will still not wrap to next line with the PR coming soon.

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/6e3bfee8-11ba-4167-a800-5a628b16af75)

**Comment by K8Sewell** [comment]
PR Ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/279

**Comment by K8Sewell** [comment]
PR to force x png into asset pipeline and prevent it from not being present in production - https://github.com/yalelibrary/yul-dc-blacklight/pull/280

**Comment by mark-dce** [comment]
**ISSUES**
* When I select a facet the facet count formatting breaks across lines ( we should be able to accommodate an arbitrary number of digits left aligned - e.g. (125,000) - the current max is probably 6 digits with comma, but ideally the design could accommodate 7 digits plus commas
* The "X" icon to deselect the facet is not displaying correctly

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/84018b3b-fdce-42eb-a9c8-cf7848820c36)

**Comment by K8Sewell** [comment]
Can we check in on which site we should be checking against?  It looks like the 2 rework PRs are on the v1.17.4 on the yale.library site (screenshot below) but the v1.17.3 on the dce site doesn't have the updated tag deployed to it so would be helpful to check in.

### yale.library
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/d26077a2-0b80-47c2-bb9e-ef5f1a4db191)

### dce
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/dbee6069-6e0c-4ed4-84d5-812f5bb6c9e3)

**Comment by K8Sewell** [comment]
PR to increase facet count limit to 7 digits - https://github.com/yalelibrary/yul-dc-blacklight/pull/295
