### ISSUE TITLE
Style the "searched for" bar

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#463]
## Summary
Update the app UI to match Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)

## Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/4f098a33-dfd7-405b-a059-cd7b8d60df1d)

## Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/2f8cf27d-fa94-4ff2-ae87-e165ef78529c)

## Acceptance Criteria
- [x] "You searched for" is capitalized, in the correct color and correct (or nearest) font
- [ ] The facet or term that was searched on is capitalized, in the correct color and correct (or nearest) font
- [ ] The facet or term that was searched on doesn't have a box around it
- [x]  Hide/remove the button that says "Remove constraint <term>"
- [x] Add a grey box with white X that removes the search item instead
- [x] The "start over" button is right aligned
- [x] The "start over" button is title cased, in the correct color and correct (or nearest) font
- [x] The "start over" button has the correct icon next to it
- [x] There's left and right padding around the entire bar that keeps it from lining up directly with the pagination on the left side or the checkboxes on the right side

**Comment by FCRodriguez7** [comment]
I have reached to Matt about the design for the search bar (field tags) and the missing icon for the "Start Over" text at the end.  The design proposed on the card is different from the one on in Zeplin

![Screen Shot 2020-09-09 at 4.20.52 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5a25da2f-fd60-4a83-99ba-9e67cbcc3e51)

If Matt would like the design in Zeplin, I have code that modifies a partial for the constraints already. I will need to make a few more changes:
![Screen Shot 2020-09-10 at 10.50.49 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d910e703-8a0e-4846-a96e-f22475a764aa)

**Comment by FCRodriguez7** [comment]
I had a meeting with Matt this morning.   He pointed me to the right icon. 


  ![history.svg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/21d8b704-0a19-4a9e-9e69-dfb40c5818cc)
