### ISSUE TITLE
Style the display bar

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#464]
## Summary
Update the app UI to match Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)

## Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/ee166a52-901f-4b1f-8c4b-551fd862426b)

## Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/61af0336-d50b-4607-bb1c-b320f682d172)

## Acceptance Criteria
- [x] "Sort by relevance" is capitalized, in the correct color, size and (nearest) font
- [x] Replace the arrow next to it with a caret in the correct color and size
- [x] "10 per page" is capitalized, in the correct color, size and (nearest) font
- [x] Replace the arrow next to it with a caret in the correct color and size
- [x] THERE IS NO "SELECT ALL" text
- [x] THERE IS NO CHECKBOX
- [x] The entire area with the drop downs, list view and gallery view toggles are right aligned on the page

Updated:
- [x] Remove hover
- [x] Include the gray as in the design over the options as in the attached image
- [x] Arrows need to rotate when open

**Comment by alishaevn** [comment]
This is what happens when you click on one of the sort buttons in the existing app. I assume we want the button to just drop down?
![464.gif](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/44e6a99e-22eb-4e7c-b21f-3d86245a029b)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/260

# Expected Behavior
- All acceptance criteria outlined on the ticket
- Clicking on the "sort by ..." and "... per page" buttons doesn't appear to actually sort. They options also don't drop down, they show on the right of the button. Will address that in a separate ticket
- The sort widget is responsive
- Changes made that weren't mocked up in zeplin:
    - The hover button color is light gray
    - The active button color is dark gray
    - The active list/gallery view color is yale blue

# Demo
![image](https://user-images.githubusercontent.com/29032869/92154905-67019880-eddb-11ea-8846-6f2b993b5408.png)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/293

# Expected behavior
- the "sort by ...", "... per page", "list view" and "gallery view" buttons all have the light grey background since Matt Walker noted that the grey background is to denote that the objects are clickable
- none of the items above change color on hover or when clicked
- when clicking the "sort by ..." or "... per page" drop downs, the text is still horizontal and there is a background color on it. that will be addressed in [ticket 564](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/564)
- the light blue caret is visually rotated when the "sort by ..." or "... per page" drop downs are clicked

# Demo
![464](https://user-images.githubusercontent.com/29032869/93393701-d8a00480-f827-11ea-90e3-f5f7d3467569.gif)

**Comment by dl-maura** [comment]
This works as displayed above on collections-test
![Screen Shot 2020-09-17 at 11.32.51 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/f1f06d58-a6d3-44ff-be59-d2d56909f865)
![Screen Shot 2020-09-17 at 11.32.59 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/edb05721-d252-4b10-a9be-a05ca4d89b58)
![Screen Shot 2020-09-17 at 11.33.07 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/ea1a07df-58a7-46af-90e4-cfaea94dce11)
