### ISSUE TITLE
Style the search results list view

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#465]
## Summary
Update the app UI to match Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)

## Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/d3b78198-e875-4051-b0e5-b15783aa578e)

## Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/9bd5e074-f64b-45ea-8763-69630be533e3)

External example:  https://digital.library.emory.edu/?utf8=%E2%9C%93&search_field=common_fields&q=

## Acceptance Criteria
- [ ] The grey line that separates search results is darker
- [ ] Thumbnails show to the immediate left of the search result number and is top aligned with the number
- [ ] The thumbnail is relegated to 200 x 200 pixel size (Yale Bulldog image is a square example)
- [ ] The result number is in the correct color, size and (nearest) font
- [ ] The title of the result is top aligned with the number and thumbnail, but is to the left of the thumbnail with 71 px of spacing
- [ ] The title of the result is title cased, in the correct color, size and (nearest) font
- [ ] The result details are left aligned with the title and directly underneath the title
- [ ] The name of each detail is title cased, in the correct color, size and (nearest) font
- [ ] The description of each detail is title cased, in the correct color, size and (nearest) font
- [ ] The description of each detail is left aligned to the one(s) above and/or beneath it
- [ ] The description of each detail doesn't extend beyond the checkbox. It can wrap if necessary

**Comment by K8Sewell** [comment]
Fix for overlapping metadata bug - PR ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/274

### Before
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/7a5c8ea9-6a1d-4fee-848b-bc56b60b4cc2)

### After
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4038376e-6186-4c2b-a28a-b7090df38a54)

**Comment by FCRodriguez7** [comment]
The management is broken this morning. 

![Screen Shot 2020-10-06 at 10.24.20 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/548f919d-380d-4498-919d-9f3b41b1c37b) application

**Comment by FCRodriguez7** [comment]
**Mobile**
![mobile.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/427fed88-b85c-4e12-a4bd-e2d622a4abd4)

**Mobile Medium**
![mobileMedium.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8c7ddd29-b691-41e3-9d44-2ef9f1737223)

**Mobile Large**
![mobileLarge.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2bf712fe-0492-4d28-bc92-46c0f2a720d8)

**Desktop**
![Desktop.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3c5f89fc-ce37-4c69-a417-e193b296cc6a)
