### ISSUE TITLE
Style the search results gallery view

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#471]
## Summary
Update the app UI to match the current branding practices in Matt Walker's design: https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f0fd3010b521c8d2c66b758
(View the design at 100% when making comparisons to the blacklight app)

## Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/dd1ac106-62eb-476a-8cf5-87b019d45842)

## Acceptance Criteria
- [x] Each search result title should match the color, size and (nearest) font of the title in the list view design
- [x] There should be 16px of margin between the thumbnail and title
- [x] The parent element to each image should be a 200 x 200 pixel box so that each title in a row is top aligned
- [x]  Each thumbnail is aligned to the top left corner

**Comment by FCRodriguez7** [comment]
I talked with Matt in the evening about designing a gallery view for the project.   At his request, I sent him an image of the current gallery view, see below: 


![Screen Shot 2020-08-25 at 1.51.16 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/60b8bd6d-d99c-49d8-a4ca-981be950508a)

**Comment by FCRodriguez7** [comment]
I have attached Matt's design:


![Screen Shot 2020-08-31 at 3.23.21 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1b0635b3-4f1e-4bc7-8d51-9f991c86f1b9)![Screen Shot 2020-08-31 at 3.23.48 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3e392544-847a-47e2-b26f-591c2d68ba03)![Screen Shot 2020-08-31 at 3.24.07 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d0614cfc-48f2-422f-8205-3cbf24fba8e6)

**Comment by DraxIndustries79** [comment]
Per meeting 9/2/20, sizing matches search result view (this is no different than indicated above).

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/273

# Expected behavior
- the gallery is 1 column wide on screens 320px - 566px wide
- the gallery is 2 columns wide on screens 567px - 1159px wide
- the gallery is 3 columns wide on screens 1200px and larger

# Demo
![471](https://user-images.githubusercontent.com/29032869/92948063-ab112080-f40d-11ea-871f-246c0731ae54.gif)

**Comment by alishaevn** [comment]
Branch:v1.17.3,Deployed:2020-09-15T09:47:00-04:00
