### ISSUE TITLE
Single Item Page: Body Styling

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#477]
### Acceptance Criteria

- [x] Field Name 
     - [x] Color ($medium_grey)
     - [x] Font Size (14px)
     - [x] Font type ($mallory_medium)
     - [x] Font justification
          - [x] left alignment   
          - [x] field words align with the start of the UV box   

- [x] Body Text 
     - [x] Font Color with without links ($medium_grey)
     - [x] Font Color with with links ($light_blue)
     - [x] Font Size (14px)
     - [x] Font type ($mallory_medium) 
     - [x] Font justification
          - [x] left alignment   
          - [x] field words align with the end of the UV box   
              
------
**Current UV Page Design**
![Screen Shot 2020-09-15 at 1.35.49 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9c8dab49-9d2e-4ac4-8d6b-fcb0b7e3c6e1)

**Proposed UV Page Design**
![Screen Shot 2020-08-21 at 2.32.10 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/647ce892-e8a5-4eca-a6b6-b4ef456a7556)

REFER TO UPDATED ZEPLIN:  https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f59b2192f77b936b0d88fe0

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/271

### Screenshot
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/a86d6059-d4cd-4e8f-8c13-f76e6f8817f1)

**Comment by FCRodriguez7** [comment]
[Uploading... Screen Shot 2020-09-15 at 1.35.49 PM.png ]

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/310

# Screenshot of PR
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/142e8499-9212-43ef-9a55-3a42eda74263)

# Screenshot of Zeplin
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/4885fa6e-5844-4c62-b4e9-6926404dd51b)
