### ISSUE TITLE
Add other Solr Field Types

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#479]
I want to be able to search on keywords within these fields from the search bar.  

Current Solr field type: 
1. 'author_tsim', 
2. 'alternativeTitle_ssim'
3. 'subject_topic_tsim'

Proposed Solr field type: 
1. 'author_tesim', 
2. 'alternativeTitle_tesim'
3. 'subject_topic_tesim'

**Comment by DraxIndustries79** [comment]
Author may be there, someone might want to double check the others.

**Comment by maxkadel** [comment]
You can see the current fields being indexed to Solr from the Management application (on master currently) here - https://github.com/yalelibrary/yul-dc-management/blob/master/app/models/concerns/solr_indexable.rb#L26 . 

* alternativeTitle_tesim is already in there
* subjectTopic_tesim is already in there
* author_tesim needs to be added, and author_tsim needs to be deprecated
