### ISSUE TITLE
Yale Cluster Deployment Test

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#482]
**ACCEPTANCE**
- [x] We can deploy a specific version of the blacklight and management applications to the https://collections-uat.library.yale.edu cluster at Yale
- [x] We can deploy a specific version of the blacklight and management applications to the https://collections-demo.library.yale.edu cluster at Yale
- [x] We can deploy a (different) specific version of the blacklight and management applications to the https://collections-test.library.yale.edu cluster at Yale
- [x] The smoke test runs successfully after each deployment
- [x] Each member of DevOps has run the smoke test successfully (a Jenkins job has been created)
    - [x] Keith
    - [x] Bob
    - [x] Rick
- [x] Each member of DevOps has run the deployment process  successfully
    - [x] Keith
    - [x] Bob
    - [x] Rick

**Comment by fnibbit** [comment]
Just to flag this up -- #380 isn't done yet, so "cam env_copy" and friends are not going to give you "We can deploy a (different) specific version of the blacklight and management applications to the https://collections-test.library.yale.edu cluster at Yale" yet -- it'll be a matter of setting BLACKLIGHT_VERSION=, MANAGEMENT_VERSION=, etc. in the deploy command line for the cluster that's using different versions than what was set by cam push_version.

**Comment by bobrice** [comment]
Created a Jenkins build job for deployment to all clusters.

See https://collections-test.library.yale.edu/management for running versions.

**Comment by fnibbit** [comment]
YUL_DC_SERVER=collections-test.library.yale.edu cam smoke
        load  /Users/rkadel/DCE/.cameratarc
         run  rspec /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec  from "."
Current Blacklight basic auth settings:
 username: yul-dc
 password: nocrawl

The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu
  The blacklight site at https://yul-dc:nocrawl@collections-test.library.yale.edu
    loads the home page (FAILED - 1)
    is local or has a valid SSL certificate
    has a public item
      that shows Universal Viewer (FAILED - 2)
    has a yale-only item
      that does not show Universal Viewer
  The manifest service at https://collections-test.library.yale.edu
    provides a manifest for item 2005512
      links to the manifest from blacklight
    provides a manifest for item 16371253:
      has a sequence with nine canvases that links an image to a live URI
  The iiif service at https://collections-test.library.yale.edu
    serves an info.json for image 1030368 that has a width/height ratio between 1.5 and 1.7
  The management index page at https://collections-test.library.yale.edu/management
    has at least six version numbers in the table (FAILED - 3)

Failures:

  1) The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The blacklight site at https://yul-dc:nocrawl@collections-test.library.yale.edu loads the home page
     Failure/Error: expect(page).to have_selector(".document-position-6"), "an open search has at least six items"
       an open search has at least six items
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:57:in `block (3 levels) in <top (required)>'

  2) The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The blacklight site at https://yul-dc:nocrawl@collections-test.library.yale.edu has a public item that shows Universal Viewer
     Failure/Error: expect(page).to have_selector(".universal-viewer-iframe")
       expected to find css ".universal-viewer-iframe" but there were no matches
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:72:in `block (4 levels) in <top (required)>'

  3) The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The management index page at https://collections-test.library.yale.edu/management has at least six version numbers in the table
     Failure/Error: expect(page).to have_content(/v\d+\.\d+\.\d+/)
       expected to find text matching /v\d+\.\d+\.\d+/ in "Camerata n/a yalelibrary/yul-dc-camerata"
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:156:in `block (4 levels) in <top (required)>'
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/capybara-3.33.0/lib/capybara/session.rb:345:in `within'
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/capybara-3.33.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/capybara-3.33.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:155:in `block (3 levels) in <top (required)>'

Finished in 11.57 seconds (files took 1.08 seconds to load)
8 examples, 3 failures

Failed examples:

rspec /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:51 # The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The blacklight site at https://yul-dc:nocrawl@collections-test.library.yale.edu loads the home page
rspec /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:70 # The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The blacklight site at https://yul-dc:nocrawl@collections-test.library.yale.edu has a public item that shows Universal Viewer
rspec /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.4/smoke_spec/deploy_spec.rb:129 # The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The management index page at https://collections-test.library.yale.edu/management has at least six version numbers in the table

**Comment by bobrice** [comment]
Good morning, Rachel.  

We will work on UAT and Demo cluster deployments later today and hold off on running the smoke tests for now.  We tried runningthem against the test cluster yesterday, but they all fail as you've mentioned above.

**Comment by fnibbit** [comment]
Which means that the test cluster deploy also didn't quite work.
