### ISSUE TITLE
Run the smoke test against a persistent cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#486]
**ACCEPTANCE**
- [x] we have scheduled CircleCI (#487) job in yul-dc-camerata that runs the smoke test against a persistent cluster (yul-deploy).
- [x] [BONUS] failures of the job do not impact the main CI status

**Comment by fnibbit** [comment]
Need to tweak smoke test to use environment, not explicitly rely on .secrets.

**Comment by fnibbit** [comment]
Nearly there, but one test is behaving differently locally than on circleci against the same deployed cluster -- on circle the SSL test fails against any of curationexperts clusters (but not against example.com!).  https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-camerata/571/workflows/d4d6c08d-96df-4249-97d5-41a5c8c67c0a/jobs/616

**Comment by fnibbit** [comment]
next sub-goal: get current SSL certificate bundle in to CI environment.
