### ISSUE TITLE
SPIKE: run a scheduled job in CircleCI

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#487]
**ACCEPTANCE**
Do a time-boxed experiment to
- [ ] Run the camerata CI job (or even just rubocop) at a specified time (in addition to being triggered on new commits) [what we run isn't as important as the being able to schedule part]

NOTE: if we can't solve this in the defined time box, we may want to look at other ways to trigger this from Github, Dockerhub, or AWS instead of scheduling via CircleCI.

**Comment by fnibbit** [comment]
https://circleci.com/docs/2.0/workflows/  "triggers"

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/b7ef2d87-747e-44c9-b94d-308456639364)
