### ISSUE TITLE
Run cam deploy against the deployment cluster on a schedule

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#488]
**ACCEPTANCE**
- [ ] We can run something like `cam deploy-main yul-deploy` on a recurring schedule via CircleCI

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/2fa7eade-d0a8-4663-b00b-1e78856d43db)  https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-camerata?branch=deploy-from-circle
