### ISSUE TITLE
SPIKE: Identify mechanism to host web assets like MalloryMP fonts

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#490]
**ISSUE**
We have decided not to commit web resources like fonts into the application repository, so any that we wish to access for the design need to be hosted on some other publicly accessible system.  Right now this applies especially to MalloryMP fonts.

**ACCEPTANCE**
- [x] Create an inventory of any web assets described in the site designs that are not currently available from an existing Yale web host
- [x] Investigate options to host those additional assets
- [x] Make a recommendation and/or write up tickets needed to provide access to the necessary assets

**Comment by dl-maura** [comment]
Host the fonts on static server, need to check on licensing

**Comment by dl-maura** [comment]
Font List:

- YaleNew-Roman (listed as YaleDisplay-Roman in the design, but appear to be the same font)
- YaleNew-Italic
- Mallory-Light
- Mallory-LightItalic
- Mallory-Medium
- MalloryMP-Medium
- MalloryMP-Black
- Mallory-Book
