### ISSUE TITLE
Implement DRAFT Internal Preview Homepage

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#491]
**ACCEPTANCE**
- [ ] The application homepage has welcome content similar to the text below (feel free to wordsmith for clarity and brevity)

**DRAFT WELCOME TEXT**
>Welcome!
>Welcome to the Yale University Digital Collections internal preview site
>*  The initial preview includes approximately 500 items from across the Beinecke's digital holdings
>* Over the duration of the initial phase, the content will grow to represent over 125,000 items representing the Beinecke Libaries digital holdings
>* In addition, the site will include one additional collection from YULs diverse holdings at the initial public launch
>* Future phases will incorporate additonal content from across YUL's digital holdings</li>
>
>**Plese feel free to explore the site and share your feedback with us**
>The preview is designed to give a fully functional preview of browse, search, and view capabilities as we migrate content from the legacy site.  Here's a few things you can do:
>* Search for content by Title, Keyword, and Author using the search bar above
>* Browse content using the "Limit Your Search" facets at the left of the screen
>* Pan, Zoom, and page through materials by clicking through to item-level show pages
>
>**Giving Feedback**
>We're using a tool called BugHerd to give stakeholders an easy way to give us clear and precise feedback about your experiences
>1. Search, browse, and use the site as you normally would</li>
>1. When you see something you'd like to give us feedback about, click the "&lt;BH" icon at the right side of your screen
>1. Click the green plus button on the BugHerd toolbar
>1. Click on the item or part of the screen you have feedback about
>1. Type a short description of your feedback in the "Task Details" box
>1. Click on the "Create Task" button to send us your feedback

**MOCK-UP**
(please feel free to tighten up the layout and improve the design)
![image](https://user-images.githubusercontent.com/3064318/91198251-f0211d00-e6c1-11ea-956a-e9ce936c399e.png)

**Comment by K8Sewell** [comment]
BugHerd does not capture the user's browser information as far as I could see.  When the instructions for using BugHerd are added they should include the request to add browser information to the feedback comment.

**Comment by mark-dce** [comment]
PR: **Update the welcome message on the homepage** [#257](https://github.com/yalelibrary/yul-dc-blacklight/pull/257)

The PR has the exact text from the ticket description, we're working on some minor tweaks and will include BugHerd anti-tracking info in the revised text.
