### ISSUE TITLE
Management App: Exception Handling when no import file is selected

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#493]
**ACCEPTANCE**
- [x] I should get a warning rather than an exception when I try to run an import with no CSV selected.

![Aug-25-2020 12-52-06.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/31949392-f1ed-4e62-916f-9c57ded774b8)

**Comment by mark-dce** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/3064318/91742415-dd07c480-eb7b-11ea-9ec0-bd10bb73ba31.png">
