### ISSUE TITLE
SPIKE: Mount Access Masters to Yale Clusters (NFS FARGATE)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#501]
**ISSUE**
In order to create PTIFFs for universal viewer, we need a way to access the Storage@Yale shares that have the original access masters saved on them. We need to see if we can do this with FARGATE/NFS

**ACCETPANCE**
- [ ] We can read access masters stored on Storage@Yale from the management app in any ECS cluster 
    - [ ] the 'management' container on each Yale cluster can read access master TIFFs from the NFS mount
    - [ ] any instances of the `management worker` container can read TIFFs from the NFS mount

NOTE: the mounts can probably be read-only if that's helpful

Answer: We need to do this WITHOUT Fargate. Need to make a new ticket for new path forward

**Comment by bobrice** [comment]
We have requested a firewall change to accommodate this connection to storage. 

@kbcarter has begun the investigation to mount the NFS volumes to the test cluster.

**Comment by dl-maura** [comment]
Request is in for subnet accessibility

**Comment by kbcarter** [comment]
Mounting external volumes using DockerVolumes is not supported when using FARGATE clusters.
