### ISSUE TITLE
Acquire Credentials for Cross Browser Testing

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#503]
# Summary
In order to implement cross browser testing licensing, credentials, and permissions need set up.

# Acceptance Criteria
- [x] Acquire license for [Browserstack](https://www.browserstack.com/) for Yale Digital Collections
- [ ] Share auth credentials with performance team member who can add the credentials to the AWS parameter store
- [ ] Update blacklight repo with appropriate environment variables

**Comment by mikeapp** [comment]
Browserstack has a number of products and plans, with additional costs per parallel test, and it looks like it can add up quickly.   We should decide on what we need prior to signing up.

**Comment by mikeapp** [comment]
Account created and invites sent to @mark-dce @bess @alishaevn @K8Sewell  @FCRodriguez7 @edejesusyale

**Comment by alishaevn** [comment]
Created my account!

**Comment by mikeapp** [comment]
For the second acceptance criterion, additional invites sent to @fnibbit @mlooney @JzGo @orangewolf  + Yale DevOps
There's an "Access Key" option just below the top menu bar.

**Comment by mark-dce** [comment]
How will the performance team be able to demonstrate this work is complete?  Is there some kind of front-end test that then gets run once credentials are in place?
