### ISSUE TITLE
SPIKE: set IIIF_MANIFESTS_BASE_URL and IIIF_IMAGE_BASE_URL on deployed environments to specific hostnames

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#505]
Current deployed manifest services use "$$host" to dynamically set the hostnames for IIIF image and manifest urls -- let the manifest service know where it and its buddy are rather than guessing from where they were found.
https://github.com/yalelibrary/yul-dc-camerata/blob/master/templates/iiif-manifest-compose.ecs.yml
```
     IIIF_MANIFESTS_BASE_URL: 'https://$$host/manifests/'
     IIIF_IMAGE_BASE_URL: 'https://$$host/iiif'
```
makes the iiif manifest server show both the manifest url and the image url as whatever hostname they were reached at -- different from eventual desired behavior where the iiif image and manifest services are at consistent known hostnames.

- [ ] These should always use `https` (*not* http) in any production-like system

**Comment by dl-maura** [comment]
Jez will speak with Max
