### ISSUE TITLE
Make an S3 bucket for each cluster

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#510]
**ACCEPTANCE**
- [x] Change the Camerata "creating a new cluster" code to include creating an S3 bucket
- [x] Configure the required s3 bucket(s) for any existing clusters that we are not building from scratch
- [ ] Rebuild at least one regularly used cluster to ensure automatic bucket creation is working as expected

**NOTE**
- This is required due to the decision that IIIF Manifests need to be saved with static urls, necessitating them to be saved on a per-cluster basis.

**Comment by fnibbit** [comment]
Notes/breadcrumbs: Currently the bucket YUL_DC_SAMPLES is serving this purpose across all three yale clusters, and is pointed to by the parameter store variable SAMPLE_BUCKET.  When this ticket is done, the parameter store variables /yul-dc-uat/SAMPLE_BUCKET and /yul-dc-test/SAMPLE_BUCKET should each point to different places.

**Comment by kbcarter** [comment]
Created two new S3 buckets for UAT and Demo: yul-dc-uat-samples and yul-dc-demo-samples

**Comment by fnibbit** [comment]
I'm working on the changes to the cluster creation scripts and building this out at DCE; creating yul-dc-test-samples still needs to be done.
