### ISSUE TITLE
Host the needed fonts at a static location

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#512]
Now that we've identified a path forward, we need to host the fonts used for the project on a static server for access by the project. The following fonts will need to be hosted:

- YaleNew-Roman (listed as YaleDisplay-Roman in the design, but appear to be the same font)
- YaleNew-Italic
- Mallory-Light
- Mallory-LightItalic
- Mallory-Medium
- MalloryMP-Medium
- MalloryMP-Black
- Mallory-Book

**Comment by mikeapp** [comment]
Emailed Matt to ask about procedure for getting the fonts.

**Comment by mikeapp** [comment]
Discussed using S3/SpinUp for hosting.  We will likely do this, but would like to manage assets in Github and push to S3 via Jenkins.

**Comment by FCRodriguez7** [comment]
The Yale Roman fonts appear to be public-facing:  https://yaleidentity.yale.edu/typefaces.

**Comment by mikeapp** [comment]
I have created a private repo with the fonts and updated the internal ticket with info for DevOps.

The YaleDisplay font seems to be for desktops, I've added the YaleNew *.otf fonts to the repo.

**Comment by ra359** [comment]
Is this path ok? http://static-test.yalepages.org/mallory/Mallory-Light.woff

Or do we need the "fonts" dir in there?
