### ISSUE TITLE
Teach out accessibility resources

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#514]
# Summary
Additional resources (shared from Kara Franco) regarding accessibility to be reviewed by team members.

# Acceptance Criteria
Following team members have reviewed the additional resources:
- [ ] Eric
- [ ] Frederick
- [ ] Lakeisha
- [x] Maggie
- [ ] Martin
- [ ] Alisha
- [ ] JP
- [ ] Mark
- [ ] Maura
- [ ] Mike
- [ ] Rebecca

# Additional Resources
### Videos
[A11yCasts (series of YouTube videos about accessibility from Google)](https://www.youtube.com/watch?v=HtTyRajRuyY)
[W3C Intro to Accessibility edX (Free)](https://www.edx.org/course/web-accessibility-introduction)

### Guides and Standards
[WCAG Overview](https://www.w3.org/WAI/standards-guidelines/wcag/)
[ARIA Overview](https://www.w3.org/WAI/standards-guidelines/aria/)
[W3C WAI Tutorials](https://www.w3.org/WAI/tutorials/)

### Testing
[Screen reader testing Q&A](https://webaim.org/articles/screenreader_testing/)
[Keyboard Testing Basics](https://webaim.org/techniques/keyboard/)

### Resources to follow
[Digita11y- The Great Accessible Blog Round up (list of influential bloggers)](https://www.digitala11y.com/accessibility-blogs/)
[A11yWeekly (newsletter that sends links to great info)](https://a11yweekly.com/)
[MicroAssist Accessibility Newsletter (more legal focused, less dev focus- but a great resource for keeping up with disability rights!)](hhttps://www.microassist.com/digital-access/news/)

**Comment by mark-dce** [comment]
I've added the links to the wiki here:
https://github.com/yalelibrary/yul-dc-documentation/wiki/Accessibility-Resources
