### ISSUE TITLE
Add advanced search capabilities to the discovery application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#516]
**STORY**
When I'm trying to find a specific type of work, I would like to be able to target specific search fields with greater granularity, so that I can more quickly find items that meet my research needs.

**ACCEPTANCE**
- [x] Add blacklight advanced search capabilities to the application https://github.com/projectblacklight/blacklight_advanced_search
- [x] Configure all fields to be searchable in advanced search - even if they aren't included in the "All Fields" default - see https://github.com/projectblacklight/blacklight_advanced_search 

**EXAMPLE CODE**
https://github.com/emory-libraries/dlp-lux/pull/214 (note that there has been a Blacklight 7.x compatible release since this code)

**Comment by FCRodriguez7** [comment]
We configured advanced search: 

![AdvancedSearchOID.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/6acbb03a-7b9d-4749-892b-5bf1b32fd9c3)

**Comment by FCRodriguez7** [comment]
The next step is to write test.

**Comment by FCRodriguez7** [comment]
I also sent Matt the out of box layout for the [Advanced Search](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/533).

**Comment by FCRodriguez7** [comment]
We need some clarification on "Configure all fields to be searchable in advanced search - even if they aren't included in the "All Fields" default - see https://github.com/projectblacklight/blacklight_advanced_search."  

What do you mean by all fields?  
- Is it all solr fields?  If this is the case,  could you provide the fields to us?    
- or simple woiuld you like 'all fields' in the current search?  (This are the current fields in the all field:  ```
'abstract_tesim', 
'author_tesim', 
'alternativeTitle_tesim',
 'description_tesim',
 'subjectGeographic_tesim', 
'identifierShelfMark_tesim', 
'orbisBibId_ssi', 
'publicatonPlace_tesim', 
'publisher_tesim',
'resourceType_tesim', 
'sourceCreated_tesim', 
'subjectName_tesim',
 'subject_topic_tesim',
'title_tesim' ``` )

**Comment by FCRodriguez7** [comment]
Additionally,  Matt reached back out with the [new design.](https://zpl.io/25Wdrjn)  We can start making the ticket(s) for the new advanced search page. 

-----

![Screen Shot 2020-09-08 at 8.38.36 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/35fcee05-857e-4916-a25f-4f7a3a65f7ad)
