### ISSUE TITLE
Add Search by Call Number (Identifier Shelf Marker)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#517]
Specifically in main search box.

**ACCEPTANCE**
- [x] I have a drop-down option to search by "Call Number"
- [x] The search performs an exact match, non-tokenized search on the string I enter - i.e. searching for "

**Comment by FCRodriguez7** [comment]
Duplicate ticket: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/518
