### ISSUE TITLE
Add search by "Call Number" (Identifier Shelf Mark)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#518]
**ACCEPTANCE**
- [x] I can choose "Call Number" as the target for my search
- [x] Call number searches produce an exact match on the prefix/first part of call number

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/32e3261b-6bc9-4fe2-8afe-4456e0c39cd8)

**Comment by DraxIndustries79** [comment]
Call Number should be a dropdown in the Primary Search

**Comment by FCRodriguez7** [comment]
[Uploading... CallNumberFeature.gif ]

**Comment by FCRodriguez7** [comment]
There was another ticket out: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/517

This ticket has the work done.

**Comment by dl-maura** [comment]
Demo'd this with Rebecca, Mark, and Mike. Call Number is present and returns search results
![Screen Shot 2020-09-16 at 6.20.21 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6d3e1a6b-26e5-4f73-8199-2d1dc87b509f)
![Screen Shot 2020-09-16 at 6.20.34 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/b10ad2d9-515c-4631-9c33-c13ddcfefda5)
![Screen Shot 2020-09-16 at 6.20.46 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/50f775ba-e280-44b4-a24f-9be8cdf87ef4)
