### ISSUE TITLE
camerata release PR should use a different branch name each time

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#522]
At the end of the `cam release camerata` process we auto-create a PR to increment the camerata version number. However, if there is still a branch sticking around with the same name as the branch we're trying to push, it won't work correctly.

- [ ] Each auto-released version of camerata should use a different branch name for the auto-increment PR

**Comment by fnibbit** [comment]
The auto-created pull request code has been disabled -- instead "cam release camerata" gives a reminder to increment the version number in the version file.
