### ISSUE TITLE
Automated update of version number within camerata repo fails when running "cam release camerata"

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#523]
The cam release  command attempts to create a pull request for an update to the version.rb file, but it fails when running from an installed copy of the cam gem with this error: `fatal: /Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.2/lib/camerata/version.rb: '/Users/rkadel/.rvm/gems/ruby-2.6.6@yul-dc/gems/camerata-2.5.2/lib/camerata/version.rb' is outside repository`

**Comment by bess** [comment]
I've removed this feature for now, since it wasn't working. When you do `cam release camerata` now it just prints something to the screen saying you should also go update the version.rb file.

**Comment by DraxIndustries79** [comment]
This may be closeable but will check with Software Eng team.
