### ISSUE TITLE
Spike: Trigger a deploy using the terraform code from the cam gem

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#524]
Given that the switch to terraform is a significant departure from our existing cluster-building and deploy process, let's investigate how much work it's going to be to rewrite our user interface to the deploy process.

Hoped-for outcomes: we hope that we could use a command like "cam deploy-something yul-test" to trigger a deployment of at least one microservice using the terraform infrastructure.

**Comment by mark-dce** [comment]
It seems like our Bash-based build and deployment are working effectively right now and there's not enough value to pursue Terraform in this phase.  We'll open a new ticket if new reasons to make the change surface in a new phase.
