### ISSUE TITLE
Single Item Pagination Change  

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#530]
According to our conversation with Matt the change pagination design should look like:

![Single Items Pagination.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b4c780d7-d3a7-4a0a-835e-3a44384f7fe8)

- [ ] Pagination functionality needs to be restored

**Comment by FCRodriguez7** [comment]
The pagination on the search result page is correct on the Zeplin design.

**Comment by dl-maura** [comment]
As some extra information, if you resize your window (to like mobile size) the buttons work!
![Screen Shot 2020-09-16 at 3.50.16 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/5f0f0d9e-e459-4ca5-a3ce-417cafd761b2)
