### ISSUE TITLE
Search Results Page: Reformat Bottom Pagination

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#531]
Bottom pagination nav on search results page needs more tweaking to match Matt Walker's design (based on feedback from 9/2/20 meeting).  Assumes that over 10 pages it uses Blacklight ellipses.

**ACCEPTANCE**
A few revised requirements differ from the Zeplin mock-up below.
- [x] Move 'Next' and '>>' to right of numbers, so that the numbers are between 'Previous' and 'Next'
- [x] Separate the double arrows ('<<' and '>>') from the words ('Previous,' 'Next') so that they are individually clickable and function independently
- [x] Make 'Previous' and 'Next' go one page in each direction
- [x] Make '<<' and '>>' functional to jump to end or beginning of results (first and last page)

*Current Demo Site*
![Screen Shot 2020-09-02 at 6.40.55 PM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/a65bc72c-0b50-4e9a-9d5d-12a8a4a4d059)
*Original Mock-up* (Note changes above):
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/07dfbc3b-09a2-4544-b226-eb375a49b53a)

Related to:  https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/387

Reference: ![Screen Shot 2020-09-08 at 10.26.16 AM.png](https://images.zenhubusercontent.com/5e5d4b9fe308104eddc52c88/3f3187c4-2208-4dac-bb17-c765ed9479d3)

**Comment by K8Sewell** [comment]
Putting ticket back down until can find a solution to having more records to work with.  
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/83d68522-6e26-4c02-a3c2-cd758db88be5)

**Comment by K8Sewell** [comment]
Present implementation of elipses

**Comment by K8Sewell** [comment]
In the present blacklight default the last page and first page are visible at all times so if acceptable we could leave this implementation and not have to rewrite part of the kaminari gem that is producing the bottom pagination. 

<iframe src="https://share.getcloudapp.com/Jru6Yre2?branding=true&amp;embed=true&amp;title=true" width="575" height="400" style="border:none" frameborder="0" allowtransparency="true" allowfullscreen="true"></iframe>

PR for above implementation - ready for review - https://github.com/yalelibrary/yul-dc-blacklight/pull/270

**Comment by K8Sewell** [comment]
# Needs Reworkc- [x] remove double arrows by Previous and Next - screenshot in details
<details>
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/85d800b6-b822-4c4f-9588-c346486bdfd1)
</details>
- [ ] add go to last and first double arrow links in pagination

WIP PR -  https://github.com/yalelibrary/yul-dc-blacklight/pull/282

**Comment by dl-maura** [comment]
All functional on Safari on collections-test -- demo'd with Mark, Rebecca, and Mike today.
![Screen Shot 2020-09-16 at 6.17.09 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/0c454b49-d6bf-44a2-aabd-76734f291ed5)
