### ISSUE TITLE
Advanced Search Body Styling

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#533]
I send Matt the current out of box layoff for the Advanced Search page.   

![Screen Shot 2020-09-03 at 4.44.55 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/905fd4a6-f09e-45a3-9ab7-ee91f4c44c71)

**Comment by mark-dce** [comment]
Matt reached back out with the [new design.](https://zpl.io/25Wdrjn)  We can start making the ticket(s) for the new advanced search page. 

-----

![Screen Shot 2020-09-08 at 8.38.36 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/35fcee05-857e-4916-a25f-4f7a3a65f7ad)

**Comment by alishaevn** [comment]
Created #561, #562 and #563 to complete this work.

**Comment by alishaevn** [comment]
Frederick also created #569 for this ticket

**Comment by mark-dce** [comment]
We're not showing all the fields - is this covered in another ticket?

**Comment by mark-dce** [comment]
What does "Start Over" do or mean?  Is this "Back to Basic Search" (or just "Basic Search")?

**Comment by alishaevn** [comment]
On the advanced search page, the "start over" resets all of the input boxes to be empty
