### ISSUE TITLE
Update the welcome text

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#538]
**ISSUE**
We've done some slight word-smithing and clarification for the preview homepage, so we need to update the text.

**ACCEPTANCE**
- [x] Update the text to match the version here https://docs.google.com/document/d/1TgI5wqDDHO61eUOUvRUM1WW2EOrnHNN-YdVlGR1qRFk/edit

- [x] In Giving Back, #2, include the Bugherd icon at the end of the line.

**Comment by FCRodriguez7** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/266

**Comment by dl-maura** [comment]
![Screen Shot 2020-09-15 at 1.45.45 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/1bd62502-24ef-4a12-a87d-683ada367c42)

**Comment by FCRodriguez7** [comment]
The text was modified to: 

![Screen Shot 2020-09-15 at 3.34.20 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7c7b1420-8aa3-4093-a80b-d1d97fa2c977)

**Comment by FCRodriguez7** [comment]
The image is broken in the latest release. I am working on it.

**Comment by mark-dce** [comment]
Item two in the "Giving Feedback" section should read
* When you see something you'd like to give us feedback about, click the ![BugHerd](https://github.com/yalelibrary/yul-dc-blacklight/blob/master/app/assets/images/bugherd.png?raw=true) **icon at the right of your screen*
