### ISSUE TITLE
Create CSV for 500 item ingest

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#539]
**ACCEPTANCE**
- [x] Create an updated CSV that can be used to ingest the 500 sample items
- [x] Successfully run the ingest on at least one cluster ( https://collections-test.library.yale.edu )
- [ ] [BONUS] run the ingest on all Yale and DCE clusters

NOTE: At this point, we expect the following
* Items may not have corresponding manifests
* Manifests may point at currently non-accessible PTIFFs

**Comment by maxkadel** [comment]
* Failed jobs are not accumulating as I would expect. May need to explicitly set a `last_error` message on jobs?
```
Failed Jobs
The list below contains all jobs that have a last_error message set.
```

**Comment by maxkadel** [comment]
Successfully ran on https://collections-test.library.yale.edu/management/parent_objects, had to re-run ~100 parent oids, which, on running "Update Metadata", successfully got data from the MetadataCloud.

**Comment by maxkadel** [comment]
running on https://collections-test.curationexperts.com/ and https://collections-demo.curationexperts.com/ as well

**Comment by maxkadel** [comment]
Started ingest on https://collections-uat.library.yale.edu/management/parent_objects @ 8:17 am eastern, not babysitting.
