### ISSUE TITLE
Identify access master OIDs required for Internal Preview

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#540]
**ISSUE**
If we can't find a means to directly connect to the access masters, we'll need to copy them somewhere that we can get to from ECS.  So, as a start, we'll need a list of what needs to be copied.

**ACCEPTANCE**
- [x] We have a list (and count) of all the child OIDs associated with our initial 500 item sample

**Comment by maxkadel** [comment]
Child oids csv -  https://drive.google.com/file/d/11zWnGZP9kdaeoIQEsrm_fGT96dlsIJuy/view?usp=sharing
