### ISSUE TITLE
Publication Date Slider does not return results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#549]
**STEPS TO REPRODUCE**
1. Go to any system running v.1.15.1 (e.g. https://collections-test.library.yale.edu/?search_field=all_fields&q= )
2. Click on search (search for all items)
3. Expand the "Publication Date" facet
4. *Use the mouse* to slide the upper date limit about 1/4 of the way earlier (i.e. from around 2020 --> 1775)
5. Click on "Apply"

**EXPECTED RESULT**
- [x] I should get some subset of the previous results
- [x] I should have a facet limit for the years that I can click to remove

**ACTUAL RESULT**
- [x] I get no results found
- [x] There is no facet constraint shown

**STEP 3**
<img width="315" alt="image" src="https://user-images.githubusercontent.com/3064318/92637118-0e7c4080-f29e-11ea-9545-314f7a82d2b1.png">

**STEP 4**
<img width="311" alt="image" src="https://user-images.githubusercontent.com/3064318/92637275-3d92b200-f29e-11ea-9fb2-eedea859002a.png">

**ACTUAL RESULT**
<img width="758" alt="image" src="https://user-images.githubusercontent.com/3064318/92637372-5d29da80-f29e-11ea-9a5f-d73fb5944388.png">

**EXPECTED RESULT**
Something similar to this
<img width="234" alt="image" src="https://user-images.githubusercontent.com/3064318/92637520-8cd8e280-f29e-11ea-9c91-a7785a3d81a6.png">

**Comment by DraxIndustries79** [comment]
Was this released?  I'm not seeing this functional in collections-test or collections-demo

**Comment by DraxIndustries79** [comment]
Confirmed not working as slider or as typed-in dates.

**Comment by FCRodriguez7** [comment]
Could be a bug from the gem?
 https://github.com/sul-dlss/exhibits/pull/1646

I am looking into the bug some more.

**Comment by K8Sewell** [comment]
Bug from gem (ordering of 'includes') was remedied and fix was introduced.  Fix works in local development but when pushed to production no longer works.  Potential issue from non normalized dates but further investigation is needed.

**Comment by alishaevn** [comment]
currently on localhost `Branch:v1.23.1,Deployed:2020-08-04T13:50:46-04:00`

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/f9575dc0-07a1-4a06-9383-56e8d02384e0)

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/330

**Comment by dl-maura** [comment]
Looking into making year into integer instead of date

**Comment by martinlovell** [comment]
Metadata cloud test and UAT should both be returning arrays of integer years in dateStructured.  The array contains all years in the range.

**Comment by martinlovell** [comment]
See: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/833

**Comment by mark-dce** [comment]
replaced by #877
