### ISSUE TITLE
Add a "Hello World" Rails App to an existing cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#55]
**ACCEPTANCE**
- [ ] We have a helm chart that deploys a vanilla rails app (splash screen from `rails new`) to an existing cluster

**Comment by kcompsci** [comment]
This is Lakeisha and I'm assigning myself this task. Please let me know the best time to connect to discuss this. Thanks!

**Comment by geekscruff** [comment]
Let's take this one step further and build a vanilla Blacklight app.

BONUS ACCEPTANCE CRITERIA

- [ ] we have a set of helm charts to deploy a blacklight / solr / database combo

**Comment by alishaevn** [comment]
https://github.com/projectblacklight/blacklight/wiki/README_SOLR

**Comment by kcompsci** [comment]
We created a repo within notch8 and got rails up and running.
