### ISSUE TITLE
Post 9/14 Demo - move iiif manifest service to port 3002 (not port 80)

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#552]
## Why?
- Security, best practices

## What?
This may require the following

- [ ] Changing the the existing IIIF Manifest application to run on port 3002, rather than port 80 
  - DEV HINT: Search in the management application for `3001` and create parallel changes in the iiif manifest app
- [ ] Changing the Camerata build scripts for new clusters to expect the port for this application to be 3002 (again, similar to management)
- [ ] Tear down the existing clusters, since we can't edit the ports on the load balancers once they've been built, and re-build them with the new ports.

**Comment by dl-maura** [comment]
@orangewolf @maxkadel Is there still a need for this ticket?
