### ISSUE TITLE
Refactor database creation to match iiif_manifest pattern

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#554]
Instead of maintaining a list of databases that are needed for our cluster to run, better to allow each application to create their own. See for reference, this section of the `iiif_manifest` service in `camerata/templates/iiif-manifest-compose.ecs.yml`

```
    # This is a workaround to create the needed database for iiif_manifest on an existing cluster.
    # We are pre-pending the database creation command to the passenger start command that it otherwise
    # inherits from the base docker image. 
    command: bash -c "bundle exec rake db:create && /sbin/my_init"
```

**Comment by DraxIndustries79** [comment]
Manifest service has been moved into Blacklight.  n/a
