### ISSUE TITLE
Grant team members access to Yale AWS 

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#555]
**ACCEPTANCE**
- Grant the following individuals access

- [x] Jez 
- [x] Rob K
- [x] Dylan
- [x] Mike A
- [x] Frederick
- [x] Eric
- [x] Martin
- [ ] Other software engineering (Maggie, Yue, Lakeisha, Kalee)
- [x] Rachel K
- [x] McClain
- [x] Max K
- Grant access to 
- [x] Cloudwatch logs (all, read-only)
- [x] S3 access master, ptiff, & manifest buckets
- [x] ECS clusters

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-camerata/tree/master/iam_policies These policies might be useful to work from: the "deploy-only-policy.json" grants enough access to deploy to and inspect DCE clusters, and the "test-deploy-only-policy.json" grants enough access to deploy to and inspect one specific cluster on the DCE infrastructure.  https://github.com/yalelibrary/yul-dc-camerata/commit/be75606a96839c0e9558aed525a39284b3994198

**Comment by dl-maura** [comment]
Get netid list

**Comment by fnibbit** [comment]
Looks good in terms of inspectability -- I can look at most of the things I would want to through the AWS console, with the exception of Systems Manager parameter store, and I can use cam env_get to look at individual parameter store values.   I think this version of the IAM policy is ready to roll out to the rest of the team members listed in the ticket.
