### ISSUE TITLE
Update No Image Available badge

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#559]
- [x] Replace the 'no-image' thumbnail with the no-image graphic from zeplin
- [x] Replace the 'vpn-only' thumbnail with the no-image graphic from zeplin

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-09-11 at 2.13.40 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7ee08fd7-4f4a-4089-81c5-3f0af95f69c1)

**Comment by FCRodriguez7** [comment]
**VPN IMAGE**

![Screen Shot 2020-09-11 at 2.24.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7c290a9e-07de-4285-b527-f6a519e29b54)
