### ISSUE TITLE
Bug: Digital Collections row styling

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#560]
# Summary
There are a few styling changes that still need to be made to resemble the zeplin design

# Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/a6f74391-8710-4f39-896e-e604764c746c)

# Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/f760c09b-1ebd-4bbf-925e-f83a1d6a74ce)

# Acceptance Criteria
- More spacing between the bar underneath the Digital Collections row and the "Limit your search" text
- The bar underneath the Digital Collections row doesn't right align with the other content on the page. It should extend to the right edge of the gallery view box, links in the header/footer, etc.

**Comment by mark-dce** [comment]
The NetID and logout in the "Digital Collections" row are redundant to the ones in the topmost header.  They should be removed from the design and the application.

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3d696c53-e6e3-4853-9ce5-1a4121251809)

**Comment by alishaevn** [comment]
# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/560

# Expected behavior
- Additional spacing between the bar underneath the Digital Collections row and the "Limit your search" text
- Additional spacing between the Digital Collections text and the search bar above it
- The grey line underneath the Digital Collections row right aligns with the gallery view box beneath it
- The icons for the user net id and log out options on the Digital Collections row have been commented out

# Demo
![560](https://user-images.githubusercontent.com/29032869/94067699-1d391c00-fda3-11ea-8248-74219d8e497e.gif)
