### ISSUE TITLE
Style the Advanced Search - header

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#561]
# Summary
Updated the Advanced Search page to reflect the design [in zeplin](https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f5707bfd9b7b87a960b8314)

# Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/4bc9ad16-0be4-4c64-8ce6-0ca8b9555abd)

# Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/b74186ea-c119-4cdd-89bf-18d555d7ec5b)

# Acceptance Criteria
- [x] remove the Basic Search bar
- [x] replace "Digital Collections" with "Advanced Search"
- [x] the "find items..." section is aligned with the "Advanced Search" text
- [x] the button to clear the form says "Clear Search" instead of "Start Over"
- [x] the "Clear Search" button is styled correctly and in line with the "Advanced Search" text
- [x] the "sort by" dropdown that's on a regular search page, needs to also be on this page
- [x] the "sort by" dropdown needs to say "sort results by" and not just "sort by"
- [x] all text in the header have the proper color, font, sizes and capitalized
- [x] proper spacing between each of the items in the row, and between the row and the elements above/beneath it
- [x] remove the default hover and active state css changes on all drop downs and buttons in this section

**Comment by mark-dce** [comment]
I've updated the acceptance criteria to reliable the "Clear Search" button.  We use the wording "Start Over" elsewhere to return to the homepage - we should not use the same wording for different behaviors in different parts of the application.

**Comment by DraxIndustries79** [comment]
This is pending decision about the Start Over/Clear/Basic Search button placement

**Comment by FCRodriguez7** [comment]
I have some failing test still.  

![Screen Shot 2020-09-23 at 11.53.10 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1bad3093-e42b-4df4-aef0-7a8832bcc7be)

**Comment by FCRodriguez7** [comment]
I need to coordinate with Keith for deployment.

**Comment by FCRodriguez7** [comment]
My communication with Matt before the meeting.  

![Screen Shot 2020-09-30 at 10.45.49 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/887b3350-7ac4-4956-893c-86687ba7291f)

**Comment by FCRodriguez7** [comment]
During the meeting, Matt requested full screenshots for different resolutions.   I sent the following images: 

**Mobile**
![Mobile.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f1832888-be1a-47af-9efd-e4a81485c57b)


**Large Mobile** 
![LargeMobile.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d9e19bc3-1ff6-4899-9903-5080638efef3)

**Comment by DraxIndustries79** [comment]
Updates from Matt eta 10/1
