### ISSUE TITLE
Style the Advanced Search - footer

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#562]
# Summary
Updated the Advanced Search page to reflect the design [in zeplin](https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f5707bfd9b7b87a960b8314)

# Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/aeb72f2b-56dc-4b46-8ee9-1554e5ae96f7)

# Intended UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/b92f6103-562e-4bee-8903-f0e480309f10)

# Acceptance Criteria
- [x] all text in the ~"start over"~ "clear search" button has the proper color, font, size and capitalized
- [x] all text in the "search" button has the proper color, font, size and capitalized
- [x] the borders of both buttons have the proper color and size
- [x] remove the default hover and active state css changes on all drop downs and buttons in this section
- [x] from left to right the buttons are ordered "Search", "Clear", and a "Basic Search" link
- [x] proper spacing between each of the buttons, and between the row and the elements above/beneath it

**Comment by mark-dce** [comment]
The button to clear the form should be labelled "Clear Search" instead of "Start Over" since we use "Start Over" to link to different behavior elsewhere in the application.

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/318

**Comment by K8Sewell** [comment]
PR updated with comments -
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/e212532c-0d6e-4800-ac08-df5beb0346c4)

**Comment by FCRodriguez7** [comment]
This feature on Blacklight application v1.29.3
