### ISSUE TITLE
Style the Advanced Search - body

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#563]
# Summary
Updated the Advanced Search page to reflect the design [in zeplin](https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa/screen/5f5707bfd9b7b87a960b8314)

# Current UI
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/3b1f8312-d821-4464-b810-8e04b5b62ab5)

# Intended UI
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3064318/93688915-50bc3380-fa8f-11ea-933b-b9c4ea13dda5.png">

# Acceptance Criteria
- [ ] the body form fields are set off from the form header and footer by a thin horizontal rule
- [ ] all titles have the proper color, font and size
- [ ] all text boxes are properly sized with the correct border size and color
- [ ] the amount of columns on screen are responsive (may mimic the gallery list view)
- [ ] proper spacing between each column, row, and between the body and the elements above/beneath it
- [ ] the "Search Tips" section is formatted to match the zeplin design
- [ ] the form is laid out to accommodate additional fields- see #594

**Comment by DraxIndustries79** [comment]
Waiting for design update to include Search Tips

**Comment by K8Sewell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/319

**Comment by FCRodriguez7** [comment]
This feature on Blacklight application v1.29.3
