### ISSUE TITLE
SPIKE: How can we speed up the deployment feedback loop?

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#567]
In replacing the IIIF Manifest service, we had to try deploys many times in order to get the service up and running. The feedback loop for this was relatively slow, slowing overall development for this service. 

Areas that were noticeably slow (to Max):

- CI
  - Camerata CI (this may be addressed by https://github.com/yalelibrary/yul-dc-camerata/pull/172 ?)
  - Rails apps CI 
    - Can we put the gems into another layer of Docker image so they aren't in the cache-busted one?
      - So we'd have a "Base" layer shared by all 3 rails apps, a "Gems" layer for each, and a "web application" or somesuch top layer for each, so the gems wouldn't have to be re-installed on each CI run
    - Is there any more CI caching or saving we can do? Maybe save Docker images as artifacts or something? We seem to be doing a lot of pushing and pulling of the docker images between CI steps even within the same run.
- Deploy-main
  - Each deployment pulls each entire docker image for each service - 
    - is there any more caching on Amazon or elsewhere we could do to make this faster? It doesn't seem to remember the old layers and just update them, as it does in local development?
    - Is it maybe a good time to give each service its own task? (like postgres and solr have?)
  - Health checks give lots of time for the services to be up
     - can this be reasonably shortened for any of them?

**Comment by fnibbit** [comment]
Data on that first bullet point: PR 172 got the camerata commit-workflow down to a couple-three minutes.  The scheduled workflow (continuous deploy + integration tests, development-mode integration tests) takes ten minutes every 4 hours; that's not set up to block merges.

**Comment by mark-dce** [comment]
Main issues addressed in the course of other work.  We'll continue to refine the process as we go.
