### ISSUE TITLE
Add Honeybadger to IIIF Manifest application

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#568]
- [x] Set up on Honeybadger - get key
- [x] Add environment variable to Camerata 
- [x] Add key to AWS Systems Manager Parameter store
- [x] Does anything need to be done in rails application? not sure (create config file in manifest repo)

**Comment by JzGo** [comment]
Working on the PRs for adding honeybadger key to camerata and manifest server

**Comment by JzGo** [comment]
- PRs are merged on camerata and manifest.
- I can see the Honeybadger key in the manifest task on collections-test
- I was able to trigger an error that showed up on the [manifest project in honeybadger](https://app.honeybadger.io/projects/76879/faults/68786670)

**Comment by JzGo** [comment]
Retroactively adding this screenshot for the error generated from demo:
![Screen Shot 2020-10-14 at 10.38.09 AM.png](https://images.zenhubusercontent.com/55b8f4ac4f7a08fbb7f3f98c/0bef15c4-9931-4a62-bbad-2a6429a6b0c5)
