### ISSUE TITLE
Move code repos to Yale GitHub organization

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#57]
**ISSUE**
We're starting to have enough different repos and folks needing access to them that it makes sense to move them to their final home and set up access rights there.

**ACCEPTANCE**
Move existing repos to a Yale GitHub organization
- [x] https://github.com/curationexperts/YUL-DC
- [x] https://github.com/curationexperts/yul-dc-iiif-manifest - forked
- [ ] https://github.com/curationexperts/yul-dc-iiif-manifest - deleted
- [x] https://github.com/curationexperts/manifests-yul - forked
- [ ] https://github.com/curationexperts/manifests-yul - deleted
- [x] https://github.com/yalelibrary/yul-dc-blacklight - pushed
- [x] https://github.com/notch8/blacklight-yul - deleted
- [x] https://github.com/yalelibrary/yul-dc-deploy - pushed
- [x] https://github.com/notch8/deploy-yul - deleted

New Repos (public!)
- [x] a repo for the front-end blacklight app: https://github.com/yalelibrary/yul-dc-blacklight
- [x] a repo for the IIIF image service: https://github.com/yalelibrary/yul-dc-iiif-imageserver

Access
- [x] Ensure everyone on the project team has access to the repos above https://docs.google.com/spreadsheets/d/1buZmd2Nq_R8yL6NYUySPW5cWaNoZwNRWqk-1OIzYX74/edit#gid=0

**Comment by mikeapp** [comment]
Invites to `yalelibrary` org sent to DCE + Notch8 teams.

**Comment by geekscruff** [comment]
Please may I rename yul-dc-iiif-manifest

we already have manifests-yul so how about manifests-yul-images (in line with the agreed url) and then we can have iiif-yul-images

**Comment by mikeapp** [comment]
Need @jpengst , @JzGo , and @fnibbit  to accept my GitHub invite.

**Comment by mikeapp** [comment]
Created public repos for the image server and Blacklight.  Added DCE/Notch8 team with `write` to new repos and https://github.com/curationexperts/yul-dc-iiif-manifest and https://github.com/curationexperts/manifests-yul - forked

Still to do: transfer YUL-DC

**Comment by mikeapp** [comment]
YUL-DC has been transferred
