### ISSUE TITLE
Move "Source" metadata field down to "Migration Source" section

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#571]
- [ ] "Source" should be moved down to the "Migration Source" section of the page

![Screen Shot 2020-09-14 at 1.33.29 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/3f5b2c37-8309-4ada-9152-91164d5d8967)

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/4ce00e97-4b26-4c90-9d67-e092faa12479)
