### ISSUE TITLE
Disable public access to collections-demo.library.yale.edu (VPN only access)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#576]
**ACCEPTANCE**
- [x] I should be able to access https://collections-demo.library.yale.edu when I am on the Yale VPN
- [x] I should not have to enter HTTP Auth credentials to access the demo site

**Comment by dl-maura** [comment]
Plan is set, use f5 traffic

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-camerata/pull/194 deployed to test, demo @yale; confirmed lack of basic auth in private browser with Maura
