### ISSUE TITLE
Duplicate metadata fields should be removed from single item view

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#578]
**ISSUE**
Some fields are indexed twice to support both exact match searches (`_ssim` suffix) and tokenized searched (`_tesim` and `_tsim` suffixes).  We only need to show one version of those fields in the item view page.

**ACCEPTANCE**
-  [ ] When the same field exists with both a `_ssim` and either `_tesim` or `_tsim` suffix, only display the `_tesim` or `_tsim` version of the field

**BACKGROUND**
See https://github.com/yalelibrary/yul-dc-management/blob/86996e6a039f7aa35f3874e5728440b24791f1e2/app/models/concerns/solr_indexable.rb#L38-L125  
e.g. L55-L56 collectionID; L78-L79 identifierShelfMark

**EXAMPLE**
![Screen Shot 2020-09-15 at 1.36.15 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/518568f3-5bd9-49ba-beb7-07d67c9415eb)

**Comment by K8Sewell** [comment]
PR Ready for Review - https://github.com/yalelibrary/yul-dc-blacklight/pull/315
