### ISSUE TITLE
VPN General Image 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#579]

**Comment by FCRodriguez7** [comment]
Current Image: 
![placeholder_restricteddraft.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c4f1fa3a-94e6-495e-8cdd-e154c407b2ba)

Intended Image: 
[Placeholder]

**Comment by mark-dce** [comment]
It looks like we have an updated design from Matt in the repo now
https://github.com/yalelibrary/yul-dc-blacklight/blob/master/app/assets/images/placeholder_restricted.png

I also noticed 2 older placeholder images that I think we can delete in this PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/368

**Comment by mark-dce** [comment]
We removed the obsolete images 
https://github.com/yalelibrary/yul-dc-blacklight/pull/368
