### ISSUE TITLE
Remove the index number from the gallery view

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#580]
# Related ticket
#471

# Acceptance Criteria
- [x] remove the index number from the top left corner of a result on the gallery view
- [x] the index number still shows on the list view

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/283

# Expected behavior
- The index number is hidden on the gallery view
- The index number still shows on the list view

# Demo
![580](https://user-images.githubusercontent.com/29032869/93252064-da939600-f749-11ea-8f3f-51a0e21619ac.gif)

**Comment by dl-maura** [comment]
Numbers don't show when I'm on collections-test-yale
![Screen Shot 2020-09-16 at 6.21.54 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/35b73742-eae1-4534-a2a0-709870cd4d62)
