### ISSUE TITLE
Can't simple search on advanced search

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#581]
If I'm in the advanced search but opt to use the still available top search, it doesn't work (seems to just reload the page)

Browser: happens in Firefox and Safari
Code Version: Branch:v1.17.4,Deployed:2020-09-15T14:19:06-04:00

![Screen Shot 2020-09-15 at 3.09.09 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/8f8763f8-46e5-4fb2-a6e7-78948e241793)

**Comment by alishaevn** [comment]
The search bar is intended to be removed from the advanced search page in #561.
