### ISSUE TITLE
Implement a production version of the Metadata Cloud

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#583]
**ACCEPTANCE**
- [ ] We can access a production instance of the metadata cloud service which provides production metadata for Voyager, Archivespace, and Ladybird

**Comment by mikeapp** [comment]
Requests in flight...

**Comment by bobrice** [comment]
Production has been deployed and automation is set up.  Waiting on f5 entry to be finished.  Hopefully that will be today or tomorrow.(10/1 or 10/2

**Comment by bobrice** [comment]
The production version of MetaDataCloud is up at https://metadata-api.library.yale.edu/metadatacloud/api/ils/bib/5555?mediaType=json

NOTE: It is currently configured to use Test Archivesspace until the credentials arrive.

**Comment by bobrice** [comment]
Received archivesspace production keys and re-deployed production Metadata cloud app.  Complete from my perspective.
