### ISSUE TITLE
BUG: STYLING: Arrow Rotation: Sub-Header Menu has no rotation

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#588]
![Screen Shot 2020-09-18 at 9.33.27 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/dfc7faae-5ab0-4fe9-ba80-96c3cc330bad)

**EXPECTED RESULT**
- [x] The arrows should rotation when the user clicks on one.

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/311

# Expected behavior
- arrows in the secondary nav rotate when a link is clicked

# Demo
![588](https://user-images.githubusercontent.com/29032869/93924469-a2e89900-fcc9-11ea-892a-01e764ab40e6.gif)

**Comment by mark-dce** [comment]
In Safari Version 12.1.2 (14607.3.9) when I click on the drop-down menus in the sub-header, they do not collapse correctly.  I don't see this behavior in Chrome.  (The loaner laptop I'm using appears to be running a slightly older version of Safari from 2019.)

![image](https://user-images.githubusercontent.com/3064318/94298856-6cf71f00-ff2c-11ea-9372-5ed75060cbcc.png)

![image](https://user-images.githubusercontent.com/3064318/94302097-4a1b3980-ff31-11ea-9be4-d39bd70f86d4.png)

![image](https://user-images.githubusercontent.com/3064318/94302274-923a5c00-ff31-11ea-8965-ec5cc9d0b10b.png)

**Comment by alishaevn** [comment]
@mark-dce I have safari v 14.0 and I do not see the behavior you described above. the gif I made is too large to be added as an attachment, but you can view it at the link below.

https://share.getcloudapp.com/Blu1LvZz

**Comment by DraxIndustries79** [comment]
Decided that the secondary bug isn't worth pursuing.  Safari 12 is out of support.
