### ISSUE TITLE
Search Bar Alignment and Sizing - styling

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#589]
**Proposed Design**
![Screen Shot 2020-09-18 at 9.52.06 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a56cc119-cf30-48d6-a231-db3b8463d229)

**Implemented Design**
![Screen Shot 2020-09-18 at 9.50.32 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b0630646-132b-4f68-a498-051765fedd1e)

**Alignment and Space**

- [x] The collective whole without exclusion of the "All Fields" button, search bar, search button, and Advanced Search ought to be centered on the screen for the different resolutions: 
   - [x] default device 
   - [x] medium device
   - [x] large device 
   - [x] xlarge device 

**Padding**
- [x] Overall padding

**Sizing**
- [ ] The font size should be smaller across that area 
*Please refer to the Zeplin board

***Note: We want the wording of ADVANCED SEARCH over MORE OPTIONS.

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/320
