### ISSUE TITLE
Build initial ECS cluster in YUL AWS organization

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#59]
**ACCEPTANCE**
- [x] We have an ECS cluster running in YUL AWS running
   - [x] The manifest service
   - [x] The image service
   - [x] The blacklight service
- [x] [Team members](https://docs.google.com/spreadsheets/d/1buZmd2Nq_R8yL6NYUySPW5cWaNoZwNRWqk-1OIzYX74/edit#gid=0) can deploy changes to the cluster
- [x] Team members can inspect Tasks running in the cluster

**Comment by dl-maura** [comment]
Keith has built up a cluster in ECS in Yale's account. Working on refactoring McClain's ECS compose file to work.

**Comment by dl-maura** [comment]
Keith is working on this, still trying to figure out compose file in cluster

**Comment by dl-maura** [comment]
Cluster is up and running, but load balancers aren't attached yet. Requires latest release of ECS CLI, which can't get.

**Comment by dl-maura** [comment]
Load balancers are up, working on getting clusters and target groups and end restart loop

**Comment by dl-maura** [comment]
This is tested and works, and we have had Yale, DCE, and N8 people test.
