### ISSUE TITLE
[Check] Bug: unexpected behavior when clicking drop downs in a certain order

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#591]
# Summary
- refreshing the page, clicking on one of the secondary nav items, then clicking on the "sort by..." or "... per page" drop down works as expected. only the active drop down is dropped down
- if you click on one of the secondary nav items a **second** time, then click on the "sort by..." or "... per page" drop down, the secondary nav link item still shows the blue background...but the text is gone. the "sort by..." or "... per page" drop down will show, but instead of dropping down, it drops up

# Related ticket
- https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/564

# Demo
![BUG564](https://user-images.githubusercontent.com/29032869/93549383-049db180-f91e-11ea-93c0-7b0cfe26fcc4.gif)

# Acceptance Criteria
- [ ] **Close if not still an issue.**
- [ ] clicking on one of the secondary nav items or the "sort by..." or "... per page" drop down should close the previously opened drop down

# Implementation suggestions
- the code below in `_header_navbar.html.erb` appears to trigger the first time....but not any subsequent times, only for the "sort by..." or "... per page" drop downs though. (I realized this behavior by adding a console log of `e.target` in this function)
```
$('body').on('click', function(e) {
            if (
                !$(e.target).is('.secondary-nav .nav-link-title') && !$(e.target).is('.secondary-nav .nav-link-title li a') ||
                $(e.target).is('.sort-dropdown') ||
                $(e.target).is('.per-page-dropdown')
            ) {
                $('.secondary-nav .content-yul').removeClass('content-show')
                $('.content-yul').height(0)
            }
        })
```

**Comment by FCRodriguez7** [comment]
The "sort by relevance," "10 per page," and the submenu bar described behavior no longer is impacted in the same way.  The "new" behavior is different.  Is the new behavior acceptable?

https://images.zenhubusercontent.com/242185115/2de02f6e-9458-4ab8-9b78-41379bdba504/new_click_behavior.mov

**Comment by FCRodriguez7** [comment]
The design came from the current home page.  See the video below: 

https://images.zenhubusercontent.com/242185115/0c8bc1d5-48ba-4493-a55e-7e84473a9d9c/current_home_page_behavior_.mov
