### ISSUE TITLE
Knowledge Transfer: Adding Gems to Management App

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#592]
As a developer, I would like to add gems to the management app to add functionality easily.

Acceptance Criteria: More than two Yale developers know the process to add a gem to the management application.
- How to first test the gem on development box.
- How to add the new gem to the base image. (if necessary)
- What to commit to git for the Gemfile/Gemfile.lock changes.
- Notify other developers that they need to pull?

(Maybe this is the same for Discovery, etc?)
(We could use will_paginate as an example.)

**Comment by martinlovell** [comment]
@FCRodriguez7 said he can help us with this.

**Comment by FCRodriguez7** [comment]
@martinlovell Some reading:  https://github.com/yalelibrary/yul-dc-blacklight#when-installing-a-new-gem

**Comment by mark-dce** [comment]
@martinlovell I'm removing the dependency for the pagination issue so that we can complete that ticket within the next sprint.  Sounds like Frederick is happy to knowledge share on this.  I'm sure @orangewolf would be too.
