### ISSUE TITLE
Advanced Search page should have a link/button back to basic search

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#593]
**ACCEPTANCE**
- [x] The "Start Over" button does not appear at the top of the Advanced Search page
- [x] There is a clear clickable target that takes me back to basic search from the homepage

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/6e77201b-0130-4bc8-b547-b64b42a38b62)

**Comment by DraxIndustries79** [comment]
We need some clarity on this

**Comment by DraxIndustries79** [comment]
Duplicate of https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/561?

**Comment by mark-dce** [comment]
Completed as part of the Advanced search body ticket?
