### ISSUE TITLE
Advanced Search Fields Decisions

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#594]
**ACCEPTANCE**

- [x] Rebecca to edit/trim list
- [x] Individual fields are in Rebecca's comment below

Finishing advanced search is now in #668

Highlighting of new fields is new ticket to be created.

The Advanced Search form lists all currently searchable fields in alphabetical order by field label (in quotes below)
 - [ ] abstract_tesim: "Abstract"
 - [ ] accessRestrictions_tesim: "Access Restrictions"
 - [ ] accessionNumber_ssi: "Accession Number"
 - [ ] alternativeTitle_tesim: "Alternative Title"
 - [ ] alternativeTitleDisplay_tesim: "Alternative Title Display"
 - [ ] archiveSpaceUri_ssi: "ArchiveSpace Uri"
 - [ ] box_ssim: "Archival Box ID",
 - [ ] collectionId_tesim: "Collection Identifier"
 - [ ] contents_tesim: "Contents"
 - [ ] contributor_tsim: "Contributor"
 - [ ] contributorDisplay_tsim: "Contributor Display Label"
 - [ ] coordinates_ssim: "Coordinates"
 - [ ] author_tesim: "Creator"
 - [ ] creatorDisplay_tsim: "Creator Display Label"
 - [ ] date_ssim: "Date [General Label]"
 - [ ] dateStructured_ssim: "Date [ISO]"
 - [ ] copyrightDate_ssim: "Date Copyrighted"
 - [ ] dateDepicted_ssim: "Date Depicted"
 - [ ] description_tesim: "Description"
 - [ ] digital_ssim: "Digital"
 - [ ] edition_ssim: "Edition"
 - [ ] extent_ssim: "Extent"
 - [ ] extentOfDigitization_ssim: "Extent Of Digitization"
 - [ ] folder_ssim: "Archival Folder ID"
 - [ ] format: "Format"
 - [ ] genre_ssim: "Genre"
 - [ ] identifierMfhd_ssim: "Identifier Mfhd"
 - [ ] identifierShelfMark_tesim: "Call Number [approximate match]"
 - [ ] identifierShelfMark_ssim: "Call Number [exact match]"
 - [ ] illustrativeMatter_tesim: "Illustrative Matter"
 - [ ] caption_tesim: "Image Captions",
 - [ ] label_tesim: "Image Labels",
 - [ ] language_ssim: "Language"
 - [ ] localRecordNumber_ssim: "Local Record Number"
 - [ ] material_tesim: "Material"
 - [ ] oid_ssi: "OID [Parent/primary]",
 - [ ] child_oids_ssim: "OID [Child/images]",
 - [ ] orbisBarcode_ssi: "Orbis Barcode"
 - [ ] orbisBibId_ssi: "Orbis BibId" 
 - [ ] partOf_tesim: "Part Of Collection"
 - [ ] projection_tesim: "Projection Type"
 - [ ] publicationPlace_tesim: "Publication Place"
 - [ ] publisher_tesim: "Publisher"
 - [ ] references_tesim: "References"
 - [ ] repository_ssim: "Repository"
 - [ ] resourceType_tesim: "Resource Type"
 - [ ] rights_tesim: "Rights Statement"
 - [ ] scale_tesim: "Scale"
 - [ ] sourceCreated_tesim: "Source Created"
 - [ ] sourceDate_tesim: "Source Date"
 - [ ] sourceEdition_tesim: "SourceEdition" # Not currently in Blacklight application
 - [ ] sourceNote_tesim: "Source Note"
 - [ ] sourceTitle_tesim: "Source Title"
 - [ ] subjectEra_ssim: "Subject Era"
 - [ ] subjectGeographic_tesim: "Subject (Geographic)"
 - [ ] subjectTitle_tsim: "Subject (Title)"
 - [ ] subjectTitleDisplay_tsim: "Subject (Title Display)"
 - [ ] subjectName_tesim: "Subject (Name)"
 - [ ] subjectTopic_tesim: "Subject( Topic)"
 - [ ] title_tesim: "Title"
 - [ ] visibility_ssi: "Visibility"

**Comment by DraxIndustries79** [comment]
Rebecca does not want all of these fields.  Rebecca will edit list.  We also need to determine consistency on using () vs. [].

**Comment by dl-maura** [comment]
Rebecca and I met:

- [ ] “All fields” should search all fields (maybe called keyword?) NEED TO DISCUSS
- [ ] author_tesim: “Creator”
- [ ] title_tesim: “Title”
- [ ] identifierShelfMark_ssim: “Call Number”
- [ ] date_ssim: “Date”
- [ ] Subject should search:
- [ ] subjectEra_ssim: “Subject Era”
  - [ ] subjectGeographic_tesim: “Subject (Geographic)”
  - [ ] subjectTitle_tsim: “Subject (Title)”
  - [ ] subjectTitleDisplay_tsim: “Subject (Title Display)”
  - [ ] subjectName_tesim: “Subject (Name)”
  - [ ] subjectTopic_tesim: “Subject( Topic)”
- [ ] Genre/format should search:
  - [ ] format: “Format”
  - [ ] genre_ssim: “Genre”
- [ ] break in formatting
- [ ] oid_ssi: “OID [Parent/primary]“, (maybe relabel Parent Object ID)
- [ ] child_oids_ssim: “OID [Child/images]“, (maybe relabel Image ID)

**Comment by K8Sewell** [comment]
Questions:
- 'All Fields' has been changed to 'Common Fields' - is that ok or is there anticipated change here?
- Should 'Author' be changed to 'Creator' everywhere in the app?
- What does 'break in formatting' mean?  like a <br>? a line or just extra space?  Or is it just denoting to use brackets instead of parenthesis?
- Who should we look to for an answer on the maybe relabel fields at the end?

**Comment by K8Sewell** [comment]
Do we want Author to change to Creator app wide or just on the advanced search page?

**Comment by mark-dce** [comment]
Genre/format search appears to be case sensitive and should not be:

**STEPS TO REPRODUCE**
1. Choose advanced search
2. In the "Genre/format" field, enter "**a**utographs"
3. Click the search buttons  

4. Go back to advanced search
5. In the "Genre/format" field, enter "**A**utographs"
6. Click the search buttons

**Comment by MaggieZhaoYale** [comment]
We will going to add genre_tesim for advanced search. and add format_tesim as well.

**Comment by dl-maura** [comment]
All fields is going to be it's own ticket

**Comment by dl-maura** [comment]
Deployed in test, successfully searched lowercase autograph
![Screen Shot 2020-10-12 at 9.56.26 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/7b963fd9-cdec-4a35-8390-1fd8e1321c70)
![Screen Shot 2020-10-12 at 9.57.18 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c96d6a77-f827-4a7a-9213-6d9a63f98580)

**Comment by FCRodriguez7** [comment]
Is the work complete?

**Comment by FCRodriguez7** [comment]
The acceptance criteria seem to be clear.

**Comment by MaggieZhaoYale** [comment]
genre/format thing is fixed
