### ISSUE TITLE
Rename "All Fields" search label to "Common Fields"

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#595]
**ACCEPTANCE**
- [x] The default search option is listed as "Common Fields" instead of "All Fields"

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/942cab74-57ed-4ebd-9d94-fb3e93ce8678)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/313

**Comment by FCRodriguez7** [comment]
Blacklight v1.25.0
