### ISSUE TITLE
CAS authentication doesn't work on Yale

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#596]
**STEPS TO REPRODUCE**
1.  Visit https://collections-demo.library.yale.edu or collections-test.yale (happening to MC on both)
2. Click on the "Sign In" link at the top right of the window
3. Enter your Yale NetID and password

**EXPECTED BEHAVIOR (working on collections-test)**
I should return to the page I was on and my NetID should be displayed with a sign-out option in the header
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/35993ac9-1581-4cac-a639-e5777f62dda8)

**ACTUAL BEHAVIOR (same steps on collections-demo)**
"We're sorry, but something went wrong..."  
See https://app.honeybadger.io/projects/72587/faults/67053737
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/5015dcd0-bf94-44dc-ba6e-2eeb43894374)

**Comment by dl-maura** [comment]
Remove email, mike thinks that is the bug

**Comment by bess** [comment]
@maxkadel and I have a fix in progress for this.
