### ISSUE TITLE
[Check] Microsoft Edge Browser - Search Results Rendering

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#598]
**ISSUE**
When viewing the site in Microsoft Edge, search result lists are not formatted as expected.

**ACCEPTANCE**
- [ ] **Close if good on current Edge version**
- [ ] Titles are adjacent to the result order number (rather than below)
- [ ] Result numbers and field names are left justified and aligned with one another
- [ ] Field labels are on the same row as the corresponding metadata (instead of overlapping)

**CURRENT EDGE**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/b5934aa9-bbbc-4c36-8c39-76ce3ae6856c)

**Comment by K8Sewell** [comment]
Microsoft Edge - Edge 85.0.564.51 (Official build) (64-bit) does not have this issue.  Issue occurs with older versions of Edge.

**Comment by K8Sewell** [comment]
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/85fba08b-7fe0-41a6-8d5c-5057593d21b9)

**Comment by dl-maura** [comment]
Here's a bugherd ticket having the issue, with browser info: https://www.bugherd.com/t/KPJoDunpHArvCmYxhQXeew

**Comment by FCRodriguez7** [comment]
Edge version:  
MS-based source code:
The library is using version 38 with the majority of computers on 42.x and 44.x, 42.17134.1098.0

Chromium-based source code:
Microsoft Edge			Microsoft	86.0
Microsoft Edge			Microsoft	85.0
Microsoft Edge			Microsoft	84.0
Microsoft Edge			Microsoft	83.0

**Comment by FCRodriguez7** [comment]
**Staff Image**

![62437708392__DF0588DC-8E4C-4603-93FE-B0708F152D34.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/548e4578-e36d-421f-be66-3420b2e226d4)!

[62437713128__463CF0AA-ED95-4F18-8CA0-0B52BEB9ADE5.jpeg](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/393b0467-4026-40a4-bbde-526caffaaee4)

**Comment by FCRodriguez7** [comment]
Edge Verison 86.0.6222

[https://app.zenhub.com/files/242185115/b83a8fdc-9530-44b0-a88c-cd3815e5803d/download](https://app.zenhub.com/files/242185115/b83a8fdc-9530-44b0-a88c-cd3815e5803d/download)
