### ISSUE TITLE
Management App can Create PTIFFS from Storage@Yale Access Masters (ECS<-->NFS)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#599]
**STORY**
We need to be able to read and write Access Master TIFF images from Storage@Yale.  In oder to do this, we intend to mount Storage@Yale as an NFS volume mounted to an EC2 instance.

**DETAILS**
See #545 and the related decision document  https://docs.google.com/document/d/1Qi59J00D13gN37YI1sfjlHtC6n_Q-kWsa3jhk_ckFFU/edit#

**ACCEPTANCE**
- [x] The management application can successfully read Access Masters and generate PTIFFS for legacy images (images that have been moved to the proper location in the pair-tree on Storage@Yale and are named by their OID)

**Comment by dl-maura** [comment]
Deployed worker to EC2 task, smoothing out scripting

**Comment by dl-maura** [comment]
Used McClain's scripts to update uat, worker is running, next working on updating test

**Comment by dl-maura** [comment]
Verifying ptiff conversion

**Comment by dl-maura** [comment]
UAT was successful
