### ISSUE TITLE
Determine whether to use EKS or ECS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#60]
**ISSUE**
Before investing too much more effort into developing deployment tooling, we need to make a decision about which container platform we want to adopt for the project.

**ACCEPTANCE**
- [x] Review the decision deck here https://docs.google.com/presentation/d/1Pvu13BcD5x-e6jVmXiUQJy4vhBoAvkabAjxaGwP8ROg/edit#slide=id.g7311923ff6_0_51
- [ ] Write up tickets for any additional tickets, experiments, or spikes to help provide context and data
- [x] Make a decision by EOD Thursday 4/16 (so we can incorporate the direction into planning for the following sprint)

**Comment by bobrice** [comment]
Received.  Meeting later today, 4/13/20, should provide good content for this topic.

**Comment by DraxIndustries79** [comment]
Per 4/13 meeting, decision to go with ECS
