### ISSUE TITLE
SPIKE: Management App System Status

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#601]
**ACCEPTANCE**
The management app has a system status page that displays
- [ ] Local disk usage (% Free, Total Size in GB)
- [ ] EFS mount disk usage (GB in Use)
- [ ] For each background worker 
    - [ ] Worker ID
    - [ ] Worker disk usage (%Free, Total Size in GB)
    - [ ] Storage@Yale NFS mount status

Rick is looking at options

**Comment by RachelDCE** [comment]
New info: Can we use DynaTrace?
