### ISSUE TITLE
Users must authenticate to view the management application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#602]
**ISSUE**
The management application supports destructive and data modifying activities.  Users should authenticate to the application using their NetID before being able to access any portion of the management application.

**ACCEPTANCE**
As an unauthenticated user
- [ ] Visiting any route in the application redirects me to a login screen
As an authenticated user
- [ ] I can navigate the application as expected
- [ ] I have a logout option (last option in the left navigation bar)

**Comment by orangewolf** [comment]
Note that this should likely use omniauth-cas as is set up in the Blacklight app.
