### ISSUE TITLE
SPIKE: Design authorization system across apps

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#605]
- How will the manifest service know if it should serve a manifest?
- Does the management app need to further restrict records to be VPN only or not since it will limit the kinds of users that can log in
- Are permissions for records in the blacklight application sufficient or do they require more granular permissions?
- What is the source of authorization authority?
- How do we determine if a request is 'on campus'?

**Comment by dl-maura** [comment]
M schedule meeting -- 1 hour

**Comment by dl-maura** [comment]
@mikeapp @orangewolf @mark-dce @maxkadel @K8Sewell (opt) @alishaevn (opt) @jpengst @kcompsci

**Comment by mark-dce** [comment]
See notes document here: https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#heading=h.9qspi256ge5g
