### ISSUE TITLE
Select visibility from dropdown

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#607]
**ISSUE**
I want to be able to select an objects visibility from a controlled value list, so that I don't inadvertently enter an invalid visibility setting.

**ACCEPTANCE**
- [ ] The visibility field on the parent object edit form is a dropdown containing valid values understood by the discovery application.

**Comment by dl-maura** [comment]
Record the values for Maura to use in Goobi

**Comment by MaggieZhaoYale** [comment]
Public
Private
Yale Community Only
(any others visibility values?)
