### ISSUE TITLE
OIDs in the Parent Object list are clickable

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#608]
**ISSUE**
I'd like to be able to just click on the OID in a row rather than having to scroll to the right and click the "Show" button.

**ACCEPTANCE**
- [ ] The OID in the first column of the parent object list is a clickable link that takes me to the same view as "Show"

**Comment by FCRodriguez7** [comment]
I want to pair on this with someone from the management team.

**Comment by martinlovell** [comment]
I was able to get the tests passing on this.  I'm not sure if I did it the right way.  Let me know if you want to pair and take a look.

**Comment by mark-dce** [comment]
Can we format the links differently than normal text.

Links in blue with underlines would be conventional and acceptable.
