### ISSUE TITLE
Remove Subject Topic SSIM from Item Page Metadata (and anywhere else it shows in the UI) (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#609]
From Bugherd: https://www.bugherd.com/t/QpmKbMvBn6KhpiHJr3odVw

We have Subject Topic and then Subject Topic Ssim, we don't need Subject Topic SSIM to display on this page, just Subject Topic

**Comment by mikeapp** [comment]
Duplicate of #578 ?

**Comment by dl-maura** [comment]
@mikeapp looks like it!

also not sure if this is being indexed and therefore would sometimes show if it is a highlight match
