### ISSUE TITLE
Parent object Link to Discovery

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#610]
**ISSUE**
I'd like to be able to quickly view an object in the discovery application without having to perform a search.

**ACCEPTANCE**
- [x] There is a "Discovery" button in each row of the parent object list that opens a new window with the discovery application showing the view page for that parent OID.  (put the button next to "Show" in the list of buttons on each row)

**Comment by MaggieZhaoYale** [comment]
The two cols Last id update	 and the col with show | edit |update | Destroy are no longer in the table.     
 Since "show' is not in the row, where should the button be with? Thank you.

**Comment by MaggieZhaoYale** [comment]
![Screen Shot 2020-09-29 at 2.58.20 PM.png](https://images.zenhubusercontent.com/5e5d51efa9378ddb51816940/d6614091-199c-4360-823a-55c83011d1ad) Is the button acceptable?

**Comment by RachelDCE** [comment]
Would like text to say Public View.
