### ISSUE TITLE
Implement Mirador Service

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#613]
**STORY**
As a digital collections manager, I want folks to be able to view works in our own instance of Mirador, so that researchers have an easily accessible tool to conduct deeper image scholarship.

**ACCEPTANCE**
- [ ] We have a Mirador server that can be access from blacklight
- [ ] The server can display any public manifest
*FUTURE* Ensure we respect access restrictions on Yale-only content.

**Comment by mikeapp** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/352 adds Mirador at `/mirador/:oid`, e.g., http://127.0.0.1:3000/mirador/2005512

![Screen Shot 2020-10-20 at 7 31 47 AM](https://user-images.githubusercontent.com/1987952/96580698-ad855680-12a6-11eb-8e38-b62b3d665fe0.png)
