### ISSUE TITLE
Word gets cut off in advanced search display (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#614]
See bugherd for information: https://www.bugherd.com/t/kggSPwhMFvblvjb1cgb3Ow

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/fc5c2acd-7027-4317-aad5-b617ffbeee69)

**Comment by mark-dce** [comment]
I think this may be fixed once we handle the Advanced Search body styling - we should double check whether this issue is still occurring after #563 is complete.
