### ISSUE TITLE
Remove Illustrative Matter display from Metadata in Item view and results view if necessary (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#615]
See Bugherd: https://www.bugherd.com/t/XXjXWX1wE9xyhMuREOinpA

Not sure if this is being indexed and therefore would sometimes show if it is a highlight match

Option 1 below was chosen:  Remove field from application

**Comment by mark-dce** [comment]
@rebeccahirsch This one is your call - the values in this field don't seem to have very friendly formatting.  

We can either:
1) Remove the field entirely
2) Leave the field and remedy the issue at the metadata cloud or voyager level to ensure more human-friendly content (this would mean living with what's there in ladybird for now)

**Comment by dl-maura** [comment]
Did this, PR is ready for blacklight, need to remove field from solr in management.

Current:
![Screen Shot 2020-10-12 at 9.05.29 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/f91f44ac-feb4-41db-82e5-030e4e14ce38)

Now:
![Screen Shot 2020-10-12 at 9.06.01 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/94022eb7-189c-44ec-8505-5b80fbabea94)

**Comment by dl-maura** [comment]
Martin did PR to remove from Management
