### ISSUE TITLE
Numbers are back in gallery View?

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#619]
Numbers seem to be back in Gallery view on collections-test-yale, but only sometimes? Seems tied to advanced search, here I did advanced search for call num 'gen mss' and I got this. Happens every now and then from advanced search.
![Screen Shot 2020-09-24 at 10.08.22 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/144fc21e-65c7-434a-98de-b8cc7b3cf7df)

**Comment by dl-maura** [comment]
More info, it seems to happen when I had gallery on but then do any search (this was a general)
![Screen Shot 2020-10-06 at 10.08.08 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6620103f-6f0f-4e51-b965-e6a966227496)

**Comment by mark-dce** [comment]
I'm not able to replicate this on v1.31.2 .  If we see it again, would someone capture the release number in the issue.

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3a68721c-24ca-4932-8238-304bcd302ad4)

**Comment by mark-dce** [comment]
Fixed in #885
