### ISSUE TITLE
Containerized SOLR for development environments

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#62]
**STORY**
I'd like an easy way to get Solr in my development environment populated with good metadata to use when starting to develop new features.

**ACCEPTANCE**
- [x] We have a Solr image 
   - [x] That can be used with a local Blacklight development environment
   - [x] That can be used with a containerized Blacklight development environment

**Comment by geekscruff** [comment]
It might not be necessary to have a custom solr image, the existing docker solr is widely used and there are a number of pre-existing mechanisms for loading the config and creating the core. Worth considering whether it's necessary.

Question - does this solr need to be separate to blacklight, or, put another way, does it need to be accessed by anything other than blacklight? If it does, then a separate repo just for the Dockerization and configs would make sense. If it doesn't, then putting configs into the existing https://github.com/yalelibrary/yul-dc-blacklight repo makes sense.

**Comment by mark-dce** [comment]
For now, I think an existing image with a customized core for the metadata should do the trick.  That may change as the design evolves, but if we can use an existing stable, public image that would be great.

**Comment by bess** [comment]
Version control here: https://github.com/yalelibrary/yul-dc-solr
