### ISSUE TITLE
[Valid] Smaller view not working right in IE? (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#620]
**Story**

![Screen Shot 2020-09-24 at 11.36.19 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/3c864585-a244-4728-922b-e93a88c67f41)

![Screen Shot 2020-09-24 at 11.36.55 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/61c2406e-5a3d-46d0-8f05-7b0727a0cdb7)

No bugherd link because I was helping the person learn bugherd and just did this local when I noticed it.

**Acceptance**
- [ ] Verify the behavior is still as above.
- [ ] Add screen capture of  individual object page

**Comment by K8Sewell** [comment]
Internet Explorer still has some styling issues that could be addressed:

![Screen Shot 2021-11-17 at 2.53.00 PM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/032e7b2c-396e-4a23-97f0-408ed02e483d)

![Screen Shot 2021-11-17 at 2.53.32 PM.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/5c749f04-0b05-465a-a5d6-0025d5157a60)

![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/abb7f417-f4e7-4031-9699-372d6cb65349)
