### ISSUE TITLE
Highlights not appearing for matched items

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#623]
**STEPS TO REPRODUCE**
1. Search for "SUBJECT" : "Portable Medieval Manuscripts"

**EXPECTED RESULTS**
- [x] Each of my search results should indicate the field[s] that caused the match

**ACTUAL RESULTS**
Only one of my 22 matches displayed any highlighting.
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/b6007f8d-178d-40be-af04-aa83763e1a13)

**Comment by FCRodriguez7** [comment]
I am getting the same results for both demo and test.   

**Demo** 
![Screen Shot 2020-09-30 at 3.35.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ce262ac4-f781-4d51-b7a4-1475ef9be21f)

**Test**
![Screen Shot 2020-09-30 at 3.36.03 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/7b392e51-4af3-4cf6-a335-ca69b6cf169b)

**Comment by FCRodriguez7** [comment]
This ticket does not seem to be a bug.

**Comment by FCRodriguez7** [comment]
The result is produced by selecting the Subject in the search drop down.

**Comment by FCRodriguez7** [comment]
Highlighting works on the specified feilds described in 

config.add_index_field 'author_tesim', label: 'Creator', highlight: true
    config.add_index_field 'date_ssim', label: 'Date'
    config.add_index_field 'identifierShelfMark_tesim', label: 'Call Number', highlight: true
    config.add_index_field 'imageCount_isi', label: 'Image Count'
    config.add_index_field 'partOf_ssim', label: 'Collection Name'
    config.add_index_field 'resourceType_tesim', label: 'Resource Type', highlight: true
    config.add_index_field 'abstract_tesim', label: 'Abstract', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'alternativeTitle_tesim', label: 'Alternative Title', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'description_tesim', label: 'Description', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'subjectGeographic_tesim', label: 'Subject Geographic', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'orbisBidId_ssi', label: 'Orbis BidId', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'publicatonPlace_tesim', label: 'Publication Place', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'publisher_tesim', label: 'Publisher', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'sourceCreated_tesim', label: 'Created Source', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'subjectName_tesim', label: 'Subject Name', highlight: true, solr_params: disp_highlight_on_search_params
    config.add_index_field 'subject_topic_tesim', label: 'Subject Topic', highlight: true, solr_params: disp_highlight_on_search_params

**Comment by FCRodriguez7** [comment]
There seems to be one feild with the incorrect solr name in the basic search array: 

   search_fields = ['abstract_tesim', 'author_tesim', 'alternativeTitle_tesim', 'description_tesim', 'subjectGeographic_tesim',
                     'identifierShelfMark_tesim', 'orbisBibId_ssi', 'publicatonPlace_tesim', 'publisher_tesim',
                     'resourceType_tesim', 'sourceCreated_tesim', 'subjectName_tesim', '**subject_topic_tesim'**,
                     'title_tesim']

I will change 'subject_topic_tesim' to 'subjectTopic_tesim'.

**Comment by FCRodriguez7** [comment]
The result: 

**Page 1**
![SubjectTopic Feature.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/0d9e38d4-404d-4a5e-9c8d-88b459cc0de0)

**Page 2**
![SubjectTopicFeature p2.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d70b9ce2-0d15-4310-845b-a67948dd51aa)

**Page 3**
![SubjectTopicFeature p3.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d084c613-a8b5-47c3-8951-3088b8c7aa4a)
