### ISSUE TITLE
[Check] Start Over Not working in some Safari? (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#624]
**Check and close**

Bugherd Ticket: https://www.bugherd.com/t/ntEkJC0yi27exFWf7WU0OA

![Screen Shot 2021-06-14 at 11.33.46 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/77e02349-755c-4cd2-81cd-8280967fb85c)

**Comment by FCRodriguez7** [comment]
The behavior in Safari and in Firefox. 

https://images.zenhubusercontent.com/242185115/c0a944e4-fc8c-414f-a254-af244213a330/screen_recording_2021_06_14_at_2_19_04_pm.mov

**Comment by FCRodriguez7** [comment]
The behavior in Chrome: 

https://images.zenhubusercontent.com/242185115/2acff742-87d4-4119-8c1d-aa6b9fa367d1/screen_recording_2021_06_14_at_2_44_36_pm.mov
