### ISSUE TITLE
Set ENV var for Discovery Base URL

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#629]
## Acceptance ##
Camerata will set a variable BLACKLIGHT_BASE_URL that lets Management know where it can link routes to Discovery

This issus was split from #610

**Comment by maxkadel** [comment]
Failing tests?

**Comment by orangewolf** [comment]
@fnibbit This is the template https://github.com/yalelibrary/yul-dc-camerata/pull/204/files#diff-a66404069ec03072d9e7dda578b220b9R445 

The SSM for UAT (as a specific example) should look like `BLACKLIGHT_BASE_URL=http://collections-uat.library.yale.edu`

**Comment by dl-maura** [comment]
DevOps needs to put values in

**Comment by fnibbit** [comment]
You can see this working on test
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/a8e07d8a-5e97-4479-a667-a8b972a71cb7) the "public view" button links here: ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/94d0814b-f660-478b-8e4f-5c1d5332af02)

I'll do a UAT deploy, and then check on 610.
