### ISSUE TITLE
Display manifest links in Blacklight

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#63]
**STORY**
As a researcher, I'd like an easy way to copy the URL for the manifest of the work I'm looking at into Universal Viewer or Mirador.

**DETAILS**
This story is _not_ about displaying the work's images in blacklight (see #64).  This is just about providing a copyable link to the manifest.

Assume the application builds the manifest link based on convention and the OID.

**ACCEPTANCE**
When I'm viewing a work
- [ ] There is a link to the corresponding IIIF manifest
- [ ] When I'm running the manifest service (container) in my development environment, the link returns a valid manifest

**MOCK-UP**
From https://wellcomelibrary.org/item/b20417081#?c=0&m=0&s=0&cv=0&z=-1.1369%2C-0.0828%2C3.2737%2C1.6564
![image](https://user-images.githubusercontent.com/3064318/79164977-ccf77000-7da7-11ea-896d-d6142ceba665.png)

From https://digitalcollections.library.harvard.edu/catalog/990122195650203941?utm_source=HLWebsite&amp;utm_medium=website&amp;utm_campaign=HLwebsite
![image](https://user-images.githubusercontent.com/3064318/79165641-257b3d00-7da9-11ea-908c-8cfde5cc5c3b.png)

**Comment by geekscruff** [comment]
Aren't we missing building out the Blacklight to display stuff from the solr index? The existing https://github.com/yalelibrary/yul-dc-blacklight is completely vanillla. So shouldn't this ticket be to Make the vanilla Blacklight look like the mockup including displaying links.

**Comment by mark-dce** [comment]
I think I was assuming we'd make the Solr metadata #62 line up with the default blacklight field names, so we'd have something that looks a lot like https://demo.projectblacklight.org/catalog/2009001121

**Comment by geekscruff** [comment]
WIP: https://github.com/yalelibrary/yul-dc-blacklight/pull/12

![Screenshot 2020-04-22 at 17.41.04.png](https://images.zenhubusercontent.com/5e5d2e87a9378d624781682e/2bf0f7b0-253e-4786-8ad4-7fbde34459ca)

**Comment by mark-dce** [comment]
Hey - I'm re-opening this ticket because the link I'm getting is

*https://universalviewer.io/uv.html?manifest=*https://spinup-0010ef.spinup.yale.edu/manifests/2012036.json

Instead of just https://spinup-0010ef.spinup.yale.edu/manifests/2012036.json

If you look at the examples, they let me directly copy the link I need to paste into Mirador or the UV demo site, or any other IIIF compatible viewer.  

What I'm looking for is a link that I can directly cut and paste into someone's mirador implementation:
* https://projectmirador.org/demo/
* https://digitalcollections.lmu.edu/documents/mirador/15474
* https://iiif.bodleian.ox.ac.uk/iiif/mirador/faac7582-69cc-4d52-9b7b-81c8098d3fa0

**Comment by mikeapp** [comment]
The Spinup Blacklight has been updated:
http://spinup-0010eb-cantaloupeiiif.svc.spinup.yale.edu:3000/catalog/9801995
