### ISSUE TITLE
Short Search Bar

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#633]
There seems to be a bug with the search bar.  If you click on the search button and then click the back button.

![Screen Shot 2020-09-29 at 1.14.05 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/906aa259-5c2e-46a6-9ae2-0270a529e175)

Note:  Rob suggests this is likely related to turbolinks

**Comment by dl-maura** [comment]
I haven't been able to re-create this?

**Comment by martinlovell** [comment]
This is an issue with autocomplete being initialized twice.

There's a related commit that we do have: https://github.com/projectblacklight/blacklight/commit/af249d64454db13d891dac8f2782467e9cfb8108
but it doesn't seem to work properly for us.

I will try removing autocomplete to see if that helps: #672
