### ISSUE TITLE
Preliminary Batch Job Index Page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#635]
**STORY**
I would like a status page that let's me view my job(s) in relation to other jobs, so that I can better understand when my job might run in relation to other users' jobs.

**ACCEPTANCE**
- [x] I can see the order of my job in relation to other queued jobs
- [x] I can see who else has submitted jobs (by YaleNetID - not first name as show below)
- [x] I can see the submission time and size of all jobs

![User^ TimEs ITems.jpg](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/695f9883-9356-4674-8b8f-ec3d11f8b3f2)

**Comment by RachelDCE** [comment]
Status is not part of this ticket.
