### ISSUE TITLE
Preliminary Batch detail page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#636]
**STORY**
Once I've submitted a batch job, I want to be able to inspect the individual job, so that I can ensure it submitted as expected

**ACCEPTANCE**
I can see
- [x] The batch ID
- [x] Who submitted it
- [x] When it was submitted
- [x] The name of the ingest file
  - [x] A link to view the original ingest file
    - [x] CSV 
    - [x] XML
- [x] A list of parent works in the batch
- [x] When this page exists, please allow us to get to it by clicking the Process ID on Batch Processes page or with a View link

![BATCH JOB View (Su30).jpg](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/af05a3a2-1ffb-4b67-bcee-54f515063ede)

**Comment by RachelDCE** [comment]
Status not part of this ticket.
