### ISSUE TITLE
Sorting doesn't seem to sort? (Bugherd) HIGH VALUE

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#639]
See bugherd: https://www.bugherd.com/t/bLXpUBeLBA4XpWLpKTcfTQ

I've tried a few sorting options, and they don't seem to work correctly (title and author/creator)

I can sort by:
 - [x] Title
 - [x] Creator (still labeled author)

And:
 - [x] Remove all the date sort options (Year, Date newest, date oldest)

Relevance:
![Screen Shot 2020-09-30 at 11.53.08 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/991622f7-45e5-431c-bd41-f5ba3c9eb7d5)

Title (Same order):
![Screen Shot 2020-09-30 at 11.53.21 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/32231276-b1b2-4adb-9999-44c6269e1edd)

**Comment by dl-maura** [comment]
Note: this is broken in our most current version too, not just demo (tested in test)

**Comment by FCRodriguez7** [comment]
What is the most current version?

**Comment by dl-maura** [comment]
@FCRodriguez7 I'm doing this in collections-test-yale so 1.28.0 (also doesn't work in collections demo but that is older)
