### ISSUE TITLE
Add UniversalViewer to display images in Blacklight

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#64]
**STORY**
As a scholar, I'd like to be able to view the images related to the metadata on the work page I'm viewing, so I can visually confirm I've found the correct resource.

**ACCEPTANCE**
Given a work with a an OID in it's metadata
- [x] Display Universal Viewer on the work's show page
- [ ] Show the first image in the manifest in UV (see #63 for manifest link info)

**DEVELOPMENT NOTES**
DCE have a very nice playbook documenting the steps for adding UV to Blacklight: https://curationexperts.github.io/playbook/tools/uv/uv_in_blacklight.html

**Comment by DraxIndustries79** [comment]
Note Per Julie, look into Lea Ann's code from Notch8 project

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/81011417-ed09d480-8e25-11ea-80bc-e98f10af7c5d.png)
