### ISSUE TITLE
Author Solr Mismatch

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#643]
**Currently the Author field inside the code:** 
 ![Screen Shot 2020-10-02 at 5.03.11 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d6d01abd-84e1-41cb-983f-491dccf6bba3)

**Currently the Author field inside Solr:** 
![Screen Shot 2020-10-02 at 5.02.47 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8c3afc3d-2d1c-487c-8275-13027b1d1657)

**Comment by alishaevn** [comment]
Deployed to https://collections-test.library.yale.edu/: Branch:v1.30.0,Deployed:2020-10-08T14:21:24-04:00

**Comment by mark-dce** [comment]
@FCRodriguez7 I'm not sure where this issue would show up or how I would sign off on the fix.  Can you provide steps to reproduce the user facing error and or define the user facing acceptance criteria?
