### ISSUE TITLE
Batch Detail Page

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#648]
~**OLD Acceptance**
As a user I want to see if the batch process for a given parent object is successful, in process, queued, in error (we don't recognize the exception state) or failed (we recognize why this didn't process). If the parent object is in process, I want to know the most recent event that it has completed (see #647)~

**ACCEPTANCE**
- [x] Parent OID links to Parent Job Status Page
- [x] Link back to Batch Listing page
- [x] Start Time
- [ ] [Bonus] Duration
- [x] Status roll-up
- [x] Link to Manifest
- [x] List of Parent Jobs associated with manifest

**DESIGN DOCUMENT**
https://docs.google.com/document/d/1X-KqIBasDKRmZSmwQ2D-QJ3kjYUOu4GwdOmJKkvNM0s/edit?usp=sharing

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/917a6f86-d518-47d6-8ff6-475b8765e098)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-management/pull/377
https://github.com/yalelibrary/yul-dc-management/pull/379
https://github.com/yalelibrary/yul-dc-management/pull/381
https://github.com/yalelibrary/yul-dc-management/pull/382
