### ISSUE TITLE
Set up manifest service in Yale SpinUp

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#65]
**ACCEPTANCE**
Given a docker image corresponding to https://github.com/yalelibrary/yul-dc-iiif-manifest
 - [ ] I can access it when it's running on a SpinUp instance

**Comment by geekscruff** [comment]
Same comment as before. Why aren't we setting up the three services?

**Comment by mark-dce** [comment]
I was trying to break the work down into the smallest independent units possible.  I was targeting the manifest service first because it seems like it has the fewest external dependencies.  Once we had that under our belt, I figured it would be easier to estimate "add image service" and "add blacklight (+solr)"

**Comment by DraxIndustries79** [comment]
per @kbcarter http://spinup-00104e-iiifmanifest.svc.spinup.yale.edu

**Comment by kbcarter** [comment]
Redeployed container **notch8/yul-dc-iiif-manifest** in Yale's SpinUp Service.
