### ISSUE TITLE
Views not updating in development mode on management

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#650]
When I update a view in management (starting from the management directory), the views are not updating as I would expect in dev mode on a rails app. 

I believe we saw this in Blacklight at some point and it was fixed.

To re-create:
- Bring up management locally using Yale AWS credentials, with cam, from the management directory (`VPN=false cam up management`)
- Bonus round: Make a failing-then-passing test for next step.
- Update a view in such a way that it should be super obvious on the page (add `Rob presumably enjoys bicycles` or something)
- Refresh page - change will not appear
- Restart management container (`VPN=false cam restart management`) - change will now appear

**Comment by orangewolf** [comment]
This is a known regression in Docker for Mac in 2.4.0.0 - see https://github.com/rails/rails/issues/25186. https://github.com/docker/for-mac/issues/4962.  Looks like you can turn off grpc_fuse (which came out in 2.4.0.0) or upgrade to the prerelease mentioned in the docker issue thread.

**Comment by alishaevn** [comment]
upgrading docker desktop for mac from `v2.4.0.0` to `v2.4.0.1` fixed the issue for me.

_I probably should have shut down the running server before I shut down and restarted docker, so after the restart I also wound up having to:_
- run `cam stop`
- `VPN=false cam up` in the blacklight repo
- shut down the blacklight app after it had done the necessary pulls/downloads/etc
- run `VPN=false cam up management` from the management repo

success!
