### ISSUE TITLE
Management app reports actual versions running

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#654]
**ISSUE**
Now that we've split out the deployments of some containers like Solr & Postgres, we can have different versions deployed than are listed in the management application.  This is misleading and could lead to inadvertent data or diagnostic conflicts.

**ACCEPTANCE**
- [x] Remove container versions (solr, postgres, and camerata) that are not actually controlled by the deploy script for the management application

**Comment by K8Sewell** [comment]
PR up for removing those 3 rows from the dashboard - https://github.com/yalelibrary/yul-dc-management/pull/355

### Screenshot
<details>
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/38e8a561-d2a6-40b5-ae5f-d6509334235c)
</details>

**Comment by K8Sewell** [comment]
![image.png](https://images.zenhubusercontent.com/5eac63d9b58bd7046578e120/ffcef4de-02dd-45f3-a475-cd36b5d37ce3)

Rows no longer present on Demo
