### ISSUE TITLE
Implement Staging ECS Cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#655]
**ACCEPTANCE**
We have a staging cluster running all the services:
- [x] collections-staging.library.yale.edu/  - blacklight
- [ ] ~iiif-staging.library.yale.edu/image/2/ - cantaloupe~
- [x] ~iiif-staging.library.yale.edu/manifests/ - manifests~
- [x] management-collections-staging.library.yale.edu/ - management [can be a different DNS and behind VPN]
- [x] solr-staging
- [x] postgres-staging
- [x] management-worker-staging
- [x] All containers & clusters are configured identically (memory, cpu, disk) to production

- [x] We can successfully ingest content to the new cluster
- [x] We can view content on the new cluster

**NOTE: Updated URLS for IIIF**
- [x] collections-staging.library.yale.edu/ - blacklight
- [x] collections-staging.library.yale.edu/iiif/2/ - cantaloupe IIIF API 2.x endpoint
- [x] collections-staging.library.yale.edu/manifests/ - manifests~

**Comment by bobrice** [comment]
The staging cluster is set up and running at...

https://alb-yul-dc-staging-1178206805.us-east-1.elb.amazonaws.com

DNS entries are forthcoming.

**Comment by ra359** [comment]
These are resolving on the internet now:

$ host collections-staging.library.yale.edu
collections-staging.library.yale.edu is an alias for alb-yul-dc-staging-1178206805.us-east-1.elb.amazonaws.com.
alb-yul-dc-staging-1178206805.us-east-1.elb.amazonaws.com has address 34.236.30.93
alb-yul-dc-staging-1178206805.us-east-1.elb.amazonaws.com has address 52.54.157.174

$ host collections-ingest.library.yale.edu 
collections-ingest.library.yale.edu is an alias for alb-yul-dc-ingest-949437022.us-east-1.elb.amazonaws.com.
alb-yul-dc-ingest-949437022.us-east-1.elb.amazonaws.com has address 3.94.1.143
alb-yul-dc-ingest-949437022.us-east-1.elb.amazonaws.com has address 52.204.107.204

**Comment by bobrice** [comment]
Parameters have been created

/yul-dc-staging/IIIF_MANIFESTS_BASE_URL
/yul-dc-staging/IIIF_IMAGE_BASE_URL
/yul-dc-staging/BLACKLIGHT_BASE_URL

**Comment by fnibbit** [comment]
/yul-dc-staging/IIIF_IMAGE_BASE_URL and /yul-dc-staging/IIIF_MANIFESTS_BASE_URL should reflect that the agreed on URIs for cantaloupe (images) and manifests start with "iiif-staging.library.yale.edu/image/2/"
 "iiif-staging.library.yale.edu/manifests/" as in the acceptance criteria in the top of the ticket. 

Right now, /yul-dc-staging/IIIF_IMAGE_BASE_URL is set to "https://collections-staging.library.yale.edu/iiif"; it should be "https://iiif-staging.library.yale.edu/image/2".  

Right now, /yul-dc-staging/IIIF_MANIFESTS_BASE_URL is set to "https://collections-staging.library.yale.edu/manifests"; it should be "https://iiif-staging.library.yale.edu/manifests".

**Comment by fnibbit** [comment]
And right now when I get on the VPN and go to urls starting with "https://iiif-staging.library.yale.edu" I get

"This site can’t be reached
iiif-staging.library.yale.edu’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by fnibbit** [comment]
S3_SOURCE_BUCKET_NAME: I remember a conversation about using different piles of ptiffs for staging+production than for test/uat/demo; right now everybody and their cousin is pointing at yul-dc-image-samples.

**Comment by ra359** [comment]
iiif-staging.library.yale.edu CNAME requested via INC1867749

**Comment by fnibbit** [comment]
The iiif image endpoints being at "iiif" rather than "image" is hard-coded in cantaloupe, which would make using 
"https://iiif-staging.library.yale.edu/image/2" a bigger lift/maintenance commitment than using "https://iiif-staging.library.yale.edu/iiif/2"; would the latter be acceptable?

https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/main/java/edu/illinois/library/cantaloupe/resource/Route.java#L21-L23
src/main/java/edu/illinois/library/cantaloupe/resource/Route.java:21-23
    public static final String IIIF_1_PATH        = "/iiif/1";
    public static final String IIIF_2_PATH        = "/iiif/2";
    public static final String IIIF_3_PATH        = "/iiif/3";

**Comment by dl-maura** [comment]
Need to find out if images/iiif is do-able
