### ISSUE TITLE
Implement Production ECS Cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#656]
**ACCEPTANCE**
We have a production cluster running all the services:
- [x] collections.library.yale.edu/  - blacklight
- [x] collections.library.yale.edu/management  - management [can be a different DNS and behind VPN]
- [x] solr-prod
- [x] postgres-prod
- [x] management-worker-prod
- [x] All containers & clusters are configured identically (memory, cpu, disk) to staging
- [x] We can successfully ingest content to the new cluster
- [x] We can view content on the new cluster

**NOTE: Updated URLS for IIIF**
- [x] collections.library.yale.edu/ - blacklight
- [x] collections.library.yale.edu/iiif/2/ - cantaloupe IIIF API 2.x endpoint
- [x] collections.library.yale.edu/manifests/ - manifests~

**Comment by bobrice** [comment]
The production cluster is up and available at...
A-record: collections.library.yale.edu
Target: alb-yul-dc-prod-140579099.us-east-1.elb.amazonaws.com
