### ISSUE TITLE
Build Ingest Test ECS cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#657]
**ACCEPTANCE**
- [x] We have cluster we can run ingest tests against without contending with folks using Test or UAT clusters
- [ ] We can visit collections-ingest.library.yale.edu and view the blacklight management images (100-150 items)

**Comment by bobrice** [comment]
The staging cluster is set up and running at...

https://alb-yul-dc-ingest-1178206805.us-east-1.elb.amazonaws.com

DNS entries are forthcoming.

**Comment by DraxIndustries79** [comment]
Waiting on domain names to get registered.

**Comment by ra359** [comment]
ServiceNow ticket INC1865429 - DNS changes assigned to Yale hostmaster

**Comment by bobrice** [comment]
DNS changes have been completed.

**Comment by bobrice** [comment]
parameters URLs have been created

/yul-dc-ingest/IIIF_MANIFESTS_BASE_URL
/yul-dc-ingest/BLACKLIGHT_BASE_URL
/yul-dc-ingest/IIIF_IMAGE_BASE_URL

**Comment by fnibbit** [comment]
There need to be new deploys (cam deploy-main and cam deploy-worker, not just stop and restart task) in order for the SSM updates to be picked up.
