### ISSUE TITLE
Restrict public access to the management application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#659]
**STORY**
We would like to protect the management application from public access by restricting it to on-campus/vpn access only.  We would like to protect management app independently of the Blacklight app.

**ACCEPTANCE**
- [ ] we can access the management application when connected to the VPN
- [ ] the management application cannot be accessed from the public internet

- [ ] We have updated each cluster
    - [ ] test
    - [ ] infra
    - [ ] uat
    - [ ] demo
    - [ ] staging
    - [ ] production

**Comment by ra359** [comment]
I believe we will need to stand up a separate ALB for management.collections-XXX.library.yale.edu .The target group for this will have it's own Security Group ACL.
