### ISSUE TITLE
Set up manifest service on ECS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#66]
**ACCEPTANCE**
Given a docker image corresponding to https://github.com/yalelibrary/yul-dc-iiif-manifest
 - [x] I can access it when it's running on an ECS cluster
      - [x] In Yale's AWS partner account
      - [x] In DCE's hosting AWS account: http://ec2co-ecsel-vpiqpyupumvj-996102624.us-east-1.elb.amazonaws.com/
      - [ ] [Optional] in an N8 AWS account

**Comment by geekscruff** [comment]
Why not broaden this out to ... setup a cluster containing the three services (image service, manifests service and blacklight)? And in so doing, create a cloud formation template for the deployment.

I don't see any value in doing this in a N8 space, better to pair on it.

**Comment by DraxIndustries79** [comment]
@mlooney and @kbcarter to pair

**Comment by kbcarter** [comment]
Yale ECS deployment: http://ec2co-ecsel-w8pev7zcu4x1-172076313.us-east-1.elb.amazonaws.com
