### ISSUE TITLE
Thumbnails do not work as expected

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#661]
## Images don't display
![Screen Shot 2020-10-07 at 10.47.07 AM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/c020fa1e-ba1c-4cbd-b8e6-dece8872f665)

Browser can't resolve images with urls similar to: http://iiif_image:8182/iiif/2/1030368/full/!200,200/0/default.jpg

**Comment by maxkadel** [comment]
Working fine for me locally - seems like a dev environment issue
![image](https://user-images.githubusercontent.com/45948126/95384545-c5c6a000-08ba-11eb-9d31-9f3f34966ccb.png)

Might want to check that you don't have multiple containers trying to run on that port. Also be sure that if you're working while on the Yale VPN you have updated your Docker settings, as documented here - https://github.com/yalelibrary/yul-dc-management#troubleshooting .

**Comment by mark-dce** [comment]
Issue appears to have been resolved
