### ISSUE TITLE
Add height and width as S3 metadata when writing PTIFF

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#662]
When writing the PTIFF to S3, add metadata values to the S3 object containing height and width.   In the future this data could allow the management application to quickly create child objects and manifests using existing PTIFF images without requiring a separate JSON file containing the image height and width.

Acceptance criteria:
- [ ] The PTIFF object in S3 has a metadata entry for `height` with the height in pixels of the PTIFF as its value
- [ ] The PTIFF object in S3 has a metadata entry for `width` with the width in pixels of the PTIFF as its value
- [ ] When retrieving the `object.metadata` for the PTIFF object, the hash contains these keys/values

See`metadata` in 
* https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Bucket.html#put_object-instance_method 
* https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#metadata-instance_method

**Comment by martinlovell** [comment]
Draft PR here:  https://github.com/yalelibrary/yul-dc-management/pull/342

I need help on setting up some tests.  (I'm not able to figure out how S3 client works in the tests.)

**Comment by martinlovell** [comment]
I was able to add some tests to the AWS stubs to make sure that the right headers were getting passed.
It verifies that the correct headers are sent when we make the AWS call.

(Still haven't tested with real AWS.)

**Comment by mark-dce** [comment]
Moving back to "Review on Test" to check PR from @maxkadel before accepting

**Comment by dl-maura** [comment]
Can test by ingesting unique object
