### ISSUE TITLE
Spike: Manifest Authentication Test

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#663]
# Acceptance #
We need data on how hard / easy it might be to use CAS to authenitcate manifest requests. Do we even need a more complex system or will it redirect correctly?

This spike should set up a dummy end point on management (which is already behind CAS), then hit that end point from Blacklight starting with Blacklight logged in, but management not logged in.  There may be CORs issues here that need to be resolved.

**Comment by orangewolf** [comment]
Even when you are logged in to CAS in both apps, it will not connect for the manifests. It tries to do the redirect but fails for CORs at the CAS server level. A pure CAS based solution therefor seems unlikely to be workable.

**Comment by mark-dce** [comment]
@orangewolf - can you write up your notes in the discussion doc here: https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#

Once that's done, I think you can close this ticket.
