### ISSUE TITLE
Allow developers to bring up local versions of more than one application

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#666]
As a developer, I want to be able to work on multiple containers locally to see how changes across containers interact.

Ideally, the user could somehow choose which applications to mount locally and where they are, and run there.

If it's too hard to specify, maybe there could be a way to run cam from a directory containing blacklight and management, and run those locally for blacklight, management, and management workers.

The best option would be having some way to run SOLR locally too so that it's possible to change the solr config locally and test with blacklight and manement workers.

**Comment by mark-dce** [comment]
@martinlovell @orangewolf @maxkadel I think this is possible now using various camerata commands.  Does that sound right & is this ticket closable, or is there more work to do here that we should consider in Phase 2?
