### ISSUE TITLE
Switch Thumbnail Placeholder images

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#667]
## Swap Images

This is placeholder_restricted.png
![placeholder_restricted.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/aaefd617-94eb-4b1a-bd44-bccf87cb437a)

This is image_not_found.png
![image_not_found.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/3ac4c6f5-f6fc-48b1-acea-129b64ec3043)

- [ ] These need to be switched!

**Comment by dl-maura** [comment]
Made the switch, but can't really test this locally? Restrictions are pulled from LadyBird, so I can't set something to private, and I can't create a parent without images and get a SOLR record. Do we have a workaround?

**Comment by dl-maura** [comment]
Will submit a PR and a human will look at them!

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/dfd9a067-accc-4dc4-9290-0f437e0abd50)
