### ISSUE TITLE
Ingest 10,000 additional public items to DEMO

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#673]
**STORY**
As a stakeholder, I'd like to see an even wider variety of materials in the new system, so that I can have a better sense of how I will be able to discover and use resources.

**ACCEPTANCE**
- [x] Performing a search on https://collections-demo.library.yale.edu returns at least 10,000 search results
    - [x]  Items display short metadata in search result listings
    - [x]  Items display thumbnails in search result listings
    - [x]  Items display full metadata in single item views
    - [x]  Items display pan & zoomable images in single item views

**Comment by ra359** [comment]
INC1867786 - new VM for metadata-api-uat.library.yale.internal

**Comment by mlooney** [comment]
10k import in process, approx 20% done at the time of this writing

**Comment by mlooney** [comment]
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/c0dcd294-8158-4ffd-a255-81e1fa9c1aeb)
