### ISSUE TITLE
Parent Job Detail Page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#675]
**ACCEPTANCE**
- [x] Link back to BatchJob Detail page
- [x] Start Time
- [x] [Bonus] Duration
- [x] Parent OID
- [x] Status roll-up
- [x] Metdata Status
- [x] Maifest Status
- [x] Index Status
- [x] <s>List of child image jobs</s> (Currently lists & links to child objects and shows last time the PTIFF was recorded, since child object batch info is not done yet)
- [x] Needs to be implemented as a data table

**DESIGN DOCUMENT**
https://docs.google.com/document/d/1X-KqIBasDKRmZSmwQ2D-QJ3kjYUOu4GwdOmJKkvNM0s/edit?usp=sharing

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/e1965450-109f-47a8-947c-ddc8843d9865)

**Comment by alishaevn** [comment]
is anyone familiar with this spec failure?
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/5e99385d-27a5-48cf-9cfe-3c9faf08e34c)

**Comment by maxkadel** [comment]
![Uploading image.png…]()

**Comment by dl-maura** [comment]
Metadata Fetched 2020-11-09 17:30:59 UTC

Manifest Built 2020-11-09 17:46:34 UTC

Metadata Indexed 2020-11-09 17:46:37 UTC

If these don't have data, have some sort of placeholder: 'Pending'

**Comment by alishaevn** [comment]
Co-author: JP Engstrom <jp@notch8.com>

# MR
https://github.com/yalelibrary/yul-dc-management/pull/402

# Summary
If the Metadata Fetched/Indexed/Built headings don't have data, it will say "Pending"

# Demo
![image](https://user-images.githubusercontent.com/29032869/99284610-51511c00-27eb-11eb-9ed7-163b1961d7ee.png)
