### ISSUE TITLE
Update Cursor on Drop down caret

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#677]
The main menu in the blacklight app has a drop-down caret.  It has a text cursor.  Since it's a link, it should have a pointer cursor.

The requirements to update:
- [x] text cursor,  and caret, [completed in milestone 2020-50]
- [x] additional requirement of the space in between the text and the now arrow. 

(css class may be nav-link-caret)

**Comment by FCRodriguez7** [comment]
Code modification, its no longer a text: 
￼
![16 mmmm appviewsshared_header_navbar.html.erb.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8862b82a-02b3-4b88-a8c2-04c26370ffd5)


https://github.com/yalelibrary/yul-dc-blacklight/pull/433

**Comment by maxkadel** [comment]
I think it would be nice if the whole object, including the arrows, had a single hover behavior - right now:

- Link text - underlined with hand
- Space - nothing with cursor
- Caret - nothin with arrow

**Comment by FCRodriguez7** [comment]
I modified the code earlier for the click function to work in a way that allows the user to click anywhere on the words or arrow. I think this is acceptable.

**Comment by FCRodriguez7** [comment]
The PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/439

---

![Screen Shot 2020-12-09 at 11.58.01 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/8c9a5f6b-7ec5-4eb2-9493-b1d6c47314b8)


----


![Screen Shot 2020-12-09 at 11.57.59 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5244a7cc-8df1-4f53-8296-625c2327ac8f)


-----

![Screen Shot 2020-12-09 at 11.57.56 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c85189e8-a06d-4852-a2cf-83ba837c045d)

-----

![Screen Shot 2020-12-09 at 11.57.53 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5ddba262-b549-4425-9835-a7dc6f9914ce)

**Comment by FCRodriguez7** [comment]
**TEST ENVIRONMENT**

![Screen Recording 2020-12-09 at 03.45.09 PM-16 (dragged).tiff](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9ca2cbfb-a8aa-4df3-8ca3-87e76ecbdfe1)

**Comment by mark-dce** [comment]
In safari Version 14.0 (15610.1.28.1.9, 15610), I'm still seeing an arrow on UAT and a text insertion point on TEST.

In chrome Version 87.0.4280.88 (Official Build) (x86_64), I'm seeing the arrow on UAT, the hand pointer on Test, but there's still a strange text insertion point when I hover between the end of the text and the arrow.

Here's a quick screen capture of the above https://www.youtube.com/watch?v=V1HGKNDcVWM

**Comment by FCRodriguez7** [comment]
The main menu in the blacklight app has a drop-down caret.  It has a text cursor.  Since it's a link, it should have a pointer cursor.

The requirements to update text cursor and caret were completed in milestone 2020-50.  The additional requirement of the space in between the text and the now arrow to have a finger cursor is now completed.  


![Screen Recording 2020-12-16 at 09.35.33 AM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/680aee44-917c-4a8c-9fe9-95d3b5dd669e)

**Comment by FCRodriguez7** [comment]
**Code on Test Environment**

![Screen Recording 2020-12-16 at 10.05.47 AM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1961732b-45f6-4eac-acfe-7693d04b8d1e)
