### ISSUE TITLE
Be able to prioritize job type independently

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#679]
**STORY**
When I add additional workers to a cluster, I want to be able to determine whether they work on PTIFF, metadata or other types of jobs

**ACCEPTANCE**
- [ ] We can target how many workers are allocated to a particular job type / queue

**STEPS**
- [x] Add a named queue to each worker type in the mangement application
- [x] In Camerata, specify that the main workers will work all the named queues EXCEPT the pdf queue (both dev and prod)
- [x] In Camerata, create a new worker that runs only PDF queue (both dev and prod)

**Comment by orangewolf** [comment]
This can be done by either priority or by queue names. See conversation and poll in slack for more context and information.

**Comment by orangewolf** [comment]
List of named queues:

manifest
pdf
ptiff
zeros
metadata
solr_index

**Comment by orangewolf** [comment]
Queue names - https://github.com/yalelibrary/yul-dc-management/pull/407

**Comment by JzGo** [comment]
Draft PR: [specify worker queues](https://github.com/yalelibrary/yul-dc-camerata/pull/271) 

So far the PR:
- adds `pdf-worker-compose` templates
- applies applicable template files to the **local** set in camerata
- sets up the `pdf_worker` as a dependency of the management app

When `cam up management` is run, one should see a `pdf_worker` spin up along with the `management_worker`.
Running `cam sh pdf_worker` should allow you to shell into the pdf_worker as well.

Next steps:
- [ ] Test that locally: **pdf_worker** runs **pdf** jobs and **management_worker** runs the rest
- [ ] Update `deploy-worker.sh` or create a new `deploy-pdf-worker.sh` script to deploy the **pdf-worker** ensuring that it can be run via camerata wrapper
- [ ] Test that the workers run the expected jobs on a deployed **ecs** environment
- [ ] If applicable, apply deploy script to Jenkins

**Note**: I've attempted to specify queues by passing in an env var (**QUEUE(S)**) into the template files. This was my first pass at this using Rob's link as a guide (https://github.com/collectiveidea/delayed_job#named-queues) so some tweaking may be required.

**Comment by orangewolf** [comment]
this is pending https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/950 but the coding part is wrapped up.
