### ISSUE TITLE
Edge/IE Version Information and Testing

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#682]
We need to know which versions of IE/Edge are in use at Yale, which we need to support/test, and how to test if they aren't readily available.

**Comment by mikeapp** [comment]
Both IE 11 and various Edge versions are available on staff systems and the VDI systems

**Comment by mikeapp** [comment]
Libguides shows a warning to IE 11 users: 
```
<div id="obsolete_browser_alert" class="alert alert-danger obsolete_browser_alert">
    It looks like you&#039;re using Internet Explorer 11 or older. This website works best with modern browsers such as the latest versions of Chrome, Firefox, Safari, and Edge. If you continue with this browser, you may see unexpected results.
</div>
```

**Comment by mikeapp** [comment]
Only 3% use Edge, IE < 1%

**Comment by dl-maura** [comment]
Decision: Use VDI version, but beyond that, we can't support all versions of IE/Edge available
