### ISSUE TITLE
Update SOLR for consistency with latest MC

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#683]
We have changed fields in the latest MC, need to change SOLR code to match. May be blocked by versioning work?
- [x] author -> creator
- [x] IdentifierShelfMark -> callNumber (LB and ILS only? Don't think that this exists in Aspace)
- [x] geoSubject -> subjectGeographic
- [x] partOf -> sourceTitle (need to test this, correct for LB, not sure how it affects aspace/voyager)
- [x] change box to [rename] containerGrouping (for consistency with aspace and voyager)
- [x] check for other changes to MC
     - [x] publicationPlace_ssim: json_to_index["creationPlace"]
     - [x] publicationPlace_tesim: json_to_index["creationPlace"]
     - [x] references_ssim: json_to_index["preferredCitation"]
     - [x] references_tesim: json_to_index["preferredCitation"]

Update SOLR mappings in blacklight to match.
Blacklight labels do not have to correspond based on these updates, that will be different ticket work as some will be different for reading comprehension purposes

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/426
