### ISSUE TITLE
Change Publication Date Label (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#684]
Not everything we have is 'published' so we need to change this label

Ideally (mimicking FIndIt):
 - [x] The metadata label would be Published/Created in index page and show page
 - [x] The facet label would be 'Date Created'

**Comment by MaggieZhaoYale** [comment]
The date_ssim and dateStructured_ssim are not always the same. 
e.g. if dateStructured_ssim is 1986, date_ssim is 1971
In one of our old system, we have facet date, display date, sort date and search date use different fields, and may have inconsistent sorting or search result. 
It is reasonable that the date_ssim, and dateStructured_ssim are both used as the search date;
I wonder if the sort date also sorted by the same values as the search fields. (I know it is not in the scope of this ticket)
