### ISSUE TITLE
Management as source of authority for some aspects of parent object

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#686]
Once a legacy parent object has been ingested, from that point on use the Management application as the source of authority (meaning do not overwrite from ladybird or other authoritative metadata source) for:
- [x] visibility
- [x] reading_direction -> viewing direction **(not in solr index)**
- [x] pagination - > display_layout **(not in solr index)**
- [x] child object count
- [x] bib number (voyager / ils)
- [x] holding (voyager / ils) **(not in solr index)**
- [x] item (voyager / ils) **(not in solr index)**
- [x] barcode
- [x] aspace uri

**Comment by dl-maura** [comment]
See also ##669

**Comment by MaggieZhaoYale** [comment]
viewing direction, display_layout,holding and item are not in the solr index.
