### ISSUE TITLE
Provide unauthenticated access to OID Minter

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#688]
The OID minter ended up behind CAS when we moved away from basic auth.  This is blocking work by Intranda.  

Acceptance:
- [x] OID minter is exposed without a login 
- [x] OID minter does not require (or log) `current_user`
- [x] OID minter does log requesting IP
- [x] access is verified from the Goobi server (needs @dl-maura to check)

**Comment by martinlovell** [comment]
Created PR: https://github.com/yalelibrary/yul-dc-management/pull/346
Not sure how to check checkbox 1 above before deploy.

**Comment by mikeapp** [comment]
We plan to have the management app restricted on all servers, so I think checkbox 1 is done by default.    I think the true test is requesting an OID (via `curl` or similar) from the Goobi box, perhaps @dl-maura could do this.

**Comment by mikeapp** [comment]
I'll change the first requirement to "is accessible from the Goobi server"

**Comment by dl-maura** [comment]
works on test and uat with a curl from goobi
