### ISSUE TITLE
Manifest generation failing on Demo

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#689]
It appears that the width and height are being recorded as 0 for child objects, and that the parent_object is being marked as ready for manifest creation when that happens, at which point the manifest creation errors out because width and height must be > 0

**Comment by mlooney** [comment]
clue: This has only been observed when regenerating existing oids. For instance, albergatti's bible has many pages with correct wxh, but also many pages where wxh are both 0.

**Comment by dl-maura** [comment]
OID: 2003431
