### ISSUE TITLE
Solr Core with Sample Data from Voyager

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#69]
**ACCEPTANCE**
- [x] I can easily build, load, populate a solr index with metadata for our sample objects
- [x] There are 40 objects with title, OIDs, and any other key fields required by blacklight
- [x] Populated with metadata for the public Beinecke sample works (raw metadata available on S3), including at least:
  - [x] Title
  - [x] OID
  - [x] Creator
  - [x] Description
  - [ ] ~Date~ [AFAICT, there is no publication date field in these voyager records]

**Comment by bess** [comment]
![Screen Shot 2020-04-21 at 3.20.06 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/bca9b008-6462-4535-b665-97af08141a77)

![Screen Shot 2020-04-21 at 3.19.52 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/9e013b12-d2d5-4314-bc35-98d463c2c450)
