### ISSUE TITLE
Facet Should Not Carry Over to Advanced Search

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#690]
I did a facet for a creator, then went to the advanced search. Per RH, we don't want this, Advanced Search should be a clear search, so need to address this behavior (marked as bug).

![Screen Shot 2020-10-15 at 11.34.41 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/389c1793-7689-4ec1-8baf-a431784372de)

**Comment by maxkadel** [comment]
Unless this was a previously requested change that wasn't fully implemented, this reflects default functionality and I wouldn't call it a bug, I'd call it a feature request.

**Comment by martinlovell** [comment]
Should this just clear the facets clicked on the index page, and not the other search terms?

For instance, if I go to advanced search and search by Creator for "john", and then go back to advanced search, should Creator be cleared?

**Comment by dl-maura** [comment]
@martinlovell Per @rebeccahirsch it should clear, when we go to advanced we want a clean search
