### ISSUE TITLE
Make S3 bucket for Dev / test images 

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#692]
- [x]  Make S3 bucket for Dev / test images. Should include the originals and ptiffs from the current `yul-dc-image-samples` bucket in the pair-tree structure (easiest would be to copy whole bucket / directories, cheapest would be to only copy those associated with the original sample objects) 
- [x] Update camerata to default to this new bucket in local development 
- [x] Clusters to buckets
  - [x] Prod-staging
  - [x] test uat demo
  - [x] local development

**Comment by kbcarter** [comment]
Created the image bucket for dev/test: **yul-dc-dev-image-samples**

We currently have 3 image buckets:
-  yul-dc-dev-image-samples (dev and test)
-  yul-dc-images-samples (uat and demo)
-  yul-dc-prod-image-samples (staging and prod)

**Comment by kbcarter** [comment]
Changed the prod image bucket to **yul-dc-prod-images**

**Comment by fnibbit** [comment]
I see an "originals" directory tree on yul-dc-dev-image-samples but no "ptiffs" directory tree; can we have a copy of the ptiffs for the same set of images as the originals that are in that bucket?

**Comment by K8Sewell** [comment]
We were able to set up the copy of a ptiff folder but wanted to check in regarding size / limit because it's almost 2 TB of data - so wasn't super confident that I should execute the copy of the folders myself.  Would be happy to pair on this tomorrow morning.

**Comment by K8Sewell** [comment]
### Next steps:
- [ ] Connect w/ Software Engineering re: ideal # of parent objects for local development (understanding that if additional records are needed they have access to oid short lists and can add more through their local environment - in /management )
- [ ] Copy only originals folder (est. 45 parent objects) and their corresponding ptiffs folder (est. 5000 child objects) of ideal # as defined above into the **yul-dc-dev-image-samples** image bucket on AWS
- [ ] Double check that on spinning up a local development environment it includes the expected number of parent objects to begin with
- [ ] Double check that on ingesting records locally (adding more records to local development environment through the /management portion of the app) - these records are reflected as also added to the correct AWS image bucket **yul-dc-dev-image-samples**

**Comment by fnibbit** [comment]
amendment to the second point above (apologies that I didn't put this together earlier): there are the same (larger) number of "originals" (access-master image files) as the number of child objects and ptiffs.  Each parent object has many originals.  (Said this in conversation with Kait+Ric but wanted to connect the dots.) 

The originals and ptiffs folders are both organized in a pair tree structure by *child* oid, so copying the right things to the right place on S3 will be a bit more complicated than moving whole folders I believe.

**Comment by K8Sewell** [comment]
While I still need to poll to identify the ideal number of sample objects the PR to connect local dev to the s3 buckets for local development is ready for review. https://github.com/yalelibrary/yul-dc-camerata/pull/240

**Comment by fnibbit** [comment]
Put in a merge commit to satisfy some conflicts.

**Comment by K8Sewell** [comment]
PR merged.  Awaiting poll results to preload the s3 sample buckets with adequate number of objects.
