### ISSUE TITLE
Finish Gap Load

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#693]
These two can happen simultaneously:
- [x] Locate 1540 missing images from gap load.
- [x] rescan directories containing missing images.
- [x] Start copying images that are ready  (There are over 70,000 ready already. We can start with those and then rerun to get the missing ones.)

**Comment by dl-maura** [comment]
DevOps is fixing an issue

**Comment by dl-maura** [comment]
Copy is finished per ML
