### ISSUE TITLE
[Check] Advanced Search 'Any Of' Styling Issue (Safari)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#696]
Any of has no styling and is to the wrong side (if we want to display it). Also seems to prevent me from changing views in Safari (no issues when I have the All, also no issues in Firefox or Chrome). Possibly 2 tickets

![Screen Shot 2020-10-16 at 3.03.53 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c3138986-f60c-44a7-b79f-848c2f98495b)

**Comment by jpengst** [comment]
Have not seen this issue on production, test, or uat.
