### ISSUE TITLE
Log to stdout from Management

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#697]
Blacklight commit - 8bee47d5 

Apparently the only logs we are seeing from management are the boot process logs, and nothing else.

**Comment by dl-maura** [comment]
Do the same thing from that commit above in management

**Comment by alishaevn** [comment]
all of the file changes on the blacklight app in [PR 186](https://github.com/yalelibrary/yul-dc-blacklight/pull/186/files) were also already completed in the management app on [PR 166](https://github.com/yalelibrary/yul-dc-management/pull/166/files).

the management PR does have 2 additional file changes at the bottom that the blacklight PR doesn't have, but I'm unsure if that's actually the cause of not seeing the logs in management.
