### ISSUE TITLE
Add IIIF fields to Parent Object Display page and Be Editable

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#698]
I want to be able to see what the Viewing Direction and Display Layout of a parent are, and also be able to change them in the app.

- [ ] Can see IIIF data in Parent Object View and Edit
- [ ] can update IIIF data for Parent in Edit screen (nil/blank is allowed)

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/bb7a4e5a-fdee-4e4b-86af-75970d9dea03)

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/a1801895-b77b-473f-99b5-5ad6d71c6b89)

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3c1ed116-c5b1-48ff-ab78-57e6f1414fe3)

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/d37afbbe-de0a-4476-9e2b-8c0df9400b9e)
