### ISSUE TITLE
Display Selected Parent Fields as Read-Only

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#700]
**ACCEPTANCE**
When Editing a parent record in the management application,
I should be able to view, but not the following fields:
- [x] Parent OID
- [ ] ~~Last LB updated~~
- [ ] ~~Last voyager update~~
- [ ] ~~Last aspace update~~

**Comment by maxkadel** [comment]
Before:
![image](https://user-images.githubusercontent.com/45948126/102666479-0bbea080-4155-11eb-8497-45a8167c3432.png)

After:
![image](https://user-images.githubusercontent.com/45948126/102666341-a66aaf80-4154-11eb-8661-24a69d434897.png)

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/management/parent_objects/17290054/edit
![image](https://user-images.githubusercontent.com/45948126/102925960-36b13900-4462-11eb-8796-20c6e56d8594.png)
