### ISSUE TITLE
Validation for Parent Object Data (METS)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#701]
We need to validate the following before allowing a new item to be imported:
- [x] Rights Statement (this is required, only validation is can't be nil)
- [x] ASpace URI (formatting only)
- [x] Voyager (numerical only)
NOTE: In the future Morris library will have a "b" at the end of Voyager IDs

Non-formatting?
- [ ] If ASpace URI returns no record, don't save, give error
- [ ] If voyager does not return record, don't save, give error

**Comment by maxkadel** [comment]
Questions:
- Rights statement: Is there a "most conservative" one we can put if none is provided? Or just not save
- ASpace URI: in the Ladybird data from the MetadataCloud, these look like "/repositories/11/archival_objects/304086". What about the formatting do we want to validate? Should they all be `/repositories/[some_number]/archival_objects/[another number]`? Is there other variation we can expect?
- Voyager: That the `orbisBibId` is a number? That the holding, item, and barcode, if present, are numbers?
- For checking ASpace and Voyager - does that mean if we don't get a record from the MetadataCloud don't save? Or would we check against something else?

**Comment by dl-maura** [comment]
Questions:

Rights statement: Is there a "most conservative" one we can put if none is provided? Or just not save
**We have a default, but nothing can come in from goobi without a rights statement so if somehow it doesn't have a. rights statement we don't want it saved -- should error**
ASpace URI: in the Ladybird data from the MetadataCloud, these look like "/repositories/11/archival_objects/304086". What about the formatting do we want to validate? Should they all be /repositories/[some_number]/archival_objects/[another number]? Is there other variation we can expect?
**will always be /repositories/[some_number]/archival_objects/[another number] -> the 11 means brbl**
Voyager: That the orbisBibId is a number? That the holding, item, and barcode, if present, are numbers?
**Should all be numeric**
For checking ASpace and Voyager - does that mean if we don't get a record from the MetadataCloud don't save? Or would we check against something else?
**Nothing else to check against -- if it isn't turning up in MC there is a problem**

**Comment by dl-maura** [comment]
we do want to require barcode or holding or item
