### ISSUE TITLE
Rights Statement on parent Object

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#702]
For the parent object, I should get the rights statement and store it. If there is no rights statement (null value) do not save the record.

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/102923201-56922e00-445d-11eb-9c6e-3217dd7dff89.png)

- Note, this has not been populated for legacy objects, although it is available in the Ladybird JSON. Might have to create a job to update these in the background.

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/management/parent_objects/17218176/edit
![image](https://user-images.githubusercontent.com/45948126/102926457-03bb7500-4463-11eb-810b-81dc119fe2b3.png)

**Comment by mark-dce** [comment]
I'm not seeing rights statements on any of the Parent Objects I'm trying to spot check on UAT, but I see them in the original JSON.  Does this mean we need to re-index the full repository for this ticket to be visible in the discovery application?

**Comment by dl-maura** [comment]
@mark-dce Some of them do have it -- wonder if some of the ones that don't were very early? See these for ones that have them in:
https://collections-uat.library.yale.edu/catalog/2011788 
https://collections-uat.library.yale.edu/catalog/2018372

**Comment by dl-maura** [comment]
This isn't updating when we tested it

**Comment by maxkadel** [comment]
See, for successful example - https://collections-test.library.yale.edu/management/parent_objects/2001466

**Comment by dl-maura** [comment]
I edited that one and that also works!

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/e1da52ba-40aa-4f01-bf4f-accbfd40c0d6)

**Comment by mark-dce** [comment]
And I was able to set it back 
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/7f15d290-9469-46b9-b915-d366379cad72)
