### ISSUE TITLE
Re-Indexing from the management app should not clear discovery

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#704]
**ISSSUE**
Currently when you trigger a reindex from the management application, the discovery application is reset to 0 search results and then rebuilds the index.  We should NEVER do this in a production environment.

**ACCEPTANCE**
When I trigger a re-index
- [x] Any solr IDs which don't correspond to a current OID in the management application are deleted
- [x] SolrIDs which correspond to a current OID are re-indexed without deleting them

**Comment by orangewolf** [comment]
Here is the orphan detection https://github.com/sunspot/sunspot/blob/aa236c157dac119781646f0453987714a0218c52/sunspot_rails/lib/sunspot/rails/searchable.rb#L340
