### ISSUE TITLE
Restrict manifests for non-Public works

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#705]
**ACCEPTANCE**
- For parent objects with 'public' visibility
  - [x] Manifests should always be returned
- For parent objects with 'yale community' visibility
  - [x] Manifests should be returned when the request comes from an 'on-campus' IP address
  - [x] Manifests should be returned when the request comes from an authenticated client
  - [x] The manifest service should return an HTTP unauthorized status when neither of the above conditions are met
- For parent objects with any other visibility setting (including nil)
  - [x] The manifest service should return an HTTP unauthorized (401) status

Move controlling monitors into blacklight service.

**REQUIREMENTS DISCUSSION**
For additional design background see: https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#heading=h.4m0k7rj0mta9

**Comment by orangewolf** [comment]
@alishaevn @jpengst and I decided to write the visibility to the S3 metadata for the manifests and then read the metadata on the blacklight side. We did some pseudocode to start this process.

Blacklight WIP branch - check_metadata_on_manifest_read
Management WIP branch - write_visibility_to_s3_metadata

**Comment by alishaevn** [comment]
Co-author: JP Engstrom <jp@notch8.com>
Co-author: Rob Kaufman <rob@notch8.com>

# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/412

# Summary
- manifests should be filtered according to whether they are set to "public" or "yale community only"
- although we don't have an example in the app of a yale only work or a work with the visibility prop set, we are testing for them both

# Demo
![albergati](https://user-images.githubusercontent.com/29032869/100135766-f351b380-2e3e-11eb-8519-39e292c67ea9.gif)

**Comment by orangewolf** [comment]
this now requires code in https://github.com/yalelibrary/yul-dc-blacklight/pull/415 (which enables the IP check)

**Comment by orangewolf** [comment]
Added assignees for the people I know have worked on the various chores and splits for this ticket. I'm sure someone has gotten missed and I'm not sure who took the devops tickets.

**Comment by maxkadel** [comment]
999957 - Yale Only - https://collections-uat.library.yale.edu/catalog/999957 
999981 - Private - https://collections-uat.library.yale.edu/catalog/999981

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/422

Summary
- if a manifest does not show because it does not have the visibility_ssi property, the user gets a 404 error
- if the user is not on campus or logged in with cas, they'll get a 401 error when viewing "yale community only" manifests
