### ISSUE TITLE
Restrict Images for non-public works

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#708]
**ACCEPTANCE**
- For parent objects with 'public' visibility
  - [x] Images should always be returned
- For parent objects with 'yale community' visibility
  - [x] Images should be returned when the request comes from an 'on-campus' IP address
  - [x] Images should be returned when the request comes from an authenticated client
  - [x] The image service should return an HTTP unauthorized status when neither of the above conditions are met
- For parent objects with any other visibility setting (including nil)
  - [x] The image service should return an HTTP unauthorized status

**REQUIREMENTS DISCUSSION**
For additional design background see: https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#heading=h.4m0k7rj0mta9

**Comment by orangewolf** [comment]
Possible path - https://github.com/ncr/rack-proxy

**Comment by orangewolf** [comment]
Ended up doing this in stead https://medium.com/@jefawks3/using-nginx-as-a-multi-step-reverse-proxy-to-authorize-requests-before-serving-content-on-s3-d4094577c60e

That lets Nginx do all the hard parts and was easier to make work for development as well as production.

The finishing of this ticket requires the following:

- Merge of the IP address checking
- When this is deployed Cantaloupe needs to be moved to /authorized-iiif and /iiif needs to be sent to Blacklight in the load balancer.
- Any manifests that say "localhost:8182" (ie the dev ones) should be rewritten to say "localhost:3000" instead.
