### ISSUE TITLE
Ingest 50,000 Items to UAT

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#711]
**STORY**
As a stakeholder, I'd like to see an even wider variety of materials in the new system, so that I can have a better sense of how I will be able to discover and use resources.

**DATA SOURCE**
50K public oids: CSV on Box https://yale.app.box.com/s/hkl1io2fnkps3h4nbxed8iim8dmj6v8u

**ACCEPTANCE**
- [ ] Performing a search on https://collections-uat.library.yale.edu returns at least 50,000 search results
    - [ ]  Items display short metadata in search result listings
    - [ ]  Items display thumbnails in search result listings
    - [ ]  Items display full metadata in single item views
    - [ ]  Items display pan & zoomable images in single item views

**BONUS ACCEPTANCE**
1000-object batch successfully uploaded - place orders with McClain!
- [x] McClain
- [x] Kait
- [x] Keith
- [x] Rachel K
- [x] Dylan
- [x] Ric
- [x] Bob
- [x] Jez

**Comment by K8Sewell** [comment]
Address for uploading - https://collections-uat.library.yale.edu/management/batch_processes

**Comment by DraxIndustries79** [comment]
Plan is to close this ticket when we have the final list to ingest to staging.
