### ISSUE TITLE
Use MetadataCloud version in calls to the metadata cloud api (not activity stream)

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#712]
- The MetadataCloud is versioning its API so that we can request a specific version. We will want to set this separately for different environments, and separately from the `METADATA_CLOUD_HOST` environment variable we currently have. 
- For the MetadataCloud documentation on this, see https://github.com/yalelibrary/metadata-cloud/blob/test/API_VERSIONING.md 

- [ ] Update Management to include the metadata version number in building the url for its calls to the MetadataCloud
  - [ ] If the management application gets the message "Unable to find retriever for source: [version]", it should raise an error (rather than falling back to an un-versioned call), since the version of the indexing code and the version of the metadata cloud are tightly coupled.

**Comment by dl-maura** [comment]
@mikeapp Please take a look and let us know your thoughts on versioning the activity stream.

**Comment by mikeapp** [comment]
I would not version the Activity Stream, at least for now.  If a new version comes out in the future we can deal with it at that time.
