### ISSUE TITLE
Make creator a facet/search reachable from item record (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#713]
As a user, I want to be able to click on the creator name to get a search of the creator.
![Screen Shot 2020-10-21 at 8.54.04 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/fd7ffa3c-1ab4-4f82-aa00-3c79be71d026)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-11-03 at 1.02.52 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b8a0eb28-1eff-4d58-99fc-94cbfadef33e)

**Comment by FCRodriguez7** [comment]
Test Environment

![Screen Shot 2020-11-03 at 1.20.18 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/337546aa-f54f-445d-b1d1-d05f6e9ad242)

**Comment by dl-maura** [comment]
Doesn't appear to work on test? See: https://collections-test.library.yale.edu/catalog/2001937

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/372

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/373

**Comment by dl-maura** [comment]
Remove the link search from search results page

**Comment by FCRodriguez7** [comment]
The bug for the creator link on the result page: https://github.com/yalelibrary/yul-dc-blacklight/pull/396

**Comment by FCRodriguez7** [comment]
Deployed the single branch: 


![Screen Shot 2020-11-13 at 2.47.07 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/e8711d2c-710b-4fec-a309-ef78a66382da)
