### ISSUE TITLE
Schedule ITS Performance Testing

### ISSUE THREAD

**Issue by bobrice** [yalelibrary/YUL-DC#714]
Gather information to pass on to ITS load balancing team.

There is a form we fill out.
- [x] Create testing steps for ITS
- [x] Answer questions we can answer
- [x] Schedule test with ITS

**Comment by ra359** [comment]
- [ ] Fill out Questionnaire for ITS
- [ ] Schedule initial test

**Comment by dl-maura** [comment]
Form and tests are sent, waiting to hear back on when we're scheduled
