### ISSUE TITLE
Build Staging & Production Environments

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#715]
**STORY**
Before going live, we need a public facing production environment.  For security and performance testing purposes, we'd like an identically provisioned staging environment where we can do destructive/hostile testing without affecting production end-users.

**ACCEPTANCE**
- [ ] There is a `staging` environment
- [ ] There is a `production` environment

**Comment by bobrice** [comment]
@mark-dce The clusters have been built identically and content has been loaded.  Is this complete?

**Comment by mark-dce** [comment]
I think we have Goobi and Metadata Cloud issues to address yet.  We could pull Goobi out to a separate epic, but I think triple checking MC issues should be done before we close this.
