### ISSUE TITLE
Shared Logging

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#717]
**STORY**
As a DevOps best practice, we want to ensure that logging is visible to the whole team responsible for the application - i.e. both DevOps and Software Engineering, so there is a common understanding of how the application is actually behaving and a shared source of truth for making design, development, and problem resolution decisions.

From [The 5 Foundational DevOps Practices](https://puppet.com/resources/whitepaper/5-foundational-devops-practices-how-establish-build-them/)
>Monitoring and alerting are configurable by the team operating the service. Monitoring and alerting are key to sharing information about how systems and applications are running, and getting everyone to a common
understanding. This common understanding is vital for making improvements, whether within a single team and function or across multiple teams and functions.

**ACCEPTANCE**
- [x] We have a common logging platform for all services in the DL system (AWS CloudWatch)
- [ ] All team members can access and view logs

**Comment by bobrice** [comment]
Logs will be available via Dynatrace once the permissions are worked out with ITS.  I think it's a "2".

The groups are set up, but not configured in Dynatrace yet.
