### ISSUE TITLE
All team members can access CloudWatch logs

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#718]
**STORY**
In order to establish a shared understanding of how the system behaves in production and to create a shared source of truth for making design and problem resolution decisions, all team members should be have read-only access to logs for all clusters in the deployment pipeline.

**STEPS TO CONFIRM**
1) Login to the Yale AWS console
2) Go to the Elastic Container Service (ECS) dashboard
3) Make user you're in the us-east-1 region
4) Find the cluster you want
5) Go to the tasks tab
6) Click on a task (like main if you want to see logs for blacklight)
7) Scroll down to containers and expand the blacklight container
8) Scroll down until you see the _View logs in CloudWatch_ link 
9) Click on the link to jump to the logs
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/b886e70a-de6c-4cc5-b106-0286ccc9fb58)

**ACCEPTANCE**
Team members can view AWS CloudWatch logs for current clusters*
- [X] Bob
- [X] Rick
- [X] Keith
- [X] Mark
- [ ] Jez
- [ ] Rachel
- [ ] Kait
- [x] McClain
- [ ] Dylan
- [ ] Mike
- [ ] Frederic
- [ ] Eric
- [ ] Lakeisha
- [ ] Maggie
- [ ] Martin
- [ ] Alisha
- [ ] Rob
- [ ] Max
- [ ] JP

*Current Clusters = test, uat, demo, infra, staging, production (as of 10/21)

**Comment by martinlovell** [comment]
I can view alarms (not obvious what they are), but get permission errors on some pages like: 

Unauthorized to:
cloudwatch:ListDashboards
resource-groups:ListGroups

**Comment by mark-dce** [comment]
I think this is ready to close - I'm going to do a mobbing session at the end of Software Engineering Sprint Planning or just after to walk any Software Engineering folks through who want to follow along.
