### ISSUE TITLE
Make Subject TopicClickable for search (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#724]
As a user, I want to be able to click on a subject term to be able to get a search showing me other things with that subject term.

- [ ] Subject Topic

![Screen Shot 2020-10-23 at 9.40.32 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/b69abbae-89b2-428b-97d8-86c051ced933)

**Comment by FCRodriguez7** [comment]
**OID Example** 
16700283

**Before**
![Screen Shot 2021-01-07 at 1.33.48 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/67048140-ef47-4f80-a5fc-7873024e2a09)


**After**
![Screen Shot 2021-01-07 at 1.38.25 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/366a2bdf-fda6-4817-9772-9b183a9a2c57)

**Comment by FCRodriguez7** [comment]
**Review on Test**

![Screen Shot 2021-01-08 at 3.17.39 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/23e6ff60-d125-4edc-95b9-67b5d0713fe9)

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/1a8dd50b-d107-4d8f-b7d4-6d89aca47230)
