### ISSUE TITLE
Change 'Back to Search' to 'Back to Search Results'(BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#725]
We would like to change the buttons to say 'Back to Search Results' and confirm styling isn't broken
![Screen Shot 2020-10-23 at 9.42.57 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/4f0cdaf8-8938-4f25-8a3b-4a89889e14df)

**Comment by ArshdeepSingh98** [comment]
I would to like to work on this issue.

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/97918741-9887d900-1d24-11eb-8c12-0dde1d373627.png)

**Comment by FCRodriguez7** [comment]
Reviewed on Test Environment

![Screen Shot 2020-11-03 at 1.39.11 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/10a2bb21-5764-45f0-8d59-413d107ddffb)
