### ISSUE TITLE
Remove Barcode, Holding, and Item ID from Metadata Listing (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#726]
Barcode, holding, item id do not need to display to users, these can be removed in display.

![Screen Shot 2020-10-23 at 9.44.59 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/cdbb72fd-48e9-4e02-8bd1-1bb16b86cffc)

**Comment by dl-maura** [comment]
As far as we can tell, holding and item ID aren't being pulled since they don't exist in LB (see: /catalog/2000017 in test where item and holding are set to 0 but nothing shows in the metadata, also don't see references to them in the display code)

**Comment by mark-dce** [comment]
I think this one has been handled?
https://collections.library.yale.edu/catalog/2007321 

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/956c61d1-66d7-424a-bb63-bc9881120f1f)

**Comment by dl-maura** [comment]
Nope, see https://collections-uat.library.yale.edu//catalog/2 (same on prod)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/428

# Summary
- removes all references to orbisBarcode_ssi
- the "holding" and "item id" fields are already gone

# Demo
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/100920309-c41af200-348f-11eb-8824-75590102a507.png) | ![image](https://user-images.githubusercontent.com/29032869/100920128-8ddd7280-348f-11eb-90ef-8e2a61f0462a.png) |

**Comment by alishaevn** [comment]
https://collections-uat.library.yale.edu/catalog/999956
![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/99387878-64de-4904-9ef3-3f7968ef8210)
