### ISSUE TITLE
Make production environment visible to the public internet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#734]
**ACCEPANCE**
- [x] I can reach https://collections.library.yale.edu/ from anywhere on the public internet
- [x] I can reach https://collections.library.yale.edu/catalog from anywhere on the public internet
- [x] I can reach https://collections.library.yale.edu/manifest from anywhere on the public internet
- [x] I can reach https://collections.library.yale.edu/iiif from anywhere on the public internet
- [ ] ~I can reach https://collections.library.yale.edu/mirador from anywhere on the public internet~

AND
- [x] I **cannot** access https://collections.library.yale.edu/management from the public internet

**Comment by bobrice** [comment]
the production environment is open to the world and management cannot be accessed unless on VPN

Unchecked URLs above contain misspellings or are incomplete and were not tested.

**Comment by fnibbit** [comment]
A manifest from outside the vpn: ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/d82c8938-90c3-45cd-b26b-2e5726da02f7)

An image from outside the vpn: ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/ae054c1d-a48b-4fb9-a154-c274ae1991dc)
