### ISSUE TITLE
Change Common Fields to All Fields (Label and Function) in Basic Search (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#735]
Right now, Basics search has a 'Common Fields' that only searches a subset of defined fields. We want to just use the same All Fields from Advanced Search. A test for this is to search Romanov -- right now it returns nothing in common search but does return in the All Fields in Advanced
- [x] Common Fields is Removed from Basic Search or renamed to All Fields
- [x] All Fields in Basic Search searches ALL fields i.e. the same as advanced search

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/429

# Summary
- The first option on a basic search is "All Fields"
- It operates the same way as the "All Fields" option on the advanced search page

# Demo
Before: https://share.getcloudapp.com/WnulNzY8
After: https://share.getcloudapp.com/2Nu0B1Dr

**Comment by alishaevn** [comment]
Tested by searching for "autographs" in the "all fields" sections for basic and advanced search.
`Branch:v1.36.0,Deployed:2020-12-07T11:28:37-05:00 `

Demo: https://share.getcloudapp.com/4guO9mRQ

**Comment by alishaevn** [comment]
performed the same search on uat and it's also working. `Branch:v1.36.0,Deployed:2020-12-07T12:27:56-05:00 `

advanced search: https://collections-uat.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=autographs&creator_tesim=&title_tesim=&identifierShelfMark_tesim=&date_fields=&subject_fields=&genre_fields=&oid_ssi=&child_oids_ssim=&commit=SEARCH

basic search: https://collections-uat.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&creator_tesim=&title_tesim=&identifierShelfMark_tesim=&date_fields=&subject_fields=&genre_fields=&oid_ssi=&child_oids_ssim=&search_field=all_fields&q=autographs

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/101387207-1ee78b80-388c-11eb-89ff-55956f5733bd.png)
