### ISSUE TITLE
Broken object identification

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#738]
As a system administrator, I want to identify potentially "broken" objects (where ingest failed for some reason, but though there may or may not be existing notifications for it) so that I can identify and remedy them.  I want to optionally be able to re-ingest these objects, or create a report of broken objects.

One possible way to identify broken objects:
``` sql
select distinct(parent_object_oid) from child_objects where child_object.ptiff_conversion_at is null
```

There may be other ways to identify broken objects

**Comment by dl-maura** [comment]
Possibly completed by the batch statuses?
