### ISSUE TITLE
Batch process pagination text off by 10 error

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#740]
pagination text is off by 10:

![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/4794edc2-5b18-4ba8-819f-e6f24f58d5b3)

at the end:

![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/8881c46f-9bd2-4c4f-a483-3c8bfc2bc77e)

**Comment by mikeapp** [comment]
I think the problem here is that Process IDs are not necessarily continuous.   I see some numbers missing from the sequence in production but the counts of objects per page shown in the pagination are correct.

**Comment by maxkadel** [comment]
I'm down to just leave as-is, as Mike mentioned in his #1.
