### ISSUE TITLE
Change Subject Labels (BUGHERD)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#741]
We want to change the labels to Subject (Geographic), Subject (Name), Subject (Topic) for the subject labels in the blacklight display.

**ACCEPTANCE**
- [ ] "Subject Topic" is changed to "Subject (Topic)"
    - [x] In the facet list
    - [ ] In search results
    - [x] On single item view pages 
- [ ] "Subject Name" is changed to "Subject (Name)"
    - [x] In the facet list
    - [ ] In search results
    - [x] On single item pages
- [ ] "Geo Subject" is changed to "Subject (Geographic)"
    - [ ] In search results
    - [ ] On the single item view page

See OID 16612817 for topic and name examples
See OID 15352339 for geo subject example

**Comment by dl-maura** [comment]
![Screen Shot 2020-10-30 at 12.25.17 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/72c3ebfd-8830-4914-a8e1-50ff61ee8c79)
![Screen Shot 2020-10-30 at 12.27.45 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6a2d566c-81b0-4ec4-ad23-0328b7916e61)
![Screen Shot 2020-10-30 at 12.28.04 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/2b5cd3f6-9e52-4275-b8c0-4d8cacfc4d68)
![Screen Shot 2020-10-30 at 12.28.17 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/ae28bbd6-0c18-4218-9e7e-a42187c7a8d0)
![Screen Shot 2020-10-30 at 11.46.10 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/be0825c0-2a18-4771-9502-ceeeb845f9f1)

**Comment by FCRodriguez7** [comment]
The pr for this work: https://github.com/yalelibrary/yul-dc-blacklight/pull/365/files

The title of the branch: 
741-subjects-label

**Comment by FCRodriguez7** [comment]
In the test environment: 

![Screen Shot 2020-11-03 at 2.08.19 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/fac93e03-d0a8-4fd4-aabb-e0a4e63126cf)
