### ISSUE TITLE
Developers should be able to deploy Solr & Postgress in test

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#744]
**ISSUE**
We were able to stop solr but not deploy a new version to test because of AWS permissions.

**ACCEPTANCE**
- [ ] Software Engineering team members can deploy Solr to the test cluster
- [ ] Software Engineering team members can deploy Postgress to the test cluster

**Comment by bobrice** [comment]
Jez and Max were able to stop and start Solr and PostGres this after adding "ListStackResources" to the group permissions in AWS.  

It was also important to run get params for the cluster using the following command...
VPC_ID=vpc-57bee630 SUBNET0=subnet-2dc03400 SUBNET1=subnet-71b55b4d cam get-params yul-dc-test
