### ISSUE TITLE
Test that Geo Subjects are broken up by line and Label is right

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#745]
Test that Geo Subjects are broken up by line and called Subject (Geographic) in the short view
Geo Subject: 2006858

**Comment by dl-maura** [comment]
These come through correctly on the short view (the search results list when we hit for a highlight) just not the view page

**Comment by mark-dce** [comment]
Is this still and open issue?  Can we provide some sample OIDs that should demonstrate when the issue is working correctly (or that it's not fixed yet)

**Comment by dl-maura** [comment]
Needs 930 to be reviewed and released but yes:
![Screen Shot 2020-12-15 at 12.34.37 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/5cdac7e0-7dc2-46d4-a581-99d1ce3fb45b)
