### ISSUE TITLE
Deploy Blacklight to SpinUp 🌀

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#75]
**STORY**
As a project team member, I'd like an automated way to deploy changes to the blacklight app to a test cluster in SpinUp, so that I can reliably deploy and test different changes.

**ACCEPTANCE**
- [ ] I have a command-line or web-ui tool that lets me specify a branch (default to `master`) I'd like to deploy and cluster (default to whatever we currently have) I'd like like to deploy it to
- [ ] The tool indicates whether the deployment was successful or not

**Comment by mikeapp** [comment]
@FCRodriguez7 and I stood this up on a VM in Spinup using docker-compose.   You must be on the Yale VPN to access the Blacklight.

URLs:
http://10.5.38.103:3000/catalog/   (temporarily)
http://spinup-001113.spinup.yale.edu:3000/catalog/3798665 (when the DNS provisions)

It will take some more work on the configuration to move the web container into ECS.

**Comment by mikeapp** [comment]
Blacklight image pushed to Docker Hub: yalelibraryit/dc-blacklight:latest

**Comment by mikeapp** [comment]
![Screen Shot 2020-04-27 at 1.11.06 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/63a02b17-162b-4f54-9cce-a5ba8b81e5aa)

**Comment by mark-dce** [comment]
Looks great.
