### ISSUE TITLE
SPIKE: Can contact section be entirely suppressed when address information is not available

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#759]
**ACCEPTANCE**
Review the PDF generator code and determine
- [x] If we can completely suppress the contact information section on the cover page without additional code changes
* YES:
    - [ ] No further action necessary
* NO:
    - [x] Estimate the level of effort necessary to update the code to allow calls to it to suppress the contact information on the cover page (either thought a command line switch, or via the JSON containing cover page metadata)

**Comment by dl-maura** [comment]
Martin already did it
