### ISSUE TITLE
SPIKE: Determine whether to modify existing Java repo or clone for this project

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#761]
**ISSUE**
Based on the information discovered by #758 - Cover Page Key-Value Pairs and #759 Cover Page Contact Info, we need to determine whether we can use a single copy of the PDF Builder that supports both FindId and the new DL or whether we need to fork the Java application so that we can make DL specific modifications.

**ACCEPTANCE**
- [x] We have decided to use the existing PDF generation codebase OR we've forked a copy that will be customized for the DL

**Comment by dl-maura** [comment]
For devops: How is this being deployed right now? Is the JAR being built automatically against this repo?

**Comment by DraxIndustries79** [comment]
We will fork a copy.
