### ISSUE TITLE
Serve PDFs from a web-service

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#763]
**ISSUE**
We want to pre-generate PDFs for 

**ACCEPTANCE**
- [x] I can request a PDF from a service named https:collections[-environment].library.yale.edu/pdfs/[OID].pdf
- [x] When I pass the service a valid OID for a PDF that has been previously generated, the service returns the PDF
- [x] When I pass the service an invalid OID, the service returns a "not found" status with the following error message
>We're sorry, but the PDF you've requested does not appear to exist
> * If this is a new item, PDF generation may take some time, please check back in 24 hours
> * If this item is restricted, please log-in with your Yale NetID
> * If you believe you've received this notice in error please contact LIT support
- [x] Any errors loading or serving the PDF are logged, e.g.
   - [x] Can't find expected file on ~Storage@Yale~ **S3**
   - [x] Can't connect to ~Storage@Yale~ **S3**

**DEV NOTES**
* PDFs will be stored in a pair-tree structure on **S3** ~Storage@Yale~ matching the pair-tree structure for manifests

**Comment by DraxIndustries79** [comment]
Will store PDFs on S3

**Comment by martinlovell** [comment]
A PR to serve PDFs and return not found message when they are not found.
https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/31

Updated nginx config to rewrite so /pdfs/ will map to the right URL in the app.

We still need to setup the routing so that any URL ending in /pdfs/ go to the manifest app similarly to /manifests/ urls.
I'm not sure how to do that or where it is configured.

**Comment by martinlovell** [comment]
Updated this based on some feedback from Max.

Splitting into separate controllers, and setting up nginx to not remove /manifests/ or /pdfs/ from the URL before passing to rails.
This will make it simpler to move to blacklight app when needed.

New PR: https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/32

**Comment by martinlovell** [comment]
Max has updated camerata to include the necessary environment variables and to setup ALB rule for /pdfs/*.
https://github.com/yalelibrary/yul-dc-camerata/pull/252/files

Rick has update the existing ALBs for all environments adding the rule through AWS console so /pdfs/* goes to the iiif_manifest server.

There is a PR remaining on iiif_manifests that updates the PDF controller to use streaming:
https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/34

**Comment by mark-dce** [comment]
How do I trigger a PDF to be generated - it looks like we should be ready for this object https://collections-uat.library.yale.edu/catalog/12222098 ?

**Comment by martinlovell** [comment]
PDFs are generated whenever the manifest is (re-)created.  The easiest way is to ingest an oid that hasn't been ingested yet.
