### ISSUE TITLE
Add the PDF link to the manifest as part of the manifest generation process

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#764]
**ACCEPTANCE**
- [x] The manifest for any parent object includes a link to download the full work as a PDF
- [x] When I view the manifest in Universal Viewer, I see a PDF option in the download links
- [x] The link points to https://collections[-environment].library.yale.edu/pdfs/[OID]

ACCEPTANCE NOTE
*The link does not need to function correctly until ticket #763 - Serve PDFs from a web service, is complete.  For acceptance, we only need to validate that the link exists and has the expected form.*

**NOTE**
See https://wellcomelibrary.org/iiif/b20417081-0/manifest for an example manifest with downloadable PDF rendering.  The main work page is here https://wellcomelibrary.org/item/b20417081#?c=0&m=0&s=0&cv=0&z=-0.6522%2C-0.0828%2C2.3042%2C1.6564

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/04a3ca6f-9e52-4e10-845f-162c9af287cd)

```
 "sequences": [
    {
      "@id": "https://wellcomelibrary.org/iiif/b20417081-0/sequence/s0",
      "@type": "sc:Sequence",
      "label": "Sequence s0",
      "rendering": [
        {
          "@id": "https://dlcs.io/pdf/wellcome/pdf-item/b20417081/0",
          "format": "application/pdf",
          "label": "Download as PDF"
        },
        {
          "@id": "https://wellcomelibrary.org/service/fulltext/b20417081/0?raw=true",
          "format": "text/plain",
          "label": "Download raw text"
        }
      ],
      "viewingHint": "paged",
      "canvases": [
        {
          "@id": "https://wellcomelibrary.org/iiif/b20417081-0/canvas/c0",
          "@type": "sc:Canvas",
          "label": " - ",
          "thumbnail": {
            "@id": "https://dlcs.io/thumbs/wellcome/5/b20417081_001_0001.jp2/full/67,100/0/default.jpg",
            "@type": "dctypes:Image",
```

**Comment by mikeapp** [comment]
Testing the manifest above, it does not show a download link in Mirador 3 (that I can find).

**Comment by mikeapp** [comment]
Note that Wellcome puts the `rendering` at the level of the `sequence`.   More expected (and might possibly work in Mirador) is to put it at the root level of the Manifest, per the example in the spec at https://iiif.io/api/presentation/2.1/#c-example-manifest-response

**Comment by maxkadel** [comment]
> Note that Wellcome puts the `rendering` at the level of the `sequence`. More expected (and might possibly work in Mirador) is to put it at the root level of the Manifest, per the example in the spec at https://iiif.io/api/presentation/2.1/#c-example-manifest-response

- I tried putting it in the root level of the Manifest, and it did not display in Universal Viewer, whereas it did display when I put it on the sequence.
![image](https://user-images.githubusercontent.com/45948126/98570603-9fad6a80-2281-11eb-9a91-6eace4b173fa.png)

**Comment by mikeapp** [comment]
Mirador 3 test shows it is looking at Manifest level (at least):

![Screen Shot 2020-11-09 at 1.32.11 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/12fa882f-10de-4ef0-ada1-750800d791cf)

**Comment by mark-dce** [comment]
Looks good in UV and Mirador - see https://collections-uat.library.yale.edu/catalog/12222098

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/a853d8c9-ec29-4d51-af45-a656bf4df3c7)

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/b394b21e-e5ff-4e6c-9127-d9a3c8c35420)
