### ISSUE TITLE
 Add a link for “Download as PDF” to the bottom of the single item view page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#765]
**ACCEPTANCE**
- [x] The single item view page for any parent object includes a link in the Tools section, that allows me to download the full work as a PDF
- [x] The link points to https://collections[-environment].library.yale.edu/pdfs/[OID]

ACCEPTANCE NOTE
*The link does not need to function correctly until ticket #763 - Serve PDFs from a web service, is complete.  For acceptance, we only need to validate that the link exists and has the expected form.*

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/b4b68c4a-6e47-4e93-993d-a330628f6b1b)

**Comment by orangewolf** [comment]
link currently goes to `/manifests/2066513.pdf`. This is a blatant attempt to skate to where the puck is going instead of where it has been, but will also be trivial to change if https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/31 changes direction.

**Comment by maxkadel** [comment]
Mobile - 
![image](https://user-images.githubusercontent.com/45948126/98557259-fb6ff780-2271-11eb-8e6f-b945caaaa8a8.png)

Desktop - 
![image](https://user-images.githubusercontent.com/45948126/98557319-0dea3100-2272-11eb-9d6c-13b693915576.png)

Link goes to `pdfs/2066523.pdf`
