### ISSUE TITLE
(Re) Generate the PDF when the parent or associated children are changed

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#766]
**ACCEPTANCE**
- [x] A new PDF is generated any time the metadata for a parent or child object changes
- [x] A new PDF is generated any time a child object image is added, deleted, reordered, or replaced
- [x] The new PDF is saved to **S3** ~Stoarage@Yale~ in the expected pair tree location
- [x] The new PDF overwrites any existing PDF (i.e. no versioning of PDFs)
- [x] Any errors in PDF generation are logged, as a start
    - [ ] Could load one or more child images for conversion
    - [ ] Conversion script failed
    - [ ] Failed to read parent metadata for coverage

**Comment by martinlovell** [comment]
Preliminary PR: https://github.com/yalelibrary/yul-dc-management/pull/391
