### ISSUE TITLE
Schedule Security Testing

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#769]
**ACCEPTANCE**
- [x] Complete any pre-test information requests
- [x] Schedule security test

**Comment by ra359** [comment]
John Coleman at InfoSec created an Asset in Tenable called "*library static name" that we can use to create ELB fronted sites. I've requested that "collections-staging.library.yale.edu" and "collections.library.yale.edu" be added via INC1897294.

**Comment by ra359** [comment]
We allegedly have access now to scan collections.* - I've kicked off a scan and am awaiting results.

**Comment by ra359** [comment]
[https://app.zenhub.com/files/242185115/1772a598-7678-4cd0-9289-e2bb4f0a0742/download](https://app.zenhub.com/files/242185115/1772a598-7678-4cd0-9289-e2bb4f0a0742/download)  Results of remote vuln scan.
