### ISSUE TITLE
Facets should display "More >" link when there are more than 10 items per facet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#777]
**ISSUE**
When I go to view a number of facets, only the top 10 facet values are listed and I have no way to access items with smaller facet counts.

**ACCEPTANCE**
- [x] All facets display a "more >>" option when there are more than 10 unique values in the facet.
   - [x] "Genre" is definitely missing "MORE"
   - [x] "Subject Topic" is definitely missing "MORE"
   - [x] "Subject Name" is definitely missing "MORE"
   - [x] "Digital Collection" is definitely missing "MORE"
   - [x] Please check other facets to ensure they are not misconfigured

**DEV HINT**
We need to set the facet `limit:` value correctly.  Compare the facet configuration in the catalog controller for a facet that is configured correctly with one that's not.  See the comment in front of facets in the catalog controller https://collections-staging.library.yale.edu/?f%5Blanguage_ssim%5D%5B%5D=German&q=&search_field=all_fields

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/1830fb41-84df-49f2-a2ae-b7cbdc738aa6)

**Comment by dl-maura** [comment]
Creator needs to be switched to default to numerical (# of matches)
