### ISSUE TITLE
SPIKE: Verify characters with accents being passed through & displayed correctly

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#778]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/f69eb30f-5b92-4c84-b87e-449a5239f19d)

https://collections-test.library.yale.edu/catalog/10656773

https://collections-test.library.yale.edu/management/parent_objects/10656773
```
  "title_tesim": [
    "Affiche for the representation of \"Le Neveu de Rameau, ThÌ©Ì¢tre Art et Action, Paris, 1926. [05118-1]"
```

**ACCEPTANCE**
- [x] Try to identify 3-5 examples that have surprising characters (document them in the comments)
- [x] Check the data from the metadata cloud as displayed by the management app
- [x] Check the data in the source system or FindIt
- [x] Write up a new ticket identifying any discrepancies between the source system and Blacklight

**Comment by maxkadel** [comment]
@martinlovell - Do you have ideas about how we might verify that the MetadataCloud is passing on the correct data for this work?

If I had to guess, this work should probably have `Théâtre` in its title, we're indexing that to Solr as `ThÌ©Ì¢tre`, does the issue stem from the Management app or the data from the MetadataCloud.

**Comment by mikeapp** [comment]
Probably an error in the source data, FindIt has the same problem:
<img width="906" alt="Screen Shot 2020-11-02 at 11 26 24 AM" src="https://user-images.githubusercontent.com/1987952/97892669-4fbd2980-1cfe-11eb-9e89-27e454b8ef32.png">

**Comment by maxkadel** [comment]
[Search for ThÌ©Ì¢tre](https://collections.library.yale.edu/catalog?search_field=all_fields&q=Th%C3%8C%C2%A9%C3%8C%C2%A2tre) in collections.library.edu yields 325 results.

Looking for the same items in findit yields the same rendering - 
* http://hdl.handle.net/10079/digcoll/3854451
* http://hdl.handle.net/10079/digcoll/3854740
* http://hdl.handle.net/10079/digcoll/3854956
* http://hdl.handle.net/10079/digcoll/3854747
* http://hdl.handle.net/10079/digcoll/3854861

Seems to be specific to the Filippo Tommaso Marinetti Libroni on Futurism collection, perhaps?

**Comment by maxkadel** [comment]
Limiting by Russian
On first page of search results - 
![image](https://user-images.githubusercontent.com/45948126/103660334-77698180-4f3b-11eb-9bcc-5851a111e47a.png)
show page:
https://collections.library.yale.edu/catalog/15509689 
![image](https://user-images.githubusercontent.com/45948126/103660546-b697d280-4f3b-11eb-9af0-208b99a2d17e.png)

![image](https://user-images.githubusercontent.com/45948126/103660572-bef00d80-4f3b-11eb-93e7-e58b94da2120.png)

It appears that the metadata is correct, but the different fonts have different abilities to render the ligatures correctly (ligatures are a MARC requirement for Romanizing Cyrillic).

**Comment by maxkadel** [comment]
Hebrew - metadata issue
https://collections.library.yale.edu/catalog/2008142
![image](https://user-images.githubusercontent.com/45948126/103663566-3d9a7a00-4f3f-11eb-84d3-d225f76976c6.png)
http://hdl.handle.net/10079/digcoll/3357349

**Comment by maxkadel** [comment]
Japanese
Romanization mostly looks good, title on show page font not showing some characters correctly - https://collections.library.yale.edu/catalog/2005230
![image](https://user-images.githubusercontent.com/45948126/103666269-68d29880-4f42-11eb-83cb-fc53aa0f8e94.png)

**Comment by maxkadel** [comment]
Final summary: 

- Most issues are with the source data
- Ligatures used for Romanizing Cyrillic scripts do not render correctly in a number of fonts we are using
- Macrons and breve marks (used in Romanizing Japanese and Korean) do not render correctly in show page title font (show backup), render correctly in other fonts

**Comment by maxkadel** [comment]
New ticket - see #962
