### ISSUE TITLE
Manifests render in Universal Viewer

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#78]
**ACCEPTANCE**
Given a link from the manifest service, 
- [x] It renders successfully at https://universalviewer.io
- [x] [BONUS] It renders successfully in mirador

**Comment by ra359** [comment]
INC1740811 created for configure the SSL connection to the container. i.e.
https://iiif-transcribe.library.yale.edu/ -> http://spinup-0010ab-iiiftranscriptproductionservice.svc.spinup.yale.edu:8182

**Comment by mikeapp** [comment]
* Nginx proxy with self-signed cert running in Spinup VM
* Cantaloupe running in Spinup ECS
  * Github: https://github.com/yalelibrary/yul-dc-iiif-imageserver
  * Docker hub:  yalelibraryit/dc-iiif-cantaloupe:0.1
  * Image source is DCE AWS S3 yale-image-samples bucket
  * Sample URL:  https://spinup-0010ef.spinup.yale.edu/iiif/2/1014332/info.json
* Manifests
  * Generated ~48 IIIF manifests programmatically, with URLs pointing to the new Spinup server
  * Uploaded to https://github.com/yalelibrary/yul-dc-fixture-manifests
  * TODO: stand up manifest Docker in Spinup ECS and put behind Nginx proxy for SSL

**Comment by mikeapp** [comment]
Manifests and images are working.  Caveats:
* You must be on the Yale VPN
* You must accept the self-signed SSL certificate

UV: https://universalviewer.io/uv.html?manifest=https://spinup-0010ef.spinup.yale.edu/manifests/10001192.json

Mirador:

![Screen Shot 2020-04-24 at 4.21.07 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/de588bb8-d17e-46c4-b952-3bf278473e6c)
