### ISSUE TITLE
Ensure ECS clusters point at corresponding Metadata Cloud Endpoints

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#780]
**ACCEPTANCE**
- [x] ECS Production ☞ MC Production
- [x] ECS Staging ☞ MC Production
- [x] ECS Demo  ☞ MC UAT
- [x] ECS UAT  ☞ MC UAT
- [x] ECS Test  ☞ MC Test
- [x] ECS Infra  ☞ MC Test

**Comment by bobrice** [comment]
ECS Test management is currently pointing to Metadatacloud UAT, not Test.
ECS Infra management is also pointing at UAT

**Comment by bobrice** [comment]
Confirmed that test cluster is pointing at test MDC and infra cluster is pointing at UAT MDC.
