### ISSUE TITLE
Ensure that Metadata Cloud instances point a corresponding SOAs

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#781]
**ACCEPTANCE**
- [x] MC Production ☞ LadyBird / ILS / ASpace Production
- [x] MC UAT  ☞ LadyBird / ILS / ASpace Test
- [x] MC Test  ☞ LadyBird / ILS / ASpace Test

**Comment by bobrice** [comment]
MC UAT and Test point to LadyBird Test, ILS Test, and ASpace Test.
