### ISSUE TITLE
Make staging environment visible to the public internet

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#787]
ACCEPANCE

- [x] I can reach https://collections-staging.library.yale.edu/ from anywhere on the public internet
- [x] I can reach https://collections-staging.library.yale.edu/catalog from anywhere on the public internet
- [x] I can reach https://collections-staging.library.yale.edu/manifest from anywhere on the public internet
- [x] I can reach https://collections-staging.library.yale.edu/iiif from anywhere on the public internet
- [ ] ~I can reach https://collections-staging.library.yale.edu/mirador from anywhere on the public internet~

AND

- [x] I cannot access https://collections-staging.library.yale.edu/management from the public internet
- [x] staging is behind http auth

**Comment by bobrice** [comment]
Staging is open to the world using httpd basic auth and the management app is not accessible unless authenticated and signed in to VPN.

URLs above for iiif, manifest, and mirador are not complete or misspelled and cannot be tested.

**Comment by fnibbit** [comment]
I'm not on the vpn at the moment.  Here's a screenshot of a manifest on staging.  ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/f5d2a784-a4d9-404b-9cfe-bfd724c0cea4).  

An image on staging: ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/0caefb78-07b3-4f87-8c02-81ae13b14978) 

The mirador endpoint listed above looks like this![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/497d5ab0-a463-40eb-8e4b-d4ed8a9ab3c6) from here (which is also the as-expected way the management endpoint listed above looks).  Going to investigate the mirador part a little more.

**Comment by fnibbit** [comment]
The code for the mirador endpoint is in v1.33.0 of our blacklight app.  Staging is currently at v1.29.2 of our blacklight app. On demo, from within the vpn, a mirador endpoint looks like this: ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/9dfacf7f-dc1c-4a04-bd34-f3b741604b4b) ({cluster-hostname}/mirador/{parent-oid}).  Going to the corresponding endpoints both in and outside the VPN on staging gives identical results and the mirador endpoint is part of the blacklight app whose other endpoints are behaving as expected, so I believe this ticket is closeable, and that as separate work a more recent version of blacklight on staging and production will be wanted.
