### ISSUE TITLE
Accessibility Requirement: Change Dodger Blue to Cornflower Blue

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#791]
Per Accessibility requirements 
- [x] Change light blue to  Cornflower Blue  (#006EF5)

**Comment by FCRodriguez7** [comment]
Replace $lighter_blue: #009cff  with cornflower blue.

**Comment by FCRodriguez7** [comment]
A screenshot from the test environment: 


![Screen Shot 2020-11-05 at 3.24.13 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d654aca5-e212-44fa-95df-700471862b9b)

**Comment by maxkadel** [comment]
Darkens blue used for links
Left - UAT (new)
Right - Demo (old)

![image](https://user-images.githubusercontent.com/45948126/98392277-ca02ec00-2025-11eb-8bda-12d47aa32221.png)
