### ISSUE TITLE
Question:  Do we need to support CJK and other scripts in PDF?

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#792]
The jar file for PDF generation is 20M.  Most of that is for the unicode font needed for special script like CJK.

If we use the transliterated title, creator, etc, we could reduce the size significantly.

**Comment by martinlovell** [comment]
The Jar contains the font file.  We could put the font file somewhere in the image, and the jar could read the fonts from a specific path if that would help.

**Comment by mikeapp** [comment]
CJK is needed

**Comment by dl-maura** [comment]
I think yes, but I defer to Rebecca and Mike
