### ISSUE TITLE
Address PG::ConnectionBad Exceptions

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#793]
**ISSUE**
We're currently seeing a spike in exceptions from the blacklight application (that has put us at 4x our execution reporting quota for Honeybadger).  

See details at https://app.honeybadger.io/projects/72587/faults/65223983 

**ACCEPTANCE**
- [x] Address any misconfiguration issues leading to the connection errors
- [ ] Confirm that the error rate for this particular error has dropped for an 8 hour period

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/faec91da-57e2-471f-a766-f4dc68fc7175)

**Comment by mlooney** [comment]
We believe this has been rectified, but this uncovered a potential ssm/camerata issue in the process.


We should also have Yale take ownership of the honey badger account (or create a new one) before we forget.

**Comment by mark-dce** [comment]
FWIW- all Yale exception reporting is occurring under a separate Honeybadger account that can be transitioned to Yale or shut down at the end of the project.

**Comment by mlooney** [comment]
good to know. the issue was caused by an errant cluster configuration / camerata bug in dce-land. that cluster has been cleaned out, and we haven't had this exception in about 5h.
