### ISSUE TITLE
Update sql client version to match server version

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#795]
We are currently running postgresql server 12, but using client version 10, which can cause some issues/annoyances

**Comment by JzGo** [comment]
I believe this requires an update to the **base** image in camerata.

Need to update these images with the new base:
- [ ] Blacklight
- [ ] Management
- [ ] Manifest

**Comment by mikeapp** [comment]
Just deployed to test, so reopened this issue.
