### ISSUE TITLE
Populate sample images for development

### ISSUE THREAD

**Issue by alishaevn** [yalelibrary/YUL-DC#80]
**STORY**
Ensure that the imageserver is / can be populated with a set of sample images for development

**ACCEPTANCE**
- [x] The imageserver has sample images available for demo purposes
- [x] There is a README telling new users how to get access to the images

**Comment by DraxIndustries79** [comment]
Investigate mini IO

**Comment by bess** [comment]
![Screen Shot 2020-04-30 at 3.59.07 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/f30c32e3-89ec-4f10-9bbf-80d6a15964a1)
