### ISSUE TITLE
Stream PDFs rather than download and send

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#800]
iiif_manifest server sends PDFs.
It is pulling the PDF down and then sending it.  It should stream the PDF instead.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-iiif-manifest/pull/34

**Comment by mark-dce** [comment]
I marked this as a possible chore - I don't know how I would verify this from an end-user browser.  Is there anything we can show to the team about how this works?

**Comment by martinlovell** [comment]
Nothing is really noticeable for the user.  The only way to see the change is to look at the code changes in the PR.
