### ISSUE TITLE
Restrict access to Management application to a list of specific NetIDs

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#803]
**STORY**

Access to the management application should be restricted to a list of specific NetIDs. (**Do not put that list here**)

**ACCEPTANCE**

- [x] Seed list of net ids will be in csv on S3
- [x] Logins to management are rejected for unauthorized NetIDs
- [x] Authorized users can successfully log in to the management interface
- [ ] All management pages are protected (or create follow-on ticket for remediation)

**Comment by martinlovell** [comment]
Where should we configure the list of NetIds?
Should there be a way to configure the list through the management app?

We could do a yaml, but then we'd need to re-deploy to add/remove someone.

**Comment by orangewolf** [comment]
this seems like a really reasonable use of Rails CRUD to me. Make it easy to add or remove netids in the management interface, then key off the list at login time. As long as you build in one to start with for seeding its not a big deal to add the rest as needed.

**Comment by mikeapp** [comment]
Note that we may have to remove access for people as well (e.g., as people roll off the project).

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/397

**Comment by dl-maura** [comment]
Maura will have someone test this

**Comment by dl-maura** [comment]
test from a non-authorized person
![unauthorized.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c66691c8-720d-4e82-a73e-0fb62128b74f)

**Comment by dl-maura** [comment]
![image.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/a0032f18-4e32-4062-99bb-178783e65422)
