### ISSUE TITLE
SPIKE: Test AWS Web Application Firewall (WAF)

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#804]
**STORY**

Activate the AWS WAF for the test cluster's Application Load Balancer (ALB).

**ACCEPTANCE**

- [ ] The WAF is enabled for the ALB on the test cluster
- [ ] The Blacklight and Management applications are accessible and responding normally
- [ ] Turn on for Staging

If successful this change will need to be deployed the other clusters and added to Camerata.

**Comment by ra359** [comment]
Enabled WAF for yul-dc-prod. Rate-limitting set to 1,200 connections max over a 5min period.

**Comment by DraxIndustries79** [comment]
@ra359 Should we turn this on in staging as well?  May not need to since it's behind basic auth...

**Comment by DraxIndustries79** [comment]
Turn on for staging.

**Comment by ra359** [comment]
Completed.
