### ISSUE TITLE
Load manifests in local development

### ISSUE THREAD

**Issue by fnibbit** [yalelibrary/YUL-DC#806]
Story: as a developer working on configuration changes, I would like to see images in universal viewer when spinning up the services locally, to validate that the suite of services  work together end-to-end.  

Acceptance:
- [ ] when running in local development, using a current version of the iiif_manifest container, I can see a manifest at http://localhost/manifests/2005512.json
- [ ] when running in local development, using a current version of the iiif_manifest container, I can see images in universal viewer at http://localhost:3000/catalog/2005512 

Current behavior: version 3.0.2 of the IIIF_MANIFEST container is running on at least some of our deployed environments successfully, but in local development spinning up with version 3.0.2 results in ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/43558575-1ad2-471c-837f-560fec69bb34) in a configuration where using 3.0.1 results in the expected behavior.

**Comment by fnibbit** [comment]
Questions to investigate: is this related to the circleci build process (v3.0.1 was pushed by max rather than the circle user)?  Do other recent builds of the manifest app show the same behavior? am I barking up the wrong tree entirely?

**Comment by DraxIndustries79** [comment]
We think this was covered in other work and will open a new ticket if it comes up again.
