### ISSUE TITLE
Fix or Remove tests that fail when VPN != false

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#808]
There are some tests that are not being maintained when VPN=false is not set.
These tests should either be updated or removed.

**Comment by maxkadel** [comment]
I believe these have all been resolved, at least as of 1/4/2021. @martinlovell

**Comment by martinlovell** [comment]
Because of dateStructured changes in MC, `rspec ./spec/system/parent_object_spec.rb:132` is failing.
I'm not sure which makes most sense: (1) updating fixture and test expectations or (2) set VPN to false for that test suite.

It seems like (2) would be the easiest to maintain, since we will have more data and logic changes in MC in the future, unless there's a need to be able to test making the API call to MC.  We could set VPN to false for all tests unless we need to specifically test making the API call to the actual server.

**Comment by mikeapp** [comment]
Per Max's comment `rspec ./spec/system/parent_object_spec.rb` works.  We should open tickets if additional tests are failing.
