### ISSUE TITLE
[Check] Fix Firefox menu drift and Chrome strangeness when window is expanded

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#812]
In Firefox, it the screen loads with the browser window small, and the browser is expanded, the nav menu drifts off the sceen.

Cannot reproduce in Safari.
Other issues in Chrome: the menu does behave strangely when the window is expanded with drop down icon wrapping, etc.

To create the examples below, I captured just the left side of the browser and expanded and contracted the window.

Firefox
![MenuDrift.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/0bbe3c18-8005-4bb7-85b5-19eb7a218842)

Chrome
![ChromeMenuIssues.gif](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/a03ead59-3aa0-40fa-b591-17a8dc2f559a)

**Comment by jpengst** [comment]
Have not been able to reproduce. I don't think this is an issue anymore.
