### ISSUE TITLE
Filter and Start Over should semantically be buttons

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#817]
**DETAILS**
See issue 4 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] Make sure these are 44px high and 44px wide minimum
- [x] The Remove Filter button and Start Over buttons found at the top of the Search Results page should be buttons.
- [x] The images within these buttons should have null alt text. Currently the file name is beingread aloud by VoiceOver, which is not a good experience.

**Comment by dl-maura** [comment]
Related: What do we want behavior to be for buttons on focus/active states?

**Comment by dl-maura** [comment]
Could add role=button or html <button>
One large button of the name and the x 44 high and min 44 wide

**Comment by FCRodriguez7** [comment]
Branch name: 
817_FilterStartoverSemanticButtons

**Comment by FCRodriguez7** [comment]
**Images for the Test server**
![Screen Shot 2020-11-17 at 11.36.42 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/eea3b92a-81e5-4cf3-9842-e8e20b1c5dd9)

![Screen Shot 2020-11-17 at 11.36.54 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/be26f24b-8c87-480c-875f-828d7d373eea)

**Comment by dl-maura** [comment]
Format Is not coming through as 44px for clickable area
