### ISSUE TITLE
Pagination and Find functions have clear ARIA labelling

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#818]
**DETAILS**
See issue 5 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] The Pagination selection has role=navigation is more appropriate.
- [x] 'Find items that match’ select uses aria-labeledby or adding an aria-label to the select will suffice

**Comment by dl-maura** [comment]
Do you want these to be submitted to blacklight proper repositories rather than overrides?

**Comment by mark-dce** [comment]
I think we'll have to do them locally first.  @mikeapp what's your feeling about the long-term value of pushing the changes back upstream?

**Comment by dl-maura** [comment]
![Screen Shot 2020-11-12 at 9.30.08 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/4079f6a6-c9ef-4b5a-8b95-31ad46f1f78c)

**Comment by dl-maura** [comment]
![Screen Shot 2020-11-12 at 9.32.20 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/3da56ed8-abf6-4ba6-8568-137648b3c921)
