### ISSUE TITLE
Pagination Bar Pointer targets should have 44px minimum spacing

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#822]
**DETAILS**
See issue 9 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] Clickable targets like result page numbers in the lower pagination bar must be at least 44 x 44 pixels

**Comment by dl-maura** [comment]
These also need 44px minimum
![Screen Shot 2020-11-13 at 1.24.10 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/e7850ab6-1866-4a7d-83a9-7368fe449bc0)
