### ISSUE TITLE
Advanced Search page missing H1

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#823]
**DETAILS**
See issue 10 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] Each page should have an H1

**Comment by jpengst** [comment]
Before:  
![Image 2020-11-12 at 1.54.53 PM.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/3a52f6b8-604b-45b5-a49c-e75eeebb54e2)  

After:  
![Image 2020-11-12 at 1.39.11 PM.png](https://images.zenhubusercontent.com/5e5fd7630c989fb08bbc978d/e2081a6b-c099-4efe-a77c-9d556cd801b7)
