### ISSUE TITLE
Remove unused fields from Blacklight catalog controller

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#826]
The following fields are in the "Show page" of Blacklight, but the fields they are based on are not currently being indexed to Solr by the Management app. 

### Acceptance Criteria
- [x] Remove these fields
  - [x] Subtitle (not needed)
  - [x] Published (if this is date published, need to look at updated MC mappings to see if this exists separate from date)
  - [x] Children (this IS being indexed as we can search child oids but we do not want this displayed as a list on a parent)
  - [x] Import URL (no)
  - [x] ISBN (no)
  - [x] URL (is this just the url to the item? if so, no)

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/424

# Summary
the following fields are no longer on the show page. there's no visual verification because only fields with a value were appearing on the show page anyway.
- Subtitle
- Published
- Children
- Import URL
- ISBN
- URL
