### ISSUE TITLE
Ensure headings are properly nested

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#829]
**DETAILS**
See issue 13 in https://drive.google.com/open?id=1KsZmdBi00ScskmAMffnM1O_N-CnMUZIv

**ACCEPTANCE**
- [x] Run Lighthouse from Chrome developer tools on the search results, item, and advanced search pages and address any of the heading order issues found 
- [x] Ensure headings on all pages and partials are correctly nested - see Kara's example

**NOTES**
Lighthouse in Chrome developer tools picks this issue up
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/c4310c44-56ee-49af-8564-922f4b88f745)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/407

**Comment by martinlovell** [comment]
This worked well for testing the changes locally:

https://github.com/GoogleChrome/lighthouse#using-the-node-cli

**Comment by mark-dce** [comment]
Ran lighthouse on Homepage, Search Results, Advanced Search, and Single Item view and the issue is resolved on all pages!

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/291a7e7d-17e5-41b0-b222-4857ba9b20e6)
