### ISSUE TITLE
Produce final infrastructure diagram(s)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#831]
**ISSUE**
As we move into operational mode, we should document in as much detail as needed the configuration and connections in each cluster

**NOTE**
This might be best accomplished via a shared white boarding session with some or all team members using a tool like Miro, then translated to a more formal diagram like lucid chart, etc. after.

**ACCEPTANCE**
- [x] Create a diagram showing the running containers in each cluster
   - [x] Containers
   - [x] Connections between containers (port and protocol)
   - [x] Inbound (visual reference of ALB and target group rules)
   - [x] Outbound connections (Storage@Yale, S3, Metadata Cloud, CAS)
- [x] [optional] Document shared resources - i.e. PTIFFs shared between Staging & Production clusters

**Comment by DraxIndustries79** [comment]
We'll plan to demo this Friday 12/18

**Comment by ra359** [comment]
https://git.yale.edu/Library-ESS/DCE/architecture-diadram-yul-dc-staging.png
