### ISSUE TITLE
Default sort of "Creator" should be number, not alpha

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#832]
The default for facets is by number of results, right now all facets except for Creator is using that default.

When you click "more" you can select which sort you want.

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/f7bf680d-7a71-4afa-ab1f-1e6f8cb7b2cd)

**Comment by mikeapp** [comment]
Sort all by count

**Comment by dl-maura** [comment]
Answer was to make creator match all the others (number not alpha)
