### ISSUE TITLE
Buttons Should be Semantic (Item Show Page and Advanced Search)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#837]
Kara says all buttons should be semantically buttons (Could add role=button or html <button>, role is probably easier at this point). Prior art is using <button> so it seems like it is good to go with that.

**Comment by alishaevn** [comment]
# MR
https://github.com/yalelibrary/yul-dc-blacklight/pull/406

# Summary
- the three buttons at the bottom of the advanced search page now have a role of button (see screenshots below)
- the "back to search results", "search" and "advanced search" buttons at the top of the individual show page now have a role of button (see screenshots below)
- the "start over" button on that same page already had a role of button

# Demo
##### advanced search
| | | |
| --- | --- | --- |
| ![Screen Shot 2020-11-17 at 12 44 44 PM](https://user-images.githubusercontent.com/29032869/99459622-4083d180-28e3-11eb-8edf-7cbc69274dac.png) | ![Screen Shot 2020-11-17 at 12 44 52 PM](https://user-images.githubusercontent.com/29032869/99459657-4e395700-28e3-11eb-9d85-f55d147b20fa.png) | ![Screen Shot 2020-11-17 at 12 45 00 PM](https://user-images.githubusercontent.com/29032869/99459680-55606500-28e3-11eb-9be4-02495f941831.png) |

##### show page
| | | |
| --- | --- | --- |
| ![Screen Shot 2020-11-17 at 2 31 40 PM](https://user-images.githubusercontent.com/29032869/99459735-6dd07f80-28e3-11eb-99ed-f4d519532c52.png)|![Screen Shot 2020-11-17 at 2 34 58 PM](https://user-images.githubusercontent.com/29032869/99459755-72953380-28e3-11eb-99d4-0de5333b3942.png) |![Screen Shot 2020-11-17 at 2 35 22 PM](https://user-images.githubusercontent.com/29032869/99459763-77f27e00-28e3-11eb-8922-c51d4a529b2e.png) |

**Comment by alishaevn** [comment]
Verified this is present on https://collections-test.library.yale.edu -- Branch:v1.35.2,Deployed:2020-11-18T11:45:59-05:00
