### ISSUE TITLE
Fix OID and Pages in Manifest Metadata

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#842]
The OID isn't pulling in the manifest metadata and number of pages is pulling in the title.
- [x] Make OID show up in display
- [x] ~~Make sure Number of Pages shows number of pages~~ Remove Number of Images/Pages from this section (not blacklight just canvas metadata)

**Comment by dl-maura** [comment]
Right now, this is looking at authoritative metadata but image count won't come from that -- that needs to come from the solr record of the item

**Comment by dl-maura** [comment]
On Tes
![Screen Shot 2020-12-09 at 5.34.38 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/e717cc2c-f03d-47b7-a4a1-e3e80124088f)

On local
![Screen Shot 2020-12-09 at 5.34.33 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/5f674f9a-6729-4095-b0fd-14f4e356f2ff)

**Comment by martinlovell** [comment]
See: https://collections-uat.library.yale.edu/catalog/17290885

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/1b632448-dcab-467b-bd37-b8ce0994dc8b)
