### ISSUE TITLE
Document all the Jenkins roles and who is associated with which and what each should do

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#844]
Roles (Deploy):
- [x] Everyone:  Test, UAT, Demo, Infa
- [x] Yale DevOps:  Staging, Prod

**Comment by bobrice** [comment]
All users(DCE,Notch8, and Yale Engineering and DevOps) are able to deploy to Test, UAT, Demo, and Infra.  Also, the only Jenkins job that is currently configurable by anyone other than Yale DevOps is YUL-DC-INFRA-Deploy .



Only Yale DevOps is able to deploy to staging and prod.
