### ISSUE TITLE
Everyone should try Release and Deploy Part 2 (Yale)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#845]
Some folks haven't done a release and deploy, or may be out of practice, or may not have done it after changes to the process.

- [x] Martin
- [x] Lakeisha
- [x] Mike
- [x] Eric
- [x] Frederick
- [x] Maggie
- [x] Yue
- [x] Alisha
- [x] JP

**Comment by dl-maura** [comment]
Can Yale folks check to see if they have deploy access to Test, UAT, and demo?

**Comment by MaggieZhaoYale** [comment]
Not able to access UAT, can access Test and demo
