### ISSUE TITLE
SPIKE: Evaluate S3 Encryption Performance for IIIF images

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#846]
**ACCCEPTANCE**
- [x] Create a copy of encrypted PTIFFs in the S3 bucket on at least one environment
- [x] Write a script to randomly load a list of 5000 known image OIDs directly from S3
- [x] Time the script running against
   - [x] The system using the unencrpyted S3 bucket
   - [x] The system using the encrypted S3 bucket
- [x] Compare results to determine if encryption incurs any significant performance penalty

NOTE: consider bumping up the cpu and memory resources on the test system during the test:
1. We'd like to get the tests run as quickly as possible
2. We'd like to remove any memory or cpu bottlenecks from the process so we know the results we're seeing accurately reflect differences in S3 configurations only.

**Comment by K8Sewell** [comment]
Draft PR - https://github.com/yalelibrary/yul-dc-iiif-imageserver/pull/14

**Comment by fnibbit** [comment]
Rather than executing iiif queries, we'll evaluate the bucket performance by using direct s3 api queries.

**Comment by fnibbit** [comment]
134 (2%) of the child oids on the list of 5k we have for this ticket don't exist as ptiffs in the unencrypted prod-images bucket.   Dylan and I captured a log of the failures as the rest copied to the encrypted bucket.

**Comment by dylansalay** [comment]
We have a script to benchmark the S3 urls. This has been tested locally. We are running into issues with the workers when deploying to yul-dc-infra. Here is a link to the draft PR: https://github.com/yalelibrary/yul-dc-management/pull/429.

**Comment by fnibbit** [comment]
Script ran in 1343 seconds against the unencrypted bucket and 1305 seconds against the encrypted bucket; the apparent 3% performance improvement against the encrypted bucket is presumably noise.

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-documentation/wiki/Evaluating-S3-Encryption-Performance-for-IIIF-images

https://github.com/yalelibrary/yul-dc-management/pull/429
