### ISSUE TITLE
Add # of Children Column to ParentObjects table in Management

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#847]
I would be really nice to sort by number of children in the ParentObject table to find some with a lot of children, or with just one child, for testing purposes.

**Comment by maxkadel** [comment]
Ascending
![image](https://user-images.githubusercontent.com/45948126/102639426-09dde880-4127-11eb-87b4-ea4846aabe33.png)

Descending
![image](https://user-images.githubusercontent.com/45948126/102639444-12ceba00-4127-11eb-9378-7fef7dce8837.png)

**Comment by maxkadel** [comment]
https://collections-test.library.yale.edu/management/parent_objects

![image](https://user-images.githubusercontent.com/45948126/102923044-07e49400-445d-11eb-90f0-14c6a1198b09.png)

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/management/parent_objects
![image](https://user-images.githubusercontent.com/45948126/102926314-c0f99d00-4462-11eb-9ad8-fb6d4e31a108.png)
