### ISSUE TITLE
Gather list of IDs to import for Joel Sumner Smith collection pilot

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#848]
**ACCEPTANCE**
- [ ] We have a finalized list of IDs for works from the JSS collection that we'd like to import for the pilot.

**Comment by dl-maura** [comment]
Have a full list, will pick a smaller subset

**Comment by dl-maura** [comment]
Pick some edge cases

**Comment by MaggieZhaoYale** [comment]
volume object slavicbooks:2132784: http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:2132784  has 2250 pages

volume object: slavicbooks:1118930 http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:1118930 has 104 pages

**Comment by maxkadel** [comment]
What are the slavicbooks identifiers? Is there any relationship to the oids we've been working with? How might one get all the child identifiers / metadata related to the slavicbooks individual pages?

**Comment by dl-maura** [comment]
@maxkadel No relationship to OIDs -- these all need OIDs. Just internal identifiers for the data in the current system. These have no individual metadata for the pages beyond the physical page order (so this image is 1, this image is 2). No caption data or order labels. We have bib/barcode to get parent level data.
