### ISSUE TITLE
SPIKE: Copy JSS images to Storage@Yale hot-folder location

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#849]
**STORY**
We will need all the images for the JSS pilot collection in some kind of hot-folder location on Storage @ Yale where the management application can access them for ingest.  The management app will be responsible for assigning OIDs and moving the image files into the pair tree.

**ACCEPTANCE**
- [x] get list of 500 parents
- [x] ~~All the image files corresponding to works in the JSS pilot set are accessible on Storage @ Yale~~Do a subset of the pilot corpus as test move to Storage at Yale

**Comment by MaggieZhaoYale** [comment]
http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:152151 has 510 images

**Comment by dl-maura** [comment]
Make this copy some test batches, and a new ticket for all? Doing all will take...awhile.

**Comment by mikeapp** [comment]
Attempting to `touch` a file on the test share yields `Permission denied`
