### ISSUE TITLE
Restrict PDFs for non-Public works

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#853]
**ACCEPTANCE**
For parent objects with 'public' visibility
- [x] PDFs should always be returned

For parent objects with 'yale community' visibility
- [x] PDFs should be returned when the request comes from an 'on-campus' IP address
- [x] PDFs should be returned when the request comes from an authenticated client
- [x] The PDF service should return an HTTP unauthorized status when neither of the above conditions are met

For parent objects with any other visibility setting (including nil)
- [x] The PDF service should return an HTTP unauthorized (401) status

**REQUIREMENTS DISCUSSION**
For additional design background see: https://docs.google.com/document/d/1pwjxb5aVBNYqqkmlye6wdvNlz6eeZt0RyWpuS2t5eKE/edit#heading=h.4m0k7rj0mta9

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/416

**Comment by martinlovell** [comment]
Added ability to override the 404 returned by CheckAuthorization concern so PDFs can return 401.
(Assuming the 404 works better with IIIF viewers, so left 404 as the default.)
