### ISSUE TITLE
SPIKE: Get dynatrace runtime install working

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#854]
**ACCEPATANCE**
- [x] We can see the instance in dynatrace
  - [x] Blacklight
  - [x] Management
  - [x] Solr
  - [x] Canteloupe
  - [x] Postgres
  - [x] Workers
- [x] Dyntrace install is automated

**CLARIFICATION 12/1**
- [x] Dynatrace does not run / throw errors in local Docker environments

**Comment by mark-dce** [comment]
Hypothesis: we should not set the Dynatrace Environment Variable in local Docker environments

- [ ] Remove the variable from the local environment file in camerata

**Comment by fnibbit** [comment]
Confirmed dynatrace is not running or throwing errors in local development when building dc-base, building blacklight, spinning up blacklight.

**Comment by bobrice** [comment]
It appears that only the Solr is missing from Dynatrace for all of the environments.  MGMT, MFT, Workers, and Blacklight reporting is present on the dashboard.

**Comment by dylansalay** [comment]
I've confirmed that Dynatrace is not running locally in any of the 6 applications. 

1.) Set environment versions + `cam up`
2.) `cam sh <app_name>` for (management, blacklight, iiif_manifest) or `docker exec -it <container id> /bin/bash` for (solr, iiif_images, postgres)
3.) `ps -ef`  
4.) No sign of dynatrace/OneAgent

**Comment by DraxIndustries79** [comment]
This needs to be deployed into staging before we can verify and close.

**Comment by DraxIndustries79** [comment]
Mark will create ticket following up that it is implemented on all environments.
