### ISSUE TITLE
Refactor Code from IIIF Manifest App to Blacklight App to make Permissions Work Easier

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#858]
# Acceptance #
One should no longer need to run the iiif-manifest app in order to see either manifests or pdfs. All functionality should be contained in the blacklight app. There will be separate follow up tickets to implement the deployment.

**Comment by dl-maura** [comment]
Check CI

**Comment by mark-dce** [comment]
* Manifest & PDF move to Blacklight container - Logistics
    * Add Manifest & PDF services to Blacklight
    * Test branch on Test environment
    * Update LB on Test & restest PDF and Manifest links (shouldn’t need
    * Merge to master & Deploy new blacklight to all remaining environments
        * collections-[environment].libary.yale.edu/manifest
    * Update Load Balancer to point PDF & Manifest to Blacklight on all remaining environments
    * Decommission stand-alone Manifest service
        * Update deploy scripts (not to deploy standalone manifest container)
        * Update build scripts (not to build standalone manifest container)
