### ISSUE TITLE
Bottom Bar Pagination Arrow Styling 

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#859]
The arrows in the front of the pagination bar should match the arrows at the end 

![Screen Shot 2020-11-18 at 2.59.15 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5c62b1ce-9cd5-471c-8c27-eca7a6cb60fa)

**Comment by dl-maura** [comment]
Is only the disabled button style
![Screen Shot 2020-11-19 at 1.22.53 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/18562054-16de-477f-849f-059ecb91a602)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-11-20 at 3.18.38 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/636a1dc0-e06b-4247-8da9-f68a483cecb4)


![Screen Shot 2020-11-20 at 3.18.48 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/97a76e56-5a93-4add-99e0-c9ea2d1c92e0)

**Comment by FCRodriguez7** [comment]
Review from the test server: 

![Screen Shot 2020-11-20 at 4.27.56 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/4a75a007-0eb6-433d-9ace-7102799e8883)


![Screen Shot 2020-11-20 at 4.27.45 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/64f5e205-8144-4058-b1c2-33179fab810b)

**Comment by maxkadel** [comment]
Looks good on test
![image](https://user-images.githubusercontent.com/45948126/100112284-0f545580-2e3d-11eb-9700-1a601b16a527.png)

**Comment by mark-dce** [comment]
Looks good on UAT too.
