### ISSUE TITLE
Retire IIIF Manifest Rails App

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#860]
**ACCEPTANCE**
- [ ] Remove IIIF Manifest Repository
   - [ ] github
   - [ ] dockerhub
- [x] Remove IIIF manifest app from Camerata (iiif_manfiest templates, mention in other templates) 
    - [x] Update deploy scripts not to deploy the standalone manifest container
    - [x] Update build scripts not to build a standalone manifest container
- [x] Remove manifest app from management dashboard

See #858 & #861 for additional details

**Comment by fnibbit** [comment]
I'm starting on the camerata side of this.

**Comment by fnibbit** [comment]
Is yul-dc-camerata/bin/add-alb.sh up to date?  looking particularly at the create-target-group sections.

**Comment by fnibbit** [comment]
Used this camerata branch to deploy to infra successfully. https://github.com/yalelibrary/yul-dc-camerata/pull/296/files 
Once it's reviewed/merged I'd like to see it exercised on test before wiping the repos.

**Comment by FCRodriguez7** [comment]
The PR for the removal of manifest app from management dashboard.


https://github.com/yalelibrary/yul-dc-management/pull/466

**Comment by FCRodriguez7** [comment]
The removal of manifest app from management dashboard on test: 

![Screen Shot 2021-01-15 at 9.12.12 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a34cc38c-7cf3-4b36-b78a-a289743b92dc)

**Comment by FCRodriguez7** [comment]
The removal of manifest app from management dashboard on UAT: 


![Screen Shot 2021-01-15 at 9.33.50 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c1fe5b58-c37f-40af-b7d6-437d61ea0545)
