### ISSUE TITLE
Update firewall rule to route /pdf and /manifest to Blacklight app (basically remove the special rules)

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#861]
After https://github.com/yalelibrary/yul-dc-blacklight/pull/408 is deployed we need to adjust the load balancer rules to use these routes instead of the IIIF manifest app. This will allow the new permissions work to become functional.  code from PR 408 should go to the environment before firewall rules are changes so that no requests are dropped.

**ACCEPTANCE**
- [ ] Ensure all environments have at least blacklight v1.35.9 deployed to them (deploy the latest approved release if not)
   - [x] test
   - [x] infra
   - [x] uat
   - [x] demo
   - [x] staging
   - [ ] ~production~  see #894
- [ ] Remove the load balancer target groups to route /manifests & /pdfs (they should just default to the blacklight container)
   - [x] test
   - [x] infra
   - [x] uat
   - [x] demo
   - [x] staging
   - [ ] ~production~  see #894
- [ ] Update the load balancer target groups from /iiif to /authorized-iiif. /authorized-iiif should only be accessible within Yale's IP range.
   - [x] test
   - [x] infra
   - [x] uat
   - [x] demo
   - [x] staging
   - [ ] ~production~  see #894

**Comment by mark-dce** [comment]
* Manifest & PDF move to Blacklight container - Logistics
    * Add Manifest & PDF services to Blacklight
    * Test branch on Test environment
    * Update LB on Test & restest PDF and Manifest links (shouldn’t need
    * Merge to master & Deploy new blacklight to all remaining environments
        * collections-[environment].libary.yale.edu/manifest
    * Update Load Balancer to point PDF & Manifest to Blacklight on all remaining environments
    * Decommission stand-alone Manifest service
        * Update deploy scripts (not to deploy standalone manifest container)
        * Update build scripts (not to build standalone manifest container)

**Comment by orangewolf** [comment]
When this is deployed Cantaloupe needs to be moved to /authorized-iiif and /iiif needs to be sent to Blacklight in the load balancer. The new /authorized-iiif should only be accessible from within Yale's ip range, which would allow the cluster to see it (and thus proxy it) but would not allow outside of network to access it at all.

**Comment by kbcarter** [comment]
![image.png](https://images.zenhubusercontent.com/5e6002742347da559ce428f3/8ba5940b-9a21-474f-aab4-8e015d02a584)
Changed /iiif* to /authorized-iiif* for test environment
