### ISSUE TITLE
Get the rest of the font types for Mallory and Mallory MP

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#863]
We only have Woff and Woff2 for the Mallory and Mallory fonts, but we need the eot, ttf and maybe eot?#iefix (this exists for other fonts we have, not sure if it is standard).

- [ ] Fix CORS issues (devops)
- [ ] Get the other versions of Mallory fonts on static site
- [ ] Get the other versions of Mallory MP fonts on static site
- [ ] Add new fonts to the typography

**Comment by mikeapp** [comment]
Some fonts from the static bucket are failing CORS while others succeed, I have no idea why that would happen:

![Screen Shot 2020-11-20 at 10.16.26 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/a4d85576-f0c7-4431-89ac-3452409782b0)

A test of that file using `curl` looks good.   I wonder if this isn't causing the issues we see in Firefox.

It looks like .woff an .woff2 cover the major browsers:  https://transfonter.org/formats

**Comment by ra359** [comment]
fyi - current s3 static config:

<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>*.library.yale.edu</AllowedOrigin>
   <AllowedHeader>*</AllowedHeader>
   <AllowedMethod>GET</AllowedMethod>
   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>
   <AllowedMethod>DELETE</AllowedMethod>
   <MaxAgeSeconds>3000</MaxAgeSeconds>
 </CORSRule>
</CORSConfiguration>

**Comment by mikeapp** [comment]
And now MalloryMP-Black is working, no idea why.   

![Screen Shot 2020-11-23 at 1.25.33 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/51aa8847-d27b-4ce5-b6f9-9732c3f5a9e9)
