### ISSUE TITLE
Configure ALB to use TLS versions that comply with Yale Security Policy

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#868]
**ISSUE**
The production site at https://collections.library.yale.edu should support the latest TLS version in order to comply with Yale security standards.

**ACCEPTANCE**
- [x] Confirm TLS versions which should be enabled and disabled
- [x] Update the ALB listener policies as needed
    - [x] demo
    - [x] infra
    - [x] prod
    - [x] staging
    - [x] test
    - [x] uat
- [ ] Update the camerata build scripts to apply the correct security policy when building new clusters
- [ ] Build a new cluster using the updated script

**BACKGROUND**
* See the following AWS documentation for available TLS security policies https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
We probably want ELBSecurityPolicy-TLS-1-2-Ext-2018-06

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/a9e90659-0d42-48f3-92fe-54634221c8ca)

**Comment by ra359** [comment]
Security policy "ELBSecurityPolicy-TLS-1-1-2017-01" applied to

- [x] alb-yul-dc-prod
- [x] alb-yul-dc-staging
- [x] alb-yul-dc-uat
- [ ] alb-yul-dc-demo
- [ ] alb-yul-dc-infra
- [ ] alb-yul-dc-demo
- [ ] alb-yul-dc-test

**Comment by kbcarter** [comment]
All ALs have been updated to use TLS 1.1
