### ISSUE TITLE
SPIKE: Button Accessibility and Design Part 2

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#874]
I reviewed the buttons and spoke with Kara and we need some final tweaks:

- [ ] Some of the buttons when changed to semantic broke the accessible styling (so the color contrast is wrong). See start over button
- [ ] For the ones where we used role, we need to add some other things so that they activate with a space bar (this happens with button tag but not with links

I propose picking one convention (whichever checks all the boxes) and applying this to all, and confirming styling is correct (colors don't revert). Look into button_to and button_tag.

(if this takes more than a 3, drop it and we will go back for designs)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/462

**Comment by mark-dce** [comment]
I don't know what to look at to sign off on this ticket...

It would be helpful to write down which buttons were not meeting requirements and what design solution was selected to address the issue.

**Comment by dl-maura** [comment]
Will demo (some of the color things are hard to describe) but

- [ ] Colors are accessible (text is contrasted and not disappearing)

- [ ] I can 'click' buttons with space bar

- [ ] Remove filter/facet button area is larger (the whole box not just the x)

**Comment by martinlovell** [comment]
Check button updates:

- Search button on landing page does not have contract issues regardless of pseudo classes.

- Start Over button on item and index page is an actual button and does not contain an anchor. (should have tab stop and work with space bar)

- "You searched for" constrain links should be buttons (tab and spacebar should work to remove them)

- All buttons at the bottom of advanced search are actual buttons.

- Advanced Search from /catalog pages is now a button.

- Back to Search Results from Item page is a button.
