### ISSUE TITLE
Update header carets

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#875]
**ACCEPTANCE**
- [ ] Expand & Collapse carets use the same font and characters as the main library home page

**DETAILS**
Down Arrow
```
content: '\f0d7';
font-family: 'FontAwesome';
```

Up Arrow
```
content: '\f0d8';
font-family: 'FontAwesome';
```

**CURRENT**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/7708ffdc-1ccc-4a69-a92c-e09a54d981ab)

**DEISRED**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/6395b903-5cb3-4b8c-b921-a36671f2a551)

**Comment by FCRodriguez7** [comment]
The Zeplin board shows: 

![Screen Shot 2020-12-03 at 12.15.42 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9e2e22c7-942b-4291-ac4a-7fe2f9bf49f2)

The arrows are slightly different than what's current on the site, but not the same as the desired image above.

**Comment by mark-dce** [comment]
At our meeting on Tuesday, Matt Walker said "the arrows should match the ones on the main library site".  Let's confirm with him.

**Comment by FCRodriguez7** [comment]
The chevron arrow seems to be the correct one: 


![Screen Shot 2020-12-03 at 1.01.17 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/92ff4875-504a-4ef0-8c55-0870cf843f2b)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-12-03 at 3.02.14 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/1ff3defd-4de1-4bb8-9736-0a509017ae83)

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-12-04 at 11.11.37 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/847f5927-bf2a-4aa4-9255-6db0386b205b)

**Comment by FCRodriguez7** [comment]
The PR https://github.com/yalelibrary/yul-dc-blacklight/pull/433

**Comment by FCRodriguez7** [comment]
Feature on Test: 

https://share.getcloudapp.com/mXu5AdYe
