### ISSUE TITLE
Add sort by year options to search results

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#876]
**ACCEPTANCE**
- [x] I have a sorting option "Year (ascending)" for search results
- [x] I have a sorting option "Year (descending)" for search results
- [x] The option sorts results by `year_isim` as the primary sort
- [x] The option sorts results by `id` as the disambiguation sort (i.e. if more than one item has the same year)

**Comment by FCRodriguez7** [comment]
**Sort function for the Test Environment**

**Descending**
![Screen Shot 2020-12-02 at 12.22.48 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/77bab48b-5d26-4849-83d5-230e901b9949)

![Screen Shot 2020-12-02 at 12.23.03 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a865be94-1c13-4739-aa8d-2a0dbc3d2378)



**Ascending**

![Screen Shot 2020-12-02 at 12.23.24 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f976fc25-f87a-441e-881f-a3ebe67d96b6)

![Screen Shot 2020-12-02 at 12.23.34 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/83b87817-ba9e-4433-b465-3aed867c9a31)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/427
