### ISSUE TITLE
Update date slider

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#877]
**STORY**
We initially implemented the date slider on a field that did meet Blacklight Range Limit's data requirements (see https://github.com/projectblacklight/blacklight_range_limit#requirements).  We now have a year field that contains integer data and need to update the date facet.

**ACCEPTANCE**
- [x] I can limit my search results by their year - i.e. `year_isim`

**NOTE**
This story replaces the former date slider bug ticket #549

**Comment by dl-maura** [comment]
The date_ssim and dateStructured_ssim are not always the same.
e.g. if dateStructured_ssim is 1986, date_ssim is 1971
In one of our old system, we have facet date, display date, sort date and search date use different fields, and may have inconsistent sorting or search result.
It is reasonable that the date_ssim, and dateStructured_ssim are both used as the search date;
I wonder if the sort date also sorted by the same values as the search fields. (I know it is not in the scope of this ticket)

**Comment by edejesusyale** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/432

**Comment by FCRodriguez7** [comment]
I am not sure if this is the correct output: 

![Screen Shot 2020-12-04 at 1.01.57 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/61b18fe9-f35f-46bd-afe8-8837004c6a22)

**Comment by dl-maura** [comment]
Slider is no longer jumping and looks normal on test:
![Screen Shot 2020-12-15 at 12.47.55 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/3c9d6b45-01bc-4017-9102-8929f8f9f8a3)

![Screen Shot 2020-12-15 at 12.48.06 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c70d51bf-59a2-44ab-b7a3-80f859c84f31)
