### ISSUE TITLE
SPIKE: Test access controls on staging environment

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#880]
**STORY**
We need an environment that we can access from the public internet to test access controls (otherwise we're alway on-campus by virtue of being connected to the VPN).  So, we need to make an exception to our usual workflow and deploy related code to staging in order to test it.

**ACCETPANCE**
- [x] Test that an item can be changed from "Public Access" to "Yale Community Access" on management in staging
- [x] Test that non-VPN access to staging shows this item as "restricted"
    - [x] Thumbnail
    - [x] Universal Viewer
    - [x] Manifest
    - [x] Link to an image directly from the manifest
    - [x] pdf
- [x] Write up tickets for any unexpected behaviors

**Comment by maxkadel** [comment]
Yale Community Only
- https://collections-staging.library.yale.edu/catalog/11872480
- On VPN
  - Search page
![image](https://user-images.githubusercontent.com/45948126/102380945-97d69980-3f96-11eb-9650-565183426121.png)
  - Show page
![image](https://user-images.githubusercontent.com/45948126/102381003-ade45a00-3f96-11eb-8535-268d307712de.png)
  - Can see manifest
  - Can see / download PDF

**Comment by dl-maura** [comment]
Yale Community Only NOT on VPN:

**Thumbnail**
![Screen Shot 2020-12-16 at 12.02.02 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/c1d5d88f-38a3-4cfa-a4ba-bef60e0e6b73)

**Item View**
![Screen Shot 2020-12-16 at 12.02.08 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/45c2967e-59f8-462c-b1ad-5e4a78ca34a8)

**Manifest**
![Screen Shot 2020-12-16 at 12.02.14 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/f4012bc8-114e-4ac7-81f4-25f6220f588f)


**PDF**
![Screen Shot 2020-12-16 at 12.02.21 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/a54bba06-21f5-4898-9fa9-fa99b3b36168)

**Trying to get to a tile**
![Screen Shot 2020-12-16 at 12.02.36 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/569afb83-c5ce-45e4-85ea-78d1c700eeb7)

**Comment by maxkadel** [comment]
On VPN - Private
https://collections-staging.library.yale.edu/catalog/11873651
Before:
![image](https://user-images.githubusercontent.com/45948126/102381538-5bf00400-3f97-11eb-985f-4215fdb3de4c.png)
![image](https://user-images.githubusercontent.com/45948126/102381485-4b3f8e00-3f97-11eb-84e8-076fdcbe3c58.png)

After:
