### ISSUE TITLE
Create destination for JSS image files for Test

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#881]
**ACCEPTANCE**
- [X] Decide on moving images to ~an S3 bucket or~ Storage @ Yale mount
- [x] Create a new Storage @ Yale share / mount point for JSS content
- [X] Mount that share to management workers
- [x] Mount the folder to the existing JSS server (for copying - see #849)

**Comment by DraxIndustries79** [comment]
Will make a new ticket if we cannot close this in 48.

**Comment by ra359** [comment]
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU/jss_import is now mounted on dcoll.library.yale.internal:/jss_import_test

Waiting for permissions on UAT and PRD export

**Comment by ra359** [comment]
All (3) mounted on dcoll.library.yale.internal now:

wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU/jss_import
                       524288000    28369568   495918432   6% /jss_import_test
wcsfs00.its.yale.internal:/NFS_SFS_std_mult_000/Goobi_Deposits_UAT-CC1741-BRBLDSU/jss_import
                      5368709120           0  5368709120   0% /jss_import_uat
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_004/Goobi_Deposits_PROD-CC1741-BRBLDSU/jss_import
                     10737418240           0 10737418240   0% /jss_import_prod

**Comment by ra359** [comment]
We may have to dork around w/ permissions to make this write-able from whatever process will be doing that on dcoll.library.yale.internal .
