### ISSUE TITLE
Gallery view should always suppress item numbers

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#885]
**ACCEPTANCE**
Regardless of how I get to gallery view, 
- [x] item numbers should never be displayed

**CURRENT BEHAVIOR**
Doesn't show numbers: https://collections.library.yale.edu/catalog?q=&search_field=all_fields&view=gallery
Shows numbers: https://collections.library.yale.edu/catalog?search_field=all_fields&q=  - i.e. delete the `view` query param
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/6846d831-fbc9-4b98-9432-3ef6c316a6f3)

**DESIRED BEHVAIOR**
Should not show numbers whether or not the URL has the query parameter `&view=gallery` even when in gallery view from a previous command
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/cd92720c-33da-4197-ba33-06ce0fa30398)

**Comment by martinlovell** [comment]
Number of items per page also is off when gallery mode is active but parameter is not present.  Will fix that also.

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/441

**Comment by mark-dce** [comment]
With or without query parameter 
* https://collections-uat.library.yale.edu/catalog?q=&search_field=all_fields&view=gallery
* https://collections-uat.library.yale.edu/catalog?q=&search_field=all_fields

both give the same view:
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/0669d087-58a2-4527-8e52-223e79f38ac3)
