### ISSUE TITLE
SPIKE: Document how to verify workers are working

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#886]
**ACCEPTANCE**
- [ ] We have a definitive/documented way to test that workers are running as expected
- [ ] We have a definitive/documented way to restart workers when they are not running

**Comment by fnibbit** [comment]
https://github.com/yalelibrary/yul-dc-documentation/wiki/Confirming-whether-delayed_job-workers-are-running-as-expected
