### ISSUE TITLE
Update Blacklight to not use deprecated Solr fields of MC101

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#888]
- [x] abstract_ssim: json_to_index["abstract"], # replaced by abstract_tesim
- [x] alternativeTitle_ssim: json_to_index["alternativeTitle"], # replaced by alternativeTitle_tesim
- [x] box_ssim: extract_container_information(json_to_index), # replaced by containerGrouping
- [x] date_tsim: json_to_index["date"], # replaced by date_ssim
- [x] identifierShelfMark_ssim: json_to_index["callNumber"], # replaced by callNumber_ssim
- [x] identifierShelfMark_tesim: json_to_index["callNumber"], # replaced by callNumber_tesim
- [x] oid_ssim: oid, # replaced by oid_ssi
- [x] ~~geo_subject_ssim: json_to_index["geoSubject"], # replaced by geoSubject_ssim~~
- [x] material_ssim: json_to_index["material"], # replaced by material_tesim
- [x] orbisBarcode_ssim: json_to_index["orbisBarcode"] || json_to_index["barcode"], # replaced by orbisBarcode_ssi
- [x] orbisBibId_ssim: json_to_index["orbisBibId"], # replaced by orbisBibId_ssi
- [x] projection_ssim: json_to_index["projection"], # replaced by projection_tesim
- [x] publicationPlace_ssim: json_to_index["creationPlace"], #replaced by creationPlace_ssim
- [x] publicationPlace_tesim: json_to_index["creationPlace"],#replaced by creationPlace_tesim
- [x] recordType_ssim: json_to_index["recordType"], # replaced by recordType_ssi
- [x] references_ssim: json_to_index["preferredCitation"], # replaced by references_tesim
- [x] references_tesim: json_to_index["preferredCitation"], # replaced by preferredCitation_tesim

- [x] scale_ssim: json_to_index["scale"], # replaced by scale_tesim
- [x] sourceCreated_ssim: json_to_index["sourceCreated"], # replaced by sourceCreated_tesim
- [x] sourceDate_ssim: json_to_index["sourceDate"], # replaced by sourceDate_tesim
- [x] sourceEdition_ssim: json_to_index["sourceEdition"], # replaced by sourceEdition_tesim
- [x] sourceNote_ssim: json_to_index["sourceNote"], # replaced by sourceNote_tesim
- [x] sourceTitle_ssim: json_to_index["sourceTitle"], # repleaced by sourceTitle_tesim
- [x] subject_topic_tsim: json_to_index["subjectTopic"], # replaced by subjectTopic_tesim and subjectTopic_ssim
- [x] title_tsim: json_to_index["title"] # replaced by title_tesim

----
- [x] Check with Maura
   - [x] partOf_tesim: json_to_index["partOf"], checked with Maura; a request to remove the field 
   - [x] partOf_ssim: json_to_index["partOf"], check with Maura ; a request to remove the field

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/431

**Comment by martinlovell** [comment]
From @rebeccahirsch :
We should remove the Collection Name index and show fields and the Digital Collection facet field from BL.  These are using PartOf.
The values from LB are not correct, and we need to think about how to do it with Voyager and ASpace for phase two before displaying those fields.  (Also, Collection Name and Digital Collection are not the same thing.)

So, for now, BL will not display PartOf and it does not need to be indexed.

**Comment by FCRodriguez7** [comment]
Don't merge until the metadata update is completed.

**Comment by FCRodriguez7** [comment]
The blocker is deployment not work completion.
