### ISSUE TITLE
Index OID so Blacklight can connect to manifests

### ISSUE THREAD

**Issue by bess** [yalelibrary/YUL-DC#89]
The voyager records contain most of the metadata we want to display in Blacklight. However, in order to connect the voyager records to the manifests & images, we need to also add the work-level OID from ladybird.

- [ ] Augment the current process for indexing voyager records to fold in the work-level OID from ladybird

When this is done, each record in Blacklight will contain an OID that can be used to connect it to an image.

**Comment by mikeapp** [comment]
One possibility to consider is starting with the Ladybird record, which contains a reference to the Voyager BIBID (or partial ASpace URI)

**Comment by yjyale** [comment]
"orbisBibId" is voyager bib id. See the bibid and oid connection from the example oid-2003431.json:

**"orbisBibId": "9734763",**
  "orbisBarcode": "39002091549668",
  "importUrl": "https://pre1600ms.beinecke.library.yale.edu/docs/pre1600.ms407.htm",
  "references": [
    "Albergati Bible. General Collection, Beinecke Rare Book and Manuscript Library, Yale University.",
    "Shailor, B. Catalogue of Medieval and Renaissance Manuscripts in the Beinecke Rare Book and 
  **"oid": 2003431,**
