### ISSUE TITLE
Adjust Manifest fields to reflect changes in metadata display

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#891]
There are fields in the IIIF manifests that have been removed from the overall metadata display, such as record type, URI (?) and source.   The manifest metadata should be brought into sync with what we are displaying on screen.   

![Screen Shot 2020-12-04 at 9.26.02 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/b0c3732c-0597-4887-b3c2-b4db1d52c1f7)

Also, the OID is not populated.

**Acceptance**
- [x] The manifest displays the same metadata fields in the same order as the web UI.
- [x] The OID is displayed

**Comment by fnibbit** [comment]
need to put breadcrumbs -- oids to look at + what fields
