### ISSUE TITLE
IIIF Reverse proxying not working yet

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#893]
* Released Blacklight v1.35.12, which includes http / https fix
* Deployed Blacklight v1.35.12 to collections-test
* Manifests have the expected public iiif url 
  * e.g. https://collections-test.library.yale.edu/manifests/2.json includes https://collections-test.library.yale.edu/iiif/2/10628961/full/!200,200/0/default.jpg 
  * Going directly to https://collections-test.library.yale.edu/iiif/2/10628961/full/!200,200/0/default.jpg works as expected
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/fa3b6827-e67b-4fee-a14e-adcbf62020fe)
  * Going to the show page for this object and looking at it in Universal viewer (https://collections-test.library.yale.edu/catalog/2), the main images do not load. It appears that the thumbnails may load, but that may be because of caching.
  * Looking at the network tab and re-loading the page, it appears that the browser is requesting the internal IIIF url, aka https://yul-dc-test-images.yul-dc-test/iiif/2/10628961/full/24,/0/default.jpg
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/35cd31d9-5e42-4e33-8572-74ee2b9ba3f7)

**Comment by orangewolf** [comment]
https://share.getcloudapp.com/P8umm5Jp < video of UAT.  Note that IP based non-restriction is not currently set up for UAT. It seems to be working as a code path, but the env var is not set of UAT at the moment... which makes testing this in UAT a lot easier.
