### ISSUE TITLE
Update /pdf, /manifest, and /iiif routing to support access restrictions on production

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#894]
**ISSUE**
Once we've verified all of the access restriction code and configuration is working successfully in the staging environment, we need to promote those changes to production.

**ACCEPTANCE**
- [x] Ensure production at least blacklight v1.36.7 deployed (or deploy the latest approved release if not)
- [x] Remove the load balancer target groups on production to route /manifests & /pdfs (they should just default to the blacklight container)

**Comment by martinlovell** [comment]
Should /authorized-iiif be accessible from Yale's IP range, or just from the blacklight container?
Nothing else should need access, and allowing Yale IP range to access it will allow anyone on the Yale network to access any image by going directly to the IIIF server.  Nginx on the blacklight container needs access to handle the proxy.

**Comment by bobrice** [comment]
Complete.  Blacklight updated to v1.36.7, ALB listeners were changed to include IP restriction, add authorized-iiif targets, and removed manifest and pdf targets.
