### ISSUE TITLE
Show Child OID information in IIIF About This Item Manifest

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#895]
We need to be able to see the child OID ID and caption/label information in the About this Item sidebar

- [x] Image OID shows up
- [x] Image Caption is displayed (can't be tested without a goobi item?)
- [x] Image label is displayed (legacy uses this for caption and label data)

**Comment by dl-maura** [comment]
Need to write tests

**Comment by dl-maura** [comment]
Made a ticket for testing pull of captions

**Comment by maxkadel** [comment]
* This is included in a release, but it cannot be accepted until manifests are generated using Management v2.24.1 on collections-uat.

**Comment by martinlovell** [comment]
See:
https://collections-uat.library.yale.edu/catalog/17290885
https://collections-uat.library.yale.edu/catalog/17290880

![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/781452ba-a7b5-4b31-ae6d-efcc423d0b59)
