### ISSUE TITLE
SPIKE: investigate performance of fully proxying IIIF through Blacklight

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#896]
**ISSUE**
We're running into issues trying to bypass proxying IIIF images on their return trip from cantaloupe to the browser.  We have implemented working versions that do not bypass on the return trip.  This introduces and additional hop, but we're unsure the overall cost of that addition in terms of speed.

**ACCEPTANCE**
- [ ] Implement the two-way proxying solution in blacklight
- [ ] Time the round trip for an few IIIF requests

**Comment by dl-maura** [comment]
Not needed, current proxy is plan
