### ISSUE TITLE
Merge manifest fixture repos

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#90]
- [x] merge https://github.com/yalelibrary/manifests-yul (older & useful for history) into https://github.com/yalelibrary/yul-dc-fixture-manifests (newer & better) (keep `fixture` in the name)
- [x] update https://github.com/yalelibrary/yul-dc-iiif-manifest accordingly

**Comment by bess** [comment]
These repos have been merged. The docker image didn't need any changes.
