### ISSUE TITLE
Ingest Yale Only Items to Production

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#905]
**STORY**
As a repository owner, I would like to be able to deliver Yale Community Only objects, so that Yale community members can conduct scholarship using restricted resources.

**ACCEPTANCE**
- [ ] All of the Yale Only Items from the pre-gap object list are available to logged in or network connected users on the **PRODUCTION** site.
- [ ] Items are restricted from public (non-authenticated, non-yale-network) view

Update: ingested all non problem items

**Comment by dl-maura** [comment]
We have about 400 items with various errors -- some are related to ticket #1031 so we plan to prioritize that and re-run the list of fails
