### ISSUE TITLE
Set team up on Yale docker hub

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#91]
Get everyone's docker hub ids
Add them to Yale's docker hub
Make Yale docker hub images public

For DCE/Notch8
- [x] Mark
- [x] Bess
- [x] McClain
- [x] Rachel
- [x] Max - Dockerhub ID is mkadel
- [x] Jez
- [x] Julie
- [x] Alisha
- [x] JP
- [x] Maura

**Comment by alishaevn** [comment]
my docker hub un is @alishaevn

**Comment by jpengst** [comment]
Mine ID is jpengstrom

**Comment by fnibbit** [comment]
dockerhub id = fnibbit
