### ISSUE TITLE
Update objects from MC using new mappings on STAGING

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#910]
**STORY**
As a scholar, I would like to view objects using the most recent metadata mappings, so that I'm seeing the most complete view of descriptive metadata possible.

**ACCETPANCE**
- [x] Ensure we're making calls to latest API for MC
- [x] Increase the worker count as needed on the environment
- [x] make sure staging has most recent code release  (At least version **v2.27.2** for management)
- [x] Refresh the metadata for all object on **STAGING** from the Metadata Cloud - i.e. click the "Update Metadata" button on the parent object tab (Make sure all dependent cards are released and on Staging before clicking.)
- [ ] Set the worker count back to 1 or 2 on the environment
- [ ] Spot check items and write up tickets for any issues found

**Comment by dl-maura** [comment]
Running well!

**Comment by martinlovell** [comment]
Done except for PDF.

Staging went slowly, but very smoothly with the same code as production.
Only 30 + 1 workers, but it seems like things worked well.  (No disk space issues, etc.  Some jobs failed the first time, but reran without issues.)

There are almost as many Parent Objects in staging as production.
Searching for a parent in the management app works fine without any timeouts.
