### ISSUE TITLE
Update objects from MC using new mappings on PRODUCTION

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#911]
**STORY**
As a scholar, I would like to view objects using the most recent metadata mappings, so that I'm seeing the most complete view of descriptive metadata possible.

**ACCETPANCE**
- [x] Make sure production has the latest releases
- [x] Increase the worker count as needed on the environment
- [x] Update prod to use most recent releases
- [x] Refresh the metadata for all object on **PRODUCTION** from the Metadata Cloud - i.e. click the "Update Metadata" button on the parent object tab
- [ ] Set the worker count back to 1 or 2 on the environment
- [ ] Spot check items and write up tickets for any issues found

**Comment by maxkadel** [comment]
Before - couple of Hebrew dates that were indexed incorrectly [year search](https://collections.library.yale.edu/catalog?q=&search_field=all_fields&sort=year_isim+asc%2C+id+desc&range%5Byear_isim%5D%5Bbegin%5D=2240&range%5Byear_isim%5D%5Bend%5D=5686&commit=Apply)
![image](https://user-images.githubusercontent.com/45948126/105419617-fb468d80-5c0c-11eb-8db7-33ab85414e7c.png)
