### ISSUE TITLE
Update Landing/homepage

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#912]
**ACCETPANCE**
- [x] Update design to match Zeplin
  - [x] Handheld
  - [x] Tablet
  - [x] Desktop

- [x] Update text to be a clickable button and not exclusively the image.

**NOTE** 
Just use a single hero image

**Comment by dl-maura** [comment]
https://app.zeplin.io/project/5f0fd2b5fa16ac9ddd54d6fa

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-12-08 at 1.31.45 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2458473c-6e10-40ea-a3ee-a6df42d6845a)


-----


![Screen Shot 2020-12-08 at 1.31.56 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/9965ce97-ef70-4a10-b1d4-96227d092124)



----

![Screen Shot 2020-12-08 at 1.32.24 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5998cf6b-a696-4137-848f-a21d739961b9)![Screen Shot 2020-12-08 at 1.32.32 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ed0ec60b-37c7-4804-95d8-0ca9a23c48a3)

**Comment by FCRodriguez7** [comment]
![Re Homepage Design Resolution Question.tiff](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b0df60f5-5d77-420e-add8-9156648ecf34)

**Comment by FCRodriguez7** [comment]
Communication for Images

![Screen Shot 2020-12-10 at 9.50.34 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a40205d7-b68e-4dd2-90b8-1f9935ce5183)

**Comment by alishaevn** [comment]
the work to remove the carousel and use a single hero image was completed as part of https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/913. the PR for that work has been merged into master.

**Comment by FCRodriguez7** [comment]
Mobile Design:  In the current design the image is only clickable.  Now that the title text not on the image, should both the image and text be clickable?

![Screen Recording 2020-12-11 at 11.00.01 AM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/323d4fea-216a-4e90-b647-6da39c86ba05)

**Comment by FCRodriguez7** [comment]
**Completed Design**

**Mobile**
![Screen Shot 2020-12-15 at 16.41.31.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/457456af-4162-4861-bba6-4a09fa9cee70)

----
**Tablet View 1** 
![Screen Shot 2020-12-15 at 16.45.13.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5ccb4599-2e54-4331-9c62-6667fbbe2744)

-----
**Tablet View 2** 

![Screen Shot 2020-12-15 at 16.46.07.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/57362603-27a3-4ed5-b5d2-9f3a81284f1a)

----
**Desktop 1200 px**
![Screen Shot 2020-12-15 at 16.52.40.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a4282e2e-cfc3-4149-8f07-709d3137b8ca)


**Desktop 1366 px [Zeplan Design]**
 

![Screen Shot 2020-12-15 at 16.51.58.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2aec84aa-8665-4028-bdf1-61fa0833effb)

**Comment by FCRodriguez7** [comment]
The Stenzel Collection title does not appear fully.  

![Screen Shot 2020-12-16 at 11.55.38 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5a19a0da-e92a-4fd7-b424-236d2aec74a0)

**Comment by FCRodriguez7** [comment]
Yale Display Roman does not appear in FireFox or Chrome.  

Error message: downloadable font: rejected by sanitizer (font-family: "YaleDisplay-Roman" style:normal weight:400 stretch:100 src index:0) source: https://static.library.yale.edu/fonts/yaledisplay/YaleDisplay-Roman.eot

**Comment by mark-dce** [comment]
Let's pull the font issues to a separate ticket if needed.

Besides that, this looks great.  Nice work!

**Comment by alishaevn** [comment]
@mark-dce the font issue was addressed on https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/948.
