### ISSUE TITLE
Enable S3 encryption on INFRA, TEST, UAT, and DEMO

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#915]
**ISSUE**
We've tested S3 encryption and haven't seen any negative performance impact.  We'd like continue experimenting with a rollout of S3 encryption by enabling it on non-public facing environments.

**ACCEPTANCE**
Enable S3 encryption on
- [x] Infra
- [x] Test
- [x] UAT
- [x] Demo

Testing Steps:
- [x] Ingest some sample items on UAT
- [x] Test IIIF user experience on those sample items and make sure it seems normal

**Comment by fnibbit** [comment]
Looking to identify appropriate sample items -- is "what are some oids that have been ingested in this environment but not that environment" a thing we've already scripted?

**Comment by mark-dce** [comment]
Can we just use one of the higher numbered batched ingested into staging and prod and just pull 5-15 rows from the beginning of one of those CSVs?

**Comment by mark-dce** [comment]
e.g. https://gist.github.com/mark-dce/f62f5aab33e8c00cee35c40eeb17f4b3  (pulled from the Batch 266 page in the staging management app)

**Comment by dylansalay** [comment]
We've checked some oids for newly ingested objects and panned/zoomed with no issues.
![Screen Shot 2020-12-16 at 9.31.38 AM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/539462bc-e5d9-4b37-9ea7-4a4091c09d7a)
