### ISSUE TITLE
Update smoke tests to reflect newest code changes

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#916]
**ISSUE**
Smoke tests have not been updated to reflect a variety of recent code changes and are currently failing on Jenkins.

**ACCEPTANCE**
- [x] Smoke tests pass on their respective Jenkins environments

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/2ebce9f5-5cee-4e30-a238-b0800d0d4c2a)

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/2c7d72c9-4aa1-4e54-99ef-eb1ffba8031b)  I noticed while working on this that the CLUSTER_URL array in the jenkins scripts doesn't include staging and prod, which results in the smoke tests being called with an empty string as the hostname after deploys to those environments.  That's not the only thing that needs updating, but it'd help.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/8350be6d-db77-4627-a340-8445eac42067)

Showing these tests pass locally.

**Comment by DraxIndustries79** [comment]
We'll close this when we see blue on any environment; we can make tickets for additional environments if necessary.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/a8e8d278-2e2f-4503-9243-4af9941f3102)

Latest deploy to test with these camerata changes merged shows blue.
