### ISSUE TITLE
SPIKE: Resolution and Reingest of Failed Imaging Works

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#918]
Follow up from [ticket #899](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/899).  McClain sent a list of imaging works to Maura to investigate.  

**ACCEPTANCE:**
- [ ] Imaging works investigated and resolved
  - [x] Corrupt images
  - [ ] ~~Graya reformat~~ new ticket
  - [ ] ~~Missing images -- LB mismatch (goes to phase 2)~~ new ticket
- [ ] ~~Works reingested~~ new ticket
- [ ] ~~Works from list are viewable on production~~ new ticket

**Comment by DraxIndustries79** [comment]
Reingest after resolved

**Comment by DraxIndustries79** [comment]
This has been moved into three different categories of failures.
- Corrupt
- Moved to Phase 2
- Photoshop issues, which will be worked on

**Comment by dl-maura** [comment]
Corrupt images are in process.

Graya reformat happening today.

I will share the list of 'not coming after all' with the team

**Comment by dl-maura** [comment]
Graya may actually be a corruption issue to, working with David now
