### ISSUE TITLE
Can't use searching in batch process status screen

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#919]
I tried to do a search on the batch process screen (where it lists all the items) and it got angry![Screen Shot 2020-12-10 at 2.32.57 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/39edef45-1db0-4941-a5d0-18963311412c)

**Comment by mikeapp** [comment]
In data tables now.
