### ISSUE TITLE
Test package of JSS items through Goobi

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#922]
- [x] Stage 5 test items in the import folder
- [x] Import 5 items through Goobi
  - [x] add jss to import button
- [x] Ingest into collections-test
- [x] Ingest into collections-uat
- [x] Validate test items against current JSS site (We need to trigger an automated ingest on UAT and compare the item counts to see if they're OK.)

Note: Maura has been doing manual XML upload; could use a share, but they are on a different folder.

**Comment by dl-maura** [comment]
Made a ticket for the UAT and Prod Goobi: #1095

**Comment by dl-maura** [comment]
UAT is good to go, need to get Maggie permissions on prod

**Comment by dl-maura** [comment]
UAT is running an ingest but I think it's behind some other jobs...

**Comment by MaggieZhaoYale** [comment]
> UAT is good to go, no prod ingest until ownership groups

I have the permission to write image to prod. Thank you.

**Comment by DraxIndustries79** [comment]
We need to trigger an automated ingest on UAT and compare the item counts to see if they're OK.

**Comment by DraxIndustries79** [comment]
May need to contact Intrandra.

**Comment by MaggieZhaoYale** [comment]
automated ingest on UAT :
- bib 2486030 barcode 39002064098867 has 1244 children.
https://collections-uat.library.yale.edu/management/batch_processes/166/parent_objects/30013489
compare with jss collection: http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:46045 the volume has 1244 pages

- bib 2486030 barcode 39002064098891  has 1572 children
https://collections-uat.library.yale.edu/management/parent_objects/30009975
compare with jss collection: http://jss.library.yale.edu/DPresInterface/PageViewServlet?pid=slavicbooks:101476 has 1572 pages
