### ISSUE TITLE
IIIF Manifest thumbnail and startCanvas

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#923]
With the addition of the ability to select a "representative thumbnail" in the management interface, we can now implement two additional features in the IIIF Manifest:

1. The IIIF Manifest can supply a `thumbnail` property so that viewers can display a preferred image rather than just the first image of the first canvas. https://iiif.io/api/presentation/2.1/#thumbnail

2. The IIIF Manifest can contain a `startCanvas` property so that the viewer can start on the first 'interesting' Canvas of the work. https://iiif.io/api/presentation/2.1/#startcanvas

**Acceptance**

- [ ] Provide the "representative thumbnail" image's IIIF Image service as the `thumbnail` for the manifest; otherwise use the first child to create the thumbnail link.
- [ ] If the ChildObject corresponding to the "representative thumbnail" is one of the first 10 children for that Parent, set its Canvas ID as the Manifest's  `startCanvas`.

**Comment by edejesusyale** [comment]
Parent with representative child with order number of 11 or higher:

![Screen Shot 2021-04-22 at 1.55.47 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/cc507244-d5f9-4b74-bbd6-eb20d3f06d65)

**Comment by mikeapp** [comment]
Here's an example from Oxford:  https://iiif.bodleian.ox.ac.uk/iiif/manifest/bacf016f-4722-44a9-a1a4-f5647057fd2d.json

![Screen Shot 2021-04-22 at 2.05.17 PM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/219a26ea-1522-4fc6-b58a-f4ddda4dc7de)

**Comment by edejesusyale** [comment]
Using image resource for the thumbnail:

![Screen Shot 2021-04-26 at 1.53.43 PM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/bd1e06c9-72a3-4686-b21f-b5a89efba6b8)

**Comment by FCRodriguez7** [comment]
The feature needs a metadata update.

**Comment by edejesusyale** [comment]
On collections-test

![Screen Shot 2021-04-27 at 11.32.14 AM.png](https://images.zenhubusercontent.com/5e5d4ad7fa7805fc6ebcbfd1/1fce34fc-9c0c-4e19-aff5-22d48056bfda)

**Comment by FCRodriguez7** [comment]
Released management v2.36.1

**Comment by mikeapp** [comment]
Looks good on test.
