### ISSUE TITLE
IIIF Manifests - can we add Management version and timestamp of creation?

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#925]
* Today, when trying to see whether https://github.com/yalelibrary/YUL-DC/issues/895 was ready for acceptance, I ran into difficulty determining which version of Management had generated a given IIIF Manifest 
* Would it be possible to add the Management version and a timestamp to the IIIF manifests when we generate them?
  * If so, what would the appropriate IIIF field / area be to put that?

**Comment by mikeapp** [comment]
I really don't think this belongs in `metadata`, so we'd need to create new fields to do this in the Manifest itself. 

What about writing the management version to the S3 metadata?  We could then include it in a HTTP header in the response.  We should probably set the response's last modified date based on S3 if we don't already so a client can understand when the file last changed.

**Comment by mark-dce** [comment]
Is the problem we're trying to solve "I want to know what version of the software created the manifest" or is it just "I want to know this manifest was generated using the currently deployed release"?

It feels like just adding a "Regenerate Manifest" option to the parent object page in the management app might be a simpler / faster / cheaper solution.  Do we want to know when a manifest was generated, or do we just want to know that it was generated by the most recent codebase?

**Comment by mikeapp** [comment]
Closing, I think we can use the timestamp in S3 for last modified date.
