### ISSUE TITLE
VPN Users should not see restricted icon for Yale Community objects

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#927]
**ISSUE**
When I'm logged in via VPN, I should be treated as if I'm connected to the Yale network.

**ACCEPTANCE**
- [ ] When I connect via VPN, I should see thumbnails and be able to view Yale Community Only objects without needing to login

**THINGS TO CHECK** 
- [ ] IP List
- [ ] Way we check IP list
- [ ] Remote IP is wrong
- [ ] Blacklight helper [url](https://github.com/yalelibrary/yul-dc-blacklight/blob/214510dc06af44229a87a2fcf0264312db4fc054/app/helpers/blacklight_helper.rb)

**CURRENT**
Search for parent OID [2053490](https://collections-uat.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&search_field=advanced&all_fields_advanced=&creator_tesim=&title_tesim=&identifierShelfMark_tesim=&date_fields=&subject_fields=&genre_fields=&oid_ssi=2053490&child_oids_ssim=&commit=SEARCH)
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/f0740ec7-26ac-491d-9775-01a3a134d250)

**DESIRED**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/cc395872-75e7-4c50-9205-c732308fc9de)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/447

**Comment by maxkadel** [comment]
Notes:
- Way we check IP list: 
  - right now we're using the `.remote_ip` method, which is explicitly looking for untrusted IPs https://apidock.com/rails/v5.2.3/ActionDispatch/RemoteIp, and *excludes* any IP in a couple private ranges, including the private range Yale uses for its VPN. 
  - So, if my IP chain is [A, B, C] and B & C are on the "trusted" list, this method will return A, but for "on campus" we're testing for B.
