### ISSUE TITLE
Show Errors when Bringing in Item through Parent Objects Screen

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#929]
When I bring in an item using the New Parent Object Button, the batch process information doesn't show me any errors (just says pending for all), so we don't see why things fail like we do when we bring things in with CSV.

- [x] I want to be able to see the errors when I use that method of import

Test item: 15238222 will fail on local, so if you see the errors in both methods, that is a good confirmation. Can try a fake OID for the test/uat environments as well.
_When testing a fake oid, be sure that it's an oid that does not already exist in the system you are testing._

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-management/pull/459

**Comment by martinlovell** [comment]
Be sure to use OID that doesn't exist when testing.  See: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/976

**Comment by martinlovell** [comment]
This is sort of blocked by https://github.com/yalelibrary/YUL-DC/issues/976

**Comment by mark-dce** [comment]
I'm still seeing the old behavior on UAT - unless 1001 is a valid OID???

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/24bd0307-46ab-4c43-993e-5eb30c881342)

OR... maybe the metadata job is just stuck behind 50K indexing jobs...
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/93c49e3e-027d-4024-a55d-1cda6ea17c07)
