### ISSUE TITLE
Fix Subject Geographic on show page

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#930]
Subject geographic was pulling from the wrong field on the show page, we need to make it subjectGeographic_tesim instead of geoSubject_ssim

Test case: 2006858

**Comment by dl-maura** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/444

**Comment by dl-maura** [comment]
Tested my branch on test:

OLD:
![Screen Shot 2020-12-15 at 11.09.23 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/2406a215-c734-4c09-ab8a-20f4db0c587d)

New:

![Screen Shot 2020-12-15 at 11.08.45 AM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6d73669b-41a4-4af0-ad95-134289d2b19e)

**Comment by mikeapp** [comment]
Did you check multiple values - i.e., can you close #745?

**Comment by martinlovell** [comment]
It looks like multiple values is tested here: https://github.com/yalelibrary/yul-dc-blacklight/pull/444/files#diff-98c5dc30095691fdbfb8641ba617e2d3870c6e94e630c69592d2f9692ed095bf

**Comment by dl-maura** [comment]
On UAT:

![Screen Shot 2020-12-16 at 12.21.36 PM.png](https://images.zenhubusercontent.com/5e6273e6ee0145d627e11c85/6e2f2a69-fb39-4174-bc79-9cc13a9ce380)
