### ISSUE TITLE
Indexing null values to Solr

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#932]
When the Management application indexes to Solr, if a field is not represented in the data from the MetadataCloud, it is set as "null" in Solr. 

I would expect:
- [x] If a key is not present the MetadataCloud data, it would not be mapped to the Solr data at all
- [ ] If a key is set to null in the MetadataCloud data, that would be passed through in the key value pair to Solr 

For example: 
https://collections-test.library.yale.edu/management/parent_objects/999957 

```
{
  "id": "999957",
  "abstract_tesim": null,
  "accessionNumber_ssi": null,
  "accessRestrictions_tesim": null,
  "alternativeTitle_tesim": null,
  "alternativeTitleDisplay_tesim": null,
  "archiveSpaceUri_ssi": null,
  "callNumber_ssim": "1979 Folio 88",
  "callNumber_tesim": "1979 Folio 88",
  "caption_tesim": [

  ],
```

**Comment by martinlovell** [comment]
Because SOLR interprets keys with null values the same as not having a key, and because Metadata Cloud shouldn't return null values in the JSON, we can safely remove any keys with nil values.  (Checkbox 2 shouldn't be necessary.)

https://github.com/yalelibrary/yul-dc-management/pull/451

**Comment by maxkadel** [comment]
See https://collections-test.library.yale.edu/management/parent_objects/999957 - not recording null values

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/management/parent_objects/999957
