### ISSUE TITLE
Enable S3 Encryption on Staging and Production

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#933]
**ISSUE**
We've tested S3 encryption and haven't seen any negative performance impact.  We'd like continue experimenting with a rollout of S3 encryption by enabling it on non-public facing environments.

**ACCEPTANCE**
Enable S3 encryption on
- [x] Staging
- [x] Production

Testing Steps:
- [x] Ingest some sample items on Staging
- [x] Test IIIF user experience on those sample items and make sure it seems normal

**Comment by dylansalay** [comment]
Ingested sample items (2, 3, 4, 5, 6) on Staging and tested the IIIF User experience on those sample items. Panning/zooming worked with no issues. 

![Screen Shot 2020-12-16 at 11.46.17 AM.png](https://images.zenhubusercontent.com/5eac63602bc3d4b76b1f451c/5b27d5fb-b8a7-47cc-8130-b6da402d9acb)

**Comment by dylansalay** [comment]
Ingested 5 Yale Only items (2054845, 2057527, 2054642, 2055036, 2056394) on Staging and tested the IIIF User experience on those sample items. Panning/zooming worked with no issues.

**Comment by fnibbit** [comment]
Spot-checked the panning/zooming of those items and the encryption of the actual ptiffs we're looking at on the relevant bucket.  I'd call this ready for acceptance.
