### ISSUE TITLE
[CHECK] Add min/max filters to Sort by Year

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#938]
**CHECK WHETHER THIS ISSUE IS STILL VALID**

**ISSUE**
Because Year is a multi-valued field that may include year ranges, we want to ensure that we take the minimum value or maximum value when year_isim includes multiple values.

**EXAMPLES**
* In ascending sorts use 1937 for the year_isim value [1937, 1938, 1939, 1940]
* In descending sorts use 1940 for the year_isim value [1937, 1938, 1939, 1940]
* In ascending sorts use 1870 for the year_isim value [1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879]
* In ascending sorts use 1879 for the year_isim value [1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879]

**ACCEPTACE**
- [x] When sorting by Year ascending, use the minimum value in the year field
- [x] When sorting by Year descending, use the maximum value in the year field

**IMPLEMENTATION NOTES**
Potential breadcrumb: https://lucidworks.com/post/minmax-on-multivalued-field/

**Comment by martinlovell** [comment]
Solr seems to take care of this for us:

(PR just adds test to confirm)
https://github.com/yalelibrary/yul-dc-blacklight/pull/600
