### ISSUE TITLE
Facet and Metadata for Visibility

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#939]
I want to be able to easily tell if a thing is Public or Yale Community Only.

- [x] I see the visibility in the show page metadata
- [x] I can filter/facet on visibility (YCO or Public)

**Comment by dl-maura** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/451

**Comment by FCRodriguez7** [comment]
**The result from the test environment:** 

![Screen Shot 2020-12-17 at 12.49.18 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/28e5067a-3707-4b32-b705-64a3ca83f393)
