### ISSUE TITLE
📦 Baseline manifest service on ECS

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#94]
ACCEPTANCE
- [x] Fill out system configuration on the ECS section of the reporting document
- [x] Complete the indicated testing baselines using JMeter or equivalent tools and fill in testing results
- [x] Be able to rerun the same tests against future versions of the system 

https://docs.google.com/document/d/1CPOPLSuMXjX-9_K8kJbRfly4WIrVAzMUEiNu5WcQgKY/edit

**Comment by FCRodriguez7** [comment]
I will need the url.

**Comment by dl-maura** [comment]
Frederick was working on this in SpinUp, so he may have some headway on doing this work.

**Comment by FCRodriguez7** [comment]
I have attached the reports for ECS.  The attachments include 500 serial users, and 1000 (500each) concurrent users.

[https://app.zenhub.com/files/242185115/57d37825-95b6-454f-b471-2d3a165d7d88/download](https://app.zenhub.com/files/242185115/57d37825-95b6-454f-b471-2d3a165d7d88/download)

[https://app.zenhub.com/files/242185115/cbc4a0f0-93e8-4279-9cca-d258736505ae/download](https://app.zenhub.com/files/242185115/cbc4a0f0-93e8-4279-9cca-d258736505ae/download)

**Comment by fnibbit** [comment]
Looking through the reports, not sure how to pull out the answers to the questions in the reporting doc linked up top.

**Comment by dl-maura** [comment]
Not sure the reports contain the configuration information of what server they were tested against and the document at the top of the ticket asks for specifics on benchmarks and not sure the levels that were hit in the corresponding testing. Useful information in there, but not answering the exact questions.

**Comment by dl-maura** [comment]
Links to the Beinecke Google Analytics reports:

https://app.zenhub.com/files/242185115/162474f2-8138-4081-8d3d-6787c56cd505/download

https://app.zenhub.com/files/242185115/ef518483-42c1-46b2-871b-1bd960eaf6bf/download

**Comment by dl-maura** [comment]
Did a teach out for Loadster, seems insufficient, Rachel will look more at Jmeter and do a teach out

**Comment by dl-maura** [comment]
JMeter test plan nearly done which will allow for tests in ticket to be run (sharable script). Results off of running locally today and will coordinated with people before hitting ECS-Test

**Comment by dl-maura** [comment]
Test plan run against local service, plan for 9-10 AM eastern as test window against ECS-test tomorrow 5-14

**Comment by dl-maura** [comment]
Rachel ran tests, and will update the ticket with information.
