### ISSUE TITLE
Test Private Access Restrictions on Staging

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#940]
**STORY**
We need an environment that we can access from the public internet to test access controls (otherwise we're alway on-campus by virtue of being connected to the VPN).  So, we need to make an exception to our usual workflow and deploy related code to staging in order to test it.

**ACCEPTANCE**
- [x] Test that an item can be changed from "Public Access" to "Private" on management in staging
- [x] Test that VPN and non-VPN access to staging does not appear, logged in or not
    - [x] In search results 
    - [x] From a direct URL to the show page
    - [x] Thumbnail
    - [x] Universal Viewer
    - [x] Manifest
    - [x] PDF
    - [x] Link to an image directly from the manifest
- [x] Write up tickets for any unexpected behaviors

**Comment by maxkadel** [comment]
On VPN - Private
https://collections-staging.library.yale.edu/catalog/11873651
Before:
![image](https://user-images.githubusercontent.com/45948126/102381538-5bf00400-3f97-11eb-985f-4215fdb3de4c.png)
![image](https://user-images.githubusercontent.com/45948126/102381485-4b3f8e00-3f97-11eb-84e8-076fdcbe3c58.png)

After:
Search:
![image](https://user-images.githubusercontent.com/45948126/102381732-92c61a00-3f97-11eb-951c-7deb6ef47cbc.png)

Directly to it:
![image](https://user-images.githubusercontent.com/45948126/102381801-a96c7100-3f97-11eb-8a62-27f3203c431d.png)

*Can* see manifest
https://collections-staging.library.yale.edu/manifests/11873651

**Comment by martinlovell** [comment]
I think the issue may be that CheckAuthorization.check_authrorization needs to explicitly return false when it finds no know visibility so that the controller stops.  I think it returns nil in that case now.

**Comment by maxkadel** [comment]
Martin made a PR addressing his comment above - https://github.com/yalelibrary/yul-dc-blacklight/pull/450

**Comment by maxkadel** [comment]
After v1.36.7 - on VPN on collections-test 
Can still see show page:
https://collections-test.library.yale.edu/catalog/11873651

**Comment by maxkadel** [comment]
Created spike ticket for determining Management behavior for Private objects - https://github.com/yalelibrary/YUL-DC/issues/943
