### ISSUE TITLE
SPIKE: Figure out what's causing bad image queries at a constant rate of 2 per minute

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#942]
**ISSUE**
Starting around November 9th, we're seeing a process that is consistently requesting non-existent Tiffs about twice a minute.  This creates a lot of noise that obscures true errors.  In addition, if our exception system is metered (like Honeybadger), it eats up licensing capacity.

**ACCEPTANCE**
Note, this is a spike, so time box this investigation appropriately
-  [x] Identify what's triggering the recurring baseline traffic
 - [ ] Disable it if possible

**DETAILS**
https://app.honeybadger.io/projects/73072/faults/65537884

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/7dfa08a8-f6d5-4838-97a8-0e10661aa4fc)

**Comment by mlooney** [comment]
This smells like a health check looking for a specific image. check target groups

**Comment by mlooney** [comment]
or maybe even nagios?

**Comment by mlooney** [comment]
verified to not be a target group health check. also verified to not be configured in opsview...

**Comment by mlooney** [comment]
it's caused by a canary from devops requesting /catalog/10000003, which includes a thumbnail image w/ that oid. it's been changed to 10513835, which might resolve it

**Comment by mlooney** [comment]
curious why this doesn't have a proper stack trace. we shouldn't be logging exceptions for 404s...
