### ISSUE TITLE
SPIKE: What should the Management behavior be for actually-private objects?

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#943]
What processing steps should Management do for:

1. New objects that come in that are actually private (aka, don't start private and get set to public once we get the MetadataCloud data, which is the current pattern with legacy Ladybird objects.
  - [x] Fetch metadata
  - [ ] Generate PTIFFs
  - [ ] Generate iiif manifest
  - [ ] Index to Solr -- we do not want to index Private items to SOLR, only YCO or Public
  - [ ] Generate PDF -- not sure we can do this step until we do Solr based on code?
2. Objects that have been previously processed and "published" as Public or Yale Community Only and are subsequently changed to Private
  - [ ] PTIFFs (delete / leave)
  - [ ] IIIF Manifest (delete / leave)
  - [ ] Could Cantaloupe cache on S3 be an issue?
  - [ ] Solr index (re-index with "Private" info / delete from solr index) -- delete from solr index
  - [ ] PDF (delete / leave)

NOTE: Current behavior: Re-indexes to Solr with "Private" in `visibility_ssi` field

**Comment by dl-maura** [comment]
For PDF/IIIF Manifest, if something is private but I know the ID (maybe got set to private) will I be able to get to that page and see it? If so, we'd need to purge. If not, I don't have strong feelings on if we delete, defer to RH. For things starting as private (coming in as private and not being switched), no solr record until it is YCO or Public, not sure if this means no pdf and also no IIIF manifest for the access issue and also processing steps issue.

**Comment by mikeapp** [comment]
Cantaloupe cache is an issue.  Also, see #963 - images are being delivered with very high cache lifetimes.

**Comment by dl-maura** [comment]
Notes from parking lot:

- no solr indexing if it came in as private and delete solr index when switched to private

- just fetch metadata, create parent & child objects for new items in, don't do any of the other stuff until they are switched to one of the other permissions

- when something gets switched to private, leave previously created artifacts, EXCEPT SOLR RECORD which must be deleted
