### ISSUE TITLE
In Blacklight, do not show metadata for Private works 

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#944]
As of Blacklight v1.36.7, if you search for a Private work via the UI, it will not appear in the search results; however, if you have the direct URL, you can see the metadata on the show page. 

## Acceptance Criteria
- [x] Going directly to the "Show" page of a private object results in a 401 unauthorized page

## Testing notes
e.g. https://collections-staging.library.yale.edu/catalog/11873651 was made Private for testing purposes (is actually a public work)

Searching for OID gives no results (correct behavior)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/4d241aa1-2ff9-441c-aedf-5b2d3ae135e5)

Going directly to URL shows metadata (incorrect behavior)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/83485759-d152-493c-a114-ae493bcc218d)

**Comment by martinlovell** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/457

**Comment by maxkadel** [comment]
https://collections-test.library.yale.edu/catalog/11873651

Restricts for both logged out and logged in users
![image](https://user-images.githubusercontent.com/45948126/102921969-48dba900-445b-11eb-81f9-7a9f8aeee894.png)

**Comment by maxkadel** [comment]
https://collections-uat.library.yale.edu/catalog/11873651
![image](https://user-images.githubusercontent.com/45948126/102926111-79731100-4462-11eb-8458-7a1ca9f8a164.png)
