### ISSUE TITLE
Check all permissions on Prod before YCO Ingest

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#945]
I want to confirm it all came in as public and resolve any LB mismatches

- [x] Finish Public Ingest (re-try broken items)
- [x] Confirm everything has a permission of public

**Comment by mlooney** [comment]
the broken items have been re-uploaded and are currently in-process. looking good so far.

**Comment by dl-maura** [comment]
Everything looks good, could someone just run a db report of all the parent objects in prod? want a final list before YCO goes in
