### ISSUE TITLE
🌀 Set up paths for services on SpinUp

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#95]
**STORY**
Build out the service paths for the the `test` environment on SpinUp

**ACCEPTANCE**
I can reach
- [ ] The blacklight application at https://dl-test.library.yale.edu/
- [ ] The manifest service at https://iiif-test.library.yale.edu/manifests
- [ ] The image service at https://iiif-test.library.yale.edu/images

For additional context and details see https://docs.google.com/presentation/d/1p58-Prs_ZQAqAj73uYvt8YIRhl02edc-ivNUkj8RtY4/edit#slide=id.g722593bcb2_1_0

**Comment by mikeapp** [comment]
The services are on this ECS in Spinup:
https://spinup.internal.yale.edu/r/spinup-0010eb-cantaloupeIIIF

*Ports*
Cantaloupe: 8182
Manifest: 80
Blacklight: 3000

I've also mapped the Cantaluope and manifest services (`/manifests/*` URLs)  servers through Nginx on spinup-0010ef.spinup.yale.edu, using a self-signed cert.  This instance can be discarded when we have the F5 up and running.

**Comment by ra359** [comment]
instead of:

https://dl-test.library.yale.edu/ -> http://container:3000
https://iiif-test.library.yale.edu/manifests -> http://container:80
https://iiif-test.library.yale.edu/images -> http://container:8182

is it possible we could do:

https://dl-test.library.yale.edu/ -> http://container:3000
https://iiif-manifests-test.library.yale.edu/ -> http://container:80
https://iiif-images-test.library.yale.edu/ -> http://container:8182

This has some advantages, namely simplifies load balancer config, also allows us to move/scale these services around w/ less effort (i.e. separate containers) if ever needed.

**Comment by ra359** [comment]
Submitted INC1747621 for F5 VIP https://dl-test.library.yale.edu -> spinup-0010eb-cantaloupeIIIF.svc.spinup.yale.edu:80 . (Ports 3000 and 8182 to follow)

**Comment by ra359** [comment]
Ended up working with ITS  and went the "cloud native" route. Waiting INC1747859 to re-point DNS to the Amazon IP.

**Comment by ra359** [comment]
DNS entries pointing to AWS load balancer are in effect now:

$ host dl-test.library.yale.edu            
dl-test.library.yale.edu is an alias for internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com.
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.36.237
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.32.126

$ host iiif-manifests-test.library.yale.edu
iiif-manifests-test.library.yale.edu is an alias for internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com.
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.32.126
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.36.237

$ host iiif-images-test.library.yale.edu
iiif-images-test.library.yale.edu is an alias for internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com.
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.32.126
internal-library-it-internal-1983206671.us-east-1.elb.amazonaws.com has address 10.5.36.237

We are getting what looks like a Rails error on https://dl-test.library.yale.edu/

**Comment by dl-maura** [comment]
This is on SpinUp, not ECS, so need a separate ticket for this problem for ECS (McClain seems to know how to fix this?).
