### ISSUE TITLE
Update text on icon for restricted items (Please log in to CAS - instead of VPN)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#956]
**ACCEPTANCE**
- [x] The text on the icon users see when they attempt to access Yale community only items asks them to login using their NetID

**DETAILS**
The image is here https://github.com/yalelibrary/yul-dc-blacklight/blob/master/app/assets/images/placeholder_restricted.png

Update the text "Offsite? Access via Yale VPN" to say "Offsite? Please login with your NetID"

**Comment by FCRodriguez7** [comment]
I have recreated the image with the changed wording.

![AccessRestricted.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/cf681d5d-a47c-4168-8da2-04dfd2b98428)

**Comment by FCRodriguez7** [comment]
https://github.com/yalelibrary/yul-dc-blacklight/pull/481
