### ISSUE TITLE
Show bucket names in management application

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#958]
**STORY** 
As a support engineer, I would like be able to view S3 bucket configurations directly in the management application, in order to simplify diagnostics for issues with PTIFFs, PDFs, and other content stored on S3.

**ACCEPTANCE**
- [x] The management application has a "Storage" section on the Management Dashboard page
 
- [x] The management application has a "Base URLs" section on the Management Dashboard page that lists:
  - [x] "IIIF images"  -  IIIF_IMAGE_BASE_URL
  - [x] "IIIF manifests" - IIIF_MANIFESTS_BASE_URL
  - [x] "MetaData Cloud" - METADATA_CLOUD_HOST
  - [x] "PDFs" - PDF_BASE_URL

- [x] The "Storage" status page displays *read-only* values for each of the buckets used on S3:
  - [x] "S3 Source" - S3_SOURCE_BUCKET_NAME
  - [x] "S3 Samples" - SAMPLE_BUCKET

**Comment by FCRodriguez7** [comment]
What are we calling the "navigation pane"?

![Screen Shot 2021-02-10 at 3.09.21 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/66d56857-78d5-416d-8838-9624bf7eb4bb)

![Screen Shot 2021-02-10 at 3.09.55 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2dba37b7-d4ce-4f3d-9dcd-2d7448e81818)

**Comment by FCRodriguez7** [comment]
Displaying this list: 
        VPN
        SAMPLE_BUCKET
        S3_SOURCE_BUCKET_NAME
        METADATA_CLOUD_HOST
        BLACKLIGHT_PASSWORD_PROTECT
        BLACKLIGHT_BASE_URL
        GOOBI_MOUNT
        IIIF_IMAGE_BASE_URL
        IIIF_MANIFESTS_BASE_URL
        PDF_BASE_URL


The list is from yul-dc-camerata/lib/camerata/

**Comment by FCRodriguez7** [comment]
Storage Feature could go in the navigation pane: 

![Screen Shot 2021-02-11 at 9.36.25 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ca4efbb6-f1be-4afb-bbff-ee8b27b62777)

**Comment by FCRodriguez7** [comment]
I have added the storage information under the Dashboard tab: 

![Screen Shot 2021-02-11 at 12.04.05 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/5fd3c099-fe0f-4788-bff0-ba8869b20029)


![Screen Shot 2021-02-11 at 12.16.41 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/a4ff7559-08e1-4202-9938-62dbee9c194e)

**Comment by FCRodriguez7** [comment]
Feedback

![Screen Shot 2021-02-11 at 1.27.57 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/f7efec16-10f7-4107-a53c-28be93d6415d)

**Comment by FCRodriguez7** [comment]
**Code Modification after Feedback** 


![Screen Shot 2021-02-11 at 3.52.25 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/2c3e1031-a790-4f08-ac06-afcc445063d8)

**Comment by FCRodriguez7** [comment]
**Code on the Test Environment**

![Screen Shot 2021-02-11 at 5.06.43 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d44b743a-7152-437d-a8c0-6727bc15ef1e)
