### ISSUE TITLE
Provide Yale-themed 404 page for bad kids

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#959]
**STORY**
As a repository owner, I would like a Yale-themed 404 page when users try to view an invalid OID, so that it's clearer that the OID they've provided is wrong instead of looking like the application had some kind of error (because the page looks so different)

**ACCEPTANCE**
When I submit a reference to an invalid OID - e.g. https://collections.library.yale.edu/catalog/floof
- [x] I get a 404 response
- [x] The page has the same header & footer as all other pages on the DL site
- [x] The error text is displayed in YaleDisplay-Roman
- [x] The main error is tagged as heading text

**CURRENT**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/cb450ffd-c5e5-42f5-97d5-50eb4bfd588b)

**DESIRED**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/fb2af608-6f14-4796-9071-675a39e9d7a1)

**Comment by alishaevn** [comment]
# PR
https://github.com/yalelibrary/yul-dc-blacklight/pull/510

# Summary
- the `/404` page shows yale branding with the same text as before
- the `/catalog/<invalid-OID>` page shows yale branding with the requested text

# Demo
| 404 | invalid OID |
| --- | --- |
| ![Screen Shot 2021-04-13 at 1 36 07 PM](https://user-images.githubusercontent.com/29032869/114617674-4b0d8180-9c5d-11eb-91b9-fd7ec61eee81.png) | ![Screen Shot 2021-04-13 at 1 34 55 PM](https://user-images.githubusercontent.com/29032869/114617583-2addc280-9c5d-11eb-95f9-3ec940535d99.png) |

**Comment by alishaevn** [comment]
Dylan pushed and checked this on test.

**Comment by mikeapp** [comment]
URLs not under /catalog return 404 but a blank page, for example: https://collections-uat.library.yale.edu/floof
