### ISSUE TITLE
Configure endpoints for services on on Yale Cluster

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#96]
**STORY**
Build out the service paths for the the `test` environment on Yale's ECS cluster

**ACCEPTANCE**
I can reach
- [x] The blacklight application at https://collections-test.library.yale.edu/catalog
- [ ] The manifest service at https://iiif-test.library.yale.edu/manifests
- [ ] The image service at https://iiif-test.library.yale.edu/images

For additional context and details see https://docs.google.com/presentation/d/1p58-Prs_ZQAqAj73uYvt8YIRhl02edc-ivNUkj8RtY4/edit#slide=id.g722593bcb2_1_0

**Comment by ra359** [comment]
Can these be deleted? (F5 -> SpinUP)

https://dl-test.library.yale.edu/
https://iiif-manifests-test.library.yale.edu/
https://iiif-images-test.library.yale.edu/

Do we no longer need these DNS records?

**Comment by mark-dce** [comment]
Yes - that's what #125 Clean up public endpoints to SpinUp cluster was about.

**Comment by ra359** [comment]
This hostname is already taken:

$ host images-test.library.yale.edu
images-test.library.yale.edu is an alias for libsvcs-1.its.yale.internal.
libsvcs-1.its.yale.internal has address 172.18.56.135

**Comment by ra359** [comment]
Request DNS entry for collections-test.library.yale.edu and generated Certificate Signing Request for GlobalSign.

**Comment by mark-dce** [comment]
@mikeapp @rebeccahirsch & @dl-maura discussed and suggest we go with

 The manifest service at https://iiif-test.library.yale.edu/manifests
 The image service at https://iiif-test.library.yale.edu/images

I've updated the main description to reflect this too.

**Comment by ra359** [comment]
INC1766801 to modify A-records iiif-test.library.yale.edu to use 3.208.130.194 and 3.93.208.59 .
