### ISSUE TITLE
[CHECK] METS Pre-Ingest Validation

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#961]
**CHECK WHETHER ALREADY DONE**

**STORY**
When I submit a METS file for import, I want to know whether it's valid as soon as possible, so that the system doesn't ingest incomplete parents and/or generate errors that could have been fixed before import.

**ACCEPTANCE**
When I submit a METS file for ingest, scan it for potential errors and terminate the import if there are errors:
- [ ] The file must be valid XML
- [ ] The file must have at least one parent object described in it
- [ ] The file must have an parent OID
- [ ] The file must have an OID for each child image

If the METS file has any of the errors above
- [ ] Write an error file to disk
- [ ] Show the first 20 lines of the error file in the batch job status / error information

**Comment by martinlovell** [comment]
We don't write error logs to disk.  This would be helpful because one could identify items that were queued for ingest (done file written) but not successful (error file written) by just looking at the disk.
