### ISSUE TITLE
Remove help text from catalog root page

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#964]
**STORY**
As a researcher, I want to see browsable content as soon as possible, so that I don't have to click through text-heavy screens that I'm unlikely to read...

**ACCEPTANCE**
When any user visits the '/catalog' endpoint
- [x] They should see a relatively blank page with populated facets.
- [x] The page should have text "Please enter a search term in the search box above or use the facets at left to begin searching."

**Comment by mikeapp** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/460
