### ISSUE TITLE
Automate import of new items in Goobi hot-folder

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#966]
**STORY**
As a digital studio team member, I'd like to simplify the DL import process by having new packages from Goobi automatically detected and imported into the DL, so that I don't have log in to two apps and do a two-step export from Goobi, import to DL Management process.

**ACCEPTANCE**
When I complete and export a package from Goobi
- [ ] do directory scan and when something is found...
- [ ] The DL management app launches a METS import job for the corresponding package
- [ ] When finished importing, write a dcs-[env].done file back to the goobi directory (env = collections-test, collections-uat etc)

Will be a periodic directory scan, not notification-based

**ADDITIONAL DESIGN DISCUSSION**
https://docs.google.com/document/d/1SbzqQfAUDoRn26VmR-II6fsNgNiTn6KuAvYRE5wzBBQ/edit

**Comment by dl-maura** [comment]
Possible writing in progress file

**Comment by martinlovell** [comment]
Have a PR with a URL to trigger the scan.  I think that's a good step before automating it:
https://github.com/yalelibrary/yul-dc-management/pull/514

**Comment by martinlovell** [comment]
Ran on test.  Results can be seen in batch jobs list.   Jobs with the user System, were triggered by the scan.

**Comment by martinlovell** [comment]
Updated done/progress file name prefix to be:

dcs-<indicator>

indicator uses:
- ENV[METS_SCAN_LOCK_NAME]
- subdomain of ENV[BLACKLIGHT_BASE_URL]
- fallback to NO_ENV_NAME

This will cause done filename to include collections-uat, collections-test, collections-staging, collections, etc. until we explicitly set METS_SCAN_LOCK_NAME.
