### ISSUE TITLE
Confirm Goobi hot-folders are mounted in all environments

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#967]
**ACCEPTANCE**
Confirm the corresponding Goobi hotfolder from Storage@Yale is mounted to the corresponding management workers

- [ ] Confirm latest management

- Goobi Test
- [x] infra
- [x] test
/

- Goobi UAT
- [x] uat
  /

- Goobi Production
- [x] staging
- [x] production

**Comment by ra359** [comment]
We are working on mounting:

wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU to /brbl-dsu on the TEST mgmnt containers
wcsfs00.its.yale.internal:/NFS_SFS_std_mult_000/Goobi_Deposits_UAT-CC1741-BRBLDSU to /brbl-dsu on the UAT mgmnt containers
wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_004/Goobi_Deposits_PROD-CC1741-BRBLDSU to /brbl-dsu on the PROD mgmnt containers

**Comment by dl-maura** [comment]
This will also need the r/w confirmation

**Comment by dl-maura** [comment]
Test is set.

UAT has nothing mounted, needs the dcs and jss_export subfolders mounted

Prod needs the dcs and jss_export folder mounted, did has jss_import which we tested and was writable, so settings seem right on the tomcat end

**Comment by ra359** [comment]
Added the following to create-continst.sh but have not tested yet:

  # Mount Goobi Host Folders
  if [ $CLUSTER_NAME = "yul-dc-test" ]
  then
    GOOBI_HOT="wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU"
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 $GOOBI_HOT /brbl-dsu
  elif [ $CLUSTER_NAME = "yul-dc-infra" ]
    GOOBI_HOT="wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_003/Goobi_Deposits-CC1741-BRBLDSU"
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_export /brbl-dsu/jss_export
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_import /brbl-dsu/jss_import
  elif [ $CLUSTER_NAME = "yul-dc-uat" || $CLUSTER_NAME = "yul-dc-demo" ]
    GOOBI_HOT="wcsfs00.its.yale.internal:/NFS_SFS_std_mult_000/Goobi_Deposits_UAT-CC1741-BRBLDSU"
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_export /brbl-dsu/jss_export
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_import /brbl-dsu/jss_import
  elif [ $CLUSTER_NAME = "yul-dc-staging" || $CLUSTER_NAME = "yul-dc-prod" ]
    GOOBI_HOT="wcsfs00.its.yale.internal:/NFS_SFS_std_sngl_004/Goobi_Deposits_PROD-CC1741-BRBLDSU"
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_export /brbl-dsu/jss_export
    mount -t nfs -orw,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3 ${GOOBI_HOT}/jss_import /brbl-dsu/jss_import
  fi

**Comment by ra359** [comment]
Deployed to UAT/INFRA/TEST

**Comment by ra359** [comment]
STAGING completed

**Comment by ra359** [comment]
PROD completed

**Comment by ra359** [comment]
PR  #302 submitted for `bin/create-continst.sh`
