### ISSUE TITLE
Deploy latest Solr release to all enviornments

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#969]
**ACCEPTANCE**
- [x] Release the newest version of Solr
- Deploy to
- [x] Infra
- [x] Test
- [x] UAT
- [x] Demo
- [x] Staging
- Status check
- [x] E-mail production outage notification
- [x] Production

**Comment by bobrice** [comment]
@here Solr has been updated to v1.0.5 on all environments, except production.

**Comment by bobrice** [comment]
All set.  Solr is at v1.0.5 on prod.
