### ISSUE TITLE
Ensure all samples are discoverable

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#97]
**ACCEPTANCE**
- [x] I get 45 results when searching blacklight in any of our testing environments

See spreadsheet attached (below). Talk to Maura if you don't understand indexing requirements.  

**Note 1:** There are 45 OIDs across 39 works because some OIDs are individual pieces of a work (ie, volumes of one work).  

**Note 2:** Please see the "Compare to Spec" sheet and the "Fixture" vs. "Blacklight ID in Test" columns for an analysis of differences between our fixtures and the sample target items. https://docs.google.com/spreadsheets/d/1al09lS7KR2rDCgB2S88l1fy-XW3oJCr2_IgTppScmVw/edit#gid=52505720

See #69 for additional context

**Comment by mikeapp** [comment]
Uploaded normalize/metadata-cloud JSON to DCE yale-image-samples bucket, /archivesspace/metadata-cloud-json/*.json

**Comment by dl-maura** [comment]
https://docs.google.com/spreadsheets/d/1B4U2lWIEubL__j2_-fEUxji2cT0VBeWWK01tx7lGl8I/edit?usp=sharing

**Comment by FCRodriguez7** [comment]
I have reached out to Maura about a brief discussion per the group meeting recommendation yesterday.  Eric and I anticipate a meeting time for Thursday.

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-05-06 at 3.23.03 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/bb23f928-ea57-413e-93ab-314f5b41ce8b)


CHANGES: 

![Screen Shot 2020-05-06 at 3.45.08 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c3395272-a573-46cb-9e73-0976555d4111)

VIEW FIX: 

![Screen Shot 2020-05-06 at 3.45.08 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/d3a4fe22-c752-47e2-98f1-f9a925d8f996)

Commit: 
https://github.com/yalelibrary/yul-dc-blacklight/tree/97_EnsureAllSamplesDiscoverable

**Comment by edejesusyale** [comment]
We changed the solr id from bib_id to oid. This is done because multiple oids with the same bib_id would overwrite the same solr record instead of creating a new one.

**Comment by FCRodriguez7** [comment]
![Screen Shot 2020-05-12 at 1.02.16 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/542cbe7a-dfdf-4bef-b43b-482511ed94ec)
