### ISSUE TITLE
Inconsistent behavior when removing filter

### ISSUE THREAD

**Issue by mlooney** [yalelibrary/YUL-DC#971]
Removing a call number filter from a search result page redirects back to /catalog, should go to /catalog?search_field=all_fields

to reproduce:

* go to a work
* click on the call number link
* on the resulting page, click the dismissal control on the "YOU SEARCHED FOR" section:
![image.png](https://images.zenhubusercontent.com/5e5d3aa83ca793986edab47d/027f76aa-5a68-4404-9e03-1d764f3ebff5)

observe redirection to /catalog

This may, or may not be desired, but is different behavior than removing the filter from a top-level search

**Comment by mikeapp** [comment]
Works correctly now.
