### ISSUE TITLE
Ingest Parent Objects from Latest Goobi Package

### ISSUE THREAD

**Issue by orangewolf** [yalelibrary/YUL-DC#972]
## Acceptance ##
- [ ] The system ingests the corresponding parent and it's child images
  - [x] Process a METS file with the latest formatting
  - [x] Refactor code to allow parent objects to be created even if they do not have a corresponding Ladybird record.
  - [x] Refactor code to allow child objects to be created even if they do not have a corresponding Ladybird record.
  - [x] Modify PTIFF generation to pull source files from goobi package OR access master mount depending on if they are mets or not (do not copy files twice please)

Questions:
- Do we want to copy access masters from package in to access master mount? (con is copying file extra time, pro is being able to recreate ptiffs in future)
- When can we get some actual goobi packages?

**Comment by maxkadel** [comment]
Per @mikeapp - "Do we want to copy access masters from package in to access master mount? (con is copying file extra time, pro is being able to recreate ptiffs in future)" - yes, do copy from package to access master mount

**Comment by dl-maura** [comment]
When can we get some actual goobi packages? I've given one, but happy to give more when needed!
