### ISSUE TITLE
Change number of workers for PDF queue in each environment to 1

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#974]
Set pdf workers to 1 (intensive worker count)
- [x] Infra
- [x] Test
- [x] UAT
- [x] Demo
- [x] Staging
- [x] Production

**Comment by fnibbit** [comment]
confirmed that the jenkins config contains
'export INTENSIVE_WORKER_COUNT=1' and '    WORKER_COUNT=$INTENSIVE_WORKER_COUNT cam deploy-intensive-worker $CLUSTER_NAME' for infra, test, uat, demo, staging.  

On the aws console, in the intensive worker task definitions, WORKER_COUNT is blank on infra, 1 on test, 1 on UAT, 10 on demo, 1 on staging, 1 on prod.

**Comment by kbcarter** [comment]
![image.png](https://images.zenhubusercontent.com/5e6002742347da559ce428f3/f46f63a2-8686-4388-a427-0bc03f8e02fe)

Updated Jenkins job if statement so updated to SSM will only happen when the **Update SSM** checkbox is checked.
**if [ ! "$UPDATE_SSM" = "true" ]** to **if [ "$UPDATE_SSM" = "true" ]**

Redeployed management v2.27.1 to demo
