### ISSUE TITLE
Make all subjects clickable

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#975]
**STORY**
In issue #724, we made "Subject (Topics)" link to a search for all items with the same Subject Topic.  For consistency, we'd like this behavior for all subject types including "Subject (Name)" and "Subject (Geographic)".

**ACCEPTANCE**
When an item has one or more subject names
- [x] I can click on the subject name to get a list of all other parent objects with the same subject name - e.g. OID:  **2054600**; Subject (Name): **Milosz, Czeslaw** -  https://collections-test.library.yale.edu/catalog/2054600

When an item has one or more geographic subjects
- [x] I can click on the geographic subject to get a list of all other parent objects with the same subject - e.g. OID **2041336**; Subject (Geographic): **Mississippi River** - https://collections-test.library.yale.edu/catalog/2041336

**Comment by FCRodriguez7** [comment]
There is no data for subject (geographic) in any of the environments. I attached examples of the subject (name).  

**Before**
![Screen Shot 2021-01-11 at 9.14.29 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/09f7ee8e-26ca-403d-89c0-3bbc90a150e8)

**After**
![Screen Shot 2021-01-11 at 9.13.27 AM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/3f5a5c21-de9c-4879-ab6c-251cdefa9bfb)

**Comment by FCRodriguez7** [comment]
I need more objects to test this feature.  @dl-maura will provide the objects to test feature.  Additionally,  I want the Solr subjectGeographic_ssim added. 

Frederick

**Comment by dl-maura** [comment]
Geographic:
https://collections-uat.library.yale.edu/catalog/15238222
https://collections-uat.library.yale.edu/catalog/15952230
https://collections-uat.library.yale.edu/catalog/15821713

Name:
https://collections-uat.library.yale.edu/catalog/16584342
https://collections-uat.library.yale.edu/catalog/15821713
https://collections-uat.library.yale.edu/catalog/10590049

**Comment by FCRodriguez7** [comment]
The example for subject (geographic).

**Before**
![Screen Shot 2021-01-12 at 4.33.40 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/fcf9422d-374f-4559-ae54-f6a20fcf0365)

-------

**After**
![Screen Shot 2021-01-12 at 4.28.30 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/c8578eb0-72ca-46b1-a08e-77245b7296e9)  

![Screen Shot 2021-01-12 at 4.28.51 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/ece49096-781a-48ac-b94e-08fa9c1a005c)

**Comment by FCRodriguez7** [comment]
management application solr prerequisite work: https://github.com/yalelibrary/yul-dc-management/pull/463

**Comment by FCRodriguez7** [comment]
A test search:
https://collections-test.library.yale.edu/catalog?f%5BsubjectGeographic_ssim%5D%5B%5D=Colorado

**Comment by FCRodriguez7** [comment]
A search on the UAT environment: 

https://collections-uat.library.yale.edu/catalog?f%5BsubjectGeographic_ssim%5D%5B%5D=Colorado
