### ISSUE TITLE
Extent of Digitization for Parent Object

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#979]
Like the rights statement, we want to store the extent of digitization that comes in from LadyBird (or Goobi) and also be able to edit it.

- [x] Bring in extent of Digitization and save value to DB (LB and Goobi both have this)
- [x] Be Able to edit this field - it will be a drop-down, 2 options: Completely digitized, Partially digitized
- [x] Make sure this field displays regardless of system of record (LB, ASpace, Voyager should all show this)

**Comment by maxkadel** [comment]
Example on UAT:
* Management - https://collections-uat.library.yale.edu/management/parent_objects/999951
* Blacklight - https://collections-uat.library.yale.edu/catalog/999951
