### ISSUE TITLE
Access to restricted items for non-Yale team members

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#98]
**STORY**
As a non-Yale team member, I would like to be able to view restricted objects, but can't see them even when I'm on VPN.

**ACCEPTANCE**
- [ ] Non-Yale team members can view restricted items in the DL

**CURRENT BEHAVIOR**
![image](https://user-images.githubusercontent.com/3064318/80512630-66e02080-8943-11ea-8458-038af3b28748.png)

**Comment by mark-dce** [comment]
Here's my connection details:

Client Address (IPv4): 172.25.167.181
Server Address: 130.132.2.16

<img width="670" alt="image" src="https://user-images.githubusercontent.com/3064318/80528210-31473180-895b-11ea-823f-28dfe4b5efc5.png">

**Comment by dl-maura** [comment]
I've filed the ticket and included your two screenshots, will keep you all posted!

**Comment by dl-maura** [comment]
Here are the 3 things I have: 2 GA pdfs for brbl-dl and the sheet Mike sent me about FindIt
[BRBL-DLFebMar.pdf](https://github.com/yalelibrary/YUL-DC/files/4553185/BRBL-DLFebMar.pdf)
[BRBL-DLMarApril.pdf](https://github.com/yalelibrary/YUL-DC/files/4553186/BRBL-DLMarApril.pdf)
[FindItAnalyticsData.pdf](https://github.com/yalelibrary/YUL-DC/files/4553218/FindItAnalyticsData.pdf)

**Comment by maxkadel** [comment]
When trying to access https://brbl-dl.library.yale.edu/vufind/Record/4314460, can see shotguns, can't see "Similar items".
![image](https://user-images.githubusercontent.com/45948126/80833557-cac14e00-8bbc-11ea-9172-1349ad1ae3ba.png)

**Comment by maxkadel** [comment]
Also can't log in to spinup
![image](https://user-images.githubusercontent.com/45948126/80833658-02c89100-8bbd-11ea-9935-821e39ef0f43.png)

**Comment by fnibbit** [comment]
Netid rk785 ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/575f1090-5364-4764-9bed-34b6943339f1) ![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/eed0b64a-b027-4f8e-9650-0c83bde2e203)

**Comment by RachelDCE** [comment]
Net ID rl864
![Screen Shot 2020-05-01 at 2.57.06 PM.png](https://images.zenhubusercontent.com/5ca3faa0fed84050d0a7bcf8/aad56ab9-6cb5-4dbe-a055-46e0ccff4c6c)

**Comment by dl-maura** [comment]
We may have identified the issue, and I am assembling the list of net ids in use to send on to another department who may be able to fix it!

**Comment by mikeapp** [comment]
@alishaevn  I updated your VPN access, can you try visiting https://brbl-dl.library.yale.edu/vufind/Record/4314460 and let me know whether you can see all of the images on the page?

**Comment by alishaevn** [comment]
@mikeapp I can see the images of the shotgun, but not the images for "similar items" at the bottom of that page.

![Screen Shot 2020-05-06 at 8.01.56 AM.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/6d50333a-4e90-49ea-874a-051e4b66f983)

![Screen Shot 2020-05-06 at 8.02.08 AM.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/dda13ca3-c13b-497d-85e3-bf168d4fd591)

**Comment by mark-dce** [comment]
Remote Desktop Works!

**VPN using laptop browser**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/656474cf-4f3b-49a7-b826-5e3638afbc58)

**VPN using Remote Desktop**
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/c5226e04-0567-4ab9-b6e4-d1e162cb28b7)
