### ISSUE TITLE
Create list of parents in Gap 2 list (Jan 2021)

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#985]
**Story**

Gap load 1 caught us up to the end of December.  Now we want to load objects created in 2021.

**Acceptance**

- [x] Create a list of parents added from January to 2/9/2021
- [x] Give list to YUL for child oids
- [x] check for images and replace any missing
- [x] copy to prod pair tree (we can test in staging)

**Comment by dl-maura** [comment]
Got list from Jay, will have the expanded list today
