### ISSUE TITLE
Ingest Gap 2 works to Staging

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#988]
**Story**

We want to ingest the Gap load 2 items on Staging first.  (We can't do this in lower environments because the production pair tree is no longer available there.)

**Acceptance**
- [x] Start gap load into staging using list from #985
- [ ] Monitor load
- [ ] Report on errors and any discrepancy in number of items loaded

**Comment by dl-maura** [comment]
everything worked but 17300443, which I've sent on to be investigated
