### ISSUE TITLE
SPIKE: Identify why PDF generation is triggering errors on Demo

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#991]
**ISSUE**
We're experiencing an unexpectedly high number of errors generating PDFs on demo.

**ACCEPTANCE**
- [x] Identify at least one possible cause for the errors
- [x] Implement a potential fix

Suspicion is running too many workers at one time.

**Comment by martinlovell** [comment]
Comparing test with demo: 

Tried rerunning some of the failed jobs: demo is having trouble even with 2 page PDFs.
It seems to fail when shelling out to `convert` for PTIFF->JPG conversion.  In other cases this has been a memory issue.

A difference with test PDF worker:
Demo Container Instance:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/9616abdf-0d1d-49d1-bcba-1d370a4a9be3)

Test Container Instance:
![image.png](https://images.zenhubusercontent.com/5e5e9bbd38fda217bdabbde0/d74b1596-025e-485d-baeb-a6a1abf9221a)

EC2 instance running PDF and Normal tasks on test is a m5.xlarge, demo is t2.large.

To investigate more, I'd need shell access to the EC2 instance in Demo to run a PDF manually to see what happens.

**Comment by maxkadel** [comment]
> To investigate more, I'd need shell access to the EC2 instance in Demo to run a PDF manually to see what happens.

@martinlovell  - Good find, it would make sense for this to be a big part of the issue. 

This wiki page has https://github.com/yalelibrary/yul-dc-documentation/wiki/Evaluating-S3-Encryption-Performance-for-IIIF-images documentation of how to ssh into a container on an Ec2 instance, but you'd need to get the private key for the demo instance from someone on the DevOps team.
