### ISSUE TITLE
Default redirect for requests to the BRBL DL

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#995]
There will be a default redirect to handle requests to the BRBL DL that are not matched by specific redirect rules.   The default redirect will send users to a page that will be created on the main Beinecke site to provide guidance about the transition to the new system.

**Acceptance**
- [x] Beinecke provides the URL for the new page on the main site.  DONE: https://beinecke.library.yale.edu/digital-collections/digital-collections-beinecke-library 
- [x] The redirect application redirects any requests that fail to match a specific redirect rule to the specified URL on the Beinecke site.

**Comment by mikeapp** [comment]
Use https://beinecke.library.yale.edu/digital-collections/digital-collections-beinecke-library for the default redirect.

**Comment by kcompsci** [comment]
Trying to populate the table with updates using the ccd server. Got the following:
E, [2021-01-21T17:27:04.439695 #31152] ERROR -- : And exception #<Mysql2::Error: Unknown MySQL server host 'vm-odaiprd-01.its.yale.edu' (2)> occurred when trying to update Beinecke redirects!

**Comment by mikeapp** [comment]
PR https://github.com/yalelibrary/yul-dc-redirects/pull/7
