### ISSUE TITLE
Create  test, uat, prod environments for redirect application

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#996]
Create dev, test, and production environments for the redirect application.

**Acceptance**
Test
- [x] Rails app deployed
- [x] Postgresql DB created

UAT
- [x] Rails app deployed
- [x] Postgresql DB created

Production
- [x] Rails app deployed
- [x] Postgresql DB created

**Comment by mikeapp** [comment]
See INC1923222

**Comment by ra359** [comment]
INC1925725 New F5 VIP DNS entries for Library collections

**Comment by ra359** [comment]
F5 redirects are in progress - see INC1927638

**Comment by bobrice** [comment]
This is complete
